### ISSUE TITLE
ray.init() outputs too much to stdout

### ISSUE THREAD

**Issue by rshin** [ray-project/ray#1135] opened 2017-10-17 20:14 UTC
If I run
```
import ray
ray.init()
```
then the following is printed to stdout:
```
33111:M 17 Oct 13:10:46.536 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
33111:M 17 Oct 13:10:46.536 # Server started, Redis version 3.9.102
33111:M 17 Oct 13:10:46.536 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
33111:M 17 Oct 13:10:46.536 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
33115:M 17 Oct 13:10:46.643 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
33115:M 17 Oct 13:10:46.643 # Server started, Redis version 3.9.102
33115:M 17 Oct 13:10:46.644 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
33115:M 17 Oct 13:10:46.644 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
33111:signal-handler (1508271047) Received SIGTERM scheduling shutdown...
33111:M 17 Oct 13:10:47.840 # User requested shutdown...
33111:M 17 Oct 13:10:47.841 # Redis is now ready to exit, bye bye...
33115:signal-handler (1508271047) Received SIGTERM scheduling shutdown...
33115:M 17 Oct 13:10:47.847 # User requested shutdown...
33115:M 17 Oct 13:10:47.847 # Redis is now ready to exit, bye bye...
Waiting for redis server at 127.0.0.1:12291 to respond...
Waiting for redis server at 127.0.0.1:16689 to respond...
Starting local scheduler with 56 CPUs, 0 GPUs

======================================================================
View the web UI at http://localhost:8889/notebooks/ray_ui35279.ipynb?token=a75d7565c169ac4a55b17825a5e203c1c605714c1deba239
======================================================================
```

With
```
import ray
ray.init(redirect_output=True)
```
the lines starting with `33111` and `33115` are gone, but the others remain.

It seems more appropriate to have these sent to stderr, if at all.

**Comment by robertnishihara** [comment] 2017-10-18 22:23
You're right, there's probably no need for the all the warnings from Redis, we could redirect those by default.

We do want to print the web UI address so people can copy and paste it.

**Comment by robertnishihara** [comment] 2017-10-20 00:20
More or less resolved by #1142 (though there are still some things printed).

**Comment by rshin** [comment] 2017-10-21 01:36
I think it would still be useful to print the web UI address to stderr instead of stdout, or expose whether to start the web UI in `ray.init` (or both).

It's a convention for processes to write their output to stdout, and having libraries also write to stdout interferes with this. But this also applies to all other messages, like "Waiting for redis server ..." and "Starting local scheduler ...".

**Comment by robertnishihara** [comment] 2018-04-12 07:10
Duplicate of #1884 :)

**Closed by robertnishihara** 2018-04-12 07:10 UTC
