### ISSUE TITLE
What is the role of get_policy()? Why the result of trainer.get_policy().compute_single_action is different from trainer.compute_single_action ?

### ISSUE THREAD

**Issue by Wang-XR** [ray-project/ray#27978] opened 2022-08-18 04:02 UTC
### What happened + What you expected to happen

trainer = ppo.PPOTrainer(config=config, env=env)
(a).  trainer.get_policy().compute_single_action(obs,explore=False)
(b). trainer.compute_single_action(obs,explore=False)
I don't know why the results of (a) and (b) are different. What is the role of get_policy()?
I would appreciate it if you could help me.

### Versions / Dependencies

python 3.8

### Reproduction script

trainer = ppo.PPOTrainer(config=config, env=env)
trainer.get_policy().compute_single_action(obs,explore=False)
trainer.compute_single_action(obs,explore=False)

**Comment by jaredvann** [comment] 2022-11-17 17:00
An example of this:

```py
import gym
import numpy as np
import ray
from ray import tune
from ray.rllib.algorithms.registry import get_algorithm_class

assert ray.__version__ == "2.1.0"


class MockEnv(gym.Env):
    def __init__(self, *args, **kwargs):
        self.current_step = 0

        self.observation_space = gym.spaces.Dict({
            "a": gym.spaces.Box(low=0.0, high=1.0, shape=(1,)),
            "b": gym.spaces.Box(low=0.0, high=1.0, shape=(1,)),
        })

        self.action_space = gym.spaces.Discrete(2)

    def step(self, action):
        self.current_step += 1

        return ({"a": np.array([0.0]), "b": np.array([0.0])}, 0.0, self.current_step <= 100, {})

    def reset(self):
        return {"a": np.array([0.0]), "b": np.array([0.0])}


ray.init()

tune.run(
    "PPO",
    config=dict(env=MockEnv, env_config={}, num_workers=1),
    name="compute_actions_test",
    checkpoint_freq=1,
    stop={"training_iteration": 1}
)

checkpoint = "/home/ubuntu/ray_results/compute_actions_test/PPO_MockEnv_69bcb_00000_0_2022-11-17_16-46-42/checkpoint_000001/"

algo = get_algorithm_class("PPO")(env=MockEnv, config={})
algo.restore(checkpoint)

obs = {"a": np.array([0.0]), "b": np.array([0.0])}

print("\nalgo.compute_single_action()\n")
print(algo.compute_single_action(obs, policy="default_policy"))

print("\nalgo.get_policy().compute_single_action()\n")
print(algo.get_policy("default_policy").compute_single_action(obs))
```

gives:

```
<<stdout omitted>>

algo.compute_single_action()

0

algo.get_policy().compute_single_action()

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tree/__init__.py", line 280, in assert_same_structure
    _tree.assert_same_structure(a, b, check_types)
ValueError: The two structures don't have the same nested structure.

First structure: type=Tensor str=Tensor("default_policy/obs:0", shape=(?, 2), dtype=float32)

Second structure: type=dict str={'a': array([[0.]]), 'b': array([[0.]])}

More specifically: Substructure "type=dict str={'a': array([[0.]]), 'b': array([[0.]])}" is a sequence, while substructure "type=Tensor str=Tensor("default_policy/obs:0", shape=(?, 2), dtype=float32)" is not

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ray_bug.py", line 59, in <module>
    print(algo.get_policy("default_policy").compute_single_action(obs))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ray/rllib/policy/policy.py", line 459, in compute_single_action
    out = self.compute_actions_from_input_dict(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ray/rllib/policy/tf_policy.py", line 305, in compute_actions_from_input_dict
    to_fetch = self._build_compute_actions(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ray/rllib/policy/tf_policy.py", line 1021, in _build_compute_actions
    tree.map_structure(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tree/__init__.py", line 428, in map_structure
    assert_same_structure(structures[0], other, check_types=check_types)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tree/__init__.py", line 284, in assert_same_structure
    raise type(e)("%s\n"
ValueError: The two structures don't have the same nested structure.

First structure: type=Tensor str=Tensor("default_policy/obs:0", shape=(?, 2), dtype=float32)

Second structure: type=dict str={'a': array([[0.]]), 'b': array([[0.]])}

More specifically: Substructure "type=dict str={'a': array([[0.]]), 'b': array([[0.]])}" is a sequence, while substructure "type=Tensor str=Tensor("default_policy/obs:0", shape=(?, 2), dtype=float32)" is not
Entire first structure:
.
Entire second structure:
{'a': ., 'b': .}
```

Also confusingly the doc string descriptions for `Algorithm.compute_actions` and `Algorithm.compute_single_action` in the docs are the same (https://docs.ray.io/en/latest/rllib/package_ref/algorithm.html)

**Comment by ArturNiederfahrenhorst** [comment] 2022-12-15 19:55
Sorry for the confusion.
The Policy does not preprocess. Hence the difference.
Note that in @jaredvann 's case, the preprocessor flattens the inputs.
We are introducing a new API for this that will make it more obvious.
Closing because this is not a bug but design issue and changes are already underway 👍

**Closed by ArturNiederfahrenhorst** 2022-12-15 19:55 UTC
Labels: bug, triage
