### ISSUE TITLE
[Core] Importing ray by default will mess up logging config

### ISSUE THREAD

**Issue by shayanhoshyari** [ray-project/ray#37920] opened 2023-07-29 01:07 UTC
### What happened + What you expected to happen

Starting from ray 2.6.0 this snippet if you use the code snippet in `Reproduction script` nothing will be printed. This is because of this line in ray, that will disable all the loggers https://github.com/ray-project/ray/blame/releases/2.6.0/python/ray/__init__.py#L7-L11. Modules should not modify global loggers, *especially loggers that don't belong to them*.

Commenting out the `import ray` line will give:
```
python scratch/test.py 
INFO:my_logger:Hello
```
without `import ray`, nothing will be printed.

Took 2 hours of my time today to find out why our logs suddenly have disappeared in some scenarious.

### Versions / Dependencies

> 2.6.0

### Reproduction script

```
logger = logging.getLogger("my_logger")

import ray

logging.basicConfig(level="INFO")
logger.info("Hello")
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by richardliaw** [comment] 2023-07-29 01:14
Hey, thanks for the diagnosis and the bug report! 

Let me escalate this internally, as we need to get into a better discipline here.

**Comment by jjyao** [comment] 2023-07-31 20:12
This should be a duplicate of https://github.com/ray-project/ray/issues/37941. This has been fixed in master and will be released in 2.6.2 soon.

**Closed by jjyao** 2023-07-31 20:12 UTC
Labels: bug, triage, core

**Comment by klieret** [comment] 2023-07-31 21:05
Thanks @richardliaw @jjyao . Accidentally had an `is:open` filter in my issue search, I realized. Sorry for the duplicate!

**Comment by xieus** [comment] 2023-08-04 02:36
@shayanhoshyari Ray 2.6.2 is released today with an proper fix. 
https://github.com/ray-project/ray/releases/tag/ray-2.6.2

Please check it out and let us know how it goes. Thank you for your patience and understanding.
