### ISSUE TITLE
[Feature] [core] Selecting network interface

### ISSUE THREAD

**Issue by tupui** [ray-project/ray#22732] opened 2022-03-01 17:14 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Add a parameter to `ray.init(...)` to be able to select the network interface. Or be able to use the `--address` parameter for that.

### Use case

If you have a HPC cluster, you most likely have multiple network interfaces. Right now Ray defaults to `eth0`. This can be an issue depending on the network topology/firewall rules.

I tried to manually set `--address` but it was not working with `The primary external redis server 'x.x.x.x' is not reachable`.  I could go around by manually overwriting the key `GcsServerAddress`. Only then I could register a worker.

### Related issues

Linked to #22326, #8430 and #5371

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by richardliaw** [comment] 2022-03-04 10:07
cc @ericl @scv119 @rkooo567 

It'd be great to support this, though I don't know how complicated the implementation would be.

It would open up a big set of use cases (SLURM is one of the top-searched entries on our discourse).

**Comment by tupui** [comment] 2022-03-04 10:11
I was told that with the move away from Redis, this behaviour might have been fixed (ability to set `--address`). I still need to check.

**Comment by richardliaw** [comment] 2022-03-04 22:47
OK, that'd be great. Keep us updated here.

**Comment by scv119** [comment] 2022-04-13 16:41
@iycheng do you have bandwidth take it in next 1-2 weeks?

**Comment by iycheng** [comment] 2022-06-07 07:27
@tupui  I have a question for your case here. With what you proposed here, we can bind all services on the head node to this. But how about the worker nodes? Do you need the worker nodes to bind to some specific eth as well?

**Comment by tupui** [comment] 2022-06-07 09:46
@iycheng I think yes since some network interface can be isolated from each other. Selecting an interface should apply to all services (head+workers). I don't know if that makes really sense to allow a mixed interface configuration.

**Comment by iycheng** [comment] 2022-06-07 18:58
@tupui  Got it. I feel just reusing `--address` is not enough here. The main issue is about the worker's binding. For worker `--address` will always be the header's GCS address so that it can connect to the cluster. Also raylet is started  1) by autoscaler; 2) manually. So if manually specify something like `--local-ip-address` might work, but if it's started by autoscaler, it's not working.

If we'd like to support autoscaler, we have to introduce something higher level which can select the IP address to bind automatically. Some ideas come to my mind and please let me know if it makes sense or not (I'm not very familiar with this fields):

1. We can just choose the IP address that is in the same subnet as the GCS one. For example, in the head node: `ray start --head --address 172.0.0.1:6379` which will start the GCS binding with `172.0.0.1`, and then, for worker nodes, it'll call, `ray start --address 172.0.0.1:6379` and ray will find the IP address in the local node which is in the same subnet as this one. And use this.
1. We can have a flag like `--eth`, if the eth name is the same across the cluster, we can get the right IP address and bind it there. For example, in worker nodes, `ray start --address gcs:6379 --eth=eth1`, for all worker nodes it'll bind to the IP address in eth1.

**Comment by vakker** [comment] 2022-06-08 10:23
@iycheng I'm using the 1st option with my Slurm scripts, a script launches the head node on the selected interface and then just launches the worker nodes pointed to that address. E.g.:
```sh
interface=ib0  # for the InfiniBand interface
ip=$(ip -f inet addr show $interface | sed -En -e 's/.*inet ([0-9.]+).*/\1/p')

# head
ray start --head --node-ip-address=$ip --port=6379 --redis-password=$redis_password

# worker (on another machine)
ray start --address $ip:6379 --redis-password=$redis_password
```

The 2nd option might be more cumbersome, e.g. I see interfaces like eno1, eth0, em1, bond0 across the cluster, and it's non-trivial which one should be used.

**Comment by tupui** [comment] 2022-06-08 10:43
I would vote for the subnet option. From a user perspective it would be transparent (need to improve the error messaging to point out to that if they is a connection issue though).

**Comment by scv119** [comment] 2022-06-09 04:33
> Sounds good, I think we'll go with option 1). I also prefer this one since it doesn't introduce new APIs and the existing one should continue to work. cc @scv119

sounds good to me! A minor question, should the parameter to be `--bind-address` for clarity?

**Comment by iycheng** [comment] 2022-06-13 20:55
@scv119 I'm ok with this, @pcmoritz do you have some suggestions?

**Comment by iycheng** [comment] 2022-06-13 22:05
> sounds good to me! A minor question, should the parameter to be --bind-address for clarity?

I'd suggest `--bind-ip` with an ip address which seems better.

**Comment by chris-aeviator** [comment] 2023-08-15 10:20
this is also an issue with multip interface machines and ray serve (which doesnt take the --node-ip-address param). I basically cannot use these nodes to start ray serve jobs

**Comment by mattip** [comment] 2023-08-28 15:37
You did not show how you are using the commands. In the logs you can see:
`To add another node to this Ray cluster, run ray start --address='10.11.241.83:6379`

and
```
To connect to this Ray cluster:
import ray
ray.init(_node_ip_address='10.11.241.83')
```

and
```
To submit a Ray job using the Ray Jobs CLI:
RAY_ADDRESS='http://127.0.0.1:8265' ray job submit --working-dir . -- python my_script.py
```

The error states `This node has an IP address of 10.13.23.83, but we cannot find a local Raylet with the same address. This can happen when you connect to the Ray cluster with a different IP address or when connecting to a container.`

Which command did you use?

**Comment by mattip** [comment] 2023-08-28 15:41
@chris-aeviator `ray-serve` uses the [autoscalar](https://docs.ray.io/en/latest/serve/scaling-and-resource-allocation.html#autoscaling) to allocate resources, which, as noted 
> The Ray Serve Autoscaler is an application-level autoscaler that sits on top of the [Ray Autoscaler](https://docs.ray.io/en/latest/cluster/getting-started.html#cluster-index). Concretely, this means that the Ray Serve autoscaler asks Ray to start a number of replica actors based on the request demand. If the Ray Autoscaler determines there aren’t enough available CPUs to place these actors, it responds by requesting more Ray nodes. The underlying cloud provider will then respond by adding more nodes. Similarly, when Ray Serve scales down and terminates some replica actors, it will try to do so in a way that results in the most nodes having no Ray actors or tasks running on them, at which point the Ray autoscaler will remove those nodes.

**Comment by gpucce** [comment] 2023-08-28 15:44
This is the sbatch script, while the vllm repo I think only calls `ray.init`

```
#!/bin/bash
# shellcheck disable=SC2206
# THIS FILE IS GENERATED BY AUTOMATION SCRIPT! PLEASE REFER TO ORIGINAL SCRIPT!
# THIS FILE IS MODIFIED AUTOMATICALLY FROM TEMPLATE AND SHOULD BE RUNNABLE!
#SBATCH --partition=develbooster
#SBATCH --job-name=test_0828-1638
#SBATCH --output=test_0828-1638-%j.log

### This script works for any number of nodes, Ray will find and manage all resources
#SBATCH --nodes=2
#SBATCH --exclusive
### Give all resources to a single Ray task, ray can manage the resources internally
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-task=4
#SBATCH --cpus-per-task=24
#SBATCH --account=transfernetx

# Load modules or your own conda environment here
# module load pytorch/v1.4.0-gpu
# conda activate ${CONDA_ENV}


# ===== DO NOT CHANGE THINGS HERE UNLESS YOU KNOW WHAT YOU ARE DOING =====
# This script is a modification to the implementation suggest by gregSchwartz18 here:
# https://github.com/ray-project/ray/issues/826#issuecomment-522116599
redis_password=$(uuidgen)
export redis_password

eval "$(/p/home/jusers/puccetti1/juwels/puccetti1/miniconda3/bin/conda shell.bash hook)" # init conda
conda activate llm

export CUDA_VISIBLE_DEVICES=0,1,2,3

nodes=$(scontrol show hostnames "$SLURM_JOB_NODELIST") # Getting the node names
nodes_array=($nodes)

node_1=${nodes_array[0]}
ip=$(srun --nodes=1 --ntasks=1 -w "$node_1" hostname --ip-address)
# ip="${node_1}i"

# if we detect a space character in the head node IP, we'll
# convert it to an ipv4 address. This step is optional.
# if [[ "$ip" == *" "* ]]; then
#   IFS=' ' read -ra ADDR <<< "$ip"
#   if [[ ${#ADDR[0]} -gt 16 ]]; then
#     ip=${ADDR[1]}
#   else
#     ip=${ADDR[0]}
#   fi
#   echo "IPV6 address detected. We split the IPV4 address as $ip"
# fi

port=6379
ip_head=$ip:$port
export ip_head
echo "IP Head: $ip_head"

echo "STARTING HEAD at $node_1"
srun --nodes=1 --ntasks=1 -w "$node_1" \
  ray start --head --node-ip-address="$ip" --port=$port --redis-password="$redis_password" --block &
sleep 10

worker_num=$(($SLURM_JOB_NUM_NODES - 1)) #number of nodes other than the head node
for ((i = 1; i <= worker_num; i++)); do
  node_i=${nodes_array[$i]}
  echo "STARTING WORKER $i at $node_i"
  echo "IP Head: $ip_head"
  this_node_ip=$(srun --nodes=1 --ntasks=1 -w "$node_i" hostname --ip-address)
  echo "Node: $node_i IP Local: $this_node_ip"
  srun --nodes=1 --ntasks=1 -w "$node_i" \
    ray start \
    --address "$ip_head" \
    --node-ip-address ${this_node_ip} \
    --num-cpus 24 \
    --num-gpus 4 \
    --redis-password="$redis_password" \
    --block &

  sleep 5
done

# ===== Call your code below =====
export i=wikihow_chatGPT

echo "STARTING python command"
python -u /p/home/jusers/puccetti1/juwels/puccetti1/llm/llm-foundry/scripts/inference/vllm_generate.py \
--name_or_path /p/fastdata/mmlaion/puccetti1/llama-2-models-hf/llama-2-70b-chat/ \
--temperature 1.0 \
--top_p 0.95 \
--top_k 50 \
--max_new_tokens 256 \
--prompts "file::/p/home/jusers/puccetti1/juwels/puccetti1/llm/M4/data/$i.jsonl" \
--max_prompts 3000 \
--output_path "/p/home/jusers/puccetti1/juwels/puccetti1/llm/llm-foundry/outputs/CHANGE-it/llama-2-70b-chat/repubblica/$i/" \
--num_nodes 2
```

**Comment by mattip** [comment] 2023-08-28 15:49
Maybe you can add `set -x` at the top of the file and capture the output so that you can see what the actual bash calls are. Then study the output to figure out which address is wrong.

**Comment by a-zhenya** [comment] 2023-09-28 10:51
> This node has an IP address of 10.13.23.83, but we cannot find a local Raylet with the same address.

I am also experience the same error message. The error comes from raylet binary, not a py file. Can you direct me on a module that should be updated to get better flexibility?

**Comment by rkooo567** [comment] 2023-10-03 08:49
@a-zhenya this issue is probably fixed in ray 2.7. Can you try that out? The reason why when you create a new driver, it doesn't pick up the IP address that was given by ray start. It is fixed in 2.7

**Comment by a-zhenya** [comment] 2023-10-10 18:39
> @a-zhenya this issue is probably fixed in ray 2.7. Can you try that out? The reason why when you create a new driver, it doesn't pick up the IP address that was given by ray start. It is fixed in 2.7

Hi I am trying to localize the issue and develop a minimum reproducible case. I use a machine with 2 network cards.
I am starting the ray head as "ray start --head --node-ip-address=x.x.x.x" where x is desired IP address to bind the ray jobs endpoint. Correct?

**Comment by rkooo567** [comment] 2023-10-10 22:23
yes that's right. It is not just for job endopint. Every network communication will happen through that network interface that is bound to the node ip

**Comment by a-zhenya** [comment] 2023-10-19 11:15
This did not work as expected.

However with 2.7.1, I've solved the initial problem. I removed this key (--node-ip-address=x.x.x.x) out of head start command line and it works now. The head has  binded to 0.0.0.0 so it is reachable with all interfaces.

**Comment by anyscalesam** [comment] 2023-10-25 16:37
@mattip latest on this; per @peytondmurray there were some new configs added to the CLI. If so, is that sufficient to close this ticket out?

**Comment by mattip** [comment] 2023-10-25 16:58
@chris-aeviator @gpucce does 2.7.1 work for you? If so I think we can close this.

**Comment by YarShev** [comment] 2023-11-01 08:23
@mattip, closing this issue means that Ray is able to run over infiniband and other network interfaces?

**Comment by gpucce** [comment] 2023-12-26 10:27
> @chris-aeviator @gpucce does 2.7.1 work for you? If so I think we can close this.

hi, sorry for the late reply, it looks like I can use it now

**Comment by mattip** [comment] 2023-12-26 11:13
Thanks, closing.

**Comment by rkooo567** [comment] 2024-01-16 05:10
Is that output from lsof?

**Comment by mattip** [comment] 2024-02-15 06:38
@thestick6123: please open a new issue with all the required information to reproduce (operating system, version(s) of software used, where you got ray and how you installed it ...). Re-closing since you have not responded to the request for more information.

**Closed by mattip** 2024-02-15 06:38 UTC
Labels: enhancement, P1, size:small, QS, core, Ray 2.4, core-api
