### ISSUE TITLE
[Ray 2.3 release][core] stress_test_state_api_scale fails on AssertionError `Expect 10000 non finished tasks`

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#32005] opened 2023-01-27 20:29 UTC
* https://buildkite.com/ray-project/release-tests-branch/builds/1313#0185f02a-496d-4d9f-b21a-54ed997c64f3
* https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_dynkgewjyiv9ihluktpr72ig9u?command-history-section=command_history

```
AssertionError: Calling list_tasks({'filters': [('name', '=', 'pi4_sample'), ('state', '!=', 'FINISHED')], 'limit': 1000000, 'timeout': 600, 'raise_on_missing_output': False}) failed with AssertionError('Calling State API failed. len(res)=(9631): Expect 10000 non finished tasks.').
```

**Comment by cadedaniel** [comment] 2023-01-27 20:30
@rickyyx or @rkooo567 can you confirm that this should be release blocking, or if we can ignore?

**Comment by rickyyx** [comment] 2023-01-27 21:30
hmm, seems there is regression. likely not release blocking tho.

**Comment by rkooo567** [comment] 2023-01-29 15:20
It should be a release blocker if it is a regression?

**Comment by rkooo567** [comment] 2023-01-29 15:20
What's the root cause?

**Comment by rickyyx** [comment] 2023-01-30 18:10
Taking a look today.

**Comment by rickyyx** [comment] 2023-01-30 21:18
The recent run finishes - wondering if it's due to this PR https://github.com/ray-project/ray/pull/32057

It could be the timeout as well. 

Running the release tests here: https://buildkite.com/ray-project/release-tests-pr/builds/26884

**Comment by cadedaniel** [comment] 2023-01-30 22:57
marking as release blocker until we know it's not

**Comment by zhe-thoughts** [comment] 2023-01-30 23:32
Assigning to @rickyyx while waiting for the rerun

**Comment by rickyyx** [comment] 2023-01-31 19:43
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/11676094/215865637-2430f05c-755b-4076-8f32-3e0ca1c5f47c.png">


Closing since this has been passing. (I suspect one of the nodes was down in the failed run causing issues)

**Closed by rickyyx** 2023-01-31 19:43 UTC
Labels: release-blocker, P1, core
