### ISSUE TITLE
[AIR][RLlib] Any solutions to train Large Language Models with RLHF on Ray?

### ISSUE THREAD

**Issue by weberxie** [ray-project/ray#33436] opened 2023-03-19 05:44 UTC
### Description

Training LLM with RLHF, the number of parameters of LLM may be up to 175B.

**Comment by Yard1** [comment] 2023-03-22 18:12
cc @richardliaw

**Comment by richardliaw** [comment] 2023-03-22 18:48
I believe this is a duplicate of #33021 . Closing this here, let's continue the conversation there!

**Closed by richardliaw** 2023-03-22 18:48 UTC
Labels: enhancement, triage

**Comment by zhanghaoie** [comment] 2023-03-30 03:46
Any updates?
