### ISSUE TITLE
Ray Core: Not respecting --node-ip-address

### ISSUE THREAD

**Issue by steventrouble** [ray-project/ray#26293] opened 2022-07-05 05:42 UTC
### What happened + What you expected to happen

**Expected:**

Run `ray start --head --node-ip-address=127.0.0.1` should start a service using my localhost IP.

**What happened:**

It seems to have ignored the node-ip-address flag.

```
$ ray start --head --node-ip-address=127.0.0.1
Local node IP: 172.30.93.204
2022-07-04 22:31:27,576 INFO services.py:1164 -- View the Ray dashboard at http://localhost:8266

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='172.30.93.204:6379' --redis-password='5241590000000000'

  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='5241590000000000')

  If connection fails, check your firewall settings and network configuration.

  To terminate the Ray runtime, run
    ray stop
```

I cannot connect using the IP it tries to use, because my firewall blocks it.

### Versions / Dependencies

```
$ ray --version
ray, version 1.13.0
```

### Reproduction script

`ray start --head --node-ip-address=127.0.0.1`

on my laptop, running Linux on Windows (WSL 2).

### Issue Severity

High: It blocks me from completing my task.

**Comment by steventrouble** [comment] 2022-07-05 08:12
Alright, it looks like this is intentional:

https://github.com/ray-project/ray/blob/43aa2299e6623c8f8c7c4a1b80133459d0aa68b0/python/ray/_private/services.py#L487

If we were able to use "127.0.0.1", it would help work around firewall issues. There's already workarounds in the code for mac and windows to use "127.0.0.1", so it's clear that some users need to use loopback due to firewalls.

**Current workaround:**

For WSL specifically, you need to give a blanket firewall exception to WSL. On your Windows host, run:

`New-NetFirewallRule -DisplayName "WSL" -Direction Outbound -InterfaceAlias "vEthernet (WSL)" -Action Allow`

**Comment by tupui** [comment] 2022-07-05 10:04
Hi @steventrouble, thank you for reporting. You might also work this around by having a rule in your host file pointing to a random IP that you would redirect to localhost.

I will close this now since this is the intended behaviour here. FYI, there are work in progress around networking interfaces #22732. It might help.

**Closed by tupui** 2022-07-05 10:04 UTC
Labels: bug, triage
