### ISSUE TITLE
[tune/autoscaler/docker] GPU support in docker

### ISSUE THREAD

**Issue by vtomenko** [ray-project/ray#8975] opened 2020-06-16 20:56 UTC
### GPU support in docker
Reading docs on [Automatic Cluster Setup](https://docs.ray.io/en/master/autoscaling.html), section "Docker":

> This currently does not have GPU support

However, [aws/example-gpu-docker.yaml](https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/aws/example-gpu-docker.yaml) coupled with [merged PR](https://github.com/ray-project/ray/pull/3921) suggests GPU is supported.

Could you please clarify and if GPU is indeed supported in docker - would docker be good choice from stability perspective?

**Comment by richardliaw** [comment] 2020-06-16 21:02
Hey @vtomenko - you might run into some bugs with the current state of the code, but @ijrsvt is hard at work on improving this right now. 

@ijrsvt feel free to chime in

**Comment by vtomenko** [comment] 2020-06-17 05:36
Hey @richardliaw - thanks for your reply, I'll give it a try and let you know guys know what happened.

It is also great to hear you are working on this - I believe stable autoscaler + docker with GPU support combination would be really beneficial for many ML scenarios because it cleanly separates concerns:
-  high-level cluster description including instances details handled by cluster YAML
-  specific ML training task fully contained (including dependencies) and described using docker

In this way ML engineer could just change docker image reference in cluster YAML leaving remaining parts as is (as opposed to updating setup_commands for each different ML task). Then it would be really easy to execute different training tasks on the same cluster, provided ray handles correctly the sequence of (a) updating docker image reference in cluster YAML and (b) `ray up`

**Comment by ijrsvt** [comment] 2020-06-17 06:41
@vtomenko Please do let us know what the result is for running it with GPUs! If you have any further questions or problems please let me know!

**Comment by richardliaw** [comment] 2020-06-17 07:44
@vtomenko absolutely agree! Will keep you updated from our side too.

cc @anabranch @pcmoritz

**Comment by vtomenko** [comment] 2020-06-18 06:32
I'm using ray version 0.8.5 and trying to test basic docker setup.

From [autoscaler doc](https://docs.ray.io/en/master/autoscaling.html):

> Docker: Specify docker image. This executes all commands on all nodes in the docker container, and opens all the necessary ports to support the Ray cluster. **It will also automatically install Docker if Docker is not installed.**

It does not seem to be the case, the error when creating the cluster with say busybox docker image:
`Command 'docker' not found, but can be installed with:`

Installing docker in `initialization_commands` section also does not help for reasons described in #7519 

Can you please point me to any currently working way to configure ray with docker?

**Comment by ijrsvt** [comment] 2020-06-18 16:25
Hmm, let me try working on a solution to this--if you rerun after the first install, does it work? 
Also what are you running on: a local cluster or public cloud?

**Comment by vtomenko** [comment] 2020-06-18 17:42
I use AWS, attaching [configuration I tried](https://github.com/ray-project/ray/files/4800253/sample.yaml.zip)

Rerun does not help:

> 2020-06-18 08:01:00,874 INFO updater.py:264 -- NodeUpdater: i-0374e72fcc8b8ea2a: Running docker inspect -f '{{.State.Running}}' busybox || docker run --rm --name busybox -d -it -p 6379:6379 -p 8076:8076 -p 4321:4321  -e LC_ALL=C.UTF-8 -e LANG=C.UTF-8  --net=host busybox:latest bash on 54.69.9.155...
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
Template parsing error: template: :1:8: executing "" at <.State.Running>: map has no entry for key "State"
WARNING: Published ports are discarded when using host network mode
e2735eef81dcd0dd304fd131ab7c092c68556b8414e908449bd925fb08810bd7
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown.
2020-06-18 08:01:01,527 INFO log_timer.py:17 -- NodeUpdater: i-0374e72fcc8b8ea2a: Setup commands completed [LogTimer=653ms]
2020-06-18 08:01:01,527 INFO log_timer.py:17 -- NodeUpdater: i-0374e72fcc8b8ea2a: Applied config 9784c6630decbe7b8ad6cb2a34f12c3c48314063 [LogTimer=2745ms]
2020-06-18 08:01:01,527 ERROR updater.py:359 -- NodeUpdater: i-0374e72fcc8b8ea2a: Error updating (Exit Status 127) ssh -i /home/ubuntu/.ssh/ray-autoscaler_1_us-west-2.pem -o ConnectTimeout=120s -o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_1d41c853af/e55cd6ce94/%C -o ControlPersist=10s -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 ubuntu@54.69.9.155 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && docker inspect -f '"'"'{{.State.Running}}'"'"' busybox || docker run --rm --name busybox -d -it -p 6379:6379 -p 8076:8076 -p 4321:4321  -e LC_ALL=C.UTF-8 -e LANG=C.UTF-8  --net=host busybox:latest bash'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/projects/ai-ml-model-search/env/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 362, in run
    raise e
  File "/home/ubuntu/projects/ai-ml-model-search/env/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 352, in run
    self.do_update()
  File "/home/ubuntu/projects/ai-ml-model-search/env/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 440, in do_update
    self.cmd_runner.run(cmd)
  File "/home/ubuntu/projects/ai-ml-model-search/env/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 274, in run
    self.process_runner.check_call(final_cmd)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ssh', '-i', '/home/ubuntu/.ssh/ray-autoscaler_1_us-west-2.pem', '-o', 'ConnectTimeout=120s', '-o', 'StrictHostKeyChecking=no', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/tmp/ray_ssh_1d41c853af/e55cd6ce94/%C', '-o', 'ControlPersist=10s', '-o', 'IdentitiesOnly=yes', '-o', 'ExitOnForwardFailure=yes', '-o', 'ServerAliveInterval=5', '-o', 'ServerAliveCountMax=3', 'ubuntu@54.69.9.155', 'bash', '--login', '-c', '-i', '\'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && docker inspect -f \'"\'"\'{{.State.Running}}\'"\'"\' busybox || docker run --rm --name busybox -d -it -p 6379:6379 -p 8076:8076 -p 4321:4321  -e LC_ALL=C.UTF-8 -e LANG=C.UTF-8  --net=host busybox:latest bash\'']' returned non-zero exit status 127.

**Comment by ijrsvt** [comment] 2020-06-18 18:27
I'll try using that AMI! Thanks for sharing this!

**Comment by ijrsvt** [comment] 2020-06-18 21:00
The issue is that we reuse SSH sessions. I'm working on a PR now, but in the meantime there is a subpart workaround:
1) Run ray up, with the `initialization` commands you have above
2) Remove the `initialization` commands
3) Rerun ray up in about 15 seconds or so.

**Comment by vtomenko** [comment] 2020-06-18 22:49
Thanks @ijrsvt , I tried the workaround and it fails. The error seems to be similar to the one reported previously for rerun. Does the workaround work for you?

> 2020-06-18 22:45:57,181 INFO updater.py:264 -- NodeUpdater: i-0230e74237fc85cc4: Running docker inspect -f '{{.State.Running}}' busybox || docker run --rm --name busybox -d -it -p 6379:6379 -p 8076:8076 -p 4321:4321  -e LC_ALL=C.UTF-8 -e LANG=C.UTF-8  --net=host busybox:latest bash on 54.187.139.187...
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
Template parsing error: template: :1:8: executing "" at <.State.Running>: map has no entry for key "State"
WARNING: Published ports are discarded when using host network mode
99e67b7ac1327a73ee5f81be226f96a3712d785d5475080c511c60bddbe40609
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown.
2020-06-18 22:45:57,860 INFO log_timer.py:17 -- NodeUpdater: i-0230e74237fc85cc4: Setup commands completed [LogTimer=679ms]
2020-06-18 22:45:57,861 INFO log_timer.py:17 -- NodeUpdater: i-0230e74237fc85cc4: Applied config 0318fe55a69a325f60716771d1a6f9f9a36457ec [LogTimer=3565ms]
2020-06-18 22:45:57,861 ERROR updater.py:359 -- NodeUpdater: i-0230e74237fc85cc4: Error updating (Exit Status 127) ssh -i /home/ubuntu/.ssh/ray-autoscaler.pem -o ConnectTimeout=120s -o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_1d41c853af/e55cd6ce94/%C -o ControlPersist=10s -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 ubuntu@54.187.139.187 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && docker inspect -f '"'"'{{.State.Running}}'"'"' busybox || docker run --rm --name busybox -d -it -p 6379:6379 -p 8076:8076 -p 4321:4321  -e LC_ALL=C.UTF-8 -e LANG=C.UTF-8  --net=host busybox:latest bash'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/projects/ai-ml-model-search/env/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 362, in run
    raise e
  File "/home/ubuntu/projects/ai-ml-model-search/env/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 352, in run
    self.do_update()
  File "/home/ubuntu/projects/ai-ml-model-search/env/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 440, in do_update
    self.cmd_runner.run(cmd)
  File "/home/ubuntu/projects/ai-ml-model-search/env/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 274, in run
    self.process_runner.check_call(final_cmd)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ssh', '-i', '/home/ubuntu/.ssh/ray-autoscaler.pem', '-o', 'ConnectTimeout=120s', '-o', 'StrictHostKeyChecking=no', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/tmp/ray_ssh_1d41c853af/e55cd6ce94/%C', '-o', 'ControlPersist=10s', '-o', 'IdentitiesOnly=yes', '-o', 'ExitOnForwardFailure=yes', '-o', 'ServerAliveInterval=5', '-o', 'ServerAliveCountMax=3', 'ubuntu@54.187.139.187', 'bash', '--login', '-c', '-i', '\'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && docker inspect -f \'"\'"\'{{.State.Running}}\'"\'"\' busybox || docker run --rm --name busybox -d -it -p 6379:6379 -p 8076:8076 -p 4321:4321  -e LC_ALL=C.UTF-8 -e LANG=C.UTF-8  --net=host busybox:latest bash\'']' returned non-zero exit status 127.

**Comment by ijrsvt** [comment] 2020-06-18 23:19
I think this error is because the docker image (busybox) in your YAML does
not have bash installed.

**Comment by vtomenko** [comment] 2020-06-19 01:26
Makes sense, thank you @ijrsvt ! I will update the YAML and use the docker image I compiled to train ML models and see what happens.

**Comment by ijrsvt** [comment] 2020-06-19 02:11
Awesome--I have a PR out to automatically install docker if it is not preinstalled; this won't be a problem in the future!

**Comment by vtomenko** [comment] 2020-06-25 22:42
Hey @ijrsvt , thank you for the PR - any chance it is going to be merged into master soon so that I can avoid the workaround?

**Comment by ijrsvt** [comment] 2020-06-26 21:36
@vtomenko I am closing it for the moment because it actually breaks some of the autoscaler--It should be merged in about a week

**Comment by ijrsvt** [comment] 2020-07-20 18:09
@vtomenko any updates on your end? How are things going?

**Comment by vtomenko** [comment] 2020-07-24 04:20
@ijrsvt , I got it working with the following configuration for AWS:

- head/worker nodes: Deep Learning Base AMI (Ubuntu 18.04) (so that all required GPU drivers etc. and docker is installed)
- instance type: g4dn.xlarge
- docker image: based on nvidia/cuda:10.2-cudnn7-runtime-ubuntu18.04 (so that container can use GPUs) + in my case mxnet packages with GPU support
- for custom docker repository: added "docker login ..." to initialization_commands section in cluster YAML.  

Note: I also added openssh-client to docker image because autoscaler manages worker nodes via ssh

**Comment by ijrsvt** [comment] 2020-07-24 17:11
@vtomenko Great to hear!! The autoscaler _should_ work without needing to directly SSH into the containers on the worker nodes. Was this not happening for you?

**Comment by vtomenko** [comment] 2020-07-24 18:29
@ijrsvt , my understanding is that autoscaler ssh into worker node from docker container on head node. So if the container on head node does not have ssh installed, worker nodes are not configured properly. Looks like same issue here #5496

**Comment by ijrsvt** [comment] 2020-07-24 18:50
Oh--that totally makes sense--my bad. I mis-read that as an `openssh-server`. The general requirements of the autoscaler are captured [in this Dockerfile](https://github.com/ray-project/ray/blob/master/docker/base-deps/Dockerfile). Please let me know if you have any other problems/questions/feedback! I'm always happy to hel!

**Comment by richardliaw** [comment] 2021-07-16 05:50
Should be supported now. Try using `rayproject/ray:latest-gpu`.

**Closed by richardliaw** 2021-07-16 05:50 UTC
Labels: P2, enhancement, tune
