### ISSUE TITLE
[core] many_tasks release test failing

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#29911] opened 2022-11-01 22:40 UTC
### What happened + What you expected to happen

cluster: https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_XXdPUNHdTr9Fyddf9XAvQzDK?command-history-section=command_history

recent runs: https://b534fd88.us1a.app.preset.io/superset/dashboard/26/?native_filters_key=YmnjIijUTaSB05DuD8BFeQ8X5NgGkEWlu_vTBj1fxVbiujAehX6OuHjC20cbUPsk

### Versions / Dependencies

master

### Reproduction script

https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_XXdPUNHdTr9Fyddf9XAvQzDK?command-history-section=command_history

**Comment by rickyyx** [comment] 2022-11-07 18:52
Tried a run with lower grpcio version here: https://buildkite.com/ray-project/release-tests-pr/builds/19924#01843950-3ca3-4c13-ba9f-bfe20f1306f0

The tl;dr is that higher version of grpcio seems to result in regression on the test perf metrics, running a few more to validate it.

**Comment by rickyyx** [comment] 2022-11-07 18:55
I also think this could be relevant with the task metric exporting. Let me see if I could turn the task metrics exporting off and see what's the benchmark value.

**Comment by rickyyx** [comment] 2022-11-14 18:02
With pretty high confidence - I think the recent regression (test failures) is due to the revert of this PR. 

Opening a PR to rever the revert and make sure tests passing. https://github.com/ray-project/ray/pull/30219

**Comment by xwjiang2010** [comment] 2022-11-16 17:22
Still failing in the most recent try: https://buildkite.com/ray-project/release-tests-branch/builds/1197#01847d5a-ee8b-4105-b2a3-c16e198e4623

When can we land the revert of revert?

**Comment by rickyyx** [comment] 2022-11-17 22:50
Landed https://github.com/ray-project/ray/pull/30219. Waiting for next succesful run to close the issue.

**Comment by rickyyx** [comment] 2022-11-18 18:04
Was able to [pass (after retry) on the recent master](https://buildkite.com/ray-project/release-tests-branch/builds/1201#018488f6-b8c9-4550-ada7-247b49c37228) - this should not be a release blocker anymore, but the core team will monitor and keep optimizing the test.

**Closed by rickyyx** 2022-11-18 18:04 UTC
Labels: bug, release-blocker, P0, core, r2.2-failure
