### ISSUE TITLE
A3C + pytorch seems to crash on jenkins

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#2610] opened 2018-08-09 00:20 UTC
I've seen this multiple times, never before with the current ray backend though.

```
+ docker run -e RAY_USE_XRAY=1 --rm --shm-size=10G --memory=10G cfca7c87523a7d361ba790a1c243ee28904b7148b9b0bd0029ed2da28d2e28eb python /ray/python/ray/rllib/train.py --env CartPole-v1 --run A3C --stop '{"training_iteration": 2}' --config '{"num_workers": 2, "use_pytorch": true}'
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Detected environment variable 'RAY_USE_XRAY'.
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:15291 to respond...
Waiting for redis server at 127.0.0.1:46790 to respond...
Warning: Reducing object store memory because /dev/shm has only 10737418240 bytes available. You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui78021.ipynb?token=83f0de448b2c4722ea862e3a0d9b766b34f716a75fd787a1
======================================================================

WARNING: Serializing objects of type <class 'ray.rllib.evaluation.sample_batch.SampleBatch'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARN: gym.spaces.Box autodetected dtype as <type 'numpy.float32'>. Please provide explicit dtype.
Constructing fcnet [256, 256] <class 'torch.nn.modules.activation.Tanh'>
/ray/thirdparty/build/arrow/cpp/src/plasma/client.cc:628 Check failed: object_entry != objects_in_use_.end() 
A worker died or was killed while executing task 000000003130127e1a001b624d57a9d8f7792bc3.
Remote function train failed with:

Traceback (most recent call last):
  File "/ray/python/ray/worker.py", line 934, in _process_task
    *arguments)
  File "/ray/python/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/ray/python/ray/tune/trainable.py", line 137, in train
    result = self._train()
  File "/ray/python/ray/rllib/agents/a3c/a3c.py", line 102, in _train
    self.optimizer.step()
  File "/ray/python/ray/rllib/optimizers/async_gradients_optimizer.py", line 44, in step
    gradient, info = ray.get(fut)
  File "/ray/python/ray/worker.py", line 2493, in get
    raise RayGetError(object_ids, value)
RayGetError: Could not get objectid ObjectID(010000003130127e1a001b624d57a9d8f7792bc3). It was created by remote function <unknown> which failed with:

Remote function <unknown> failed with:

Invalid return value: likely worker died or was killed while executing the task.

A worker died or was killed while executing task 00000000d24e47fe917ec9734fcbe8b2229a24b4.
A worker died or was killed while executing task 00000000077dc670da5ee1bcfe07be2fda36bdb0.
== Status ==
Using FIFO scheduling algorithm.

Created LogSyncer for /root/ray_results/default/A3C_CartPole-v1_0_2018-08-08_22-12-14o1hPr0 -> 
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 3/48 CPUs, 0/0 GPUs
Result logdir: /root/ray_results/default
RUNNING trials:
 - A3C_CartPole-v1_0:	RUNNING

Error processing event: Traceback (most recent call last):
  File "/ray/python/ray/tune/trial_runner.py", line 265, in _process_events
    result = ray.get(result_id)
  File "/ray/python/ray/worker.py", line 2493, in get
    raise RayGetError(object_ids, value)
RayGetError: Could not get objectid ObjectID(01000000f86621c5f95317bb8f95d539d6e6a24c). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/ray/python/ray/worker.py", line 934, in _process_task
    *arguments)
  File "/ray/python/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/ray/python/ray/tune/trainable.py", line 137, in train
    result = self._train()
  File "/ray/python/ray/rllib/agents/a3c/a3c.py", line 102, in _train
    self.optimizer.step()
  File "/ray/python/ray/rllib/optimizers/async_gradients_optimizer.py", line 44, in step
    gradient, info = ray.get(fut)
  File "/ray/python/ray/worker.py", line 2493, in get
    raise RayGetError(object_ids, value)
RayGetError: Could not get objectid ObjectID(010000003130127e1a001b624d57a9d8f7792bc3). It was created by remote function <unknown> which failed with:

Remote function <unknown> failed with:

Invalid return value: likely worker died or was killed while executing the task.


Worker ip unknown, skipping log sync for /root/ray_results/default/A3C_CartPole-v1_0_2018-08-08_22-12-14o1hPr0
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/48 CPUs, 0/0 GPUs
Result logdir: /root/ray_results/default
ERROR trials:
 - A3C_CartPole-v1_0:	ERROR, 1 failures: /root/ray_results/default/A3C_CartPole-v1_0_2018-08-08_22-12-14o1hPr0/error_2018-08-08_22-12-21.txt

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/48 CPUs, 0/0 GPUs
Result logdir: /root/ray_results/default
ERROR trials:
 - A3C_CartPole-v1_0:	ERROR, 1 failures: /root/ray_results/default/A3C_CartPole-v1_0_2018-08-08_22-12-14o1hPr0/error_2018-08-08_22-12-21.txt

```

**Comment by guoyuhong** [comment] 2018-08-09 02:43
https://github.com/ray-project/ray/issues/2494 At first I thought this could be caused by some concurrent issue. After debug, it is not the reason. I believe this crash happened in worker part not the backend part. Is it possible caused by some script misuse, which is similar to use `fetch` in raylet?

**Comment by ericl** [comment] 2018-08-09 03:32
I think the only difference is that we return pytorch gradients converted to numpy. These might have different structure than the tensorflow values.

**Comment by guoyuhong** [comment] 2018-08-09 03:51
This error is not introduced by raylet. In legacy ray, it the same has this problem. However, it is very hard to repro it in my local env. Do you have any clue?

**Comment by ericl** [comment] 2018-08-09 05:35
Hmm, I also cannot reproduce locally. I've never seen it fail on legacy ray
though, do you have a link?

**Comment by guoyuhong** [comment] 2018-08-09 06:29
Yes. Here: https://github.com/ray-project/ray/issues/2494 . In the description, there are many error. Actually, at that time when this issue was posted, there are two major issues. 
1. https://github.com/ray-project/ray/issues/2503
2. https://github.com/ray-project/ray/issues/2494
I though raylet could fix both, but it failed. I only fix the timeout issue. The plasma client check failure continues...

**Comment by robertnishihara** [comment] 2018-08-09 06:37
There's probably a bug or misuse of the Plasma API in these lines https://github.com/ray-project/ray/blob/df7ee7ff1eaba5afbfa8e84c47b5a727a66f5ec7/src/ray/raylet/node_manager.cc#L776-L786

Do we have a backtrace? Is the fatal error happening when the `data` buffer destructor runs?

cc @pcmoritz

**Comment by guoyuhong** [comment] 2018-08-09 06:52
When I debug the misuse of `fetch` in raylet mode of script `python/ray/rllib/utils/actors.py` in https://github.com/ray-project/ray/pull/2567 . The log comes from worker instead of backend. If a node_manager failed, there will be many other error message posted. Therefore, I believe this is only a script side failure in PlasmaClient.

**Comment by guoyuhong** [comment] 2018-08-09 06:54
For the code snippet that @robertnishihara posted, I changed it to the following code, but it still did not work.
```c
if (status.ok()) { 
   ARROW_CHECK_OK(store_client_.Seal(object_id.to_plasma_id()));
}
```

**Comment by guoyuhong** [comment] 2018-09-06 07:34
I add some test code in arrow and there is call stack now: https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/8009/console .
The output is: 
```
WARNING: Serializing objects of type <class 'ray.rllib.evaluation.sample_batch.SampleBatch'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
F0906 07:00:24.489765   299 client.cc:637]  Check failed: object_entry != objects_in_use_.end() 
*** Check failure stack trace: ***
    @     0x7fead4739ced  google::LogMessage::Fail()
    @     0x7fead473b648  google::LogMessage::SendToLog()
    @     0x7fead47397fb  google::LogMessage::Flush()
    @     0x7fead4739a19  google::LogMessage::~LogMessage()
    @     0x7fead4734f20  arrow::ArrowLog::~ArrowLog()
    @     0x7fead470ca42  plasma::PlasmaClient::Impl::PerformRelease()
    @     0x7fead470cd21  plasma::PlasmaClient::Impl::Release()
    @     0x7fead4713edd  std::_Sp_counted_ptr_inplace<>::_M_dispose()
    @     0x7fead498efe1  arrow::Buffer::~Buffer()
    @     0x7fead5ec3731  __pyx_tp_dealloc_7pyarrow_3lib_Buffer()
    @     0x7feaee527aa9  array_dealloc
    @     0x7feaaa9c35ac  _ZNSt17_Function_handlerIFvPvEZN5torch5utils17tensor_from_numpyEP7_objectEUlS0_E_E9_M_invokeERKSt9_Any_dataS0_
    @     0x7fead7f3cc9c  at::deleteInefficientStdFunctionContext()
    @     0x7fead81e7314  THStorage_free
    @     0x7fead8286a1f  THTensor_free
    @     0x7fead80c98b9  at::CPUFloatTensor::~CPUFloatTensor()
    @     0x7feaaad1cbd1  torch::autograd::Variable::Impl::~Impl()
    @     0x7feaaad1cd49  torch::autograd::Variable::Impl::~Impl()
    @     0x7feaaad33e89  THPVariable_clear()
    @     0x7feaf0e9df72  collect
    @     0x7feaf0e9e971  _PyObject_GC_Malloc
    @     0x7feaf0e9e9be  _PyObject_GC_New
    @     0x7feaf0dee095  PyGen_New
    @     0x7feaf0df828a  function_call
    @     0x7feaf0dd37a3  PyObject_Call
    @     0x7feaf0de263d  instancemethod_call
    @     0x7feaf0dd37a3  PyObject_Call
    @     0x7feaf0e2c650  slot_tp_iter
    @     0x7feaf0dd490f  PyObject_GetIter
    @     0x7feaf0e68cfe  PyEval_EvalFrameEx
    @     0x7feaf0e6df9e  PyEval_EvalFrameEx
    @     0x7feaf0e6f4e9  PyEval_EvalCodeEx
WARN: gym.spaces.Box autodetected dtype as <type 'numpy.float32'>. Please provide explicit dtype.
Constructing fcnet [256, 256] <class 'torch.nn.modules.activation.Tanh'>
The worker with ID 359663a0a9229ff83a2de6b4a931d737f96580c3 died or was killed while executing the task with ID 92b019464da617fb5f5243277bd4de3d81d2474d
Remote function train failed with:
```
It looks like this is called by pytorch. @ericl , do you have an idea which script calls this?

**Comment by ericl** [comment] 2018-09-06 16:41
That looks like pyarrow interpreting a numpy array as a tensor. Somehow
that is deallocating the array which crashes?

**Comment by robertnishihara** [comment] 2018-09-06 22:28
@guoyuhong @ericl @pcmoritz interesting, I would expect `tensor_from_numpy` to create a PyTorch Tensor, which holds a reference to the numpy array that it was created from, which in turn should hold a reference to the pyarrow buffer backed by shared memory.

However, it looks like the pyarrow buffer is getting released, which makes me think that isn't happening..

I can reproduce the issue in docker, but somehow not when I add print statements..

**Comment by guoyuhong** [comment] 2018-09-09 02:46
FYI:
From the following error message:
```
Remote function train failed with:

Traceback (most recent call last):
  File "/ray/python/ray/worker.py", line 931, in _process_task
    *arguments)
  File "/ray/python/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/ray/python/ray/rllib/agents/agent.py", line 212, in train
    return Trainable.train(self)
  File "/ray/python/ray/tune/trainable.py", line 146, in train
    result = self._train()
  File "/ray/python/ray/rllib/agents/a3c/a3c.py", line 106, in _train
    self.optimizer.step()
  File "/ray/python/ray/rllib/optimizers/async_gradients_optimizer.py", line 44, in step
    gradient, info = ray.get(fut)
  File "/ray/python/ray/worker.py", line 2514, in get
    raise RayGetError(object_ids, value)
```
It looks like  [`compute_gradients`](https://github.com/ray-project/ray/blob/master/python/ray/rllib/evaluation/torch_policy_graph.py#L85-L89) fails in function  `torch.from_numpy` in the worker. Therefore the later worker tries to get the output of this function but fails.

**Comment by richardliaw** [comment] 2018-09-10 03:14
Is this a pyarrow issue? Should we open an issue on PyArrow to track?

**Comment by guoyuhong** [comment] 2018-09-10 03:15
I have some new findings. I need to confirm. Let's hold for a second.

**Comment by guoyuhong** [comment] 2018-09-12 05:49
I added some more test code. At the beginning, I doubted that this could be caused by some racing issue while killing a worker, but the experiments didn't indicate that. The issue only happens in PyTorch test. No Tensorflow tests have this problem. Moreover, the PyTorch crash log is always the earliest log from the output. Therefore, it could be caused by PyTorch or PyArrow problem. @robertnishihara Is the release not an expected behavior? @richardliaw Could you please open an issue on PyArrow to track?

**Comment by robertnishihara** [comment] 2018-09-12 06:36
@guoyuhong `release` definitely should be called when objects going out of scope. It's not obvious to me that it should be called in `tensor_from_numpy`, but I'm not sure.

**Comment by guoyuhong** [comment] 2018-09-12 07:06
@robertnishihara Thanks. I may turn to other work items and put this problem aside due to our arrangement.

**Comment by robertnishihara** [comment] 2018-09-12 07:08
@guoyuhong ok, thanks for looking into it, and please let me know if you have other ideas.

**Comment by robertnishihara** [comment] 2018-09-13 18:50
I'm going to look into this a little bit now.

**Comment by pcmoritz** [comment] 2018-09-13 19:01
Given the stacktrace, I wonder if it is possible that Release is called from a different thread, that might cause problems.

**Comment by ericl** [comment] 2018-10-28 04:47
@pcmoritz @guoyuhong I've managed to reproduce this by having a plasma object released by a different thread than the one that created it (confirming the above hypothesis).

**Comment by robertnishihara** [comment] 2018-10-28 19:59
Oh nice!

**Comment by robertnishihara** [comment] 2018-10-30 18:49
The `plasma_client` is not thread safe. So whenever we use it, we protect it with a lock. However, the plasma client gets used implicitly whenever a numpy array backed by the object store goes out of scope (because it is used to call "release" on the object store).

That may be the problem.

**Comment by ericl** [comment] 2018-11-01 06:40
No good -- it seems slightly more reliable (?), but still got a check failure with APEX_DDPG:

```
/home/eric/Desktop/ray-private/build/external/arrow/src/arrow_ep/cpp/src/plasma/client.cc:663:  Check failed: object_entry != objects_in_use_.end() 
/home/eric/Desktop/ray-private/python/ray/pyarrow_files/pyarrow/libarrow.so.12(+0x80808)[0x7f0fc9473808]
/home/eric/Desktop/ray-private/python/ray/pyarrow_files/pyarrow/libarrow.so.12(_ZN5arrow4util8ArrowLogD1Ev+0xdd)[0x7f0fc952359d]
/home/eric/Desktop/ray-private/python/ray/pyarrow_files/pyarrow/libplasma.so.12(+0x13642)[0x7f0fc8814642]
/home/eric/Desktop/ray-private/python/ray/pyarrow_files/pyarrow/libplasma.so.12(+0x13b71)[0x7f0fc8814b71]
/home/eric/Desktop/ray-private/python/ray/pyarrow_files/pyarrow/libplasma.so.12(+0x1b02d)[0x7f0fc881c02d]
/home/eric/Desktop/ray-private/python/ray/pyarrow_files/pyarrow/_plasma.cpython-35m-x86_64-linux-gnu.so(_ZN5arrow6BufferD1Ev+0x71)[0x7f0fc8a693c1]
/home/eric/Desktop/ray-private/python/ray/pyarrow_files/pyarrow/lib.cpython-35m-x86_64-linux-gnu.so(+0x5471a)[0x7f0fc98ab71a]
/usr/local/lib/python3.5/dist-packages/numpy/core/multiarray.cpython-35m-x86_64-linux-gnu.so(+0x22e97)[0x7f0fdc4a8e97]
/home/eric/bin/python[0x5a1091]
/home/eric/bin/python[0x580fd5]
/home/eric/bin/python[0x5a1091]
/home/eric/bin/python[0x580fd5]
/home/eric/bin/python[0x4e9117]
/home/eric/bin/python(PyEval_EvalFrameEx+0x4b36)[0x53b816]
/home/eric/bin/python(PyEval_EvalFrameEx+0x4b04)[0x53b7e4]
/home/eric/bin/python(PyEval_EvalFrameEx+0x4b04)[0x53b7e4]
/home/eric/bin/python(PyEval_EvalCodeEx+0x13b)[0x540f9b]
/home/eric/bin/python[0x4ebd23]
/home/eric/bin/python(PyObject_Call+0x47)[0x5c1797]
/home/eric/bin/python[0x4fb9ce]
/home/eric/bin/python(PyObject_Call+0x47)[0x5c1797]
/home/eric/bin/python(PyEval_CallObjectWithKeywords+0x30)[0x534d90]
/home/eric/bin/python[0x609c02]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f0fddd226ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f0fdda5841d]
A worker died or was killed while executing task 0000000026e8f84442746bb5c92d995e0f9cae73.
```

**Closed** 2020-03-30 00:21 UTC
