### ISSUE TITLE
[Data]Can't instantiate ray on Python 3.10.11 | packaged by Anaconda, Inc. | [MSC v.1916 64 bit (AMD64)] on win32

### ISSUE THREAD

**Issue by lejarx** [ray-project/ray#37036] opened 2023-07-03 10:50 UTC
### What happened + What you expected to happen

Hi

I'm just going through the getting-started page
https://docs.ray.io/en/latest/ray-overview/getting-started.html

I'm not able to instantiate the ray class as below
```
import ray
# Load data.
dataset = ray.data.read_csv("s3://anonymous@air-example-data/breast_cancer.csv")
```

The error is below.

```
>>> ray
<module 'ray' from 'C:\\Users\\user1\\anaconda3\\envs\\raycheck\\lib\\site-packages\\ray\\__init__.py'>
>>> ray.data.read_csv("s3://anonymous@air-example-data/breast_cancer.csv")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user1\anaconda3\envs\raycheck\lib\site-packages\ray\data\read_api.py", line 1015, in read_csv
    return read_datasource(
  File "C:\Users\user1\anaconda3\envs\raycheck\lib\site-packages\ray\_private\auto_init_hook.py", line 17, in auto_init_wrapper
    auto_init_ray()
  File "C:\Users\user1\anaconda3\envs\raycheck\lib\site-packages\ray\_private\auto_init_hook.py", line 11, in auto_init_ray
    ray.init()
  File "C:\Users\user1\anaconda3\envs\raycheck\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\user1\anaconda3\envs\raycheck\lib\site-packages\ray\_private\worker.py", line 1534, in init
    _global_node = ray._private.node.Node(
  File "C:\Users\user1\anaconda3\envs\raycheck\lib\site-packages\ray\_private\node.py", line 290, in __init__
    self.start_ray_processes()
  File "C:\Users\user1\anaconda3\envs\raycheck\lib\site-packages\ray\_private\node.py", line 1213, in start_ray_processes
    resource_spec = self.get_resource_spec()
  File "C:\Users\user1\anaconda3\envs\raycheck\lib\site-packages\ray\_private\node.py", line 459, in get_resource_spec
    self._resource_spec = ResourceSpec(
  File "C:\Users\user1\anaconda3\envs\raycheck\lib\site-packages\ray\_private\resource_spec.py", line 175, in resolve
    num_gpus = _autodetect_num_gpus()
  File "C:\Users\user1\anaconda3\envs\raycheck\lib\site-packages\ray\_private\resource_spec.py", line 287, in _autodetect_num_gpus
    lines = subprocess.check_output(cmdargs).splitlines()[1:]
  File "C:\Users\user1\anaconda3\envs\raycheck\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\user1\anaconda3\envs\raycheck\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\user1\anaconda3\envs\raycheck\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\user1\anaconda3\envs\raycheck\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Some relevant information
```
System: Windows
Release: 10
Version: 10.0.22621
Machine: AMD64
Processor: Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
```

```
pip freeze
pip freeze
aiohttp==3.8.4
aiohttp-cors==0.7.0
aiorwlock==1.3.0
aiosignal==1.3.1
ansicon==1.89.0
anyio==3.7.0
async-timeout==4.0.2
attrs==23.1.0
blessed==1.20.0
cachetools==5.3.1
certifi==2023.5.7
charset-normalizer==3.1.0
click==8.1.3
colorama==0.4.6
colorful==0.5.5
distlib==0.3.6
exceptiongroup==1.1.2
fastapi==0.99.1
filelock==3.12.2
frozenlist==1.3.3
fsspec==2023.6.0
google-api-core==2.11.1
google-auth==2.21.0
googleapis-common-protos==1.59.1
gpustat==1.1
grpcio==1.51.3
h11==0.14.0
idna==3.4
jinxed==1.2.0
jsonschema==4.17.3
msgpack==1.0.5
multidict==6.0.4
numpy==1.25.0
nvidia-ml-py==11.525.131
opencensus==0.11.2
opencensus-context==0.1.3
packaging==23.1
pandas==2.0.3
platformdirs==3.8.0
prometheus-client==0.17.0
protobuf==4.23.3
psutil==5.9.5
py-spy==0.3.14
pyarrow==6.0.1
pyasn1==0.5.0
pyasn1-modules==0.3.0
pydantic==1.10.10
pyrsistent==0.19.3
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0
ray==2.5.1
requests==2.31.0
rsa==4.9
six==1.16.0
smart-open==6.3.0
sniffio==1.3.0
starlette==0.27.0
tensorboardX==2.6.1
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
uvicorn==0.22.0
virtualenv==20.21.0
wcwidth==0.2.6
yarl==1.9.2
```

### Versions / Dependencies

Some relevant information
```
System: Windows
Release: 10
Version: 10.0.22621
Machine: AMD64
Processor: Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
```

```
pip freeze
pip freeze
aiohttp==3.8.4
aiohttp-cors==0.7.0
aiorwlock==1.3.0
aiosignal==1.3.1
ansicon==1.89.0
anyio==3.7.0
async-timeout==4.0.2
attrs==23.1.0
blessed==1.20.0
cachetools==5.3.1
certifi==2023.5.7
charset-normalizer==3.1.0
click==8.1.3
colorama==0.4.6
colorful==0.5.5
distlib==0.3.6
exceptiongroup==1.1.2
fastapi==0.99.1
filelock==3.12.2
frozenlist==1.3.3
fsspec==2023.6.0
google-api-core==2.11.1
google-auth==2.21.0
googleapis-common-protos==1.59.1
gpustat==1.1
grpcio==1.51.3
h11==0.14.0
idna==3.4
jinxed==1.2.0
jsonschema==4.17.3
msgpack==1.0.5
multidict==6.0.4
numpy==1.25.0
nvidia-ml-py==11.525.131
opencensus==0.11.2
opencensus-context==0.1.3
packaging==23.1
pandas==2.0.3
platformdirs==3.8.0
prometheus-client==0.17.0
protobuf==4.23.3
psutil==5.9.5
py-spy==0.3.14
pyarrow==6.0.1
pyasn1==0.5.0
pyasn1-modules==0.3.0
pydantic==1.10.10
pyrsistent==0.19.3
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0
ray==2.5.1
requests==2.31.0
rsa==4.9
six==1.16.0
smart-open==6.3.0
sniffio==1.3.0
starlette==0.27.0
tensorboardX==2.6.1
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
uvicorn==0.22.0
virtualenv==20.21.0
wcwidth==0.2.6
yarl==1.9.2
```

### Reproduction script

I create the conda env
`conda create --name raycheck python=3.10`

Next I just install ray
`pip install -U "ray[air]"`

Below is the machine information
```
System: Windows
Release: 10
Version: 10.0.22621
Machine: AMD64
Processor: Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by rkooo567** [comment] 2023-07-07 08:08
cc @c21 Is ray dataset supporting windows?

**Comment by c21** [comment] 2023-07-10 22:57
Thanks for reporting, we will reproduce and see where is the issue.

**Comment by mattip** [comment] 2023-07-25 09:42
The problem is this
```
File "C:\Users\user1\anaconda3\envs\raycheck\lib\site-packages\ray\_private\resource_spec.py", line 175, in resolve
    num_gpus = _autodetect_num_gpus()
```

which should be solved by #35581 (using `gpustat`, which should always be installed, instead of `GPUtil` which is not consistently installed).

**Comment by anyscalesam** [comment] 2023-11-08 21:35
@mattip do you think you'll be able to get the gpustat PR merged by EOTM? Slack me; I can help prioritize reviews as required.

**Comment by mattip** [comment] 2023-11-09 07:51
PR #41020 makes #35581 obsolete and merging #41020 should close this.

**Comment by jjyao** [comment] 2023-11-14 19:30
https://github.com/ray-project/ray/pull/41020 is merged. @lejarx or @mattip could you try nightly and verify that your issue is resolved?

**Closed** 2023-11-30 18:14 UTC
Labels: bug, P1, windows, @external-author-action-required, QS, data, ray 2.9
