### ISSUE TITLE
[data] benchmark regression iter_tensor_batches_benchmark_multi_node

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#40759] opened 2023-10-27 21:58 UTC
there is a 20% regression on benchmark iter_tensor_batches_benchmark_multi_node. 

Only those cases with specified batch_size have regressed, those with default batch size haven't.
Should be related to https://github.com/ray-project/ray/pull/39710

<img width="1260" alt="image" src="https://github.com/ray-project/ray/assets/2883335/73a3dfa0-647e-435f-ac22-dd5711befcb5">

**Comment by stephanie-wang** [comment] 2023-10-28 00:50
I didn't notice any performance changes after manually reverting #40248. But it might be because I've been testing on single node.

I did find a ~10% perf regression in the same benchmark but for single node. Oddly it does not show up on the data dashboard, maybe there is something wrong with the test setup. Offending commit is #40541, which makes sense since it adds an (async) actor task submission to each batch submission

So i'm re-triggering the test right now on:
- [revert of #40541](https://buildkite.com/ray-project/release-tests-pr/builds/57323)
- [revert of the block slicing PR (#40248)](https://buildkite.com/ray-project/release-tests-pr/builds/57322#018b73a5-44bf-4e27-9dfa-7c66380c8eba)

And we'll see from these results... it's possible there were actually two perf regressions introduced at the same time.

**Comment by stephanie-wang** [comment] 2023-10-30 17:16
Downgrading to P1 since #40765 fixes the issue for 2.8.

**Comment by stephanie-wang** [comment] 2023-11-02 17:08
Seems like the regression is expected:

- current target block size=128MiB and the test's configured batch size means that each block only produces 1-2 batches, and these batches aren't aligned with the block boundaries. So there is likely some memory copying and remote object fetching overhead.
- reverting to 512MiB block size fixes the perf regression
- the batch prefetching version of the benchmark has no regression

**Comment by stephanie-wang** [comment] 2023-11-03 16:53
Closing since regression in this test is expected.

**Closed by stephanie-wang** 2023-11-03 16:53 UTC
Labels: P1, data, ray 2.9
