### ISSUE TITLE
[tune][rllib] How to do rollout by code?

### ISSUE THREAD

**Issue by suprmat95** [ray-project/ray#7660] opened 2020-03-19 14:02 UTC
### Is it possible to do rollout by code?

* python: 3.7.3
* ray:  0.8.2

I trained my MultiAgentEnv by code:

```
ray.init()

env = StockTradingMultiAgent(5)
register_env("test", lambda _: env)
trainer = ppo.PPOTrainer(env="test", config={
            "env":  "test",
            "num_gpus": 0,
            "num_workers": 0,
            "simple_optimizer": True,
            "multiagent": {
                "policies": {
                               "pg_policy": (None,  spaces.Box(
                                    low=0, high=1, shape=(10, 7), dtype=np.float16),  spaces.Box(
                                    low=np.array([0, 0.01, -1]), high=np.array([3, 0.5, 1]), dtype=np.float16), {}),
                              },
                "policy_mapping_fn": (lambda agent_id: select_policy(agent_id)),
                "policies_to_train": ["pg_policy"],

            },
        })
for i in range(3):
   result = trainer.train()
   print(pretty_print(result))

   if i % 1 == 0:
       checkpoint = trainer.save()
       print("checkpoint saved at", checkpoint)
```

How can I run the environment trained by code ? In other words can I do the same of the command rllib rollout by code? Because I tried to do rllib rollout and I got some errors.
Thanks,
Matteo

**Comment by ericl** [comment] 2020-03-19 21:35
Uncomment and fill in the line here: https://github.com/ray-project/ray/blob/master/rllib/rollout.py#L33

**Comment by ericl** [comment] 2020-03-19 21:36
Duplicate of https://github.com/ray-project/ray/issues/7659

**Closed by ericl** 2020-03-19 21:36 UTC
Labels: P2, question, rllib

**Comment by ruben39x2** [comment] 2020-04-14 22:25
@suprmat95 Hi,
I faced a similar issue and please, note that `register_env` wasn't even needed after all.
I was considering open a Pull Request with support for an additional parameter in `config` (something like a "custom_env": "module_name.CustomClassName") (simple, like [this](https://github.com/ray-project/ray/files/4478061/custom_env_registering.patch.txt)) but turns out that having my custom environment module ready on PYTHONPATH system variables works for me.
Hope it helps.
