### ISSUE TITLE
[Core] gcs failed with grpc crashed 

### ISSUE THREAD

**Issue by Basasuya** [ray-project/ray#35432] opened 2023-05-17 11:59 UTC
### What happened + What you expected to happen

When I am running ray cluster with 100-400 worker nodes. The number of worker nodes will change dynamically.
Maybe every minutes have 10 nodes changes.
I meet some condition gcs would failed with below errors

gcs_server.err
```
[2023-05-17 16:56:16,566 E 151 244] (gcs_server) ray_syncer-inl.h:291: [1] Failed to read the message from: 3e490b97944d4a799ed36bdf0ad1d1ab562bfcc210f28329559fc712
[2023-05-17 17:13:50,351 E 151 244] (gcs_server) ray_syncer-inl.h:291: [101] Failed to read the message from: e062841bf20eef404c7123edd679bc26c7b769e1059cab81099644c3
[2023-05-17 17:24:00,993 E 151 243] (gcs_server) ray_syncer-inl.h:291: [201] Failed to read the message from: fe14498fa5afdb21f822baee89e3b428bc0e7eb88c20be3ec8a76698
[2023-05-17 17:34:06,317 E 151 234] (gcs_server) ray_syncer-inl.h:291: [301] Failed to read the message from: 27f762b1ae34f1071ff68fc2c02e3bddd2e7bb39941ad263e45752f8
E0517 17:38:33.254823205     230 call.cc:686]                assertion failed: !destroy_called_
free(): corrupted unsorted chunks
malloc(): unsorted double linked list corrupted
*** SIGABRT received at time=1684316313 on cpu 35 ***
[failure_signal_handler.cc : 329] RAW: Signal 6 raised at PC=0x7f003496cce1 while already in AbslFailureSignalHandler()
[failure_signal_handler.cc : 329] RAW: Signal 6 raised at PC=0x7f003496cce1 while already in AbslFailureSignalHandler()
malloc(): unsorted double linked list corrupted
[failure_signal_handler.cc : 329] RAW: Signal 6 raised at PC=0x7f003496cce1 while already in AbslFailureSignalHandler()
PC: @     0x7f003496cce1  (unknown)  raise
    @     0x7f0034e53140       4064  (unknown)
    @     0x563f274292a3        144  grpc::internal::CallOpSet<>::FinalizeResult()
    @     0x563f27416418         48  grpc::internal::CallbackWithSuccessTag::StaticRun()
    @     0x563f2785ebda         48  grpc::(anonymous namespace)::CallbackAlternativeCQ::Ref()::{lambda()#1}::_FUN()
    @     0x563f27bb9d66        112  grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix()::{lambda()#1}::_FUN()
    @     0x7f0034e47ea7  (unknown)  start_thread
[2023-05-17 17:38:33,260 E 151 230] (gcs_server) logging.cc:361: *** SIGABRT received at time=1684316313 on cpu 35 ***
[2023-05-17 17:38:33,260 E 151 230] (gcs_server) logging.cc:361: PC: @     0x7f003496cce1  (unknown)  raise
[2023-05-17 17:38:33,261 E 151 230] (gcs_server) logging.cc:361:     @     0x7f0034e53140       4064  (unknown)
[2023-05-17 17:38:33,261 E 151 230] (gcs_server) logging.cc:361:     @     0x563f274292a3        144  grpc::internal::CallOpSet<>::FinalizeResult()
[2023-05-17 17:38:33,261 E 151 230] (gcs_server) logging.cc:361:     @     0x563f27416418         48  grpc::internal::CallbackWithSuccessTag::StaticRun()
[2023-05-17 17:38:33,261 E 151 230] (gcs_server) logging.cc:361:     @     0x563f2785ebda         48  grpc::(anonymous namespace)::CallbackAlternativeCQ::Ref()::{lambda()#1}::_FUN()
[2023-05-17 17:38:33,261 E 151 230] (gcs_server) logging.cc:361:     @     0x563f27bb9d66        112  grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix()::{lambda()#1}::_FUN()
[2023-05-17 17:38:33,261 E 151 230] (gcs_server) logging.cc:361:     @     0x7f0034e47ea7  (unknown)  start_threadIn
```

another gcs_server.err
```
[2023-04-24 14:47:07,410 I 89 89] (gcs_server) gcs_actor_scheduler.cc:630: Finished leasing worker from 9d383c1089c62cecf8df1926f1a17be927968841db825af764a43773 for actor 228dd4f594354e4a39ddb350cd000000, job id = cd000000
[2023-04-24 14:47:07,410 I 89 89] (gcs_server) gcs_actor_scheduler.cc:312: Start leasing worker from node 8cadd73c59057e365575db9d97d72f5d9e3f6c67ee76b1d46b6dd06a for actor 228dd4f594354e4a39ddb350cd000000, job id = cd000000
[2023-04-24 14:47:07,412 E 89 171] (gcs_server) logging.cc:361: *** SIGSEGV received at time=1682318827 on cpu 57 ***
[2023-04-24 14:47:07,412 E 89 171] (gcs_server) logging.cc:361: PC: @     0x7fb58c270de0  (unknown)  (unknown)
[2023-04-24 14:47:07,413 E 89 171] (gcs_server) logging.cc:361:     @     0x7fb63ab19140       3392  (unknown)
[2023-04-24 14:47:07,413 E 89 171] (gcs_server) logging.cc:361:     @     0x55947bb899fc         48  grpc_core::ExecCtx::Flush()
[2023-04-24 14:47:07,413 E 89 171] (gcs_server) logging.cc:361:     @     0x55947bb33aa5        240  cq_next()
[2023-04-24 14:47:07,413 E 89 171] (gcs_server) logging.cc:361:     @     0x55947b83fcb5         48  grpc::(anonymous namespace)::CallbackAlternativeCQ::Ref()::{lambda()#1}::_FUN()
[2023-04-24 14:47:07,413 E 89 171] (gcs_server) logging.cc:361:     @     0x55947bb9ae26        112  grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix()::{lambda()#1}::_FUN()
[2023-04-24 14:47:07,413 E 89 171] (gcs_server) logging.cc:361:     @     0x7fb63ab0dea7  (unknown)  start_thread
```

### Versions / Dependencies

ray 2.3.0

### Reproduction script

maybe can reproduce with continually create and delete pod = =

### Issue Severity

High: It blocks me from completing my task.

**Comment by Basasuya** [comment] 2023-05-17 12:05
maybe similar to https://github.com/ray-project/ray/issues/34591

**Comment by Basasuya** [comment] 2023-05-17 12:07
@scv119 could you help to take a look?

**Comment by rkooo567** [comment] 2023-05-22 21:24
Do you set RAY_use_ray_syncer=1?

**Comment by rkooo567** [comment] 2023-05-22 21:25
cc @iycheng this error seems like it is from grpc when the syncer is on. Have you seen a similar issue or doing a investigation now?

**Comment by cadedaniel** [comment] 2023-05-22 22:19
@Basasuya Can you try Ray nightly and see if this still reproduces?

**Comment by scv119** [comment] 2023-05-23 00:49
@Basasuya also do you know if the error happens during the node being stopped?

**Comment by scv119** [comment] 2023-05-23 17:28
given this issue is reported by ray 2.3 and hasn't have more wild spread impact, we decided this is not a release blocker.

**Comment by iycheng** [comment] 2023-05-24 22:29
```
import ray
from ray.cluster_utils import Cluster
import time
import random

cluster = Cluster()


head = cluster.add_node(True, num_cpus=2)

ray.init(cluster.address)


@ray.remote(max_retries=-1)
def run_task():
    time.sleep(1)


objs = [run_task.remote() for _ in range(1024)]

nodes = [cluster.add_node(True, num_cpus=2) for _ in range(32)]

while True:
    random.shuffle(nodes)
    to_kill = nodes[-4:]
    nodes = nodes[:-4]

    for n in to_kill:
        cluster.remove_node(n, False)

    for _ in range(len(to_kill)):
        nodes.append(cluster.add_node(True, num_cpus=2))
    ready, objs = ray.wait(objs, num_returns=len(objs), timeout=0)
    print("ready", len(ready), "objs", len(objs))
    time.sleep(1)
    if len(objs) == 0:
        objs = [run_task.remote() for _ in range(1024)]
```
It can easily being reproduced with ray 2.3. 


```
 (e) base  ~  cat /tmp/ray/session_latest/logs/gcs_server.err
[2023-05-24 22:22:48,743 E 3426216 3426258] (gcs_server) ray_syncer-inl.h:291: [1] Failed to read the message from: 84e6840f46da2ed6969be5c2a3e23b25e7bf0ea8bd8423293d95e810
*** SIGSEGV received at time=1684967005 on cpu 12 ***
PC: @     0x56447e68c090  (unknown)  gpr_free_aligned
    @     0x7fa672fd5420       3360  (unknown)
    @     0x56447e6639ec         32  grpc_core::Arena::Destroy()
    @     0x56447e62f7ca         64  grpc_core::FilterStackCall::ReleaseCall()
    @     0x56447e67ae3c         48  grpc_core::ExecCtx::Flush()
    @     0x56447e624ee5        240  cq_next()
    @     0x56447e331105         48  grpc::(anonymous namespace)::CallbackAlternativeCQ::Ref()::{lambda()#1}::_FUN()
    @     0x56447e68c266        112  grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix()::{lambda()#1}::_FUN()
    @     0x7fa672fc9609  (unknown)  start_thread
```

Running with master and so far so good. I'm going to let it run for a while before conclude this is fixed.

**Comment by iycheng** [comment] 2023-05-25 00:46
Unlike 2.3, which failed within minutes, the master has been running for more than 5hs. I'll consider the issue have been fixed in the master. Close this ticket.

Feel free to reopen if you still see this error.

**Closed by iycheng** 2023-05-25 00:46 UTC
Labels: bug, P0, @external-author-action-required, core

**Comment by xieus** [comment] 2023-05-25 16:23
Thanks @iycheng for reproducing the issue and verifying that the issue is gone in the latest master. Could you pls also point out what was the root cause or what has been done in the latest master that fixed the issue?

**Comment by iycheng** [comment] 2023-06-01 23:08
@xieus I'm not quite sure about this. Given the limit bandwidth, I didn't try to find the root cause given that 2.3 is a really old version and thus hard to bisect. So potentially there still could be the bug happened in this ticket.

But maybe it's this one https://github.com/ray-project/ray/pull/32798

**Comment by Basasuya** [comment] 2023-06-02 06:53
sorry for the delay reply, I am using ray 2.3 without RAY_use_ray_syncer=1

@iycheng  
I would like just cherry-pick https://github.com/ray-project/ray/pull/32798 to see if I can solve this problem. Are there any other related PRs?

BTW, The branch I am using is based on 2.3, and add lots of inner develop theses days.
so If i have to reproduce these error on nightly version, I would take some time to merge my branch to lastest upstream master

**Comment by xieus** [comment] 2023-06-05 21:07
cc: @iycheng
