### ISSUE TITLE
[cluster/windows] ray up is not able to ssh into head node.

### ISSUE THREAD

**Issue by sreddy-es** [ray-project/ray#23844] opened 2022-04-11 21:56 UTC
### What happened + What you expected to happen

Ray up tries to ssh into head node and fails. The nodes are created but `ray up` appears to hang while it attempts to ssh into the head node. `ray attach` doesn't work either after I press `ctrl+c`.  But I can ssh into the machine separately.

`ray up ray_cfg.yaml --no-config-cache`
Error message:(The whitespace is part of the error message)
```
Cluster: minimal

2022-04-11 17:37:40,580 INFO util.py:278 -- setting max workers for head node type to 0
Checking AWS environment settings
AWS config
  IAM Profile: ray-autoscaler-v1 [default]
  EC2 Key pair (all available node types): sid_EC2
  VPC Subnets (all available node types): subnet-fe1fb7f0, subnet-934540ad, subnet-58159315, subnet-6e47ba4f, subnet-4f9f6929, subnet-1303f04c [default]
  EC2 Security groups (all available node types): sg-0b7b4cb93529627cc [default]
  EC2 AMI (all available node types): ami-004641c36e898afd9

No head node found. Launching a new cluster. Confirm [y/N]: y

Acquiring an up-to-date head node
  create_instances: Attempt failed with An error occurred (Unsupported) when calling the RunInstances operation: Your requested instance type (m1.small) is not supported in your requested Availability Zone (us-east-1f). Please retry your request by not specifying an Availability Zone or choosing us-east-1a, us-east-1b, us-east-1c, us-east-1d., retrying.
  create_instances: Attempt failed with An error occurred (Unsupported) when calling the RunInstances operation: Your requested instance type (m1.small) is not supported in your requested Availability Zone (us-east-1e). Please retry your request by not specifying an Availability Zone or choosing us-east-1a, us-east-1b, us-east-1c, us-east-1d., retrying.
  Launched 1 nodes [subnet_id=subnet-58159315]
    Launched instance i-08cf773eb68dcadba [state=pending, info=pending]
  Launched a new head node
  Fetching the new head node

<1/1> Setting up head node
  Prepared bootstrap config
  New status: waiting-for-ssh
  [1/7] Waiting for SSH to become available
    Running `uptime` as a test.
    Fetched IP: 18.209.43.116
getsockname failed: Bad file descriptor
channel_send_open: channel 0: unexpected internal error
    SSH still not available (SSH command failed.), retrying in 5 seconds.
getsockname failed: Bad file descriptor

 )





                                                                                                                       )
















                                                                                                                       1
                                                                                                                       .







```

`ray submit .\ray_cfg.yaml --tmux --stop .\ray_test_job.py`
Error:
```
2022-04-11 17:44:55,450 INFO util.py:278 -- setting max workers for head node type to 0
Loaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
Head node (i-08cf773eb68dcadba) is in state update-failed.
Traceback (most recent call last):
  File "C:\Users\sidfb\anaconda3\envs\ray\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sidfb\anaconda3\envs\ray\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\sidfb\anaconda3\envs\ray\Scripts\ray.exe\__main__.py", line 7, in <module>
  File "C:\Users\sidfb\anaconda3\envs\ray\lib\site-packages\ray\scripts\scripts.py", line 1958, in main
    return cli()
  File "C:\Users\sidfb\anaconda3\envs\ray\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\sidfb\anaconda3\envs\ray\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\sidfb\anaconda3\envs\ray\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\sidfb\anaconda3\envs\ray\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\sidfb\anaconda3\envs\ray\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\sidfb\anaconda3\envs\ray\lib\site-packages\ray\autoscaler\_private\cli_logger.py", line 808, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\sidfb\anaconda3\envs\ray\lib\site-packages\ray\scripts\scripts.py", line 1244, in submit
    rsync(
  File "C:\Users\sidfb\anaconda3\envs\ray\lib\site-packages\ray\autoscaler\_private\commands.py", line 1126, in rsync
    head_node = _get_running_head_node(
  File "C:\Users\sidfb\anaconda3\envs\ray\lib\site-packages\ray\autoscaler\_private\commands.py", line 1257, in _get_running_head_node
    raise RuntimeError("Head node of cluster ({}) not found!".format(
RuntimeError: Head node of cluster (minimal) not found!
```
With `--start`
`ray submit .\ray_cfg.yaml --tmux --start --stop .\ray_test_job.py`
```
Cluster: minimal

2022-04-11 17:45:46,190 INFO util.py:278 -- setting max workers for head node type to 0
Loaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
AWS config
  IAM Profile: ray-autoscaler-v1 [default]
  EC2 Key pair (all available node types): sid_EC2
  VPC Subnets (all available node types): subnet-fe1fb7f0, subnet-934540ad, subnet-58159315, subnet-6e47ba4f, subnet-4f9f6929, subnet-1303f04c [default]
  EC2 Security groups (all available node types): sg-0b7b4cb93529627cc [default]
  EC2 AMI (all available node types): ami-004641c36e898afd9

Updating cluster configuration and running full setup.
Cluster Ray runtime will be restarted. Confirm [y/N]: y [automatic, due to --yes]

<1/1> Setting up head node
  Prepared bootstrap config
  New status: waiting-for-ssh
  [1/7] Waiting for SSH to become available
    Running `uptime` as a test.
    Fetched IP: 18.209.43.116
Warning: Permanently added '18.209.43.116' (ECDSA) to the list of known hosts.
 21:46:00 up 7 min,  1 user,  load average: 1.90, 1.63, 0.91
Connection to 18.209.43.116 closed.
    Success.
  Updating cluster configuration. [hash=08a37f76e75a4949c55fe7a84de9499c46f9e819]
  New status: syncing-files
  [2/7] Processing file mounts
getsockname failed: Bad file descriptor
channel_send_open: channel 0: unexpected internal error
  New status: update-failed
  !!!
  SSH command failed.
  !!!

  Failed to setup head node.
```

### Versions / Dependencies

Ray: 1.11.0
Python: 3.9.12
local OS: Windows 11
server OS: Ubuntu

### Reproduction script

ray_cfg.yaml
```
cluster_name: minimal

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-east-1
    security_group:
      GroupName: launch-wizard-14
    cache_stopped_nodes: False 

available_node_types:
    ray.head.default:
        resources: {}
        node_config:
            InstanceType: m1.small
            KeyName: sid_EC2
            ImageId: ami-004641c36e898afd9 # Deep Learning AMI (Ubuntu) Version 30
            # You can provision additional disk space with a conf as follows
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 130

    ray.worker.default:
        min_workers: 0
        max_workers: 2
        resources: {}
        node_config:
            InstanceType: m1.small
            KeyName: sid_EC2
            ImageId: ami-004641c36e898afd9 # Deep Learning AMI (Ubuntu) Version 30

# Specify the node type of the head node (as configured above).
head_node_type: ray.head.default
auth:
  ssh_user: ubuntu
  ssh_private_key: path/to/private_key_file.pem
```
Commands: 
1. `ray up ray_cfg.yaml --no-config-cache`
2. `ray submit .\ray_cfg.yaml --tmux --stop .\ray_test_job.py`

**Comment by mattip** [comment] 2022-04-17 06:36
This looks suspicious:
>  create_instances: Attempt failed with An error occurred (Unsupported) when calling the RunInstances operation: Your requested instance type (m1.small) is not supported in your requested Availability Zone (us-east-1f). Please retry your request by not specifying an Availability Zone or choosing us-east-1a, us-east-1b, us-east-1c, us-east-1d., retrying.

Does the failure reproduce when running `ray up ray_cfg.yaml --no-config-cache` on linux, for instance in wsl?

**Comment by sreddy-es** [comment] 2022-04-18 14:59
Thanks @mattip, running on WSL helped. I can `ray up` and `ray attach` to the cluster but I'm getting stuck at step [6/7] which I believe is head node setup.

log:
```
username@devicename:~$ ray up -y ray_cfg.yaml
Usage stats collection will be enabled by default in the next release. See https://github.com/ray-project/ray/issues/20857 for more details.
Cluster: minimal

2022-04-18 10:45:26,419 INFO util.py:335 -- setting max workers for head node type to 0
Checking AWS environment settings
AWS config
  IAM Profile: ray-autoscaler-v1 [default]
  EC2 Key pair (all available node types): sid_EC2
  VPC Subnets (all available node types): subnet-fe1fb7f0, subnet-934540ad, subnet-58159315, subnet-6e47ba4f, subnet-4f9f6929, subnet-1303f04c [default]
  EC2 Security groups (all available node types): sg-0b7b4cb93529627cc [default]
  EC2 AMI (all available node types): ami-0726ab024ba364a36

No head node found. Launching a new cluster. Confirm [y/N]: y [automatic, due to --yes]

Acquiring an up-to-date head node
  Launched 1 nodes [subnet_id=subnet-fe1fb7f0]
    Launched instance i-03a63dba1f2308bcd [state=pending, info=pending]
  Launched a new head node
  Fetching the new head node

<1/1> Setting up head node
  Prepared bootstrap config
  New status: waiting-for-ssh
  [1/7] Waiting for SSH to become available
    Running `uptime` as a test.
    Waiting for IP
      Not yet available, retrying in 5 seconds
      Not yet available, retrying in 5 seconds
      Not yet available, retrying in 5 seconds
      Not yet available, retrying in 5 seconds
      Not yet available, retrying in 5 seconds
      Not yet available, retrying in 5 seconds
      Not yet available, retrying in 5 seconds
      Not yet available, retrying in 5 seconds
      Not yet available, retrying in 5 seconds
      Not yet available, retrying in 5 seconds
      Not yet available, retrying in 5 seconds
      Not yet available, retrying in 5 seconds
      Received: 3.239.11.195
ssh: connect to host 3.239.11.195 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 3.239.11.195 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 3.239.11.195 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 3.239.11.195 port 22: Connection timed out
    SSH still not available (SSH command failed.), retrying in 5 seconds.
ssh: connect to host 3.239.11.195 port 22: Connection refused
    SSH still not available (SSH command failed.), retrying in 5 seconds.
Warning: Permanently added '3.239.11.195' (ECDSA) to the list of known hosts.
 14:47:43 up 0 min,  1 user,  load average: 3.38, 0.85, 0.29
Shared connection to 3.239.11.195 closed.
    Success.
  Updating cluster configuration. [hash=2bd220364738bbb7cfc5fe0f1d50419a91a4381a]
  New status: syncing-files
  [2/7] Processing file mounts
Shared connection to 3.239.11.195 closed.
Shared connection to 3.239.11.195 closed.
  [3/7] No worker file mounts to sync
  New status: setting-up
  [4/7] No initialization commands to run.
  [5/7] Initalizing command runner
  [6/7] Running setup commands
    (0/3) (stat $HOME/anaconda3/envs/ten...
Shared connection to 3.239.11.195 closed.
    (1/3) which ray || pip install -U "r...
ERROR: ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl is not a supported wheel on this platform.
Shared connection to 3.239.11.195 closed.
  New status: update-failed
  !!!
  SSH command failed.
  !!!

  Failed to setup head node.
```

**Comment by mattip** [comment] 2022-04-18 16:04
Why doesn't the run via wsl show the "create_instances" error message? Are you not creating a `m1.small` machine now?

**Comment by sreddy-es** [comment] 2022-04-18 16:11
no I switched to `t2.micro`. When I switch back to `m1.small` the "create_instances" error message comes back. I don't think that is an issue for me because I still get a running cluster except the head node is not getting setup. So I can `ray attach` but not `ray submit`.

**Comment by mattip** [comment] 2022-04-18 20:31
You may need to update your pip in order to be able to install manylinux2014 wheels on python3.7

**Comment by sreddy-es** [comment] 2022-04-18 20:38
update pip on the head/worker node? Shouldn't that be a part of the ray head node initialization rather than part of an AMI that I've built from an EBS snapshot?

**Comment by mattip** [comment] 2022-04-18 20:50
> Tried head node configuration in the yaml file ...

Something is off. Can you paste the exact yml file you are using? The wheel you are using is for python3.7, the example you link to above uses python3.8

**Comment by sreddy-es** [comment] 2022-04-18 21:03
So in the example the whole setup is done explicitly as far as I understand.
```
cluster_name: minimal

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-east-1
    security_group:
      GroupName: launch-wizard-14
    # Whether to allow node reuse. If set to False, nodes will be terminated
    # instead of stopped.
    cache_stopped_nodes: False # If not present, the default is True.
available_node_types:
    ray.head.default:
        # The node type's CPU and GPU resources are auto-detected based on AWS instance type.
        # If desired, you can override the autodetected CPU and GPU resources advertised to the autoscaler.
        # You can also set custom resources.
        # For example, to mark a node type as having 1 CPU, 1 GPU, and 5 units of a resource called "custom", set
        # resources: {"CPU": 1, "GPU": 1, "custom": 5}
        resources: {}
        # Provider-specific config for this node type, e.g. instance type. By default
        # Ray will auto-configure unspecified fields such as SubnetId and KeyName.
        # For more documentation on available fields, see:
        # http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.ServiceResource.create_instances
        node_config:
            InstanceType: m1.small
            KeyName: sid_EC2
            ImageId: ami-0726ab024ba364a36 # Deep Learning AMI (Ubuntu) Version 30
            # You can provision additional disk space with a conf as follows
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 130
            # Additional options in the boto docs.
    ray.worker.default:
        # The minimum number of worker nodes of this type to launch.
        # This number should be >= 0.
        min_workers: 0
        # The maximum number of worker nodes of this type to launch.
        # This takes precedence over min_workers.
        max_workers: 2
        # The node type's CPU and GPU resources are auto-detected based on AWS instance type.
        # If desired, you can override the autodetected CPU and GPU resources advertised to the autoscaler.
        # You can also set custom resources.
        # For example, to mark a node type as having 1 CPU, 1 GPU, and 5 units of a resource called "custom", set
        # resources: {"CPU": 1, "GPU": 1, "custom": 5}
        resources: {}
        # Provider-specific config for this node type, e.g. instance type. By default
        # Ray will auto-configure unspecified fields such as SubnetId and KeyName.
        # For more documentation on available fields, see:
        # http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.ServiceResource.create_instances
        node_config:
            InstanceType: m1.small
            KeyName: sid_EC2
            ImageId: ami-0726ab024ba364a36 # Deep Learning AMI (Ubuntu) Version 30
            # Run workers on spot by default. Comment this out to use on-demand.
            # NOTE: If relying on spot instances, it is best to specify multiple different instance
            # types to avoid interruption when one instance type is experiencing heightened demand.
            # Demand information can be found at https://aws.amazon.com/ec2/spot/instance-advisor/
            # InstanceMarketOptions:
            #     MarketType: spot
                # Additional options can be found in the boto docs, e.g.
                #   SpotOptions:
                #       MaxPrice: MAX_HOURLY_PRICE
            # Additional options in the boto docs.

# Specify the node type of the head node (as configured above).
head_node_type: ray.head.default

head_setup_commands:
  # Two first lines are a workaround for ssh timing out
  - sleep 60
  - sudo chown -R $(whoami) /opt/conda/*
  - conda create -y -n "ray" python=3.8.5
  - conda activate ray && echo 'conda activate ray' >> ~/.bashrc
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade "jax[cpu]==0.2.14"
  - python -m pip install --upgrade fabric dataclasses optax==0.0.6 git+https://github.com/deepmind/dm-haiku google-api-python-client cryptography tensorboardX ray[default]
  - python -m pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl
  - git clone https://github.com/Yard1/swarm-jax.git && cd swarm-jax && python -m pip install .

# Install Jax and other dependencies on TPU
# worker_setup_commands:
#   - pip3 install --upgrade pip
#   - pip3 install --upgrade "jax[tpu]==0.2.14" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
#   - pip3 install --upgrade fabric dataclasses optax==0.0.6 git+https://github.com/deepmind/dm-haiku tensorboardX ray[default]
#   - python3 -c "import jax; jax.device_count(); jax.numpy.add(1, 1)"  # test if Jax has been installed correctly
#   - pip3 install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl
#   - git clone https://github.com/Yard1/swarm-jax.git && cd swarm-jax && sudo pip3 install .

auth:
  ssh_user: ubuntu
  ssh_private_key: path/to/private_key_file.pem
```

**Comment by mattip** [comment] 2022-04-19 03:50
In the example above the wheel is `ray-2.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl`. In your error message the wheel is `ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl`. Maybe this difference is causing the error in setting up the head?

**Comment by sreddy-es** [comment] 2022-04-19 14:00
I'm not explicitly choosing this wheel anywhere `ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl'.  It gets automatically chosen irrespective of the actual python version in the virtual env. This is why I'm explicitly choosing the appropriate python version in config file. Even doing that doesn't seem to be helping.

**Comment by mattip** [comment] 2022-04-19 14:54
Sorry I am still confused. I understand now that the section above comes from the file in [the comment above](https://github.com/ray-project/ray/issues/23844#issuecomment-1101765447). Is this the complete example you are using? The error message suggests you are pulling in the [`autoscaler/aws/default.yaml`](https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/aws/defaults.yaml) somewhere instead, since it contains the beginning of this line containing the python37 wheel https://github.com/ray-project/ray/blob/e0c0ea2e592efdaeb0e068508b7150e72de86801/python/ray/autoscaler/aws/defaults.yaml#L127

**Comment by sreddy-es** [comment] 2022-04-19 16:31
I don't think I'm pulling that, at least to my knowledge.

**Comment by sreddy-es** [comment] 2022-04-22 18:50
@theocean154 Still doesn't.

**Comment by mattip** [comment] 2022-08-05 11:53
@sreddy-es does this still reproduce for you?

**Comment by zhe-thoughts** [comment] 2022-10-26 18:33
Closing this but when @sreddy-es gets back we can reopen

**Closed by zhe-thoughts** 2022-10-26 18:33 UTC
Labels: bug, triage, windows, QS
