### ISSUE TITLE
[Core] Call Actor function in remote function cause worker stay after finish.

### ISSUE THREAD

**Issue by TipTa** [ray-project/ray#26041] opened 2022-06-23 16:09 UTC
Call actor in remote function will cause worker stay after the program finish. 
Is there any way to using actor function in remote function?

not using below:
```python

@ray.remote
class Actor(object):
    def __init__(self):
        self.counter = 0
    def add(self, c):
        self.counter += c
        return self.counter

actor = Actor.options(name='actor').remote()

@ray.remote
def do_add(c):
    return c

ref = do_add.remote(1)
actor.add.remote(ref)
```

### Versions / Dependencies

platform: window 11
python: 3.9.13
ray: 1.13.0

### Reproduction script

```python
@ray.remote
class Actor(object):
    def __init__(self):
        self.counter = 0
    def add(self, c):
        self.counter += c
        return self.counter

actor = Actor.options(name='actor').remote()

@ray.remote
def do_add(c):
    return actor.add.remote(c)

do_add.remote(1)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by scv119** [comment] 2022-06-24 02:26
@TipTa to make sure I understand your question, do you expect the worker process to be killed after your job finishes? That's probably a feature where we cache the worker for future execution.

**Comment by TipTa** [comment] 2022-06-24 04:12
> @TipTa to make sure I understand your question, do you expect the worker process to be killed after your job finishes? That's probably a feature where we cache the worker for future execution.

I mean the worker not killed after the main process end, it stay forever until run  `ray stop`

**Comment by TipTa** [comment] 2022-06-24 11:08
> 

never mind, I found a way to solve it. but it will be cool if it can use actor in remote function not causing zombie worker.
```python
@ray.remote
class Actor(object):
    def __init__(self):
        self.counter = 0
    def add(self, c):
        self.counter += c
        return self.counter

actor = Actor.options(name='actor').remote()

@ray.remote
class Executer(object):
    def do_add(self, c):
        return actor.add.remote(c)

executer = Executer.options(name='executer').remote()

executer.do_add.remote(1)
```

**Comment by zhe-thoughts** [comment] 2022-10-26 18:01
As @scv119 commented this is intended behavior (Worker process lives beyond the Driver process). Closing this out but @TipTa please reopen if this is still an open question for you

**Comment by hora-anyscale** [comment] 2022-12-14 01:45
Per Triage sync: if active worker == bug, if idle worker == ok behavior

**Comment by mattip** [comment] 2023-03-29 15:55
@hora-anyscale I am not sure I understand. Is there a bug that needs to be fixed here? As far as I can tell, keeping the workers alive until `ray stop` is run is intended behaviour.

**Comment by ericl** [comment] 2023-03-29 23:44
I cannot reproduce this on master:

![Screenshot from 2023-03-29 16-43-08](https://user-images.githubusercontent.com/14922/228692015-2ea50ddf-a0ee-487b-97f1-f1ce2a3a13f4.png)

The actors seem to be dead after the script exits.

> platform: window 11

Could this be windows bug?

**Comment by mattip** [comment] 2023-04-04 15:08
I get the same result on windows: the worker is dead after executing the script. For completeness, here is what I did:
 (after putting the reproducer in a file `\temp\issue_26041.py`): 
```
python -m venv \temp\ray_venv
\temp\venv\Scripts\activate
pip install "ray[serve]" "ray[dashboard]"
ray start --head
python \temp\issue_26041
```

@TipTa did you expect some other result?

**Comment by anyscalesam** [comment] 2024-01-03 17:11
Bump @TipTa is this issue still occurring for you?

**Closed** 2024-01-07 12:04 UTC
Labels: bug, P2, @external-author-action-required, QS, core
