### ISSUE TITLE
[RLlib] Latest numpy version (1.24.1) causes errors

### ISSUE THREAD

**Issue by jkcarney** [ray-project/ray#31565] opened 2023-01-10 15:54 UTC
### What happened + What you expected to happen

While using the latest numpy version (1.24.1), RLLib's examples for training on the readme error out. When downgrading to numpy==1.23.0, the sample on the readme works and begins training. This was first noticed with my team's code, but it also seems to affect all of RLLib. It would be preferable that RLLib works with the latest version of numpy, instead of having to specify 1.23.0.

Here is the error traceback after following the instructions on the README for tensorflow.

```
2023-01-10 10:49:57,784 ERROR trial_runner.py:1088 -- Trial APPO_CartPole-v0_682f1_00000: Error processing event.
ray.tune.error._TuneNoNextExecutorEventError: Traceback (most recent call last):
  File "/home/carnejk1/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/tune/execution/ray_trial_executor.py", line 1070, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "/home/carnejk1/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/carnejk1/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::APPO.__init__() (pid=4024717, ip=10.115.26.133, repr=APPO)
  File "/home/carnejk1/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/algorithms/appo/appo.py", line 201, in __init__
    super().__init__(config, *args, **kwargs)
  File "/home/carnejk1/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 441, in __init__
    super().__init__(
  File "/home/carnejk1/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 169, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/carnejk1/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/algorithms/appo/appo.py", line 210, in setup
    super().setup(config)
  File "/home/carnejk1/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/algorithms/impala/impala.py", line 464, in setup
    super().setup(config)
  File "/home/carnejk1/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 566, in setup
    self.workers = WorkerSet(
  File "/home/carnejk1/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 169, in __init__
    self._setup(
  File "/home/carnejk1/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 253, in _setup
    spaces = self._get_spaces_from_remote_worker()
  File "/home/carnejk1/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 279, in _get_spaces_from_remote_worker
    remote_spaces = self.foreach_worker(
  File "/home/carnejk1/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 696, in foreach_worker
    handle_remote_call_result_errors(remote_results, self._ignore_worker_failures)
  File "/home/carnejk1/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 73, in handle_remote_call_result_errors
    raise r.get()
  File "/home/carnejk1/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/utils/actor_manager.py", line 473, in __fetch_result
    result = ray.get(r)
ray.exceptions.RaySystemError: System error: _generator_ctor() takes from 0 to 1 positional arguments but 2 were given
traceback: Traceback (most recent call last):
TypeError: _generator_ctor() takes from 0 to 1 positional arguments but 2 were given
```

### Versions / Dependencies

```
ray==2.2.0
numpy==1.24.1
```
Linux
Python 3.8.15

### Reproduction script

```
$ conda create -n rllib python=3.8
$ conda activate rllib
$ pip install "ray[rllib]" tensorflow "gym[atari]" "gym[accept-rom-license]" atari_py
$ # Run a test job:
$ rllib train --run APPO --env CartPole-v0
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by mvindiola1** [comment] 2023-01-10 19:42
Hi @jkcarneyj,

Have you tried using the nightly wheels? I am not seeing this issue there.
https://colab.research.google.com/drive/1sRfZeLbcOT8t55dKxKrpHAEK_NmkFUuN?usp=sharing

**Comment by ArturNiederfahrenhorst** [comment] 2023-01-11 15:45
This is a duplicate of https://github.com/ray-project/ray/issues/31293
numpy>=1.24 triggers this.
Please install a lower numpy version for now if you encountering this error.
Thanks for logging this issue 🙂

**Closed by ArturNiederfahrenhorst** 2023-01-11 15:45 UTC
Labels: bug, triage

**Comment by ArturNiederfahrenhorst** [comment] 2023-01-11 15:52
@mvindiola1 This is indeed fixed on master, thanks for pointing it out! 👍

**Comment by swamidass** [comment] 2023-01-19 18:39
Note that this is creating some serious compatibility problems with other libraries. When will ray release a patch that fixes this?

**Comment by mvindiola1** [comment] 2023-01-20 02:35
@swamidass,
 You can install the nightly wheels, the support 1.24.

https://docs.ray.io/en/latest/ray-overview/installation.html#daily-releases-nightlies

**Comment by swamidass** [comment] 2023-02-08 18:59
Thanks. That works. Seems that Ray should probably release a version 3.0.0 soon, right?
