### ISSUE TITLE
[Bug] ERROR syncer.py:75 -- Log sync requires rsync to be installed. but newest ray doesn't need it

### ISSUE THREAD

**Issue by tom634** [ray-project/ray#20747] opened 2021-11-28 14:12 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune, Others

### What happened + What you expected to happen

I installed newest ray (version 1.8.0) on Windows 10, I am using VS Code with Python 3.9.1.
I am running this code: https://github.com/StephanAkkerman/TensorTrade/tree/main/src
but I get error:
`ERROR syncer.py:75 -- Log sync requires rsync to be installed.`
But:
`pip install ray[rsync]`
gives me:
`WARNING: ray 1.8.0 does not provide the extra 'sync'`
What should I do?

### Versions / Dependencies

Requirement already satisfied: ray in c:\users\tomek\appdata\local\programs\python\python39\lib\site-packages (1.8.0)
Requirement already satisfied: attrs in c:\users\tomek\appdata\local\programs\python\python39\lib\site-packages (from ray) (21.2.0)
Requirement already satisfied: click>=7.0 in c:\users\tomek\appdata\local\programs\python\python39\lib\site-packages (from ray) (8.0.3)
Requirement already satisfied: grpcio>=1.28.1 in c:\users\tomek\appdata\local\programs\python\python39\lib\site-packages (from ray) (1.42.0)
Requirement already satisfied: filelock in c:\users\tomek\appdata\local\programs\python\python39\lib\site-packages (from ray) (3.4.0)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in c:\users\tomek\appdata\local\programs\python\python39\lib\site-packages (from ray) (1.0.3)
Requirement already satisfied: redis>=3.5.0 in c:\users\tomek\appdata\local\programs\python\python39\lib\site-packages (from ray) (4.0.2)
Requirement already satisfied: jsonschema in c:\users\tomek\appdata\local\programs\python\python39\lib\site-packages (from ray) (4.2.1)
Requirement already satisfied: numpy>=1.19.3 in c:\users\tomek\appdata\local\programs\python\python39\lib\site-packages (from ray) (1.19.3)
Requirement already satisfied: pyyaml in c:\users\tomek\appdata\local\programs\python\python39\lib\site-packages (from ray) (5.4.1)
Requirement already satisfied: protobuf>=3.15.3 in c:\users\tomek\appdata\local\programs\python\python39\lib\site-packages (from ray) (3.19.1)
Requirement already satisfied: colorama in c:\users\tomek\appdata\roaming\python\python39\site-packages (from click>=7.0->ray) (0.4.4)
Requirement already satisfied: six>=1.5.2 in c:\users\tomek\appdata\roaming\python\python39\site-packages (from grpcio>=1.28.1->ray) (1.15.0)
Requirement already satisfied: deprecated in c:\users\tomek\appdata\local\programs\python\python39\lib\site-packages (from redis>=3.5.0->ray) (1.2.13)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\tomek\appdata\local\programs\python\python39\lib\site-packages (from jsonschema->ray) (0.18.0)
Requirement already satisfied: wrapt<2,>=1.10 in c:\users\tomek\appdata\roaming\python\python39\site-packages (from deprecated->redis>=3.5.0->ray) (1.12.1)

### Reproduction script

https://github.com/StephanAkkerman/TensorTrade/tree/main/src

### Anything else

Everytime.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mattip** [comment] 2021-12-29 15:33
The default log sync mechanism can only use rsync, which is a unix-y only facility (it cannot be installed via pip). The error can be avoided by setting TUNE_DISABLE_AUTO_CALLBACK_SYNCER before running the code.
```
> set TUNE_DISABLE_AUTO_CALLBACK_SYNCER=1
> python src\main.py
```

And in too much detail:
The [code path](https://github.com/ray-project/ray/blob/8d2f53e25b9ae8d8250b733b38901f3971d4b8a7/python/ray/tune/utils/callback.py#L122) calls `SyncerCallback(sync_function=None)`. This evetually calls`get_node_syncer(%DEFAULT_RESULTS_DIR%/A2C/A2C_TradingEnv_xxxx, %DEFAULT_RESULTS_DIR%/A2C/A2C_TradingEnv_xxxx, None) from [here](https://github.com/ray-project/ray/blob/8d2f53e25b9ae8d8250b733b38901f3971d4b8a7/python/ray/tune/syncer.py#L420). Since `sync_function` is `None`, it calls [`log_sync_template()`](https://github.com/ray-project/ray/blob/8d2f53e25b9ae8d8250b733b38901f3971d4b8a7/python/ray/tune/syncer.py#L446), which then tries to use `rsync`.

I am not sure what the default should be for windows.

**Comment by mattip** [comment] 2022-01-02 12:50
There must be tests that hit this codepath. Any hints which ones? They must not be active on windows

**Comment by mattip** [comment] 2022-01-03 07:25
Running `bazel test python/ray/tune:example` fails for me on windows, something about PythonZipper.

**Comment by mattip** [comment] 2022-01-03 13:59
I don't think downgrading will help, will it?

On the otherhand, I am getting somewhere with running tune tests on windows, and I can replicate the issue running this command once I have pytest and some other packages installed:
```
python -m pytest python\ray\tune\tests\test_commands.py
```

In both the example here and the tests, the remote and local directories are the same so there is nothing to sync. I submitted #21342 to recognize this and set the `sync_client` to `NOOP`.

**Comment by tom634** [comment] 2022-01-03 14:29
Unfortunately, meanwhile the problem dissapeared "by itself" and I am able again to run Ray on Windows. My current, working version of ray is: ray==1.8.0. After reading your replies, I upgraded it to 1.9.1 and it... still works. Maybe there was some different code responsible for this thing in the ray.tune version between them (1.8.0 and 1.9.1)? 
My current issue is that on Linux Virtual Machine (within the same computer) I am able to run ray.tune on even 14 processors, while on my main OS - Windows I can run only up to 4 processors, because it bottlenecks and I have memory error... I have 32 GB of RAM, but this is not the issue of this topic. Thanks for your patience and time!

**Comment by mattip** [comment] 2022-01-03 14:53
Can you open a new issue with a minimal reproducer, and, if this one is no longer relevant, close it?

**Closed** 2022-01-06 13:38 UTC
Labels: bug, P1, windows

**Comment by xiaoToby** [comment] 2022-08-15 02:30
> Unfortunately, meanwhile the problem dissapeared "by itself" and I am able again to run Ray on Windows. My current, working version of ray is: ray==1.8.0. After reading your replies, I upgraded it to 1.9.1 and it... still works. Maybe there was some different code responsible for this thing in the ray.tune version between them (1.8.0 and 1.9.1)? My current issue is that on Linux Virtual Machine (within the same computer) I am able to run ray.tune on even 14 processors, while on my main OS - Windows I can run only up to 4 processors, because it bottlenecks and I have memory error... I have 32 GB of RAM, but this is not the issue of this topic. Thanks for your patience and time!

Did you fix the error now ?
