### ISSUE TITLE
[Docker container] TensorFlow not detecting GPU on p3.8xlarge machine.

### ISSUE THREAD

**Issue by sven1977** [ray-project/ray#13735] opened 2021-01-27 13:59 UTC
The following problem occurs on our docker container: `rayproject/ray-ml:latest-gpu` when deploying it on a GPU machine on an AWS p3.8xlarge instance.

Ray version: https://s3-us-west-2.amazonaws.com/ray-wheels/master/d629292d635b30a350cbd16f4a8943efa8145b00/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
TF version: tf-nightly-gpu==2.4.0.dev20201001

The GPU is not detected by tf.
```
$ python
>>> import tensorflow as tf
>>> tf.config.list_physical_devices()
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
```

This then leads to a follow up error when running e.g. an RLlib job:
```
RuntimeError: GPUs were assigned to this worker by Ray, but your DL framework (tf) reports GPU acceleration is disabled. This could be due to a bad CUDA- or tf installation.
```

### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ijrsvt** [comment] 2021-01-27 16:53
The issue is that the `ray-ml` container currently uses CUDA 10.1 (**not CUDA 11**). Tensorflow bumped their CUDA version support from [10.1 -> 11 ](https://www.tensorflow.org/install/source#gpu) in the 2.4.0 release. 

One workaround until that PR is merged is to run the following in setup commands: 
```
```

**Closed** 2021-01-27 21:45 UTC
Labels: P1, bug
