### ISSUE TITLE
[ray_client] Client prints handled exceptions

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#14161] opened 2021-02-17 19:09 UTC
### What is the problem?
The following does not print anything about the exception:
```python
import ray
ray.init(address="auto")

try:
    ray.get_actor("abc")
except ValueError:
    pass
```
```
2021-02-17 13:07:34,905 INFO worker.py:648 -- Connecting to existing Ray cluster at address: 192.168.0.124:6379
```

but when running with the Ray client, it has verbose output with the exception:
```python
import ray
ray.util.connect("localhost:61234")

try:
    ray.get_actor("abc")
except ValueError:
    pass
```
```
Failed to deserialize b"\x80\x05\x95\xf1\x00\x00\x00\x00\x00\x00\x00\x8c\x08builtins\x94\x8c\nValueError\x94\x93\x94\x8c\xcfFailed to look up actor with name 'abc'. You are either trying to look up a named actor you didn't create, the named actor died, or the actor hasn't been created because named actor creation is asynchronous.\x94\x85\x94R\x94."
Traceback (most recent call last):
  File "/Users/eoakes/code/ray/python/ray/util/client/worker.py", line 275, in _call_schedule_for_task
    raise cloudpickle.loads(ticket.error)
ValueError: Failed to look up actor with name 'abc'. You are either trying to look up a named actor you didn't create, the named actor died, or the actor hasn't been created because named actor creation is asynchronous.
```

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by barakmich** [comment] 2021-02-17 19:32
This looks like a dupe of #13842 but I prefer your reproduction as being simpler and easy to test -- so I'm going to merge it the other way :)

**Closed** 2021-02-18 19:13 UTC
Labels: P1, bug, fix-error-msg
