### ISSUE TITLE
[core] Using ray wheels with latest master in a Python soft-link setup breaks

### ISSUE THREAD

**Issue by roireshef** [ray-project/ray#12543] opened 2020-12-01 19:09 UTC
### What is the problem?
I'm trying to edit ray python code with using latest nightly build and soft-linking to my Ray repo using the script in:
https://docs.ray.io/en/master/development.html#building-ray-python-only

It fails on missing files and constants. The soft-linking script is probably missing some files, but I'm not entirely sure which ones to add and which to not. 

*Ray version and other system information (Python version, TensorFlow version, OS):*
Latest nightly wheel
Latest master branch

### Reproduction (REQUIRED)
1. install latest Ray nightly wheel and run he script in https://docs.ray.io/en/master/development.html#building-ray-python-only
2. Run any Tune experiment

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment] 2020-12-01 19:28
Thanks for filing this issue. Which commit are you on? This might be related to https://github.com/ray-project/ray/commit/9021f15b2ac4a72187c7770f6a8f6d3a6f3373bd cc @sven1977

**Comment by roireshef** [comment] 2020-12-02 00:32
> Thanks for filing this issue. Which commit are you on? This might be related to [9021f15](https://github.com/ray-project/ray/commit/9021f15b2ac4a72187c7770f6a8f6d3a6f3373bd) cc @sven1977

@simon-mo I'm at 9021f15b2ac4a72187c7770f6a8f6d3a6f3373bd ("[RLlib] Fix setup-dev.py error when creating a softlink for new_dashboard. (#12442)") but please do note that there are quite a few exceptions thrown asking for different files that aren't mapped with soft links but neither exist in the nightly build.

It might be a good idea to include a test that makes sure this setup isn't broken when PRs are getting approved by your build system.

**Comment by simon-mo** [comment] 2020-12-02 00:34
@sven1977 can you help?

**Comment by wuisawesome** [comment] 2020-12-14 20:15
@roireshef do you have a reproduction of this? For reference, this seems to consistently work for me when doing autoscaler development. 

Happy to find some time to sit down with you pair debug if this is still an issue btw. 

For reference, here's a cluster yaml of my typical setup:

```
# Experimental: an example of configuring a mixed-node-type cluster.
cluster_name: alex
min_workers: 0
max_workers: 40

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-1
    availability_zone: us-west-1a

# Tell the autoscaler the allowed node types and the resources they provide.
# The key is the name of the node type, which is just for debugging purposes.
# The node config specifies the launch config and physical instance type.
available_node_types:
    cpu_4_ondemand:
        node_config:
            InstanceType: m4.xlarge
        # For AWS instances, autoscaler will automatically add the available
        # CPUs/GPUs/accelerator_type ({"CPU": 4} for m4.xlarge) in "resources".
        resources: {"CPU": 4}
        min_workers: 2
        max_workers: 5
    custom1:
        node_config:
            InstanceType: m4.4xlarge
            InstanceMarketOptions:
                MarketType: spot
        resources: {"Custom1": 1}
        max_workers: 10
    custom2:
        node_config:
            InstanceType: m4.4xlarge
            InstanceMarketOptions:
                MarketType: spot
        resources: {"Custom2": 2}
        max_workers: 4

# Specify the node type of the head node (as configured above).
head_node_type: cpu_4_ondemand

# Specify the default type of the worker node (as configured above).
worker_default_node_type: cpu_4_ondemand

# The default settings for the head node. This will be merged with the per-node
# type configs given above.
head_node:
    ImageId: latest_dlami

# The default settings for worker nodes. This will be merged with the per-node
# type configs given above.
worker_nodes:
    ImageId: latest_dlami

setup_commands:
    - pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.1.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
    - git clone --branch master https://github.com/wuisawesome/ray.git || true
    - pushd ray; git reset --hard; popd;
    - ray/python/ray/setup-dev.py -y 
    - rm /home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py
    - ln -s /home/ubuntu/ray/python/ray/monitor.py /home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py


# Configure the cluster for very conservative auto-scaling otherwise.
target_utilization_fraction: 1.0
idle_timeout_minutes: 2

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu
```

**Comment by roireshef** [comment] 2020-12-16 00:44
Hi @wuisawesome Ive never used autoscaler since I'm running on premise. The repro is very simple and already detailed in the body of the original ticket https://github.com/ray-project/ray/issues/12543#issue-754650947

Have you tried running it with latest nightly build and master branch using the script provided and it worked for you??

**Comment by wuisawesome** [comment] 2020-12-16 00:51
Yeah, as you can see, my cluster yaml pulls the latest nightly wheel, and runs `setup-dev.py`. 

The one caveat is that if `setup-dev.py` doesn't symlink files in the module's top level directory, so if you're changing those, you need manually symlink them (see the `monitor.py` example).

**Comment by roireshef** [comment] 2020-12-16 00:57
I also tried linking monitor.py like you suggest in your yaml file. 
This is the result I'm getting:
```
Traceback (most recent call last):
  File "/home/kz430x/projects/uc_workspace/ultracruise/planning_research/src/full_lateral_merge_tune.py", line 164, in <module>
    max_failures=-1
  File "/home/kz430x/.local/lib/python3.6/site-packages/ray/tune/tune.py", line 358, in run
    callbacks, sync_config, loggers=loggers)
  File "/home/kz430x/.local/lib/python3.6/site-packages/ray/tune/utils/callback.py", line 89, in create_default_callbacks
    _sync_to_driver = detect_sync_to_driver(sync_config.sync_to_driver)
  File "/home/kz430x/.local/lib/python3.6/site-packages/ray/tune/syncer.py", line 457, in detect_sync_to_driver
    from ray.tune.integration.docker import DockerSyncer
  File "/home/kz430x/.local/lib/python3.6/site-packages/ray/tune/integration/docker.py", line 5, in <module>
    from ray.autoscaler.sdk import rsync, configure_logging
  File "/home/kz430x/.local/lib/python3.6/site-packages/ray/autoscaler/sdk.py", line 9, in <module>
    from ray.autoscaler._private import commands
  File "/home/kz430x/.local/lib/python3.6/site-packages/ray/autoscaler/_private/commands.py", line 25, in <module>
    from ray.autoscaler.node_provider import NodeProvider
  File "/home/kz430x/.local/lib/python3.6/site-packages/ray/autoscaler/node_provider.py", line 6, in <module>
    from ray.autoscaler._private.command_runner import \
  File "/home/kz430x/.local/lib/python3.6/site-packages/ray/autoscaler/_private/command_runner.py", line 15, in <module>
    from ray.autoscaler._private.constants import \
  File "/home/kz430x/.local/lib/python3.6/site-packages/ray/autoscaler/_private/constants.py", line 3, in <module>
    from ray.ray_constants import (  # noqa F401
ImportError: cannot import name 'DEFAULT_OBJECT_STORE_MEMORY_PROPORTION'
(pid=raylet) Traceback (most recent call last):
(pid=raylet)   File "/home/kz430x/.local/lib/python3.6/site-packages/ray/new_dashboard/agent.py", line 27, in <module>
(pid=raylet)     from ray.ray_logging import setup_component_logger
(pid=raylet) ModuleNotFoundError: No module named 'ray.ray_logging'
```

**Comment by wuisawesome** [comment] 2020-12-16 01:00
hmmm what commit is your nightly wheel? (`python -c "import ray; print(ray.__commit__)"`)

Also when was the last time you rebased/merged upstream/master into your branch?

**Comment by roireshef** [comment] 2020-12-16 01:32
> hmmm what commit is your nightly wheel? (`python -c "import ray; print(ray.__commit__)"`)

9527220a868fbd57aa7617fa9a5eacecd56602db

> Also when was the last time you rebased/merged upstream/master into your branch?

Just now.

**Comment by roireshef** [comment] 2020-12-16 01:37
I now see my ray build is on a commit from Nov 4, which is already outdated, and this issue might have already been fixed by now. Problem is, running `ray install-nightly` doesn't seem to update to the latest nightly wheel. What should I do to update?

**Comment by wuisawesome** [comment] 2020-12-16 01:39
Ah yes, `ray install-nightly` broke for 1 commit when we updated from manylinux1 to manylinux14. 

Can you try grabbing the latest nightly from the table here? https://docs.ray.io/en/master/installation.html#daily-releases-nightlies

Sorry about that :/

**Comment by roireshef** [comment] 2020-12-16 01:43
> Ah yes, `ray install-nightly` broke for 1 commit when we updated from manylinux1 to manylinux14.

It might be worth documenting that somewhere so other won't get stuck as well...

**Comment by roireshef** [comment] 2020-12-16 01:54
Yes, it works. Thanks @wuisawesome !

**Comment by wuisawesome** [comment] 2020-12-16 01:56
No problem! It seems like this was a one-off issue due to the manylinux upgrade, but let us know (or submit a PR) if you have any suggestions around improving the documentation for this :)

**Comment by roireshef** [comment] 2020-12-16 16:24
I'm reopening this, as `ray start` keeps crashing at startup with:
```
Some Ray subprcesses exited unexpectedly:
  dashboard [exit code=0]
```

And the dashboard temp log file shows:
```
2020-12-16 18:17:37,557	INFO head.py:49 -- Dashboard head grpc address: 10.66.64.193:35879
2020-12-16 18:17:37,557	INFO head.py:51 -- Dashboard head http address: localhost:6006
2020-12-16 18:17:37,561	WARNING dashboard.py:208 -- The dashboard on node ILHERLNCN2QWDVF failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/new_dashboard/dashboard.py", line 192, in <module>
    log_dir=args.log_dir)
  File "/usr/local/lib/python3.6/dist-packages/ray/new_dashboard/dashboard.py", line 81, in __init__
    build_dir = setup_static_dir()
  File "/usr/local/lib/python3.6/dist-packages/ray/new_dashboard/dashboard.py", line 45, in setup_static_dir
    "&& npm run build)", build_dir)
FileNotFoundError: [Errno 2] Dashboard build directory not found. If installing from source, please follow the additional steps required to build the dashboard(cd python/ray/new_dashboard/client && npm install && npm ci && npm run build): '/usr/local/lib/python3.6/dist-packages/ray/new_dashboard/client/build'
```

@wuisawesome any magic trick for that one?

**Comment by mfitton** [comment] 2020-12-16 18:33
Hey @roireshef to fix this, I think you'll need to run `cd /usr/local/lib/python3.6/dist-packages/ray/new_dashboard/client && npm ci && nom run build`. This is occurring because the `setup-dev.py` script sym links the dashboard code as well to allow for development on the dashboard without building entirely from source. That said, it requires the locally sym linked dashboard be built manually by the user.

**Comment by mfitton** [comment] 2020-12-16 18:34
Please let me know if you run into any difficulties running that command, and I'll help debug.

**Comment by roireshef** [comment] 2020-12-16 19:41
Hi @mfitton - I am running into difficulties with building locally, probably related to some npm dependencies. This is something I tried to avoid. I mean, the whole purpose of the `setup-dev.py` script is to avoid building any software locally, as it's using the Ray binaries, plus softlinking the python code. Why is the dashboard different?

**Comment by mfitton** [comment] 2020-12-16 20:05
I've always considered the setup-dev.py script to be a way to develop on the non-CPP non-ray-core part of the code without having to compile the C++ binary. It essentially takes all the non C++ parts of Ray and links them in place of those parts of Ray in a pre-built ray wheel.

To provide some justification for why it is this way--if it didn't symlink the dashboard, then you wouldn't be able to use this to develop on the dashboard, which is something we frequently do. Furthermore, the dashboard depends on the python code of Ray, less-so the C++ code of Ray, so if you changed the dashboard python code without changing the front-end running on the dashboard python code, there would likely be issues with the dashboard front-end not rendering. This makes it a little odd to link the built version of the dashboard to the C++ binary rather than to the Python code.

That said, you can comment out this line to prevent the dashboard being symlinked: https://github.com/ray-project/ray/blob/master/python/ray/setup-dev.py#L73

Maybe we can consider making the dashboard linking a flag to the setup-dev.py script. Thoughts @edoakes?

**Comment by mfitton** [comment] 2020-12-16 20:06
You can also copy the `client/build` directory from the ray wheel install to the `new_dashboard/client/build` directory of the code you're sym-linking.

**Comment by roireshef** [comment] 2020-12-16 20:33
@mfitton, I see. I think the cleaner solution would be to modify setup-dev.py to sym-link only the new_dashboard contents, excluding `client/build`, which as far as I see, comes with the ray wheel. This way running setup-dev.py will not require re-building the dashboard, as well as copying folders around, and you could still develop the python code of it.

**Comment by roireshef** [comment] 2020-12-16 20:35
A better, longer term solution, would be to take the client folder out of the python code's folder, because it doesn't belong there. This way you could easily sym-link the new_dashboard folder as a whole.

**Comment by mfitton** [comment] 2020-12-17 00:29
I frequently want to use the development version of the dashboard typescript code in addition to the development version of the dashboard javascript code, and want the shown dashboard UI to be the one built from the code on the branch I'm developing on, rather than the version included with the master branch. What if the setup.py script built the dashboard as part of its script?
That said, I can definitely see the argument that the client/build folder doesn't belong in the src directory at all, and that the typescript code itself could also live in a different directory. I still think some kind of switch in the setup-dev.py script would be ideal.

**Comment by wuisawesome** [comment] 2020-12-17 01:21
> What if the setup.py script built the dashboard as part of its script

Ideally we can do this via bazel though (which effectively makes it part of setup.py)

**Comment by mfitton** [comment] 2020-12-17 01:32
@wuisawesome can you expand upon that a little bit? I'm not super familiar with Bazel. Does this mean we define the dashboard build as a Bazel task and then can run that Bazel task (or not, depending on the flag) based on whether the flag is passed to setup-dev? Or am I way off base?

**Comment by wuisawesome** [comment] 2020-12-17 01:41
Yup, the rough idea would be to create a new bazel target, then add that to `ray_pkg`. @barakmich thoughts?

**Comment by roireshef** [comment] 2020-12-17 11:48
@mfitton @wuisawesome - Having to build any part of the software requires meeting dependencies and much move overhead than installing the binaries. The setup-dev.sh script is doing great job by avoiding that, and still, allow modifying the **python** code in a clean an concise way. I think it should relatively straightforward to move the `client/build` artifacts into a different folder than any of the ones `setup-dev.sh` sym-links to the local github repo. This way we still preserve the very convenient setup where one shouldn't be worried about building the software or meeting any dependencies that aren't covered already by the ray wheel.

**Comment by edoakes** [comment] 2020-12-17 22:29
Agree that this should just be part of the regular bazel build/setup.py workflow. Opened an issue tracking this improvement here:
https://github.com/ray-project/ray/issues/12956

Another to improve this error message:
https://github.com/ray-project/ray/issues/12956

**Closed by edoakes** 2020-12-17 22:29 UTC
Labels: P1, bug, core
