### ISSUE TITLE
[Bug] ValueError: ('Observation ({}) outside given space ({})!'

### ISSUE THREAD

**Issue by brodermind** [ray-project/ray#23527] opened 2022-03-28 08:52 UTC
### Search before asking

- [ ] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune, Ray Train, RLlib

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

rrlib's `preprocessor.py` line 62 gets stuck in the value error `ValueError: ('Observation ({}) outside given space ({})!`. But the observation is not outside the given space. 
**Observation**
```
ValueError: ('Observation ({}) outside given space ({})!', array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.68      , 0.71333333, 0.74666667, 0.78      , 0.81333333,
       0.84666667, 0.88      , 0.91333333, 0.94666667, 0.98      ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.68      , 0.71333333, 0.74666667, 0.78      , 0.81333333,
       0.84666667, 0.88      , 0.91333333, 0.94666667, 0.98      ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.68      , 0.71333333, 0.74666667, 0.78      , 0.81333333,
       0.84666667, 0.88      , 0.91333333, 0.94666667, 0.98      ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.68      , 0.71333333, 0.74666667, 0.78      , 0.81333333,
       0.84666667, 0.88      , 0.91333333, 0.94666667, 0.98      ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.27272727, 0.27272727, 0.27272727, 0.27272727, 0.27272727,
       0.27272727, 0.27272727, 0.27272727, 0.27272727, 0.27272727,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.18181818, 0.18181818, 0.18181818, 0.18181818, 0.18181818,
       0.18181818, 0.18181818, 0.18181818, 0.18181818, 0.18181818,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.54545455, 0.54545455, 0.54545455, 0.54545455, 0.54545455,
       0.54545455, 0.54545455, 0.54545455, 0.54545455, 0.54545455,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.63636364, 0.63636364, 0.63636364, 0.63636364, 0.63636364,
       0.63636364, 0.63636364, 0.63636364, 0.63636364, 0.63636364,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       2.        , 1.        , 2.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 2.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 2.        , 1.        , 2.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 2.        , 2.        , 2.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       2.        , 1.        , 2.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        ]), Box([0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], [3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.], (323,), float32))
```
**Space**
`Box(low=0., high=3, shape = 323, dtype=np.float32)`

### Versions / Dependencies

Ubuntu 18.04
Ray:1.3.0
python:3.8.5

### Reproduction script

 ```
def check_shape(self, observation: Any) -> None:                                       
        """Checks the shape of the given observation."""
        if self._i % OBS_VALIDATION_INTERVAL == 0:
            if type(observation) is list and isinstance(
                    self._obs_space, gym.spaces.Box):
                observation = np.array(observation)
            try:
                if not self._obs_space.contains(observation):
                    raise ValueError(
                        "Observation ({}) outside given space ({})!",
                        observation, self._obs_space)
            except AttributeError:
                raise ValueError(
                    "Observation for a Box/MultiBinary/MultiDiscrete space "
                    "should be an np.array, not a Python list.", observation)
        self._i += 1

```

### Anything else

I find the similar problem in #12940, but my  `observation` only has a float32  dtype, which means it doesn't a a float32 vs float64 problem. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by gjoliver** [comment] 2022-04-08 09:27
@avnishn can you help take a look?

**Comment by gjoliver** [comment] 2022-04-08 16:43
another report: https://github.com/ray-project/ray/issues/22429

**Comment by ArturNiederfahrenhorst** [comment] 2022-04-22 16:29
I tried to reproduce this with Python 3.8 on master and with [this script](https://gist.github.com/ArturNiederfahrenhorst/409825f6a8d9b5c8647d064348db8acd).
Can someone confirm that this should produce the issue?

**Comment by sven1977** [comment] 2022-04-22 16:41
@ArturNiederfahrenhorst , let me try ...

**Comment by sven1977** [comment] 2022-04-22 16:45
I can run your script, @ArturNiederfahrenhorst , but don't see the error on master (py 3.8) Everything runs ok.

**Comment by sven1977** [comment] 2022-04-22 16:47
Hey @brodermind , could you post a small, fully self-sufficient repro script? We seem to be unable to reproduce this.

Either way, we should probably invest some time into providing a much more specific error message in our env-checker when checking these large, complex dict/tuple spaces. As a user, I would like to know, which exact sub-key was failing and why (shape, dtype, or data range wrong?).

**Comment by sven1977** [comment] 2022-04-22 16:51
Hey @smita-09 , one of your values in your given observation (value=1.2) is definitely outside the range of your observation space, which has ranges from 0.0 to 1.0, only. This would be one reason, why you see this error. Try increasing your observation space's range or fix the observation outputs from your environment to fall into the [0.0, 1.0] range.

**Comment by atrejut** [comment] 2022-04-22 18:57
In my older report linked above as a duplicate (#22429) I did include a self-contained reproduction script -- I can't test against latest master right now though.

**Comment by sven1977** [comment] 2022-04-22 21:01
Don't you have to implement the `step()` method in TestEnv @atrejut ?

I'm getting:
```
ray::RolloutWorker.__init__() (pid=19149, ip=0.0.0.0, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f9e69413be0>)
(RolloutWorker pid=19149, ip=127.0.0.1)   File "/Users/sven/opt/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 499, in __init__
(RolloutWorker pid=19149, ip=127.0.0.1)     check_env(self.env)
(RolloutWorker pid=19149, ip=127.0.0.1)   File "/Users/sven/opt/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/utils/pre_checks/env.py", line 77, in check_env
(RolloutWorker pid=19149, ip=127.0.0.1)     raise ValueError(
(RolloutWorker pid=19149, ip=127.0.0.1) ValueError: Traceback (most recent call last):
(RolloutWorker pid=19149, ip=127.0.0.1)   File "/Users/sven/opt/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/utils/pre_checks/env.py", line 66, in check_env
(RolloutWorker pid=19149, ip=127.0.0.1)     check_gym_environments(env)
(RolloutWorker pid=19149, ip=127.0.0.1)   File "/Users/sven/opt/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/utils/pre_checks/env.py", line 174, in check_gym_environments
(RolloutWorker pid=19149, ip=127.0.0.1)     next_obs, reward, done, info = env.step(sampled_action)
(RolloutWorker pid=19149, ip=127.0.0.1)   File "/Users/sven/opt/anaconda3/envs/ray/lib/python3.8/site-packages/gym/core.py", line 58, in step
(RolloutWorker pid=19149, ip=127.0.0.1)     raise NotImplementedError
(RolloutWorker pid=19149, ip=127.0.0.1) NotImplementedError
```
when running your script on master, which makes sense as `step()` is not defined. ...

**Comment by atrejut** [comment] 2022-04-23 06:55
Hi @sven1977,

yes, step was not necessary for reproduction, I guess `ray` already tries to validate the observation it gets from a `reset`.

when I run the above snippet (`ray==1.10.0`, `gym==0.21.0`) I get

```
2022-04-23 08:51:08,557	INFO trainer.py:2054 -- Your framework setting is 'tf', meaning you are using static-graph mode. Set framework='tf2' to enable eager execution with tf2.x. You may also then want to set eager_tracing=True in order to reach similar execution speed as with static-graph mode.
2022-04-23 08:51:08,562	INFO ppo.py:249 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't work for you.
2022-04-23 08:51:08,563	INFO trainer.py:790 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(RolloutWorker pid=4901, ip=127.0.0.1) 2022-04-23 08:51:12,385	WARNING rollout_worker.py:1701 -- Validating sub-env at vector index=0 ... (NOT OK)
(RolloutWorker pid=4901, ip=127.0.0.1) 2022-04-23 08:51:12,388	ERROR worker.py:432 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=4901, ip=0.0.0.0)
(RolloutWorker pid=4901, ip=127.0.0.1)   File "/Users/XXX/miniconda3/envs/ray/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 464, in __init__
(RolloutWorker pid=4901, ip=127.0.0.1)     _validate_env(self.env, env_context=self.env_context)
(RolloutWorker pid=4901, ip=127.0.0.1)   File "/Users/XXX/miniconda3/envs/ray/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1702, in _validate_env
(RolloutWorker pid=4901, ip=127.0.0.1)     raise EnvError(
(RolloutWorker pid=4901, ip=127.0.0.1) ray.rllib.utils.error.EnvError: Env's `observation_space` Dict(action_mask:Box([0. 0. 0.], [1. 1. 1.], (3,), float32), observations:Box([0. 0. 0. 0. 0.], [10. 10. 10. 10. 10.], (5,), float32)) does not contain returned observation after a reset ({'action_mask': array([0., 0., 0.]), 'observations': array([0., 0., 0., 0., 0.])})!
(RolloutWorker pid=4900, ip=127.0.0.1) 2022-04-23 08:51:12,386	WARNING rollout_worker.py:1701 -- Validating sub-env at vector index=0 ... (NOT OK)
(RolloutWorker pid=4900, ip=127.0.0.1) 2022-04-23 08:51:12,388	ERROR worker.py:432 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=4900, ip=0.0.0.0)
(RolloutWorker pid=4900, ip=127.0.0.1)   File "/Users/XXX/miniconda3/envs/ray/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 464, in __init__
(RolloutWorker pid=4900, ip=127.0.0.1)     _validate_env(self.env, env_context=self.env_context)
(RolloutWorker pid=4900, ip=127.0.0.1)   File "/Users/XXX/miniconda3/envs/ray/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1702, in _validate_env
(RolloutWorker pid=4900, ip=127.0.0.1)     raise EnvError(
(RolloutWorker pid=4900, ip=127.0.0.1) ray.rllib.utils.error.EnvError: Env's `observation_space` Dict(action_mask:Box([0. 0. 0.], [1. 1. 1.], (3,), float32), observations:Box([0. 0. 0. 0. 0.], [10. 10. 10. 10. 10.], (5,), float32)) does not contain returned observation after a reset ({'action_mask': array([0., 0., 0.]), 'observations': array([0., 0., 0., 0., 0.])})!
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
~/miniconda3/envs/ray/lib/python3.9/site-packages/ray/rllib/agents/trainer.py in setup(self, config)
    810         try:
--> 811             self._init(self.config, self.env_creator)
    812         # New design: Override `Trainable.setup()` (as indented by Trainable)

~/miniconda3/envs/ray/lib/python3.9/site-packages/ray/rllib/agents/trainer.py in _init(self, config, env_creator)
    922               env_creator: Callable[[EnvContext], EnvType]) -> None:
--> 923         raise NotImplementedError
    924 

NotImplementedError: 

During handling of the above exception, another exception occurred:

RayActorError                             Traceback (most recent call last)
/var/folders/mc/tp4bg6ld1_38smzn0c6xpwmh0000gn/T/ipykernel_4872/1998306871.py in <module>
     28 })
     29 
---> 30 trainer = agents.ppo.PPOTrainer(env='TestEnv', config={})
     31 # -> results in ray.rllib.utils.error.EnvError:

~/miniconda3/envs/ray/lib/python3.9/site-packages/ray/rllib/agents/trainer.py in __init__(self, config, env, logger_creator, remote_checkpoint_dir, sync_function_tpl)
    726         self.evaluation_metrics = {}
    727 
--> 728         super().__init__(config, logger_creator, remote_checkpoint_dir,
    729                          sync_function_tpl)
    730 

~/miniconda3/envs/ray/lib/python3.9/site-packages/ray/tune/trainable.py in __init__(self, config, logger_creator, remote_checkpoint_dir, sync_function_tpl)
    120         start_time = time.time()
    121         self._local_ip = self.get_current_ip()
--> 122         self.setup(copy.deepcopy(self.config))
    123         setup_time = time.time() - start_time
    124         if setup_time > SETUP_TIME_THRESHOLD:

~/miniconda3/envs/ray/lib/python3.9/site-packages/ray/rllib/agents/trainer.py in setup(self, config)
    824             # This matches the behavior of using `build_trainer()`, which
    825             # should no longer be used.
--> 826             self.workers = self._make_workers(
    827                 env_creator=self.env_creator,
    828                 validate_env=self.validate_env,

~/miniconda3/envs/ray/lib/python3.9/site-packages/ray/rllib/agents/trainer.py in _make_workers(self, env_creator, validate_env, policy_class, config, num_workers, local_worker)
   1923             The created WorkerSet.
   1924         """
-> 1925         return WorkerSet(
   1926             env_creator=env_creator,
   1927             validate_env=validate_env,

~/miniconda3/envs/ray/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py in __init__(self, env_creator, validate_env, policy_class, trainer_config, num_workers, local_worker, logdir, _setup)
     98                     (not trainer_config.get("observation_space") or
     99                      not trainer_config.get("action_space")):
--> 100                 remote_spaces = ray.get(self.remote_workers(
    101                 )[0].foreach_policy.remote(
    102                     lambda p, pid: (pid, p.observation_space, p.action_space)))

~/miniconda3/envs/ray/lib/python3.9/site-packages/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
    103             if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104                 return getattr(ray, func.__name__)(*args, **kwargs)
--> 105         return func(*args, **kwargs)
    106 
    107     return wrapper

~/miniconda3/envs/ray/lib/python3.9/site-packages/ray/worker.py in get(object_refs, timeout)
   1733                     raise value.as_instanceof_cause()
   1734                 else:
-> 1735                     raise value
   1736 
   1737         if is_individual_id:

RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=4900, ip=0.0.0.0)
  File "/Users/XXX/miniconda3/envs/ray/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 464, in __init__
    _validate_env(self.env, env_context=self.env_context)
  File "/Users/XXX/miniconda3/envs/ray/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1702, in _validate_env
    raise EnvError(
ray.rllib.utils.error.EnvError: Env's `observation_space` Dict(action_mask:Box([0. 0. 0.], [1. 1. 1.], (3,), float32), observations:Box([0. 0. 0. 0. 0.], [10. 10. 10. 10. 10.], (5,), float32)) does not contain returned observation after a reset ({'action_mask': array([0., 0., 0.]), 'observations': array([0., 0., 0., 0., 0.])})!
```
Note that in my experiments also the gym version was relevant, not just the ray version.

**Comment by atrejut** [comment] 2022-04-23 07:04
just tried with `ray==1.12` and can **not** reproduce -- I get the same `NotImplementedError` as you got above.
Adding a very simple `step`-method the trainer seems to instantiate just fine -- so I guess as far as I'm concerned this has been fixed in `1.12`.

**Comment by brodermind** [comment] 2022-04-23 08:07
> Hey @brodermind , could you post a small, fully self-sufficient repro script? We seem to be unable to reproduce this.
> 
> Either way, we should probably invest some time into providing a much more specific error message in our env-checker when checking these large, complex dict/tuple spaces. As a user, I would like to know, which exact sub-key was failing and why (shape, dtype, or data range wrong?).

@sven1977 Hi, thank you for your reply, I have fixed my problem by degrading the ray version.

**Comment by sven1977** [comment] 2022-04-23 17:37
Awesome @atrejut . Thanks for letting us know.
@brodermind: I'm going to close this issue. Should this become a problem again, please feel free to re-open.

**Closed by sven1977** 2022-04-23 17:37 UTC
Labels: bug, needs-repro-script, P0, rllib, rllib-env, multiple-reports
