### ISSUE TITLE
Ray dependency on async_timeout

### ISSUE THREAD

**Issue by dss010101** [ray-project/ray#41318] opened 2023-11-21 22:44 UTC
### What happened + What you expected to happen

Recently  upgraded from python 3.11.5 to 3.11.6.   Now when im using ray,  i get an exception at on the following line:
```
            ray.init(ignore_reinit_error=True)
```

```
2023-11-21 17:01:38,062	ERROR services.py:1398 -- 
The last 20 lines of /tmp/ray/session_2023-11-21_17-01-33_209123_30712/logs/dashboard.log (it contains the error message from the dashboard): 
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ray/dashboard/utils.py", line 134, in get_all_modules
    raise e
  File "/usr/local/lib/python3.11/site-packages/ray/dashboard/utils.py", line 121, in get_all_modules
    importlib.import_module(name)
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/site-packages/ray/dashboard/modules/test/test_agent.py", line 6, in <module>
    import ray.dashboard.modules.test.test_utils as test_utils
  File "/usr/local/lib/python3.11/site-packages/ray/dashboard/modules/test/test_utils.py", line 3, in <module>
    import async_timeout
**ModuleNotFoundError: No module named 'async_timeout'**
2023-11-21 17:01:38,204	INFO worker.py:1673 -- Started a local Ray instance.
ERROR
```

Now i think i can solve this by pip installing aync_timeout - but i want to understand why this dependency is now cropping up when it wasnt before...is it new?

### Versions / Dependencies

**OS:**
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"

**Python Libs:**
aiohttp                    3.9.0
aiohttp-cors               0.7.0
aiosignal                  1.3.1
asn1crypto                 1.5.1
asttokens                  2.4.1
attrs                      23.1.0
bcrypt                     4.0.1
blessed                    1.20.0
blinker                    1.7.0
cachetools                 5.3.2
certifi                    2023.11.17
cffi                       1.16.0
charset-normalizer         3.3.2
click                      8.1.7
colorful                   0.5.5
comm                       0.2.0
cryptography               41.0.5
debugpy                    1.8.0
decorator                  5.1.1
defusedxml                 0.7.1
distlib                    0.3.7
et-xmlfile                 1.1.0
executing                  2.0.1
filelock                   3.13.1
Flask                      3.0.0
frozenlist                 1.4.0
gevent                     23.9.1
google-api-core            2.14.0
google-auth                2.23.4
googleapis-common-protos   1.61.0
gpustat                    1.1.1
greenlet                   3.0.1
grpcio                     1.59.3
gunicorn                   21.2.0
idna                       3.4
ipykernel                  6.27.0
ipython                    8.17.2
itsdangerous               2.1.2
jedi                       0.19.1
Jinja2                     3.1.2
jsonschema                 4.20.0
jsonschema-specifications  2023.11.1
jupyter_client             8.6.0
jupyter_core               5.5.0
lxml                       4.9.3
MarkupSafe                 2.1.3
matplotlib-inline          0.1.6
msgpack                    1.0.7
multidict                  6.0.4
nest-asyncio               1.5.8
numpy                      1.26.2
nvidia-ml-py               12.535.133
opencensus                 0.11.3
opencensus-context         0.1.3
openpyxl                   3.1.2
packaging                  23.2
pandas                     2.1.3
paramiko                   3.3.1
parso                      0.8.3
pexpect                    4.8.0
pip                        23.3.1
platformdirs               3.11.0
prometheus-client          0.19.0
prompt-toolkit             3.0.41
protobuf                   4.25.1
psutil                     5.9.6
ptyprocess                 0.7.0
pure-eval                  0.2.2
py-spy                     0.3.14
pyarrow                    14.0.1
pyasn1                     0.5.1
pyasn1-modules             0.3.0
pycparser                  2.21
pydantic                   1.10.13
Pygments                   2.17.1
PyJWT                      2.8.0
PyNaCl                     1.5.0
pyOpenSSL                  23.3.0
python-dateutil            2.8.2
pytz                       2023.3.post1
PyYAML                     6.0.1
pyzmq                      25.1.1
ray                        2.8.0
referencing                0.31.0
requests                   2.31.0
rpds-py                    0.13.1
rsa                        4.9
setuptools                 65.5.0
six                        1.16.0
smart-open                 6.4.0
snowflake-connector-python 3.5.0
sortedcontainers           2.4.0
stack-data                 0.6.3
tableauhyperapi            0.0.18161
tableauserverclient        0.28
tomlkit                    0.12.3
tornado                    6.3.3
traitlets                  5.13.0
typing_extensions          4.8.0
tzdata                     2023.3
urllib3                    2.0.6
virtualenv                 20.21.0
wcwidth                    0.2.11
Werkzeug                   3.0.1
yarl                       1.9.3
zope.event                 5.0
zope.interface             6.1

### Reproduction script

ray.init(ignore_reinit_error=True)

### Issue Severity

None

**Comment by jjyao** [comment] 2023-11-22 23:22
Possible it's a duplicate of #41267

**Comment by dss010101** [comment] 2023-11-23 06:32
> Possible it's a duplicate of #41267

does seem to be the case

**Comment by rickyyx** [comment] 2023-11-27 18:21
Closing as a duplicate of https://github.com/ray-project/ray/issues/41267

**Closed by rickyyx** 2023-11-27 18:21 UTC
Labels: bug, question, release-blocker, P0, dashboard, core, observability-ux
