### ISSUE TITLE
Connecting driver does not allow to set temp dir, uses default

### ISSUE THREAD

**Issue by vonHartz** [ray-project/ray#4726] opened 2019-05-01 08:57 UTC
This is somewhat related to #4593. 

It can be recreated by following these steps:
- Make the /tmp/ray folder be owned by some other user (as in #4593).
- Run `ray init --temp_directory SOMEFOLDER` in the command line.
- Open python and try to run connect to the just started ray cluster via ray.init(). 

Not providing the temp-dir as an argument in the last step will result in a permission error as the driver created in python will try to access the default tmp-dir:
> PermissionError: [Errno 13] Permission denied: '/tmp/ray/session

Providing it as an argument, will raise an exception:
> When connecting to an existing cluster, temp_dir must not be provided."

Below is the original comment by @RaghuSpaceRajan about this issue.

----------------------------------------------------------------------------------------
I think the intent is to have /tmp/ray writeable by everyone and its sub-directories with user-specific permissions. Is that right?

However, that still wouldn't solve the problem of non-head nodes not being allowed to have their own temp directories. Commenting out the following from worker.py should fix that:

```
        if temp_dir is not None:
            raise Exception("When connecting to an existing cluster, "
                            "temp_dir must not be provided.")

```
 Should that be a separate bug?

_Originally posted by @RaghuSpaceRajan in https://github.com/ray-project/ray/issues/4593#issuecomment-487594308_

**Comment by RaghuSpaceRajan** [comment] 2019-05-03 19:30
@robertnishihara Is the driver supposed to be started only on the head node?

**Comment by robertnishihara** [comment] 2019-05-04 17:58
I think the issue is that the driver is trying to create a new directory in the temp_directory, but it shouldn't be doing that.

See also https://github.com/ray-project/ray/pull/4605.

**Comment by robertnishihara** [comment] 2019-05-04 18:10
I think #4605 fixes this.

**Comment by robertnishihara** [comment] 2019-05-08 07:20
Closing because I think this has been fixed. Please reopen if it’s still an issue!

**Closed by robertnishihara** 2019-05-08 07:20 UTC

**Comment by drozzy** [comment] 2019-07-25 19:16
This still persists for me. I'm running `0.7.2`.
Might it have something to do with required minimum disk space?
