### ISSUE TITLE
Actors should call atexit before gracefully exiting

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#17967] opened 2021-08-19 21:31 UTC
### What is the problem?

Ray actors should run the atexit procedure before gracefully exiting. We should also document this behavior. 

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
import ray
import multiprocessing
import multiprocessing.managers
import sys
import time
​
​
class Server:
    def get(self):
        return 5
​
​
class Manager(multiprocessing.managers.BaseManager):
    pass
​
​
Manager.register(
    "Server",
    Server,
    exposed=("get",),
)
​
​
def set_proc_title(name: str):
    try:
        import setproctitle
​
        setproctitle.setproctitle(name)
    except ImportError:
        pass
​
​
class Actor:
    def start(self):
        manager = Manager()
        manager.start(set_proc_title, ("do i leak",))  # proc title to make it easier to identify
        self.server = manager.Server()
​
    def run(self):
        for _ in range(10):
            print(self.server.get())
            time.sleep(0.1)
​
​
def ray_main():
    ray.init()
    RemoteActor = ray.remote(Actor)
    a = RemoteActor.remote()
    ray.get(a.start.remote())
    ray.get(a.run.remote())
​
​
def main():
    a = Actor()
    a.start()
    a.run()
​
​
if __name__ == "__main__":
    if sys.argv[1] == "ray":
        ray_main()
    elif sys.argv[1] == "noray":
        main()
    else:
        assert False
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by hauntsaninja** [comment] 2021-09-14 20:52
If you're okay with an external dependency, running `pip install setproctitle` makes this easier to spot, since you can then run `ps aux | grep leak` to see the leaked process.

**Comment by zhe-thoughts** [comment] 2021-09-15 22:42
@ericl Assigning to you for now for further triaging

**Comment by ericl** [comment] 2021-09-20 18:47
Duplicate of https://github.com/ray-project/ray/issues/18700

**Closed by ericl** 2021-09-20 18:47 UTC
Labels: bug, P1
