### ISSUE TITLE
[CI] `linux://python/ray/tests:test_autoscaler` is failing/flaky on master.

### ISSUE THREAD

**Issue by anyscalesam** [ray-project/ray#41588] opened 2023-12-04 18:17 UTC
- 20c7607b8926316a003867fa46564f9fb2978f81 FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1907#018c32f4-52a9-44fa-af9c-62b8e2b453cd)
- 5d13766dd51df3f3e412dd2ee10aedc7988a5dc8 FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1904#018c27d3-e551-40fe-b32b-6918ba97ce58)
- b8f0fbb2b682200bec4296fb6f763eb85a2385e3 FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1902#018c26d4-825e-4ad0-bef8-53b45c4d36ee)
- bc096cbe309d99b38d27395a0c9c0ac05c67ea01 FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1899#018c260f-d66d-4795-a362-0e9ec6bc30c7)
- c61c95723b1c88748c444c55dd375672d5cc8bef FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1898#018c250b-2e6c-46e0-8070-9cfd788e097b)
- 7cd5c09a93bcf5cdcf6e1566603d4c7b26872424 FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1895#018c236f-6dc2-4a6b-8b2f-5b71b03b9d85)
- 32f3b23e699ffe2024409b5f2bf8614babfdee76 FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1887#018c2215-825a-4d35-9217-19ea4e5c650b)
- 42c8e0bd3c52fe9036a57dbba4b3bd9e3829075d FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1876#018c1eba-0633-4041-9076-559834ab2af0)
- 31260fb895bd44b30eecd03d80b7d727b168c9a2 FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1872#018c1dfd-40b8-4030-af31-4877273d717a)
- 24455c8710eaa3fc0958d9912646d62ffbd8d5fd FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1871#018c1df9-d4a9-4db9-b373-bcce0cb3fed1)
- f83749b75b33e267a755a04de1de3587626f10ec FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1870#018c1df4-4f75-4b47-8d59-d62d0b5e8bb9)
- c913358c1a85dc341e6abe5cce815d42ac11280c FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1868#018c1dbc-d6a4-480c-9c1a-d93cabbb80bc)
- 2a6c6ee032701e49bcebd1df1a400f70fddb0cc7 FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1856#018c1ac5-a885-4eec-ab8d-eb367316f482)
- ab1532c5790fd3efa6afbe156a71841cb0fa7a63 FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1848#018c1904-5817-476c-aec1-75730c8f0a63)
- e26bd755239d67d07c73c236c55da4e888f96aa5 FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1847#018c18a2-8023-47c7-a873-7d5c6b45ffb7)
- 339b1c8ccb51de1af12319be8b375e31b24861f8 FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1844#018c1868-d0ba-424c-9511-feb45f655a85)
- 48102d5f9f373834bb5680ca8f0f4ea94fa8d3dc FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1841#018c1800-6da1-48e9-8020-fa4ff8134674)
- 725c9f326be50dcf7e1f05962d542761218dbf71 FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1840#018c1800-27b5-4db5-9d64-2a10e824ea2c)
- 9e963338e4180742d2e0f02eac9141b25f1ca887 FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1830#018c1467-8701-4df7-9c98-c9eb274d8b84)
- 55ae63bc3219219bd69fa8fada036f47c37644b0 FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1824#018c12ef-2fc7-4d9c-afa5-45b019d7c8e2)
- 709101081fb7887cb35dcc89094fe86cac782efe FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1821#018c1277-b2d5-4b68-a00f-6b31ad898625)
- d98e7ff777322c9ea6cb9f4ba41aea841fb4e70c FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1815#018c11e4-0b0d-4dbe-a55e-19c7ba95b12e)
- d7b0ac21bebff0a459372f6efdae719425e310c4 FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1814#018c11d1-5e47-4326-bfc7-00a35f07ad77)
- d3ac31ec80691714c88dfd140b9383dae6d6645b FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1800#018bfd9b-4afd-4291-b2f2-c2934c5203a9)
- 53da874c375f1bd8b6af4f1b04c41d9d0f9ae499 FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1785#018bf833-9ec7-4f7a-b254-7c695ccbb5ab)
- 57f92bfd410564dc2b346b0e41539a05ea3b0fd3 FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1784#018bf808-80d5-4ceb-bffe-7f8488779c0e)
- 13e92d41d65d3ec879053c55147de9ef4c84d28b FAILED [Buildkite :serverless: serverless: flaky tests](https://buildkite.com/ray-project/postmerge/builds/1782#018bf7a3-15b2-4d00-9698-a5081345e660)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_autoscaler-END
....

**Comment by jjyao** [comment] 2023-12-04 22:11
Duplicate of #41186

**Closed by jjyao** 2023-12-04 22:11 UTC
Labels: release-blocker, P0, core, flaky-tracker
