### ISSUE TITLE
[dashboard] Dashboard errors (React)

### ISSUE THREAD

**Issue by 20zinnm** [ray-project/ray#8805] opened 2020-06-05 18:58 UTC
### What is the problem?

The dashboard appears for a split second before the window goes blank. The console shows many instances of this error:

```
react-dom.production.min.js:209 TypeError: Cannot read property 'total' of undefined
    at Errors.tsx:43
    at Qi (react-dom.production.min.js:153)
    at vl (react-dom.production.min.js:261)
    at cu (react-dom.production.min.js:246)
    at lu (react-dom.production.min.js:246)
    at Zl (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Uo (react-dom.production.min.js:122)
    at Ko (react-dom.production.min.js:123)
el @ react-dom.production.min.js:209
react-dom.production.min.js:209 TypeError: Cannot read property 'total' of undefined
    at Logs.tsx:42
    at Qi (react-dom.production.min.js:153)
    at vl (react-dom.production.min.js:261)
    at cu (react-dom.production.min.js:246)
    at lu (react-dom.production.min.js:246)
    at Zl (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Uo (react-dom.production.min.js:122)
    at Ko (react-dom.production.min.js:123)
el @ react-dom.production.min.js:209
```

I believe it is referring to [this line](https://github.com/ray-project/ray/blob/0fadc1143739f6edb5518dc2110bb795378c8c01/python/ray/dashboard/client/src/pages/dashboard/node-info/features/Logs.tsx#L42) in Logs.tsx and [this line](https://github.com/ray-project/ray/blob/0fadc1143739f6edb5518dc2110bb795378c8c01/python/ray/dashboard/client/src/pages/dashboard/node-info/features/Errors.tsx#L43) in Errors.tsx.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Latest nightly version of Ray, Python 3.7.7, on RedHat 7.

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
from collections import Counter
import os
import sys
import time
import ray

redis_password = sys.argv[1]
num_cpus = 56 * 2

ray.init(address=os.environ["ip_head"], redis_password=redis_password)

print("Nodes in the Ray cluster:")
print(ray.nodes())

@ray.remote
def f():
    time.sleep(120)
    return ray.services.get_node_ip_address()

# The following takes one second (assuming that ray was able to access all of the allocated nodes).
for i in range(60):
    start = time.time()
    ip_addresses = ray.get([f.remote() for _ in range(num_cpus)])
    print(Counter(ip_addresses))
    end = time.time()
    print(end - start)
```

(running on a SLURM cluster)

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by 20zinnm** [comment] 2020-06-05 20:44
I unfortunately do not know enough about React to be able to debug this.

**Comment by rkooo567** [comment] 2020-06-06 10:02
cc @mfitton

**Comment by 20zinnm** [comment] 2020-06-12 16:56
@mfitton I've verified that I encounter this issue with both Firefox and Chrome on Red Hat Enterprise Linux Server release 7.6 (Maipo) and Windows 10 Education 2004 (19041.329). I suspect the React code is just expecting an empty list of errors but for whatever reason the list is omitted instead.

**Comment by 20zinnm** [comment] 2020-07-03 17:57
This is still an issue on master (not stale).

**Comment by mfitton** [comment] 2020-07-10 00:35
@20zinnm sorry to have taken so long to get back to you on this. This is a known issue that is happening when a node is removed from a cluster. You can track resolution here: https://github.com/ray-project/ray/issues/9317

**Comment by mfitton** [comment] 2020-07-10 00:35
I'll be working on it next week.

**Comment by 20zinnm** [comment] 2020-07-10 00:37
@mfitton No worries.

I should note that this occurs for me even when no nodes have been removed. Simply starting up the cluster leads to this.

**Comment by edoakes** [comment] 2020-08-07 21:23
Duplicate of https://github.com/ray-project/ray/issues/9317

**Closed by edoakes** 2020-08-07 21:23 UTC
Labels: P1, bug, dashboard
