### ISSUE TITLE
[datasets] map_batches tf-model inference pickle error

### ISSUE THREAD

**Issue by vsriram23** [ray-project/ray#32524] opened 2023-02-14 07:37 UTC
### What happened + What you expected to happen

hi, 

when I try to use ray.data map function to perform data-processing on cpu and then map_batches to perform a tensorflow model-inference on gpu, I see this error:

  File "/usr/local/lib/python3.8/dist-packages/ray/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/usr/local/lib/python3.8/dist-packages/ray/cloudpickle/cloudpickle_fast.py", line 634, in dump
    raise pickle.PicklingError(msg) from e
_pickle.PicklingError: Could not pickle object as excessively deep recursion required.

I'm using csv-file which contains sample image-names and gt to load as ray-dataset.

### Versions / Dependencies

Ray 2.2.0

### Reproduction script
```
import ray
import os, glob
import numpy as np
import pandas as pd
import cv2
import tensorflow as tf

class nn_preprocess:

    def __init__(self,img_dir=None):
        self.mean = 127.5
        self.std = 1/127.5
        self.img_path = img_dir

    def __call__(self,df):
        file_name = df['file_name']
        file_gt = df['gt']
        #print(file_name)
        roi = cv2.imread(os.path.join(self.img_path,file_name))
        roi = (roi-self.mean)*self.std
        return roi

class tf_inference:
    def __init__(self,model_path=None):
        #self.path = model_path
        self.model = tf.keras.models.load_model(model_path)

    def __call__(self,roi):
        #pred = self.model(roi,training=False)
        pred = self.model.predict(roi)
        return pred

ds = ray.data.read_csv(csv_path)\
             .repartition(20)\
             .window(blocks_per_window=32)\
             .map(nn_preprocess(img_dir=img_dir))\
             .map_batches(tf_inference(model_path=model_path),compute="actors", num_gpus=1, batch_size=4)\
             .write_csv('predictions.csv')
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by amogkam** [comment] 2023-02-14 10:29
Hey @vsriram23, could you share the full stack trace you are seeing? I am not able to repro on my side, albeit with slight modifications since I don't have the CSV file you are using.

Also, for batch prediction, I would recommend using your built in `TensorflowPredictor` and `BatchPredictor` APIs: https://docs.ray.io/en/latest/ray-air/predictors.html

**Comment by amogkam** [comment] 2023-02-14 10:31
btw, a very easy test you can do is just manually run `cloudpickle` on the functions and arguments you are using in the `map_batches` calls:

```
cloudpickle.loads(cloudpickle.dumps(tf_inference))
cloudpickle.loads(cloudpickle.dumps(nn_preprocess))
```

**Comment by amogkam** [comment] 2023-02-14 10:35
or using Ray's built-in utility: https://docs.ray.io/en/latest/ray-core/objects/serialization.html#troubleshooting

**Comment by richardliaw** [comment] 2023-03-21 01:16
Unfortunately unable to reproduce, closing for now.

**Closed by richardliaw** 2023-03-21 01:16 UTC
Labels: bug, P2, @external-author-action-required, datasets
