### ISSUE TITLE
[rllib] torch.cuda.is_available() issue 

### ISSUE THREAD

**Issue by RodgerLuo** [ray-project/ray#11247] opened 2020-10-07 06:51 UTC
### What is the problem?

Ray version: 1.0

I've seen the following error during PBT trainings using pyTorch on GPUs. It seems it only happened after perturbations. The trails kept training after the errors, but I'm not sure if the clones were performed successfully.  

```
2020-10-07 01:52:54,579	ERROR worker.py:1018 -- Possible unhandled error from worker: ray::RolloutWorker.restore() (pid=75693, ip=10.55.144.214)
  File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 438, in ray._raylet.execute_task.function_executor
  File "/home/ubuntu/anaconda3/envs/ray-1.0/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 916, in restore
    objs = pickle.loads(objs)
  File "/home/ubuntu/anaconda3/envs/ray-1.0/lib/python3.6/site-packages/torch/storage.py", line 134, in _load_from_bytes
    return torch.load(io.BytesIO(b))
  File "/home/ubuntu/anaconda3/envs/ray-1.0/lib/python3.6/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/anaconda3/envs/ray-1.0/lib/python3.6/site-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
  File "/home/ubuntu/anaconda3/envs/ray-1.0/lib/python3.6/site-packages/torch/serialization.py", line 665, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/ubuntu/anaconda3/envs/ray-1.0/lib/python3.6/site-packages/torch/serialization.py", line 156, in default_restore_location
    result = fn(storage, location)
  File "/home/ubuntu/anaconda3/envs/ray-1.0/lib/python3.6/site-packages/torch/serialization.py", line 132, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/ubuntu/anaconda3/envs/ray-1.0/lib/python3.6/site-packages/torch/serialization.py", line 116, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

### Reproduction (REQUIRED)

This official script can reproduce the error if the `framework` is set to `torch`: [https://docs.ray.io/en/latest/tune/examples/pbt_ppo_example.html](https://docs.ray.io/en/latest/tune/examples/pbt_ppo_example.html)

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment] 2020-10-07 17:07
cc @sven1977 is this something you've seen before? This seems to be a GPU deserialization problem

**Comment by sven1977** [comment] 2020-10-09 07:14
No, I have never seen this before. Could we get a simple repro script for this so we can debug?

**Comment by RodgerLuo** [comment] 2020-10-09 18:05
I believe the code below will reproduce the error:

```
import random

import ray
from ray.tune import run, sample_from
from ray.tune.schedulers import PopulationBasedTraining

if __name__ == "__main__":

    # Postprocess the perturbed config to ensure it's still valid
    def explore(config):
        # ensure we collect enough timesteps to do sgd
        if config["train_batch_size"] < config["sgd_minibatch_size"] * 2:
            config["train_batch_size"] = config["sgd_minibatch_size"] * 2
        # ensure we run at least one sgd iter
        if config["num_sgd_iter"] < 1:
            config["num_sgd_iter"] = 1
        return config

    pbt = PopulationBasedTraining(
        time_attr="time_total_s",
        metric="episode_reward_mean",
        mode="max",
        perturbation_interval=120,
        resample_probability=0.25,
        # Specifies the mutations of these hyperparams
        hyperparam_mutations={
            "lambda": lambda: random.uniform(0.9, 1.0),
            "clip_param": lambda: random.uniform(0.01, 0.5),
            "lr": [1e-3, 5e-4, 1e-4, 5e-5, 1e-5],
            "num_sgd_iter": lambda: random.randint(1, 30),
            "sgd_minibatch_size": lambda: random.randint(128, 16384),
            "train_batch_size": lambda: random.randint(2000, 160000),
        },
        custom_explore_fn=explore)

    ray.init()
    run(
        "PPO",
        name="pbt_humanoid_test",
        scheduler=pbt,
        num_samples=8,
        config={
            "framework": "torch",
            "env": "CartPole-v0",
            "kl_coeff": 1.0,
            "num_workers": 8,
            "num_gpus": 1,
            "model": {
                "free_log_std": True
            },
            # These params are tuned from a fixed starting value.
            "lambda": 0.95,
            "clip_param": 0.2,
            "lr": 1e-4,
            # These params start off randomly drawn from a set.
            "num_sgd_iter": sample_from(
                lambda spec: random.choice([10, 20, 30])),
            "sgd_minibatch_size": sample_from(
                lambda spec: random.choice([128, 512, 2048])),
            "train_batch_size": sample_from(
                lambda spec: random.choice([10000, 20000, 40000]))
        })
```

**Comment by lasagnaphil** [comment] 2020-10-16 06:41
Have you tried out the latest Ray version? I had the same error message even with normal PPO before (when loading checkpoints), and the culprit was that torch optimizer objects weren't serialized properly. The pull request for the bugfix (#11208) was merged right around the time you made this issue, so you should maybe try out with a more recent build.

**Comment by janblumenkamp** [comment] 2020-11-23 23:15
This sounds like a duplicate of/related to #9181 #10175 #10491 #11071

**Closed** 2023-04-08 15:57 UTC
Labels: bug, needs-repro-script, P2, rllib
