### ISSUE TITLE
Example code doesn't work. ObjectRef doesn't translate to asyncio.Futures for Python versions after 3.10 due to asyncio API change (Issue on page /ray-core/actors/async_api.html)

### ISSUE THREAD

**Issue by zoeyzyhu** [ray-project/ray#40772] opened 2023-10-28 20:47 UTC
I was going through the User guide for actors on AsyncIO. In the section "ObjectRefs as asyncio.Futures", the example code did not work for **Python versions after 3.10**. It reported "AttributeError: 'ray._raylet.ObjectRef' object has no attribute 'add_done_callback'". 

This is probably due to changes in the "asyncio" package, following the link below, stating that "Changed in version 3.11: Passing coroutine objects to wait() directly is forbidden." 

https://docs.python.org/3/library/asyncio-task.html#asyncio.wait

**Comment by jjyao** [comment] 2024-02-26 22:36
Duplicate of https://github.com/ray-project/ray/issues/31606

**Closed by jjyao** 2024-02-26 22:36 UTC
Labels: triage, core
