### ISSUE TITLE
[RLllib] Failed to Restore the model with A3C + Atari Env(SpaceInvaders-v0)

### ISSUE THREAD

**Issue by heavenlxj** [ray-project/ray#16578] opened 2021-06-21 13:08 UTC
### What is the problem?
when i do the restore the trained model,  the error output as below:
```
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ray/tune/trainable.py", line 366, in restore
    self.load_checkpoint(checkpoint_path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 697, in load_checkpoint
    self.__setstate__(extra_data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 177, in __setstate__
    Trainer.__setstate__(self, state)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1235, in __setstate__
    self.workers.local_worker().restore(state["worker"])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1014, in restore
    self.policy_map[pid].set_state(state)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ray/rllib/policy/tf_policy.py", line 482, in set_state
    self._optimizer_variables.set_weights(optimizer_vars)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ray/experimental/tf_utils.py", line 191, in set_weights
    self.sess.run(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1164, in _run
    raise ValueError(
ValueError: Cannot feed value of shape (6, 1) for Tensor 'default_policy/Placeholder_default_policy/default_policy/value_out/kernel/Adam:0', which has shape '(256, 1)'
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
Environment:
ray                              1.2.0
tensorboard                      1.15.0
tensorboardX                     2.0
tensorflow-estimator             1.15.1
tensorflow-gpu                   1.15.3

Gym Env:
SpaceInvaders-v0

OS info:
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):
```
import ray.rllib.agents.a3c as a3c
import ray

ray.init(ignore_reinit_error=True)
config_mapper ={'env': 'SpaceInvaders-v0', 'config': {'num_workers': 1, 'env_config': {}, 'timesteps_per_iteration': 0, 'lr': 0.0001, 'rollout_fragment_length': 200, 'gamma': 0.99, 'train_batch_size': 200}}
agent = a3c.A3CTrainer(**config_mapper)

agent.restore(checkpoint_path='/Users/xjliu/Downloads/a3c-error-model/experiment/A3C_SpaceInvaders-v0_92c19_00000_0_2021-06-11_17-51-20/checkpoint_000002/checkpoint-2')
```

My model file upload failed:

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by heavenlxj** [comment] 2021-06-21 13:09
my model file could not be uploaded seems the file size is larger? 10.2MB

**Comment by krfricke** [comment] 2021-07-12 14:35
Hi @heavenlxj, I cannot reproduce this issue. Can you try upgrading Ray to the latest release (1.4.1)?

Script I used:

```
import ray.rllib.agents.a3c as a3c
import ray
from ray import tune


def restore(trainer_kwargs: dict, checkpoint_path: str):
    agent = a3c.A3CTrainer(**trainer_kwargs)

    agent.restore(
        checkpoint_path=checkpoint_path)


def train(trainer_kwargs: dict):
    config = trainer_kwargs["config"].copy()
    config["env"] = trainer_kwargs["env"]

    analysis = tune.run(
        "A3C",
        config=config,
        metric="episode_reward_mean",
        mode="max",
        stop={"training_iteration": 2},
        checkpoint_at_end=True,
        checkpoint_freq=1
    )
    return analysis.best_checkpoint


if __name__ == "__main__":
    ray.init(ignore_reinit_error=True)

    trainer_kwargs = {'env': 'SpaceInvaders-v0',
                      'config': {
                          'num_workers': 1,
                          'env_config': {},
                          'timesteps_per_iteration': 0,
                          'lr': 0.0001,
                          'rollout_fragment_length': 200,
                          'gamma': 0.99,
                          'train_batch_size': 200
                      }}

    checkpoint_path = train(trainer_kwargs)
    restore(trainer_kwargs, checkpoint_path)
```

Output:

```
== Status ==
Memory usage on this node: 10.7/16.0 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/16 CPUs, 0/0 GPUs, 0.0/5.2 GiB heap, 0.0/2.6 GiB objects (0.0/1.0 CPU_group_0_345bd3721bed9ad238e0624acab1cfb2, 0.0/1.0 CPU_group_1_345bd3721bed9ad238e0624acab1cfb2, 0.0/2.0 CPU_group_345bd3721bed9ad238e0624acab1cfb2)
Current best trial: 057c0_00000 with episode_reward_mean=315.0 and parameters={'num_workers': 1, 'num_envs_per_worker': 1, 'create_env_on_driver': False, 'rollout_fragment_length': 200, 'batch_mode': 'truncate_episodes', 'gamma': 0.99, 'lr': 0.0001, 'train_batch_size': 200, 'model': {'_use_default_native_models': False, 'fcnet_hiddens': [256, 256], 'fcnet_activation': 'tanh', 'conv_filters': None, 'conv_activation': 'relu', 'post_fcnet_hiddens': [], 'post_fcnet_activation': 'relu', 'free_log_std': False, 'no_final_linear': False, 'vf_share_layers': True, 'use_lstm': False, 'max_seq_len': 20, 'lstm_cell_size': 256, 'lstm_use_prev_action': False, 'lstm_use_prev_reward': False, '_time_major': False, 'use_attention': False, 'attention_num_transformer_units': 1, 'attention_dim': 64, 'attention_num_heads': 1, 'attention_head_dim': 32, 'attention_memory_inference': 50, 'attention_memory_training': 50, 'attention_position_wise_mlp_dim': 32, 'attention_init_gru_gate_bias': 2.0, 'attention_use_n_prev_actions': 0, 'attention_use_n_prev_rewards': 0, 'num_framestacks': 'auto', 'dim': 84, 'grayscale': False, 'zero_mean': True, 'custom_model': None, 'custom_model_config': {}, 'custom_action_dist': None, 'custom_preprocessor': None, 'lstm_use_prev_action_reward': -1, 'framestack': True}, 'optimizer': {}, 'horizon': None, 'soft_horizon': False, 'no_done_at_end': False, 'env': 'SpaceInvaders-v0', 'observation_space': None, 'action_space': None, 'env_config': {}, 'env_task_fn': None, 'render_env': False, 'record_env': False, 'clip_rewards': None, 'normalize_actions': True, 'clip_actions': False, 'preprocessor_pref': 'deepmind', 'log_level': 'WARN', 'callbacks': <class 'ray.rllib.agents.callbacks.DefaultCallbacks'>, 'ignore_worker_failures': False, 'log_sys_usage': True, 'fake_sampler': False, 'framework': 'tf', 'eager_tracing': False, 'explore': True, 'exploration_config': {'type': 'StochasticSampling'}, 'evaluation_interval': None, 'evaluation_num_episodes': 10, 'evaluation_parallel_to_training': False, 'in_evaluation': False, 'evaluation_config': {}, 'evaluation_num_workers': 0, 'custom_eval_function': None, 'sample_async': True, 'sample_collector': <class 'ray.rllib.evaluation.collectors.simple_list_collector.SimpleListCollector'>, 'observation_filter': 'NoFilter', 'synchronize_filters': True, 'tf_session_args': {'intra_op_parallelism_threads': 2, 'inter_op_parallelism_threads': 2, 'gpu_options': {'allow_growth': True}, 'log_device_placement': False, 'device_count': {'CPU': 1}, 'allow_soft_placement': True}, 'local_tf_session_args': {'intra_op_parallelism_threads': 8, 'inter_op_parallelism_threads': 8}, 'compress_observations': False, 'collect_metrics_timeout': 180, 'metrics_smoothing_episodes': 100, 'remote_worker_envs': False, 'remote_env_batch_wait_ms': 0, 'min_iter_time_s': 5, 'timesteps_per_iteration': 0, 'seed': None, 'extra_python_environs_for_driver': {}, 'extra_python_environs_for_worker': {}, 'num_gpus': 0, '_fake_gpus': False, 'num_cpus_per_worker': 1, 'num_gpus_per_worker': 0, 'custom_resources_per_worker': {}, 'num_cpus_for_driver': 1, 'placement_strategy': 'PACK', 'input': 'sampler', 'input_config': {}, 'actions_in_input_normalized': False, 'input_evaluation': ['is', 'wis'], 'postprocess_inputs': False, 'shuffle_buffer_size': 0, 'output': None, 'output_compress_columns': ['obs', 'new_obs'], 'output_max_file_size': 67108864, 'multiagent': {'policies': {}, 'policy_mapping_fn': None, 'policies_to_train': None, 'observation_fn': None, 'replay_mode': 'independent', 'count_steps_by': 'env_steps'}, 'logger_config': None, 'simple_optimizer': False, 'monitor': -1, 'use_critic': True, 'use_gae': True, 'lambda': 1.0, 'grad_clip': 40.0, 'lr_schedule': None, 'vf_loss_coeff': 0.5, 'entropy_coeff': 0.01}
Result logdir: /Users/kai/ray_results/A3C
Number of trials: 1/1 (1 TERMINATED)
+----------------------------------+------------+-------+--------+------------------+------+----------+----------------------+----------------------+--------------------+
| Trial name                       | status     | loc   |   iter |   total time (s) |   ts |   reward |   episode_reward_max |   episode_reward_min |   episode_len_mean |
|----------------------------------+------------+-------+--------+------------------+------+----------+----------------------+----------------------+--------------------|
| A3C_SpaceInvaders-v0_057c0_00000 | TERMINATED |       |      2 |          6.09313 | 3600 |      315 |                  395 |                  175 |               1168 |
+----------------------------------+------------+-------+--------+------------------+------+----------+----------------------+----------------------+--------------------+


2021-07-12 15:11:33,992	INFO tune.py:550 -- Total run time: 17.94 seconds (17.66 seconds for the tuning loop).
2021-07-12 15:11:34,189	INFO trainer.py:706 -- Tip: set framework=tfe or the --eager flag to enable TensorFlow eager execution
2021-07-12 15:11:34,189	INFO trainer.py:720 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
2021-07-12 15:11:40,647	WARNING util.py:55 -- Install gputil for GPU system monitoring.
2021-07-12 15:11:40,723	INFO trainable.py:383 -- Restored on 10.245.46.210 from checkpoint: /Users/kai/ray_results/A3C/A3C_SpaceInvaders-v0_057c0_00000_0_2021-07-12_15-11-16/checkpoint_000001/checkpoint-1
2021-07-12 15:11:40,723	INFO trainable.py:390 -- Current state after restoring: {'_iteration': 1, '_timesteps_total': None, '_time_total': 0.7183358669281006, '_episodes_total': 0}
```

**Comment by krfricke** [comment] 2021-09-23 13:18
Closing this for now, feel free to reopen with a repro script if the issue persists.

**Closed by krfricke** 2021-09-23 13:18 UTC
Labels: bug, needs-repro-script, P2, rllib
