### ISSUE TITLE
Autoscaler stopping nodes when updating cluster

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#14323] opened 2021-02-24 22:53 UTC
I have a fairly normal YAML (legacy yaml, if it matters). If you run "ray up" on the YAML, wait for the nodes to start, and then try "ray up" again to update the cluster, you'll see that the nodes are first stopped before "reused".

The nodes should not be stopped, this adds 1+ minutes to the cluster update.

```
cluster_name: default4
min_workers: 4
max_workers: 4
target_utilization_fraction: 0.5
autoscaling_mode: aggressive
idle_timeout_minutes: 1

provider:
    type: aws
    region: us-west-2
    availability_zone: us-west-2a,us-west-2b,us-west-2c
    cache_stopped_nodes: true
auth:
    ssh_user: ubuntu

head_node:
    InstanceType: i3.8xlarge
    ImageId: latest_dlami

    BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
              VolumeSize: 150


# Patterns for files to exclude when running rsync up or rsync down
rsync_exclude:
    - "**/.git"
    - "**/.git/**"

# Pattern files to use for filtering out files when running rsync up or rsync down. The file is searched for
# in the source directory and recursively through all subdirectories. For example, if .gitignore is provided
# as a value, the behavior will match git's behavior for finding and using .gitignore files.
rsync_filter:
    - ".gitignore"

worker_nodes:
    InstanceType: i3.8xlarge
    ImageId: latest_dlami
    BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
              VolumeSize: 150

setup_commands:
    - source activate pytorch_p36 && [ -e ~/ray ] || pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp36-cp36m-manylinux2014_x86_64.whl
    - sudo mkfs -t xfs /dev/nvme1n1 || true
    - sudo mkdir /data || true
    - sudo mount /dev/nvme1n1 /data || true
    - sudo chown ubuntu:ubuntu -R /data # ping
      #    - sudo rm -rf /tmp/ray || true
      #    - sudo ln -sf /data /tmp/ray || true

head_start_ray_commands:
    - source activate pytorch_p36 && ray stop
    - source activate pytorch_p36 && OMP_NUM_THREADS=1 ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --system-config='{"automatic_object_spilling_enabled":true,"max_io_workers":1,"object_spilling_config":"{\"type\":\"filesystem\",\"params\":{\"directory_path\":\"/data\"}}"}'


worker_start_ray_commands:
    - source activate pytorch_p36 && ray stop
    - source activate pytorch_p36 && OMP_NUM_THREADS=1 ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076
```

**Comment by AmeerHajAli** [comment] 2021-03-03 00:15
@ericl , I tried this on all commits, used git bisect, and with a lot of debugging I found the issue. 
The issue is that you used the cluster name "default4" :D. When I use "efihajghrsgh" for example it works.
God knows if this is because this is aliasing with other users who used "default4" in their cluster name :D.

**Comment by AmeerHajAli** [comment] 2021-03-03 00:16
Please reopen the issue if you think this is still happening if you change the cluster name.

**Comment by stephanie-wang** [comment] 2021-03-03 00:43
I can confirm that this issue is also happening for my yaml, where the cluster name is "ray".

Maybe the workaround is to rename the cluster and `ray up` again, but we should also just fix the issue.

**Comment by AmeerHajAli** [comment] 2021-03-03 00:46
@stephanie-wang , but I am not sure this is then a P0 or a regression in that case. I am not even sure it is an issue, this might be expected because we have 20 people using the same AWS account and if you use commonly used cluster names that other folks might use then this might happen right?

**Comment by stephanie-wang** [comment] 2021-03-03 00:47
This is on a personal AWS account, and there is for sure no name collision.

**Comment by AmeerHajAli** [comment] 2021-03-03 00:49
just to confirm, if you use a cluster name "ray9031" for example, and call `ray up` then `ray up` (without changing the cluster name in the middle) does it work for you?

**Comment by AmeerHajAli** [comment] 2021-03-03 01:06
I think the main reason we originally marked this as a P0 because we thought it is a regression, but if this is not a regression then it is just an issue where using some legacy cluster names will make workers take 30 seconds more to launch, this does not seem like a P0 to me.

**Comment by stephanie-wang** [comment] 2021-03-03 01:15
This issue was definitely happening before, but it appears to be working for me now on nightly, without needing a cluster name change.

**Closed by stephanie-wang** 2021-03-03 01:15 UTC
Labels: P1
