### ISSUE TITLE
[ci][release] many_tasks failed

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29324] opened 2022-10-13 17:59 UTC
### What happened + What you expected to happen

[Build failure ](https://buildkite.com/ray-project/release-tests-branch/builds/1108#0183cdac-cb1d-42b9-bffe-ec698fda9353)

[Cluster](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_jHSSbXD6zgBfZFSbAH1FSkLm?command-history-section=command_history)

### Versions / Dependencies

release 2.1 branch 

### Reproduction script

NA

**Comment by scv119** [comment] 2022-10-17 17:22
after some bisecting i'm 90% confident it's caused by #28418.

**Comment by scv119** [comment] 2022-10-17 17:23
here is the success runs on the previous commit of https://github.com/ray-project/ray/pull/28418. https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_xsV2ncB84hxXiEaFqdEtVUBY?command-history-section=command_history

**Comment by scv119** [comment] 2022-10-17 17:24
and failed runs: https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_yX3YPSTVkYAtNemir8jXduR1?command-history-section=command_history

**Comment by scv119** [comment] 2022-10-17 20:48
hmm the reverted wheels still have this issue. maybe the test is really flaky?

**Comment by rickyyx** [comment] 2022-10-17 21:03
I think @jiaodong believes there could be a simpler forward fix for this.

**Comment by jiaodong** [comment] 2022-10-17 22:21
so .. @scv119 is https://github.com/ray-project/ray/pull/28418 the culprit that you want me to dive deeper or it's due to flakiness ?

**Comment by scv119** [comment] 2022-10-17 22:41
let me spend a bit more time before invest your time in it.

**Comment by scv119** [comment] 2022-10-19 07:00
@jiaodong so i rerun both commits to 10 runs:

> here is the success runs on the previous commit of https://github.com/ray-project/ray/pull/28418. https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_xsV2ncB84hxXiEaFqdEtVUBY?command-history-section=command_history

passed 10 times

> and failed runs at https://github.com/ray-project/ray/pull/28418: https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_yX3YPSTVkYAtNemir8jXduR1?command-history-section=command_history

failed 10 times..

looks the regression caused by this PR is significant :(

**Comment by jiaodong** [comment] 2022-10-20 03:20
sigh, ok let me see what i can do to change imports then.

**Comment by rkooo567** [comment] 2022-10-20 07:12
I think we should handle this issue asap. @jiaodong I wonder

1. Were you able to figure out the root cause of slow down? Based on the history, this is highly likely due to importing some expensive modules & they are imported upon starting a new worker process.
2. If not, https://github.com/ray-project/ray/pull/27658 -> is this fix reasonable?

**Comment by jiaodong** [comment] 2022-10-20 16:51
@rkooo567 just got time back to this thread again -- 

1) The reason #28418 could relate to slowdown is because during diff reviews we wanted to unify conversion utils from ray.data to ray.air, however ray.air's import is tied to ray scheduling task level while data is not, thus surfaced a number of expensive imports previously only living in ray.data.
2)  Yep it is. Let me look into it and see if we can cherrypick.

**Comment by jiaodong** [comment] 2022-10-20 17:58
To make it easier to debug, on the good runs we're getting **20~60 iter/s** 

```
Ensuring all tasks have finished:  99%|█████████████████████████████████████████████████████████████▏| 9868/10000 [06:02<00:03, 37.44it/s]
Ensuring all tasks have finished:  99%|█████████████████████████████████████████████████████████████▍| 9902/10000 [06:02<00:01, 51.36it/s]
Ensuring all tasks have finished:  99%|█████████████████████████████████████████████████████████████▌| 9925/10000 [06:02<00:01, 59.71it/s]
Ensuring all tasks have finished:  99%|█████████████████████████████████████████████████████████████▋| 9945/10000 [06:04<00:01, 38.77it/s]
Ensuring all tasks have finished: 100%|█████████████████████████████████████████████████████████████▊| 9960/10000 [06:04<00:00, 41.89it/s]
Ensuring all tasks have finished: 100%|█████████████████████████████████████████████████████████████▊| 9972/10000 [06:05<00:01, 23.21it/s]
Ensuring all tasks have finished: 100%|█████████████████████████████████████████████████████████████▉| 9993/10000 [06:05<00:00, 31.42it/s]
Ensuring all tasks have finished: 100%|█████████████████████████████████████████████████████████████| 10000/10000 [06:06<00:00, 27.31it/s]
```

And from runs with regression we're getting **9~10 iter/s**

```
Waiting:  96%|████████████████████████████████████████████████████████████████████████████████████▍   | 2878/3000 [04:59<00:12,  9.68it/s]
Waiting:  96%|████████████████████████████████████████████████████████████████████████████████████▍   | 2879/3000 [04:59<00:12,  9.64it/s]
Waiting:  96%|████████████████████████████████████████████████████████████████████████████████████▍   | 2880/3000 [04:59<00:12,  9.65it/s]
Waiting:  96%|████████████████████████████████████████████████████████████████████████████████████▌   | 2881/3000 [04:59<00:12,  9.64it/s]
Waiting:  96%|████████████████████████████████████████████████████████████████████████████████████▌   | 2882/3000 [05:00<00:12,  9.60it/s]
```

**Comment by rickyyx** [comment] 2022-10-20 22:34
Also, looks like the task regression shows up in other task related benchmark as well: https://github.com/ray-project/ray/pull/29529/files#r1001181635

Will see how this looks up after the linked PR is merged.

**Comment by jiaodong** [comment] 2022-10-21 05:23
So I manually verified failed runs # of cpus used, where threshold for passing is 2500 * 0.7 = 1750 / 4096 CPUs used.

Before
```
AssertionError: Only 1664.25/4096.0 cpus used.
AssertionError: Only 1670.25/4096.0 cpus used.
AssertionError: Only 1696.25/4096.0 cpus used.
AssertionError: Only 1693.25/4096.0 cpus used.
AssertionError: Only 1695.75/4096.0 cpus used.
AssertionError: Only 1730.25/4096.0 cpus used.
AssertionError: Only 1698.0/4096.0 cpus used.
AssertionError: Only 1707.0/4096.0 cpus used.
AssertionError: Only 1700.75/4096.0 cpus used.
AssertionError: Only 1720.25/4096.0 cpus used.
``` 

After ([cluster link](https://console.anyscale.com/o/anyscale-internal/clusters/ses_KvP3hCm9DG1Aq4JEg7vUUAS2?command-history-section=command_history)) with #29517

```
AssertionError: Only 1742.0/4096.0 cpus used.
AssertionError: Only 1712.75/4096.0 cpus used.
3rd run succeeded.

```

**Comment by rkooo567** [comment] 2022-10-21 06:29
The suggestion sounds reasonable to me! Can you also run 5~10 times for this new run and see how many times it fails?

**Comment by matthewdeng** [comment] 2022-10-21 15:50
@jiaodong what was the number of CPUs _before_ the numpy narrow waist change? It looks like after making the fix we're still under the 1750 threshold? Was it consistently over 1750 before?

**Comment by jiaodong** [comment] 2022-10-21 16:02
@matthewdeng we don't print CPUs used for passing tests so we won't know for sure, all data points i got from Chen was it mostly passes before numpy commit but can also fail due to flakiness.

The metrics shown above didn't include last inline numpy commit yet but gives promising signals for passing test. With last commit of inlining numpy, https://github.com/ray-project/ray/pull/28418 didn't add any new eager import to `ray.data` anymore and can be removed from critical path of `many_tasks` failure.

**Comment by rickyyx** [comment] 2022-10-21 16:35
Thanks so much Jiao for looking into this! Let me also get some microbenchmark numbers with #29517 .

**Comment by rkooo567** [comment] 2022-10-22 14:09
We merged the PR. @rickyyx can you cherry pick the issue, run final tests, and close the issue?

**Comment by rickyyx** [comment] 2022-10-24 06:38
Cherry-picked. Running tests here: https://buildkite.com/ray-project/release-tests-branch/builds/1148

**Closed** 2022-10-24 20:07 UTC
Labels: bug, release-blocker, triage, r2.1-failure
