### ISSUE TITLE
Resnet example with GPU crashes

### ISSUE THREAD

**Issue by xc9** [ray-project/ray#916] opened 2017-09-02 18:00 UTC
Running the resnet example locally on a g2.2xlarge EC2 instance with the following options:
python ray/examples/resnet/resnet_main.py     
--eval_dir=/tmp/resnet-model/eval     
--train_data_path=cifar-10-batches-bin/data_batch*    
 --eval_data_path=cifar-10-batches-bin/test_batch.bin     
--dataset=cifar10     
--num_gpus=1

produces the following output:

I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Waiting for redis server at 127.0.0.1:57431 to respond...
Waiting for redis server at 127.0.0.1:43581 to respond...
Starting local scheduler with 8 CPUs, 1 GPUs
View the web UI at http://localhost:8890/notebooks/ray_ui80356.ipynb
The log files for tensorboard are stored at ip 172.31.2.122.
Starting training loop. Use Ctrl-C to exit.
Traceback (most recent call last):
  File "ray/examples/resnet/resnet_main.py", line 248, in <module>
    train()
  File "ray/examples/resnet/resnet_main.py", line 231, in train
    for actor in train_actors])
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 1983, in get
    raise RayGetError(object_ids[i], value)
ray.worker.RayGetError: Could not get objectid ObjectID(819d1c29782d0330f0bae9b966c4fa4f7909c849). It was created by remote function compute_steps which failed with:

Remote function compute_steps failed with:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 732, in _process_task
    self.actors[task.actor_id().id()], *arguments)
  File "ray/examples/resnet/resnet_main.py", line 113, in compute_steps
    self.model.variables.sess.run(self.model.train_op)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
OutOfRangeError: FIFOQueue '_1_fifo_queue' is closed and has insufficient elements (requested 128, current size 0)
	 [[Node: fifo_queue_DequeueMany = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](fifo_queue, fifo_queue_DequeueMany/n/_2345)]]
	 [[Node: fifo_queue_DequeueMany/_2349 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_5921_fifo_queue_DequeueMany", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'fifo_queue_DequeueMany', defined at:
  File "/usr/local/lib/python2.7/dist-packages/ray/workers/default_worker.py", line 105, in <module>
    ray.worker.global_worker.main_loop()
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 880, in main_loop
    self._wait_for_and_process_task(task)
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 833, in _wait_for_and_process_task
    self._process_task(task)
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 732, in _process_task
    self.actors[task.actor_id().id()], *arguments)
  File "ray/examples/resnet/resnet_main.py", line 96, in __init__
    False)
  File "/home/ubuntu/ray/examples/resnet/cifar_input.py", line 105, in build_input
    images, labels = example_queue.dequeue_many(batch_size)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 458, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1310, in _queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): FIFOQueue '_1_fifo_queue' is closed and has insufficient elements (requested 128, current size 0)
	 [[Node: fifo_queue_DequeueMany = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](fifo_queue, fifo_queue_DequeueMany/n/_2345)]]
	 [[Node: fifo_queue_DequeueMany/_2349 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_5921_fifo_queue_DequeueMany", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Remote function compute_steps failed with:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 732, in _process_task
    self.actors[task.actor_id().id()], *arguments)
  File "ray/examples/resnet/resnet_main.py", line 113, in compute_steps
    self.model.variables.sess.run(self.model.train_op)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
OutOfRangeError: FIFOQueue '_1_fifo_queue' is closed and has insufficient elements (requested 128, current size 0)
	 [[Node: fifo_queue_DequeueMany = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](fifo_queue, fifo_queue_DequeueMany/n/_2345)]]
	 [[Node: fifo_queue_DequeueMany/_2349 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_5921_fifo_queue_DequeueMany", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'fifo_queue_DequeueMany', defined at:
  File "/usr/local/lib/python2.7/dist-packages/ray/workers/default_worker.py", line 105, in <module>
    ray.worker.global_worker.main_loop()
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 880, in main_loop
    self._wait_for_and_process_task(task)
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 833, in _wait_for_and_process_task
    self._process_task(task)
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 732, in _process_task
    self.actors[task.actor_id().id()], *arguments)
  File "ray/examples/resnet/resnet_main.py", line 96, in __init__
    False)
  File "/home/ubuntu/ray/examples/resnet/cifar_input.py", line 105, in build_input
    images, labels = example_queue.dequeue_many(batch_size)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 458, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1310, in _queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): FIFOQueue '_1_fifo_queue' is closed and has insufficient elements (requested 128, current size 0)
	 [[Node: fifo_queue_DequeueMany = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](fifo_queue, fifo_queue_DequeueMany/n/_2345)]]
	 [[Node: fifo_queue_DequeueMany/_2349 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_5921_fifo_queue_DequeueMany", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:57431")
  
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ray/workers/default_worker.py", line 105, in <module>
    ray.worker.global_worker.main_loop()
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 880, in main_loop
    self._wait_for_and_process_task(task)
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 836, in _wait_for_and_process_task
    flush_log()
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 1949, in flush_log
    worker.local_scheduler_client.log_event(event_log_key,
AttributeError: 'Worker' object has no attribute 'local_scheduler_client'

  This error is unexpected and should not have happened. Somehow a worker
  crashed in an unanticipated way causing the main_loop to throw an exception,
  which is being caught in "python/ray/workers/default_worker.py".
  

  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:57431")
  
[1]+  Terminated              python ray/examples/resnet/resnet_main.py --eval_dir=/tmp/resnet-model/eval --train_data_path=cifar-10-batches-bin/data_batch* --eval_data_path=cifar-10-batches-bin/test_batch.bin --dataset=cifar10 --num_gpus=0 &> output.txt

**Comment by xc9** [comment] 2017-09-02 18:05
Running this without gpu seems to work fine.

**Comment by robertnishihara** [comment] 2017-09-02 19:32
Interesting, it looks like this may be the same issue as #446. @Wapaul1 @pcmoritz do you have any ideas about this? It's easily reproducible.

**Comment by maxim28** [comment] 2017-09-06 11:31
Same problem with same error

**Comment by robertnishihara** [comment] 2017-09-06 22:50
@xc9 @maxim28, can you share some details so we can reproduce the problem? What versions os TensorFlow, CUDA, cuDNN are you using? Which OS and Python version? What type of GPU? Is this on EC2? If so, which instance type? Any other important details about your setup?

If it's on EC2, perhaps you could share an AMI where we can reproduce the problem.

We're thinking of fixing this by replacing the queues with the TensorFlow Dataset API https://www.tensorflow.org/versions/r1.3/programmers_guide/datasets.

**Comment by robertnishihara** [comment] 2017-09-13 05:37
@xc9 @maxim28, want to see if #971 fixes the problem?

Note that a more comprehensive rewrite of this example is in the pipeline in #960.

**Comment by robertnishihara** [comment] 2017-09-20 21:14
This issue should also be fixed by #960. Please reopen if you continue to see this issue.

**Closed** 2017-09-20 21:14 UTC
