### ISSUE TITLE
Ray dashboard is broken in latest dev code

### ISSUE THREAD

**Issue by manishagarwal23** [ray-project/ray#11427] opened 2020-10-16 05:46 UTC
pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.1.0.dev0-cp36-cp36m-manylinux1_x86_64.whl

I am unable to see dashboard properly on launching . 

![jsonerr](https://user-images.githubusercontent.com/6428619/96217799-fc7a7580-0fa0-11eb-9f1f-00f0d76edbef.JPG)

Workaround is to submit a job first . Then the dashboard is visible else you get the bellow stack 

I get following stack in dashboard.err 

```
Error handling request
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/opt/app-root/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/opt/app-root/lib/python3.6/site-packages/ray/dashboard/dashboard.py", line 264, in raylet_info
    result = self.dashboard_controller.get_raylet_info()
  File "/opt/app-root/lib/python3.6/site-packages/ray/dashboard/dashboard.py", line 158, in get_raylet_info
    return self._construct_raylet_info()
  File "/opt/app-root/lib/python3.6/site-packages/ray/dashboard/dashboard.py", line 96, in _construct_raylet_info
    workers_info_by_node, infeasible_tasks, ready_tasks)
  File "/opt/app-root/lib/python3.6/site-packages/ray/dashboard/node_stats.py", line 162, in get_actors
    for worker_info in workers_info:
TypeError: 'NoneType' object is not iterable
```
Error handling request
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/opt/app-root/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/opt/app-root/lib/python3.6/site-packages/ray/dashboard/dashboard.py", line 264, in raylet_info
    result = self.dashboard_controller.get_raylet_info()
  File "/opt/app-root/lib/python3.6/site-packages/ray/dashboard/dashboard.py", line 158, in get_raylet_info
    return self._construct_raylet_info()
  File "/opt/app-root/lib/python3.6/site-packages/ray/dashboard/dashboard.py", line 96, in _construct_raylet_info
    workers_info_by_node, infeasible_tasks, ready_tasks)
  File "/opt/app-root/lib/python3.6/site-packages/ray/dashboard/node_stats.py", line 162, in get_actors
    for worker_info in workers_info:
TypeError: 'NoneType' object is not iterable

**Comment by rkooo567** [comment] 2020-10-16 23:42
cc @mfitton

**Comment by mfitton** [comment] 2020-10-18 20:57
Duplicate of https://github.com/ray-project/ray/issues/11384

**Closed by mfitton** 2020-10-18 20:57 UTC
Labels: bug, triage

**Comment by manishagarwal23** [comment] 2020-10-19 05:31
@mfitoon . For me  dashboard is still not up after 2 days . The bug #11384  sort of  says  after   you need to wait till all systems are up .

**Comment by mfitton** [comment] 2020-10-19 14:59
The issue in both cases is the same root cause I believe @manishagarwal23 which is that the page does not render correctly if there are no workers. This error will be fixed in the next release of the dashboard, which branch cut is scheduled for Wednesday.
