### ISSUE TITLE
[CI] `osx://python/ray/tests:test_gcs_utils` is failing/flaky on master.

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#30268] opened 2022-11-14 22:57 UTC
- f67bf50996317d2dabc93d88b8577c5971a6889f FAILED [Buildkite :mac: :apple: Medium A-J](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1039#01847200-3f22-44cb-a1f5-3bf11e387cd7)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-osx://python/ray/tests:test_gcs_utils-END
....

**Comment by clarng** [comment] 2022-11-14 22:58
@iycheng  

looks like the test is failing with pull based ,do we still need it?

https://buildkite.com/ray-project/oss-ci-build-branch/builds/1039#01847200-3f22-44cb-a1f5-3bf11e387cd7

**Comment by iycheng** [comment] 2023-01-14 20:57
Close this given that it's not flakey after switching to push based.
(flakey dashboard somehow don't have this data and I manually check 10 commits and confirmed that it's not flakey)

@clarng  we still need this since this now is based on push based.

Close it for now. Feel free to reopen.

**Closed by iycheng** 2023-01-14 20:57 UTC
Labels: P0, flaky-tracker
