### ISSUE TITLE
[Ray Core] failed to serialize namedtuple in py3.9

### ISSUE THREAD

**Issue by auderson** [ray-project/ray#25951] opened 2022-06-21 02:31 UTC
### What happened + What you expected to happen

ray failed to serialize namedtuple in py3.9, which looks like a error from cloudpickle:
https://github.com/cloudpipe/cloudpickle/issues/460

### Versions / Dependencies

python 3.9.7
ray 1.13.0

not tested with other versions

### Reproduction script

```python
from typing import NamedTuple
import ray
ray.init()

class T(NamedTuple):
    a:str
    
@ray.remote
def test():
    return T('a')

ray.get(test.remote())
```

```
Traceback (most recent call last):
  File "/home/auderson/miniconda3/envs/py3.9/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3361, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-7f1d37acd5e0>", line 1, in <cell line: 1>
    ray.get(test.remote())
  File "/home/auderson/miniconda3/envs/py3.9/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/auderson/miniconda3/envs/py3.9/lib/python3.9/site-packages/ray/worker.py", line 1831, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::test() (pid=353630, ip=...)
RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:
ray::test() (pid=353630, ip=...)
  File "/home/auderson/miniconda3/envs/py3.9/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle.py", line 872, in _make_skeleton_class
    skeleton_class = types.new_class(
  File "/home/auderson/miniconda3/envs/py3.9/lib/python3.9/types.py", line 77, in new_class
    return meta(name, resolved_bases, ns, **kwds)
  File "/home/auderson/miniconda3/envs/py3.9/lib/python3.9/typing.py", line 1852, in __new__
    module=ns['__module__'])
KeyError: '__module__'
```

```python
ray.util.inspect_serializability(T)
```
```
================================================
Checking Serializability of <class '__main__.T'>
================================================
Out[9]: (True, set())
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by tupui** [comment] 2022-06-21 10:58
Hi @auderson, thank you for reporting. As you found out, this is not an issue with ray but with cloudpickle. I am afraid there is not much to be done here. Did you try what they suggested in the issue with moving the class in its module?

Out of curiosity, why not using a dataclass or `collections.namedtuple`.

**Comment by auderson** [comment] 2022-06-21 11:10
I don’t know the implementation detail of serialization in ray. Because ray.util.inspect_serializability reports True, so I think maybe I should report this in case there are other potential bugs.
For your last question, using typing.NamedTuple is just my personal preference.

**Comment by scv119** [comment] 2022-06-24 02:14
@suquark is this something we documented or plan to fix?

**Comment by rkooo567** [comment] 2022-07-08 18:21
@scv119 @iycheng  can you guys make sure @suquark follow up on this (or find another owner? )

**Comment by suquark** [comment] 2022-07-12 23:48
@auderson Yes, this is indeed an error from cloudpickle. Currently a workaround is to move 

```
class T(NamedTuple):
    a:str
```

to another python module and import it.

@rkooo567 @scv119 I think we should wait for the upstream (cloudpickle) to fix it if this is not a major blocker.

**Comment by rkooo567** [comment] 2022-07-21 22:54
@suquark do you happen to know if cloudpickle is aware of this issue and plan to fix it?

**Comment by suquark** [comment] 2022-07-25 03:41
@rkooo567 yes, cloudpickle is aware of this in https://github.com/cloudpipe/cloudpickle/issues/460. But I am not sure when it is going to be fixed in the upstream.

**Comment by hora-anyscale** [comment] 2022-10-25 00:02
Per Triage Sync: Dependent on upstream - https://github.com/cloudpipe/cloudpickle/issues/460

**Comment by VenomPaco** [comment] 2023-04-26 12:09
Looks like cloudpickle fixed this issue (v2.2.1).

**Comment by rkooo567** [comment] 2023-04-26 13:19
Nice. We are using the custom fork of the cloud pickle. We may need to update the version..

**Comment by rkooo567** [comment] 2023-04-26 13:19
@suquark curious if you have bandwidth for the backport cloudpickle?

**Comment by rickyyx** [comment] 2024-01-26 03:55
no longer reproducible.

**Comment by moriyoshi** [comment] 2024-01-28 05:37
It's still reproducing. The bundled version of cloudpickle didn't catch up with the upstream version the problem was fixed in.

* Here: https://github.com/ray-project/ray/blob/master/python/ray/cloudpickle/cloudpickle_fast.py#L130-L131
* Upstream: https://github.com/cloudpipe/cloudpickle/pull/495/files#diff-3a0a886a228997d065d615f2f5860bb94e616656b634c433a416f234470ad9e3L114

**Comment by rkooo567** [comment] 2024-01-31 07:03
@rickyyx is it possible your newest changes also fix this issue?

**Comment by rkooo567** [comment] 2024-01-31 07:03
@moriyoshi we are bringing the upstream changes to the latest ray now

**Comment by rickyyx** [comment] 2024-01-31 07:04
Oh - i actually ran the repro on the current ray master and wasn't able to repro it.

**Closed** 2024-02-01 17:33 UTC
Labels: bug, P2, core
