### ISSUE TITLE
[tune] ASHA terminated trials but does not start new ones despite of available GPUs.

### ISSUE THREAD

**Issue by anhnht3** [ray-project/ray#17939] opened 2021-08-18 23:34 UTC
I am using the latest RayTune to do hyperparameter optimization. Each trial is allocated a few CPUs and 1 GPU. When first started, Tune will utilize all GPUs. However, once a trial is terminated by ASHA, new trials woud not be started even though some GPUs are now free. 

I've looked at the issues here and it seems to be something about Placementgroup and Autoscaler. Any pointer how should I address this problem?

**Comment by richardliaw** [comment] 2021-08-19 01:26
@anhnht3 this seems to be a problem that is recurring. Do you have a small simple script and some information about your cluster that I can use to reproduce?

**Comment by anhnht3** [comment] 2021-08-19 14:41
@richardliaw My code is messy and proprietary so I cannot share. There is no message, no warning except:

`DEBUG serialization.py:20 -- Unable to encode. Falling back to cloudpickle`.

I will try to create a simple script later when I have time.

**Comment by anhnht3** [comment] 2021-08-19 14:58
It seems that there is something that blocks the next trial. 

```
2021-08-19 14:55:46,162 DEBUG trial_executor.py:62 -- Trial trainable_81c5f662: Saving trial metadata.
2021-08-19 14:55:46,162 DEBUG trial_executor.py:45 -- Trial trainable_81c5f662: Changing status from RUNNING to TERMINATED.
2021-08-19 14:55:46,162 DEBUG trial_executor.py:62 -- Trial trainable_81c5f662: Saving trial metadata.
2021-08-19 14:55:46,162 DEBUG ray_trial_executor.py:489 -- Trial trainable_81c5f662: Destroying actor.
2021-08-19 14:55:46,162 DEBUG ray_trial_executor.py:551 -- Trial trainable_81c5f662: Returning resources.
2021-08-19 14:55:46,163 DEBUG search_generator.py:93 -- creating trial
2021-08-19 14:55:46,170 INFO trial_runner.py:1098 -- Blocking for next trial...
2021-08-19 14:55:46,170 DEBUG search_generator.py:93 -- creating trial
2021-08-19 14:55:47,178 INFO trial_runner.py:1098 -- Blocking for next trial...
2021-08-19 14:55:47,178 DEBUG search_generator.py:93 -- creating trial
2021-08-19 14:55:48,193 INFO trial_runner.py:1098 -- Blocking for next trial...
2021-08-19 14:55:48,193 DEBUG search_generator.py:93 -- creating trial
2021-08-19 14:55:49,206 INFO trial_runner.py:1098 -- Blocking for next trial...
2021-08-19 14:55:49,206 DEBUG search_generator.py:93 -- creating trial
2021-08-19 14:55:50,219 INFO trial_runner.py:1098 -- Blocking for next trial...
2021-08-19 14:55:50,220 DEBUG search_generator.py:93 -- creating trial
```

**Comment by anhnht3** [comment] 2021-08-19 21:06
I found the culprit. It was BlendSearch who blocked new trials, I changed to different Searcher and everything is good.

**Comment by krfricke** [comment] 2021-08-20 15:53
Hi @anhnht3, do you still have a reproducible code example you can share? I'd like to take a look into if and why Blendsearch malfunctioned

**Comment by anhnht3** [comment] 2021-08-22 19:03
Really sorry for the false alarm. For some reasons, search_alg.is_finished() is not True but the trial is terminated at the time I wrote my comments above. Now, I dont think it's BlendSearch.

**Comment by krfricke** [comment] 2021-09-27 08:05
I'll close this for now, please feel free to reopen with a repro script.

**Closed by krfricke** 2021-09-27 08:05 UTC
Labels: bug, needs-repro-script, P1, tune
