### ISSUE TITLE
[Bug] [RLlib] module 'gym.wrappers' has no attribute 'Monitor'

### ISSUE THREAD

**Issue by MarioGalindoQ** [ray-project/ray#23286] opened 2022-03-17 20:31 UTC
## Ray Component
RLlib

## Problem description
gym version 0.23.1 has removed `Monitor` from wrappers, so `ray/rllib/env/utils.py` do not work!

## Issue Severity
Medium: I solved the problem installing gym version 0.21.0

## Code reference
https://github.com/ray-project/ray/blob/f400b4333a3f9008ebfc069d1e6c6812f996e995/rllib/env/utils.py#L59
ray/rllib/evaluate.py also uses gym_wrappers.Monitor

**Comment by Maritimo** [comment] 2022-03-17 20:41
ray/rllib/evaluate.py also uses gym_wrappers.Monitor

**Comment by mattearllongshot** [comment] 2022-03-22 10:51
It looks like `ray[default]` doesn't have a dependency on gym.  After setting up a fresh conda env with these commands:

```
conda create -n ray-test python==3.8.12
conda activate ray-test
pip install ray[default]
```

It looks like gym isn't installed meaning rllib can't be imported:
```
$ pip freeze | grep ray
ray==1.11.0
$ pip freeze | grep gym
$ python -c 'import ray.rllib'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/data/conda/envs/ray-test/lib/python3.8/site-packages/ray/rllib/__init__.py", line 5, in <module>
    from ray.rllib.env.base_env import BaseEnv
  File "/mnt/data/conda/envs/ray-test/lib/python3.8/site-packages/ray/rllib/env/__init__.py", line 1, in <module>
    from ray.rllib.env.base_env import BaseEnv
  File "/mnt/data/conda/envs/ray-test/lib/python3.8/site-packages/ray/rllib/env/base_env.py", line 5, in <module>
    import gym
ModuleNotFoundError: No module named 'gym'
```
Is the proper fix to add a dependency on gym with an appropriate version spec such that `Monitor` exists?

**Comment by mattearllongshot** [comment] 2022-03-22 11:32
Having reviewed the rllib docs it appears that `ray[rllib]` is the thing to install for rllib, which does indeed have the right dependency on gym.  So I think this might be a non-bug, aside from having a slightly confusing error message.

**Comment by gjoliver** [comment] 2022-04-08 09:37
we are in the middle of fixing related issues caused by gym upgrade.
@avnishn, we can close this issue too once your PR lands.

**Comment by zplizzi** [comment] 2022-10-17 20:47
This is still broken. A clean install of the latest `ray[rllib]` (2.0.0) installs `gym-0.23.1`, which does not have the necessary `gym.wrappers.Monitor` class.

**Comment by avnishn** [comment] 2023-02-23 00:37
we have since moved to the gymnasium api, which I don't believe still supports the Monitor class.

**Closed by avnishn** 2023-02-23 00:37 UTC
Labels: P1, rllib, rllib-env
