### ISSUE TITLE
Ray shutdown prints ugly SIGTERM error

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#3303] opened 2018-11-11 23:47 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OS 10.13.12
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5.3
- **Python version**: 3.5.2
- **Exact command to reproduce**:
A bit involved:
(1) install flow https://github.com/flow-project/flow
(2) Run flow/examples/rllib/figure_eight.py for one or more iterations
Observe error. 

### Describe the problem
Seems like there's memory corruption. 

### Source code / logs

Result for PPO_AccelEnv-v0_0:
  custom_metrics: {}
  date: 2018-11-11_13-35-56
  done: true
  episode_len_mean: 1500.0
  episode_reward_max: 140.74661679750818
  episode_reward_mean: 94.01203774256558
  episode_reward_min: 78.75708145789343
  episodes_this_iter: 20
  episodes_total: 40
  experiment_id: 40437ca2287f4f9fb002804acde81a47
  hostname: Eugenes-MacBook-Pro-2.local
  info:
    cur_lr: 4.999999873689376e-05
    entropy: 1.4295375347137451
    grad_time_ms: 5171.109
    kl: 0.0016951033612713218
    load_time_ms: 25.644
    num_steps_sampled: 60000
    num_steps_trained: 60000
    policy_loss: -0.0011931781191378832
    sample_time_ms: 84044.494
    total_loss: 2.822516918182373
    update_time_ms: 245.699
    vf_explained_var: 0.8191723823547363
    vf_loss: 2.823540687561035
  iterations_since_restore: 2
  node_ip: 10.0.0.21
  num_metric_batches_dropped: 0
  pid: 68248
  policy_reward_mean: {}
  time_since_restore: 179.08559918403625
  time_this_iter_s: 101.70458102226257
  time_total_s: 179.08559918403625
  timestamp: 1541979356
  timesteps_since_restore: 60000
  timesteps_this_iter: 30000
  timesteps_total: 60000
  training_iteration: 2

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/3 CPUs, 0/0 GPUs
Memory usage on this node: 11.3/17.2 GB
Result logdir: /Users/eugenevinitsky/ray_results/for_test
TERMINATED trials:
 - PPO_AccelEnv-v0_0:	TERMINATED [pid=68248], 179 s, 2 iter, 60000 ts, 94 rew

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/3 CPUs, 0/0 GPUs
Memory usage on this node: 11.3/17.2 GB
Result logdir: /Users/eugenevinitsky/ray_results/for_test
TERMINATED trials:
 - PPO_AccelEnv-v0_0:	TERMINATED [pid=68248], 179 s, 2 iter, 60000 ts, 94 rew

/Users/eugenevinitsky/Desktop/Research/Bayen/Code/flow-ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 9
*** Aborted at 1541979356 (unix time) try "date -d @1541979356" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGTERM (@0x7fff5826dec2) received by PID 68230 (TID 0x7fff91220340) stack trace: ***
    @     0x7fff5839ef5a _sigtramp
/Users/eugenevinitsky/Desktop/Research/Bayen/Code/flow-ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 15
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).
sumo(68306,0x7fff91220340) malloc: *** error for object 0x7f8f2b850d60: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
/Users/eugenevinitsky/Desktop/Research/Bayen/Code/flow-ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 14
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).
sumo(68307,0x7fff91220340) malloc: *** error for object 0x7f9b6d150f60: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error)./Users/eugenevinitsky/Desktop/Research/Bayen/Code/flow-ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc
:609: Disconnecting client on fd 10
sumo(68301,0x7fff91220340) malloc: *** error for object 0x7fa239c7bdb0: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
/Users/eugenevinitsky/Desktop/Research/Bayen/Code/flow-ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 13
/Users/eugenevinitsky/Desktop/Research/Bayen/Code/flow-ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 12
/Users/eugenevinitsky/Desktop/Research/Bayen/Code/flow-ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 7
/Users/eugenevinitsky/Desktop/Research/Bayen/Code/flow-ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 5
/Users/eugenevinitsky/Desktop/Research/Bayen/Code/flow-ray/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 8

**Comment by ericl** [comment] 2018-11-14 00:19
Hey @eugenevinitsky I can't reproduce this on a Ray build from 11/13 on a g3.16xl machine. Maybe it has been fixed in masteR?

**Comment by ericl** [comment] 2018-11-14 05:16
Looks like the crash is just sumo during SIGTERM. We shouldn't be printing such a message on clean shutdown though.

**Comment by ericl** [comment] 2019-03-15 02:49
I think this is fixed

**Closed by ericl** 2019-03-15 02:49 UTC
