### ISSUE TITLE
[regression] Autoscaler events no longer printed to driver stdout

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#17218] opened 2021-07-20 20:07 UTC
It seems we've lost the autoscaler events (e.g., "Adding 1 nodes").

**Comment by AmeerHajAli** [comment] 2021-07-21 06:07
@ericl, I can't seem to repro in OSS. Are you reproducing?

**Comment by AmeerHajAli** [comment] 2021-07-21 06:32
Closing this issue since it seems to be resolved in OSS.

**Closed by AmeerHajAli** 2021-07-21 06:32 UTC
Labels: P0, bug, core-usability-hotlist
