### ISSUE TITLE
[autoscaler][docker] num files ulimit extremely low 

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#13044] opened 2020-12-22 19:50 UTC
### What is the problem?

When starting a new ray cluster, the ulimit inside the docker container is very low. This is a problem because our recommended `ulimit -n 65535; ray start --head ...` approach runs into a permission denied within docker. 

The proper solution is to do `docker run --ulimit nofile=65535 ...`. The implementation here should mirror  #11953.

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by edoakes** [comment] 2020-12-29 18:55
duplicate of https://github.com/ray-project/ray/issues/13045

**Closed by edoakes** 2020-12-29 18:55 UTC
Labels: bug, triage
