### ISSUE TITLE
[core][new scheduler] New scheduler starts too many workers

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#13725] opened 2021-01-27 02:12 UTC
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 2.0dev

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

I saw this issue when testing Dask-on-Ray to sort a 100GB dataframe. After a minute or so, many more workers than the number of CPUs would get started. Some would get destroyed, but there were always consistently more workers than the number of CPUs. The number of workers was stable on the same workload with the old scheduler.

Script [here](https://gist.github.com/stephanie-wang/1bc13114de2422f509de8749e69878b7).

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by stephanie-wang** [comment] 2021-01-27 02:13
@wuisawesome, have you seen anything like this before? It wasn't clear what was causing this.

**Comment by wuisawesome** [comment] 2021-01-27 02:34
Hmm this almost feels like the anti #12052. Can you try running with `RAY_ENABLE_WORKER_PRESTART=0`? In theory, that fix should've only been necessary for the old scheduler.

**Comment by wuisawesome** [comment] 2021-01-27 02:47
@ericl and @rkooo567  have run into this issue too now, so we should probably fix it before the release.

**Comment by rkooo567** [comment] 2021-01-27 03:01
Is it possible to reproduce?

**Comment by wuisawesome** [comment] 2021-01-27 07:12
Seems like we don't have a minimal reproduction, but if we can reproduce with dask on ray and object spilling, this is likely quite prevalent.

**Comment by rkooo567** [comment] 2021-01-27 07:13
Oh gotcha. I misread your comment.

**Comment by wuisawesome** [comment] 2021-01-27 21:44
Hmm having trouble reproducing this on an 8 core ubuntu machine w/ a 50GB test. It seems like there's almost always exactly 1 idle worker. 

@stephanie-wang @rkooo567  what type of instance did y'all use?

**Comment by stephanie-wang** [comment] 2021-01-27 21:56
This was on m5.8xlarge (32 vCPUs) and a 100GB input. You can run the attached script:
```
python test_dask.py --sort --nbytes $(( 10 ** 11 )) --ray
```

**Comment by stephanie-wang** [comment] 2021-01-28 20:40
I wasn't clear in the initial description, but this is just about the number of workers that were started. The actual number of live workers at any time is the same as the number of CPUs.

So I'm going to remove the P0 and release-blocker tags since this is unfortunate, but shouldn't actually affect performance much except for long-running jobs that need disk space (since this bug will result in many worker log files in /tmp/ray/session_latest/logs).


It's also most likely related to the WorkerPool, not the new scheduler. @kfstorm, do you have any ideas why we would keep starting and killing workers?

**Comment by wuisawesome** [comment] 2021-01-28 21:04
Ok, I think we've pieced together all the missing pieces here. This is the result of 2 "features" clashing. 

1. `kill_idle_workers_interval_ms = 200`. So we intentionally kill off idle workers.
2. `enable_worker_prestart = true` by default. This means we ensure that we always have `num_cpus` running worker processes. This is enforced on every lease request.

**Comment by stephanie-wang** [comment] 2021-01-28 21:06
Hmm but there are always num_cpus workers, so condition 2 shouldn't be met, right?

**Comment by wuisawesome** [comment] 2021-01-28 21:08
I think the first feature is killing the idle workers, so feature 2 is trying to restart them.

**Comment by wuisawesome** [comment] 2021-01-28 21:12
One thing to note here is that the worker prestart was in response to #12052 which was only a problem in the old scheduler. A  short (or maybe even long term) fix for this could be to just turn the worker prestart feature off when using the new scheduler (doesn't address the problem for the old scheduler though).

**Comment by ericl** [comment] 2021-01-28 22:03
We shouldn't be killing idle workers unless another job is trying to
acquire them. Can we disable that feature safely? It will actually greatly
slow down repeated waves of tasks if there is a delay.

Eric

**Comment by wuisawesome** [comment] 2021-01-28 23:19
Didn't we establish that prestart was only critical for the old scheduler? https://github.com/ray-project/ray/issues/12052#issuecomment-732461183

**Comment by ericl** [comment] 2021-01-28 23:42
It's needed for both.

**Comment by rkooo567** [comment] 2021-01-29 02:25
We kill IDLE workers only when they exceed the soft limit (num_cpus). Regular IDLE workers shouldn't be killed.

**Comment by ericl** [comment] 2021-01-29 02:31
Then what explains the issue then? Is it we are counting io workers towards the worker limit?

**Comment by rkooo567** [comment] 2021-01-29 02:43
I just checked code, and it doesn’t look like io workers are counted to the worker limit. I am not sure what’s the root cause here (maybe some other bugs)? We should definitely look at this soon

**Comment by wuisawesome** [comment] 2021-02-17 22:14
Using the native shuffle (with 2 cluster util nodes with 4 cores each), i get the following:

With the worker pool's `TryKillingIdleWorkers` feature turned off, I see 12 core workers created (in theory this could require 8).

With the feature turned on (which it is by default), I get 23 core workers. 

These numbers are all excluding io workers (which there always appears to be the correct number of).

**Comment by ericl** [comment] 2021-02-24 23:08
I'm still seeing this on ray.__commit__
'021ed92e8aa72d6ed6892d81346b9b43804fd59a'

If you run python -m ray.experimental.shuffle --num-partitions=500 --partition-size=1e6 --ray-address=auto this happens very reliably on a 4 node cluster.

```
Map Progress.: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [00:30<00:00,  2.16s/it2021-02-24 23:05:06,188|█
WARNING worker.py:1090 -- WARNING: 96 PYTHON workers have been started. This could be a result of using a large number of actors, or it could be a consequence of using nested tasks (see https://github.com/ray-project/ray/issues/3644) for some a discussion of workarounds.
```

I am not able to reproduce on a single node cluster. Maybe it only happens related to tasks in the WAITING queue (multi-node data transfer).

**Comment by wuisawesome** [comment] 2021-02-24 23:27
I think this is a different issue (Stephanie's issue was creating 10k+ workers).

Btw what size nodes are you using?

**Comment by ericl** [comment] 2021-02-24 23:45
Oh, I think I see the issue. There are zombie shuffle_map tasks hanging around

ubuntu    35081  1.8  0.6 3490472 1657936 pts/1 Sl   22:43   1:05 ray::shuffle_map()
ubuntu    35082  0.7  0.0 2266752 128000 pts/1  Sl   22:43   0:26 ray::shuffle_map()
ubuntu    35083  2.0  0.7 3722712 1958972 pts/1 Sl   22:43   1:13 ray::shuffle_map()
ubuntu    35084  1.5  0.4 3108408 1240724 pts/1 Sl   22:43   0:55 ray::shuffle_map()

I think the issue is those workers are getting killed as "idle", but since they own objects, we keep them around in zombie state, and launch a new set of workers. Perhaps the solution is to not count these workers towards the warning message? cc @stephanie-wang 

```
ubuntu@ip-192-168-14-248:~$ ps aux | grep ray::IDLE | wc -l
87
ubuntu@ip-192-168-14-248:~$ ps aux | grep ray::shuffle_map | wc -l
32
ubuntu@ip-192-168-14-248:~$ ps aux | grep ray::shuffle_reduce | wc -l
30
```

**Comment by ericl** [comment] 2021-02-25 01:53
Let me file a new issue.

**Comment by stephanie-wang** [comment] 2021-02-25 02:32
How about not counting those workers as idle?

**Comment by ericl** [comment] 2021-02-25 02:40
Here's the new bug: https://github.com/ray-project/ray/issues/14332

**Comment by wuisawesome** [comment] 2021-02-25 02:44
I'll close this one so we centralize the new conversation there.

**Closed by wuisawesome** 2021-02-25 02:44 UTC
Labels: P1, bug
