### ISSUE TITLE
SYN cookies cause errors

### ISSUE THREAD

**Issue by jssmith** [ray-project/ray#260] opened 2017-02-09 05:52 UTC
I am running an EC2 cluster using 18 nodes of type c4.8xlarge in the us-west-2c region.

After installing Ray and starting the cluster I find that a simple test script that launches 1000 tasks hangs. I see this error on the head node:

```
[FATAL] (/home/ubuntu/ray/src/photon/photon_client.c:53: errno: Resource temporarily unavailable) Check failure: type == EXECUTE_TASK

/home/ubuntu/.local/lib/python2.7/site-packages/ray-0.0.1-py2.7.egg/core/src/photon/libphoton.so(photon_get_task+0xdd)[0x7fabb09e50db]
/home/ubuntu/.local/lib/python2.7/site-packages/ray-0.0.1-py2.7.egg/core/src/photon/libphoton.so(+0x488c)[0x7fabb09e188c]
/opt/conda/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x82dc)[0x7fabbc156f3c]
/opt/conda/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x89e)[0x7fabbc1581ce]
/opt/conda/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8596)[0x7fabbc1571f6]
/opt/conda/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x89e)[0x7fabbc1581ce]
/opt/conda/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCode+0x32)[0x7fabbc1582e2]
/opt/conda/bin/../lib/libpython2.7.so.1.0(PyRun_FileExFlags+0xb0)[0x7fabbc178960]
/opt/conda/bin/../lib/libpython2.7.so.1.0(PyRun_SimpleFileExFlags+0xef)[0x7fabbc178b3f]
/opt/conda/bin/../lib/libpython2.7.so.1.0(Py_Main+0xca4)[0x7fabbc18e484]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fabbb384830]
python[0x400649]
```

Additionally, I see the following in `/var/log/syslog`:

```
Feb  9 05:27:29 ip-172-31-3-24 kernel: [11293.538325] TCP: request_sock_TCP: Possible SYN flooding on port 63148. Dropping request.  Check SNMP counters.
```

After some experimentation I found that turning off SYN cookies on the head node fixes the problem:
```
sudo sysctl -w net.ipv4.tcp_syncookies=0
sudo sysctl -p
```

We need to make sure that users do not encounter this issue. Perhaps some investigation will show how Ray can work with SYN cookies enabled. Alternatively we can update installation instructions to disable this kernel feature.

## Test Script
```python
import ray

ray.init(redis_address="172.31.3.24:6379")

@ray.remote
def f():
    return ray.services.get_node_ip_address()

queries = [f.remote() for _ in range(1000)]
(ready, _) = ray.wait(queries, timeout=3000, num_returns=len(queries))
nodes = set(ray.get(ready))
print len(nodes), nodes
```

**Comment by robertnishihara** [comment] 2017-02-09 05:57
Wow, nice find. If you can run into this issue on the head node, I'd guess that it can also occur with other nodes (that is, whatever adjustments you made on the head node will probably also have to be made on the other nodes).

@atumanov may have some insights.

**Comment by robertnishihara** [comment] 2017-09-05 06:20
Closing for now because I haven't seen this problem. Please reopen if it looks like the issue is arising.

**Closed by robertnishihara** 2017-09-05 06:20 UTC
