### ISSUE TITLE
Fail to create keras model in ray.actor

### ISSUE THREAD

**Issue by raopku** [ray-project/ray#410] opened 2017-03-29 09:45 UTC
```
@ray.actor
class myactor(object):
    def __init__(self, model_config): 
        from keras.utils.layer_utils import layer_from_config
        self.model = layer_from_config(model_config, custom_objects={}) 
```
```
Create first actor, it works
actor1 = myactor(model_config_id)
```
```
Create second actor, it works
actor2 = myactor(model_config_id)
```
```
Create third actor, it fails
actor3 = myactor(model_config_id)
```
model_config can be make like this：
```
from keras.models import Sequential
from keras.layers import Dense,Flatten,Activation
ENV_NAME = 'CartPole-v0'
import gym
import numpy as np
# Get the environment and extract the number of actions.
env = gym.make(ENV_NAME)
np.random.seed(123)
env.seed(123)
nb_actions = env.action_space.n

# Next, we build a very simple model.
model = Sequential()
model.add(Flatten(input_shape=(1,) + env.observation_space.shape))
model.add(Dense(16))
model.add(Activation('relu'))
model.add(Dense(16))
model.add(Activation('relu'))
model.add(Dense(16))
model.add(Activation('relu'))
model.add(Dense(nb_actions))
model.add(Activation('linear'))
model_config = {
    'class_name': model.__class__.__name__,
    'config': model.get_config(),
}
model_config_id = ray.put(model_config)
```

The error logs is here:
```
Remote function __init__ failed with:

Traceback (most recent call last):
  File "/home/dl/.local/lib/python2.7/site-packages/ray-0.0.1-py2.7.egg/ray/worker.py", line 1611, in process_task
    outputs = function_executor(worker.actors[task.actor_id().id()], *arguments)
  File "<ipython-input-1-c1938c799746>", line 53, in __init__
  File "/home/dl/anaconda2/envs/tensorflow_rao/lib/python2.7/site-packages/keras/utils/layer_utils.py", line 36, in layer_from_config
    return layer_class.from_config(config['config'])
  File "/home/dl/anaconda2/envs/tensorflow_rao/lib/python2.7/site-packages/keras/models.py", line 1025, in from_config
    model.add(layer)
  File "/home/dl/anaconda2/envs/tensorflow_rao/lib/python2.7/site-packages/keras/models.py", line 308, in add
    output_tensor = layer(self.outputs[0])
  File "/home/dl/anaconda2/envs/tensorflow_rao/lib/python2.7/site-packages/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])
  File "/home/dl/anaconda2/envs/tensorflow_rao/lib/python2.7/site-packages/keras/layers/core.py", line 695, in build
    name='{}_W'.format(self.name))
  File "/home/dl/anaconda2/envs/tensorflow_rao/lib/python2.7/site-packages/keras/initializations.py", line 59, in glorot_uniform
    return uniform(shape, s, name=name)
  File "/home/dl/anaconda2/envs/tensorflow_rao/lib/python2.7/site-packages/keras/initializations.py", line 32, in uniform
    return K.random_uniform_variable(shape, -scale, scale, name=name)
  File "/home/dl/anaconda2/envs/tensorflow_rao/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 282, in random_uniform_variable
    return variable(value, dtype=dtype, name=name)
  File "/home/dl/anaconda2/envs/tensorflow_rao/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 152, in variable
    if tf.get_default_graph() is get_session().graph:
  File "/home/dl/anaconda2/envs/tensorflow_rao/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 76, in get_session
    _SESSION = tf.Session(config=tf.ConfigProto(allow_soft_placement=True))
  File "/home/dl/anaconda2/envs/tensorflow_rao/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1138, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/dl/anaconda2/envs/tensorflow_rao/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 502, in __init__
    self._session = tf_session.TF_NewSession(opts, status)
  File "/home/dl/anaconda2/envs/tensorflow_rao/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/dl/anaconda2/envs/tensorflow_rao/lib/python2.7/site-packages/tensorflow/python/framework/errors.py", line 463, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
InternalError: Failed to create session.
```

what is the problem? it looks like that there is a conflict between actors

**Comment by robertnishihara** [comment] 2017-03-29 18:08
Interesting, your code works for me (I tried with both a Theano and TensorFlow backend), and I haven't quite been able to reproduce the error.

Questions:
1. What versions of Keras and TensorFlow are you using?
2. Does it deterministically fail when you create the third actor? Or does the timing matter? E.g., what if you do it in an IPython interpreter and wait a while between creating the actors. In the past I've seen Keras read/write files when it starts up and when multiple processes do this they can conflict. This could be worked around by sleeping for a random duration in the actor constructor.
3. Are you using GPUs? Is it possible that you'r running out of GPU resources (or some other resources) because each session is reserving a bunch of memory (or some resource) for itself?


Other notes:
1. By default Keras uses a Theano backend. I think you're using a TensorFlow backend so I did `export KERAS_BACKEND=tensorflow` before starting Python.
2. In the latest version of Keras (`2.0.2` I believe), `layer_from_config` is no longer defined. I had to downgrad to Keras `1.2.2` to run your example.

**Comment by raopku** [comment] 2017-03-30 02:08
@robertnishihara 
I think it is related with the your recent work of expose gpu to tasks.
#403 
What versions of Keras and TensorFlow are you using?
I use keras 1.2.2 and Tensorflow 0.11. It always failed when i start multi actors. In fact, i run the actor creation command in Ipython one by one. So it will have enough time for actor to start.

My computer has four GPUs. I found that every time i create a actor, it takes up a gpu
```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
| GPU       PID  Type  Process name                               Usage      |
|    0      7487    C    python                                          75MiB |
|    1     16289    C                                                       10897MiB |
|    1     28360    C   python                                         366MiB |
|    1     28624    C   python                                         170MiB |
|    2     16289    C   python                                         10869MiB |
```

Process 28360 and process 28624 are ators.

I think when there is no enough for create actor, it just fails.

But different users login in the computer using ssh, and start their own application when there is no enough, things go well. Is there something special of actor's resource occupancy?

I simply set actor's num_gpus=0, it does not work.

**Comment by robertnishihara** [comment] 2017-03-30 02:57
That makes sense. I think by default when you create a TensorFlow session, it will try to reserve space on all of the visible GPUs, and so if you have multiple processes trying to do this then some of them may fail.

You can do something like the following.

```python
import os

@ray.actor(num_gpus=1)
class myactor(object):
    def __init__(self, model_config): 
        os.environ['CUDA_VISIBLE_DEVICES'] = ','.join([str(i) for i in ray.get_gpu_ids()])
        from keras.utils.layer_utils import layer_from_config
        self.model = layer_from_config(model_config, custom_objects={})
```

Then you should be able to create four actors (since you have four GPUs).

```python
a1 = myactor()
a2 = myactor()
a3 = myactor()
a4 = myactor()
```

Then if you try to create a fifth actor `a5 = myactor()`, an exception will be raised saying there aren't enough GPUs. At least that's the current behavior.

Note that this all assumes you started ray with `ray.init(num_gpus=4)`.

If you want to create actors that don't use any CPUs, you could do the following.

```python
class myactor(object):
    def __init__(self, model_config): 
        os.environ['CUDA_VISIBLE_DEVICES'] = ','.join([str(i) for i in ray.get_gpu_ids()])
        from keras.utils.layer_utils import layer_from_config
        self.model = layer_from_config(model_config, custom_objects={})

gpu_actor = ray.actor(num_gpus=1)(myactor)
cpu_actor = ray.actor(myactor)

# Then create some GPU actors and some CPU actors
gpu_actors = [gpu_actor() for _ in range(4)]
cpu_actors = [cpu_actor() for _ in range(10)]
```

As for optionally giving the actor a GPU based on whether there are any GPUs available or not, there currently isn't a super convenient way to do that.

**Comment by raopku** [comment] 2017-04-01 10:00
@robertnishihara 
```
gpu_actor = ray.actor(num_gpus=1)(myactor)
cpu_actor = ray.actor(myactor)
```
I think it is an elegant API for task parallel. A minor changes is needed to parallel the stand-alone  algorithms.

however, the code `ray.get_gpu_ids()` does not work for me.
it always returns an empty list ( [] ).  

I use the command to check the usage to GPU. So there is enough GPU to use.
watch -n 0.1 nvidia-smi
you can see that no process is using GPU.
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+



To exclude the possibility of the environment variable CUDA_VISIBLE_DEVICES is set incorrectly.

so i do it in a command line like this
```
dl@dl123:~$ export CUDA_VISIBLE_DEVICES=0,1,2,3
dl@dl123:~$ python
>>> import ray
>>> ray.get_gpu_ids()
[]
>>> 
```

what is principle of the command of ray.get_gpu_ids() ? I am trying to figure out what is the problem.

**Comment by robertnishihara** [comment] 2017-04-01 16:17
The method `ray.get_gpu_ids` is meant to be used inside of tasks and actors, so that GPUs can be allocated to tasks and actors.

For example, it is intended to work as follows.

```python
@ray.actor(num_gpus=1)
class Foo(object):
  def __init__(self):
    gpu_ids = ray.get_gpu_ids()
```

The following will also work after #403 is merged.

```python
@ray.remote(num_gpus=1)
def f():
  ray.get_gpu_ids()
```

The intended use case is that the local scheduler can assign different GPUs on a node to different tasks or actors that use GPUs. Note that for this to work, you have to start Ray with `ray.init(num_gpus=4)` or something like that.

Currently it is not possible to assign a GPU to the driver process, though I could see that being useful.

**Comment by robertnishihara** [comment] 2017-05-26 22:54
Closing this because I think it has been resolved. Please reopen if there are more problems here!

**Closed by robertnishihara** 2017-05-26 22:54 UTC
