### ISSUE TITLE
[CI]Mac OS Pipeline not kicked off

### ISSUE THREAD

**Issue by ArturNiederfahrenhorst** [ray-project/ray#32774] opened 2023-02-23 10:59 UTC
## Why are these changes needed?

I bisected our buildkite history from master (where this kickoff always happens) and found the following:

First time the pipeline did not get kicked off properly:
<img width="1198" alt="Screenshot 2023-02-23 at 06 59 32" src="https://user-images.githubusercontent.com/9356806/220831214-4a18de34-c72a-42ad-ad48-27aa8043304a.png">

Last time the pipeline got kicked off properly:
<img width="1198" alt="Screenshot 2023-02-23 at 06 59 55" src="https://user-images.githubusercontent.com/9356806/220831263-3830be39-0d7d-4ab1-beae-76061d636ea7.png">

The pipeline has been broken since Feb 14th, very close to https://github.com/ray-project/ray/pull/32409.
I don't have enough context on the changes in the PR in question to confirm that it causes this issue so this is sort of a shot in the dark.

### Versions / Dependencies

master

### Reproduction script

Open PR to master, have a look at buildkite to see that Mac OS tests don't run.

### Issue Severity

None

**Comment by stephanie-wang** [comment] 2023-02-23 13:00
Hmm it seems like it stopped working before that PR, though?

Should we try reverting it and see if it passes in CI?

**Comment by ArturNiederfahrenhorst** [comment] 2023-02-23 15:49
@rkooo567 said that this was fixed by https://github.com/ray-project/ray/commit/7774cc3ebaf613eaf42067c0518667a49c26bb12, I don't see the jobs running on CI for master right now though.

The buildkite job for the PR in question still ran fine: https://buildkite.com/ray-project/oss-ci-build-pr/builds/12043#_

**Comment by ArturNiederfahrenhorst** [comment] 2023-02-23 15:52
The first PR where they did not run is https://github.com/ray-project/ray/commit/d092b126b6755779707be6e4d5b7f52c272181c1

**Comment by scv119** [comment] 2023-03-01 22:23
Looks the problem is fixed by @krfricke

**Closed by scv119** 2023-03-01 22:23 UTC
Labels: bug, P0
