### ISSUE TITLE
Memory leak from raylet in Ray 1.3

### ISSUE THREAD

**Issue by soundway** [ray-project/ray#16136] opened 2021-05-28 18:51 UTC
This is not a contribution.

Ray version: 1.3
Python version: 3.6.8
OS: Ubuntu 18.04 Docker

In 1.3, we discovered memory leaks from raylet in some of our applications. It’s reproducible with the latest pip wheel, but the leak does not happen in Ray 1.2. The application is a driver script that aggregates data from a set of data workers from a different node via ParallelIterator. There seems to be a certain set of conditions that must be met for the leak to happen. See the Caveats list below. The source code might require slight modifications depending on the cluster environment.

Caveats:
- There must be at least 2 nodes in the cluster (in the repro setup we have exactly 2).
- All DataWorker must be allocated to the non-driver node. In our cluster setup, we assigned a custom resource of “worker=100” for the non-driver node. It appears that having additional DataWorker on the driver node somehow reduces/eliminates the leak.
- In the example script, we assumed that the 2nd node has 36 CPU cores (c5.9xlarge on AWS), and we launched 36 DataWorker there. Worker node CPUs need to be kept busy — we added a busy for loop during data generation in DataWorker.

```python
import numpy as np
import ray

@ray.remote(num_cpus=1, resources={"worker": 0.1})  # Must be allocated on 2nd node, with ‘worker’ resource.
class DataWorker(ray.util.iter.ParallelIteratorWorker):
    def __init__(self):
        def gen():
            while True:
                for _ in range(10000000): pass  # Keep CPU busy, necessary for fast leak.
                yield np.random.random((1, 100 * 1024))
        super().__init__(gen, repeat=True)

if __name__ == '__main__':
    ray.init(address="auto")
    # All data workers must be allocated on the worker node. Assume 36 cores on the worker node (c5.9xlarge).
    it = ray.util.iter.from_actors([DataWorker.remote() for _ in range(36)])
    batches = it.gather_async(num_async=2).batch(50).for_each(lambda b: np.stack(b, axis=0))
    for i, _ in enumerate(batches):
        if (i + 1) % 100 == 0:
            print(f"Processed {i + 1} batches.")
```
We observed continuous growth in memory usage for the raylet and the driver processes on the driver node. Below is the memory usage graph between Ray 1.2 (top) vs Ray 1.3 (bottom) — yellow for the driver node, green for the worker node.

<img width="779" alt="Screen Shot 2021-05-28 at 11 06 13 AM" src="https://user-images.githubusercontent.com/61214581/120025024-e906a280-bfa4-11eb-91f1-a12fbca206f5.png">
<img width="768" alt="Screen Shot 2021-05-28 at 11 07 03 AM" src="https://user-images.githubusercontent.com/61214581/120025027-ea37cf80-bfa4-11eb-8627-225af9658798.png">

We also have applications with more complex but different flows that leak at much higher rates, but it’s difficult to reduce them into minimal scripts for bug report. That said, there are other applications that contain execution flows that are very similar to the script above and basically satisfy all of the conditions, but they don’t have any noticeable leak — so there could be additional conditions we haven’t uncovered that’s hidden in this setup. None of our applications leaks in Ray 1.2.

**Comment by rkooo567** [comment] 2021-05-29 06:33
Before we dig into further, can you do a couple more follow up actions? 

1. Can you try the leak is reproducible in the latest master?
2. Can you check which process has the leaking memory? (e.g., worker process, driver script, raylet), especially checking if shm is increasing or rss is increasing?

**Comment by soundway** [comment] 2021-05-30 09:04
1. As I mentioned in the report -- it is reproducible with the latest wheel.
2. Also mentioned in the report, both the Raylet and the worker processes seem to have leaks. If I put the aggregation into a different actor on the driver node, that actor's memory usage will also grow as fast as the driver.

**Comment by rkooo567** [comment] 2021-05-31 02:40
@soundway sounds good. Sorry that I missed those two points. We will start investigation. Thanks for the repro & report!

**Comment by soundway** [comment] 2021-05-31 04:35
No problem. Regarding your question on the type of memory growth -- both working set memory and RSS grow at the same rate on the driver node for both processes, while shared memory usage seems to remain negligible.

**Comment by soundway** [comment] 2021-06-07 21:59
It seems that 1.4 has just been released and this remains a problem for us.

I wonder if you have managed to reproduce this issue independently or need any help with the reproduction. Currently, this makes a few of our applications crash almost immediately rendering 1.3 and 1.4 un-usable, and we are a bit surprised that there aren't other similar reports. It'd be good for us to know if it's potentially caused by something in our dependencies or environment.

**Comment by rkooo567** [comment] 2021-06-07 22:28
I haven’t started investigating it yet. I will start it in a few days. The fix will be included in the next version. I will lyk if I have trouble to repro

**Comment by ericl** [comment] 2021-06-08 17:43
Possibly related to https://discuss.ray.io/t/ray-actor-ram-usage-keep-growing/2450/3

**Comment by duburcqa** [comment] 2021-06-14 14:04
I don't know if it is related, but I have done some memory analysis because I'm having memory leak issues, and it turns out the issue is coming from [here](https://github.com/ray-project/ray/blob/2a02b97f1ae552debd2071985e23e2da418ed906/python/ray/serialization.py#L156). Here is what I get using `tracemalloc` and ray 1.3.0:
```
.../python3.6/site-packages/ray/serialization.py:156: size=350 MiB (+37.0 MiB), count=9871110 (+1070182), average=37 B
```

**Comment by ericl** [comment] 2021-06-17 23:30
@iycheng could you take a look at this?

**Comment by iycheng** [comment] 2021-06-19 20:19
After some investigation, I think it's related to long-running RPC (https://github.com/ray-project/ray/blob/197dab0e2fe9198b10a79a800fef54f41de7472c/src/ray/core_worker/reference_count.cc#L1128).  Tested with this PR (https://github.com/ray-project/ray/pull/16407) and it looks good. But it got reverted, @rkooo567 do you have some plan about when it can be re-merged?

**Comment by iycheng** [comment] 2021-06-19 20:20
And here is the memory footprint:
```
With the fix:
(raylet) Dumping heap profile to /tmp/profile-new.0001.heap (1024 MB allocated cumulatively, 14 MB currently in use)
(raylet) Dumping heap profile to /tmp/profile-new.0002.heap (2048 MB allocated cumulatively, 15 MB currently in use)
(raylet) Dumping heap profile to /tmp/profile-new.0003.heap (3073 MB allocated cumulatively, 16 MB currently in use)
(raylet) Dumping heap profile to /tmp/profile-new.0004.heap (4098 MB allocated cumulatively, 14 MB currently in use)
(raylet) Dumping heap profile to /tmp/profile-new.0005.heap (5123 MB allocated cumulatively, 14 MB currently in use)
(raylet) Dumping heap profile to /tmp/profile-new.0006.heap (6147 MB allocated cumulatively, 16 MB currently in use)
(raylet) Dumping heap profile to /tmp/profile-new.0007.heap (7171 MB allocated cumulatively, 14 MB currently in use)
(raylet) Dumping heap profile to /tmp/profile-new.0008.heap (8196 MB allocated cumulatively, 14 MB currently in use)
Without the fix
(raylet) Dumping heap profile to /tmp/old-prof.0001.heap (1024 MB allocated cumulatively, 18 MB currently in use)
(raylet) Dumping heap profile to /tmp/old-prof.0002.heap (2048 MB allocated cumulatively, 26 MB currently in use)
(raylet) Dumping heap profile to /tmp/old-prof.0003.heap (3072 MB allocated cumulatively, 31 MB currently in use)
(raylet) Dumping heap profile to /tmp/old-prof.0004.heap (4097 MB allocated cumulatively, 38 MB currently in use)
(raylet) Dumping heap profile to /tmp/old-prof.0005.heap (5122 MB allocated cumulatively, 42 MB currently in use)
```

**Comment by rkooo567** [comment] 2021-06-19 20:27
Yeah that’ll be remerged, but I am currently debugging the regression I found from the pr

**Comment by duburcqa** [comment] 2021-06-20 17:25
> After some investigation, I think it's related to long-running RPC 

@iycheng Do you think both memory leaks are related to the same issue ?

Glad to hear there is a fix in progress !

**Comment by iycheng** [comment] 2021-06-21 17:07
@duburcqa they both might be related, I haven't run the tracemalloc with worker yet, but from my previous experience, long running rpc will lead both raylet and worker memory high.

**Comment by iycheng** [comment] 2021-06-23 04:30
Fixing in this PR #16487 
I'll verify it later.

**Comment by duburcqa** [comment] 2021-06-23 07:29
Amazing ! I will check as soon as a wheel is available of Linux.

**Comment by ericl** [comment] 2021-06-29 17:20
Should be fixed in master. @soundway can you confirm? Feel free to close if so.

**Comment by soundway** [comment] 2021-07-01 07:38
@ericl Just tried the latest build running the same script above, got tons of errors from pull_manager.cc, then eventually a failure in about 5 minutes. 

```
[2m[33m(raylet)[0m [2021-07-01 07:32:54,053 E 418 418] pull_manager.cc:273: Margin required 0
[2m[33m(raylet)[0m [2021-07-01 07:32:54,054 E 418 418] pull_manager.cc:273: Margin required 819459
[2m[33m(raylet)[0m [2021-07-01 07:32:54,054 E 418 418] pull_manager.cc:273: Margin required 0
[2m[33m(raylet)[0m [2021-07-01 07:32:54,056 E 418 418] pull_manager.cc:273: Margin required 0
[2m[33m(raylet)[0m [2021-07-01 07:32:54,057 E 418 418] pull_manager.cc:273: Margin required 0
[2m[33m(raylet)[0m [2021-07-01 07:32:54,057 E 418 418] pull_manager.cc:273: Margin required 0
2021-07-01 07:32:54,076	WARNING worker.py:1502 -- Local object store memory usage:
num clients with quota: 0
quota map size: 0
pinned quota map size: 0
allocated bytes: 42611869
allocation limit: 29503039078
pinned bytes: 9212358079
(global lru) capacity: 29503039078
(global lru) used: 0%
(global lru) num objects: 0
(global lru) num evictions: 0
(global lru) bytes evicted: 0

Traceback (most recent call last):
  File "baseline.py", line 18, in <module>
    for i, _ in enumerate(batches):
  File "/usr/local/lib/python3.6/dist-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/usr/local/lib/python3.6/dist-packages/ray/util/iter.py", line 857, in apply_batch
    for item in it:
  File "/usr/local/lib/python3.6/dist-packages/ray/util/iter.py", line 551, in base_iterator
    batch = ray.get(obj_ref)
  File "/usr/local/lib/python3.6/dist-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1506, in get
    raise value
ray.exceptions.ObjectLostError: Object 294e6e857463d19781e3ea0a642deb9f9379f3ca0100000001000000 is lost due to node failure.
[2m[33m(raylet)[0m [2021-07-01 07:32:54,072 E 418 418] pull_manager.cc:273: Margin required 0
[2m[33m(raylet)[0m [2021-07-01 07:32:54,072 E 418 418] pull_manager.cc:273: Margin required 0
[2m[33m(raylet)[0m [2021-07-01 07:32:54,072 E 418 418] pull_manager.cc:273: Margin required 0
[2m[33m(raylet)[0m [2021-07-01 07:32:54,072 E 418 418] pull_manager.cc:273: Margin required 819459
```

**Comment by ericl** [comment] 2021-07-01 16:21
Those aren't real errors (just a misleading message), you can ignore for
now. Is the object loss issue reproducible or is it due to a node failure?

**Comment by rkooo567** [comment] 2021-07-01 16:22
Hey the object loss error could be resolved after I fix the issue that happened in test_scheduling )it was a real bug)

**Comment by rkooo567** [comment] 2021-07-01 16:22
The PR is out, so you can try out in 1-2 days

**Comment by ericl** [comment] 2021-07-03 22:08
The original issue should now be fixed in the nightly.

**Closed by ericl** 2021-07-03 22:08 UTC
Labels: P1, bug, size:medium
