### ISSUE TITLE
[xray] Lots of error messages on exit

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#2537] opened 2018-08-01 23:18 UTC
### Describe the problem
Run something simple like:
```
import ray

@ray.remote
class X(object):
    def __init__(self):
        pass
    def get(self):
        return 2

ray.init(use_raylet=True, num_cpus=10)
actors = [X.remote() for _ in range(20)]
print(ray.get([a.get.remote() for a in actors]))
```

### Source code / logs
```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 572, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 439, in connect
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 538, in send_packed_command
    sock = self._connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 494, in _connect
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 442, in connect
    raise err
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 482, in _connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 128.32.38.222:55099. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 439, in connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 572, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 128.32.38.222:55099. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 439, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 494, in _connect
    raise err
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eric/Desktop/ray-private/python/ray/worker.py", line 2083, in connect
    ray.services.check_version_info(worker.redis_client)
    sock = self._connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 494, in _connect
    raise err
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eric/Desktop/ray-private/python/ray/workers/default_worker.py", line 55, in <module>
    info, mode=ray.WORKER_MODE, use_raylet=(args.raylet_name is not None))
  File "/home/eric/Desktop/ray-private/python/ray/worker.py", line 2094, in connect
    driver_id=None)
  File "/home/eric/Desktop/ray-private/python/ray/services.py", line 382, in check_version_info
    redis_reply = redis_client.get("VERSION_INFO")
  File "/home/eric/Desktop/ray-private/python/ray/utils.py", line 324, in _wrapper
    return orig_attr(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 880, in get
    return self.execute_command('GET', name)
  File "/home/eric/Desktop/ray-private/python/ray/utils.py", line 128, in push_error_to_driver_through_redis
    ray.gcs_utils.TablePubsub.ERROR_INFO, driver_id, error_data)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/home/eric/Desktop/ray-private/python/ray/utils.py", line 324, in _wrapper
    return orig_attr(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 128.32.38.222:55099. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 439, in connect
    sock = self._connect()
redis.exceptions.ConnectionError: Error 111 connecting to 128.32.38.222:55099. Connection refused.
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 494, in _connect
    raise err
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 572, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 439, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 494, in _connect
redis.exceptions.ConnectionError: Error 111 connecting to 128.32.38.222:55099. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 439, in connect
    sock = self._connect()
    raise err
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 494, in _connect
    raise err
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 572, in execute_command
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 482, in _connect
    connection.send_command(*args)
    sock.connect(socket_address)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 563, in send_command
ConnectionRefusedError: [Errno 111] Connection refused
    self.send_packed_command(self.pack_command(*args))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eric/Desktop/ray-private/python/ray/workers/default_worker.py", line 55, in <module>
    info, mode=ray.WORKER_MODE, use_raylet=(args.raylet_name is not None))
  File "/home/eric/Desktop/ray-private/python/ray/worker.py", line 2094, in connect
    driver_id=None)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 128.32.38.222:55099. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 439, in connect
  File "/home/eric/Desktop/ray-private/python/ray/utils.py", line 128, in push_error_to_driver_through_redis
    ray.gcs_utils.TablePubsub.ERROR_INFO, driver_id, error_data)
  File "/home/eric/Desktop/ray-private/python/ray/utils.py", line 324, in _wrapper
    return orig_attr(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 578, in execute_command
    sock = self._connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 494, in _connect
    connection.send_command(*args)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 128.32.38.222:55099. Connection refused.
    raise err
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eric/Desktop/ray-private/python/ray/worker.py", line 2083, in connect
    ray.services.check_version_info(worker.redis_client)
  File "/home/eric/Desktop/ray-private/python/ray/services.py", line 382, in check_version_info
    redis_reply = redis_client.get("VERSION_INFO")
  File "/home/eric/Desktop/ray-private/python/ray/utils.py", line 324, in _wrapper
    return orig_attr(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 880, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 128.32.38.222:55099. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 439, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 494, in _connect
    raise err
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 572, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 128.32.38.222:55099. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 439, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 494, in _connect
    raise err
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eric/Desktop/ray-private/python/ray/workers/default_worker.py", line 55, in <module>
    info, mode=ray.WORKER_MODE, use_raylet=(args.raylet_name is not None))
  File "/home/eric/Desktop/ray-private/python/ray/worker.py", line 2094, in connect
    driver_id=None)
  File "/home/eric/Desktop/ray-private/python/ray/utils.py", line 128, in push_error_to_driver_through_redis
    ray.gcs_utils.TablePubsub.ERROR_INFO, driver_id, error_data)
  File "/home/eric/Desktop/ray-private/python/ray/utils.py", line 324, in _wrapper
    return orig_attr(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 128.32.38.222:55099. Connection refused.

```

**Comment by robertnishihara** [comment] 2018-10-31 19:41
Closing because I can't reproduce.

**Closed by robertnishihara** 2018-10-31 19:41 UTC
Labels: regression
