### ISSUE TITLE
[adag] Avoid deserialization during CompiledDAGRef's deallocation

### ISSUE THREAD

**Issue by jeffreyjeffreywang** [ray-project/ray#47614] opened 2024-09-11 20:25 UTC
### What happened + What you expected to happen

Although we don't call ray.get, ray.get is called and deserialization still happens when the dag ref is deallocated because of the following code. https://github.com/ray-project/ray/blob/4aea49f5301ac083aed5d016919482afd2f54f83/python/ray/experimental/compiled_dag_ref.py#L80

### Versions / Dependencies

ray master

### Reproduction script

```
a = Actor.remote(0)
with InputNode() as inp:
    dag = a.inc.bind(inp)

compiled_dag = dag.experimental_compile()
ref = compiled_dag.execute(1)
compiled_dag.teardown()

# ref.get() is called upon ref's deallocation -- deserialization still happens
```

### Issue Severity

None

**Comment by rkooo567** [comment] 2024-09-11 23:29
@jeffreyjeffreywang would you be interested in taking this?

**Comment by jeffreyjeffreywang** [comment] 2024-09-12 08:15
@rkooo567 Yup, definitely.

Hey @stephanie-wang @ruisearch42, I just wanted to clarify a few things before I proceed with this issue. You've suggested to release the value of a CompiledDAGRef if `ray.get()` isn't called by the user (https://github.com/ray-project/ray/pull/45951#issuecomment-2168530073). **Could you please help me understand how the following code avoids execution result leak?** https://github.com/ray-project/ray/blob/44dd9a7abd0a153dd11167c8d48cde9b0a9ecfb9/python/ray/experimental/compiled_dag_ref.py#L87-L89

With this code, another issue arises -- attempting to load a python library during program exit (when CompiledDAGRef is destructed) will fail. Please refer to https://github.com/ray-project/ray/pull/47305#discussion_r1738029669 for more context.
```
foo = Foo.remote()
bar = Bar.remote()

with InputNode() as inp:
    dag = MultiOutputNode([foo.increment.bind(inp), bar.decrement.bind(inp)])

dag = dag.experimental_compile()

ref1 = dag.execute(1)
ref2 = dag.execute(1)

assert ref1.get() == [1, -1]

dag.teardown()
# Upon destruction, the DAG will be executed until the latest index.
# However, we attempt to import DAGContext during program exit. 
```

I'm thinking about removing the custom destructor entirely but wanted to understand the implications before doing so.

**Comment by rkooo567** [comment] 2024-09-12 15:02
> With this code, another issue arises -- attempting to load a python library during program exit (when CompiledDAGRef is destructed) will fail. Please refer to https://github.com/ray-project/ray/pull/47305#discussion_r1738029669 for more context.

I think this is because python cannot guarantee all modules exist when `__del__` is called. So I agreed doing clean up this way in a destructor is a bad idea, and it is something we should clean up.

**Comment by ruisearch42** [comment] 2024-09-12 16:03
> Could you please help me understand how the following code avoids execution result leak?

With this code, the python object is retrieved and then immediately goes out of scope. If there are any native buffers underneath, they will also be released.

**Comment by jeffreyjeffreywang** [comment] 2024-09-12 17:02
> With this code, the python object is retrieved and then immediately goes out of scope. If there are any native buffers underneath, they will also be released.

Thank you @ruisearch42, could you give me an example/repro when native buffers are used and therefore this destruction is necessary? I'd like to measure whether the deserialization is necessary.

If deserialization is necessary, we still need to solve the module import issue. We might want to move the deserialization (stepping through the remaining steps in the DAG) to `teardown()`.

**Comment by jeffreyjeffreywang** [comment] 2024-09-12 22:14
This is a duplicate of #46909. Will close both bugs once this issue is addressed.

**Comment by stephanie-wang** [comment] 2024-09-12 22:25
Thanks, @jeffreyjeffreywang for the great questions! The deserialization is necessary because the native buffer is reused for future data. If the reader does not explicitly read and release the buffer, then the buffer cannot be reused for future values. You can reproduce it by returning a numpy array as the DAG output; since numpy arrays are zero-copy, the buffer will be held until the np array in python goes out of scope.

Note that you do not need to deserialize the data in order to release the buffer. We just need to make sure to call the [`ReadAcquire`](https://github.com/ray-project/ray/blob/35b453445b49ad286c08099953c000c3942acf6a/src/ray/core_worker/experimental_mutable_object_manager.h#L180) and `ReadRelease` methods on the buffer (but skip the python-based deserialization).

We do a similar custom destructor for when ObjectRefs and actors go out of scope, so I think you can reuse a similar codepath to avoid the destruction ordering problem, see [here](https://github.com/ray-project/ray/blob/35b453445b49ad286c08099953c000c3942acf6a/python/ray/actor.py#L1380).

**Comment by jeffreyjeffreywang** [comment] 2024-09-13 16:23
Thank you, Stephanie, for the thorough explanation. I'll dig a bit deeper and publish a PR.

**Comment by rkooo567** [comment] 2024-09-14 00:13
Thanks @jeffreyjeffreywang ! Btw, are you in OSS ray slack? We have regular sync up, and you are more than welcome to join!

**Comment by jeffreyjeffreywang** [comment] 2024-09-14 05:24
@rkooo567 Yeah, I just joined couple days ago. Thanks for inviting, I'll keep an eye on the sync up next time and hopefully I'll be able to join! 😄

**Comment by rkooo567** [comment] 2024-09-14 05:36
@anyscalesam can you make sure @jeffreyjeffreywang is invited to next sync?! Thank you!

**Comment by rkooo567** [comment] 2024-11-04 15:55
@jeffreyjeffreywang let me konw if you'd like to talk about this one in person btw!

**Comment by jeffreyjeffreywang** [comment] 2024-11-04 22:06
Hey @rkooo567, I'm down for a chat, but is there anything specific you wanted to talk about? Am I heading towards the wrong direction in 
#48534  that addresses this issue or is there anything else we wanted to tackle along with this?

**Closed** 2024-12-13 07:00 UTC
Labels: bug, good first issue, P1, core, compiled-graphs
