### ISSUE TITLE
[Bug] Tune tutorial "Quick Start" not working with Ray client

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#20379] opened 2021-11-15 18:16 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

I'm trying https://docs.ray.io/en/latest/tune/index.html#quick-start with the Ray client and getting an error

```python
(pid=316) 2021-11-15 10:09:07,349	INFO tune.py:630 -- Total run time: 2.20 seconds (1.96 seconds for the tuning loop).
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-1f157ac0ee08> in <module>
     20     config={
     21         "alpha": tune.grid_search([0.001, 0.01, 0.1]),
---> 22         "beta": tune.choice([1, 2, 3])
     23     })
     24 

~/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py in run(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, search_alg, scheduler, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, queue_trials, reuse_actors, trial_executor, raise_on_failed_trial, callbacks, max_concurrent_trials, loggers, _remote)
    358         _handle_execute_queue()
    359 
--> 360         return ray.get(remote_future)
    361 
    362     del remote_run_kwargs

~/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
    102             # we only convert init function if RAY_CLIENT_MODE=1
    103             if func.__name__ != "init" or is_client_mode_enabled_by_default:
--> 104                 return getattr(ray, func.__name__)(*args, **kwargs)
    105         return func(*args, **kwargs)
    106 

~/anaconda3/lib/python3.7/site-packages/ray/util/client/api.py in get(self, vals, timeout)
     40             timeout: Optional timeout in milliseconds
     41         """
---> 42         return self.worker.get(vals, timeout=timeout)
     43 
     44     def put(self, *args, **kwargs):

~/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py in get(self, vals, timeout)
    347                 op_timeout = MAX_BLOCKING_OPERATION_TIME_S
    348             try:
--> 349                 res = self._get(to_get, op_timeout)
    350                 break
    351             except GetTimeoutError:

~/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py in _get(self, ref, timeout)
    375                 raise
    376             raise err
--> 377         return loads_from_server(resp.data)
    378 
    379     def put(self, vals, *, client_ref_id: bytes = None):

~/anaconda3/lib/python3.7/site-packages/ray/util/client/client_pickler.py in loads_from_server(data, fix_imports, encoding, errors)
    171     return ServerUnpickler(
    172         file, fix_imports=fix_imports, encoding=encoding,
--> 173         errors=errors).load()
    174 
    175 

AttributeError: Can't get attribute 'new_block' on <module 'pandas.core.internals.blocks' from '/Users/pcmoritz/anaconda3/lib/python3.7/site-packages/pandas/core/internals/blocks.py'>
```

### Versions / Dependencies

This is on Ray 1.8.0

### Reproduction script

Start a Ray cluster, connect to it via the client and run e.g.

```
import ray

ray.init("ray://address")

from ray import tune


def objective(step, alpha, beta):
    return (0.1 + alpha * step / 100)**(-1) + beta * 0.1


def training_function(config):
    # Hyperparameters
    alpha, beta = config["alpha"], config["beta"]
    for step in range(10):
        # Iterative training function - can be any arbitrary training procedure.
        intermediate_score = objective(step, alpha, beta)
        # Feed the score back back to Tune.
        tune.report(mean_loss=intermediate_score)


analysis = tune.run(
    training_function,
    config={
        "alpha": tune.grid_search([0.001, 0.01, 0.1]),
        "beta": tune.choice([1, 2, 3])
    })

print("Best config: ", analysis.get_best_config(
    metric="mean_loss", mode="min"))

# Get a dataframe for analyzing trial results.
df = analysis.results_df
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by amogkam** [comment] 2021-11-15 18:17
@pcmoritz can you make sure that you have the same version of pandas on both the client and the server.

@AmeerHajAli @ckw017 this error has come up before. Is there a better error message we can show here?

**Comment by amogkam** [comment] 2021-11-15 18:19
@pcmoritz how are you setting up the dependencies on the server (are you using Ray docker image)? And can you also share what versions of Pandas you have on the client and server?

I can look into this to see if we can pin the version somewhere to avoid the mismatch.

**Comment by pcmoritz** [comment] 2021-11-15 18:22
I had version 1.3.4 on the server and 1.2.0 on the client side, that's likely the cause of the failure.

**Comment by pcmoritz** [comment] 2021-11-15 18:37
After upgrading the laptop version to 1.3.4, it is working. I think the TL;DR here is we need better reporting on mismatches of laptopt/server libraries to avoid such scary error messages.

**Comment by richardliaw** [comment] 2021-11-15 19:00
This is a duplicate of this - https://github.com/ray-project/ray/issues/15407.

**Closed by richardliaw** 2021-11-15 19:00 UTC
Labels: bug, triage
