### ISSUE TITLE
Removal of zombie processes

### ISSUE THREAD

**Issue by jsuarez5341** [ray-project/ray#12337] opened 2020-11-24 07:01 UTC
There's this minor but annoying bug where Ray sometimes leaves zombie processes running, and after a few hours of development involving lots of job start/kills, they consume all the ram and crash the server :/ ... I sadly don't have a repro, but from what I understand, this is a common problem. Not sure if this is a standalone issue or a conflict with some other common library. Best hint I can give is that the zombie processes do not respect the standard quit instruction. You have to kill -9 them manually. Any ideas? Issue is in Ray 1.0, but this has been a thing for a long time
@rkooo567

**Comment by edoakes** [comment] 2020-11-24 19:08
@jsuarez5341 could you provide the output of `ps -aux` that shows the zombie processes?

**Comment by jsuarez5341** [comment] 2020-11-24 23:58
Here you go @edoakes 
`(base) hex@battlestation:~/FileStruct/Git/neural-mmo$ ps aux | grep ray
hex       241734  0.9  0.0 20097208 62308 pts/1  Sl   18:55   0:01 ray::IDLE
hex       241735 15.4  6.0 34415636 3953428 pts/1 Sl  18:55   0:29 ray::RolloutWorker
hex       241736  0.9  0.0 20097208 62444 pts/1  Sl   18:55   0:01 ray::IDLE
hex       241737  0.9  0.0 20097220 62580 pts/1  Sl   18:55   0:01 ray::IDLE
hex       241738 15.3  6.0 34415432 3952580 pts/1 Sl  18:55   0:29 ray::RolloutWorker
hex       241739 15.3  6.0 34415776 3953420 pts/1 Sl  18:55   0:29 ray::RolloutWorker
hex       241740  0.9  0.0 20097208 62300 pts/1  Sl   18:55   0:01 ray::IDLE
hex       241741 15.3  6.0 34283972 3953212 pts/1 Sl  18:55   0:29 ray::RolloutWorker
hex       249319  0.0  0.0   8900   732 pts/1    S+   18:58   0:00 grep ray`

**Comment by rkooo567** [comment] 2020-11-30 06:50
Are these deleted when you run ray stop --force?

**Comment by janblumenkamp** [comment] 2020-12-02 11:09
I second this issue! Noticed it already a few months ago but was never able to reproduce, it just happens randomly.

**Comment by janblumenkamp** [comment] 2020-12-02 11:12
Just had a few random `ray:IDLE` processes again and `ray stop --force` actually killed them, but I am not sure if this is always the case. Will observe and see when it happens next time.

**Comment by jsuarez5341** [comment] 2020-12-02 15:34
Same observation here
```
ps aux | grep ray
hex      2010079  0.7  0.0 19689308 10052 pts/1  Sl   Dec01   9:05 ray::IDLE
hex      2010082  0.7  0.0 19689308 12440 pts/1  Sl   Dec01   9:00 ray::IDLE
hex      2010083  0.7  0.0 19689416 9280 pts/1   Sl   Dec01   9:08 ray::IDLE
hex      2010084  0.7  0.0 19689292 11684 pts/1  Sl   Dec01   9:02 ray::IDLE
hex      2377072  0.0  0.0   8900   732 pts/0    S+   10:32   0:00 grep ray
ray stop --force
Stopped all 4 Ray processes.
ps aux | grep ray
hex      2377083  0.0  0.0   8900   732 pts/0    S+   10:33   0:00 grep ray
```

**Comment by jsuarez5341** [comment] 2020-12-02 16:04
Reran on more zombie workers -- can confirm this kills ray::RolloutWorker processes as well

**Comment by PidgeyBE** [comment] 2020-12-07 10:08
I'm currently investigating a similar issue. I have also not been able yet to make something reproducible, in our case however it seems to be occuring in async actors when multiple calls are done to the same actor.
We are using `ray.kill` to make sure actors get fully cleaned up, but that also doesn't always work:
```
>>> ray.get_actor("68a362a4-f716-4104-ad63-8e0280206020::InferencePipelineActor")
Actor(InferencePipelineActor,32bfbb1701000000)
>>> a=ray.get_actor("68a362a4-f716-4104-ad63-8e0280206020::InferencePipelineActor")
>>> ray.kill(a)
>>> a=ray.get_actor("68a362a4-f716-4104-ad63-8e0280206020::InferencePipelineActor")
>>> ray.kill(a)
>>> ray.get_actor("68a362a4-f716-4104-ad63-8e0280206020::InferencePipelineActor")
Actor(InferencePipelineActor,32bfbb1701000000)
```

**Comment by rkooo567** [comment] 2020-12-08 06:20
One possibility is that we might have some race condition in the shutdown process (since we deallocate cpp code => python, but there are some parts python code accesses cpp code). We definitely need more investigation here since many users suffer from it. It'll be really awesome if any of you guys can create a reproducible script!

**Comment by rkooo567** [comment] 2020-12-08 18:27
I also found processes are not killed when raylets die with some unexpected error (ex, segfault). Do you guys see the same pattern?

**Comment by janblumenkamp** [comment] 2020-12-08 18:37
I think I can reproduce the issue if I send multiple SIGINT in the command line (i.e. press Ctrl+C repeatedly) without waiting for the process to terminate on its own. In that case, the last thing that is printed is something like `[1]    1687004 abort (core dumped)`.  If I send a single SIGINT and wait, ray seems to clean up everything and quit properly.

**Comment by rkooo567** [comment] 2020-12-08 19:42
Oh probably our sigint handler is not idempotent so when it receives multiple of them, it is crashed (and that causes the whole processes to be killed fast).

**Comment by jsuarez5341** [comment] 2020-12-10 20:14
That sounds about right. Quit behavior is pretty wonky -- sometimes, one SIGINT does the job. Normally, it's hammer Ctrl-C repeatedly. Especially (though not always) from within pdb

**Comment by jsuarez5341** [comment] 2021-02-16 22:51
Adding a note here: it seems zombie processes are always created when calling ray workers from a callback inside of a Twisted web socket server. Not exactly a repro I know, but perhaps somebody knows of a possible interaction? E.g. conflict in signal behavior?

**Comment by rkooo567** [comment] 2021-02-16 22:52
I actually verified the singal stuff worked correctly. If you can create a repro script, I think we can try fixing it quickly.

**Comment by hongjisung** [comment] 2021-04-28 13:58
This always happens in specific case when import other local codes.
That import code like `from jobs.next.next import diff`

But copy that code with other directory. it never happens.
That import code like `from utils.diff import diff`

(that files have same code in it)

I cannot understand why this happens....
But python import process would effect on it

**Comment by rkooo567** [comment] 2022-12-08 04:57
I believe this is fixed in the master. If this issue is still coming up, please reopen the issue

**Closed by rkooo567** 2022-12-08 04:57 UTC
Labels: bug, P2

**Comment by jschweiz** [comment] 2023-06-23 15:08
Hi! I'm having a similar issue: I'm using ray with python and `pytest`, and the code of the test is:
```
ray.init(num_cpus=10)
# blahblah create some ray actors
ray.shutdown()
```
When I check the subprocesses of my python main after the shutdown, I see 2 zombie process that I can't kill from my python main process (`log_monitor.py` and `monitor.py`) but which disappear when the main process exits. This is painful because it does not clean properly the env between each test. 

Any idea what might cause that?

**Comment by rkooo567** [comment] 2023-06-29 03:56
We @jschweiz can you actually provide a script I can run to reproduce it?

**Comment by ilml** [comment] 2023-10-05 04:06
Hi team, i can confirm that this issue still persists. I'm running on version 2.7.0, and my use case is to use vLLM with distributed inference. By default vLLM will use Ray as backend, and if I got GPU OOM etc. and the program exit unexpectedly, the Ray processed can't be killed and will become zombie process.

**Comment by Superskyyy** [comment] 2024-01-15 14:26
I persistently see zombie processes (defunct) within my devcontainer when starting ray on an alternative port (idk if its relevant info). it says:

```
Stopped only 0 out of 6 Ray processes within the grace period 16 seconds. Set `-v` to see more details. Remaining processes [psutil.Process(pid=16373, name='raylet', status='zombie', started='09:20:36'), psutil.Process(pid=16255, name='python', status='zombie', started='09:20:35'), psutil.Process(pid=16374, name='python', status='zombie', started='09:20:36'), psutil.Process(pid=16256, name='python', status='zombie', started='09:20:35'), psutil.Process(pid=16254, name='python', status='zombie', started='09:20:35'), psutil.Process(pid=16175, name='gcs_server', status='zombie', started='09:20:34')] will be forcefully terminated.
You can also use `--force` to forcefully terminate processes or set higher `--grace-period` to wait longer time for proper termination.
```

**Comment by rkooo567** [comment] 2024-01-16 05:09
@ilml I think that's a known issue, and it must've been fixed in the latest version Ray!

**Comment by rkooo567** [comment] 2024-01-16 05:10
@Superskyyy does it happen in the latest master?

**Comment by Superskyyy** [comment] 2024-01-16 05:25
> @Superskyyy does it happen in the latest master?

yes, i use a nightly build for python3.10. 

more context: I'm developing on ray, so I enabled the symbolic links on latest master branch from the latest nightly build. (shouldn't matter right?) 

Environment is bookworm python3.10, a pretty standard devcontainer. Everytime I do ray stop it leaves a bunch of zombie processes.

**Comment by rkooo567** [comment] 2024-01-16 22:17
It'd be great if you create a new issue with a repro script. We can investigate it shortly if you create an issue and tag me!

**Comment by Superskyyy** [comment] 2024-01-17 02:38
> It'd be great if you create a new issue with a repro script. We can investigate it shortly if you create an issue and tag me!

Cool, I will try to share the manifest that creates the devcontainer and ray. Thanks!
