### ISSUE TITLE
[Ray General] Python 3.11 support on macos 

### ISSUE THREAD

**Issue by yinweisu** [ray-project/ray#35177] opened 2023-05-09 18:01 UTC
### Description

Currently ray can be installed on both linux and windows with python 3.11 but not macos. Wonder when would it be supported?

**Comment by ddelange** [comment] 2023-05-11 16:16
potential duplicate of https://github.com/ray-project/ray/issues/31362

**Comment by rkooo567** [comment] 2023-05-15 21:22
We will close it as a duplicate of ^.

**Closed by rkooo567** 2023-05-15 21:22 UTC
Labels: enhancement, triage
