### ISSUE TITLE
[core] ObjectRef-to-ActorHandle losts ref to actor after `ray.get`

### ISSUE THREAD

**Issue by rynewang** [ray-project/ray#44991] opened 2024-04-26 09:08 UTC
### What happened + What you expected to happen

If an `ActorHandle` is (recursively) in an ObjectRef, Ray should retain the actor's ref count until last ObjectRef is gone. However:

```py
import ray
ray.init()

@ray.remote
class A:
    def __init__(self):
        pass
    def f(self):
        return 1

@ray.remote
def wrapper():
    return A.remote()

a_ref = wrapper.remote()

# This works
a = ray.get(a_ref)
print(a.f.remote())

# This does not work
print(ray.get(ray.get(a_ref).f.remote()))
```
Output:
```
1
Traceback (most recent call last):
  File "/home/ray/default/actor_ref.py", line 19, in <module>
    print(ray.get(ray.get(a_ref).f.remote()))
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/actor.py", line 202, in remote
    return self._remote(args, kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/util/tracing/tracing_helper.py", line 426, in _start_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/actor.py", line 327, in _remote
    return invocation(args, kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/actor.py", line 306, in invocation
    raise RuntimeError("Lost reference to actor")
RuntimeError: Lost reference to actor
```

Note that even we have a reference `a` in place, the last line still raises.

### Versions / Dependencies

master

### Reproduction script

see above

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jjyao** [comment] 2024-04-29 21:35
I think it's duplicate of #6265

**Closed by jjyao** 2024-04-29 21:35 UTC
Labels: bug, triage, core
