### ISSUE TITLE
Release test dataset_shuffle_push_based_random_shuffle_100tb.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#39527] opened 2023-09-10 10:02 UTC
Release test **dataset_shuffle_push_based_random_shuffle_100tb.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2148#018a7975-874a-4162-b13f-d6d28a01da77 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment] 2023-09-16 18:46
Test has been failing for far too long. Jailing.

**Comment by can-anyscale** [comment] 2023-09-27 21:37
Close to see if it is fixed

**Comment by can-anyscale** [comment] 2023-09-30 23:13
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2204#018ae702-70b6-4d83-b444-cb40c2b7c832

**Comment by can-anyscale** [comment] 2023-10-03 00:59
Just FYI @scottjlee , this test has been failing more than a month. I think @bveeramani and myself previously tried to bisect but we failed (the test requires some type of number of machines that make it hard to run).

**Comment by scottjlee** [comment] 2023-10-03 01:00
yeah i have been slowly bisecting this for the past few weeks as well, but it's slow going (due to the reasons you mentioned), and also got inundated with a bunch of other oncall requests. Still looking into it, thanks for bumping

**Comment by stephanie-wang** [comment] 2023-10-16 18:43
@can-anyscale is it okay to close this to try running the test again? Looks like it passed 10/1-10/6. I'd like to get the metrics on memory usage per node on a fresh run too.

**Comment by scottjlee** [comment] 2023-10-16 18:45
wait, this test runs weekly right? are there manual runs for those dates where the 100TB test succeeds? @stephanie-wang

**Comment by stephanie-wang** [comment] 2023-10-16 18:58
> wait, this test runs weekly right? are there manual runs for those dates where the 100TB test succeeds? @stephanie-wang

Hmm not sure how the tests were triggered, but I see them [here](https://b534fd88.us1a.app.preset.io/superset/dashboard/19/?native_filters_key=_PivmtbWAj8TtReb9gyPePf2xNmKbqbHQ4QubLBMF95JyDn9yXlrK2ypm7hX_ZhW).

**Comment by stephanie-wang** [comment] 2023-10-16 23:10
The root cause is probably excessive task OOM failures, but not sure if that's a regression in Data, regression in some other cluster env, or just an inherent issue with the test setup. Seems we've had worker OOMs in much older runs too, so I don't think it's a release blocker for 2.8.

Since the root cause is excessive task OOM, there are a few options to handle for 2.9:
- There might be a memory leak regression in the data task. This is the most important thing to look into
- Have a smarter way to prevent task OOM failures (this has been discussed in the past but never prioritized) - i.e. wait to retry OOM-killed tasks / adjust Data scheduling policy to account for memory usage
- Update the test to ensure we don't OOM (by adjusting instance type, number of partitions, etc) - recommend we do this anyway so that the test is more stable in the future

**Comment by can-anyscale** [comment] 2023-10-18 03:06
I mark the test as unstable so it won't create release blocker for 2.8 release: https://github.com/ray-project/ray/pull/40437

**Comment by anyscalesam** [comment] 2023-11-07 19:30
@stephanie-wang are you still planning on investigating further and implementing some/all of the options above for ray29?

**Comment by stephanie-wang** [comment] 2023-11-13 19:33
This issue may have been fixed already since we had some failures in related tests. Let me trigger the test now, and will try to investigate if it's still an issue.

**Comment by anyscalesam** [comment] 2023-11-18 01:22
@stephanie-wang did the test pass?

**Comment by can-anyscale** [comment] 2023-11-18 05:02
let's close to run the test in this weekly run; the issue will re-open itself if the test doesn't pass

**Comment by can-anyscale** [comment] 2023-11-18 15:44
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release/builds/1661#018be237-2f08-41eb-b5c6-043d94533e36

**Comment by stephanie-wang** [comment] 2023-11-20 23:28
Ah thanks. It looks like there is a real memory regression in Data but seems it was also failing in 2.8. I think we can ignore for now and address as p0 for 2.10.

**Comment by can-anyscale** [comment] 2024-01-06 12:05
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release/builds/5289#018cde80-6077-4406-a258-14dd970f341e

**Comment by stephanie-wang** [comment] 2024-01-09 16:29
> Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release/builds/5289#018cde80-6077-4406-a258-14dd970f341e

Ah sorry, introduced a bug in the test script...

**Closed** 2024-01-09 18:33 UTC
Labels: bug, P1, data, release-test, jailed-test, unstable-release-test, ray 2.10

**Comment by can-anyscale** [comment] 2024-01-13 14:49
Test passed on latest run: https://buildkite.com/ray-project/release/builds/5909#018d0243-4275-4ac6-8203-7bfc058255f5
