### ISSUE TITLE
Why batch in ReplayActor.add_batch has the "weights" key? 

### ISSUE THREAD

**Issue by zhan0903** [ray-project/ray#4721] opened 2019-05-01 00:56 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem

What does the key "weights" stand for? And where the "weights" come from? Thanks.

### Source code / logs

In async_replay_optimizer.ReplayActor.add_batch
```python
...
  for row in s.rows():
                    self.replay_buffers[policy_id].add(
                        row["obs"], row["actions"], row["rewards"],
                        row["new_obs"], row["dones"], row["weights"])
...
```

**Comment by ericl** [comment] 2019-05-02 03:32
This seems to be a duplicate of https://github.com/ray-project/ray/issues/4730

**Closed by ericl** 2019-05-02 03:32 UTC
