### ISSUE TITLE
[dataframes] Travis test failure in test_groupby.py.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#2136] opened 2018-05-25 07:07 UTC
I saw the following test failure in https://github.com/ray-project/ray/pull/2133. It seems unlikely to be related to that PR.

```
python/ray/dataframe/test/test_groupby.py ..F.[36m                           [100%][0m

=================================== FAILURES ===================================
[31m[1m____________________________ test_large_row_groupby ____________________________[0m

[1m    def test_large_row_groupby():[0m
[1m        pandas_df = pandas.DataFrame(np.random.randint(0, 8, size=(100, 4)),[0m
[1m                                     columns=list('ABCD'))[0m
[1m    [0m
[1m        ray_df = from_pandas(pandas_df, 2)[0m
[1m    [0m
[1m        by = pandas_df['A'].tolist()[0m
[1m        n = 4[0m
[1m    [0m
[1m        ray_groupby = ray_df.groupby(by=by)[0m
[1m        pandas_groupby = pandas_df.groupby(by=by)[0m
[1m    [0m
[1m        ray_groupby_equals_pandas(ray_groupby, pandas_groupby)[0m
[1m        test_ngroups(ray_groupby, pandas_groupby)[0m
[1m        test_skew(ray_groupby, pandas_groupby)[0m
[1m        test_ffill(ray_groupby, pandas_groupby)[0m
[1m        test_sem(ray_groupby, pandas_groupby)[0m
[1m        test_mean(ray_groupby, pandas_groupby)[0m
[1m        test_any(ray_groupby, pandas_groupby)[0m
[1m        test_min(ray_groupby, pandas_groupby)[0m
[1m        test_idxmax(ray_groupby, pandas_groupby)[0m
[1m        test_ndim(ray_groupby, pandas_groupby)[0m
[1m        test_cumsum(ray_groupby, pandas_groupby)[0m
[1m        test_pct_change(ray_groupby, pandas_groupby)[0m
[1m        test_cummax(ray_groupby, pandas_groupby)[0m
[1m    [0m
[1m        apply_functions = [lambda df: df.sum(), lambda df: -df][0m
[1m        for func in apply_functions:[0m
[1m            test_apply(ray_groupby, pandas_groupby, func)[0m
[1m    [0m
[1m        test_dtypes(ray_groupby, pandas_groupby)[0m
[1m        test_first(ray_groupby, pandas_groupby)[0m
[1m        test_backfill(ray_groupby, pandas_groupby)[0m
[1m        test_cummin(ray_groupby, pandas_groupby)[0m
[1m        test_bfill(ray_groupby, pandas_groupby)[0m
[1m        test_idxmin(ray_groupby, pandas_groupby)[0m
[1m        # test_prod(ray_groupby, pandas_groupby) causes overflows[0m
[1m        test_std(ray_groupby, pandas_groupby)[0m
[1m    [0m
[1m        agg_functions = ['min', 'max'][0m
[1m        for func in agg_functions:[0m
[1m            test_agg(ray_groupby, pandas_groupby, func)[0m
[1m            test_aggregate(ray_groupby, pandas_groupby, func)[0m
[1m    [0m
[1m        test_last(ray_groupby, pandas_groupby)[0m
[1m        test_mad(ray_groupby, pandas_groupby)[0m
[1m        test_rank(ray_groupby, pandas_groupby)[0m
[1m        test_max(ray_groupby, pandas_groupby)[0m
[1m        test_var(ray_groupby, pandas_groupby)[0m
[1m        test_len(ray_groupby, pandas_groupby)[0m
[1m        test_sum(ray_groupby, pandas_groupby)[0m
[1m        test_ngroup(ray_groupby, pandas_groupby)[0m
[1m        test_nunique(ray_groupby, pandas_groupby)[0m
[1m>       test_median(ray_groupby, pandas_groupby)[0m

[1m[31mpython/ray/dataframe/test/test_groupby.py[0m:257: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[1m[31mpython/ray/dataframe/test/test_groupby.py[0m:526: in test_median
[1m    ray_df_equals_pandas(ray_groupby.median(), pandas_groupby.median())[0m
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

ray_df =      A    B    C    D
0  0.0  3.0  5.0  5.0
1  1.0  3.0  2.0  4.0
2  2.0  3.0  3.0  1.0
3  3.0  3.0  4.0  3.0
4  4.0  5.0  4.0  5.0
5  5.0  3.0  4.0  3.0
6  6.0  4.0  3.0  5.0
7  7.0  2.0  5.0  2.0
pandas_df =    A  B  C  D
0  0  3  5  5
1  1  3  2  4
2  2  3  3  1
3  3  3  4  3
4  4  5  4  5
5  5  3  4  3
6  6  4  3  5
7  7  2  5  2

[1m    @pytest.fixture[0m
[1m    def ray_df_equals_pandas(ray_df, pandas_df):[0m
[1m        assert isinstance(ray_df, pd.DataFrame)[0m
[1m>       assert to_pandas(ray_df).equals(pandas_df)[0m
[1m[31mE       assert False[0m
[1m[31mE        +  where False = <bound method NDFrame.equals of      A    B    C    D\n0  0.0  3.0  5.0  5.0\n1  1.0  3.0  2.0  4.0\n2  2.0  3.0  3.0  1.0\n3  3.0  3.0  4.0  3.0\n4  4.0  5.0  4.0  5.0\n5  5.0  3.0  4.0  3.0\n6  6.0  4.0  3.0  5.0\n7  7.0  2.0  5.0  2.0>(   A  B  C  D\n0  0  3  5  5\n1  1  3  2  4\n2  2  3  3  1\n3  3  3  4  3\n4  4  5  4  5\n5  5  3  4  3\n6  6  4  3  5\n7  7  2  5  2)[0m
[1m[31mE        +    where <bound method NDFrame.equals of      A    B    C    D\n0  0.0  3.0  5.0  5.0\n1  1.0  3.0  2.0  4.0\n2  2.0  3.0  3.0  1.0\n3  3.0  3.0  4.0  3.0\n4  4.0  5.0  4.0  5.0\n5  5.0  3.0  4.0  3.0\n6  6.0  4.0  3.0  5.0\n7  7.0  2.0  5.0  2.0> =      A    B    C    D\n0  0.0  3.0  5.0  5.0\n1  1.0  3.0  2.0  4.0\n2  2.0  3.0  3.0  1.0\n3  3.0  3.0  4.0  3.0\n4  4.0  5.0  4.0  5.0\n5  5.0  3.0  4.0  3.0\n6  6.0  4.0  3.0  5.0\n7  7.0  2.0  5.0  2.0.equals[0m
[1m[31mE        +      where      A    B    C    D\n0  0.0  3.0  5.0  5.0\n1  1.0  3.0  2.0  4.0\n2  2.0  3.0  3.0  1.0\n3  3.0  3.0  4.0  3.0\n4  4.0  5.0  4.0  5.0\n5  5.0  3.0  4.0  3.0\n6  6.0  4.0  3.0  5.0\n7  7.0  2.0  5.0  2.0 = to_pandas(     A    B    C    D\n0  0.0  3.0  5.0  5.0\n1  1.0  3.0  2.0  4.0\n2  2.0  3.0  3.0  1.0\n3  3.0  3.0  4.0  3.0\n4  4.0  5.0  4.0  5.0\n5  5.0  3.0  4.0  3.0\n6  6.0  4.0  3.0  5.0\n7  7.0  2.0  5.0  2.0)[0m

[1m[31mpython/ray/dataframe/test/test_groupby.py[0m:22: AssertionError
[31m[1m===================== 1 failed, 3 passed in 183.53 seconds =====================[0m

travis_time:end:26c02634:start=1527224588186385052,finish=1527224772764063391,duration=184577678339
[0K
[31;1mThe command "python -m pytest python/ray/dataframe/test/test_groupby.py" exited with 1.[0m
```

**Comment by devin-petersohn** [comment] 2018-05-25 15:19
I see the failure, but interestingly it did not happen in any of the other tests. Also I cannot reproduce locally.

I reran the test, even though the PR was merged, just to see if it happens again. I am not aware of any sources of non-determinism in the test code or implementation, so I will have to look into this deeper.

**Comment by robertnishihara** [comment] 2018-05-26 05:01
The issue above seems to be that `ray_df` consists of floats and `pandas_df` consists of ints. At least that's what it looks like from the log. Strange that it's non-deterministic though.

**Comment by devin-petersohn** [comment] 2018-05-26 07:26
We figured it out. The issue is that pandas uses a different implementation for `groupby` + `median`, and force casts it. I am curious as to why it doesn't fail all the time. We're discussing a way to move forward because the cast is expensive (element-wise cast then check equality in pandas) and I hope to avoid it.

**Comment by devin-petersohn** [comment] 2018-07-30 22:36
Closing as code base was moved: https://github.com/modin-project/modin

**Closed by devin-petersohn** 2018-07-30 22:36 UTC
Labels: test failure
