### ISSUE TITLE
[Data] Absymal performance & disk usage when reading files from S3

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#29374] opened 2022-10-14 20:20 UTC
### What happened + What you expected to happen

I've ran a simple script to read two files from S3 (partitions of NYC taxi dataset). With pure pyarrow, this is done in <10 seconds. With Ray Data, this takes over 350 seconds, while also taking up a lot of disk space and memory.

The disk space is not cleaned up afterwards, too, meaning if I run the repro script twice, the node crashes due to all disk space being filled.

I ran this on an Anyscale Workspace (poke me on slack for link) consisting of a single m5.2xlarge instance.

### Versions / Dependencies

4f07b6139b9f9f1356419012e63c7a27e2b8d78d

### Reproduction script

```python
import time
from pyarrow import parquet as pq
import gc
import ray

s3_files = ['s3://anonymous@air-example-data/ursa-labs-taxi-data/by_year/2019/05/data.parquet/359c21b3e28f40328e68cf66f7ba40e2_000000.parquet',
 's3://anonymous@air-example-data/ursa-labs-taxi-data/by_year/2019/06/data.parquet/ab5b9d2b8cc94be19346e260b543ec35_000000.parquet']

# Reading one file with pyarrow

start = time.time()
dataset = pq.read_table(s3_files[0]).to_pandas()
data_loading_time = time.time() - start
print(f"Data loading time for pyarrow, 1 file : {data_loading_time} seconds")

del dataset
gc.collect()

# Reading two files sequentially with pyarrow

start = time.time()
dataset = pq.read_table(s3_files[0]).to_pandas()
dataset = pq.read_table(s3_files[1]).to_pandas()
data_loading_time = time.time() - start
print(f"Data loading time for pyarrow, 2 files : {data_loading_time} seconds")

del dataset
gc.collect()

ray.init()

# Reading one file with ray.data

start = time.time()
dataset = ray.data.read_parquet(s3_files[0]).to_pandas(float("inf"))
data_loading_time = time.time() - start
print(f"Data loading time for ray.data, 1 file : {data_loading_time} seconds")

del dataset
gc.collect()

ray.shutdown()
ray.init()

# Reading two files with ray.data

start = time.time()
dataset = ray.data.read_parquet(s3_files).to_pandas(float("inf"))
data_loading_time = time.time() - start
print(f"Data loading time for ray.data, 2 files : {data_loading_time} seconds")

ray.shutdown()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by clarkzinzow** [comment] 2022-10-14 22:33
Is data being spilled to disk on the read? Is there anything useful being logged, e.g. file sampling taking a long time? Have you checked out the [Datasets stats](https://docs.ray.io/en/master/data/performance-tips.html#debugging-statistics) to see if there's any signal there as to why it's slow?

We should try to see if there's anything unexpected in the benchmark (e.g. spilling to disk), and if not, try to find the optimal configuration, and then see if we can align the default config to be closer to the optimal config without sacrificing stability.

A few things to note:
1. `ray.data.read_parquet().to_pandas()` will read data into Arrow Tables, then converted into a single Pandas DataFrame, so this isn't just measuring a read. If you wanted to purely measure the read, I would do something like `ray.data.read_parquet(s3_files).take_all()`.
2. You may want to try hard-coded parallelism, e.g. `ray.data.read_parquet(s3_files, parallelism=len(s3_files))`, to see if Datasets' automatic parallelism determination (which will sample data from the files) is slowing things down.
3. You may want to try the [bulk Parquet API](https://docs.ray.io/en/master/data/api/input_output.html#ray.data.read_parquet_bulk), `ray.data.read_parquet_bulk()`, which bypasses some expensive metadata operations.

**Comment by Yard1** [comment] 2022-10-14 23:54
Data is defined being spilled to disk. I'll try the things you suggested. I had ran it without to pandas previously (with a simple batch transform instead) and the results were similar.

**Comment by clarkzinzow** [comment] 2022-10-15 00:19
I experimented with this benchmark + a few different tweaks, it looks like there might have been a regression in Parquet read performance that we didn't catch. I'd be happy to pair on investigating this!

**Comment by clarkzinzow** [comment] 2022-10-24 21:30
When removing the Pandas conversion, which can be a confuser, the biggest contributor to this being slow appears to be:
1. disk spilling,
2. file sampling.

(1) is the biggest culprit; without disk spilling, Datasets is a few seconds slower on a single file and ~4 seconds faster on two files, since file sampling has a further added time of 3-5 seconds. Without file sampling, Datasets is only a second slower on a single file (due to overhead of Ray) and is ~5 seconds faster on two files.

I'm going to call this a non-issue for now, since disk spilling seemed to be the main culprit. We should keep an eye on the file sampling, though, which can be nearly as expensive as the actual read in some cases.

**Comment by clarkzinzow** [comment] 2022-10-24 21:31
Closing this for now but will make a note for ongoing benchmarking work that we should have a very basic parallel reading benchmark.

**Closed by clarkzinzow** 2022-10-24 21:31 UTC
Labels: bug, P1, datasets

**Comment by clarkzinzow** [comment] 2022-10-24 21:36
@Yard1 Ping me on Slack if this was blocking a benchmark or release test, we can ensure that the benchmark/test is well-formed and that e.g. spilling to disk is avoided. At that point, we can open up some follow-up P1s for optimizing e.g. file sampling and the like.

**Comment by Yard1** [comment] 2022-10-25 19:58
This was actually caused by https://github.com/ray-project/ray/issues/29673
