### ISSUE TITLE
[Ray] Cannot have empty byte string (b"")  argument for remote calls

### ISSUE THREAD

**Issue by alindkhare** [ray-project/ray#6944] opened 2020-01-28 22:53 UTC
### What is the problem?
Ray version: 0.8.1
Getting this traceback for below script - 
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
IndexError: Out of bounds on buffer access (axis 0)
Exception ignored in: 'ray._raylet.prepare_args'
IndexError: Out of bounds on buffer access (axis 0)
---------------------------------------------------------------------------
RayTaskError(AssertionError)              Traceback (most recent call last)
<ipython-input-1-f78ed339f691> in <module>
      4     return a
      5 ray.init()
----> 6 result = ray.get(f.remote(b""))
      7 print(result)

~/anaconda3/envs/check-ray/lib/python3.6/site-packages/ray/worker.py in get(object_ids, timeout)
   1490                     worker.core_worker.dump_object_store_memory_usage()
   1491                 if isinstance(value, RayTaskError):
-> 1492                     raise value.as_instanceof_cause()
   1493                 else:
   1494                     raise value

RayTaskError(AssertionError): ray_worker (pid=19607, ip=130.207.124.200)
  File "python/ray/_raylet.pyx", line 633, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 634, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 521, in ray._raylet.deserialize_args
  File "/nethome/akhare39/anaconda3/envs/check-ray/lib/python3.6/site-packages/ray/signature.py", line 163, in recover_args
    "Flattened arguments need to be even-numbered. See `flatten_args`.")
AssertionError: Flattened arguments need to be even-numbered. See `flatten_args`.
```
### Reproduction (REQUIRED)
```python
import ray
@ray.remote
def f(a):
    return a
ray.init()
result = ray.get(f.remote(b""))
print(result)
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by alindkhare** [comment] 2020-01-28 22:54
@simon-mo

**Comment by simon-mo** [comment] 2020-01-28 23:29
@chaokunyang is there a change from ray streaming/xlang that prevent `prepare_args` from serializing zero length bytes? 

It seems like `&buffer[0]` will error in cython. 
```
elif type(arg) is bytes:
            buffer = arg
            size = buffer.nbytes
            arg_data = dynamic_pointer_cast[CBuffer, LocalMemoryBuffer](
                make_shared[LocalMemoryBuffer](
                    <uint8_t*>(&buffer[0]), size, True))
```
but if we do 
```
if len(arg) == 0:
                arg_data = dynamic_pointer_cast[CBuffer, LocalMemoryBuffer](
                    make_shared[LocalMemoryBuffer](0)
                )
```
the deserialization will fail and print out 
```
*** Aborted at 1580253913 (unix time) try "date -d @1580253913" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 90230 (TID 0x118952dc0) stack trace: ***
    @     0x7fff6ca63b1d _sigtramp
    @        0x10dde63ec call_function
    @        0x10e0ffdea __Pyx_PyObject_GenericGetAttrNoDict()
    @        0x10e1025b2 __pyx_f_3ray_7_raylet_6Buffer_make()
    @        0x10e1497f7 __pyx_f_3ray_7_raylet_deserialize_args()
    @        0x10e13d6bd __pyx_f_3ray_7_raylet_execute_task()
    @        0x10e13500f __pyx_f_3ray_7_raylet_task_execution_handler()
    @        0x10e14ff8b std::__1::__function::__func<>::operator()()
    @        0x10e1895e5 ray::CoreWorker::ExecuteTask()
    @        0x10e1bb23e std::__1::__function::__func<>::operator()()
    @        0x10e1e6090 ray::CoreWorkerDirectTaskReceiver::HandlePushTask()::$_2::operator()()
    @        0x10e1e5365 ray::CoreWorkerDirectTaskReceiver::HandlePushTask()
    @        0x10e1c6d4e boost::asio::detail::completion_handler<>::do_complete()
    @        0x10e1b3e90 boost::asio::detail::scheduler::do_run_one()
    @        0x10e1b3a02 boost::asio::detail::scheduler::run()
    @        0x10e192382 ray::CoreWorker::StartExecutingTasks()
    @        0x10e117f0b __pyx_pw_3ray_7_raylet_10CoreWorker_3run_task_loop()
    @        0x10dd10f95 _PyCFunction_FastCallDict
    @        0x10dde638f call_function
    @        0x10dde3ef2 _PyEval_EvalFrameDefault
    @        0x10dde673c fast_function
    @        0x10dde63ec call_function
    @        0x10dde3ef2 _PyEval_EvalFrameDefault
    @        0x10ddd7659 _PyEval_EvalCodeWithName
    @        0x10de3010c PyRun_FileExFlags
    @        0x10de2f5e4 PyRun_SimpleFileExFlags
    @        0x10de562a6 Py_Main
    @        0x10dc88009 main
    @     0x7fff6c8622e5 start
    @                0xc (unknown)
```

**Comment by chaokunyang** [comment] 2020-02-03 01:16
@simon-mo `&buffer[0]`  is a bug. But `deserialize_args` shouldn't fail. Since there won't be a empty buffer of length 0, maybe this is a problem existed before. I'll look into this and submit a PR after I figured out.

**Comment by raulchen** [comment] 2020-02-03 03:05
I think @jovany-wang has encountered and fixed this bug in our internal version.

**Comment by jovany-wang** [comment] 2020-02-03 07:18
Yes, I have ran into this issue before in xlang. I‘m not sure it's the same issue as this one.

Anyway, it's actually a bug, I'll look into it later as well.

**Comment by chaokunyang** [comment] 2020-02-04 12:38
After new serialization introduced in #6948, the error is:
```
PC: @                0x0 (unknown)
*** SIGABRT (@0x7fff711a7b66) received by PID 30645 (TID 0x7fffa970c380) stack trace: ***
    @     0x7fff71365f5a _sigtramp
    @        0x10032b279 PyErr_Occurred
    @     0x7fff711031ae abort
    @        0x10807f679 google::logging_fail()
    @        0x10807f66a google::LogMessage::Fail()
    @        0x10807e548 google::LogMessage::SendToLog()
    @        0x10807eb9c google::LogMessage::Flush()
    @        0x10807ec6f google::LogMessage::~LogMessage()
    @        0x107cf5a05 arrow::util::ArrowLog::~ArrowLog()
    @        0x1089400c7 arrow::py::PyBuffer::Init()
    @        0x108940159 arrow::py::PyBuffer::FromPyObject()
    @        0x107ac80bf __pyx_pw_7pyarrow_3lib_131py_buffer()
    @        0x100d8e958 __Pyx_PyObject_CallMethO()
    @        0x100d975e9 __pyx_f_3ray_7_raylet_write_serialized_object()
    @        0x100db09c1 __pyx_f_3ray_7_raylet_prepare_args()
    @        0x100da2efa __pyx_pw_3ray_7_raylet_10CoreWorker_29submit_task()
    @        0x100295967 _PyCFunction_FastCallDict
    @        0x100317927 call_function
    @        0x1003140d2 _PyEval_EvalFrameDefault
    @        0x10031838f _PyEval_EvalCodeWithName
    @        0x100318c41 fast_function
    @        0x100317901 call_function
    @        0x1003140d2 _PyEval_EvalFrameDefault
    @        0x10031838f _PyEval_EvalCodeWithName
    @        0x100318c41 fast_function
    @        0x100317901 call_function
    @        0x100314171 _PyEval_EvalFrameDefault
    @        0x10031838f _PyEval_EvalCodeWithName
    @        0x100318c41 fast_function
    @        0x100317901 call_function
    @        0x1003140d2 _PyEval_EvalFrameDefault
    @        0x10031838f _PyEval_EvalCodeWithName
Abort trap: 6
```
It's failed in pyarrow.py_buffer():
```cpp
Status PyBuffer::Init(PyObject* obj) {
  if (!PyObject_GetBuffer(obj, &py_buf_, PyBUF_ANY_CONTIGUOUS)) {
    data_ = reinterpret_cast<const uint8_t*>(py_buf_.buf);
    ARROW_CHECK_NE(data_, nullptr) << "Null pointer in Py_buffer";
    size_ = py_buf_.len;
    capacity_ = py_buf_.len;
    is_mutable_ = !py_buf_.readonly;
    if (is_mutable_) {
      mutable_data_ = reinterpret_cast<uint8_t*>(py_buf_.buf);
    }
    return Status::OK();
  } else {
    return ConvertPyError(StatusCode::Invalid);
  }
}
```
It caused by `NULL` buffer when `make_shared[LocalMemoryBuffer](0)`. I'll fix this

**Comment by jovany-wang** [comment] 2020-02-10 04:10
@alindkhare  just FYI: The PR to fix this issue was merged.

**Closed** 2020-02-10 06:58 UTC
Labels: bug
