### ISSUE TITLE
Ray generating core dump on Program abort

### ISSUE THREAD

**Issue by subbareddydagumati** [ray-project/ray#12505] opened 2020-11-30 20:28 UTC
When program/script abort while running ray processes. It's generating core dump.
Please follow the below procedure to re-create issue @rkooo567 

Underlying OS:
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"

sample program to re-create issue "ray_core_dump_issue.py"

````
import ray
import time, datetime
import sys, os

@ray.remote
def sample_check(batch):
    print(f"Batch:{batch}")
    a=10
    b = a + a
    time.sleep(10)
    print(b)
    return


def split_proc(proc_cnt, batch_size):
    start_time = time.time()
    ray.init(dashboard_host="0.0.0.0",num_cpus=proc_cnt)
    total_batches = batch_size
    ret_ids = []
    while total_batches!=0:
        total_batches = total_batches -1
        print(f"Batch Number:{total_batches}")
        red_id= sample_check.remote( total_batches)
        ret_ids.append(red_id)
    ret = ray.get(ret_ids)
    ray.shutdown()

if __name__ == "__main__":
    split_proc(8, 12)


1) Pull the docker image
docker pull subbareddy425/python36-ray:1.0.0

2) Start the Docker container
 docker run -d -it --name ray-core-issue subbareddy425/python36-ray:1.0.0 bash

3) Exec console to docker container
  docker exec -it ray-core-issue bash
  
4) Run the python program in the directory /apps/python_scripts/

cd /apps/python_scripts/
python3 ray_core_dump_issue.py

5) it will create core dump in the current directory program ran

bash-4.2# ls -ltrh
total 52M
-rw-r----- 1 root root  649 Nov 30 19:31 ray_core_dump_issue.py
-rw------- 1 root root 153M Nov 30 19:47 core.41

**Comment by rkooo567** [comment] 2020-11-30 20:32
Can you also post the code inside `ray_core_dump_issue.py`?

**Comment by subbareddydagumati** [comment] 2020-11-30 20:45
ray_core_dump_issue.py

```
import ray
import time, datetime
import sys, os

@ray.remote
def sample_check(batch):
    print(f"Batch:{batch}")
    a=10
    b = a + a
    time.sleep(10)
    print(b)
    return


def split_proc(proc_cnt, batch_size):
    start_time = time.time()
    ray.init(dashboard_host="0.0.0.0",num_cpus=proc_cnt)
    total_batches = batch_size
    ret_ids = []
    while total_batches!=0:
        total_batches = total_batches -1
        print(f"Batch Number:{total_batches}")
        red_id= sample_check.remote( total_batches)
        ret_ids.append(red_id)
    ret = ray.get(ret_ids)
    ray.shutdown()

if __name__ == "__main__":
    split_proc(8, 12)
```

**Comment by crystalww** [comment] 2020-12-01 06:29
I've met this too in ray 1.0.0. The core dump files are quite large.

**Comment by rkooo567** [comment] 2020-12-01 17:02
Another question. After core dump is created, do you guys still see the worker process, or is it killed properly?

**Comment by subbareddydagumati** [comment] 2020-12-01 17:13
It will left with idle sessions. But, In the test program I created, It able to clear all the processes.

**Comment by subbareddydagumati** [comment] 2020-12-04 19:07
Today it generated 1.9TB core dump files

bash-4.2# ls -ltrh
total 1.9T
-rw-r--r-- 1 root root 7.9K Dec  3 23:16 hhc.py
-rw-r--r-- 1 root root    0 Dec  3 23:16 __init__.py
-rw-r--r-- 1 root root  15K Dec  3 23:16 severity_rating.py
-rw-r--r-- 1 root root  33K Dec  3 23:16 proactive_maintenance.py
-rw------- 1 root root 184M Dec  4 06:20 core.216
-rw------- 1 root root 111G Dec  4 12:18 core.266
-rw------- 1 root root 111G Dec  4 12:18 core.255
-rw------- 1 root root 108G Dec  4 12:18 core.264
-rw------- 1 root root 106G Dec  4 12:18 core.258
-rw------- 1 root root 109G Dec  4 12:18 core.263
-rw------- 1 root root 108G Dec  4 12:18 core.256
-rw------- 1 root root 108G Dec  4 12:18 core.252
-rw------- 1 root root 110G Dec  4 12:18 core.260
-rw------- 1 root root 109G Dec  4 12:18 core.259
-rw------- 1 root root 110G Dec  4 12:18 core.262
-rw------- 1 root root 110G Dec  4 12:18 core.250
-rw------- 1 root root 110G Dec  4 12:18 core.248
-rw------- 1 root root 110G Dec  4 12:18 core.261
-rw------- 1 root root 110G Dec  4 12:18 core.257
-rw------- 1 root root 110G Dec  4 12:18 core.247
-rw------- 1 root root 111G Dec  4 12:18 core.254
-rw------- 1 root root 110G Dec  4 12:18 core.253

**Comment by crystalww** [comment] 2020-12-07 10:16
@rkooo567 @richardliaw Is there a way to prevent to write core dump files. The ray cluster almost can not  be used because of this.

![image](https://user-images.githubusercontent.com/20527302/101335693-831e4580-38b4-11eb-89ec-2fc87aaa9984.png)

**Comment by rkooo567** [comment] 2020-12-07 21:50
https://discuss.ray.io/t/how-to-abort-a-driver-program-elegant/152/2 Can you try this?

**Comment by subbareddydagumati** [comment] 2020-12-08 00:31
It worked.

**Comment by rkooo567** [comment] 2020-12-08 06:18
Awesome! We can probably add this to the documentation.

**Comment by Yuchen-Cao** [comment] 2021-07-28 12:28
> https://discuss.ray.io/t/how-to-abort-a-driver-program-elegant/152/2 Can you try this?

We encounter this issue as well. Setting 'ulimit -c 0' surely helps save disk space.
So this means "no core dump file" written, right? But I'm wondering if there is still something aborted inside. If this is the case, whether or not "core dump" will affect performance?

**Comment by yiwei00000** [comment] 2021-07-29 05:56
> When program/script abort while running ray processes. It's generating core dump.
> Please follow the below procedure to re-create issue @rkooo567
> 
> Underlying OS:
> NAME="Red Hat Enterprise Linux Server"
> VERSION="7.5 (Maipo)"
> 
> sample program to re-create issue "ray_core_dump_issue.py"
> 
> ```
> import ray
> import time, datetime
> import sys, os
> 
> @ray.remote
> def sample_check(batch):
>     print(f"Batch:{batch}")
>     a=10
>     b = a + a
>     time.sleep(10)
>     print(b)
>     return
> 
> 
> def split_proc(proc_cnt, batch_size):
>     start_time = time.time()
>     ray.init(dashboard_host="0.0.0.0",num_cpus=proc_cnt)
>     total_batches = batch_size
>     ret_ids = []
>     while total_batches!=0:
>         total_batches = total_batches -1
>         print(f"Batch Number:{total_batches}")
>         red_id= sample_check.remote( total_batches)
>         ret_ids.append(red_id)
>     ret = ray.get(ret_ids)
>     ray.shutdown()
> 
> if __name__ == "__main__":
>     split_proc(8, 12)
> 
> 
> 1) Pull the docker image
> docker pull subbareddy425/python36-ray:1.0.0
> 
> 2) Start the Docker container
>  docker run -d -it --name ray-core-issue subbareddy425/python36-ray:1.0.0 bash
> 
> 3) Exec console to docker container
>   docker exec -it ray-core-issue bash
>   
> 4) Run the python program in the directory /apps/python_scripts/
> 
> cd /apps/python_scripts/
> python3 ray_core_dump_issue.py
> 
> 5) it will create core dump in the current directory program ran
> 
> bash-4.2# ls -ltrh
> total 52M
> -rw-r----- 1 root root  649 Nov 30 19:31 ray_core_dump_issue.py
> -rw------- 1 root root 153M Nov 30 19:47 core.41
> ```

Hi, using your code, I did not reproduce the core dump file...

**Comment by rkooo567** [comment] 2021-07-30 18:48
Maybe core dump itself was generated because of our destruction path's bug, and we happened to fix that.

**Comment by rkooo567** [comment] 2022-12-08 04:58
I believe this is fixed in the master. Please reopen if you see this issue

**Closed by rkooo567** 2022-12-08 04:58 UTC
Labels: bug, P2, docs
