### ISSUE TITLE
[RLlib] MCTS with nested observation space: The two structures don't have the same nested structure

### ISSUE THREAD

**Issue by Tsesterh** [ray-project/ray#24617] opened 2022-05-09 19:59 UTC
### What happened + What you expected to happen

**What is the Problem?**

When using the MCTS implementation in RLlib for a custom environment with a nested observation space, we get the following error:

```
ValueError: The two structures don't have the same nested structure.

First structure: type=dict str={'obs': array(['control_flow_matrix', 'bit_specification'], dtype='<U19'), 'action_mask': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1.], dtype=float32)}

Second structure: type=OrderedDict str=OrderedDict([('action_mask', array([0.7586012 , 0.41466984, 0.61585647, 0.54837763, 0.10162925,
       0.11003609, 0.18092145, 0.68561834, 0.97628546, 0.8155792 ,
       0.76124734, 0.21725808, 0.6867367 , 0.10675921, 0.9481447 ,
       0.88930786, 0.8112188 , 0.34928837, 0.85642624], dtype=float32)), ('obs', OrderedDict([('bit_specification', array([[ 0, -1, -1]])), ('control_flow_matrix', array([[0, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1, 1]]))]))])

More specifically: Substructure "type=OrderedDict str=OrderedDict([('bit_specification', array([[ 0, -1, -1]])), ('control_flow_matrix', array([[0, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1, 1]]))])" is a sequence, while substructure "type=ndarray str=['control_flow_matrix' 'bit_specification']" is not
```

**Reproduction**

Nested observation space (i.e. gym.spaces.Dict) + wrapper environment following the example in https://github.com/ray-project/ray/blob/master/rllib/contrib/alpha_zero/environments/cartpole.py 

### Versions / Dependencies

Ray: 1.11.0
Gym: 0.17.3
PyTorch: 1.11.0
OS: Ubuntu 20.04 LTS

### Reproduction script

needs-repro-script

### Issue Severity

High: It blocks me from completing my task.

**Comment by kouroshHakha** [comment] 2022-05-24 16:21
Can you share a simple minimal reproduction script?

**Comment by kouroshHakha** [comment] 2022-10-26 21:32
closing this issue, due to lack of a repro script.

**Closed by kouroshHakha** 2022-10-26 21:32 UTC
Labels: bug, needs-repro-script, triage, @author-action-required, rllib
