### ISSUE TITLE
Release test gcp_cluster_launcher_latest_image failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#40241] opened 2023-10-10 21:40 UTC
Release test **gcp_cluster_launcher_latest_image** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2245#018b1b7e-0b8a-41b7-99ae-a686e4de68b1 for more details.

Managed by OSS Test Policy

**Comment by rkooo567** [comment] 2023-10-10 22:14
cc @rickyyx

**Comment by rkooo567** [comment] 2023-10-10 22:17
Is it the same issue, or something new?

**Comment by can-anyscale** [comment] 2023-10-10 22:53
They are all existing issues ;), the issues only cut today since the release test run has been failing in the last few days

**Comment by can-anyscale** [comment] 2023-10-11 08:20
Test has been failing for far too long. Jailing.

**Comment by rickyyx** [comment] 2023-10-11 16:50
cc @gvspraveen @architkulkarni I believe there is something wrong with the cluster launcher's setup for nightly tests. 

Could you folks help take a look? 

This is related as well: https://github.com/ray-project/ray/issues/40228

**Comment by can-anyscale** [comment] 2023-10-13 00:31
Found the root cause, should be fixed at least for aws

**Comment by can-anyscale** [comment] 2023-10-13 08:41
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2252#018b2826-8c55-4db0-bfd2-b64bb1815dda

**Comment by can-anyscale** [comment] 2023-10-13 21:31
The original issue is fixed, now it is just an error specific to this one test, CC: @iycheng who is core oncall

**Comment by iycheng** [comment] 2023-10-16 18:12
@gvspraveen @architkulkarni can you take a look at this?

It seems like failure from cluster launcher.

**Comment by can-anyscale** [comment] 2023-10-18 17:08
@architkulkarni the one that passed is the nightly_image ;), this test has been jailed so it haven't been running for a while.

**Comment by architkulkarni** [comment] 2023-10-18 17:11
Oh I see. Is there any better way to see when it started to fail, other than manually scrolling through buildkite?

**Comment by can-anyscale** [comment] 2023-10-18 17:31
@architkulkarni totally, https://buildkite.com/ray-project/release-tests-branch/builds/2245#018b1b7e-0b8a-41b7-99ae-a686e4de68b1 should be the last time it failed

The last time it passed was on https://buildkite.com/ray-project/release-tests-branch/builds/2235#018b01c5-b641-4b16-9624-6418f98025b1

`[INFO 2023-10-10 21:40:40,546] ray_test_db.py: 34  Test results: [{"status": "error", "commit": "24012e57c6a083d02990b6648a032a38bb00e8af", "url": "https://buildkite.com/ray-project/release-tests-branch/builds/2245#018b1b7e-0b8a-41b7-99ae-a686e4de68b1", "timestamp": 1696974039316}, {"status": "error", "commit": "e918a19737e2ba6df52f1c772274dc88a035090b", "url": "https://buildkite.com/ray-project/release-tests-branch/builds/2239#018b0446-3d82-49dc-b1ab-82f9c2cce589", "timestamp": 1696584484870}, {"status": "success", "commit": "07f3d3ac4036688f83911cc8b9cece18b739b191", "url": "https://buildkite.com/ray-project/release-tests-branch/builds/2235#018b01c5-b641-4b16-9624-6418f98025b1", "timestamp": 1696543196618}, {"status": "success", "commit": "3286dc933c73619b29a9b21c722c0a7bf879d72b", "url": "https://buildkite.com/ray-project/release-tests-branch/builds/2213#018af66d-837f-4d0a-a731-6be27412a633", "timestamp": 1696352892331}, {"status": "success", "commit": "9670b3c2ec5c5d43660182df609c212637db50da", "url": "https://buildkite.com/ray-project/release-tests-branch/builds/2208#018aef36-7b88-47f3-b9a9-19e058a82027", "timestamp": 1696231822766}, {"status": "success", "commit": "3135323aa1f6eb5861c331b24a9209419106c0ed", "url": "https://buildkite.com/ray-project/release-tests-branch/builds/2202#018ae020-6c7d-4d84-96ba-92e2f56e0c14", "timestamp": 1695978823355}, {"status": "success", "commit": "9c143f63233d5cbde8a6943db31b91fb3b05f017", "url": "https://buildkite.com/ray-project/release-tests-branch/builds/2195#018ad5c5-faf6-4b20-afe4-bfac6338cdf8", "timestamp": 1695805104050}, {"status": "success", "commit": "3e8aad8177a4e284771eb9b1eb80593ef1a90246", "url": "https://buildkite.com/ray-project/release-tests-branch/builds/2194#018ad28a-e574-45b6-9334-c07ed6be719b", "timestamp": 1695750891517}, {"status": "success", "commit": "f2eaea027f3744c3008c1a6b7ed6553c46de250b", "url": "https://buildkite.com/ray-project/release-tests-branch/builds/2192#018acb84-badd-4253-ba11-cfa386e121ba", "timestamp": 1695632605557}, {"status": "success", "commit": "75a68c02bfffdb40011ef442934462c8a17b023e", "url": "https://buildkite.com/ray-project/release-tests-branch/builds/2189#018abd26-9178-45c9-b6f4-f5245f707086", "timestamp": 1695391974192}]`

**Comment by architkulkarni** [comment] 2023-10-18 21:23
I just opened a PR with no behavior changes and the release test passed. https://buildkite.com/ray-project/release-tests-pr/builds/56209#018b4482-139c-42e4-b86f-1cffb25daa3a (nightly and latest were mistakenly switched prior to this PR; this PR unswitches them, but they both passed.)

I also ran the release test command 4 times from my laptop (`python launch_and_verify_cluster.py gcp/example-full.yaml --num-expected-nodes 2 --retries 20  --docker-override nightly`) and it passed each time.

I'm guessing it's a transient error in GCP. In the PR I added more debug logs to have a more useful traceback. If we merge the PR, would you consider unjailing the test? The next time it fails it'll have more debug logs for me to figure out the root cause.

**Comment by architkulkarni** [comment] 2023-10-19 19:16
@can-anyscale Added another commit to the PR to retrigger the tests and it passed again:
- nightly https://buildkite.com/ray-project/release-tests-pr/builds/56261#018b44e9-9434-454c-bfa8-b86171e93b35
- latest https://buildkite.com/ray-project/release-tests-pr/builds/56261#018b44e9-9431-4f00-b969-29740086434c

**Comment by can-anyscale** [comment] 2023-10-19 19:34
w00h00, thanks @architkulkarni, feel free to close this issue then and that will unjail this test automatically

**Comment by architkulkarni** [comment] 2023-10-19 20:01
Cool, I'll close it when the PR https://github.com/ray-project/ray/pull/40453 is merged.

**Comment by can-anyscale** [comment] 2023-10-20 16:27
This has now escalated to be a release-blocker since the branch has been cut, so please help to prioritize. Thankkks

**Comment by can-anyscale** [comment] 2023-10-23 08:07
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2285#018b5b8a-ce68-4200-8182-bb75da00bc36

**Comment by architkulkarni** [comment] 2023-10-23 16:59
Seems to be an error related to too many SSH keys being created and stored in the GCP project "common instance metadata".  I think I'll update the test to reuse a single key instead of generating a new one for each test.

**Comment by vitsai** [comment] 2023-10-24 17:04
gcp_cluster_launcher_nightly_image also failed, presumably the same test.

**Comment by vitsai** [comment] 2023-10-24 17:07
`gcp_cluster_launcher_minimal` and `gcp_cluster_launcher_full` have failed as well.

**Comment by architkulkarni** [comment] 2023-10-24 17:45
It's the same root cause. Each GCP cluster launcher test was creating a new SSH key, and we hit the per-project limit.

To mitigate the issue and unblock the release, I have deleted 200 unused SSH keys from the project.  The test passes now (see screenshot) and should pass for at least a month with no further changes, but today or tomorrow I'll merge a PR that makes all the GCP cluster launcher tests use the same SSH key, which will permanently fix the issue.

<img width="1353" alt="Screenshot 2023-10-24 at 10 41 53 AM" src="https://github.com/ray-project/ray/assets/5459654/ad9c0cf9-9ea4-45e3-8fee-b4e760e8606b">

I'll close this issue because the release is no longer blocked, and track the remaining work here https://github.com/ray-project/ray/issues/40635

**Closed by architkulkarni** 2023-10-24 17:45 UTC
Labels: bug, release-blocker, P0, release-test, clusters, jailed-test

**Comment by can-anyscale** [comment] 2023-10-25 08:04
Test passed on latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2314#018b65c9-1b17-426f-8422-fab849da9c43
