### ISSUE TITLE
[Autoscaler][Kubernetes] Workers pods aren't scaling in k8s ray cluster 

### ISSUE THREAD

**Issue by Luis-Victor** [ray-project/ray#16549] opened 2021-06-18 19:58 UTC
### What is the problem?

Workers pods are not scaling as expected. I've only been able to make them scale from 0 to 1 pod on some specific cases besides I couldn't make them scale from 1 to n pods either.

- When `.values.podTypes.rayWorkerType.rayResources` contains `{ "GPU": 0 }`, the autoscaler doesn't scale new worker pods
- When task requirement is `num_cpus=1` and the number of workers pods in cluster is `0`, autoscaler doesn't seem to  recognize the task and doesn't show resources demands on logs.
- When task requirements is greater than 1, autoscale recognizes the task and start a new worker pod, but only one, even if `one worker resources < task requirements < maxWorkers resources` .

Ray version: 1.4.0
Python version: 3.8.5
Linux: Ubuntu 18.04
Kubernetes version: 1.18.14 (AKS)

### Reproduction (REQUIRED)
- Install k8s ray cluster using helm (I've tested with `rayproject/ray:1.4.0-py38`, `rayproject/ray:nightly-py38` and `rayproject/ray:latest-py38`)
- values.yaml
```
# RayCluster settings:
image: rayproject/ray:1.4.0-py38
headPodType: rayHeadType
podTypes:
  rayHeadType:
    minWorkers: 0
    maxWorkers: 0
    CPU: 1
    memory: 512Mi
    GPU: 0
    rayResources: { "CPU": 0 }
    nodeSelector: { use: development }
  rayWorkerType:
    minWorkers: 0
    maxWorkers: 3
    memory: 16Gi
    CPU: 2
    GPU: 0
    rayResources: { "CPU": 2 }
    nodeSelector: { use: development }

# Operator settings:
operatorOnly: false
clusterOnly: false
namespacedOperator: false
operatorNamespace: default
operatorImage: rayproject/ray:1.4.0-py38
```
- task.py
```
import ray
LOCAL_PORT = 10001

@ray.remote(num_cpus=1)
def f(i):
    import time
    print(f"Try number {i}")
    time.sleep(300)

if __name__ == "__main__":
    ray.util.connect(f"127.0.0.1:{LOCAL_PORT}")
    ray.get([f.remote(i + 1) for i in range(6)])
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by DmitriGekhtman** [comment] 2021-06-21 15:13
Thanks for pointing these things out. I'll take a look as soon.

**Comment by DmitriGekhtman** [comment] 2021-06-28 15:17
> When task requirements is greater than 1, autoscale recognizes the task and start a new worker pod, but only one, even if one worker resources < task requirements < maxWorkers resources .

We have to fix the default behavior here or make max_workers required.
For now, please specify max_workers for all podTypes to get reasonable behavior.
I think this may resolve the rest of the bullets as well.
Thanks for helping us iron out the UX...

**Comment by Luis-Victor** [comment] 2021-06-28 20:43
Thanks for the answer, Dmitri. I've tried with maxWorkers in each podTypes (_head and worker_) and it continues presenting the same behavior. Actually, i've just forgotten to write it in `rayWorkerType` at `values.yaml`. My sincere apologies for it.
I am editing it right now and adding the following parameters: `.rayWorkerType.minWorkers: 0` and `.rayWorkerType.maxWorkers: 3` in the issue description.

**Comment by DmitriGekhtman** [comment] 2021-06-29 02:46
I'm not yet able to reproduce --
Once the ray tasks are submitted, could you 
- open a new shell,
- identify the ray-operator pod with `kubectl get pods`
- get the last 100 lines of operator logs with `kubectl logs ray-operator-<identifier>`

**Comment by Luis-Victor** [comment] 2021-06-29 18:33
I've been testing this issue a little more and I realized that some things have changed. It seems to work better now. 
Sending tasks that require `num_cpus=1` works as expected  when `.rayWorkerType.maxWorkers <= 3`, because Ray is scaling up to 3 workers, even if `maxWorkers` is greater than this.

Ray-operator logs:
```
======== Autoscaler status: 2021-06-29 11:06:50.310403 ========
Node status
---------------------------------------------------------------
Healthy:
 1 rayHeadType
Pending:
 10.244.5.44: rayWorkerType, waiting-for-ssh
 10.244.5.46: rayWorkerType, waiting-for-ssh
 10.244.5.45: rayWorkerType, waiting-for-ssh
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------

Usage:
 1.0/1.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:K80
 0.00/0.350 GiB memory
 0.00/0.135 GiB object_store_memory

Demands:
 {'CPU': 1.0}: 3+ pending tasks/actors
Unable to use a TTY - input is not a terminal or the right kind of file
test,dev:2021-06-29 11:06:50,375	DEBUG legacy_info_string.py:24 -- Cluster status: 3 nodes (3 updating)
 - MostDelayedHeartbeats: {'10.244.5.43': 0.8282203674316406}
 - NodeIdleSeconds: Min=0 Mean=0 Max=0
 - ResourceUsage: 1.0/1.0 CPU, 0.0/1.0 GPU, 0.0/1.0 accelerator_type:K80, 0.0 GiB/0.35 GiB memory, 0.0 GiB/0.13 GiB object_store_memory
 - TimeSinceLastHeartbeat: Min=0 Mean=0 Max=0
Worker node types:
 - rayWorkerType: 3
Unable to use a TTY - input is not a terminal or the right kind of file
Unable to use a TTY - input is not a terminal or the right kind of file
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
 11:06:51 up 22:17,  0 users,  load average: 0.38, 0.31, 0.22
 11:06:51 up 22:17,  0 users,  load average: 0.38, 0.31, 0.22
 11:06:51 up 22:17,  0 users,  load average: 0.38, 0.31, 0.22
test,dev:2021-06-29 11:06:51,094	DEBUG updater.py:304 -- Node tags: {'ray-cluster-name': 'test', 'ray-launch-config': '98ad538a9ebbd41e3222cdcc82b7170927f387a2', 'ray-node-name': 'ray-test-worker', 'ray-node-status': 'waiting-for-ssh', 'ray-node-type': 'worker', 'ray-node-uuid': '329169c3-6e77-4f04-9967-91c9425cb1e0', 'ray-user-node-type': 'rayWorkerType'}
test,dev:2021-06-29 11:06:51,098	DEBUG updater.py:304 -- Node tags: {'ray-cluster-name': 'test', 'ray-launch-config': '98ad538a9ebbd41e3222cdcc82b7170927f387a2', 'ray-node-name': 'ray-test-worker', 'ray-node-status': 'waiting-for-ssh', 'ray-node-type': 'worker', 'ray-node-uuid': '329169c3-6e77-4f04-9967-91c9425cb1e0', 'ray-user-node-type': 'rayWorkerType'}
test,dev:2021-06-29 11:06:51,104	DEBUG updater.py:304 -- Node tags: {'ray-cluster-name': 'test', 'ray-launch-config': '98ad538a9ebbd41e3222cdcc82b7170927f387a2', 'ray-node-name': 'ray-test-worker', 'ray-node-status': 'waiting-for-ssh', 'ray-node-type': 'worker', 'ray-node-uuid': '329169c3-6e77-4f04-9967-91c9425cb1e0', 'ray-user-node-type': 'rayWorkerType'}
test,dev:2021-06-29 11:06:51,181	INFO command_runner.py:172 -- NodeUpdater: test-ray-worker-type-jxgjb: Running kubectl -n dev exec -it test-ray-worker-type-jxgjb -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (export RAY_OVERRIDE_RESOURCES='"'"'{"CPU":1,"memory":375809638}'"'"';export RAY_HEAD_IP=10.244.5.43; ray stop)'
test,dev:2021-06-29 11:06:51,185	INFO command_runner.py:172 -- NodeUpdater: test-ray-worker-type-rrvfd: Running kubectl -n dev exec -it test-ray-worker-type-rrvfd -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (export RAY_OVERRIDE_RESOURCES='"'"'{"CPU":1,"memory":375809638}'"'"';export RAY_HEAD_IP=10.244.5.43; ray stop)'
test,dev:2021-06-29 11:06:51,190	INFO command_runner.py:172 -- NodeUpdater: test-ray-worker-type-nkn46: Running kubectl -n dev exec -it test-ray-worker-type-nkn46 -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (export RAY_OVERRIDE_RESOURCES='"'"'{"CPU":1,"memory":375809638}'"'"';export RAY_HEAD_IP=10.244.5.43; ray stop)'
Unable to use a TTY - input is not a terminal or the right kind of file
Unable to use a TTY - input is not a terminal or the right kind of file
Unable to use a TTY - input is not a terminal or the right kind of file
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2021-06-29 11:06:52,766	INFO scripts.py:833 -- Did not find any active Ray processes.
2021-06-29 11:06:52,785	INFO scripts.py:833 -- Did not find any active Ray processes.
2021-06-29 11:06:52,795	INFO scripts.py:833 -- Did not find any active Ray processes.
test,dev:2021-06-29 11:06:52,879	INFO command_runner.py:172 -- NodeUpdater: test-ray-worker-type-jxgjb: Running kubectl -n dev exec -it test-ray-worker-type-jxgjb -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (export RAY_OVERRIDE_RESOURCES='"'"'{"CPU":1,"memory":375809638}'"'"';export RAY_HEAD_IP=10.244.5.43; ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379)'
test,dev:2021-06-29 11:06:52,902	INFO command_runner.py:172 -- NodeUpdater: test-ray-worker-type-nkn46: Running kubectl -n dev exec -it test-ray-worker-type-nkn46 -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (export RAY_OVERRIDE_RESOURCES='"'"'{"CPU":1,"memory":375809638}'"'"';export RAY_HEAD_IP=10.244.5.43; ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379)'
test,dev:2021-06-29 11:06:52,963	INFO command_runner.py:172 -- NodeUpdater: test-ray-worker-type-rrvfd: Running kubectl -n dev exec -it test-ray-worker-type-rrvfd -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (export RAY_OVERRIDE_RESOURCES='"'"'{"CPU":1,"memory":375809638}'"'"';export RAY_HEAD_IP=10.244.5.43; ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379)'
Unable to use a TTY - input is not a terminal or the right kind of file
Unable to use a TTY - input is not a terminal or the right kind of file
Unable to use a TTY - input is not a terminal or the right kind of file
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2021-06-29 11:06:54,397	INFO services.py:319 -- This node has an IP address of 10.244.5.44, while we can not found the matched Raylet address. This maybe come from when you connect the Ray cluster with a different IP address or connect a container.
2021-06-29 11:06:54,370	INFO scripts.py:708 -- Local node IP: 10.244.5.44
2021-06-29 11:06:54,398	SUCC scripts.py:721 -- --------------------
2021-06-29 11:06:54,398	SUCC scripts.py:722 -- Ray runtime started.
2021-06-29 11:06:54,398	SUCC scripts.py:723 -- --------------------
2021-06-29 11:06:54,398	INFO scripts.py:725 -- To terminate the Ray runtime, run
2021-06-29 11:06:54,398	INFO scripts.py:726 --   ray stop
2021-06-29 11:06:54,433	INFO services.py:319 -- This node has an IP address of 10.244.5.46, while we can not found the matched Raylet address. This maybe come from when you connect the Ray cluster with a different IP address or connect a container.
2021-06-29 11:06:54,412	INFO scripts.py:708 -- Local node IP: 10.244.5.46
2021-06-29 11:06:54,434	SUCC scripts.py:721 -- --------------------
2021-06-29 11:06:54,434	SUCC scripts.py:722 -- Ray runtime started.
2021-06-29 11:06:54,434	SUCC scripts.py:723 -- --------------------
2021-06-29 11:06:54,434	INFO scripts.py:725 -- To terminate the Ray runtime, run
2021-06-29 11:06:54,434	INFO scripts.py:726 --   ray stop
test,dev:2021-06-29 11:06:55,898	DEBUG resource_demand_scheduler.py:160 -- Cluster resources: [{'object_store_memory': 144418781.0, 'accelerator_type:K80': 1.0, 'node:10.244.5.43': 1.0, 'GPU': 1.0, 'memory': 375809638.0, 'CPU': 0.0}, {'memory': 375809638.0, 'node:10.244.5.44': 1.0, 'CPU': 1.0, 'accelerator_type:K80': 1.0, 'object_store_memory': 144368025.0, 'GPU': 1.0}, {'GPU': 1.0, 'memory': 375809638.0, 'node:10.244.5.46': 1.0, 'object_store_memory': 144227942.0, 'accelerator_type:K80': 1.0, 'CPU': 1.0}, {'CPU': 1.0, 'memory': 375809638.0, 'GPU': 1.0, 'object_store_memory': 144368025.0}]
test,dev:2021-06-29 11:06:55,898	DEBUG resource_demand_scheduler.py:161 -- Node counts: defaultdict(<class 'int'>, {'rayHeadType': 1, 'rayWorkerType': 3})
test,dev:2021-06-29 11:06:55,898	DEBUG resource_demand_scheduler.py:172 -- Placement group demands: []
test,dev:2021-06-29 11:06:55,898	DEBUG resource_demand_scheduler.py:218 -- Resource demands: [{'CPU': 1.0}, {'CPU': 1.0}, {'CPU': 1.0}, {'CPU': 1.0}, {'CPU': 1.0}]
test,dev:2021-06-29 11:06:55,898	DEBUG resource_demand_scheduler.py:219 -- Unfulfilled demands: [{'CPU': 1.0}, {'CPU': 1.0}]
test,dev:2021-06-29 11:06:55,899	WARNING resource_demand_scheduler.py:712 -- The autoscaler could not find a node type to satisfy the request: [{'CPU': 1.0}, {'CPU': 1.0}]. If this request is related to placement groups the resource request will resolve itself, otherwise please specify a node type with the necessary resource https://docs.ray.io/en/master/cluster/autoscaling.html#multiple-node-type-autoscaling.
test,dev:2021-06-29 11:06:55,977	DEBUG resource_demand_scheduler.py:241 -- Node requests: {}
test,dev:2021-06-29 11:06:55,988	DEBUG load_metrics.py:87 -- Node 10.244.5.46 is newly setup, treating as active
test,dev:2021-06-29 11:06:55,997	DEBUG load_metrics.py:87 -- Node 10.244.5.44 is newly setup, treating as active
test,dev:2021-06-29 11:06:56,005	DEBUG autoscaler.py:755 -- test-ray-worker-type-jxgjb is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:06:56,031	DEBUG autoscaler.py:755 -- test-ray-worker-type-nkn46 is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:06:56,061	DEBUG autoscaler.py:755 -- test-ray-worker-type-jxgjb is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:06:56,084	DEBUG autoscaler.py:755 -- test-ray-worker-type-nkn46 is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:06:56,193	INFO autoscaler.py:354 -- 
======== Autoscaler status: 2021-06-29 11:06:56.193614 ========
Node status
---------------------------------------------------------------
Healthy:
 1 rayHeadType
 2 rayWorkerType
Pending:
 10.244.5.45: rayWorkerType, setting-up
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------

Usage:
 1.0/3.0 CPU
 0.0/3.0 GPU
 0.0/3.0 accelerator_type:K80
 0.00/1.050 GiB memory
 0.00/0.403 GiB object_store_memory

Demands:
 {'CPU': 1.0}: 5+ pending tasks/actors
test,dev:2021-06-29 11:06:56,268	DEBUG legacy_info_string.py:24 -- Cluster status: 3 nodes (1 updating)
 - MostDelayedHeartbeats: {'10.244.5.43': 0.6873548030853271, '10.244.5.46': 0.20567607879638672, '10.244.5.44': 0.19674944877624512}
 - NodeIdleSeconds: Min=0 Mean=0 Max=0
 - ResourceUsage: 1.0/3.0 CPU, 0.0/3.0 GPU, 0.0/3.0 accelerator_type:K80, 0.0 GiB/1.05 GiB memory, 0.0 GiB/0.4 GiB object_store_memory
 - TimeSinceLastHeartbeat: Min=0 Mean=0 Max=0
Worker node types:
 - rayWorkerType: 3
test,dev:2021-06-29 11:06:56,443	INFO monitor.py:224 -- :event_summary:Resized to 3 CPUs, 3 GPUs.
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2021-06-29 11:06:57,558	INFO services.py:319 -- This node has an IP address of 10.244.5.45, while we can not found the matched Raylet address. This maybe come from when you connect the Ray cluster with a different IP address or connect a container.
2021-06-29 11:06:57,538	INFO scripts.py:708 -- Local node IP: 10.244.5.45
2021-06-29 11:06:57,559	SUCC scripts.py:721 -- --------------------
2021-06-29 11:06:57,559	SUCC scripts.py:722 -- Ray runtime started.
2021-06-29 11:06:57,559	SUCC scripts.py:723 -- --------------------
2021-06-29 11:06:57,559	INFO scripts.py:725 -- To terminate the Ray runtime, run
2021-06-29 11:06:57,559	INFO scripts.py:726 --   ray stop
test,dev:2021-06-29 11:07:01,817	DEBUG resource_demand_scheduler.py:160 -- Cluster resources: [{'node:10.244.5.43': 1.0, 'memory': 375809638.0, 'accelerator_type:K80': 1.0, 'GPU': 1.0, 'object_store_memory': 144418781.0, 'CPU': 0.0}, {'memory': 375809638.0, 'GPU': 1.0, 'object_store_memory': 144368025.0, 'accelerator_type:K80': 1.0, 'node:10.244.5.44': 1.0, 'CPU': 0.0}, {'object_store_memory': 144227942.0, 'memory': 375809638.0, 'GPU': 1.0, 'accelerator_type:K80': 1.0, 'node:10.244.5.46': 1.0, 'CPU': 0.0}, {'object_store_memory': 144317644.0, 'GPU': 1.0, 'accelerator_type:K80': 1.0, 'memory': 375809638.0, 'node:10.244.5.45': 1.0, 'CPU': 0.0}]
test,dev:2021-06-29 11:07:01,817	DEBUG resource_demand_scheduler.py:161 -- Node counts: defaultdict(<class 'int'>, {'rayHeadType': 1, 'rayWorkerType': 3})
test,dev:2021-06-29 11:07:01,817	DEBUG resource_demand_scheduler.py:172 -- Placement group demands: []
test,dev:2021-06-29 11:07:01,817	DEBUG resource_demand_scheduler.py:218 -- Resource demands: [{'CPU': 1.0}, {'CPU': 1.0}]
test,dev:2021-06-29 11:07:01,817	DEBUG resource_demand_scheduler.py:219 -- Unfulfilled demands: [{'CPU': 1.0}, {'CPU': 1.0}]
test,dev:2021-06-29 11:07:01,817	WARNING resource_demand_scheduler.py:712 -- The autoscaler could not find a node type to satisfy the request: [{'CPU': 1.0}, {'CPU': 1.0}]. If this request is related to placement groups the resource request will resolve itself, otherwise please specify a node type with the necessary resource https://docs.ray.io/en/master/cluster/autoscaling.html#multiple-node-type-autoscaling.
test,dev:2021-06-29 11:07:01,899	DEBUG resource_demand_scheduler.py:241 -- Node requests: {}
test,dev:2021-06-29 11:07:01,911	DEBUG load_metrics.py:87 -- Node 10.244.5.45 is newly setup, treating as active
test,dev:2021-06-29 11:07:01,920	DEBUG autoscaler.py:755 -- test-ray-worker-type-jxgjb is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:07:01,945	DEBUG autoscaler.py:755 -- test-ray-worker-type-nkn46 is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:07:01,975	DEBUG autoscaler.py:755 -- test-ray-worker-type-rrvfd is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:07:02,000	DEBUG autoscaler.py:755 -- test-ray-worker-type-jxgjb is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:07:02,018	DEBUG autoscaler.py:755 -- test-ray-worker-type-nkn46 is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:07:02,038	DEBUG autoscaler.py:755 -- test-ray-worker-type-rrvfd is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:07:02,139	INFO autoscaler.py:354 -- 
======== Autoscaler status: 2021-06-29 11:07:02.139343 ========
Node status
---------------------------------------------------------------
Healthy:
 1 rayHeadType
 3 rayWorkerType
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------

Usage:
 4.0/4.0 CPU
 0.0/4.0 GPU
 0.0/4.0 accelerator_type:K80
 0.00/1.400 GiB memory
 0.00/0.538 GiB object_store_memory

Demands:
 {'CPU': 1.0}: 2+ pending tasks/actors
test,dev:2021-06-29 11:07:02,195	DEBUG legacy_info_string.py:24 -- Cluster status: 3 nodes
 - MostDelayedHeartbeats: {'10.244.5.46': 0.6888699531555176, '10.244.5.43': 0.6887912750244141, '10.244.5.44': 0.688715934753418, '10.244.5.45': 0.22785067558288574}
 - NodeIdleSeconds: Min=0 Mean=0 Max=0
 - ResourceUsage: 4.0/4.0 CPU, 0.0/4.0 GPU, 0.0/4.0 accelerator_type:K80, 0.0 GiB/1.4 GiB memory, 0.0 GiB/0.54 GiB object_store_memory
 - TimeSinceLastHeartbeat: Min=0 Mean=0 Max=0
Worker node types:
 - rayWorkerType: 3
test,dev:2021-06-29 11:07:02,286	INFO monitor.py:224 -- :event_summary:Resized to 4 CPUs, 4 GPUs.
test,dev:2021-06-29 11:07:07,665	DEBUG resource_demand_scheduler.py:160 -- Cluster resources: [{'object_store_memory': 144418781.0, 'memory': 375809638.0, 'accelerator_type:K80': 1.0, 'GPU': 1.0, 'node:10.244.5.43': 1.0, 'CPU': 0.0}, {'accelerator_type:K80': 1.0, 'node:10.244.5.44': 1.0, 'GPU': 1.0, 'memory': 375809638.0, 'object_store_memory': 144368025.0, 'CPU': 0.0}, {'GPU': 1.0, 'node:10.244.5.46': 1.0, 'object_store_memory': 144227942.0, 'accelerator_type:K80': 1.0, 'memory': 375809638.0, 'CPU': 0.0}, {'accelerator_type:K80': 1.0, 'object_store_memory': 144317644.0, 'GPU': 1.0, 'node:10.244.5.45': 1.0, 'memory': 375809638.0, 'CPU': 0.0}]
test,dev:2021-06-29 11:07:07,665	DEBUG resource_demand_scheduler.py:161 -- Node counts: defaultdict(<class 'int'>, {'rayHeadType': 1, 'rayWorkerType': 3})
test,dev:2021-06-29 11:07:07,665	DEBUG resource_demand_scheduler.py:172 -- Placement group demands: []
test,dev:2021-06-29 11:07:07,666	DEBUG resource_demand_scheduler.py:218 -- Resource demands: [{'CPU': 1.0}, {'CPU': 1.0}]
test,dev:2021-06-29 11:07:07,666	DEBUG resource_demand_scheduler.py:219 -- Unfulfilled demands: [{'CPU': 1.0}, {'CPU': 1.0}]
test,dev:2021-06-29 11:07:07,666	WARNING resource_demand_scheduler.py:712 -- The autoscaler could not find a node type to satisfy the request: [{'CPU': 1.0}, {'CPU': 1.0}]. If this request is related to placement groups the resource request will resolve itself, otherwise please specify a node type with the necessary resource https://docs.ray.io/en/master/cluster/autoscaling.html#multiple-node-type-autoscaling.
test,dev:2021-06-29 11:07:07,743	DEBUG resource_demand_scheduler.py:241 -- Node requests: {}
test,dev:2021-06-29 11:07:07,755	DEBUG autoscaler.py:755 -- test-ray-worker-type-jxgjb is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:07:07,783	DEBUG autoscaler.py:755 -- test-ray-worker-type-nkn46 is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:07:07,812	DEBUG autoscaler.py:755 -- test-ray-worker-type-rrvfd is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:07:07,838	DEBUG autoscaler.py:755 -- test-ray-worker-type-jxgjb is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:07:07,864	DEBUG autoscaler.py:755 -- test-ray-worker-type-nkn46 is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:07:07,881	DEBUG autoscaler.py:755 -- test-ray-worker-type-rrvfd is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:07:07,982	INFO autoscaler.py:354 -- 
======== Autoscaler status: 2021-06-29 11:07:07.982546 ========
Node status
---------------------------------------------------------------
Healthy:
 1 rayHeadType
 3 rayWorkerType
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------

Usage:
 4.0/4.0 CPU
 0.0/4.0 GPU
 0.0/4.0 accelerator_type:K80
 0.00/1.400 GiB memory
 0.00/0.538 GiB object_store_memory

Demands:
 {'CPU': 1.0}: 2+ pending tasks/actors
test,dev:2021-06-29 11:07:08,037	DEBUG legacy_info_string.py:24 -- Cluster status: 3 nodes
 - MostDelayedHeartbeats: {'10.244.5.45': 0.689037561416626, '10.244.5.46': 0.688983678817749, '10.244.5.43': 0.6889369487762451, '10.244.5.44': 0.6888933181762695}
 - NodeIdleSeconds: Min=0 Mean=0 Max=0
 - ResourceUsage: 4.0/4.0 CPU, 0.0/4.0 GPU, 0.0/4.0 accelerator_type:K80, 0.0 GiB/1.4 GiB memory, 0.0 GiB/0.54 GiB object_store_memory
 - TimeSinceLastHeartbeat: Min=0 Mean=0 Max=0
Worker node types:
 - rayWorkerType: 3
test,dev:2021-06-29 11:07:13,504	DEBUG resource_demand_scheduler.py:160 -- Cluster resources: [{'accelerator_type:K80': 1.0, 'GPU': 1.0, 'node:10.244.5.43': 1.0, 'memory': 375809638.0, 'object_store_memory': 144418781.0, 'CPU': 0.0}, {'node:10.244.5.44': 1.0, 'memory': 375809638.0, 'object_store_memory': 144368025.0, 'GPU': 1.0, 'accelerator_type:K80': 1.0, 'CPU': 0.0}, {'node:10.244.5.46': 1.0, 'memory': 375809638.0, 'GPU': 1.0, 'object_store_memory': 144227942.0, 'accelerator_type:K80': 1.0, 'CPU': 0.0}, {'GPU': 1.0, 'accelerator_type:K80': 1.0, 'object_store_memory': 144317644.0, 'memory': 375809638.0, 'node:10.244.5.45': 1.0, 'CPU': 0.0}]
test,dev:2021-06-29 11:07:13,504	DEBUG resource_demand_scheduler.py:161 -- Node counts: defaultdict(<class 'int'>, {'rayHeadType': 1, 'rayWorkerType': 3})
test,dev:2021-06-29 11:07:13,505	DEBUG resource_demand_scheduler.py:172 -- Placement group demands: []
test,dev:2021-06-29 11:07:13,505	DEBUG resource_demand_scheduler.py:218 -- Resource demands: [{'CPU': 1.0}, {'CPU': 1.0}]
test,dev:2021-06-29 11:07:13,505	DEBUG resource_demand_scheduler.py:219 -- Unfulfilled demands: [{'CPU': 1.0}, {'CPU': 1.0}]
test,dev:2021-06-29 11:07:13,505	WARNING resource_demand_scheduler.py:712 -- The autoscaler could not find a node type to satisfy the request: [{'CPU': 1.0}, {'CPU': 1.0}]. If this request is related to placement groups the resource request will resolve itself, otherwise please specify a node type with the necessary resource https://docs.ray.io/en/master/cluster/autoscaling.html#multiple-node-type-autoscaling.
test,dev:2021-06-29 11:07:13,573	DEBUG resource_demand_scheduler.py:241 -- Node requests: {}
test,dev:2021-06-29 11:07:13,584	DEBUG autoscaler.py:755 -- test-ray-worker-type-jxgjb is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:07:13,610	DEBUG autoscaler.py:755 -- test-ray-worker-type-nkn46 is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:07:13,635	DEBUG autoscaler.py:755 -- test-ray-worker-type-rrvfd is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:07:13,659	DEBUG autoscaler.py:755 -- test-ray-worker-type-jxgjb is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:07:13,675	DEBUG autoscaler.py:755 -- test-ray-worker-type-nkn46 is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:07:13,699	DEBUG autoscaler.py:755 -- test-ray-worker-type-rrvfd is not being updated and passes config check (can_update=True).
test,dev:2021-06-29 11:07:13,815	INFO autoscaler.py:354 -
```

**Comment by DmitriGekhtman** [comment] 2021-06-29 20:14
Glad it's working!
I am observing the `{ "GPU": 0 }` bug and think I understand the reason and fix -- the thing to do for now is to exclude that setting from values.yaml if possible.

**Comment by Luis-Victor** [comment] 2021-06-29 20:45
Nice!
There is some internal limit to ray MaxWorkers? Could it be more than 3 rayWorkers running simultaneously?

**Comment by DmitriGekhtman** [comment] 2021-06-29 21:54
There’s no internal limit — autoscaling is only limited by the k8s
environment. If your k8s cluster is unable to accommodate a pod creation
request from the ray autoscaler, the pod will enter a pending state for up
to a certain timeout period, before the pod is deleted. Running and pending
pods are deleted on helm  cleanup.

We haven’t run scalability benchmarks on k8s, but things should run
smoothly with a few hundred worker pods.

**Comment by DmitriGekhtman** [comment] 2021-06-29 22:15
https://github.com/ray-project/ray/pull/16761

**Comment by richardliaw** [comment] 2021-07-02 02:28
nice! @DmitriGekhtman can we close this issue?

**Closed** 2021-07-02 02:37 UTC
Labels: P2, bug
