### ISSUE TITLE
I noticed that there are tests on https://flakey-tests.ray.io/ that have 0 failures/flaky/missing data builds in the last 100 commits

### ISSUE THREAD

**Issue by ollie-iterators** [ray-project/ray#35550] opened 2023-05-19 15:43 UTC
### What happened + What you expected to happen

There are tests on https://flakey-tests.ray.io/ with 0 failures/flaky/missing data builds in the last 100 commits.

### Versions / Dependencies

Main branch

### Reproduction script

Look at the bottom of https://flakey-tests.ray.io/#showAll=true

### Issue Severity

Low: It annoys or frustrates me.

**Comment by ollie-iterators** [comment] 2023-05-20 15:04
<img width="979" alt="2023-05-19_11-40-53" src="https://github.com/ray-project/ray/assets/46904826/2cb16a08-6e27-4bd5-82a1-37137bcac061">

**Comment by ollie-iterators** [comment] 2023-05-23 15:22
There are at least 70 tests that should not be on https://flakey-tests.ray.io/#showAll=true because they have 0 failures/flaky/missing data builds in the last 100 commits

**Comment by aslonnie** [comment] 2023-06-05 23:34
closing as duplicate of https://github.com/ray-project/ray/issues/35716

**Closed by aslonnie** 2023-06-05 23:34 UTC
Labels: bug, P2, Devprod
