### ISSUE TITLE
[Docs] Top bar obstructs section headers when clicking on TOC

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#36786] opened 2023-06-24 02:43 UTC
### Description

When I click on a link in the right hand side table of contents, I get taken to that section as expected. However, the top bar in the docs page blocks the header. [For example](https://docs.ray.io/en/master/serve/index.html#why-choose-serve):

<img width="1200" alt="Screen Shot 2023-06-23 at 7 42 01 PM" src="https://github.com/ray-project/ray/assets/92341594/48d893f1-85e6-47c2-a23f-3f8900e2687c">

Ideally, the header should not be blocked. This makes for a smoother reading experience, since I can confirm where I am in the docs when I click on a TOC link. For example, this used to be the behavior [in 2.3.0](https://docs.ray.io/en/releases-2.3.0/serve/index.html#quickstart):

<img width="1216" alt="Screen Shot 2023-06-23 at 7 43 23 PM" src="https://github.com/ray-project/ray/assets/92341594/36fd9543-352a-47de-b363-cac9065126bd">

### Link

You can reproduce this behavior by clicking any link in the right hand side's table of contents.

**Comment by angelinalg** [comment] 2023-06-27 22:37
Thanks for filing, @shrekris-anyscale. This is a known issue and is a duplicate of https://github.com/ray-project/ray/issues/36786

**Closed by angelinalg** 2023-06-27 22:37 UTC
Labels: docs

**Comment by shrekris-anyscale** [comment] 2023-06-27 22:40
Thanks for closing @angelinalg. I think you linked this PR in your comment by accident. Do you mind linking the PR that this is a duplicate of?
