### ISSUE TITLE
[Ray Dataset] Streaming executor trying to consume more resources than limit. 

### ISSUE THREAD

**Issue by QingxianLai** [ray-project/ray#32714] opened 2023-02-21 22:41 UTC
### What happened + What you expected to happen

When using streaming executor to run a dataset pipeline, I specified the following resource limit: 
```
ctx.execution_options.resource_limits.cpu = 20
ctx.execution_options.resource_limits.gpu = 0
ctx.execution_options.resource_limits.object_store_memory = 20e9
ctx.execution_options.locality_with_output = False 
```

However, when I try to execute the pipeline, it apparently trying to use much more resources than the limit. 

```
Resource usage vs limits: 98.0/20 CPU, 0.0/0 GPU, 22623.92 GiB/18.63 GiB object_store_memory:
...
Resource usage vs limits: 210.0/20 CPU, 0.0/0 GPU, 18641.43 GiB/18.63 GiB object_store_memory:
```

Confirmed on the ray dashboard, that much more resource has been used. but the usage number is also weird, e.g. in our case, we only have about 500GB object memory store, but the usage shows above is about `22623.92GiB`

The pipeline is just read some parquet file and return as batches. 

### Versions / Dependencies

For this test, we used the nightly released version:
```
https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
```

### Reproduction script

```
ctx = ray.data.context.DatasetContext.get_current()
ctx.use_streaming_executor = True
ctx.execution_options.resource_limits.cpu = 20
ctx.execution_options.resource_limits.gpu = 0
ctx.execution_options.resource_limits.object_store_memory = 20e9
ctx.execution_options.locality_with_output = False   # 

ds = ray.data.read_parquet(
        file_paths,
        filesystem=p_fs.S3FileSystem(),
        parallelism=len(file_paths),
    )

batch_iter = ds.iter_batches(....)

for i in range(100):
    next(batch_iter)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by ericl** [comment] 2023-02-23 00:01
Hey @QingxianLai , thanks for the bug report! I'm trying to reproduce this in my environment and wonder if these work for you:

(10GB, parquet reads):
```
import ray


ray.init()

ctx = ray.data.context.DatasetContext.get_current()
ctx.use_streaming_executor = True
ctx.execution_options.resource_limits.cpu = 20
ctx.execution_options.resource_limits.gpu = 0
ctx.execution_options.resource_limits.object_store_memory = 20e9
ctx.execution_options.locality_with_output = False

ds = ray.data.read_parquet("s3://air-example-data-2/movie-image-small-filesize-10GB-parquet/", parallelism=400)

it = ds.iter_batches()
for i in it:
    pass
```

(1TB, synthetic data):
```
ds = ray.data.range_tensor(1000000, shape=(1024, 128), parallelism=5000)
```

I am not able to reproduce the issue with the two above datasets. Perhaps there's some unique size / other property of your data that's triggering the issue? It may be worth trying out the latest `master` build as well, since we have fixed some bugs recently that may be related.

**Comment by ericl** [comment] 2023-03-06 23:35
Closing this for now.

**Closed by ericl** 2023-03-06 23:35 UTC
Labels: bug, P1, datasets
