### ISSUE TITLE
[Question][rllib] How can I save my customised metrics to TensorBoard after building customised model and policy?

### ISSUE THREAD

**Issue by GoingMyWay** [ray-project/ray#7652] opened 2020-03-19 04:24 UTC
### What is your question?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray: 0.8.2
Python: 3.6
TF: 2.1
OS: macOS 

By running `rllib train --run=PG --env=CartPole-v0`, we can get some data saved in Tensoborad format and visualize it via Tensorboard, however, after customizing my own model and policy, there is no Tensorboard data after running my code. How can I set my loss, my customized metrics (accuracy, probability distributions, histogram, etc) and save them to TensorBoard?

**Comment by gjoliver** [comment] 2022-04-09 23:07
closing due to lack of updates.
if this is still a problem for you, please provide a simple reproduce script so we can help make sure the metrics you need shows up in tensorboard.
thanks.

**Closed by gjoliver** 2022-04-09 23:07 UTC
Labels: question, P3, tune, rllib
