### ISSUE TITLE
[rllib] After creating a trainer, matplotlib plots won't show in jupyter notebooks

### ISSUE THREAD

**Issue by giancds** [ray-project/ray#17618] opened 2021-08-05 20:28 UTC
### What is the problem?

Before creating a RLLib trainer, plots work fine. As soon as a trainer is created, the output of a plot in a jupyter notebook is something similar to `Figure(432x288)`

*Ray version and other system information (Python version, TensorFlow version, OS):*

* MacBook Pro M1, 8gb
* OS: macOS Big Sur (11.5)
* Python 3.9
* ray version: '2.0.0.dev0'

### Reproduction in Jupyter notebook
First cell: 

```{python}
import ray
from ray.rllib.agents.dqn import R2D2Trainer, R2D2_DEFAULT_CONFIG
import matplotlib
import matplotlib.pyplot as plt
print(matplotlib.__version__)
print(ray.__version__)
```
Second cell:

```{python}
plt.plot(range(10))
plt.show()
```

Third cell

```{python}
ray.init(num_cpus=1)
config = R2D2_DEFAULT_CONFIG.copy()
config.update({
    "batch_mode": "complete_episodes",
    "num_workers": 1,
    "num_gpus": 0,
    "framework": 'torch',
    "hiddens": [5],
    "model": {
        "fcnet_activation": 'relu',
        "fcnet_hiddens": [5],
        "use_lstm": True,
        "lstm_cell_size": 5,
    },
})
agent = R2D2Trainer(config=config, env="CartPole-v1")
```
Fourth cell
```{python}
plt.plot(range(10))
plt.show()
```

This happens with different installs of jupyter (notebook, lab and also on Collab) and on different OSses (macOS and Linux, didn't test in Windows). I also have tried with different matplotlib versions back to 3.3.4 (didn't test on previous versions). 

Below is a screenshot of the notebook demonstrating the behaviour.

![Screenshot 2021-08-05 at 17 25 02](https://user-images.githubusercontent.com/3305726/128416353-63f73db1-ea95-4987-9637-05eddb136c0d.png)

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by Sepiafs** [comment] 2021-08-17 18:16
I have the same issue with ray version '1.5.0', python 3.8 on windows

**Comment by sgillen** [comment] 2021-08-18 18:58
Exact same issue for me, I'm on Ubuntu 18.04. python==3.6, ray==1.5.1, matplotlib==3.3.4,jupyterlab==3.1.7.

**Comment by timothy003** [comment] 2021-09-14 22:55
This is caused by #16675. The plot shows correctly if I remove this line:

https://github.com/ray-project/ray/blob/15512c27c252baa6760bc3ffd0aecf77d7cb16db/python/ray/tune/trainable.py#L79

**Comment by mehes-kth** [comment] 2021-09-21 13:54
This context manager provides a (hopefully temporary) workaround, until this gets fixed in Ray:
```python
from IPython.core.interactiveshell import InteractiveShell


class recover_ipython:
    def __enter__(self):
        self.instance = InteractiveShell.instance()
        
    def __exit__(self, *args, **kwargs):
        # feel free to improve with error handling, etc.
        InteractiveShell._instance = self.instance
```

Wrap calls that create agents like this:
```python
with recover_ipython():
    agent = R2D2Trainer(config=config, env="CartPole-v1")
```

![Screen Shot 2021-09-21 at 15 54 25](https://user-images.githubusercontent.com/84348450/134183794-1e398ff9-78db-47b2-afe1-806263435ba8.png)

**Comment by richardliaw** [comment] 2021-09-21 15:41
@krfricke can you take this one?

The right fix seems to be gating "self._disable_ipython" in the Trainable class with a check if you are in an actor or not.

**Comment by krfricke** [comment] 2021-09-21 15:57
Yes, happy to look into this!

**Closed** 2021-09-22 10:05 UTC
Labels: bug, regression, release-blocker, P0, tune
