### ISSUE TITLE
[dashboard] "new_dashboard" is leaking processes on Linux

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#12176] opened 2020-11-19 21:57 UTC
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* Ray 1.1dev

OS: Ubuntu 18.04
Python 3.6

When a ray is started and stopped with `ray.init()`, I see a process left over like this:

```
swang    30660  4805  1 16:55 pts/1    00:00:02 /home/swang/anaconda3/envs/ray-36/bin/python -u /home/swang/ray/python/ray/new_dashboard/agent.py ...
```

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

`ray.init()`

**Comment by stephanie-wang** [comment] 2020-11-19 21:58
cc @mfitton

**Comment by edoakes** [comment] 2020-11-19 22:05
Max is out until next week. @fyrestone @mxz96102 could you please take a look? This might be linux-only because I'm not able to repro locally.

**Comment by stephanie-wang** [comment] 2020-11-20 01:45
Closed by #12096 :)

**Comment by fyrestone** [comment] 2020-11-20 02:13
> Max is out until next week. @fyrestone @mxz96102 could you please take a look? This might be linux-only because I'm not able to repro locally.

The dashboard agent has a loop for checking parent is alive. https://github.com/ray-project/ray/blob/master/dashboard/agent.py#L90

**Comment by edoakes** [comment] 2020-11-20 16:16
@stephanie-wang did you confirm that this fixes the issue? Above it says you have processes left from ray.init() but #12096 seems to only change ray stop.

**Comment by stephanie-wang** [comment] 2020-11-20 16:24
Oh I think you're right about that. It seems it's still leaking processes. Here is the output that I have from a dashboard agent (it repeats this over and over):

```
2020-11-20 11:21:07,215	INFO agent.py:69 -- Dashboard agent grpc address: XXX.XXX.XXX.XXX:63209
2020-11-20 11:21:07,221	INFO utils.py:201 -- Get all modules by type: DashboardAgentModule
2020-11-20 11:21:07,889	INFO agent.py:82 -- Loading DashboardAgentModule: <class 'ray.new_dashboard.modules.log.log_agent.LogAgent'>
2020-11-20 11:21:07,889	INFO agent.py:82 -- Loading DashboardAgentModule: <class 'ray.new_dashboard.modules.reporter.reporter_agent.ReporterAgent'>
2020-11-20 11:21:07,892	INFO agent.py:86 -- Loaded 2 modules.
2020-11-20 11:21:07,893	INFO agent.py:150 -- Dashboard agent http address: XXX.XXX.XXX.XXX:42441
2020-11-20 11:21:07,894	INFO agent.py:157 -- <ResourceRoute [GET] <StaticResource  /logs -> PosixPath('/tmp/ray/session_2020-11-20_11-21-05_809084_19322/logs')> -> <bound method StaticResource._handle of <StaticResource  /logs -> PosixPath('/tmp/ray/session_2020-11-20_11-21-05_809084_19322/logs')>>
2020-11-20 11:21:07,894	INFO agent.py:157 -- <ResourceRoute [OPTIONS] <StaticResource  /logs -> PosixPath('/tmp/ray/session_2020-11-20_11-21-05_809084_19322/logs')> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7f4226661da0>>
2020-11-20 11:21:07,894	INFO agent.py:158 -- Registered 2 routes.
2020-11-20 11:21:10,437	ERROR reporter_agent.py:234 -- Error publishing node physical stats.
Traceback (most recent call last):
  File "/home/swang/ray/python/ray/new_dashboard/modules/reporter/reporter_agent.py", line 232, in _perform_iteration
    await aioredis_client.publish(self._key, jsonify_asdict(stats))
  File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/site-packages/aioredis/pool.py", line 257, in _wait_execute
    conn = await self.acquire(command, args)
  File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/site-packages/aioredis/pool.py", line 324, in acquire
    await self._fill_free(override_min=True)
  File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/site-packages/aioredis/pool.py", line 383, in _fill_free
    conn = await self._create_new_connection(self._address)
  File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/site-packages/aioredis/connection.py", line 113, in create_connection
    timeout)
  File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/site-packages/aioredis/stream.py", line 24, in open_connection
    lambda: protocol, host, port, **kwds)
  File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/asyncio/base_events.py", line 798, in create_connection
    raise exceptions[0]
  File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/asyncio/base_events.py", line 785, in create_connection
    yield from self.sock_connect(sock, address)
  File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('XXX.XXX.XXX.XXX', 6379)
```

**Comment by fyrestone** [comment] 2020-11-23 02:10
> Oh I think you're right about that. It seems it's still leaking processes. Here is the output that I have from a dashboard agent (it repeats this over and over):
> 
> ```
> 2020-11-20 11:21:07,215	INFO agent.py:69 -- Dashboard agent grpc address: XXX.XXX.XXX.XXX:63209
> 2020-11-20 11:21:07,221	INFO utils.py:201 -- Get all modules by type: DashboardAgentModule
> 2020-11-20 11:21:07,889	INFO agent.py:82 -- Loading DashboardAgentModule: <class 'ray.new_dashboard.modules.log.log_agent.LogAgent'>
> 2020-11-20 11:21:07,889	INFO agent.py:82 -- Loading DashboardAgentModule: <class 'ray.new_dashboard.modules.reporter.reporter_agent.ReporterAgent'>
> 2020-11-20 11:21:07,892	INFO agent.py:86 -- Loaded 2 modules.
> 2020-11-20 11:21:07,893	INFO agent.py:150 -- Dashboard agent http address: XXX.XXX.XXX.XXX:42441
> 2020-11-20 11:21:07,894	INFO agent.py:157 -- <ResourceRoute [GET] <StaticResource  /logs -> PosixPath('/tmp/ray/session_2020-11-20_11-21-05_809084_19322/logs')> -> <bound method StaticResource._handle of <StaticResource  /logs -> PosixPath('/tmp/ray/session_2020-11-20_11-21-05_809084_19322/logs')>>
> 2020-11-20 11:21:07,894	INFO agent.py:157 -- <ResourceRoute [OPTIONS] <StaticResource  /logs -> PosixPath('/tmp/ray/session_2020-11-20_11-21-05_809084_19322/logs')> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7f4226661da0>>
> 2020-11-20 11:21:07,894	INFO agent.py:158 -- Registered 2 routes.
> 2020-11-20 11:21:10,437	ERROR reporter_agent.py:234 -- Error publishing node physical stats.
> Traceback (most recent call last):
>   File "/home/swang/ray/python/ray/new_dashboard/modules/reporter/reporter_agent.py", line 232, in _perform_iteration
>     await aioredis_client.publish(self._key, jsonify_asdict(stats))
>   File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/site-packages/aioredis/pool.py", line 257, in _wait_execute
>     conn = await self.acquire(command, args)
>   File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/site-packages/aioredis/pool.py", line 324, in acquire
>     await self._fill_free(override_min=True)
>   File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/site-packages/aioredis/pool.py", line 383, in _fill_free
>     conn = await self._create_new_connection(self._address)
>   File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/site-packages/aioredis/connection.py", line 113, in create_connection
>     timeout)
>   File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
>     return (yield from fut)
>   File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/site-packages/aioredis/stream.py", line 24, in open_connection
>     lambda: protocol, host, port, **kwds)
>   File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/asyncio/base_events.py", line 798, in create_connection
>     raise exceptions[0]
>   File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/asyncio/base_events.py", line 785, in create_connection
>     yield from self.sock_connect(sock, address)
>   File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
>     return (yield from fut)
>   File "/home/swang/anaconda3/envs/ray-36/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
>     raise OSError(err, 'Connect call failed %s' % (address,))
> ConnectionRefusedError: [Errno 111] Connect call failed ('XXX.XXX.XXX.XXX', 6379)
> ```

This error is expected, because redis has exit. I will find out the cause of this problem.

**Comment by fyrestone** [comment] 2020-11-23 02:45
@stephanie-wang Can you help to find out what the parent pid of the agent process is? I can't reproduce this problem in my Linux, I wonder if it is caused by running in a container.

I will create a PR to fix this problem. It is not enough for dashboard agent to detect `ppid == 1` (The same logic from ray core https://github.com/ray-project/ray/blob/master/src/ray/util/process.cc#L569).

**Comment by ericl** [comment] 2020-12-14 19:22
cc @edoakes @mfitton since this is a P0 in dashboard, can one of you guys take a look?

**Comment by wuisawesome** [comment] 2020-12-14 19:37
btw I think this should just be a matter of tracking a process in the fate-sharing/reaper code.

**Comment by edoakes** [comment] 2020-12-14 19:51
@ericl @stephanie-wang is this reproducible? I haven't been able to reproduce it locally. Also, I thought the above PR fixed it -- is that not the case? Or was that PR reverted or something?

**Comment by ericl** [comment] 2020-12-14 19:55
@edoakes you need a Linux machine to reproduce. The PR above was reverted since it broke the build; not sure if it actually fixed the issue:

```
eric@eric-thinkpad-t490s:~/Desktop/ray#big-sur-fix$ ray stop
Did not find any active Ray processes.
eric@eric-thinkpad-t490s:~/Desktop/ray#big-sur-fix$ pytest python/ray/tests/test_multi_node_2.py::test_wait_for_nodes
Results (5.37s):
       1 passed
eric@eric-thinkpad-t490s:~/Desktop/ray#big-sur-fix$ ray stop
Stopped all 2 Ray processes.
```

**Comment by edoakes** [comment] 2020-12-14 21:04
@ericl I'm still not able to reproduce this unfortunately. This is with Ray built from source off of latest master on an AWS t3a instance running Ubuntu 18.04:
```
(base) ubuntu@ip-172-31-44-163:~/ray/python/ray$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
r>>> ray.init()
2020-12-14 21:03:15,434 INFO services.py:1171 -- View the Ray dashboard at http://127.0.0.1:8265
{'node_ip_address': '172.31.44.163', 'raylet_ip_address': '172.31.44.163', 'redis_address': '172.31.44.163:6379', 'object_store_address': '/tmp/ray/session_2020-12-14_21-03-14_962366_18515/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2020-12-14_21-03-14_962366_18515/sockets/raylet', 'webui_url': '127.0.0.1:8265', 'session_dir': '/tmp/ray/session_2020-12-14_21-03-14_962366_18515', 'metrics_export_port': 57450, 'node_id': '718eb7ddbb8bb086894cf39bb161d36d57bd54be'}
>>> 
[1]+  Stopped                 python
(base) ubuntu@ip-172-31-44-163:~/ray/python/ray$ ps aux | grep dashboard | wc -l
3
(base) ubuntu@ip-172-31-44-163:~/ray/python/ray$ fg
python
^C
KeyboardInterrupt
>>> 
(base) ubuntu@ip-172-31-44-163:~/ray/python/ray$ ps aux | grep dashboard | wc -l
1
(base) ubuntu@ip-172-31-44-163:~/ray/python/ray$ python -m pytest tests/test_multi_node_2.py::test_wait_for_nodes
============================================ test session starts =============================================
platform linux -- Python 3.8.5, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/ubuntu/ray/python
collected 1 item                                                                                             

tests/test_multi_node_2.py .                                                                           [100%]

============================================= 1 passed in 5.03s ==============================================
(base) ubuntu@ip-172-31-44-163:~/ray/python/ray$ ps aux | grep dashboard | wc -l
1
```

**Comment by ericl** [comment] 2020-12-14 21:06
Maybe it only applies to custom compiles?

**Comment by mfitton** [comment] 2020-12-14 21:07
The original fix PR was reverted. Let me see if another fix was made. Maybe there's another PR to cherry-pick instead.

**Comment by edoakes** [comment] 2020-12-15 02:45
We were unable to reproduce this on an EC2 instance but @ericl confirmed that the reverted PR above fixes the issue for him Made a new PR to get that fix merged:
https://github.com/ray-project/ray/pull/12867

**Closed** 2020-12-15 19:36 UTC
Labels: P0, bug, dashboard, release-blocker
