### ISSUE TITLE
[Feature] Create and publish in pypi a wheel for linux arm64

### ISSUE THREAD

**Issue by azisi** [ray-project/ray#21786] opened 2022-01-21 22:15 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Create and publish in pypi a wheel for linux arm64, so that i can pip install ray inside a docker container running in docker for mac in apple silicon/m1.

### Use case

Able to pip install ray inside a docker container running in docker for mac in apple silicon/m1.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by MarvinSt** [comment] 2022-01-23 16:06
would love to see this as well!

**Comment by billadam28** [comment] 2022-01-24 10:12
I would love to see this as well!!

**Comment by ddelange** [comment] 2022-03-18 14:37
duplicate of #12128

**Comment by aviau** [comment] 2022-08-04 12:55
We would love to see this.

**Comment by baswelsh** [comment] 2022-08-16 20:20
VERY interested in this.  Without it, we are unable to use Ray from a Docker container running on ARM (Apple Silicon).  We instead need to run our containers as x86 which is very slow on the M1s.

**Comment by etorhub** [comment] 2022-08-31 07:38
Indeed, this would save our lives. Very interested on this.

**Comment by ddelange** [comment] 2022-08-31 07:57
> Indeed, this would save our lives. Very interested on this.

xref https://github.com/ray-project/ray/issues/12128#issuecomment-1163980281

**Comment by ezorita** [comment] 2022-08-31 16:49
+1

**Comment by infherny** [comment] 2022-10-11 20:00
+1

**Comment by rsantanna** [comment] 2022-10-11 20:14
+1

**Comment by mattip** [comment] 2022-10-20 17:31
This is different from #12128, which is specific to raspberry pi wheels. Those are difficult to publish since they are not supported on PyPI.

**Comment by mattip** [comment] 2022-11-13 15:35
Duplicate of #13780. Closing. Please comment on the other issue, or reopen this with an explanation of why this is different.

**Closed by mattip** 2022-11-13 15:35 UTC
Labels: enhancement, QS

**Comment by pcmoritz** [comment] 2023-01-10 01:49
We now have nightly wheels https://github.com/ray-project/ray/pull/31522 and for future releases we will also push those to pypi (possibly retroactively for Ray 2.2 if there is sufficient interest).

**Comment by krfricke** [comment] 2023-01-10 21:11
I've just uploaded 2.2.0 ARM wheels to PyPI, so `pip install ray` will now work
