### ISSUE TITLE
[CI] `osx://python/ray/tests:test_runtime_env_working_dir_3` is failing/flaky on master.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#34740] opened 2023-04-25 12:00 UTC
- b09f3ec179cff0f201aca94740858eed700db924 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3581#0187ace7-b389-40d3-bf8d-04c5699dbff8)
- d571fa2b5eb6ea14c75fba71a41edf1b6e8c700b FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3478#018795b8-bf4a-44d5-b2e6-107d1b268d03)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-osx://python/ray/tests:test_runtime_env_working_dir_3-END
....

**Comment by rynewang** [comment] 2023-07-27 22:39
It's port conflict on dashboard agent start up. Should be fixed by https://github.com/ray-project/ray/pull/37585 because we will no longer use dashboard agent port.

**Comment by rynewang** [comment] 2023-08-13 22:38
Not reproducible

**Closed by rynewang** 2023-08-13 22:38 UTC
Labels: P0, core, flaky-tracker
