### ISSUE TITLE
[tune] "unexpected keyword argument 'points_to_evaluate'" even after installing the nightly version on Goggle Colab Pro

### ISSUE THREAD

**Issue by zrajabi** [ray-project/ray#14609] opened 2021-03-10 23:28 UTC
Hi @turmeric-blend, 
I have installed using the following wheel as was suggested to resolve the issue raised by you here but still get the error:

Ray nightly version on Colab Pro: ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64
!pip install https://s3-us-west-2.amazonaws.com/ray-wheels/master/ba6cebe30fab6925e5b2d9e859ad064d53015246/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl

the `points_to_evaluate` arguments for most algorithms are currently only available in the nightly wheels / current master and not in the latest release.
You can try `ray install-nightly` to install the nightly wheels.

_Originally posted by @krfricke in https://github.com/ray-project/ray/issues/13576#issuecomment-763431897_

**Comment by krfricke** [comment] 2021-03-12 08:57
Hi @zrajabi, can you share the code you are running or the relevant parts from the Colab?

Please also restart the kernel after installing the latest wheels (or only import Ray after updating the wheels), otherwise python might still be working we the previously installed version.

What is `ray.__version__`? I.e. the output of this code:

```
>>> import ray
>>> ray.__version__
'2.0.0.dev0'
```

The wheels you posted definitely contain the relevant changes, and I just confirmed it is working in a fresh environment:

```
> pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/master/ba6cebe30fab6925e5b2d9e859ad064d53015246/ray-2.0.0.dev0-cp37-cp37m-macosx_10_13_intel.whl
> pip install "ray[tune]" optuna
> python
>>> from ray.tune.suggest.optuna import OptunaSearch
>>> OptunaSearch(points_to_evaluate=[])
<ray.tune.suggest.optuna.OptunaSearch object at 0x1010fce90>
```

**Comment by krfricke** [comment] 2021-03-17 09:34
I'll close this for now since it is probably a usage error. Let me know if the issue persists and can be reproduced on a clean environment/colab.

**Closed by krfricke** 2021-03-17 09:34 UTC
Labels: tune
