### ISSUE TITLE
[core] Assertion failure (it->second.submitted_task_ref_count > 0) during dependency resolution

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#18908] opened 2021-09-27 04:24 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

```
[2021-09-25 13:34:55,450 C 655 718] reference_count.cc:352:  Check failed: it->second.submitted_task_ref_count > 0
--
  | *** StackTrace Information ***
  | ray::SpdLogMessage::Flush()
  | ray::RayLog::~RayLog()
  | ray::core::ReferenceCounter::RemoveSubmittedTaskReferences()
  | ray::core::ReferenceCounter::UpdateSubmittedTaskReferences()
  | ray::core::TaskManager::OnTaskDependenciesInlined()
  | std::_Function_handler<>::_M_invoke()
  | ray::core::CoreWorkerMemoryStore::Put()
  | ray::core::TaskManager::MarkPendingTaskFailed()
  | ray::core::TaskManager::PendingTaskFailed()
  | ray::core::CoreWorkerDirectActorTaskSubmitter::DisconnectActor()
  | ray::core::ActorManager::HandleActorStateNotification()
  | std::_Function_handler<>::_M_invoke()
  | ray::gcs::GcsPubSub::ExecuteCommandIfPossible()::{lambda()#1}::operator()()
  | std::_Function_handler<>::_M_invoke()
  | std::_Function_handler<>::_M_invoke()
  | boost::asio::detail::completion_handler<>::do_complete()
  | boost::asio::detail::scheduler::do_run_one()
  | boost::asio::detail::scheduler::run()
  | boost::asio::io_context::run()
  | ray::core::CoreWorker::RunIOService()
  | execute_native_thread_routine
```

### Reproduction script

https://buildkite.com/ray-project/periodic-ci/builds/1112#e3ad94ef-d92f-4b57-9759-e3693cda9884

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment] 2021-09-27 13:48
cc @stephanie-wang

**Comment by ericl** [comment] 2021-10-05 00:17
Closing this for now (could not reproduce). It's unlikely to be fixed, but it currently is too infrequent to be debuggable.

**Comment by scv119** [comment] 2022-06-20 23:58
```
ServeController pid=2178) [2022-06-16 16:25:31,742 C 2178 2205] reference_count.cc:434:  Check failed: it->second.submitted_task_ref_count > 0 
(ServeController pid=2178) *** StackTrace Information ***
(ServeController pid=2178)     ray::SpdLogMessage::Flush()
(ServeController pid=2178)     ray::RayLog::~RayLog()
(ServeController pid=2178)     ray::core::ReferenceCounter::RemoveSubmittedTaskReferences()
(ServeController pid=2178)     ray::core::ReferenceCounter::UpdateSubmittedTaskReferences()
(ServeController pid=2178)     ray::core::TaskManager::OnTaskDependenciesInlined()
(ServeController pid=2178)     std::_Function_handler<>::_M_invoke()
(ServeController pid=2178)     ray::core::CoreWorkerMemoryStore::Put()
(ServeController pid=2178)     ray::core::TaskManager::MarkTaskReturnObjectsFailed()
(ServeController pid=2178)     ray::core::TaskManager::FailPendingTask()
(ServeController pid=2178)     ray::core::TaskManager::FailOrRetryPendingTask()
(ServeController pid=2178)     ray::core::CoreWorkerDirectActorTaskSubmitter::DisconnectActor()
(ServeController pid=2178)     EventTracker::RecordExecution()
(ServeController pid=2178)     std::_Function_handler<>::_M_invoke()
(ServeController pid=2178)     boost::asio::detail::completion_handler<>::do_complete()
(ServeController pid=2178)     boost::asio::detail::scheduler::do_run_one()
(ServeController pid=2178)     boost::asio::detail::scheduler::run()
(ServeController pid=2178)     boost::asio::io_context::run()
(ServeController pid=2178)     ray::core::CoreWorker::RunIOService()
(ServeController pid=2178)     execute_native_thread_routine
```

**Comment by sihanwang41** [comment] 2022-06-21 03:15
I did some debugging and the issue happens at one scenario. https://github.com/ray-project/ray/blob/master/python/ray/serve/deployment_state.py#L334

When doing the FailOrRetryPendingTask. 
For unknown reason, the `reconfigure` task will do decrease the reference count to its argument `_allocated_obj_ref` **first**, and then the  `_allocated_obj_ref` reference count becomes 0, and then is_allocated task will also decrease the reference count to `_allocated_obj_ref` and then it bring up the error message. 

In contrast, when task succeed,  `is_allocated` tasks will always be the **first** to finish, and the `reconfigure` tasks won't have the argument `_allocated_obj_ref` as object ref any more.

**Comment by iycheng** [comment] 2022-06-27 21:56
@stephanie-wang  do you have some bandwidth to take a look? it seems related to ref count.

**Closed** 2022-07-13 21:39 UTC
Labels: bug, P0, Ray 2.0
