### ISSUE TITLE
[Serve] Proxy stuck in restarting loop during when serve start

### ISSUE THREAD

**Issue by GeneDer** [ray-project/ray#39716] opened 2023-09-17 00:29 UTC
### What happened + What you expected to happen

This is an intermittent failure, and was only able to reproduce in aviary Anyscale org (not seem in staging at least). Some VMs seem to have issue/ taking a long time (~23s) to start proxy with uvloop. This caused the default 5s proxy ready timeout to always met and serve controller killing and restart a new proxy. Due to this proxy ready process was never able to complete, we will just see logs like the following noting that the proxy stuck in a restarting loop
```
2904INFO 2023-09-15 18:08:58,621 controller 1666 http_state.py:488 - Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-7745cec1475fe1a0f1de1e6153df143335db4467df10bc2975f81e1a' on node '7745cec1475fe1a0f1de1e6153df143335db4467df10bc2975f81e1a' listening on '0.0.0.0:8000'
2903INFO 2023-09-15 18:08:58,620 controller 1666 http_state.py:515 - HTTP proxy on node '7745cec1475fe1a0f1de1e6153df143335db4467df10bc2975f81e1a' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.
2902WARNING 2023-09-15 18:08:58,620 controller 1666 http_state.py:242 - Didn't receive ready check response for HTTP proxy 7745cec1475fe1a0f1de1e6153df143335db4467df10bc2975f81e1a after 5.0s.
2901INFO 2023-09-15 18:08:53,557 controller 1666 http_state.py:488 - Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-7745cec1475fe1a0f1de1e6153df143335db4467df10bc2975f81e1a' on node '7745cec1475fe1a0f1de1e6153df143335db4467df10bc2975f81e1a' listening on '0.0.0.0:8000'
2900INFO 2023-09-15 18:08:53,556 controller 1666 http_state.py:515 - HTTP proxy on node '7745cec1475fe1a0f1de1e6153df143335db4467df10bc2975f81e1a' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.
2899WARNING 2023-09-15 18:08:53,556 controller 1666 http_state.py:242 - Didn't receive ready check response for HTTP proxy 7745cec1475fe1a0f1de1e6153df143335db4467df10bc2975f81e1a after 5.0s.
2898INFO 2023-09-15 18:08:48,496 controller 1666 http_state.py:488 - Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-7745cec1475fe1a0f1de1e6153df143335db4467df10bc2975f81e1a' on node '7745cec1475fe1a0f1de1e6153df143335db4467df10bc2975f81e1a' listening on '0.0.0.0:8000'
2897INFO 2023-09-15 18:08:48,495 controller 1666 http_state.py:515 - HTTP proxy on node '7745cec1475fe1a0f1de1e6153df143335db4467df10bc2975f81e1a' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.
2896WARNING 2023-09-15 18:08:48,494 controller 1666 http_state.py:242 - Didn't receive ready check response for HTTP proxy 7745cec1475fe1a0f1de1e6153df143335db4467df10bc2975f81e1a after 5.0s.
2895INFO 2023-09-15 18:08:43,435 controller 1666 http_state.py:488 - Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-7745cec1475fe1a0f1de1e6153df143335db4467df10bc2975f81e1a' on node '7745cec1475fe1a0f1de1e6153df143335db4467df10bc2975f81e1a' listening on '0.0.0.0:8000'
2894INFO 2023-09-15 18:08:43,434 controller 1666 http_state.py:515 - HTTP proxy on node '7745cec1475fe1a0f1de1e6153df143335db4467df10bc2975f81e1a' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.
```

In a normal case, proxy should start within 5s. The user shouldn't need to set `RAY_SERVE_DEBUG_MODE=1` or `RAY_SERVE_PROXY_READY_CHECK_TIMEOUT_S=100` to bypass this issue. 

- This is an example workspace with experiencing the proxy restart loop: [Cloned-Workspace-from-praveen-endpoints-demo](https://console.anyscale.com/o/aviary/workspaces/expwrk_mlhp11crgw6gmi9ikrpne528xm/ses_1eb9agzwuf9lxdiy8rd7safv81)
- This is an example workspace with `RAY_SERVE_PROXY_READY_CHECK_TIMEOUT_S=100` set and showing that the proxy takes 23s to start [Cloned-Workspace-from-praveen-endpoints-demo-gene-test](https://console.anyscale.com/o/aviary/workspaces/expwrk_6law1t1dpyq7g3n66v8rbfpply/ses_bu8e7vz6e5spzbj3f19ud34vqp). At the time when someone is working on this issue, the workspace might be terminated already. But if it's started on an issue VM, then we should see it takes quite sometime to start proxy and not seeing it failing and stuck in a loop like the above. Might need to terminate and restart this workspace to see it land on an issue VM
- This is an example workspace with `RAY_SERVE_DEBUG_MODE=1` set and never experience the same issue [Cloned-Workspace-from-Cloned-Workspace-from-Cloned-Workspace-from-praveen-endpoints-demo-gene-test...](https://console.anyscale.com/o/aviary/workspaces/expwrk_zl9h18dmkbi2tskqvxmlcwv1ae/ses_t98kyydf48ac71sy911ns3sccj)

PS. We also saw stack trace like below so suspecting this is caused by the recent uvloop change. 
```
148Traceback (most recent call last):
149  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/serve/_private/replica.py", line 730, in wrap_user_method_call
150    yield
151  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/serve/_private/replica.py", line 878, in call_user_method
152    raise e from None
153ray.exceptions.RayTaskError: anyio._backends._asyncio.ExceptionGroup: 2 exceptions were raised in the task group:
154----------------------------
155[36mray::ServeReplica:router:Router.handle_request_streaming()[39m (pid=3078, ip=10.0.61.80)
156  File "/home/ray/anaconda3/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 167, in try_connect
157    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
158  File "/home/ray/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1627, in connect_tcp
159    await get_running_loop().create_connection(
160  File "uvloop/loop.pyx", line 2039, in create_connection
161  File "uvloop/loop.pyx", line 2016, in uvloop.loop.Loop.create_connection162ConnectionRefusedError: [Errno 111] Connection refused
```

### Versions / Dependencies

Ray Nightly as of 9/15/2023 (maybe?) Basically whatever that's in this docker image 241673607239.dkr.ecr.us-west-2.amazonaws.com/aviary:release-endpoints-80a7920396e7587b95597fae59bf32cd9a77a007

### Reproduction script

- starting a serve in a workspace or services with config environment [praveen-aviary-byod:2](https://console.anyscale.com/o/aviary/configurations/app-config-details/bld_k79d23yd6pqfsuzqu7ux56hq4v), if landed on issue VM, we will see proxy stuck in restarting loop
- starting a serve in a workspace or services with config environment [gene-aviary-byod:1](https://console.anyscale.com/o/aviary/configurations/app-config-details/bld_543nc273qcd6q2i1hdysybj7kk), with `RAY_SERVE_DEBUG_MODE=1` set, we never see an issue
- starting a serve in a workspace or services with config environment [gene-aviary-byod:2](https://console.anyscale.com/o/aviary/configurations/app-config-details/bld_ntz7a89jhzszs4u553keahi19w), with `RAY_SERVE_PROXY_READY_CHECK_TIMEOUT_S=100` set, we will experience long proxy start time (~23s) during serve start if landed on an issue VM

** all those are ran from "aviary" Anyscale org

### Issue Severity

High: It blocks me from completing my task.

**Comment by GeneDer** [comment] 2023-09-18 15:52
We also see an occasion of the restarting loop happening on the service using Ray 2.6.3 [service-embedding](https://console.anyscale.com/o/demos/services/service2_4f2qwfzfynftmh87795rj1wjw8) in the demo org. This suggest the error is not caused by the uvloop.

<img width="1564" alt="image" src="https://github.com/ray-project/ray/assets/7553988/08f0e15e-518f-4126-b6dc-68573e5811d9">

**Comment by alexeykudinkin** [comment] 2023-09-29 18:50
@GeneDer we can close this one, provided that we figure the issue was caused by the worker shell script taking too long to start (due to misconfiguration of the DNS on the host, sudo was taking 10s to execute)

**Comment by GeneDer** [comment] 2023-09-29 18:54
@alexeykudinkin yes and no, I'm working on adding a linear backoff to the proxy so if the same issue happen again it will be mitigated automatically. There's a PR attached to this https://github.com/ray-project/ray/pull/39738

This is taking longer bc we are also doing a refactoring of the proxy state and making test better at the same time. Reopen for now. Eta is next Tuesday.

**Closed** 2023-10-12 15:08 UTC
Labels: bug, serve
