### ISSUE TITLE
Ray Serve multimodel deployments with FastAPI issue

### ISSUE THREAD

**Issue by somal** [ray-project/ray#41439] opened 2023-11-28 14:57 UTC
I try to infer my HF model. I split it into 3 deployments: HTTP, CPU(pre/post-processing), and GPU (model inference).
Also, I try to wrap HTTP deployment into FastAPI app `@serve.ingress(app)`.

And always in runtime, it writes 'LongPollClient timed out. Retrying'

... But if delete integration with FastAPI, this warning disappears

**Comment by somal** [comment] 2023-12-04 17:08
@shrekris-anyscale 
```import asyncio
import logging
import uuid
from typing import List, Tuple

import torch
from PIL import Image
from aiobotocore.session import get_session
from fastapi.responses import JSONResponse
from ray import serve
from starlette.requests import Request
from transformers import *

MAX_BATCH_SIZE = 16
MODEL_NAME = ""
MODEL_CACHE_DIR = "./cache"
VIDEO_BUCKET_NAME = ""


class DeploymentGPU:
    DEFAULT_MODEL_ARGS = dict()

    def __init__(self):
        self._model = <>
        self._device = self._model.device

        self._pixel_values_batch_gpu = None
        self._generated_ids_batch_gpu = None
        self._generated_ids_batch_cpu = None

    def __call__(self, pixel_values_batch_cpu: torch.Tensor) -> torch.Tensor:
        torch.cuda.empty_cache()

        self._pixel_values_batch_gpu = pixel_values_batch_cpu.to(self._model.device)  # [B, 3, 224, 224]

        self._generated_ids_batch_gpu = self._model.generate(
            pixel_values=self._pixel_values_batch_gpu,
            **self.DEFAULT_MODEL_ARGS
        )  # [B, 21])
        self._generated_ids_batch_cpu = self._generated_ids_batch_gpu.to('cpu')
        return self._generated_ids_batch_cpu


@serve.deployment
class DeploymentCPU:
    FILES_DOWNLOAD_TIMEOUT = 300

    def __init__(self):
        # self._model_gpu_deployment = model_gpu_deployment  # .options(use_new_handle_api=True)
        self._model_gpu_deployment = ImageCaptioningBLIPDeploymentGPU()

        self._processor = AutoProcessor.from_pretrained(MODEL_NAME, cache_dir=MODEL_CACHE_DIR)
        self._aibotocore_session = get_session()

        self._logger = logging.getLogger("ray.serve")
        self._logger.setLevel(level=logging.DEBUG)

    async def __call__(self, request: Request) -> JSONResponse:
        payload = await request.json()
        s3_image_path = payload.get(<>, None)
        if s3_image_path is None:
            return JSONResponse(status_code=400, content=dict(response={}, error='Add "inputs" to parameters'))
        self._logger.info(f'Processing request for: {s3_image_path}')

        try:
            img_caption = await self._processing(s3_image_path)
            self._logger.info(f'Img caption: {img_caption}')
            response = img_caption
        except Exception as e:
            self._logger.error(e)
            return JSONResponse(status_code=400, content=dict(response={}, error=str(e)))

        result = JSONResponse(status_code=200, content=dict(response=response, error={}))
        return result

    @serve.batch(max_batch_size=MAX_BATCH_SIZE, batch_wait_timeout_s=.5)
    async def _processing(self, s3_image_paths: List[str]) -> List[str]:
        local_file_paths = await asyncio.wait_for(
            asyncio.gather(
                *[self._download_from_s3(VIDEO_BUCKET_NAME, s3_image_path)
                  for s3_image_path in s3_image_paths]),
            timeout=self.FILES_DOWNLOAD_TIMEOUT)

        pixel_values_batch_cpu: torch.Tensor = self.preprocess(local_file_paths)

        generated_ids_batch_cpu = self._model_gpu_deployment.__call__(pixel_values_batch_cpu)

        output_batch = self.postprocess(generated_ids_batch_cpu)  # [B, X]
        output = [output_batch[i] for i in range(len(s3_image_paths))]

        return output

    def preprocess(self, local_file_paths: Tuple[str]) -> torch.Tensor:
        images = [Image.open(local_file_path) for local_file_path in local_file_paths]
        pixel_values = self._processor(images=images, return_tensors="pt").pixel_values
        pixel_values = pixel_values.to(torch.float16)
        return pixel_values

    def postprocess(self, generated_ids: torch.Tensor) -> List[str]:
        result = [row.strip() for row in self._processor.batch_decode(generated_ids, skip_special_tokens=True)]
        return result

    async def _download_from_s3(self, bucket_name: str, s3_image_path: str) -> str:
        tmp_file_path = f'/tmp/{uuid.uuid4()}'
        try:
            async with self._aibotocore_session.create_client('s3') as client:
                response = await client.get_object(Bucket=bucket_name, Key=s3_image_path)
                async with response['Body'] as stream:
                    with open(tmp_file_path, 'wb') as file:
                        file.write(await stream.read())
            self._logger.info(f'{s3_image_path} is downloaded to {tmp_file_path}')
        except Exception:
            raise RuntimeError(f'File not found. Bucket: {bucket_name}. Path: {s3_image_path}')
        return tmp_file_path


pipeline = DeploymentCPU.options(
    route_prefix='/model',
    name='DeploymentCPU',
    num_replicas=1,
    max_concurrent_queries=MAX_BATCH_SIZE,
    ray_actor_options={"num_cpus": 1,
                       "num_gpus": 1},
).bind()

**Comment by shrekris-anyscale** [comment] 2023-12-05 00:34
Thanks for following up @somal! Could you minimize the application-related code in the repro? It's not possible for us to run this now because the model is (understandably) redacted, and it's a tough to understand all the application-specific logic.

In general, [minimal reproductions](https://stackoverflow.com/help/minimal-reproducible-example) should provide as little code as possible that still produces the problem.

**Comment by somal** [comment] 2023-12-05 16:17
@shrekris-anyscale, thank you for your support!
This is the minimal code
```
import logging

from fastapi import FastAPI
from fastapi.responses import JSONResponse
from ray import serve
from starlette.requests import Request

API_PREFIX = '/'

app = FastAPI()


@serve.deployment
class Service1:
    def __init__(self):
        self._service = None


@serve.deployment
@serve.ingress(app)
class Service2:
    def __init__(self, service1_deployment):
        self._service1 = service1_deployment.options(use_new_handle_api=True)

        self._logger = logging.getLogger("ray.serve")
        self._logger.setLevel(logging.DEBUG)

    @app.post('/call')
    async def call(self, request: Request) -> JSONResponse:
        payload = await request.json()
        self._logger.info(f'Input: {payload}')
        response = ''
        result = JSONResponse(status_code=200, content=dict(error=None,
                                                            response=response))
        return result


service1 = Service1.options(
    num_replicas=2,
    ray_actor_options=dict(num_cpus=.5),
    max_concurrent_queries=1,
).bind()

service2 = Service2.options(
    route_prefix=API_PREFIX,
    ray_actor_options=dict(num_cpus=.5),
    num_replicas=2,
    max_concurrent_queries=20,
).bind(service1)

if __name__ == '__main__':
    from time import sleep

    serve.run(service2, host='0.0.0.0', port=8002)

    sleep(120)
```

There are logs:
```
2023-12-05 17:12:58,388	WARNING deployment.py:404 -- DeprecationWarning: `route_prefix` in `@serve.deployment` has been deprecated. To specify a route prefix for an application, pass it into `serve.run` instead.
/Users/msokolov/Documents/PycharmProjects/ReCam/ML_backend/venv/lib/python3.9/site-packages/ray/serve/api.py:479: UserWarning: Specifying host and port in `serve.run` is deprecated and will be removed in a future version. To specify custom HTTP options, use `serve.start`.
  warnings.warn(
2023-12-05 17:13:00,457	INFO worker.py:1664 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
(ProxyActor pid=34234) INFO 2023-12-05 17:13:07,717 proxy 127.0.0.1 proxy.py:1072 - Proxy actor 1c5ba1470fdc5029ccae45ba01000000 starting on node b379b09c00bc7ef8fae5ec2462b4956e6983009ab0a2047ccf9ba2e1.
(ProxyActor pid=34234) INFO 2023-12-05 17:13:07,726 proxy 127.0.0.1 proxy.py:1257 - Starting HTTP server on node: b379b09c00bc7ef8fae5ec2462b4956e6983009ab0a2047ccf9ba2e1 listening on port 8002
(ProxyActor pid=34234) INFO:     Started server process [34234]
(ServeController pid=34231) INFO 2023-12-05 17:13:07,844 controller 34231 deployment_state.py:1379 - Deploying new version of deployment Service1 in application 'default'.
(ServeController pid=34231) INFO 2023-12-05 17:13:07,847 controller 34231 deployment_state.py:1379 - Deploying new version of deployment Service2 in application 'default'.
(ServeController pid=34231) INFO 2023-12-05 17:13:07,952 controller 34231 deployment_state.py:1668 - Adding 2 replicas to deployment Service1 in application 'default'.
(ServeController pid=34231) INFO 2023-12-05 17:13:07,962 controller 34231 deployment_state.py:1668 - Adding 2 replicas to deployment Service2 in application 'default'.
(ServeReplica:default:Service2 pid=34238) DEBUG 2023-12-05 17:13:55,421 Service2 default#Service2#IYHHWo long_poll.py:151 - LongPollClient polling timed out. Retrying.
```
And `LongPollClient polling timed out. Retrying.` appears every X seconds

Libraries:
ray                                      2.8.0
starlette                             0.27.0
fastapi                                0.103.2

**Comment by shrekris-anyscale** [comment] 2023-12-05 23:22
Thanks for the minimal repro! I took a look, and this is expected behavior. The logs appear even if Serve is operating normally.

For context, Serve actors use a long poller internally to detect changes in other actors. This long poller periodically times out and reconnects in order to clear connections from dead actors. After timing out, the long poller logs [a debug message](https://github.com/ray-project/ray/blob/ba53d2f332654ffe2da98935f25241b0a79cd0da/python/ray/serve/_private/long_poll.py#L151-L154).

Currently, Serve replicas only use a LongPoll client if they hold a handle to another Serve deployment. The reason you see the message isn't because the Serve deployment uses FastAPI; it's actually because the FastAPI `Service2` deployment in your repro holds a `ServeHandle` for the `Service1` deployment. If you remove the `Service2` FastAPI integration, you'll still see the timeout messages.

Note that the timeout messages are debug logs. They're appearing in the first place only because the `Service2` replica sets `self._logger.setLevel(logging.DEBUG)` in its constructor. Removing this should also make the logs stop appearing.

Since there's no bug, I'll close this issue. Let us know if you have any questions or concerns!

**Closed by shrekris-anyscale** 2023-12-05 23:22 UTC
