### ISSUE TITLE
Should I  specify the num_gpus for remote class for using the gpus or how to use the gpus with pytorch?

### ISSUE THREAD

**Issue by zhan0903** [ray-project/ray#3910] opened 2019-01-30 23:18 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

### Source code / logs

Hi. When I use the Ray with pytorch, I do not set any num_gpus flag for the remote class. I got the error: RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. But when I print "torch.cuda.is_available()", It is True. Any suggestions? Thanks.

**Comment by richardliaw** [comment] 2019-01-30 23:39
Hi, can you post this on stackoverflow (along with some relevant reproduction information)? Thanks!

**Comment by zhan0903** [comment] 2019-01-30 23:47
> Hi, can you post this on stackoverflow (along with some relevant reproduction information)? Thanks!

Sure. The main process is: I create a remote class and transfer a pytorch model state_dict()(created in main function) to it. In the main function, the torch.cuda.is_available() is True, but In the remote function, torch.cuda.is_available() is False.

**Comment by robertnishihara** [comment] 2019-01-31 00:02
Closing because the conversation has been migrated to https://stackoverflow.com/questions/54451362/how-to-use-gpus-with-ray-in-pytorch-should-i-specify-the-num-gpus-for-the-remot.

**Closed by robertnishihara** 2019-01-31 00:02 UTC
