### ISSUE TITLE
[VM Launcher] Default to latest ray version instead of master when docker image is not specified

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#35018] opened 2023-05-03 22:04 UTC
### What happened + What you expected to happen

When you start a cluster on ec2, if you don't specify the docker image, it will install ray master by default.
We should default to latest ray version.

### Versions / Dependencies

2.4

### Reproduction script

The example yaml file in the ray doc: https://docs.ray.io/en/latest/cluster/vms/getting-started.html#launch-a-cluster-on-a-cloud-provider

### Issue Severity

Low: It annoys or frustrates me.

**Comment by scottsun94** [comment] 2023-05-03 22:04
@gvspraveen @wuisawesome

**Comment by architkulkarni** [comment] 2023-05-03 23:14
Duplicate of https://github.com/ray-project/ray/issues/34991

@scottsun94 Feel free to reopen if I made a mistake

**Closed by architkulkarni** 2023-05-03 23:14 UTC
Labels: bug, triage, clusters
