### ISSUE TITLE
seg fault/Core Dump after running ray tune jobs in k8s cluster

### ISSUE THREAD

**Issue by tylerkohn** [ray-project/ray#13302] opened 2021-01-08 21:38 UTC
I have a k8s cluster with 32 workers and 1 head on 16 nodes.  When I run 32 jobs that each span about 11 experiments eventually after about 30 or so minutes the logs in the ray-head will report a core dump and all the jobs will fail.

using:
- python 3.8
- ray 1.0.1.post1
- GKE k8s cluster
- k8s version v1.16.15-gke.4300
- Ubuntu 18.04.5 LTS

an example fo this
```
(pid=38, ip=10.40.17.10) Result for mwatsywer6a4ssyhghniuq:
(pid=38, ip=10.40.17.10)   date: 2021-01-08_19-09-29
(pid=38, ip=10.40.17.10)   done: false
*** Aborted at 1610132978 (unix time) try "date -d @1610132978" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x1821a5b87) received by PID 57 (TID 0x7f062cff9700) from PID 18446744071597349767; stack trace: ***
    @     0x7f07ff762980 (unknown)
    @           0x55d28f PyEval_RestoreThread
    @     0x7f07fd58fa77 __pyx_pw_3ray_7_raylet_10CoreWorker_65get_named_actor_handle()
    @           0x5d242c (unknown)
    @           0x5566d2 _PyEval_EvalFrameDefault
    @           0x4fa05a _PyFunction_Vectorcall
    @           0x55a47a _PyEval_EvalFrameDefault
    @           0x4fa9aa _PyObject_Call_Prepend
    @           0x534747 (unknown)
    @           0x531b8e (unknown)
    @           0x4f98f9 _PyObject_MakeTpCall
    @           0x55a217 _PyEval_EvalFrameDefault
    @           0x4fa05a _PyFunction_Vectorcall
    @           0x5ce881 (unknown)
    @           0x556398 _PyEval_EvalFrameDefault
    @           0x5553e0 _PyEval_EvalCodeWithName
    @           0x4fa0ed _PyFunction_Vectorcall
    @           0x556398 _PyEval_EvalFrameDefault
    @           0x4fa05a _PyFunction_Vectorcall
    @           0x4fb31b PyVectorcall_Call
    @           0x557ed8 _PyEval_EvalFrameDefault
    @           0x4fa05a _PyFunction_Vectorcall
    @           0x5566d2 _PyEval_EvalFrameDefault
    @           0x4fa05a _PyFunction_Vectorcall
    @           0x4fb31b PyVectorcall_Call
    @           0x557ed8 _PyEval_EvalFrameDefault
    @           0x4fa05a _PyFunction_Vectorcall
    @           0x5566d2 _PyEval_EvalFrameDefault
    @           0x4fa05a _PyFunction_Vectorcall
    @           0x5566d2 _PyEval_EvalFrameDefault
    @           0x4fa05a _PyFunction_Vectorcall
    @           0x5ce9a0 (unknown)
Segmentation fault (core dumped)
(pid=38, ip=10.40.17.10)
```

additionally I'm seeing these messages and subsequent failures as well:
```
    self._actor = ray.get_actor(CONTINUAL_TRAINER_ACTOR_NAME)
  File "python/ray/_raylet.pyx", line 1287, in ray._raylet.CoreWorker.get_named_actor_handle
  File "python/ray/_raylet.pyx", line 144, in ray._raylet.check_status
ray.exceptions.GetTimeoutError: There was timeout in getting the actor handle. It is probably because GCS server is dead or there's a high load there
```

This does not occur on a smaller cluster running fewer jobs.  on cluster half the size I can run half or fewer concurrent sets of experiments without problems.  I'm trying to scale this up so that I can run more in parallel and am hitting this issue.

**Comment by richardliaw** [comment] 2021-01-09 05:40
@tylerkohn this is pretty bad, can you provide a core dump?

Also, how are you using the `get_actor` in your workload?

cc @rkooo567

**Comment by tylerkohn** [comment] 2021-01-10 21:20
Thanks for taking a look!

Not sure about the core dump - k8s is restarting the pod when it crashes.  Any advice on finding it?

We are using a TrainingDetailsModelVersion for each model we are training that is calling get_actor.  when we create that object we call:
```
class TrainingDetailsModelVersion:
    def __init__(self, model_version_name: str):
        self._lock = threading.Lock()
        self._actor = ray.get_actor(TRAINER_ACTOR_NAME)
        self._model_version_name = model_version_name
        self._port = -1

        self._sequence_lock = threading.Lock()
        with self._sequence_lock:
            self._sequence = 0

        return
```
TRAINER_ACTOR_NAME is a constant.  

we use this to keep track of information relating to a model that is being trained (e.g):
```
    def put_extra_details(self, key: str, val):
        func_oid = self._actor.put_extra_details.remote(
            self._model_version_name, key, val
        )
        ray.get(func_oid)
        return
```

when we want to put or get information we call TrainingDetailsModelVersion(modelVersionName) to get this object and interact with it. 

we train hundreds of models.  Now that I look at it, is using a single actor going to cause issues (don't remember why we did this)?

Also, I noticed a few other things:
1. this core dump seems to happen when the head has less memory allocated to it then the workers
2. when i only have a single worker on a k8s node execution for a training happens a lot faster (~3-6 minutes vs 12-30 minutes)
3. after we have cycled through a number of models to train (more than 1 per worker) things slow down and I start seeing messages like:
```
 (pid=7318, ip=10.40.1.9) 2021-01-10 20:53:46,869        WARNING util.py:137 -- The `process_trial` operation took 136.6077697277069 seconds to complete, which may be a performance bottleneck.
```

**Comment by tylerkohn** [comment] 2021-01-11 00:21
another core dump.  pod got restarted by k8s so don't think there's a core dump file to get.

this ran for about 2 hours crunching away until this happened.   This run I set the deployment requirements so that a worker (And the head) are on an individual k8s node.   seem to work a lot better/faster until this hit!

The trainingGRPCserver you see there is a GRPC server we start on the head so we can query the system for status on jobs that are running.  It looks up the actor to get the details for training runs.

```
E0110 23:41:35.775079    64   126 direct_task_transport.cc:333] The worker failed to receive a response from the local raylet. This is most likely because the local raylet has crahsed.
F0110 23:41:35.775130    64   126 direct_task_transport.cc:336] IOError: 14: Connection reset by peer
*** Check failure stack trace: ***
2021-01-10 23:41:35 ERROR    Exception calling application: System error: Broken pipe
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/app/continual/services/ray_services/training/training_grpc_server.py", line 246, in GetTrainingJob
    training_details_dict = training_details_actor.get_model_version_dict()
  File "/app/continual/services/ray_services/training/training_details_actor.py", line 316, in get_model_version_dict
    return ray.get(training_details_oid)
  File "/venv/lib/python3.8/site-packages/ray/worker.py", line 1447, in get
    values = worker.get_objects(object_refs, timeout=timeout)
  File "/venv/lib/python3.8/site-packages/ray/worker.py", line 314, in get_objects
    data_metadata_pairs = self.core_worker.get_objects(
  File "python/ray/_raylet.pyx", line 818, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 818, in ray._raylet.CoreWorker.get_objects
ray.exceptions.RaySystemError: System error: Broken pipe
2021-01-10 23:41:35 ERROR    Exception calling application: System error: Broken pipe
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/app/continual/services/ray_services/training/training_grpc_server.py", line 246, in GetTrainingJob
    training_details_dict = training_details_actor.get_model_version_dict()
  File "/app/continual/services/ray_services/training/training_details_actor.py", line 316, in get_model_version_dict
    return ray.get(training_details_oid)
  File "/venv/lib/python3.8/site-packages/ray/worker.py", line 1447, in get
    values = worker.get_objects(object_refs, timeout=timeout)
  File "/venv/lib/python3.8/site-packages/ray/worker.py", line 314, in get_objects
    data_metadata_pairs = self.core_worker.get_objects(
  File "python/ray/_raylet.pyx", line 818, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 148, in ray._raylet.check_status
ray.exceptions.RaySystemError: System error: Broken pipe
2021-01-10 23:41:35 ERROR    Exception calling application: System error: Broken pipe
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/app/continual/services/ray_services/training/training_grpc_server.py", line 246, in GetTrainingJob
    training_details_dict = training_details_actor.get_model_version_dict()
  File "/app/continual/services/ray_services/training/training_details_actor.py", line 316, in get_model_version_dict
    return ray.get(training_details_oid)
  File "/venv/lib/python3.8/site-packages/ray/worker.py", line 1447, in get
    values = worker.get_objects(object_refs, timeout=timeout)
  File "/venv/lib/python3.8/site-packages/ray/worker.py", line 314, in get_objects
    data_metadata_pairs = self.core_worker.get_objects(
  File "python/ray/_raylet.pyx", line 818, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 148, in ray._raylet.check_status
ray.exceptions.RaySystemError: System error: Broken pipe
2021-01-10 23:41:35 ERROR    Exception calling application: System error: Connection reset by peer
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/app/continual/services/ray_services/training/training_grpc_server.py", line 246, in GetTrainingJob
    training_details_dict = training_details_actor.get_model_version_dict()
  File "/app/continual/services/ray_services/training/training_details_actor.py", line 316, in get_model_version_dict
    return ray.get(training_details_oid)
  File "/venv/lib/python3.8/site-packages/ray/worker.py", line 1447, in get
    values = worker.get_objects(object_refs, timeout=timeout)
  File "/venv/lib/python3.8/site-packages/ray/worker.py", line 314, in get_objects
    data_metadata_pairs = self.core_worker.get_objects(
  File "python/ray/_raylet.pyx", line 818, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 148, in ray._raylet.check_status
ray.exceptions.RaySystemError: System error: Connection reset by peer
2021-01-10 23:41:35 ERROR    Exception calling application: System error: Broken pipe
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/app/continual/services/ray_services/training/training_grpc_server.py", line 246, in GetTrainingJob
    training_details_dict = training_details_actor.get_model_version_dict()
  File "/app/continual/services/ray_services/training/training_details_actor.py", line 316, in get_model_version_dict
    return ray.get(training_details_oid)
  File "/venv/lib/python3.8/site-packages/ray/worker.py", line 1447, in get
    values = worker.get_objects(object_refs, timeout=timeout)
  File "/venv/lib/python3.8/site-packages/ray/worker.py", line 314, in get_objects
    data_metadata_pairs = self.core_worker.get_objects(
  File "python/ray/_raylet.pyx", line 818, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 148, in ray._raylet.check_status
ray.exceptions.RaySystemError: System error: Broken pipe
    @     0x7f60c0c19b5d  google::LogMessage::Fail()
2021-01-10 23:41:35 ERROR    Exception calling application: System error: Broken pipe
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/app/continual/services/ray_services/training/training_grpc_server.py", line 246, in GetTrainingJob
    training_details_dict = training_details_actor.get_model_version_dict()
  File "/app/continual/services/ray_services/training/training_details_actor.py", line 316, in get_model_version_dict
    return ray.get(training_details_oid)
  File "/venv/lib/python3.8/site-packages/ray/worker.py", line 1447, in get
    values = worker.get_objects(object_refs, timeout=timeout)
  File "/venv/lib/python3.8/site-packages/ray/worker.py", line 314, in get_objects
    data_metadata_pairs = self.core_worker.get_objects(
  File "python/ray/_raylet.pyx", line 818, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 148, in ray._raylet.check_status
ray.exceptions.RaySystemError: System error: Broken pipe
2021-01-10 23:41:35 ERROR    Exception calling application: System error: Broken pipe
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/app/continual/services/ray_services/training/training_grpc_server.py", line 246, in GetTrainingJob
    training_details_dict = training_details_actor.get_model_version_dict()
  File "/app/continual/services/ray_services/training/training_details_actor.py", line 316, in get_model_version_dict
    return ray.get(training_details_oid)
  File "/venv/lib/python3.8/site-packages/ray/worker.py", line 1447, in get
    values = worker.get_objects(object_refs, timeout=timeout)
  File "/venv/lib/python3.8/site-packages/ray/worker.py", line 314, in get_objects
    data_metadata_pairs = self.core_worker.get_objects(
  File "python/ray/_raylet.pyx", line 818, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 148, in ray._raylet.check_status
ray.exceptions.RaySystemError: System error: Broken pipe
2021-01-10 23:41:35 ERROR    Exception calling application: System error: Broken pipe
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/app/continual/services/ray_services/training/training_grpc_server.py", line 246, in GetTrainingJob
    training_details_dict = training_details_actor.get_model_version_dict()
  File "/app/continual/services/ray_services/training/training_details_actor.py", line 316, in get_model_version_dict
    return ray.get(training_details_oid)
  File "/venv/lib/python3.8/site-packages/ray/worker.py", line 1447, in get
    values = worker.get_objects(object_refs, timeout=timeout)
  File "/venv/lib/python3.8/site-packages/ray/worker.py", line 314, in get_objects
    data_metadata_pairs = self.core_worker.get_objects(
  File "python/ray/_raylet.pyx", line 818, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 148, in ray._raylet.check_status
ray.exceptions.RaySystemError: System error: Broken pipe
    @     0x7f60c0c1afcc  google::LogMessage::SendToLog()
    @     0x7f60c0c19839  google::LogMessage::Flush()
    @     0x7f60c0c19a51  google::LogMessage::~LogMessage()
    @     0x7f60c0bccec9  ray::RayLog::~RayLog()
    @     0x7f60c089fbec  _ZZN3ray29CoreWorkerDirectTaskSubmitter24RequestNewWorkerIfNeededERKSt5tupleIIiSt6vectorINS_8ObjectIDESaIS3_EENS_7ActorIDEEEPKNS_3rpc7AddressEENKUlRKNS_6StatusERKNSA_23RequestWorkerLeaseReplyEE_clESG_SJ_
    @     0x7f60c08de8b5  ray::rpc::ClientCallImpl<>::OnReplyReceived()
    @     0x7f60c083b770  _ZN5boost4asio6detail18completion_handlerIZN3ray3rpc17ClientCallManager29PollEventsFromCompletionQueueEiEUlvE_E11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm
    @     0x7f60c0c7b97f  boost::asio::detail::scheduler::do_run_one()
    @     0x7f60c0c7c741  boost::asio::detail::scheduler::run()
    @     0x7f60c0c7d692  boost::asio::io_context::run()
    @     0x7f60c081c2b0  ray::CoreWorker::RunIOService()
    @     0x7f60c0134a50  (unknown)
    @     0x7f60c29876db  start_thread
    @     0x7f60c1abc71f  clone
Aborted (core dumped)
```

**Comment by richardliaw** [comment] 2021-01-11 00:33
@tylerkohn do you have any logs of memory? also, on the head-node, usually ray should create logs via `/tmp/ray/session_latest`. Is there any way of getting these logs, as it'll probably point out the cause of this issue.

cc @rkooo567

**Comment by tylerkohn** [comment] 2021-01-11 07:07
will try...the pod restarts but will see about checking the gcp vm instance and setting up an persistent volume.

See these as well:
```
2021-01-11 06:10:11,239 WARNING worker.py:1093 -- WARNING: 10 PYTHON workers have been started. This could be a result of using a large number of actors, or it could be a consequence of using nested tasks (se
e https://github.com/ray-project/ray/issues/3644) for some a discussion of workarounds.
```
and
```
(pid=raylet, ip=10.40.30.2)   File "/venv/lib/python3.8/site-packages/ray/workers/default_worker.py", line 167, in <module>
2021-01-11 06:10:11,391 WARNING worker.py:1093 -- A worker died or was killed while executing task ffffffffffffffff9796f32e01000000.
(pid=raylet, ip=10.40.32.2) E0111 06:10:11.353085     8     8 process.cc:498] Failed to kill process 9161 with error system:3: No such process
E0111 06:10:11.442694    54   122 core_worker.cc:419] Will resubmit task after a 5000ms delay: Type=NORMAL_TASK, Language=PYTHON, Resources: {CPU: 1, }, function_descriptor={type=PythonFunctionDescriptor, mod
ule_name=continual.services.ray_services.training.continual_trainer, class_name=, function_name=ContinualRayTrainer, function_hash=3c64637946dbf13ae6df3813fcdd4df77e0fe91a}, task_id=8b52151a8a692a3bffffffff01
000000, task_name=ContinualRayTrainer(), job_id=01000000, num_args=16, num_returns=1
(pid=raylet, ip=10.40.12.2) E0111 06:10:11.387457     9     9 node_manager.cc:535] Failed to send local GC request: IOError: 14: Socket closed
E0111 06:10:11.485312    54   122 core_worker.cc:419] Will resubmit task after a 5000ms delay: Type=NORMAL_TASK, Language=PYTHON, Resources: {CPU: 1, }, function_descriptor={type=PythonFunctionDescriptor, mod
ule_name=continual.services.ray_services.training.continual_trainer, class_name=, function_name=ContinualRayTrainer, function_hash=3c64637946dbf13ae6df3813fcdd4df77e0fe91a}, task_id=40d423529b979046ffffffff01
000000, task_name=ContinualRayTrainer(), job_id=01000000, num_args=16, num_returns=1
```
and 
```
(pid=raylet, ip=10.40.30.2) redis.exceptions.ConnectionError: Error 111 connecting to 10.44.5.146:6379. Connection refused.
E0111 06:10:13.756018    54   122 core_worker.cc:419] Will resubmit task after a 5000ms delay: Type=NORMAL_TASK, Language=PYTHON, Resources: {CPU: 1, }, function_descriptor={type=PythonFunctionDescriptor, module_name=continual.services.ray_services.training.continual_trainer, class_name=, function_name=ContinualRayTrainer, function_hash=3c64637946dbf13ae6df3813fcdd4df77e0fe91a}, task_id=276c086ca8ed2092ffffffff01000000, task_name=ContinualRayTrainer(), job_id=01000000, num_args=16, num_returns=1
(pid=raylet, ip=10.40.33.2) Traceback (most recent call last):
(pid=raylet, ip=10.40.33.2)   File "/venv/lib/python3.8/site-packages/redis/connection.py", line 552, in connect
(pid=raylet, ip=10.40.33.2)     sock = self._connect()
(pid=raylet, ip=10.40.33.2)   File "/venv/lib/python3.8/site-packages/redis/connection.py", line 609, in _connect
(pid=raylet, ip=10.40.33.2)     raise err
(pid=raylet, ip=10.40.33.2)   File "/venv/lib/python3.8/site-packages/redis/connection.py", line 597, in _connect
(pid=raylet, ip=10.40.33.2)     sock.connect(socket_address)
(pid=raylet, ip=10.40.33.2) ConnectionRefusedError: [Errno 111] Connection refused
```

I'm definitely doing something the system doesn't like.  I'm sure those logs and a core dump will be useful ;-) working to get them.  Is the actor pattern i'm using above likely to cause a problem (having a single named actor used by everything)?

I took a look a the issue page referenced above and will see if there are things we are doing that are inefficient.

**Comment by tylerkohn** [comment] 2021-01-11 23:56
haven't core dumped yet but not pushing it too hard.  I am seeing things slow down over time and seeing high CPU for actors that shouldn't be doing anything. The batchprediction related actor should be doing nothing.

[session_2021-01-11_22-29-57_319554_6 2.zip](https://github.com/ray-project/ray/files/5798953/session_2021-01-11_22-29-57_319554_6.2.zip)
[session_2021-01-11_22-29-57_319554_6.zip](https://github.com/ray-project/ray/files/5798954/session_2021-01-11_22-29-57_319554_6.zip)


```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                               
   7005 root      20   0 17.043g 909020 400432 S  40.7  1.7  13:03.01 ray::ContinualR                                                                                          8696 root      20   0 14.615g 939172 377504 S  38.0  1.8  11:27.38 ray::ImplicitFu                                                                                       
   5344 root      20   0 14.731g 745644 344372 S  37.0  1.4  11:02.29 ray::BatchPredi                                                                                          4306 root      20   0 16.304g 755836 347104 S  35.0  1.4  11:40.08 ray::IDLE                                                                                             
   8657 root      20   0 15.925g 817544 357644 S  27.7  1.5  11:55.63 ray::ContinualR                                                                                          6287 root      20   0 14.063g 721024 330192 S  26.7  1.3  11:33.76 ray::IDLE                                                                                             
   7828 root      20   0 15.281g 798076 368444 S  24.0  1.5  11:35.22 ray::BatchPredi                                                                                          9132 root      20   0 14.595g 946848 376712 S  16.3  1.8  11:14.00 ray::ImplicitFu                                                                                       
   8984 root      20   0 14.595g 947680 377688 S  14.7  1.8  11:10.51 ray::ImplicitFu                                                                                          8640 root      20   0 16.035g 855732 371120 S  14.0  1.6  11:55.42 ray::ContinualR                                                                                       
   8805 root      20   0 14.616g 939588 377692 S  13.3  1.8  11:16.36 ray::ImplicitFu                                                                                          5359 root      20   0 16.492g 755160 346860 S  12.7  1.4  11:39.53 ray::BatchPredi                                                                                       
   8752 root      20   0 14.579g 915912 372844 S  12.7  1.7  11:11.95 ray::ImplicitFu                                                                                          4570 root      20   0 15.599g 860508 362424 S  11.3  1.6  11:24.94 ray::IDLE                                                                                             
     10 root      20   0  198764  49716  25264 S   9.3  0.1   6:28.67 /venv/bin/pytho                                                                                          2809 root      20   0 16.491g 755520 347384 S   8.3  1.4  11:45.13 ray::IDLE              
```

**Comment by rkooo567** [comment] 2022-12-08 05:01
I believe this is fixed in the master. Please reopen the issue if you still see the issue

**Closed by rkooo567** 2022-12-08 05:01 UTC
Labels: bug, P2, k8s
