### ISSUE TITLE
[release][weekly] `learning_tests` failed

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#20385] opened 2021-11-15 19:29 UTC
https://buildkite.com/ray-project/periodic-ci/builds/1621#eeafa268-0368-4875-a5de-3aa8b998d3f5

```




Analyzing experiment ppo-breakoutnoframeskip-v4-torch ...
  | ... Trials: [PPO_BreakoutNoFrameskip-v4_39c7b_00000].
  | ... Desired reward=50.0; desired throughput=972.2222222222222
  | ... Successful: (mark ok).
  | Analyzing experiment sac-halfcheetahbulletenv-v0-torch ...
  | ... Trials: [SAC_HalfCheetahBulletEnv-v0_39c7b_00001].
  | ... Desired reward=500.0; desired throughput=13.88888888888889
  | ... Successful: (mark ok).
  | Analyzing experiment td3-halfcheetahbulletenv-v0-tf ...
  | ... Trials: [TD3_HalfCheetahBulletEnv-v0_39c7b_00002].
  | ... Desired reward=400.0; desired throughput=138.88888888888889
  | ... Not successful: Actual reward=404.23096283571743; actual throughput=56.037505379002276
  | Analyzing experiment td3-halfcheetahbulletenv-v0-torch ...
  | ... Trials: [TD3_HalfCheetahBulletEnv-v0_39c7b_00003].
  | ... Desired reward=400.0; desired throughput=138.88888888888889
  | ... Not successful: Actual reward=407.2058860631569; actual throughput=39.62698388114434
  | Traceback (most recent call last):
  | File "learning_tests/run.py", line 40, in <module>
  | json.dump(results, f)
  | File "/home/ray/anaconda3/lib/python3.7/json/__init__.py", line 179, in dump
  | for chunk in iterable:
  | File "/home/ray/anaconda3/lib/python3.7/json/encoder.py", line 431, in _iterencode
  | yield from _iterencode_dict(o, _current_indent_level)
  | File "/home/ray/anaconda3/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
  | yield from chunks
  | File "/home/ray/anaconda3/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
  | yield from chunks
  | File "/home/ray/anaconda3/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
  | yield from chunks
  | File "/home/ray/anaconda3/lib/python3.7/json/encoder.py", line 438, in _iterencode
  | o = _default(o)
  | File "/home/ray/anaconda3/lib/python3.7/json/encoder.py", line 179, in default
  | raise TypeError(f'Object of type {o.__class__.__name__} '
  | TypeError: Object of type float32 is not JSON serializable
 

<br class="Apple-interchange-newline">
```

**Comment by amogkam** [comment] 2021-11-15 19:44
@gjoliver looks like there's been some throughput regressions.

**Comment by gjoliver** [comment] 2021-11-15 19:52
it is actually a testing harness bug, I probably introduced it. let me send you a PR soon.

**Comment by iycheng** [comment] 2021-11-19 06:44
@gjoliver I'm reopening this since it still fails https://buildkite.com/ray-project/periodic-ci/builds/1716#70d3fc92-7874-4cfb-a2c7-1a4dc4f389e4


The error looks similar as before:
```




Analyzing experiment appo-pongnoframeskip-v4-torch ...
  | ... Trials: [APPO_PongNoFrameskip-v4_0675b_00000].
  | ... Desired reward=18.0; desired throughput=None
  | ... Successful: (mark ok).
  | Analyzing experiment sac-halfcheetahbulletenv-v0-torch ...
  | ... Trials: [SAC_HalfCheetahBulletEnv-v0_0675b_00001].
  | ... Desired reward=500.0; desired throughput=None
  | ... Successful: (mark ok).
  | Traceback (most recent call last):
  | File "learning_tests/run.py", line 40, in <module>
  | json.dump(results, f)
  | File "/home/ray/anaconda3/lib/python3.7/json/__init__.py", line 179, in dump
  | for chunk in iterable:
  | File "/home/ray/anaconda3/lib/python3.7/json/encoder.py", line 431, in _iterencode
  | yield from _iterencode_dict(o, _current_indent_level)
  | File "/home/ray/anaconda3/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
  | yield from chunks
  | File "/home/ray/anaconda3/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
  | yield from chunks
  | File "/home/ray/anaconda3/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
  | yield from chunks
  | File "/home/ray/anaconda3/lib/python3.7/json/encoder.py", line 438, in _iterencode
  | o = _default(o)
  | File "/home/ray/anaconda3/lib/python3.7/json/encoder.py", line 179, in default
  | raise TypeError(f'Object of type {o.__class__.__name__} '
  | TypeError: Object of type float32 is not JSON serializable
 

<br class="Apple-interchange-newline">

**Comment by gjoliver** [comment] 2021-11-19 16:03
have trouble re-produce it. ok.

**Comment by amogkam** [comment] 2021-11-19 23:26
Hey @iycheng this is resolved on master by  #20387 and #20439. Here's the passing test from earlier today https://buildkite.com/ray-project/periodic-ci/builds/1726#69928313-bceb-4fb7-b3ba-dc819d425be5

**Comment by zhe-thoughts** [comment] 2021-11-20 16:20
Yup this is not a release blocker. Thanks for the diligent checking @iycheng !

**Comment by gjoliver** [comment] 2021-11-20 16:42
This is a test with #20439 picked to 1.9rc0 branch that passed without problem.
https://github.com/gjoliver/ray/commits/releases/1.9.0rc0
I am going to close this issue now, since we are not cherry-picking, and there is nothing left to do.
Thanks all.

**Closed by gjoliver** 2021-11-20 16:42 UTC
Labels: release-blocker, P0
