### ISSUE TITLE
[2.0][nightly-test] many-tasks regression

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27606] opened 2022-08-07 00:36 UTC
### What happened + What you expected to happen

many_tasks test regression: 
https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_Ueg7eY6NXWCWW5cmifgvagVF?command-history-section=event_log&drivers-section=deployments passing
https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_wnF3jdENJ3rDBEiJA3E9BsrU?command-history-section=command_history failing

### Versions / Dependencies

master / releases/2.0.0

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by scv119** [comment] 2022-08-07 04:20
https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_3NTcHnGMAtw8auqTJ2ENEmGc?command-history-section=command_history failing  8d848890

**Comment by scv119** [comment] 2022-08-07 05:09
https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_7tbk9PcfR4AFDsvT8QFEuKis?command-history-section=command_history failing  6efca71c35fc644eeb4d1f6ce092b5ca3be9b1ae

**Comment by scv119** [comment] 2022-08-07 05:46
https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_M9c52ScxDzFeXgbfRTLm9Hve?command-history-section=command_history failed

**Comment by scv119** [comment] 2022-08-07 06:26
https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_iV2gaNPYm5WMxE4nwxFE6pen?command-history-section=command_history passed

**Comment by scv119** [comment] 2022-08-07 06:28
hmm it points to f7ae8923f652779d8eff392d23ec491549352cb5

**Comment by clarkzinzow** [comment] 2022-08-07 20:04
@scv119 That being the culprit seems very unlikely, that PR is all docs and has no meaningful code changes. The only code changes are:
- privatized a few AIR abstractions,
- fixed an import.
Neither of these should affect the `many_tasks` path.

**Comment by scv119** [comment] 2022-08-07 23:37
huh... looks the import might slow down things

**Comment by scv119** [comment] 2022-08-07 23:39
with that import:
```
Success! Started 100 tasks in 35.653570890426636s. (17.687935985614516 tasks/s)
```

without import

```
Success! Started 100 tasks in 34.369340658187866s. (22.886748327257653 tasks/s)
```

**Comment by scv119** [comment] 2022-08-07 23:48
i'm 95% confident the slows down is caused by the import.

**Comment by clarkzinzow** [comment] 2022-08-08 02:03
Hmm that's surprising, I wouldn't expect that module to be imported unless `ray.data` was imported... 🤔 

This is probably an issue because we eagerly import the `data` subpackage [here](https://github.com/ray-project/ray/blob/a61095a48073c0fd878cc2fa6beea81f77817124/python/ray/__init__.py#L170), when `ray` is imported, to allow for the `ray.data` attribute access to the `data` subpackage.

@ericl why was that eager tensor type import needed again?

**Comment by ericl** [comment] 2022-08-08 03:04
Without the eager import, then implicit tensor conversion can crash (it crashes example doccode actually).

We've run into this lazy data import issue a bunch of times. Is there some simple way of fixing it like making it import on first attribute access?

**Comment by clarkzinzow** [comment] 2022-08-08 05:53
@ericl Yep there's a simple pattern (for Python 3.7, see [PEP](https://peps.python.org/pep-0562/)) for that that I think I mentioned a while back:
```python
# In __init__.py

__all__ = [
    "data",
    "workflow",
    ...,
]

def __getattr__(value):
    if name in __all__:
        return importlib.import_module("." + name, __name__)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
```

Would love for us to standardize on this!

**Comment by clarkzinzow** [comment] 2022-08-08 05:54
For the tensor extension specifically, I'd need to look at the error, that sounds like a more specific issue.

**Comment by ericl** [comment] 2022-08-08 06:09
You can reproduce by running the tensors doc code with the import commented
out, that should raise an exception in the conversions I believe.

**Comment by clarkzinzow** [comment] 2022-08-08 19:55
@ericl @scv119 I have two PRs out, one with the small-scope fix for this specific issue with the tensor extension type importing, the other with a more generic fix for making expensive, isolated subpackages (like Datasets) dynamically imported upon `ray.data` attribute access:
1. https://github.com/ray-project/ray/pull/27653
2. https://github.com/ray-project/ray/pull/27658

The specific, small-scope fix reverts back to pre-regression throughput for the smoke test on the many-tasks release test, while the generic fix (dynamic import on attribute access) is another 10-20% faster than that.

**Comment by clarkzinzow** [comment] 2022-08-08 21:13
@ericl @scv119 Comparisons on the two approaches for the smoke tests:
1. Small-scope fix: 22 tasks/second
2. Generic fix: 26 tasks/second

I'm going to kick off the full release test for each to see the difference.

**Closed** 2022-08-09 00:06 UTC
Labels: bug, release-blocker, triage, unbreak-now
