### ISSUE TITLE
Carriage return strange behavior

### ISSUE THREAD

**Issue by vlad17** [ray-project/ray#798] opened 2017-08-01 22:49 UTC
After ray is initialized, carriage return changes its behavior (this is a problem if you're training something which logs progress to a terminal). The attached notebook demonstrates first correct behavior and then behavior after initializing ray.
[colorama-cr.ipynb.zip](https://github.com/ray-project/ray/files/1192165/colorama-cr.ipynb.zip)

**Comment by robertnishihara** [comment] 2017-08-01 22:58
Thanks for investigating this! It looks like the problem is triggered by 

```python
import colorama
colarama.init()
```

Colorama is a module we use to print some error messages in color to make the errors a little more readable. It isn't really critical, so it could be removed if it's a problem.

Your example seems to work fine in an IPython interpreter, but not in a Jupyter notebook.

What are you using carriage returns for?

**Comment by vlad17** [comment] 2017-08-01 23:06
Yes, I also found that it only breaks in Jupyter. Keras uses carriage returns to update the progress bar, so when it runs code like this (yes, for some reason Keras prints the progress bar in two `write`s):

    sys.stdout.write('[===>    ]')
    sys.stdout.write(' some metric = 7')
    sys.stdout.flush()
    sys.stdout.write('\r)
    sys.stdout.write('[====>   ]')
    sys.stdout.write(' some metric = 8')
    sys.stdout.flush()

We expect the printout to be `[===>    ] some metric = 7`  then `[====>   ] some metric = 8`. With colorama, the second write after the carriage return gets moved to the end of the line (somehow, probably a colorama bug). It ends up semi-overlapped, like `[===>    ] some metric = 7 some metric = 8`, which obviously gets overwhelming as training goes on.

I think using colorama is fine, it's just a bit of a surprise/hard to debug if you don't know it's being used. Would running `colorama.deinit()` break anything? If not, then just documenting the fact that it's used would suffice, since anyone who doesn't want it could just disable it.

**Comment by robertnishihara** [comment] 2017-08-01 23:29
It looks like the call to `colorama.init()` actually isn't necessary (at least on Mac, I'm trying it out on Ubuntu now). In that case we can just remove the call as in #799.

**Comment by robertnishihara** [comment] 2017-08-01 23:31
Yeah, the colors show up on Ubuntu even without the call to `colorama.init()`.

**Comment by pcmoritz** [comment] 2017-08-01 23:40
Hm, looks like the init is only to perform some conversions for Win32, so should be fine not doing it:
https://github.com/tartley/colorama/blob/master/colorama/initialise.py#L76

**Comment by robertnishihara** [comment] 2017-08-02 02:11
Addressed by #799. Thanks for pointing this out! And let us know if you continue to see problems.

**Closed by robertnishihara** 2017-08-02 02:11 UTC
