### ISSUE TITLE
Make it possible to connect to Ray from multiple users on the same machine

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#2200] opened 2018-06-07 08:20 UTC
see https://groups.google.com/forum/#!topic/ray-dev/AGlrON95M0c

This would be very useful functionality to have, contributions welcome!

**Comment by robertnishihara** [comment] 2018-06-08 00:53
I just tried this on AWS and it worked for me (one user was `ubuntu` and one was `root`). I tried with both users using the same Python executable and also with different executables.

I suspect the issue is that the two users have different Python versions or Ray versions.

**Comment by robertnishihara** [comment] 2019-03-12 19:08
Closing because I think this works. Feel free to reopen if you see the issue.

**Closed by robertnishihara** 2019-03-12 19:08 UTC
Labels: help wanted
