### ISSUE TITLE
[Bug] `ExternalMultiAgentEnv.log_returns()` called with wrong signature

### ISSUE THREAD

**Issue by import-antigravity** [ray-project/ray#18907] opened 2021-09-27 03:59 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

I'm setting up an RL server+client setup where I log the reward simply with `env.log_returns(state.episode_id, reward)`, where `reward` is a float. When I do that, the following error happens:

```
Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/ray/rllib/env/policy_client.py", line 184, in log_returns
    return self.env.log_returns(episode_id, reward, info)
  File ".../lib/python3.8/site-packages/ray/rllib/env/external_multi_agent_env.py", line 140, in log_returns
    for agent, rew in reward_dict.items():
AttributeError: 'float' object has no attribute 'items'
```

The culprit seems to be L184 in `PolicyClient.log_returns`:
```python
        if self.local:
            self._update_local_policy()
            if multiagent_done_dict is not None:
                assert isinstance(reward, dict)
                return self.env.log_returns(episode_id, reward, info,
                                            multiagent_done_dict)
            return self.env.log_returns(episode_id, reward, info)
```

`self.env` is a MultiAgentExternalEnv, which is expecting the signature:

```python
    def log_returns(self,
                    episode_id: str,
                    reward_dict: MultiAgentDict,
                    info_dict: MultiAgentDict = None,
                    multiagent_done_dict: MultiAgentDict = None) -> None:
```

So this seems to be a bug. I can't find a way to disable multi-agent training, since my environment should be a single agent as it is.

### Reproduction script

This should happen with the cartpole example, but the cartpole example also fails when I try to run it due to another error.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by gjoliver** [comment] 2021-09-27 17:25
For multi agent environments, rewards need to be keyed by the corresponding agent ids.
So this is not a bug for multi-agent external env.

How is your environment set up? Can you share a reproduce-able script so we can understand this problem better?

**Comment by import-antigravity** [comment] 2021-09-28 04:35
I can't really make any promises about a reproducible script since my use-case is kind of complicated. I'm basically trying to train an RLLib policy to do hyperparameter tuning. It's really not very complicated but there's nothing in my code that tells the server or client to make a multi-agent environment so I don't know why it's doing that...

**Comment by gjoliver** [comment] 2021-09-28 05:02
ok, here are the 2 different log_returns(), just for our information.

https://github.com/ray-project/ray/blob/master/rllib/env/external_env.py#L145-L148

https://github.com/ray-project/ray/blob/master/rllib/env/external_multi_agent_env.py#L118-L122

**Comment by import-antigravity** [comment] 2021-09-28 20:21
Okay, here's a simple script that illustrates the issue.

Server:
```python
import logging

import ray
from gym.spaces import Box
from ray.rllib.agents.sac import SACTrainer
from ray.rllib.env import PolicyServerInput

logging.basicConfig(level=logging.DEBUG)

RL_PORT = 9900

try:
    ray.init(address='auto')
except ConnectionError:
    pass

observation_space = Box(0, 10, shape=(10,))
action_space = Box(0, 10, shape=(10,))

n_episodes = 10
episode_length = 100


class TuningServer:
    def __init__(self):
        self.checkpoint_path = 'checkpoint'
        self.stop_iters = n_episodes
        self.steps_per_iter = episode_length
        print('Starting server')

        # `InputReader` generator (returns None if no input reader is needed on
        # the respective worker).
        def _input(ioctx):
            # We are remote worker or we are local worker with num_workers=0:
            # Create a PolicyServerInput.
            if ioctx.worker_index > 0 or ioctx.worker.num_workers == 0:
                return PolicyServerInput(
                    ioctx, 'localhost', RL_PORT + ioctx.worker_index -
                                        (1 if ioctx.worker_index > 0 else 0))
            # No InputReader (PolicyServerInput) needed.
            else:
                return None

        # Trainer config. Note that this config is sent to the client only in case
        # the client needs to create its own policy copy for local inference.
        config = {
            # Indicate that the Trainer we setup here doesn't need an actual env.
            # Allow spaces to be determined by user (see below).
            "env": None,

            "observation_space": observation_space,
            "action_space": action_space,

            # Use the `PolicyServerInput` to generate experiences.
            "input": _input,
            # Use n worker processes to listen on different ports.
            "num_workers": 1,
            # Disable OPE, since the rollouts are coming from online clients.
            "input_evaluation": [],
            # Create a "chatty" client/server or not.
            "callbacks": None,
            # DL framework to use.
            "framework": 'torch',
            # Set to INFO so we'll see the server's actual address:port.
            "log_level": "INFO",
            # How many steps of the model to sample before learning starts.
            "learning_starts": 0,
            # Update the replay buffer with this many samples at once. Note that this
            # setting applies per-worker if num_workers > 1.
            "rollout_fragment_length": 10,
            # Size of a batched sampled from replay buffer for training.
            "train_batch_size": 2,
            # Number of env steps to optimize for before returning.
            "timesteps_per_iteration": self.steps_per_iter * 2,

            # Model options for the Q network(s). These will override MODEL_DEFAULTS.
            # The `Q_model` dict is treated just as the top-level `model` dict in
            # setting up the Q-network(s) (2 if twin_q=True).
            # That means, you can do for different observation spaces:
            # obs=Box(1D) -> Tuple(Box(1D) + Action) -> concat -> post_fcnet
            # obs=Box(3D) -> Tuple(Box(3D) + Action) -> vision-net -> concat w/ action
            #   -> post_fcnet
            # obs=Tuple(Box(1D), Box(3D)) -> Tuple(Box(1D), Box(3D), Action)
            #   -> vision-net -> concat w/ Box(1D) and action -> post_fcnet
            # You can also have SAC use your custom_model as Q-model(s), by simply
            # specifying the `custom_model` sub-key in below dict (just like you would
            # do in the top-level `model` dict.
            "Q_model": {
                "fcnet_hiddens": [4, 4],
                "fcnet_activation": "relu",
                "post_fcnet_hiddens": [],
                "post_fcnet_activation": None,
                "custom_model": None,  # Use this to define custom Q-model(s).
                "custom_model_config": {},
            },
            # Model options for the policy function (see `Q_model` above for details).
            # The difference to `Q_model` above is that no action concat'ing is
            # performed before the post_fcnet stack.
            "policy_model": {
                "fcnet_hiddens": [4, 4],
                "fcnet_activation": "relu",
                "post_fcnet_hiddens": [],
                "post_fcnet_activation": None,
                "custom_model": None,  # Use this to define a custom policy model.
                "custom_model_config": {},
            },
        }

        self.trainer = SACTrainer(config=config)

    def train_loop(self):
        print('Starting loop')
        # Serving and training loop.
        ts = 0
        for _ in range(self.stop_iters):
            print(ts)
            results = self.trainer.train()
            print(results)
            checkpoint = self.trainer.save()
            print("Last checkpoint", checkpoint)
            with open(self.checkpoint_path, "w") as f:
                f.write(checkpoint)
            ts += results["timesteps_total"]


server = TuningServer()
server.train_loop()
```

Client:
```python
import random
from time import sleep

import numpy as np
import ray
from gym.spaces import Box
from ray.rllib.env import PolicyClient

RL_PORT = 9900


try:
    ray.init(address='auto')
except ConnectionError:
    pass

observation_space = Box(0, 10, shape=(10,))
action_space = Box(0, 10, shape=(10,))
state = np.asarray([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

client = PolicyClient(f'http://localhost:{RL_PORT}', inference_mode='local')

n_episodes = 10
episode_length = 100

# start episode
ids = []
for _ in range(n_episodes):
    ids.append(client.start_episode())

for _ in range(episode_length):
    for episode_id in ids:
        sleep(.1)
        action = client.get_action(episode_id, state)
        reward = random.random()
        print('Episode', episode_id, 'reward', reward)
        client.log_returns(episode_id, reward)

for episode_id in ids:
    client.end_episode(episode_id, state)
```

Running them produces the following error on the client side:
```
--- Logging error ---
Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/ray/rllib/env/policy_client.py", line 272, in run
    samples = self.rollout_worker.sample()
  File ".../lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 744, in sample
    batches = [self.input_reader.next()]
  File ".../lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 101, in next
    batches = [self.get_data()]
  File ".../lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 231, in get_data
    item = next(self.rollout_provider)
  File ".../lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 588, in _env_runner
    base_env.poll()
  File ".../lib/python3.8/site-packages/ray/rllib/env/base_env.py", line 261, in poll
    results = self._poll()
  File ".../lib/python3.8/site-packages/ray/rllib/env/base_env.py", line 304, in _poll
    for agent_id in eid_dict.keys():
AttributeError: 'numpy.ndarray' object has no attribute 'keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File ".../lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File ".../lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File ".../lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File ".../lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File ".../lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File ".../lib/python3.8/site-packages/ray/rllib/env/policy_client.py", line 289, in run
    logger.info("Error: inference worker thread died!", e)
Message: 'Error: inference worker thread died!'
Arguments: (AttributeError("'numpy.ndarray' object has no attribute 'keys'"),)
```

The error is thrown here in `ray.rllib.env.base_env.py`:
```python
        if self.multiagent: # <- This should be false, the environment is not multi-agent
            # Ensure a consistent set of keys
            # rely on all_obs having all possible keys for now.
            for eid, eid_dict in all_obs.items():
                for agent_id in eid_dict.keys():
```

**Comment by import-antigravity** [comment] 2021-09-28 20:23
> ok, here are the 2 different log_returns(), just for our information.
> 
> https://github.com/ray-project/ray/blob/master/rllib/env/external_env.py#L145-L148
> 
> https://github.com/ray-project/ray/blob/master/rllib/env/external_multi_agent_env.py#L118-L122

Right, but the environment is not multi-agent so it shouldn't be creating an `ExternalMultiAgentEnv`

**Comment by import-antigravity** [comment] 2021-09-28 20:24
As a workaround for example, instead of `action = client.get_action(episode_id, state)` I would do `action = client.get_action(episode_id, {'agent-1': state})['agent-1']`, which would work except when an episode ends the server reports `NaN` rewards...

**Comment by gjoliver** [comment] 2021-09-29 05:43
Thanks for the script, really helpful.
I think this problem may have already been fixed in head. I can't reproduce it with the script you provided (runs completely fine from master).

This is a recent change that updated how we create MultiAgentEnv in rollout_worker.py:
https://github.com/ray-project/ray/commit/336e79956a1def412049440f4a6586c110576188#diff-380f29c4af45d6f1d4f2b6b51877f4877bb10cbad3e8ddd9cbc048252389dab7

We are going to release 1.7.0 hopefully soon, in case you can't wait for it, maybe you can give our daily release wheel a try?
https://docs.ray.io/en/latest/installation.html

Thanks for the report. Really helpful.

**Comment by import-antigravity** [comment] 2021-09-29 23:20
Okay, it looks like this works on master. However, the server is reporting `nan` for the rewards, similar to #3030. Could this be a similar issue or is it different?

**Comment by gjoliver** [comment] 2021-10-01 14:45
I took a quick look.
you are not getting any episode related stats (episode_reward_max, etc) because the custom environments run on the client side. Server.py has no idea what the environments look like except for a bunch of training frames.
the training batches have good rewards. and the trainer related stats are fine (losses, etc)

This is not related to #3030.
I am closing this issue based on our conversation.
Thanks again.

**Closed by gjoliver** 2021-10-01 14:45 UTC
Labels: bug

**Comment by import-antigravity** [comment] 2021-10-01 17:38
> I took a quick look. you are not getting any episode related stats (episode_reward_max, etc) because the custom environments run on the client side. Server.py has no idea what the environments look like except for a bunch of training frames. the training batches have good rewards. and the trainer related stats are fine (losses, etc)
> 
> This is not related to #3030. I am closing this issue based on our conversation. Thanks again.

okay, thanks! How would I get that information to the server so that it can log rewards, etc?

**Comment by gjoliver** [comment] 2021-10-01 17:52
Not sure if this interface exists between server and client.
Can you just summarize on the client side?
Like running an evaluation job querying the same policy server at a certain interval, etc.
