### ISSUE TITLE
f() takes 0 positional arguments but 6 were given

### ISSUE THREAD

**Issue by vaibhavsingh007** [ray-project/ray#6197] opened 2019-11-19 16:32 UTC
Facing issue when reading a csv using modin.pandas.read_csv().

Version:
CentOS Linux (v 7)
Python 3
Ray vr: 0.7.3
Modin vr: 0.6.2

Stack trace excerpt:

~/.local/lib/python3.6/site-packages/modin/engines/ray/generic/io.py in _read_csv_from_file_ray(cls, filepath, kwargs)
490 # or based on the column(s) that were requested.
491 if index_col is None:
--> 492 row_lengths = ray.get(index_ids)
493 new_index = pandas.RangeIndex(sum(row_lengths))
494 else:

~/.local/lib/python3.6/site-packages/ray/worker.py in get(object_ids)
2245 if isinstance(value, RayError):
2246 last_task_error_raise_time = time.time()
-> 2247 raise value
2248
2249 # Run post processors.

RayTaskError: ray_worker (pid=209, host=vsingh3-v3-jupyterhub-vsing20-1-m7bwl)
TypeError: **f() takes 0 positional arguments but 6 were given**

**Comment by simon-mo** [comment] 2019-11-19 22:14
@devin-petersohn Do you think this is ray related or should it be directed to modin? The only information seems to be ` ray.get(index_ids)` throws exceptions.

**Comment by devin-petersohn** [comment] 2019-11-19 23:09
Thanks for the ping @simon-mo.

I have seen this issue before, but have never been able to reproduce it. We do not define `f` internally to my knowledge, and I have looked into the issue before. 

Link to issue in Modin: https://github.com/modin-project/modin/issues/851

@vaibhavsingh007 we just released within the last couple of days, are you able to update and see if the issue persists?

**Comment by vaibhavsingh007** [comment] 2019-11-27 17:52
Thanks @simon-mo 
Hi @devin-petersohn what is the latest version of ray we are talking about?

**Comment by devin-petersohn** [comment] 2019-11-29 19:42
@vaibhavsingh007 The ray version has not changed for some time due to a regression in functionality in Ray so it is still 0.7.3. The latest Modin version can be installed via
```
pip install -U modin
```

Modin's latest version is 0.6.3

**Comment by vaibhavsingh007** [comment] 2019-12-17 17:40
Hi @devin-petersohn 
Sorry for the delay, was traveling. I tried reinstalling Modin and verified the versions for both it and Ray are same as you mentioned. 
It now throws the following error when executing (modin.pandas.read_csv('data/mnist_train.csv'))

~/.local/lib/python3.6/site-packages/ray/worker.py in get(object_ids)
   2245             if isinstance(value, RayError):
   2246                 last_task_error_raise_time = time.time()
-> 2247                 raise value
   2248 
   2249         # Run post processors.

RayTaskError: ray_worker (pid=229, host=vsingh3-v4-jupyterhub-vsing-1-8b898)
  File "/home/vsing/.local/lib/python3.6/site-packages/modin/engines/ray/task_wrapper.py", line 8, in deploy_ray_func
    return func(**args)
  File "/home/vsing/.local/lib/python3.6/site-packages/modin/backends/pandas/parsers.py", line 69, in parse
    pandas_df = pandas.read_csv(BytesIO(to_read), **kwargs)
TypeError: parser_f() got an unexpected keyword argument 'cache_dates'

This is a partial trace. Let me know if you need the full stack trace.
Looking forward.

**Comment by devin-petersohn** [comment] 2019-12-17 19:59
@vaibhavsingh007 I have seen this before but it is a strange error.

Effectively, the other Python processes being spun up are using a different version of pandas. Does the same issue happen on the [dask](https://github.com/modin-project/modin/blob/master/README.md) backend?

**Comment by robertnishihara** [comment] 2019-12-18 05:58
@vaibhavsingh007 we just released a new version of Ray today. Can you try upgrading Ray to see if the error persists?

**Comment by vaibhavsingh007** [comment] 2019-12-18 15:03
@devin-petersohn I tried installing modin[dask] and removed ray, but seems modin checks for a ray backend. See error below. 

@robertnishihara latest modin seems to check for a specific version of ray unfortunately. :(

```
~/.local/lib/python3.6/site-packages/modin/__init__.py in <module>
     61 
     62 __version__ = "0.6.3"
---> 63 __execution_engine__ = get_execution_engine()
     64 __partition_format__ = get_partition_format()
     65 

~/.local/lib/python3.6/site-packages/modin/__init__.py in get_execution_engine()
     50                 if ray.__version__ != "0.7.3":
     51                     raise ImportError(
---> 52                         "Please `pip install modin[ray] to install compatible Ray version."
     53                     )
     54     return engine

ImportError: Please `pip install modin[ray] to install compatible Ray version.

```

**Comment by devin-petersohn** [comment] 2019-12-19 05:32
Yes, we do this check because there were functionalities we used that were removed/disallowed in Ray. I think they are bringing back some of that functionality so hopefully soon we can be up to date and get some of the performance improvements they've been adding.

**Comment by vaibhavsingh007** [comment] 2019-12-19 19:56
Ok, but how do I force dask as the backend in modin then instead of ray?

**Comment by devin-petersohn** [comment] 2019-12-19 20:28
Try:
```python
import os
os.environ["MODIN_ENGINE"] = "dask"
import modin.pandas as pd
```
That should ignore the Ray import altogether.

**Comment by devin-petersohn** [comment] 2019-12-19 20:41
As a side note, you can replace `"dask"` with `"ray"` to ignore the version check as well.

**Closed** 2020-06-14 04:54 UTC
