### ISSUE TITLE
[tune] iter doesn't match epoch after loading a checkpoint in a Horovod trainable

### ISSUE THREAD

**Issue by henrique** [ray-project/ray#16779] opened 2021-06-30 15:04 UTC
### What is the problem?

ray.tune.integration.horovod  DistributedTrainableCreator doesn't load latest checkpoint.
Although all the checkpoints seem to be saved correctly in the local folder, it doesn't seem to load the very last one.
checkpoint_dir might be None, or the checkpoint returned might be a few epochs behind, so it looks like it might not be saving the state correctly (?)
However, the 'iter' on the Trial table is never reset, so we end up with 'iter' larger than it's supposed to run (epochs).
This can be reproduced both locally on my laptop or on a slurm GPU cluster at CSCS
Perhaps I am just loading or saving it in the wrong way, as it loads a _tmpXXX folder instead of the numbered folders used for saving. But I couldn't find anything better in the docu and previous issues here.
Thanks you so much for having a look at this, and as well for the great work with the framework!

PyTorch 1.9
horovod[pytorch] 0.22.1
ray[tune] 1.4

### Reproduction (REQUIRED)
- [ X ] I have verified my script runs in a clean environment and reproduces the issue.
- [ X ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

```python
import ray
from ray import tune
from ray.tune.suggest.hebo import HEBOSearch
from ray.tune.integration.horovod import DistributedTrainableCreator

import torch
import torch.optim as optim
from torchvision import models
import horovod.torch as hvd

import os
import time
import glob
from attrdict import AttrDict


def save_checkpoint(epoch, model, optimizer):
    with tune.checkpoint_dir(epoch) as checkpoint_dir:
        filepath = os.path.join(checkpoint_dir, 'checkpoint')
        state = {
            'epoch': epoch,
            'model': model.state_dict(),
            'optimizer': optimizer.state_dict(),
        }
        print(f'SAVED {epoch} at {filepath}')
        torch.save(state, filepath)

def load_checkpoint(checkpoint_dir, model, optimizer):
    filepath = os.path.join(checkpoint_dir, 'checkpoint')
    checkpoint = torch.load(filepath)
    model.load_state_dict(checkpoint['model'])
    optimizer.load_state_dict(checkpoint['optimizer'])
    return checkpoint['epoch']


def train_model(config, checkpoint_dir):
    args = AttrDict(**config)

    hvd.init()
    print(hvd.rank(), checkpoint_dir, config)

    # Set up standard ResNet-50 model.
    model = models.resnet50()

    optimizer = optim.SGD(model.parameters(), lr=args.base_lr, momentum=args.momentum, weight_decay=args.wd)

    # resume training from a given checkpoint_dir
    if checkpoint_dir:
        resume_from_epoch = load_checkpoint(checkpoint_dir, model, optimizer)
        print(f'LOADED CHECKPOINT WITH {resume_from_epoch} {checkpoint_dir}')
    else:
        resume_from_epoch = 0

    for epoch in range(resume_from_epoch, args.epochs):
        time.sleep(3)
        val_accuracy = epoch / args.epochs
        save_checkpoint(epoch, model, optimizer)
        tune.report(epoch=epoch, accuracy=val_accuracy)

    return dict(epoch=epoch, accuracy=val_accuracy)


if __name__ == '__main__':
    # ray.init(address='auto',
    #         _node_ip_address=os.environ['RAY_HEAD_NODE'],
    #         _redis_password=os.environ['RAY_REDIS_PASSWORD'])
    ray.init()  # single node

    local_dir = os.getenv('SCRATCH', '/tmp')
    job_name = 'hebo-search'
    analysis = tune.run(
        DistributedTrainableCreator(train_model, num_hosts=1, use_gpu=False, num_slots=1,
                                    num_cpus_per_slot=os.cpu_count()),
        num_samples=6,
        resume=os.path.exists(os.path.join(local_dir, job_name)),
		local_dir=local_dir,
		search_alg=HEBOSearch(metric='accuracy', mode='max'),
        name=job_name,
        metric='accuracy',
        mode='max',
        config={
            'wd': tune.loguniform(1e-5, 1e-3),
            'base_lr': tune.loguniform(1e-5, 0.2),
            'momentum': tune.uniform(0.75, 0.95),
            'epochs': 19,
            # ...
        }
    )

    print(analysis.best_config)
```

I start the cluster with this script below (I had to add some sleeps to make sure the head and the workers are started before the workload, but please let me know if there is a better way of doing this).
```bash
#!/bin/bash -l

# Get the node names
nodes=$(scontrol show hostnames "$SLURM_JOB_NODELIST")
nodes_array=($nodes)

# Export head node and redis password
head_node=${nodes_array[0]}
redis_password=$(uuidgen)
export RAY_HEAD_NODE=$head_node
export RAY_REDIS_PASSWORD=$redis_password

# Set IP and ports
head_node_ip=$(hostname --ip-address)
port=6379
dashboard_port=8265

# Head node, redis and dashboard
echo "Starting Ray cluster HEAD at $head_node"
ray start --head --node-ip-address=$head_node --port=$port \
    --include-dashboard=1 --dashboard-port=$dashboard_port --dashboard-host=$head_node_ip \
    --redis-password=$redis_password --num-gpus=1 --num-cpus=$SLURM_CPUS_PER_TASK --block &
sleep 2

# Worker nodes
for ((i = 1; i < $SLURM_JOB_NUM_NODES; i++)); do
    node=${nodes_array[$i]}
    echo "Starting Ray WORKER $i at $node"
    srun -N1 -n1 -w"$node" ray start --address=$head_node:$port --redis-password=$redis_password \
         --num-gpus=1 --num-cpus=$SLURM_CPUS_PER_TASK --block &
    sleep 0.1
done
```

**Comment by henrique** [comment] 2021-06-30 15:05
@krfricke thank you

**Comment by richardliaw** [comment] 2021-07-02 02:27
@Yard1 do you mind if I assign this item to you? 

cc @amogkam @krfricke

**Comment by Yard1** [comment] 2021-07-02 08:41
@richardliaw sure, go ahead

**Comment by Yard1** [comment] 2021-07-09 14:34
@henrique If I understand correctly, the symptom of the issue is that iter becomes bigger than epochs, yes?

**Comment by henrique** [comment] 2021-07-10 15:10
Thanks for the reply @Yard1 

I've added 'done' like you suggested but now it doesn't seem to go past the first sample. Does 'done' mean that the whole experiment finished?

Anyway, let me try to explain a bit better:
iter becoming bigger than epochs is just a symptom.
I think the issue is that ray or my code is resuming the wrong checkpoint, perhaps the metadata is not being updated after the interruption (Ctril+C, slurm timeout, or some exception)
(The other thing is that my runs don't seem to be very stable and are crashing very often with some random memory issue, but that might another problem altogether, so I can open another ticket in case I find something more concrete.)

Anyway, removing `address='auto'` from `ray.init()` makes it easier to reproduce on a single node/laptop:
I run until epoch 10 and then stop it with Ctrl+C:
```
...
ESC[2mESC[36m(pid=61963)ESC[0m SAVED 9 at /tmp/hebo-search/WrappedHorovodTrainable_306ed912_1_base_lr=1e-05,epochs=19,momentum=0.75,wd=1e-05_2021-07-10_16-43-28/worker_0/checkpoint_000009/checkpoint
ESC[2mESC[36m(pid=61963)ESC[0m epoch 10 iteration
^C
2021-07-10 16:44:09,201	ERROR trial_runner.py:748 -- Trial WrappedHorovodTrainable_306ed912: Error processing event.
BrokenPipeError: [Errno 32] Broken pipe ...
```

Then resuming, it does find iter=9 epoch=8 but then actually opens the checkpoint on epoch 6!
```
Number of trials: 1/1 (1 RUNNING)
+----------------------------------+----------+-------+-----------+------------+-------+--------+------------------+---------+------------+
| Trial name                       | status   | loc   |   base_lr |   momentum |    wd |   iter |   total time (s) |   epoch |   accuracy |
|----------------------------------+----------+-------+-----------+------------+-------+--------+------------------+---------+------------|
| WrappedHorovodTrainable_306ed912 | RUNNING  |       |     1e-05 |       0.75 | 1e-05 |      9 |          31.7887 |       8 |   0.421053 |
+----------------------------------+----------+-------+-----------+------------+-------+--------+------------------+---------+------------+


ESC[2mESC[36m(pid=62455)ESC[0m 0 /tmp/hebo-search/WrappedHorovodTrainable_306ed912_1_base_lr=1e-05,epochs=19,momentum=0.75,wd=1e-05_2021-07-10_16-43-28/worker_0/checkpoint_tmp7ecc77/./ {'wd': 1e-05, 'base_lr': 1e-05, 'momentum': 0.75, 'epochs': 19}
ESC[2mESC[36m(pid=62455)ESC[0m LOADED CHECKPOINT WITH 6 /tmp/hebo-search/WrappedHorovodTrainable_306ed912_1_base_lr=1e-05,epochs=19,momentum=0.75,wd=1e-05_2021-07-10_16-43-28/worker_0/checkpoint_tmp7ecc77/./
ESC[2mESC[36m(pid=62455)ESC[0m epoch 6 iteration
Number of trials: 1/1 (1 RUNNING)
+----------------------------------+----------+---------------------+-----------+------------+-------+--------+------------------+---------+------------+
| Trial name                       | status   | loc                 |   base_lr |   momentum |    wd |   iter |   total time (s) |   epoch |   accuracy |
|----------------------------------+----------+---------------------+-----------+------------+-------+--------+------------------+---------+------------|
| WrappedHorovodTrainable_306ed912 | RUNNING  | 192.168.1.112:62456 |     1e-05 |       0.75 | 1e-05 |      9 |          31.5662 |       6 |   0.315789 |
+----------------------------------+----------+---------------------+-----------+------------+-------+--------+------------------+---------+------------+
...
```

You can see that the save  and load path don't really match:
```
SAVED 9               at /tmp/hebo-search/WrappedHorovodTrainable_306ed912_1_base_lr=1e-05,epochs=19,momentum=0.75,wd=1e-05_2021-07-10_16-43-28/worker_0/checkpoint_000009/checkpoint
LOADED CHECKPOINT WITH 6 /tmp/hebo-search/WrappedHorovodTrainable_306ed912_1_base_lr=1e-05,epochs=19,momentum=0.75,wd=1e-05_2021-07-10_16-43-28/worker_0/checkpoint_tmp7ecc77/./
```

Am I doing something wrong? or is it an issue on tune/HorovodTrainable?
Thanks again for having a look!
Cheers

**Comment by Yard1** [comment] 2021-07-10 15:50
Yes, if `done` is True in `tune.report`, it means the training is over. In my example, it's set to be true on the final iteration. Thanks for more details - I'll look more into it and keep you posted.

**Comment by richardliaw** [comment] 2021-07-11 06:55
Ah @henrique -- could you try moving the `save_checkpoint` call before `tune.report`? 

The checkpoint is registered with the Tune controller when the `report` call is made.

**Comment by Yard1** [comment] 2021-07-11 07:46
Hey @henrique, the cause of the issue is that we checkpoint both iterations and global experiment state separately. The latter does not necessarily happen after every iteration, but instead every X seconds (by default, 10). You can control the frequency of the global checkpointing with the `TUNE_GLOBAL_CHECKPOINT_S` environment variable. Setting it to 0 will ensure the global checkpoint is updated after every iteration (though it may slow down the tuning process). For example: `TUNE_GLOBAL_CHECKPOINT_S=0 python tune.py`

That being said you should also do what Richard pointed out!

**Comment by henrique** [comment] 2021-07-11 21:12
Thanks a lot @Yard1 and @richardliaw 
Your 2 suggestions seem to fix the problem (which was partly caused just by my quick test, sorry).
Note that `iter` doesn't seem to perfectly follow `epoch` (e.g.: it saves `iter=7 epoch=6`, but restarts `iter=8 epoch=6` and so on, incrementing an additional 1 every time it stops and restarts, so it ends iter=epochs+number of restarts)
Making it run from `range(1, epochs+1)` doesn't seem to change that.
However, it does seem to train the right number of epochs and to resume the correct checkpoint now, so I guess we can close this issue.
Thanks again

**Comment by richardliaw** [comment] 2021-07-11 22:50
@henrique that's good to hear! can I ask what you're doing with Tune and how you're liking it?


> Note that iter still doesn't seem to perfectly follow epoch (e.g.: it saves iter=7 epoch=6, but restarts iter=8 epoch=6

hmm, that does seem like a bug. 

@Yard1 I think it's that we don't restore `iter` correctly -- do you mind taking a quick look at that when you have time?

**Comment by Yard1** [comment] 2021-07-11 23:52
Will do @richardliaw

**Comment by henrique** [comment] 2021-07-12 09:50
Thanks guys!

@richardliaw I was evaluating tune for large hyperparam opt on SLURM clusters as, at least with Horovod, it easily allows training several multinode models within a single SLURM allocation -- should that also work with the regular DistTrainers for TF/PT (without Horovod)?
For some context, at CSCS we don't allow users having too many parallel allocations, but they can have a few allocations with up to a few hundreds/thousands nodes each.
The dask support seems also quite interesting, as well as the support for population based training, RL, etc...

The bash script above seems to work alright
(something like https://jobqueue.dask.org/en/latest/generated/dask_jobqueue.SLURMCluster.html would be great :) but that's fine; dask_jobqueue creates a separated slurm allocation, which can be a bit annoying too...).
The need of adding sleeps in the script is a bit unfortunate IMHO, and as I mentioned, I was seeing some other random failures (some looked like out-of-memory issues, but I wasn't able to track them down properly).
I'm a bit busy with other things right now, but hopefully will have a better look at this next month.

Thank you all again for the great work!

**Comment by Yard1** [comment] 2021-11-25 16:56
Hey @henrique, sorry for taking so long. The reason for the iterations and epochs diverging is due to a small mistake in your code - when you load an epoch, it is already finished and therefore you should start from the next epoch (eg. if you save epoch 2, you need to start from epoch 3). In your code, if you save epoch 2, you'd start from epoch 2 again. There isn't any issue related to that in Tune I can see. Feel free to reopen if you have any other questions :)

**Closed by Yard1** 2021-11-25 16:56 UTC
Labels: bug, P1, tune, sgd
