### ISSUE TITLE
[core][regression] stress_test_many_tasks stage_3_time 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#41424] opened 2023-11-28 00:52 UTC
### What happened + What you expected to happen

<img width="481" alt="image" src="https://github.com/ray-project/ray/assets/11676094/e5cfc165-8c38-4481-b141-3bc726cb4f8c">

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

None

**Comment by jjyao** [comment] 2023-11-29 23:20
Duplicate of #41109

**Closed by jjyao** 2023-11-29 23:20 UTC
Labels: bug, release-blocker, P0, core
