### ISSUE TITLE
[Bug][core] Node receives a stale object location update and fails to fetch object

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#23596] opened 2022-03-30 18:23 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

Medium: It contributes to significant difficulty to complete my task but I work arounds and get it resolved.

### What happened + What you expected to happen

When we do large scale data shuffle, occasionally we saw it failed due to ObjectFetchTimedOutError. Based on the initial investigation, it seems that object directory failed to publish location change notifications in some cases.

### Versions / Dependencies

master

### Reproduction script

python scripts/run_release_test.py dataset_random_shuffle_1tb

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by stephanie-wang** [comment] 2022-03-30 19:42
This is partially worked around in #23539 for cases where the node is trying to pull an object that it already has according to the object directory, but the root bug is not fixed yet.

**Comment by stephanie-wang** [comment] 2022-04-01 18:43
@clarkzinzow @rkooo567 any ideas about this? Seems like the root cause should in the object directory and/or pubsub.

**Comment by stephanie-wang** [comment] 2022-05-24 18:23
Closing because I think this is a duplicate of #25084.

**Closed by stephanie-wang** 2022-05-24 18:23 UTC
Labels: bug, P2, triage
