### ISSUE TITLE
[core][raylet] dict_info not set

### ISSUE THREAD

**Issue by ProjitB** [ray-project/ray#36869] opened 2023-06-27 17:33 UTC
### What happened + What you expected to happen

While running jobs (using kuberay) to apply significant load on ray's object store encountered:
```
10168[2m[36m(ScanProvider pid=371, ip=10.17.3.7)[0m 2023-06-24 00:11:14,327	ERROR worker.py:844 -- Worker exits with an exit code None. The worker may have exceeded K8s pod memory limits.
10169[2m[36m(ScanProvider pid=371, ip=10.17.3.7)[0m  Traceback (most recent call last):
10170[2m[36m(ScanProvider pid=371, ip=10.17.3.7)[0m   File "python/ray/_raylet.pyx", line 1197, in ray._raylet.task_execution_handler
10171[2m[36m(ScanProvider pid=371, ip=10.17.3.7)[0m   File "python/ray/_raylet.pyx", line 1100, in ray._raylet.execute_task_with_cancellation_handler
10172[2m[36m(ScanProvider pid=371, ip=10.17.3.7)[0m   File "python/ray/_raylet.pyx", line 759, in ray._raylet.execute_task
10173[2m[36m(ScanProvider pid=371, ip=10.17.3.7)[0m AttributeError: 'dict' object has no attribute 'function_name'
10174[2m[36m(ScanProvider pid=371, ip=10.17.3.7)[0m An unexpected internal error occurred while the worker was executing a task.
10175[2m[36m(ScanProvider pid=371, ip=10.17.3.7)[0m Traceback (most recent call last):10176[2m[36m(ScanProvider pid=371, ip=10.17.3.7)[0m   File "python/ray/_raylet.pyx", line 1197, in ray._raylet.task_execution_handler
10177[2m[36m(ScanProvider pid=371, ip=10.17.3.7)[0m   File "python/ray/_raylet.pyx", line 1100, in ray._raylet.execute_task_with_cancellation_handler
10178[2m[36m(ScanProvider pid=371, ip=10.17.3.7)[0m   File "python/ray/_raylet.pyx", line 759, in ray._raylet.execute_task
10179[2m[36m(ScanProvider pid=371, ip=10.17.3.7)[0m AttributeError: 'dict' object has no attribute 'function_name'
10180[2m[36m(ScanProvider pid=371, ip=10.17.3.7)[0m During handling of the above exception, another exception occurred:
10181[2m[36m(ScanProvider pid=371, ip=10.17.3.7)[0m Traceback (most recent call last):10182[2m[36m(ScanProvider pid=371, ip=10.17.3.7)[0m   File "python/ray/_raylet.pyx", line 1238, in ray._raylet.task_execution_handler
10183[2m[36m(ScanProvider pid=371, ip=10.17.3.7)[0m SystemExit
```

Thread on the ray slack channel implies that there may be a bug here. There might be a case where `dict_info` is not set:
 https://github.com/ray-project/ray/blob/d2fc4823126927b2c54f89ec72fa3d24b442e6a3/python/ray/_raylet.pyx#L759

cc @rkooo567 

### Versions / Dependencies

Ray version 2.4.0
Kuberay (if relevant): 0.5.2

### Reproduction script

Create ~70-90 actors with larger memory usage (load large files into memory).
Multiple tasks pulling memory contents from all these actors.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by xieus** [comment] 2023-06-28 22:15
@ProjitB Could you please provide a repro script or step? Thanks.

**Comment by jjyao** [comment] 2024-03-11 21:36
Someone should read the related code and see how it can possibly happen.

**Comment by anyscalesam** [comment] 2024-04-08 06:11
@fishbone are we keeping this p1 or do we need further repro script from @ProjitB ?

**Comment by rynewang** [comment] 2024-04-26 11:15
Can't repro

**Comment by jjyao** [comment] 2024-04-26 16:33
@ProjitB closing this ticket as we cannot reproduce it on our end. Feel free to re-open it if you have a repro with latest Ray.

**Closed by jjyao** 2024-04-26 16:33 UTC
Labels: bug, needs-repro-script, P0, core, stability, core-kuberay

**Comment by CescMessi** [comment] 2025-12-03 02:08
> [@ProjitB](https://github.com/ProjitB) closing this ticket as we cannot reproduce it on our end. Feel free to re-open it if you have a repro with latest Ray.

Hello @jjyao ,

I have encountered what appears to be the same exception, `AttributeError: 'dict' object has no attribute 'function_name'`, in a different scenario, which suggests the underlying bug might still exist. I am not sure they are caused by same bug.

The issue appears to be related to the interaction between:

1. Using a `JobConfig` with `code_search_path` in ray.init().

2. Defining an actor using the `ray.remote(Class)` syntax (instead of the decorator `@ray.remote`).

3. Compiling the DAG using `dag.experimental_compile()`.

Here is the script:
```python
import ray
from ray.job_config import JobConfig
from ray.dag import InputNode

class Counter:
    def __init__(self):
        self.value = 0

    def increment(self, i) -> int:
        self.value += i
        return self.value

if __name__ == "__main__":
    ray.init(
        job_config=JobConfig(code_search_path=['/usr'])
    )
    counter = ray.remote(Counter)
    counter_actor = counter.remote()

    with InputNode() as dag_inputs:
        dag = counter_actor.increment.options(num_returns=1).bind(
            dag_inputs['i']
        )

    compiled_dag = dag.experimental_compile()
    output = compiled_dag.execute(**{
        'i': 10
    })
    print(ray.get(output, timeout=100))

```

The script runs correctly if I use any one of the following changes:

A. Run `ray.init()` with no arguments (or just `job_config=JobConfig()` without `code_search_path`).

B. Define the actor using the decorator (`@ray.remote`) instead of `ray.remote(Counter)`.

C. Do not compile the DAG (i.e., use `dag.execute(**{'i': 10})` instead of `dag.experimental_compile()` and `compiled_dag.execute(**{'i': 10})`).

This suggests the combination of `JobConfig(code_search_path)` + `ray.remote(Class)` + `experimental_compile()` is the root cause.

Hopefully, this minimal example helps track down the bug!

version:

ray 2.52.1

full output:

```
2025-12-03 10:05:49,353 INFO worker.py:2014 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py:2062: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
(raylet) Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 2164, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 2023, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 1606, in ray._raylet.execute_task
AttributeError: 'dict' object has no attribute 'function_name'
An unexpected internal error occurred while the worker was executing a task.
(raylet) A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. Lease ID: 000000004cd26e809a1114dcf94b3405ac6f67dedaa4287070ce3deaf6e61a48 Worker ID: fa05512d72f78a692bb4b8750b12f85e2549d68389019786edb109b0 Node ID: 1d68bb3a11e5ccd48c98aa5420c2d5867ba0018a0caade778728eb80 Worker IP address: 172.17.0.3 Worker port: 40905 Worker PID: 1683036 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None. Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 2164, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 2023, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 1606, in ray._raylet.execute_task
AttributeError: 'dict' object has no attribute 'function_name'
An unexpected internal error occurred while the worker was executing a task.
Traceback (most recent call last):
  File "/code/model_infer_flow/test_ray/ray_attribute_error.py", line 25, in <module>
    compiled_dag = dag.experimental_compile()
  File "/usr/local/lib/python3.10/dist-packages/ray/dag/dag_node.py", line 354, in experimental_compile
    return build_compiled_dag_from_ray_dag(
  File "/usr/local/lib/python3.10/dist-packages/ray/dag/compiled_dag_node.py", line 3309, in build_compiled_dag_from_ray_dag
    compiled_dag._get_or_compile()
  File "/usr/local/lib/python3.10/dist-packages/ray/dag/compiled_dag_node.py", line 1572, in _get_or_compile
    self._preprocess()
  File "/usr/local/lib/python3.10/dist-packages/ray/dag/compiled_dag_node.py", line 1182, in _preprocess
    self.actor_to_gpu_ids[actor_handle] = CompiledDAG._get_gpu_ids(
  File "/usr/local/lib/python3.10/dist-packages/ray/dag/compiled_dag_node.py", line 1519, in _get_gpu_ids
    accelerator_ids = ray.get(
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 2972, in get
    values, debugger_breakpoint = worker.get_objects(
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 1033, in get_objects
    raise value
ray.exceptions.ActorDiedError: The actor died unexpectedly before finishing this task.
        class_name: Counter
        actor_id: 4175909c6a9c0d5a90d0813201000000
        pid: 1683036
        namespace: 3442e2d0-315b-4aaf-8bc0-f18d394a622e
        ip: 172.17.0.3
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker exits unexpectedly. Worker exits with an exit code None. Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 2164, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 2023, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 1606, in ray._raylet.execute_task
AttributeError: 'dict' object has no attribute 'function_name'
An unexpected internal error occurred while the worker was executing a task.
```
