### ISSUE TITLE
[Bug] [nightly dashboard] dask_on_ray failure doesn't show up in the dashboard

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#21537] opened 2022-01-11 22:18 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

dask_on_ray_test_spilling[ failed this morning](https://buildkite.com/ray-project/periodic-ci/builds/2326#_) but it doesn't show up in the nightly dashboard's failure graph and flakiness graph. @rkooo567 do you know why that's the case?

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Anything else

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment] 2022-01-12 01:56
I found this has been updated to the first graph, but not the second. Maybe there was an issue with Preset that calculates the time? It looks like the second graph only displays the result up to 10th (whereas the first shows up to 11th which has the dask on ray failure)

<img width="1449" alt="Screen Shot 2022-01-11 at 5 55 35 PM" src="https://user-images.githubusercontent.com/18510752/149050127-560d6690-30f1-49a1-b1f7-858cc301483f.png">

**Comment by rkooo567** [comment] 2022-01-17 08:14
Confirmed it just came up to the dashboard late. Closing it.

**Closed by rkooo567** 2022-01-17 08:14 UTC
Labels: bug, P1
