### ISSUE TITLE
If a merge request that fails a certain test is automatically reverted, then it should be made that merge requests cannot complete without that test passing

### ISSUE THREAD

**Issue by ollie-iterators** [ray-project/ray#33458] opened 2023-03-20 13:55 UTC
### What happened + What you expected to happen

I think it would be good if the security requirements for merge requests had it so that certain tests caused a pull request to not be able to be merged without passing, like the Documentation test, and once the lint tests pass, the lint test.

### Versions / Dependencies

Main branch

### Reproduction script

This is about security requirements for the repository

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by krfricke** [comment] 2023-03-23 18:00
There are many reasons tests can fail after a PR is merged even if the test passed in the PR build. For instance, when documentation is updated, links can change on the master page. Cached docker images can be outdated. External (sub)dependencies can have an update that botches part of the CI. (This is actually quite common). Some tests may not have been kicked off by a PR but were affected by the changes. And yes, sometimes human error leads to merging PRs that break master.

In all these cases, having too strict merge requirements on merging PRs (including other PRs that are being developed in parallel) severely reduces developer productivity. If lint is broken on master for any of the above reasons, development of dozens of PRs may be stalled until it's resolved. Some errors take longer to resolve, depending on the cause. 

We do not make any stability guarantees for nightly wheels or the master branch. 

With all this background, enforcing rigid branch protection mechanisms on github may do more harm than good. It is better to rely on good committer practice: Committers should make sure that test failures are unrelated. And on-calls should make sure to track failures on master and resolve them as early as possible after they've been detected. All this is in place and working reasonably well. Of course, we're always open for suggestions on how to improve.

**Comment by ollie-iterators** [comment] 2023-03-24 14:00
Well, I think that at least the linting tests should be a blocker for pull requests because the changes to fix the linter should be easy to fix.

**Comment by ollie-iterators** [comment] 2023-03-24 14:02
> 
> We do not make any stability guarantees for nightly wheels or the master branch.
>

Writing good code should make it easier to improve the code because there is less time wondering if the failure is because of the pull request or because of something different.

**Comment by aslonnie** [comment] 2024-05-04 04:12
premerge tests are blocking now.

**Closed by aslonnie** 2024-05-04 04:12 UTC
Labels: enhancement, P2, Devprod
