### ISSUE TITLE
[Job Submission] ray.exceptions.RuntimeEnvSetupError: Failed to setup runtime environment.

### ISSUE THREAD

**Issue by peterghaddad** [ray-project/ray#27962] opened 2022-08-17 18:43 UTC
### What happened + What you expected to happen

When submitting multiple Tune Experiments through the Job SDK, I receive the following errors after a few iterations.

These errors only occur when submitting multiple Jobs at once (3).

```
to stop the Ray actor:Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py", line 93, in post_stop_cleanup
    ray.get(future, timeout=0)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/worker.py", line 1811, in get
    raise value
ray.exceptions.RuntimeEnvSetupError: Failed to setup runtime environment.
Could not create the actor because its associated runtime env failed to be created.
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 280, in CreateRuntimeEnv
    runtime_env_context = await asyncio.wait_for(
  File "/home/ray/anaconda3/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 150, in _setup_runtime_env
    size_bytes = await manager.create(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/runtime_env/pip.py", line 423, in create
    return await task
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/runtime_env/pip.py", line 414, in _create_for_hash
    await PipProcessor(target_dir, runtime_env, logger)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/runtime_env/pip.py", line 314, in _run
    await self._create_or_get_virtualenv(path, exec_cwd, logger)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/runtime_env/pip.py", line 256, in _create_or_get_virtualenv
    await check_output_cmd(create_venv_cmd, logger=logger, cwd=cwd, env={})
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/runtime_env/utils.py", line 101, in check_output_cmd
    raise SubprocessCalledProcessError(
ray._private.runtime_env.utils.SubprocessCalledProcessError: Run cmd[11] failed with the following details.
Command '['/home/ray/anaconda3/bin/python', '-m', 'virtualenv', '--app-data', '/tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/pip/51b413458a80411d9de06325775fbfad3d9b1009/virtualenv_app_data', '--reset-app-data', '--no-periodic-update', '--system-site-packages', '--no-download', '/tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/pip/51b413458a80411d9de06325775fbfad3d9b1009/virtualenv']' returned non-zero exit status 1.
Last 50 lines of stdout:
    RuntimeError: failed to build image pip because:
    Traceback (most recent call last):
      File "/home/ray/anaconda3/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 57, in _install
        installer.install(creator.interpreter.version_info)
      File "/home/ray/anaconda3/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 39, in install
        self._sync(filename, into)
      File "/home/ray/anaconda3/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/pip_install/copy.py", line 13, in _sync
        copy(src, dst)
      File "/home/ray/anaconda3/lib/python3.9/site-packages/virtualenv/util/path/_sync.py", line 52, in copy
        method(norm(src), norm(dest))
      File "/home/ray/anaconda3/lib/python3.9/site-packages/virtualenv/util/path/_sync.py", line 63, in copytree
        shutil.copy(src_f, dest_f)
      File "/home/ray/anaconda3/lib/python3.9/shutil.py", line 419, in copy
        copymode(src, dst, follow_symlinks=follow_symlinks)
      File "/home/ray/anaconda3/lib/python3.9/shutil.py", line 307, in copymode
        st = stat_func(src)
      File "/home/ray/anaconda3/lib/python3.9/shutil.py", line 229, in _stat
        return fn.stat() if isinstance(fn, os.DirEntry) else os.stat(fn)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/pip/51b413458a80411d9de06325775fbfad3d9b1009/virtualenv_app_data/wheel/3.9/image/1/CopyPipInstall/pip-22.0.4-py3-none-any/pip/_vendor/html5lib/_ihatexml.py'

```

### Versions / Dependencies

KubeRay - Latest
Ray 1.12.1
Python 3.9

CPU worker has 16 CPUs and 28 MI of Memory.

### Reproduction script

Submitting multiple PPO jobs that run for a while. Only 7 Trials per experiment, retry logic is set to 7 failures, and only CPUs and default PPO configuration with the CartPole-v1 Gym environment.

### Issue Severity

High: It blocks me from completing my task.

**Comment by architkulkarni** [comment] 2022-08-17 19:03
@peterghaddad Thanks for reporting this, is it possible for you to see if the issue still persists with version `2.0.0rc1`?  Also, would you be willing to share the logs in `/tmp/ray/session_latest/logs` on the head node? I'd be interested in `dashboard_agent.log` and potentially `gcs_server.out` if there are runtime env logs in that file.

**Comment by peterghaddad** [comment] 2022-08-18 17:38
Hi @architkulkarni.

For gcs_server.out the only run_time related logs are:
```
28085[runtime env manager] URIs reference table:28173[runtime env manager] ID to URIs table:
Repeated...
```

dashboard_agent:
```
2832022-08-17 11:13:11,435	INFO runtime_env_agent.py:258 -- Creating runtime env: {"workingDir":"gcs://_ray_pkg_1abf30326c25114c.zip","envVars":{"TUNE_ORIG_WORKING_DIR":"/tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/working_dir_files/_ray_pkg_1abf30326c25114c"},"extensions":{"_ray_commit":"e4ce38d001dbbe09cd21c497fedd03d692b2be3e"},"pythonRuntimeEnv":{"pipRuntimeEnv":{"config":{"packages":["deprecated","tensorflow"]}}},"uris":{"workingDirUri":"gcs://_ray_pkg_1abf30326c25114c.zip","pipUri":"pip://51b413458a80411d9de06325775fbfad3d9b1009"}}.2842022-08-17 11:13:11,437	INFO runtime_env_agent.py:308 -- Successfully created runtime env: {"workingDir":"gcs://_ray_pkg_1abf30326c25114c.zip","envVars":{"TUNE_ORIG_WORKING_DIR":"/tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/working_dir_files/_ray_pkg_1abf30326c25114c"},"extensions":{"_ray_commit":"e4ce38d001dbbe09cd21c497fedd03d692b2be3e"},"pythonRuntimeEnv":{"pipRuntimeEnv":{"config":{"packages":["deprecated","tensorflow"]}}},"uris":{"workingDirUri":"gcs://_ray_pkg_1abf30326c25114c.zip","pipUri":"pip://51b413458a80411d9de06325775fbfad3d9b1009"}}, the context: {"command_prefix": ["cd /tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/working_dir_files/_ray_pkg_1abf30326c25114c", "source /tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/pip/51b413458a80411d9de06325775fbfad3d9b1009/virtualenv/bin/activate 1>&2"], "env_vars": {"TUNE_ORIG_WORKING_DIR": "/tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/working_dir_files/_ray_pkg_1abf30326c25114c", "PYTHONPATH": ":/tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/working_dir_files/_ray_pkg_1abf30326c25114c"}, "py_executable": "/tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/pip/51b413458a80411d9de06325775fbfad3d9b1009/virtualenv/bin/python", "resources_dir": null, "container": {}}2852022-08-17 11:13:15,112	INFO runtime_env_agent.py:233 -- Runtime env already created successfully. Env: {"workingDir":"gcs://_ray_pkg_1abf30326c25114c.zip","envVars":{"TUNE_ORIG_WORKING_DIR":"/tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/working_dir_files/_ray_pkg_1abf30326c25114c"},"extensions":{"_ray_commit":"e4ce38d001dbbe09cd21c497fedd03d692b2be3e"},"pythonRuntimeEnv":{"pipRuntimeEnv":{"config":{"packages":["deprecated","tensorflow"]}}},"uris":{"workingDirUri":"gcs://_ray_pkg_1abf30326c25114c.zip","pipUri":"pip://51b413458a80411d9de06325775fbfad3d9b1009"}}, context: {"command_prefix": ["cd /tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/working_dir_files/_ray_pkg_1abf30326c25114c", "source /tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/pip/51b413458a80411d9de06325775fbfad3d9b1009/virtualenv/bin/activate 1>&2"], "env_vars": {"TUNE_ORIG_WORKING_DIR": "/tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/working_dir_files/_ray_pkg_1abf30326c25114c", "PYTHONPATH": ":/tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/working_dir_files/_ray_pkg_1abf30326c25114c"}, "py_executable": "/tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/pip/51b413458a80411d9de06325775fbfad3d9b1009/virtualenv/bin/python", "resources_dir": null, "container": {}}2862022-08-17 11:13:15,119	INFO runtime_env_agent.py:233 -- Runtime env already created successfully. Env: {"workingDir":"gcs://_ray_pkg_1abf30326c25114c.zip","envVars":{"TUNE_ORIG_WORKING_DIR":"/tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/working_dir_files/_ray_pkg_1abf30326c25114c"},"extensions":{"_ray_commit":"e4ce38d001dbbe09cd21c497fedd03d692b2be3e"},"pythonRuntimeEnv":{"pipRuntimeEnv":{"config":{"packages":["deprecated","tensorflow"]}}},"uris":{"workingDirUri":"gcs://_ray_pkg_1abf30326c25114c.zip","pipUri":"pip://51b413458a80411d9de06325775fbfad3d9b1009"}}, context: {"command_prefix": ["cd /tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/working_dir_files/_ray_pkg_1abf30326c25114c", "source /tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/pip/51b413458a80411d9de06325775fbfad3d9b1009/virtualenv/bin/activate 1>&2"], "env_vars": {"TUNE_ORIG_WORKING_DIR": "/tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/working_dir_files/_ray_pkg_1abf30326c25114c", "PYTHONPATH": ":/tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/working_dir_files/_ray_pkg_1abf30326c25114c"}, "py_executable": "/tmp/ray/session_2022-08-15_06-53-45_431943_8/runtime_resources/pip/51b413458a80411d9de06325775fbfad3d9b1009/virtualenv/bin/python", "resources_dir": null, "container": {}}2872022-08-17 11:13:15,127
```

I'm not seeing any failures in the logs unfortunately. 

I tried using ray 2.0.0rc, but looks like the JobSubmissionSdk may have changed? Is there updated documentation anywhere?

**Comment by architkulkarni** [comment] 2022-08-18 18:05
Thanks for the details-- after more thinking, I believe the root cause is https://github.com/ray-project/ray/issues/24513, since I've seen similar errors before caused by this (random internal pip files missing).  This is fixed on the nightly wheels (and fixed in 2.0, you can try `2.0.0rc1` today).  Please let me know if you can confirm the issue goes away on a more recent version!

**Comment by rkooo567** [comment] 2022-11-22 01:55
Please reopen if this is still a problem!

**Closed by rkooo567** 2022-11-22 01:55 UTC
Labels: bug, triage

**Comment by alvitawa** [comment] 2024-04-13 11:22
I have this issue.

command:
`ray job submit --working-dir . --entrypoint-memory 1048576000 --runtime-env runtime_env.yaml --entrypoint-num-gpus 1 echo 123`

runtime_env.yaml
`conda: "./environment.yaml"`

environment.yaml
`name: coprompt
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py311h06a4308_0
  - python=3.11.8=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
#      - git+https://github.com/KaiyangZhou/Dassl.pytorch.git
      - absl-py==2.1.0
      - beautifulsoup4==4.12.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - entrypoints==0.3
      - filelock==3.13.4
      - flake8==3.7.9
      - fsspec==2024.3.1
      - ftfy==6.1.1
      - future==1.0.0
      - gdown==5.1.0
      - grpcio==1.62.1
      - idna==3.7
      - isort==4.3.21
      - jinja2==3.1.3
      - joblib==1.4.0
      - littleutils==0.2.2
      - markdown==3.6
      - markupsafe==2.1.5
      - mccabe==0.6.1
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - ogb==1.3.6
      - outdated==0.2.2
      - pandas==2.2.2
      - pillow==10.3.0
      - protobuf==4.25.3
      - pycodestyle==2.5.0
      - pyflakes==2.1.1
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests==2.31.0
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - six==1.16.0
      - soupsieve==2.5
      - sympy==1.12
      - tabulate==0.9.0
      - tb-nightly==2.17.0a20240412
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.4.0
      - torch==2.2.2
      - torchaudio==2.2.2
      - torchvision==0.17.2
      - tqdm==4.66.2
      - triton==2.2.0
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - wcwidth==0.2.13
      - werkzeug==3.0.2
      - wilds==1.2.2
      - yacs==0.1.8
      - yapf==0.29.0
prefix: /home/ook/anaconda3/envs/coprompt
`
