### ISSUE TITLE
[Datasets] Perf regression in DatasetPipeline ingest benchmark

### ISSUE THREAD

**Issue by jianoaix** [ray-project/ray#30490] opened 2022-11-18 23:48 UTC
The following is the result out of running release/nightly_tests/dataset/data_ingest_benchmark.py. There was a significant regression since 11/8.

<img width="999" alt="Screen Shot 2022-11-18 at 2 32 21 PM" src="https://user-images.githubusercontent.com/99709935/202821373-86c47700-bbe7-479e-8d19-1adba187b98d.png">

**Comment by c21** [comment] 2022-11-18 23:51
Given the regression is big and looks like related to PyArrow (we shall figure out if this is a issue with benchmark itself or real code), bump the priority to P0.

**Comment by jianoaix** [comment] 2022-11-18 23:54
Yeah, actually the right-hand side is running a similar benchmark (just bulk not pipeline), so it would be both bench itself or a real regression.

**Comment by xwjiang2010** [comment] 2022-11-19 00:34
curious... why is the regression not showing up in datasets release test? Is this tracked separately by the team and not by the release test infra?

**Comment by jianoaix** [comment] 2022-11-19 01:08
This test is in release test already, but we usually have a much larger margin in release test (e.g. it timeout/fail if it's 5-10x higher of the normal time).

**Comment by clarkzinzow** [comment] 2022-11-28 18:14
![Screenshot 2022-11-28 at 12 13 32 PM](https://user-images.githubusercontent.com/7699919/204350488-75f129ec-c5c8-4fb2-b713-6787566b4b46.png)

Confirmed that the regression was fixed with https://github.com/ray-project/ray/pull/30532

**Closed by clarkzinzow** 2022-11-28 18:14 UTC
Labels: release-blocker, P0, datasets
