### ISSUE TITLE
Forwarding SSH keys for autoscaler

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#1799] opened 2018-03-29 22:28 UTC
Sometimes, we want to clone a private repo and install a python package from it as part of setting up the nodes in the autoscaler. For this it would be convenient to have an option similar to `ssh -A`.

**Comment by ericl** [comment] 2018-03-29 22:30
One workaround is to sync your SSH key as a file mount

**Comment by robertnishihara** [comment] 2018-03-29 22:31
Yeah, you might be able to sync your keys using something like

```
file_mounts: {
    "/home/ubuntu/.ssh/github_key.pem": "/Users/pcmoritz/.ssh/github_key.pem",
}
```

May also need to start an ssh agent and do ssh-add, though I'm not sure.

**Comment by pcmoritz** [comment] 2018-03-29 23:43
As a workaround, modifying `ray/python/ray/autoscaler/updater.py` by adding the `-A` flag in the `ssh_cmd` method, and then this works:

```
GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone ...
```

(note it is important to have StrictHostKeyChecking for the git command)

**Comment by richardliaw** [comment] 2019-10-07 21:48
I'm not sure we're planning to do this. Closing this for now.

**Comment by NasserBenabderrazikSonos** [comment] 2020-04-21 13:54
@richardliaw Can we reopen this ? 
I think this is important since mounting private keys to the instances is not safe ...

**Comment by lenassero** [comment] 2020-04-21 13:58
Hi @richard4912,
Can we reopen this ? I think it is important since transferring private ssh keys is not safe.
Instead, using the ssh agent with the `-A` ssh option is

**Comment by McCrearyD** [comment] 2020-04-23 12:32
> Hi @richard4912,
> Can we reopen this ? I think it is important since transferring private ssh keys to remote servers is not safe.
> Instead, using the ssh agent with the `-A` ssh option is
> 
> **[EDIT]**
> Found a workaround by updating `~/.ssh/config` with:
> 
> ```
> Host *
>     ForwardAgent yes
> ```
> 
> Thanks !

This worked great, however what happens if I'm no longer connected to the head node? Say, I open a tmux session & let it run. Will it fail when horizontally scaling? Assuming that key is required.

**Comment by McCrearyD** [comment] 2020-04-24 02:25
> > Hi @richard4912,
> 
> > Can we reopen this ? I think it is important since transferring private ssh keys to remote servers is not safe.
> 
> > Instead, using the ssh agent with the `-A` ssh option is
> 
> > 
> 
> > **[EDIT]**
> 
> > Found a workaround by updating `~/.ssh/config` with:
> 
> > 
> 
> > ```
> 
> > Host *
> 
> >     ForwardAgent yes
> 
> > ```
> 
> > 
> 
> > Thanks !
> 
> 
> 
> This worked great, however what happens if I'm no longer connected to the head node? Say, I open a tmux session & let it run. Will it fail when horizontally scaling? Assuming that key is required.

I can confirm that it does indeed fail. I’ve resorted to copying the ssh key.

**Closed** 2020-10-01 18:39 UTC
