### ISSUE TITLE
Segfault on osx

### ISSUE THREAD

**Issue by rahulpalamuttam** [ray-project/ray#772] opened 2017-07-25 16:36 UTC
The following simple code leads to a segfault on osx.

import ray
ray.init()
ray.put("k")

I do see the builds passing so it may be a user-specific issue.

**Comment by atumanov** [comment] 2017-07-25 17:04
@rahulpalamuttam , I can't reproduce on my mac osx on the latest master:
```
import ray
ray.init()
ray.put("k")
Out[3]: ObjectID(2f8f9e6914f04734fdb73e1f66c1a5a054cf81e1)
```
Could you post the logs or the stack trace you are seeing?
Thanks.

**Comment by robertnishihara** [comment] 2017-07-25 18:09
Are you building Ray from source? If you built Ray multiple times and also did a `git pull` in between, it's possible that that the version of Arrow changed but that Arrow didn't get recloned.

If that's the problem, it should be addressable by uninstalling Ray, removing the ray directory, recloning it, and reinstalling it.

If that doesn't help, you can get more information by doing `ulimit -c unlimited`, running the thing that crashes, finding the core file under `/cores/`, and inspecting it with `lldb -c /cores/core_file...`. If that works, can you post the backtrace?

**Comment by rahulpalamuttam** [comment] 2017-07-28 15:20
Yes I'm building ray from source.
I did uninstall ray, remove the directory, and reinstalled it but the issue still persists.

Here's the output of backtrace from lldb after inspecting the core dump.
[Core Dump BT](https://gist.github.com/rahulpalamuttam/477d060bef9e28edf908e7c8c9370f4d)
Is there something specific I should be looking for here?

**Comment by robertnishihara** [comment] 2017-07-29 21:02
Thanks for sharing the backtrace! Are there any other interesting features of your platform?

- You're using Python 3.5, right?
- Which Python distribution are you using (e.g., Anaconda, homebrew, or the system Python)?
- What version of OSX?

**Comment by rahulpalamuttam** [comment] 2017-08-01 21:16
* Yes Python 3.5
* I'm using the Anaconda distribution
* macOS Sierra 10.12.5

Note I have no issue with a pip installed ray, just when I build from source.

**Comment by robertnishihara** [comment] 2017-08-02 05:17
Let's see if we can make the backtrace more informative. Can you try two things?

1. Compile in debug mode instead of release mode. You can do this by changing the `Release` -> `Debug` in build.sh here https://github.com/ray-project/ray/blob/master/build.sh#L45.
2. Compile numbuf with `-g` to include more debug symbols. You should be able to add `-g` in the line here https://github.com/ray-project/ray/blob/master/src/numbuf/CMakeLists.txt#L32.

After doing that maybe the backtrace will be more informative.

**Comment by robertnishihara** [comment] 2017-08-02 05:19
Oh actually, one thing that would be even better is to just run the process that's segfaulting in lldb. I think it's the driver that's segfaulting (is that right?), so you should be able to just save the script that fails in a file `test.py` and then do

```
lldb python
> run test.py
```

**Comment by rahulpalamuttam** [comment] 2017-08-25 00:04
Yea it's the driver that is segfaulting. 
The rest of the ray processes are up and running.

Here's the lldb [output](https://gist.github.com/rahulpalamuttam/9eb1a2567810f873f390429018e2dd56).


Here's the barebones [test.py](https://gist.github.com/rahulpalamuttam/6fbcc7732e795b4dc3801677a1e96c02).

**Comment by robertnishihara** [comment] 2017-08-25 18:48
One more thing, any chance you could share the full output of installation? In particular, could you clone a fresh copy of the repository before installing Ray? I'd like to see which versions of flatbuffers are being found by Arrow and by Ray.

If you have a chance, could you also try building the `installchanges` branch from my fork https://github.com/robertnishihara/ray/tree/installchanges?

Can you also share the output of `which flatc` and `flatc --version`?

**Comment by rahulpalamuttam** [comment] 2017-08-31 21:49
Hey, unfortunately, I had to give in my laptop.
I wish I had been more responsive on this issue.

Let me know what you want to do with the issue.

**Comment by robertnishihara** [comment] 2017-09-01 23:42
No worries! I'll close this for now since it'll be pretty hard to make more progress on this. If someone else sees the issue then we should reopen it!

**Closed by robertnishihara** 2017-09-01 23:42 UTC
