### ISSUE TITLE
[SERVE] tracing_startup_hook doesn't work

### ISSUE THREAD

**Issue by stan1astrumu** [ray-project/ray#46357] opened 2024-07-01 16:53 UTC
### What happened + What you expected to happen

enabling tracing_startup_hook causes ingress deployment to fail
`'got an unexpected keyword argument '_ray_trace_ctx''`

related: https://github.com/ray-project/ray/issues/46252

### Versions / Dependencies

`ray == 2.30.0`
`python == 3.9.18`

### Reproduction script

```py
from fastapi import FastAPI
from ray import serve

app = FastAPI()

@serve.deployment
@serve.ingress(app)
class APIIngress:

   @app.post("/test")
   def test(data: List[int]) -> List[int]:
        return data
        
entry = APIIngress.bind()
```

```bash
ray start --head --tracing-startup-hook="ray.util.tracing.setup_local_tmp_tracing:setup_tracing"
```
```bash
serve run my_file:entry
```
make a call to the API

### Issue Severity

High: It blocks me from completing my task.

**Comment by anyscalesam** [comment] 2024-08-26 21:12
p2 because tracing-startup-hook is an experimental feature on Core side...

**Comment by itsparth** [comment] 2024-08-29 12:48
Is there any workaround? To let tracing work in ray core, but disable it for ray serve?

**Comment by jjyao** [comment] 2024-09-04 22:38
Duplicate of https://github.com/ray-project/ray/issues/46252

**Comment by jjyao** [comment] 2024-09-04 22:38
> Is there any workaround? To let tracing work in ray core, but disable it for ray serve?

I'm actually not aware of a way now.

**Closed by jjyao** 2024-09-04 22:38 UTC
Labels: bug, triage, core
