### ISSUE TITLE
[Docs] Instructions for building documentation don't work

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#24200] opened 2022-04-26 01:13 UTC
### What happened + What you expected to happen

I followed the [instructions to build the documentation](https://docs.ray.io/en/master/ray-contribute/development.html#building-the-docs).

I received an error
```
ray/doc on  master via 🐍 v3.8.12 (venv) 
❯ make html
sphinx-build -W -b html -d _build/doctrees   source _build/html
Running Sphinx v4.3.2
Package pickle5 becomes unnecessary in Python 3.8 and above. Its presence may confuse libraries including Ray. Please uninstall the package.
	making output directory... done
myst v0.15.2: MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['dollarmath', 'amsmath', 'deflist', 'html_admonition', 'html_image', 'colon_fence', 'smartquotes', 'replacements'], dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], url_schemes=['http', 'https', 'mailto', 'ftp'], heading_anchors=None, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 348 source files that are out of date
updating environment: [new config] 348 added, 0 changed, 0 removed
reading sources... [ 24%] ray-core/actors/patterns/concurrent-operations-async-areading sources... [ 25%] ray-core/actors/patterns/fault-tolerance-actor-checkporeading sources... [ 25%] ray-core/actors/patterns/overlapping-computation-commuNCCL seems unavailable. Please install Cupy following the guide at: https://docs.cupy.dev/en/stable/install.html.
lz4 not available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
reading sources... [ 66%] train/examples/torch_data_prefetch_benchmark/benchmarkreading sources... [ 81%] tune/examples/includes/hyperopt_conditional_search_spareading sources... [ 87%] tune/examples/includes/xgboost_dynamic_resources_exampreading sources... [100%] workflows/package-ref                                 
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 24%] ray-core/actors/patterns/concurrent-operations-async-acwriting output... [ 25%] ray-core/actors/patterns/fault-tolerance-actor-checkpoiwriting output... [ 25%] ray-core/actors/patterns/overlapping-computation-communwriting output... [ 66%] train/examples/torch_data_prefetch_benchmark/benchmark_writing output... [ 81%] tune/examples/includes/hyperopt_conditional_search_spacwriting output... [ 87%] tune/examples/includes/xgboost_dynamic_resources_examplwriting output... [100%] workflows/package-ref                                  
sitemap.xml was generated for URL / in /private/tmp/example/ray/doc/_build/html/sitemap.xml

Warning, treated as error:
/private/tmp/example/ray/doc/venv/lib/python3.8/site-packages/xgboost_ray/sklearn.py:docstring of xgboost_ray.sklearn.RayXGBClassifier:21:unknown document: /treemethod
make: *** [html] Error 2
```

### Versions / Dependencies

**Python**: 3.8.12
**Ray**: 1.12.0
**OS**: macOS 11.5.2 (20G95)

### Reproduction script

```
git clone https://github.com/ray-project/ray
cd ray/doc
python -m venv venv
source ./venv/bin/activate
pip install -r requirements-doc.txt
make html
```

Note that the error also occurs after building Ray (Python only).

```
cd ..
pip uninstall ray
pip install https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp38-cp38-macosx_10_15_x86_64.whl
python python/ray/setup-dev.py -y
cd doc
make html
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by maxpumperla** [comment] 2022-04-26 08:15
@bveeramani I did the exact same thing (which is also what we run on CI) and can't reproduce your `xgboost_ray` related finding. Is it possible that your `/private/tmp` venv leaks into your build somehow? Can you try to re-install `xgboost_ray`?

I'm closing this for now, as I'm reasonably sure it's a fluke, but please reopen if it persists.

**Comment by maxpumperla** [comment] 2022-04-26 09:13
@bveeramani interesting, I accidentally ran into the same issue on an outdated branch just now. you should be able to fix this by rebasing on latest master.

**Comment by maxpumperla** [comment] 2022-04-26 12:30
@bveeramani turns out to be an xgboost version issue. it fails with xgboost==1.6.0, but is fine with `xgboost==1.5.2` or earlier.

**Closed** 2022-04-26 15:38 UTC
Labels: bug, triage
