### ISSUE TITLE
[Release 1.12.0] regression in ray client related benchmarks

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#23534] opened 2022-03-28 18:25 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

There are few benchmark regression relates to ray client. 
specifically:
`client__get_calls/client__put_gigabytes` regressed, whereas `single_client_put_gigabytes` improved a lot.

Please refer to https://github.com/ray-project/ray/pull/23508 for details.

### Versions / Dependencies

1.12.0rc1

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by scv119** [comment] 2022-03-28 18:26
hey @ckw017 @mwtian can you find the right owner to investigate this?

**Comment by mwtian** [comment] 2022-03-28 19:00
`client__get_calls`: 1584 (before) vs 1105 (now)
`client__put_gigabytes`: 0.13(before) vs 0.045 (now)

These could be related to the chunking changes. Maybe increasing the chunk sizes would help. 

I think they should not block release, since Ray client is intended for interactive use cases. If any user complains, we can look into optimizations later. @ckw017 what do you think?

**Comment by ckw017** [comment] 2022-03-28 23:03
Increasing chunk size for put should help on put_gigabytes. I agree, I think this is fine given client's expected usecase. We've already accepted similar performance losses to add the proxier server in the past.

**Comment by mwtian** [comment] 2022-03-28 23:18
Sounds good. Closing the issue because the regression is not a release blocker.

**Closed by mwtian** 2022-03-28 23:18 UTC
Labels: release-blocker
