### ISSUE TITLE
[Train] Better log message for actor name

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#20914] opened 2021-12-06 18:56 UTC
From @matthewdeng:

In Ray Train, any log/print messages from the worker side show up like this 

```
(BaseWorkerMixin pid=78517) op: "TensorSliceDataset"
(BaseWorkerMixin pid=78517) input: "Placeholder/_0"
(BaseWorkerMixin pid=78517) input: "Placeholder/_1"
(BaseWorkerMixin pid=78517) attr {
(BaseWorkerMixin pid=78517)   key: "Toutput_types"
(BaseWorkerMixin pid=78517)   value {
(BaseWorkerMixin pid=78517)     list {
(BaseWorkerMixin pid=78517)       type: DT_FLOAT
(BaseWorkerMixin pid=78517)       type: DT_INT64
(BaseWorkerMixin pid=78517)     }
(BaseWorkerMixin pid=78517)   }
(BaseWorkerMixin pid=78517) }
```

By default the class name that's executing the training function is used (`BaseWorkerMixin`), but this is confusing since it's an internal concept.

It would be better to show a better name here: either the name of the actual function or something like `TrainingWorker_0`, `TrainingWorker_1`, etc.

**Comment by richardliaw** [comment] 2021-12-06 18:58
You can use `__repr__` to do this I think.

**Comment by matthewdeng** [comment] 2021-12-06 19:00
Duplicate of https://github.com/ray-project/ray/issues/20593

**Closed by matthewdeng** 2021-12-06 19:00 UTC
Labels: train
