### ISSUE TITLE
Core

### ISSUE THREAD

**Issue by pcarinhas** [ray-project/ray#27882] opened 2022-08-15 20:56 UTC
### Description

Add support for full JSON logging output.

When outputting logs to /tmp/ray/session_latest/*, ensure all output is full JSON structured logs. This is important for allowing other processes to parse and react to the data.

### Use case

We want to be able to react and parse logging data in a programatic way. The unstructured nature of the current plain logs doesn't easily lend itself to that purpose. Structured JSON logs would allow us to read, react (alerts), add data (like tags) to logs, and other programatic methods based on the JSON.

**Comment by jjyao** [comment] 2022-08-17 00:33
Duplicate of https://github.com/ray-project/ray/issues/27883

**Closed by jjyao** 2022-08-17 00:33 UTC
Labels: enhancement
