### ISSUE TITLE
Building from source fails on Ubuntu 17.04

### ISSUE THREAD

**Issue by pschafhalter** [ray-project/ray#889] opened 2017-08-29 18:27 UTC
Following the [build instructions](https://ray.readthedocs.io/en/latest/install-on-ubuntu.html) results in `subprocess.CalledProcessError: Command '['../build.sh', '/home/peter/workspace/ray_dev_env/bin/python']' returned non-zero exit status 2` after the command `python setup.py install`.

My Python version is 3.5.3 and I'm running the installation script in a virtual environment using `venv`. The issue occurs even when building outside of a virtual environment.

I've attached the full output. Perhaps this is related to the issues with Arrow.

[output.txt](https://github.com/ray-project/ray/files/1261290/output.txt)

**Comment by robertnishihara** [comment] 2017-08-29 20:52
I think the first error that I see is

```
[ 21%] Building CXX object src/plasma/CMakeFiles/plasma_objlib.dir/eviction_policy.cc.o
cd /home/peter/workspace/ray/src/thirdparty/arrow/cpp/build/src/plasma && /usr/bin/c++    -isystem /home/peter/workspace/ray/src/thirdparty/boost/include -isystem /home/peter/workspace/ray/src/thirdparty/arrow/cpp/build/src/rapidjson_ep/include -isystem /home/peter/workspace/ray/src/thirdparty/flatbuffers/include -isystem /home/peter/workspace/ray/src/thirdparty/arrow/cpp/thirdparty/hadoop/include -I/home/peter/workspace/ray/src/thirdparty/arrow/cpp/src -isystem /usr/include/python3.5m -I/home/peter/workspace/ray/src/thirdparty/arrow/cpp/src/plasma -I/home/peter/workspace/ray/src/thirdparty/arrow/cpp/src/plasma/thirdparty -I/home/peter/workspace/ray/src/thirdparty/arrow/cpp/src/plasma/..  -g -O3 -O3 -DNDEBUG -Wall -std=c++11 -msse3  -fvisibility=hidden -fvisibility-inlines-hidden -D_XOPEN_SOURCE=500 -D_POSIX_C_SOURCE=200809L -fPIC -O3 -DNDEBUG -fPIC   -std=gnu++11 -o CMakeFiles/plasma_objlib.dir/eviction_policy.cc.o -c /home/peter/workspace/ray/src/thirdparty/arrow/cpp/src/plasma/eviction_policy.cc
In file included from /home/peter/workspace/ray/src/thirdparty/boost/include/boost/config.hpp:61:0,
                 from /home/peter/workspace/ray/src/thirdparty/boost/include/boost/cstdint.hpp:36,
                 from /home/peter/workspace/ray/src/thirdparty/boost/include/boost/multiprecision/cpp_int.hpp:11,
                 from /home/peter/workspace/ray/src/thirdparty/arrow/cpp/src/arrow/util/decimal.h:30,
                 from /home/peter/workspace/ray/src/thirdparty/arrow/cpp/src/arrow/python/arrow_to_pandas.cc:42:
/home/peter/workspace/ray/src/thirdparty/boost/include/boost/multiprecision/cpp_int.hpp:193:4: error: right operand of shift expression ‘(1u << 63u)’ is >= than the precision of the left operand [-fpermissive]
    BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));
    ^
```

We'll have to try compiling Arrow on Ubuntu 17 and see if that works.

**Comment by robertnishihara** [comment] 2017-08-30 01:00
It looks like Arrow wasn't compiling on Ubuntu 17 (at the commit of Arrow that we checked out), however, this seems to be fixed on the current Arrow master.

So the solution here is to checkout a more recent Arrow commit.

**Comment by compressed** [comment] 2017-09-01 19:37
I also ran into this on debian-stretch. In addition to pulling the latest arrow from master, I also needed to update the boost library due to the same `fpermissive` error. I noticed the specified boost version (1.60.0) is quite old (2015: https://sourceforge.net/projects/boost/files/boost/). Is there any reason for that? Or could we update it to the newer one? I used the latest boost version (1.65.0) and was able to compile ray. I can submit a PR if you want.

**Comment by robertnishihara** [comment] 2017-09-01 21:54
So, some of this will go away when we use a more recent version of Arrow.

Are you saying that compiling boost 1.60.0 didn't work? We could potentially use a newer version of boost, but the only way in which we use boost is to through Arrow, so I just copied the version of boost that Arrow pulls in.

Hopefully down the road we'll just `pip install pyarrow` and won't have to worry about building Arrow at all.

**Comment by robertnishihara** [comment] 2017-09-05 06:04
This may be fixed by #910.

@pschafhalter, can you try out the latest master and see if you can build Ray on Ubuntu 17?

**Comment by pschafhalter** [comment] 2017-09-05 06:57
The latest master builds and passes all tests on my Ubuntu 17.10 setup.

**Comment by robertnishihara** [comment] 2017-09-05 06:58
Excellent! I'll close this issue then.

However, Ubuntu 17 is not being tested in our CI, and most of us don't use it very regularly, so we'll need to keep an eye out for regressions.

**Closed by robertnishihara** 2017-09-05 06:59 UTC

**Comment by pschafhalter** [comment] 2017-09-05 07:05
Great! I'll let you know if something breaks in the future.
