### ISSUE TITLE
[Ray Dashboard] The format of the GPU profile file downloaded from the dashboard is incorrect 

### ISSUE THREAD

**Issue by yx367563** [ray-project/ray#46240] opened 2024-06-25 01:19 UTC
### What happened + What you expected to happen

Hi All. I ran GPU profiling on Ray using Nsight and the report was also generated. However, I am not able to view it on Nsight Systems on **WSL**. I got the following error:
/dvs/p4/build/sw/devtools/Agora/Rel/QuadD_Main/QuadD/Common/Analysis/Clients/ReportFile.cpp(339): Throw in function void QuadDAnalysis::ReportFile::verifyVersionTag() Dynamic exception type: boost::wrapexceptQuadDCommon::CorruptedDataException std::exception::what: CorruptedDataException [QuadDCommon::tag_message*] = Invalid version prefix: **1NVIDIA** Tegra Profiler Report [QuadDAnalysis::tag_report_file_name*] = “/Users/rajesh.dalai/Downloads/nsight_worker_process_854.nsys-rep”
Can anyone help with this? It seems that there is a problem with the format downloaded from the dashboard. Maybe some escapes are not processed properly. **Because there is a 1 in front of NVIDIA, and the subsequent lines have similar problems**

### Versions / Dependencies

Ray: 2.23.0
Nsight: 2024.4.1.61-244134315967v0

### Reproduction script

Follow the instructions in the Ray official documentation: https://docs.ray.io/en/latest/ray-observability/user-guides/profiling.html#run-nsight-on-ray

### Issue Severity

High: It blocks me from completing my task.

**Comment by rynewang** [comment] 2024-07-11 00:14
Hi, I root caused this issue and I think there should only be one `1` in the file. Can you try to remove it and retry? The proper fix is in #46556 .

**Comment by yx367563** [comment] 2024-07-11 01:23
@rynewang Sorry, just deleting the leading 1 does not solve the problem, the file is still broken. Is it possible that the file is transmitted in several packets, which introduces multiple wrong "1"s?

**Comment by rynewang** [comment] 2024-07-11 18:52
possible. would you mind trying to apply the patch in https://github.com/ray-project/ray/pull/46556 and retry downloading? Or, if you have access to the node that runs nsight, go to `/tmp/ray/sessions_latest/logs/nsight` to get the original profile file.

**Closed** 2024-07-16 00:49 UTC
Labels: bug, P2, core
