### ISSUE TITLE
[Serve] replica actor reconstructed after redeploy

### ISSUE THREAD

**Issue by MissiontoMars** [ray-project/ray#34122] opened 2023-04-06 02:52 UTC
### What happened + What you expected to happen

Replic actor reconstructed after redeploy, is this as expected?

### Versions / Dependencies

ray 2.3

### Reproduction script

conda create --name ray2.3 python=3.7
conda activate ray2.3
pip install -U "ray[default]"
pip install -U "ray[serve]"

```
import ray
from ray import serve

@serve.deployment(num_replicas=1, ray_actor_options={"num_cpus": 0.01})
class MyFirstDeployment:
  def __init__(self):
      print("MyFirstDeployment constructor")

  def __call__(self):
      return "Hello"

  def model_call(self):
      return "HELLO"

  def reconfigure(self, config):
      print(f"reconfigure {config}")

serve.start(http_options={"location":"NoServer"})
MyFirstDeployment.deploy()
handle = MyFirstDeployment.get_handle().model_call
print(ray.get(handle.remote())) # "Hello world!"

MyFirstDeployment._config.max_concurrent_queries = 1
MyFirstDeployment.deploy()
for i in range(1):
    print(ray.get(handle.remote()))

```

logs:
(ray2.3) ➜  grpc python3.7 demo.py
2023-04-06 10:45:50,833 INFO worker.py:1550 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8266
(ServeController pid=422794) INFO 2023-04-06 10:45:52,745 controller 422794 deployment_state.py:1335 - Adding 1 replica to deployment 'MyFirstDeployment'.
(ServeReplica:MyFirstDeployment pid=422878) MyFirstDeployment constructor
HELLO
(ServeController pid=422794) INFO 2023-04-06 10:45:53,722 controller 422794 deployment_state.py:1224 - Stopping 1 replicas of deployment 'MyFirstDeployment' with outdated versions.
(ServeReplica:MyFirstDeployment pid=422878) INFO 2023-04-06 10:45:53,676 MyFirstDeployment MyFirstDeployment#qnVmyR replica.py:523 - HANDLE model_call OK 0.1ms
(ServeController pid=422794) INFO 2023-04-06 10:45:55,881 controller 422794 deployment_state.py:1335 - Adding 1 replica to deployment 'MyFirstDeployment'.
HELLO
(ServeReplica:MyFirstDeployment pid=422971) INFO 2023-04-06 10:45:56,695 MyFirstDeployment MyFirstDeployment#oKNtDm replica.py:523 - HANDLE model_call OK 0.1ms
(ServeReplica:MyFirstDeployment pid=422971) MyFirstDeployment constructor

### Issue Severity

High: It blocks me from completing my task.

**Comment by MissiontoMars** [comment] 2023-04-06 02:52
@sihanwang41

**Comment by zcin** [comment] 2023-06-21 21:59
@MissiontoMars This is expected behavior. Also, I've noticed that you are using 1.x API - note that we may be removing support for 1.x API soon, please see the [migration guide](https://docs.ray.io/en/latest/serve/migration.html).
I would recommend moving to 2.x API since it seems like from your code snippet that you might be looking for this behavior: [Lightweight Config Updates](https://docs.ray.io/en/latest/serve/production-guide/deploy-vm.html#lightweight-config-updates) which is a feature of [Serve config files](https://docs.ray.io/en/latest/serve/production-guide/config.html) on the 2.x API.

**Closed** 2023-07-04 02:54 UTC
Labels: bug, P1, serve
