### ISSUE TITLE
Many processes spawned for a simple ray code

### ISSUE THREAD

**Issue by Arjunsankarlal** [ray-project/ray#10447] opened 2020-08-31 17:17 UTC
For this small piece of code, 

```
import ray

ray.init(num_cpus=1)
print('Enter something')
t = input()
```

Totally 7 processes are spawned. Why is this happening ? Is this intentional ?

<img width="504" alt="Screenshot 2020-08-31 at 10 43 41 PM" src="https://user-images.githubusercontent.com/28828445/91747242-7619f800-ebdb-11ea-8724-2abf97271d1f.png">

And when I don't set the `num_cpus` value, since it automatically sets to the number of cores, the processes spawned goes up from 7 to 14

<img width="561" alt="Screenshot 2020-08-31 at 10 46 37 PM" src="https://user-images.githubusercontent.com/28828445/91747478-e163ca00-ebdb-11ea-90e7-092040ad3437.png">

I am using ray version 0.8.7 in MacOS with Python 3.7.2

**Comment by rkooo567** [comment] 2020-09-01 08:19
I couldn't reproduce it in my Python 3.7.6, MacOS with ray 0.8.7. Could you try 3.7.6 and see if it is still reproduced?

**Comment by Arjunsankarlal** [comment] 2020-09-01 09:37
Just now tried with 3.7.6 and 3.8.5, and with both the versions I am getting the same behaviour. Can you please share how many processes are spawned if you initialize the params with num_cpus=2 and without any configuration ? So that we could get some idea of the problem.

**Comment by Arjunsankarlal** [comment] 2020-09-01 09:37
Just now tried with 3.7.6 and 3.8.5, and with both the versions I am getting the same behaviour. Can you please share how many processes are spawned if you initialize the params with num_cpus=2 and without any configuration ? So that we could get some idea of the problem.

**Comment by rkooo567** [comment] 2020-09-01 09:38
Sure. I will respond to you in the morning tomorrow. When I set num_cpus=1, it spawned only a single process properly fyi

**Comment by wuisawesome** [comment] 2020-09-07 20:24
Btw I checked on this and also count many processes but this is to be expected. 

The python processes that I see 
* reporter
* worker
* log monitor
* monitor
* reaper
* driver

I'm not sure what the 7th one you're seeing is, but in general these are to be expected. These are all to be expected, and you shouldn't need to worry about them (but we can point you to some references if you're curious).

I will close this issue for now, but feel free to reopen it if this is something problematic.

**Closed by wuisawesome** 2020-09-07 20:24 UTC
Labels: bug, triage

**Comment by rkooo567** [comment] 2020-09-07 20:35
Must be the dashboard if it is a head node
