### ISSUE TITLE
[Core] Import thread race condition causes partial import error

### ISSUE THREAD

**Issue by devin-petersohn** [ray-project/ray#25675] opened 2022-06-10 19:49 UTC
### What happened + What you expected to happen

We are getting a circular import error in Modin on the latest Ray release. We have had this issue before and our prior workarounds to this import thread race condition are no longer supported. Context is here: https://github.com/modin-project/modin/issues/4564

### Versions / Dependencies

Ray 1.13

### Reproduction script

This can be reproduced by running the following Modin test:

```
pytest modin/pandas/test/dataframe/test_pickle.py
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by wuisawesome** [comment] 2022-06-13 17:56
cc @iycheng

**Comment by devin-petersohn** [comment] 2022-06-15 18:32
For now, our fix has been to downgrade Ray to `<1.13`. 

It would be great to understand if there's something we should be doing differently on our side to avoid this. Is it possible to avoid using the import thread altogether?

**Comment by rkooo567** [comment] 2022-06-16 14:46
cc @scv119 seems to be pretty bad regression. Let's treat it as P0? 

Maybe it is a good chance to fix the race condition issue as well

**Comment by devin-petersohn** [comment] 2022-06-20 19:08
Hey team, just wanted to check to see if this is on the roadmap or if any decision has been made here. Reminder that Modin users can't use the latest Ray due to this bug, so we'd like to understand what we can do to help.

**Comment by richardliaw** [comment] 2022-06-20 22:32
labeling as P0 for now; @scv119 to triage correctly.

**Comment by scv119** [comment] 2022-06-20 23:46
@iycheng I think you have the most context here?

**Comment by iycheng** [comment] 2022-06-22 21:43
Let's track it in the op which has more context about the issue @devin-petersohn

**Comment by iycheng** [comment] 2022-06-24 03:02
Close this one given that [this](https://github.com/modin-project/modin/issues/4564#issuecomment-1164710743) should be the solution. Modin should update their library to make it work correctly.

**Closed by iycheng** 2022-06-24 03:02 UTC
Labels: bug, P0, core
