### ISSUE TITLE
Suppress : UserWarning: PySoundFile failed

### ISSUE THREAD

**Issue by pn12** [ray-project/ray#10753] opened 2020-09-11 23:43 UTC
Hi , 

I have been using ray for librosa audio files and am unable to supress the below userwarning.

**(pid=132) /opt/conda/lib/python3.7/site-packages/librosa/core/audio.py:162: UserWarning: PySoundFile failed. Trying audioread instead.
(pid=132)   warnings.warn("PySoundFile failed. Trying audioread instead.")**

Can anybody suggest a method to supress warnings in ray?

Thanks

**Comment by sumanthratna** [comment] 2020-09-12 16:24
> Can anybody suggest a method to supress warnings in ray?

the warning came from `warnings.warn` which means you can add the following before calling whatever function raises that warning:
```python
import warnings
warnings.filterwarnings("ignore")
```

note that the following might be safer if you want to maintain warnings in other parts of your code:
```python
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
```

see https://github.com/librosa/librosa/issues/1015

most importantly: make sure you're okay with using `audioread`. 

---

by the way, I'm labeling this as a question and not a bug since you're asking a question. If you think that `PySoundFile` should be used and this behavior is a bug, please open another bug report. I hope this helped! closing; feel free to comment if you still have related questions

**Closed by sumanthratna** 2020-09-12 16:24 UTC
Labels: question, triage

**Comment by iamk0** [comment] 2022-11-19 00:41
Guys, good evening!
I search a solution to my problem and I believ that what happens here it's a same/extension of the question of the colleague above. I run this code:

import librosa, librosa.display
audio = '00b16e02-a418-47da-8341-867981ca3255.wav'
a0, fs = librosa.load(tosse, sr=None)

and revieve this message:
"
LibsndfileError                           Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py](https://localhost:8080/#) in load(path, sr, mono, offset, duration, dtype, res_type)
    148     try:
--> 149         with sf.SoundFile(path) as sf_desc:
    150             sr_native = sf_desc.samplerate

6 frames
LibsndfileError: Error opening '00b16e02-a418-47da-8341-867981ca3255.wav': System error.
"

Do you think If have a actualization or other way for this?

Since that, thanks!

**Comment by iamk0** [comment] 2022-11-19 00:45
Guys, good evening!
I search a solution to my problem and I believe that what happens here it's a same/extension of the question of the colleague above. I run this code:

import librosa, librosa.display
audio = '00b16e02-a418-47da-8341-867981ca3255.wav'
a0, fs = librosa.load(audio, sr=None)

and recieve this message:
"
LibsndfileError                           Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py](https://localhost:8080/#) in load(path, sr, mono, offset, duration, dtype, res_type)
    148     try:
--> 149         with sf.SoundFile(path) as sf_desc:
    150             sr_native = sf_desc.samplerate

LibsndfileError: Error opening '00b16e02-a418-47da-8341-867981ca3255.wav': System error.
"

Do you think If have a actualization or other way for this?

Since that, thanks!
