### ISSUE TITLE
[Bug] problem with running ray with WSL in powershell

### ISSUE THREAD

**Issue by irani74** [ray-project/ray#22859] opened 2022-03-07 12:27 UTC
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Hi
I have an amazing problem with running the ray in WSL
in powershell and cmd:
when input: (1)
wsl
(then:) 
ray start --head
evrything is OK and 12 process was running

but when input: (2)
wsl ray start --head

just 2 process of ray was run

I need to autorun the ray with bash scripts in WSL. so I create bash file (.sh) and run "bash test.sh"
when I run scripts (1) , second script was not running (just run "wsl" and not running next script)
and when I run script (2) , ray start script run successfully (and any other scripts). but just 2 process of ray was run (and ray was not work)

### Versions / Dependencies

ray: 1.10
Python: 3.8
WSL2 in Windows 10

### Reproduction script

I saved linux bash scripts in 2 test file:
1.sh :
wsl
ray start --head

2.sh:
wsl ray start --head

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by irani74** [comment] 2022-03-07 20:30
> Please update the title!

Thanks!

**Comment by mattip** [comment] 2022-03-28 08:01
I am missing something. If I create a file `wsl.sh` with either the contents of (1) or (2) and try to run it from cmd.exe or from powershell, the script does not run. If I create a file `wsl.bat`, then the single-line in (2) runs, but the two line form in (1) enters wsl and presents a bash prompt, hanging after executing the first line. How are you running the scripts?

**Comment by mattip** [comment] 2022-05-03 14:31
@irani74 is this still happening? Could you refine the reproducer so I can test it out?

**Comment by mattip** [comment] 2022-07-04 07:03
This issue cannot be reproduced and the OP has not provided more information. I will close it, please reopen or open a new issue if the issue is seen again.

**Closed by mattip** 2022-07-04 07:03 UTC
Labels: bug, needs-repro-script, triage, QS
