### ISSUE TITLE
[ray]ERROR: ray-0.9.0.dev0-cp36-cp36m-manylinux1_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by forhonourlx** [ray-project/ray#9518] opened 2020-07-16 12:42 UTC
Hi Ray Team,
I am trying to pip install  https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.9.0.dev0-cp36-cp36m-manylinux1_x86_64.whl
Got `ERROR: ray-0.9.0.dev0-cp36-cp36m-manylinux1_x86_64.whl is not a supported wheel on this platform.`

My env is:
Python 3.6.10 |Anaconda, Inc.| (default, Mar 23 2020, 23:13:11) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

Anything to fix this? Thanks in advance.

**Comment by richardliaw** [comment] 2020-07-16 20:38
Can you also post `pip --version`?

**Comment by forhonourlx** [comment] 2020-07-16 23:42
Hi @richardliaw ，
pip 20.1.1 from /home/simon/anaconda3/lib/python3.6/site-packages/pip (python 3.6)

**Comment by forhonourlx** [comment] 2020-07-16 23:46
And some older ray-0.9.0.dev0-cp36-cp36m-manylinux1_x86_64.whl could still be installed.

**Comment by rkooo567** [comment] 2020-07-17 21:30
What linux distro are you using?

**Comment by rkooo567** [comment] 2020-07-17 21:30
cc @mehrdadn

**Comment by mehrdadn** [comment] 2020-07-17 21:51
@forhonourlx Could you please let us know the following?

- Your Linux distro + version

- The latest wheel that works

You can try wheels for a particular commit by changing the commit hash here:

https://ray-wheels.s3-us-west-2.amazonaws.com/master/ac39e23145336fa7d450dd170e3e12ffc3d72d83/ray-0.9.0.dev0-cp36-cp36m-manylinux1_x86_64.whl

In particular these commits would be great to check:
```
22a5c3d3eee2ad314b4fd241a7e4d863888029cf
26fcda50e759a90fcf575c0ce159d2ad199f83c6
7e1326c0f6e0d198d126f2e555aff94f4536b1a2
```

Thanks!

**Comment by forhonourlx** [comment] 2020-07-18 01:35
Hi @mehrdadn @rkooo567 @richardliaw 
`$ cat /proc/version
Linux version 5.3.0-62-generic (buildd@lcy01-amd64-004) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020
`
Sorry, I found it was because the .whl file is renamed with postfix due to sys name conflict.
If renaming it to `ray-0.9.0.dev0-cp36-cp36m-manylinux1_x86_64.whl`, all .whl could be installed successfully.
Thank you.

**Comment by mehrdadn** [comment] 2020-07-18 01:38
Oh I see, sounds like the issue is resolved then? I'll close the issue in that case, let us know if it comes up again. Thanks!

**Closed by mehrdadn** 2020-07-18 01:38 UTC
Labels: P3, bug

**Comment by TheAlpha1550** [comment] 2021-03-24 16:03
Hello. I am having the same issue, except with 

ray-0.9.0.dev0-cp38-cp38m-manylinux1_x86_64.whl

instead of cp36. If anyone can help me resolve this issue, i will greatly appreciate it. Thank you.
