### ISSUE TITLE
[core] release test failure: long_running_node_failures

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#34334] opened 2023-04-12 20:11 UTC
### What happened + What you expected to happen

Potential release blocker

```
(pid=gcs_server) [2023-04-12 10:20:09,130 E 873 895] (gcs_server) ray_syncer-inl.h:305: Failed to read the message from: 976bc7dded84cf30ed35b8051b9d9e6df0df4eceea1f84d81caae551
Iteration 73:
  - Iteration time: 9.377341032028198.
  - Absolute time: 1681320009.403061.
  - Total elapsed time: 714.510059595108.
2023-04-12 10:20:09,403 INFO test_utils.py:1822 -- Wrote results to /tmp/release_test_out.json
2023-04-12 10:20:09,404 INFO test_utils.py:1823 -- {"iteration": 73, "iteration_time": 9.377341032028198, "absolute_time": 1681320009.403061, "elapsed_time": 714.510059595108, "last_update": 1681320009.4031348}
2023-04-12 10:20:10,996 WARNING worker.py:1986 -- Raylet is terminated: ip=10.0.35.88, id=976bc7dded84cf30ed35b8051b9d9e6df0df4eceea1f84d81caae551. Termination is unexpected. Possible reasons include: (1) SIGKILL by the user or system OOM killer, (2) Invalid memory access from Raylet causing SIGSEGV or SIGBUS, (3) Other termination signals. Last 20 lines of the Raylet logs:
    [state-dump] 
    [state-dump] 
    [2023-04-12 10:19:14,192 I 946 946] (raylet) accessor.cc:611: Received notification for node id = 34d177b9c18b69d09baa36f2d8e2fb776ef073b9ea3e10c901e8118d, IsAlive = 0
    [2023-04-12 10:19:14,328 I 946 946] (raylet) accessor.cc:611: Received notification for node id = e1fea953514660ea229f4e9651b8b5c7ac68e9edeb7e4a246e2b7da1, IsAlive = 1
    [2023-04-12 10:19:14,331 I 946 946] (raylet) node_manager.cc:1201: [UpdateResourceUsage]: received resource usage from unknown node id e1fea953514660ea229f4e9651b8b5c7ac68e9edeb7e4a246e2b7da1
    [2023-04-12 10:19:23,363 I 946 946] (raylet) accessor.cc:611: Received notification for node id = e1fea953514660ea229f4e9651b8b5c7ac68e9edeb7e4a246e2b7da1, IsAlive = 0
    [2023-04-12 10:19:23,453 I 946 946] (raylet) accessor.cc:611: Received notification for node id = 893e1dac1ae5b33333d718069948ba86390a649015cb3eb104b9a18a, IsAlive = 1
    [2023-04-12 10:19:31,680 I 946 946] (raylet) accessor.cc:611: Received notification for node id = 893e1dac1ae5b33333d718069948ba86390a649015cb3eb104b9a18a, IsAlive = 0
    [2023-04-12 10:19:31,766 I 946 946] (raylet) accessor.cc:611: Received notification for node id = f995f7a57c3019b1dff8658da4ce32f77d004cc71a4b14e9d969e10a, IsAlive = 1
    [2023-04-12 10:19:31,768 I 946 946] (raylet) node_manager.cc:1201: [UpdateResourceUsage]: received resource usage from unknown node id f995f7a57c3019b1dff8658da4ce32f77d004cc71a4b14e9d969e10a
    [2023-04-12 10:19:40,853 I 946 946] (raylet) accessor.cc:611: Received notification for node id = f995f7a57c3019b1dff8658da4ce32f77d004cc71a4b14e9d969e10a, IsAlive = 0
    [2023-04-12 10:19:40,956 I 946 946] (raylet) accessor.cc:611: Received notification for node id = a4669f32f6d970c0418c6f6acb0f83d0287455aac61f96bc9e29ed54, IsAlive = 1
    [2023-04-12 10:19:51,238 I 946 946] (raylet) accessor.cc:611: Received notification for node id = a4669f32f6d970c0418c6f6acb0f83d0287455aac61f96bc9e29ed54, IsAlive = 0
    [2023-04-12 10:19:51,321 I 946 946] (raylet) accessor.cc:611: Received notification for node id = c1dc9f9fc1e2bd1afe82cee463fb9765733cbe1d4a2938930172c421, IsAlive = 1
    [2023-04-12 10:19:51,325 I 946 946] (raylet) node_manager.cc:1201: [UpdateResourceUsage]: received resource usage from unknown node id c1dc9f9fc1e2bd1afe82cee463fb9765733cbe1d4a2938930172c421
    [2023-04-12 10:19:59,816 I 946 946] (raylet) accessor.cc:611: Received notification for node id = c1dc9f9fc1e2bd1afe82cee463fb9765733cbe1d4a2938930172c421, IsAlive = 0
    [2023-04-12 10:19:59,937 I 946 946] (raylet) accessor.cc:611: Received notification for node id = 976bc7dded84cf30ed35b8051b9d9e6df0df4eceea1f84d81caae551, IsAlive = 1
    [2023-04-12 10:20:09,119 I 946 946] (raylet) accessor.cc:611: Received notification for node id = 976bc7dded84cf30ed35b8051b9d9e6df0df4eceea1f84d81caae551, IsAlive = 0
    [2023-04-12 10:20:09,291 I 946 946] (raylet) accessor.cc:611: Received notification for node id = 66b34ea5c3107ed41796e674863a252aaa5da72f4d0b5a5ba1c7b370, IsAlive = 1
    [2023-04-12 10:20:09,296 I 946 946] (raylet) node_manager.cc:1201: [UpdateResourceUsage]: received resource usage from unknown node id 66b34ea5c3107ed41796e674863a252aaa5da72f4d0b5a5ba1c7b370

(pid=gcs_server) [2023-04-12 10:20:19,870 E 873 895] (gcs_server) ray_syncer-inl.h:305: Failed to read the message from: 66b34ea5c3107ed41796e674863a252aaa5da72f4d0b5a5ba1c7b370
Iteration 74:
  - Iteration time: 10.627615213394165.
  - Absolute time: 1681320020.0306761.
  - Total elapsed time: 725.1376748085022.
2023-04-12 10:20:20,031 INFO test_utils.py:1822 -- Wrote results to /tmp/release_test_out.json
2023-04-12 10:20:20,031 INFO test_utils.py:1823 -- {"iteration": 74, "iteration_time": 10.627615213394165, "absolute_time": 1681320020.0306761, "elapsed_time": 725.1376748085022, "last_update": 1681320020.0307224}
2023-04-12 10:20:21,755 WARNING worker.py:1986 -- Raylet is terminated: ip=10.0.35.88, id=66b34ea5c3107ed41796e674863a252aaa5da72f4d0b5a5ba1c7b370. Termination is unexpected. Possible reasons include: (1) SIGKILL by the user or system OOM killer, (2) Invalid memory access from Raylet causing SIGSEGV or SIGBUS, (3) Other termination signals. Last 20 lines of the Raylet logs:
```

### Versions / Dependencies

2.4.0

### Reproduction script

https://buildkite.com/ray-project/release-tests-branch/builds/1550#01877661-a560-4218-b0f4-1384dd33c71f

### Issue Severity

None

**Comment by iycheng** [comment] 2023-04-12 21:33
Add release-blocker label first. We'll remove once we decide it's not a release blocker.

**Comment by clarng** [comment] 2023-04-12 21:35
cc @zhe-thoughts

**Comment by clarng** [comment] 2023-04-12 21:35
looks like one of the weekly tests regressed, possibly due to one of the patches

**Comment by zhe-thoughts** [comment] 2023-04-12 21:52
OK let's stick with the plan of speculatively deploying the current wheel to the product. @iycheng please tag / DM me when we have a conclusion here. cc @scv119 as well

**Comment by iycheng** [comment] 2023-04-13 00:36
I think it's because the gcs failed due to some reason, but I can't find what's the root cause

```
[2023-04-12 11:23:25,823 E 946 946] (raylet) gcs_rpc_client.h:533: Failed to connect to GCS within 60 seconds. GCS may have been killed. It's either GCS is terminated by `ray stop` or is killed unexpectedly. If it is killed unexpectedly, see the log file gcs_server.out. https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure. The program will terminate.
```

Trying to reproduce this.

**Comment by zhe-thoughts** [comment] 2023-04-14 06:06
Let's still investigate the root cause. But since the [new run](https://buildkite.com/ray-project/release-tests-branch/builds/1550#018778be-c8aa-4bda-a8e9-6aa0d0b97917) passed, I'm making a call that let's not treat this as a blocker for 2.4.0

**Comment by rickyyx** [comment] 2023-04-17 23:16
I took a look at one of the tests (failure not related) : https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_s2wtlgq2rf9h18lsjwag1fgjn2

It seems that the cluster is running into MAX cpu, could that be a reason why GCS being not responsive? 
<img width="817" alt="image" src="https://user-images.githubusercontent.com/11676094/232630157-c7557720-b3e0-45bf-b1bd-86a7fbc77316.png">

**Comment by woosangbum** [comment] 2023-04-20 17:03
I also received the following error while using rllib's policy server and client.

`[2023-04-12 11:23:25,823 E 946 946] (raylet) gcs_rpc_client.h:533: Failed to connect to GCS within 60 seconds. GCS may have been killed. It's either GCS is terminated by `ray stop` or is killed unexpectedly. If it is killed unexpectedly, see the log file gcs_server.out. https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure. The program will terminate.`

I have three clients and one server running on one machine, each client running in its own docker container. Also, ROS is running inside each client.

I am using less than 40% RAM.
In my opinion, it is expected that the communication load such as ROS on each client may have caused the above error, but the exact cause has not been identified.

The above error doesn't happen every time, but only occasionally

Thanks.

**Comment by woosangbum** [comment] 2023-04-21 11:56
> Hey @woosangbum - would you mind sharing your last lines of the gcs_server.err /out?

Hello. I'm sorry for the late response.

```
[2023-04-21 10:52:31,397 I 837928 837928] (gcs_server) gcs_server.cc:192: GcsNodeManager: 
- RegisterNode request count: 1
- DrainNode request count: 0
- GetAllNodeInfo request count: 14001
- GetInternalConfig request count: 1

GcsActorManager: 
- RegisterActor request count: 3
- CreateActor request count: 3
- GetActorInfo request count: 3
- GetNamedActorInfo request count: 0
- GetAllActorInfo request count: 1
- KillActor request count: 0
- ListNamedActors request count: 0
- Registered actors count: 3
- Destroyed actors count: 0
- Named actors count: 0
- Unresolved actors count: 0
- Pending actors count: 0
- Created actors count: 1
- owners_: 1
- actor_to_register_callbacks_: 0
- actor_to_create_callbacks_: 0
- sorted_destroyed_actor_list_: 0

GcsResourceManager: 
- GetResources request count: 0
- GetAllAvailableResources request count0
- ReportResourceUsage request count: 0
- GetAllResourceUsage request count: 6978

GcsPlacementGroupManager: 
- CreatePlacementGroup request count: 0
- RemovePlacementGroup request count: 0
- GetPlacementGroup request count: 0
- GetAllPlacementGroup request count: 0
- WaitPlacementGroupUntilReady request count: 0
- GetNamedPlacementGroup request count: 0
- Scheduling pending placement group count: 0
- Registered placement groups count: 0
- Named placement group count: 0
- Pending placement groups count: 0
- Infeasible placement groups count: 0

GcsPublisher {}

[runtime env manager] ID to URIs table:
[runtime env manager] URIs reference table:

GcsTaskManager: 
-Total num task events reported: 195324
-Total num status task events dropped: 0
-Total num profile events dropped: 0
-Total num bytes of task event stored: 12.0895MiB
-Current num of task events stored: 19534
-Total num of actor creation tasks: 3
-Total num of actor tasks: 19530
-Total num of normal tasks: 0
-Total num of driver tasks: 1

GrpcBasedResourceBroadcaster:
- Tracked nodes: 1
[2023-04-21 10:52:31,397 I 837928 837928] (gcs_server) gcs_server.cc:757: Event stats:


Global stats: 1719221 total (7 active)
Queueing time: mean = 9.623 us, max = 29.300 ms, min = -0.000 s, total = 16.543 s
Execution time:  mean = 14.108 us, total = 24.255 s
Event stats:
	RaySyncer.deadline_timer.report_resource_report - 349135 total (1 active), CPU time: mean = 9.124 us, total = 3.185 s
	ResourceUpdate - 344816 total (0 active), CPU time: mean = 11.816 us, total = 4.074 s
	NodeManagerService.grpc_client.RequestResourceReport - 344816 total (0 active), CPU time: mean = 23.414 us, total = 8.074 s
	NodeManagerService.grpc_client.UpdateResourceUsage - 344814 total (0 active), CPU time: mean = 10.840 us, total = 3.738 s
	GcsInMemoryStore.Put - 55979 total (0 active), CPU time: mean = 2.875 us, total = 160.915 ms
	InternalKVGcsService.grpc_server.InternalKVPut - 55925 total (0 active), CPU time: mean = 4.648 us, total = 259.956 ms
	InternalKVGcsService.grpc_client.InternalKVPut - 41904 total (0 active), CPU time: mean = 3.108 us, total = 130.257 ms
	RayletLoadPulled - 34918 total (1 active), CPU time: mean = 64.881 us, total = 2.266 s
	NodeManagerService.grpc_client.GetResourceLoad - 34916 total (0 active), CPU time: mean = 8.773 us, total = 306.303 ms
	GcsInMemoryStore.Get - 34126 total (0 active), CPU time: mean = 3.407 us, total = 116.258 ms
	InternalKVGcsService.grpc_server.InternalKVGet - 34122 total (0 active), CPU time: mean = 14.803 us, total = 505.100 ms
	NodeInfoGcsService.grpc_server.GetAllNodeInfo - 14001 total (0 active), CPU time: mean = 16.399 us, total = 229.606 ms
	HealthCheck - 11638 total (0 active), CPU time: mean = 1.797 us, total = 20.909 ms
	NodeInfoGcsService.grpc_server.CheckAlive - 6981 total (0 active), CPU time: mean = 3.488 us, total = 24.353 ms
	NodeResourceInfoGcsService.grpc_server.GetAllResourceUsage - 6978 total (0 active), CPU time: mean = 22.425 us, total = 156.483 ms
	GCSServer.deadline_timer.debug_state_dump - 3492 total (1 active), CPU time: mean = 251.929 us, total = 879.736 ms
	GCSServer.deadline_timer.debug_state_event_stats_print - 582 total (1 active, 1 running), CPU time: mean = 166.624 us, total = 96.975 ms
	WorkerInfoGcsService.grpc_server.AddWorkerInfo - 36 total (0 active), CPU time: mean = 11.227 us, total = 404.187 us
	GcsInMemoryStore.GetAll - 8 total (0 active), CPU time: mean = 3.668 ms, total = 29.344 ms
	PeriodicalRunner.RunFnPeriodically - 4 total (0 active), CPU time: mean = 36.768 us, total = 147.071 us
	WorkerInfoGcsService.grpc_server.ReportWorkerFailure - 3 total (0 active), CPU time: mean = 10.060 us, total = 30.179 us
	CoreWorkerService.grpc_client.PushTask - 3 total (0 active), CPU time: mean = 112.184 us, total = 336.551 us
	ActorInfoGcsService.grpc_server.GetActorInfo - 3 total (0 active), CPU time: mean = 3.751 us, total = 11.254 us
	ActorInfoGcsService.grpc_server.RegisterActor - 3 total (0 active), CPU time: mean = 191.993 us, total = 575.978 us
	NodeManagerService.grpc_client.RequestWorkerLease - 3 total (0 active), CPU time: mean = 105.875 us, total = 317.626 us
	CoreWorkerService.grpc_client.WaitForActorOutOfScope - 3 total (3 active), CPU time: mean = 0.000 s, total = 0.000 s
	ActorInfoGcsService.grpc_server.CreateActor - 3 total (0 active), CPU time: mean = 116.931 us, total = 350.793 us
	GcsInMemoryStore.Delete - 1 total (0 active), CPU time: mean = 2.441 us, total = 2.441 us
	JobInfoGcsService.grpc_server.GetAllJobInfo - 1 total (0 active), CPU time: mean = 18.743 us, total = 18.743 us
	JobInfoGcsService.grpc_server.AddJob - 1 total (0 active), CPU time: mean = 44.089 us, total = 44.089 us
	NodeInfoGcsService.grpc_server.RegisterNode - 1 total (0 active), CPU time: mean = 60.515 us, total = 60.515 us
	InternalKVGcsService.grpc_server.InternalKVDel - 1 total (0 active), CPU time: mean = 9.016 us, total = 9.016 us
	JobInfoGcsService.grpc_server.GetNextJobID - 1 total (0 active), CPU time: mean = 2.072 us, total = 2.072 us
	ActorInfoGcsService.grpc_server.GetAllActorInfo - 1 total (0 active), CPU time: mean = 3.654 us, total = 3.654 us
	NodeInfoGcsService.grpc_server.GetInternalConfig - 1 total (0 active), CPU time: mean = 11.839 us, total = 11.839 us
	GcsHealthCheckManager::AddNode - 1 total (0 active), CPU time: mean = 5.589 us, total = 5.589 us


[2023-04-21 10:52:31,397 I 837928 837928] (gcs_server) gcs_server.cc:758: GcsTaskManager Event stats:


Global stats: 21095 total (0 active)
Queueing time: mean = 10.952 us, max = 2.574 ms, min = 774.000 ns, total = 231.043 ms
Execution time:  mean = 508.498 us, total = 10.727 s
Event stats:
	TaskInfoGcsService.grpc_server.AddTaskEventData - 21095 total (0 active), CPU time: mean = 508.498 us, total = 10.727 s


[2023-04-21 10:52:49,737 I 837928 837928] (gcs_server) gcs_job_manager.cc:87: Finished marking job state, job id = 01000000
[2023-04-21 10:52:49,737 W 837928 837928] (gcs_server) gcs_server.cc:416: The GCS actor metadata garbage collector timer failed to fire. This could old actor metadata not being properly cleaned up. For more information, check logs/gcs_server.err and logs/gcs_server.out
[2023-04-21 10:52:49,738 I 837928 837928] (gcs_server) gcs_actor_manager.cc:744: Worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff failed, destroying actor child, job id = 01000000
[2023-04-21 10:52:49,738 I 837928 837928] (gcs_server) gcs_actor_manager.cc:766: Destroying actor, actor id = 7561373c8402b0b776f652f201000000, job id = 01000000
[2023-04-21 10:52:49,739 I 837928 837928] (gcs_server) gcs_actor_manager.cc:744: Worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff failed, destroying actor child, job id = 01000000
[2023-04-21 10:52:49,739 I 837928 837928] (gcs_server) gcs_actor_manager.cc:766: Destroying actor, actor id = a9b77b4e371bb22fd764128401000000, job id = 01000000
[2023-04-21 10:52:49,739 I 837928 837928] (gcs_server) gcs_actor_manager.cc:744: Worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff failed, destroying actor child, job id = 01000000
[2023-04-21 10:52:49,739 I 837928 837928] (gcs_server) gcs_actor_manager.cc:766: Destroying actor, actor id = 8d6c8cbc6a3d625ff6d1140f01000000, job id = 01000000
```

**Comment by rickyyx** [comment] 2023-04-21 17:43
And is there anything from the .err log for gcs?

**Comment by woosangbum** [comment] 2023-04-21 17:56
> And is there anything from the .err log for gcs?

Nothing was displayed in .err.

**Comment by rickyyx** [comment] 2023-04-21 18:08
And was there anything in the raylet.err? Actually - if you could zip all the log files and upload here, it will be better.

**Comment by fishbone** [comment] 2024-03-26 01:43
Close this one given that it hasn't failed for a quarter.

**Closed by fishbone** 2024-03-26 01:43 UTC
Labels: bug, core, P1.5, stability
