### ISSUE TITLE
[autoscaler/core][logging] Make autoscaler event error color red

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#26992] opened 2022-07-26 00:24 UTC
### What happened + What you expected to happen

The current default autoscaler error message color is painfully difficult to read on the default background.

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/3980609/180896595-f63c60ea-d867-477b-a76a-c972e3897da3.png">

### Versions / Dependencies

Master

### Reproduction script

Launch a 4 CPU head node with available 8 CPU worker node, then trigger autoscaling.

```
available_node_types:
  head_node:
    resources: { "CPU" : 4}
  worker_node:
    resources: {"CPU": 8}
    min_workers: 0
    max_workers: 1
```

```
ray.init()
@ray.remote(num_cpus=8)
def foo():
   pass

ray.get(foo.remote())
```

**Comment by zahyaah** [comment] 2022-07-28 21:18
Can I work on this? @wuisawesome

**Comment by zahyaah** [comment] 2022-07-28 21:22
### Do I have to change the following 
 return colorama.Style.BRIGHT + colorama.Fore.YELLOW
to 
 return colorama.Style.BRIGHT + colorama.Fore.YELLOW

[File -> python/ray/_private/worker.py]

<img width="605" alt="image" src="https://user-images.githubusercontent.com/72253920/181639779-3a9565e4-ed0c-4c77-8cc4-0830712aa974.png">

**Comment by wuisawesome** [comment] 2022-07-29 18:18
> Can I work on this? @wuisawesome

That would be awesome!

> Is this what I am supposed to do?

Yup exactly.

**Comment by zahyaah** [comment] 2022-07-29 18:21
> > Can I work on this? @wuisawesome
> 
> That would be awesome!
> 
> > Is this what I am supposed to do?
> 
> Yup exactly.

Okay, I will do it right away. Thanks @wuisawesome

**Comment by rkooo567** [comment] 2022-10-30 07:25
@zahyaah Did you get to make a PR?

**Comment by Yicheng-Lu-llll** [comment] 2023-10-03 20:58
Hi @wuisawesome, I've noticed that this issue has been open for some time and it hasn't been resolved yet. Can I take this on?

**Comment by rkooo567** [comment] 2023-10-03 23:55
We need an input from @scottsun94 for this one

**Comment by scottsun94** [comment] 2023-10-04 04:57
https://github.com/ray-project/ray/pull/27272

actually there was a suggestion for it. @Yicheng-Lu-llll if u could take it ovet and finish it, that'll be great!

**Comment by Yicheng-Lu-llll** [comment] 2023-10-04 15:34
> actually there was a suggestion for it. @Yicheng-Lu-llll if u could take it ovet and finish it, that'll be great!

Sure! Will follow the suggestion here: https://github.com/ray-project/ray/pull/27272#issuecomment-1201993905.

**Comment by Yicheng-Lu-llll** [comment] 2023-10-05 20:31
Hi, @scottsun94. Here is what I found:

**Comment by Yicheng-Lu-llll** [comment] 2023-10-05 23:39
Hi, @scottsun94, here's what I found:

Ray uses colorama, so it essentially utilizes ANSI code. The actual color is controlled by the Terminal Emulator (how it interprets the ANSI colors). Mac, Windows and Ubuntu have their own Terminal Emulator. 

Given these considerations, I believe it's reasonable to use the default config and test the colors on Mac, Windows, Ubuntu, and in VSCode(IDEs might also interpret the ANSI colors differently)

For further verification, I tested with both Ray 1.13.0 (the release version when this issue was opened) and the master branch of Ray.

As you can see from the screenshot below:

1.  the current colors appear quite satisfactory. No “too bright” problem(might because mac updates its Terminal Emulator since the issues created).
2. Some cases, logs without BRIGHT looks worse(bright aslo bolds the text, See issue https://github.com/tartley/colorama/issues/158)

Thus, my thought is that we retain the brightness and only change the autoscaler error color to bright red(see below). I'd like to know if this sounds good to you. Thank you in advance!



**Log in Mac's terminal:** On the left, tests were conducted on Ray 1.13.0 and the master branch of Ray. On the right, tests were done without the BRIGHT setting.
<img width="1728" alt="1" src="https://github.com/ray-project/ray/assets/51814063/31c2a19b-3200-4ed0-bfd7-bff9e1a6eb9e">




**Log in Ubuntu’s terminal:** On the left, tests were conducted on Ray 1.13.0 and the master branch of Ray. On the right, tests were done without the BRIGHT setting
<img width="1728" alt="2" src="https://github.com/ray-project/ray/assets/51814063/43e868f7-01c4-41d3-a913-751900fd84f8">


**Log in Windows terminal:** On the left, tests were conducted on Ray 1.13.0 and the master branch of Ray. On the right, tests were done without the BRIGHT setting

<img width="1728" alt="3" src="https://github.com/ray-project/ray/assets/51814063/abfe72c9-334e-4690-bf24-5bffe99b47dd">


**Log in VSCode** **with a gray background:** On the left, tests were conducted on Ray 1.13.0 and the master branch of Ray. On the right, tests were done without the BRIGHT setting
<img width="1728" alt="4" src="https://github.com/ray-project/ray/assets/51814063/69b4f9c2-bb29-4496-8f0d-593ca91c0e10">


**Log after changing the autoscaler error color to red in Mac's terminal with default config:**

The left side is with brightness, while the right side is tested without BRIGHT.
<img width="1728" alt="5" src="https://github.com/ray-project/ray/assets/51814063/e9b0161e-c24d-4e5a-bd5b-77268c30c4f9">



**Log after changing the autoscaler error color to red in Ubuntu’s terminal:**

The left side is with brightness, while the right side is tested without BRIGHT.
<img width="1728" alt="6" src="https://github.com/ray-project/ray/assets/51814063/9e1a3481-a01d-4b4c-b55c-c2658c7fd3bb">


**Log after changing the autoscaler error color to red in Windows terminal:**

The left side is with brightness, while the right side is tested without BRIGHT.
<img width="1728" alt="7" src="https://github.com/ray-project/ray/assets/51814063/17eb28e3-f570-428a-82db-262cf99c7c6e">


**Log after changing the autoscaler error color to red in VSCode** **with a gray background:**

The left side is with brightness, while the right side is tested without BRIGHT.
<img width="1728" alt="8" src="https://github.com/ray-project/ray/assets/51814063/a211855c-50e3-4a77-bb9b-f7d7798336f9">

**Comment by scottsun94** [comment] 2023-10-06 00:17
> only change the autoscaler error color to bright red(see below)

Using "red" probably is not the way to. I think there is a reason why we didn't use red initially. Red usually indicates real errors - a stop of partial/complete functionality. However, the autoscaler "errors" here are more like warnings that can be resolved by itself via autoscaling. It's more appropriate to use yellow. (a separate thing we should improve is the wording of those messages).


> Log in Mac's terminal: On the left, tests were conducted on Ray 1.13.0 and the master branch of Ray. On the right, tests were done without the BRIGHT setting.

When you say "without the BRIGHT setting", what do you mean? You mean using `Yellow` instead of `Bright yellow` or terminal setting like this?

<img width="182" alt="Screenshot 2023-10-05 at 5 16 25 PM" src="https://github.com/ray-project/ray/assets/9677264/f4bf2545-e93f-4a79-86c6-3c413d942502">

**Comment by Yicheng-Lu-llll** [comment] 2023-10-06 00:22
"without the BRIGHT setting" means I delete `colorama.Style.BRIGHT` in source code.

From
```python
        elif data.get("pid") == "autoscaler":
            if "Error:" in line or "Warning:" in line:
                return colorama.Style.BRIGHT + colorama.Fore.YELLOW
            else:
                return colorama.Style.BRIGHT + colorama.Fore.CYAN
```
to

```python
        elif data.get("pid") == "autoscaler":
            if "Error:" in line or "Warning:" in line:
                return colorama.Fore.YELLOW
            else:
                return colorama.Fore.CYAN
```

**Comment by scottsun94** [comment] 2023-10-06 05:06
I see. We actually don't use light/bright yellow. We just use the bright as the style.

I played with the colorama a bit on my basic mac terminal. The color looks a bit different from your test.

<img width="522" alt="Screenshot 2023-10-05 at 10 05 57 PM" src="https://github.com/ray-project/ray/assets/9677264/34759e83-eaa7-4e09-b0d0-dea00748f5de">

**Comment by Yicheng-Lu-llll** [comment] 2023-10-06 05:21
Yes, I have also tried using Colorama previously. For some reason, the color of the real log and the color produced solely through Colorama are different. Below is a screenshot of my Mac terminal using just Colorama. I think we get the same color.
<img width="1920" alt="image" src="https://github.com/ray-project/ray/assets/51814063/1f0a1b0b-6668-4bde-a9ca-72484ca6d808">

**Comment by scottsun94** [comment] 2023-10-06 05:28
> > I see: we actually don't use light/bright yellow. We just use the bright as the style.
> 
> I see!

lol... This is something I just learnt from you I guess? I never read this piece of code before.


> Yes, I have also tried using Colorama previously. For some reason, the color of the real log and the color produced solely through Colorama are different. Below is a screenshot of my Mac terminal using just Colorama. I think we get the same color. <img alt="image" width="1920" src="https://user-images.githubusercontent.com/51814063/273111229-1f0a1b0b-6668-4bde-a9ca-72484ca6d808.png">

Hmm. Then it seems that the colorama setting is changed by ray somewhere else?

**Comment by Yicheng-Lu-llll** [comment] 2023-10-06 05:34
It is possible. I haven't dived deep into it to see if it has also been changed somewhere. If there is such a need, I am happy to look into it! But based on the final appearance, I wonder if you think we should change or keep the original code.

**Comment by scottsun94** [comment] 2023-10-06 05:45
> It is possible. I haven't dived deep into it to see if it has also been changed somewhere. If there is such a need, I am happy to look into it! But based on the final appearance, I wonder if you think we should change or keep the original code.

If the log color can be the same yellow as produced solely through Colorama. I think we should just remove the `BRIGHT` style. Yellow itself should work well on all 3 background. However, we need to make sure the log can print the same yellow first.

**Comment by Yicheng-Lu-llll** [comment] 2023-10-06 05:48
I see, Will try to find out where it has also been changed.

**Comment by Yicheng-Lu-llll** [comment] 2023-10-07 01:09
Hi @scottsun94, I've found it! There indeed exists a setting that also changes the colorama configuration.

Basically, [here](https://github.com/ray-project/ray/blob/master/python/ray/_private/worker.py#L1978) it adds `colorama.Style.DIM`, which is used to create a dim or faint appearance of the text, making it less bright compared to the normal text.

Could I remove `colorama.Style.DIM` and follow your suggestion to also remove the `BRIGHT` style? I think removing colorama.Style.DIM is reasonable because, according to the [colorama documentation](https://github.com/tartley/colorama#description), on Windows, Colorama does not support ANSI 'dim text'; it looks the same as 'normal text'. This can also be confirmed by my previous screenshot, so to make it consistent with Mac and Linux terminals, removing it seems reasonable.

By the way, currently colorama.Style.DIM affects all worker logs, like raylet, autoscaler. But I think removing it is reasonable as on Windows, Colorama does not support ANSI 'dim text'.

I wonder if this seems good to you. Thank you in advance!

Here is the final screenshot:
<img width="1920" alt="image" src="https://github.com/ray-project/ray/assets/51814063/92be3658-1465-4b8b-b2ff-8c532517a67d">

**Comment by scottsun94** [comment] 2023-10-07 06:30
Thanks for the investigation!
Yeah. I think it's fine to remove it.

**Comment by scottsun94** [comment] 2023-10-07 06:32
Can you help test how it looks like now on different terminals and different bgs (white, dark, grey). Don't have share the results but could you do a sanity check and make sure they all have reasonable color contrast?

**Comment by Yicheng-Lu-llll** [comment] 2023-10-09 23:23
> Can you help test how it looks like now on different terminals and different bgs (white, dark, grey)? Don't need to share the results but just do a sanity check and make sure they all have reasonable color contrast.

Of course! I have also made a PR for it. It is ready for review(The CI failure is not related to my change).

**Closed** 2023-10-11 00:42 UTC
Labels: bug, good first issue, P2, core, UX, observability-ux
