### ISSUE TITLE
[Core] ray.init hangs, corrupts, crashes on WSL 

### ISSUE THREAD

**Issue by jsuarez5341** [ray-project/ray#28478] opened 2022-09-13 19:24 UTC
### What happened + What you expected to happen

Installed ray[all]==2.0 on a fresh WSL 2 with conda 3.9

ray.init() hangs and eventually crashes. This leaves extra processes around that ray kill --force cannot terminate (have to kill -9). Even managed to freeze my entire WSL, unresponsive to wsl --shutdown, and required a reboot of the host machine.

Fixed by ray.init(include_dashboard=False) -- presumably, the dashboard isn't connecting properly through WSL and is missing a timeout?

### Versions / Dependencies

ray 2.0, python 3.9.x, WSL Ubuntu 20.04, conda 3.9

### Reproduction script

import ray
ray.init()

### Issue Severity

High: It blocks me from completing my task.

**Comment by mattip** [comment] 2022-09-14 17:18
I assume you are running the `ray.init()` in the WSL2 shell, right? Can you see any suspicious messages in /tmp/ray/sessson*/logs ?

Could you describe your hardware: do you have an nvidia graphics card? We have seen some instances where dashboard uses gpustat which can crash on windows. PR #26295 was meant to fix that but has not been merged yet. Could you try updating gpustat to `gpustat == 1.0.0` instead of `gpustat == 1.0.0b1` and see if that helps?

**Comment by peytondmurray** [comment] 2022-09-14 23:39
I'm trying to recreate this bug just now.

<details>
<summary>Environment</summary>
<pre><code>
# packages in environment at /home/pdmurray/.pyenv/versions/mambaforge/envs/ray:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aiohttp                   3.8.1                    pypi_0    pypi
aiohttp-cors              0.7.0                    pypi_0    pypi
aiorwlock                 1.3.0                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
anyio                     3.6.1                    pypi_0    pypi
asgiref                   3.5.2                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     22.1.0                   pypi_0    pypi
backoff                   1.10.0                   pypi_0    pypi
blessed                   1.19.1                   pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.6.15.2          ha878542_0    conda-forge
cachetools                5.2.0                    pypi_0    pypi
certifi                   2022.9.14                pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.0.4                    pypi_0    pypi
cloudpickle               2.2.0                    pypi_0    pypi
colorful                  0.5.4                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
distlib                   0.3.6                    pypi_0    pypi
dm-tree                   0.1.7                    pypi_0    pypi
fastapi                   0.84.0                   pypi_0    pypi
filelock                  3.8.0                    pypi_0    pypi
fonttools                 4.37.1                   pypi_0    pypi
frozenlist                1.3.1                    pypi_0    pypi
fsspec                    2022.8.2                 pypi_0    pypi
google-api-core           2.10.1                   pypi_0    pypi
google-auth               2.11.0                   pypi_0    pypi
googleapis-common-protos  1.56.4                   pypi_0    pypi
gpustat                   1.0.0                    pypi_0    pypi
grpcio                    1.43.0                   pypi_0    pypi
gym                       0.23.1                   pypi_0    pypi
gym-notices               0.0.8                    pypi_0    pypi
h11                       0.13.0                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.21.3                   pypi_0    pypi
importlib-metadata        4.12.0                   pypi_0    pypi
iso8601                   1.0.2                    pypi_0    pypi
jsonschema                4.16.0                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
kopf                      1.35.6                   pypi_0    pypi
kubernetes                24.2.0                   pypi_0    pypi
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.39.3               h753d276_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.12               h166bdaf_3    conda-forge
lz4                       4.0.2                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
msgpack                   1.0.4                    pypi_0    pypi
multidict                 6.0.2                    pypi_0    pypi
ncurses                   6.3                  h27087fc_1    conda-forge
networkx                  2.8.6                    pypi_0    pypi
numpy                     1.23.3                   pypi_0    pypi
nvidia-ml-py              11.495.46                pypi_0    pypi
oauthlib                  3.2.1                    pypi_0    pypi
opencensus                0.11.0                   pypi_0    pypi
opencensus-context        0.1.3                    pypi_0    pypi
openssl                   3.0.5                h166bdaf_2    conda-forge
opentelemetry-api         1.1.0                    pypi_0    pypi
opentelemetry-exporter-otlp 1.1.0                    pypi_0    pypi
opentelemetry-exporter-otlp-proto-grpc 1.1.0                    pypi_0    pypi
opentelemetry-proto       1.1.0                    pypi_0    pypi
opentelemetry-sdk         1.1.0                    pypi_0    pypi
opentelemetry-semantic-conventions 0.20b0                   pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pandas                    1.4.4                    pypi_0    pypi
pillow                    9.2.0                    pypi_0    pypi
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
platformdirs              2.5.2                    pypi_0    pypi
prometheus-client         0.13.1                   pypi_0    pypi
protobuf                  3.20.1                   pypi_0    pypi
psutil                    5.9.2                    pypi_0    pypi
py-spy                    0.3.14                   pypi_0    pypi
pyarrow                   6.0.1                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pydantic                  1.10.2                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
python                    3.9.13          h2660328_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python-json-logger        2.0.4                    pypi_0    pypi
pytz                      2022.2.1                 pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
ray                       3.0.0.dev0                dev_0    <develop>
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scipy                     1.9.1                    pypi_0    pypi
setuptools                65.3.0             pyhd8ed1ab_1    conda-forge
six                       1.16.0                   pypi_0    pypi
smart-open                6.2.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
sqlite                    3.39.3               h4ff8645_0    conda-forge
starlette                 0.19.1                   pypi_0    pypi
tabulate                  0.8.10                   pypi_0    pypi
tensorboardx              2.5.1                    pypi_0    pypi
tifffile                  2022.8.12                pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
typing-extensions         4.3.0                    pypi_0    pypi
tzdata                    2022c                h191b570_0    conda-forge
urllib3                   1.26.12                  pypi_0    pypi
uvicorn                   0.16.0                   pypi_0    pypi
virtualenv                20.16.5                  pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
websocket-client          1.4.1                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yarl                      1.8.1                    pypi_0    pypi
zipp                      3.8.1                    pypi_0    pypi
</pre></code>
</details>

Test:
```python
import ray
ray.init()
print('done')
```

Executed successfully. This still could be an issue with `gpustat` - I don't currently have an NVIDIA GPU in my machine, so gpustat just errors out immediately. I'll try with an NVIDIA GPU and report back.

**Comment by mattip** [comment] 2022-10-02 08:35
@peytondmurray any updates?

**Comment by peytondmurray** [comment] 2022-10-03 23:05
@mattip I haven't been able to reproduce this yet. I can't tell if this is just my machine, though, so I'm looking into trying with a different one as well.

**Comment by mattip** [comment] 2022-10-04 06:03
Without any more comment from @jsuarez5341 about the hardware (GPU, whether it is exposed to WSL and how) I don't think we can make any progress here.

**Comment by mattip** [comment] 2022-10-04 06:04
I labelled this "needs-repo-script" in spite of actually needing a platform description, since reproduction seems to be the problem here.

**Comment by mattip** [comment] 2022-10-20 17:18
We have had no update from the OP on describing their hardware, and have been unsuccessful in reproducing. I am closing, please reopen with more info or open a new issue as appropriate.

**Closed by mattip** 2022-10-20 17:18 UTC
Labels: bug, needs-repro-script, triage, windows, QS
