### ISSUE TITLE
Ray crashes on a large cluster

### ISSUE THREAD

**Issue by panye** [ray-project/ray#1479] opened 2018-01-28 04:25 UTC
### Describe the problem

I'm using ray on a large cluster with 50 machine each has 8 gpu. Ray crashes when I run a test script as below. The script creates 400 actors each uses exactly 1 gpu. But when I try to create 50 actors each uses 8 gpu, ray works fine and returns the result. I have tried command `ulimit -n 65536` after `/usr/local/bin/ray start --head --redis-port=6379 --num-cpus=0`. But it still returns the same error.

### Source code / logs

My test scrpit:
```
import ray

@ray.remote(num_gpus=1)
class WorkerNode(object):
    def __init__(self):
        self.node_ip = ray.services.get_node_ip_address()
        self.gpu = ray.get_gpu_ids()
    def kill_trgo(self):
        return str(self.node_ip) + ":" + str(self.gpu[0])

if __name__ == '__main__':
    ray.init(redis_address="10.98.246.67:6379")
    worker_nodes = [WorkerNode.remote() for _ in xrange(400)]
    results = ray.get([worker_node.kill_trgo.remote() for worker_node in worker_nodes])
    results.sort()
    print results

```

This script returns following error:

```
A worker died or was killed while executing a task.

  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="10.98.246.67:6379")
  
Traceback (most recent call last):
  File "/disk1/ray_test_gpu1.py", line 14, in <module>
    results = ray.get([worker_node.kill_trgo.remote() for worker_node in worker_nodes])
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 2168, in get
    raise RayGetError(object_ids[i], value)
ray.worker.RayGetError: Could not get objectid ObjectID(3b84fc32ba8ebaaf0c27d8cbe51242614e68d5eb). It was created by remote function <unknown> which failed with:

Remote function <unknown> failed with:

Invalid return value: likely worker died or was killed while executing the task.
```

**Comment by robertnishihara** [comment] 2018-01-28 05:25
Thanks for reporting the problem!

Can you try the following?

1. If you run the same application on a single machine and create 8 actors that each require 1 GPU, does it work? I'm guessing this only appears with many machines?

2. What is the output of `ulimit -n`? It's important to run `ulimit -n 65536` BEFORE running `ray start`. One way to check is after running `ray.init`, to run

    ```python
    ray.init(redis_address="10.98.246.67:6379")
    r = ray.worker.global_worker.redis_client
    print(r.config_get('maxclients'))  # What does this print?
    ```

    What is printed by the last line?

    After the application fails, can you try starting a new Python interpreter and running the following.

    ```python
    ray.init(redis_address="10.98.246.67:6379")
    r = ray.worker.global_worker.redis_client
    print(r.config_get('maxclients'))
    print(r.info('clients'))  # What does this print?
    ```

    If the `maxclients` value is close to the `connected_clients` value in `r.info('clients')`, then the issue may be that the number of clients attempting to connect to Redis is greater than the number allowed.

3. Can you run `log_files = ray.global_state.log_files()` and see if there is any useful information in there that explains why the worker crashed? This tries to gather all of the log files from the workers (grouped by IP address and then by filename). The hope is that something there suggests why the worker died. Note that this function hasn't been used much and it may not work.

    Really we should make the error message that you're seeing contain a command that can be used to retrieve the relevant log file (or at least it should include the relevant machine IP address and log filename).

Thanks for including the code. I'll give it a try and see if I can reproduce the problem.

**Comment by robertnishihara** [comment] 2018-01-28 05:42
I just ran something similar (on EC2) with the following results. Your script succeeded for me.

```python
>>> print(r.config_get('maxclients'))
{'maxclients': '10000'}

>>> print(r.info('clients'))
{'connected_clients': 2848, 'client_biggest_input_buf': 0, 'client_longest_output_list': 3670, 'blocked_clients': 0}
```

I didn't use actual GPUs since that seemed unlikely to be the issue. Do you know if you can reproduce the problem with just CPUs?

**Comment by panye** [comment] 2018-01-28 06:09
Hi robertnishihara, thank you for your detailed reply!
As your suggestion, I tried the following things:
1. The script should be OK on single machine. Actually I have run the script on a cluster with 16 machines each has 8 gpu. The script works well.
2. I tested your posted script on the cluster. First I start ray without `ulimit -n 65536`, the script returns `{'maxclients': '10000'}`.
    Then I ran  `ulimit -n 65536` before `ray start --head` , with only the head , it returns```
 {'maxclients': '10000'}
{'client_biggest_input_buf': 0, 'blocked_clients': 0, 'client_longest_output_list': 0, 'connected_clients': 19}
```
The number of maxclients doesn't change. 
At last, I started 50 minions , ran my script and ran this command again. It returns ```
{'maxclients': '10000'}
{'client_biggest_input_buf': 0, 'blocked_clients': 0, 'client_longest_output_list': 0, 'connected_clients': 8870}
```
The number of maxclients and connected_clients are close.

**Comment by robertnishihara** [comment] 2018-01-28 06:19
What if you start Ray on the head machine with `ray start --head --redis-max-clients=65500`. Does that work and successfully use a much larger number of Redis clients?

How many CPUs does each machine have? By default, each machine starts a number of workers equal to the number of CPUs. You can cause Ray to not start any workers initially by passing `--num-workers=0` into `ray start` (both on the head and on all of the other nodes).

**Comment by panye** [comment] 2018-01-28 06:30
The command `--redis-max-clients=65500` works! Thank you very much!

**Comment by robertnishihara** [comment] 2018-01-28 06:31
Ok hmm... maybe we should be doing that automatically then.

**Comment by robertnishihara** [comment] 2018-01-28 06:59
Fixed! Thanks for pointing that out.

**Comment by robertnishihara** [comment] 2018-01-28 21:19
#1482 should make this happen automatically without `--redis-max-clients` being specified.

Closing since I believe this is resolved, but please reopen if there are more issues.

**Closed by robertnishihara** 2018-01-28 21:19 UTC
