### ISSUE TITLE
[dashboard] `failed to connect to all addresses` in docker

### ISSUE THREAD

**Issue by Legend94rz** [ray-project/ray#13090] opened 2020-12-28 06:48 UTC
### What is the problem?
I run the example code from https://docs.ray.io/en/master/tune/examples/mnist_pytorch.html, then I get the following error:
```
2020-12-28 14:25:01,355 WARNING worker.py:1034 -- The agent on node bjlt-hg263.sy failed with the following error:
Traceback (most recent call last):
  File "/root/miniconda/envs/py37/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 306, in <module>
    loop.run_until_complete(agent.run())
  File "/root/miniconda/envs/py37/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/root/miniconda/envs/py37/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 180, in run
    agent_ip_address=self.ip))
  File "/root/miniconda/envs/py37/lib/python3.7/site-packages/grpc/experimental/aio/_call.py", line 286, in __await__
    self._cython_call._status)
grpc.experimental.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1609136701.349665128","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4090,"referenced_errors":[{"created":"@1609136701.349661159","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}"
>

(pid=raylet) Traceback (most recent call last):
(pid=raylet)   File "/root/miniconda/envs/py37/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 317, in <module>
(pid=raylet)     raise e
(pid=raylet)   File "/root/miniconda/envs/py37/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 306, in <module>
(pid=raylet)     loop.run_until_complete(agent.run())
(pid=raylet)   File "/root/miniconda/envs/py37/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
(pid=raylet)     return future.result()
(pid=raylet)   File "/root/miniconda/envs/py37/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 180, in run
(pid=raylet)     agent_ip_address=self.ip))
(pid=raylet)   File "/root/miniconda/envs/py37/lib/python3.7/site-packages/grpc/experimental/aio/_call.py", line 286, in __await__
(pid=raylet)     self._cython_call._status)
(pid=raylet) grpc.experimental.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
(pid=raylet)    status = StatusCode.UNAVAILABLE
(pid=raylet)    details = "failed to connect to all addresses"
(pid=raylet)    debug_error_string = "{"created":"@1609136701.349665128","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4090,"referenced_errors":[{"created":"@1609136701.349661159","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}"
(pid=raylet) >
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

ray 1.1
python 3.7
tensorflow 2.2
pytorch 1.7
os: ubuntu 18.04
edit: os is in a docker.

### Reproduction (REQUIRED)
just run the example code: https://docs.ray.io/en/master/tune/examples/mnist_pytorch.html.
besides, when I run another piece of code wirtten by myself, this error also appears.
I have tested the example code in a cleaned environment, which only install ray[tune] 1.1 and pytorch 1.7 (and other requirements)

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment] 2020-12-28 18:39
cc @mfitton I think we should improve the error msg here.

This is streamed from the dashboard agent that it is failed to be connected to the node. It is possible that one of your nodes are crashed for some reason. 

Can you run

```python3
ray.init(address='auto')
print(ray.nodes())
```

and see what's printed after you see this error message?

**Comment by Legend94rz** [comment] 2020-12-29 02:30
Thank you @rkooo567 

I added
```
ray.init(address='auto', include_dashboard=False)
print(ray.nodes())
```
before `ray.run`, and the errorr still exists.

The output of `ray.nodes()` is:
```
[{'NodeID': '4c5a196d8003a155e8cda2629f9ceb689e855e0d', 'Alive': True, 'NodeManagerAddress': '10.48.242.141', 'NodeManagerHostname': 'bjlt-hg263.sy', 'NodeManagerPort': 51404, 'ObjectManagerPort': 37228, 'ObjectStoreSocketName': '/tmp/ray/session_2020-12-
28_20-03-21_258995_144395/sockets/plasma_store', 'RayletSocketName': '/tmp/ray/session_2020-12-28_20-03-21_258995_144395/sockets/raylet', 'MetricsExportPort': 59305, 'alive': True, 'Resources': {'GPU': 5.0, 'node:10.48.242.141': 1.0, 'memory': 1059.0, 'ac
celerator_type:RTX': 1.0, 'CPU': 30.0, 'object_store_memory': 365.0}}]
```

I have seen an issue said similar failure with include_dashboard set to false, so is it related?

**Comment by mfitton** [comment] 2020-12-31 00:45
Going to take a look at this now and report back.

**Comment by mfitton** [comment] 2020-12-31 18:21
@Legend94rz just want to confirm, you're running on Ray version `1.1.0` not Ray version `1.0.1`, is that correct? I ask because the line of code for the error you're seeing doesn't line up with that line of code in version `1.1.0` as far as I'm seeing.

Also, can I ask how you launched these nodes? Was it manual, or are you using the Ray cluster launcher? I ask because the cluster launcher sets up a security group for the Ray cluster that allows this GRPC connection between the raylet and the dashboard agent. That said, this connection is made within the same node, so that's likely not the issue. Still, I'd like to get a better idea of how you're launching this cluster.

**Comment by mfitton** [comment] 2020-12-31 20:59
@Legend94rz I tried to recreate the error, using https://gist.github.com/6f46ee557b2629b6f4e9fe94c4ff201c this cluster YAML file to launch the node and then calling `ray submit` on the repro script you provided, and I didn't see any errors. I'd appreciate any additional information you can get me to help reproduce.

**Comment by Legend94rz** [comment] 2021-01-02 13:39
@mfitton I have checked the ray version is `1.1.0`.

This node (a virtual machine) managed by my company. The node located in a LAN and it cannot access Internet in general, except using proxy by setting `http_proxy` and `https_proxy` env parameters. Besides, most of the ports of the node are closed for security, and I have no permission to open it in general, but I don't think this has anything to do with that error, because I'm running code on only one node, and even if that node can't access other nodes, the code should still run correctly.

BTW, I just install ray (by `pip install ray[tune]`) on it and then `python mnist_example.py`, and it tells me the errors. No additional changes have been made, and no other command.

**Comment by gshimansky** [comment] 2021-03-26 23:16
@Legend94rz Are you by chance running Ray with `http_proxy` or `https_proxy` environment variables? To me this comment helped to resolve the problem https://github.com/ray-project/ray/issues/11940#issuecomment-730844828
Dashboard (in Ray 1.1.0) doesn't work when proxy variables are present because GRPC attempts to use proxy for connections.

**Comment by Legend94rz** [comment] 2021-03-31 04:15
Weird.. today I rerun the example code and the simple code written by myself, it works without any change.
`http_proxy` and `https_proxy` are both set to a proxy server.
I use `ray start --head` to start a node, and run the code on this node.

**Comment by scottsun94** [comment] 2022-10-05 21:43
@Legend94rz Is this issue fixed? Shall we close it now?

**Closed** 2022-10-17 09:49 UTC
Labels: bug, P2, dashboard, fix-error-msg
