### ISSUE TITLE
[ray] [tune] __ray_terminate__() blocks computing units

### ISSUE THREAD

**Issue by ninamiolane** [ray-project/ray#6938] opened 2020-01-28 02:00 UTC
When running a python pipeline on different processing units using ray, the function 
``` ray_MyTrainableClass:__ray_terminate__()```
does not terminate (!) and therefore blocks the corresponding unit. This leads the pipeline to fail, as ultimately there is no remaining units available.

*Ray version and other system information (Python version, TensorFlow version, OS):*

System:
CENTOS 7.7.1908 3.10.0-957.12.2.el7.x86_64 Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz 
Python: 
3.5.2
Ray: 
0.7.6

**Comment by richardliaw** [comment] 2020-01-30 08:43
Hi Nina, can you update to the latest version of Ray? (0.8 or even better, latest wheels)

**Comment by richardliaw** [comment] 2020-04-21 04:19
I'm closing this because I'm not quite sure how to reproduce this - but feel free to reopen!

**Closed by richardliaw** 2020-04-21 04:19 UTC
Labels: bug, tune
