### ISSUE TITLE
[tune] Experiment specs get mixed up sometimes

### ISSUE THREAD

**Issue by arunmk** [ray-project/ray#8744] opened 2020-06-02 17:27 UTC
### What is the problem?
I use the tune.run_experiments and sent a set of experiment specs with their appropriate configs. However sometimes the experiment runs with the wrong config. From reading code I think that this is the line with the issue: https://github.com/ray-project/ray/blob/releases/0.8.4/python/ray/tune/tune.py#L251

I think that should become:
`
                config=exp["config"],
`
 

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.8.0, 0.8.4 (also master based on code)

### Reproduction (REQUIRED)
***WORKING ON GETTING A SCRIPT***
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by krfricke** [comment] 2020-07-20 13:04
@arunmk is this issue still prevailing? The code line you pointed out should be correct as is, since it only affects items that are _not_ `Experiment` objects (and thus don't have their own config). I did a short test and confirmed it's working as intended.

It would be helpful if you could provide the code where you build the experiments and start up Tune.

I'm closing this for now, feel free to reopen or ping me if the issue prevails.

**Closed by krfricke** 2020-07-20 13:04 UTC
Labels: P2, bug, needs-repro-script, tune

**Comment by arunmk** [comment] 2020-07-20 19:32
Thanks @krfricke, yes the code location is invalid. I still see the issue but have worked around it by passing the trainer function name as part of the config. I will reopen this when I have a small repro
