### ISSUE TITLE
[CI] `windows://python/ray/tests:test_tensorflow` is failing/flaky on master.

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#31194] opened 2022-12-19 20:37 UTC
- 49b1ed180d0447bcfd82d819bc1d37ef024afbab FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1591#01852ac1-d82e-439e-8aa1-da969ff836d0)
- 9bb62fbe30910078885faaf51b9172a1042e9117 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1590#01852a63-93ba-41cb-8fde-ed2c5e9cdc01)
- d28552b7b61b4ba74563d7710fdd6b5562fe73a2 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1589#01852a62-baec-4422-aea0-d2cfec5490dc)
- 608276bb96b5b49769cd8816414c280c5431d843 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1588#01852a5b-f1f4-48b5-b195-53148d709617)
- c03c4c67182d7f79d36465f2ffbef88b2b958afb FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1587#01852a30-52c9-4481-b1b8-908139932d78)
- 24b6a8035aa2afac641024d4d6664b6c066f6d20 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1586#01852a25-8d21-43be-82b0-6e8f47ffa553)
- 70b0d039da09cb35f5b4584e5a9603643cf29757 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1585#01852a24-6506-4eb4-bf7a-7da323c4c791)
- 98fef7732852cdb3e9377cd87c1ee1085b894928 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1584#018529b1-d576-45d5-af44-815b73ba0b90)
- 69b2506c281c777c44980c376497bc2a8d2ad051 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1583#018529b1-9831-468d-86be-3adc5289bcce)
- 8f499013de9c7beaf7bf5537a70aaa8bf0322203 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1582#018528ce-12a1-426e-979c-40cc5c7c2ff4)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-windows://python/ray/tests:test_tensorflow-END
....

**Comment by clarng** [comment] 2022-12-19 20:38
\\?\C:\Users\ContainerAdministrator\AppData\Local\Temp\Bazel.runfiles_zl__8zx0\runfiles\com_github_ray_project_ray\python\ray\tests\test_tensorflow.py:124:
--
  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  | c:\install\ray\python\ray\experimental\tf_utils.py:142: in set_flat
  | arrays = unflatten(new_weights, shapes)
  | c:\install\ray\python\ray\experimental\tf_utils.py:15: in unflatten
  | size = np.prod(shape, dtype=np.int)
  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  |  
  | attr = 'int'
  |  
  | def __getattr__(attr):
  | # Warn for expired attributes, and return a dummy function
  | # that always raises an exception.
  | import warnings
  | try:
  | msg = __expired_functions__[attr]
  | except KeyError:
  | pass
  | else:
  | warnings.warn(msg, DeprecationWarning, stacklevel=2)
  |  
  | def _expired(*args, **kwds):
  | raise RuntimeError(msg)
  |  
  | return _expired
  |  
  | # Emit warnings for deprecated attributes
  | try:
  | val, msg = __deprecated_attrs__[attr]
  | except KeyError:
  | pass
  | else:
  | warnings.warn(msg, DeprecationWarning, stacklevel=2)
  | return val
  |  
  | if attr in __future_scalars__:
  | # And future warnings for those that will change, but also give
  | # the AttributeError
  | warnings.warn(
  | f"In the future `np.{attr}` will be defined as the "
  | "corresponding NumPy scalar.  (This may have returned Python "
  | "scalars in past versions.", FutureWarning, stacklevel=2)
  |  
  | # Importing Tester requires importing all of UnitTest which is not a
  | # cheap import Since it is mainly used in test suits, we lazy import it
  | # here to save on the order of 10 ms of import time for most users
  | #
  | # The previous way Tester was imported also had a side effect of adding
  | # the full `numpy.testing` namespace
  | if attr == 'testing':
  | import numpy.testing as testing
  | return testing
  | elif attr == 'Tester':
  | from .testing import Tester
  | return Tester
  |  
  | >       raise AttributeError("module {!r} has no attribute "
  | "{!r}".format(__name__, attr))
  | E       AttributeError: module 'numpy' has no attribute 'int'

**Comment by cadedaniel** [comment] 2022-12-19 21:16
I believe both this failure and [the other windows failure](https://github.com/ray-project/ray/issues/31193) are caused by breaking changes in numpy 1.24 release

**Comment by cadedaniel** [comment] 2022-12-20 00:56
See https://github.com/ray-project/ray/issues/31193#issuecomment-1358690888 (+ thread) for latest

**Comment by krfricke** [comment] 2023-01-03 14:22
This has been fixed by #31329

**Closed by krfricke** 2023-01-03 14:22 UTC
Labels: P0, flaky-tracker
