### ISSUE TITLE
[core][perf] single_node_2 large_object_time latency benchmark spikes

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#30711] opened 2022-11-28 22:54 UTC
### What happened + What you expected to happen

[single_node_2](https://b534fd88.us1a.app.preset.io/explore/?dashboard_page_id=p80veMwQTX&slice_id=619)

Latency spiked by ~20% several times over the last week.

### Versions / Dependencies

3.0dev

### Reproduction script

single_node_2 core benchmark.

**Comment by stephanie-wang** [comment] 2022-11-29 17:16
So far I found that the latency for this workload is not very stable. Both a recent (c835ef9543a66301da2ba39181f7bd53e7e5da1d) and an older commit (96b7cddfeff7bbdc4b10552a395ed33784ee81c2) showed similarly high latencies when run multiple times.

c835ef9543a66301da2ba39181f7bd53e7e5da1d: 
```
2022-11-28 18:01:02,519	INFO worker.py:1231 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-28 18:01:02,520	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.31.155.186:9031...
2022-11-28 18:01:02,531	INFO worker.py:1535 -- Connected to Ray cluster. View the dashboard at [1m[32mhttps://console.anyscale-staging.com/api/v2/sessions/ses_1umb7y1yvcuavs8ad7pai967/services?redirect_to=dashboard [39m[22m
Generating object
Putting object


Getting object
Done
Ray.get large object time: 262.44733826899983 (107374182400 bytes)
[0m2022-11-28 18:05:36,886	INFO worker.py:1231 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-28 18:05:36,886	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.31.155.186:9031...
2022-11-28 18:05:36,894	INFO worker.py:1535 -- Connected to Ray cluster. View the dashboard at [1m[32mhttps://console.anyscale-staging.com/api/v2/sessions/ses_1umb7y1yvcuavs8ad7pai967/services?redirect_to=dashboard [39m[22m
Generating object
Putting object
Getting object
Done
Ray.get large object time: 386.5621551559998 (107374182400 bytes)
[0m2022-11-28 18:12:16,216	INFO worker.py:1231 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-28 18:12:16,216	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.31.155.186:9031...
2022-11-28 18:12:16,225	INFO worker.py:1535 -- Connected to Ray cluster. View the dashboard at [1m[32mhttps://console.anyscale-staging.com/api/v2/sessions/ses_1umb7y1yvcuavs8ad7pai967/services?redirect_to=dashboard [39m[22m
Generating object
Putting object
Getting object
Done
Ray.get large object time: 389.24902958800067 (107374182400 bytes)
[0m2022-11-28 18:18:58,964	INFO worker.py:1231 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-28 18:18:58,964	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.31.155.186:9031...
2022-11-28 18:18:58,973	INFO worker.py:1535 -- Connected to Ray cluster. View the dashboard at [1m[32mhttps://console.anyscale-staging.com/api/v2/sessions/ses_1umb7y1yvcuavs8ad7pai967/services?redirect_to=dashboard [39m[22m
Generating object
Putting object
Getting object
Done
Ray.get large object time: 388.1630175270002 (107374182400 bytes)
[0m2022-11-28 18:25:42,957	INFO worker.py:1231 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-28 18:25:42,957	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.31.155.186:9031...
2022-11-28 18:25:42,965	INFO worker.py:1535 -- Connected to Ray cluster. View the dashboard at [1m[32mhttps://console.anyscale-staging.com/api/v2/sessions/ses_1umb7y1yvcuavs8ad7pai967/services?redirect_to=dashboard [39m[22m
Generating object
Putting object
Getting object
Done
Ray.get large object time: 385.7731976979994 (107374182400 bytes)
[0m2022-11-28 18:32:22,438	INFO worker.py:1231 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-28 18:32:22,438	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.31.155.186:9031...
2022-11-28 18:32:22,447	INFO worker.py:1535 -- Connected to Ray cluster. View the dashboard at [1m[32mhttps://console.anyscale-staging.com/api/v2/sessions/ses_1umb7y1yvcuavs8ad7pai967/services?redirect_to=dashboard [39m[22m
Generating object
Putting object
Getting object
Done
Ray.get large object time: 387.66130479300045 (107374182400 bytes)
[0m2022-11-28 18:39:05,426	INFO worker.py:1231 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-28 18:39:05,427	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.31.155.186:9031...
2022-11-28 18:39:05,436	INFO worker.py:1535 -- Connected to Ray cluster. View the dashboard at [1m[32mhttps://console.anyscale-staging.com/api/v2/sessions/ses_1umb7y1yvcuavs8ad7pai967/services?redirect_to=dashboard [39m[22m
Generating object
Putting object
Getting object
Done
Ray.get large object time: 386.1147940340006 (107374182400 bytes)
[0m2022-11-28 18:45:44,626	INFO worker.py:1231 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-28 18:45:44,626	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.31.155.186:9031...
2022-11-28 18:45:44,635	INFO worker.py:1535 -- Connected to Ray cluster. View the dashboard at [1m[32mhttps://console.anyscale-staging.com/api/v2/sessions/ses_1umb7y1yvcuavs8ad7pai967/services?redirect_to=dashboard [39m[22m
Generating object
Putting object
Getting object
Done
Ray.get large object time: 388.67203187199993 (107374182400 bytes)
[0m2022-11-28 18:52:27,482	INFO worker.py:1231 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-28 18:52:27,483	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.31.155.186:9031...
2022-11-28 18:52:27,491	INFO worker.py:1535 -- Connected to Ray cluster. View the dashboard at [1m[32mhttps://console.anyscale-staging.com/api/v2/sessions/ses_1umb7y1yvcuavs8ad7pai967/services?redirect_to=dashboard [39m[22m
Generating object
Putting object
Getting object
Done
Ray.get large object time: 387.1391345010006 (107374182400 bytes)
[0m2022-11-28 18:59:07,400	INFO worker.py:1231 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-28 18:59:07,400	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.31.155.186:9031...
2022-11-28 18:59:07,409	INFO worker.py:1535 -- Connected to Ray cluster. View the dashboard at [1m[32mhttps://console.anyscale-staging.com/api/v2/sessions/ses_1umb7y1yvcuavs8ad7pai967/services?redirect_to=dashboard [39m[22m
Generating object
Putting object
Getting object
Done
Ray.get large object time: 388.85012134799945 (107374182400 bytes)
[0m
```

96b7cddfeff7bbdc4b10552a395ed33784ee81c2:
```bash
2022-11-28 19:09:18,222	INFO worker.py:1231 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-28 19:09:18,223	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.31.255.186:9031...
2022-11-28 19:09:18,231	INFO worker.py:1535 -- Connected to Ray cluster. View the dashboard at [1m[32mhttps://console.anyscale-staging.com/api/v2/sessions/ses_nefefi9qusrt4aqh38ygp84r/services?redirect_to=dashboard [39m[22m
Generating object
Putting object
Getting object
Done
Ray.get large object time: 245.10925642200004 (107374182400 bytes)
[0m2022-11-28 19:13:41,756	INFO worker.py:1231 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-28 19:13:41,756	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.31.255.186:9031...
2022-11-28 19:13:41,765	INFO worker.py:1535 -- Connected to Ray cluster. View the dashboard at [1m[32mhttps://console.anyscale-staging.com/api/v2/sessions/ses_nefefi9qusrt4aqh38ygp84r/services?redirect_to=dashboard [39m[22m
Generating object
Putting object
Getting object
Done
Ray.get large object time: 381.9200874090002 (107374182400 bytes)
[0m2022-11-28 19:20:17,410	INFO worker.py:1231 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-28 19:20:17,410	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.31.255.186:9031...
2022-11-28 19:20:17,419	INFO worker.py:1535 -- Connected to Ray cluster. View the dashboard at [1m[32mhttps://console.anyscale-staging.com/api/v2/sessions/ses_nefefi9qusrt4aqh38ygp84r/services?redirect_to=dashboard [39m[22m
Generating object
Putting object
Getting object
Done
Ray.get large object time: 387.63092451600005 (107374182400 bytes)
[0m2022-11-28 19:26:57,020	INFO worker.py:1231 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-28 19:26:57,020	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.31.255.186:9031...
2022-11-28 19:26:57,028	INFO worker.py:1535 -- Connected to Ray cluster. View the dashboard at [1m[32mhttps://console.anyscale-staging.com/api/v2/sessions/ses_nefefi9qusrt4aqh38ygp84r/services?redirect_to=dashboard [39m[22m
Generating object
Putting object
Getting object
Done
Ray.get large object time: 389.5693053939999 (107374182400 bytes)
[0m2022-11-28 19:33:39,358	INFO worker.py:1231 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-28 19:33:39,358	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.31.255.186:9031...
2022-11-28 19:33:39,366	INFO worker.py:1535 -- Connected to Ray cluster. View the dashboard at [1m[32mhttps://console.anyscale-staging.com/api/v2/sessions/ses_nefefi9qusrt4aqh38ygp84r/services?redirect_to=dashboard [39m[22m
Generating object
Putting object
^[1^R
^[1Getting object
Done
Ray.get large object time: 389.16783859199995 (107374182400 bytes)
[0m2022-11-28 19:40:21,746	INFO worker.py:1231 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-28 19:40:21,746	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.31.255.186:9031...
2022-11-28 19:40:21,755	INFO worker.py:1535 -- Connected to Ray cluster. View the dashboard at [1m[32mhttps://console.anyscale-staging.com/api/v2/sessions/ses_nefefi9qusrt4aqh38ygp84r/services?redirect_to=dashboard [39m[22m
Generating object
Putting object
Getting object
Done
Ray.get large object time: 387.7720168569999 (107374182400 bytes)
[0m2022-11-28 19:47:01,589	INFO worker.py:1231 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-28 19:47:01,590	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.31.255.186:9031...
2022-11-28 19:47:01,598	INFO worker.py:1535 -- Connected to Ray cluster. View the dashboard at [1m[32mhttps://console.anyscale-staging.com/api/v2/sessions/ses_nefefi9qusrt4aqh38ygp84r/services?redirect_to=dashboard [39m[22m
Generating object
Putting object
^R
^[1Getting object
Done
Ray.get large object time: 389.57854929799987 (107374182400 bytes)
[0m2022-11-28 19:53:44,016	INFO worker.py:1231 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-28 19:53:44,017	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.31.255.186:9031...
2022-11-28 19:53:44,025	INFO worker.py:1535 -- Connected to Ray cluster. View the dashboard at [1m[32mhttps://console.anyscale-staging.com/api/v2/sessions/ses_nefefi9qusrt4aqh38ygp84r/services?redirect_to=dashboard [39m[22m
Generating object
Putting object
Getting object
Done
Ray.get large object time: 388.24687943200024 (107374182400 bytes)
[0m2022-11-28 20:00:24,119	INFO worker.py:1231 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-28 20:00:24,119	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.31.255.186:9031...
2022-11-28 20:00:24,127	INFO worker.py:1535 -- Connected to Ray cluster. View the dashboard at [1m[32mhttps://console.anyscale-staging.com/api/v2/sessions/ses_nefefi9qusrt4aqh38ygp84r/services?redirect_to=dashboard [39m[22m
Generating object
Putting object
Getting object
Done
Ray.get large object time: 389.7650322059999 (107374182400 bytes)
[0m2022-11-28 20:07:06,806	INFO worker.py:1231 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-28 20:07:06,806	INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 172.31.255.186:9031...
2022-11-28 20:07:06,815	INFO worker.py:1535 -- Connected to Ray cluster. View the dashboard at [1m[32mhttps://console.anyscale-staging.com/api/v2/sessions/ses_nefefi9qusrt4aqh38ygp84r/services?redirect_to=dashboard [39m[22m
Generating object
Putting object
Getting object
Done
Ray.get large object time: 388.02584947500054 (107374182400 bytes)
[0m
```

I'll check on 2.0 and see if the variance is similar.

**Comment by stephanie-wang** [comment] 2022-11-30 19:00
Seems the results are similar from 2.0. I think it's worthwhile to look into the variance and see if we can either incorporate it into the result reporting and/or fix it completely, but probably not a p0 right now.

**Comment by rkooo567** [comment] 2023-01-23 22:51
WE need to at least investigate this before 2.3

**Comment by cadedaniel** [comment] 2023-01-25 22:06
@rickyyx do you have time to investigate this?

**Comment by rickyyx** [comment] 2023-01-25 22:28
Not yet.

**Comment by cadedaniel** [comment] 2023-01-27 02:59
The variation is very likely caused by EBS burst reads/writes. The 128GB object store configuration is much larger than our release test infra provides to docker by default, so the object store actually uses disk instead of shared memory. In our current release infra, the disk is backed by EBS, so it's actually a network-backed disk.

I validated this hypothesis by spinning up the same instance and running a docker container with 128GB of shared memory (`--shm-size=128GB`). The results are:
```
Generating object
Putting object
Getting object
Duration: 36.43 s for 107374182400 bytes
Duration for put: 36.00 s for 107374182400 bytes
Duration for get: 0.43 s for 107374182400 bytes
```

When omitting this docker config, the results are:
```
Generating object
Putting object
Getting object
Duration: 321.73 s for 107374182400 bytes
Duration for put: 321.11 s for 107374182400 bytes
Duration for get: 0.62 s for 107374182400 bytes
```

We should configure this test so that it uses shared-memory instead of disk for the object store!

**Comment by cadedaniel** [comment] 2023-01-27 02:59
Removing release blocker tag since this is likely EBS

**Comment by scv119** [comment] 2023-01-27 03:00
Nice!

**Comment by rkooo567** [comment] 2023-01-27 03:01
nice that explains the random regression. Let's use a different instance for this test after the release.

Additoinal question. This seems like a potential performance gotcha. Is there any way to raise a warning message when something similar happens (using disk instead of shm)?

**Comment by cadedaniel** [comment] 2023-01-27 04:23
> Nice! that explains the random regression. Let's use a different instance for this test after the release.
> 
> Additoinal question. This seems like a potential performance gotcha. Is there any way to raise a warning message when something similar happens (using disk instead of shm)?

++ to changing instance, but more cost effective to change the docker shm size. I think it should be an anyscale feature request. 

Yeah, there is a message already thrown by Ray. But I think we should crash in our CI if this happens in benchmarking?

> Also additional question; when you say "disk is used", it doesn't mean spill happens right? It means the shared memory is not enough, so object store uses the volume directly attached to the instance?

Yes that's right. No spilling occurs (which was what was confusing, because something was writing 300MB/s). Ray is just using a disk file mapped into memory for the object store.

**Comment by rkooo567** [comment] 2023-01-30 22:17
Follow up: Create an issue to ansycale to change this config (seems to be a common gotach from prod)

**Comment by cadedaniel** [comment] 2023-01-30 23:17
Blocked by https://github.com/anyscale/product/issues/17031. This might be fixed in v2 infra, waiting for response. Otherwise we can work around by running it on a very large instance? not sure but maybe

**Comment by rkooo567** [comment] 2023-02-20 08:15
This issue seems to be fixed in the V2 stack. Let's make sure to verify after migration is done @cadedaniel

**Closed** 2023-03-13 21:31 UTC
Labels: bug, P1, core, Devprod, Ray 2.5
