### ISSUE TITLE
[core][datasets] Worker raylets OOM when using smaller machines and default object store memory

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#24176] opened 2022-04-25 15:55 UTC
### What happened + What you expected to happen

Currently the datasets_shuffle_* nightly tests use 32-vCPU large machines and limit the object store memory to only a fraction of the available RAM. This means that we're probably underutilizing the machines and it's not very representative to a real setup either. Previous attempts to use smaller instance types / larger object store memory cause worker raylet OOMs, such as in datasets_shuffle_random_shuffle_1tb.

[Here's](https://gist.github.com/stephanie-wang/a3cefd0c11327760e097618386cdcd54) some example output from `dmesg` on a worker raylet.

### Versions / Dependencies

2.0dev

### Reproduction script

datasets_shuffle_* nightly tests, and changing the instance type in the cluster config.

**Comment by stephanie-wang** [comment] 2022-04-26 19:20
A few odd things from the above dmesg output that we should look into, looking at the RSS column (multiply by 4096 to get # bytes):
- raylet memory usage is very high. anon-rss (so not including shared memory) at time of OOM is ~7GB.
- reduce tasks should be reading and writing 1GB partitions, but table shows rss is sometimes more than 10GB. Even including inputs/outputs in shared memory, this seems pretty high for heap memory usage (8x).
- unclear if I/O worker memory usage is as expected since there is no standard spill size

**Comment by mwtian** [comment] 2022-04-26 23:03
I did not reproduce worker OOM yet, but managed to cause head raylet to exit unexpectedly with `m5.2xlarge` instances. We should first change the `dataset_shuffle_*` tests to use a smaller instance type like `m5.4xlarge`, and see if the tests can pass continuously. I'm investigating the head raylet issue with `m5.2xlarge` instances in parallel.

**Comment by mwtian** [comment] 2022-05-02 17:50
Current status:
- https://github.com/ray-project/ray/pull/24322 should decrease driver Raylet memory usage significantly, based on profiling and testing.
- For worker Raylet memory usage, it is observed that the memory usage can grow significantly during the reduce stage. Memory profiling is a bit harder to interpret in this case. I'm still investigating the source of memory usages.
- Python worker memory usage can be usually high (4GB~6GB) even when idle. Investigation has not started on this yet.

**Comment by mwtian** [comment] 2022-05-05 04:50
[5a82640](https://github.com/ray-project/ray/commit/5a8264015b1bde67924f0a38f1d55b1280ead17d) should reduce driver raylet memory usage. For Python workers, it seems their RSS memory is mostly shared memory usage, e.g. a Python worker with 6.6GB RSS uses about 6.4GB shared memory.

**Comment by stephanie-wang** [comment] 2022-05-06 23:47
One note for users is that we can often (always?) work around this in Datasets by decreasing the partition size, at the cost of potentially higher system overhead.

**Comment by mwtian** [comment] 2022-05-10 00:05
I generated a Raylet memory profile for shuffling on a single node:
<img width="1818" alt="image" src="https://user-images.githubusercontent.com/81660174/167517062-513767cd-a760-4f50-a357-2e466d027dd0.png">

Raw data: [profile023.pb.gz](https://github.com/ray-project/ray/files/8656059/profile023.pb.gz)

There is significant memory usage under `ClusterTaskManager::QueueAndScheduleTask()`, which is consistent with high worker Raylet memory usage.

**Comment by stephanie-wang** [comment] 2022-05-10 00:12
> I generated a Raylet memory profile for shuffling on a single node: <img alt="image" width="1818" src="https://user-images.githubusercontent.com/81660174/167517062-513767cd-a760-4f50-a357-2e466d027dd0.png">
> 
> Raw data: [profile023.pb.gz](https://github.com/ray-project/ray/files/8656059/profile023.pb.gz)
> 
> There is significant memory usage under `ClusterTaskManager::QueueAndScheduleTask()`, which is consistent with high worker Raylet memory usage.

Nice find! I guess the next question is whether there is a memory scalability bug and whether there is any low-hanging performance fruit on the raylet side.

Since this is happening during the reduce phase, a quick fix would be limiting how many tasks we're sending to the raylet from the Datasets side (`ray.wait` on some results before submitting more tasks).

**Comment by mwtian** [comment] 2022-05-10 00:45
Great info. Another thing I'm trying to confirm is that if the task metadata is only for the 32 / 64 running tasks, or includes more past tasks. It is a bit hard to imagine that metadata from running tasks can balloon to a few GBs.

**Comment by stephanie-wang** [comment] 2022-05-10 00:50
Yeah, one thing here is that you're probably seeing the memory blow up because of queued tasks in addition to the running ones. But yes, we should confirm that there's no memory leak from the past tasks.

I agree, it's a bit odd that the memory footprint is so high. Compared to the driver metadata, each worker raylet is only handling a fraction of the ObjectRefs. The raylets do significantly more work for each ObjectRef, but still I would've expected the worker raylet memory usage to be comparable to driver memory.

**Comment by mwtian** [comment] 2022-05-10 01:10
Task queueing makes sense. I will try to set up profiling in product, and capture a profile for the case of 19 workers + 1 head node as well. That should give a more definite picture about the memory consumers.

**Comment by mwtian** [comment] 2022-05-11 17:48
Tried profiling memory usage of push-based shuffle, and the result is similar. Most memory usage seems to be due to metadata for arguments and objects.
<img width="1786" alt="image" src="https://user-images.githubusercontent.com/81660174/167910191-1a043782-2603-4107-ae7e-cb2810a5b393.png">

Raw data: [profile028.pb.gz](https://github.com/ray-project/ray/files/8672157/profile028.pb.gz)

Some of these metadata are:
- Per-object `LocationListenerState` in `OwnershipBasedObjectDirectory`
- Per-object `ObjectPullRequest` in `PullManager`
- Metadata in `LocalObjectManager`
- Per-object subscriber for eviction.
- Per-object subscriber for location change.

Trimming the size of one or two of these data types will not help reduce memory usage of Raylets significantly. My estimate is the each task arg / object ref dependency can use 3~4KB in memory. Brainstorming some ideas for next steps:

1. Add instrumentation to periodically dump `DependencyManager` stats, so we have an idea of metadata cost when a worker OOMs.
2. Merging Ray pub/sub channels for object refs from 3 to 1 should reduce the memory cost.
3. Using a single data structure to manage object refs in Ray can also reduce metadata memory cost, but significant refactoring is needed.
4. It may be possible to delay resolving task dependencies, if there are queued tasks that are ready to run and already a large number of objects in the dependency manager.
5. Raylet memory usage can be taken into account during scheduling.
6. During shuffle, the driver can limit the number of tasks queued at each node, e.g. `ray.wait()` for tasks to finish before queueing more tasks.

**Comment by mwtian** [comment] 2022-06-09 22:42
With changes to limit the number of pending tasks, Raylet OOM is less common. Closing the issue.

**Closed by mwtian** 2022-06-09 22:42 UTC
Labels: bug, P1
