### ISSUE TITLE
Ray worker dies or gets killed when importing separate protobuf definition

### ISSUE THREAD

**Issue by rbrigden** [ray-project/ray#2391] opened 2018-07-11 23:35 UTC
## System information
OS Platform and Distribution: Linux Ubuntu 16.04
Ray installed from (source or binary): binary
Ray version: 0.5.0
Python version: Python 2.7
Exact command to reproduce: n/a

## Describe the problem 

I am currently working on setting up a cluster job with Ray that interfaces with an application on each node through protobuf2 messages. Peculiarly, any remote worker that invokes a generated python proto template is killed without an error message other than:

`The worker with ID x died or was killed while executing the task with ID y`

where x is the worker id and y is the task id. I understand that pyarrow uses protobuf and I wonder if there is some interaction here. Any help is much appreciated.

**Comment by robertnishihara** [comment] 2018-07-12 03:42
Thanks for reporting this, can you try importing and starting ray and then running the remote function code locally (instead of in a worker), and see if it segfaults or what happens?

If it crashes, could you then repeat the same thing in gdb and post the backtrace?

**Comment by rbrigden** [comment] 2018-07-12 20:43
Thanks for getting back to me so quickly. It doesn't seem to segfault locally or on a worker, but there is some unexpected behavior. Even tho I am only trying to launch one task, it spews out many `The worker with ID x died or was killed while executing the task with ID y` messages at a regular interval. Here is a sample (please ignore the ROS warning messages).

```
he rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
The worker with ID 874e893794f040c8560e2ac3b44c6b10f29f64c4 died or was killed while executing the task with ID ddb38f8a9e16e4178fb82395b943dee183a48415
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
The worker with ID 56051700f4332468bd1933e5956e03560f4d95ec died or was killed while executing the task with ID c4192000b91f4cb1ef4c2e8e01d1f4c3bf9e1fdc
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
The worker with ID 13bb3ab08354f70e36187cb96e362b60e12b4689 died or was killed while executing the task with ID ddb38f8a9e16e4178fb82395b943dee183a48415
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
The worker with ID e464812675c3611d3c183a9e23595f9728345657 died or was killed while executing the task with ID c4192000b91f4cb1ef4c2e8e01d1f4c3bf9e1fdc
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
The worker with ID 84545f211de1370d5f983c435351a8677b65f211 died or was killed while executing the task with ID ddb38f8a9e16e4178fb82395b943dee183a48415
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
The worker with ID 1276f0dc0b06a8d83cec7391c0b862014d3a4f9b died or was killed while executing the task with ID c4192000b91f4cb1ef4c2e8e01d1f4c3bf9e1fdc
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
The worker with ID 9e3967b1b79aa3b4b6a00939c3aa152ca59e2089 died or was killed while executing the task with ID ddb38f8a9e16e4178fb82395b943dee183a48415
```

Because the issue doesn't cause the main thread to terminate, I couldn't do any kind of backtrace. Any other things I can try to run to diagnose?

**Comment by robertnishihara** [comment] 2018-07-12 21:10
Can you share a minimal example that reproduces the issue?

Also, what happens when you run the function locally (not in a task)? What kind of unexpected behavior do you see?

**Comment by rbrigden** [comment] 2018-07-12 21:50
So unfortunately there is no very short example, it would require access to protobuf definitions that I cannot share, although they are fairly standard. Here is something that you won't be able to run on your end, but I hope it may shed some light. 

```python
import ray
import time
from myprotobuflib import bar_pb2  # standard generated python proto module

@ray.remote
def f():
    x = bar_pb2.Foo # this is where something bad happens, without this things work fine
    while True:
        print("I'm alive")
        time.sleep(1)

ray.init()
p = f.remote()
ray.wait([p])   
```


When I run this, I get the following output
```
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:36486 to respond...
Waiting for redis server at 127.0.0.1:45516 to respond...
Warning: Reducing object store memory because /dev/shm has only 2147483648 bytes available. You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
Starting local scheduler with the following resources: {'GPU': 1, 'CPU': 6}.
Failed to start the UI, you may need to run 'pip install jupyter'.
The worker with ID 5daefeb317fd7beb753e18671228a7c9c58077d3 died or was killed while executing the task with ID f754c4e0b2c6cf53dcfd0a17b92790e923d32131
```
Then it hangs with no more output. I send a keyboard interrupt and then I get this output

```
^CTraceback (most recent call last):
  File "reproduce.py", line 20, in <module>
    ray.wait([p])
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 2879, in wait
    object_id_strs, timeout, num_returns)
  File "pyarrow/_plasma.pyx", line 590, in pyarrow._plasma.PlasmaClient.wait
  File "pyarrow/error.pxi", line 79, in pyarrow.lib.check_status
  File "/usr/local/lib/python2.7/dist-packages/ray/pyarrow_files/pyarrow/compat.py", line 104, in frombytes
    def frombytes(o):
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 1781, in cleanup
    {"end_time": time.time()})
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2011, in hmset
    return self.execute_command('HMSET', name, *items)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to 10.0.0.108:36486. Connection refused.
Error in sys.exitfunc:
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 1807, in custom_excepthook
    {"exception": error_message})
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2011, in hmset
    return self.execute_command('HMSET', name, *items)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 10.0.0.108:36486. Connection refused.

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/ray/worker.py", line 1781, in cleanup
    {"end_time": time.time()})
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2011, in hmset
    return self.execute_command('HMSET', name, *items)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 10.0.0.108:36486. Connection refused.
```

**Comment by rbrigden** [comment] 2018-07-13 17:56
I am using Pytorch 0.4.0 and it turns out that this error completely resolves when I uninstall Pytorch.

**Comment by rbrigden** [comment] 2018-07-16 16:50
Do you have an idea for why this might be the case? That importing PyTorch 0.4.0 along with separate protobuf definitions might cause Ray tasks/workers to be killed or die.

**Comment by pcmoritz** [comment] 2018-07-18 19:59
Can you check dmesg for segfaults? It looks like one of the workers is dying, probably from a segfault.

**Comment by robertnishihara** [comment] 2018-08-22 20:30
I'm closing this for now since we don't know how to reproduce it. If any new information arises, please feel free to reopen the issue!

**Closed by robertnishihara** 2018-08-22 20:30 UTC
