### ISSUE TITLE
[core] many_nodes_actor_test_on_v2 perf regression

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#37061] opened 2023-07-03 22:26 UTC
### What happened + What you expected to happen

there is performance regression for many_nodes_actor_test_on_v2, @cadedaniel can you investigate?

### Versions / Dependencies

latest

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by cadedaniel** [comment] 2023-07-05 20:25
Could be variation

<img width="1930" alt="Screen Shot 2023-07-05 at 1 23 55 PM" src="https://github.com/ray-project/ray/assets/950914/56a8e7c5-2d25-4c9e-aebd-721e9ff1ed7b">

**Comment by cadedaniel** [comment] 2023-07-05 22:12
Closing since it seems normal variation

**Comment by scv119** [comment] 2023-07-24 20:01
<img width="509" alt="image" src="https://github.com/ray-project/ray/assets/837180/eeed03a3-6f78-41cf-a5f0-b212f9489a69">

**Comment by scv119** [comment] 2023-07-24 20:56
https://console.anyscale-staging.com/o/anyscale-internal/configurations/app-config-details/bld_7v4b9yij782xvald2anrfyku3s

latest run reveals the metrics is flaky.

**Comment by jjyao** [comment] 2024-02-20 18:59
No longer regression.

**Closed by jjyao** 2024-02-20 18:59 UTC
Labels: bug, P1, core
