### ISSUE TITLE
Ray Dashboard not rendering

### ISSUE THREAD

**Issue by SheldonCurtiss** [ray-project/ray#16781] opened 2021-06-30 17:03 UTC
### What is the problem?
Upon installing cuda I now see a white screen and get the following error in the console for the ray dashboard
Issue wasn't present pre installing gpu requirements???

![image](https://user-images.githubusercontent.com/78921582/124002201-732a9800-d9a3-11eb-9025-fbebe7c3851c.png)

Using WSL
Python39
Ubuntu LTS 18
Latest Ray

### Reproduction (REQUIRED)
Using lunarlander demo.

**Comment by mattip** [comment] 2022-04-28 06:06
Where is the code for the lunarlander demo you tried? How exactly did you set this up: the entire demo is running inside WSL together with CUDA installed into WSL or some other variant? Which version of CUDA are you using?

It would be helpful if you could provide the exact commands you used to create the environment and run the ray instance.

**Comment by mattip** [comment] 2022-04-28 06:12
I ask because the failure is due to a failure to get the gpu usage statistics, so somewhere between WSL, windows, and the way ray is probing the statistics, there is a problem. The lunarlander demo is not really involved, the question is more how you are starting the ray instance and the dashboard.

**Comment by mattip** [comment] 2022-04-28 06:46
Could you report what this prints (please check the output for sensitive personal data):
```python
>>> import pprint
>>> import dashboard.modules.reporter.reporter_agent as agent
>>> data = agent.ReporterAgent._get_gpu_usage()
>>> data.pop['processes']
>>> ignore = [d.pop('processes') for d in data]
>>> pprint(data)
```

Maybe something in the data collection is off? For me, with my tiny graphics card, this prints
```
[{'enforced_power_limit': 125,
  'fan_speed': 52,
  'index': 0,
  'memory_total': 5941,
  'memory_used': 1281,
  'name': 'GeForce GTX 1660 SUPER',
  'power_draw': 52,
  'temperature_gpu': 72,
  'utilization_dec': 0,
  'utilization_enc': 0,
  'utilization_gpu': 40,
  'uuid': 'GPU-e140fccf-3143-3561-8170-4a053e621422'}]
```

The [api](https://github.com/ray-project/ray/blob/629424f48957af55cf06d86d23b850be73fb3017/dashboard/client/src/api.ts#L97) wants exactly this structure (with the extra `processes` field the code above filters out).

**Comment by mattip** [comment] 2022-05-03 14:17
Still waiting to hear how to reproduce your setup for your head and worker nodes:
- which of them were on WSL and which on windows?
- how did you install CUDA on the WSL machine: via a nvidia docker? Directly in the WSL environment?

**Comment by mattip** [comment] 2022-05-04 06:59
I opened an issue in gpustat https://github.com/wookayin/gpustat/issues/121 about a failure to gather info.

**Comment by mattip** [comment] 2022-05-31 14:19
The gpustat issue was fixed, but has not yet been released. @SheldonCurtiss could you try after installing the latest HEAD of gpustat:
```
pip install git+https://github.com/wookayin/gpustat@master
```

**Comment by mattip** [comment] 2022-07-04 07:15
On the one hand I am the only commenter in this issue, the OP has not responded, so I am inclined to close it. On the other, there is a known problem with gpustat and the maintainer has not released a new version in over a year. Should we vendor the project into ray to get the latest HEAD?

**Comment by mattip** [comment] 2022-07-05 07:58
gpustat has released a [new rc1 version](https://pypi.org/project/gpustat/1.0.0rc1/) @SheldonCurtiss could you see if this fixes the problem?

**Comment by scottsun94** [comment] 2022-10-07 01:38
Let's close this one for now? @mattip 
Please open a new issues or let us know if this issue still exists. @SheldonCurtiss

**Comment by mattip** [comment] 2022-10-07 06:35
Since @SheldonCurtiss has not responded, I think we have no choice other than to close this.

**Comment by scottsun94** [comment] 2022-10-07 17:02
SG. Closing it for now.

**Closed by scottsun94** 2022-10-07 17:02 UTC
Labels: bug, needs-repro-script, P2, dashboard, QS
