### ISSUE TITLE
[install] Could not find a version that satisfies the requirement ray (from versions: none)

### ISSUE THREAD

**Issue by xiezhipeng-git** [ray-project/ray#33524] opened 2023-03-21 16:09 UTC
### What happened + What you expected to happen

python 3.11.2
windows 11
pip install ray
Could not find a version that satisfies the requirement ray (from versions: none)
https://pypi.org/project/ray/#files
It is no windows python 3.11

### Versions / Dependencies

ray 

### Reproduction script

pip install

### Issue Severity

High: It blocks me from completing my task.

**Comment by rickyyx** [comment] 2023-03-24 21:12
Hey @xiezhipeng-git we don't have windows wheels for python 3.11 yet, while it's WIP: https://github.com/ray-project/ray/issues/31362

**Comment by rickyyx** [comment] 2023-03-24 21:13
Closing this since it's a duplicate of https://github.com/ray-project/ray/issues/31362

**Closed by rickyyx** 2023-03-24 21:13 UTC
Labels: bug, core
