### ISSUE TITLE
[tune] logger customised config 

### ISSUE THREAD

**Issue by hcch0912** [ray-project/ray#11464] opened 2020-10-19 12:50 UTC
### Allow Users to customise config for Loggers

Currently, we need to pass a List of Logger Classes to the ray.tune.run(), sometimes we want to give some customised configs to our customised logger classes, and it's not feasible in the current version. 

If we can pass instances of loggers to run() instead of classes it would be great.

**Comment by richardliaw** [comment] 2020-10-19 18:39
@hcch0912 thanks for posting this issue! This is a duplicate of https://github.com/ray-project/ray/issues/10612. Closing this to track implementation in one issue.

**Closed by richardliaw** 2020-10-19 18:39 UTC
Labels: enhancement, triage
