### ISSUE TITLE
[Client] Training with a large model (size>2GB) with Ray Client leads to Ray stuck forever

### ISSUE THREAD

**Issue by xinchen384** [ray-project/ray#20869] opened 2021-12-03 04:26 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Train

### What happened + What you expected to happen

1. The bug. 
In our application, we need to construct a large Pytorch model. (size >> 2GB). 
When doing the training, ray gets stuck forever with the large model. The terminal does not show anything.

2. Expected behavior
We expect that it can be slow. It should finish running no matter how long it takes.

3. Useful infomation
We tried running in local mode, or directly connect to ray cluster using "6379 port"/"auto". 
Both work fine. However, in our application, we have to run the training in a client way, with "ray://head_IP:10001", as shown in the reproduction script. 
This way results in the problem here. 

4. Logs.
In the worker's log, it is the following:
core_worker.cc:2898: Force kill actor request has received. exiting immediately...

ERROR:grpc._common:Exception serializing message!
Traceback (most recent call last):
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/grpc/_common.py", line 86, in _transform
    return transformer(message)
ValueError: Message ray.rpc.DataResponse exceeds maximum protobuf size of 2GB: 4096129280

### Versions / Dependencies

Tried ray = 1.6.0 and ray = 1.9.0. They give the same results
The ray version does not change anything.

### Reproduction script
    
    import ray
    from ray.util.sgd import TorchTrainer
    from ray.util.sgd.torch import TrainingOperator
    
    import torch
    from torch.utils.data import DataLoader
    import numpy as np
    
    row, col = 32000, 32000
    num_sample = 4 
    
    class CustomDataset(torch.utils.data.Dataset):
    
        def __init__(self, size=1000):
            x = np.random.rand(num_sample, row).astype('float32')
            s = np.random.rand(row, col).astype('float32')
            self.x = torch.from_numpy(x)
            self.y = torch.from_numpy(np.matmul(x, s))
            #print("XIN:", self.x[0, None].type(), self.y[0, None].type())
    
        def __getitem__(self, index):
            return self.x[index, None], self.y[index, None]
    
        def __len__(self):
            return len(self.x)
    
    class CustomTrainingOperator(TrainingOperator):
    
        def setup(self, config):
            # Load data.
            train_loader = DataLoader(CustomDataset(), 64)
            val_loader = DataLoader(CustomDataset(), 64)
    
            model = torch.nn.Linear(row, col) 
    
            # Create optimizer.
            optimizer = torch.optim.SGD(model.parameters(), lr=1e-2)
    
            # Create loss.
            loss = torch.nn.MSELoss()
    
            # Register model, optimizer, and loss.
            self.model, self.optimizer, self.criterion = self.register(
                models=model,
                optimizers=optimizer,
                criterion=loss)
    
            # Register data loaders.
            self.register_data(train_loader=train_loader, validation_loader=val_loader)
    
    ray_head = "ray://10.128.115.12:10001" 
    ray.init(address=ray_head)
    #ray.init(address="auto")
    
    trainer1 = TorchTrainer(
        training_operator_cls=CustomTrainingOperator,
        num_workers=1,
        use_gpu=False,
        config={})
    
    stats = trainer1.train()
    print(stats)
    trainer1.shutdown()
    print("success!")

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by HuangLED** [comment] 2021-12-03 17:11
@amogkam @richardliaw

**Comment by mwtian** [comment] 2021-12-03 17:33
Thanks for the detailed report and reproduction script. Ray probably should emit a better error message instead of hanging here. From the error log the script was running into the client object / protobuf size limit in https://github.com/ray-project/ray/issues/18378,  cc @ckw017

**Comment by amogkam** [comment] 2021-12-03 18:02
@xinchen384 Is there a longer stack trace on where exactly in ray sgd this is happening?

**Comment by amogkam** [comment] 2021-12-03 18:06
One quick fix would be to just wrap everything in a ray task.

**Comment by xinchen384** [comment] 2021-12-03 18:54
@amogkam >Is there a longer stack trace on where exactly in ray sgd this is happening?
No. In the terminal, nothing shows up. The log is the thing I copied from /tmp/ray/session_latest/logs.

INFO:ray.util.client.server.server:Starting Ray Client server on 0.0.0.0:10001
INFO:ray.util.client.server.proxier:New data connection from client 6b18bfbeffc44e888fa3e24dd7bec455: 
INFO:ray.util.client.server.proxier:SpecificServer started on port: 23000 with PID: 1294627 for client: 6b18bfbeffc44e888fa3e24dd7bec455
INFO:ray.util.client.server.proxier:6b18bfbeffc44e888fa3e24dd7bec455 last started stream at 1638557451.2066822. Current stream started at 1638557451.2066822.
ERROR:ray.util.client.server.proxier:Proxying call to WaitObject failed!
Traceback (most recent call last):
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/ray/util/client/server/proxier.py", line 402, in _call_inner_function
    return getattr(stub, method)(request, metadata=metadata)
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1638557518.934509401","description":"Error received from peer ipv4:127.0.0.1:23000","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"Socket closed","grpc_status":14}"
>
ERROR:grpc._common:Exception serializing message!
Traceback (most recent call last):
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/grpc/_common.py", line 86, in _transform
    return transformer(message)
TypeError: descriptor 'SerializeToString' requires a 'google.protobuf.pyext._message.CMessage' object but received a 'NoneType'

This log comes from "ray_client_server.err".

**Comment by xinchen384** [comment] 2021-12-03 18:59
@amogkam > One quick fix would be to just wrap everything in a ray task.
The reproduction code is something we directly copied from the SGD example here, https://docs.ray.io/en/latest/raysgd/raysgd.html. The only change we made is on the size of the model. I am not clear on how to wrap this example in a ray task.

BTW, we just tried the SGD v2, and it behaves exactly the same.

**Comment by amogkam** [comment] 2021-12-03 19:28
@xinchen384 so the log you shared in the second comment is different than the one you shared in the original post.

```
ERROR:grpc._common:Exception serializing message!
Traceback (most recent call last):
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/grpc/_common.py", line 86, in _transform
    return transformer(message)
ValueError: Message ray.rpc.DataResponse exceeds maximum protobuf size of 2GB: 4096129280
```

```
ERROR:grpc._common:Exception serializing message!
Traceback (most recent call last):
File "/opt/conda/envs/py37/lib/python3.7/site-packages/grpc/_common.py", line 86, in _transform
return transformer(message)
TypeError: descriptor 'SerializeToString' requires a 'google.protobuf.pyext._message.CMessage' object but received a 'NoneType'
```

**Comment by amogkam** [comment] 2021-12-03 22:00
Ah ok so this is the line that is attempting to deserialize the model state dict on the driver: https://github.com/ray-project/ray/blob/master/python/ray/util/sgd/torch/torch_trainer.py#L448.

Unfortunately the 2GB limit is a limitation of Ray Client. You can either not use Ray Client altogether, or wrap the main code in a Ray task like so (which is equivalent to not using Ray Client):

```
ray_head = "ray://10.128.115.12:10001" 
ray.init(address=ray_head)
#ray.init(address="auto")

@ray.remote
def train_driver():
    trainer1 = TorchTrainer(
        training_operator_cls=CustomTrainingOperator,
        num_workers=1,
        use_gpu=False,
        config={})
    
    stats = trainer1.train()
    print(stats)
    trainer1.shutdown()
    print("success!")

return ray.get(train_driver.remote())
```

**Comment by amogkam** [comment] 2021-12-03 22:01
As @mwtian mentioned, the issue is the same as https://github.com/ray-project/ray/issues/18378 and we should raise a better error message here. 

I am going to close this for now as a duplicate of https://github.com/ray-project/ray/issues/18378, but please feel free to reopen if the workaround does not work for you.

**Closed by amogkam** 2021-12-03 22:01 UTC
Labels: bug, triage
