### ISSUE TITLE
Check failure in ray::raylet::NodeManager::HandleObjectMissing

### ISSUE THREAD

**Issue by zplizzi** [ray-project/ray#6189] opened 2019-11-19 02:50 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.4
- **Python version**: 3.6.4
- **Exact command to reproduce**: can't consistently reproduce

I get the following errors sometimes when running a hyperparameter tuning experiment with Tune. I'm tuning a RL algorithm (which uses parts of RLlib also, such as nested actors for environment rollouts). I've never seen this issue when running the training directly (not through Tune).

Here's the contents of `/tmp/ray` on the head node: [ray_logs.zip](https://github.com/ray-project/ray/files/3861680/ray_logs.zip)
Let me know what other info I can provide to debug.

```
(pid=271, ip=192.168.80.248) Traceback (most recent call last):
(pid=271, ip=192.168.80.248)   File "/usr/local/lib/python3.6/dist-packages/ray/workers/default_worker.py", line 98, in <module>
(pid=271, ip=192.168.80.248)     ray.worker.global_worker.main_loop()
(pid=271, ip=192.168.80.248)   File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1134, in main_loop
(pid=271, ip=192.168.80.248)     task = self._get_next_task_from_raylet()
(pid=271, ip=192.168.80.248)   File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1117, in _get_next_task_from_raylet
(pid=271, ip=192.168.80.248)     task = self.raylet_client.get_task()
(pid=271, ip=192.168.80.248)   File "python/ray/_raylet.pyx", line 247, in ray._raylet.RayletClient.get_task
(pid=271, ip=192.168.80.248)   File "python/ray/_raylet.pyx", line 61, in ray._raylet.check_status
(pid=271, ip=192.168.80.248) ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Raylet connection closed.
(pid=271, ip=192.168.80.248)
(pid=271, ip=192.168.80.248) During handling of the above exception, another exception occurred:
(pid=271, ip=192.168.80.248)
(pid=271, ip=192.168.80.248) Traceback (most recent call last):
(pid=271, ip=192.168.80.248)   File "/usr/local/lib/python3.6/dist-packages/ray/workers/default_worker.py", line 105, in <module>
(pid=271, ip=192.168.80.248)     job_id=None)
(pid=271, ip=192.168.80.248)   File "/usr/local/lib/python3.6/dist-packages/ray/utils.py", line 68, in push_error_to_driver
(pid=271, ip=192.168.80.248)     worker.raylet_client.push_error(job_id, error_type, message, time.time())
(pid=271, ip=192.168.80.248)   File "python/ray/_raylet.pyx", line 300, in ray._raylet.RayletClient.push_error
(pid=271, ip=192.168.80.248)   File "python/ray/_raylet.pyx", line 61, in ray._raylet.check_status
(pid=271, ip=192.168.80.248) ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Connection closed unexpectedly.
2019-11-19 02:31:15,861 ERROR worker.py:1791 -- The node with client ID 5308993854613ba26e1b2a1128a1d616538ff531 has been marked dead because the monitor has missed too many heartbeats from it.
2019-11-19 02:31:17,558 ERROR worker.py:1791 -- The node with client ID f6d51b8c28f60765ea6ddb54bf1d1acbd675890f has been marked dead because the monitor has missed too many heartbeats from it.
2019-11-19 02:31:30,706 ERROR trial_runner.py:552 -- Error processing event.
```

and 
```
(pid=raylet, ip=192.168.66.223) F1119 02:31:03.937857    17 scheduling_queue.cc:318]  Check failed: task_ids.empty()
(pid=raylet, ip=192.168.66.223) *** Check failure stack trace: ***
(pid=raylet, ip=192.168.66.223)     @           0x6f6e3a  google::LogMessage::Fail()
(pid=raylet, ip=192.168.66.223)     @           0x6f8223  google::LogMessage::SendToLog()
(pid=raylet, ip=192.168.66.223)     @           0x6f6b62  google::LogMessage::Flush()
(pid=raylet, ip=192.168.66.223)     @           0x6f6d51  google::LogMessage::~LogMessage()
(pid=raylet, ip=192.168.66.223)     @           0x5293a2  ray::RayLog::~RayLog()
(pid=raylet, ip=192.168.66.223)     @           0x46d659  ray::raylet::SchedulingQueue::MoveTasks()
(pid=raylet, ip=192.168.66.223)     @           0x4608cc  ray::raylet::NodeManager::HandleObjectMissing()
(pid=raylet, ip=192.168.66.223)     @           0x49cdc0  ray::ObjectStoreNotificationManager::ProcessStoreRemove()
(pid=raylet, ip=192.168.66.223)     @           0x49e666  ray::ObjectStoreNotificationManager::ProcessStoreNotification()
(pid=raylet, ip=192.168.66.223)     @           0x49db1a  boost::asio::detail::read_op<>::operator()()
(pid=raylet, ip=192.168.66.223)     @           0x49dd12  boost::asio::detail::reactive_socket_recv_op<>::do_complete()
(pid=raylet, ip=192.168.66.223)     @           0x425bdd  boost::asio::detail::scheduler::run()
(pid=raylet, ip=192.168.66.223)     @           0x40fb20  main
(pid=raylet, ip=192.168.66.223)     @     0x7fe34f6b4b97  __libc_start_main
(pid=raylet, ip=192.168.66.223)     @           0x4207f1  (unknown)
```

**Comment by arunavo4** [comment] 2019-11-20 02:24
@zplizzi I wanted to ask if your Wifi / Ethernet connection was turned off or you happened to change the Connection somehow? This could have occurred. Last night I had the same issue, as soon as I turned off the Wifi this crash occurred, since the IP address of the node is the one assigned by the router, it crashes.

**Comment by arunavo4** [comment] 2019-11-20 02:27
Let me know if you can reproduce it by turning off your Wifi / Ethernet.

**Comment by zplizzi** [comment] 2019-11-20 02:30
The whole cluster is in AWS, so the internet connection between nodes
should presumably be rock solid.

**Comment by richardliaw** [comment] 2019-11-20 06:19
Can you try using the latest nightly build? https://ray.readthedocs.io/en/latest/installation.html

**Comment by zplizzi** [comment] 2019-11-21 02:21
It's not quickly or reliably reproducible, but I'll try the latest nightly next time I'm doing a few of these larger tuning runs - probably within the next week or two.

**Comment by jkerfs** [comment] 2019-11-21 06:57
I get the exact same error and tried the nightly (0.8.0.dev6) without success.

**Comment by ericl** [comment] 2019-11-21 20:12
It looks like somehow there is an internal inconsistency tracking the set of tasks that are in the WAITING state. I don't think this is a recent regression (perhaps @stephanie-wang can confirm), so perhaps it shouldn't block the release.

Fortunately / unfortunately we're migrating Ray away from this code path. If you're feeling adventurous, you can try the env var `RAY_FORCE_DIRECT=1` to try out the direct gRPC based actors. Note that you really need the very latest wheels for this to have any chance of working though :)

Otherwise, a script that can be run without external dependencies (i.e., training some dummy model or dummy env) would be needed for tracking the issue down, it would be very hard to debug otherwise.

**Comment by ericl** [comment] 2019-11-21 20:13
By the way, can this error be reproduced with a single Ray node cluster?

**Comment by jkerfs** [comment] 2019-11-22 02:28
I'lll try to get a reproducible example.  I was able to avoid the issue by reducing the number of tasks from ~100,000 to ~1,000.  With the large number of tasks it would happen every time, but with only 1000 tasks I never encountered it.

**Comment by edoakes** [comment] 2020-02-06 22:44
No reproducible error. We saw some issues like this in the release tests but resolved them, so closing for now. Feel free to re-open if the problem persists.

**Closed by edoakes** 2020-02-06 22:44 UTC
Labels: bug
