### ISSUE TITLE
[CI] linux://python/ray/tune:test_progress_reporter is failing/flaky on master.

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#29768] opened 2022-10-27 18:27 UTC
<img width="887" alt="Screen Shot 2022-10-27 at 11 26 51 AM" src="https://user-images.githubusercontent.com/950914/198369659-4dcd0693-d54b-48db-bdf6-396b5da21830.png">

```
=================================== FAILURES ===================================
--
  | __________________ ProgressReporterTest.testVerboseReporting ___________________
  |  
  | self = <python.ray.tune.tests.test_progress_reporter.ProgressReporterTest testMethod=testVerboseReporting>
  |  
  | def testVerboseReporting(self):
  | try:
  | os.environ["_TEST_TUNE_TRIAL_UUID"] = "xxxxx"
  |  
  | verbose_0_cmd = VERBOSE_CMD + "verbose=0)"
  | output = run_string_as_driver(verbose_0_cmd)
  | try:
  | self.assertNotIn(VERBOSE_EXP_OUT_1, output)
  | self.assertNotIn(VERBOSE_EXP_OUT_2, output)
  | self.assertNotIn(VERBOSE_TRIAL_NORM_1, output)
  | self.assertNotIn(VERBOSE_TRIAL_NORM_2, output)
  | self.assertNotIn(VERBOSE_TRIAL_NORM_3, output)
  | self.assertNotIn(VERBOSE_TRIAL_NORM_4, output)
  | self.assertNotIn(VERBOSE_TRIAL_DETAIL, output)
  | except Exception:
  | print("*** BEGIN OUTPUT ***")
  | print(output)
  | print("*** END OUTPUT ***")
  | raise
  |  
  | verbose_1_cmd = VERBOSE_CMD + "verbose=1)"
  | output = run_string_as_driver(verbose_1_cmd)
  | try:
  | self.assertIn(VERBOSE_EXP_OUT_1, output)
  | self.assertIn(VERBOSE_EXP_OUT_2, output)
  | self.assertNotIn(VERBOSE_TRIAL_NORM_1, output)
  | self.assertNotIn(VERBOSE_TRIAL_NORM_2, output)
  | self.assertNotIn(VERBOSE_TRIAL_NORM_3, output)
  | self.assertNotIn(VERBOSE_TRIAL_NORM_4, output)
  | self.assertNotIn(VERBOSE_TRIAL_DETAIL, output)
  | except Exception:
  | print("*** BEGIN OUTPUT ***")
  | print(output)
  | print("*** END OUTPUT ***")
  | raise
  |  
  | verbose_2_cmd = VERBOSE_CMD + "verbose=2)"
  | output = run_string_as_driver(verbose_2_cmd)
  | try:
  | self.assertIn(VERBOSE_EXP_OUT_1, output)
  | self.assertIn(VERBOSE_EXP_OUT_2, output)
  | self.assertIn(VERBOSE_TRIAL_NORM_1, output)
  | >               self.assertIn(VERBOSE_TRIAL_NORM_2, output)
  | E               AssertionError: "\nTrial train_xxxxx_00001 reported _metric=6 with parameters={'do': 'once'}.\nTrial train_xxxxx_00001 completed. Last result: _metric=6\n" not found in "2022-10-26 01:32:45,785\tINFO worker.py:1524 -- Started a local Ray instance. View the dashboard at \x1b[1m\x1b[32mhttp://127.0.0.1:8266 \x1b[39m\x1b[22m\n2022-10-26 01:32:54,405\tINFO tune.py:788 -- Total run time: 6.60 seconds (5.33 seconds for the tuning loop).\n== Status ==\nCurrent time: 2022-10-26 01:32:51 (running for 00:00:02.57)\nMemory usage on this node: 2.6/7.6 GiB \nUsing FIFO scheduling algorithm.\nResources requested: 1.0/2 CPUs, 0/0 GPUs, 0.0/3.42 GiB heap, 0.0/1.71 GiB objects\nResult logdir: /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/_tmp/3fba95ff54c67161134a94c8463b3e4b/train_2022-10-26_01-32-47\nNumber of trials: 3/3 (2 PENDING, 1 RUNNING)\n\n\nTrial train_xxxxx_00000 reported acc=5 with parameters={'do': 'complete'}. This trial completed.\nTrial train_xxxxx_00002 reported acc=7 with parameters={'do': 'twice'}.\nTrial train_xxxxx_00002 reported acc=8 with parameters={'do': 'twice'}. This trial completed.\nTrial train_xxxxx_00001 reported _metric=6 with parameters={'do': 'once'}.\n== Status ==\nCurrent time: 2022-10-26 01:32:54 (running for 00:00:05.33)\nMemory usage on this node: 2.7/7.6 GiB \nUsing FIFO scheduling algorithm.\nResources requested: 1.0/2 CPUs, 0/0 GPUs, 0.0/3.42 GiB heap, 0.0/1.71 GiB objects\nResult logdir: /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/_tmp/3fba95ff54c67161134a94c8463b3e4b/train_2022-10-26_01-32-47\nNumber of trials: 3/3 (1 RUNNING, 2 TERMINATED)\n\n\nTrial train_xxxxx_00001 completed. Last result: _metric=6\n== Status ==\nCurrent time: 2022-10-26 01:32:54 (running for 00:00:05.35)\nMemory usage on this node: 2.6/7.6 GiB \nUsing FIFO scheduling algorithm.\nResources requested: 0/2 CPUs, 0/0 GPUs, 0.0/3.42 GiB heap, 0.0/1.71 GiB objects\nResult logdir:
```

**Comment by bveeramani** [comment] 2022-10-27 18:31
There's a PR open for this: https://github.com/ray-project/ray/pull/29748

**Comment by bveeramani** [comment] 2022-10-27 18:32
Closing as duplicate of https://github.com/ray-project/ray/issues/29693

**Closed by bveeramani** 2022-10-27 18:32 UTC
Labels: P0, flaky-tracker
