### ISSUE TITLE
[Core] ray start --include-dashboard=true succeeds, but dashboard fails to start 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#37931] opened 2023-07-31 15:06 UTC
### Description

We just came across a case where the Ray dashboard started successfully (ray start --include-dashboard=true ran successfully) but the dashboard didn't pass healthchecks so the node never came up (ray dashboard health check: Get "http://localhost:8265/": dial tcp 127.0.0.1:8265: connect: connection refused). The dashboard reported a bunch of warnings like the following -

```
Module ray.dashboard.modules.test.test_head cannot be loaded because we cannot import all dependencies. Install this module using pip install 'ray[default]' for the full dashboard functionality. Error: No module named 'opencensus'
```

It would be better if this exception were caught in ray start --include-dashboard=true so we can surface it to users through our existing observability pipelines. The infra contract should read that if --include-dashboard=true is set, then ray start only returns when the dashboard has successfully started.

### Use case

Important use case for cluster management

**Comment by rkooo567** [comment] 2023-08-02 21:28
1. Talk to Shomil for more detailed requirements.
2. Decide if fate share dashboard & ray cluster is necessary when using Anyscale (after ray start succeeds)

**Comment by rkooo567** [comment] 2023-08-02 21:28
cc @vitsai

**Comment by vitsai** [comment] 2023-08-17 00:19
Seems that dashboard already fate-shares with ray start in the common case (ray start blocks on retrieving the url from GCS, which dashboard only posts upon successful initialization). Based on the warnings that you posted, you seem to have accidentally triggered the "minimal install" codepath, which will not start the dashboard *by design*. 

The reason this codepath was triggered is because the current way to detect whether the install is minimal is to check whether the optional dashboard dependencies are installed. If the optional dependencies fail to be imported, we assume a minimal install of Ray. Apparently this is the best way to detect this?

The expectation is that this shouldn't happen as long as dependencies are installed. Closing this now, please reopen if you would still like some behavior change @shomilj.

cc: @rkooo567 regarding the minimal install behavior.

**Closed by vitsai** 2023-08-17 00:19 UTC
Labels: enhancement, P1, core, Ray 2.7

**Comment by vitsai** [comment] 2023-08-18 01:18
So one change that might make sense here is to just assume user intent is *not* to run in minimal mode when the flag is explicitly included. PR linked.
