### ISSUE TITLE
[core][Bug] ray metrics SIGSEGV

### ISSUE THREAD

**Issue by chaokunyang** [ray-project/ray#22981] opened 2022-03-10 02:44 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

When running `Mars` on `Ray`, I got following crash occasionally:
```
*** SIGSEGV received at time=1646847326 on cpu 0 ***
PC: @     0x7fde64ca37e3  (unknown)  absl::lts_20210324::hash_internal::Wyhash()
    @     0x7fde8a1a53c0       3344  (unknown)
    @     0x7fde64ca3674         80  absl::lts_20210324::hash_internal::HashState::CombineLargeContiguousImpl64()
    @     0x7fde64ca32ce         64  absl::lts_20210324::hash_internal::hash_range_or_bytes<>()
    @     0x7fde64ca3384         48  opencensus::tags::TagMap::Initialize()
    @     0x7fde64ca35dd         32  opencensus::tags::TagMap::TagMap()
    @     0x7fde646157ca        192  ray::stats::internal::Stats::Record()
    @     0x7fde64680eda        224  ray::stats::internal::Stats::Record()
    @     0x7fde648a4243        112  instrumented_io_context::RecordStart()
    @     0x7fde647c359a        208  ray::rpc::ClientCallManager::CreateCall<>()
    @     0x7fde647c53ba        288  ray::raylet::RayletClient::ReportWorkerBacklog()
    @     0x7fde646b44bf        320  ray::core::CoreWorkerDirectTaskSubmitter::ReportWorkerBacklogInternal()
    @     0x7fde646b47e2         32  ray::core::CoreWorkerDirectTaskSubmitter::ReportWorkerBacklog()
    @     0x7fde646562a5        224  ray::core::CoreWorker::InternalHeartbeat()
    @     0x7fde648a81dc        176  ray::PeriodicalRunner::DoRunFnPeriodically()
    @     0x7fde648a0a76        112  boost::asio::detail::completion_handler<>::do_complete()
    @     0x7fde64c75f3b        128  boost::asio::detail::scheduler::do_run_one()
    @     0x7fde64c77191        192  boost::asio::detail::scheduler::run()
    @     0x7fde64c77610         64  boost::asio::io_context::run()
    @     0x7fde64605d85        208  ray::core::CoreWorker::RunIOService()
    @     0x7fde64d675a0  (unknown)  execute_native_thread_routine
    @     0x55bddfe82130  (unknown)  (unknown)
    @     0x7fde645ef920  (unknown)  (unknown)
    @ 0x9000777ca1e90789  (unknown)  (unknown)
[2022-03-09 17:35:26,170 E 2666 53847] logging.cc:317: *** SIGSEGV received at time=1646847326 on cpu 0 ***
[2022-03-09 17:35:26,170 E 2666 53847] logging.cc:317: PC: @     0x7fde64ca37e3  (unknown)  absl::lts_20210324::hash_internal::Wyhash()
[2022-03-09 17:35:26,173 E 2666 53847] logging.cc:317:     @     0x7fde8a1a53c0       3344  (unknown)
[2022-03-09 17:35:26,174 E 2666 53847] logging.cc:317:     @     0x7fde64ca3674         80  absl::lts_20210324::hash_internal::HashState::CombineLargeContiguousImpl64()
[2022-03-09 17:35:26,174 E 2666 53847] logging.cc:317:     @     0x7fde64ca32ce         64  absl::lts_20210324::hash_internal::hash_range_or_bytes<>()
[2022-03-09 17:35:26,174 E 2666 53847] logging.cc:317:     @     0x7fde64ca3384         48  opencensus::tags::TagMap::Initialize()
[2022-03-09 17:35:26,175 E 2666 53847] logging.cc:317:     @     0x7fde64ca35dd         32  opencensus::tags::TagMap::TagMap()
[2022-03-09 17:35:26,175 E 2666 53847] logging.cc:317:     @     0x7fde646157ca        192  ray::stats::internal::Stats::Record()
[2022-03-09 17:35:26,175 E 2666 53847] logging.cc:317:     @     0x7fde64680eda        224  ray::stats::internal::Stats::Record()
[2022-03-09 17:35:26,176 E 2666 53847] logging.cc:317:     @     0x7fde648a4243        112  instrumented_io_context::RecordStart()
[2022-03-09 17:35:26,176 E 2666 53847] logging.cc:317:     @     0x7fde647c359a        208  ray::rpc::ClientCallManager::CreateCall<>()
[2022-03-09 17:35:26,176 E 2666 53847] logging.cc:317:     @     0x7fde647c53ba        288  ray::raylet::RayletClient::ReportWorkerBacklog()
[2022-03-09 17:35:26,176 E 2666 53847] logging.cc:317:     @     0x7fde646b44bf        320  ray::core::CoreWorkerDirectTaskSubmitter::ReportWorkerBacklogInternal()
[2022-03-09 17:35:26,177 E 2666 53847] logging.cc:317:     @     0x7fde646b47e2         32  ray::core::CoreWorkerDirectTaskSubmitter::ReportWorkerBacklog()
[2022-03-09 17:35:26,177 E 2666 53847] logging.cc:317:     @     0x7fde646562a5        224  ray::core::CoreWorker::InternalHeartbeat()
[2022-03-09 17:35:26,177 E 2666 53847] logging.cc:317:     @     0x7fde648a81dc        176  ray::PeriodicalRunner::DoRunFnPeriodically()
[2022-03-09 17:35:26,178 E 2666 53847] logging.cc:317:     @     0x7fde648a0a76        112  boost::asio::detail::completion_handler<>::do_complete()
[2022-03-09 17:35:26,178 E 2666 53847] logging.cc:317:     @     0x7fde64c75f3b        128  boost::asio::detail::scheduler::do_run_one()
[2022-03-09 17:35:26,178 E 2666 53847] logging.cc:317:     @     0x7fde64c77191        192  boost::asio::detail::scheduler::run()
[2022-03-09 17:35:26,179 E 2666 53847] logging.cc:317:     @     0x7fde64c77610         64  boost::asio::io_context::run()
[2022-03-09 17:35:26,179 E 2666 53847] logging.cc:317:     @     0x7fde64605d85        208  ray::core::CoreWorker::RunIOService()
[2022-03-09 17:35:26,179 E 2666 53847] logging.cc:317:     @     0x7fde64d675a0  (unknown)  execute_native_thread_routine
[2022-03-09 17:35:26,183 E 2666 53847] logging.cc:317:     @     0x55bddfe82130  (unknown)  (unknown)
[2022-03-09 17:35:26,188 E 2666 53847] logging.cc:317:     @     0x7fde645ef920  (unknown)  (unknown)
[2022-03-09 17:35:26,193 E 2666 53847] logging.cc:317:     @ 0x9000777ca1e90789  (unknown)  (unknown)
/home/runner/work/_temp/50d02a85-162b-4373-97db-58d98034967b.sh: line 30:  2666 Segmentation fault      (core dumped) pytest $PYTEST_CONFIG --durations=0 --timeout=600 -v -s -m ray
```

### Versions / Dependencies

`ray==1.9.2`

### Reproduction script

The crash happens occasionally, I can't reproduce.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment] 2022-03-10 06:10
Hmm we might need the repro to fix it. I am looking at code now, and I cannot think of any scenario this can cause sigsegv. Did it happen upon shutdown?

**Comment by chaokunyang** [comment] 2022-03-15 06:17
> Hmm we might need the repro to fix it. I am looking at code now, and I cannot think of any scenario this can cause sigsegv. Did it happen upon shutdown?

Ray didin't shutdown when it crash. It happend in a CI environment which is a 2C7G ubuntu docker container, I can't reproduce in my local machine.

**Comment by zhe-thoughts** [comment] 2022-10-26 05:18
Hey @chaokunyang are you still seeing the issue? I'm leaning towards marking this as a P2 since the same issue has not been reported in other settings and we cannot reproduce.

**Comment by zhe-thoughts** [comment] 2022-10-26 05:19
@chaokunyang  @rkooo567 Let me know if P2 is reasonable here. Thanks

**Comment by scv119** [comment] 2022-11-30 01:23
duplicate of #30747

**Closed by scv119** 2022-11-30 01:23 UTC
Labels: bug, needs-repro-script, P2
