### ISSUE TITLE
[Core] `ray stop` does not clean up `ray_current_cluster` file 

### ISSUE THREAD

**Issue by m-harmonic** [ray-project/ray#45771] opened 2024-06-06 05:00 UTC
### What happened + What you expected to happen

1. Start a cluster from the command line without a .yaml file:

`ray start --head --port=6379 --temp-dir=/tmp/ray`

2. Stop Ray processes manually

`ray stop`

3. The cluster file (ray_current_cluster) is still there and has not been cleaned up.

The problem is that starting ray again after this using `ray.init()` will fail because it sees the existing cluster file and tries to connect to that cluster instead of starting a new local one. Passing address="local" fixes the problem, however.

### Versions / Dependencies

Ray: 2.9.3
Python: 3.10.12
OS: Ubuntu 20.04.6 LTS

### Reproduction script

```
ray start --head --port=6379 --temp-dir=/tmp/ray
ray stop
ls /tmp/ray/ray_current_cluster
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by MaxVanDijck** [comment] 2024-06-06 07:35
Try updating your version of ray, I suspect this is the same issue that was fixed in https://github.com/ray-project/ray/pull/27666
issue: https://github.com/ray-project/ray/issues/27021

**Comment by jjyao** [comment] 2024-06-18 23:32
Hi @m-harmonic, could you try the latest Ray. I think the issue is fixed.

**Closed** 2024-06-18 23:33 UTC
Labels: bug, triage, core
