### ISSUE TITLE
[Core] Support not reporting task events for specified tasks.

### ISSUE THREAD

**Issue by MissiontoMars** [ray-project/ray#42113] opened 2023-12-28 06:10 UTC
### Description

There are many actors in our ray job. After running for a while, the number of task events can easily exceed the upper limit (max_num_task_in_gcs 100000), causing the timeline downloaded on the dashboard to be incomplete. Users don't care much about many actor tasks in their jobs, such as health check tasks. Can we support ignoring these tasks? Like using the following method:

```
class MyActor:
    def __init__(sefl):
        pass

    def health_check(self):
        return True

actor = MyActor.remote()
ray.get(actor.health_check.options(no_task_report=True).remote())
```

with **no_task_report=True,** task event ignored.

Currently, task events do not support classification by job, for example here: https://github.com/ray-project/ray/issues/31071So things will get worse when running multiple jobs in a ray cluster.

**Comment by MissiontoMars** [comment] 2023-12-28 06:11
@rickyyx Any better suggestions?

**Comment by rickyyx** [comment] 2023-12-28 18:37
This is a great idea! I think allowing users to ignore task events report for some tasks could be a good mitigation for running into large number of tasks. 

I think one current workaround (maybe not so clean at the API level) is through setting runtime env on the task with `RAY_task_events_report_interval_ms=0`

This is kind of similar to https://github.com/ray-project/ray/issues/42076

cc @rkooo567

**Comment by MissiontoMars** [comment] 2023-12-29 02:25
@rickyyx My understanding of the role of RAY_task_events_report_interval_ms is to turn off the current worker's task event reporter. This may not be accurate, for example:The Driver calls MyActor.ping.remote(), and sets RAY_task_events_report_interval_ms=0 for MyActor, but the reporting of MyActor.ping task events is on the Driver side, so it can't take effect? https://github.com/ray-project/ray/blob/master/src/ray/core_worker/task_manager.cc#L1440

If we set RAY_task_events_report_interval_ms=0 for the Driver, then the task events of other actors will also be ignored.So I think we need more granular control options, such as specifying no event reporting for specific tasks, including task status events and task profile events.

**Comment by rickyyx** [comment] 2023-12-29 23:05
> @rickyyx My understanding of the role of RAY_task_events_report_interval_ms is to turn off the current worker's task event reporter. This may not be accurate, for example:
> 
> The Driver calls MyActor.ping.remote(), and sets RAY_task_events_report_interval_ms=0 for MyActor, but the reporting of MyActor.ping task events is on the Driver side, so it can't take effect? https://github.com/ray-project/ray/blob/master/src/ray/core_worker/task_manager.cc#L1440
> 
> If we set RAY_task_events_report_interval_ms=0 for the Driver, then the task events of other actors will also be ignored.So I think we need more granular control options, such as specifying no event reporting for specific tasks, including task status events and task profile events.

I see - yeah, good catch. You are right here. The workaround will not disable all task events from the driver side.

**Comment by rkooo567** [comment] 2024-01-26 00:06
I think it is duplicate of https://github.com/ray-project/ray/issues/42076

**Comment by MissiontoMars** [comment] 2024-01-26 02:58
> > @rickyyx My understanding of the role of RAY_task_events_report_interval_ms is to turn off the current worker's task event reporter. This may not be accurate, for example:
> > The Driver calls MyActor.ping.remote(), and sets RAY_task_events_report_interval_ms=0 for MyActor, but the reporting of MyActor.ping task events is on the Driver side, so it can't take effect? https://github.com/ray-project/ray/blob/master/src/ray/core_worker/task_manager.cc#L1440
> > If we set RAY_task_events_report_interval_ms=0 for the Driver, then the task events of other actors will also be ignored.So I think we need more granular control options, such as specifying no event reporting for specific tasks, including task status events and task profile events.
> 
> I see - yeah, good catch. You are right here. The workaround will not disable all task events from the driver side.

@rkooo567 Oh, it's not duplicate with https://github.com/ray-project/ray/issues/42076. Can you please take a look at the previous conversation with @rickyy?

**Comment by rkooo567** [comment] 2024-01-26 06:09
@MissiontoMars so it is that issue + we also allow to disable task event report per task right?

**Comment by rkooo567** [comment] 2024-01-26 06:09
I think we can close it together

**Comment by rkooo567** [comment] 2024-01-26 06:09
shouldn't be too hard to support both

**Comment by MissiontoMars** [comment] 2024-01-26 07:11
> disable task event report per task

Yeah，if we support disable task event report per task, both the two issues can be fixed.

**Comment by khluu** [comment] 2024-02-29 02:14
ETA fixed by Feb28/29

**Closed** 2024-02-29 22:37 UTC
Labels: enhancement, release-blocker, P0, core, ray 2.10
