### ISSUE TITLE
[RLLib] RandomNumberGenerator error while running example code for RLLib

### ISSUE THREAD

**Issue by deborshigoswami95** [ray-project/ray#31598] opened 2023-01-11 18:00 UTC
### What happened + What you expected to happen

The example code provided in [Ray RLLib Documentation](https://docs.ray.io/en/latest/rllib/index.html) fails to run. 

Error message

> RaySystemError: System error: RandomNumberGenerator._generator_ctor() takes from 0 to 1 positional arguments but 2 were given
> traceback: Traceback (most recent call last):
>   File "/Users/goswamd/anaconda3/envs/rllib_env/lib/python3.10/site-packages/ray/_private/serialization.py", line 369, in deserialize_objects
>     obj = self._deserialize_object(data, metadata, object_ref)
>   File "/Users/goswamd/anaconda3/envs/rllib_env/lib/python3.10/site-packages/ray/_private/serialization.py", line 252, in _deserialize_object
>     return self._deserialize_msgpack_data(data, metadata_fields)
>   File "/Users/goswamd/anaconda3/envs/rllib_env/lib/python3.10/site-packages/ray/_private/serialization.py", line 207, in _deserialize_msgpack_data
>     python_objects = self._deserialize_pickle5_data(pickle5_data)
>   File "/Users/goswamd/anaconda3/envs/rllib_env/lib/python3.10/site-packages/ray/_private/serialization.py", line 195, in _deserialize_pickle5_data
>     obj = pickle.loads(in_band, buffers=buffers)
> TypeError: RandomNumberGenerator._generator_ctor() takes from 0 to 1 positional arguments but 2 were given

### Versions / Dependencies

- Environment --> [requirements.txt](https://github.com/ray-project/ray/files/10394819/requirements.txt)
- Python 3.10.8
- MacOS x 64

### Reproduction script

```python
from ray.rllib.algorithms.ppo import PPOConfig

config = (  # 1. Configure the algorithm,
    PPOConfig()
    .environment("Taxi-v3")
    .rollouts(num_rollout_workers=2)
    .framework("tf2")
    .training(model={"fcnet_hiddens": [64, 64]})
    .evaluation(evaluation_num_workers=1)
)

algo = config.build()  # 2. build the algorithm,

for _ in range(5):
    print(algo.train())  # 3. train it,

algo.evaluate()  # 4. and evaluate it.
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by maxpumperla** [comment] 2023-01-11 18:05
@deborshigoswami95 thanks for reporting, can't check right now, but looks like a potential duplicate of https://github.com/ray-project/ray/issues/31293

**Comment by maxpumperla** [comment] 2023-01-11 18:06
you seem to be using the same numpy version as in that issue, so looks likely

**Comment by deborshigoswami95** [comment] 2023-01-11 18:09
Thanks for the comment, I will try to downgrade numpy and try again

**Comment by deborshigoswami95** [comment] 2023-01-11 18:20
The code runs after downgrading numpy :) Thank you! We can close this issue

**Comment by maxpumperla** [comment] 2023-01-11 18:21
cool! happy to hear that

**Closed** 2023-01-11 18:21 UTC
Labels: bug, triage

**Comment by mavroudisv** [comment] 2023-02-08 21:30
`pip install numpy==1.23.5`

did it for me. I haven't tried if a newer version could solve it too.
