### ISSUE TITLE
Core: Importing ray causes critical log messages to not be shown

### ISSUE THREAD

**Issue by klieret** [ray-project/ray#37941] opened 2023-07-31 18:54 UTC
### What happened + What you expected to happen

Simply importing ray hides all log messages in the newest ray version when importing a logger. 
This is a new issue with ray 2.6.xx (I can confirm that this issue does not appear with 2.5.1).

This sounds somewhat similar to https://github.com/ray-project/ray/issues/17374, but here ray isn't even initialized (and the solution presented there does not work).

### Versions / Dependencies

- ray 2.6.1 (not an issue with 2.5.1)
- py 3.11.3

### Reproduction script

Create file `log.py`:

```python
import logging

logger = logging.getLogger("test")
```

Create file `test_log.py`:

```python3
from log import logger
# import ray

logger.critical("This is bad")
```

Executing `test_log.py` like this causes the log message to be shown (as expected). 
However, uncommenting `import ray`, no more log message is shown.

### Issue Severity

High: It blocks me from completing my task.

**Comment by richardliaw** [comment] 2023-07-31 19:53
This seems similar to https://github.com/ray-project/ray/issues/37920.

**Comment by jjyao** [comment] 2023-07-31 20:12
This should be a duplicate of https://github.com/ray-project/ray/issues/37941. This has been fixed in master and will be released in 2.6.2 soon.

**Closed by jjyao** 2023-07-31 20:12 UTC
Labels: bug, triage, core

**Comment by klieret** [comment] 2023-07-31 21:05
Thanks @richardliaw @jjyao . Accidentally had an is:open filter in my issue search, I realized. Sorry for the duplicate!

**Comment by xieus** [comment] 2023-08-04 02:37
@klieret Ray 2.6.2 is released today with an proper fix.
https://github.com/ray-project/ray/releases/tag/ray-2.6.2

Please check it out and let us know how it goes. Thank you for your patience and understanding.
