### ISSUE TITLE
Python3 2x slower than Python2 for some operations

### ISSUE THREAD

**Issue by devin-petersohn** [ray-project/ray#1427] opened 2018-01-15 23:09 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OS X
- **Ray installed from (source or binary)**: source
- **Python version**: Python 2.7 & Python 3.6

### Describe the problem
I am seeing a slowdown of 2x when I run things on Python3 vs Python2. The slowdown doesn't look to be linked to creating actors, but rather in executing certain types of tasks.

Code to reproduce is below.
`python2 time: 4.214621067047119`
`python3 time: 9.676268259005155`

### Source code / logs

```python
import ray
ray.init()

@ray.remote
class Actor(object):
    def __init__(self, rows={"Item1": "Value1", "Item2": "Value2"}):
        self.rows = rows
    def split(self):
        half = int(len(self.rows)/2)
        items = list(self.rows.items())
        items.sort()
        second_dict = dict(items[half:])
        self.rows = dict(items[:half])
        return second_dict
    def get_rows(self):
        return self.rows

def f():
    actor = Actor.remote()
    actor2 = Actor.remote(actor.split.remote())
    print(ray.get(actor2.get_rows.remote()))
    print(ray.get(actor.get_rows.remote()))

import timeit
timeit.timeit(f, number=10)
```

**Comment by robertnishihara** [comment] 2018-01-15 23:37
On Linux (Ubuntu 16.04), I see

**Python 2:** 7.4s
**Python 3:** 6.8s

**Comment by robertnishihara** [comment] 2018-01-16 01:31
Ok, I can reproduce the problem on Mac

**Python 2:** 6.5s
**Python 3:** 11s

**Comment by robertnishihara** [comment] 2018-01-16 01:44
Ok, the basic difference seems to be how long it takes to create an actor.

```python
import ray
ray.init()

@ray.remote
class Foo(object):
    def f(self):
        return 1

%timeit ray.get(Foo.remote().f.remote())  # 613ms in Python2, 1.12s with Python3.
```

One factor, which could partially account for this is the time required to start a Python interpreter.

```shell
# Python 2
> time python2 -c "print('hi')"  # 0.024s

# Python 3
> time python3 -c "print('hi')"  # 0.105s
```

Although that doesn't seem to explain the full difference.

**Comment by robertnishihara** [comment] 2018-01-16 04:39
Ok, if you replace `"print('hi')"` with `"import ray"`, then you see the full difference. We should really speed up `import ray`.

**Comment by robertnishihara** [comment] 2018-01-16 20:23
Ok, I think this can be reproduced more simply with `"import pyarrow"` instead of `"import ray"`. We import `pyarrow` when ray is imported.

**Comment by robertnishihara** [comment] 2018-01-17 00:43
A decent fraction of the time is spent in pyarrow when we import torch and pandas to create the `_default_serialization_context`.

```python
In [1]: %time import torch
CPU times: user 319 ms, sys: 22.1 ms, total: 341 ms
Wall time: 372 ms

In [2]: %time import pandas
CPU times: user 193 ms, sys: 23.5 ms, total: 217 ms
Wall time: 219 ms
```

We should probably not do this (though this will just shift the time from the `import ray` call to the `ray.init()` call), but we should make sure that import statements are fast.

**Comment by devin-petersohn** [comment] 2018-01-17 03:46
Interesting. I did like the idea you mentioned earlier about having a process on remote machines waiting. Could you have a process that runs from cluster startup and `fork()` it? Would that reduce the startup time?

**Comment by devin-petersohn** [comment] 2018-01-17 07:01
For another interesting twist on the situation, the problem disappears if you run things in a conda environment where you set `python=3`.

This seems bizarre to me, I would think the execution times would be similar.

**Comment by robertnishihara** [comment] 2018-01-17 07:29
The difference may be less about python2 versus python3 and more about which libraries you have installed. E.g., for your newly created conda environment, if you don't have torch or pandas installed then it will be faster. If you install torch and pandas, then it will get slower.

**Comment by robertnishihara** [comment] 2018-02-02 07:45
Closing because I think we know what the underlying issue is.

We should do some stuff to mitigate this, in particular.
- not import libraries like `torch` or `pandas` until they are needed
- start workers ahead of time so they can be converted into actors more quickly when they are needed

**Closed by robertnishihara** 2018-02-02 07:45 UTC
