### ISSUE TITLE
ImportError: cannot import name 'ExtensionArrayFormatter' from 'pandas.io.formats.format' 

### ISSUE THREAD

**Issue by b-phi** [ray-project/ray#42572] opened 2024-01-22 18:02 UTC
### What happened + What you expected to happen

`ray/air/util/tensor_extensions/pandas.py:45` attempts to import `ExtensionArrayFormatter` from `pandas.io.formats.format`. This class was made private in [this commit](https://github.com/pandas-dev/pandas/commit/6c58a217f5d9a2520d9d4bee665edff5397bbfc6#diff-c2df0eefbdda16cb85d5e0a305db90101f92bfb790a8e989ab2e99b935b7f6b3L1589) which was released with Pandas 2.2.0. 

### Versions / Dependencies

* ray == 2.9.1
* pandas == 2.2.0

### Reproduction script

```python
import pandas as pd
import ray

df = pd.DataFrame()
ray.data.from_pandas(df)
```

### Issue Severity

None

**Comment by wpm** [comment] 2024-01-23 20:23
Looks like this is only referenced in [ray/python/ray/air/util/tensor_extensions/pandas.py](https://github.com/ray-project/ray/blame/5c77f32bb993fd65fb50230f458a9dd8c7109586/python/ray/air/util/tensor_extensions/pandas.py#L45) and was pulled in two years ago.

The class is pandas is now called `_ExtensionArrayFormatter`. The following import works.

```
>>> from pandas.io.formats.format import _ExtensionArrayFormatter
```

The change in pandas is commit [55389](https://github.com/pandas-dev/pandas/commit/6c58a217f5d9a2520d9d4bee665edff5397bbfc6) from October 4, 2023. The problem is fixed if I downgrade to pandas 2.1.2.

**Comment by wpm** [comment] 2024-01-23 20:32
`pandas.io.formats.format.ExtensionArrayFormatter` was changed to `pandas.io.formats.format._ExtensionArrayFormatter` in the commit for issue [55398](https://github.com/pandas-dev/pandas/commit/6c58a217f5d9a2520d9d4bee665edff5397bbfc6) on October 4, 2023.

Downgrading to pandas 2.1.2 fixes the problem in Ray.

**Comment by scottjlee** [comment] 2024-04-09 23:44
We recommend upgrading to `ray 2.10` or higher to resolve the issue. Otherwise, you can downgrade pandas to 2.1.2.

Closed by https://github.com/ray-project/ray/pull/42892

**Closed by scottjlee** 2024-04-09 23:44 UTC
Labels: bug, P1, data, ray 2.11
