### ISSUE TITLE
[Bug] Not enough permissions to watch for resources: changes (creation/deletion/updates) will not be noticed; the resources are only refreshed on operator restarts.

### ISSUE THREAD

**Issue by kssanthosh** [ray-project/ray#19071] opened 2021-10-04 06:59 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

Ray operator starting with error

`Not enough permissions to watch for resources: changes (creation/deletion/updates) will not be noticed; the resources are only refreshed on operator restarts.`

I can see all permissions are fine.

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ray-operator-serviceaccount
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ray-operator-clusterrole
rules:
- apiGroups: ["", "cluster.ray.io"]
  resources: ["rayclusters", "rayclusters/finalizers", "rayclusters/status", "pods", "pods/exec", "services"]
  verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]
- apiGroups: [""]
  resources: [events]
  verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ray-operator-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: ray-operator-serviceaccount
  namespace: default
roleRef:
  kind: ClusterRole
  name: ray-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io

```

### Reproduction script

Deploy it with helm3 and try to spin up ray work some time work only start after restarting ray operator

### Anything else

Ray work is starting after restarting Ray operator it is not able to trace the changes. I'm using ray work on the same namespace it should work without issue not sure what is happening.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment] 2021-10-04 17:10
I think the error message is benign.

The failed startup needs to be fixed, though.

@kssanthosh 
Are you able to reproduce the issue consistently? Could you post detailed reproduction steps?

**Comment by DmitriGekhtman** [comment] 2021-10-16 16:25
I'm unable to reproduce the issue when deploying using the default helm configuration. Let me know if there are any other reproduction details that might be helpful in identifying the problem.

**Comment by DmitriGekhtman** [comment] 2021-10-20 23:54
Just noting that I was just able to reproduce the issue once. Hopefully we can figure out a consistent repro.

**Comment by PatTheSilent** [comment] 2021-11-23 08:29
@DmitriGekhtman Sorry to dig this one out but I'm seeing the same errors as were originally reported. All new pods are spitting out `Not enough permissions to watch for resources: changes (creation/deletion/updates) will not be noticed; the resources are only refreshed on operator restarts.`
I don't have any raycluster resources deployed yet (helm chart deployed with `operatorOnly: true`) and use a separate namespace for the operator (`operatorNamespace: ray`)

**Comment by wuisawesome** [comment] 2022-01-04 22:21
We should consider how to solve this problem in the context of kuberay

**Comment by holdenk** [comment] 2022-02-26 22:11
While I still get the error message, deleting and re-creating the ray namespace seems to do the trick for subsequent helm clusters set up in that namespace suggesting that maybe there is some weird resource hanging out.

**Comment by OAfzal** [comment] 2022-04-11 08:12
@holdenk were you able to solve this problem? I am getting the same message when trying to deploy via helm

**Comment by saswatac** [comment] 2022-08-02 05:33
It looks like additionally list/watch namespace permissions are needed. 

https://github.com/nolar/kopf/blob/129fe4ced27e097ff92cde6d1b2405e726e4c820/kopf/_cogs/configs/configuration.py#L240

https://github.com/nolar/kopf/issues/901

i edited the ray-operator-clusterrole and added the list/watch permissions for namespace, and now it seems to correctly create/delete the ray clusters without needing restart of the ray operator pod. Although i still the warning during the pod startup.

**Comment by harksodje** [comment] 2022-10-24 14:51
@saswatac please can show a sample of the changes you made in code format. 
Thanks

**Comment by DmitriGekhtman** [comment] 2022-10-24 16:27
I'd strongly recommend deploying Ray use KubeRay.
You can read about that here: https://docs.ray.io/en/latest/cluster/kubernetes/index.html
The KubeRay operator is now the preferred tool for deploying Ray on Kubernetes.

**Comment by DmitriGekhtman** [comment] 2022-11-19 17:00
The older operator is deprecated and will be removed in Ray 2.2.0.
Closing this issue.

**Closed by DmitriGekhtman** 2022-11-19 17:00 UTC
Labels: bug, needs-repro-script, P2, infra
