### ISSUE TITLE
[ADAG] Sending sharded outputs into multiple downstream DAG nodes

### ISSUE THREAD

**Issue by kevin85421** [ray-project/ray#47098] opened 2024-08-12 22:56 UTC
### Description

<img width="803" alt="image" src="https://github.com/user-attachments/assets/8e2f1cf3-6838-4b4a-a3d5-82fe9292990d">

```python
with InputNode() as inp:
    ref1, ref2 = actor.fwd.bind()
    actor2.fwd.bind(ref1)
    actor3.fwd.bind(ref1)
```

### Use case

"In the future, if we want to do training on heterogeneous resources, we want to allocate different numbers of GPUs for different submodules. These submodules have the same global batch size, but have different micro batch sizes. Currently ADAG API only supports reading the full outputs from a parent node.
" from @woshiyyya

**Comment by stephanie-wang** [comment] 2024-08-13 04:52
This is a duplicate of #45569, and @dengwxn has #47024 open for it.

**Closed by stephanie-wang** 2024-08-13 04:52 UTC
Labels: enhancement, accelerated-dag
