### ISSUE TITLE
Console output got relipated n times if there are n ray nodes on the same machine

### ISSUE THREAD

**Issue by yangw1234** [ray-project/ray#10392] opened 2020-08-28 07:49 UTC
### What is the problem?
Ray version: 0.8.7
Python version:  3.6.7

Problem:

If multiple ray nodes (say n ray nodes) are started on the same machine, then one ray nodes' console output will got replicated n times on driver. 

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Step 1: start two ray nodes on the same machine
```shell
ray start --head
ray start --address='the address printed' --redis-password='the password printed'
```

Step 2: run the following script
```python
import ray
def print_hello():
    print("hello")
    return 0

remote_print = ray.remote(print_hello)
ray.get(remote_print.remote())
```
Then "hello" will be printed twice on the driver.
![image](https://user-images.githubusercontent.com/10561966/91535616-ff180180-e945-11ea-8e64-14d469897824.png)

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment] 2020-08-28 07:51
It is not recommended to run multiple ray nodes in the same machine. Is it reproducible when it is running in multiple machines?

**Comment by rkooo567** [comment] 2020-08-28 07:52
Also, if you need to run multiple nodes in a single machine, would you mind sharing your use case?

**Comment by yangw1234** [comment] 2020-08-28 08:02
Hi @rkooo567, I only observe this when running multiple ray nodes in the same machine.

We are actually running on a multi-sockets machine and we want to bind ray processes to different numa nodes to achieve best performance. 

Is there a way to do this without starting multiple ray nodes?

**Comment by yangw1234** [comment] 2020-08-28 08:09
@rkooo567 it seems all ray nodes shard the same log directory on the same machine, and all ray nodes have a log_monitor monitoring the same log directory. As a result, when one worker prints something, all log_monitor will see it and forward it to the driver.

**Comment by yangw1234** [comment] 2020-08-28 08:14
Is there a way to set this logging directory manually?

**Comment by rkooo567** [comment] 2020-08-28 21:11
Yes I think you can use this command arg https://docs.ray.io/en/latest/package-ref.html#cmdoption-ray-start-temp-dir

**Comment by yangw1234** [comment] 2020-08-31 06:21
@rkooo567 https://github.com/ray-project/ray/blob/master/python/ray/node.py#L233, seems non-head ray process just read the "temp_dir" set to head node. 

I worked around this issue by manually killing the redundant log_monitor processes. However, I think it would be nice to have it in ray out of box. E.g. separating each ray nodes' log dir to "/tmp/ray/session-xx/0/logs", "/tmp/ray/session-xxx/1/logs", .etc

**Comment by byoung0589** [comment] 2020-10-16 17:18
I am seeing this on latest 1.0.0 , worker stdout / stderr is duplicated to all of the workers. It *was fixed in 0.9.0  and I have had to pin to this release: https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.9.0.dev0-cp35-cp35m-manylinux1_x86_64.whl

I am trying to find the original issue where this was addressed. Anyone know why this has Resurfaced in 1.0.0?

I am running multiple worker procs under supervisor to process messages from a an AMQP queue.  Each pid is replicating the stdout of each-other where as in 0.9.0 the logs are correctly only logged by the respective process and not duplicated.

**Comment by rkooo567** [comment] 2020-10-17 05:09
Hmm interesting. cc @wuisawesome Doesn't this mean our log_monitor per job is broken?

**Comment by rkooo567** [comment] 2020-10-17 05:09
@byoung0589 Can you give us a simple script to reproduce this? We can probably find a quick fix.

**Comment by rkooo567** [comment] 2020-10-17 05:09
Also please open an new issue! So that we won't lose the track of it.

**Comment by byoung0589** [comment] 2020-10-17 22:47
Sure , thanks. Our setup is kind  I will write something simple to demonstrate the issue and create a seperate issue here for it.

**Comment by wuisawesome** [comment] 2020-10-19 02:30
I'll close this issue for now since you will open a new issue with the repro

**Closed by wuisawesome** 2020-10-19 02:30 UTC
Labels: P3, bug
