### ISSUE TITLE
[Core] plasma unlimited is limited by max number of open fds

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#17731] opened 2021-08-11 07:45 UTC
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*  2.0dev

### Reproduction (REQUIRED)
The idea of plasma_unlimited is to fallback allocate objects to disk and it will success as long as we have disk space available. However, when we running [non_streaming_shuffle_1tb_5000_partitions](https://github.com/ray-project/ray/blob/master/release/nightly_tests/nightly_tests.yaml#L144), we will hit the 65535 open fd limits and crash the raylet. An idea fix could be group multiple fallback allocations into one mmap file.

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment] 2021-08-13 01:39
[note from offline discussion]: The root cause of this seems to be object unpinning taking longer than the 2 second spill grace period. So even though we shouldn't be fallback allocating while spilling is happening, we still do.

**Comment by ericl** [comment] 2021-09-07 19:57
[resolved by batch obod pr]

**Closed by ericl** 2021-09-07 19:57 UTC
Labels: bug, P1
