### ISSUE TITLE
Ray seems to be caching the imported .py even after code terminates

### ISSUE THREAD

**Issue by TBashida** [ray-project/ray#8550] opened 2020-05-22 08:04 UTC
I am testing ray on 1 head node and 1 cluster node.
I started the head node with:

    ray start --head --redis-port=6379

and the cluster node with:

    ray start --address='<ip_head_node>:6379'

At both the head node and the cluster node, there is f.py & ray_test.py

f.py:

    def f(num):
        print("f:", num)
        return num

ray_test.py:

    import ray
    import f

    @ray.remote
    def r(num):
          return f.f(num)

     if __name__ == "__main__":
        num_tasks = 8
        ray.init(address="auto")
        result_ids = [r.remote(t) for t in range(num_tasks)]
        results = ray.get(result_ids)
        print(results)

running:

    python ray_test.py

works fine.

But, when I modify f.py, (eg. change the print statement), on **BOTH** head and cluster node, (both head node and cluster node have the same f.py because I'm rsync-ing it over and also verifying on the cluster node), subsequent:

    python ray_test.py

still uses the **OLD** f.py

I've even tried deleting f.py on the cluster node, but the code still runs when it shouldn't (??) So it seems that f.py is being cached somewhere? Or am I missing something?

### What is your question?

My goal is to be able to modify f.py on both head, rsync it to the cluster node, and run ray using the *NEW* f.py, without stopping and restarting ray on both head and cluster. Is that possible?

Thanks!

Python 3.6.9
ray==0.8.5

**Comment by rkooo567** [comment] 2020-05-25 05:08
Yes. The function is cached based on its module name + function name, and pickled function hash. This seems to happen because although the function f is modified, the remote function function descriptor is not changed (because remote function's function hash, module name, and function name is still the same after f is changed). 

@edoakes Isn't it a bug or expected behavior? It seems to happen because `execution_info` only caches function_descriptor, not function_descriptor + job_id. (https://github.com/ray-project/ray/blob/860eb6f13a0e570b95bd251eb53105473850cbdc/python/ray/_raylet.pyx#L349)
Is there any reason why we don't cache functions based on job_id + function_descriptor?

**Comment by TBashida** [comment] 2020-05-25 11:01
Ok thanks for the response! I thought I was imagining things ...

For my 2c worth ... I think the behaviour should not be the case, because that goes against what import is supposed to do. I get it that caching has obvious speed advantages, but at the very least this feature/bug should be documented. I spent quite a while looking at various parameters to use on ray.init(), hoping to force it to NOT use any memory to cache stuff, but obviously to no avail. 

If only there was a flag (yet another flag ?!!) to turn this feature on/off... Would caching the function last modified datetime make things simpler? Just a thought.

Don't get me wrong, I think that Ray is truly awesome and I'm very thankful for the work you guys have put into it. I think that Ray is something that **should** be built in to Python! Looking forward to seeing which way this is going to go. Thanks again!

**Comment by ericl** [comment] 2020-05-28 21:56
This would probably be resolved in the future with proper multitenancy support between drivers.

**Comment by rkooo567** [comment] 2020-09-19 09:00
@TBashida Can you check if it is still the case in the latest master? As far as I understood this could've been fixed already.

**Comment by rkooo567** [comment] 2020-10-22 06:44
@ericl Bump up the priority of this task as multi tenancy is turned on by default.

**Comment by rkooo567** [comment] 2020-10-27 04:37
This is actually already resolved in the latest master

**Closed by rkooo567** 2020-10-27 04:37 UTC
Labels: P1, bug, core
