### ISSUE TITLE
User has no control over TorchPolicy migrating model to GPU [rllib]

### ISSUE THREAD

**Issue by roireshef** [ray-project/ray#8579] opened 2020-05-24 08:22 UTC
### What is the problem?
in the constructor in /usr/local/lib/python3.6/dist-packages/ray/rllib/policy/torch_policy.py there's casting of torch model to GPU if CUDA is available, regardless of a user's preference not to use GPU. I believe this should be controlled by `num_gpus` and `num_gpus_per_worker`. Current setup ends up with incompatibility when rollout samples are on CPU and model on GPU, etc.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray version is 0.8.5, Torch 1.3.0

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

**Use any environment with PyTorch (I use custom Flow environment + A3C), and set num_gpus to 0.**

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by ericl** [comment] 2020-05-24 20:36
Ray sets CUDA_VISIBLE_DEVICES based on those configs to assign GPUs, so it should be working as you mention.

To clarify, is the report that this restriction is not working as expected on a GPU machine (device being detected despite ray setting the env var)?

**Comment by roireshef** [comment] 2020-05-30 11:08
@ericl - the condition in this line is wrong https://github.com/ray-project/ray/blob/master/rllib/policy/torch_policy.py#L77

Even if CUDA is available, user doesn't always like to use it. The config param that controls using GPU or not AFAIK is num_gpus (or num_gpus_per_worker). If it is set to 0, there is no reason to move model tensors to cuda device here.

**Comment by ericl** [comment] 2020-05-30 20:52
Hmm shouldn't that return false if CUDA_VISIBLE_DEVICES is set to empty
string? Ray is setting that to selectively enable GPU for certain actors as
requested only.

**Comment by roireshef** [comment] 2020-06-21 20:12
@ericl - Sorry it took me so much time to respond. 
Are you suggesting I manually unset an environment variable named CUDA_VISIBLE_DEVICES? Or is it a Tune/RLlib config parameter? 

Also, what happens in the case of IMPALA - was it tested to work? AFAIK in IMPALA the model should be stored in CPU mode (RAM) for the workers, while it is stored in GPU mode for the master/optimizer.

**Comment by ericl** [comment] 2020-06-21 20:59
> since it didn't make sense to find out a GPU is used if you already set num_gpus to 0.

The reason this is the case is that num_gpus only applies to the learner. The workers are configured separately. Ray will ensure the GPUs are made visible as configured, so cuda.is_available() should be the right check.

Basically: always use the RLlib config to assign GPUs to the learner or workers, and Ray will do the right thing.

**Comment by roireshef** [comment] 2020-06-22 17:39
> Basically: always use the RLlib config to assign GPUs to the learner or workers, and Ray will do the right thing.

I take it that you are referring to num_gpus and num_gpus_per_worker when you write RLlib config. Well, if yes, then this is not the case today - if you set both of them to 0, you still get the model parameters moved to the GPU since cuda.is_available() returns True, and IMHO this is not the desired behavior. It sounds natural to me that _num_gpus_ and _num_gpus_per_worker_ will override <cuda.is_available() returns True>, since those are the hooks for the user to control GPU usage in the config.

Do you agree?

**Comment by ericl** [comment] 2020-06-22 17:51
Are you saying that `torch.cuda.is_available()` returns True for you even if both are set to zero? That's very unexpected. To verify, what does this print for you:

```
@ray.remote(num_gpus=0)
def f():
   print(torch.cuda.is_available())

ray.init()
ray.get(f.remote())
```

**Comment by roireshef** [comment] 2020-06-22 20:12
> Are you saying that `torch.cuda.is_available()` returns True for you even if both are set to zero? That's very unexpected. To verify, what does this print for you:
> 
> ```
> @ray.remote(num_gpus=0)
> def f():
>    print(torch.cuda.is_available())
>    print(os.environ.get("CUDA_VISIBLE_DEVICES"))
> 
> ray.init()
> ray.get(f.remote())
> ```

Short answer is yes. I can re-verify tomorrow with newest 0.9dev version, but last time I checked, about a month ago, _torch.cuda.is_available() returned True_ even when I set _num_gpus=0_

**Comment by ericl** [comment] 2020-06-22 20:24
The ray param overrides CUDA_VISIBLE_DEVICES, which *should* be respected by pytorch (it is respected by tensorflow, etc). There might be some bug where this isn't the case.

**Comment by ericl** [comment] 2020-06-26 21:18
This doesn't seem to be the case as of torch 1.4. I'm going to close this; feel free to reopen if you can reproduce otherwise with a recent torch version.

```
>>> import torch
>>> torch.__version__
'1.4.0'
>>> torch.cuda.is_available()
True
```
```
>>> import torch
>>> import os
>>> @ray.remote(num_gpus=0)
... def f():
...    print(torch.cuda.is_available())
...    print(os.environ.get("CUDA_VISIBLE_DEVICES"))
... 
>>> 
>>> f.remote()
ObjectID(f66d17bae2b0e765ffffffff010000c001000000)
>>> (pid=61816) False
```

**Closed by ericl** 2020-06-26 21:18 UTC
Labels: P1, bug
