### ISSUE TITLE
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:165) Killed worker pid 549 which hadn't started yet.

### ISSUE THREAD

**Issue by i4hashmi** [ray-project/ray#1421] opened 2018-01-13 06:21 UTC
[code.zip](https://github.com/ray-project/ray/files/1628118/code.zip)

### System information
- **OS Platform and Distribution (Ubuntu 16.04.2 LTS as subsystem on windows 10)**:
- **Ray installed from (pip3 install ray)**:
- **Ray version**: (0.3.0)
- **Python version**: (Python 3.5.2)
- **Exact command to reproduce**:

### Describe the problem
 I am running a code which has to read a csv file, extract data from it and find the links in data using loops. The csv file is quite big (not the biggest one yet) and has a lot of data in it. If I run it using simple version of the script without ray, it takes the whole day but works fine. I wanted to parallelize it and read about ray. I used ray correctly and when I run the script, it gives the following output and gets killed without producing any output: I am attaching it with the small csv file which can reproduce the problem.

hashmi@hashmi-PC:/mnt/d/bash$ **python3 CascadeDataStream.py**
Waiting for redis server at 127.0.0.1:33116 to respond...
Waiting for redis server at 127.0.0.1:59546 to respond...
Allowing the Plasma store to use up to 3.40746GB of memory.
Starting object store with directory /dev/shm and huge page support disabled
Starting local scheduler with 8 CPUs, 0 GPUs

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui62273.ipynb?token=52b74343d883dae0e66f66b2464fc2113919bbe15e46e5a7
======================================================================

Disconnecting client on fd 9
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:165) Killed worker pid 549 which hadn't started yet.
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:165) Killed worker pid 550 which hadn't started yet.
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:165) Killed worker pid 551 which hadn't started yet.
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:165) Killed worker pid 552 which hadn't started yet.
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:165) Killed worker pid 553 which hadn't started yet.
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:165) Killed worker pid 554 which hadn't started yet.
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:165) Killed worker pid 555 which hadn't started yet.
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:165) Killed worker pid 556 which hadn't started yet.
Disconnecting client on fd 7
Disconnecting client on fd 5

### Source code / logs
I have attached the source code with the input file which can be run directly.
Here is the code:

`import csv
import sys
import ray

ray.init()

@ray.remote
def extractdata(file):
    List_of_Data = [] # A list to save all the csv data in it
    f = open(file, 'r', encoding="utf8")
    file_read = csv.reader(f, delimiter=';', quoting=csv.QUOTE_NONE)
    for row in file_read:
        List_of_Data.append(row)
    return List_of_Data

@ray.remote
def writeCSV(list_to_write, OutputFileName):
    file = open(OutputFileName, 'w', newline='')
    writer = csv.writer(file, quotechar='"', delimiter=';',quoting=csv.QUOTE_ALL, skipinitialspace=True)
    for row in list_to_write:
        writer.writerow(row)

@ray.remote
def data_to_nodes(list_of_all_data):
    node_list = []
    for item in list_of_all_data:
        if item[2] != "":
            sublist = [item[0], item[1]] 
            identifier_list = []  
            identifiers = item[2].split(",")
            for identifier in identifiers:
                identifier_list.append(identifier)
            sublist.append(identifier_list) 
            node_list.append(sublist)
    return node_list

@ray.remote
def nodes_to_formatted_nodes(list_of_nodes):
    formatted_nodes = []
    for item in list_of_nodes:
        sublist = []
        sublist.append(str(item[0]))
        sublist.append(item[1])
        sublist.append(','.join(map(str, item[2])))
        formatted_nodes.append(sublist)
    return formatted_nodes
         
InFile = "examples/wikipedia.csv"
InFileName = InFile.split('\\').pop().split('/').pop().rsplit('.', 1)[0]

AllData = extractdata.remote(InFile)

nodes = data_to_nodes.remote(AllData)

nodes_formatted = nodes_to_formatted_nodes.remote(nodes)

writeCSV.remote(nodes_formatted,'output_files/'+InFileName+'-nodes.csv')`

@ray.remote
def nodes_to_links(nodes_list):
    output_list = []
    for ii, elem in enumerate(nodes[:-1]):  s
        for jj in range(ii + 1, len(nodes)):
            common = set(elem[-1]).intersection(
                set(nodes[jj][-1]))  
            if len(common) > 0 and common != {''}:  
                output_list.append([elem[0], nodes[jj][0], ','.join(
                    map(str, list(common)))])  
    return output_list                          

links = nodes_to_links.remote(nodes)

**Comment by i4hashmi** [comment] 2018-01-13 06:22
I don't know why it is not showing anything I wrote. :(

**Comment by robertnishihara** [comment] 2018-01-15 00:42
It looks to me like you are submitting some tasks (e.g., by calling `nodes_to_links.remote(nodes)`) but then the script is exiting before those tasks have completed (which causes the Ray processes to shutdown, which is why the local scheduler is killing some workers).

Basically, I think you need to issue a blocking call like

```python
result = ray.get(links)
```

as well as 

```python
write_id = writeCSV.remote(nodes_formatted,'output_files/'+InFileName+'-nodes.csv')`
# We aren't interested in the return value here, just the side effect.
# But we need to wait for the task to finish
ray.get(write_id)
```

**Comment by robertnishihara** [comment] 2018-02-02 07:44
Closing because I think the problem is identified in the previous comment. Please reopen if that's not the case.

**Closed by robertnishihara** 2018-02-02 07:44 UTC
