### ISSUE TITLE
[Datasets] `split_at_indices` hangs

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#18285] opened 2021-09-01 20:14 UTC
Running this script hangs with the below warning:
```
import math

import ray
from ray.data import Dataset, from_items

ds = from_items([1, 2, 3, 4])
ds = ds.repeat(2).random_shuffle()

def _split_dataset(dataset, num_workers):
    # First make sure size of dataset is divisible by num_workers.
    dataset_size = dataset.count()
    total_rows = math.ceil(dataset_size / num_workers) * num_workers
    assert dataset_size <= total_rows
    # Pad the dataset so it's divisible by ``num_workers``.
    if dataset_size < total_rows:
        dataset = dataset.union(
            dataset.limit(limit=total_rows - dataset_size))
    assert dataset.count() == total_rows

    per_worker_size = total_rows / num_workers
    split_indices = [per_worker_size*(i+1) for i in range(num_workers-1)]
    datasets = dataset.split_at_indices(split_indices)
    assert [ds.count() == datasets[0].count() for ds in datasets]
    return datasets

dataset_splits = _split_dataset(ds, num_workers=2)

@ray.remote
def train(ds):
	for batch in ds.iter_batches():
		print(batch)

ray.get(train.remote(ds) for ds in dataset_splits)
```

```
Warning: shard 0 of the pipeline has been stalled more than 10.0s waiting for other shards to catch up.
Warning: shard 0 of the pipeline has been stalled more than 20.0s waiting for other shards to catch up.
Warning: shard 0 of the pipeline has been stalled more than 40.0s waiting for other shards to catch up.
Warning: shard 0 of the pipeline has been stalled more than 80.0s waiting for other shards to catch up.
Warning: shard 0 of the pipeline has been stalled more than 160.0s waiting for other shards to catch up.
```

**Comment by scv119** [comment] 2021-09-02 06:47
I've noticed this as well while trying to repro https://github.com/ray-project/ray/issues/18101

**Comment by clarkzinzow** [comment] 2021-09-03 21:55
@amogkam The issue is caused by synchronously calling `.count()` on each individual shard pipeline, which blocks and consumes the first shard pipeline:
```python
assert [ds.count() == datasets[0].count() for ds in datasets]
```
As indicated in the `DatasetPipeline.split()` [docs](https://docs.ray.io/en/master/data/package-ref.html#ray.data.dataset_pipeline.DatasetPipeline.split), consuming a single shard will hang forever since the splits are expected to be consumed in parallel:

> Implementation detail: this launches a coordinator actor that is used to execute the pipeline and push data blocks to each pipeline shard. Reading from an individual shard will be blocked if other shards are falling behind. A warning will be printed if a shard has been blocked on read for more than 10 seconds.

So, blocking on consumption of a single shard isn't supported. If you ever really need to get the count of all splits, you should be able to if you count them all in tasks:
```python
@ray.remote
def count(pipe):
    return pipe.count()

counts = [count.remote(shard) for shard in shards]
assert len(set(counts)) == 1
```

We should probably make this more clear in the docs for `DatasetPipeline.split()` and `DatasetPipeline.split_at_indices()`, and maybe include a note about this in the logged warning message.

Closing this as unsupported for now, but I'll add this to the usability tracker issue: #18262

**Closed by clarkzinzow** 2021-09-03 21:55 UTC
Labels: bug, P0
