### ISSUE TITLE
Feeing up memory using ray.internal.free

### ISSUE THREAD

**Issue by hlbkin** [ray-project/ray#4571] opened 2019-04-06 16:12 UTC
Hi Team!

I want to free memory from some of the dataset objects we are using

1) We pin the object using "pin_in_object_store(object))" function
2) ray.internal.free([object_id]) require some object_id which should be instance of ray.ObjectId

The only workaround I've found is modifying source code like that

Is there any other way to do it? 

```def pin_in_object_store(obj):
    """Pin an object in the object store.

    It will be available as long as the pinning process is alive. The pinned
    object can be retrieved by calling get_pinned_object on the identifier
    returned by this call.
    """

    obj_id = ray.put(_to_pinnable(obj))
    _pinned_objects.append(ray.get(obj_id))
    return "{}{}".format(PINNED_OBJECT_PREFIX,
                         base64.b64encode(obj_id.binary()).decode("utf-8")), obj_id```

**Comment by raulchen** [comment] 2019-04-10 06:40
cc @ericl

**Comment by robertnishihara** [comment] 2019-04-10 06:48
Hi @hlbkin, I don't really understand the question. `pin_in_object_store(object))` returns on object ID, so you can just pass that into `ray.internal.free`, right?

**Comment by ericl** [comment] 2019-04-10 06:54
I think the issue is the return is an encoded object id.

Since the pin function is simply a wrapper around ray APIs, I would recommend copying it into your codebase and modifying it as needed.

**Comment by neychev** [comment] 2019-04-24 15:07
Seems similar to issue #4512

**Comment by rkooo567** [comment] 2020-10-12 03:43
This should be resolved by automatic memory management using distributed ref count.

**Closed by rkooo567** 2020-10-12 03:43 UTC
