### ISSUE TITLE
[CI] `linux://rllib:learning_tests_cartpole_crashing_and_stalling_appo` is failing/flaky on master.

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#41792] opened 2023-12-11 18:25 UTC
- d7926fad6e4c793566a4f8639c55112c8bebfdb9 FAILED [Buildkite :brain: rllib: learning tests tf2-static-graph](https://buildkite.com/ray-project/postmerge/builds/2063#018c588a-bb45-43c7-b895-dfbc1a15ee17)
- 6fe398f4cbb7c2797ccd04ee7dd516401f782b34 FAILED [Buildkite :brain: rllib: learning tests tf2-static-graph](https://buildkite.com/ray-project/postmerge/builds/2059#018c5627-f92d-4362-9cfa-4ccabbf14f36)
- cb5bb4e7763994db4f4e765ce9dc74376d7eedca FAILED [Buildkite :brain: rllib: learning tests tf2-static-graph](https://buildkite.com/ray-project/postmerge/builds/2038#018c5003-960f-4263-89fe-a679a116c257)
- 2307fd1d5ce38182d2967e0275e494aac10f2924 FAILED [Buildkite :brain: rllib: learning tests tf2-static-graph](https://buildkite.com/ray-project/postmerge/builds/2029#018c4ed8-3c05-4b63-af16-44c029d057c7)
- b71e1c358b7b0a4ab5c1f7ffc0db807dc4f908d8 FAILED [Buildkite :brain: rllib: learning tests pytorch](https://buildkite.com/ray-project/postmerge/builds/2028#018c4e3d-faa8-4fb9-8d40-f7319977e874)
- b71e1c358b7b0a4ab5c1f7ffc0db807dc4f908d8 FAILED [Buildkite :brain: rllib: learning tests tf2-static-graph](https://buildkite.com/ray-project/postmerge/builds/2026#018c4cc3-d5e4-4848-8092-c378bddaca6f)
- b71e1c358b7b0a4ab5c1f7ffc0db807dc4f908d8 FAILED [Buildkite :brain: rllib: learning tests tf2-static-graph](https://buildkite.com/ray-project/postmerge/builds/2028#018c4e3d-faa5-42ac-b4d8-e66104203c96)
- 84ba97155f1b1281320abdbcfb6483779fc16d7e FAILED [Buildkite :brain: rllib: learning tests tf2-static-graph](https://buildkite.com/ray-project/postmerge/builds/2025#018c4c7a-ec4e-4a33-a7e9-0088df5c385a)
- 956317a9fedf6bb23618ff80e5eee404d5938141 FAILED [Buildkite :brain: rllib: learning tests pytorch](https://buildkite.com/ray-project/postmerge/builds/2024#018c4c6a-34f4-403c-a2f5-1a917d751132)
- 284617dd54cc1bd1866de4d9d41c4c5525b892ad FAILED [Buildkite :brain: rllib: learning tests pytorch](https://buildkite.com/ray-project/postmerge/builds/2022#018c4c11-920a-4621-ad7c-1a9e5f9a5dae)
- 284617dd54cc1bd1866de4d9d41c4c5525b892ad FAILED [Buildkite :brain: rllib: learning tests tf2-static-graph](https://buildkite.com/ray-project/postmerge/builds/2022#018c4c11-9206-41e3-984b-700a888edfc1)
- ab36f94aaa009cd4f1cc7d0b49c996aece5e121b FAILED [Buildkite :brain: rllib: learning tests pytorch](https://buildkite.com/ray-project/postmerge/builds/2020#018c4c08-2c69-4de5-bc38-9cecfc9a1b4b)
- 2f29500b07166f37704e283f4a9efac72e6caf4c FAILED [Buildkite :brain: rllib: learning tests tf2-static-graph](https://buildkite.com/ray-project/postmerge/builds/2019#018c4c2b-e50c-444f-ac7d-8f9ee36074b7)
- 208e4526265acfeaad7cf312a5168b8a3925173a FAILED [Buildkite :brain: rllib: learning tests pytorch](https://buildkite.com/ray-project/postmerge/builds/2016#018c4bd4-a4ac-4a5d-98f2-47a6de16ea51)
- 567e5744b255899d54f5b048646e4bd4caf64fc0 FAILED [Buildkite :brain: rllib: learning tests pytorch](https://buildkite.com/ray-project/postmerge/builds/2015#018c4b80-ab67-40d1-aed8-e0bd79e9e218)
- d6d26890a74ae12ca32fd0bb6a5cffe10b2fe3c9 FAILED [Buildkite :brain: rllib: learning tests pytorch](https://buildkite.com/ray-project/postmerge/builds/2014#018c4bad-8927-4ab1-b683-f24e14423c17)
- 24875534ae69659562c4ef304a698dcd502c76ca FAILED [Buildkite :brain: rllib: learning tests tf2-static-graph](https://buildkite.com/ray-project/postmerge/builds/2012#018c4b18-6b9c-475b-ab13-24054d01cd32)
- aa86ef664a971aee660feb968fa58765b5e72bca FAILED [Buildkite :brain: rllib: learning tests pytorch](https://buildkite.com/ray-project/postmerge/builds/2011#018c4b6a-ec4c-4cd1-8dc0-ccaa5e0e0d0b)
- 70019824e7f623809fcd56a914873b32150b1884 FAILED [Buildkite :brain: rllib: learning tests pytorch](https://buildkite.com/ray-project/postmerge/builds/2010#018c4b09-4d34-4395-9cb5-8189a3596274)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://rllib:learning_tests_cartpole_crashing_and_stalling_appo-END
....

**Comment by simonsays1980** [comment] 2023-12-19 15:29
So far I cannot reproduce any of these errors on my Linux platform. Tomorrow I can hopefully tell more.

**Comment by sven1977** [comment] 2024-07-09 07:08
Test has been renamed. Closing this issue in favour of this one here: https://github.com/ray-project/ray/issues/46051

**Closed by sven1977** 2024-07-09 07:08 UTC
Labels: bug, P0, rllib, flaky-tracker
