### ISSUE TITLE
Can't install Ray from source on OS X

### ISSUE THREAD

**Issue by barrachri** [ray-project/ray#1719] opened 2018-03-14 07:51 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OS X 10.13.3
- **Ray installed from (source or binary)**: master version from git 
- **Ray version**: master
- **Python version**: Python 3.6.4
- **Exact command to reproduce**:

### Describe the problem
I am trying to install ray locally, to run some tests, but the installation process fails.

### Source code / logs

output of `pip install -e python --verbose`
```
    CMake Error at cmake_modules/BuildUtils.cmake:88 (message):
      No static or shared library provided for boost_system
    Call Stack (most recent call first):
      cmake_modules/ThirdpartyToolchain.cmake:249 (ADD_THIRDPARTY_LIB)
      CMakeLists.txt:292 (include)


    -- Configuring incomplete, errors occurred!
    See also "/Users/cbarra/Projects/oss/ray/thirdparty/build/arrow/cpp/build/CMakeFiles/CMakeOutput.log".
    See also "/Users/cbarra/Projects/oss/ray/thirdparty/build/arrow/cpp/build/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/cbarra/Projects/oss/ray/python/setup.py", line 133, in <module>
        license="Apache 2.0")
      File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/setuptools/command/develop.py", line 36, in run
        self.install_for_development()
      File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/cbarra/Projects/oss/ray/python/setup.py", line 62, in run
        subprocess.check_call(["../build.sh", sys.executable])
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['../build.sh', '/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/bin/python3']' returned non-zero exit status 1.
Cleaning up...
Command "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/bin/python3 -c "import setuptools, tokenize;__file__='/Users/cbarra/Projects/oss/ray/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Users/cbarra/Projects/oss/ray/python/
Exception information:
Traceback (most recent call last):
  File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/pip/req/req_install.py", line 845, in install
    install_options, global_options, prefix=prefix)
  File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/pip/req/req_install.py", line 1007, in install_editable
    show_stdout=False)
  File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/bin/python3 -c "import setuptools, tokenize;__file__='/Users/cbarra/Projects/oss/ray/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Users/cbarra/Projects/oss/ray/python/
```
```
# cat /Users/cbarra/Projects/oss/ray/thirdparty/build/arrow/cpp/build/CMakeFiles/CMakeError.log
Performing C++ SOURCE FILE Test CXX_SUPPORTS_ALTIVEC failed with the following output:
Change Dir: /Users/cbarra/Projects/oss/ray/thirdparty/build/arrow/cpp/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_3ee4a/fast"
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_3ee4a.dir/build.make CMakeFiles/cmTC_3ee4a.dir/build
Building CXX object CMakeFiles/cmTC_3ee4a.dir/src.cxx.o
/Library/Developer/CommandLineTools/usr/bin/c++    -g -O3 -DCXX_SUPPORTS_ALTIVEC   -maltivec -o CMakeFiles/cmTC_3ee4a.dir/src.cxx.o -c /Users/cbarra/Projects/oss/ray/thirdparty/build/arrow/cpp/build/CMakeFiles/CMakeTmp/src.cxx
clang: error: invalid argument '-faltivec' only allowed with 'ppc/ppc64/ppc64le'
make[1]: *** [CMakeFiles/cmTC_3ee4a.dir/src.cxx.o] Error 1
make: *** [cmTC_3ee4a/fast] Error 2

Source file was:
int main() { return 0; }
```

**Comment by devin-petersohn** [comment] 2018-03-14 16:20
Hi @barrachri, Do you have all the prerequisites from the [readthedocs](http://ray.readthedocs.io/en/latest/index.html) page?

**Comment by barrachri** [comment] 2018-03-14 16:54
Hi @devin-petersohn,

yes, I followed this part: http://ray.readthedocs.io/en/latest/installation.html#building-ray-from-source

**Comment by robertnishihara** [comment] 2018-03-14 16:57
Hm, we're compiling boost from source now as part of our build process. It's possible that cmake has cached some outdated information. Could you try removing the entire ray directory and trying installation again? If that fails, can you post the entire output of installation (I know it's long)?

**Comment by barrachri** [comment] 2018-03-14 18:00
I deleted the my `ray` folder and cloned it again.

```bash
Warning: cmake 3.10.2 is already installed
Warning: pkg-config 0.29.2 is already installed
Warning: automake 1.16.1 is already installed
Warning: autoconf 2.69 is already installed
Warning: libtool 2.4.6_1 is already installed
Warning: openssl 1.0.2n is already installed
Warning: bison 3.0.4_1 is already installed
Warning: wget 1.19.4_1 is already installed
```

```
    Scanning dependencies of target thrift-deps
    make[2]: *** No rule to make target `thrift_ep/src/thrift_ep-install/lib/libthrift.a', needed by `src/parquet/parquet_types.cpp'.  Stop.
    make[1]: *** [CMakeFiles/thrift-deps.dir/all] Error 2
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/cbarra/Projects/oss/ray/python/setup.py", line 138, in <module>
        license="Apache 2.0")
      File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/setuptools/command/develop.py", line 36, in run
        self.install_for_development()
      File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/cbarra/Projects/oss/ray/python/setup.py", line 67, in run
        subprocess.check_call(["../build.sh", sys.executable])
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['../build.sh', '/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/bin/python3']' returned non-zero exit status 2.
Cleaning up...
Command "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/bin/python3 -c "import setuptools, tokenize;__file__='/Users/cbarra/Projects/oss/ray/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Users/cbarra/Projects/oss/ray/python/
Exception information:
Traceback (most recent call last):
  File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/pip/req/req_install.py", line 845, in install
    install_options, global_options, prefix=prefix)
  File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/pip/req/req_install.py", line 1007, in install_editable
    show_stdout=False)
  File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/bin/python3 -c "import setuptools, tokenize;__file__='/Users/cbarra/Projects/oss/ray/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Users/cbarra/Projects/oss/ray/python/
```

**Comment by richardliaw** [comment] 2018-03-15 06:19
bumping this - looks like the main problem starts at 
`    -- Thrift compiler/libraries NOT found:  (THRIFT_INCLUDE_DIR-NOTFOUND, THRIFT_STATIC_LIB-NOTFOUND). Looked in system search paths.`

Maybe this comment is relevant? https://github.com/ray-project/ray/issues/1553#issuecomment-366573422

**Comment by pcmoritz** [comment] 2018-03-15 20:10
It looks like thrift is being compiled, but _after_ parquet-cpp is searching for it. Maybe some bug in the parallel build? What happens if you remove the `-j4` from the make command in line the line "make -j4" in `ray/thirdparty/scripts/build_parquet.sh`?

**Comment by barrachri** [comment] 2018-03-15 20:30
`

``bash
#!/bin/bash

set -x

# Cause the script to exit if a single command fails.
set -e

unamestr="$(uname)"
TP_DIR=$(cd "$(dirname "${BASH_SOURCE:-$0}")"; pwd)/../
PARQUET_HOME=$TP_DIR/pkg/arrow/cpp/build/cpp-install
OPENSSL_DIR=/usr/local/opt/openssl
BISON_DIR=/usr/local/opt/bison/bin

if [ ! -d $TP_DIR/build/parquet-cpp ]; then
  git clone https://github.com/apache/parquet-cpp.git "$TP_DIR/build/parquet-cpp"
  pushd $TP_DIR/build/parquet-cpp
  git fetch origin master
  git checkout 76388ea4eb8b23656283116bc656b0c8f5db093b

  if [ "$unamestr" == "Darwin" ]; then
    OPENSSL_ROOT_DIR=$OPENSSL_DIR \
    PATH="$BISON_DIR:$PATH" \
    BOOST_ROOT=$TP_DIR/pkg/boost \
    ARROW_HOME=$TP_DIR/pkg/arrow/cpp/build/cpp-install \
    cmake -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=$PARQUET_HOME \
          -DPARQUET_BUILD_BENCHMARKS=off \
          -DPARQUET_BUILD_EXECUTABLES=off \
          -DPARQUET_BUILD_TESTS=off \
          .

    OPENSSL_ROOT_DIR=$OPENSSL_DIR \
    PATH="$BISON_DIR:$PATH" \
    make

    OPENSSL_ROOT_DIR=$OPENSSL_DIR \
    PATH="$BISON_DIR:$PATH" \
    make install
  else
    BOOST_ROOT=$TP_DIR/pkg/boost \
    ARROW_HOME=$TP_DIR/pkg/arrow/cpp/build/cpp-install \
    cmake -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=$PARQUET_HOME \
          -DPARQUET_BUILD_BENCHMARKS=off \
          -DPARQUET_BUILD_EXECUTABLES=off \
          -DPARQUET_BUILD_TESTS=off \
          .

    PARQUET_HOME=$TP_DIR/pkg/arrow/cpp/build/cpp-install \
    BOOST_ROOT=$TP_DIR/pkg/boost \
    make
    make install
  fi

  popd
fi
```

**Comment by robertnishihara** [comment] 2018-03-16 06:14
I've definitely seen this error before, I think I fixed it by doing `brew install openssl bison` before installing.

**Comment by robertnishihara** [comment] 2018-03-16 06:16
Looks like you have the installed already, but perhaps they're older versions? Would uninstalling and reinstalling them help?

**Comment by barrachri** [comment] 2018-03-16 06:23
Let me try to installing them again, this are my current versions:
```
autoconf 2.69
automake 1.16.1
bison 3.0.4_1
cmake 3.10.2
gettext 0.19.8.1
libidn2 2.0.4
libtool 2.4.6_1
libunistring 0.9.9
openssl 1.0.2n
pkg-config 0.29.2
rbenv 1.1.1
ruby-build 20180224 20171226
wget 1.19.4_1
```

**Comment by barrachri** [comment] 2018-03-16 06:44
No still complaining...

```
   CMake Error at cmake_modules/BuildUtils.cmake:88 (message):
      No static or shared library provided for boost_system
    Call Stack (most recent call first):
      cmake_modules/ThirdpartyToolchain.cmake:249 (ADD_THIRDPARTY_LIB)
      CMakeLists.txt:292 (include)


    -- Configuring incomplete, errors occurred!
    See also "/Users/cbarra/Projects/oss/ray/thirdparty/build/arrow/cpp/build/CMakeFiles/CMakeOutput.log".
    See also "/Users/cbarra/Projects/oss/ray/thirdparty/build/arrow/cpp/build/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/cbarra/Projects/oss/ray/python/setup.py", line 133, in <module>
        license="Apache 2.0")
      File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/setuptools/command/develop.py", line 36, in run
        self.install_for_development()
      File "/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/lib/python3.6/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/cbarra/Projects/oss/ray/python/setup.py", line 62, in run
        subprocess.check_call(["../build.sh", sys.executable])
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['../build.sh', '/Users/cbarra/.local/share/virtualenvs/ray-sA7mnjJX/bin/python3']' returned non-zero exit status 1.
```
I am wondering if this could be somehow related too:

```
==> Pouring openssl-1.0.2n.high_sierra.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the SystemRoots
keychain. To add additional certificates (e.g. the certificates added in
the System keychain), place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local,
because Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.zshrc

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2n: 1,792 files, 12.3MB
==> Downloading https://homebrew.bintray.com/bottles/bison-3.0.4_1.high_sierra.bottle.tar.gz
Already downloaded: /Users/cbarra/Library/Caches/Homebrew/bison-3.0.4_1.high_sierra.bottle.tar.gz
==> Pouring bison-3.0.4_1.high_sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because some formulae require a newer version of bison.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/bison/bin:$PATH"' >> ~/.zshrc

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/bison/lib
```

**Comment by robertnishihara** [comment] 2018-03-16 07:12
That's really strange. I'm not too sure what the issue is here. In the worst case, we can make compilation with parquet optional, since we're only using so that we can use parquet with pyarrow.

**Comment by barrachri** [comment] 2018-03-17 09:30
Thanks for the help, at the end I gave up and switched to docker 👍 

Feel free to close this.

**Comment by robertnishihara** [comment] 2018-03-20 07:56
Ok, closing since we're unlikely to make more progress on this.

If anyone else runs into this issue or has further ideas, please comment or reopen.

**Closed by robertnishihara** 2018-03-20 07:56 UTC
Labels: installation

**Comment by raulchen** [comment] 2018-05-08 05:04
I saw the same error on my mac. 
The problem is because something goes wrong when building thrift. (I didn't exactly figure out why. it seemed to me that thrift was still using built-in bison instead of the brew one.)
`brew install thrift` fixed the issue for me.

**Comment by heyucongtom** [comment] 2018-05-21 19:46
Similar things happen when I am trying to compile from source.

It pops the error on #1 before. (also pops up that I need to install jdk). After I install it and redo pip install -e , this error comes up:
 -- Checking for module 'parquet'
    --   No package 'parquet' found
    --  Could not find the parquet library. Looked in  system search paths.
    CMake Error at CMakeLists.txt:338 (message):
      Unable to locate Parquet libraries

**Comment by robertnishihara** [comment] 2018-05-22 01:42
Can you create a new issue and include the entire stderr/stdout from installation?

It definitely shouldn't require jdk.

As for parquet, can you make sure to run the lines

```
brew update
brew install cmake pkg-config automake autoconf libtool openssl bison wget

pip install cython
```

**Comment by heyucongtom** [comment] 2018-05-22 01:53
Thanks Robert.

I followed the #1953 and reinstall to solve the problem.

Interestingly the jdk only pops up when I install ray from the first
installation. I would try to re-trigger it on a new MacOS system.

**Comment by robertnishihara** [comment] 2018-05-22 07:06
Ok, good to know. There are some java related changes to the build system in https://github.com/ray-project/ray/pull/2092 though it shouldn't be touched by the python installation path.

**Comment by fywu85** [comment] 2018-06-10 01:41
I am able to resolve the problem by replacing `make -j4` with `make -j2` in `ray/thirdparty/scripts/build_parquet.sh`.

**Comment by zou000** [comment] 2018-07-11 23:37
I met the same problem in a freshly synced repo.  Instructions in #1953 doesn't work, neither does changing -j4 to -j2 in ray/thirdparty/scripts/build_parquet.sh. `brew install thrift` finally fixed the issue for me.

**Comment by heyucongtom** [comment] 2018-07-16 04:12
The solution I figured out finally is that we download jdk from java
website, uninstall (if installed) ray, re-clone this project, run the
script and then you are done.

Re-starting from the interrupted install would greatly confuse the install
script.

**Comment by chuxi** [comment] 2018-07-25 05:01
brew install thrift

if not work. Thrift is not found when building parquet-cpp. so make it be found.

in thirdparty/scripts/build_parquet.sh

add THRIFT_HOME to the cmake command.

for example:

```bash
    cmake -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=$PARQUET_HOME \
          -DTHRIFT_HOME=/usr/local/opt/thrift \
          -DPARQUET_BUILD_BENCHMARKS=off \
          -DPARQUET_BUILD_EXECUTABLES=off \
          -DPARQUET_BUILD_TESTS=off \
```

reference: https://github.com/apache/parquet-cpp/blob/master/cmake_modules/FindThrift.cmake
