### ISSUE TITLE
Actor support multiple return values

### ISSUE THREAD

**Issue by suquark** [ray-project/ray#856] opened 2017-08-22 22:08 UTC
`num_return_vals` is very useful when distributing return values to different process.
But how should I do these with Ray `Actors`? I haven't found a case for it in Ray's API doc. 

@mitar

**Comment by robertnishihara** [comment] 2017-08-22 22:11
You're right, it currently isn't supported! This is a good idea.

What do you think the syntax should be? It probably requires adding a decorator to the methods that should return multiple return values.

**Comment by suquark** [comment] 2017-08-22 22:29
Yes, decorators are fine in most cases. 

But in my task there's something troublesome. A function may return certain numbers of values according to the input.

I know how to deal with decorator in this way for dynamically adjusting the `num_return_vals`, but not sure how to deal with it with `Actors`.

It looks like
```python
n_outputs = len(self.xxx_num_outputs)
# _executor is a function
executor_warpper = ray.remote(max_calls=1, num_return_vals=n_outputs)(_executor)
ray_object_ids = executor_warpper.remote(....)
```

**Comment by mitar** [comment] 2017-08-22 23:27
Isn't this a duplicate of #750?

**Comment by robertnishihara** [comment] 2017-08-22 23:44
Oh, good catch. I'll close this one.

**Closed by robertnishihara** 2017-08-22 23:44 UTC
Labels: enhancement
