### ISSUE TITLE
ray.wait should not consume current worker

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#2627] opened 2018-08-10 03:57 UTC
The following never finishes:

```python
import ray
import time

ray.init(num_cpus=1)

@ray.remote
def sleep(x):
    time.sleep(x)

@ray.remote
def delegate(x):
    ray.wait([sleep.remote(x)])

ray.get(delegate.remote(30))
```

The issue is demonstrated because there is only one CPU available, so the `sleep` task cannot run because there is no available worker. Surprisingly, the following does work:

```python
@ray.remote
def delegate(x):
    ray.get(sleep.remote(x))
```

It seems that inside `ray.get` Ray is smart enough to release the current worker to the `sleep` task, but for `ray.wait` it is not. I would ask that the same should happen for `ray.wait`. It is clear that the task is not doing anything (just waiting) so it should not be consuming a resource/worker.

Tested with Ray version 0.5.0.

**Comment by suquark** [comment] 2018-08-10 08:59
Yes, ray did the optimization here:

https://github.com/ray-project/ray/blob/f21d783e6d40bfb408a4fde4e107b0c785b7dc84/src/local_scheduler/local_scheduler.cc#L1096-L1113

When `ray.get` is called and blocked, `local_scheduler` will release its resources.

I will try to implement similar settings on `wait`.

**Comment by robertnishihara** [comment] 2018-08-18 06:34
Thanks for point this out, you're right it's a bug. I'm closing because it's a duplicate of #1273.

**Comment by robertnishihara** [comment] 2018-08-18 06:34
It should be fixable purely on the Python side.

**Closed by robertnishihara** 2018-08-18 06:34 UTC
