### ISSUE TITLE
[core] Raylet crash with "unknown resources" when using dynamic resources

### ISSUE THREAD

**Issue by PidgeyBE** [ray-project/ray#11079] opened 2020-09-28 16:58 UTC
### What is the problem?

* Ray 1.0.0rc2
* Running ray autoscale on kubernetes

When autoscaling a second worker, the first worker's raylet crashes.
### Reproduction (REQUIRED)
1. I'm using ray autoscale on kubernetes with the following config:
```
available_node_types:
      def_head:
          node_config: {}
          resources: {"CPU": 1}
          max_workers: 1
      def_worker:
          node_config: {}
          resources: {"CPU": 1, "GPU": 1}
          max_workers: 3
```
2. I deploy an actor requesting 1 GPU -> 1 worker is autoscaled
3. I deploy a second actor requesting 1 GPU -> A second worker is autoscaled, but the first worker's raylet crashes:
```
(regulator) root@ray-worker-nzlzg:/tmp/ray/session_latest/logs# cat raylet.err 
F0928 16:30:47.069190   464   464 scheduling_resources.cc:176]  Check failed: resource_capacity_.count(resource_label) == 1 Attempt to acquire unknown resource: GPU capacity 1
*** Check failure stack trace: ***
    @     0x55d353af79cd  google::LogMessage::Fail()
    @     0x55d353af8b2c  google::LogMessage::SendToLog()
    @     0x55d353af76a9  google::LogMessage::Flush()
    @     0x55d353af78c1  google::LogMessage::~LogMessage()
    @     0x55d353aafad9  ray::RayLog::~RayLog()
    @     0x55d353a9fb2c  ray::ResourceSet::SubtractResourcesStrict()
    @     0x55d3537c89f9  ray::raylet::NodeManager::AssignTask()
    @     0x55d3537cad0a  ray::raylet::NodeManager::DispatchTasks()
    @     0x55d3537d07a5  ray::raylet::NodeManager::HandleWorkerAvailable()
    @     0x55d3537d092f  ray::raylet::NodeManager::HandleWorkerAvailable()
    @     0x55d3537d0a0f  ray::raylet::NodeManager::ProcessAnnounceWorkerPortMessage()
    @     0x55d3537d5ae2  ray::raylet::NodeManager::ProcessClientMessage()
    @     0x55d353747d90  _ZNSt17_Function_handlerIFvSt10shared_ptrIN3ray16ClientConnectionEElRKSt6vectorIhSaIhEEEZNS1_6raylet6Raylet12HandleAcceptERKN5boost6system10error_codeEEUlS3_lS8_E0_E9_M_invokeERKSt9_Any_dataS3_lS8_
    @     0x55d353a95c7e  ray::ClientConnection::ProcessMessage()
    @     0x55d353a92b6a  boost::asio::detail::read_op<>::operator()()
    @     0x55d353a93bb2  boost::asio::detail::reactive_socket_recv_op<>::do_complete()
    @     0x55d353df546f  boost::asio::detail::scheduler::do_run_one()
    @     0x55d353df6971  boost::asio::detail::scheduler::run()
    @     0x55d353df79a2  boost::asio::io_context::run()
    @     0x55d35371afde  main
    @     0x7f2f422c7b97  __libc_start_main
    @     0x55d353731bb1  (unknown)
```

I hope this information is sufficient...

Best regards, Pieterjan
@ericl

**Comment by ericl** [comment] 2020-09-28 17:06
@wuisawesome it seems like we're crashing trying to acquire some GPU resource that does not exist. Any idea why this is the case?

Btw @PidgeyBE are you able to reproduce this on any other version of Ray (perhaps with say a GPU head node and CPU worker), or provide the reproduction script?

**Comment by wuisawesome** [comment] 2020-09-28 17:16
hmmm this is a super weird check to fail, especially when the expected and actual look the same... I wonder if this could be floating point error...

**Comment by PidgeyBE** [comment] 2020-09-28 17:24
I have the same issue when I do not use `available_node_types`.
I did not see this same issue in ray 0.8.7. (I had other issues there which might have masked this one...)

**Comment by ericl** [comment] 2020-09-28 17:27
I see, it would be really helpful if you could provide a script / autoscaler config that can reproduce this without available_node_types. That way we can test ourselves against older Ray versions (that do not support available_node_types).

**Comment by PidgeyBE** [comment] 2020-09-28 17:48
I found in our codebase that this line: `ray.experimental.set_resource("GPU", num_gpus)` is executed via `ray.worker.global_worker.run_function_on_all_workers()`. I think I did this change because the calculation for the number of GPUs is not always correct (e.g. in a Google Cloud VM).
Instead we are using `len(GPUtil.getGPUs())`, which seems to be correct for us on all platforms/cloud providers...

This change was done 3 weeks (1 week before my holiday) ago so this might be causing this I guess? :mask: 

I'll patch this change and retest.

**Comment by ericl** [comment] 2020-09-28 21:09
FYI, you can instead use the --resources flag (or the resources config in avail_node_types) instead of using set_resources (which is quite experimental not well tested).

**Comment by PidgeyBE** [comment] 2020-09-29 12:16
We are using `set_resources` in multiple places and up till now it behaves as expected!

This issue is caused by our own code, so I'll close the ticket. Sorry for wasting your time...

**Comment by ericl** [comment] 2020-09-29 18:24
That's great news. We probably shouldn't be crashing in this case though, so I'll keep this open at a lower priority.

**Comment by PidgeyBE** [comment] 2020-11-23 16:50
Just to be clear, raylet is still crashing when a custom resources becomes 0.
E.g in case the custom resource is `GPU` (we overwrite it): 
```
==> raylet.err <==
F1120 16:31:35.222613  1055  1055 scheduling_resources.cc:176]  Check failed: resource_capacity_.count(resource_label) == 1 Attempt to acquire unknown resource: GPU capacity 1
*** Check failure stack trace: ***
    @     0x5575c62f49cd  google::LogMessage::Fail()
    @     0x5575c62f5b2c  google::LogMessage::SendToLog()
    @     0x5575c62f46a9  google::LogMessage::Flush()
    @     0x5575c62f48c1  google::LogMessage::~LogMessage()
    @     0x5575c62acad9  ray::RayLog::~RayLog()
    @     0x5575c629cb2c  ray::ResourceSet::SubtractResourcesStrict()
    @     0x5575c5fc59f9  ray::raylet::NodeManager::AssignTask()
    @     0x5575c5fc7d0a  ray::raylet::NodeManager::DispatchTasks()
    @     0x5575c5fcd7a5  ray::raylet::NodeManager::HandleWorkerAvailable()
    @     0x5575c5fcd92f  ray::raylet::NodeManager::HandleWorkerAvailable()
    @     0x5575c5fcda0f  ray::raylet::NodeManager::ProcessAnnounceWorkerPortMessage()
    @     0x5575c5fd2ae2  ray::raylet::NodeManager::ProcessClientMessage()
    @     0x5575c5f44d90  _ZNSt17_Function_handlerIFvSt10shared_ptrIN3ray16ClientConnectionEElRKSt6vectorIhSaIhEEEZNS1_6raylet6Raylet12HandleAcceptERKN5boost6system10error_codeEEUlS3_lS8_E0_E9_M_invokeERKSt9_Any_dataS3_lS8_
    @     0x5575c6292c7e  ray::ClientConnection::ProcessMessage()
    @     0x5575c628fb6a  boost::asio::detail::read_op<>::operator()()
    @     0x5575c6290bb2  boost::asio::detail::reactive_socket_recv_op<>::do_complete()
    @     0x5575c65f246f  boost::asio::detail::scheduler::do_run_one()
    @     0x5575c65f3971  boost::asio::detail::scheduler::run()
    @     0x5575c65f49a2  boost::asio::io_context::run()
    @     0x5575c5f17fde  main
    @     0x7f5c0e4e4b97  __libc_start_main
    @     0x5575c5f2ebb1  (unknown)
==> raylet.out <==
F1120 16:31:35.222613  1055  1055 scheduling_resources.cc:176]  Check failed: resource_capacity_.count(resource_label) == 1 Attempt to acquire unknown resource: GPU capacity 1
F1120 16:31:35.222613  1055  1055 scheduling_resources.cc:176]  Check failed: resource_capacity_.count(resource_label) == 1 Attempt to acquire unknown resource: GPU capacity 1
F1120 16:31:35.222613  1055  1055 scheduling_resources.cc:176]  Check failed: resource_capacity_.count(resource_label) == 1 Attempt to acquire unknown resource: GPU capacity 1
F1120 16:31:35.222613  1055  1055 scheduling_resources.cc:176]  Check failed: resource_capacity_.count(resource_label) == 1 Attempt to acquire unknown resource: GPU capacity 1
```
Together with these logs, the raylet's memory usage sky rockets right before crashing:
![image](https://user-images.githubusercontent.com/19860056/99990624-577b6580-2db4-11eb-83fe-c706fca7c50b.png)

**Comment by ericl** [comment] 2020-11-23 22:56
@PidgeyBE are you still using `ray.experimental.set_resource`? Or is this when passing resources at ray start time?

**Comment by PidgeyBE** [comment] 2020-11-24 09:19
> @PidgeyBE are you still using `ray.experimental.set_resource`? Or is this when passing resources at ray start time?

@ericl Yes indeed. We are using `ray.experimental.set_resource`. If we don't use it, then the issue disappears.

**Comment by PidgeyBE** [comment] 2020-11-27 14:51
I saw this today in autoscaling logs, might be related, did not make a repro script yet
```
020-11-27 14:33:04,626	INFO autoscaler.py:612 -- StandardAutoscaler: resource_requests=[{'CPU': 0.1}, {'CPU': 0.1}, {'CPU': 1.0}, {'CPU': 0.2, 'GPU': 0.0}, {'CPU': 0.2, 'GPU': 0.0}, {'CPU': 0.2, 'GPU': 1.0}]
2020-11-27 14:33:09,774	INFO resource_demand_scheduler.py:166 -- Cluster resources: [{'memory': 62.0, 'object_store_memory': 21.0, 'node:10.208.0.75': 1.0, 'CPU': 1.0}, {'memory': 94.0, 'accelerator_type:RTX': 1.0, 'node:10.208.0.39': 1.0, 'object_store_memory': 27.0}]
2020-11-27 14:33:09,774	INFO resource_demand_scheduler.py:167 -- Node counts: defaultdict(<class 'int'>, {'def_head': 1, 'def_regulator': 1})
2020-11-27 14:33:09,774	INFO resource_demand_scheduler.py:174 -- Placement group demands: []
2020-11-27 14:33:09,774	ERROR autoscaler.py:129 -- StandardAutoscaler: Error during autoscaling.
Traceback (most recent call last):
  File "/app/miniconda3/envs/regulator/lib/python3.6/site-packages/ray/autoscaler/_private/autoscaler.py", line 127, in update
    self._update()
  File "/app/miniconda3/envs/regulator/lib/python3.6/site-packages/ray/autoscaler/_private/autoscaler.py", line 217, in _update
    ensure_min_cluster_size=self.resource_demand_vector)
  File "/app/miniconda3/envs/regulator/lib/python3.6/site-packages/ray/autoscaler/_private/resource_demand_scheduler.py", line 192, in get_nodes_to_launch
    resource_demands)
  File "/app/miniconda3/envs/regulator/lib/python3.6/site-packages/ray/autoscaler/_private/resource_demand_scheduler.py", line 664, in get_bin_pack_residual
    _inplace_subtract(node, demand)
  File "/app/miniconda3/envs/regulator/lib/python3.6/site-packages/ray/autoscaler/_private/resource_demand_scheduler.py", line 680, in _inplace_subtract
    assert k in node, (k, node)
AssertionError: ('GPU', {'memory': 62.0, 'object_store_memory': 21.0, 'node:10.208.0.75': 1.0, 'CPU': 0.6000000000000001})
```

**Comment by wuisawesome** [comment] 2021-02-07 22:51
Closing this issue since we've deprecated the dynamic resources API.

**Closed by wuisawesome** 2021-02-07 22:51 UTC
Labels: P3, bug, needs-repro-script
