### ISSUE TITLE
[rllib] Offline Dataset Logs no longer include 'info' attribute

### ISSUE THREAD

**Issue by JohnMcCarroll** [ray-project/ray#13468] opened 2021-01-14 21:05 UTC
### Describe your feature request

For the project I'm working on, logging the 'info' variable returned by an environment's step() method is desired. In ray1.0, the 'infos' key held this data when saving episodes to file (config['output'] = file_path). However, it seems it has been removed, along with some other elements, in ray 1.1.

I was hoping there was a supported way to reintroduce the 'infos' key to the output files, or otherwise log episode state data to file. I believe implementing a custom Callback for "on_process_traj" would have access to the right information in order to set up the state logs, however I am trying to avoid it. Any suggestions would be greatly appreciated.

**Comment by krfricke** [comment] 2021-01-18 11:14
Duplicate of #13469

**Closed by krfricke** 2021-01-18 11:14 UTC
Labels: enhancement, rllib
