### ISSUE TITLE
[Bug] Non conversion to PyTorch Tensor using DDPG and PBT

### ISSUE THREAD

**Issue by thomascizeron** [ray-project/ray#22216] opened 2022-02-08 14:01 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune, RLlib

### What happened + What you expected to happen

Using DDPG and PBT with PyTorch framework cause the following error:
```
ray\rllib\utils\exploration\ornstein_uhlenbeck_noise.py", line 174, in _get_torch_exploration_action
    mean=torch.zeros(self.ou_state.size()), std=1.0) \
TypeError: 'int' object is not callable
```

Ornstein-Uhlenbeck is the noise used in DDPG, I do not have this error when I remove `"framework": "torch"` from the config or when I do not use PBT. I think that `self.ou_state` is a np array instead of a PyTorch Tensor since the `.size` returns an int in numpy while it’s a function in PyTorch. I do not know where the conversion does (or does not) happen.

### Versions / Dependencies

ray 1.10.0
python 3.9

### Reproduction script

import random as rd
import os

import ray
from ray.rllib.agents import ddpg
from ray.rllib.utils.framework import try_import_torch
from ray import tune
from ray.tune.schedulers import PopulationBasedTraining

torch, nn = try_import_torch()

if __name__ == "__main__":
    ray.init()

    config = {
        "env": "Pendulum-v1",
        "num_gpus": int(os.environ.get("RLLIB_NUM_GPUS", "0")),
        "num_workers": 1,
        "framework": "torch",
    }

    ddpg_config = ddpg.DEFAULT_CONFIG.copy()
    ddpg_config.update(config)
    ddpg_config["train_batch_size"] = 256

    ddpg_config["actor_lr"] = tune.loguniform(1e-5, 1e-3)
    ddpg_config["critic_lr"] = tune.loguniform(1e-5, 1e-3)

    stop = {
        "training_iteration": 25,
    }

    pbt = PopulationBasedTraining(
        time_attr="training_iteration",
        metric="episode_reward_mean",
        mode="max",
        perturbation_interval=8,
        hyperparam_mutations={
            'actor_lr': lambda: rd.uniform(1e-5, 1e-3),
            'critic_lr': lambda: rd.uniform(1e-5, 1e-3),
        })

    analysis = tune.run(ddpg.DDPGTrainer,
                        config=ddpg_config,
                        num_samples=8,
                        stop=stop,
                        scheduler=pbt,
                        )

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by orthosku** [comment] 2022-03-04 05:12
running into this problem with ddpg as well

**Comment by gjoliver** [comment] 2022-03-07 18:43
I tried your repro script in python3.9, torch 1.10, and ray 1.10.0.
but I couldn't reproduce the problem you mentioned here.
the job seemed to run fine.

**Comment by gjoliver** [comment] 2022-04-08 17:10
closing due to lack of updates.
do let us know if you need any other helps.

**Closed by gjoliver** 2022-04-08 17:10 UTC
Labels: bug, needs-repro-script, rllib
