### ISSUE TITLE
[serve][quickstart] _pickle.PicklingError

### ISSUE THREAD

**Issue by aaronhmiller** [ray-project/ray#11853] opened 2020-11-06 07:43 UTC
# What is the problem?

Running the existing `https://ray.io/#serve` sample and the newer one: `https://github.com/ray-project/ray/blob/master/python/ray/serve/examples/doc/quickstart_class.py` throw errors.

Focusing on the newer one, here's the full traceback:

```
Traceback (most recent call last):
  File "/Users/amiller/Dropbox/code/python/ray/serve.py", line 19, in <module>
    client.create_backend("counter", Counter)
  File "/Users/amiller/.pyenv/versions/3.7.3/lib/python3.7/site-packages/ray/serve/api.py", line 29, in check
    return f(self, *args, **kwargs)
  File "/Users/amiller/.pyenv/versions/3.7.3/lib/python3.7/site-packages/ray/serve/api.py", line 246, in create_backend
    replica_config))
  File "/Users/amiller/.pyenv/versions/3.7.3/lib/python3.7/site-packages/ray/actor.py", line 101, in remote
    return self._remote(args, kwargs)
  File "/Users/amiller/.pyenv/versions/3.7.3/lib/python3.7/site-packages/ray/actor.py", line 142, in _remote
    return invocation(args, kwargs)
  File "/Users/amiller/.pyenv/versions/3.7.3/lib/python3.7/site-packages/ray/actor.py", line 136, in invocation
    num_returns=num_returns)
  File "/Users/amiller/.pyenv/versions/3.7.3/lib/python3.7/site-packages/ray/actor.py", line 793, in _actor_method_call
    list_args, name, num_returns, self._ray_actor_method_cpus)
  File "python/ray/_raylet.pyx", line 1132, in ray._raylet.CoreWorker.submit_actor_task
  File "python/ray/_raylet.pyx", line 1138, in ray._raylet.CoreWorker.submit_actor_task
  File "python/ray/_raylet.pyx", line 295, in ray._raylet.prepare_args
  File "/Users/amiller/.pyenv/versions/3.7.3/lib/python3.7/site-packages/ray/serialization.py", line 404, in serialize
    return self._serialize_to_msgpack(value)
  File "/Users/amiller/.pyenv/versions/3.7.3/lib/python3.7/site-packages/ray/serialization.py", line 384, in _serialize_to_msgpack
    self._serialize_to_pickle5(metadata, python_objects)
  File "/Users/amiller/.pyenv/versions/3.7.3/lib/python3.7/site-packages/ray/serialization.py", line 344, in _serialize_to_pickle5
    raise e
  File "/Users/amiller/.pyenv/versions/3.7.3/lib/python3.7/site-packages/ray/serialization.py", line 341, in _serialize_to_pickle5
    value, protocol=5, buffer_callback=writer.buffer_callback)
  File "/Users/amiller/.pyenv/versions/3.7.3/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 70, in dumps
    cp.dump(obj)
  File "/Users/amiller/.pyenv/versions/3.7.3/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 656, in dump
    return Pickler.dump(self, obj)
_pickle.PicklingError: Can't pickle <cyfunction _process_class.<locals>._pydantic_post_init at 0x10cd20b38>: attribute lookup _pydantic_post_init on pydantic.dataclasses failed
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray version, 1.0.0
Python 3.7.3
OS Version: Mac OS 10.15.7

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

`python serve.py` where serve.py is the example file here: `https://github.com/ray-project/ray/blob/master/python/ray/serve/examples/doc/quickstart_class.py`

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).
^^ Tried this, but get 404:
ERROR: HTTP error 404 while getting https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp37-cp37m-macosx_10_13_intel.whl
ERROR: Could not install requirement ray==1.0.0 from https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp37-cp37m-macosx_10_13_intel.whl because of HTTP error 404 Client Error: Not Found for url: https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp37-cp37m-macosx_10_13_intel.whl for URL https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp37-cp37m-macosx_10_13_intel.whl

**Comment by architkulkarni** [comment] 2020-11-06 17:31
Duplicate of https://github.com/ray-project/ray/issues/11648.  Thanks for reporting, and sorry you ran into this!

**Closed by architkulkarni** 2020-11-06 17:31 UTC
Labels: bug, triage
