### ISSUE TITLE
[Tune][Bug] Large checkpoint size results in PLACEMENT_GROUP_REMOVED error

### ISSUE THREAD

**Issue by jnpm** [ray-project/ray#23470] opened 2022-03-24 18:05 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

I am using TuneBOHB in order to optimize hyperparameters of a transformer model with the functional training API. The trainable function is supposed to save a checkpoint after each training and validation iteration. Everything runs fine in the first round of hyperband, where each trial is running for 1 epoch. The checkpoints are also saved properly. **When the next phase starts, the model does not pick up from the checkpoint but starts from the beginning because the worker died.**
The original model has a checkpoint size of roughly 1.2GB. I have included a Colab link where I reproduced the error. There, the checkpoint size is about 400MB. If I do not save the model weights (which shrinks the file size to <1MB), the tuning works properly without any errors. This goes for both the original model and the reproduction.
```
2022-03-24 17:43:28,132	ERROR worker.py:84 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::ImplicitFunc.restore_from_object() (pid=582, ip=172.28.0.2, repr=hyper_optim)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: wrap_function.<locals>.ImplicitFunc
	actor_id: 6dcfd75a9deabefe962d2c0e01000000
	pid: 508
	namespace: 7946face-9a55-4ea6-abff-56b539dafefb
	ip: 172.28.0.2
The actor is dead because its worker process has died. Worker exit type: PLACEMENT_GROUP_REMOVED
```

### Versions / Dependencies

ray 1.11.0
python 3.9.10
IPython          : 7.30.1
ipykernel        : 6.5.1
ipywidgets       : not installed
jupyter_client   : 7.1.0
jupyter_core     : 4.9.1
jupyter_server   : 1.12.1
jupyterlab       : 3.2.4
nbclient         : 0.5.9
nbconvert        : 6.3.0
nbformat         : 5.1.3
notebook         : 6.4.6
qtconsole        : not installed
traitlets        : 5.1.1
posix.uname_result(sysname='Linux', nodename='default', release='4.14.262-200.489.amzn2.x86_64', version='https://github.com/ray-project/ray/pull/1 SMP Fri Feb 4 20:34:30 UTC 2022', machine='x86_64')

### Reproduction script

Google Colab link where I reproduced the error:

https://colab.research.google.com/drive/1KnBYSMkjfq64foCS3UGdF4dFeJy9d0ij

### Anything else

The code is being executed in jupyterlab (amazon sagemaker studio with a g4dn.xlarge instance).

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jnpm** [comment] 2022-03-25 15:59
`reuse_actors=True` seems to solve the issue mentioned above. However, in my original model for large checkpoint sizes (~1.4GB) raytune will start to idle after running 2 different trials. The status for the third trial stays at pending with no resources being requested. I have tried initiating the model outside the trainable function and including it with `tune.with_parameters` but that does not seem to work either.

Below I have reproduced the error with a RoBERTa large model (~2GB file size):

https://colab.research.google.com/drive/1A3lyms-terMyjonHZ413QKJqboCSpI8n

Any idea how large checkpoint files can be dealt with?

**Comment by krfricke** [comment] 2022-03-25 18:15
Interesting - it seems like `restore_from_object` suffers from too large object sizes.

For single node training, you could try passing `sync_config=tune.SyncConfig(syncer=None, sync_on_checkpoint=False)` to `tune.run()` to disable resrtoring from object (Tune will then try to restore from the directory directly, assuming it is locally available). For distributed training you may want to specify an `upload_dir` to cloud storage instead.

In any case, this is a bug and we will look into this

**Comment by jnpm** [comment] 2022-03-25 20:58
@krfricke
Just tried the `sync_config` setting but it does not seem to solve the issue either. Guess I'll have to switch to a search algorithm that doesn't require checkpointing for the time being.

**Comment by xwjiang2010** [comment] 2022-04-18 22:02
Hi @jnpm

I tried your script on the following cluster:
m5.4xlarge (head with 0 CPU assigned) + m5.4xlarge (worker node with 16CPU). I also modified resources_per_trial to only use CPUs.

Running your script as it is caused `on_trial_result` very slow for me (> 500s) due to 2G bytes of checkpoint file. This is expected, considering tune is not optimized when syncing such large size file to driver. Despite that, I still observed iteration=2 successfully restored from in memory checkpoint. I then killed the script since it's too slow.

I then tried removing `keep_checkpoints_num=1` and adding `sync_config=SyncConfig(sync_on_checkpoint=False)` to disable syncing to driver. This time, the script finishes in reasonable time. I didn't observe any issues when restoring from checkpoints.

So overall, I wasn't able to reproduce the issue you described.

Checkpoint is really an overloaded term. In the current context, it could mean 
1. saving and restoring trial state when trials are paused and restarted.
2. fault tolerance in case a node is dead.

I would suggest a separation of concerns here. In either case, I wouldn't recommend syncing to driver as it would incur too much load given the size of files. 

Let me know if this helps. And I am happy to try more stuff on my end to further debug the issue.

**Comment by krfricke** [comment] 2022-04-20 08:31
Hi @jnpm, I've reproduced your problem in the colab and did two minor adjustments that fixed the problem for me.

First, you're currently calling `model = BertModel.from_pretrained('yiyanghkust/finbert-tone')` in each training function. This means that the model is downloaded for each trial separately (even though it should be cached - I've seen it being downlaoded four times). The solution here is to move the model into the `tune.with_parameters` call:

```
model = BertModel.from_pretrained('yiyanghkust/finbert-tone')

analysis = tune.run(
        tune.with_parameters(hyper_optim, model=model, logging=False, tuning=True),
        ...
)
```

Second, because of the resource constraints in google colab (2 CPUs), only one trial can be run at the same time, which means we're instantiating new training actors all the time. I'm not sure why this fails in the case of large checkpoints (it could be that GCS gets overloaded) and we will investigate this. However, the solution here is to use `reuse_actors=True`, which will only call the training function again, but not deconstruct and reconstruct the actor.

Thus

```
model = BertModel.from_pretrained('yiyanghkust/finbert-tone')

analysis = tune.run(
        tune.with_parameters(hyper_optim, model=model, logging=False, tuning=True),
        name="bohb_test",
        scheduler=bohb_hyperband,
        metric="val_loss",
        mode="min",
        verbose=3,
        reuse_actors=True,  # <-- set this
        search_alg=bohb_search,
        stop=stopper,
        keep_checkpoints_num=1,
        checkpoint_score_attr="training_iteration",
        resources_per_trial={"cpu": 1},
        num_samples=4,
        config=configuration)
```

solves the problem for me.

Can you give it a try?

**Comment by jnpm** [comment] 2022-04-20 11:03
@xwjiang2010
I did try it with `sync_on_checkpoint=False` as Kai suggested earlier in the comments but it did not seem to work for me (atleast for the larger model with 2GB file size). Did you run it in Sagemaker Studio or a standard EC2 instance? I will look into it further next week though and will get back to you.

@krfricke
I have tried exactly that before and it worked for the smaller model (~400MB size) but once I tried it on my actual model, which has ~1.5GB file size, it resulted in the problem mentioned in my first comment https://github.com/ray-project/ray/issues/23470#issuecomment-1079168089 .

Have you tried reproducing the second colab link?

P.S. I'm getting the error `valueError: invalid literal for int() with base 10: 'max\n'` when I run the colab script with the latest version of ray (1.12). Had to go back to 1.11.0 for it to work again.

**Comment by krfricke** [comment] 2022-04-20 14:03
Ah sorry, I missed that - let me look into the second colab.

The invalid literal bug was fixed here https://github.com/ray-project/ray/pull/23922 and will be included in the upcoming patch release 1.12.1

**Comment by krfricke** [comment] 2022-04-20 15:10
For the second colab I run into this:

```
Your session crashed after using all available RAM. If you are interested in access to high-RAM runtimes, you may want to check out [Colab Pro](https://colab.research.google.com/signup/pricing?utm_source=dialog&utm_medium=link&utm_campaign=oom).
```

Which makes sense, as the models are held in memory (4 * 2GB) and when they are serialized they will be added to the object store. These operations are not always zero-copy, and lastly the VM and Ray need RAM as well.

Can you run this on a larger machine?

**Comment by jnpm** [comment] 2022-04-20 17:58
I ran the notebook on a g4dn.12xlarge instance and got the following results:

Run 1: Got the PLACEMENT_GROUP_REMOVED error in the beginning and the tune process stopped requesting resources and did nothing for 5 minutes.

I then stopped the run and reduced the number of CPU cores per trial.

Run 2: Still PLACEMENT_GROUP_REMOVED errors but no more "idle" issue.

Eventually I stopped the run and tried out @xwjiang2010's procedure. I removed `keep_checkpoints_num=1` and added `sync_config=SyncConfig(sync_on_checkpoint=False)`. Apart from a `OSError: [Errno 28] No space left on device` there was no PLACEMENT_GROUP_REMOVED error nor "idle" issue. After a while I stopped that run too and tried adding back `keep_checkpoints_num=1`.

Run 4: No PLACEMENT_GROUP_REMOVED error but "idle" issue.

Any idea how I can keep the number of checkpoints to a minimum (preferably only the latest one per trial) without it getting stuck? Also, I don't know why each epoch takes 60-100s considering that I'm not computing much.

I will add the `sync_config` option into my actual model again next week and see how it goes.

Attached are the notebooks in HTML format.

[Output.zip](https://github.com/ray-project/ray/files/8523963/Output.zip)

**Comment by xwjiang2010** [comment] 2022-04-25 21:24
@jnpm 
I am coming back to copy exactly your setup (starting at Run 1).
I am using also just one node cluster with g4dn.12xlarge instance.
Running the exact same script as your Run 1 on head node with `ray.init(address="auto")`.

The result I am getting is:
```
+----------------------+------------+----------------+--------------+-------------+-------------+------------+--------+------------------+------------+---------+------------------------+
| Trial name           | status     | loc            |   batch_size |          lr |     w_decay |     warmup |   iter |   total time (s) |   val_loss |   epoch |   early_stopping_count |
|----------------------+------------+----------------+--------------+-------------+-------------+------------+--------+------------------+------------+---------+------------------------|
| hyper_optim_ab8d159a | TERMINATED | 10.0.0.44:2266 |           16 | 0.000262143 | 0.137689    | 0.0987475  |      3 |          28.5321 |  0.0684351 |       3 |                      2 |
| hyper_optim_acfd5246 | TERMINATED | 10.0.0.44:2445 |           32 | 6.5388e-05  | 0.185657    | 0.012852   |      8 |          60.985  |  0.88518   |       8 |                      7 |
| hyper_optim_acfec248 | TERMINATED | 10.0.0.44:2681 |            8 | 0.00635492  | 0.000602458 | 0.0496576  |      8 |          70.6757 |  0.88518   |       8 |                      7 |
| hyper_optim_acffee0c | TERMINATED | 10.0.0.44:2731 |           32 | 1.76854e-05 | 0.135651    | 0.0745786  |      8 |          70.7221 |  0.88518   |       8 |                      7 |
| hyper_optim_d23dce78 | TERMINATED | 10.0.0.44:2736 |           16 | 0.0301399   | 0.0962911   | 0.0839446  |      8 |          51.4227 |  0.88518   |       8 |                      7 |
| hyper_optim_e0b440c2 | TERMINATED | 10.0.0.44:2867 |            8 | 0.050592    | 0.295251    | 0.0994576  |      8 |          51.1859 |  0.88518   |       8 |                      7 |
| hyper_optim_e76ed292 | TERMINATED | 10.0.0.44:2869 |           16 | 1.59296e-05 | 0.268854    | 0.00934304 |      8 |          52.806  |  0.88518   |       8 |                      7 |
| hyper_optim_ed5be640 | TERMINATED | 10.0.0.44:2947 |           16 | 0.000224229 | 0.23126     | 0.0094014  |      8 |          52.9689 |  0.88518   |       8 |                      7 |
| hyper_optim_0c4a70b2 | TERMINATED | 10.0.0.44:3013 |            8 | 0.000182626 | 0.195762    | 0.0196448  |      8 |          46.1217 |  0.811941  |       8 |                      7 |
| hyper_optim_106a25c0 | TERMINATED | 10.0.0.44:3052 |           16 | 0.00487661  | 0.0569472   | 0.0383833  |      8 |          46.4332 |  0.811941  |       8 |                      7 |
| hyper_optim_1238681c | TERMINATED | 10.0.0.44:3090 |            8 | 0.00372572  | 0.298095    | 0.0599721  |      8 |          48.9859 |  0.811941  |       8 |                      7 |
| hyper_optim_1547eea6 | TERMINATED | 10.0.0.44:3128 |           32 | 0.005453    | 0.0581508   | 0.0928897  |      8 |          45.4474 |  0.811941  |       8 |                      7 |
+----------------------+------------+----------------+--------------+-------------+-------------+------------+--------+------------------+------------+---------+------------------------+


2022-04-25 21:18:05,187	INFO tune.py:702 -- Total run time: 226.29 seconds (225.93 seconds for the tuning loop).
```

Looking pretty reasonable to me.

I understand that you were getting "PLACEMENT_GROUP_REMOVED" error in the beginning. The only difference I notice between your run and my run is accidentally using a 300GB block device. I am now trying without that.

**Comment by xwjiang2010** [comment] 2022-04-26 16:59
@jnpm 
How did you launch the ray cluster? 
Did you just spin up a bare metal instance using deep learning AMI for example? And do `pip install xxx`?

**Comment by jnpm** [comment] 2022-05-11 10:56
@xwjiang2010 I am using a python base sagemaker image and creating a conda environment from a yml file with packages from pip and conda-forge upon initialization.

**Closed** 2023-04-17 18:09 UTC
Labels: bug, P1, tune
