### ISSUE TITLE
Serializing/deserializing converts integer to long in python 2

### ISSUE THREAD

**Issue by pschafhalter** [ray-project/ray#2078] opened 2018-05-16 20:18 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 17.10
- **Ray installed from (source or binary)**: Source
- **Ray version**: 0.4.0
- **Python version**:  2.7.14
- **Exact command to reproduce**:
```python
In [3]: val = 0

In [4]: type(val)
Out[4]: int

In [5]: x = ray.put(val)

In [6]: type(ray.get(x))
Out[6]: long
```

### Describe the problem

Serializing an integer through `ray.put()` and then deserializing it with `ray.get()` returns a `long` instead of an integer. Note that this is not an issue in python 3 where the long type does not exist.

It seems to be an issue with serialization in Arrow.

**Comment by robertnishihara** [comment] 2018-05-16 22:12
Thanks @pschafhalter, closing because this is a duplicate of #1014. I'll assign the other issue to you, thanks for looking into this!

**Closed by robertnishihara** 2018-05-16 22:12 UTC
Labels: bug
