### ISSUE TITLE
[rllib] Update pip version

### ISSUE THREAD

**Issue by ArciAndres** [ray-project/ray#11895] opened 2020-11-09 16:02 UTC
### `pip` version outdated

I bumped with a problem where the master version is needed. Ray **v1.1.0** is not loaded as pip module yet, and installing the nightly version is not working either, as both are v.1.0.0. 

### Reproduction

The entire sequence of steps for reproduction is described in the following NotebooK

https://colab.research.google.com/drive/1SJHadMoAg2CmsLeYoTicGgZG8tpWoiRO?usp=sharing

**Comment by sven1977** [comment] 2020-11-25 12:59
Hey @ArciAndres Thanks for filing this issue!
So this has been fixed in the current master and I'm understanding that the problem is more about pettingzoo versions as well as the fact that our `ray install-nightly` command is not stable at the moment.
You can always upgrade to the latest master by going to:

https://docs.ray.io/en/master/installation.html

, get the link to the latest wheel for your py version and platform.

Then do manually:
`pip install -U [link from above]`.

**Comment by sven1977** [comment] 2020-11-25 13:00
I'm closing this issue, since the described error message related to pettingzoo seemed to have been fixed.

**Closed by sven1977** 2020-11-25 13:00 UTC
Labels: bug, rllib, triage
