### ISSUE TITLE
[Ray Cluster Launcher] Support TPU VM Pod for Ray Cluster

### ISSUE THREAD

**Issue by OrenLeung** [ray-project/ray#31260] opened 2022-12-21 02:52 UTC
### Description

Support TPU VM Pod for ray cluster @jiaodong  @simon-mo 

https://docs.ray.io/en/latest/cluster/vms/references/ray-cluster-configuration.html#tpu-configuration

### Use case

setup ray on TPU VM Pods through a simple command instead of every single company writing a custom parallel ssh script to run `ray start` on every worker on a tpu pod

**Comment by richardliaw** [comment] 2022-12-21 08:59
Thanks a bunch for this :) @OrenLeung I'm going to close this as a duplicate of #25223 -- if you don't mind, please upvote that issue and leave a comment!

**Closed by richardliaw** 2022-12-21 08:59 UTC
Labels: enhancement
