### ISSUE TITLE
[Dashboard] Ray Dashboard goes blank when moving to the "Actor" tab of the "Node Detail" page

### ISSUE THREAD

**Issue by ckw017** [ray-project/ray#42460] opened 2024-01-17 22:35 UTC
### What happened + What you expected to happen

Seeing this in the console

react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'ipAddress')
    at ActorTable.tsx:384:68
    at Array.filter (<anonymous>)
    at ActorTable.tsx:381:29
    at Array.map (<anonymous>)
    at t.Z (ActorTable.tsx:362:19)
    at oo (react-dom.production.min.js:157:137)
    at Ws (react-dom.production.min.js:267:460)
    at Al (react-dom.production.min.js:250:347)
    at Ol (react-dom.production.min.js:250:278)
    at xl (react-dom.production.min.js:250:138)
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mi @ react-dom.production.min.js:131
hs @ react-dom.production.min.js:220
Ml @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Va @ react-dom.production.min.js:122
Dl @ react-dom.production.min.js:252
bl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Va @ react-dom.production.min.js:122
$a @ react-dom.production.min.js:123
Wa @ react-dom.production.min.js:122
Le @ react-dom.production.min.js:292
Kt @ react-dom.production.min.js:73
Show 16 more frames
Show less
ActorTable.tsx:384 Uncaught TypeError: Cannot read properties of undefined (reading 'ipAddress')
    at ActorTable.tsx:384:68
    at Array.filter (<anonymous>)
    at ActorTable.tsx:381:29
    at Array.map (<anonymous>)
    at t.Z (ActorTable.tsx:362:19)
    at oo (react-dom.production.min.js:157:137)
    at Ws (react-dom.production.min.js:267:460)
    at Al (react-dom.production.min.js:250:347)
    at Ol (react-dom.production.min.js:250:278)
    at xl (react-dom.production.min.js:250:138)

### Versions / Dependencies

ray 2.9.0

### Issue Severity

Low: It annoys or frustrates me.

**Comment by scottsun94** [comment] 2024-01-23 23:55
![Image](https://github.com/ray-project/ray/assets/9677264/23a59b50-8f13-400b-8592-b29f596aa9b5)

![Image](https://github.com/ray-project/ray/assets/9677264/560b1d6d-a09c-47cf-a77e-04028510578c)

@ckw017 Is there a way to reproduce this. Cannot reproduce on my side.

**Comment by scottsun94** [comment] 2024-01-24 00:16
> ActorTable.tsx:384 Uncaught TypeError: Cannot read properties of undefined (reading 'ipAddress')

@alanwguo Can you take a look?

**Comment by ckw017** [comment] 2024-01-24 00:17
Can only repro when looking at nodes with dead actors on them. I have a repro on an internal cluster, feel free to dm for details

**Comment by nikitavemuri** [comment] 2024-02-01 23:09
This was probably fixed by https://github.com/ray-project/ray/pull/42788 and confirmed the node detail page works with dead actors
<img width="1528" alt="Screen Shot 2024-02-01 at 3 08 56 PM" src="https://github.com/ray-project/ray/assets/6900234/9b6ced04-9ca6-47c1-ae3e-0cbeaa2b923e">

@ckw017 could you check if this is fixed in your repro also?

**Comment by ckw017** [comment] 2024-02-01 23:13
Tricky to upgrade the cluster I repro'd with onto nightly, but if this fixed a problem with the same symptoms (can't load the page when there's a dead actor on it) then was likely the same issue.

**Comment by nikitavemuri** [comment] 2024-02-22 23:18
Closing because this seems to be fixed on master

**Closed by nikitavemuri** 2024-02-22 23:18 UTC
Labels: bug, P1, dashboard

**Comment by danielgafni** [comment] 2024-11-20 03:31
Having this issue with Ray `2.39.0`

```
ActorTable.tsx:558 Uncaught TypeError: Cannot read properties of undefined (reading 'ipAddress')
    at ActorTable.tsx:558:68
    at Array.filter (<anonymous>)
    at ActorTable.tsx:555:29
    at Array.map (<anonymous>)
    at H (ActorTable.tsx:533:19)
    at gi (react-dom.production.min.js:160:137)
    at _l (react-dom.production.min.js:289:337)
    at bc (react-dom.production.min.js:279:389)
    at gc (react-dom.production.min.js:279:320)
    at mc (react-dom.production.min.js:279:180)
```

**Comment by alanwguo** [comment] 2024-11-20 18:11
@danielgafni do you have a simple repro script?

I tried creating an actor on ray 2.39.0 and I didn't run into this issue.

**Comment by danielgafni** [comment] 2024-11-20 18:13
I don't have a simple script. 

Happening to me with Ray Serve in KubeRay. 

I'll see if I can reproduce it locally.
