### ISSUE TITLE
[Serve] (random) Delay in Collecting Results from a Remote Actor Deployment

### ISSUE THREAD

**Issue by bakeryproducts** [ray-project/ray#40328] opened 2023-10-13 17:49 UTC
### What happened + What you expected to happen

Hey Ray team! this is a follow-up for this thread: https://discuss.ray.io/t/ray-get-delayed-return-results-from-deployment/12075. There are 2 a bit different repro scripts in discussion, and one more attached to this issue, all behave the same.

Here is some backstory:

I'm trying to setup HTTP fastapi ray-serve for DL-pytorch based task. Task takes some time, can be up to minutes. 

So a user starts a bunch of a remote jobs from Ingress. So far it is similar to any fastapi example. But after I send a remote job to worker, I do not want to wait couple of minutes for request to be done. So, i collect `DeploymentHandle` from remote job start, pair it with generated unique ID and return that UID to user. After that user tries to access a result with that UID. 

Here my problem/bug arise. When I try to `[ray.get / ray.wait / .result / await]` for that `object_ref / depl_handle` it does not get back to me in time. From all the logs i see, Job is finished, but result is not accessible, (`ray.get` still in blocked state). Eventually i get results, but with random delay, and only at the end of some other job. 

I want to confirm whether this behavior is intended or if it might be a bug. If it’s the former, how can I modify my code to retrieve results from actor jobs as soon as they become available? Thanks!

some logs:

```
2023-10-13 20:38:00,045	INFO router.py:910 -- Using router <class 'ray.serve._private.router.PowerOfTwoChoicesReplicaScheduler'>.
2023-10-13 20:38:00,050	INFO router.py:470 -- Got updated replicas for deployment 'Ingress' in application 'default': {'default#Ingress#HpsuMq'}.
(ServeReplica:default:Ingress pid=22376) waiting on 3 <ray.serve.handle.DeploymentResponse object at 0x7f97385c77f0>
(ServeReplica:default:Ingress pid=22376) INFO 2023-10-13 20:38:00,088 Ingress default#Ingress#HpsuMq default replica.py:726 - __CALL__ OK 31.2ms
(ServeReplica:default:Downstream pid=22375) finished 0
(ServeReplica:default:Downstream pid=22375) INFO 2023-10-13 20:38:02,102 Downstream default#Downstream#ghpxJT default replica.py:726 - __CALL__ OK 2006.9ms
(ServeReplica:default:Downstream pid=22375) finished 1
(ServeReplica:default:Downstream pid=22375) INFO 2023-10-13 20:38:04,113 Downstream default#Downstream#ghpxJT default replica.py:726 - __CALL__ OK 2009.8ms
(ServeReplica:default:Downstream pid=22375) finished 2
(ServeReplica:default:Downstream pid=22375) INFO 2023-10-13 20:38:06,123 Downstream default#Downstream#ghpxJT default replica.py:726 - __CALL__ OK 2009.3ms
(ServeReplica:default:Downstream pid=22375) finished 3
(ServeReplica:default:Downstream pid=22375) INFO 2023-10-13 20:38:08,133 Downstream default#Downstream#ghpxJT default replica.py:726 - __CALL__ OK 2009.8ms
(ServeReplica:default:Downstream pid=22375) finished 4
(ServeReplica:default:Downstream pid=22375) INFO 2023-10-13 20:38:10,144 Downstream default#Downstream#ghpxJT default replica.py:726 - __CALL__ OK 2009.8ms
(ServeReplica:default:Downstream pid=22375) finished 5
(ServeReplica:default:Downstream pid=22375) INFO 2023-10-13 20:38:12,153 Downstream default#Downstream#ghpxJT default replica.py:726 - __CALL__ OK 2009.4ms
(ServeReplica:default:Downstream pid=22375) finished 6
(ServeReplica:default:Downstream pid=22375) INFO 2023-10-13 20:38:14,164 Downstream default#Downstream#ghpxJT default replica.py:726 - __CALL__ OK 2009.9ms
(ServeReplica:default:Downstream pid=22375) finished 7
(ServeReplica:default:Downstream pid=22375) INFO 2023-10-13 20:38:16,173 Downstream default#Downstream#ghpxJT default replica.py:726 - __CALL__ OK 2009.2ms
(ServeReplica:default:Downstream pid=22375) finished 8
(ServeReplica:default:Downstream pid=22375) INFO 2023-10-13 20:38:18,181 Downstream default#Downstream#ghpxJT default replica.py:726 - __CALL__ OK 2007.6ms
Got # 3
(ServeReplica:default:Downstream pid=22375) finished 9
(ServeReplica:default:Downstream pid=22375) INFO 2023-10-13 20:38:20,189 Downstream default#Downstream#ghpxJT default replica.py:726 - __CALL__ OK 2007.6ms
(ServeReplica:default:Ingress pid=22376) INFO 2023-10-13 20:38:20,191 Ingress default#Ingress#HpsuMq default replica.py:726 - GET_TASK OK 20101.0ms
```

### Versions / Dependencies

i tried a lot of setups, each and every one behaves the same way. (ray 2.7+/3.0.0 nightly, python3.9, Debian10)

### Reproduction script

```
import time
from ray import serve

@serve.deployment
class Downstream:
    def __call__(self, idx): 
        time.sleep(2)
        print('finished', idx)
        return idx
    
@serve.deployment
class Ingress:
    def __init__(self, handle):
        self.handle = handle
        
    def __call__(self, total):
        self.refs = [self.handle.remote(i) for i in range(total)]        
    
    async def get_task(self, i):
        ref = self.refs[i]
        print(f'waiting on {i}', ref)
        return await ref

app = Ingress.bind(Downstream.bind())
handle_app = serve.run(app)
TOTAL_TASKS = 10
handle_app.remote(TOTAL_TASKS)

TASK_IDX = 3 # 3/10
response = handle_app.get_task.remote(TASK_IDX).result()
print('Got #', response)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by edoakes** [comment] 2023-10-13 20:05
@bakeryproducts thanks for the detailed report. I reproduced your issue and it seems to be related to the fact that the `Downstream` method is blocking the `asyncio` event loop. I confirmed this by running three modified versions of the code, all of which worked as you expected:

- Setting `max_concurrent_queries=1` in the `Downstream` deployment decorator. This causes only one of the queries to be scheduled to the replica at a time.
- Using `await asyncio.sleep(idx*2)` instead of `time.sleep(2)` to not block the event loop.
- Using `await asyncio.get_running_loop.run_in_executor(None, lambda: time.sleep(idx*2))` to not block the event loop.

I understand this is a very poor/confusing user experience and I will give some thought as to how we can improve it in the general case.

To unblock you, I'd suggest avoiding blocking the event loop by using one of the above options. I assume that `time.sleep` is a placeholder for some real work you want to do; in that case, the third option above of `run_in_executor` may be your best bet.

**Comment by bakeryproducts** [comment] 2023-10-13 20:22
@edoakes Thanks for a respond. Indeed `time.sleep` is a placeholder. Option 1 would be good enough, but setting max_concurrent_queries=1 at Downstream deployment would block HTTP /set Ingress method, from where i go with `handle._longpytorchjob.remote(args)`. So my job is a blocking one. Using option 3 should allow me go do the pytorch job, but I struggle to understand how to retrieve results after that? Also doesnt it break Actor logic of doing things one after another (im actually looking for it, as it is a heavy-gpu-resources job), sequentially? With option 3 and non blocking event loop all jobs will try to start *almost* at the same time..

**Comment by edoakes** [comment] 2023-10-13 22:40
@bakeryproducts setting `max_concurrent_queries=1` will not cause the `.remote` call to block, only the `await response` call (not sure if that's still an issue for you).

Yeah, you're right that it sort of breaks the actor model. But it turns out that concurrency/batching is quite important for ML serving workloads :)

**Comment by bakeryproducts** [comment] 2023-10-14 22:09
@edoakes Setting `max_concurrent_queries=1` for Deployment will block all `await` calls in my FastAPI Ingress. *For example* if you modify Ingress \_\_call\__ for 
```
async def __call__(self, total):
        # self.refs = [self.handle.remote(i) for i in range(total)] 
        self.refs = []
        for i in range(total):
            dep_han = self.handle.remote(i)
            self.refs.append(dep_han)
            # next line will block everything
            obj_ref = await dep_han._to_object_ref() # any await call, just to demonstrate
            print('Job #', i, 'ref', obj_ref)
``` 

At each iteration this will get blocked and wait for a job to end (and unblock event loop probably?). Without `max_concurrent_queries=1` it will not block and create all jobs on the spot.

 Even thou i got a ref to my job result in time, i dont know how to retrieve those results without blocking everything and waiting. Does any of that make any  sense or Im doing it wrong?

**Comment by edoakes** [comment] 2023-10-19 22:05
> @edoakes Setting `max_concurrent_queries=1` for Deployment will block all `await` calls in my FastAPI Ingress. _For example_ if you modify Ingress __call__ for
> 
> ```
> async def __call__(self, total):
>         # self.refs = [self.handle.remote(i) for i in range(total)] 
>         self.refs = []
>         for i in range(total):
>             dep_han = self.handle.remote(i)
>             self.refs.append(dep_han)
>             # next line will block everything
>             obj_ref = await dep_han._to_object_ref() # any await call, just to demonstrate
>             print('Job #', i, 'ref', obj_ref)
> ```
> 
> At each iteration this will get blocked and wait for a job to end (and unblock event loop probably?). Without `max_concurrent_queries=1` it will not block and create all jobs on the spot.
> 
> Even thou i got a ref to my job result in time, i dont know how to retrieve those results without blocking everything and waiting. Does any of that make any sense or Im doing it wrong?

@bakeryproducts the `self.handle.remote()` call will not block on assignment, so even if the replica cannot currently process the request it will return immediately. `_to_object_ref` does need to wait for the request to be assigned to a replica though.

**Comment by JakeSummers** [comment] 2023-11-14 01:25
I am pretty sure that I am running into the same issue here.

Issue description: https://discuss.ray.io/t/no-request-can-complete-until-all-requests-are-ready/12772?u=jacob_summers

Possible workarounds: 

* https://discuss.ray.io/t/no-request-can-complete-until-all-requests-are-ready/12772/8?u=jacob_summers
* https://discuss.ray.io/t/no-request-can-complete-until-all-requests-are-ready/12772/9?u=jacob_summers

Suggestions to resolve this issue: https://discuss.ray.io/t/no-request-can-complete-until-all-requests-are-ready/12772/10?u=jacob_summers

**Comment by alexeykudinkin** [comment] 2023-12-06 03:50
@JakeSummers @bakeryproducts so as Edward already called out in both of your use-cases underlying root-cause of the "delay" in results deliver is the fact that your request execution is inherently _synchronous_, therefore blocking the asyncio Event Loop used by Ray Serve ([this is a simplified example](https://stackoverflow.com/questions/61358303/how-can-we-block-event-loop) of what that practically might mean for your application).

In the context of your application what this means is following:

1. You're submitting requests to a Replica trying to handle these requests
2. While requests handling completes (which you're able to confirm indirectly from the logs), sending response requires additional handling as well, however
3. Before result of handling of the previous request has been sent out, new requests handling starts (occupying, blocking the event-loop) therefore preventing response to be sent back
4. This persists until all requests are handled, event-loop is unblocked and response handling gets a chance to be executed

That's the reason why you seeing response times scaling up with the number of requests that you submit.

As have already been called out to avoid this from occurring you'd avoid executing large, uninterrupted blocks (for ex, long loops) on the event-loop.

**Closed** 2024-05-17 00:29 UTC
Labels: enhancement, P1, serve
