### ISSUE TITLE
[rllib] Fractional GPU no longer works for Torch policies in RLLib

### ISSUE THREAD

**Issue by soundway** [ray-project/ray#16962] opened 2021-07-09 00:52 UTC
This is not a contribution.

Since 1.4, using fractional GPUs for trainers lead to errors.

Example command:

```
rllib train --run=PPO --env=CartPole-v0 --config='{"num_gpus": 0.5, "num_workers": 2,"framework": "torch”}'
```

Exceptions:

```
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() 
 File "python/ray/_raylet.pyx", line 534, in ray._raylet.execute_task
 File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task.function_executor
 File "/home/.local/lib/python3.6/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
   return method(__ray_actor, *args, **kwargs)
 File "/home/.local/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 556, in __init__
   policy_dict, policy_config)
 File "/home/.local/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1335, in _build_policy_map
   policy_map[name] = cls(obs_space, act_space, merged_conf)
 File "/home/.local/lib/python3.6/site-packages/ray/rllib/policy/policy_template.py", line 267, in __init__
   get_batch_divisibility_req=get_batch_divisibility_req,
 File "/home/.local/lib/python3.6/site-packages/ray/rllib/policy/torch_policy.py", line 141, in __init__
   self.device for _ in range(config["num_gpus"] or 1)
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by mvindiola1** [comment] 2021-07-10 18:16
Duplicate of #16880

**Closed** 2021-12-03 04:05 UTC
Labels: bug, triage, rllib
