### ISSUE TITLE
[CI] `osx://python/ray/tests:test_runtime_env_working_dir` is failing/flaky on master.

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#37059] opened 2023-07-03 22:14 UTC
- 8fa28197751f205f0a121cbd215d696ae23dc12b FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4791#01890ef0-adf2-463d-9484-04a5919da2c9)
- 2ba7a9788762036c3051cc85695659b7a31374f2 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4784#01890ea2-cc3f-481e-a20f-8f0b0e54f8cd)
- 0d617310038e30a923e57863aa44dd7423739ae6 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4775#01890e5e-2a5a-455e-94b9-557a6ecfb339)
- f40d236d6de2d878cc8983f1601448956b2086ca FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4774#01890e56-6844-4f3e-b030-e857bae22acd)
- 95d04563bbb8fa6e34752f2bf1c76b8701b0c8ff FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4760#01890d68-4d1c-44ad-9e3c-c92d31df2d6d)
- 80e458c0294f499665586b25c98c718c2d132325 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4751#01890a5b-6993-441d-a261-15a85b27dbb1)
- 49342d58eca763fe274a2328fb839778984c5ff3 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4743#0189095b-51e4-4895-ba43-6d6723ca545f)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-osx://python/ray/tests:test_runtime_env_working_dir-END
....

**Comment by aslonnie** [comment] 2023-09-11 22:52
is this reproducable on release branch?

**Comment by GeneDer** [comment] 2023-09-12 03:03
Yep those are flaky on the release branch as well https://buildkite.com/ray-project/oss-ci-build-branch/builds/6072#018a82b5-d60e-4043-acf4-ad1267c46042/3700-4674 But just retry it few more times, we can eventually get a passing run

**Comment by rynewang** [comment] 2023-10-30 22:42
I think it's passing these days? @rkooo567 

<img width="1334" alt="image" src="https://github.com/ray-project/ray/assets/56065503/f000b7ed-dd94-40e1-8552-f357e1b60e6f">

**Comment by rkooo567** [comment] 2023-10-31 06:34
looks like 2 & 3 are flaky, not 1. closing it

**Closed by rkooo567** 2023-10-31 06:34 UTC
Labels: P1, core, flaky-tracker, ray 2.9
