### ISSUE TITLE
[tune] PyTorch - Invalid device ordinal 

### ISSUE THREAD

**Issue by anthonytec2** [ray-project/ray#5737] opened 2019-09-19 14:00 UTC
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Ray installed from (source or binary)**: Binary
- **Ray version**: 0.7.3
- **Python version**: 3.7
- **Exact command to reproduce**:
.to("cuda:0")

### Describe the problem
I am using pytorch currently and trying to get tune to distribute runs across 4 GPUs. As mentioned in the docs, this should be taken care of by CUDA_VISIBLE_DEVICES. Although, commonly when I start runs using tune I get an error regarding invalid device ordinal. I have printed out ray.get_gpu_ids() and each process does indeed get mapped correctly to the correct GPU. Although still the error persists. Any thoughts as to fix this problem? I have also tried changing cuda:0 to f"cuda:{ray.get_gpu_ids()[0]}" and the error still occurs. 

### Source code / logs
2019-09-19 13:51:18,077	ERROR trial_runner.py:550 -- Error processing event.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 498, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 342, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/ubuntu/.local/lib/python3.7/site-packages/ray/worker.py", line 2247, in get
    raise value
ray.exceptions.RayTaskError: () (pid=4978, host=ip-172-31-0-67)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/ray/tune/trainable.py", line 99, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/ubuntu/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 432, in to
    return self._apply(convert)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/ubuntu/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 230, in _apply
    param_applied = fn(param)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 430, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal

**Comment by anthonytec2** [comment] 2019-09-19 14:02
similar to #3772

**Comment by beabevi** [comment] 2019-09-19 21:23
I am running into the same issue. I have multiple `Trainables` and each of them in the `_setup` tries to move the model to `cuda:<n>`. I am using 3 GPUs set with `CUDA_VISIBLE_DEVICES=0,1,3` and each `Trainable` using `0.05` of GPU.
`tune` starts but every now and then some `Trainable` fails with `invalid device ordinal` although other `Trainables` in the _same_ `tune.run` still complete normally running on all of those 3 devices.

**Comment by richardliaw** [comment] 2019-09-19 22:36
@anthonytec2 @beabevi thanks for raising this issue! Can any of you post some code for reproducing?

**Comment by richardliaw** [comment] 2019-10-15 19:24
Can you also provide a cuda version?

**Comment by bonnie-chow** [comment] 2020-01-02 11:38
Hi!
I'm running into the same issue - `tune` does start but like @beabevi mentioned, some `Trainable` fails every now and then (doesn't seem to be limited to one specific GPU device either)

- Ray version: 0.7.6
- Python version: 3.7.3
- CUDA Version: 10.1 

**Source code/logs:**

2020-01-02 11:26:35,870	ERROR trial_runner.py:569 -- Error processing event.
Traceback (most recent call last):
  File "/home/bonnie/.cache/pypoetry/virtualenvs/<ENV-NAME>/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 515, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/bonnie/.cache/pypoetry/virtualenvs/<ENV-NAME>/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 351, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/bonnie/.cache/pypoetry/virtualenvs/<ENV-NAME>/lib/python3.7/site-packages/ray/worker.py", line 2121, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray_DynamicTrainable:train() (pid=10170, host=<HOSTNAME>)
  File "/home/bonnie/.cache/pypoetry/virtualenvs/<ENV-NAME>/lib/python3.7/site-packages/ray/tune/trainable.py", line 96, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/bonnie/.cache/pypoetry/virtualenvs/<ENV-NAME>/lib/python3.7/site-packages/lumi/training/trainable.py", line 201, in _setup
    verbose=self._verbose,
  File "/home/bonnie/.cache/pypoetry/virtualenvs/<ENV-NAME>/lib/python3.7/site-packages/lumi/pytorch/trainer.py", line 64, in __init__
    pipeline=pipeline.to(device=device),
  File "/home/bonnie/.cache/pypoetry/virtualenvs/<ENV-NAME>/lib/python3.7/site-packages/lumi/pytorch/pipelines/training/default.py", line 57, in to
    self._model = self._model.to(device)
  File "/home/bonnie/.cache/pypoetry/virtualenvs/<ENV-NAME>/lib/python3.7/site-packages/lumi/pytorch/models/model.py", line 33, in to
    nn.Module.to(self, device)
  File "/home/bonnie/.cache/pypoetry/virtualenvs/<ENV-NAME>/lib/python3.7/site-packages/torch/nn/modules/module.py", line 432, in to
    return self._apply(convert)
  File "/home/bonnie/.cache/pypoetry/virtualenvs/<ENV-NAME>/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/bonnie/.cache/pypoetry/virtualenvs/<ENV-NAME>/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/bonnie/.cache/pypoetry/virtualenvs/<ENV-NAME>/lib/python3.7/site-packages/torch/nn/modules/module.py", line 230, in _apply
    param_applied = fn(param)
  File "/home/bonnie/.cache/pypoetry/virtualenvs/<ENV-NAME>/lib/python3.7/site-packages/torch/nn/modules/module.py", line 430, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal

**Comment by MaksymPetyak** [comment] 2020-02-06 13:25
Hi!
Had the same issue when running on 4 GPUs. 
- Ray version: 0.8.0
- Python version: 3.7.5
- CUDA Version: 10.0

Fixed it by not specifying a concrete GPU and letting cuda decide. Instead of ```"cuda:{}".format(ray.get_gpu_ids()[0])``` just used ```"cuda"```. 

It is possible that there is a race condition when separate threads are trying to access ```ray.get_gpu_ids()[0]```.

**Comment by snownus** [comment] 2020-03-26 04:50
@MaksymPetyak , can you provide the codes to address the issue?

**Comment by richardliaw** [comment] 2020-03-26 07:06
Basically, I think you should not specify the specific GPU ID. For anywhere you see this issue, just specify `torch.device("cuda")` and NOT `torch.device("cuda:0")`. 

This is probably bc Ray specifies the CUDA_VISIBLE_DEVICES and it does not play well with Torch.

**Comment by richardliaw** [comment] 2020-03-26 07:07
I'll close this issue for now because it seems resolved. @snownus please post a reproducible script for this error if the above fix doesn't work; would love to take a look at it.

**Closed by richardliaw** 2020-03-26 07:07 UTC
Labels: tune

**Comment by snownus** [comment] 2020-03-26 08:16
@richardliaw , I only use CUDA_VISIBLE_DEVICES to run ray. When #gpu =1, it works. While #gpus=multiple, it doesn't work.

**Comment by richardliaw** [comment] 2020-03-26 15:48
Can you post a reproducible script?

**Comment by snownus** [comment] 2020-03-27 01:48
The script is too long. 

Maybe it is better provide a summary what I have done. 
1. I load a pytorch nn.dataparallel model.
2. I allocate 1 gpu resources for each trial
3. Then I call the ray with CUDA_VISIBLE_DEVICES=0,1,2,3 python run.py, it doesn't work (I have tried to allocate 2 gpus for each trial in this case, it still doesn't work). But when I call the ray with CUDA_VISIBLE_DEVICES=0 python run.py, it works. 

Can u provide some suggestions? @richardliaw , many thanks.

**Comment by DavidMChan** [comment] 2020-06-30 02:17
@richardliaw  - I also now have this issue in Ray SGD at master in _set_cuda_device, however it seems to be flaky, only occurring at random. It does seem like there may be a race condition in the setup which needs to be addressed. 

It can happen whenever you use more than one worker, with one GPU per worker, and is more likely to happen when you have more GPUs.

**Comment by richardliaw** [comment] 2020-06-30 02:42
@DavidMChan ah OK. Can you open a new issue and provide a traceback?

**Comment by DavidMChan** [comment] 2020-06-30 03:39
Sure - see: #9202

**Comment by richardrl** [comment] 2021-01-01 19:21
> Basically, I think you should not specify the specific GPU ID. For anywhere you see this issue, just specify `torch.device("cuda")` and NOT `torch.device("cuda:0")`.
> 
> This is probably bc Ray specifies the CUDA_VISIBLE_DEVICES and it does not play well with Torch.

But this is not a solution right? Because for model parallelism, we specifically want to split the model onto different GPUs

**Comment by Waterkin** [comment] 2022-04-03 16:54
have the same problem as above, any solution now?
