### ISSUE TITLE
[AIR output] Several issues with Trial results

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#36790] opened 2023-06-24 05:37 UTC
### What happened + What you expected to happen

@xwjiang2010 explained this to me before but I still felt like that `time_total_s` is equal to `Total running time` on my first reaction. 

1. We should clarify "Total running time" somehow. To me, it refers to the running time of the trial because it's right behind trial info.
2. `time_this_iter_s` seems not useful when reporting trial results?
3. I remember that we discussed `training_iteration` and `time_total_s` before. Ideally, we should only show them when they use pbt scheduler and choose that as the time attribute. This is more a p2 if we cannot do it now.
4. Shall we remove `config/` in `config/train_loop_config/lr`?

```
Trial TorchTrainer_8dace_00004 completed training after 20 iterations at 2023-06-23 15:30:42. Total running time: 14s
╭───────────────────────────────────────────────────╮
│ Trial TorchTrainer_8dace_00004 result             │
├───────────────────────────────────────────────────┤
│ time_this_iter_s                          0.16039 │
│ time_total_s                              9.51638 │
│ training_iteration                             20 │
│ config/train_loop_config/lr               0.00304 │
│ loss                                       0.6204 │
╰───────────────────────────────────────────────────╯
```

### Versions / Dependencies

nightly

### Reproduction script

Torch tuning example in ray air get started page
https://docs.ray.io/en/releases-2.5.0/ray-air/getting-started.html

### Issue Severity

Low: It annoys or frustrates me.

**Comment by krfricke** [comment] 2023-06-26 14:23
>     4. Shall we remove `config/` in `config/train_loop_config/lr`?

This will be done in https://github.com/ray-project/ray/pull/36764

Everything else looks like a duplicate of #36795 so I'll close this issue and will follow-up in #36795.

**Closed by krfricke** 2023-06-26 14:23 UTC
Labels: bug, P1, triage
