### ISSUE TITLE
[Bug] Infeasible placement group is not scheduled after the cluster is auto-scaled

### ISSUE THREAD

**Issue by noe-mis** [ray-project/ray#20968] opened 2021-12-08 10:19 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core, Ray Clusters

### What happened + What you expected to happen

1. When creating a single placement group (STRICT_PACK) for a node on EC2, it never becomes ready, even though the node comes up (seen in ray monitor). When looking at the placement_group_table, it says INFEASIBLE. Once the node is up, it is possible to remove and re-add the placement group, and it then becomes ready. This only happens with one node/placement_group. With two or more nodes, it works. However, placement_group_table says 'scheduling_attempt': 3 once they are up, so something seems a bit fishy.

3. I haven't been able to get that much out of logs. It just keeps saying:
`2021-12-08 02:08:11,690 WARNING resource_demand_scheduler.py:731 -- The autoscaler could not find a node type to satisfy the request: [{'bundle_group_f603e2de7cd8965a3e9e30f6357dbb7b': 0.001}]. If this request is related to placement groups the resource request will resolve itself, otherwise please specify a node type with the necessary resource https://docs.ray.io/en/master/cluster/autoscaling.html#multiple-node-type-autoscaling.` even though the instance is up.

### Versions / Dependencies

ray 1.9.0 and 1.8.0 have given the same results
python both 3.8.10 and 3.7.7 have given the same results

### Reproduction script
```
from ray.util.placement_group import placement_group, placement_group_table, remove_placement_group
import ray

ray.init('auto')

bundle = {"CPU": 4, "GPU": 1}
pg = placement_group(
    [bundle],
    name=f'worker_1',
    strategy="STRICT_PACK"
)
```

### Anything else

This happens every time we try so far. Did a minimal yaml for reproduction:
```
cluster_name: ray-test
max_workers: 2

docker:
    image: "rayproject/ray:1.9.0"
    container_name: "ray_docker"
    pull_before_run: True

provider:
    type: aws
    region: eu-central-1
    availability_zone: eu-central-1a,eu-central-1b
    use_internal_ips: True
    cache_stopped_nodes: False # If not present, the default is True.


auth:
    ssh_user: ubuntu
    ssh_private_key: ~/.ssh/<key>

available_node_types:
    gpu_ondemand:
        node_config:
            InstanceType: g4dn.xlarge
            ImageId: ami-0bdfa178b5c1fb9e6 # Deep Learning AMI (Ubuntu 18.04)
            KeyName: <key-name>
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 150
            SubnetIds:
                - <subnet1>
                - <subnet2>
            IamInstanceProfile:
                Arn: <ARN>
        # Autoscaler will auto fill the CPU/GPU resources below.
        resources:
            CPU: 4
            GPU: 1
        max_workers: 15
    cpu_ondemand:
        node_config:
            InstanceType: m5.large
            SubnetIds:
                - <subnet1>
                - <subnet2>
            ImageId: ami-0bdfa178b5c1fb9e6 # Deep Learning AMI (Ubuntu 18.04)
            KeyName: <key-name>
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 150
        max_workers: 0
        resources:
            CPU: 2

head_node_type: cpu_ondemand
worker_default_node_type: gpu_ondemand
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment] 2021-12-08 10:29
> When creating a single placement group (STRICT_PACK) for a node on EC2, it never becomes ready, even though the node comes up (seen in ray monitor). When looking at the placement_group_table, it says INFEASIBLE. Once the node is up, it is possible to remove and re-add the placement group, and it then becomes ready.

So in summary, you are saying infeasible placement group is not scheduled although the node is up, and then if you reschedule the placement group (when the node is already up), it is scheduled?

cc @clay4444 it seems like the issue is related to the infeasible placement group handling? Do you think you have bandwidth to take a look at this?

**Comment by noe-mis** [comment] 2021-12-08 10:40
Yes, exactly that!

**Comment by clay4444** [comment] 2021-12-09 11:44
hmm. it seems weird, I'll try to reproduce it on my local laptop firstly.

**Comment by dirkweissenborn** [comment] 2022-01-14 11:59
+1 to this. I am seeing something similar. In particular we are starting 64 runs in a single sweep with the following.

`tune.run(..., resources_per_trial={"cpu": 4, "custom_resources": {"CPU_ONLY": 4}})`

The clusters scales up to 64 nodes as can be seen but (some) jobs are not placed. Most curiously, some jobs are starting, in the below case 2, while all others are not.

```
======== Autoscaler status: 2022-01-14 12:30:19.454870 ========
Node status
---------------------------------------------------------------
Healthy:
 1 ray_head_default
 64 ray_worker_cpu
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 8.0/260.0 CPU (8.0 used of 256.0 reserved in placement groups)
 8.0/256.0 CPU_ONLY (8.0 used of 256.0 reserved in placement groups)
 0.00/663.679 GiB memory
 0.00/285.061 GiB object_store_memory

Demands:
 {'CPU': 4.0, 'CPU_ONLY': 4.0}: 1+ pending tasks/actors (1+ using placement groups)
2022-01-14 12:30:26,102	WARNING resource_demand_scheduler.py:730 -- The autoscaler could not find a node type to satisfy the request: [{'CPU_group_7fbcf34bf0ee1c12e8232d0465a0b33f': 4.0, 'CPU_group_0_7fbcf34bf0ee1c12e8232d0465a0b33f': 4.0, 'CPU_ONLY_group_0_7fbcf34bf0ee1c12e8232d0465a0b33f': 4.0, 'CPU_ONLY_group_7fbcf34bf0ee1c12e8232d0465a0b33f': 4.0}, {'bundle_group_2e58459c42b3c319879ed99c522de3e5': 0.001}]. If this request is related to placement groups the resource request will resolve itself, otherwise please specify a node type with the necessary resource https://docs.ray.io/en/master/cluster/autoscaling.html#multiple-node-type-autoscaling.
```

**Comment by efokschaner** [comment] 2022-01-17 12:36
I believe I am also running in to this on 1.9.2, launching a 1 trial tune rllib run on an unscaled cluster, autoscaling occurs but tune never starts. Will post more diagnostics tomorrow.

**Comment by rkooo567** [comment] 2022-01-17 12:38
We haven’t handled the issue yet. Let me prioritize to fix it soon. Thanks for raising it guys!

**Comment by efokschaner** [comment] 2022-01-17 20:18
I made a smaller repro and it's unclear if I'm having the same issue as others in here as my tune trial won't start even if i re-launch it after scaling.

Here's what my repro looks like:

I'm on ray version 1.9.2

- 4 CPU head node (2 CPU and 2 custom "HEAD_CPU" advertised as resources).
- 4 CPU worker node,

My rllib run set to one worker with 4 cpu per worker.

This results in the following output from tune:
```
(ray_main pid=595) == Status ==
(ray_main pid=595) Current time: 2022-01-17 11:46:36 (running for 00:03:40.19)
(ray_main pid=595) Memory usage on this node: 1.4/15.6 GiB
(ray_main pid=595) Using FIFO scheduling algorithm.
(ray_main pid=595) Resources requested: 0/6 CPUs, 0/0 GPUs, 0.0/11.97 GiB heap, 0.0/5.8 GiB objects (0.0/2.0 HEAD_CPU)
(ray_main pid=595) Result logdir: /home/ray/ray_results/appo_training
(ray_main pid=595) Number of trials: 1/1 (1 PENDING)
(ray_main pid=595) +--------------------------+----------+-------+
(ray_main pid=595) | Trial name               | status   | loc   |
(ray_main pid=595) |--------------------------+----------+-------|
(ray_main pid=595) | APPO_our_env_ab1dd_00000 | PENDING  |       |
(ray_main pid=595) +--------------------------+----------+-------+
```

`ray monitor` shows the following:
```
======== Autoscaler status: 2022-01-17 11:46:11.370168 ========
Node status
---------------------------------------------------------------
Healthy:
 1 ray_head_default
 1 ray_worker_small
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/6.0 CPU
 1.0/2.0 HEAD_CPU
 0.00/11.970 GiB memory
 0.00/5.797 GiB object_store_memory

Demands:
 {'CPU': 1.0} * 1, {'CPU': 4.0} * 1 (PACK): 1+ pending placement groups
```

I also grabbed the following state from ray in case it helps:

`ray.available_resources()`
```
{'CPU': 6.0,
 'HEAD_CPU': 1.0,
 'memory': 12852385794.0,
 'node:10.182.0.63': 1.0,
 'node:10.182.15.192': 1.0,
 'object_store_memory': 6224792213.0}
 ```

` ray.cluster_resources()`
 ```
{'CPU': 6.0,
 'HEAD_CPU': 2.0,
 'memory': 12852385794.0,
 'node:10.182.0.63': 1.0,
 'node:10.182.15.192': 1.0,
 'object_store_memory': 6224797285.0}
 ```
 
`ray.util.placement_group_table()`
```
{'23e6d966b7b3748eacf8d0dc19fd54a5': {'bundles': {0: {'CPU': 1.0},
                                                  1: {'CPU': 4.0}},
                                      'name': '__tune_83e72cbd__a565778b',
                                      'placement_group_id': '23e6d966b7b3748eacf8d0dc19fd54a5',
                                      'state': 'REMOVED',
                                      'stats': {'end_to_end_creation_latency_ms': 0.0,
                                                'highest_retry_delay_ms': 1000.0,
                                                'scheduling_attempt': 236,
                                                'scheduling_latency_ms': 0.0,
                                                'scheduling_state': 'REMOVED'},
                                      'strategy': 'PACK'},
 '23f1bf68e9a140e0e8326ba9bf60c573': {'bundles': {0: {'CPU': 1.0},
                                                  1: {'CPU': 4.0}},
                                      'name': '__tune_3f706cb3__e2694e22',
                                      'placement_group_id': '23f1bf68e9a140e0e8326ba9bf60c573',
                                      'state': 'PENDING',
                                      'stats': {'end_to_end_creation_latency_ms': 0.0,
                                                'highest_retry_delay_ms': 1000.0,
                                                'scheduling_attempt': 365,
                                                'scheduling_latency_ms': 0.0,
                                                'scheduling_state': 'NO_RESOURCES'},
                                      'strategy': 'PACK'}}
```


That `NO_RESOURCES` is a bit surprising given that I definitely have 4 + 1 CPU's available.

Let me know if there's any other information I can provide / any tips on debugging this further.

**Comment by efokschaner** [comment] 2022-01-17 21:06
I wonder if i'm running in to problems due to this logic:
Described here: https://github.com/ray-project/ray/blob/f5fdbeb5940e65bab80722786b03428cebe58d05/src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc#L104
Implemented here: https://github.com/ray-project/ray/blob/f5fdbeb5940e65bab80722786b03428cebe58d05/src/ray/gcs/gcs_server/gcs_resource_scheduler.cc#L246

If, in my case, the 1 CPU bundle were placed on th 4 CPU worker, the algorithm would have nowhere to place the 4 CPU bundle. Based on my limited understanding of the scheduler, it seems greedy with no backtracking when it fails and so it may be failing to find a solution even though one exists.

This suggests a workaround, if I can customize the tune driver resource requirements I may be able to hand-hold the scheduler.

**Comment by efokschaner** [comment] 2022-01-17 21:57
I used this approach to pin the Trainer itself to my head node, which worked:

```
class HeadCpuDefaultResourceRequest:
    @classmethod
    def default_resource_request(cls, config):
        original_pg_factory = appo.APPOTrainer.default_resource_request(config)
        bundles = original_pg_factory.bundles  # copied vie property accessor
        # This is a an assumption that the first element is always the "learner" resources
        learner_bundle = bundles[0]
        # Convert cpu to head_cpu
        learner_bundle["HEAD_CPU"] = learner_bundle["CPU"]
        del learner_bundle["CPU"]
        return tune.PlacementGroupFactory(
            bundles=bundles, strategy=original_pg_factory._strategy
        )


APPOTrainerOnHeadNode = appo.APPOTrainer.with_updates(
    mixins=[HeadCpuDefaultResourceRequest]
)

tune.run(
    APPOTrainerOnHeadNode ...
```
HEAD_CPU is a custom resource which only the head has which i defined in the cluster yaml as such:
```
...
    ray_head_default:
        # The resources provided by this node type.
        resources: {"CPU": 0, "HEAD_CPU": 2}
```

**Comment by noe-mis** [comment] 2022-01-24 15:51
Do you have any ETA on this? It is still causing us quite a lot of hassle.

**Comment by rkooo567** [comment] 2022-01-24 22:41
Hi, I will have bandwidth to investigate the issue from tmrw! I can lyk the ETA after the initial investigation

**Comment by rkooo567** [comment] 2022-01-27 07:26
@efokschaner this (https://github.com/ray-project/ray/issues/20968#issuecomment-1014885271) is probably equivalent issue as https://github.com/ray-project/ray/issues/18309. Can you confirm this?

**Comment by rkooo567** [comment] 2022-01-27 07:51
Just to let you know I had a couple interrupts, so I haven't started look into it deeply yet. I think the issue itself is probably overlapped with https://github.com/ray-project/ray/issues/18309, and I will let you guys know about the progress of the issue asap

**Comment by rkooo567** [comment] 2022-01-31 13:24
@noe-mis This issue must be fixed by https://github.com/ray-project/ray/pull/21993

@dirkweissenborn I believe your issue is the same one as  https://github.com/ray-project/ray/issues/21920. Let's follow up there. I will make a fix for this issue during next week.

**Closed** 2022-02-02 14:44 UTC
Labels: bug, P1, placement-group

**Comment by noe-mis** [comment] 2022-02-24 12:29
A bit late, but verified that it works on the nightly now. Thanks!
