### ISSUE TITLE
Rsync breaks when source or target is None

### ISSUE THREAD

**Issue by ijrsvt** [ray-project/ray#10718] opened 2020-09-10 16:20 UTC
### What is the problem?
When `rsync` is run with `source` and `target` set to `None` and `file_mounts` are included in the YAML, ray fails with
```
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by wuisawesome** [comment] 2020-09-10 16:51
Duplicate of #10720?

**Closed by wuisawesome** 2020-09-10 16:51 UTC
Labels: bug, triage
