### ISSUE TITLE
[Doc] The nav bar on the right side is not activated correctly when I clicked it  

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#33318] opened 2023-03-15 00:36 UTC
### Description

<img width="500" alt="Screen Shot 2023-03-14 at 5 35 25 PM" src="https://user-images.githubusercontent.com/18510752/225173202-5fadeb55-ebec-4f4b-9d68-d92fddb3cf21.png">

When I clicked the nav bar on the right side of the documentation, it redirects me correctly, but incorrectly activated. 

cc @maximsmol @angelinalg 

<img width="1352" alt="Screen Shot 2023-03-14 at 5 36 12 PM" src="https://user-images.githubusercontent.com/18510752/225173291-93212adc-8ead-4882-a117-8cbe6143f658.png">

**Comment by hora-anyscale** [comment] 2023-03-16 23:58
Per Triage Sync: @maxpumperla assigning to you

**Comment by peytondmurray** [comment] 2023-08-18 21:59
This is due to a bug in an upstream dependency: https://github.com/executablebooks/sphinx-book-theme/issues/678. Investigating workarounds now.

**Comment by peytondmurray** [comment] 2023-08-18 23:22
I looked into updating to `sphinx-book-theme==1.0.1`, the latest version. Happily, we can upgrade now without any conflicts with other dependencies, and it indeed solves the issue. We also would gain a lot of other benefits of upgrading; see https://github.com/ray-project/ray/issues/37944 for the issue dedicated to upgrading doc dependencies.

The downside is that the docs look completely different, a change that is way outside the scope of this issue and would best be discussed in the issue mentioned above. The other issue is that upgrading `sphinx-book-theme` is a problem with `generate_nav_html`, used in the `sbt-sidebar-nav.html` template:

```jinja
       {{- generate_nav_html(
              startdepth=0,
              kind="sidebar",
              maxdepth=4,
              collapse=True,
              includehidden=True,
              titles_only=True,
              show_nav_level=theme_show_navbar_depth) }}
```

throws an exception. I'm not sure where this function is defined, but anyway we can't make use of it as-is. So we'd have to solve that issue as well.

For now I'm going to see if we can make a workaround with some other method (JS?)

**Comment by peytondmurray** [comment] 2023-08-31 23:57
After looking into this further, the issue is in how bootstrap's ScrollSpy behaves. Some people have reported that [modifying a CSS rule seems to fix](https://github.com/twbs/bootstrap/issues/36431#issuecomment-1397391047) it, but when I load our docs I don't see any conflicting CSS rule here :/. I tried setting the appropriate rule anyway, but didn't see any change. This is supposed to get fixed in a later version of `sphinx-book-theme` anyway, so I think it might just be best to focus on upgrading our frontend build system entirely.

**Comment by peytondmurray** [comment] 2023-11-28 21:15
@maxpumperla @rkooo567 Now that #41115 is merged, can we close this? To be totally clear, this still won't always work as you might expect - for example, if there are two headings close to the bottom of the page, and you click on the last one, the second-to-last heading might be highlighted in the secondary sidebar because that's the heading the top of the window is closest to. But I think in most cases the behavior is sensible, so can we close this one out?

**Closed** 2024-03-11 00:26 UTC
Labels: P1, docs
