### ISSUE TITLE
Release test lightning_gpu_train_3x16_3x1.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#37004] opened 2023-06-30 20:26 UTC
Release test **lightning_gpu_train_3x16_3x1.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/1845#01890b56-8073-4b38-923e-49d89e6072a7 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment] 2023-06-30 20:26
Blamed commit: 80e458c0294f499665586b25c98c718c2d132325 found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/314

**Comment by can-anyscale** [comment] 2023-06-30 20:40
@amogkam potentially broke because the pinning of torchtext

**Comment by woshiyyya** [comment] 2023-06-30 20:52
Seems that torchtext 0.14.0 is in compatible with lightning 1.6.5.

Seems that the cluster env is now using BYOD. I remember previously we are building it on the fly so we can see the package versions from the build log.  @can-anyscale Do you know where I can get the package versions now?
https://console.anyscale-staging.com/o/anyscale-internal/configurations/app-config-details/bld_ddzvqtel9rmx4mxtdb8l6l2b8x

**Comment by can-anyscale** [comment] 2023-06-30 20:58
@woshiyyya the package version should be in this list https://github.com/ray-project/ray/blob/master/release/ray_release/byod/requirements_byod_3.8.txt

**Comment by amogkam** [comment] 2023-06-30 21:23
@can-anyscale I don't see torch or torchtext in https://github.com/ray-project/ray/blob/master/release/ray_release/byod/requirements_byod_3.8.txt.

What docker image or requirements file is being used for the release test?

**Comment by woshiyyya** [comment] 2023-06-30 21:25
@amogkam https://github.com/ray-project/ray/blob/fa385e7fa5c9f71856d7859a0a6ac121ba36a611/release/lightning_tests/app_config.yaml#L1C1-L1C1

I think it's "anyscale/ray-ml:nightly-py37-gpu"

**Comment by can-anyscale** [comment] 2023-06-30 21:25
Sorry sending the wrong file, this should be correct: https://github.com/ray-project/ray/blob/master/release/ray_release/byod/requirements_ml_byod_3.8.txt

**Comment by can-anyscale** [comment] 2023-06-30 21:29
The docker is 029272617770.dkr.ecr.us-west-2.amazonaws.com/anyscale/ray-ml:940625-py38-gpu (since it's a BYOD)

**Comment by amogkam** [comment] 2023-06-30 21:45
@can-anyscale can you tell me more about the how the dependencies are working here?

Is `anyscale/ray-ml:nightly-py38-gpu` used as the base image? And then on top of that `ray_release/byod/requirements_ml_byod_3.8.txt is installed?

The problem is that the torchtext version that is being installed is incompatible with the torch version that is being installed. But not sure where to make the fix.

**Comment by can-anyscale** [comment] 2023-06-30 21:53
@amogkam totally, the rayproject/ray-ml:940625-py38-gpu is used as the base image, and then anyscale_cli + ray_release/byod/requirements_ml_byod_3.8.txt is installed on top of that

ray_release/byod/requirements_ml_byod_3.8.txt has the final say on what torch and torchtext version is installed, but that file is automatically generated from this file https://github.com/ray-project/ray/blob/master/release/ray_release/byod/requirements_ml_byod_3.8.in, so you can probably fix it by adding torchtext to requirements_ml_byod_3.8.in and then re-compile that file


BTW, why pinning torchtext and torch separately if they can drift and cause breakages? Should one of them be relaxed to be compatible?

**Comment by amogkam** [comment] 2023-06-30 22:01
I'm following what's currently being done in `requirements_dl.txt`

**Comment by amogkam** [comment] 2023-06-30 22:02
BTW, are there release tests that are run without additional dependencies installed on top? So just using the docker images directly?

**Comment by can-anyscale** [comment] 2023-06-30 22:09
All release tests are run with the same set of requirements_byod so we can keep the environment hermetic. Currently there might be drift in the requirements installed in the docker image and the requirements used in test environment. There is another effort going on to eventually make them use the same infrastructure and same pinned version everywhere across CI/CD versions.

**Comment by amogkam** [comment] 2023-06-30 23:25
resolved by https://github.com/ray-project/ray/pull/37011

**Closed by amogkam** 2023-06-30 23:25 UTC
Labels: bug, P0, release-test, ml

**Comment by woshiyyya** [comment] 2023-06-30 23:43
Thank you @amogkam @can-anyscale !
