### ISSUE TITLE
[Ray Dataset] 'NoneType' object is not callable

### ISSUE THREAD

**Issue by v4if** [ray-project/ray#42819] opened 2024-01-30 02:38 UTC
### What happened + What you expected to happen

An error will be reported after the iteration through iter_torch_batches: `TypeError: 'NoneType' object is not callable`
![image](https://github.com/ray-project/ray/assets/16042235/9caac5eb-7bac-4c61-9974-45bb46d9ed29)

### Versions / Dependencies

Ray version: 2.9.1

### Reproduction script

```python
import ray
import numpy as np
import time

ray.init(num_cpus=6)
ray.data.DataContext.get_current().execution_options.verbose_progress = True


def transform1(image_batch):
    print("transform1 batch_size:", len(image_batch["image"]))
    return image_batch


def transform2(image_batch):
    print("transform2 batch_size:", len(image_batch["image"]))
    return image_batch


ray_dataset = (
    ray.data.from_items(
        [{"image": np.random.randn(224, 224, 3)} for x in range(2000)],
    )
    .map_batches(transform1, batch_size=8)
    .map_batches(transform2, batch_size=8, num_cpus=0.5)
)

print("ray_dataset", ray_dataset)

for batch in ray_dataset.iter_torch_batches(batch_size=8):
    pass

```

### Issue Severity

High: It blocks me from completing my task.

**Comment by pableeto** [comment] 2024-02-04 08:22
Same issue here. Tried the following versions and all of them has this behavior: 2.9.1, 2.9.0, 2.8.1, 2.7.1, 2.6.0.

**Comment by bveeramani** [comment] 2024-02-28 07:09
Closing because this has been fixed by https://github.com/ray-project/ray/pull/43014

**Comment by bveeramani** [comment] 2024-02-28 07:10
Duplicate of https://github.com/ray-project/ray/issues/42382

**Closed by bveeramani** 2024-02-28 07:09 UTC
Labels: bug, P2, data
