### ISSUE TITLE
Create conda installation.

### ISSUE THREAD

**Issue by veritas9872** [ray-project/ray#13184] opened 2021-01-05 07:15 UTC
### Describe your feature request

I would like to request an anaconda installation of ray (e.g. conda install -c conda-forge ray).

To the best of my understanding, ray does not have many dependencies complicating this process.

However, the lack of source code on the PYPI link means that using `conda skeleton pypi ray` does not work.

I believe that many people would find a native conda installation very convenient. For example, PyTorch uses conda as its main package manager.

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by Maltimore** [comment] 2021-01-05 10:28
Ray is already in conda-forge: https://github.com/conda-forge/ray-packages-feedstock

**Comment by sumanthratna** [comment] 2021-01-05 18:50
closing as duplicate of https://github.com/ray-project/ray/issues/585. Thanks!

**Closed by sumanthratna** 2021-01-05 18:50 UTC
Labels: enhancement
