### ISSUE TITLE
Bad error message when library deps not found for function on worker nodes

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#18771] opened 2021-09-20 23:00 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

ray throws on jupyter notebook:
```
2021-09-20 15:55:08,782	ERROR worker.py:80 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::fit_model() (pid=487, ip=10.0.19.47)
RuntimeError: This function was not imported properly.
2021-09-20 15:55:08,782	ERROR worker.py:80 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::fit_model() (pid=487, ip=10.0.19.47)
RuntimeError: This function was not imported properly.
2021-09-20 15:55:08,784	ERROR worker.py:80 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::fit_model() (pid=487, ip=10.0.19.47)
RuntimeError: This function was not imported properly.
---------------------------------------------------------------------------
RayTaskError(RuntimeError)                Traceback (most recent call last)
/tmp/ipykernel_1022/1460729839.py in <module>
     21     forecasts.append(fit_model.remote(df))
     22 
---> 23 results = [ray.get(forecasts[x]) for x in range(len(forecasts))]

/tmp/ipykernel_1022/1460729839.py in <listcomp>(.0)
     21     forecasts.append(fit_model.remote(df))
     22 
---> 23 results = [ray.get(forecasts[x]) for x in range(len(forecasts))]

~/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
     80         if client_mode_should_convert():
     81             return getattr(ray, func.__name__)(*args, **kwargs)
---> 82         return func(*args, **kwargs)
     83 
     84     return wrapper

~/anaconda3/lib/python3.7/site-packages/ray/worker.py in get(object_refs, timeout)
   1619                     worker.core_worker.dump_object_store_memory_usage()
   1620                 if isinstance(value, RayTaskError):
-> 1621                     raise value.as_instanceof_cause()
   1622                 else:
   1623                     raise value

RayTaskError(RuntimeError): ray::fit_model() (pid=487, ip=10.0.19.47)
RuntimeError: This function was not imported properly.
```

### Reproduction script

`git clone https://github.com/facebook/prophet.git`

```
import ray
import time
from prophet import Prophet
ray.init()
@ray.remote
def fit_model(comb):
    model = Prophet(yearly_seasonality=True, daily_seasonality=True)
    model.fit(comb)
    future = model.make_future_dataframe(periods=28)
    forecast = model.predict(future)
    return forecast
​
import pandas as pd
from datetime import datetime
​
df = pd.read_csv('./prophet/examples/example_wp_log_peyton_manning.csv')
​
​
forecasts=[]
for i in range(1000):
    forecasts.append(fit_model.remote(df))
​
results = [ray.get(forecasts[x]) for x in range(len(forecasts))]
```

### Anything else

you need to `pip install prophet pandas`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by AmeerHajAli** [comment] 2021-09-20 23:00
CC @ericl

**Comment by ericl** [comment] 2021-09-20 23:01
Can you reproduce without "import prophet" or the CSV read"?

**Comment by AmeerHajAli** [comment] 2021-09-20 23:04
But this is the whole point, I am not sure how I can repro without using prophet.

**Comment by AmeerHajAli** [comment] 2021-09-20 23:05
if you set the range to 100 it works
if you set it to 1000 it does not.

**Comment by ericl** [comment] 2021-09-21 02:22
I'm not able to reproduce on 8-core and 32-core clusters with {1.6, master}. This is likely an environment specific issue, could you also provide the cluster env / cloud to reproduce?

**Comment by AmeerHajAli** [comment] 2021-09-21 02:53
@ericl, it seems the issue is that the workers do not have the dependencies installed... pip installing on the head node is not sufficient.. Ahh we should improve the error message.

**Comment by AmeerHajAli** [comment] 2021-09-21 02:55
@ericl, who should take into fixing this usability issue...?

**Comment by ericl** [comment] 2021-09-21 03:02
Assign to me?

**Closed** 2021-09-22 02:50 UTC
Labels: P1, usability-hotlist, size:small
