### ISSUE TITLE
[Core] gcs_server.out becomes too big

### ISSUE THREAD

**Issue by jingzhaoo** [ray-project/ray#45678] opened 2024-06-03 06:54 UTC
### What happened + What you expected to happen

We run a few Ray serve applications. After a few days, we found that our node will run out of disk space and cause all our Ray applications to go down. Upon further digging, it is the file `gcs_sever.out` file growing too big. I checked the source code. Looks like only `gcs_sever.err` is under log monitor but not for gcs_server.out`. 

[https://github.com/ray-project/ray/blob/d4fc01c584935ba4ebe4290a7ed8470f1fa82b74/python/ray/_private/log_monitor.py#L237](https://github.com/ray-project/ray/blob/d4fc01c584935ba4ebe4290a7ed8470f1fa82b74/python/ray/_private/log_monitor.py#L237)

I am very curious why. Is there any way to limit the max size of `gcs_server.out`? I appreciate your help!

### Versions / Dependencies

2.22.0

### Reproduction script

N/A

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jjyao** [comment] 2024-06-03 21:39
We current do not log rotate gcs_server.out. Can you use some external tool like `logrotate` to do the log rotation and delete old logs to avoid disk full error?

**Comment by frank-berlin** [comment] 2024-06-04 09:29
What action is needed that after the file is moved that the deamon reopens a new file?

**Comment by manasvitickoo17** [comment] 2024-06-18 00:17
Hi, We are encountering the same issue.
Here is a snapshot of the increase in disk usage (1.5 GB per hour) by `gcs_server.out`: 
![gcs](https://github.com/ray-project/ray/assets/166422421/b8f5d465-faab-4e08-bec0-c66b3e25e447)

**Comment by frank-berlin** [comment] 2024-07-17 19:46
any the fix will be merged?
This still a huge issue.

**Comment by autolyticus** [comment] 2024-08-19 16:31
I can confirm that this is still an issue with the latest version of Ray (v2.34.0). `gcs_server.out` was single-handedly responsible for reaching 1.8TB(!) of space on my system. 

I guess especially Ray Serve applications that are supposed to be long-running processes cannot necessitate having to set quotas or restrict it with external tools. I am also unable to see any relevant workarounds for this issue on the [documentation](https://docs.ray.io/en/latest/ray-observability/user-guides/configure-logging.html)

Respectfully, this doesn't make sense for a production grade framework and is a big gap. Please do prioritise this issue. I see that the related PR #26121 was closed without being merged a few years. Is there something that the community can help with @Bye-legumes ?

**Comment by dentiny** [comment] 2024-11-21 11:06
@jingzhaoo / @autolyticus  / @manasvitickoo17 

Reading through the code, I think the feature has already been implemented:
- All components are initialized with logger, which respects max rotation size: https://github.com/ray-project/ray/blob/2dbd08a46f7f08ea614d8dd20fd0bca5682a3078/src/ray/util/logging.cc#L347-L357
- All preset env vars will be passed to system components' env: https://github.com/ray-project/ray/blob/2dbd08a46f7f08ea614d8dd20fd0bca5682a3078/python/ray/_private/services.py#L1014-L1023

I tested locally, as long as you set env var yourself, it will be passed to system component side.

**Comment by dentiny** [comment] 2024-11-21 11:18
On GCS specifically, all logs are generated from spdlog.
Checkout https://github.com/gabime/spdlog/blob/1245bf8e8a19d914271df03124da9593f3634a9c/include/spdlog/sinks/rotating_file_sink.h#L24-L28, so the overall size capped is indicated by the product for env `RAY_ROTATION_BACKUP_COUNT` and `RAY_ROTATION_MAX_BYTES`.

**Comment by dentiny** [comment] 2024-11-21 11:22
I believe the official doc already documents the behavior for these two env vars: https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-rotation

**Comment by autolyticus** [comment] 2024-11-22 06:43
This is great news. Thank you for explaining, @dentiny 

Just wondering, has this landed in a particular release version of ray yet, or is this still only in `master`?

**Comment by dentiny** [comment] 2024-11-22 07:26
Hi @atumanov , I found something new today

The weird log rotation behavior comes from spdlog, which we use for logging:
- every time you write, it's not flushed from app buffer to page cache, and it's not synced from page cache to storage
https://github.com/gabime/spdlog/blob/1245bf8e8a19d914271df03124da9593f3634a9c/include/spdlog/details/file_helper-inl.h#L100-L107
- file size is implemented via stat on disk size
https://github.com/gabime/spdlog/blob/1245bf8e8a19d914271df03124da9593f3634a9c/include/spdlog/sinks/rotating_file_sink-inl.h#L83
- so the weird truth is, say, the rotation size you've configured is 5 bytes, and you expect every log file to be less than 5 bytes; but considering spdlog only sync-s data from page cache to disk when requested, chances are that rotation happens adhoc.

I don't understand what's the reasoning behind that, my plan is to write a customized sink which has a better control on when we flush data from library buffer to page cache, and from page cache to disk.

**Comment by dentiny** [comment] 2024-11-22 11:22
I followup with spdlog team on this issue: https://github.com/gabime/spdlog/issues/3265

**Comment by dentiny** [comment] 2024-11-25 21:45
@jingzhaoo / @autolyticus Could you please provide me a minimal reproducible script for this particular issue, so I could debug locally? Thank you!

**Comment by dentiny** [comment] 2024-11-28 02:21
Further investigation and fix see https://github.com/ray-project/ray/issues/45678

**Closed** 2024-12-23 01:08 UTC
Labels: enhancement, P1, core, stability

**Comment by dentiny** [comment] 2024-12-23 01:09
Fix PR: https://github.com/ray-project/ray/pull/48952

**Comment by Hxinyue** [comment] 2026-01-05 08:39
> Fix PR: [#48952](https://github.com/ray-project/ray/pull/48952)
Have you considered also fixing this feature in the ray 2.40 version? In addition, for gcs_server.[out|err] and python-core-worker-[worker_id]_[pid].log, log rotation can be performed. Can the application logs such as worker-[worker_id]-[job_id]-[pid].[out|err] and ray_client_server-[job_id].[out|err] also have their log rotation settings configured? Because if there are a large number of logs in the application, the content of worker-[worker_id]-[job_id]-[pid].[out|err] at this time will also be quite large.
