### ISSUE TITLE
[CI] `osx://python/ray/tests:test_scheduling_performance` is failing/flaky on master.

### ISSUE THREAD

**Issue by fishbone** [ray-project/ray#38665] opened 2023-08-21 17:40 UTC
- 762119f78b15a6485c263fd34c9443211a9ff5c1 FAILED [Buildkite :mac: :apple: Small & Client](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5564#018a0a05-6c5a-4567-b938-f9f5dc65bb77)
- f19b212ba7570e6078dd1d036515ee393c961df2 FAILED [Buildkite :mac: :apple: Small & Client](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5550#018a057c-49af-41c4-b58c-6bde7385ecee)
- f6930684b469cba16f34a016a0a06e1653de4019 FAILED [Buildkite :mac: :apple: Small & Client](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5539#018a0472-7c32-4db6-b144-42b2b08bd62a)
- 2db8e8a50eff6e669c8ed01d1cfeb7d0d9c28086 FAILED [Buildkite :mac: :apple: Small & Client](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5530#018a0417-3067-4e44-b9f2-cb7209dcb45a)
- b73a496af19bce627a611e7af2cb02a3c5d99684 FAILED [Buildkite :mac: :apple: Small & Client](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5527#018a02d9-09d4-4b0c-b68e-3e622445147d)
- c6ad28afac2b9d8b13b4d870c932e55bfb342ee4 FAILED [Buildkite :mac: :apple: Small & Client](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5519#018a013b-c6c3-4dba-9529-eb15281a1d1a)
- 80ff67645aaadf74429c1ae5fcbf0d47d7cdddb5 FAILED [Buildkite :mac: :apple: Small & Client](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5490#0189fd0a-9ecc-4301-a16a-9141e29fca8b)
- 329b409b54c7dcb2801a102f74702e61be2d8872 FAILED [Buildkite :mac: :apple: Small & Client](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5487#0189fc3d-ca89-4591-a92e-1482b9c15ac9)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-osx://python/ray/tests:test_scheduling_performance-END
....

**Comment by jjyao** [comment] 2024-03-25 20:19
Duplicate of #44238

**Closed by jjyao** 2024-03-25 20:19 UTC
Labels: P0, core, flaky-tracker, ray 2.10, weekly-release-blocker, stability
