### ISSUE TITLE
[Bug] Dashboard hangs computer in Windows 11

### ISSUE THREAD

**Issue by evo11x** [ray-project/ray#22509] opened 2022-02-18 23:40 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib, Dashboard

### What happened + What you expected to happen

When dashboard is enabled the computer hangs randomly and there is high memory load, even when the dashboard is not opened in the browser.

I suspect that the problem is caused by redis, because it is displayed with occasional high cpu usage in task manager.

### Versions / Dependencies

ray 1.10, python 3.9, 96GB RAM, RTX3060, Windows 11

### Reproduction script

the performance returns to normal with this line
`ray.init(include_dashboard=False)`

### Anything else

The problem occurs every time

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mattip** [comment] 2022-02-22 15:52
I wonder if this is connected to windows 11 and/or some new firewall setting

**Comment by mattip** [comment] 2022-03-06 17:45
Could you describe exactly what you did to get this? I cannot reproduce the problem, and without a reproducer it is hard to fix it.

**Comment by evo11x** [comment] 2022-03-06 17:48
Try to add these settings to reproduce the problem, I have a box action space and box observation

cfg = ppo.DEFAULT_CONFIG.copy()
cfg["num_gpus"] = 1    
cfg["num_workers"] = 8
cfg["num_envs_per_worker"] = 2 
cfg["framework"] = "torch"

**Comment by mattip** [comment] 2022-03-07 13:46
@evo11x that description is too telegraphic. Here is what I did and it worked fine for me on windows10 using conda
```
> conda create -n ray_test python=3.9
> conda activate ray_test
> pip install ray==1.10
> pip install ray[default]
> ray start --head --include-dashboard=True
> start http://127.0.0.1:8265
```

**Comment by evo11x** [comment] 2022-03-07 15:57
I have Windows 11 not 10

**Comment by mattip** [comment] 2022-03-07 16:04
@evo11x that might be the problem. Could you describe the steps you are using to install and run your script, just to make sure nothing else is problematic?

**Comment by evo11x** [comment] 2022-03-07 17:09
@mattip I use Visual Code with virtualenv, 
pip install "ray[rllib]" tensorflow torch

and I run the script from visual code

Try to increase num_workers to 10 or 20, and use gpu

**Comment by evo11x** [comment] 2022-03-08 15:32
I am not allowed to share the script because it contains private data, but I will try to make a demo script to demonstrate more bugs which I found

**Comment by mattip** [comment] 2022-05-05 02:27
@evo11x any progress with a reproducer script?

**Comment by mattip** [comment] 2022-07-04 07:06
This issue does not have a clear reproducer, and the only indication of a problem (high CPU use of redis) is no longer relevant since redis is no longer used by default. I will close it, please reopen or open a new issue if the problem returns.

**Closed by mattip** 2022-07-04 07:06 UTC
Labels: bug, needs-repro-script, dashboard, QS
