### ISSUE TITLE
[Core and RLlib] RLlib crashes on Win due to OOM even with simple Trainers (actors seem to use much more memory than on e.g. Mac).

### ISSUE THREAD

**Issue by sven1977** [ray-project/ray#24926] opened 2022-05-18 17:23 UTC
### What happened + What you expected to happen

RLlib on Win keeps crashing due to OOM errors. Actors (from RLlib's RolloutWorker class) seem to take much more memory than say on MAc or Linux.

### Versions / Dependencies

master
Win10 64 32Gig RAM

### Reproduction script

Running e.g. `rllib/agents/a3c/tests/test_a2c.py` and `rllib/agents/a3c/tests/test_a3c.py` both at the same time (such that more than one RLlib Trainer is instantiated) reliably causes the crash on my 32Gig RAM machine.

The error looks somewhat like this:

```
022-05-18 19:11:43,308	WARNING trainer.py:546 -- Worker crashed during call to `step_attempt()`. To try to continue training without failed worker(s), set `ignore_worker_failures=True`. To try to recover the failed worker(s), set `recreate_failed_workers=True`.
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\JetBrains\PyCharm2021.3\scratches\scratch_28.py", line 14, in <module>
    print(trainer2.train())
  File "C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\tune\trainable.py", line 360, in train
    result = self.step()
  File "C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\rllib\agents\trainer.py", line 553, in step
    raise e
  File "C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\rllib\agents\trainer.py", line 534, in step
    step_attempt_results = self.step_attempt()
  File "C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\rllib\agents\trainer.py", line 636, in step_attempt
    step_results = self._exec_plan_or_training_iteration_fn()
  File "C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\rllib\agents\trainer.py", line 1604, in _exec_plan_or_training_iteration_fn
    results = self.training_iteration()
  File "C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\rllib\agents\a3c\a2c.py", line 153, in training_iteration
    return Trainer.training_iteration(self)
  File "C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\rllib\agents\trainer.py", line 878, in training_iteration
    train_batch = synchronous_parallel_sample(
  File "C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 99, in synchronous_parallel_sample
    sample_batches = ray.get(
  File "C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\worker.py", line 1839, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RayOutOfMemoryError): ray::RolloutWorker.sample() (pid=40016, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000288CDBDA8B0>)
  File "python\ray\_raylet.pyx", line 623, in ray._raylet.execute_task
  File "C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\_private\memory_monitor.py", line 162, in raise_if_low_memory
    raise RayOutOfMemoryError(
ray._private.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node DESKTOP-0LQ89AE is used (31.63 / 31.92 GB). The top 10 memory consumers are:

PID	MEM	COMMAND
40088	4.78GiB	C:\Programs\Anaconda3\envs\ray\python.exe C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\worke
4696	3.14GiB	C:\Programs\JetBrains\PyCharm 2021.3.1\bin\pycharm64.exe
40692	2.32GiB	C:\Programs\Anaconda3\envs\ray\python.exe C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\worke
14840	1.68GiB	C:\Programs\Anaconda3\envs\ray\python.exe C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\worke
39888	1.6GiB	C:\Programs\Anaconda3\envs\ray\python.exe C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\worke
38428	1.6GiB	C:\Programs\Anaconda3\envs\ray\python.exe C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\worke
40016	1.53GiB	C:\Programs\Anaconda3\envs\ray\python.exe C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\worke
16680	1.53GiB	C:\Programs\Anaconda3\envs\ray\python.exe C:/Users/Admin/AppData/Roaming/JetBrains/PyCharm2021.3/scr
28808	1.5GiB	C:\Programs\Anaconda3\envs\ray\python.exe C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\worke
46120	1.49GiB	C:\Programs\Anaconda3\envs\ray\python.exe C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\worke

In addition, up to 0.0 GiB of shared memory is currently being used by the Ray object store.
---
--- Tip: Use the `ray memory` command to list active objects in the cluster.
--- To disable OOM exceptions, set RAY_DISABLE_MEMORY_MONITOR=1.
---
Exception ignored in: <function RolloutWorker.__del__ at 0x0000024388D3A9D0>
Traceback (most recent call last):
  File "C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\util\tracing\tracing_helper.py", line 461, in _resume_span
TypeError: 'NoneType' object is not callable
Exception ignored in: <function RolloutWorker.__del__ at 0x000002439D3AB430>
Traceback (most recent call last):
  File "C:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\util\tracing\tracing_helper.py", line 461, in _resume_span
TypeError: 'NoneType' object is not callable

Process finished with exit code 1
```

![grafik](https://user-images.githubusercontent.com/5839854/169104172-a705bdee-8562-46ec-8d1a-7f2ac39d02c3.png)

### Issue Severity

High: It blocks me from completing my task.

**Comment by czgdp1807** [comment] 2022-05-19 06:21
I don't get a memory error but I get invalid handle error. See the logs below,

```bash
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\ray_dev\lib\logging\__init__.py", line 1088, in emit
    stream.write(msg + self.terminator)
  File "c:\users\gagan\ray_project\ray\python\ray\thirdparty_files\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "c:\users\gagan\ray_project\ray\python\ray\thirdparty_files\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "c:\users\gagan\ray_project\ray\python\ray\thirdparty_files\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\users\gagan\ray_project\ray\python\ray\thirdparty_files\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\users\gagan\ray_project\ray\python\ray\thirdparty_files\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "c:\users\gagan\ray_project\ray\python\ray\thirdparty_files\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "c:\users\gagan\ray_project\ray\python\ray\thirdparty_files\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\users\gagan\ray_project\ray\python\ray\thirdparty_files\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
OSError: [WinError 6] The handle is invalid
```

**Comment by mattip** [comment] 2022-05-19 12:27
Could this be the difference between forking processes vs spawning? For instance, here ray uses `os.system` on windows (spawning) and `os.execvp` otherwise (forking).
https://github.com/ray-project/ray/blob/88dfc20c6e0b6d57794cdb565f221aa99c0b4882/python/ray/_private/runtime_env/context.py#L71-L79

I'm sure there are more places like this.

**Comment by gjoliver** [comment] 2022-06-01 17:21
@czgdp1807 @mattip, are you guys able to resolve the reproduce the problem?
do we have to do anything on our side to help?
thanks.

**Comment by mattip** [comment] 2022-06-09 06:45
Could you give complete instructions for how to replicate? I am getting an error that `PongDeterministic-v0` is not a valid gym environment. I see `Pong-ramDeterministic-v0` but not `PongDeterministic-vo`. Also: are you using pytorch or tensorflow to run the tests?

**Comment by PhilippWillms** [comment] 2022-07-15 18:19
I was able to reproduce the issue described above today with the very simple commands below, Important to choose `PyTorch`, with `tensorflow `it is not throwing the error, but leading to memory crash.

```
from ray.rllib.agents.ppo import PPOTrainer
if __name__ == "__main__":
    trainer = PPOTrainer(
        config={
            "env": "CartPole-v0",
            "num_workers": 3,
            "framework": "torch",
        }
    )
```

Error message:
```
2022-07-15 20:15:12,335 WARNING ppo.py:386 -- `train_batch_size` (4000) cannot be achieved with your other settings (num_workers=3 num_envs_per_worker=1 rollout_fragment_length=200)! Auto-adjusting `rollout_fragment_length` to 1333.
Exception ignored in: <function RolloutWorker.__del__ at 0x000001DE01D9A040>
Traceback (most recent call last):
  File "C:\Users\Philipp\anaconda3\envs\py38-wksimrl\lib\site-packages\ray\util\tracing\tracing_helper.py", line 461, in _resume_span
TypeError: 'NoneType' object is not callable`
```

Find my specs below:

- Windows 10.0.19044 Build 19044
- Ray: 1.13.0
- Python: 3.8.13
- PyTorch: 1.12.0

**Comment by hora-anyscale** [comment] 2022-10-24 23:59
Per Triage Sync: @mattip @czgdp1807 who from QS can pick this up?

cc: @richardliaw

**Comment by mattip** [comment] 2022-11-13 15:36
@PhilippWillms does this reproduce with ray 2.0.0 or later?

**Comment by PhilippWillms** [comment] 2022-11-13 17:58
> @PhilippWillms does this reproduce with ray 2.0.0 or later?

With PyTorch == 1.13.0 and Ray == 2.0.1, it is working fine. 

Nevertheless, there is still Memory allocation with `tensorflow` using the tf2 framework specifier. At the moment, I cannot give you a trace, as whole workstation runs in stackoverflow and needs hard reboot. Maybe there is some separate documentation or training needed how to use `tf2` correctly , also together with `ray.init()`-

```
from ray.rllib.agents.ppo import PPOTrainer
if __name__ == "__main__":
    trainer = PPOTrainer(
        config={
            "env": "CartPole-v0",
            "num_workers": 3,
            "framework": "tf2",
        }
    )
```

**Comment by mattip** [comment] 2022-11-13 20:35
Good to hear that the problems with PyTorch have seemingly dissipated. 
I assume the failure of tf2 is with ray 2.0.1.
What version of tensor flow, on what hardware (how much RAM and which GPU?)

**Comment by mattip** [comment] 2022-11-15 12:18
@PhilippWillms ping. Can you provide more information about the environment that still is problematic?

**Comment by mattip** [comment] 2022-11-15 15:04
See also #24955

**Comment by richardliaw** [comment] 2023-02-15 19:55
Closing this since there doesn't seem to be a clear repro and the original issue seems to be resolved.

**Closed by richardliaw** 2023-02-15 19:55 UTC
Labels: bug, P1, windows, rllib, QS, core
