### ISSUE TITLE
[RLlib] restore from checkpoint fails with torch==1.12

### ISSUE THREAD

**Issue by inpefess** [ray-project/ray#26391] opened 2022-07-08 13:45 UTC
### What happened + What you expected to happen

Any algorithm trained with torch==1.12 fails to restore from a checkpoint. In torch=1.11 it doesn't happen.
The reason is a new parameter of torch optimisers(e.g. https://pytorch.org/docs/stable/generated/torch.optim.SGD.html#torch.optim.SGD), `foreach`. It has type `Optional[bool]` and is `None` by default. For now, it's equivalent to `False` (see https://github.com/pytorch/pytorch/blob/135af0fe3046b9545fcf6ad274c66c79533d939f/torch/optim/sgd.py#L186) but might change in future. Ray tries to transform all the optimiser parameters to tensors and fails here: https://github.com/ray-project/ray/blob/86b9b4b7a580c39d7eb610a8c698e5efd1d18548/rllib/utils/torch_utils.py#L170

### Versions / Dependencies

# git HEAD 6dd564d8b5123be5f3cf8e95197f4866c003b312

pip install torch==1.12

### Reproduction script

pytest rllib/tests/test_checkpoint_restore.py::TestCheckpointRestorePG::test_ppo_checkpoint_restore

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by inpefess** [comment] 2022-07-08 13:48
If setting `foreach` to False instead of None seems to be a reasonable workaround for now, I can work on this issue. Another option may be to allow None values in `TensorStructType`, but it can affect too many things.

**Comment by ArturNiederfahrenhorst** [comment] 2022-08-03 11:01
Hi, thanks for reporting this. I could not reproduce and discovered that this was fixed by @Rohan?????
in 97bcf38ec05c9586e6c8b30789bd44e8ab912d3a.

**Closed by ArturNiederfahrenhorst** 2022-08-03 11:01 UTC
Labels: bug, P1, triage, rllib, rllib-torch

**Comment by Rohan138** [comment] 2022-08-03 21:48
@ArturNiederfahrenhorst By the way-you tagged the wrong Rohan
