### ISSUE TITLE
"Node Failure" on nested references

### ISSUE THREAD

**Issue by NathanTP** [ray-project/ray#17717] opened 2021-08-10 20:31 UTC
### What is the problem?
When nesting actors, you can sometimes get the following error:

> ray.exceptions.ObjectLostError: Object ffffffffffffffffffffffffffffffffffffffffffffffffffffffff is lost due to node failure.

This does not seem completely deterministic, although I can reproduce it pretty reliably. The main conditions for it seem to be when and where you ray.get() any of the intermediate references. For example, if an actor in the middle of the call chain ray.get()s one of the nested references before passing it up the call stack, the bug goes away. Another trigger seems to be where in the driver program you ray.get() the final answer. Calling ray.get() from the same function that triggered the call chain works, while returning the reference from the host function to another host function will trigger the bug.

It's a bit involved to trigger the bug, so the example code below is the best description of the precise scenario.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray version: master branch (febe54f4220054eefd134b2a770a532d7a90e1f5)
Python 3.8
Ubuntu 18.04 (Linux 4.15)

### Reproduction (REQUIRED)
```
import ray

TRIGGER_SOLUTION_1 = False
TRIGGER_SOLUTION_2 = False


@ray.remote
class Actor1():
    def foo(self):
        # type: ref(str)
        ref = ray.put('foo')

        return ref


@ray.remote
class Actor2():
    def __init__(self):
        self.actor1 = Actor1.remote()

    def bar(self):
        # type: ref(ref(str))
        res = self.actor1.foo.remote()

        if TRIGGER_SOLUTION_1:
            res = ray.get(res)

        return res


@ray.remote
def task1(arg):
    # arg is ref(str) if we didn't do ray.get in Actor2
    # arg is str if we did ray.get in Actor2
    if TRIGGER_SOLUTION_1:
        # arg type: str
        res = arg
    else:
        # This will fail
        # arg type: ref(str)
        res = ray.get(arg)

    return res


def caller():
    actor2 = Actor2.remote()

    # type: ref(ref(ref(str)))
    actor2Ref = actor2.bar.remote()

    # type: ref(ref(str))
    actor1Ref = ray.get(actor2Ref)

    # type: ref(str)
    task1Ref = task1.remote(actor1Ref)

    if TRIGGER_SOLUTION_2:
        # type: str
        task1Result = ray.get(task1Ref)
        print("Final Answer: ", task1Result)

    return task1Ref


ray.init()

answerRef = caller()

if not TRIGGER_SOLUTION_2:
    # This will fail, it will also fail if we never try to ray.get(answerRef)
    result = ray.get(answerRef)
    print("Result: ", result)
```

- [ x] I have verified my script runs in a clean environment and reproduces the issue.
- [ x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

@stephanie-wang

**Comment by stephanie-wang** [comment] 2021-08-10 20:39
The error message is misleading but it looks like this might be due to a ref counting issue. What happens if you keep the `actor2` handle in scope?

**Comment by NathanTP** [comment] 2021-08-10 20:54
That does seem to fix it, though the error isn't super deterministic.

The version below works reliably. If you instead create a new actor2 every time within caller, it fails. This could be due to reference counting issues or due to creating a new actor2 for each call. Calling it with n=1 doesn't reproduce for me right now, but I think that's just because the bug is non-determinisitc and my system doesn't feel like triggering it anymore.

```
def caller(actor2):
    # type: ref(ref(ref(str)))
    actor2Ref = actor2.bar.remote()

    # type: ref(ref(str))
    actor1Ref = ray.get(actor2Ref)

    # type: ref(str)
    task1Ref = task1.remote(actor1Ref)

    if TRIGGER_SOLUTION_2:
        # type: str
        task1Result = ray.get(task1Ref)
        print("Final Answer: ", task1Result)

    return task1Ref


ray.init()


def runTest(n):
    results = []
    for i in range(n):
        actor2 = Actor2.remote()
        answerRef = caller(actor2)

        if not TRIGGER_SOLUTION_2:
            # This will fail, it will also fail if we never try to ray.get(answerRef)
            results.append(ray.get(answerRef))
    print("Results: ", results)


runTest(10)
```

**Comment by stephanie-wang** [comment] 2021-08-10 22:12
I think I've tracked down the root cause to two issues: #17718 and #17719. So I will close this one for now to avoid duplicating.

For now, the recommended workaround is probably to call the additional `ray.get`s, as you said :/

By the way, is this a blocker for you?

**Closed by stephanie-wang** 2021-08-10 22:12 UTC
Labels: bug, triage
