### ISSUE TITLE
[CI] `linux://python/ray/tests:test_client_builder` is failing/flaky on master.

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#38224] opened 2023-08-08 16:56 UTC
- 6be8853ffa529a8801602f90637594131c1fddc5 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5330#0189d513-7ad1-49f3-9b6f-862d0f58aa03)
- 031353f8a3a14ab1f8cc33db0d5b92e8f4beb36b FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5322#0189d2b2-f177-4e11-9ff7-96d5a46df29c)
- 56a72b5f121376ab4a1e270750db11073b877840 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5321#0189d2a0-fdf6-4aee-8d51-947a01db13e5)
- bda04d4d446a4e27819bde5d5300b8ac7b46cd56 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5314#0189d186-e4ed-44a3-8e95-9df666427349)
- bee3833cf51ec9c80bf6fd9316223c2bfea1a3ed FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5312#0189d177-b31f-4e74-b628-409f39178334)
- 56ff789cbbdf980b2d831bc0c476f24d0ad17537 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5310#0189d166-8dd8-4ed3-bf34-df2af12f7a33)
- 7ab59fd0c2bd99bb45fd1ec1351c00088e15a840 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5308#0189d0fa-f559-4ea1-b46b-514938100eb5)
- 84ce146e4c5ad08b27cdb798aaf70de6bf457573 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5305#0189d0cc-bc33-44a3-90a1-af33e663bd26)
- 4304e45527a68e6326bedb69ae96d623cedb8bd4 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5298#0189c398-9c62-4acd-bc40-5c16c67e1c9f)
- 73311c4e3ff45bf532182d4cb90203bc7c49a69c FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5292#0189c256-6b8c-4ac9-ab86-57e6cec605e9)
- 3755c5b2431d299a9c3b52c5708a3650ce32c1ff FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5282#0189c1d9-6bbd-47c0-a5ce-ffbc5b7abff0)
- 81b1e8fdcf53521fb4039eaaef32aa798af3c913 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5272#0189bdf5-c5b2-4de3-9a98-209c9d5965f8)
- d0f5adf0b5cd145c59e6aa588fe8fd139c7d2965 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5262#0189bcb1-c90b-4e7d-94ee-a3b4455287ee)
- f91b50da14c77dc5415f681fff6921936176068d FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5250#0189b8ac-9a9d-45ce-aca6-fd97166d0316)
- 32212dc61b72cbb753123640ebf26fb07d26c712 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5245#0189b7f4-610b-4260-882e-ccf4ac13abd2)
- 50e4d4cd1126f26f7497485d0dc2bef9b9c5209a FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5243#0189b783-1577-4f86-95c1-4d24167e9620)
- 25cf1842da5fab09466b5e548b0214b6bd8e750f FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5241#0189b73b-5d1b-4841-998b-48a6690e1483)
- 67945d078942c99e859d97eef5c6e3aa6b132283 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5240#0189b71c-3cd1-45db-a6b5-e50889031930)
- 48488f50de39a9d7ef51094b5c5eefabee3ba08c FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5236#0189b61e-e782-4ca9-9aa5-629bbaed2863)
- 8a84227416b72b63d25a79449e62386a954d7cc9 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5232#0189b39c-757f-4bfd-940d-77bd3728cc57)
- 787de4c2b6f7f039b06bf25e2c7bdfbcab133c4e FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5227#0189b238-fab1-4847-be79-fa1e1ef9b5a8)
- ba2e40678d1efbc385dad564eeddbdd6d356c6b4 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5226#0189b207-a70f-42d1-9095-9c4efd8522fa)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_client_builder-END
....

**Comment by jjyao** [comment] 2024-01-31 23:30
Duplicate of #42875

**Closed by jjyao** 2024-01-31 23:30 UTC
Labels: P1, core-client, core, flaky-tracker, ray 2.11
