### ISSUE TITLE
[Bug] [autoscaler] [gcp] [docker] `ray up gcp/example-full.yaml` requires two tries

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#18755] opened 2021-09-20 00:50 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

Running
```ray up gcp/example-full.yaml -vvvvvvvvv```
once yields (I named the cluster `tttttdefaultttttttttttt`)
```
Cluster: tttttdefaultttttttttttt

2021-09-19 17:18:27,066 INFO util.py:282 -- setting max workers for head node type to 0
Checking GCP environment settings
2021-09-19 17:18:30,246 INFO config.py:449 -- _configure_key_pair: Private key not specified in config, using/Users/dmitrigekhtman/.ssh/ray-autoscaler_gcp_us-west1_dmitri-test-300222_ubuntu_0.pem
No head node found. Launching a new cluster. Confirm [y/N]: y

Acquiring an up-to-date head node
2021-09-19 17:18:46,690 INFO node.py:295 -- wait_for_compute_zone_operation: Waiting for operation operation-1632097125440-5cc6239669b4d-77b51b5b-c48dc92d to finish...
2021-09-19 17:18:57,154 INFO node.py:307 -- wait_for_compute_zone_operation: Operation operation-1632097125440-5cc6239669b4d-77b51b5b-c48dc92d finished.
  Launched a new head node
  Fetching the new head node

<1/1> Setting up head node
  Prepared bootstrap config
2021-09-19 17:18:57,968 INFO node.py:295 -- wait_for_compute_zone_operation: Waiting for operation operation-1632097137620-5cc623a2076f1-00a7d5c6-3ab1720d to finish...
2021-09-19 17:19:03,312 INFO node.py:307 -- wait_for_compute_zone_operation: Operation operation-1632097137620-5cc623a2076f1-00a7d5c6-3ab1720d finished.
  New status: waiting-for-ssh
  [1/7] Waiting for SSH to become available
    Running `uptime` as a test.
    Fetched IP: 34.105.87.101
    Running `uptime`
      Full command is `ssh -tt -i /Users/dmitrigekhtman/.ssh/ray-autoscaler_gcp_us-west1_dmitri-test-300222_ubuntu_0.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_58967657f5/d0cfe78324/%C -o ControlPersist=10s -o ConnectTimeout=5s ubuntu@34.105.87.101 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'`
ssh: connect to host 34.105.87.101 port 22: Connection refused
    SSH still not available (SSH command failed.), retrying in 5 seconds.
    Running `uptime`
      Full command is `ssh -tt -i /Users/dmitrigekhtman/.ssh/ray-autoscaler_gcp_us-west1_dmitri-test-300222_ubuntu_0.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_58967657f5/d0cfe78324/%C -o ControlPersist=10s -o ConnectTimeout=5s ubuntu@34.105.87.101 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'`
Warning: Permanently added '34.105.87.101' (ECDSA) to the list of known hosts.
ubuntu@34.105.87.101: Permission denied (publickey).
    SSH still not available (SSH command failed.), retrying in 5 seconds.
    Running `uptime`
      Full command is `ssh -tt -i /Users/dmitrigekhtman/.ssh/ray-autoscaler_gcp_us-west1_dmitri-test-300222_ubuntu_0.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_58967657f5/d0cfe78324/%C -o ControlPersist=10s -o ConnectTimeout=5s ubuntu@34.105.87.101 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'`
Warning: Permanently added '34.105.87.101' (ECDSA) to the list of known hosts.
 00:19:18 up 0 min,  1 user,  load average: 1.65, 0.39, 0.13
Shared connection to 34.105.87.101 closed.
    Success.
  Updating cluster configuration. [hash=a60dcad0bd2eb59112a4b5b7ee6e8338b0e1182c]
2021-09-19 17:19:19,126 INFO node.py:295 -- wait_for_compute_zone_operation: Waiting for operation operation-1632097158830-5cc623b64195b-11e094af-aafc969d to finish...
2021-09-19 17:19:24,450 INFO node.py:307 -- wait_for_compute_zone_operation: Operation operation-1632097158830-5cc623b64195b-11e094af-aafc969d finished.
  New status: syncing-files
  [2/7] Processing file mounts
    Running `mkdir -p /tmp/ray_tmp_mount/tttttdefaultttttttttttt/~ && chown -R ubuntu /tmp/ray_tmp_mount/tttttdefaultttttttttttt/~`
      Full command is `ssh -tt -i /Users/dmitrigekhtman/.ssh/ray-autoscaler_gcp_us-west1_dmitri-test-300222_ubuntu_0.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_58967657f5/d0cfe78324/%C -o ControlPersist=10s -o ConnectTimeout=120s ubuntu@34.105.87.101 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (mkdir -p /tmp/ray_tmp_mount/tttttdefaultttttttttttt/~ && chown -R ubuntu /tmp/ray_tmp_mount/tttttdefaultttttttttttt/~)'`
Shared connection to 34.105.87.101 closed.
    Running `rsync --rsh ssh -i /Users/dmitrigekhtman/.ssh/ray-autoscaler_gcp_us-west1_dmitri-test-300222_ubuntu_0.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_58967657f5/d0cfe78324/%C -o ControlPersist=10s -o ConnectTimeout=120s -avz --exclude **/.git --exclude **/.git/** --filter dir-merge,- .gitignore /var/folders/s8/6bvltss57rl_d_3_92c3r2140000gn/T/ray-bootstrap-28u3zc16 ubuntu@34.105.87.101:/tmp/ray_tmp_mount/tttttdefaultttttttttttt/~/ray_bootstrap_config.yaml`
building file list ... done
ray-bootstrap-28u3zc16

sent 1110 bytes  received 42 bytes  2304.00 bytes/sec
total size is 2733  speedup is 2.37
    Running `docker inspect -f '{{.State.Running}}' ray_container || true`
      Full command is `ssh -tt -i /Users/dmitrigekhtman/.ssh/ray-autoscaler_gcp_us-west1_dmitri-test-300222_ubuntu_0.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_58967657f5/d0cfe78324/%C -o ControlPersist=10s -o ConnectTimeout=120s ubuntu@34.105.87.101 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (docker inspect -f '"'"'{{.State.Running}}'"'"' ray_container || true)'`
Shared connection to 34.105.87.101 closed.
    `rsync`ed /var/folders/s8/6bvltss57rl_d_3_92c3r2140000gn/T/ray-bootstrap-28u3zc16 (local) to ~/ray_bootstrap_config.yaml (remote)
    ~/ray_bootstrap_config.yaml from /var/folders/s8/6bvltss57rl_d_3_92c3r2140000gn/T/ray-bootstrap-28u3zc16
    Running `mkdir -p /tmp/ray_tmp_mount/tttttdefaultttttttttttt/~ && chown -R ubuntu /tmp/ray_tmp_mount/tttttdefaultttttttttttt/~`
      Full command is `ssh -tt -i /Users/dmitrigekhtman/.ssh/ray-autoscaler_gcp_us-west1_dmitri-test-300222_ubuntu_0.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_58967657f5/d0cfe78324/%C -o ControlPersist=10s -o ConnectTimeout=120s ubuntu@34.105.87.101 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (mkdir -p /tmp/ray_tmp_mount/tttttdefaultttttttttttt/~ && chown -R ubuntu /tmp/ray_tmp_mount/tttttdefaultttttttttttt/~)'`
Shared connection to 34.105.87.101 closed.
    Running `rsync --rsh ssh -i /Users/dmitrigekhtman/.ssh/ray-autoscaler_gcp_us-west1_dmitri-test-300222_ubuntu_0.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_58967657f5/d0cfe78324/%C -o ControlPersist=10s -o ConnectTimeout=120s -avz --exclude **/.git --exclude **/.git/** --filter dir-merge,- .gitignore /Users/dmitrigekhtman/.ssh/ray-autoscaler_gcp_us-west1_dmitri-test-300222_ubuntu_0.pem ubuntu@34.105.87.101:/tmp/ray_tmp_mount/tttttdefaultttttttttttt/~/ray_bootstrap_key.pem`
building file list ... done
ray-autoscaler_gcp_us-west1_dmitri-test-300222_ubuntu_0.pem

sent 1469 bytes  received 42 bytes  1007.33 bytes/sec
total size is 1675  speedup is 1.11
    Running `docker inspect -f '{{.State.Running}}' ray_container || true`
      Full command is `ssh -tt -i /Users/dmitrigekhtman/.ssh/ray-autoscaler_gcp_us-west1_dmitri-test-300222_ubuntu_0.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_58967657f5/d0cfe78324/%C -o ControlPersist=10s -o ConnectTimeout=120s ubuntu@34.105.87.101 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (docker inspect -f '"'"'{{.State.Running}}'"'"' ray_container || true)'`
Shared connection to 34.105.87.101 closed.
    `rsync`ed /Users/dmitrigekhtman/.ssh/ray-autoscaler_gcp_us-west1_dmitri-test-300222_ubuntu_0.pem (local) to ~/ray_bootstrap_key.pem (remote)
    ~/ray_bootstrap_key.pem from /Users/dmitrigekhtman/.ssh/ray-autoscaler_gcp_us-west1_dmitri-test-300222_ubuntu_0.pem
  [3/7] No worker file mounts to sync
2021-09-19 17:19:31,205 INFO node.py:295 -- wait_for_compute_zone_operation: Waiting for operation operation-1632097170822-5cc623c1b166e-217a8d72-cf0e2caf to finish...
2021-09-19 17:19:36,606 INFO node.py:307 -- wait_for_compute_zone_operation: Operation operation-1632097170822-5cc623c1b166e-217a8d72-cf0e2caf finished.
  New status: setting-up
  [4/7] No initialization commands to run.
  [5/7] Initalizing command runner
    Running `command -v docker || echo 'NoExist'`
      Full command is `ssh -tt -i /Users/dmitrigekhtman/.ssh/ray-autoscaler_gcp_us-west1_dmitri-test-300222_ubuntu_0.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_58967657f5/d0cfe78324/%C -o ControlPersist=10s -o ConnectTimeout=120s ubuntu@34.105.87.101 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (command -v docker || echo '"'"'NoExist'"'"')'`
Shared connection to 34.105.87.101 closed.
2021-09-19 17:19:37,812 INFO node.py:295 -- wait_for_compute_zone_operation: Waiting for operation operation-1632097177433-5cc623c7ff6c6-a7ac08bf-b6a8300b to finish...
2021-09-19 17:19:43,227 INFO node.py:307 -- wait_for_compute_zone_operation: Operation operation-1632097177433-5cc623c7ff6c6-a7ac08bf-b6a8300b finished.
  New status: update-failed
  !!!
  {'message': 'SSH command failed.'}
  SSH command failed.
  !!!

  Failed to setup head node.
```
Running `ray up gcp/example-full.yaml` again yields successful setup.

### Reproduction script

See above, happens with current master.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment] 2021-09-20 00:53
cc @ijrsvt -- does the error output give you a sense of what's up?

**Comment by ijrsvt** [comment] 2021-09-20 17:08
Not quite. I'm guessing this is another issue with the actual error being swallowed.

**Comment by DmitriGekhtman** [comment] 2021-09-24 15:48
Can no longer reproduce the issue. Going to focus on related problem of ssh command error output failing to show https://github.com/ray-project/ray/issues/18774

**Comment by AmeerHajAli** [comment] 2021-09-28 17:50
should this be a P0?

**Comment by richardliaw** [comment] 2021-09-28 17:53
GCP is not usable on OSS with this bug!

**Comment by AmeerHajAli** [comment] 2021-09-28 17:57
@richardliaw , Dmitri mentioned above that he cannot reproduce.

**Comment by richardliaw** [comment] 2021-09-28 18:42
Sorry, the issue that we care about now is https://github.com/ray-project/ray/issues/18774. It's the underlying issue to this. Let's close this one and consolidate discussion on the other.

**Closed by richardliaw** 2021-09-28 18:42 UTC
Labels: bug, P0
