### ISSUE TITLE
[weekly release]  many_ppo weekly has memory leak causing gRPC deadline exceeds

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#19309] opened 2021-10-12 00:03 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Weekly many_ppo is failing due to grpc DEADLINE_EXCEEDED error.
https://buildkite.com/ray-project/periodic-ci/builds/1207#69e7d975-4806-497c-bd14-0eaeba2fde30
Session log: https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_SkryRYXzKpiLTR6BeGs9is7B?command-history-section=command_history

Is my understanding correct that Ray Core uses gRPC for inter-node communication? Is this failure more of a problem of Ray Core not recovering from inter-node failures or this is something that applications should handle?

This is causing our weekly release test to be red, potentially delaying 1.8. Please help!

 

### Reproduction script

NA

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xwjiang2010** [comment] 2021-10-12 00:03
@matthewdeng @krfricke

**Comment by rkooo567** [comment] 2021-10-12 01:48
This must be the root cause; 
```
(pid=772620) 2021-10-10 17:05:27,811    ERROR worker.py:425 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=772620, ip=172.31.87.239)
(pid=772620) ray._private.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node ip-172-31-87-239 is used (29.42 / 30.58 GB). The top 10 memory consumers are:
(pid=772620) 
(pid=772620) PID        MEM     COMMAND
(pid=772620) 144        6.54GiB /home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/gcs/gcs_server --redis_address=172.
(pid=772620) 1105       6.41GiB python workloads/many_ppo.py
(pid=772620) 160        6.08GiB /home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/dash
(pid=772620) 139        2.74GiB /home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/thirdparty/redis/src/redis-server *
(pid=772620) 134        0.58GiB /home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/thirdparty/redis/src/redis-server *
(pid=772620) 772556     0.52GiB ray::PPO.__init__()
(pid=772620) 772611     0.5GiB  ray::IDLE
(pid=772620) 772614     0.5GiB  ray::IDLE
(pid=772620) 772609     0.5GiB  ray::IDLE
(pid=772620) 772610     0.5GiB  ray::IDLE
```

Related: https://github.com/ray-project/ray/issues/18541#issuecomment-931470575

My guess is the high memory usage causes some components to fail which causes the autoscaler to be crashed (deadline exceed can happen when the component is terminated)

**Comment by rkooo567** [comment] 2021-10-12 01:49
cc @gjoliver I remember you guys mentioned there was the memory leak issue in rllib. Do you think it is the same issue here?

**Comment by gjoliver** [comment] 2021-10-12 01:55
We found a memory leak, which made things a lot better.
but it's inside tf2 eager compute graph, and was leaking a small amount every iteration (many_ppo only runs 1 iter / stack).
the fix is already merged, so if it's still happening, It's probably not related to memory leak from rllib.

**Comment by scv119** [comment] 2021-10-12 01:58
@xwjiang2010 looks a rlib memory leak issue? ^ if that's the feel free to assign to relevant owner.

**Comment by xwjiang2010** [comment] 2021-10-12 02:52
hmmm, as @gjoliver mentioned, I believe the RLlib memory leak issue was already fixed by [this](https://github.com/ray-project/ray/pull/19198) PR. This weekly release test is run at master commit 635010d460ba266b56fc857e56af8272ae08df8c. It's after Sven's fix for memory leak was already landed. 
Maybe some other memory leaks?

**Comment by rkooo567** [comment] 2021-10-12 02:53
Hmm in this case, it is possible the issue is from the ray core. I can take a look next sprint if that’s the case

**Comment by xwjiang2010** [comment] 2021-10-12 03:08
@krfricke Do you know if we have other long running weekly tests at the similar scale maybe to compare the memory consumption with? 
@sven1977 Do you have suggestions as you have recently debugged (and found :) ) a tricky memory leak?

**Comment by rkooo567** [comment] 2021-10-12 03:36
So, for the gcs server, given it holds data that it stores to Redis in memory, the memory size probably makes sense (+1gb compared to Redis). Not sure if Redis memory usage makes sense, and I will do profiling for this.

dashboard memory is a well known issue. 

Many_ppo could be core worker OR application. Since jun solves the rllib issue again, I will try profiling as well, and I think it will be more obvious with the profiling result.

**Comment by xwjiang2010** [comment] 2021-10-12 16:53
@gjoliver I wouldn't be surprised if that's the case. @scv119 Can you grab me when you do it? Would love to learn the flow.

**Comment by scv119** [comment] 2021-10-12 17:21
https://docs.google.com/document/d/1o6n3vDltJnekY4GAfm_pScHovwxC71VlJ19gU0hw5FM/edit#heading=h.wvgzvmfxc4e6

**Comment by scv119** [comment] 2021-10-12 17:23
I also captured a memory profile some point last night
[profile1 (1).pdf](https://github.com/ray-project/ray/files/7332007/profile1.1.pdf)

**Comment by gjoliver** [comment] 2021-10-20 17:47
In my opinion this is a problem with the test, not tune. tracking 1MB of data for each Trial sounds perfectly reasonable to me.
I wonder if we really need tune here. Would running RLlib in a loop for 10K times also serve the purpose?

**Comment by xwjiang2010** [comment] 2021-10-20 17:51
@gjoliver do you know who owns this test? Tune side or RLlib? What is the goal of it?

**Comment by richardliaw** [comment] 2021-10-21 21:21
I actually think that's a good idea; @scv119 ?

**Comment by rkooo567** [comment] 2021-11-01 14:07
After this PR, the Redis memory usage has drastically decreased, and the test seems to pass. https://github.com/ray-project/ray/pull/19699

But it is pretty clear there are GCS server & dashboard memory leak that are not fixed. Should be related to cleaning up actor states from memory, but we need more investigation. But I think this is not a high priority item to fix for now.

**Comment by rkooo567** [comment] 2021-11-01 14:07
^ cc @scv119 please let me know your thoughts!

**Comment by rhamnett** [comment] 2021-11-03 13:20
Hello I am also experiencing this issue (am using W&B logger)

```
2021-11-03 03:04:24,285	WARNING util.py:166 -- The `on_step_end` operation took 9.015 s, which may be a performance bottleneck.
---------------------------------------------------------------------------
GetTimeoutError                           Traceback (most recent call last)
<ipython-input-35-91f5b07df803> in <module>
    175     checkpoint_at_end=True,
    176 #     checkpoint_freq=10,
--> 177     loggers=DEFAULT_LOGGERS + (WandbLogger, ),
    178 #     loggers=DEFAULT_LOGGERS,
    179 #     restore='/root/ray_results/APPO/APPO_TradingEnv_f24a2_00000_0_2021-10-12_12-02-53/checkpoint_005858/checkpoint-5858',

~/anaconda3/envs/tt/lib/python3.7/site-packages/ray/tune/tune.py in run(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, search_alg, scheduler, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, queue_trials, reuse_actors, trial_executor, raise_on_failed_trial, callbacks, max_concurrent_trials, loggers, ray_auto_init, run_errored_only, global_checkpoint_period, with_server, upload_dir, sync_to_cloud, sync_to_driver, sync_on_checkpoint, _remote)
    586     tune_start = time.time()
    587     while not runner.is_finished() and not state[signal.SIGINT]:
--> 588         runner.step()
    589         if has_verbosity(Verbosity.V1_EXPERIMENT):
    590             _report_progress(runner, progress_reporter)

~/anaconda3/envs/tt/lib/python3.7/site-packages/ray/tune/trial_runner.py in step(self)
    644                 self._server.shutdown()
    645         with warn_if_slow("on_step_end"):
--> 646             self._run_and_catch(self.trial_executor.on_step_end)
    647         with warn_if_slow("callbacks.on_step_end"):
    648             self._callbacks.on_step_end(

~/anaconda3/envs/tt/lib/python3.7/site-packages/ray/tune/trial_runner.py in _run_and_catch(self, func)
    394         """
    395         try:
--> 396             func(self.get_trials())
    397         except AttributeError as e:
    398             if str(e) != "'list' object has no attribute 'get_trials'":

~/anaconda3/envs/tt/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py in on_step_end(self, trials)
    986             self.last_pg_recon = time.time()
    987 
--> 988         self._pg_manager.cleanup()
    989 
    990     def force_reconcilation_on_next_step_end(self) -> None:

~/anaconda3/envs/tt/lib/python3.7/site-packages/ray/tune/utils/placement_groups.py in cleanup(self, force)
    294                          self._removal_delay) >= self._pgs_for_removal[pg]:
    295                 self._pgs_for_removal.pop(pg)
--> 296                 remove_placement_group(pg)
    297 
    298     def cleanup_existing_pg(self, block: bool = False):

~/anaconda3/envs/tt/lib/python3.7/site-packages/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
    120             ref = f.remote(*args, **kwargs)
    121             return ray.get(ref)
--> 122         return func(*args, **kwargs)
    123 
    124     return wrapper

~/anaconda3/envs/tt/lib/python3.7/site-packages/ray/util/placement_group.py in remove_placement_group(placement_group)
    251     worker.check_connected()
    252 
--> 253     worker.core_worker.remove_placement_group(placement_group.id)
    254 
    255 

python/ray/_raylet.pyx in ray._raylet.CoreWorker.remove_placement_group()

python/ray/_raylet.pyx in ray._raylet.check_status()

GetTimeoutError: There was timeout in removing the placement group of id bc1f7455a235e61cdec8248e06e1bc61. It is probably because GCS server is dead or there's a high load there.
```

**Comment by rkooo567** [comment] 2021-11-04 07:22
@rhamnett what version of Ray are you using? I believe this issue should be solved in the master

**Comment by rkooo567** [comment] 2021-11-04 07:22
Also, for gcs & dashboard memory leak, it is deferred to next sprint due to other items.

**Closed** 2022-10-24 05:16 UTC
Labels: bug, P2
