### ISSUE TITLE
pip install ray[all] installs Ray 1.5.2 instead of 1.6.0

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#18237] opened 2021-08-31 01:15 UTC
### What is the problem?
`pip install "ray[all]"` always installs Ray 1.5.2, even if Ray 1.6.0 was previously installed.  

One consequence of this is that the release tests here https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/ray-project/ray%24+ray%5Ball%5D&patternType=literal are not actually being run on Ray 1.6.0 but on 1.5.2.
*Ray version and other system information (Python version, TensorFlow version, OS):*
MacOS, Python 3.7

### Reproduction (REQUIRED)
```
pip install "ray[all]"
```
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment] 2021-08-31 01:18
Thanks for reporting. I tried pinning Ray to 1.6, and I got the following error:

```
$ pip install -U 'ray[all]==1.6'

...
ERROR: Could not find a version that satisfies the requirement ray-cpp==1.6.0; extra == "all" (from ray[all]==1.6) (from versions: none)
ERROR: No matching distribution found for ray-cpp==1.6.0; extra == "all" (from ray[all]==1.6)
```

I believe this is an un-updated Ant dependency.

@krfricke or @sven1977 could you shepherd this issue?

**Comment by richardliaw** [comment] 2021-08-31 03:13
About a possible bandaid: @SongGuyang Is it feasible to release a dummy cpp package, and then raises a warning message if actually called?

**Comment by SongGuyang** [comment] 2021-08-31 03:27
@richardliaw Can we overwrite the existing ray wheel？I could remove the ray-cpp dependency from ray wheel.

**Comment by richardliaw** [comment] 2021-08-31 03:35
We can't overwrite but we can rollforward (create a 1.6.1 release).

**Comment by SongGuyang** [comment] 2021-08-31 03:41
OK, let me make a hot fix PR and you copy that to 1.6.1？

**Comment by raulchen** [comment] 2021-08-31 03:45
@SongGuyang @richardliaw Shall we just release the ray-cpp 1.6 wheel?  Then `pip install ray[all]` can succeed.
Although CPP release is not officially announced, I think releasing the wheel is okay.

**Comment by SongGuyang** [comment] 2021-08-31 03:53
@raulchen But we already announced that indirectly in documents.

**Comment by richardliaw** [comment] 2021-08-31 03:58
@SongGuyang what's the problem with just releasing a ray-cpp==1.6 wheel? It's ok to release earlier right?

**Comment by SongGuyang** [comment] 2021-08-31 04:26
@richardliaw We found that the ray-cpp wheel built from CI doesn't work in any containers, even failed in ray [docker source images](https://docs.ray.io/en/master/installation.html#docker-source-images). But if we build the wheel manually in our develop machine, it works. We don't know the reason.

**Comment by SongGuyang** [comment] 2021-08-31 04:28
@richardliaw Can we release the ray-cpp==1.6 wheel built from my developing machine manually?

**Comment by richardliaw** [comment] 2021-08-31 07:39
I see; that is unfortunate. In the spirit of risk mitigation, I think it is more preferable to push a 1.6.1 to address this and then fix the build for 1.7.0.

**Comment by krfricke** [comment] 2021-08-31 08:05
As an alternative, can we publish an empty dummy cpp wheel that does not contain any code (or just throws an exception on import)? That way we don't ship wheels that haven't been built in a reproducible setup but still enable `ray[all]==1.6.0` to be installed.

**Comment by SongGuyang** [comment] 2021-08-31 08:29
@krfricke Empty dummy cpp wheel is ok. Can you publish?

**Comment by SongGuyang** [comment] 2021-08-31 08:39
@richardliaw @krfricke https://github.com/ray-project/ray/pull/18251/files We can also copy this PR to 1.6.1 after merged.

**Comment by krfricke** [comment] 2021-08-31 09:07
I'll prepare an empty wheel and check back with the rest of the team. We would be able to publish it by EOD then.

**Comment by SongGuyang** [comment] 2021-08-31 09:14
@krfricke OK, thanks.

**Comment by krfricke** [comment] 2021-08-31 17:00
Empty wheels have been built:

```
2021-08-31 16:54:20       5667 ray_cpp-1.6.0+dbg-cp36-cp36m-manylinux2014_x86_64.whl
2021-08-31 16:54:10       5669 ray_cpp-1.6.0+dbg-cp37-cp37m-manylinux2014_x86_64.whl
2021-08-31 16:54:16       5666 ray_cpp-1.6.0+dbg-cp38-cp38-manylinux2014_x86_64.whl
2021-08-31 16:54:04       5667 ray_cpp-1.6.0+dbg-cp39-cp39-manylinux2014_x86_64.whl
2021-08-31 17:29:54       5621 ray_cpp-1.6.0-cp36-cp36m-macosx_10_6_intel.whl
2021-08-31 16:50:14       5617 ray_cpp-1.6.0-cp36-cp36m-manylinux2014_x86_64.whl
2021-08-31 16:42:03       5615 ray_cpp-1.6.0-cp36-cp36m-win_amd64.whl
2021-08-31 17:29:53       5622 ray_cpp-1.6.0-cp37-cp37m-macosx_10_6_intel.whl
2021-08-31 16:50:14       5617 ray_cpp-1.6.0-cp37-cp37m-manylinux2014_x86_64.whl
2021-08-31 16:42:04       5615 ray_cpp-1.6.0-cp37-cp37m-win_amd64.whl
2021-08-31 17:29:54       5621 ray_cpp-1.6.0-cp38-cp38-macosx_10_9_x86_64.whl
2021-08-31 16:50:16       5614 ray_cpp-1.6.0-cp38-cp38-manylinux2014_x86_64.whl
2021-08-31 16:42:04       5612 ray_cpp-1.6.0-cp38-cp38-win_amd64.whl
2021-08-31 17:29:53       5621 ray_cpp-1.6.0-cp39-cp39-macosx_10_9_x86_64.whl
2021-08-31 16:50:14       5615 ray_cpp-1.6.0-cp39-cp39-manylinux2014_x86_64.whl
2021-08-31 16:42:05       5611 ray_cpp-1.6.0-cp39-cp39-win_amd64.whl
```

**Comment by ericl** [comment] 2021-08-31 18:01
Empty cpp wheels LGTM

**Comment by krfricke** [comment] 2021-08-31 18:40
Released to pypi and test pypi - confirmed install using `pip install ray[all]==1.6.0` works for me locally on MacOS

**Comment by krfricke** [comment] 2021-08-31 18:41
Closing this for now, please re-open if issues persist

**Closed by krfricke** 2021-08-31 18:41 UTC
Labels: bug, release-blocker, P0

**Comment by SongGuyang** [comment] 2021-09-01 02:29
Great!

**Comment by pcmoritz** [comment] 2021-09-18 17:20
This still seems to be a problem in some cases: https://github.com/ray-project/ray/issues/18461
