### ISSUE TITLE
Seemingly poor scheduling for batch of GPU jobs

### ISSUE THREAD

**Issue by joschu** [ray-project/ray#1180] opened 2017-11-02 05:07 UTC
<img width="1026" alt="screen shot 2017-11-01 at 9 51 40 pm" src="https://user-images.githubusercontent.com/144178/32310718-9d6d46f0-bf51-11e7-8fdc-5da6f123188f.png">

I'm running a batch algorithm, where I have 144 tasks per batch, each requiring 1 GPU, and I have 160 GPUs in the ray cluster (40 machines x 4 gpus each). However, Ray seems to make odd scheduling decisions that sometimes require one GPU to do two jobs in a given batch.  See figure. Note that in the first batch, each GPU does one job, but in the second batch, some GPUs are left idle and others do two jobs.

I tried constructing a minimum example but was unable to reproduce at a smaller scale.

Any idea what's happening or how to fix it?

**Comment by atumanov** [comment] 2017-11-02 06:46
it would really help if you could share a script to reproduce. How are you submitting batches of GPU tasks, from the driver in a scatter-gather pattern? Any nesting of GPU tasks called from within GPU tasks? If scatter-gather pattern, how do you gather each batch, by doing a `ray.get` on all the tasks in a batch or `ray.wait`? What might be happening is the global scheduler gets a delayed heartbeat from slave nodes (which carry load/capacity information) may be operating on slightly out of date view of available resources. For instance, at the time of scheduling the second batch tasks, it might think that slave node 17 only has 3/4 GPUs freed up, while the 4th GPU is still busy.

**Comment by joschu** [comment] 2017-11-02 07:57
I'll work on a repro script -- the current one is tied into a large codebase and the specific infra I'm using.

I'm using the simplest kind of scatter-gather, essentially

```python
@ray.remote(num_gpus=1, num_cpus=2)
def calc(x):
    ... do some calculation

def main():
    while True:
        xs = some list of tasks
        delayedvals = [calc.remote(x) for x in xs]
        vals = [ray.get(dv) for dv in delayedvals]
```

**Comment by joschu** [comment] 2017-11-02 07:58
Based on your hypothesis of heartbeats, I tried putting `time.sleep(2)` after each loop iteration, but that didn't fix the problem.

**Comment by robertnishihara** [comment] 2017-11-02 08:00
I wonder, is the machine that is receiving extra GPU tasks the one that tasks are being submitted from?

We have some plans for improving the scheduling load balancing, but I'd like to think of a shorter term fix..

**Comment by joschu** [comment] 2017-11-02 08:02
Interestingly that one does seem to be getting more than its fair share of jobs, but it's not the only one getting too many jobs.

**Comment by joschu** [comment] 2017-11-02 08:03
Node ending in 107 is the head node and the node where the driver script is running.
<img width="433" alt="screen shot 2017-11-02 at 1 02 30 am" src="https://user-images.githubusercontent.com/144178/32315507-96af9922-bf69-11e7-877e-aa9efc52ceb4.png">

**Comment by joschu** [comment] 2017-11-02 08:16
Also, not sure if this is relevant, but the number of workers (according to `ray.global_state.workers()`) grows at every iteration and is much larger than the number of GPUs. After a few dozen iterations, each node has 20-25 workers.

**Comment by robertnishihara** [comment] 2017-11-02 08:24
1. How many CPUs does each machine have?

2. What `--num-cpus`, `--num-gpus`, and `--num-workers` flags are you passing in when you start Ray?

3. How many different remote functions are there? Is there only a single type of task and it requires 1 GPU and 2 CPUs or are there multiple types of tasks?

4. Is it possible to reproduce without using GPUs?

5. One comment which is completely irrelevant is that you can do the following (it can be more efficient)

    ```python
    vals = ray.get(delayedvals)
    ```

    instead of

    ```python
    vals = [ray.get(dv) for dv in delayedvals]
    ```

**Comment by joschu** [comment] 2017-11-02 08:44
1. 18 cpus and 4 gpus
2. --num-cpus=18, --num-gpus=4, --num-workers=4
3. just one task
4. looks like not. I switched the decorator's requirements to num_gpus=4, and I see the same issue
5. cool, thanks for the tip

**Comment by joschu** [comment] 2017-11-03 00:24
OK @atumanov @robertnishihara I've got a minimal script that reproduces this issue.
https://pastebin.com/qXnNMhPb

It creates a Ray cluster with `len(NAMES)` each with `CPUS_PER` cpus. Then it does a bunch of batches of work where each batch has `len(NAMES) * CPUS_PER` tasks.

When I run it with `len(NAMES)=1` or 2, it takes 1 second per batch as it should (after the first batch, which is sometimes slower). But when I run with `len(NAMES)=4`, it takes 2 seconds per batch.

**Comment by atumanov** [comment] 2017-11-03 00:27
@joschu , thanks. I have a presentation tomorrow (Fri) and will prioritize this investigation as soon as I'm done with the talk.

**Comment by robertnishihara** [comment] 2017-11-06 18:30
So, the issue is the following.

The global scheduler attempts to load balance tasks across all of the machines, and it has two sources of information for tracking the load on each machine.
1. It receives periodic heartbeats (every 100ms) from each local scheduler saying how many tasks are queued or executing on that machine.
2. For each local scheduler, it keeps track of how many tasks it assigned to that local scheduler since it received the last heartbeat from that local scheduler.

So suppose that the global scheduler assigns a task to one machine. If the local scheduler simultaneously sends a heartbeat with its load information to the global scheduler, the global scheduler will forget about the task it assigned once the heartbeat arrives.

So in practice, if heartbeats are received while the global scheduler is handing out tasks, the global schedulers load estimates can be inaccurate which can lead to poor load balancing.

There's a separate issue, which is that tasks assigned locally (without going through the global scheduler) do not count toward the global scheduler's bookkeeping until the next heartbeat, so in the meantime the global scheduler can have a slightly stale world view.

I was going to suggest solving this by doing the following:
- Don't let tasks be scheduled locally (e.g., on the node that you run the driver from, start that node with `--num-cpus=0`).
- Pause long enough during scheduling to allow the global scheduler to receive up-to-date load information from the local schedulers.

However, that doesn't quite work because the information sent by the heartbeats and used by the global scheduler is mostly about the number of tasks queued on the node and not the number of available workers.

We'll need to give this more thought, but can probably come up with a short-term fix.

Note that even with poor scheduling, `ray.wait` can be used to drop straggler tasks.

**Comment by joschu** [comment] 2017-11-06 21:15
Maybe there could be a scheduler mode where the global scheduler waits until the local scheduler has capacity for the job before sending it to that local scheduler?

**Comment by atumanov** [comment] 2017-11-06 21:25
the quick fix is simple: if perfect and immediate load balancing is desired (essentially gang scheduling), this can be done by forcing the local scheduler to forward all submitted tasks to the global scheduler. That way the global scheduler's resource accounting w.r.t. available capacity is always up to date. A mildly relaxed version of this fix that's worth giving serious consideration is to forward all GPU tasks (and actor placement requests) to the global scheduler by default. This should fix the load balancing issue reported here.

**Comment by atumanov** [comment] 2017-11-06 21:29
I could prep a "do not merge" PR implementing the latter fix if it's helpful.

**Comment by atumanov** [comment] 2017-11-06 21:36
for context, the system was designed for irregular, non-BSP control and data-flow computation patterns with light-weight tasks. Given these assumptions, load balancing is achieved asymptotically and with high probability. It's not guaranteed to be instantaneous. Heavier-weight GPU tasks and gang scheduling semantics are a better fit for more centralized scheduler for two reasons: (1) scheduling time is a smaller percentage of the task's duration, so the latency of centralized scheduling is easier tolerated, (2) centralized placement decisions always work with fresh cluster state, guaranteeing precise bin-packing gang scheduling expects.

**Comment by robertnishihara** [comment] 2017-11-06 23:24
@atumanov that fix actually doesn't quite work (I tried it out). The reason is is described in https://github.com/ray-project/ray/issues/1180#issuecomment-342241212. Basically, the heartbeats from the local scheduler and the global scheduler's own bookkeeping can get out of sync.

**Comment by robertnishihara** [comment] 2017-11-07 03:58
@joschu The solution that @atumanov is working on right now involves allowing local schedulers to push work back to the global scheduler if they don't have capacity at the moment (at which point the global scheduler can try a different local scheduler).

As you mention, it would be possible to have an alternative model in which local schedulers pull work from global schedulers.

**Comment by unixpickle** [comment] 2017-12-09 00:08
Running into the same problem. What's the status on this?

**Comment by robertnishihara** [comment] 2017-12-09 09:02
@unixpickle thanks, @atumanov is working on substantial scheduling improvements and we should have fixed this in a couple weeks. To clarify, are you running into this problem with remote functions or with actors or both?

**Comment by unixpickle** [comment] 2017-12-12 23:50
@robertnishihara I'm using remote functions.

**Comment by robertnishihara** [comment] 2017-12-13 01:09
Ok, sounds good.

**Comment by robertnishihara** [comment] 2018-01-04 23:21
Ok, you should be able to install it with

```
pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/extras/centralized-scheduling/ray-0.3.0-cp36-cp36m-linux_x86_64.whl
```

Let me know if you run into any issues or if it does not behave as expected.

**Comment by robertnishihara** [comment] 2018-05-27 01:00
Should have been fixed with spillback scheduling a while ago.

**Closed by robertnishihara** 2018-05-27 01:00 UTC
