### ISSUE TITLE
[Ray CI] Error: Observed wheel commit () is not expected commit (63783...). Aborting

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#32156] opened 2023-02-01 02:17 UTC
Some PRs suffer from this flaky failure.

**Comment by cadedaniel** [comment] 2023-02-01 02:18
cc @rkooo567 to link his most recent failure

**Comment by krfricke** [comment] 2023-02-01 05:05
I've seen this failure in different jobs. It's flaky, a retry usually works. It comes up in any job that calls `LINUX_WHEELS=1 ./ci/ci.sh build` as that will build wheels and check the commit hash. 

I _think_ it came up more often when we upgraded our manylinux build container here: https://github.com/ray-project/ray/commit/0c8b59d2d90df0cfe0f17d9feb7ef9b3e5fe53f2#diff-a2fce6a33e7a666e89ec201eb5eb823cf5c5c411ace62008781a9adc90cc0adaR461

So far I couldn't reproduce it on repro instances, likely because it doesn't come up very often...

**Comment by cadedaniel** [comment] 2023-02-01 16:46
Here's one: https://buildkite.com/ray-project/oss-ci-build-branch/builds/2137#01860ce6-af39-40f6-8f67-42c73455483f

**Comment by can-anyscale** [comment] 2023-03-24 00:22
I used to see this once every few builds in [OSS CI build: branch], but not any more. Closing this, but if it happens again feel free to re-open and assign to me. Thanks

**Closed by can-anyscale** 2023-03-24 00:22 UTC
Labels: P1, testing
