### ISSUE TITLE
[Core] [Multiprocessing] Pool.imap_unordered fails with iterator

### ISSUE THREAD

**Issue by simontindemans** [ray-project/ray#24081] opened 2022-04-21 17:39 UTC
### What happened + What you expected to happen

When using `ray.util.multiprocessing.Pool.imap_unordered(func, iterable)` with a self-defined iterator, I am confronted with the error `TypeError: Could not serialize the argument [((<generator object new_range at 0x7fa07f71e2e0>,), {})] for a task or actor ray.util.multiprocessing.pool.PoolActor.run_batch.`

This is unexpected, as the iterator can be queried within the dispatching process, so serialization should not be necessary. When I replace the iterator with a simple `range(n)`, it does work (see code below). 

The issue appears to be related to the initialization and implementation of the `IMapIterator` class, below:
```
class IMapIterator:
    """Base class for OrderedIMapIterator and UnorderedIMapIterator."""

    def __init__(self, pool, func, iterable, chunksize=None):
        self._pool = pool
        self._func = func
        self._next_chunk_index = 0
        # List of bools indicating if the given chunk is ready or not for all
        # submitted chunks. Ordering mirrors that in the in the ResultThread.
        self._submitted_chunks = []
        self._ready_objects = collections.deque()
        if not hasattr(iterable, "__len__"):
            iterable = [iterable]
        self._iterator = iter(iterable)
        self._chunksize = chunksize or pool._calculate_chunksize(iterable)
        self._total_chunks = div_round_up(len(iterable), chunksize)
        self._result_thread = ResultThread([], total_object_refs=self._total_chunks)
        self._result_thread.start()

        for _ in range(len(self._pool._actor_pool)):
            self._submit_next_chunk()

    def _submit_next_chunk(self):
        # The full iterable has been submitted, so no-op.
        if len(self._submitted_chunks) >= self._total_chunks:
            return

        actor_index = len(self._submitted_chunks) % len(self._pool._actor_pool)
        new_chunk_id = self._pool._submit_chunk(
            self._func, self._iterator, self._chunksize, actor_index
        )
        self._submitted_chunks.append(False)
        self._result_thread.add_object_ref(new_chunk_id)
```

The following lines wrap the supplied iterator *within another iterator*. 
```
        if not hasattr(iterable, "__len__"):
            iterable = [iterable]
        self._iterator = iter(iterable)
```
Swapping these two statements is sufficient to avoid the error message. However, it then exposes another problem: the code assumes that the iterator has a known length, which is now assumed to be 1: only a single task is executed. Some more refactoring seems required to cleanly empty the iterator. Perhaps `_submit_next_chunk` can extract the desired number of iterates and wrap them in an iterator for downstream use, and flag an empty iterator in the process.

### Versions / Dependencies

Ray 2.0.0dev0 (also present in 1.12.1)
Python 3.9.7

### Reproduction script

*Edit: I was confused; `range` is not an iterator. Nevertheless, I'd think that an iterator should work.*
*Edit 2: even simpler example with iter(range(.))*

```
import ray.util.multiprocessing as raymp

# test function
def func(input):
    print('run func [{}]'.format(input))
    return input

with raymp.Pool() as pool:
    
    # this works
    print('use range (iterable)')
    for x in pool.imap_unordered(func, range(5)):
        print('Finished [{}]'.format(x))

    # this fails with a TypeError (could not serialize)
    print('use an iterator')
    for x in pool.imap_unordered(func, iter(range(5))):
        print('Finished [{}]'.format(x))
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by edoakes** [comment] 2022-04-21 19:30
@simontindemans thanks for the detailed issue & reproduction! Any chance you'd be willing to contribute a fix for this? I'd be happy to guide you through it & review. Looks like you already have a good understanding of the code.

**Comment by simontindemans** [comment] 2022-04-21 19:53
@edoakes Sure, I'm already working on one (as I need it for a project).

**Comment by simontindemans** [comment] 2022-04-21 20:08
@edoakes, here is a first attempt: https://github.com/simontindemans/ray/commit/110ce5e483e89b7458d755382bad973401c04acf 

It fixes the problem above, but there are two issues:
* Serious is that I had to assume a somewhat arbitrary buffer size in line 354. Currently, I have used 10x the number of actors. If I set it too small, the code locks. 
* Ugly-but-functional is a conversion from iterator to list to iterator in line 370.

Sorry, I'm not very familiar with collaborative work on Github, so not sure how to properly link to lines, etc.

**Comment by simontindemans** [comment] 2022-04-22 06:52
I spoke too soon: I have encountered a few issues with my proposed fix. I'll revisit and post back when I have something that works and is solid.

**Comment by edoakes** [comment] 2022-04-22 16:14
Sounds good @simontindemans :)

Btw, the best way for me to review is for you to make a pull request to the ray repository based on your branch. You should be able to go to the ray-project/ray repo page and click "make a pull request," then select your branch. Assign me there / ping me.

**Comment by simontindemans** [comment] 2022-04-22 19:00
@edoakes I have made a working version that addresses all issues, as far as I can tell. I made a pull request, but am unsure how to assign you. Also, some of the checks have not been done.

**Closed** 2022-09-01 23:40 UTC
Labels: bug, triage, core
