### ISSUE TITLE
[rllib] placeholders added in postprocess_fn are missing when learn_on_batch is called

### ISSUE THREAD

**Issue by bentzinir** [ray-project/ray#9305] opened 2020-07-05 13:49 UTC
### What is the problem?
I'm working with SAC and want to add a new field to `train_batch` in the same way as it is done in the [PPO advantage example](https://docs.ray.io/en/latest/rllib-concepts.html#:~:text=ADVANTAGES%5D%20.,shapes%20of%20the%20postprocessed%20batch.). 
I've modified the `postprocess_trajectory` function in the [sac tf policy](https://github.com/ray-project/ray/blob/master/rllib/agents/sac/sac_tf_policy.py) module by adding the following line:
`sample_batch['new_placeholder'] = np.ones(shape=sample_batch[SampleBatch.REWARDS].shape, dtype=np.int32)`

which I want to call inside the 'sac_actor_critic_loss' function: 
`new_placeholder = train_batch['new_placeholder']`

The run fails when the `learn_on_batch` function is called as the `new_placeholder` do not appear in the batch. Is it possible that the function was called before the postprocess function was applied to the batch?

Traceback:
`Traceback (most recent call last):
  File "/home/nir/work/git/ray/python/ray/rllib/examples/sac_multiagent_example.py", line 70, in <module>
    results = trainer.train()  # distributed training step
  File "/home/nir/work/git/ray/python/ray/rllib/agents/trainer.py", line 500, in train
    raise e
  File "/home/nir/work/git/ray/python/ray/rllib/agents/trainer.py", line 486, in train
    result = Trainable.train(self)
  File "/home/nir/work/git/ray/python/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "/home/nir/work/git/ray/python/ray/rllib/agents/trainer_template.py", line 132, in _train
    return self._train_exec_impl()
  File "/home/nir/work/git/ray/python/ray/rllib/agents/trainer_template.py", line 170, in _train_exec_impl
    res = next(self.train_exec_impl)
  File "/home/nir/work/git/ray/python/ray/util/iter.py", line 731, in __next__
    return next(self.built_iterator)
  File "/home/nir/work/git/ray/python/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "/home/nir/work/git/ray/python/ray/util/iter.py", line 814, in apply_filter
    for item in it:
  File "/home/nir/work/git/ray/python/ray/util/iter.py", line 814, in apply_filter
    for item in it:
  File "/home/nir/work/git/ray/python/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "/home/nir/work/git/ray/python/ray/util/iter.py", line 814, in apply_filter
    for item in it:
  File "/home/nir/work/git/ray/python/ray/util/iter.py", line 1047, in build_union
    item = next(it)
  File "/home/nir/work/git/ray/python/ray/util/iter.py", line 731, in __next__
    return next(self.built_iterator)
  File "/home/nir/work/git/ray/python/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "/home/nir/work/git/ray/python/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "/home/nir/work/git/ray/python/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "/home/nir/work/git/ray/python/ray/util/iter.py", line 752, in apply_foreach
    result = fn(item)
  File "/home/nir/work/git/ray/python/ray/rllib/execution/train_ops.py", line 69, in __call__
    info = self.workers.local_worker().learn_on_batch(batch)
  File "/home/nir/work/git/ray/python/ray/rllib/evaluation/rollout_worker.py", line 719, in learn_on_batch
    builder, batch)
  File "/home/nir/work/git/ray/python/ray/rllib/policy/tf_policy.py", line 650, in _build_learn_on_batch
    self._get_loss_inputs_dict(postprocessed_batch, shuffle=False))
  File "/home/nir/work/git/ray/python/ray/rllib/policy/tf_policy.py", line 692, in _get_loss_inputs_dict
    feed_dict[ph] = batch[k]
  File "/home/nir/work/git/ray/python/ray/rllib/policy/sample_batch.py", line 212, in __getitem__
    return self.data[key]
KeyError: 'new_placeholder'`

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python version = 3.6.9
TF version = 1.15.3
ray version = 0.9.0.dev0
OS = ubuntu 18
 
### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Minimal working script:

[minimal_script.txt](https://github.com/ray-project/ray/files/4874994/minimal_script.txt)

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by ericl** [comment] 2020-07-06 03:45
```
diff --git a/rllib/agents/sac/sac_tf_policy.py b/rllib/agents/sac/sac_tf_policy.py
index 49076ac48..b5ddc32b1 100644
--- a/rllib/agents/sac/sac_tf_policy.py
+++ b/rllib/agents/sac/sac_tf_policy.py
@@ -84,7 +84,9 @@ def postprocess_trajectory(policy,
                            sample_batch,
                            other_agent_batches=None,
                            episode=None):
-    return postprocess_nstep_and_prio(policy, sample_batch)
+    sample_batch = postprocess_nstep_and_prio(policy, sample_batch)
+    sample_batch["hello"] = sample_batch["rewards"]
+    return sample_batch
 
 
 def get_dist_class(config, action_space):
@@ -118,6 +120,7 @@ def get_distribution_inputs_and_class(policy,
 def sac_actor_critic_loss(policy, model, _, train_batch):
     # Should be True only for debugging purposes (e.g. test cases)!
     deterministic = policy.config["_deterministic_loss"]
+    assert "hello" in train_batch
 
     model_out_t, _ = model({
         "obs": train_batch[SampleBatch.CUR_OBS],
diff --git a/rllib/policy/tf_policy.py b/rllib/policy/tf_policy.py
index 6b4243190..6ab7acc9e 100644
--- a/rllib/policy/tf_policy.py
+++ b/rllib/policy/tf_policy.py
@@ -356,6 +356,7 @@ class TFPolicy(Policy):
 
     @override(Policy)
     def learn_on_batch(self, postprocessed_batch):
+        assert "hello" in postprocessed_batch
         assert self.loss_initialized()
         builder = TFRunBuilder(self._sess, "learn_on_batch")
         fetches = self._build_learn_on_batch(builder, postprocessed_batch)
```

```
./train.py --run=SAC --env=MountainCarContinuous-v0
```

The above works for me, is it different from your reproduction case?

**Comment by bentzinir** [comment] 2020-07-06 08:39
In my case, the assert statement passes when the loss function is first entered with the fake batch during loss initialization, but will fail when actual evaluation happens. I believe the problem is that `sac` is off policy as oppose to `ppo`. Therefore, its execution plan creates the `train_batch` by loading it from the replay buffer. However, the replay buffer saves a fixed set of placeholders (obs, actions, etc.) and not custom ones. The loaded batch goes through `TrainOneStep` which then fails. I've noticed that the execution plan goes through a `post_fn` before entering `TrainOneStep`. However, since I'm actually interested in creating a placeholder that depends on the transition `info` filed, I am not able to restore it there without explicitly saving it in the buffer.

**Comment by ericl** [comment] 2020-07-06 16:40
Hmm I see, I think this should be fixed as of latest master. We recently merged some enhancements to replay that would preserve all the new fields added by postprocessing. Before, it only kept the basic sars' fields in the replay batch.

Could you try again with newest ray? Otherwise, let me know if you can reproduce with the commands I had above.

**Comment by bentzinir** [comment] 2020-07-06 17:53
Sure thing Eric, I'll keep you posted.
Thanks!

**Comment by bentzinir** [comment] 2020-07-30 07:50
The issue is solved with the latest version. I'm closing, Thanks.

**Closed** 2020-07-30 07:49 UTC
Labels: question, rllib
