### ISSUE TITLE
[autoscaler] _patched_makeRecord needs to make use of logging module's global _logRecordFactory

### ISSUE THREAD

**Issue by mkoh-asapp** [ray-project/ray#13795] opened 2021-01-29 17:35 UTC
### What is the problem?

Ray is monkey patching logging.Logger.makeRecord, but it does not use the logging module's `_logRecordFactory` . This means that it is not possible to use `logging.setLogRecordFactory` to customize log creation if one imports the ray autoscaler code.

*Ray version and other system information (Python version, TensorFlow version, OS):*
1.x

### Reproduction (REQUIRED)

1) Try to use logging.setLogRecordFactory with some custom function
2) Import ray.autoscaler.cli_logger somewhere (this might be automatically imported by something else in autoscaler)
3) observe that your custom logRecordFactory is not called.

### Proposed fix

I only tested this very superficially , but I think this should work.

At https://github.com/ray-project/ray/blob/e59fe65d3dee1803de2da5ab200059e992de7f9b/python/ray/autoscaler/_private/cli_logger.py#L119

```python
    rv = logging.LogRecord(name, level, fn, lno, msg, args, exc_info, func,
                           sinfo)
---
    rv = logging._logRecordFactory(name, level, fn, lno, msg, args, exc_info, func,
                           sinfo)
```

**Comment by richardliaw** [comment] 2021-01-29 19:16
Alternatively, we should just avoid doing any monkey patching of the underlying logger.

**Comment by qsz13** [comment] 2023-01-24 00:05
@richardliaw Is the proposed fix acceptable? We are using `setLogRecordFactory` following the example in [python doc](https://docs.python.org/3/library/logging.html#logging.LogRecord), and it's not working because of this monkey patch.

**Comment by DmitriGekhtman** [comment] 2023-02-09 19:20
Hi! Could we fix this? This has caused some toe stubs Cruise.
Hacking the logging module like this can cause issues for logging in any Python process that happens to indirectly trigger an import of the cli logger.

**Comment by richardliaw** [comment] 2023-02-09 19:52
OK, thanks for the signal. I think we mainly need to make sure this configuring only happens when logging happens as part of the ray autoscaling/monitoring process.

@wuisawesome @gvspraveen could you track this work?

**Comment by wuisawesome** [comment] 2023-02-09 21:17
@DmitriGekhtman @qsz13 and anyone else, can you say more about what you're trying to do/what goes wrong. I agree we should fix this, just trying to get a sense of prioritization.

**Comment by DmitriGekhtman** [comment] 2023-02-09 23:01
> what you're trying to do

More or less what the OP mentioned -- customize log records.
We use [MDC](https://pypi.org/project/mdc/) for that purpose, but MDC appears to be incompatible with Ray for this reason.

I get the sense it isn't super urgent, but @qsz13 has more context than me on priority and could probably provide reproduction details if necessary.

It would definitely be great if this were fixed by Ray 2.4!
[the next Ray release that is not currently in progress]

**Comment by pardisb** [comment] 2023-02-11 22:45
I can add a bit of context on what we're doing with [MDC](https://pypi.org/project/mdc/). But first I need to explain about a different python library.

We utilize [pythonjsonlogger](https://pypi.org/project/python-json-logger/) to format our logging output as Json. This is helpful to us because the log viewing application we use can parse json log records and gives users the ability to customize which fields they want to focus on / filter log records by / etc. 

Basically we configure python's logging library like so:
```
logging.config.dictConfig(
        {
            "version": 1,
            "formatters": {
                "json": {
                    "format": keep_all_attributes_format,
                    "class": "pythonjsonlogger.jsonlogger.JsonFormatter",
                },
            },
            "handlers": {
                "structured_stderr": {
                    "level": "INFO",
                    "formatter": "json",
                    "class": "logging.StreamHandler",
                    "stream": logstream,
                },
            },
            "loggers": {
                "": {
                    "handlers": ["structured_stderr"],
                    "level": "INFO",
                }
            },
        }
    )
```

This creates log records that look like: 
```
{
    "asctime":"2023-02-11 13:52:57,510",
    "filename":"mymodule.py",
    "funcName":"starting_point_of_my_code",
    "levelname":"INFO",
    "levelno":20,
    "lineno":567,
    "message":"Some message!",
    "module":"mymodule",
    "name":"package.mymodule",
    "stream":"stderr",
}
```

Then you can use the following snippet to insert the key value pair {"foo": "bar"} into the json output above.
```
with MDC(foo="bar"):
    logger.info("Some message!")
```

MDC creates a thread local object to store {"foo": "bar"} so a much more interesting example is that all code that executes on the same thread and inside the MDC context gets the same key value inserted into any log records emitted from them even if they are not explicitly taking the time to add some substring like "For foo=bar" to their log messages.  

Currently, what happens is that once execution gets to Ray libraries, the log records stop getting customized and {"foo": "bar"} stops getting attached to logs emitted during the execution of the Ray code even when it is wrapped in the MDC context. So we fail to do things like "embed the job_id into every log record emitted from this job".

Let me know if this explains the impact well. 😅 it's kinda long but what's broken is the integration point of 3 libraries. MDC and pythonjsonlogger work well together. It would be nice if Ray didn't break this.

**Comment by DmitriGekhtman** [comment] 2023-02-13 02:34
Adding to above explanation, here's are sample repro scripts
(`pip install mdc` to run these)

This works as expected.
```python
import mdc
import logging
from pythonjsonlogger.jsonlogger import JsonFormatter
handler = logging.StreamHandler()
handler.setFormatter(JsonFormatter())
logging.basicConfig(
    handlers=[handler]
)
with mdc.MDC(something="bar"):
    logging.warning("Everything is here.")
```
The output is
```
{"message": "Everything is here.", "something": "bar"}
```

However, importing Ray prevents MDC from doing its work.
```python
import ray
import mdc
import logging
from pythonjsonlogger.jsonlogger import JsonFormatter
handler = logging.StreamHandler()
handler.setFormatter(JsonFormatter())
logging.basicConfig(
    handlers=[handler]
)
with mdc.MDC(something="bar"):
    logging.warning("Something is missing.")
```
The output is
```
{"message": "Something is missing."}
```,
which is missing `something`.

To fix this, the goal would be to limit the blast radius of the formatter manipulation to just methods of the CLI Logger.

**Comment by DmitriGekhtman** [comment] 2023-02-19 06:54
Just fully comprehended the context and the (very simple) fix proposed by the OP.
PR for that fix: https://github.com/ray-project/ray/pull/32678
Someone should still remove the patch.

**Closed** 2023-02-23 18:55 UTC
Labels: bug, P1, autoscaler, infra
