### ISSUE TITLE
[AIR] Bug for convert data to torch

### ISSUE THREAD

**Issue by guodashun** [ray-project/ray#26248] opened 2022-07-01 03:14 UTC
### What happened + What you expected to happen

I have some pandas data and I want to convert it to torch dataset. But I got the the error info

>  feature_tensor = torch.cat(feature_tensors, dim=1)
> IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

I review the code [torch_utils.py](https://github.com/ray-project/ray/blob/master/python/ray/air/_internal/torch_utils.py) and I think  there is a bug in line 88,

https://github.com/ray-project/ray/blob/ab44133fba1fe2c3a05890a6d2a8d7b37b0acd43/python/ray/air/_internal/torch_utils.py#L88

The param **dim=1** may be not suitable for every situation.
when set '**unsqueeze_feature_tensors=False**', the bug rise up.

### Versions / Dependencies

3.0dev

### Reproduction script

Pandas data like:

> | feature_0 | feature_1 | label |
> | --------- | --------- | ----- |
> | 0.16      | 1.25      | 0     |
> | 0.24      | 3.42      | 1     |
> | ...       | ...       | ...   |
and I convert it to torch dataset
```
ray_data = ray.data.from_modin(data)
torch_ds = ray_data.to_torch(
    label_column='label', 
    batch_size=16,
    unsqueeze_feature_tensors=False,
    unsqueeze_label_tensor=False,
)
item = next(torch_ds)
```
And I got the error info.
But when I set **unsqueeze_feature_tensors=True**, this code can pass the test.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by tupui** [comment] 2022-07-05 10:47
Hi @guodashun, thank you for reporting. Here is a complete reproducer:

```python
import ray.data
import pandas as pd

df = pd.DataFrame([[0.16, 1.25, 0], [0.24, 3.42, 1]], columns=["feature_0", "feature_1", "label"])
ray_data = ray.data.from_pandas(df)
torch_ds = ray_data.to_torch(
    label_column='label', 
    batch_size=16,
    unsqueeze_feature_tensors=False,
    unsqueeze_label_tensor=False,
)
list(torch_ds)
```

I think this is intended as you have a 2D array here. What did you expect as a result? Did you find an inconsistency with respect to the doc https://docs.ray.io/en/latest/data/dataset-tensor-support.html#converting-to-a-torch-tensorflow-dataset?

**Comment by guodashun** [comment] 2022-07-07 09:10
Thanks for your reply!
So based on my understanding, the **unsqueeze_feature_tensors** just should be set **False** when in the situation that feature columns are incompatible as the doc mentions, and in the other normal situations the **unsqueeze_feature_tensors** should be **True** as the default.
Is it?

**Comment by tupui** [comment] 2022-07-07 09:31
Yes, this option would remove redundant information which is not present here. I will close the issue for now. Thanks again.

**Closed by tupui** 2022-07-07 09:31 UTC
Labels: bug, air
