### ISSUE TITLE
[Ray Train] Provide a built-in Keras Callback

### ISSUE THREAD

**Issue by JiahaoYao** [ray-project/ray#25325] opened 2022-05-31 20:38 UTC
### Description

**Current State**: The current way of using the callback in the ray train module is 1) define the call back function 2) adding to the callback of the trainer. 

**Expectation**: provide some utils methods in the ray train module for users better to adding the callback to save the checkpoint / or default saving the checkpoint. 

```python
class TrainCheckpointReportCallback(Callback):
    def on_epoch_end(self, epoch, logs=None):
        train.save_checkpoint(**{"model": self.model.get_weights()})
        train.report(**logs)
.....# some codes here #
.....

 multi_worker_model.fit(
            tf_dataset, callbacks=[TrainCheckpointReportCallback()]
        )
```

ideal case: (make this even smoother)

```python
 multi_worker_model.fit(
            tf_dataset, callbacks={'checkpoint': True, 'report': True}
        )
```

### Use case

@amogkam @bveeramani @xwjiang2010 

### related issue or PR

- [ ] https://github.com/ray-project/ray/pull/25070

**Comment by amogkam** [comment] 2022-06-06 21:57
Going to close this as a duplicate of https://github.com/ray-project/ray/issues/20808.

**Closed by amogkam** 2022-06-06 21:57 UTC
Labels: enhancement
