### ISSUE TITLE
[data] include_paths for numpy array is broken

### ISSUE THREAD

**Issue by Warhorze** [ray-project/ray#42607] opened 2024-01-23 16:22 UTC
### What happened + What you expected to happen

the paths are not returned to the data source object.

### Versions / Dependencies

using rayproject/ray-ml:nightly-py39-cu116

### Reproduction script

```
ds = (
    ray.data.read_images("s3://<path_to_npy>", include_paths=True)
)
print(ds)
```
output
```
Dataset(
   num_blocks=5,
   num_rows=?,
   schema={__value__: ArrowTensorType(shape=(512, 4), dtype=uint8)}
)
```

as you can see there are no paths in the file.

### Issue Severity

Medium

**Comment by bveeramani** [comment] 2024-01-30 22:07
Hey @Warhorze, could you confirm the Ray version by executing `print(ray.__version__)`? The `__value__` column name was removed some releases ago, and I wasn't able to reproduce this locally.

```python
import numpy as np

import ray

ds = ray.data.read_numpy("test.npy", include_paths=True)
print(ds)
```

```
Dataset(
   num_blocks=20,
   num_rows=1000,
   schema={data: numpy.ndarray(shape=(1000,), dtype=double), path: string}
)
```

**Comment by bveeramani** [comment] 2024-02-06 06:25
Closing because we can't reproduce this issue.

**Closed by bveeramani** 2024-02-06 06:25 UTC
Labels: bug, P1, cannot-reproduce, data
