### ISSUE TITLE
[rllib] How do I get my GPU to work with my Torch Policies? config["num_gpus"] = 1 introduces errors; 

### ISSUE THREAD

**Issue by akshaygh0sh** [ray-project/ray#17174] opened 2021-07-18 01:30 UTC
I am in the final stages of a project I’ve been working on for a while now in RLlib and as I try to train my model using the gpu (and the Tune API with config[“num_gpus”] = 1), I can’t seem to get it to run without throwing errors.

Specifically, when I try to train my agent, I get an error thrown from [here (Line 157) ](https://github.com/ray-project/ray/blob/3e53619d6479beea383a86f2ec1bd89e3756f6c2/rllib/policy/torch_policy.py#L157) essentially telling me that len(self.devices) is 0 and that no GPUS are being detected.

Initially I thought it was because my GPU was not set up to work with PyTorch (which is the framework I am using for my project), but after running a simple test with torch.cuda.is_available(), torch.cuda.device(0), and torch.cuda.get_device_name(0) I can see that my GPU is being recognized by Torch (RTX 2060-Max Q, just for reference).

Has anyone encountered this error before and are there any workarounds to it? I saw someone suggest removing config["num_gpus] = 1 [https://www.gitmemory.com/issue/ray-project/ray/16459/862005565](url) from the tune.run config call, but that seems to just cause the PyTorch policies to run on my CPU (and they train properly), which is not what I wanted.

Thanks for your help

**Comment by akshaygh0sh** [comment] 2021-07-18 17:41
For reference, here is the error:

`ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::PPO.__init__() (pid=5544, ip=10.0.0.37)
  File "python\ray\_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\_private\function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\agents\trainer_template.py", line 123, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\agents\trainer.py", line 548, in __init__
    super().__init__(config, logger_creator)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\tune\trainable.py", line 98, in __init__
    self.setup(copy.deepcopy(self.config))
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\agents\trainer.py", line 709, in setup
    self._init(self.config, self.env_creator)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\agents\trainer_template.py", line 155, in _init
    num_workers=self.config["num_workers"])
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\agents\trainer.py", line 797, in _make_workers
    logdir=self.logdir)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 83, in __init__
    lambda p, pid: (pid, p.observation_space, p.action_space)))
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\_private\client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\worker.py", line 1497, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=11476, ip=10.0.0.37)
  File "python\ray\_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\_private\function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 537, in __init__
    policy_dict, policy_config)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 1196, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\policy\policy_template.py", line 267, in __init__
    get_batch_divisibility_req=get_batch_divisibility_req,
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\policy\torch_policy.py", line 155, in __init__
    self.device = self.devices[0]
IndexError: list index out of range`

I am using PPO with num_gpus = 1, num_workers = 8, and num_envs_per_worker = 2. My GPU is an Rtx 2060 MaxQ and my CPU has 8 cores and 16 threads.

**Comment by loicsacre** [comment] 2021-07-19 08:36
I am also facing this issue since I have updated ray with the last Daily Release

**Comment by loicsacre** [comment] 2021-07-19 08:49
Try to set the local to false like this `ray.init(local_mode=False)`. It is a bit annoying for debugging though

It might come from this TODO
https://github.com/ray-project/ray/blob/195cdcf5b89e8e95d3991c2144cabd02cb37d736/python/ray/worker.py#L491

**Comment by akshaygh0sh** [comment] 2021-07-20 19:15
> I am also facing this issue since I have updated ray with the last Daily Release

Would rolling back to a previous ray version fix this issue (i.e. allow my GPU to work with my PyTorch policy; this would speed up my training quite a bit). If so, which ray version worked for you?

Thanks!

**Comment by akshaygh0sh** [comment] 2021-07-21 00:55
> Try to set the local to false like this `ray.init(local_mode=False)`. It is a bit annoying for debugging though
> 
> It might come from this TODO
> https://github.com/ray-project/ray/blob/195cdcf5b89e8e95d3991c2144cabd02cb37d736/python/ray/worker.py#L491

Unfortunately, this did not work, I still get the same error as above.

**Comment by BenjaminWinter** [comment] 2021-07-21 15:11
i think this might be a duplicate of #16715

**Comment by akshaygh0sh** [comment] 2021-07-21 16:53
> i think this might be a duplicate of #16715

It seems to be, quite surprising that it hasn't been addressed yet. Even rolling back to 1.3.0 didn't quite fix it and I got new errors, I guess I'll just have to wait till it gets fixed in 1.4.1 to train with my GPU.

**Comment by sven1977** [comment] 2021-07-29 20:11
Testing the above PR now ...

**Closed** 2021-08-02 21:30 UTC
Labels: enhancement
