### ISSUE TITLE
It might be good if tests that have no failing/flaky tests are kept out of https://flakey-tests.ray.io/

### ISSUE THREAD

**Issue by ollie-iterators** [ray-project/ray#35716] opened 2023-05-24 14:22 UTC
### Description

I noticed that some tests that are in flakey have no failing tests. 

Some of those tests are tests that have been moved to different files (like the recently moved computer_vision_test), so the record of the last 100 commits has to catch up.

I think it would be good for https://flakey-tests.ray.io/ to ignore the tests that have missing data and no failing/flakey tests.

### Use case

Look at https://flakey-tests.ray.io/#showAll=true

**Comment by ollie-iterators** [comment] 2023-05-24 14:23
<img width="1201" alt="2023-05-24_10-19-16" src="https://github.com/ray-project/ray/assets/46904826/1aff142f-d01c-436d-80bc-302fd5872730">

**Comment by aslonnie** [comment] 2023-06-05 23:34
closing as duplicate of https://github.com/ray-project/ray/issues/35716

**Closed by aslonnie** 2023-06-05 23:34 UTC
Labels: enhancement, triage
