### ISSUE TITLE
[rllib] Training crashes because get_gpu_ids() returns empty list

### ISSUE THREAD

**Issue by cassidylaidlaw** [ray-project/ray#16715] opened 2021-06-28 20:06 UTC
### What is the problem?

When running a simple RLlib training script, almost identical to the example [here](https://docs.ray.io/en/master/rllib-training.html#basic-python-api), I get the following error:

```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    trainer = ppo.PPOTrainer(config=config, env="CartPole-v0")
  File "/home/cassidy/miniconda3/envs/rllib_test/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 123, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/cassidy/miniconda3/envs/rllib_test/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 562, in __init__
    super().__init__(config, logger_creator)
  File "/home/cassidy/miniconda3/envs/rllib_test/lib/python3.8/site-packages/ray/tune/trainable.py", line 100, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/cassidy/miniconda3/envs/rllib_test/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 722, in setup
    self._init(self.config, self.env_creator)
  File "/home/cassidy/miniconda3/envs/rllib_test/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 147, in _init
    self.workers = self._make_workers(
  File "/home/cassidy/miniconda3/envs/rllib_test/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 804, in _make_workers
    return WorkerSet(
  File "/home/cassidy/miniconda3/envs/rllib_test/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 92, in __init__
    self._local_worker = self._make_worker(
  File "/home/cassidy/miniconda3/envs/rllib_test/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 368, in _make_worker
    worker = cls(
  File "/home/cassidy/miniconda3/envs/rllib_test/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 545, in __init__
    self.policy_map, self.preprocessors = self._build_policy_map(
  File "/home/cassidy/miniconda3/envs/rllib_test/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1323, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/home/cassidy/miniconda3/envs/rllib_test/lib/python3.8/site-packages/ray/rllib/policy/policy_template.py", line 256, in __init__
    self.parent_cls.__init__(
  File "/home/cassidy/miniconda3/envs/rllib_test/lib/python3.8/site-packages/ray/rllib/policy/torch_policy.py", line 156, in __init__
    self.device = self.devices[0]
IndexError: list index out of range
```

The script that reproduces the error is below in the reproduction section. It looks like this error is caused by `ray.get_gpu_ids()` returning an empty list (`[]`) despite there being GPUs attached to the system:

```
>>> import ray
>>> ray.init(num_gpus=4)
2021-06-28 12:57:14,182 INFO services.py:1330 -- View the Ray dashboard at http://127.0.0.1:8265
{'node_ip_address': '128.32.175.10', 'raylet_ip_address': '128.32.175.10', 'redis_address': '128.32.175.10:6379', 'object_store_address': '/tmp/ray/session_2021-06-28_12-57-13_130563_33105/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2021-06-28_12-57-13_130563_33105/sockets/raylet', 'webui_url': '127.0.0.1:8265', 'session_dir': '/tmp/ray/session_2021-06-28_12-57-13_130563_33105', 'metrics_export_port': 59050, 'node_id': 'b6854536c3fea8b39eac4a0723a2af43d56571adf35a750f99bc9982'}
>>> ray.get_gpu_ids()
[]
>>> import torch
>>> torch.cuda.is_available()
True
```

I'm not sure why this is happening—it didn't happen with RLLib 1.3. Interestingly, I can train on GPUs using `rllib train` (the RLlib CLI) with no issue.

*Ray version and other system information (Python version, TensorFlow version, OS):*
 * Ubuntu 18.04.5
 * Python 3.8.10 (anaconda)
 * CUDA 11.3
 
<details>
  <summary>Installed Python packages</summary>
  
```
Package                  Version                                                                                                                           
------------------------ -------------------                                                                                                               
aiohttp                  3.7.4.post0                                                                                                                       
aiohttp-cors             0.7.0                                                                                                                             
aioredis                 1.3.1                                                                                                                             
async-timeout            3.0.1                                                                                                                             
attrs                    21.2.0                                                                                                                            
blessings                1.7                                                                                                                               
cachetools               4.2.2                                                                                                                             
certifi                  2021.5.30                                                                                                                         
chardet                  4.0.0                                                                                                                             
click                    8.0.1                                                                                                                             
cloudpickle              1.6.0                                                                                                                             
colorama                 0.4.4                                                                                                                             
dm-tree                  0.1.6                                                                                                                             
filelock                 3.0.12                                                                                                                            
google-api-core          1.30.0                                                                                                                            
google-auth              1.32.0                                                                                                                            
googleapis-common-protos 1.53.0                                                                                                                            
gpustat                  0.6.0                                                                                                                             
grpcio                   1.38.1
gym                      0.18.3
hiredis                  2.0.0
idna                     2.10
jsonschema               3.2.0
msgpack                  1.0.2
multidict                5.1.0
numpy                    1.21.0
nvidia-ml-py3            7.352.0
opencensus               0.7.13
opencensus-context       0.1.2
opencv-python            4.5.2.54
packaging                20.9
pandas                   1.2.5
Pillow                   8.2.0
pip                      21.1.2
prometheus-client        0.11.0
protobuf                 3.17.3
psutil                   5.8.0
py-spy                   0.3.7
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pydantic                 1.8.2
pyglet                   1.5.15
pyparsing                2.4.7
pyrsistent               0.18.0
python-dateutil          2.8.1
pytz                     2021.1
PyYAML                   5.4.1
ray                      2.0.0.dev0
redis                    3.5.3
requests                 2.25.1
rsa                      4.7.2
scipy                    1.7.0
setuptools               52.0.0.post20210125
six                      1.16.0
tabulate                 0.8.9
torch                    1.9.0
typing-extensions        3.10.0.0
urllib3                  1.26.6
wheel                    0.36.2
yarl                     1.6.3
```
</details>

### Reproduction (REQUIRED)

<details>
  <summary>test.py</summary>
  
  ```
import ray
import ray.rllib.agents.ppo as ppo
from ray.tune.logger import pretty_print

ray.init()
config = ppo.DEFAULT_CONFIG.copy()
config.update({
    "num_gpus": 1,
    "num_workers": 1,
    "framework": "torch",
})
trainer = ppo.PPOTrainer(config=config, env="CartPole-v0")

# Can optionally call trainer.restore(path) to load a checkpoint.

for i in range(1000):
   # Perform one iteration of training the policy with PPO
   result = trainer.train()
   print(pretty_print(result))

   if i % 100 == 0:
       checkpoint = trainer.save()
       print("checkpoint saved at", checkpoint)
```
</details>

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by duburcqa** [comment] 2021-06-30 08:09
I have exactly the same issue using multi-gpu machines since at least v1.3.0 as  far as I remember.

**Comment by zseymour** [comment] 2021-06-30 15:40
Discussed in #16459 as well

**Comment by Wormh0-le** [comment] 2021-07-02 13:28
I also encountered this issue, and I found set `framework=tf` or `framework=tfe` will work, but when set `framework=torch`, it'll `list index out of range`，and after downgraded 0.8.7, it works well.

**Comment by richardliaw** [comment] 2021-07-02 19:20
Assigning to Sven, but Sven will be out of town for a week. If anyone has a workaround please post!

**Comment by ironv** [comment] 2021-07-09 14:21
Adding to the OP's info...   This works fine    `rllib train --run=PPO env=CartPole-v0 --config='{"num_gpus":1, "framework":"torch"}'`  and uses the GPU.

This fails

```
import logging
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

import ray
from ray.rllib.agents import ppo

import torch
torch.cuda.is_available()   #returns True

_ = ray.init(ignore_reinit_error=True)
config = ppo.DEFAULT_CONFIG.copy()
config.update({"num_gpus":1, "framework":"torch"})
trainer = ppo.PPOTrainer(config=config, env="CartPole-v0")
```

stack trace posted above.  Env `python 3.7.10`, `ray 1.4.0`, `CUDA 11.2`

**Comment by zseymour** [comment] 2021-07-09 20:27
Likewise, `rllib rollout --run=PPO --env=CartPole-v0 --config='{"num_gpus":1, "framework":"torch"}'` also produces the error.

**Comment by zseymour** [comment] 2021-07-15 22:34
@sven1977  any updates on the issue?

**Comment by SamShowalter** [comment] 2021-07-27 14:19
Has anyone found a workaround for this?

**Comment by ShuzhiLiu** [comment] 2021-07-28 01:33
I also encountered this problem when I tried to render the video with the saved checkpoint. I found a solution for my case.

This fails and returns `self.device = self.devices[0]` error
```
config = ppo.DEFAULT_CONFIG.copy()
config.update({
    "num_workers": 0,
    "num_gpus": 1,
})
```

And this works
```
config = ppo.DEFAULT_CONFIG.copy()
config.update({
    "num_cpus_for_driver": 1,
    "num_workers": 0,
    "num_gpus": 1,
    "num_cpus_per_worker": 4,
    "num_gpus_per_worker": 1,
    "num_envs_per_worker": 1,
})
```
Hope this helps

**Comment by ShuzhiLiu** [comment] 2021-07-28 08:27
I also encountered this problem. I only have 1 GPU, in my case, adding the next environment variables works.
```
FORCE_CUDA="1"
CUDA_VISIBLE_DEVICES="0"
CUDA_HOME="/usr/local/cuda"
```

**Comment by XuehaiPan** [comment] 2021-07-29 01:41
I find a way to hack the function `ray.get_gpu_ids` using the `unittest.mock` module (https://github.com/ray-project/ray/issues/17397#issuecomment-888732044):

```python
from functools import wraps
from unittest import mock

import ray

def get_gpu_ids_torch():
    import torch
    return list(range(torch.cuda.device_count()))

def get_gpu_ids_tf():
    import tensorflow as tf
    return tf.config.list_physical_devices('GPU')


def patch_ray_get_gpu_ids(patcher):
    def wrapper(func):
        @wraps(func)
        def wrapped(*args, **kwargs):
            with mock.patch('ray.get_gpu_ids', patcher):
                print('Patched ray.get_gpu_ids() = {}'.format(ray.get_gpu_ids()))

                return func(*args, **kwargs)

        return wrapped

    return wrapper


# Add `patch_ray_get_gpu_ids` to your main function before `ray.init()`!
@patch_ray_get_gpu_ids(get_gpu_ids_torch)  # replace with `get_gpu_ids_tf` for TensorFlow
def main(*args, **kwargs):
    print('training ...')

    # Your code here ...

if __name__ == '__main__':
    main()
```

This is only a temporary solution, the official solution should wait to fix `ray.get_gpu_ids()`. The patch result on my machine:

```console
$ python3 ray_patch.py
Patched ray.get_gpu_ids() = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
training ...
```

**Comment by sven1977** [comment] 2021-07-29 16:43
Hey, @krfricke provided a reproduction for this yesterday here: https://github.com/ray-project/ray/issues/17397

@rkooo567 , could one of the core team take a look at this? It's surfacing a lot recently and seems to be a bug in `ray.get_gpu_ids()`.

**Comment by sven1977** [comment] 2021-07-29 20:11
Testing the above PR now ...

**Closed** 2021-08-02 21:30 UTC
Labels: P1, bug, rllib

**Comment by sven1977** [comment] 2021-08-02 21:32
@cassidylaidlaw , this should be fixed now. Just merged this seconds ago. Could you try again on the latest master?

**Comment by cassidylaidlaw** [comment] 2021-08-24 17:23
Seems to work for me now! Thanks for the fix.

**Comment by guotong1988** [comment] 2025-10-21 01:23
https://github.com/ray-project/ray/issues/17397
