### ISSUE TITLE
[Core] GPU assignment via CUDA_VISIBLE_DEVICES is broken when using placement groups with "ray start --head"

### ISSUE THREAD

**Issue by benni-hepp** [ray-project/ray#16614] opened 2021-06-22 16:27 UTC
### What is the problem?

GPU assignment via *CUDA_VISIBLE_DEVICES* is broken when using placement groups.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 1.3.0
Tensorflow: 1.15.0
PyTorch: 1.7.1
OS: Linux (in docker container)

### Reproduction (REQUIRED)
```
import ray
from ray.util.placement_group import placement_group
import time

ray.init()

# Create placement group with 4 bundles using 1 GPU each.
num_gpus = 4
bundles = [{"GPU": 1, "CPU": 1} for _ in range(num_gpus)]
pg = placement_group(bundles)
ray.get(pg.ready())

# Actor using 1 GPU that has a method to print $CUDA_VISIBLE_DEVICES env variable
@ray.remote(num_gpus=1, num_cpus=1)
class Foo:

    def bar(self):
        import os
        print(f'CUDA_VISIBLE_DEVICES={os.environ.get("CUDA_VISIBLE_DEVICES", "<none>")}')

# Necessary to prevent SystemErrors to occur.
time.sleep(5)

# Create one actor per GPU and print the corresponding #CUDA_VISIBLE_DEVICES env variable.
actors = []
for gpu_idx in range(num_gpus):
    ray_options = {"placement_group": pg, "placement_group_bundle_index": gpu_idx}
    actors.append(Foo.options(**ray_options).remote())
    actors[-1].bar.remote()

# Necessary to prevent SystemErrors to occur.
time.sleep(5)

# Cleanup
del actors
ray.util.remove_placement_group(pg)
```

When running the above snippet on e.g. a `p3.8xlarge` AWS instance the GPU device assignments fail ~1 out of 5 runs and the output looks e.g. like this:
```
CUDA_VISIBLE_DEVICES=0
CUDA_VISIBLE_DEVICES=1,3
CUDA_VISIBLE_DEVICES=2
CUDA_VISIBLE_DEVICES=1,3
```

I could also reproduce this with the nightly build from 22nd of June 2021.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment] 2021-06-22 16:33
Hmm, I'm unable to reproduce this on my environment with latest nightlies:

```python
In [1]: import ray
   ...: from ray.util.placement_group import placement_group
   ...: import time
   ...:
   ...: ray.init(num_gpus=4)
   ...:
   ...: # Create placement group with 4 bundles using 1 GPU each.
   ...: num_gpus = 4
   ...: bundles = [{"GPU": 1, "CPU": 1} for _ in range(num_gpus)]
   ...: pg = placement_group(bundles)
   ...: ray.get(pg.ready())
   ...:
   ...: # Actor using 1 GPU that has a method to print $CUDA_VISIBLE_DEVICES env variable
   ...: @ray.remote(num_gpus=1, num_cpus=1)
   ...: class Foo:
   ...:
   ...:     def bar(self):
   ...:         import os
   ...:         print(f'CUDA_VISIBLE_DEVICES={os.environ.get("CUDA_VISIBLE_DEVICES", "<none>")}')
   ...:
   ...: # Necessary to prevent SystemErrors to occur.
   ...: time.sleep(5)
   ...:
   ...: # Create one actor per GPU and print the corresponding #CUDA_VISIBLE_DEVICES env variable.
   ...: actors = []
   ...: for gpu_idx in range(num_gpus):
   ...:     ray_options = {"placement_group": pg, "placement_group_bundle_index": gpu_idx}
   ...:     actors.append(Foo.options(**ray_options).remote())
   ...:     actors[-1].bar.remote()
   ...:
   ...: # Necessary to prevent SystemErrors to occur.
   ...: time.sleep(5)
   ...:
   ...: # Cleanup
   ...: del actors
   ...: ray.util.remove_placement_group(pg)
2021-06-22 09:31:41,632	INFO services.py:1317 -- View the Ray dashboard at http://127.0.0.1:8265
(pid=81280) CUDA_VISIBLE_DEVICES=3
(pid=81281) CUDA_VISIBLE_DEVICES=1
(pid=81275) CUDA_VISIBLE_DEVICES=2
(pid=81278) CUDA_VISIBLE_DEVICES=0
```

**Comment by richardliaw** [comment] 2021-06-22 16:50
Maybe can you check `ray.__version__` and `ray.__commit__`?

**Comment by rkooo567** [comment] 2021-06-22 16:51
I also ran it locally on my Macbook 8 times in a row (with Richard's repro), and I couldn't reproduce it in Ray 1.4.0.

**Comment by benni-hepp** [comment] 2021-06-22 17:19
Just retried with:
`ray.__version__ = 2.0.0.dev0`
`ray.__commit__ = e26c23295410184bcefbdfa0709854f382fca295`

Interesting, the code version above with the local `ray.init(num_gpus=4, num_cpus=4)` also works for me. However, when I start ray via `ray start --head` and use `ray.init(address='auto')` I see the issue that I described above.

**Comment by rkooo567** [comment] 2021-06-23 01:58
Hmm very interesting... so this happens only when the real gpu is used? (it is weird because what ray does under the hood is just setting num_gpus based on the real # of gpus on your machine...)

**Comment by richardliaw** [comment] 2021-07-02 02:39
@rkooo567 can we assign someone for getting a repro for this? this could break a lot of GPU workloads

**Comment by rkooo567** [comment] 2021-07-12 17:47
@ericl This seems to be a bug when the real gpu is used. I am not sure how it's possible, but we should at least try reproducing it imo. I will leave the triaging to you.

**Comment by richardliaw** [comment] 2021-07-12 18:08
@ericl @rkooo567 Hey, can we please treat this with high priority?

This can affect all ML libraries on Ray.

**Comment by ericl** [comment] 2021-07-12 18:24
Fixed in 1.3. Please re-open if you can reproduce on master.

**Comment by wuisawesome** [comment] 2021-07-12 18:34
Let's make sure this isn't fixed by #15049

**Comment by ericl** [comment] 2021-07-12 20:47
I can confirm this is a problem, but very strangely, it only affects `ray start --head`. Using ray.init() works fine.

Steps to reproduce:
1. Change the `ray.init()` in the original script in the issue description to `ray.init("auto")`.
2. Run `ray start --head --num-gpus=4`, then run the script. You'll see the bad GPU assignments as shown above.

**Comment by ericl** [comment] 2021-07-19 18:08
Any updates @clay4444 ?

**Comment by clay4444** [comment] 2021-07-22 17:30
> Any updates @clay4444 ?

sorry~ a little bit busy recently.. but I think I have located the issue, and I believe I will submit the pr today.

**Closed** 2021-07-27 20:51 UTC
Labels: P0, bug
