### ISSUE TITLE
[tune] Does not use all resources and keeps actor pending

### ISSUE THREAD

**Issue by neel04** [ray-project/ray#14108] opened 2021-02-15 11:00 UTC
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS): Ray - Pypi latest
Python 3.x

### Reproduction (REQUIRED)

Environment : COLAB
```

%%bash
pip install -q transformers
pip install -q datasets
pip install -q ray[tune]

train_text = list(["Aahha", "asdsaf", "Lorem Ipsum"])
train_label = list([12, 14, 9])

val_text = list("Lorem Ipsum")
val_label = list([9])

from transformers import RobertaTokenizer, TFRobertaForSequenceClassification
tokenizer = RobertaTokenizer.from_pretrained('roberta-base', num_labels=20)

train_encodings = tokenizer(train_text, truncation=True, padding=True)
val_encodings = tokenizer(val_text, truncation=True, padding=True)

import torch

class IMDbDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = IMDbDataset(train_encodings, train_label)
val_dataset = IMDbDataset(val_encodings, val_label)

from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from transformers import RobertaForSequenceClassification, Trainer, TrainingArguments

def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='weighted')  #none gives score for each class
    acc = accuracy_score(labels, preds)
    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

training_args = TrainingArguments(
    output_dir='./results',          # output directory
    overwrite_output_dir = True,
    num_train_epochs=20,              # total number of training epochs
    per_device_train_batch_size=4,  # batch size per device during training
    per_device_eval_batch_size=32,   # batch size for evaluation,
    warmup_steps=500,                # number of warmup steps for learning rate scheduler
    weight_decay=0.01,               # strength of weight decay
    logging_dir='./logs',            # directory for storing logs
    logging_steps=10,
    evaluation_strategy='steps',
    learning_rate=2e-5,
    fp16 = True,
    load_best_model_at_end = True,
    metric_for_best_model = 'accuracy',
    greater_is_better = True,
    seed = 101,
    do_eval = True,
    adam_beta1=0.9,
    adam_beta2=0.999,
    adam_epsilon=1e-8,
    max_grad_norm=1.0,
    adafactor = False

)

def model_init():
    return RobertaForSequenceClassification.from_pretrained('/content/drive/MyDrive/checkpoint-2700', num_labels=20)

trainer = Trainer(
    model_init=model_init,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

from ray.tune.suggest.hyperopt import HyperOptSearch
from ray.tune.schedulers import PopulationBasedTraining
from ray import tune
import random

pbt = PopulationBasedTraining(
    time_attr="training_iteration",
    metric="accuracy",
    mode="max",
    perturbation_interval=10,  # every 10 `time_attr` units
                               # (training_iterations in this case)
    hyperparam_mutations={
        # Alternatively, use tune search space primitives.
        # The search space for factor_1 is equivalent to factor_2.
        "weight_decay": tune.uniform(1, 0.0001),
        # Perturb factor3 by changing it to an adjacent value, e.g.
        # 10 -> 1 or 10 -> 100. Resampling will choose at random.
        "seed": tune.uniform(1,20000),
        # Using tune.choice is NOT equivalent to the above.
        # factor_4 is treated as a continuous hyperparameter.
        "learning_rate": tune.choice([1e-5, 2e-5, 3e-5, 4e-5, 5e-5, 6e-5, 2e-7, 1e-7, 3e-7, 2e-8]),
        "adafactor": tune.choice(['True','False']),
        "adam_beta1": tune.uniform(1.0, 0.0),
        "adam_beta2": tune.uniform(1.0, 0),
        "adam_epsilon": tune.choice([1e-8, 2e-8, 3e-8, 1e-9, 2e-9, 3e-10]),
        "max_grad_norm": tune.uniform(1.0, 0),

    })

best_run = trainer.hyperparameter_search(n_trials=100, compute_objective='accuracy', direction="maximize", backend='ray',
                                         search_alg=HyperOptSearch(metric='accuracy', mode='max', use_early_stopped_trials=True), scheduler=pbt,
                                         keep_checkpoints_num=1)
```
Apologies for the long script, but it was necessary in order to reproduce the exact code used. Here, in the output log:-

`Resources requested: 1/4 CPUs, 1/1 GPUs, 0.0/14.99 GiB heap, 0.0/5.18 GiB objects (0/1.0 accelerator_type:P100)`
The actor does not use all the resources available, saying this
```

2021-02-15 10:58:56,592	WARNING worker.py:1107 -- The actor or task with ID ffffffffffffffffc96088b12950798b4c09133201000000 cannot be scheduled right now. It requires {GPU: 1.000000}, {CPU: 1.000000} for placement, but this node only has remaining {3.000000/4.000000 CPU, 14.990234 GiB/14.990234 GiB memory, 0.000000/1.000000 GPU, 1.000000/1.000000 node:172.28.0.2, 1.000000/1.000000 accelerator_type:P100, 5.175781 GiB/5.175781 GiB object_store_memory}
. In total there are 0 pending tasks and 1 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster.
```
How do I get the actor to use all the resources, **especially** the accelerator because using `nvidia-smi`, it shows that there is 0% GPU usage...

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment] 2021-02-22 17:45
(duplicate of hugging face issue?)

**Closed by richardliaw** 2021-02-22 17:45 UTC
Labels: bug, triage
