### ISSUE TITLE
[installation] Ray Installation broken with circular import on virtualenvs

### ISSUE THREAD

**Issue by andreichalapco** [ray-project/ray#29587] opened 2022-10-23 10:16 UTC
### What happened + What you expected to happen

Hi,

when wanting to build ray just for python (See https://docs.ray.io/en/latest/ray-contribute/development.html#building-ray-python-only) I've encountered a problem when trying to run the script : ```python python/ray/setup-dev.py```. 

The following stack tracke appears:
```
Traceback (most recent call last):
  File "/home/andreichalapco/open-source-projects/ray/python/ray/setup-dev.py", line 6, in <module>
    import argparse
  File "/usr/lib64/python3.10/argparse.py", line 89, in <module>
    import re as _re
  File "/usr/lib64/python3.10/re.py", line 124, in <module>
    import enum
  File "/usr/lib64/python3.10/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/home/andreichalapco/open-source-projects/ray/python/ray/types.py", line 1, in <module>
    from typing import Generic, TypeVar
  File "/usr/lib64/python3.10/typing.py", line 25, in <module>
    import contextlib
  File "/usr/lib64/python3.10/contextlib.py", line 6, in <module>
    from functools import wraps
  File "/usr/lib64/python3.10/functools.py", line 22, in <module>
    from types import GenericAlias
ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' (most likely due to a circular import) (/home/andreichalapco/open-source-projects/ray/python/ray/types.py)
```

It seems it is a circular import problem... (the problem is caused by the fact that setup-dev lies in the same folder as the types file in ray)

### Versions / Dependencies

Name: ray
Version: 3.0.0.dev0

### Reproduction script

```python python/ray/setup-dev.py```

### Issue Severity

High: It blocks me from completing my task.

**Comment by zhe-thoughts** [comment] 2022-10-26 23:24
Assigning to @cadedaniel to quickly verify

**Comment by cadedaniel** [comment] 2022-10-27 18:23
I will get to this today.

**Comment by cadedaniel** [comment] 2022-10-28 23:20
I've reproduced this, I suspect it is related to the virtualenv creation since before that it wouldn't reproduce for me.

**Comment by cadedaniel** [comment] 2022-11-01 17:48
@andreichalapco to unblock you, can you try this workaround? https://github.com/ray-project/ray/issues/29236

**Comment by andreichalapco** [comment] 2022-11-01 18:34
Please look at the following small example I did:
![image](https://user-images.githubusercontent.com/39555799/199310829-746fb5ab-3685-4874-a9a3-e338771054b7.png)

If you place the setup-dev file in another folder in another folder It will eliminate the possibility for the python interpreter to look for the types module in the local path (where the setup-dev file is located). Running the script in debugging mode (or I think the trick with conda) eliminates this possibility. 
Personally I would fix this issue ( although there are workarounds). 
Found interesting that other developers didn't encounter this problem.

**Comment by richardliaw** [comment] 2023-01-25 23:59
Seems like this is also reported by @bdewilde -- can you confirm that this is still an issue when trying https://github.com/ray-project/ray/issues/29236#issuecomment-1275401354 ?

**Comment by richardliaw** [comment] 2023-01-25 23:59
```
conda create --name python310 python=3.10
conda activate python310

pip install -U ray

python python/ray/setup-dev.py
```

**Comment by nidabdella** [comment] 2023-02-20 17:08
This is still an issue for me too:

```shell
❯ python --version
Python 3.10.6
❯ python3 -m venv ray_venv 
❯ source ray_venv/bin/activate 
❯ pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp310-cp310-manylinux2014_x86_64.whl
....
....
❯ cd ray
❯ python python/ray/setup-dev.py
Traceback (most recent call last):
  File "/home/med/Documents/Clients/Ray/ray/python/ray/setup-dev.py", line 6, in <module>
    import argparse
  File "/usr/lib/python3.10/argparse.py", line 89, in <module>
    import re as _re
  File "/usr/lib/python3.10/re.py", line 124, in <module>
    import enum
  File "/usr/lib/python3.10/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/home/med/Documents/Clients/Ray/ray/python/ray/types.py", line 1, in <module>
    from typing import Generic, TypeVar
  File "/usr/lib/python3.10/typing.py", line 25, in <module>
    import contextlib
  File "/usr/lib/python3.10/contextlib.py", line 6, in <module>
    from functools import wraps
  File "/usr/lib/python3.10/functools.py", line 22, in <module>
    from types import GenericAlias
ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' (most likely due to a circular import) (/home/med/Documents/Clients/Ray/ray/python/ray/types.py)

```

**Comment by PaulFenton** [comment] 2023-08-26 15:56
I also hit this issue by following the [Prepare the Python environment](https://docs.ray.io/en/latest/ray-contribute/development.html#prepare-the-python-environment) and [Building Ray (Python only)](https://docs.ray.io/en/latest/ray-contribute/development.html#prepare-the-python-environment) steps.

I am running Python 3.8.10 on Ubuntu 20.04 LTS (WSL)

Investigating this I found that the underlying issue has been discussed in #31458 with a solution that appeared to work for some people in #31829

For my case, I found that the workaround added there was not being applied because `os.path.dirname(__file__)` was returning a relative path where my `sys.path` expected it to be absolute.

I have made a PR #38948 which makes the directory path absolute and issues a print statement when this workaround is being used

**Closed** 2024-08-06 05:19 UTC
Labels: bug, dependencies, core, P1.5, core-tech-debt
