### ISSUE TITLE
[rllib] Does the action space support gym.space.Dict?

### ISSUE THREAD

**Issue by xxArbiter** [ray-project/ray#8685] opened 2020-05-30 18:56 UTC
## Question
When I use other kinds of spaces like Box, Discrete, there is no problem. But if I use a Dict for the action space, during running, it will arise a ValueError. 

We are testing the code and running an evaluator with a random policy. The action is randomly selected by space.sample() method.

The error is shown as bellow:

```
ray::RolloutWorker.sample() (pid=8435, ip=192.168.4.207)
  File "python/ray/_raylet.pyx", line 456, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 459, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 460, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 414, in ray._raylet.execute_task.function_executor
  File "/home/arbiter/anaconda3/envs/traffic/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 521, in sample
    batches = [self.input_reader.next()]
  File "/home/arbiter/anaconda3/envs/traffic/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 56, in next
    batches = [self.get_data()]
  File "/home/arbiter/anaconda3/envs/traffic/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 101, in get_data
    item = next(self.rollout_provider)
  File "/home/arbiter/anaconda3/envs/traffic/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 374, in _env_runner
    off_policy_actions, policies, clip_actions)
  File "/home/arbiter/anaconda3/envs/traffic/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 689, in _process_policy_eval_results
    actions = clip_action(actions, policy.action_space_struct)
  File "/home/arbiter/anaconda3/envs/traffic/lib/python3.6/site-packages/ray/rllib/policy/policy.py", line 424, in clip_action
    return tree.map_structure(map_, action, action_space)
  File "/home/arbiter/anaconda3/envs/traffic/lib/python3.6/site-packages/tree/__init__.py", line 513, in map_structure
    assert_same_structure(structures[0], other, check_types=check_types)
  File "/home/arbiter/anaconda3/envs/traffic/lib/python3.6/site-packages/tree/__init__.py", line 372, in assert_same_structure
    % (e, str1, str2))
ValueError: The two structures don't have the same nested structure.

First structure: type=ndarray str=[OrderedDict([('center0', array([0.34, 0.65], dtype=float32))])
 OrderedDict([('center0', array([0.81, 0.35], dtype=float32))])]

Second structure: type=dict str={'center0': Box(2,)}

More specifically: Substructure "type=dict str={'center0': Box(2,)}" is a sequence, while substructure "type=ndarray str=[OrderedDict([('center0', array([0.34, 0.65], dtype=float32))])
 OrderedDict([('center0', array([0.81, 0.35], dtype=float32))])]" is not
```

## System information
Ray version: 0.9.0
Python version: 3.6.10
OS: Ubuntu 18.04

**Comment by ericl** [comment] 2020-05-31 01:13
Can you provide a reproduction script so that we can fix this?

**Comment by xxArbiter** [comment] 2020-06-07 22:33
Hi, sorry for the delay in response. I tried to reproduce this error from a script with simple components last week. But I failed. It works well with some simple envs & models. I knew that ray should support the Dict action space. I just have no idea where does this error come. Do you have any advice on this? Thanks!

**Comment by ericl** [comment] 2020-06-11 17:50
This should be fixed in the latest release.

**Closed by ericl** 2020-06-11 17:50 UTC
Labels: bug, needs-repro-script, rllib

**Comment by sven1977** [comment] 2020-06-11 20:50
This looks like a bug in your policy not producing an action according to its action space. But again, we cannot look into this unless we have a (small) repro script with which we can debug.
