### ISSUE TITLE
[ray] Memory leak in main function?

### ISSUE THREAD

**Issue by idthanm** [ray-project/ray#7516] opened 2020-03-09 12:03 UTC
### What is your question?
When I run the following script, the memory occupied by the main process keeps growing (about 1M/5s),  while the memory occupied by Sample_numpy actor and redis-server keeps steady. Could anyone explain this? Is there any relation between the memory of main process and object_store_memory?

```
import ray
import numpy as np


class Sample_numpy(object):
    def __init__(self):
         pass

    def sample(self):
        samples = np.random.random([1000, 1000])
        return samples

def test_remote():
      ray.init(redis_max_memory=100 * 1024 * 1024, object_store_memory=1000 * 1024 * 1024)
      sampler = ray.remote(Sample_numpy).remote()
      for _ in range(1000000000):
          objID = sampler.sample.remote()
          samples = ray.get(objID)
          ray.internal.free([objID])

if __name__ == "__main__":
    test_remote()
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray version: 0.8.2
Python version: 3.7.4
OS version: ubuntu 16.04
Numpy version: 1.17.1

**Comment by idthanm** [comment] 2020-03-09 15:20
My problem is exactly like https://stackoverflow.com/questions/6809947/python-memory-leaks-trackdown

**Comment by stephanie-wang** [comment] 2020-03-09 17:24
I tried running your script for a few minutes but the memory usage of the main process stayed stable for me, on both ray 0.8.2 and master. Are you sure this is the full script?

By the way, you don't need to manually call `ray.internal.free([objID])` since `objID` goes out of scope after each iteration (ray will free the memory automatically).

**Comment by idthanm** [comment] 2020-03-10 04:33
Hi @stephanie-wang, thank you for your quick reply! I am sure this is the full script and I still have the problem with it. When I started the script, RES of the main process (highlighted in the following figure) is 228M (the first column),
![Screenshot from 2020-03-10 11-11-39](https://user-images.githubusercontent.com/41318774/76278691-30811000-62c7-11ea-9355-a1a0e7b7632f.png)
Several minutes later, it grew to 240M and had no sign to stop.
![Screenshot from 2020-03-10 11-16-49](https://user-images.githubusercontent.com/41318774/76278885-b8671a00-62c7-11ea-9d41-95e61779dabd.png)

However, when I delete `ray.internal.free([objID])` as you suggested, it stayed perfectly stable. So I thought this is the problem. I am curious why it became worse when I manually free the objID. The reason I did this is inspired by `ray_get_and_free()` function in `rllib/utils/memory.py`. It says _This function should be used whenever possible_. So I originally thought RAY maybe not free the memory automatically. 

Could you help judge whether my following understandings are correct?

1. Assume we run a program in local machine, whenever you call `object=ray.get(objID)` or `objID=ray.put(object)` would store the object in Object Store Memory.
2. When the objID goes out of scope in python script, the corresponding object stored in Object Store Memory will be removed automatically by RAY. For example
`objID=ray.put(object)`
`objID=0`
will remove object stored in Object Store Memory.

**Comment by stephanie-wang** [comment] 2020-03-10 20:54
We used to not have automatic memory management, but it's on by default as of v0.8.1. `ray.internal.free` was a method for manually freeing memory, but it's not recommended for direct use anymore (we do need to update the documentation).

And yes, your understanding looks correct to me. One clarification, when the object ID goes out of scope, the corresponding object will only get marked for removal. The memory will not necessarily get freed immediately, so you might still see shared memory utilization increase.

Closing this issue for now, but feel free to reopen if the issue isn't resolved.

**Closed by stephanie-wang** 2020-03-10 20:54 UTC
Labels: question
