### ISSUE TITLE
[Docs] Right-hand side TOC don't skip to the right section

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#38341] opened 2023-08-10 22:48 UTC
### What happened + What you expected to happen

When I click on a line in the right-hand side TOC, the line above gets clicked. E.g. on [this page](https://docs.ray.io/en/master/serve/develop-and-deploy.html) in the docs, if I click on `Monitor Ray Serve`, the line two above (`Build Serve config files for production deployment`) gets clicked instead. Additionally, the documentation skips to the section between both of these (`Deploy Ray Serve in production`).

### Versions / Dependencies

Ray on the latest `master`.

### Reproduction script

This happens on any docs page. See [this page](https://docs.ray.io/en/master/serve/develop-and-deploy.html) for an example.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by architkulkarni** [comment] 2023-08-29 21:48
+1.  Also, if I click on "Deploy Ray Serve in production", the right hand TOC looks as if the bottom link got clicked: 
<img width="303" alt="Screenshot 2023-08-29 at 2 48 12 PM" src="https://github.com/ray-project/ray/assets/5459654/e08f4bcd-675b-47c8-ac36-6412f54d99fe">

**Comment by peytondmurray** [comment] 2023-08-31 16:45
I think this is a duplicate of https://github.com/ray-project/ray/issues/33318 - see that issue for more information.

**Comment by angelinalg** [comment] 2023-08-31 17:07
Closed as duplicate of https://github.com/ray-project/ray/issues/33318

**Closed** 2023-08-31 20:07 UTC
Labels: bug, triage, docs
