### ISSUE TITLE
[Bug] Core scalability infra failure from 3 days ago

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#21134] opened 2021-12-16 14:40 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Example: https://buildkite.com/ray-project/periodic-ci/builds/1935#c885ca1b-983a-46c6-a219-bdfc6ac0819c

Looks like core scalability test has had infra failure for a long time due to app config build failure. We should fix it.

### Versions / Dependencies

N/a

### Reproduction script

Look https://buildkite.com/ray-project/periodic-ci/builds/1935#c885ca1b-983a-46c6-a219-bdfc6ac0819c

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by architkulkarni** [comment] 2021-12-16 20:11
Duplicate of #21096.  @rkooo567 please reopen if I made a mistake!

**Closed by architkulkarni** 2021-12-16 20:11 UTC
Labels: bug, P0
