### ISSUE TITLE
AttributeError: type object 'Callable' has no attribute '_abc_registry'

### ISSUE THREAD

**Issue by devin-petersohn** [ray-project/ray#4929] opened 2019-06-04 15:04 UTC
```python
import ray
ray.init()

@ray.remote
def should_break():
    import pandas
    return pandas.DataFrame([1,2,3])

ray.get([should_break.remote() for _ in range(10)])
```

In Python 3.7 this will fail if the user has a library called `typing` installed. It has been reported several times in Modin: modin-project/modin#540, modin-project/modin#619, modin-project/modin#647. If the user uninstalls the `typing` library installed from pypi, it resolves the issue, but that is not always possible.

See modin-project/modin#647 for the conversation/traceback

**Comment by richardliaw** [comment] 2019-06-04 23:07
@devin-petersohn this is a dupe of #4794 and #4852 I think.

**Comment by robertnishihara** [comment] 2019-06-04 23:10
I closed the other issues. Let's consolidate discussion on this one since this one actually diagnoses the issue.

Is this a bug in `typing`?

**Comment by devin-petersohn** [comment] 2019-06-05 05:23
There is a pypi `typing` and a builtin `typing`. They are not compatible on Python3.7 I believe.

**Comment by robertnishihara** [comment] 2019-06-05 06:21
Interesting, we seem to require `typing` in our `setup.py`

https://github.com/ray-project/ray/blob/d10628376994fdea2eec3269201e1e589f4f2dad/python/setup.py#L151-L152

is the comment correct?

**Comment by devin-petersohn** [comment] 2019-06-05 06:26
We got rid of the dependency a couple of weeks ago. Removing it won't resolve the problem for users who prefer the pypi package though. That is what modin-project/modin#647 is about. Removing `typing` isn't an option for that user.

**Comment by richardliaw** [comment] 2020-11-14 23:40
I haven't seen this on master recently. I'd encourage folks running into this to open a new issue.

**Closed by richardliaw** 2020-11-14 23:40 UTC
