### ISSUE TITLE
[Core/Test] chaos_many_actors failed in the master

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#30606] opened 2022-11-23 02:45 UTC
### What happened + What you expected to happen

chaos_many_actors failed recently (https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_9hGiG4j8KzyNsjh6QZiVes58), and I feel like https://github.com/ray-project/ray/commit/572464c6abc555629696050585297644f68669ba -> this is the most likely. Here’s the list of commits. This test failed only once for last 2 months. Here’s the list of commits inbetween

<img width="1308" alt="Screen Shot 2022-11-22 at 6 42 37 PM" src="https://user-images.githubusercontent.com/18510752/203460102-4f3377ed-bdaf-4bb3-8151-74e68631ac5f.png">
<img width="1305" alt="Screen Shot 2022-11-22 at 6 42 41 PM" src="https://user-images.githubusercontent.com/18510752/203460105-eacf9b63-ad70-4203-a908-454faab56522.png">

### Versions / Dependencies

n/a

### Reproduction script

n/a

**Comment by iycheng** [comment] 2022-11-23 07:22
https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_vnCuEVArPXqNLFEk8ZzBGc2c

https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_vnCuEVArPXqNLFEk8ZzBGc2c

Tried to reproduce it twice, but failed. Also not able to retrieve the first run failures. maybe due to infra issues (python-core-worker logs are missing).

I'm considering closing this one. @rkooo567 how do you think?

**Comment by iycheng** [comment] 2022-11-23 19:28
https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_2MdmvThtukwpyRVQfbZPimM8?command-history-section=command_history

https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_N4NMRVSXvMsXgwepfnX9knhr?command-history-section=command_history

Hmmm this one also passed somehow. Seems flakey

**Comment by iycheng** [comment] 2022-11-23 23:07
https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_XV2irL2B3LCp1X7m8kx1NKTD

**Comment by iycheng** [comment] 2022-11-27 21:04
http://internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_6iEUcAdJpS8C4usbnaamds5H

**Comment by iycheng** [comment] 2022-11-27 22:38
https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_heUHCkeZUBQUcvX6VYeSHPqT

**Comment by iycheng** [comment] 2022-11-27 22:38
close this one given that all tests I run passed and the original failed one doesn't show anything useful.

**Closed by iycheng** 2022-11-27 22:38 UTC
Labels: bug, release-blocker, P0, core, r2.2-failure
