### ISSUE TITLE
[Serve] Constructor failure should fail deploy()

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#16597] opened 2021-06-21 23:53 UTC
Running the following code will not error the code, it's weird that if we are waiting for the scaling up, then we should wait for the healthcheck; alternatively, we should wait for neither (K8s style)

```
ray start --head
```

```python
from ray import serve
import ray
ray.init(address="auto", namespace="ns")

serve.start(detached=True)

@serve.deployment
class Fail:
    def __init__(self):
        1/0

Fail.deploy()
```

```
(ray-repro) ➜  /tmp python a.py
2021-06-21 16:50:45,117	INFO worker.py:727 -- Connecting to existing Ray cluster at address: 192.168.1.69:6379
(pid=27355) 2021-06-21 16:50:46,384	INFO http_state.py:75 -- Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-node:192.168.1.69-0' on node 'node:192.168.1.69-0' listening on '127.0.0.1:8000'
2021-06-21 16:50:47,624	INFO api.py:415 -- Updating deployment 'Fail'.
(pid=27358) INFO:     Started server process [27358]
(pid=27355) 2021-06-21 16:50:47,653	INFO backend_state.py:773 -- Adding 1 replicas to backend 'Fail'.
(pid=27355) 2021-06-21 16:50:47,668	INFO runtime_env.py:112 -- Using preinstalled conda environment: ray-repro
(pid=27364) 2021-06-21 16:50:50,203	ERROR worker.py:409 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SERVE_CONTROLLER_ACTOR:Fail#HBhQxK:RayServeWrappedReplica.__init__ (pid=27364, ip=192.168.1.69)
(pid=27364)   File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
(pid=27364)   File "python/ray/_raylet.pyx", line 448, in ray._raylet.execute_task.function_executor
(pid=27364)   File "python/ray/_raylet.pyx", line 1664, in ray._raylet.CoreWorker.run_async_func_in_event_loop
(pid=27364)   File "/Users/simonmo/miniconda3/envs/ray-repro/lib/python3.6/concurrent/futures/_base.py", line 425, in result
(pid=27364)     return self.__get_result()
(pid=27364)   File "/Users/simonmo/miniconda3/envs/ray-repro/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
(pid=27364)     raise self._exception
(pid=27364)   File "/Users/simonmo/miniconda3/envs/ray-repro/lib/python3.6/site-packages/ray/serve/backend_worker.py", line 74, in __init__
(pid=27364)     await sync_to_async(_callable.__init__)(*init_args)
(pid=27364)   File "/Users/simonmo/miniconda3/envs/ray-repro/lib/python3.6/site-packages/ray/_private/async_compat.py", line 29, in wrapper
(pid=27364)     return func(*args, **kwargs)
(pid=27364)   File "a.py", line 10, in __init__
(pid=27364)     1/0
(pid=27364) ZeroDivisionError: division by zero
(pid=27355) 2021-06-21 16:50:50,266	ERROR controller.py:121 -- Exception updating backend state: Failed to look up actor with name 'SERVE_CONTROLLER_ACTOR:Fail#HBhQxK'. You are either trying to look up a named actor you didn't create, the named actor died, or the actor hasn't been created because named actor creation is asynchronous.
(pid=27355) 2021-06-21 16:50:50,473	WARNING backend_state.py:865 -- Replica Fail#HBhQxK of backend Fail failed health check, stopping it.
(pid=27355) 2021-06-21 16:50:50,583	INFO backend_state.py:773 -- Adding 1 replicas to backend 'Fail'.
(pid=27355) 2021-06-21 16:50:50,591	INFO runtime_env.py:112 -- Using preinstalled conda environment: ray-repro
(ray-repro) ➜  # command above returned 0
```

**Comment by edoakes** [comment] 2021-06-22 22:32
@simon-mo https://github.com/ray-project/ray/issues/16114

**Comment by edoakes** [comment] 2021-06-22 22:33
@simon-mo yeah we should prioritize this. Ideally we would also do an automatic rollback to a previous version (if it existed)

**Comment by jiaodong** [comment] 2021-06-25 23:26
This is what I saw on my terminal if running the same set of instructions:

```
2021-06-25 16:23:57,505	INFO worker.py:733 -- Connecting to existing Ray cluster at address: 192.168.86.154:6379
(pid=43076) 2021-06-25 16:23:58,509	INFO http_state.py:72 -- Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-node:192.168.86.154-0' on node 'node:192.168.86.154-0' listening on '127.0.0.1:8000'
2021-06-25 16:23:59,059	INFO api.py:716 -- Started detached Serve instance in namespace 'ns'.
(pid=43078) INFO:     Started server process [43078]
2021-06-25 16:23:59,066	INFO api.py:418 -- Updating deployment 'Fail'.
(pid=43076) 2021-06-25 16:23:59,140	INFO backend_state.py:802 -- Adding 1 replicas to backend 'Fail'.
(pid=43076) 2021-06-25 16:23:59,146	INFO runtime_env.py:111 -- Using preinstalled conda environment: ray
(pid=43093) 2021-06-25 16:24:01,207	ERROR worker.py:414 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SERVE_CONTROLLER_ACTOR:Fail#ZEqBbB:RayServeWrappedReplica.__init__ (pid=43093, ip=192.168.86.154)
(pid=43093)   File "python/ray/_raylet.pyx", line 535, in ray._raylet.execute_task
(pid=43093)   File "python/ray/_raylet.pyx", line 482, in ray._raylet.execute_task.function_executor
(pid=43093)   File "python/ray/_raylet.pyx", line 1724, in ray._raylet.CoreWorker.run_async_func_in_event_loop
(pid=43093)   File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.8/concurrent/futures/_base.py", line 437, in result
(pid=43093)     return self.__get_result()
(pid=43093)   File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
(pid=43093)     raise self._exception
(pid=43093)   File "/Users/jiaodong/Workspace/ray/python/ray/serve/backend_worker.py", line 74, in __init__
(pid=43093)     await sync_to_async(_callable.__init__)(*init_args)
(pid=43093)   File "/Users/jiaodong/Workspace/ray/python/ray/_private/async_compat.py", line 29, in wrapper
(pid=43093)     return func(*args, **kwargs)
(pid=43093)   File "a.py", line 10, in __init__
(pid=43093)     1/0
(pid=43093) ZeroDivisionError: division by zero
(pid=43076) 2021-06-25 16:24:01,290	ERROR controller.py:121 -- Exception updating backend state: Failed to look up actor with name 'SERVE_CONTROLLER_ACTOR:Fail#ZEqBbB'. You are either trying to look up a named actor you didn't create, the named actor died, or the actor hasn't been created because named actor creation is asynchronous.
(pid=43076) 2021-06-25 16:24:01,493	WARNING backend_state.py:893 -- Replica Fail#ZEqBbB of backend Fail failed health check, stopping it.
(pid=43076) 2021-06-25 16:24:01,601	INFO backend_state.py:802 -- Adding 1 replicas to backend 'Fail'.
(pid=43076) 2021-06-25 16:24:01,606	INFO runtime_env.py:111 -- Using preinstalled conda environment: ray
(pid=43099) 2021-06-25 16:24:01,716	ERROR worker.py:414 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SERVE_CONTROLLER_ACTOR:Fail#vbMZgc:RayServeWrappedReplica.__init__ (pid=43099, ip=192.168.86.154)
(pid=43099)   File "python/ray/_raylet.pyx", line 535, in ray._raylet.execute_task
(pid=43099)   File "python/ray/_raylet.pyx", line 482, in ray._raylet.execute_task.function_executor
(pid=43099)   File "python/ray/_raylet.pyx", line 1724, in ray._raylet.CoreWorker.run_async_func_in_event_loop
(pid=43099)   File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.8/concurrent/futures/_base.py", line 437, in result
(pid=43099)     return self.__get_result()
(pid=43099)   File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
(pid=43099)     raise self._exception
(pid=43099)   File "/Users/jiaodong/Workspace/ray/python/ray/serve/backend_worker.py", line 74, in __init__
(pid=43099)     await sync_to_async(_callable.__init__)(*init_args)
(pid=43099)   File "/Users/jiaodong/Workspace/ray/python/ray/_private/async_compat.py", line 29, in wrapper
(pid=43099)     return func(*args, **kwargs)
(pid=43099)   File "a.py", line 10, in __init__
(pid=43099)     1/0
(pid=43099) ZeroDivisionError: division by zero
(pid=43076) 2021-06-25 16:24:01,825	ERROR controller.py:121 -- Exception updating backend state: Failed to look up actor with name 'SERVE_CONTROLLER_ACTOR:Fail#vbMZgc'. You are either trying to look up a named actor you didn't create, the named actor died, or the actor hasn't been created because named actor creation is asynchronous.
```

**Comment by edoakes** [comment] 2021-07-26 17:38
Duplicate of https://github.com/ray-project/ray/issues/16114

**Closed by edoakes** 2021-07-26 17:38 UTC
Labels: P1, bug, serve
