### ISSUE TITLE
[workflows] "Caught schedule exception" with Ray Client

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#21594] opened 2022-01-14 04:51 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

I expected there to be no output (or minimal output). 

```
In [2]: ray.init("ray://127.0.0.1:10001")
Out[2]: ClientContext(dashboard_url='127.0.0.1:8265', python_version='3.6.12', ray_version='2.0.0.dev0', ray_commit='1df67eb9776e94c60de1a3b62b67d9d7315689be', protocol_version='2021-12-07', _num_clients=1, _context_to_restore=<ray.util.client._ClientContext object at 0x7f4530c130f0>)

In [5]: workflow.init()
   ...:
2022-01-13 20:50:14,049	INFO api.py:52 -- Using storage: file:///tmp/ray/workflow_data
Caught schedule exception
2022-01-13 20:50:14,055	INFO workflow_access.py:378 -- Initializing workflow manager...
Caught schedule exception
2022-01-13 20:50:14,180	INFO threading.py:347 -- Exception from actor creation is ignored in destructor. To receive this exception in application code, call a method on the actor reference before its destructor is run.
```

A lot of exceptions here^

### Versions / Dependencies

 rayproject/ray:1df67e-py36-cpu

### Reproduction script

See above

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by iycheng** [comment] 2022-01-14 08:11
Close this one since we have https://github.com/ray-project/ray/issues/21595 ticket

**Closed by iycheng** 2022-01-14 08:11 UTC
Labels: bug, triage

**Comment by Joshuaalbert** [comment] 2022-06-18 05:30
@iycheng I'm getting the same message. Any idea what the problem is?
