### ISSUE TITLE
[Ray 2.3 Release] [Core microbenchmarks] 1:1 actor calls async perf regression just before branch cut

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#32250] opened 2023-02-06 22:42 UTC
<img width="433" alt="Screen Shot 2023-02-06 at 2 40 56 PM" src="https://user-images.githubusercontent.com/950914/217104063-db6f694a-ceaf-4821-b9a7-125a3166c17b.png">

**Comment by scv119** [comment] 2023-02-08 23:33
duplicate of https://github.com/ray-project/ray/issues/32235

**Closed by scv119** 2023-02-08 23:33 UTC
Labels: release-blocker, core
