### ISSUE TITLE
[autoscaler] AWS node provider broken due to external ip never getting updated

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#3935] opened 2019-02-03 00:26 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: Source @ https://github.com/ray-project/ray/commit/002531b199aaeb40d267b4ac50dbc7ae7689da1b
- **Ray version**: 0.6.2 @ 002531b199aaeb40d267b4ac50dbc7ae7689da1b
- **Python version**: 3.6
- **Exact command to reproduce**: `ray teardown -y ${RAY_PATH}/python/ray/autoscaler/aws/example-minimal.yaml && ray exec ${RAY_PATH}/python/ray/autoscaler/aws/example-minimal.yaml "echo test" --start`

### Describe the problem
When running the command above, the autoscaler correctly creates a head node but then hangs waiting for its ip. This happens because when the node is first created, we insert the node (without ip) to the node provider's node cache, and then when waiting for the ip we never refresh the node data, thus leading to just infinite loop [here](https://github.com/ray-project/ray/blob/002531b199aaeb40d267b4ac50dbc7ae7689da1b/python/ray/autoscaler/updater.py#L85) until `NODE_START_WAIT_S` breaks it.

This didn't happen before because we used an external ip cache, which would not have a key for a node until the external ip actually existed. The behavior was changed here: https://github.com/ray-project/ray/commit/315edab08508e7b4ca07ce22467d76dad4031a89#diff-6c1c6ac4425d69b4155cb41c15eeb277L89

### Source code / logs
```
(softlearning) ➜ kristian@jensen2: ~/github/hartikainen/ray on master ✗
$ ray teardown -y ~/github/hartikainen/ray/python/ray/autoscaler/aws/example-minimal.yaml && ray exec ~/github/hartikainen/ray/python/ray/autoscaler/aws/example-minimal.yaml "echo test" --start
2019-02-02 16:12:11,822 INFO commands.py:108 -- teardown_cluster: Terminating 1 nodes...
2019-02-02 16:12:13,112 INFO log_timer.py:21 -- teardown_cluster: Termination done. [LogTimer=1291ms]
2019-02-02 16:12:14,149 INFO commands.py:172 -- get_or_create_head_node: Launching new head node...
2019-02-02 16:12:15,510 INFO commands.py:185 -- get_or_create_head_node: Updating files on head node...
2019-02-02 16:12:15,512 INFO updater.py:126 -- NodeUpdater: i-0a4c4fcfc2ee6a75b: Updating to 7d28d7c48d6357f567a59188f2e558932a05ac3f
2019-02-02 16:12:15,512 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:12:15,633 INFO log_timer.py:21 -- AWSNodeProvider: Set tag ray-node-status=waiting-for-ssh on ['i-0a4c4fcfc2ee6a75b'] [LogTimer=120ms]
2019-02-02 16:12:25,520 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:12:35,529 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:12:45,534 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:12:55,541 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:13:05,549 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:13:15,556 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:13:25,566 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:13:35,576 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:13:45,584 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:13:55,594 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:14:05,605 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:14:15,615 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:14:25,624 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:14:35,632 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:14:45,642 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:14:55,653 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:15:05,660 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:15:15,668 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:15:25,676 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:15:35,684 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:15:45,692 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:15:55,700 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:16:05,708 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:16:15,718 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:16:25,728 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:16:35,736 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:16:45,744 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:16:55,752 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:17:05,761 INFO updater.py:88 -- NodeUpdater: Waiting for IP of i-0a4c4fcfc2ee6a75b...
2019-02-02 16:17:15,764 INFO log_timer.py:21 -- NodeUpdater: i-0a4c4fcfc2ee6a75b: Got IP [LogTimer=300251ms]
2019-02-02 16:17:15,764 INFO log_timer.py:21 -- NodeUpdater: i-0a4c4fcfc2ee6a75b: Applied config 7d28d7c48d6357f567a59188f2e558932a05ac3f [LogTimer=300251ms]
2019-02-02 16:17:15,764 ERROR updater.py:138 -- NodeUpdater: i-0a4c4fcfc2ee6a75b: Error updating Unable to find IP of node
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/kristian/conda/envs/softlearning/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/kristian/github/hartikainen/ray/python/ray/autoscaler/updater.py", line 141, in run
    raise e
  File "/home/kristian/github/hartikainen/ray/python/ray/autoscaler/updater.py", line 130, in run
    self.do_update()
  File "/home/kristian/github/hartikainen/ray/python/ray/autoscaler/updater.py", line 183, in do_update
    self.set_ssh_ip_if_required()
  File "/home/kristian/github/hartikainen/ray/python/ray/autoscaler/updater.py", line 105, in set_ssh_ip_if_required
    assert ip is not None, "Unable to find IP of node"
AssertionError: Unable to find IP of node
```

**Comment by ericl** [comment] 2019-02-03 00:42
I think the issue is the the underlying semantics of _node() has changed. Before, it only returned cached results if nodes() was called before. However, now it can cache results any time, which results in the head ip getting cached as None.

I believe we can simply revert the _node() to its previous form and things should be fixed: https://github.com/ray-project/ray/commit/315edab08508e7b4ca07ce22467d76dad4031a89#diff-6c1c6ac4425d69b4155cb41c15eeb277R223

I don't think this should give an appreciable slowdown since this only applies to the launch of the head node. Worker nodes will have _node() cached anyways since the autoscaler calls nodes(). @ls-daniel does that sound right?

**Comment by hartikainen** [comment] 2019-02-03 00:52
I actually think that the `_node` behavior is very similar to what it was previously (for the point of view of this regression at least). The reason things didn't fail previously is that we never stored the ips in the ip caches until we actually saw them the first time, whereas now the node might exist but it's ip still be empty, and the cache update only happens based on the node's existence and not when ip is empty.

**Comment by ericl** [comment] 2019-02-03 00:59
I think there's a subtle difference -- now _node() is now "get if cached, otherwise lookup and update cache". Whereas before it was "get if cached, otherwise lookup (don't cache if not found)".

> cache update only happens based on the node's existence and not when ip is empty.

I think this is right. However it's not sufficient to just revert the external ip cache, you also need to revert the behaviour of _node().

So in summary: I think reverting the _node() function and also external_ip() will fix the regression, without any significant downsides I think.

**Closed** 2019-02-04 01:48 UTC
Labels: regression
