### ISSUE TITLE
[tune] AttributeError: 'InMemoryStorage' object has no attribute 'set_trial_value' - Optuna

### ISSUE THREAD

**Issue by turmeric-blend** [ray-project/ray#13622] opened 2021-01-22 03:06 UTC
Brief setup:
```
tuning_objective = 'loss_valid'
suggest = OptunaSearch()
suggest = ConcurrencyLimiter(suggest, max_concurrent=4)
schedule = AsyncHyperBandScheduler() 
reporter = tune.CLIReporter()
parameter_columns=[...]
metric_columns=[...]
for param in parameter_columns:
    reporter.add_parameter_column(param)
for metric in metric_columns:
    reporter.add_metric_column(metric)
analysis = tune.run(runner,
				metric=tuning_objective,
				mode='min',
				search_alg=suggest,
				scheduler=schedule,
				resources_per_trial={'cpu': 1, 'gpu': 1}, 
				num_samples=100, 
				config=config,
				local_dir='./ray_results',
				progress_reporter=reporter,
				keep_checkpoints_num=3,
				checkpoint_score_attr='min-'+str(tuning_objective),
				)
```

This error occurs after the first trial is complete (`done: true`):
> File "/home/user/anaconda3/envs/user/lib/python3.7/site-packages/ray/tune/suggest/optuna.py", line 211, in on_trial_complete
>     self._storage.set_trial_value(ot_trial_id, result.get(
> AttributeError: 'InMemoryStorage' object has no attribute 'set_trial_value'

**Comment by krfricke** [comment] 2021-01-22 09:32
Hi @turmeric-blend, thanks for raising this issue. To work on it we need a full reproducible script, i.e. one I can just copy and paste and then run to reproduce the error. 

Also in this case it would be good to know which Ray version and which Optuna version you're using.

If you provide the information I'm happy to look into this. Thanks!

**Comment by putze** [comment] 2021-01-22 09:40
Hi @krfricke ,

I encountered the same problem as well by just adding to `tune.run` the `sync_config=tune.SyncConfig()` option. Without this option my script runs perfectly well.

I am using optuna==2.4.0 and ray=1.1.0

**Comment by turmeric-blend** [comment] 2021-01-22 09:50
I am also using `optuna==2.4.0 and ray=1.1.0`.

Unfortunately I dont have a minimal reproducible code, but from putze comments it seems it should work with any problem?

**Comment by krfricke** [comment] 2021-01-22 09:58
I see. So Optuna released `2.4.0` just 10 days ago, and this might have introduced some incompatibilities. We'll work on trying to reproduce and fix these. For the meantime, can you try downgrading to `optuna==2.3.0` and see if it works then?

**Comment by putze** [comment] 2021-01-22 10:02
Downgrading worked for me.

**Comment by krfricke** [comment] 2021-01-22 10:04
Good to know, thanks. We'll still try to fix this as soon as possible.

**Comment by krfricke** [comment] 2021-01-22 10:14
Turns out the update breaks our integration because of an API change. The fix was very easy (https://github.com/ray-project/ray/pull/13631). We'll probably merge this later today and the patch will be included in the next nightly wheels and the next ray release.

**Closed** 2021-01-23 08:32 UTC
Labels: P1, bug, needs-repro-script, tune
