### ISSUE TITLE
[Core] Ray 2.1 regression with non-integer resource requests

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#30161] opened 2022-11-09 23:41 UTC
This runs fine on Ray 2.0.1 but throws an exception on Ray 2.1.

```python3
#!/usr/bin/env python3

import ray

# There is no problem if memory=1024.0.
@ray.remote(num_cpus=1, memory=1024.5)
def foo():
    print('bar')

ray.get(foo.remote())
```

Logs:
```
$ ray --version
ray, version 2.0.1
$ ./test
2022-11-09 15:33:49,710 INFO worker.py:1223 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-09 15:33:50,028 INFO worker.py:1333 -- Connecting to existing Ray cluster at address: 172.31.71.84:9031...
2022-11-09 15:33:50,035 INFO worker.py:1509 -- Connected to Ray cluster. View the dashboard at https://console.anyscale-staging.com/api/v2/sessions/ses_5Ze2wrAb8qQBniAUm1B5ezMg/services?redirect_to=dashboard
2022-11-09 15:33:50,058 INFO packaging.py:343 -- Pushing file package 'gcs://_ray_pkg_dd137865a571a922fa8af01b310e6bda.zip' (7.26MiB) to Ray cluster...
2022-11-09 15:33:50,127 INFO packaging.py:352 -- Successfully pushed file package 'gcs://_ray_pkg_dd137865a571a922fa8af01b310e6bda.zip'.
(foo pid=29184) bar


$ ray --version
ray, version 2.1.0
$ ./test
2022-11-09 15:34:57,562 INFO worker.py:1230 -- Using address localhost:9031 set in the environment variable RAY_ADDRESS
2022-11-09 15:34:57,895 INFO worker.py:1342 -- Connecting to existing Ray cluster at address: 172.31.71.84:9031...
2022-11-09 15:34:57,903 INFO worker.py:1519 -- Connected to Ray cluster. View the dashboard at https://console.anyscale-staging.com/api/v2/sessions/ses_5Ze2wrAb8qQBniAUm1B5ezMg/services?redirect_to=dashboard
2022-11-09 15:34:57,928 INFO packaging.py:354 -- Pushing file package 'gcs://_ray_pkg_dd137865a571a922fa8af01b310e6bda.zip' (7.26MiB) to Ray cluster...
2022-11-09 15:34:58,001 INFO packaging.py:367 -- Successfully pushed file package 'gcs://_ray_pkg_dd137865a571a922fa8af01b310e6bda.zip'.
Traceback (most recent call last):
  File "./test", line 9, in <module>
    ray.get(foo.remote())
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/remote_function.py", line 122, in _remote_proxy
    return self._remote(args=args, kwargs=kwargs, **self._default_options)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 307, in _invocation_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/remote_function.py", line 402, in _remote
    return invocation(args, kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/remote_function.py", line 377, in invocation
    object_refs = worker.core_worker.submit_task(
  File "python/ray/_raylet.pyx", line 1787, in ray._raylet.CoreWorker.submit_task
  File "python/ray/_raylet.pyx", line 1788, in ray._raylet.CoreWorker.submit_task
  File "python/ray/_raylet.pyx", line 353, in ray._raylet.prepare_resources
ValueError: Resource quantities >1 must be whole numbers
```

**Comment by cadedaniel** [comment] 2022-11-09 23:42
I'm afraid this is an unintentional breaking change, meaning we need a hotfix. Thoughts? cc @rickyyx @jjyao

**Comment by clarng** [comment] 2022-11-09 23:47
It is because of this PR
https://github.com/clarng/ray/commit/d8dc04c3aa759c9d4d0d1e99b011b9a64cea2166#diff-b2a30c8a16cd3f6c317e6ef2ab25b67a23822f048f56535da2cb7d58713c0a98
but the round up logic is also weird on its own, and float numbers don’t really do the right thing anyway. Are we sure we should revert back to the old round up behavior and not just ask the user to fix their code?

**Comment by jjyao** [comment] 2022-11-10 03:30
Is there any valid case where users want to specify fraction number >1.

**Comment by pcmoritz** [comment] 2022-11-10 03:48
There probably isn't, but this used to work so it is a regression. Since there is no cost to keep supporting it, I think we should do it. We should not break compatibility unless there is a really good reason, especially for core APIs.

**Comment by pcmoritz** [comment] 2022-11-10 03:52
Also supporting both int and float for these kinds of things is quite common in Python, see e.g. `time.sleep` or timeouts in general.

**Comment by clarng** [comment] 2022-11-10 06:09
So for the documented API we have

num_cpus: Union[int, float] = 'Undefined', 
num_gpus: Union[int, float] = 'Undefined', 
resources: Dict[str, float] = 'Undefined',

num_cpus – The quantity of CPU cores to reserve for this task or for the lifetime of the actor.
num_gpus – The quantity of GPUs to reserve for this task or for the lifetime of the actor.
resources (Dict[str, float]) – The quantity of various custom resources to reserve for this task or for the lifetime of the actor. This is a dictionary mapping strings (resource names) to floats.

I think there are several things going on here:
1. we introduced a regression to the public API, namely float no longer works
2. the behavior that the user is relying is not documented and also quite misleading, since it silently rounds up and doesn't honor the user's request (in k8s I can specify fractional cpu, but the same doesn't work in Ray)
3. what is the desired behavior. I don't think the old behavior (round up) is desirable, but maybe it is out of scope of this issue

As part of putting back the old behavior I think we should at least log + document that the resource is getting rounded up and we don't support fractional resources although the API accepts fraction inputs.

**Comment by pcmoritz** [comment] 2022-11-10 09:33
The regression is only for memory, right (where the quantity is indivisible bytes and rounding makes sense)? The other resources have well-defined behavior for fractional values and there should be no regression there.

**Comment by pcmoritz** [comment] 2022-11-10 09:35
Fractional CPUs and GPUs should be working as they used to / are supposed to.

**Comment by clarng** [comment] 2022-11-10 13:45
Yes I confirmed the behavior for non-memory, thanks for correcting! I couldn't verify the behavior where we round down memory request from task, here is my repro script:

```
@remote(num_cpus=0.5, num_gpus=0.5, memory=2000.5, resources={'Custom': 0.5})
def task():
  time.sleep(10)
  return 0

print(ray.__version__)
with ray.init(num_cpus=1, num_gpus=2, _memory=4000.5, resources={'Custom': 2}):
  refs = [task.remote() for _ in range(2)]
  ray.get(refs)
```

If i run this on 2.0.1 I see the round up behavior:

```

======== Autoscaler status: 2022-11-10 05:39:31.294396 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_fca890587601b6011396bb5472b2d48bfc3ff35938e8385b3f3bc43e
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.5/1.0 CPU
 0.5/2.0 Custom
 0.5/2.0 GPU
 0.00/0.000 GiB memory
 0.00/8.015 GiB object_store_memory

Demands:
 {'CPU': 0.5, 'Custom': 0.5, 'GPU': 0.5, 'memory': 2001.0}: 1+ pending tasks/actors
```

If i look at the original [complaint](https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1668029866173439) it seems the user is converting their memory request from gb to bytes for the task, and somehow ended with a fractional value that now fails in 2.1. Is it important to restore the original (round up) behavior or will it suffice to help them cast it to int and just round down by default? Seems the code would be simpler without sacrificing usability if we ensure it won't fail with a float memory input?

**Comment by scv119** [comment] 2022-11-10 21:55
+1 for support float, looks the support is minimal 
+1 for not doing round up if it's only 1 byte of difference.

**Comment by scv119** [comment] 2022-11-10 21:57
(also let's add some tests to ensure we catch future regressions)

**Closed** 2022-11-17 04:06 UTC
Labels: bug, P1, core, Ray 2.2
