### ISSUE TITLE
[RLlib] ZeroDivisionError: integer division or modulo by zero because "batch size" is 0. 

### ISSUE THREAD

**Issue by DarrellDai** [ray-project/ray#30881] opened 2022-12-04 21:25 UTC
### What happened + What you expected to happen

When I'm trying to train a Hide and Seek game with PPO. I set `"train_batch_size"=20` and `"sgd_minibatch_size" = 10`. However, it raise the error as follows
![image](https://user-images.githubusercontent.com/38318509/205515886-73de3788-8894-4957-9eac-c61cf87d98f9.png)
When I use the debugger the check the size of `sample_batch`, the size is `0`. 
![image](https://user-images.githubusercontent.com/38318509/205516103-635b38d1-22de-434b-8cfe-c333db1ee7ad.png)
When I look at the full batch, it's also very different than I set, and it's different between `obs`, `actions`, and `infos`.
![image](https://user-images.githubusercontent.com/38318509/205516039-e2bc7c09-8efe-41f0-997d-3c8716bd77ff.png)

I'm very new to RLlib. Any help will be appreciated.

### Versions / Dependencies

master

### Envrionment
I used to use a multi-agent wrapper. But I just set in this way to simplify the env to single-agent. In my "Hide and Seek" game, every time the hiders gets caught, `done` will be `True`. The observation space is a `3x84x84` box.
```
import gym
import mlagents_envs
from mlagents_envs.environment import UnityEnvironment
from unity_wrappers.envs import MultiUnityWrapper
from gym.spaces.discrete import Discrete
import numpy as np

class HideAndSeek(gym.Env):
    def __init__(self, env_config):
        super().__init__()
        worker_id = env_config["worker_id"]
        file_name = env_config["file_name"]
        while True:
            self.worker_id = worker_id
            try:
                self.unity_env = UnityEnvironment(
                    file_name=file_name,
                    worker_id=worker_id,
                )
            except mlagents_envs.exception.UnityWorkerInUseException as e:
                worker_id += 1
                # Hard limit.
                if worker_id > 100:
                    raise e
            else:
                break
        self.env = MultiUnityWrapper(unity_env=self.unity_env, uint8_visual=True, allow_multiple_obs=True)
        self.agent_id = tuple(self.env.agent_id_to_behaviour_name.keys())[0]
        self.action_shape = self.env.action_space[self.agent_id].nvec
        self.action_space = Discrete(np.prod(self.action_shape))
        self.observation_space = self.env.observation_space[self.agent_id][0]

    def reset(self):
        return self.env.reset()[self.agent_id][0]

    def step(self, action):
        action = np.array(np.unravel_index(action, self.action_shape)) - 1
        (obs_dict, reward_dict, done_dict, info_dict) = self.env.step({self.agent_id: action})
        obs, reward, done = obs_dict[self.agent_id][0], reward_dict[self.agent_id], done_dict[self.agent_id]
        if obs_dict[self.agent_id][1][0] == 0:
            done = True
        return obs, reward, done, {}

```
### Algorithm
```
import ray
from ray.rllib.algorithms import ppo
from ray.tune.logger import pretty_print

from HideAndSeek import HideAndSeek

filename = '/home/darrelldai/UnityProjects/Hide and Seek/Environments/2.0/Env_Linux_Nav_3_Seekers_Big_Rocks_No_Waiting_Time_0/Hide and Seek'
ray.init()
config = ppo.DEFAULT_CONFIG.copy()
config["num_workers"] = 1
config["env_config"] = {"file_name": filename, "worker_id": 0}
config["model"] = {"use_lstm": True, "lstm_cell_size": 256, "max_seq_len": 20,
                   "fcnet_hiddens": [],
                   "conv_filters": [[32, [8, 8], 4], [64, [4, 4], 2], [64, [3, 3], 1],
                                    [512, [7, 7], 1]],
                   }
config["framework"] = "torch"
config["horizon"] = 20
config["exploration_config"] = {"type": "EpsilonGreedy"}
config["batch_mode"] = 'complete_episodes'
config["train_batch_size"] = 20
config["sgd_minibatch_size"] = 10
algo = ppo.PPO(config=config, env=HideAndSeek)
for i in range(3000):
    # Perform one iteration of training the policy with PPO
    result = algo.train()
    print(pretty_print(result))
    if i % 100 == 0:
        checkpoint = algo.save()
        print("checkpoint saved at", checkpoint)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by avnishn** [comment] 2022-12-09 21:30
@sven1977 looks like a problem with the automatic rollout fragment length computation, at a high level

**Comment by sven1977** [comment] 2022-12-12 10:28
Hey @DarrellDai , thanks for posting this issue. I do not think it has anything to do with our recent auto-by-default `rollout_fragment_length` configuration.

Would it be possible to reproduce the error w/o the complicated HideAndSeek env? It's impossible for me to reproduce the bug with this Unity3D-requiring setup. As an alternative, could you use our random env? `ray.rllib.examples.env.random_env::RandomEnv` and set its action- and observation spaces manually via `config["env_config"]["action_space"] =...` and `config["env_config"]["observation_space"]`?

This way, you can mimic the env and should still be able to see the bug.

**Comment by avnishn** [comment] 2023-02-23 18:08
Hey @DarrellDai I wasn't able to reproduce your issue as well. 

I'm going to close this for now, but please re-open if you have a repro script that you can share.

**Closed by avnishn** 2023-02-23 18:08 UTC
Labels: bug, needs-repro-script, P2, rllib
