### ISSUE TITLE
Release test scheduling_test_many_0s_tasks_many_nodes.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#36196] opened 2023-06-08 09:32 UTC
Release test scheduling_test_many_0s_tasks_many_nodes.aws failed.
See https://buildkite.com/ray-project/release-tests-branch/builds/1770#018899d9-338d-423b-af5a-a257666ff385 for more details.
cc @core

	 -- created by ray-test-bot

**Comment by can-anyscale** [comment] 2023-06-08 15:57
Test has been failing for far too long. Jailing.

**Comment by vitsai** [comment] 2023-06-12 23:18
Duplicate of https://github.com/ray-project/ray/issues/33157

**Closed by vitsai** 2023-06-12 23:18 UTC
Labels: bug, P0, release-test

**Comment by can-anyscale** [comment] 2023-06-14 07:56
Test passed on latest run: https://buildkite.com/ray-project/release-tests-branch/builds/1795#0188b885-8a1b-4f4e-8fc6-fff8a5a60a76
