### ISSUE TITLE
[core] dashboard latency regressions 

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#33888] opened 2023-03-29 21:45 UTC
### What happened + What you expected to happen

from : https://github.com/ray-project/ray/pull/33905 
we see latency regression to the dashboard from multiple tests

REGRESSION 1025.43%: dashboard_p95_latency_ms (LATENCY) regresses from 12.292 to 138.338 (1025.43%) in 2.4.0/benchmarks/many_pgs.json
REGRESSION 396.59%: dashboard_p95_latency_ms (LATENCY) regresses from 592.153 to 2940.554 (396.59%) in 2.4.0/benchmarks/many_tasks.json
REGRESSION 171.93%: dashboard_p99_latency_ms (LATENCY) regresses from 1262.576 to 3433.306 (171.93%) in 2.4.0/benchmarks/many_tasks.json
REGRESSION 10.22%: dashboard_p50_latency_ms (LATENCY) regresses from 3.14 to 3.461 (10.22%) in 2.4.0/benchmarks/many_pgs.json
REGRESSION 9.69%: dashboard_p50_latency_ms (LATENCY) regresses from 4.171 to 4.575 (9.69%) in 2.4.0/benchmarks/many_tasks.json
REGRESSION 6.41%: dashboard_p99_latency_ms (LATENCY) regresses from 2693.468 to 2866.012 (6.41%) in 2.4.0/benchmarks/many_actors.json
REGRESSION 0.58%: dashboard_p50_latency_ms (LATENCY) regresses from 3.287 to 3.306 (0.58%) in 2.4.0/benchmarks/many_nodes.json

memory:
dashboard memory went up from 478 to 632 mb since 2.3 (but latency has improved) on latest run : https://buildkite.com/ray-project/release-tests-branch/builds/1493#01872a7e-b35c-4233-bed5-abdb4f721be9

Is this expected @rickyyx @rkooo567 

### Versions / Dependencies

master

### Reproduction script

https://buildkite.com/ray-project/release-tests-branch/builds/1493#01872a7e-b35c-4233-bed5-abdb4f721be9

### Issue Severity

None

**Comment by rkooo567** [comment] 2023-03-31 00:32
will perform bisect today

**Comment by rkooo567** [comment] 2023-03-31 10:50
Hmm regarding latency, actually I found it is slower when V2 stack is used.

The primary difference is this API; 

V2
```
======Print per dashboard endpoint latencies======
=====================P50==========================
{'/': 3.99,
 '/api/cluster_status': 127.086,
 '/api/jobs/': 4.387,
 '/api/prometheus_health': 5.982,
 '/events': 2.913,
 '/log_index': 2.423,
 '/logical/actors': 2.14,
 '/nodes?view=summary': 2.971}
=====================P95==========================
{'/': 20.271,
 '/api/cluster_status': 205.186,
 '/api/jobs/': 16.279,
 '/api/prometheus_health': 6.933,
 '/events': 23.539,
 '/log_index': 2.731,
 '/logical/actors': 6.212,
 '/nodes?view=summary': 22.394}
=====================P99==========================
{'/': 59.912,
 '/api/cluster_status': 363.417,
 '/api/jobs/': 161.837,
 '/api/prometheus_health': 72.462,
 '/events': 196.173,
 '/log_index': 4.012,
 '/logical/actors': 9.047,
 '/nodes?view=summary': 37.933}
=====================Aggregated====================
{'p50': 3.41, 'p95': 139.159, 'p99': 184.434}
```

V1
```
=====================P50==========================
{'/': 3.293,
 '/api/cluster_status': 4.779,
 '/api/jobs/': 3.886,
 '/api/prometheus_health': 2.824,
 '/events': 2.101,
 '/log_index': 2.322,
 '/logical/actors': 2.69,
 '/nodes?view=summary': 3.02}
=====================P95==========================
{'/': 38.297,
 '/api/cluster_status': 10.855,
 '/api/jobs/': 28.621,
 '/api/prometheus_health': 4.301,
 '/events': 2.728,
 '/log_index': 3.309,
 '/logical/actors': 6.821,
 '/nodes?view=summary': 16.378}
=====================P99==========================
{'/': 115.969,
 '/api/cluster_status': 251.178,
 '/api/jobs/': 1330.919,
 '/api/prometheus_health': 42.593,
 '/events': 27.717,
 '/log_index': 120.899,
 '/logical/actors': 27.577,
 '/nodes?view=summary': 45.997}
=====================Aggregated====================
{'p50': 2.977, 'p95': 8.995, 'p99': 120.899}
```

**Comment by rkooo567** [comment] 2023-03-31 10:52
Looks like `/api/cluster_status'` is way slower in V2 stack. @shomilj have we sending much more RPC calls to this API in V2, or there's some setup changed from the autoscaler? (this API goes through autoscaler).

**Comment by rkooo567** [comment] 2023-03-31 10:56
also @clarng have you had a chance to run memory profiler on dashboard for 2.3 vs 2.4?

**Comment by wuisawesome** [comment] 2023-04-04 00:38
> (this API goes through autoscaler).

No it doesn't :p 

https://sourcegraph.com/github.com/ray-project/ray/-/blob/dashboard/modules/reporter/reporter_head.py?L83

**Comment by shomilj** [comment] 2023-04-04 01:19
We're not sending any calls to `/api/cluster_status` from the product codebase on v2, as far as I'm aware of.

**Comment by rkooo567** [comment] 2023-04-04 13:35
Thinking again, I will close this issue. This test was never meant to be written in a way we can correctly record the latency and track. The latency recorded there is simply a tracking purpose if there's unexpected regression. The purpose of the test is just to make sure major dashboard APIs won't take 10s of seconds to load data. I will close this for now, and properly introduce the perf related tests in ray 2.5.

The major APIs 

```
 '/api/jobs/': 161.837,
 '/api/prometheus_health': 72.462,
 '/events': 196.173,
 '/log_index': 4.012,
 '/logical/actors': 9.047,
 '/nodes?view=summary': 37.933}
```
all seems to be in the okay range (I'd expect them to fail if it takes more than something like 5 seconds).

**Closed by rkooo567** 2023-04-04 13:35 UTC
Labels: bug, release-blocker, P0, core, Ray 2.4
