### ISSUE TITLE
[1.10.0 Release] `stress_test_many_tasks` regression

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#21760] opened 2022-01-20 20:19 UTC
Context: https://github.com/ray-project/ray/pull/21512#discussion_r788310272

Result from 1.10.0:
```
"stage_3_creation_time": 0.06580400466918945,
"stage_3_time": 2932.907886981964,
```
 

This is a significant regression from 1.9:
```
"stage_3_creation_time": 0.05767488479614258, 
"stage_3_time": 1949.1530861854553
```

**Comment by architkulkarni** [comment] 2022-01-20 21:22
Assigning @jjyao (Core on-call) for now

**Comment by jjyao** [comment] 2022-01-20 22:03
The regression happens between 11/13 - 11/20

https://buildkite.com/ray-project/periodic-ci/builds/1621#524f9d0e-5d15-497f-962c-0d209ac19c43
https://buildkite.com/ray-project/periodic-ci/builds/1742#78b364bb-8d5a-476f-975f-3df71e222c77

**Comment by zhe-thoughts** [comment] 2022-01-21 06:06
Thanks @jjyao ! Could you help provide an ETA?

**Comment by jjyao** [comment] 2022-01-21 07:13
Based on the bisect result, seems it's ad56b9b432519350323575dc49eae516f2df4dd9.

**Comment by rkooo567** [comment] 2022-01-21 09:03
Note that we only take care of stage_3 time, which measures the actor creation + submission time. creation_time is irrelevant because actor creation is asynchronous (so this doesn't measure anything).

Based on @jjyao's bisect;
```
'_session_url': 'https://beta.anyscale.com/o/anyscale-internal/projects/prj_JS35jSrv5JFxMqSZmQG7Yif7/clusters/ses_9bTQZu1v2uTD4tUaeCMWhJc9', '_commit_url': 'https://s3-us-west-2.amazonaws.com/ray-wheels/master/ad56b9b432519350323575dc49eae516f2df4dd9/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl', '_stable': True}, 'artifacts': {}}
[INFO 2022-01-21 05:14:14,850] e2e.py: 660  Observed the following results:
  stage_3_creation_time = 0.05462050437927246
  stage_3_time = 2724.846255302429





11:14
'_session_url': 'https://beta.anyscale.com/o/anyscale-internal/projects/prj_JS35jSrv5JFxMqSZmQG7Yif7/clusters/ses_MsmZyB6f3ws8E16E3hXJTVtn', '_commit_url': 'https://s3-us-west-2.amazonaws.com/ray-wheels/master/255bdc8fb19382f43989b1aa9df2711bfb44eea0/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl', '_stable': True}, 'artifacts': {}}
[INFO 2022-01-21 03:59:24,735] e2e.py: 660  Observed the following results:

  stage_3_creation_time = 0.05929374694824219
  stage_3_time = 1936.1859912872314
```

According to this, the offending commit is https://github.com/ray-project/ray/commit/ad56b9b432519350323575dc49eae516f2df4dd9.

https://github.com/ray-project/ray/commits/ad56b9b432519350323575dc49eae516f2df4dd9

Looking at PR, I am not sure how the PR can cause regressions in actor startup time. One of possibilities is we are doing some unnecessary serialization / deserialization of protobuf even when runtime env is not used (test doesn't use runtime env). (note this is the test script https://github.com/ray-project/ray/blob/master/release/nightly_tests/stress_tests/test_many_tasks.py).

@SongGuyang @architkulkarni do you guys have any clue how this PR could impact the performance of actor creation?

**Comment by SongGuyang** [comment] 2022-01-21 11:12
I will take a look at this blocking issue!

**Comment by architkulkarni** [comment] 2022-01-21 17:44
I'll also take a look.  Off the top of my head it's probably something like what @rkooo567 is suggesting, where we're inadvertently going through some part of the runtime_env codepath even when the runtime_env is empty.

**Comment by SongGuyang** [comment] 2022-01-21 18:55
I have do a test using `test_many_tasks.py`(change a little to run the stage_3 in a single node) in different commit version.

In master branch(2cd3045b1684c0d9f4ed062788cd7f4adf02a520), the result is 238 seconds:

![image](https://user-images.githubusercontent.com/26714159/150583181-c7aebea1-f8eb-4f43-b6cf-89ad8bdcfa20.png)

In the commit version of https://github.com/ray-project/ray/commit/ad56b9b432519350323575dc49eae516f2df4dd9, the result is 133 seconds:

![image](https://user-images.githubusercontent.com/26714159/150583351-d36813a1-c754-4a10-907d-539eea8870fa.png)

In the commit version which is the previous commit(255bdc8fb19382f43989b1aa9df2711bfb44eea0) of my PR, the result is 140 seconds:

![image](https://user-images.githubusercontent.com/26714159/150583638-41202517-8575-4d9d-9871-a2762ebdcc2c.png)

So, if my test is correct, https://github.com/ray-project/ray/commit/ad56b9b432519350323575dc49eae516f2df4dd9 is not the root cause.

Can you guys do the test in your side?

**Comment by architkulkarni** [comment] 2022-01-21 19:09
> Can you guys do the test in your side?
Thanks for running that test, let me see if I can replicate it on my machine.

**Comment by architkulkarni** [comment] 2022-01-21 20:00
> > Can you guys do the test in your side?
> 
> Thanks for running that test, let me see if I can replicate it on my machine.

I could not replicate it in my local test:
```
master: INFO:__main__:Finished stage 3 in 33.84526467323303 seconds.

ad56b9b: INFO:__main__:Finished stage 3 in 34.01422595977783 seconds.

255bdc8: INFO:__main__:Finished stage 3 in 34.774866819381714 seconds.
```

**Comment by jjyao** [comment] 2022-01-21 20:46
https://github.com/ray-project/ray/pull/21780 Seems that PR did introduce some slowdown.

**Comment by rkooo567** [comment] 2022-01-21 22:06
^ good to know! Maybe we can have a patch for this and unblock it?

**Comment by SongGuyang** [comment] 2022-01-22 01:21
Unbelievable. I think the test in my machine is correct. What's the conclusion now?

**Comment by rkooo567** [comment] 2022-01-22 01:35
The real tests run with 100 machines, so there must be difference from local testing btw

**Comment by rkooo567** [comment] 2022-01-22 01:36
Btw how does it take 1900 seconds in 100 nodes where as 30 seconds for a single local machine?

**Comment by SongGuyang** [comment] 2022-01-22 01:42
> The real tests run with 100 machines, so there must be differences from local testing btw

But In my test, master branch's result is bad. It means the single node test is useful.

**Comment by rkooo567** [comment] 2022-01-22 01:44
It could be useful, but that’s the different workloads (I believe it means the local node scheduling perf has regression). I think we need some perf profiling metrics within scheduler..

**Comment by SongGuyang** [comment] 2022-01-22 01:45
> The real tests run with 100 machines, so there must be differences from local testing btw

Maybe the total task number is different.

**Comment by SongGuyang** [comment] 2022-01-22 02:09
> > > Can you guys do the test in your side?
> > 
> > 
> > Thanks for running that test, let me see if I can replicate it on my machine.
> 
> I could not replicate it in my local test:
> 
> ```
> master: INFO:__main__:Finished stage 3 in 33.84526467323303 seconds.
> 
> ad56b9b: INFO:__main__:Finished stage 3 in 34.01422595977783 seconds.
> 
> 255bdc8: INFO:__main__:Finished stage 3 in 34.774866819381714 seconds.
> ```

What's you test command?
In my side, I started a single node cluster by `ray start --head`, and run the test by `python release/nightly_tests/stress_tests/test_many_tasks.py --num-nodes=0`

And my test main is:
```
if __name__ == "__main__":
    args, unknown = parse_script_args()
    # These numbers need to correspond with the autoscaler config file.
    # The number of remote nodes in the autoscaler should upper bound
    # these because sometimes nodes fail to update.
    num_remote_nodes = args.num_nodes
    num_remote_cpus = 2
    total_num_remote_cpus = 1 * num_remote_cpus
    is_smoke_test = args.smoke_test

    result = {"success": 0}
    # Wait until the expected number of nodes have joined the cluster.
    while True:
        num_nodes = len(ray.nodes())
        logger.info("Waiting for nodes {}/{}".format(num_nodes,
                                                     num_remote_nodes + 1))
        if num_nodes >= num_remote_nodes + 1:
            break
        time.sleep(5)
    logger.info("Nodes have all joined. There are %s resources.",
                ray.cluster_resources())

    # stage_0_time = stage0(smoke=is_smoke_test)
    # logger.info("Finished stage 0 after %s seconds.", stage_0_time)
    # result["stage_0_time"] = stage_0_time

    # stage_1_time, stage_1_iterations = stage1(smoke=is_smoke_test)
    # logger.info("Finished stage 1 after %s seconds.", stage_1_time)
    # result["stage_1_time"] = stage_1_time
    # result["stage_1_avg_iteration_time"] = sum(stage_1_iterations) / len(
    #     stage_1_iterations)
    # result["stage_1_max_iteration_time"] = max(stage_1_iterations)
    # result["stage_1_min_iteration_time"] = min(stage_1_iterations)

    # stage_2_time, stage_2_iterations = stage2(smoke=is_smoke_test)
    # logger.info("Finished stage 2 after %s seconds.", stage_2_time)
    # result["stage_2_time"] = stage_2_time
    # result["stage_2_avg_iteration_time"] = sum(stage_2_iterations) / len(
    #     stage_2_iterations)
    # result["stage_2_max_iteration_time"] = max(stage_2_iterations)
    # result["stage_2_min_iteration_time"] = min(stage_2_iterations)

    stage_3_time, stage_3_creation_time = stage3(
        total_num_remote_cpus, smoke=is_smoke_test)
    logger.info("Finished stage 3 in %s seconds.", stage_3_time)
    result["stage_3_creation_time"] = stage_3_creation_time
    result["stage_3_time"] = stage_3_time

    stage_4_spread = stage4()
    # avg_spread ~ 115 with Ray 1.0 scheduler. ~695 with (buggy) 0.8.7
    # scheduler.
    result["stage_4_spread"] = stage_4_spread
    result["success"] = 1
    print("PASSED.")

    # TODO(rkn): The test below is commented out because it currently
    # does not pass.
    # # Submit a bunch of actor tasks with all-to-all communication.
    # start_time = time.time()
    # logger.info("Submitting actor tasks with all-to-all communication.")
    # x_ids = []
    # for _ in range(50):
    #     for size_exponent in [0, 1, 2, 3, 4, 5, 6]:
    #         x_ids = [a.method.remote(10**size_exponent, *x_ids) for a
    #                  in actors]
    # ray.get(x_ids)
    # logger.info("Finished after %s seconds.", time.time() - start_time)

    with open(os.environ["TEST_OUTPUT_JSON"], "w") as out_put:
        out_put.write(json.dumps(result))
```

**Comment by rkooo567** [comment] 2022-01-22 04:08
I merged the pr. Should we unblock the release and have postmortem for additional bottlenecks? After the patch, we still have about 20% regression

**Comment by zhe-thoughts** [comment] 2022-01-22 20:26
@rkooo567 @jjyao @iycheng @scv119 @ericl : Let's decide on this quickly (whether to block 1.10 release).
- In what scenarios would the 20% regression show up? For all Ray jobs? Or only when the number of tasks is very high?

**Comment by scv119** [comment] 2022-01-24 19:47
To summarize the issue:

- We are paying some runtime env overhead even if it’s empty 
- the logic to decide if runtime env is empty is broken

**Comment by SongGuyang** [comment] 2022-01-25 03:48
Can we add a unit test to replicate the regression? It's so hard to copy your test by 100 nodes in my side.

**Comment by architkulkarni** [comment] 2022-01-26 23:15
> Can we add a unit test to replicate the regression? It's so hard to copy your test by 100 nodes in my side.

I agree it would be great to have this. I'm still not sure why the regression doesn't show up on a single-node test.  I used essentially the same test command as you, and commented out the earlier stages the same way you did

**Closed** 2022-10-27 19:56 UTC
Labels: P1
