### ISSUE TITLE
ray.iter_batches is much slower than torch.dataloader iterable

### ISSUE THREAD

**Issue by yanxiaod123** [ray-project/ray#33325] opened 2023-03-15 10:58 UTC
### What happened + What you expected to happen

I have a ds from memory array, and .iter_batches for batch size=32, I think it's a very quick operation，but It takes about 40 milliseconds.The test code：

arr = np.random.randint(10, size=(1028, 224, 224, 3))
dataset: Dataset  = ray.data.from_numpy(arr)
pipe : DatasetPipeline = dataset.window(blocks_per_window=1)
start_time =  time.time() 
for data in pipe.iter_batches(batch_size=1, batch_format="numpy"):
    print('get data time is ', time.time() - start_time)
    start_time =  time.time() 

### Versions / Dependencies

2.3.0

### Reproduction script

arr = np.random.randint(10, size=(1028, 224, 224, 3))
dataset: Dataset  = ray.data.from_numpy(arr)
pipe : DatasetPipeline = dataset.window(blocks_per_window=1)
start_time =  time.time() 
for data in pipe.iter_batches(batch_size=1, batch_format="numpy"):
    print('get data time is ', time.time() - start_time)
    start_time =  time.time() 

### Issue Severity

None

**Comment by ericl** [comment] 2023-03-15 20:26
What do you get for the following?

```
import ray
import numpy as np
import time

arr = np.random.randint(10, size=(1028, 224, 224, 3))

dataset = ray.data.from_numpy(arr)
pipe = dataset.window(blocks_per_window=1)
start_time = time.time()
for data in pipe.iter_batches(batch_size=1, batch_format="numpy"):
    print('get data time is ', time.time() - start_time)
    start_time = time.time()
print(pipe.stats())
```

It seems to take <1ms per batch when I tried it:
```
get data time is  0.0002980232238769531
get data time is  0.00030422210693359375
get data time is  0.0002999305725097656
get data time is  0.00030517578125
== Pipeline Window 0 ==                                                         
Stage 0 from_numpy_refs: 1/1 blocks executed in 0s
* Remote wall time: 3.4ms min, 3.4ms max, 3.4ms mean, 3.4ms total
* Remote cpu time: 3.43ms min, 3.43ms max, 3.43ms mean, 3.43ms total
* Peak heap memory usage (MiB): 154.04 min, 154.04 max, 154 mean
* Output num rows: 1028 min, 1028 max, 1028 mean, 1028 total
* Output size bytes: 1237946388 min, 1237946388 max, 1237946388 mean, 1237946388 total
* Tasks per node: 1 min, 1 max, 1 mean; 1 nodes used

##### Overall Pipeline Time Breakdown #####

DatasetPipeline iterator time breakdown:
* Waiting for next dataset: 278.05us
* In ray.wait(): 37.36us
* In ray.get(): 553.81us
* In next_batch(): 27.94ms
* In format_batch(): 267.63ms
* In user code: 11.01ms
* Total time: 327.55ms
```

**Comment by yanxiaod123** [comment] 2023-03-16 03:50
> 
your ds.iter_batches batch size=1, you can try batch size=32， and get spend time。

**Comment by yanxiaod123** [comment] 2023-03-16 06:44
> Ah I see, I can reproduce ~40ms with `batch_size=32`. The culprit seems to be an introduced format conversion:
> 
> ```
> * In format_batch(): 132.0ms
> ```
> 
> Perhaps we cannot zero-copy convert from pyarrow to numpy somehow? This is a bit odd since the source format is numpy. cc @c21 @clarkzinzow @amogkam

I understand the underlying Datasets data is “ arrow”，and i browse the document from underlying Datasets “arrow” to numpy is Zero-copy。
<img width="792" alt="image" src="https://user-images.githubusercontent.com/64961652/225536344-e19b0a67-35f8-422e-bfca-42337ad51179.png">

**Comment by ericl** [comment] 2023-03-16 21:24
Here's a flame graph of the driver CPU. It seems we're spending time concatenating arrays, which doesn't appear to be a zero-copy operation:

```
            storage = pa.concat_arrays([c.storage for c in to_concat])
```

![Screenshot from 2023-03-16 14-19-35](https://user-images.githubusercontent.com/14922/225755162-48e1a0cc-50da-40b7-806e-60d6b7cf8638.png)

I checked with @amogkam and this is likely a known issue (https://github.com/ray-project/ray/issues/31108), which is already prioritized. @c21 , shall we close this as a duplicate of that issue / another test case for that issue?

**Comment by c21** [comment] 2023-03-16 21:30
Yeah I think so, @yanxiaod123, let's watch out progress from https://github.com/ray-project/ray/issues/31108. btw we are working on a feature to mitigate the issue. Thanks.

**Closed by c21** 2023-03-16 21:30 UTC
Labels: bug, P1, performance, datasets

**Comment by yanxiaod123** [comment] 2023-04-19 06:43
I use the following codes test, i debug find chunks=1, i think the question is different from [#34352](https://github.com/ray-project/ray/pull/34352), i debug i find dataset.iter_batches slower caused by [https://github.com/ray-project/ray/blob/master/python/ray/air/util/tensor_extensions/arrow.py#L491](https://github.com/ray-project/ray/blob/master/python/ray/air/util/tensor_extensions/arrow.py#L491), pyarrow.concat_arrays is a copy operator due to slower.
`arr = np.random.randint(10, size=(1024, 448, 224, 3))
dataset: Dataset = ray.data.from_numpy(arr)
start_time = time.time()
for data in dataset.iter_batches(batch_size=16, batch_format="numpy"):
    pass
print('process 0 time is ', (time.time() - start_time) / 64)`
