### ISSUE TITLE
[Ray Core] `PlacementGroupResourceManager.__del__` fails when registered as an Actor

### ISSUE THREAD

**Issue by mlguruz** [ray-project/ray#33048] opened 2023-03-05 18:31 UTC
### What happened + What you expected to happen

Registering `PlacementGroupResourceManager` as an actor gives weird deallocation error:

`AttributeError: 'ActorClass(PlacementGroupResourceManager)' object has no attribute '_request_to_staged_pgs'`

...although `_request_to_staged_pgs` is defined in `__init__`.

### Versions / Dependencies

ray == 2.3.0
python == 3.8.10

### Reproduction script

```
from ray.air.execution import FixedResourceManager, PlacementGroupResourceManager
import ray
ray.init('auto')

GLOBAL_RM_NAMESPACE = 'global_resource_manager2'
RM_NAME = 'resource_manager'
RM_SPEC = 'resource_manager_spec'
ray.remote(PlacementGroupResourceManager).options(namespace=GLOBAL_RM_NAMESPACE, name=RM_NAME, lifetime='detached').remote()
```

first run ok. second run will give the error above

### Issue Severity

High: It blocks me from completing my task.

**Comment by justinvyu** [comment] 2023-03-06 23:08
@mlguruz Looks like this is a known issue that's tracked here: https://github.com/ray-project/ray/issues/32952

**Comment by mlguruz** [comment] 2023-03-06 23:11
> @mlguruz Looks like this is a known issue that's tracked here: #32952

ah ok. Will this cause any issues?

**Comment by rickyyx** [comment] 2023-03-06 23:38
@mlguruz thanks for reporting!
Yes, we are aware of this issue- was there any reason that you would want to wrap it in an actor btw? Trying to see if there's any feasible workaround as we working on fixing the `__del__` behaviour of ray actor.

**Comment by mlguruz** [comment] 2023-03-06 23:41
> @mlguruz thanks for reporting!
> 
> Yes, we are aware of this issue- was there any reason that you would want to wrap it in an actor btw? Trying to see if there's any feasible workaround as we working on fixing the `__del__` behaviour of ray actor. 

For sure! I'm creating resource manager as an actor so that it's shared and I would delegate any resource mgmt logics to that single "global" manager.

**Comment by rickyyx** [comment] 2023-03-07 17:55
@mlguruz thanks! 

I think the linked discuss io issue might be a different one with PlacementGroupResourceManager. 

For this `__del__` problem, the current behaviour of defining a `__del__` on an actor class has a bug, and we will try to fix it by the next release. So I guess before that, you might have to just use `PlacementGroupResourceManager` as a normal python class, and might have to pass resource around as arguments. (might not be the best solution since I apparently don't know much about the usecase)

**Comment by mlguruz** [comment] 2023-03-09 13:37
Also, I've been experiencing the following error:
```
RayTaskError(KeyError): ray::PlacementGroupResourceManager.free_resources() (pid=270823, ip=10.19.199.11, repr=<ray.air.execution.resources.placement_group.PlacementGroupResourceManager object at 0x7fd87613ea90>)
  File "XXXXXX/envs/4a2dc35611fbe1c7ebfa224ac7f50c47643f4c04/lib/python3.8/site-packages/ray/air/execution/resources/placement_group.py", line 188, in free_resources
    self._acquired_pgs.remove(pg)
KeyError: <ray.util.placement_group.PlacementGroup object at 0x7fd840655af0>
```
...when using `PlacementGroupResourceManager` as an actor.

**Comment by krfricke** [comment] 2023-03-10 19:17
For the `KeyError`, it would be great to get a reproducible example. I'll close this issue as a duplicate of #32952 - let's continue the KeyError discussion either on discourse or in a separate issue!

**Closed by krfricke** 2023-03-10 19:17 UTC
Labels: bug, P1, core
