### ISSUE TITLE
'APEX_DDPG' doesn't work when there are less than 5 CPUs on a head node

### ISSUE THREAD

**Issue by Rendok** [ray-project/ray#3072] opened 2018-10-17 06:22 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Deep Learning AMI (Ubuntu) Version 16.0
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5.2
- **Python version**: 3.6.5
- **Exact command to reproduce**: None (freeze)

### Describe the problem
I cannot start 'APEX_DDPG' via Tune on p2.xlarge (head) + m5.12xlarge (worker), but it works on g3.4xlarge (head) + m5.12xlarge (worker). Terminal just freezes. I think the problem is in initialization. That is, p2.xlarge has 4 CPUs, g3.4xlarge has 16 CPUs, though APEX requires at least 5 to start (and all have to be on a head node).

### Source code / logs
None

**Comment by ericl** [comment] 2018-10-17 08:09
Thanks for reporting the hang, that's definitely not supposed to happen.

Note that you can lower the head node requirements by reducing the number of replay buffer shards: https://github.com/ray-project/ray/blob/a9e454f6fdaa4dca2cb27e748805953f8721c6f4/python/ray/rllib/agents/ddpg/apex.py#L16

**Comment by ericl** [comment] 2018-11-09 07:50
I think this is actually fixed in master, where the resource request is now 1 CPU only. Can you try this out to confirm?

**Comment by Rendok** [comment] 2018-11-11 09:55
Yes, it works in the last wheel. Thanks.

But
```
ray exec create-cluster.yaml 'tail -n 100 -f /tmp/raylogs/monitor-*'
```
doesn't work anymore though.

**Comment by ericl** [comment] 2018-11-11 19:48
/tmp/raylogs got renamed to /tmp/ray is the only thing I think.

**Comment by Rendok** [comment] 2018-11-13 07:57
Then you probably forgot to change the info in ```ray up *.yaml```

**Comment by ericl** [comment] 2018-11-20 20:09
Ah, also ran into this recently and I think the issue is a version mismatch between the locally installed Ray and the one you are deploying via ray up.

**Closed by ericl** 2018-11-20 20:09 UTC
Labels: bug
