### ISSUE TITLE
sparse_softmax_cross_entropy_with_logits Should Be "tf.nn.softmax_cross_entropy_with_logits()"

### ISSUE THREAD

**Issue by DenysAshikhin** [ray-project/ray#15676] opened 2021-05-07 03:37 UTC
### What is the problem?

When using PPO with Curiosity exploration in conjunction with a fully discrete obs/action space external environment I get the error below. However, this issue seems like it is a mix-up due to exploration or fully discreten external environment, as per multiple sources (https://stackoverflow.com/questions/58398491/valueerror-shape-mismatch-the-shape-of-labels-received-15-should-equal-th and https://datascience.stackexchange.com/questions/22456/how-can-i-solve-label-shape-problem-in-tensorflow-when-using-one-hot-encoding) it seems like `sparse_softmax_cross_entropy_with_logits` is called when instead `tf.nn.softmax_cross_entropy_with_logits()`  should be. 
```
Traceback (most recent call last):
  File "policy_server.py", line 187, in <module>
    trainer = PPOTrainer(config=DEFAULT_CONFIG, env=UnderlordEnv)
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\agents\trainer_template.py", line 121, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\agents\trainer.py", line 516, in __init__
    super().__init__(config, logger_creator)
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\tune\trainable.py", line 98, in __init__
    self.setup(copy.deepcopy(self.config))
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\agents\trainer.py", line 707, in setup
    self._init(self.config, self.env_creator)
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\agents\trainer_template.py", line 148, in _init
    self.workers = self._make_workers(
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\agents\trainer.py", line 783, in _make_workers
    return WorkerSet(
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 90, in __init__
    self._local_worker = self._make_worker(
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 317, in _make_worker
    worker = cls(
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 516, in __init__
    self.policy_map, self.preprocessors = self._build_policy_map(
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 1155, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\policy\eager_tf_policy.py", line 106, in __init__
    super(TracedEagerPolicy, self).__init__(*args, **kwargs)
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\policy\eager_tf_policy.py", line 306, in __init__
    self._initialize_loss_from_dummy_batch(
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\policy\policy.py", line 630, in _initialize_loss_from_dummy_batch
    self.exploration.postprocess_trajectory(self, self._dummy_batch)
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\utils\exploration\curiosity.py", line 234, in postprocess_trajectory
    self._postprocess_tf(policy, sample_batch, tf_sess)
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\utils\exploration\curiosity.py", line 251, in _postprocess_tf
    forward_l2_norm_sqared, _ = self._postprocess_helper_tf(
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\utils\exploration\curiosity.py", line 293, in _postprocess_helper_tf
    inverse_loss = -action_dist.logp(actions)
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\models\tf\tf_action_dist.py", line 128, in logp
    [cat.logp(act) for cat, act in zip(self.cats, actions)])
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\models\tf\tf_action_dist.py", line 128, in <listcomp>
    [cat.logp(act) for cat, act in zip(self.cats, actions)])
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\models\tf\tf_action_dist.py", line 70, in logp
    return -tf.nn.sparse_softmax_cross_entropy_with_logits(
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\util\dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 4347, in sparse_softmax_cross_entropy_with_logits_v2
    return sparse_softmax_cross_entropy_with_logits(
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\util\dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 4252, in sparse_softmax_cross_entropy_with_logits
    raise ValueError("Shape mismatch: The shape of labels (received %s) "
ValueError: Shape mismatch: The shape of labels (received (4,)) should equal the shape of logits except for the last dimension (received (32, 9)).
````

*Ray version and other system information (Python version, TensorFlow version, OS):*

OS: Windows 10
https://pastebin.com/3XKt911M

### Reproduction (REQUIRED)

```
DEFAULT_CONFIG = with_common_config({
    # Should use a critic as a baseline (otherwise don't use value baseline;
    # required for using GAE).
    "use_critic": True,
    # If true, use the Generalized Advantage Estimator (GAE)
    # with a value function, see https://arxiv.org/pdf/1506.02438.pdf.
    "use_gae": True,
    # The GAE (lambda) parameter.
    "lambda": 1.0,
    # Initial coefficient for KL divergence.
    "kl_coeff": 0.2,
    # Size of batches collected from each worker.
    "rollout_fragment_length": 25,
    # Number of timesteps collected for each SGD round. This defines the size
    # of each SGD epoch.
    "train_batch_size": 1000,
    # Total SGD batch size across all devices for SGD. This defines the
    # minibatch size within each epoch.
    "sgd_minibatch_size": 250,
    # Number of SGD iterations in each outer loop (i.e., number of epochs to
    # execute per train batch).
    "num_sgd_iter": 50,
    # Whether to shuffle sequences in the batch when training (recommended).
    "shuffle_sequences": True,
    # Stepsize of SGD.
    "lr": 5e-5,
    # Learning rate schedule.
    "lr_schedule": None,
    # Coefficient of the value function loss. IMPORTANT: you must tune this if
    # you set vf_share_layers=True inside your model's config.
    "vf_loss_coeff": 1.0,
    "model": {
        # Share layers for value function. If you set this to True, it's
        # important to tune vf_loss_coeff.
        "vf_share_layers": False,
        "use_lstm": True
    },
    # Coefficient of the entropy regularizer.
    "entropy_coeff": 0.0,
    # Decay schedule for the entropy regularizer.
    "entropy_coeff_schedule": None,
    # PPO clip parameter.
    "clip_param": 0.3,
    # Clip param for the value function. Note that this is sensitive to the
    # scale of the rewards. If your expected V is large, increase this.
    "vf_clip_param": 4000000.0,
    # If specified, clip the global norm of gradients by this amount.
    "grad_clip": None,
    # Target value for KL divergence.
    "kl_target": 0.01,
    # Whether to rollout "complete_episodes" or "truncate_episodes".
    "batch_mode": "truncate_episodes",
    # Which observation filter to apply to the observation.
    "observation_filter": "NoFilter",
    # Uses the sync samples optimizer instead of the multi-gpu one. This is
    # usually slower, but you might want to try it if you run into issues with
    # the default optimizer.
    "simple_optimizer": False,
    # Whether to fake GPUs (using CPUs).
    # Set this to True for debugging on non-GPU machines (set `num_gpus` > 0).
    "_fake_gpus": False,
    "num_gpus": 1,
    # Use the connector server to generate experiences.
    "input": (
        lambda ioctx: PolicyServerInput(ioctx, args.ip, 55555)
    ),
    # Use a single worker process to run the server.
    "num_workers": 0,
    # Disable OPE, since the rollouts are coming from online clients.
    "input_evaluation": [],
    # "callbacks": MyCallbacks,
    "env_config": {"sleep": True, "framework": 'tf'},
    "framework": "tfe",
    "eager_tracing": True,
    "explore": True,
    "exploration_config": {
        "type": "Curiosity",  # <- Use the Curiosity module for exploring.
        "eta": 1.0,  # Weight for intrinsic rewards before being added to extrinsic ones.
        "lr": 0.001,  # Learning rate of the curiosity (ICM) module.
        "feature_dim": 288,  # Dimensionality of the generated feature vectors.
        # Setup of the feature net (used to encode observations into feature (latent) vectors).
        "feature_net_config": {
            "fcnet_hiddens": [],
            "fcnet_activation": "relu",
        },
        "inverse_net_hiddens": [256],  # Hidden layers of the "inverse" model.
        "inverse_net_activation": "relu",  # Activation of the "inverse" model.
        "forward_net_hiddens": [256],  # Hidden layers of the "forward" model.
        "forward_net_activation": "relu",  # Activation of the "forward" model.
        "beta": 0.2,  # Weight for the "forward" loss (beta) over the "inverse" loss (1.0 - beta).
        # Specify, which exploration sub-type to use (usually, the algo's "default"
        # exploration, e.g. EpsilonGreedy for DQN, StochasticSampling for PG/SAC).
        "sub_exploration": {
            "type": "StochasticSampling",
        }
    }
})

# DEFAULT_CONFIG["num_workers"] = 1
# DEFAULT_CONFIG['env'] = UnderlordEnv
# DEFAULT_CONFIG['create_env_on_driver'] = True
# DEFAULT_CONFIG["input"] = lambda ioctx: PolicyServerInput(ioctx, 'localhost', 55555)
# print(DEFAULT_CONFIG)

ray.init(num_gpus=1)

print(f"running on: {args.ip}:55555")

trainer = PPOTrainer(config=DEFAULT_CONFIG, env=UnderlordEnv)

# Serving and training loop.
i = 0
while True:
    print(pretty_print(trainer.train()))
    print(f"Finished train run #{i + 1}")
    i += 1
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

[Yes] I have verified my script runs in a clean environment and reproduces the issue.
[Latest wheel fails to install saying it is unsupported on my system] I have verified the issue also occurs with the latest wheels.

**Comment by mvindiola1** [comment] 2021-05-07 13:40
Update: It also worked for me with ray.rllib.examples.env.random_env.RandomEnv which has both Discrete observation and action spaces.

**Comment by DenysAshikhin** [comment] 2021-05-07 17:58
@mvindiola1 So running your code it seems to work which then leaves me to question what exactly could be the issue with my code?

I know it works 100% the Underlords External Env + PPOTrainer + framework='tf'. And only throws the above mentioned error when using 'tfe'.

```
self.observation_space = spaces.Tuple(
            (spaces.Discrete(9),  # final position * (if not 0 means game is over!)
             spaces.Discrete(101),  # health *
             spaces.Discrete(100),  # gold
             spaces.Discrete(11),  # level *
             spaces.Discrete(99),  # remaining EXP to level up
             spaces.Discrete(50),  # round
             spaces.Discrete(2),  # locked in
             spaces.Discrete(6),  # gamePhase *
             spaces.MultiDiscrete([250, 3]),  # heroToMove: heroLocalID, isUnderlord
             spaces.Discrete(250),  # itemToMove: localID*,
             spaces.Discrete(3),  # reRoll cost
             spaces.Discrete(2),  # rerolled (item)
             spaces.Discrete(35),  # current round timer
             # below are the store heros
             spaces.MultiDiscrete([71, 71, 71, 71, 71]),
             # below are the bench heroes
             spaces.MultiDiscrete([71, 250, 4, 6, 14, 9, 9, 3]), spaces.MultiDiscrete([71, 250, 4, 6, 14, 9, 9, 3]),
             spaces.MultiDiscrete([71, 250, 4, 6, 14, 9, 9, 3]), spaces.MultiDiscrete([71, 250, 4, 6, 14, 9, 9, 3]),
             spaces.MultiDiscrete([71, 250, 4, 6, 14, 9, 9, 3]), spaces.MultiDiscrete([71, 250, 4, 6, 14, 9, 9, 3]),
             spaces.MultiDiscrete([71, 250, 4, 6, 14, 9, 9, 3]), spaces.MultiDiscrete([71, 250, 4, 6, 14, 9, 9, 3]),
             # below are the board heros
             spaces.MultiDiscrete([71, 14, 4, 6, 250, 9, 9, 3]), spaces.MultiDiscrete([71, 14, 4, 6, 250, 9, 9, 3]),
             spaces.MultiDiscrete([71, 14, 4, 6, 250, 9, 9, 3]), spaces.MultiDiscrete([71, 14, 4, 6, 250, 9, 9, 3]),
             spaces.MultiDiscrete([71, 14, 4, 6, 250, 9, 9, 3]), spaces.MultiDiscrete([71, 14, 4, 6, 250, 9, 9, 3]),
             spaces.MultiDiscrete([71, 14, 4, 6, 250, 9, 9, 3]), spaces.MultiDiscrete([71, 14, 4, 6, 250, 9, 9, 3]),
             spaces.MultiDiscrete([71, 14, 4, 6, 250, 9, 9, 3]), spaces.MultiDiscrete([71, 14, 4, 6, 250, 9, 9, 3]),
             # below are underlords to pick (whenever valid) -> underlord ID - specialty
             spaces.MultiDiscrete([5, 3, 5, 3, 5, 3, 5, 3]),
             # below are the items
             spaces.MultiDiscrete([70, 14, 250, 4, 5]), spaces.MultiDiscrete([70, 14, 250, 4, 5]),
             spaces.MultiDiscrete([70, 14, 250, 4, 5]), spaces.MultiDiscrete([70, 14, 250, 4, 5]),
             spaces.MultiDiscrete([70, 14, 250, 4, 5]), spaces.MultiDiscrete([70, 14, 250, 4, 5]),
             spaces.MultiDiscrete([70, 14, 250, 4, 5]), spaces.MultiDiscrete([70, 14, 250, 4, 5]),
             spaces.MultiDiscrete([70, 14, 250, 4, 5]), spaces.MultiDiscrete([70, 14, 250, 4, 5]),
             spaces.MultiDiscrete([70, 14, 250, 4, 5]), spaces.MultiDiscrete([70, 14, 250, 4, 5]),
             # below are the items to pick from
             spaces.MultiDiscrete([70, 70, 70]),
             # below are dicts of other players: slot, health, gold, level, boardUnits (ID, Tier)
             spaces.MultiDiscrete(
                 [9, 101, 100, 11, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4]),
             spaces.MultiDiscrete(
                 [9, 101, 100, 11, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4]),
             spaces.MultiDiscrete(
                 [9, 101, 100, 11, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4]),
             spaces.MultiDiscrete(
                 [9, 101, 100, 11, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4]),
             spaces.MultiDiscrete(
                 [9, 101, 100, 11, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4]),
             spaces.MultiDiscrete(
                 [9, 101, 100, 11, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4]),
             spaces.MultiDiscrete(
                 [9, 101, 100, 11, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4])

             ))

        self.action_space = spaces.MultiDiscrete(
            [  # 0=reroll, 1 = lock in, 2 = level up, 3 = buy unit from store, 4 = sell unit, 5 = choose item,
                # 6 = choose underlord, 7 = move Unit, 8 = move Item
                9,
                9,  # x-cordinate *
                9,  # y-cordinate *
                4,  # selection -> used only when having to choose an item or underlord
            ]
        )
````

Above is my action/observation space - maybe that will help explain the error?

**Comment by mvindiola1** [comment] 2021-05-07 19:28
It is being caused by the action space but I am not sure why yet. The example below will run but if you uncomment the action space line it will break.

```python
ray.init(local_mode=True)
from ray.rllib.examples.env.random_env import RandomEnv
from gym import spaces
DEFAULT_CONFIG["env_config"]["observation_space"] = spaces.Tuple(
    (spaces.Discrete(9),  # final position * (if not 0 means game is over!)
     spaces.Discrete(101),  # health *
     spaces.Discrete(100),  # gold
     spaces.Discrete(11),  # level *
     spaces.Discrete(99),  # remaining EXP to level up
     spaces.Discrete(50),  # round
     spaces.Discrete(2),  # locked in
     spaces.Discrete(6),  # gamePhase *
     spaces.MultiDiscrete([250, 3]),  # heroToMove: heroLocalID, isUnderlord
     spaces.Discrete(250),  # itemToMove: localID*,
     spaces.Discrete(3),  # reRoll cost
     spaces.Discrete(2),  # rerolled (item)
     spaces.Discrete(35),  # current round timer
     # below are the store heros
     spaces.MultiDiscrete([71, 71, 71, 71, 71]),
     # below are the bench heroes
     spaces.MultiDiscrete([71, 250, 4, 6, 14, 9, 9, 3]), spaces.MultiDiscrete([71, 250, 4, 6, 14, 9, 9, 3]),
     spaces.MultiDiscrete([71, 250, 4, 6, 14, 9, 9, 3]), spaces.MultiDiscrete([71, 250, 4, 6, 14, 9, 9, 3]),
     spaces.MultiDiscrete([71, 250, 4, 6, 14, 9, 9, 3]), spaces.MultiDiscrete([71, 250, 4, 6, 14, 9, 9, 3]),
     spaces.MultiDiscrete([71, 250, 4, 6, 14, 9, 9, 3]), spaces.MultiDiscrete([71, 250, 4, 6, 14, 9, 9, 3]),
     # below are the board heros
     spaces.MultiDiscrete([71, 14, 4, 6, 250, 9, 9, 3]), spaces.MultiDiscrete([71, 14, 4, 6, 250, 9, 9, 3]),
     spaces.MultiDiscrete([71, 14, 4, 6, 250, 9, 9, 3]), spaces.MultiDiscrete([71, 14, 4, 6, 250, 9, 9, 3]),
     spaces.MultiDiscrete([71, 14, 4, 6, 250, 9, 9, 3]), spaces.MultiDiscrete([71, 14, 4, 6, 250, 9, 9, 3]),
     spaces.MultiDiscrete([71, 14, 4, 6, 250, 9, 9, 3]), spaces.MultiDiscrete([71, 14, 4, 6, 250, 9, 9, 3]),
     spaces.MultiDiscrete([71, 14, 4, 6, 250, 9, 9, 3]), spaces.MultiDiscrete([71, 14, 4, 6, 250, 9, 9, 3]),
     # below are underlords to pick (whenever valid) -> underlord ID - specialty
     spaces.MultiDiscrete([5, 3, 5, 3, 5, 3, 5, 3]),
     # below are the items
     spaces.MultiDiscrete([70, 14, 250, 4, 5]), spaces.MultiDiscrete([70, 14, 250, 4, 5]),
     spaces.MultiDiscrete([70, 14, 250, 4, 5]), spaces.MultiDiscrete([70, 14, 250, 4, 5]),
     spaces.MultiDiscrete([70, 14, 250, 4, 5]), spaces.MultiDiscrete([70, 14, 250, 4, 5]),
     spaces.MultiDiscrete([70, 14, 250, 4, 5]), spaces.MultiDiscrete([70, 14, 250, 4, 5]),
     spaces.MultiDiscrete([70, 14, 250, 4, 5]), spaces.MultiDiscrete([70, 14, 250, 4, 5]),
     spaces.MultiDiscrete([70, 14, 250, 4, 5]), spaces.MultiDiscrete([70, 14, 250, 4, 5]),
     # below are the items to pick from
     spaces.MultiDiscrete([70, 70, 70]),
     # below are dicts of other players: slot, health, gold, level, boardUnits (ID, Tier)
     spaces.MultiDiscrete(
         [9, 101, 100, 11, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4]),
     spaces.MultiDiscrete(
         [9, 101, 100, 11, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4]),
     spaces.MultiDiscrete(
         [9, 101, 100, 11, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4]),
     spaces.MultiDiscrete(
         [9, 101, 100, 11, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4]),
     spaces.MultiDiscrete(
         [9, 101, 100, 11, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4]),
     spaces.MultiDiscrete(
         [9, 101, 100, 11, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4]),
     spaces.MultiDiscrete(
         [9, 101, 100, 11, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4, 71, 4])

     ))
#DEFAULT_CONFIG["env_config"]["action_space"] = spaces.MultiDiscrete([9,9,9,4])
trainer = PPOTrainer(config=DEFAULT_CONFIG, env=RandomEnv)

# Serving and training loop.
for i in range(10):
    print(pretty_print(trainer.train()))
    print(f"Finished train run #{i + 1}")
```

**Comment by DenysAshikhin** [comment] 2021-05-08 03:46
That's super strange...
I tried setting the action space to tuples:
```
DEFAULT_CONFIG["env_config"]["action_space"] = spaces.Tuple((spaces.Discrete(9), spaces.Discrete(9), spaces.Discrete(9), spaces.Discrete(4)))
```
But then it throws: `ValueError: Only (Multi)Discrete action spaces supported for Curiosity so far!`
So it's not that....
Furthermore, simply setting: 
```
DEFAULT_CONFIG["env_config"]["action_space"] = spaces.MultiDiscrete([9])
```
Which also errored out.....` raise ValueError("Shape mismatch: The shape of labels (received %s) "
ValueError: Shape mismatch: The shape of labels (received (1,)) should equal the shape of logits except for the last dimension (received (32, 9)).`

But ```
DEFAULT_CONFIG["env_config"]["action_space"] = spaces.Discrete(9)
```
Starts up fine. So this seems like some sort of bug in the Curiosity implementation handling the MultiDiscrete (action/observation) space?

**Comment by mvindiola1** [comment] 2021-05-08 12:39
@DenysAshikhin,

I found the error here: https://github.com/ray-project/ray/blob/996a002b00356d66c2feb071cef9e1a1f0b3f0e7/rllib/models/tf/tf_action_dist.py#L138-L141

actions type is different between tf1 and tf2.
In tf1 it always comes in as a tf tensor and so is split into a list of tensors for each category
In tf2 it sometimes comes in as an numpy array and in that case is not split into a list of categories.

There is probably a cleaner way to do this but as quick fix you could modify the logp method to look like this:
```python
    @override(ActionDistribution)
    def logp(self, actions: TensorType) -> TensorType:
        # If tensor is provided, unstack it into list.
        if isinstance(actions, tf.Tensor):
            if isinstance(self.action_space, gym.spaces.Box):
                actions = tf.reshape(
                    actions, [-1, int(np.product(self.action_space.shape))])
            actions = tf.unstack(tf.cast(actions, tf.int32), axis=1)
        if isinstance(actions, np.ndarray):
            actions = actions.astype(np.int32)
            actions = [np.take(actions, i, axis = -1) for i in range(actions.shape[-1])]
        logps = tf.stack(
            [cat.logp(act) for cat, act in zip(self.cats, actions)])
        return tf.reduce_sum(logps, axis=0)
```

**Comment by DenysAshikhin** [comment] 2021-05-08 21:31
So I tried your fix, however, I now run into the following error:

```
ntended to be used by Functional model.
Traceback (most recent call last):
  File "hope.py", line 154, in <module>
    trainer = PPOTrainer(config=DEFAULT_CONFIG, env=RandomEnv)
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\agents\trainer_template.py", line 121, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\agents\trainer.py", line 516, in __init__
    super().__init__(config, logger_creator)
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\tune\trainable.py", line 98, in __init__
    self.setup(copy.deepcopy(self.config))
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\agents\trainer.py", line 707, in setup
    self._init(self.config, self.env_creator)
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\agents\trainer_template.py", line 148, in _init
    self.workers = self._make_workers(
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\agents\trainer.py", line 783, in _make_workers
    return WorkerSet(
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 90, in __init__
    self._local_worker = self._make_worker(
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 317, in _make_worker
    worker = cls(
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 516, in __init__
    self.policy_map, self.preprocessors = self._build_policy_map(
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 1155, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\policy\eager_tf_policy.py", line 306, in __init__
    self._initialize_loss_from_dummy_batch(
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\policy\policy.py", line 619, in _initialize_loss_from_dummy_batch
    self.compute_actions_from_input_dict(input_dict, explore=False)
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\policy\eager_tf_policy.py", line 439, in compute_actions_from_input_dict
    return self._compute_action_helper(input_dict, state_batches, None,
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\utils\threading.py", line 21, in wrapper
    return func(self, *a, **k)
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\policy\eager_tf_policy.py", line 72, in _func
    return func(*args, **kwargs)
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\policy\eager_tf_policy.py", line 80, in _func
    out = func(*args, **kwargs)
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\policy\eager_tf_policy.py", line 514, in _compute_action_helper
    actions, logp = self.exploration.get_exploration_action(
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\utils\exploration\curiosity.py", line 175, in get_exploration_action
    return self.exploration_submodule.get_exploration_action(
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\utils\exploration\stochastic_sampling.py", line 72, in get_exploration_action
    return self._get_tf_exploration_action_op(action_distribution,
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\utils\exploration\stochastic_sampling.py", line 86, in _get_tf_exploration_action_op
    deterministic_actions = action_dist.deterministic_sample()
  File "C:\Users\ashyk\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\rllib\models\action_dist.py", line 44, in deterministic_sample
    raise NotImplementedError
NotImplementedError
```

**Comment by mvindiola1** [comment] 2021-05-08 21:36
@DenysAshikhin,
I did not encounter this error in the 10 iterations I ran. 
Do you have `explore = False` somewhere?  Maybe during evaluation?

**Comment by DenysAshikhin** [comment] 2021-05-08 22:01
So I managed to fix it by adding:

```
    @override(ActionDistribution)
    def logp(self, actions: TensorType) -> TensorType:
        # If tensor is provided, unstack it into list.
        if isinstance(actions, tf.Tensor):
            if isinstance(self.model.action_space, gym.spaces.Box):
                actions = tf.reshape(
                    actions, [-1, int(np.product(self.model.action_space.shape))])
            actions = tf.unstack(tf.cast(actions, tf.int32), axis=1)
        if isinstance(actions, np.ndarray):
            actions = actions.astype(np.int32)
            if isinstance(self.model.action_space, gym.spaces.Box):
                actions = np.reshape(
                    actions, [-1, int(np.product(self.action_space.shape))])
            actions = [
                np.take(actions, i, axis=-1) for i in range(actions.shape[-1])
            ]
        logps = tf.stack(
            [cat.logp(act) for cat, act in zip(self.cats, actions)])
        return tf.reduce_sum(logps, axis=0)
```
It was missing a `self.`

**Comment by mvindiola1** [comment] 2021-05-08 22:12
@DenysAshikhin which version of ray are you using?  I will take a look tonight at what you need for your version.

**Comment by DenysAshikhin** [comment] 2021-05-08 22:50
I am using the version that comes when you do `pip install ray`. This gives the 1.3.0 
I try to install the latest wheel but I get the error: `ERROR: ray-2.0.0.dev0-cp38-cp38-win_amd64 (3).whl is not a supported wheel on this platform.`

**Comment by mvindiola1** [comment] 2021-05-09 00:37
No problem. I am happy to help and intrigued by what you are trying to do. Seems like a complicated but cool environment. 

It turns out there is a way simpler fix to the issue. the source of the issue is actually in the curiosity exploration class. It is passing in the actions as a numpy array. In tf1 that gets converted to a tf tensor but in tf2/tfe it does not. This fix should do the trick.

Change line 293 from:

https://github.com/ray-project/ray/blob/0dfd43c61be902b8d9cbac2a05a751bac3dcc993/rllib/utils/exploration/curiosity.py#L291-L295

to

`inverse_loss = -action_dist.logp(tf.convert_to_tensor(actions))`

**Comment by DenysAshikhin** [comment] 2021-05-09 02:11
Thank you so much! That did finally get TFE + EAGER mode working. Since you mentioned being interested in what I am working on, you can add me on Discord and I can share status updates/progress (the AI is currently in the initial stages of training): The Last Spark#7586

That being said I think that's the fix for this. Not sure what I need to do? I could close the issue... if that's the right move

**Comment by mvindiola1** [comment] 2021-05-09 02:18
Glad it that it didn't the first time. We found a much simpler fix. I will reach out on discord.

Leave the issue open that way the reviewer has context for the PR. It will autoclose when the pull request is merged.

**Closed** 2021-06-21 17:03 UTC
Labels: bug, rllib, triage
