### ISSUE TITLE
[RLLib] DefaultCallbacks returning an empty policy dictionary 

### ISSUE THREAD

**Issue by Capiru** [ray-project/ray#30394] opened 2022-11-17 07:34 UTC
### What happened + What you expected to happen

When tried to interact with policies within the DefaultCallbacks, I noticed that all policies are returned as an empty dictionary, including when tried to access from the worker's attributes.

What should be happening is: returning a dict: {"id_0": PolicyClass, "id_1": PolicyClass} for multi policy optimization and {"default" : PolicyClass} for single policy optimization.

### Versions / Dependencies

Tested on ray 2.1.0 and the 3.0.0 nightly build

### Reproduction script

Include a print(policies) in any of the on_episode_start, on_episode_step and on_episode_end and it prints an empty dictionary of the AlphaZeroDefaultCallbacks

### Issue Severity

High: It blocks me from completing my task.

**Comment by sven1977** [comment] 2022-12-14 14:12
Hey @Capiru , I cannot reproduce your issue. For example, when running the rllib/algorithms/alpha_zero/tests/test_alpha_zero.py tests and adding the printout, I do see the correct dict being passed in.

```
{'default_policy': AlphaZeroPolicyWrapperClass}
```

**Comment by sven1977** [comment] 2022-12-14 14:12
Could you post an actual repro script with config and everything that would show this behavior?

**Comment by sven1977** [comment] 2022-12-14 14:15
Aah! I know what it is :)

So the `policies` arg is supposed to be the PolicyMap object from the respective RolloutWorker, on which the callback gets called. However, printing out a PolicyMap (regardless of how many policies are in there) always yields `{}`, b/c the `__str__` or `__repr__` methods are not properly implemented.

Will fix this.

**Comment by sven1977** [comment] 2022-12-14 14:24
Workaround for now (until PR is merged):
```
print(list(policies.keys()))
```

**Closed** 2022-12-16 07:04 UTC
Labels: enhancement, P2, rllib
