### ISSUE TITLE
[Core] stage_2_avg_iteration_time regression on stress_test_many_tasks 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29765] opened 2022-10-27 17:41 UTC
### What happened + What you expected to happen

There seems to be regression on this metric on the grpcio version update: https://github.com/ray-project/ray/commit/58255c79878b724288a523bf99c97e4257040c3c

https://b534fd88.us1a.app.preset.io/superset/explore/p/XrNLW0g7qpx/

### Versions / Dependencies

NA

### Reproduction script

On the commit:
- [cluster](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_8cpZzrT7Bs7wZaZsGUSDSukz)

Before the [commit](https://github.com/ray-project/ray/commit/64861270b8fceadd495229afb297c5e36351ebb5)
- [cluster](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_9XsayihUVUmY8bBhTfP22jQT), [cluster](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_dDKEVHU6NFzaEHBUknasbwE5), [cluster](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_tTKsezRmBX3Gi6P5re7YTEgx)

**Comment by rkooo567** [comment] 2022-12-09 06:50
Is there any action item we can take? If there's nothing we can do, let's close it?

**Comment by scv119** [comment] 2022-12-09 16:47
This is caused by grpcio upgrade, closing now.

**Closed** 2022-12-09 16:47 UTC
Labels: bug, P1, core
