### ISSUE TITLE
[Bug] Calling "tune.report" instead of "reporter" causes local mode to deadlock

### ISSUE THREAD

**Issue by froody** [ray-project/ray#18685] opened 2021-09-17 02:03 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

I followed the example at https://docs.ray.io/en/latest/tune/index.html and called `ray.init(local_mode=True)`, and the program hung indefinitely on `queue.get()`. By replacing the call to `tune.report` with a call to `reporter` (and adding the `reporter` as an arg to `training_function` I was able to get it to run successfully.

### Reproduction script
```
import ray
from ray import tune

def objective(step, alpha, beta):
    return (0.1 + alpha * step / 100) ** (-1) + beta * 0.1

# def training_function(config, reporter):
def training_function(config):
    # Hyperparameters
    alpha, beta = config["alpha"], config["beta"]
    for step in range(10):
        # Iterative training function - can be any arbitrary training procedure.
        intermediate_score = objective(step, alpha, beta)
        # Feed the score back back to Tune.
        tune.report(mean_loss=intermediate_score)
        # reporter(mean_loss=intermediate_score)


ray.init(local_mode=True, num_cpus=4)

analysis = tune.run(
    training_function,
    config={
        "alpha": tune.grid_search([0.001, 0.01, 0.1]),
        "beta": tune.choice([1, 2, 3]),
    },
    resources_per_trial={"cpu": 1},
)

print("Best config: ", analysis.get_best_config(metric="mean_loss", mode="min"))
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by xwjiang2010** [comment] 2021-09-17 05:19
What version of Ray are you using? 
I just tried it on master. The script runs successfully.

**Comment by froody** [comment] 2021-09-18 04:41
1.6.0

**Comment by xwjiang2010** [comment] 2021-10-05 23:39
If you are still blocked, please update to nightly ray. I believe the issue is fixed by https://github.com/ray-project/ray/pull/18023

**Closed by xwjiang2010** 2021-10-05 23:39 UTC
Labels: bug, tune
