### ISSUE TITLE
Core worker crashing in `report_streaming_generator_output` method

### ISSUE THREAD

**Issue by fishbone** [ray-project/ray#43119] opened 2024-02-12 23:53 UTC
```
*** SIGSEGV received at time=1707229696 on cpu 41 ***
PC: @     0x7f67e83f32b0  (unknown)  __pyx_f_3ray_7_raylet_report_streaming_generator_output()
    @     0x7f67e9d15420       2128  (unknown)
    @     0x7f67e8371ca4         80  __pyx_pw_11cfunc_dot_to_py_74__Pyx_CFunc_object____object____StreamingGeneratorExecutionContext___to_py_1wrap()
    @           0x505878  704448512  PyObject_Call
    @     0x7f67e936d940  (unknown)  (unknown)
[2024-02-06 06:28:16,194 E 204294 205041] logging.cc:361: *** SIGSEGV received at time=1707229696 on cpu 41 ***
[2024-02-06 06:28:16,194 E 204294 205041] logging.cc:361: PC: @     0x7f67e83f32b0  (unknown)  __pyx_f_3ray_7_raylet_report_streaming_generator_output()
[2024-02-06 06:28:16,197 E 204294 205041] logging.cc:361:     @     0x7f67e9d15420       2128  (unknown)
[2024-02-06 06:28:16,197 E 204294 205041] logging.cc:361:     @     0x7f67e8371ca4         80  __pyx_pw_11cfunc_dot_to_py_74__Pyx_CFunc_object____object____StreamingGeneratorExecutionContext___to_py_1wrap()
[2024-02-06 06:28:16,197 E 204294 205041] logging.cc:361:     @           0x505878  704448512  PyObject_Call
[2024-02-06 06:28:16,200 E 204294 205041] logging.cc:361:     @     0x7f67e936d940  (unknown)  (unknown)
Fatal Python error: Segmentation fault

**Comment by rynewang** [comment] 2024-02-21 23:51
@iycheng  do you have a repro script?

**Comment by jjyao** [comment] 2024-03-07 23:37
Duplicate of https://github.com/ray-project/ray/issues/43771

**Closed by jjyao** 2024-03-07 23:37 UTC
Labels: bug, release-blocker, P0, core, stability
