### ISSUE TITLE
Actor processes not destroyed after Python ref is released

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#1060] opened 2017-10-02 20:42 UTC
This can be reproduced with the following script. It will create 100 python processes, but even after the list is de-referenced the processes hang around forever (check `ps -A | grep python`).

```
import ray
import time
import sys

@ray.remote
class Actor(object):
    def __init__(self):
        pass

ray.init()
refs = [Actor.remote() for _ in range(100)]
time.sleep(5)
refs = None
time.sleep(99999)
```

**Comment by robertnishihara** [comment] 2017-10-02 20:57
I'm looking into this and it looks like the reference counts on the actor handles are too high, so they aren't going out of scope.

**Comment by robertnishihara** [comment] 2017-10-02 21:00
In the meantime, as a workaround, you could call

```python
a = Actor.remote()
a.__ray_terminate__.remote(ray.utils.hex_to_binary(repr(a)[6:-1]))
```

**Comment by robertnishihara** [comment] 2017-10-02 22:51
Ok, looks like the bug was introduced somewhere between `0.2.0` and `0.2.1`.

**Comment by robertnishihara** [comment] 2017-10-02 23:29
Looks like the problem first appeared in #902.

**Comment by virtualluke** [comment] 2017-10-03 03:55
I can't say that I have code to reproduce this right now but I have seen behavior where I have 100s of python processes left in "ps -A" after I have a program crash and it was definitely in code that had no Actors.

**Comment by robertnishihara** [comment] 2017-10-03 05:35
@virtualluke That might be the same issue as #1005.

**Closed** 2017-10-05 07:55 UTC
