### ISSUE TITLE
[Bug] Error when using PettingZoo Environments with ray==1.11.0

### ISSUE THREAD

**Issue by AstridVanneste** [ray-project/ray#22943] opened 2022-03-09 11:43 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

When upgrading to ray 1.11.0, using a PettingZoo environment (MPE Simple Speaker Listener) results in an error. 

```
File "/home/astrid/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 103, in __init__
    Trainer.__init__(self, config, env, logger_creator,
  File "/home/astrid/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 746, in __init__
    super().__init__(config, logger_creator, remote_checkpoint_dir,
  File "/home/astrid/.local/lib/python3.8/site-packages/ray/tune/trainable.py", line 124, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/astrid/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 114, in setup
    Trainer.setup(self, config)
  File "/home/astrid/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 807, in setup
    self._init(self.config, self.env_creator)
  File "/home/astrid/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 136, in _init
    self.workers = self._make_workers(
  File "/home/astrid/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1995, in _make_workers
    return WorkerSet(
  File "/home/astrid/.local/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 124, in __init__
    self._local_worker = self._make_worker(
  File "/home/astrid/.local/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 500, in _make_worker
    worker = cls(
  File "/home/astrid/.local/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 636, in __init__
    self.async_env: BaseEnv = convert_to_base_env(
  File "/home/astrid/.local/lib/python3.8/site-packages/ray/rllib/env/base_env.py", line 732, in convert_to_base_env
    return env.to_base_env(
  File "/home/astrid/.local/lib/python3.8/site-packages/ray/rllib/env/multi_agent_env.py", line 304, in to_base_env
    env = MultiAgentEnvWrapper(
  File "/home/astrid/.local/lib/python3.8/site-packages/ray/rllib/env/multi_agent_env.py", line 474, in __init__
    self._agent_ids = self._unwrapped_env.get_agent_ids()
AttributeError: 'raw_env' object has no attribute 'get_agent_ids'
```

### Versions / Dependencies

Ubuntu 20.04.4 LTS (in Windows Subsystem for Linux on Windows 10)
Python 3.8.10
ray==1.11.0
gym==0.21.0
PettingZoo==1.16.0
SuperSuit==3.3.3

### Reproduction script

```
import copy
import ray
import gym

from typing import Union, List, Optional, Dict, Tuple

from pettingzoo.mpe import simple_speaker_listener_v3
from ray import tune
from ray.rllib import Policy, SampleBatch
from ray.rllib.agents.trainer import COMMON_CONFIG
from ray.rllib.agents.trainer_template import build_trainer
from ray.rllib.env import ParallelPettingZooEnv
from ray.rllib.evaluation import Episode
from ray.rllib.utils.typing import TensorStructType, TensorType, TrainerConfigDict
from ray.tune import register_env
from supersuit import pad_action_space_v0, pad_observations_v0


def create_env_fn(env_config):
    return ParallelPettingZooEnv(
        pad_action_space_v0(
            pad_observations_v0(
                simple_speaker_listener_v3.parallel_env(max_cycles=env_config["max_cycles"],
                                                        continuous_actions=env_config["continuous_actions"])
            )
        )
    )


class TestPolicy(Policy):
    def __init__(self, observation_space: gym.Space, action_space: gym.Space, config: TrainerConfigDict):
        super().__init__(observation_space, action_space, config)

        self.action_space = action_space
        self.observation_space = observation_space

    def compute_actions(self, obs_batch: Union[List[TensorStructType], TensorStructType],
                        state_batches: Optional[List[TensorType]] = None,
                        prev_action_batch: Union[List[TensorStructType],
                                                 TensorStructType] = None,
                        prev_reward_batch: Union[List[TensorStructType],
                                                 TensorStructType] = None, info_batch: Optional[Dict[str, list]] = None,
                        episodes: Optional[List[Episode]] = None, explore: Optional[bool] = None,
                        timestep: Optional[int] = None, **kwargs) -> \
            Tuple[TensorType, List[TensorType], Dict[str, TensorType]]:

        return [self.action_space.sample() for obs in obs_batch], [], {}

    def learn_on_batch(self, samples: SampleBatch) -> Dict[str, TensorType]:
        pass


TestTrainer = build_trainer(
    name="TestTrainer",
    default_policy=TestPolicy,
    default_config=COMMON_CONFIG
)

if __name__ == "__main__":
    register_env("TestEnv", lambda env_config: create_env_fn(env_config))

    ray.init()

    env_config = {
        "max_cycles": 30,
        "continuous_actions": False
    }
    env = create_env_fn(env_config)

    config = copy.deepcopy(COMMON_CONFIG)
    config["env"] = "TestEnv"
    config["env_config"] = env_config
    config["num_workers"] = 0
    config["framework"] = "torch"
    config["train_batch_size"] = 200
    config["log_level"] = "INFO"
    config["normalize_actions"] = False
    config["simple_optimizer"] = True
    config["multiagent"] = {
        "policies": {
            # Speaker
            "speaker": (None, env.observation_space, env.action_space, {}),
            # Listener
            "listener": (None, env.observation_space, env.action_space, {})
        },
        "policy_mapping_fn": lambda agent_id: "speaker" if "speaker" in agent_id else "listener",
    }

    tune.run(TestTrainer, num_samples=1, config=config)

```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by NaIwo** [comment] 2022-03-21 18:43
Same issue here.

### Versions / Dependencies
Ubuntu 20.04.4 LTS
pettingzoo==1.16.0
python==3.8.12
gym==0.21.0
ray==1.11.0

**Comment by gjoliver** [comment] 2022-04-08 09:49
I am gonna mark this as a dup, and keep the other related issue open.
we will look at both example when debugging this.
thanks for the report.

**Comment by sven1977** [comment] 2022-04-19 20:28
Let's actually keep this one open here as it provides a working repro script. Closing the other dupe. ...

**Comment by sven1977** [comment] 2022-04-19 20:30
New repro script that also works w/o the deprecated build_trainer utility:

```
import copy
import ray
import gym

from typing import Union, List, Optional, Dict, Tuple

from pettingzoo.mpe import simple_speaker_listener_v3
from ray import tune
from ray.rllib import Policy, SampleBatch
from ray.rllib.agents.trainer import COMMON_CONFIG, Trainer
from ray.rllib.env import ParallelPettingZooEnv
from ray.rllib.evaluation import Episode
from ray.rllib.utils.typing import TensorStructType, TensorType, TrainerConfigDict
from ray.tune import register_env
from supersuit import pad_action_space_v0, pad_observations_v0


def create_env_fn(env_config):
    return ParallelPettingZooEnv(
        pad_action_space_v0(
            pad_observations_v0(
                simple_speaker_listener_v3.parallel_env(max_cycles=env_config["max_cycles"],
                                                        continuous_actions=env_config["continuous_actions"])
            )
        )
    )


class TestPolicy(Policy):
    def __init__(self, observation_space: gym.Space, action_space: gym.Space, config: TrainerConfigDict):
        super().__init__(observation_space, action_space, config)

        self.action_space = action_space
        self.observation_space = observation_space

    def compute_actions(self, obs_batch: Union[List[TensorStructType], TensorStructType],
                        state_batches: Optional[List[TensorType]] = None,
                        prev_action_batch: Union[List[TensorStructType],
                                                 TensorStructType] = None,
                        prev_reward_batch: Union[List[TensorStructType],
                                                 TensorStructType] = None, info_batch: Optional[Dict[str, list]] = None,
                        episodes: Optional[List[Episode]] = None, explore: Optional[bool] = None,
                        timestep: Optional[int] = None, **kwargs) -> \
            Tuple[TensorType, List[TensorType], Dict[str, TensorType]]:

        return [self.action_space.sample() for obs in obs_batch], [], {}

    def learn_on_batch(self, samples: SampleBatch) -> Dict[str, TensorType]:
        pass


class TestTrainer(Trainer):
    def get_default_policy_class(self, config):
        return TestPolicy

    @classmethod
    def get_default_config(cls):
        return COMMON_CONFIG


if __name__ == "__main__":
    register_env("TestEnv", lambda env_config: create_env_fn(env_config))

    ray.init()

    env_config = {
        "max_cycles": 30,
        "continuous_actions": False
    }
    env = create_env_fn(env_config)

    config = copy.deepcopy(COMMON_CONFIG)
    config["env"] = "TestEnv"
    config["env_config"] = env_config
    config["num_workers"] = 0
    config["framework"] = "torch"
    config["train_batch_size"] = 200
    config["log_level"] = "INFO"
    config["normalize_actions"] = False
    config["simple_optimizer"] = True
    config["multiagent"] = {
        "policies": {
            # Speaker
            "speaker": (None, env.observation_space, env.action_space, {}),
            # Listener
            "listener": (None, env.observation_space, env.action_space, {})
        },
        "policy_mapping_fn": lambda agent_id: "speaker" if "speaker" in agent_id else "listener",
    }

    tune.run(TestTrainer, num_samples=1, config=config)

```

**Comment by sven1977** [comment] 2022-04-19 20:57
Fix-it PR. Confirmed that this works now with your script.
https://github.com/ray-project/ray/pull/24025

**Comment by sven1977** [comment] 2022-04-21 19:50
Fixed by above PR, closing this now.

**Closed by sven1977** 2022-04-21 19:50 UTC
Labels: bug, P0, rllib, rllib-multi-agent, multiple-reports, repro-script-confirmed
