### ISSUE TITLE
[core] modifications to global variable has no effect

### ISSUE THREAD

**Issue by ppwwyyxx** [ray-project/ray#15946] opened 2021-05-20 17:36 UTC
### What is the problem?

Inside `tune.run`, modification to globals has no effect.

Python 3.8, Linux, nightly ray.

### Reproduction (REQUIRED)
```python
# cat has_globals.py
DICT = {}

# cat use_globals.py
from has_globals import DICT
def get(key):
    print("get", id(DICT))
    return DICT[key]

# cat test-ray.py
from ray import tune
from has_globals import DICT
from use_globals import get

def train_model(hp):
    DICT["key"] = 3
    get("key")

if __name__ == "__main__":
    hp = {"a": 3}
    result = tune.run(
        train_model,
        resources_per_trial={"cpu": 2, "gpu": 1},
        config=hp,
        num_samples=2,
    )
```

running `test-ray.py` will throw:
```
  File "HOME/.local/lib/python3.8/site-packages/ray/tune/function_runner.py", line 248, in run
    self._entrypoint()
  File "HOME/.local/lib/python3.8/site-packages/ray/tune/function_runner.py", line 315, in entrypoint
    return self._trainable_func(self.config, self._status_reporter,
  File "HOME/.local/lib/python3.8/site-packages/ray/tune/function_runner.py", line 580, in _trainable_func
    output = fn()
  File "test-ray.py", line 8, in train_model
    get("key")
  File "HOME/tmp/use_globals.py", line 8, in get
    return DICT[key]
KeyError: 'key'
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by krfricke** [comment] 2021-05-20 18:06
This is expected, as trainable functions are running in remote tasks (and on remote actors). These run in separate processes so don't share global variables with each other.

This is not specific to Ray tune by the way, but to Ray (and most distributed computing libraries) in general. See also e.g. https://stackoverflow.com/questions/62640533/how-to-use-global-variables-with-ray

Generally you'll want to avoid using global variables in parallel settings anyway because you could run into race conditions. You can use e.g. Ray queue (https://docs.ray.io/en/master/_modules/ray/util/queue.html) to pass objects between tasks.

**Comment by ppwwyyxx** [comment] 2021-05-20 18:12
> These run in separate processes so don't share global variables with each other.

The intention of the code is not to share global variables between processes. Please note that the modification to the global variable and the use of it happen in the same process. However the variable has different `id()` depending on where it is accessed.

**Comment by krfricke** [comment] 2021-05-20 19:04
Ah I see.

I'm wondering if this is actually a pickle problem. It seems the dictionaries are deserialized into two different objects here.

cc @rkooo567 have you seen this before?

**Comment by rkooo567** [comment] 2021-05-20 19:10
Hmm I don't think so. It is not clear to me what would be the issue by looking at this code (since it is Tune). Is it possible to make the repro using the core APIs?

**Comment by krfricke** [comment] 2021-05-20 19:22
Yeah:

```
import ray
from has_globals import DICT
from use_globals import get


@ray.remote
def train_model():
    DICT["key"] = 3
    get("key")


if __name__ == "__main__":
    ray.init()
    train_model.remote()
```

**Comment by rkooo567** [comment] 2021-05-20 19:24
@krfricke can you make the script runnable? It says no module named has_globals.

**Comment by rkooo567** [comment] 2021-05-20 19:25
can you tell me what's the expected output & current output?

**Comment by krfricke** [comment] 2021-05-20 19:25
See original comment for the other two files, but here's the full folder:
[issue_15946.zip](https://github.com/ray-project/ray/files/6518361/issue_15946.zip)

**Comment by krfricke** [comment] 2021-05-20 19:27
I think the expected output would be something like "get [some id]" and then just finish gracefully

Currently it is:

```
python test-ray.py
2021-05-20 20:26:59,070 INFO services.py:1264 -- View the Ray dashboard at http://127.0.0.1:8265
(pid=42377) get 4676093584
2021-05-20 20:27:01,386 ERROR worker.py:79 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::train_model() (pid=42377, ip=192.168.0.166)
  File "python/ray/_raylet.pyx", line 500, in ray._raylet.execute_task
  File "/Users/kai/coding/ray/python/ray/util/tracing/tracing_helper.py", line 280, in _function_with_tracing
    return function(*args, **kwargs)
  File "test-ray.py", line 9, in train_model
    get("key")
  File "/Users/kai/coding/sandbox/issue_15946/use_globals.py", line 4, in get
    return DICT[key]
KeyError: 'key'
```

**Comment by rkooo567** [comment] 2021-05-20 19:31
Try this; 

```python3
import ray
#from has_globals import DICT
#from use_globals import get


@ray.remote
def train_model():
    from has_globals import DICT
    from use_globals import get
    DICT["key"] = 3
    get("key")


if __name__ == "__main__":
    ray.init()
    train_model.remote()
```

The issue is when we make the remote method, it captures the DICT, which is copied to the remote process' memory, and it is different from the global variable inside use_globals. 

As a reference take a look at this example; 
```python3
import ray
from has_globals import DICT
#from use_globals import get
import use_globals
import has_globals


@ray.remote
def train_model():
    #from has_globals import DICT
    #from use_globals import get
    print(DICT is use_globals.DICT)
    print(has_globals.DICT is use_globals.DICT)
    DICT["key"] = 3
    use_globals.get("key")


if __name__ == "__main__":
    ray.init()
    train_model.remote()
```

**Comment by rkooo567** [comment] 2021-05-21 01:37
Closing the issue as it seems to be resolved!

**Closed by rkooo567** 2021-05-21 01:37 UTC
Labels: bug, triage

**Comment by heng2j** [comment] 2023-01-11 15:29
Hi everyone, for people who are still interested in integrating Ray with Detectron2, I have a new discussion thread in [Ray Discuss](https://discuss.ray.io/t/seeking-recommendation-for-training-detectron2-with-ray-tune/8849/3?u=heng2j).
