### ISSUE TITLE
[core] Idle workers from a completed job are not killed due to borrowed references

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#25699] opened 2022-06-11 07:22 UTC
### What happened + What you expected to happen

Run following scripts; once the job finished the worker is leaked because task argument `obj` is still being referenced.

**repro.py**
```python
import ray
import numpy as np
import tensorflow

def leak_repro(obj):
    # If import is moved here then the leak does not occur.
    # import tensorflow
    tensorflow
    return []

ds = ray.data.from_numpy(np.ones((100_000)))
ds.map(leak_repro)
```

`IDLE` processes will stay active.
![image](https://user-images.githubusercontent.com/3967392/173178114-594782e3-6196-449b-bd08-3411dccb7fbc.png)

Objects will stay pinned in memory.
```
--- Summary for node address: 172.31.20.214 ---
Mem Used by Objects  Local References  Pinned        Used by task   Captured in Objects  Actor Handles
241198.0 B           0, (0.0 B)        2, (241198.0 B)  0, (0.0 B)     0, (0.0 B)           0, (0.0 B)   

--- Object references for node address: 172.31.20.214 ---
IP Address       PID    Type    Call Site               Status          Size    Reference Type      Object Ref                                              
172.31.20.214    2216   Worker  (deserialize task arg)  -               120599.0 B  PINNED_IN_MEMORY    c8ef45ccd0112571ffffffffffffffffffffffff0100000001000000
                                 ray.data._internal.co                                                                                                      
                                mpute._map_block_nospl                                                                                                      
                                it                                                                                                                          

172.31.20.214    2215   Worker  (deserialize task arg)  -               120599.0 B  PINNED_IN_MEMORY    16310a0f0a45af5cffffffffffffffffffffffff0100000001000000
                                 ray.data._internal.co                                                                                                      
                                mpute._map_block_nospl                                                                                                      
                                it                                                                   
```

### Versions / Dependencies

latest ray

### Reproduction script

Create `repro.py` and run `python repro.py`

**Comment by scv119** [comment] 2022-06-11 07:25
cc @rkooo567 @matthewdeng

**Comment by rkooo567** [comment] 2022-06-11 07:29
cc @suquark do you have any guess this happens (or have you seen something similar before)?

Dataset map just starts many ray remote methods to execute the given UDF (and from numpy just creates plasma objects)

**Comment by matthewdeng** [comment] 2022-06-11 08:00
cc @clarkzinzow @jianoaix @ericl 

This one is interesting, we could **not** get it to repro with a simple Ray task:

```python
@ray.remote
def func(obj):
    return leak_repro(obj)

ray.get(func.remote(np.ones(10000)))
```

**Comment by matthewdeng** [comment] 2022-06-11 21:54
Just a quick note, I was able to reproduce this with Ray 1.12.0, so this isn't a (recent) regression.

**Comment by clarkzinzow** [comment] 2022-06-27 17:58
@jianoaix @matthewdeng What's the current status of this?

**Comment by jianoaix** [comment] 2022-06-28 02:45
Right, this was non-blocking so downgraded it. Sounds good to debug together.

**Comment by jiaodong** [comment] 2022-11-29 02:02
We ran into the exact same issue in a recent user workload pair programming, this error is subtle enough since "it works" but leads to serious perf issues that currently our release tests are not covering (we mostly only run the script once or multiple times without explicitly checking objects).

We should consider marking it as P0 fix in Ray 2.3 release.

**Comment by matthewdeng** [comment] 2022-11-29 02:18
@jiaodong can you share a simple repro? I think your workload probably captures the main issue a little better, and matches our original hypothesis of a global variable causing a memory leak. This should hopefully make this easier to debug.

This should probably still be a P1.

**Comment by jiaodong** [comment] 2022-11-29 02:23
The repro here works quite well as the minimal repro, user code i'm using can run without memory leak even with  global vars as long as all UDF used are inline imported. So the key issue from another workload still circles back to the same top of the file import issue here.

**Comment by matthewdeng** [comment] 2022-11-29 05:21
Oh I see, reading over Slack I didn't realize that the global variable that was being imported was a function from `tensorflow.keras`...

**Comment by Yard1** [comment] 2023-01-27 21:14
Another occurrence in https://github.com/ray-project/ray/issues/31967

**Comment by ericl** [comment] 2023-01-27 22:00
There are some funny things going on here. Even if tensorflow / etc create leaked references:
1. After the task finishes, the worker should be eligible to be killed. It does not seem that the worker pool is killing these idle processes.
2. After the job finishes, the workers of the job should be killed. This is also not the case.

**Comment by clarng** [comment] 2023-01-30 19:57
@Yard1 I followed the repo steps in https://github.com/ray-project/ray/issues/31967#issue-1558560219

and got an error when trying to reproduce the issue: https://gist.github.com/clarng/8a07a1dd418e696112d7c309608a8d44

can you see if this is different from what you are seeing? the workspace I have is here :
https://console.anyscale-staging.com/o/anyscale-internal/workspaces/expwrk_ip5l78walmuieraxitqsclbtc1/ses_eiqk4va1ruskdjd4gqv3vla1ru?command-history-section=head_start_up_log

**Comment by clarng** [comment] 2023-01-30 19:59
I also ran the repro from @scv119 , seems the code no longer works and I'm getting error : https://gist.github.com/clarng/484425010820caf411534f2c7ae6b75b

the code is

```

import ray
import numpy as np
import tensorflow

def leak_repro(obj):
    # If import is moved here then the leak does not occur.
    # import tensorflow
    tensorflow
    return []

ds = ray.data.from_numpy(np.ones((100_000)))
ds.map(leak_repro)
```

**Comment by ericl** [comment] 2023-01-30 20:17
Maybe upgrade your arrow version? Or, you can try this tweak:

```

import ray
import numpy as np
import tensorflow

def leak_repro(obj):
    # If import is moved here then the leak does not occur.
    # import tensorflow
    tensorflow
    return []

ds = ray.data.range_tensor(100000, parallelism=1)
ds.map(leak_repro)
```

**Comment by clarng** [comment] 2023-01-30 20:24
Thanks

I'm able to repo now, it triggers for the cluster (pre-installed) ray but not my local dev ws, trying single node cluster (pre-installed) to see if it repros

**Comment by clarng** [comment] 2023-01-30 20:54
Looks like we don't kill the worker if we think it is busy, that is, when we send the Exit command to the worker it can tell the raylet it is still not idle yet.

That is consistent with us seeing objects for the worker we calling 'ray memory'

**Comment by ericl** [comment] 2023-01-30 23:02
Furthermore, we should probably kill workers unconditionally if the job has finished, even if they contain owned objects.

**Comment by clarng** [comment] 2023-01-31 18:28
The objects in question appears to be the task arg, which may explain why it is owned by the worker, and hence holding up the worker from being freed.

One edge case with killing the worker when the job dies is the object may be used by a detached actor 


IP Address       PID    Type    Call Site               Status          Size    Reference Type      Object Ref                                              
172.31.198.64    147136  Worker  (deserialize task arg)  -               3485.0 B  PINNED_IN_MEMORY    00ffffffffffffffffffffffffffffffffffffff0100000002000000
                                 ray.data._internal.ex                                                                                                      
                                ecution.operators.map_                                                                                                      
                                operator._map_task                                                                                                          

172.31.198.64    147136  Worker  (deserialize task arg)  -               800468.0 B  PINNED_IN_MEMORY    c8ef45ccd0112571ffffffffffffffffffffffff0100000001000000
                                 ray.data._internal.ex                                                                                                      
                                ecution.operators.map_                                                                                                      
                                operator._map_task

**Comment by ericl** [comment] 2023-01-31 19:13
Task args aren't owned by the worker though... they should be owned by the submitter of the task, which calls `ray.put()` on the original arg.

**Comment by ericl** [comment] 2023-01-31 19:13
> One edge case with killing the worker when the job dies is the object may be used by a detached actor

This is already the case though. Killing the worker doesn't change the ownership model.

**Comment by clarng** [comment] 2023-01-31 21:05
> Task args aren't owned by the worker though... they should be owned by the submitter of the task, which calls `ray.put()` on the original arg.

Then perhaps there is something wrong with the reference counter logic ? Per the logs it says the two objects leaked are owned by the task, via this check:

```
bool ReferenceCounter::OwnObjects() const {
  absl::MutexLock lock(&mutex_);
  return !object_id_refs_.empty();
}
```

which returns true and hence prevents the core worker from exiting when requested by the raylet.

In the core worker it shows object_id_refs_.size() == 2

We also see the log printed below, which checks that there should be no owned object (?) when the task finished:

```
  if (task_spec.IsNormalTask() && reference_counter_->NumObjectIDsInScope() != 0) {
    RAY_LOG(DEBUG)
        << "There were " << reference_counter_->NumObjectIDsInScope()
        << " ObjectIDs left in scope after executing task " << task_spec.TaskId()
        << ". This is either caused by keeping references to ObjectIDs in Python "
           "between "
           "tasks (e.g., in global variables) or indicates a problem with Ray's "
           "reference counting, and may cause problems in the object store.";
  }

```

**Comment by ericl** [comment] 2023-01-31 21:18
I think object_id_refs_ also contains unowned objects (e.g. "Borrowed" objects). `AddBorrowedObject()` ends up inserting into that table too. So maybe that check is incorrect?

**Comment by clarng** [comment] 2023-01-31 21:27
The objects in 'ray memory' are borrowed objects per logs

[2023-01-30 22:15:53,171 D 147136 147136] reference_count.cc:106: Adding borrowed object 00ffffffffffffffffffffffffffffffffffffff0100000002000000

[2023-01-30 22:15:53,172 D 147136 147136] reference_count.cc:106: Adding borrowed object c8ef45ccd0112571ffffffffffffffffffffffff0100000001000000

Looks like we should ignore them at least for the OwnObjects check? That should allow the pool to reap the worker

**Comment by ericl** [comment] 2023-01-31 21:57
Yeah, that seems like an oversight for OwnsObjects. Probably it assumed there were no borrowed objects left after the task finished.

**Comment by clarng** [comment] 2023-02-03 05:36
Looks like there are a few issues
- the task finished but was not removed from the idle pool
- the task won't exit since it thinks it is still owning object
- the borrowed objects are not cleaned up when the task finished

Currently looking at a patch to make sure the task gets removed if the driver is finishes

**Closed** 2023-02-10 23:57 UTC
Labels: bug, release-blocker, P0, core, Ray 2.3
