### ISSUE TITLE
Permission Error: [WinError 5]  Access is denied: '(originated from OpenProcess)' combined with PermissionError: [Errno 13] assume access denied (originated from NtQueryInformationProcess(ProcessBasicInformation) -> STATUS_NOT_FOUND)

### ISSUE THREAD

**Issue by userbot2000** [ray-project/ray#13401] opened 2021-01-13 12:49 UTC
I am trying to run multiple iterations of a model to tune it using the ray.remote function. I had completed the initial coding issues, i.e. installing the Visual C++ VC_redist.x64.exe and managed to get the program to work during the same day that I had installed it. I was able to get the results required. 

The following day I had run the code, the PC had been powered down in between runs, and I ran into a permission error that prevented me from creating a dictionary that stores the results for my model tuning. I have not changed the preceding code in any way that I can imagine has a knock effect. 

The version of Ray that I am using is 1.1.0, I am operating off of a windows OS and I am using a classifier from scikit-learn version 0.23.1. 

The code runs fine for a few iterations, however after 5 minutes the error appears.

Once this error occurs I can no longer access the results produced from this process.

The following is part of the issue that I keep coming up against:

2021-01-13 12:45:53,741	

```
RayTaskError(AccessDenied): ray::parallel_processing() (pid=18664, ip=192.168.130.163)
  File "C:\Users\MarPAMM\Anaconda3\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 780, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=True)
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

ray::parallel_processing() (pid=18664, ip=192.168.130.163)
  File "C:\Users\MarPAMM\Anaconda3\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\MarPAMM\Anaconda3\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 695, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\MarPAMM\Anaconda3\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 783, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=False)
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

ray::parallel_processing() (pid=18664, ip=192.168.130.163)
  File "python\ray\_raylet.pyx", line 423, in ray._raylet.execute_task
  File "C:\Users\MarPAMM\Anaconda3\lib\site-packages\ray\memory_monitor.py", line 132, in raise_if_low_memory
    self.error_threshold))
  File "C:\Users\MarPAMM\Anaconda3\lib\site-packages\ray\memory_monitor.py", line 43, in get_message
    proc.cmdline()))
  File "C:\Users\MarPAMM\Anaconda3\lib\site-packages\ray\thirdparty_files\psutil\__init__.py", line 677, in cmdline
    return self._proc.cmdline()
  File "C:\Users\MarPAMM\Anaconda3\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=100)
```

**Comment by gumba3** [comment] 2021-02-09 08:21
The same just busted my run after a few hours, see below.

I suspect it has something to do with running out of RAM. Just before the error, it said `Memory usage on this node: 15.1/15.9 GiB: ***LOW MEMORY*** less than 10% of the memory on this node is available for use.`

Line 43 in memory_monitor.py is the RayOutOfMemoryError, so this would have been triggered, as it was above.
https://github.com/ray-project/ray/blob/2092b097eab41b118a117fdfadd0fe664db41f63/python/ray/memory_monitor.py#L43

It seems that the error is broken. Maybe build a test case in which the memory is almost exhausted to provoke it.

Ideally, ray should not break down completely but just shut down one worker to continue with less ram need.

Thanks for the team for working on the issues. As a side note, the amount of open bug issues is staggering for a "stable" version. I keep running from one documented program-exiting bug into the next, with issues untouched for weeks. Well, at least this bug here should be easy to fix.

```
2021-02-09 04:19:33,418	ERROR trainer.py:497 -- Error in train call, attempting to recover
Traceback (most recent call last):
  File "<ANACONDA_ENV>\lib\site-packages\ray\rllib\agents\trainer.py", line 494, in train
    result = Trainable.train(self)
  File "<ANACONDA_ENV>\lib\site-packages\ray\tune\trainable.py", line 183, in train
    result = self.step()
  File "<ANACONDA_ENV>\lib\site-packages\ray\rllib\agents\trainer_template.py", line 147, in step
    res = next(self.train_exec_impl)
  File "<ANACONDA_ENV>\lib\site-packages\ray\util\iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "<ANACONDA_ENV>\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "<ANACONDA_ENV>\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "<ANACONDA_ENV>\lib\site-packages\ray\util\iter.py", line 843, in apply_filter
    for item in it:
  File "<ANACONDA_ENV>\lib\site-packages\ray\util\iter.py", line 843, in apply_filter
    for item in it:
  File "<ANACONDA_ENV>\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "<ANACONDA_ENV>\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "<ANACONDA_ENV>\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "<ANACONDA_ENV>\lib\site-packages\ray\util\iter.py", line 876, in apply_flatten
    for item in it:
  File "<ANACONDA_ENV>\lib\site-packages\ray\util\iter.py", line 828, in add_wait_hooks
    item = next(it)
  File "<ANACONDA_ENV>\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "<ANACONDA_ENV>\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "<ANACONDA_ENV>\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "<ANACONDA_ENV>\lib\site-packages\ray\util\iter.py", line 471, in base_iterator
    yield ray.get(futures, timeout=timeout)
  File "<ANACONDA_ENV>\lib\site-packages\ray\worker.py", line 1379, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AccessDenied): ray::RolloutWorker.par_iter_next() (pid=11128, ip=<IP>)
  File "<ANACONDA_ENV>\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 780, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=True)
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

ray::RolloutWorker.par_iter_next() (pid=11128, ip=<IP>)
  File "<ANACONDA_ENV>\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "<ANACONDA_ENV>\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 695, in wrapper
    return fun(self, *args, **kwargs)
  File "<ANACONDA_ENV>\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 783, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=False)
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

ray::RolloutWorker.par_iter_next() (pid=11128, ip=<IP>)
  File "python\ray\_raylet.pyx", line 423, in ray._raylet.execute_task
  File "<ANACONDA_ENV>\lib\site-packages\ray\memory_monitor.py", line 131, in raise_if_low_memory
    RayOutOfMemoryError.get_message(used_gb, total_gb,
  File "<ANACONDA_ENV>\lib\site-packages\ray\memory_monitor.py", line 43, in get_message
    proc.cmdline()))
  File "<ANACONDA_ENV>\lib\site-packages\ray\thirdparty_files\psutil\__init__.py", line 677, in cmdline
    return self._proc.cmdline()
  File "<ANACONDA_ENV>\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=148)
```
After that, all workers failed with the same error:
```
ray::RolloutWorker.par_iter_next() (pid=2264, ip=<IP>)
  File "<ANACONDA_ENV>\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "<ANACONDA_ENV>\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 695, in wrapper
    return fun(self, *args, **kwargs)
  File "<ANACONDA_ENV>\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 783, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=False)
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

ray::RolloutWorker.par_iter_next() (pid=2264, ip=<IP>)
  File "python\ray\_raylet.pyx", line 423, in ray._raylet.execute_task
  File "<ANACONDA_ENV>\lib\site-packages\ray\memory_monitor.py", line 131, in raise_if_low_memory
    RayOutOfMemoryError.get_message(used_gb, total_gb,
  File "<ANACONDA_ENV>\lib\site-packages\ray\memory_monitor.py", line 43, in get_message
    proc.cmdline()))
  File "<ANACONDA_ENV>\lib\site-packages\ray\thirdparty_files\psutil\__init__.py", line 677, in cmdline
    return self._proc.cmdline()
  File "<ANACONDA_ENV>\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=148)
2021-02-09 04:19:38,522	ERROR worker.py:980 -- Possible unhandled error from worker: ray::RolloutWorker.par_iter_next() (pid=8808, ip=<IP>)
  File "<ANACONDA_ENV>\lib\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 780, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=True)
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'
```

**Comment by tom634** [comment] 2021-11-04 15:15
Did anyone resolve it? My output:
`Failure # 1 (occurred at 2021-11-04_16-07-23)
Traceback (most recent call last):
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\tune\trial_runner.py", line 586, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\tune\ray_trial_executor.py", line 609, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\_private\client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AccessDenied): [36mray::PPO.train_buffered()[39m (pid=33496, ip=192.168.1.43)
  File "python\ray\_raylet.pyx", line 439, in ray._raylet.execute_task
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\worker.py", line 176, in reraise_actor_init_error
    raise self.actor_init_error
  File "python\ray\_raylet.pyx", line 473, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 476, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\function_manager.py", line 556, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\rllib\agents\trainer_template.py", line 107, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\rllib\agents\trainer.py", line 486, in __init__
    super().__init__(config, logger_creator)
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\tune\trainable.py", line 97, in __init__
    self.setup(copy.deepcopy(self.config))
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\rllib\agents\trainer.py", line 654, in setup
    self._init(self.config, self.env_creator)
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\rllib\agents\trainer_template.py", line 134, in _init
    self.workers = self._make_workers(
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\rllib\agents\trainer.py", line 725, in _make_workers
    return WorkerSet(
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\rllib\evaluation\worker_set.py", line 79, in __init__
    remote_spaces = ray.get(self.remote_workers(
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\_private\client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AccessDenied): [36mray::RolloutWorker.foreach_policy()[39m (pid=3944, ip=192.168.1.43)
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 780, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=True)
PermissionError: [WinError 5] Odmowa dostępu: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

[36mray::RolloutWorker.foreach_policy()[39m (pid=3944, ip=192.168.1.43)
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 695, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 783, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=False)
PermissionError: [WinError 5] Odmowa dostępu: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

[36mray::RolloutWorker.foreach_policy()[39m (pid=3944, ip=192.168.1.43)
  File "python\ray\_raylet.pyx", line 440, in ray._raylet.execute_task
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\memory_monitor.py", line 131, in raise_if_low_memory
    RayOutOfMemoryError.get_message(used_gb, total_gb,
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\memory_monitor.py", line 43, in get_message
    proc.cmdline()))
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\thirdparty_files\psutil\__init__.py", line 677, in cmdline
    return self._proc.cmdline()
  File "C:\Users\Tomek\AppData\Roaming\Python\Python38\site-packages\ray\thirdparty_files\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=136)

`

**Comment by mattip** [comment] 2023-12-20 17:00
@userbot2000 does this still occur? Can one of the reporters provide a complete reproducer so I can try to figure out what is going wrong?

**Comment by mattip** [comment] 2024-01-18 14:13
Closing due to inaction by reporters. Please reopen or open a new issue if this is still relevant.

**Closed by mattip** 2024-01-18 14:13 UTC
Labels: bug, P2, windows, @external-author-action-required
