### ISSUE TITLE
[Release] wheel_urls is failing the nightly test

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#18635] opened 2021-09-15 15:35 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### What happened + What you expected to happen

https://buildkite.com/ray-project/periodic-ci/builds/987#e0ee8503-e6f2-43ae-996d-badfde63f6f0

### Reproduction script

https://buildkite.com/ray-project/periodic-ci/builds/987#e0ee8503-e6f2-43ae-996d-badfde63f6f0

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by architkulkarni** [comment] 2021-09-15 17:00
As indicated by the test output, the Mac wheels were not built for this commit for some reason: https://s3.console.aws.amazon.com/s3/buckets/ray-wheels?region=us-west-2&prefix=master/9d41aafcce2a0782754444220eb738af1808299e/&showversions=false

However, I checked manually for the next four commits, and the Mac wheels were built in those cases, so I think this was a one-off occurrence and we can close this.  Thoughts @simon-mo? This test is for catching changes to the wheel URL name format, and the names haven't changed.  We should still make sure this test passes for the commit on the release branch that we're releasing.

**Comment by simon-mo** [comment] 2021-09-15 17:48
How about making the test even more lenient? Something like it's built for one of past two commits then it passes

**Comment by architkulkarni** [comment] 2021-09-15 18:50
That's an interesting idea, I'm not sure we want to do that though... for example it could be that the URL format was changed in the last commit before the release, and this test wouldn't detect that and the release could go out with runtime_envs broken.  (I know this seems really unlikely, but I think it's still important that this test give us peace of mind without having to manually check the wheel URLs.)

The test is working as intended, the wheels haven't been uploaded so runtime_envs is broken on this master commit.  (But not broken on the subsequent 4+ commits)

If the Mac wheel build upload is flaky that sounds like a separate problem.

I'd propose we wait for the next nightly test to pass and then close this issue.

**Comment by jjyao** [comment] 2021-09-16 22:07
The latest test passed, should we close the issue now?

**Comment by architkulkarni** [comment] 2021-09-16 22:41
Closing because the latest test passed.  If this starts to fail on the release branch, we should reopen.

**Closed by architkulkarni** 2021-09-16 22:41 UTC
Labels: bug, release-blocker, P0, triage
