### ISSUE TITLE
RAY_CHECK doesn't give backtraces.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#4347] opened 2019-03-12 22:19 UTC
I think `RAY_LOG(FATAL)` does give backtraces.

**Comment by robertnishihara** [comment] 2019-03-12 22:28
Actually, `RAY_LOG(FATAL)` doesn't seem to be doing the right thing either. This is on Linux.

What I'm seeing is the following. It does seem to be trying to give some backtrace, but there's no information there.

```
F0312 22:25:47.841747 26827 node_manager.cc:2063] No lineage cache entry found for task 00000000992983d0db525e89bd8ebb6e8aa0ed1c
*** Check failure stack trace: ***
*** Aborted at 1552429547 (unix time) try "date -d @1552429547" if you are using GNU date ***
PC: @                0x0 (unknown)
```

**Comment by virtualluke** [comment] 2019-03-12 23:18
Not sure if helpful but I use the traceback module a decent amount and on unknown exception print `traceback.format_exc()`

**Comment by guoyuhong** [comment] 2019-03-18 05:17
If I used cmake to build the binary, there is not such case. It looks like this only happens in bazel built binaries.

**Comment by robertnishihara** [comment] 2019-03-18 05:23
@guoyuhong oh interesting. Maybe we're forgetting to compile with `-g` or something like that?

**Comment by guoyuhong** [comment] 2019-03-18 07:30
For cmake, it will run some tests to define some macros, but for bazel, it all predefined. Glog bazel script only uses a minimal set of macros. I'm trying out which macros are necessary.

**Comment by guoyuhong** [comment] 2019-03-19 03:16
@pcmoritz Helped to merge the PR. @robertnishihara could you help to double confirm the problem is fixed? Then we can close this issue.

**Comment by pcmoritz** [comment] 2019-03-19 03:54
I tested it with RAY_CHECK, backtraces are working now!

**Closed by pcmoritz** 2019-03-19 03:54 UTC
