### ISSUE TITLE
[clusters][Ray Core] Autoscaler is not downscaling idle nodes (azure)

### ISSUE THREAD

**Issue by mlguruz** [ray-project/ray#30991] opened 2022-12-09 12:57 UTC
### What happened + What you expected to happen

@stephanie-wang 

I'm running distributed jobs on remote Azure cluster launched via Ray autoscaler. 
The issue is that even after all jobs are done, Ray won't auto scale down the worker nodes, even a whole night (`idle_timeout_minutes` set to 2 minutes).

Using one worker as an example:
if I do `ps -ef | grep -i python`, I only see raylet, log_monitor, and dashboard agent running. all my python jobs are done:

![image](https://user-images.githubusercontent.com/24363659/206705259-4a0dba2f-bb9c-4090-a3de-9a574ac06d57.png)

Now, on the head node, I also only see just ray processes running.
![image](https://user-images.githubusercontent.com/24363659/206705612-1674d43a-b5f9-4a75-bbba-2aeabb8e0175.png)

Also I don't see any error msgs from my jobs. 

To debug, I tried to run `ray cluster-dump ~/ray_bootstrap_config.yaml` on the head node as advised but ran into the following errors:
```
Traceback (most recent call last):
  File "/home/david.zhang/projects/zstar/envs/current_linux38/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/david.zhang/projects/zstar/envs/18f4ce25b111036a11508279f5fc1dc34d1f8bbf/lib/python3.8/site-packages/ray/scripts/scripts.py", line 2596, in main
    return cli()
  File "/home/david.zhang/projects/zstar/envs/18f4ce25b111036a11508279f5fc1dc34d1f8bbf/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/david.zhang/projects/zstar/envs/18f4ce25b111036a11508279f5fc1dc34d1f8bbf/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/david.zhang/projects/zstar/envs/18f4ce25b111036a11508279f5fc1dc34d1f8bbf/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/david.zhang/projects/zstar/envs/18f4ce25b111036a11508279f5fc1dc34d1f8bbf/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/david.zhang/projects/zstar/envs/18f4ce25b111036a11508279f5fc1dc34d1f8bbf/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/david.zhang/projects/zstar/envs/18f4ce25b111036a11508279f5fc1dc34d1f8bbf/lib/python3.8/site-packages/ray/scripts/scripts.py", line 2284, in cluster_dump
    archive_path = get_cluster_dump_archive(
  File "/home/david.zhang/projects/zstar/envs/18f4ce25b111036a11508279f5fc1dc34d1f8bbf/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 1522, in get_cluster_dump_archive
    ) = _info_from_params(cluster_config_file, host, ssh_user, ssh_key, docker)
  File "/home/david.zhang/projects/zstar/envs/18f4ce25b111036a11508279f5fc1dc34d1f8bbf/lib/python3.8/site-packages/ray/autoscaler/_private/cluster_dump.py", line 616, in _info_from_params
    h, u, k, d, cluster_name = get_info_from_ray_cluster_config(cluster)
  File "/home/david.zhang/projects/zstar/envs/18f4ce25b111036a11508279f5fc1dc34d1f8bbf/lib/python3.8/site-packages/ray/autoscaler/_private/cluster_dump.py", line 576, in get_info_from_ray_cluster_config
    hosts = [provider.external_ip(node) for node in head_nodes + worker_nodes]
  File "/home/david.zhang/projects/zstar/envs/18f4ce25b111036a11508279f5fc1dc34d1f8bbf/lib/python3.8/site-packages/ray/autoscaler/_private/cluster_dump.py", line 576, in <listcomp>
    hosts = [provider.external_ip(node) for node in head_nodes + worker_nodes]
  File "/home/david.zhang/projects/zstar/envs/18f4ce25b111036a11508279f5fc1dc34d1f8bbf/lib/python3.8/site-packages/ray/autoscaler/_private/_azure/node_provider.py", line 168, in external_ip
    self._get_cached_node(node_id=node_id)["external_ip"]
KeyError: 'external_ip'

```

As a workaround, I synced all logs from head + one of the worker nodes over and put it here for debugging:

[ray_log.zip](https://github.com/ray-project/ray/files/10194995/ray_log.zip)

A few words on this: the cluster is created within a corporate set-up w/o admin permission and under various other permission constraints, so to get it working, I made quite a few changes to below few files under `_private/azure/`. This is also due to some of the Azure vm creation parameters not publicly exposed in the recent version of azure specific `.yaml` file and `node_provider.py`.
1. node_provider.py
2. azure-config-template.json
3. azure-vm-template.json 

This is has all the changes here:
[azure.zip](https://github.com/ray-project/ray/files/10194895/azure.zip)

As additional notes, the workflow is very straightforward - and embarrassingly parallizable jobs (200+ chunks) + an aggregator in the end that does no-op (i.e. pass).

Each job would return some values that get passed to the aggregator job. 
The aggregator looks like 

```
@remote(num_cpus=0)
def aggregate(*jobs):
    pass 
```

I would expect:
- Ray would terminate worker nodes when the jobs running on that worker node are all completed. Now, to be clear, if this worker node finishes earliest compared to other nodes, I would expect Ray still terminate this worker while storing the return values from all jobs running on this worker to global object store so that later they can be passed to the aggregator. This to me makes intuitive sense but I'm not sure if this is the behavior 
- Now, even if it is not the optimal (imo) case above, I would at least expect after all jobs are done, Ray would terminate all worker nodes. I don't see this happening. 

I would say this is pretty important b/c it will incur non-trivial costs, especially if we're running large batches of jobs.

### Versions / Dependencies

ray == 2.1.0
python == 3.8

### Reproduction script

I'm working on a replica now. 
I ran the actual jobs overnight just to make sure the above happens again, just in case it's some random situation to avoid wasting everybody's time.
On a high level (not to far, really), the workflow is exactly as described above.

### Issue Severity

High: It blocks me from completing my task.

**Comment by stephanie-wang** [comment] 2022-12-09 17:25
Thanks @mlguruz !

Also, can you clarify if the driver script (the python script calling `aggregate`) is still running after the idle timeout? Ray keeps objects alive as long as there is a reference holder, so I'm wondering if you're seeing this happen because the driver is still holding the ray.ObjectRefs that get passed to the `aggregate` task. If this is the case, then you could try calling `del` on any ObjectRefs that you don't need anymore; otherwise this is most likely a bug in Ray autoscaler/core.

**Comment by mlguruz** [comment] 2022-12-09 19:42
> 

Below is a single illustration of the workflow:
```
import pandas as pd 

app_root_dir = '~/dummy'
params = {}
num_chunks = 200


chunks = np.array_split(pd.date_range('20130101', '20131231'), num_chunks)


def single_job(start_date, end_date, app_root_dir, params):
    print(f"building data from {start_date} to {end_date}")
    ...


def aggregate_jobs(completed_jobs, app_root_dir, params):
    print(f"aggregating {len(completed_jobs)} total jobs.")
    ... 
    

@ray.remote(num_cpus=1, memory=1*1024**3)
def single_job_wrapper(start_date, end_date, app_root_dir, params):
    try:
        return single_job(start_date, end_date, app_root_dir, params)  # rv won't be None if successful
    except BaseException:
        return None

    
@ray.remote(num_cpus=0)
def aggegate_wrapper(chunked_jobs, app_root_dir, params):
    completed, success = [], True
    for s in chunked_jobs:
        if s is None:
            success = False
        else:
            completed.append(s)
    result = None
    if len(completed):
        result = aggregate_jobs(completed_jobs=completed, app_root_dir=app_root_dir, params=params)
    return result, success   


single_jobs = [single_job_wrapper.remote(c[0], c[-1], app_root_dir, params) for c in chunks]
result = aggegate_wrapper.remote(single_jobs, app_root_dir, params)
res = ray.get(result)
```

**Comment by stephanie-wang** [comment] 2022-12-09 20:36
Thanks, the script is helpful! I will try to reproduce it. From this script, it looks like the situation I described is not happening, because your driver script exits right after it calls `ray.get`.

> since aggegate_wrapper depends on all object refs above, ray will keep them alive, which makes sense. Question is - will Ray keep all the workers that are running them alive as well? Or, ray will store the returned object refs in global object store instead of local object store of that worker node, hence being able to shutdown the worker node w/ no live jobs running?

There isn't really a "global" object store in Ray. Instead the distributed object store is made up of the local object stores at each worker node. But once the `aggregate_wrapper` finishes and the driver exits (meaning no more ObjectRefs in scope), these objects are supposed to get cleaned up and the worker nodes should get shut down.

> I guess I can't do this if my aggregator depends on all of them right?
The way to do this would be to `del single_jobs` after calling `aggregate_wrapper.remote()`. Then, the only reference left would be the aggregator task, and once this finishes, the objects will get cleaned up. But it's not really relevant in your script because your driver script exits immediately anyway.

**Comment by mlguruz** [comment] 2022-12-09 22:58
> There isn't really a "global" object store in Ray. Instead the distributed object store is made up of the local object stores at each worker node. But once the aggregate_wrapper finishes and the driver exits (meaning no more ObjectRefs in scope), these objects are supposed to get cleaned up and the worker nodes should get shut down.

Thanks - just so I understand better - assume we have 5 worker nodes, each running 1 job, and then an aggregator running on the head node, waiting for the 5 jobs to finish. 

Assuming the min time takes for the job to finish is 1min, and max is 5min, does it mean that *all* workers need to wait for 5mins for them to be shutdown, b/c the longest job would take 5 mins? 

Or if say the job on worker A finishes in 1 min, there's a way to tell ray to shutdown worker node A, while still keeping the return valued from worker A, b/c the aggregator needs it? 

I'm asking b/c this will change the cost from `avg_job_time x num_workers` to `max_job_time x num_workers`, and sometimes the diff can be sizable when you have things like data transfer and everything happening. 

Thanks again!

**Comment by stephanie-wang** [comment] 2022-12-12 17:19
> > There isn't really a "global" object store in Ray. Instead the distributed object store is made up of the local object stores at each worker node. But once the aggregate_wrapper finishes and the driver exits (meaning no more ObjectRefs in scope), these objects are supposed to get cleaned up and the worker nodes should get shut down.
> 
> Thanks - just so I understand better - assume we have 5 worker nodes, each running 1 job, and then an aggregator running on the head node, waiting for the 5 jobs to finish.
> 
> Assuming the min time takes for the job to finish is 1min, and max is 5min, does it mean that _all_ workers need to wait for 5mins for them to be shutdown, b/c the longest job would take 5 mins?

Yes, in the current design, we do not clean up any of the objects until `aggregate` finishes, so all the workers will wait at least 5min before shutting down.

> 
> Or if say the job on worker A finishes in 1 min, there's a way to tell ray to shutdown worker node A, while still keeping the return valued from worker A, b/c the aggregator needs it?

I think there are two options here:
1. Run all of the jobs on one machine. Where possible, you should always prefer this over an autoscaling solution because it will also give you the best performance by avoiding data transfer. Unless you have need for very fine-grained elasticity, it is generally also the most cost-efficient.
2. If multiple machines are necessary, you can try to aggregate the objects one at a time using an actor. This would allow you to free earlier ObjectRefs sooner. The downside is that you will no longer get Ray's fault tolerance mechanism for free, so it's up to you to recover the actor's state if it dies.

```
@ray.remote
class Aggregator:
  def aggregate_one(self, x):
    self.sum += x
  def get_result(self):
    return self.sum

single_jobs = [single_job_wrapper.remote(c[0], c[-1], app_root_dir, params) for c in chunks]
for job in single_jobs:
  aggregator.aggregate_one.remote(job, app_root_dir, params)
# Delete the driver's references. Now the pending actor tasks are the only ref holders.
del job
del single_jobs

ray.get(aggregator.get_result.remote())


```

> 
> I'm asking b/c this will change the cost from `avg_job_time x num_workers` to `max_job_time x num_workers`, and sometimes the diff can be sizable when you have things like data transfer and everything happening.
> 
> Thanks again!

**Comment by stephanie-wang** [comment] 2022-12-14 22:32
Hi @mlguruz so far I'm not able to reproduce the issue that you're seeing.

Here is the script that I was running with max_workers=3:
```python
import ray
import time
import numpy as np


@ray.remote
def f():
    time.sleep(60)
    return np.random.randint(10, size=int(1e8 / 8))

@ray.remote
def aggregate(*xs):
    return sum(xs)


xs = [f.remote() for _ in range(6)]
print(ray.get(aggregate.remote(*xs)))
```

So the problem is either:
1. The actual program has some issue or is triggering a system-level bug that this simplified toy program is not.
2. Something to do with the azure setup.

Is there any way you could provide a full standalone script that I could use to reproduce? This would help to narrow down the cause between 1 or 2.

**Comment by mlguruz** [comment] 2022-12-14 23:31
> Hi @mlguruz so far I'm not able to reproduce the issue that you're seeing.
> 
> Here is the script that I was running with max_workers=3:
> 
> ```python
> import ray
> import time
> import numpy as np
> 
> 
> @ray.remote
> def f():
>     time.sleep(60)
>     return np.random.randint(10, size=int(1e8 / 8))
> 
> @ray.remote
> def aggregate(*xs):
>     return sum(xs)
> 
> 
> xs = [f.remote() for _ in range(6)]
> print(ray.get(aggregate.remote(*xs)))
> ```
> 
> So the problem is either:
> 
> 1. The actual program has some issue or is triggering a system-level bug that this simplified toy program is not.
> 2. Something to do with the azure setup.
> 
> Is there any way you could provide a full standalone script that I could use to reproduce? This would help to narrow down the cause between 1 or 2.

First of all - thank you vm for your time and help! 

To better figure out 1 or 2, let me first run your simple example, w/ the Azure setup and see if I still don't see cluster tearing down.

If that issue still happen, then it's 2. 
If not, they I agree, I need to figure out a way to put a close-to-real example here. 

Let me work on it.
Thanks again!

**Comment by stephanie-wang** [comment] 2022-12-21 01:50
Hey @mlguruz just wanted to check how you're doing on this. Anything I can do to help?

**Comment by mlguruz** [comment] 2022-12-21 12:12
> Hey @mlguruz just wanted to check how you're doing on this. Anything I can do to help?

Hi - we're working on creating an env that will allow us using the default ray cloud launcher. 

I should be able to get back early next wk. If not, I'll at least run your example the current way first.

Thank you for the great help!

**Comment by mlguruz** [comment] 2023-02-08 13:58
> Hey @mlguruz just wanted to check how you're doing on this. Anything I can do to help?

Hi Stephanie,

Sorry for the long wait. 

We have done a serial of tests on Azure w/ and w/o our permission driven changes, and the above behavior seems to be driven by those custom changes made to workaround permissions. 

In a nutshell, Ray (2.2.0) running on its own, w/o any changes, should not cause the above bug. 

Also, we have moved to AWS as the cloud provider for running Ray autoscaler.

**Comment by stephanie-wang** [comment] 2023-02-08 15:55
Great to hear, thanks! I'll close this issue for now then.

**Closed by stephanie-wang** 2023-02-08 15:55 UTC
Labels: bug, P1, core, clusters
