### ISSUE TITLE
No handlers could be found for logger "ray.tune.logger"

### ISSUE THREAD

**Issue by nthomas103** [ray-project/ray#3849] opened 2019-01-25 06:54 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.2
- **Python version**: 2.7.12
- **Exact command to reproduce**: import ray.tune

### Describe the problem

The following error occurs when importing ray.tune (after doing pip install -U ray, in virtual environment):

No handlers could be found for logger "ray.tune.logger"

### Source code / logs

import ray.tune

**Comment by robertnishihara** [comment] 2019-01-25 07:03
Thanks @nthomas103, is it a warning message that appears or is it an exception that prevents the application from running?

**Comment by robertnishihara** [comment] 2019-01-25 07:04
Actually never mind, I can reproduce it and I see that it's a warning that's printed.

**Comment by robertnishihara** [comment] 2019-01-26 22:01
Opening because this is not fixed yet. Thanks for reporting it!

**Comment by robertnishihara** [comment] 2019-01-31 05:06
Fixed by #3691.

**Closed by robertnishihara** 2019-01-31 05:06 UTC
