### ISSUE TITLE
[RLlib] TypeError after upgrading from Ray 1.10

### ISSUE THREAD

**Issue by qinmoelei** [ray-project/ray#26364] opened 2022-07-07 17:06 UTC
### What happened + What you expected to happen

Previously, I use python 3.7.11 and Ray 1.10 and my code works fine
afterI pose
``` trainer.train()```
there is a erroe coming out saying
 Exception ignored in: <function RolloutWorker.__del__ at 0x7f36998bc940>
Traceback (most recent call last):
  File "/home/sunshuo/miniconda3/envs/TradeMaster/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 461, in _resume_span
TypeError: 'NoneType' object is not callable
and when I restore my result using trainer.restore(checkpoint), it fails, and here is the information
Traceback (most recent call last):
  File "/home/sunshuo/qml/TradeMaster_reframe/agent/SOTA/SOTA.py", line 205, in <module>
    a.train_with_valid()
  File "/home/sunshuo/qml/TradeMaster_reframe/agent/SOTA/SOTA.py", line 179, in train_with_valid
    self.trainer.restore(checkpoint)
  File "/home/sunshuo/miniconda3/envs/TradeMaster/lib/python3.8/site-packages/ray/tune/trainable.py", line 583, in restore
    self.load_checkpoint(checkpoint_path)
  File "/home/sunshuo/miniconda3/envs/TradeMaster/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 2070, in load_checkpoint
    self.__setstate__(extra_data)
  File "/home/sunshuo/miniconda3/envs/TradeMaster/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 2693, in __setstate__
    self.workers.local_worker().restore(state["worker"])
  File "/home/sunshuo/miniconda3/envs/TradeMaster/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1542, in restore
    self.policy_map[pid].set_state(state)
  File "/home/sunshuo/miniconda3/envs/TradeMaster/lib/python3.8/site-packages/ray/rllib/policy/torch_policy.py", line 766, in set_state
    optim_state_dict = convert_to_torch_tensor(s, device=self.device)
  File "/home/sunshuo/miniconda3/envs/TradeMaster/lib/python3.8/site-packages/ray/rllib/utils/torch_utils.py", line 163, in convert_to_torch_tensor
    return tree.map_structure(mapping, x)
  File "/home/sunshuo/miniconda3/envs/TradeMaster/lib/python3.8/site-packages/tree/__init__.py", line 430, in map_structure
    [func(*args) for args in zip(*map(flatten, structures))])
  File "/home/sunshuo/miniconda3/envs/TradeMaster/lib/python3.8/site-packages/tree/__init__.py", line 430, in <listcomp>
    [func(*args) for args in zip(*map(flatten, structures))])
  File "/home/sunshuo/miniconda3/envs/TradeMaster/lib/python3.8/site-packages/ray/rllib/utils/torch_utils.py", line 157, in mapping
    tensor = torch.from_numpy(np.asarray(item))
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
Exception ignored in: <function RolloutWorker.__del__ at 0x7fcb49d3a940>
Traceback (most recent call last):
  File "/home/sunshuo/miniconda3/envs/TradeMaster/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 461, in _resume_span
TypeError: 'NoneType' object is not callable

### Versions / Dependencies

aiohttp==3.8.1
aiohttp-cors==0.7.0
aiorwlock==1.3.0
aiosignal==1.2.0
anyio==3.6.1
asgiref==3.5.2
asttokens==2.0.5
async-timeout==4.0.2
attrs==21.4.0
backcall==0.2.0
blessed==1.19.1
cachetools==5.2.0
certifi @ file:///opt/conda/conda-bld/certifi_1655968806487/work/certifi
charset-normalizer==2.1.0
click==8.0.4
cloudpickle==2.1.0
colorful==0.5.4
cycler==0.11.0
debugpy==1.5.1
decorator==5.1.1
distlib==0.3.4
dm-tree==0.1.7
entrypoints==0.4
executing==0.8.3
fastapi==0.78.0
filelock==3.7.1
fonttools==4.33.3
frozenlist==1.3.0
google-api-core==2.8.2
google-auth==2.9.0
googleapis-common-protos==1.56.3
gpustat==1.0.0b1
grpcio==1.43.0
gym==0.21.0
h11==0.13.0
idna==3.3
imageio==2.19.3
importlib-resources==5.8.0
ipykernel==6.9.2
ipython==8.1.1
jedi==0.18.1
jsonschema==4.6.1
jupyter-client==7.1.2
jupyter-core==4.9.2
kiwisolver==1.4.3
lz4==4.0.1
matplotlib==3.5.2
matplotlib-inline==0.1.3
msgpack==1.0.4
multidict==6.0.2
nest-asyncio==1.5.4
networkx==2.8.4
numpy==1.23.0
nvidia-ml-py3==7.352.0
opencensus==0.9.0
opencensus-context==0.1.2
packaging==21.3
pandas==1.4.3
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.2.0
platformdirs==2.5.2
prometheus-client==0.13.1
prompt-toolkit==3.0.28
protobuf==3.20.1
psutil==5.9.0
ptyprocess==0.7.0
pure-eval==0.2.2
py-spy==0.3.12
pyasn1==0.4.8
pyasn1-modules==0.2.8
pydantic==1.9.1
Pygments==2.11.2
pyparsing==3.0.9
pyrsistent==0.18.1
python-dateutil==2.8.2
pytz==2022.1
PyWavelets==1.3.0
PyYAML==6.0
pyzmq==22.3.0
ray==1.13.0
requests==2.28.1
rsa==4.8
scikit-image==0.19.3
scipy==1.8.1
six==1.16.0
smart-open==6.0.0
sniffio==1.2.0
stack-data==0.2.0
starlette==0.19.1
tabulate==0.8.10
tensorboardX==2.5.1
tifffile==2022.5.4
torch==1.12.0
tornado==6.1
traitlets==5.1.1
typing_extensions==4.3.0
urllib3==1.26.9
uvicorn==0.16.0
virtualenv==20.15.1
wcwidth==0.2.5
yapf @ file:///tmp/build/80754af9/yapf_1615749224965/work
yarl==1.7.2
zipp==3.8.0
OS:Ubuntu
Python:3.8.13

### Reproduction script

for i in range(self.num_epochs):
            
            self.trainer.train()
             valid_env_instance = env_creator(self.env_name)(
                  self.valid_env_config)
              state = valid_env_instance.reset()
             done = False
             while not done:
                 action = self.trainer.compute_single_action(state)
                 state, reward, #     valid_env_instance = env_creator(self.env_name)(
                 self.valid_env_config)
             state = valid_env_instance.reset()
             done = False
             while not done:
                 action = self.trainer.compute_single_action(state)
                 state, reward, done, information = valid_env_instance.step(
                     action)
             self.sharpes.append(information["sharpe_ratio"])
             checkpoint = self.trainer.save()
             print(checkpoint)
             self.trainer.restore(checkpoint)
        #     self.checkpoints.append(checkpoint)
        # self.loc = self.sharpes.index(max(self.sharpes))
        # self.trainer.restore(self.checkpoints[self.loc])
        # self.trainer.save(self.trained_model_dict)done, information = valid_env_instance.step(
        #             action)
        #     self.sharpes.append(information["sharpe_ratio"])
        #     checkpoint = self.trainer.save()
        #     print(checkpoint)
        #     self.trainer.restore(checkpoint)
        #     self.checkpoints.append(checkpoint)
        # self.loc = self.sharpes.index(max(self.sharpes))
        # self.trainer.restore(self.checkpoints[self.loc])
        # self.trainer.save(self.trained_model_dict)
        ray.shutdown()

### Issue Severity

High: It blocks me from completing my task.

**Comment by rossstump** [comment] 2022-07-12 18:13
I've been dealing with this same issue. Downgrading torch to torch==1.10 fixed it for me. Hope that helps

**Comment by ewald-florian** [comment] 2022-07-29 07:58
I get the same error. Downgrading torch to 1.10 did not work for me but I also do not use torch but tensorflow 2 as framework. Would be very grateful for any help!

**Error**

Exception ignored in: <function RolloutWorker.__del__ at 0x7f7cd84734c0>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 461, in _resume_span
TypeError: 'NoneType' object is not callable

**Dependencies**
absl-py==0.13.0
aiosignal==1.2.0
alembic @ file:///home/conda/feedstock_root/build_artifacts/alembic_1622150326904/work
anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1624539389047/work/dist
appdirs @ file:///home/conda/feedstock_root/build_artifacts/appdirs_1603108395799/work
argon2-cffi @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi_1610522574055/work
astunparse==1.6.3
async-generator==1.10
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1620387926260/work
Babel @ file:///home/conda/feedstock_root/build_artifacts/babel_1619719576210/work
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
beautifulsoup4 @ file:///home/conda/feedstock_root/build_artifacts/beautifulsoup4_1601745390275/work
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1612213472466/work
blinker==1.4
bokeh @ file:///home/conda/feedstock_root/build_artifacts/bokeh_1625756926652/work
Bottleneck @ file:///home/conda/feedstock_root/build_artifacts/bottleneck_1611195606760/work
brotlipy==0.7.0
cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
cachetools==4.2.2
certifi==2022.6.15
certipy==0.1.3
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1613413861439/work
chardet @ file:///home/conda/feedstock_root/build_artifacts/chardet_1610093490430/work
click==7.1.2
cloudpickle @ file:///home/conda/feedstock_root/build_artifacts/cloudpickle_1598400192773/work
conda==4.9.2
conda-package-handling @ file:///home/conda/feedstock_root/build_artifacts/conda-package-handling_1618231394280/work
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography_1616851476134/work
cycler==0.10.0
Cython @ file:///home/conda/feedstock_root/build_artifacts/cython_1623963298809/work
cytoolz==0.11.0
dask @ file:///home/conda/feedstock_root/build_artifacts/dask-core_1616804774713/work
debugpy @ file:///home/conda/feedstock_root/build_artifacts/debugpy_1620178540514/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1621187651333/work
defusedxml @ file:///home/conda/feedstock_root/build_artifacts/defusedxml_1615232257335/work
dill @ file:///home/conda/feedstock_root/build_artifacts/dill_1623610058511/work
distlib==0.3.5
distributed @ file:///home/conda/feedstock_root/build_artifacts/distributed_1620931187261/work
dm-tree==0.1.7
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1605121927639/work/dist/entrypoints-0.3-py2.py3-none-any.whl
filelock==3.7.1
flatbuffers==1.12
frozenlist==1.3.0
fsspec @ file:///home/conda/feedstock_root/build_artifacts/fsspec_1624452401871/work
gast==0.3.3
gmpy2==2.1.0b5
google-auth==1.32.1
google-auth-oauthlib==0.4.4
google-pasta==0.2.0
graphviz==0.11
greenlet @ file:///home/conda/feedstock_root/build_artifacts/greenlet_1620327505524/work
grpcio==1.32.0
gym==0.21.0
h5py==2.10.0
HeapDict==1.0.1
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1593328102638/work
imagecodecs @ file:///home/conda/feedstock_root/build_artifacts/imagecodecs_1623996795751/work
imageio @ file:///home/conda/feedstock_root/build_artifacts/imageio_1594044661732/work
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1625463720459/work
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1625232753004/work/dist/ipykernel-6.0.1-py3-none-any.whl
ipyleaflet==0.14.0
ipympl @ file:///home/conda/feedstock_root/build_artifacts/ipympl_1611166850005/work
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1625027225561/work
ipython-genutils==0.2.0
ipywidgets @ file:///home/conda/feedstock_root/build_artifacts/ipywidgets_1609995587151/work
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1610146791023/work
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1621419064915/work
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1612898609989/work
json5 @ file:///home/conda/feedstock_root/build_artifacts/json5_1600692310011/work
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema_1614815863336/work
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1615693636836/work
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1612125275706/work
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyter-packaging @ file:///home/conda/feedstock_root/build_artifacts/jupyter-packaging_1613054948399/work
jupyter-server @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_1624558637735/work
jupyter-telemetry @ file:///home/conda/feedstock_root/build_artifacts/jupyter_telemetry_1605173804246/work
jupyterhub @ file:///home/conda/feedstock_root/build_artifacts/jupyterhub-feedstock_1614255305026/work
jupyterlab @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_1616195786210/work
jupyterlab-drawio==0.9.0
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1601375948261/work
jupyterlab-server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1622556871679/work
jupyterlab-widgets @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_widgets_1609173350931/work
Keras==2.4.3
Keras-Preprocessing==1.1.2
kiwisolver @ file:///home/conda/feedstock_root/build_artifacts/kiwisolver_1610099769230/work
llvmlite==0.36.0
locket==0.2.0
lxml==4.6.3
lz4==4.0.2
Mako @ file:///home/conda/feedstock_root/build_artifacts/mako_1610659158978/work
mamba @ file:///home/conda/feedstock_root/build_artifacts/mamba_1625509571906/work
Markdown==3.3.4
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1621455677251/work
matplotlib @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-suite_1611858708474/work
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1618935594181/work
mistune @ file:///home/conda/feedstock_root/build_artifacts/mistune_1624941302223/work
mock @ file:///home/conda/feedstock_root/build_artifacts/mock_1610094566888/work
mpmath @ file:///home/conda/feedstock_root/build_artifacts/mpmath_1612895720168/work
msgpack @ file:///home/conda/feedstock_root/build_artifacts/msgpack-python_1610121699837/work
nbclassic @ file:///home/conda/feedstock_root/build_artifacts/nbclassic_1621947328608/work
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1614336084111/work
nbconvert @ file:///home/conda/feedstock_root/build_artifacts/nbconvert_1624472649437/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1617383142101/work
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1617163391303/work
networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1598210780226/work
notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1610575313697/work
numba @ file:///home/conda/feedstock_root/build_artifacts/numba_1623568544775/work
numexpr @ file:///home/conda/feedstock_root/build_artifacts/numexpr_1614971340455/work
numpy==1.19.5
oauthlib @ file:///home/conda/feedstock_root/build_artifacts/oauthlib_1622563202229/work
olefile @ file:///home/conda/feedstock_root/build_artifacts/olefile_1602866521163/work
opt-einsum==3.3.0
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1625323647219/work
pamela==1.0.0
pandas==1.2.5
pandocfilters==1.4.2
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1617148930513/work
partd @ file:///home/conda/feedstock_root/build_artifacts/partd_1617910651905/work
patsy==0.5.1
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1602535608087/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1625677820830/work
platformdirs==2.5.2
plotly==5.1.0
pooch @ file:///home/conda/feedstock_root/build_artifacts/pooch_1623218528920/work
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1622586138406/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1623977816122/work
protobuf==3.15.8
psutil @ file:///home/conda/feedstock_root/build_artifacts/psutil_1610127095720/work
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycosat @ file:///home/conda/feedstock_root/build_artifacts/pycosat_1610094800877/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1593275161868/work
pycurl==7.43.0.6
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1620245170812/work
PyJWT @ file:///home/conda/feedstock_root/build_artifacts/pyjwt_1619620644068/work
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1608055815057/work
pyparsing==2.4.7
pyrsistent @ file:///home/conda/feedstock_root/build_artifacts/pyrsistent_1610146798212/work
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1610291447907/work
python-dateutil==2.8.1
python-editor==1.0.4
python-json-logger @ file:///home/conda/feedstock_root/build_artifacts/python-json-logger_1602545356084/work
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1612179539967/work
PyWavelets @ file:///home/conda/feedstock_root/build_artifacts/pywavelets_1607290812047/work
PyYAML==5.4.1
pyzmq @ file:///home/conda/feedstock_root/build_artifacts/pyzmq_1622038460640/work
ray==1.13.0
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1608156231189/work
requests-oauthlib==1.3.0
requests-unixsocket==0.2.0
rise==5.7.1
rsa==4.7.2
ruamel-yaml-conda @ file:///home/conda/feedstock_root/build_artifacts/ruamel_yaml_1611943339799/work
ruamel.yaml @ file:///home/conda/feedstock_root/build_artifacts/ruamel.yaml_1624567361774/work
ruamel.yaml.clib @ file:///home/conda/feedstock_root/build_artifacts/ruamel.yaml.clib_1610146840614/work
scikit-image==0.18.2
scikit-learn @ file:///home/conda/feedstock_root/build_artifacts/scikit-learn_1619628586492/work
scipy @ file:///home/conda/feedstock_root/build_artifacts/scipy_1619561901336/work
seaborn @ file:///home/conda/feedstock_root/build_artifacts/seaborn-split_1611834504644/work
Send2Trash @ file:///home/conda/feedstock_root/build_artifacts/send2trash_1624366715919/work
six==1.15.0
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1610318319305/work
sortedcontainers @ file:///home/conda/feedstock_root/build_artifacts/sortedcontainers_1621217038088/work
soupsieve @ file:///home/conda/feedstock_root/build_artifacts/soupsieve_1597680516047/work
SQLAlchemy @ file:///home/conda/feedstock_root/build_artifacts/sqlalchemy_1624920405831/work
statsmodels @ file:///home/conda/feedstock_root/build_artifacts/statsmodels_1612273599609/work
sympy @ file:///home/conda/feedstock_root/build_artifacts/sympy_1610127369423/work
TA-Lib @ file:///home/conda/feedstock_root/build_artifacts/ta-lib_1618425390451/work
tables @ file:///home/conda/feedstock_root/build_artifacts/pytables_1610156075390/work
tabulate==0.8.10
tblib @ file:///home/conda/feedstock_root/build_artifacts/tblib_1616261298899/work
tenacity==8.0.0
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorboardX==2.5.1
tensorflow==2.4.1
tensorflow-estimator==2.4.0
termcolor==1.1.0
terminado @ file:///home/conda/feedstock_root/build_artifacts/terminado_1623365314921/work
testpath @ file:///home/conda/feedstock_root/build_artifacts/testpath_1621261527237/work
threadpoolctl @ file:///tmp/tmp79xdzxkt/threadpoolctl-2.1.0-py3-none-any.whl
tifffile @ file:///home/conda/feedstock_root/build_artifacts/tifffile_1625322421387/work
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1600973991856/work
torch==1.10.0
torchaudio==0.10.0
torchvision==0.11.0
torchviz==0.0.2
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1610094706440/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1625664838498/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1602771532708/work
traittypes==0.2.1
typing-extensions==3.7.4.3
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1624634538755/work
vincent==0.4.4
virtualenv==20.16.2
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1600965781394/work
webencodings==0.5.1
websocket-client @ file:///home/conda/feedstock_root/build_artifacts/websocket-client_1610127644879/work
Werkzeug==2.0.1
widgetsnbextension @ file:///home/conda/feedstock_root/build_artifacts/widgetsnbextension_1605475534911/work
wrapt==1.12.1
xlrd @ file:///home/conda/feedstock_root/build_artifacts/xlrd_1610224409810/work
zict==2.0.0
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1625284368454/work

**Comment by kouroshHakha** [comment] 2022-08-02 20:32
Hi, if this still an issue could @qinmoelei or @ewald-florian  provide a minimal repro script, so we can test these out on our end. The provided script does not provide a reproducible results.

**Comment by ThatIsAUsername** [comment] 2022-08-07 20:09
Sven's [MultiAgentArena example](https://github.com/sven1977/rllib_tutorials/blob/main/ray_summit_2021/tutorial_notebook.ipynb) is sufficient to repro this behavior.
I am running Python 3.9.7, ray 1.13.0, and torch 1.12.1

train script (as a .txt since Github won't allow attaching a .py):
[train_agent.txt](https://github.com/ray-project/ray/files/9277443/train_agent.txt)

environment:
[environment.txt](https://github.com/ray-project/ray/files/9277444/environment.txt)

pip freeze for context:
[pip_freeze.txt](https://github.com/ray-project/ray/files/9277446/pip_freeze.txt)

Good to hear downgrading helped some people. I will try that next.

**Comment by derpberk** [comment] 2022-08-08 17:07
I have also encountered this issue in Ray V1.13.0.

I tested the following: 

- Train with my custom envs/models (multiagent and single-agent), checkpointing, and restoring with _pytorch >= 1.12_ and _pytorch == 1.10_. Both versions returned the error above.
- Also by training a CartPole-v0 and trying to restore the state of the trainer (to exclude any issues related to my own implementation). Also with both versions of pytorch mentioned above and still fails.
- Both Python 3.7 and Python 3.8. None of the with positive results.
**- I installed Ray 3.0.0dev and finally, _trainer.restore()_ worked.**

This issue is particularly painfull as it breaks the possibility of deploying policies in not-networked agents disconnected from a ray service or similar.

**Comment by kouroshHakha** [comment] 2022-08-09 01:11
It seems like this issue does not exist on master anymore which means it will be resolved in the next release version (2.0rc0). I have confirmed by running the following repro script with the more recent ray versions.

```

from copy import deepcopy
import ray
from ray import tune
from ray.tune import result as result_keys
from ray.rllib.agents.ppo import PPOTrainer, DEFAULT_CONFIG as PPO_DEFAULT_CONFIG

from gym.spaces import Discrete, MultiDiscrete
import numpy as np


from ray.rllib.env.multi_agent_env import MultiAgentEnv


class MultiAgentArena(MultiAgentEnv):
    def __init__(self, config=None):
        config = config or {}
        # Dimensions of the grid.
        self.width = config.get("width", 10)
        self.height = config.get("height", 10)

        # End an episode after this many timesteps.
        self.timestep_limit = config.get("ts", 100)

        self.observation_space = MultiDiscrete([self.width * self.height,
                                                self.width * self.height])
        # 0=up, 1=right, 2=down, 3=left.
        self.action_space = Discrete(4)
        # self._agent_ids = set(['agent1', 'agent2'])

        # Reset env.
        self.reset()
        
    def reset(self):
        """Returns initial observation of next(!) episode."""
        # Row-major coords.
        self.agent1_pos = [0, 0]  # upper left corner
        self.agent2_pos = [self.height - 1, self.width - 1]  # lower bottom corner

        # Accumulated rewards in this episode.
        self.agent1_R = 0.0
        self.agent2_R = 0.0

        # Reset agent1's visited fields.
        self.agent1_visited_fields = set([tuple(self.agent1_pos)])

        # How many timesteps have we done in this episode.
        self.timesteps = 0

        # Return the initial observation in the new episode.
        return self._get_obs()

    def step(self, action: dict):
        """
        Returns (next observation, rewards, dones, infos) after having taken the given actions.
        
        e.g.
        `action={"agent1": action_for_agent1, "agent2": action_for_agent2}`
        """
        
        # increase our time steps counter by 1.
        self.timesteps += 1
        # An episode is "done" when we reach the time step limit.
        is_done = self.timesteps >= self.timestep_limit

        # Agent2 always moves first.
        # events = [collision|agent1_new_field]
        events = self._move(self.agent2_pos, action["agent2"], is_agent1=False)
        events |= self._move(self.agent1_pos, action["agent1"], is_agent1=True)

        # Useful for rendering.
        self.collision = "collision" in events
            
        # Get observations (based on new agent positions).
        obs = self._get_obs()

        # Determine rewards based on the collected events:
        r1 = -1.0 if "collision" in events else 1.0 if "agent1_new_field" in events else -0.5
        r2 = 1.0 if "collision" in events else -0.1

        self.agent1_R += r1
        self.agent2_R += r2
        
        rewards = {
            "agent1": r1,
            "agent2": r2,
        }

        # Generate a `done` dict (per-agent and total).
        dones = {
            "agent1": is_done,
            "agent2": is_done,
            # special `__all__` key indicates that the episode is done for all agents.
            "__all__": is_done,
        }

        return obs, rewards, dones, {}  # <- info dict (not needed here).

    def _get_obs(self):
        """
        Returns obs dict (agent name to discrete-pos tuple) using each
        agent's current x/y-positions.
        """
        ag1_discrete_pos = self.agent1_pos[0] * self.width + \
            (self.agent1_pos[1] % self.width)
        ag2_discrete_pos = self.agent2_pos[0] * self.width + \
            (self.agent2_pos[1] % self.width)
        return {
            "agent1": np.array([ag1_discrete_pos, ag2_discrete_pos]),
            "agent2": np.array([ag2_discrete_pos, ag1_discrete_pos]),
        }

    def _move(self, coords, action, is_agent1):
        """
        Moves an agent (agent1 iff is_agent1=True, else agent2) from `coords` (x/y) using the
        given action (0=up, 1=right, etc..) and returns a resulting events dict:
        Agent1: "new" when entering a new field. "bumped" when having been bumped into by agent2.
        Agent2: "bumped" when bumping into agent1 (agent1 then gets -1.0).
        """
        orig_coords = coords[:]
        # Change the row: 0=up (-1), 2=down (+1)
        coords[0] += -1 if action == 0 else 1 if action == 2 else 0
        # Change the column: 1=right (+1), 3=left (-1)
        coords[1] += 1 if action == 1 else -1 if action == 3 else 0

        # Solve collisions.
        # Make sure, we don't end up on the other agent's position.
        # If yes, don't move (we are blocked).
        if (is_agent1 and coords == self.agent2_pos) or (not is_agent1 and coords == self.agent1_pos):
            coords[0], coords[1] = orig_coords
            # Agent2 blocked agent1 (agent1 tried to run into agent2)
            # OR Agent2 bumped into agent1 (agent2 tried to run into agent1)
            return {"collision"}

        # No agent blocking -> check walls.
        if coords[0] < 0:
            coords[0] = 0
        elif coords[0] >= self.height:
            coords[0] = self.height - 1
        if coords[1] < 0:
            coords[1] = 0
        elif coords[1] >= self.width:
            coords[1] = self.width - 1

        # If agent1 -> "new" if new tile covered.
        if is_agent1 and not tuple(coords) in self.agent1_visited_fields:
            self.agent1_visited_fields.add(tuple(coords))
            return {"agent1_new_field"}
        # No new tile for agent1.
        return set()

    def render(self, mode=None):
        print("_" * (self.width + 2))
        for r in range(self.height):
            print("|", end="")
            for c in range(self.width):
                field = r * self.width + c % self.width
                if self.agent1_pos == [r, c]:
                    print("1", end="")
                elif self.agent2_pos == [r, c]:
                    print("2", end="")
                elif (r, c) in self.agent1_visited_fields:
                    print(".", end="")
                else:
                    print(" ", end="")
            print("|")
        print("‾" * (self.width + 2))
        print(f"{'!!Collision!!' if self.collision else ''}")
        print("R1={: .1f}".format(self.agent1_R))
        print("R2={: .1f}".format(self.agent2_R))
        print()




if __name__ == "__main__":

    ray.init()
    env = MultiAgentEnv()

    # Define the policies definition dict:
    # Each policy in there is defined by its ID (key) mapping to a 4-tuple (value):
    # - Policy class (None for using the "default" class, e.g. PPOTFPolicy for PPO+tf or PPOTorchPolicy for PPO+torch).
    # - obs-space (we get this directly from our already created env object).
    # - act-space (we get this directly from our already created env object).
    # - config-overrides dict (leave empty for using the Trainer's config as-is)
    policies = {
        "policy1": (None, env.observation_space, env.action_space, {}),
        "policy2": (None, env.observation_space, env.action_space, {"lr": 0.0002}),
    }

    # Define an agent->policy mapping function.
    # Which agents (defined by the environment) use which policies (defined by us)?
    # The mapping here is M (agents) -> N (policies), where M >= N.
    def policy_mapping_fn(agent_id: str):
        # Make sure agent ID is valid.
        assert agent_id in ["agent1", "agent2"], f"ERROR: invalid agent ID {agent_id}!"
        # Map agent1 to policy1, and agent2 to policy2.
        return "policy1" if agent_id == "agent1" else "policy2"

    # Define training config.
    # Specify a very simple config, defining our environment and some environment
    # options (see environment.py).
    config = {
        "env": MultiAgentArena,
        "env_config": {
            # "config": {
            "width": 10,
            "height": 10,
            "ts": 100,
            # },
        },
        "framework": "torch",
        "create_env_on_driver": True,
        "multiagent": {
            "policies": policies,
            "policy_mapping_fn": policy_mapping_fn,
        },
    }


    # Define training stop conditions. Anything from the trainer's result dict can be used here.
    stop = {
        result_keys.TRAINING_ITERATION: 1,
        result_keys.EPISODE_REWARD_MEAN: 20.0
    }
    
    tune_config = deepcopy(config)
    tune_config["lr"] = tune.grid_search([0.0001, 0.0003])
    analysis = tune.run(
        "PPO",
        config=tune_config,
        stop=stop,
        checkpoint_freq=10,
        checkpoint_at_end=True,
    )

    best_trial = analysis.get_best_trial(metric=result_keys.EPISODE_REWARD_MEAN, mode='max')
    checkpoint = analysis.get_best_checkpoint(trial=best_trial, metric=result_keys.EPISODE_REWARD_MEAN, mode='max')

    if checkpoint:
        print(f"Running sample episode with best checkpoint {checkpoint}.")
        import time
        trainer = PPOTrainer(config=config)
        trainer.restore(checkpoint)

        env = MultiAgentArena()
        obs = env.reset()
        while True:
            actions = {}
            for agent in obs:
                actions[agent] = trainer.compute_single_action(obs[agent], policy_id=policy_mapping_fn(agent))
            obs, rwds, dones, info = env.step(actions)
            # env.render()
            time.sleep(0.07)

            if dones["__all__"]:
                break
        print(f"Finished sample episode with checkpoint {checkpoint}")
    else:
        print("No best checkpoint found!")

    ray.shutdown()

```

Python 3.8.5, torch=1.12.0, 1.12.1, ray3.0.0dev

**Closed by kouroshHakha** 2022-08-09 01:11 UTC
Labels: bug, P2, triage, rllib, fixed-in-master

**Comment by cwfparsonson** [comment] 2022-08-18 13:22
I am also getting this error after upgrading torch to 1.12.1 and cuda to 11.6

python==3.9.7
ray==1.9.2
torch==1.12.1
cuda==11.6

**Comment by yyyuhan** [comment] 2022-10-04 13:20
I had the similar issues with the following packages:
ray==1.13.0
torch==1.12.1

In my case, the error occurred when RLlib tried to convert an item of None from optimizer variables to torch tensors.

My solution was to upgrade ray to 2.0.0, as I noticed there's a branch dealing with the None value case: https://github.com/ray-project/ray/blob/da50ef4986a70e1f764bdbfb72c6cbff35f03130/rllib/utils/torch_utils.py#L130
