### ISSUE TITLE
[runtime_env] Support setting runtime_env in @ray.remote decorator

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#16659] opened 2021-06-24 17:04 UTC
```
In [3]: @ray.remote(runtime_env={"env_vars": {"hi": "hi"}})                                        
   ...: def f():                                                                                   
   ...:     pass                                                                                   
   ...:                                                                                            
---------------------------------------------------------------------------                        
AssertionError                            Traceback (most recent call last)                        
<ipython-input-3-eb42742f8850> in <module>                                                         
----> 1 @ray.remote(runtime_env={"env_vars": {"hi": "hi"}})                                        
      2 def f():                                                                                   
      3     pass
      4 

~/code/ray/python/ray/worker.py in remote(*args, **kwargs)
   1949     assert len(args) == 0 and len(kwargs) > 0, error_string
   1950     for key in kwargs:
-> 1951         assert key in [
   1952             "num_returns",
   1953             "num_cpus",

AssertionError: The @ray.remote decorator must be applied either with no arguments and no parenthes
es, for example '@ray.remote', or it must be applied using some of the arguments 'num_returns', 'nu
m_cpus', 'num_gpus', 'memory', 'object_store_memory', 'resources', 'max_calls', or 'max_restarts', 
like '@ray.remote(num_returns=2, resources={"CustomResource": 1})'.
```

**Comment by architkulkarni** [comment] 2021-06-24 18:15
Duplicate of https://github.com/ray-project/ray/issues/15374

**Closed by architkulkarni** 2021-06-24 18:15 UTC
Labels: P1, bug
