### ISSUE TITLE
[AIR] Fix  //doc/source/tune/examples:sigopt_example

### ISSUE THREAD

**Issue by jiaodong** [ray-project/ray#27203] opened 2022-07-28 19:03 UTC
### What happened + What you expected to happen

Notebook is broken due to missing permission first, maybe more issues down the road. @Yard1 looked into it earlier and we're creating this issue to keep track of it.

### Versions / Dependencies

master

### Reproduction script

`bazel test //doc/source/tune/examples:sigopt_example`

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by Yard1** [comment] 2022-07-28 23:34
Duplicate of https://github.com/ray-project/ray/issues/26567

**Closed by Yard1** 2022-07-28 23:34 UTC
Labels: bug, air
