### ISSUE TITLE
[Serve] working_dir cannot be used with Azure DevOps

### ISSUE THREAD

**Issue by mfojtak** [ray-project/ray#40409] opened 2023-10-17 17:04 UTC
### What happened + What you expected to happen

working_dir forces the URL path to end with ".zip". This cannot be done with DevOps git repositories.
DevOps git repo URL looks like this:

https://dev.azure.com/[org]/[project]/_apis/git/repositories/[repo]/items?versionDescriptor[version]=main&resolveLfs=true&$format=zip&download=true

The path of URL above is zip file but does not end with ".zip" and therefore error is thrown:
"Only .zip files supported for remote URIs."

This is due to bug in python/ray/_private/runtime_env/working_dir.py:

```python
if protocol in Protocol.remote_protocols() and not path.endswith(".zip"):
            raise ValueError("Only .zip files supported for remote URIs.")
```

### Versions / Dependencies

Ray 2.7.1

### Reproduction script

This could be reproduced by setting working_dir to Azure DevOps zip file as described in What happened section.

### Issue Severity

High: It blocks me from completing my task.

**Comment by GeneDer** [comment] 2023-10-17 23:20
Hi @mfojtak I don't think we support Azure just yet. Currently AWS and GCP are recommended platforms. I don't really have access to Azure as well (but my guess is you can probably do a curl to follow the redirect and get the .zip url). 

I would also recommend you push the code into github.com and then you can pull the source code zip like http://github.com/[user]/[repository]/archive/master.zip

**Comment by mfojtak** [comment] 2023-10-18 06:07
Hi @GeneDer , this is not about supporting Azure. My Kube cluster is in EKS (AWS) and code in private corporate DevOps. Cannot be migrated to Github. The problem is the path.endswith(".zip") condition which doesn't make sense as the zip file might be available on URLs not satisfying this condition.

**Comment by GeneDer** [comment] 2023-10-18 15:09
@mfojtak So I was reading [the doc](https://docs.ray.io/en/latest/ray-core/handling-dependencies.html#api-reference) a bit more and I think this is by design. I also don't have permission to change this as it's not really a serve issue, this is more on how ray core works. 

To solve your specific issue, can you speak more on how you use it? If this is running locally, you should be able to download the zip file and just use local path? If it's on a pipeline sort of setup, maybe you can have a step before this to download the zip file and/or resolve the url to a .zip url?

**Comment by mfojtak** [comment] 2023-10-18 16:39
> @mfojtak So I was reading [the doc](https://docs.ray.io/en/latest/ray-core/handling-dependencies.html#api-reference) a bit more and I think this is by design. I also don't have permission to change this as it's not really a serve issue, this is more on how ray core works.
> 
> To solve your specific issue, can you speak more on how you use it? If this is running locally, you should be able to download the zip file and just use local path? If it's on a pipeline sort of setup, maybe you can have a step before this to download the zip file and/or resolve the url to a .zip url?

I need to use working_dir with Serve. Specifically with RayService where the remote URI is the only option. So there is no way to download locally. Therefore it is a show-stopper for me.

**Comment by GeneDer** [comment] 2023-10-18 16:44
Hmm that still doesn't explain the usage tho. All I can tell is you are probably not running this locally? Is this on a CI/ CD that you can add a step? Also would be nice if you can share one of those url so I can test some things out.

**Comment by GeneDer** [comment] 2023-10-18 17:20
It's hard to test like this. As a workaround does that api support something like this?  [https://dev.azure.com/[org]/[project]/_apis/git/repositories/[repo]/items?versionDescriptor[version]=main&resolveLfs=true&$format=zip&download=true&foo=.zip](https://dev.azure.com/%5Borg%5D/%5Bproject%5D/_apis/git/repositories/%5Brepo%5D/items?versionDescriptor%5Bversion%5D=main&resolveLfs=true&$format=zip&download=true&foo=.zip )

**Comment by mfojtak** [comment] 2023-10-19 06:22
> It's hard to test like this. As a workaround does that api support something like this? [https://dev.azure.com/[org]/[project]/_apis/git/repositories/[repo]/items?versionDescriptor[version]=main&resolveLfs=true&$format=zip&download=true&foo=.zip](https://dev.azure.com/%5Borg%5D/%5Bproject%5D/_apis/git/repositories/%5Brepo%5D/items?versionDescriptor%5Bversion%5D=main&resolveLfs=true&$format=zip&download=true&foo=.zip)

Yes - you can add foo=.zip but .zip needs to be in *path* part of the URL. 
path.endswith(".zip") throws the same error

**Comment by GeneDer** [comment] 2023-10-19 16:51
Hi @mfojtak I can't think of any other workaround at the moment. I'm guessing you are also not allowed to build and upload a wheel as well😅 At this point I would suggest the best way forward it to contribute to Ray's codebase following this [guide](https://docs.ray.io/en/latest/ray-contribute/getting-involved.html) and see how the team feels about dropping this validation.

**Comment by mfojtak** [comment] 2023-10-20 11:01
Hi @GeneDer I have even created a proxy server such that the url ends with .zip. First problem with this is that serve doesn't even accept "http" protocol. So I created https with self signed certificate only to find out serve fails there as well. So I have hit a concrete wall. In my humble opinion - this is a BUG.
Regarding contribution - I do not have expertise to do this. Is there any other option?

**Comment by GeneDer** [comment] 2023-10-20 17:14
@mfojtak So I was testing a bit more with the Kuberay with Ray Serve. You should be able to just use `{ }` as the runtime env like the following. This should use the files in the docker image instead of looking up on the remote location
```
  serveConfigV2: |
    applications:
      - name: mobilenet
        import_path: mobilenet.mobilenet:app
        runtime_env: { }
```
Then given you are brining in your own docker image built with this code, you should be able to start Serve! Please give it a try!!

**Comment by mfojtak** [comment] 2023-10-21 06:45
> @mfojtak So I was testing a bit more with the Kuberay with Ray Serve. You should be able to just use `{ }` as the runtime env like the following. This should use the files in the docker image instead of looking up on the remote location
> 
> ```
>   serveConfigV2: |
>     applications:
>       - name: mobilenet
>         import_path: mobilenet.mobilenet:app
>         runtime_env: { }
> ```
> 
> Then given you are brining in your own docker image built with this code, you should be able to start Serve! Please give it a try!!

It assumes that everytime I change the code - I have to rebuild the image. working_dir is more convenient alternative. But unfortunately, it is not working properly. Would it help to move the issue to the "Core" label?

**Comment by GeneDer** [comment] 2023-10-23 16:22
@mfojtak The dockerfile I use to test looks like this 
```
# Use Anyscale base image
FROM anyscale/ray:nightly-py310

# Install dependencies
RUN pip install --upgrade pip && pip install -U torch==2.0.1 torchvision==0.15.2

WORKDIR /home/ray

# Copy local code including protobuf and service definitions into docker image
COPY . /home/ray

# Add working directory into python path so they are importable
ENV PYTHONPATH=/home/ray
```
You do not need to build your code into a library. Simply copy the code into a python importable path (or adding the working directory into the python path in this example), then you should be able to call it from the `import_path` config yaml. I think if you just leave `runtime_env` as an empty json then it will use local path. 

Since there are existing issues talking about modifying the `working_dir` logics, I don't think we need duplicated tickets for those. If you have more issue related to how Ray Serve, I'm happy to dive deeper. Else let's close this issue and comment on the other issues for the specifics. Feel free to reopen if you have more Serve specific issues 🙂

**Closed by GeneDer** 2023-10-23 16:22 UTC
Labels: serve

**Comment by mfojtak** [comment] 2023-10-25 15:30
Why is this marked as closed?
I understand that I can have custom image built but this bug report was about working_dir functionality. Which in my opinion has some issues not covered by any existing tickets - ".zip" issue and missing http protocol issue.

**Comment by GeneDer** [comment] 2023-10-25 16:33
To my understanding this issue is to how to use working_dir with Ray Serve, and there are a few suggested solutions in this thread to get your code working. If the issue is to change the behavior behind how `working_dir` works, then it's beyond Serve's ability to make the change as it's a core issue that affect all stacks. There are existing proposed design changes as you pointed out in https://github.com/ray-project/ray/issues/26784 and https://github.com/ray-project/ray/issues/33456. Please comment on those existing issues so they don't get duplicated and distributed. Again, this is not a "bug", it's a feature designed to prevent users from passing invalid urls. Totally understand there are improvements can be made, so please put your suggestions to those other design proposals so they can be included when the new logics are implemented.
