### ISSUE TITLE
[<Ray component: Core|RLlib|etc...>] 

### ISSUE THREAD

**Issue by zusne** [ray-project/ray#27015] opened 2022-07-26 14:52 UTC
### What happened + What you expected to happen

 ERROR worker.py:431 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SACLearnerWithCost.__init__() (pid=4301, ip=202.141.180.14)
(TemporaryActor pid=4301)   At least one of the input arguments for this task could not be computed:
(TemporaryActor pid=4301) ray.exceptions.RaySystemError: System error: No module named 'policy'
(TemporaryActor pid=4301) traceback: Traceback (most recent call last):
(TemporaryActor pid=4301)   File "/home/lsj/anaconda3/envs/safety_rl/lib/python3.7/site-packages/ray/serialization.py", line 281, in deserialize_objects
(TemporaryActor pid=4301)     obj = self._deserialize_object(data, metadata, object_ref)
(TemporaryActor pid=4301)   File "/home/lsj/anaconda3/envs/safety_rl/lib/python3.7/site-packages/ray/serialization.py", line 194, in _deserialize_object
(TemporaryActor pid=4301)     return self._deserialize_msgpack_data(data, metadata_fields)
(TemporaryActor pid=4301)   File "/home/lsj/anaconda3/envs/safety_rl/lib/python3.7/site-packages/ray/serialization.py", line 172, in _deserialize_msgpack_data
(TemporaryActor pid=4301)     python_objects = self._deserialize_pickle5_data(pickle5_data)
(TemporaryActor pid=4301)   File "/home/lsj/anaconda3/envs/safety_rl/lib/python3.7/site-packages/ray/serialization.py", line 162, in _deserialize_pickle5_data
(TemporaryActor pid=4301)     obj = pickle.loads(in_band)
(TemporaryActor pid=4301) ModuleNotFoundError: No module named 'policy'

### Versions / Dependencies

ray==1.12.0

### Reproduction script

.

**Comment by kouroshHakha** [comment] 2022-07-27 23:48
Please provide more information on this issue. It's not clear what the problem is.

**Comment by jjyao** [comment] 2022-08-11 16:41
I'll close the issue since it doesn't have enough information to see what the problem is.

Feel free to provide more information and reopen the issue.

**Closed by jjyao** 2022-08-11 16:41 UTC
Labels: bug, triage, @author-action-required
