### ISSUE TITLE
[core] Possible memory leak in async actor implementation

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#38591] opened 2023-08-17 22:07 UTC
@shrekris-anyscale and I have been trying to track down a memory leak issue happening across multiple serve components. All of them are async actors and the growth only happens when actor calls are being made, so it lines up that it could be a memory leak related to async actor calls.

I ran a minimal script to send batches of many async actor calls and memory appears to be consistently growing. This is running on nightly wheels, commit sha: `0b8fd1d6dd7e83656713b21bb408fa7f04244bfb`.

Repro script (pinning to head node):
```python
import ray

@ray.remote
class A:
    async def hi(self):
        return "hi"

a = A.options(resources={"node:10.0.62.86": 0.1}).remote()

while True:
    ray.get([a.hi.remote() for _ in range(10000)])
```

Memory growth over 3 hours:
![Screen Shot 2023-08-17 at 5 05 49 PM](https://github.com/ray-project/ray/assets/9871461/841326e0-3469-4dff-b4f6-1d9f40d73d29)

Link to the workspace where this is currently running (I plan to leave it going overnight, please don't touch):

- https://console.anyscale-staging.com/o/anyscale-internal/workspaces/expwrk_czchm1deg9ecnvv44a5cnl3gq6/ses_vw8ax7ielka9scsy8m38iu2lbg

For reference, here is a run of the same script but dropping the `async def`:
```python
import ray

@ray.remote
class A:
    def hi(self):
        return "hi"

a = A.options(resources={"node:10.0.62.86": 0.1}).remote()

while True:
    ray.get([a.hi.remote() for _ in range(10000)])
```
![Screen Shot 2023-08-17 at 5 06 29 PM](https://github.com/ray-project/ray/assets/9871461/c292d2b4-3a8d-488c-8f4d-57cf13dba8e8)

**Comment by rkooo567** [comment] 2023-08-17 22:27
> Link to the workspace where this is currently running (I plan to leave it going overnight, please don't touch):

@edoakes can you run memray --native on this actor and share the memory profiling files as well?

**Comment by rkooo567** [comment] 2023-08-17 22:27
(maybe we can run 2 cluster, one with memray, one without?)

**Comment by edoakes** [comment] 2023-08-17 23:42
@rkooo567 here are two profile flame graphs. The second is from ~10min after the first.

[leak_repro_17_10pm.html.zip](https://github.com/ray-project/ray/files/12374136/leak_repro_17_10pm.html.zip)
[leak_repro_17_22pm.html.zip](https://github.com/ray-project/ray/files/12374130/leak_repro_17_22pm.html.zip)

**Comment by edoakes** [comment] 2023-08-18 16:52
Left the test running overnight. Unfortunately it was killed by a GC bot around 04:00. Doesn't look like linear growth, but the instability is concerning even if it levels out at some point.

<img width="1431" alt="Screen Shot 2023-08-18 at 11 50 55 AM" src="https://github.com/ray-project/ray/assets/9871461/2aa3b080-1d23-4c79-86fb-82e6cc5809e1">

**Comment by rynewang** [comment] 2023-08-18 19:35
doing a quick run with a sync actor and an async actor in a same cluster. Looks like they are taking ~the same memory:

![image](https://github.com/ray-project/ray/assets/56065503/e3c7ef09-d49b-4b17-93fd-cbcc1beb313e)

**Comment by rynewang** [comment] 2023-08-18 19:46
Async actor's memory keeps going up. Reproduced

![image](https://github.com/ray-project/ray/assets/56065503/4879b783-3343-4034-a202-406098d980e4)

**Comment by edoakes** [comment] 2023-08-23 22:01
Ok, I believe we've narrowed down that this is an issue related to `max_concurrency` / concurrency groups. Here's the updated repro:

```
import asyncio
import random
import time

import ray
from ray import serve

@ray.remote(concurrency_groups={"TEST_CONCURRENCY_GROUP": 1})
class Executor:
    @ray.method(concurrency_group="TEST_CONCURRENCY_GROUP")
    async def hi(self):
        return "hi"


@ray.remote
class Caller:
    def __init__(self, executors):
        self._executors = executors

        self._task = asyncio.create_task(self.run())

    async def run(self):
        for i in range(1000000):
            start = time.time()
            print(f"Starting iteration {i}!")
            await asyncio.gather(*[self.do_calls() for _ in range(1000)])
            print(f"Iteration finished in {time.time()-start}s. Sleeping for 30s.")
            time.sleep(30)

    async def do_calls(self):
        for _ in range(100):
            result = await random.choice(self._executors).hi.remote()

executors = [Executor.remote() for _ in range(10)]
callers = [Caller.remote(executors) for _ in range(20)]

import time;time.sleep(1000000000)
```

With this, there's a clear leak in the `Executor` actors:
<img width="1433" alt="Screen Shot 2023-08-23 at 3 02 25 PM" src="https://github.com/ray-project/ray/assets/9871461/c4d317c8-1f1b-483b-b147-16ad36bc6700">

**Comment by iycheng** [comment] 2023-08-23 22:18
Assign it to Ruiyang since he is working on this one activately.

**Comment by edoakes** [comment] 2023-08-23 22:47
FYI:
```
>>> import ray
>>> ray.__version__
'3.0.0.dev0'
>>> ray.__commit__
'329b409b54c7dcb2801a102f74702e61be2d8872'
>>> 
```

**Comment by jjyao** [comment] 2023-08-25 04:14
<img width="876" alt="Screenshot 2023-08-24 at 9 10 57 PM" src="https://github.com/ray-project/ray/assets/898023/c1ae8f2f-bd17-413e-b21f-2990dfa3e658">

Seems using jemalloc fixed the "memory leak"

```
import ray
from ray import serve

ray.init()

@ray.remote(concurrency_groups={"TEST_CONCURRENCY_GROUP": 1}, runtime_env={"env_vars": {
    "LD_PRELOAD": "/usr/lib/x86_64-linux-gnu/libjemalloc.so.2"}})
class Executor:
    @ray.method(concurrency_group="TEST_CONCURRENCY_GROUP")
    async def hi(self):
        return "hi"


@ray.remote
class Caller:
    def __init__(self, executors):
        self._executors = executors

        self._task = asyncio.create_task(self.run())

    async def run(self):
        for i in range(1000000):
            start = time.time()
            print(f"Starting iteration {i}!")
            await asyncio.gather(*[self.do_calls() for _ in range(1000)])
            print(f"Iteration finished in {time.time()-start}s. Sleeping for 30s.")
            time.sleep(30)

    async def do_calls(self):
        for _ in range(100):
            result = await random.choice(self._executors).hi.remote()

executors = [Executor.remote() for _ in range(10)]
callers = [Caller.remote(executors) for _ in range(20)]

import time;time.sleep(1000000000)
```

**Comment by jjyao** [comment] 2023-08-25 05:40
<img width="884" alt="Screenshot 2023-08-24 at 10 40 00 PM" src="https://github.com/ray-project/ray/assets/898023/c468c96b-714f-452a-88dd-6da5b91a16e9">

Left is with jemalloc, right is without jemalloc

**Comment by edoakes** [comment] 2023-08-25 14:13
@jjyao interesting... does this mean it's likely to also be some kind of memory fragmentation issue similar to what @iycheng saw in the GCS? We can try re-running the full serve repro using jemalloc to see if it also addresses that problem.

**Comment by edoakes** [comment] 2023-08-25 15:17
Re-testing:

- Client workspace: https://console.anyscale-staging.com/o/anyscale-internal/workspaces/expwrk_wdi23ygrdl9ttmeza1hsla2x29/ses_qncnpbtbnfk2mnw8lrnmqhld1b?workspaces-tabs=terminal
- Service: https://console.anyscale-staging.com/o/anyscale-internal/services/service2_tvbsdnk3fcwcy9k35hwdu6rhfx
- Service using this env: https://console.anyscale-staging.com/o/anyscale-internal/configurations/app-config-details/bld_2kl35knaclquguegurqvxicpka

**Comment by edoakes** [comment] 2023-08-25 15:32
On the cluster:

- Checked `/proc/<http_proxy_pid>/environ` and `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2`
- Checked that `/usr/lib/x86_64-linux-gnu/libjemalloc.so.2` exists

**Closed** 2023-09-07 23:03 UTC
Labels: bug, release-blocker, P0, core
