### ISSUE TITLE
[autoscaler]  Improper patching of logging makeRecord

### ISSUE THREAD

**Issue by shayanhoshyari** [ray-project/ray#34796] opened 2023-04-26 19:32 UTC
### What happened + What you expected to happen

Ray is not using the proper way to patch the `logging.makeLogRecord` function. So when users try to repatch the function via pythonic way (`logging.getLogRecordFactory` and `logging.setLogRecordFactory`) it will not work for them.

We would need to use a non pythonic way (follow what ray is doing) to patch the makeLogRecord function, this is brittle, as if ray changes how it does the patching, user code breaks. But if ray uses the proper way, consistency is ensured.

__use case__: I would like to include more information in the log record such as what request id (rest request id) is being processed, so that grabbing logs in splunk is easier. I store that in the [ContextVar](https://docs.python.org/3/library/contextvars.html) so different coroutines can have different values of this global context. I then in the logger.log want to include the request being processed in current coroutine into the log. I don't want people to need to be careful to include this info manually and I want it to be automatic.

### Versions / Dependencies

- ray: 2.4.0
- python: 3.10

### Reproduction script

Here is a simple deployment

`app.py`:
```py
import logging 
from functools import wraps

logger = logging.getLogger(__name__)

def setup_logging():
   logger.basicConfig("INFO")

    default_factory = logging.getLogRecordFactory()

    @wraps(default_factory)
    def record_factory(*args, **kwargs):
        record = default_factory(*args, **kwargs)
        print("Using patched record factory")
        # in practice: attach more info here from global contextvar.
        return record

    logging.setLogRecordFactory(record_factory)



@ray.serve.deployment
class MyDeployment:
    def __init__(self) -> None:
        setup_logging()

    async def __call__(self, request: Request) -> str:
        logger.info("[logger normal - info] Received request - processing")
        return f"Got {request}"

deploy = MyDeployment.bind()

if __name__ == "__main__":
    ray.init()
    ray.serve.start(detached=True)
    ray.serve.run(deploy)
    try:
        while True:
            time.sleep(10)
    finally:
        logger.info("Shutting down ray.")
        ray.shutdown()

```

If you run
```
python app.py
curl http://127.0.0.1:8000 
```

You will never see `Using patched record factory` printed. The reason is that ray also patches makeRecord, but instead of using the pythonic way of `logging.getLogRecordFactory()` and `logging.setLogRecordFactory()` it directly changes `logging.Logger.makeRecord` at [ray/autoscaler/_private/cli_logger.py](https://github.com/ray-project/ray/blob/releases/2.4.0/python/ray/autoscaler/_private/cli_logger.py#L146). This will make the python ways of repatching the logger useless.

If you replace the patch snipped with

```py
    default_factory = logging.Logger.makeRecord

    @wraps(default_factory)
    def record_factory(*args, **kwargs):
        record = default_factory(*args, **kwargs)
        print("Using patched record factory")
        return record

    logging.makeLogRecord = record_factory

```
It starts working. But this way it is brittle and it can break in future if ray decides to changes how it does the patching of makerecord.

### Issue Severity

Low: It annoys or frustrates me.

**Comment by rkooo567** [comment] 2023-04-27 14:01
In the master unless you use `ray.autoscaler.sdk` APIs, you shouldn't see this anymore. The actual root cause will be handled by @peytondmurray

**Comment by shayanhoshyari** [comment] 2023-04-28 04:48
Thanks, yes I see in 2.4.0, things look much better now, and since I don't import `ray.autoscaler.sdk` I can now use `logging.set/getLogRecordFactory`

**Comment by peytondmurray** [comment] 2023-11-28 21:23
Looks like this one has been completed. Closing for now, but if this needs to be reopened please feel free to comment.

**Closed by peytondmurray** 2023-11-28 21:23 UTC
Labels: bug, P1, observability-ux
