### ISSUE TITLE
how to kill an actor

### ISSUE THREAD

**Issue by raopku** [ray-project/ray#456] opened 2017-04-12 03:50 UTC
The actors takes up GPU. And after training, it does not release resource. How to kill the Actor Process from Ray's API instead of using the command kill -9 pid.

**Comment by robertnishihara** [comment] 2017-04-12 04:12
Can you elaborate on your use case a bit? I can think of two relevant situations.

1. You are using Ray in the cluster setting. You have a script that creates an actor, does some stuff, and then exits. This hasn't been implemented yet, but the actor should be killed when the script exits. This is being tracked in #376 and will be implemented soon.

2. You have a script that creates an actor. Then you want to kill that actor within the same script and reuse its resources for something else. We still need to decide on the right API for this. One option is to have the actor's destructor do the right thing (so you could kill the actor with a statement like `del actor`), but currently it isn't possible.

Are you trying to do one of those two things?

**Comment by raopku** [comment] 2017-04-12 10:02
I mean the second case. and I have found the first case the first day i use ray.
for example, in notebook:
```
gpu_actor = ray.actor(num_gpus=1)(Actor)
agents =[gpu_actor() for _ in range(4)]

do some training here.
```
if i exectute the code again in notebook, some errors of no enough gpu to start new actor occur. The reason is obvious that the previous four actor are still alive.

I think there is a need of API to kill actor instead of exit the script.

What do you think about different users start differet drivers, and every driver start their own actors, then the process running on the machine will grow up rapidly.

**Comment by febert** [comment] 2017-05-07 21:34
Is there already a solution to kill the actors when a running a script? When I do ctrl-C on my script and even  when I close the terminal the actors keep running.

**Comment by robertnishihara** [comment] 2017-05-07 21:57
That's surprising, the actors *should* die when the script exits. Just to confirm, you are using a recent version of Ray, right (e.g., from the last week or two)? This was done in #462 and #490.

Do you have a simple instructions for reproducing the problem?

**Comment by robertnishihara** [comment] 2017-07-14 20:46
Closing because I believe this has been fixed. Also note that when an actor handle goes out of scope, a task will be run on the actor that kills the actor (as of #617).

**Closed by robertnishihara** 2017-07-14 20:46 UTC
