### ISSUE TITLE
[tune] Result logs color

### ISSUE THREAD

**Issue by marlonjan** [ray-project/ray#3653] opened 2018-12-28 11:29 UTC
Hi all,

Thanks for creating Ray, Tune, and RLlib!

This may be a bit subjective, but I wanted to report that I am always a bit irritated by the red color of the Tune result logging output. Red always looks like a warning or error message to me. Does anyone else feel that way? 

Having said that, it's totally sensible to have the results emphasized in some color to make it nice and visible! Could it be green instead? I think that could make the Ray experience even more joyful!

Thanks & best regards,
Marlon

**Comment by ericl** [comment] 2018-12-28 11:34
Oh that's interesting, I don't think that's intentional. Could you post your system info / a screenshot?

**Comment by marlonjan** [comment] 2018-12-28 14:10
Hi Eric,

Your reply made me realize it might have to do something with my IDE. IntelliJ IDEA seems to colorize some output (but not all). I thought it was red for everyone, but I can confirm that it's _not_ red in a normal terminal window on a Mac.

Here is a screenshot of the logs in IntelliJ:

![image](https://user-images.githubusercontent.com/9771046/50517582-3ec38180-0ab1-11e9-8f1a-20c2740dc89d.png)

**Comment by ericl** [comment] 2018-12-28 22:16
This might be fixed by https://github.com/ray-project/ray/issues/3636 then. The issue is probably that the default logger goes to stderr, which may need treated as errors by intellij.

**Closed** 2019-01-06 21:20 UTC
