### ISSUE TITLE
Simple custom TF model crash in 2-GPU mode

### ISSUE THREAD

**Issue by Antymon** [ray-project/ray#9844] opened 2020-07-31 14:39 UTC
### What is the problem?

I was trying to use custom TF models in a 2-GPU mode but failed miserably due to the following error:
`tensorflow.python.framework.errors_impl.InternalError: Constraining by assigned device should not cause an error. Original root's assigned device name: /job:localhost/replica:0/task:0/device:GPU:0 node's assigned device name "/job:localhost/replica:0/task:0/device:GPU:1. Error: Cannot merge devices with incompatible ids: '/job:localhost/replica:0/task:0/device:GPU:0' and '/job:localhost/replica:0/task:0/device:GPU:1'`
Tested with 2 different machines: local one with 8 V100 GPUs and GCP instance with 2 K4 GPUs. Both cases result in the same crash.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray `0.8.6`
Python `3.6.9`
TF `2.2.0+nv`
Ubuntu `18.04`

### Reproduction (REQUIRED)

I created a minimal crash example for rllib `0.8.6` where I take an atari example and use a custom model which is a copied over `VisionNetwork` with a single extra FC layer in the V head. Without extra layer, an example runs fine across 2 GPUs.

Dockerfile:
```
FROM nvcr.io/nvidia/tensorflow:20.07-tf2-py3
WORKDIR /app

# check if nvidia-smi reports GPUs as expected

RUN apt update && apt install -y gcc libsm6 libxext6 \
    libxrender1 libgl1-mesa-dev libxrandr2 rsync \
    libxcursor-dev libxinerama1 git libgeos-dev && \
    rm -rf /var/lib/apt/lists/*

RUN pip install ray[tune,rllib]==0.8.6

RUN wget https://github.com/ray-project/ray/files/5007529/failing_tf_multigpu.zip

RUN unzip failing_tf_multigpu.zip

ENTRYPOINT bash
```
And inside call `python train_atari.py`

[failing_tf_multigpu.zip](https://github.com/ray-project/ray/files/5007529/failing_tf_multigpu.zip)

Full stack:
ray::PPO.train() (pid=20316, ip=172.17.0.3)
  File "python/ray/_raylet.pyx", line 407, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 442, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 445, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 400, in ray._raylet.execute_task.function_executor
  File "/usr/local/lib/python3.6/dist-packages/ray/rllib/agents/trainer_template.py", line 90, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/usr/local/lib/python3.6/dist-packages/ray/rllib/agents/trainer.py", line 450, in __init__
    super().__init__(config, logger_creator)
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/trainable.py", line 175, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/usr/local/lib/python3.6/dist-packages/ray/rllib/agents/trainer.py", line 623, in _setup
    self._init(self.config, self.env_creator)
  File "/usr/local/lib/python3.6/dist-packages/ray/rllib/agents/trainer_template.py", line 125, in _init
    self.train_exec_impl = execution_plan(self.workers, config)
  File "/usr/local/lib/python3.6/dist-packages/ray/rllib/agents/ppo/ppo.py", line 198, in execution_plan
    _fake_gpus=config["_fake_gpus"]))
  File "/usr/local/lib/python3.6/dist-packages/ray/rllib/execution/train_ops.py", line 152, in __init__
    self.per_device_batch_size, policy.copy))
  File "/usr/local/lib/python3.6/dist-packages/ray/rllib/execution/multi_gpu_impl.py", line 92, in __init__
    len(input_placeholders)))
  File "/usr/local/lib/python3.6/dist-packages/ray/rllib/execution/multi_gpu_impl.py", line 292, in _setup_device
    graph_obj = self.build_graph(device_input_slices)
  File "/usr/local/lib/python3.6/dist-packages/ray/rllib/policy/dynamic_tf_policy.py", line 301, in copy
    TFPolicy._initialize_loss(instance, loss, loss_inputs)
  File "/usr/local/lib/python3.6/dist-packages/ray/rllib/policy/tf_policy.py", line 265, in _initialize_loss
    self._sess.run(tf.global_variables_initializer())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Constraining by assigned device should not cause an error. Original root's assigned device name: /job:localhost/replica:0/task:0/device:GPU:0 node's assigned device name "/job:localhost/replica:0/task:0/device:GPU:1. Error: Cannot merge devices with incompatible ids: '/job:localhost/replica:0/task:0/device:GPU:0' and '/job:localhost/replica:0/task:0/device:GPU:1'

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by Antymon** [comment] 2020-08-03 11:17
Related to https://github.com/ray-project/ray/issues/6668#issuecomment-610458857

**Comment by Antymon** [comment] 2020-08-17 15:37
In meantime rllib upgraded to `0.8.7`, breaking the attached script even sooner, due to `tf_import`. This is only a migration issue and the original problem remains the same.

**Comment by chokosabe** [comment] 2020-08-27 16:34
Getting this same issue but on a PPO run with tensorflow-gpu and setting use_lstm=True.

**Comment by sven1977** [comment] 2021-08-23 12:42
Marking this as a duplicate of https://github.com/ray-project/ray/issues/7747, in which I describe a one-line fix.
PR coming up ...

**Comment by sven1977** [comment] 2021-08-23 12:42
@Antymon ^^

**Closed by sven1977** 2021-08-23 12:42 UTC
Labels: bug, P2
