### ISSUE TITLE
[RLlib] check for gym env should assume `issubclass` instead of `isinstance`

### ISSUE THREAD

**Issue by thoth291** [ray-project/ray#32697] opened 2023-02-21 15:37 UTC
### What happened + What you expected to happen

Given the code example here: https://github.com/ray-project/ray/blob/master/rllib/examples/custom_env.py#L77
I would expect that over here you would check for subclassing: https://github.com/ray-project/ray/blob/master/rllib/utils/pre_checks/env.py#L57

So `custom_env.py` example currently not working.

### Versions / Dependencies

Ray: 2.2.0
Python: 3.8.12
OS: CentOS Linux release 7.7.1908

### Reproduction script

Just run custom_env.py from your examples - listed above.

### Issue Severity

High: It blocks me from completing my task.

**Comment by avnishn** [comment] 2023-03-29 23:39
I'm currently not able to reproduce your issue on master -- pressumably this won't be an issue in ray 2.4, so I'm going to close this for now.

**Closed by avnishn** 2023-03-29 23:39 UTC
Labels: bug, P2, rllib
