### ISSUE TITLE
Compilation error on redHat

### ISSUE THREAD

**Issue by coldsheephot** [ray-project/ray#468] opened 2017-04-18 11:22 UTC
Compilation error on redHat:

- Result:
INFO GNU
CMake Error at cmake_modules/CompilerInfo.cmake:62 (message):
  Unknown compiler.  Version info:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)

Call Stack (most recent call first):
  CMakeLists.txt:156 (include)
-- Configuring incomplete, errors occurred!
See also "/root/yangjie/ray2/src/numbuf/thirdparty/arrow/cpp/build/CMakeFiles/CMakeOutput.log".
See also "/root/yangjie/ray2/src/numbuf/thirdparty/arrow/cpp/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    license="Apache 2.0")
  File "/root/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/root/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/root/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 13, in run
    subprocess.check_call(["../build.sh"])
  File "/root/anaconda2/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../build.sh']' returned non-zero exit status 1

- Error
Run Build Command:/usr/bin/make "cmTryCompileExec1115247767/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec1115247767.dir/build.make CMakeFiles/cmTryCompileExec1115247767.dir/build
make[1]: Entering directory `/home/dl/yangjie/ray/src/numbuf/thirdparty/arrow/cpp/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/dl/yangjie/ray/src/numbuf/thirdparty/arrow/cpp/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building CXX object CMakeFiles/cmTryCompileExec1115247767.dir/src.cxx.o
/usr/bin/c++    -g -O3 -march=native -mtune=native -DCXX_SUPPORTS_ALTIVEC   -maltivec -o CMakeFiles/cmTryCompileExec1115247767.dir/src.cxx.o -c /home/dl/yangjie/ray/src/numbuf/thirdparty/arrow/cpp/build/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option '-maltivec'
make[1]: *** [CMakeFiles/cmTryCompileExec1115247767.dir/src.cxx.o] Error 1
make[1]: Leaving directory `/home/dl/yangjie/ray/src/numbuf/thirdparty/arrow/cpp/build/CMakeFiles/CMakeTmp'
make: *** [cmTryCompileExec1115247767/fast] Error 2

- configuration
yum install boost boost-devel boost-doc boost-devel-static
yum update
yum install -y cmake autoconf curl libtool unzip
sudo yum install -y git cmake autoconf curl libtool boost-devel boost-devel-static unzip
sudo yum install -y gcc gcc-c++ make openssl-devel
yum groupinstall "Development Tools"
anaconda,
pip install numpy cloudpickle funcsigs colorama psutil redis flatbuffers
conda install libgcc

**Comment by xhochy** [comment] 2017-04-18 11:54
This looks like a problem in the detection of the compiler version in Arrow: 

```
gcc °æ±¾ 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)
INFO GNU
CMake Error at cmake_modules/CompilerInfo.cmake:62 (message):
Unknown compiler. Version info:

```

Can you raise an issue over at https://issues.apache.org/jira/browse/ARROW and paste the output of 

- `gcc -v`
- `LANG=C gcc -v`

With that info I can have a look at it and try to fix it ;)

**Comment by robertnishihara** [comment] 2017-04-18 20:50
@coldsheephot did you have a chance to create an issue with Arrow? If not, I can make one.

**Comment by robertnishihara** [comment] 2017-04-18 21:06
Ok, I can reproduce the error on a RedHat AMI, I was ablve to solve it with the following.

```
sudo yum install -y gcc gcc-c++ make openssl-devel
```

Can you try that?

Note that once that is solved, compilation of Ray will probably still run into the issues described in #463.

**Comment by coldsheephot** [comment] 2017-04-19 01:23
I  try your configuration, the results are still the same as above。it is not same as the problem 463.

sudo yum update
sudo yum install -y git cmake autoconf curl libtool boost-devel boost-devel-static unzip
sudo yum install -y gcc gcc-c++ make openssl-devel
wget https://repo.continuum.io/archive/Anaconda3-4.3.1-Linux-x86_64.sh
bash Anaconda3-4.3.1-Linux-x86_64.sh
pip install numpy cloudpickle funcsigs colorama psutil redis flatbuffers

**Comment by coldsheephot** [comment] 2017-04-19 01:33
@xhochy 

- [root@SZV1000268092python]# gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
目标：x86_64-redhat-linux
配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
线程模型：posix
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) 

- [root@SZV1000268092 python]# LANG=C gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)

**Comment by raopku** [comment] 2017-04-19 02:39
It seems that the outputs of `gcc -v` and `LANG=C gcc -v` are exactly same.

**Comment by coldsheephot** [comment] 2017-04-19 07:33
@xhochy 
I raise an issue on https://issues.apache.org/jira/browse/ARROW-856?filter=-2.

**Comment by coldsheephot** [comment] 2017-04-19 07:51
@robertnishihara 
what is your gcc version?

**Comment by robertnishihara** [comment] 2017-04-19 08:16
I'm able to compile Arrow on RedHat (using the Amazon Redhat AMI) (without doing much beyond installing the dependencies from #463).

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) 
```

```
$ LANG=C gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) 
```

**Comment by coldsheephot** [comment] 2017-04-19 08:38
@robertnishihara 

I just do the same as you in the other server.
yum update
yum install -y git cmake autoconf curl libtool boost-devel boost-devel-static unzip
yum install -y gcc gcc-c++ make openssl-devel
sh Anaconda2-4.2.0-Linux-x86_64.sh
source ~/.bashrc
pip install  numpy cloudpickle funcsigs colorama psutil redis flatbuffers gym keras tensorflow

but I get the result as above.(Unknown compiler)

**Comment by coldsheephot** [comment] 2017-04-19 10:55
@robertnishihara 
Yes,I try:rm -rf ray/src/numbuf/thirdparty/arrow/cpp/build/*
it does not work

**Comment by wesm** [comment] 2017-04-19 13:31
What version of CMake are you using? It's possible this is locale related.

**Comment by wesm** [comment] 2017-04-19 13:37
It seems something is going wrong in this regular expression

https://github.com/apache/arrow/blob/master/cpp/cmake_modules/CompilerInfo.cmake#L57

I'm interested to know the value of `${COMPILER_VERSION_FULL}` and the CMake version so we can figure out why the regex match is failing

**Comment by coldsheephot** [comment] 2017-04-21 05:47
@wesm 
Yes,Thank you!
I set the  value of ${COMPILER_VERSION_FULL},and I finally slove it.

**Comment by wesm** [comment] 2017-04-21 14:23
@coldsheephot can you please show what was the value of `${COMPILER_VERSION_FULL}` before you changed it?

**Comment by xhochy** [comment] 2017-04-21 14:24
@wesm it should be the following. (at least that's what the CMake file calls)

```$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ```

**Comment by wesm** [comment] 2017-04-21 14:27
Well, something is going wrong (because of unicode / non-ascii characters / console encoding?) on the OP's platform. So I'm curious to see what CMake thinks the value of the variable is

**Comment by wesm** [comment] 2017-04-21 14:28
I guess we could try to repro by installing a RedHat VM with China locale

**Comment by coldsheephot** [comment] 2017-04-22 00:06
@wesm 

- the value of ${COMPILER_VERSION_FULL} is NULL before I changed it.

- but  when I use "gcc -v" ,I can get the following:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ```

- so I set the value of ${COMPILER_VERSION_FULL} 
   export COMPILER_VERSION_FULL=.gcc-version4.8.5.

**Comment by robertnishihara** [comment] 2017-04-23 06:06
Closing because it sounds like it's working now. If not, please reopen the issue!

**Closed by robertnishihara** 2017-04-23 06:06 UTC
