### ISSUE TITLE
[tune] checkpoint_at_end fails to sync final checkpoint for a cluster

### ISSUE THREAD

**Issue by gordoni** [ray-project/ray#13256] opened 2021-01-07 07:26 UTC
Ray version: 1.1.0
OS version: Ubuntu 20.04

Running:

`
rllib train --run=PPO --env=MountainCarContinuous-v0 --config='{"framework": "torch"}' --stop='{"timesteps_total": 10000}' --checkpoint-at-end --ray-address=auto
`

on a cluster fails to sync down any checkpoints, and before terminating reports:

```
2021-01-07 06:03:17,786	ERROR syncer.py:190 -- Sync execution failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/syncer.py", line 186, in sync_down
    result = self.sync_client.sync_down(self._remote_path,
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/sync_client.py", line 212, in sync_down
    return self._execute(self.sync_down_template, source, target)
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/sync_client.py", line 271, in _execute
    stdout=self._get_logfile())
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/sync_client.py", line 201, in _get_logfile
    raise RuntimeError(
RuntimeError: [internalerror] The client has been closed. Please report this stacktrace + your cluster configuration on Github!
2021-01-07 06:03:17,786	ERROR syncer.py:413 -- Trial PPO_MountainCarContinuous-v0_fbae1_00000: Checkpoint sync skipped. This should not happen.
2021-01-07 06:03:17,788	ERROR trial_runner.py:690 -- Trial PPO_MountainCarContinuous-v0_fbae1_00000: Error handling checkpoint /home/ubuntu/ray_results/default/PPO_MountainCarContinuous-v0_fbae1_00000_0_2021-01-07_06-02-54/checkpoint_3/checkpoint-3
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/trial_runner.py", line 682, in _process_trial_save
    self._callbacks.on_checkpoint(
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/callback.py", line 204, in on_checkpoint
    callback.on_checkpoint(**info)
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/syncer.py", line 455, in on_checkpoint
    self._sync_trial_checkpoint(trial, checkpoint)
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/syncer.py", line 428, in _sync_trial_checkpoint
    raise TuneError("Trial {}: Checkpoint path {} not "
ray.tune.error.TuneError: Trial PPO_MountainCarContinuous-v0_fbae1_00000: Checkpoint path /home/ubuntu/ray_results/default/PPO_MountainCarContinuous-v0_fbae1_00000_0_2021-01-07_06-02-54/checkpoint_3/checkpoint-3 not found after successful sync down.
```

This is on a slightly non-standard AWS cluster configuration:

```
ray start --head --autoscaling-config=cluster.yaml --num-cpus=0 --num-gpus=0
```

but I don't think the cluster configuration is the cause of the issue. Nor do I think it has to do with my use of torch.

The problem seems to have been introduced by the fix for issue #12227. The first tune/trial_runner.py on_trial_complete callback needs to be deferred until later.

**Comment by krfricke** [comment] 2021-02-26 14:25
Hey @gordoni, I can't reproduce the issue on a cluster running on the latest wheels. Could you try those out (or release 1.2) and report if the issue still comes up?

For reference, this is my autoscaler config:

```
cluster_name: ray-tune-sync-debug

max_workers: 1
upscaling_speed: 1

idle_timeout_minutes: 0

docker:
    image: rayproject/ray-ml:nightly
    container_name: ray_container
    pull_before_run: true

provider:
    type: aws
    region: us-west-2
    availability_zone: us-west-2a
    cache_stopped_nodes: false

available_node_types:
    cpu_2_ondemand:
        node_config:
            InstanceType: m5.xlarge
        resources: {"CPU": 0}
        min_workers: 0
        max_workers: 0
    cpu_2_spot:
        node_config:
            InstanceType: m5.xlarge
            InstanceMarketOptions:
                MarketType: spot
        resources: {"CPU": 4}
        min_workers: 1
        max_workers: 1

auth:
    ssh_user: ubuntu

head_node_type: cpu_2_ondemand
worker_default_node_type: cpu_2_spot

setup_commands: []
```

(the `CPU: 0` sets the head node CPUs to 0 so we train on the worker node)

**Comment by krfricke** [comment] 2021-03-02 08:40
I'll close this for now, but feel free to re-open if the issue persists and can be reproduced on latest master.

**Closed by krfricke** 2021-03-02 08:40 UTC
Labels: needs-repro-script
