### ISSUE TITLE
[AIR] - StreamSplitDataIterator(epoch=-1, split=0) blocked waiting on other clients for more than 30s.

### ISSUE THREAD

**Issue by afogarty85** [ray-project/ray#41973] opened 2023-12-17 17:34 UTC
### What happened + What you expected to happen

There are perhaps several bugs available to the reproducible script:

1. Jobs wont start training when using multiple workers, likely owing to the complaints by the StreamSplitDataIterator. The data / model that I am using is trivially small (alpaca) but its unclear what is delaying training. The CPUs sit around 20% usage for 30 minutes until timeout.
```
[36m(SplitCoordinator pid=2108, ip=10.0.0.18)[0m StreamSplitDataIterator(epoch=-1, split=0) blocked waiting on other clients for more than 30s. All clients must read from the DataIterator splits at the same time. This warning will not be printed again for this epoch.
[36m(RayTrainWorker pid=1856, ip=10.0.0.21)[0m 
  0%|          | 0/38000 [00:00<?, ?it/s][32m [repeated 7x across cluster][0m
[36m(RayTrainWorker pid=2300)[0m [E ProcessGroupNCCL.cpp:828] [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=26, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1800251 milliseconds before timing out.
```

2. This is perhaps a deepspeed issue when trying to use "auto" parameters, but worth mentioning and only seems to cause problems with zero 3 rather than 2.
```
AssertionError: Check batch related parameters. train_batch_size is not equal to micro_batch_per_gpu * gradient_acc_step * world_size 32 != 4 * 1 * 1
```

3. If no function is passed to collate_fn in iter_torch_batches -- we get this error. Interestingly, an empty function passes this check. I could get this far training on a single worker.

```
TypeError: can't convert np.ndarray of type numpy.str_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

```

### Versions / Dependencies

ray[air]==2.8.1
trl==0.7.4
deepspeed==0.12.5
accelerate==0.25.0
transformers==4.36.1

### Reproduction script

```
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
)
import torch
import ray
import numpy as np
from trl import SFTTrainer
from transformers import TrainingArguments
from datasets import load_dataset, interleave_datasets
from azureml.core import Run
from ray.train.huggingface.transformers import prepare_trainer, RayTrainReportCallback
from ray.train.torch import TorchTrainer, TorchConfig
from ray.train import RunConfig, ScalingConfig, CheckpointConfig, DataConfig, Checkpoint
import os
torch.backends.cuda.matmul.allow_tf32 = True


def collate_fn(examples):
    return examples

def train_func(config):
    # tf32
    torch.backends.cuda.matmul.allow_tf32 = True
   
    deepspeed = {
        "fp16": {
            "enabled": "auto"
        },
        "bf16": {
            "enabled": "auto"
        },
        "zero_optimization": {
            "stage": 3,
            "offload_optimizer": {
                "device": "cpu",
                "pin_memory": True
            },
            "offload_param": {
                "device": "cpu",
                "pin_memory": True
            },
            "overlap_comm": True,
            "contiguous_gradients": True,
            "sub_group_size": 1e9,
            "reduce_bucket_size": 5e8,
            "stage3_prefetch_bucket_size": 5e8,
            "stage3_param_persistence_threshold": 1e6,
            "stage3_max_live_parameters": 1e9,
            "stage3_max_reuse_distance": 1e9,
            "stage3_gather_16bit_weights_on_model_save": True,
            "round_robin_gradients": True
        },
        "gradient_accumulation_steps": "auto",
        "gradient_clipping": "auto",
        "steps_per_print": 10,
        "train_batch_size": "auto",
        "train_micro_batch_size_per_gpu": "auto",
        "wall_clock_breakdown": False
    }

    tokenizer = AutoTokenizer.from_pretrained(
        "facebook/opt-350m",
        add_eos_token=False,
        add_bos_token=False,
        use_fast=True,
    )
    tokenizer.pad_token = tokenizer.eos_token

    train_ds = ray.train.get_dataset_shard("train")
    valid_ds = ray.train.get_dataset_shard("valid")

    train_ds_iterable = train_ds.iter_torch_batches(batch_size=batch_size, collate_fn=collate_fn, prefetch_batches=1,)
    valid_ds_iterable = valid_ds.iter_torch_batches(batch_size=batch_size, collate_fn=collate_fn, prefetch_batches=1,)
    
    def formatting_func(example):
        text = f"{example['instruction']}\n {example['text']}"
        return text

    args = TrainingArguments(
            logging_steps=1,
            save_strategy='steps',
            per_device_train_batch_size=batch_size,
            per_device_eval_batch_size=batch_size,
            gradient_checkpointing=True,
            gradient_accumulation_steps=1,
            learning_rate=5e-4,
            max_steps=38000,
            weight_decay=0.01,
            push_to_hub=False,
            save_steps=1000,
            report_to='none',
            optim="paged_adamw_32bit",
            lr_scheduler_type="constant",
            output_dir="mycloudpath",
            bf16=True,
            tf32=True,
            deepspeed=deepspeed,           
        )

    # SFT
    trainer = SFTTrainer(
        model="facebook/opt-350m",
        model_init_kwargs={
        "torch_dtype": torch.bfloat16,
        "trust_remote_code": True,
    },
        tokenizer=tokenizer,
        train_dataset=train_ds_iterable,
        eval_dataset=valid_ds_iterable,
        formatting_func=formatting_func,
        max_seq_length=2048,
        neftune_noise_alpha=5,
        packing=True,
        args=args,
    )

    trainer.add_callback(RayTrainReportCallback())

    trainer = prepare_trainer(trainer)

    print("Starting training")
    trainer.train()


# dataset settings
ctx = ray.data.context.DatasetContext.get_current()
ctx.use_streaming_executor = False  # also times out with True
ctx.execution_options.verbose_progress = True
options = ray.data.ExecutionOptions(verbose_progress=True, locality_with_output=True, resource_limits=ray.data.ExecutionResources(object_store_memory=160e9))
dataset_config = DataConfig(datasets_to_split=["train", "valid"], execution_options=options)

# data
train_ds = load_dataset("tatsu-lab/alpaca", split="train")
ray_ds = ray.data.from_huggingface(train_ds)
train_ds, valid_ds = ray_ds.train_test_split(test_size=0.1)

batch_size = 4

# trainer
trainer = TorchTrainer(
    train_func,
    scaling_config=ScalingConfig(num_workers=4, use_gpu=True),
    datasets={
        "train": train_ds,
        "valid": valid_ds,
    },
    dataset_config=dataset_config,    
)

result = trainer.fit()



```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by raulchen** [comment] 2023-12-19 00:47
Looks like the issue is because an error happens on one/some of the training workers. Then the data consumption cannot proceed, thus this hanging issue happens. 
Closing this issue for now. as it should be an issue on the app side, not something that needs to be fixed in Ray Data.

**Closed by raulchen** 2023-12-19 00:47 UTC
Labels: bug, triage, data
