### ISSUE TITLE
[RLlib] `agent_collector.py` `_check_view_requirement` bugs on `space.Tuples`

### ISSUE THREAD

**Issue by matteobettini** [ray-project/ray#31594] opened 2023-01-11 14:09 UTC
### What happened + What you expected to happen

The function `_check_view_requirement` triggers a warning (in the future an assertion error) for `space.Tuples` (which have a shape of `None`)

```python
vr.space = spaces.Tuple(Box(-2.0, 2.0, (2,), float32), Box(-2.0, 2.0, (2,), float32))  

if (
        hasattr(vr.space, "shape") # Returns True
        and not vr.space.shape == np.shape(data) # None compared to an actual shape
        and log_once(
            f"view_requirement"
            f"_{view_requirement_name}_checked_in_agent_collector"
        )
    ):
```

### Versions / Dependencies

rllib 2.2.0
gym  0.23.1

### Reproduction script

Any gym environment with `space = spaces.Tuple(Box(-2.0, 2.0, (2,), float32), Box(-2.0, 2.0, (2,), float32))  ` will trigger this

### Issue Severity

Low: It annoys or frustrates me.

**Comment by ArturNiederfahrenhorst** [comment] 2023-01-11 15:42
Duplicate of https://github.com/ray-project/ray/issues/31561
A PR is underway! Thanks for logging this issue 🙂

**Closed by ArturNiederfahrenhorst** 2023-01-11 15:42 UTC
Labels: bug, triage
