### ISSUE TITLE
[CI] `bk://:book: Documentation` is failing/flaky on master.

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#30719] opened 2022-11-29 00:30 UTC
- 579770ad0f7caabccb5ac94b9bd4645af15e480f FAILED [:book: Documentation](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1304#0184c066-6ffe-48e4-8bff-ba1f0be6f685)
- 79783bde769db18679d4815c71ad579060306432 FAILED [:book: Documentation](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1303#0184c061-7f92-4ed9-8922-706bda6bc7fd)
- 24438cd3f4ed2e4abc18dcad218c07a0fbf7b1f3 FAILED [:book: Documentation](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1301#0184c051-f969-4344-834e-90dc8cd380f5)
- f0a2165ca98fde91972272802a32607bd66bf33b FAILED [:book: Documentation](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1300#0184c018-d7e1-42f9-bb15-3c9b9ec1e444)
- ba4af8ef16265b2a13cec149d27265516d3884bb FAILED [:book: Documentation](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1299#0184c009-e2bc-4018-a1f1-df2b6a98bd43)
- 53a5b4dd6bfd15926d92e3eb6ef1d674dccb6074 FAILED [:book: Documentation](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1287#0184bc9f-c87e-400e-91a1-d07f590187aa)
- 22dd1b2e83b97676600eaf10165df3843bba77ba FAILED [:book: Documentation](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1260#0184a636-c88c-41f8-b436-8b2c76fd245b)
- a5a48db7b9421c57594f4723fefa41a45f7c8f2b FAILED [:book: Documentation](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1259#0184a636-73b5-4221-b9b3-cac480511448)
- 2b3c1af41e70bf1b628dc37b0ecde9daec87ee5d FAILED [:book: Documentation](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1258#0184a636-99f5-4c0a-8720-d5cd4d0126a5)
- 289f7e955b34e2e31c98f53828a70257c0968533 FAILED [:book: Documentation](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1257#0184a635-9e9e-40c6-b77b-1cf0aafb2d55)
- 805ff74037d97e1e27a5c8cd91e65a5d0fbb3679 FAILED [:book: Documentation](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1256#0184a635-a150-49a5-a46d-e15a8053ca73)
- 3c06fb1a5fd2f1bc2a2fc93d1fecd2be4917c223 FAILED [:book: Documentation](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1254#0184a60e-ddd9-47d8-a75f-c2af2011831c)
- fd1152667120452d02f27290a625fcbe57137bae FAILED [:book: Documentation](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1253#0184a60e-9f09-4a5a-928d-c38ae59f26e1)
- 656577c6824016e18e05612127ab776fce1e5600 FAILED [:book: Documentation](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1251#0184a5db-d294-4678-9752-b9f99ef98fd4)
- 3d6598deb031e43ad1c03b673697d76e40196dd2 FAILED [:book: Documentation](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1250#0184a5c6-1180-416e-9f37-8b0997ce4345)
- c81626d9879cb6186dacd7bc2adaee7dd79853ba FAILED [:book: Documentation](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1249#0184a5af-0221-45a2-8116-99b8e75cb858)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-bk://:book: Documentation-END
....

**Comment by stephanie-wang** [comment] 2022-11-29 17:22
Closed by #30718.

**Comment by clarng** [comment] 2023-01-31 17:56
Failing again

https://buildkite.com/ray-project/oss-ci-build-branch/builds/2091#018608ac-7311-4c45-9cfd-a7b126aeb786

**Comment by clarng** [comment] 2023-01-31 18:01
Looks like failure is caused by https://github.com/ray-project/ray/pull/31750

If we can't resolve this right away we should revert per policy @alanwguo

**Comment by alanwguo** [comment] 2023-01-31 19:49
looking

**Comment by rickyyx** [comment] 2023-03-08 18:42
Seems to be caused by this: https://github.com/ray-project/ray/commit/2703c56e112d5af43ef6e9adf482ca4c042e8e0c

**Comment by scottjlee** [comment] 2023-03-08 18:43
have a PR out to fix this: https://github.com/ray-project/ray/pull/33125
waiting on CI tests to pass. thanks for flagging

**Comment by scottjlee** [comment] 2023-03-13 19:42
@rickyyx this should be resolved by the above PR now. let me know if there are any followups. thanks!

**Closed** 2023-03-14 02:08 UTC
Labels: flaky-tracker
