### ISSUE TITLE
Calling ray.shutdown before ray.init makes ray forget function definitions

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#3897] opened 2019-01-30 01:37 UTC
This is an error one of our users was running into:

```
import ray
@ray.remote
def f():
  return 1

ray.shutdown()
ray.init()
ray.get(f.remote())
```

And ray will print:
```
This worker was asked to execute a function that it does not have registered. You may have to restart Ray.
```

Shutdown will clear the function cache and therefore ray.init won't register the right functions. This looks like a user error, but I can see what they are trying to do (making sure any other ray instance has shut down properly I guess).

This is not a bug I think but we might want to print a more informative error message here. And hopefully this issue will point people into the right direction too if this happens.

**Comment by jovany-wang** [comment] 2019-01-30 03:02
Could we add a check to check that whether users has called `init()` before calling `shutdown()`.
In other words, Ray requires users to call `init()` and `shutdown` in order.

**Comment by robertnishihara** [comment] 2019-01-30 03:07
This is a duplicate of #1798. There's some more discussion in #1814.

**Comment by robertnishihara** [comment] 2019-01-31 03:55
@jovany-wang, one situation where we use `ray.shutdown()` a lot is in the tests (to clean up even if a test failed), so we want it to run even if the test failed before `ray.init()` was called.

**Closed** 2020-10-12 03:37 UTC
Labels: P3
