### ISSUE TITLE
problem with centos 7.3 build?

### ISSUE THREAD

**Issue by virtualluke** [ray-project/ray#759] opened 2017-07-20 21:04 UTC
The build looks fine until I do a ray.init().  This is with Anaconda3-4.4.0. At the end you can see I have no problem importing redis or numpy manually:

[root@box25 ~]# /opt/anaconda3/bin/pip install ray-0.1.2-cp36-cp36m-manylinux1_x86_64.whl  
Processing ./ray-0.1.2-cp36-cp36m-manylinux1_x86_64.whl  
Requirement already satisfied: cloudpickle>=0.2.2 in /opt/anaconda3/lib/python3.6/site-packages (from ray==0.1.2)  
Requirement already satisfied: click in /opt/anaconda3/lib/python3.6/site-packages (from ray==0.1.2)  
Requirement already satisfied: redis in /opt/anaconda3/lib/python3.6/site-packages (from ray==0.1.2)  
Requirement already satisfied: flatbuffers in /opt/anaconda3/lib/python3.6/site-packages/flatbuffers-2015.5.14.0-py3.6.egg (from ray==0.1.2)  
Requirement already satisfied: funcsigs in /opt/anaconda3/lib/python3.6/site-packages (from ray==0.1.2)  
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.6/site-packages (from ray==0.1.2)  
Requirement already satisfied: colorama in /opt/anaconda3/lib/python3.6/site-packages (from ray==0.1.2)  
Requirement already satisfied: psutil in /opt/anaconda3/lib/python3.6/site-packages (from ray==0.1.2)  
Installing collected packages: ray  
Successfully installed ray-0.1.2  

[root@box25 ~]# opt/anaconda3/bin/python  
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux  
Type "help", "copyright", "credits" or "license" for more information.  
\>>> import ray
\>>> ray.init()
11845:M 20 Jul 20:39:44.137 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.  
11845:M 20 Jul 20:39:44.137 # Server started, Redis version 3.9.102  
11845:M 20 Jul 20:39:44.137 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.  
11845:M 20 Jul 20:39:44.137 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.  
Waiting for redis server at 127.0.0.1:53428 to respond...  
11849:M 20 Jul 20:39:44.241 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.  
11849:M 20 Jul 20:39:44.241 # Server started, Redis version 3.9.102  
11849:M 20 Jul 20:39:44.241 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.  
11849:M 20 Jul 20:39:44.241 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
Waiting for redis server at 127.0.0.1:52073 to respond...
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/monitor.py", line 9, in <module>
    import redis
ImportError: No module named redis
Allowing the Plasma store to use up to 162.267GB of memory.
Starting local scheduler with 56 CPUs and 0 GPUs.
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11859
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11860
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11861
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11862
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11863
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11864
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11865
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11866
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11867
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11868
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11869
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11870
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11871
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11872
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11873
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11874
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11875
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11876
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11877
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11878
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11879
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11880
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11881
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11882
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11883
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11884
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11885
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11886
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11887
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11888
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11889
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11890
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11891
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11892
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11893
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11894
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11895
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11896
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11897
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11898
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11899
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11900
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11901
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11902
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11903
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11904
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11905
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11906
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11907
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11908
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11909
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11910
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11911
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11912
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11913
[INFO] (/ray/src/local_scheduler/local_scheduler.cc:219) Started worker with pid 11914
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
Traceback (most recent call last):
ImportError:   File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
No module named numpy
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
Traceback (most recent call last):
ImportError  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
: No module named numpy
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
    import numpy as np
ImportError: ImportErrorNo module named numpy: 
No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
Traceback (most recent call last):
    import numpy as np
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
ImportError: No module named numpy
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
    import numpy as np
ImportError: ImportErrorNo module named numpy: 
No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
ImportError: No module named numpy
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
    import numpy as np
ImportError: ImportErrorNo module named numpy: 
No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
Traceback (most recent call last):
    import numpy as np
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
ImportError: No module named numpyImportError
: No module named numpy
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/workers/default_worker.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
Failed to start the UI, you may need to run 'pip install jupyter'.
{'node_ip_address': '127.0.0.1', 'redis_address': '127.0.0.1:53428', 'object_store_addresses': [ObjectStoreAddress(name='/tmp/plasma_store66780044', manager_name='/tmp/plasma_manager97012142', manager_port=21398)], 'local_scheduler_socket_names': ['/tmp/scheduler67179135']}
\>>> import numpy as np
\>>> import redis

**Comment by robertnishihara** [comment] 2017-07-20 21:12
I suspect the problem is the following.

You are starting Python and running Ray using the binary `opt/anaconda3/bin/python`. However, Ray is starting a bunch of python workers, and it is just running the `python` command, so it is finding whichever version of python that `which python` returns. And that version of Python on your machine probably doesn't have numpy or redis installed.

If that's the case, you could work around this by doing `export PATH=opt/anaconda3/bin:$PATH` so that `which python` returns `opt/anaconda3/bin/python`.

But really, we should fix this by starting the workers using the same version of Python that you are using (and not just running the `python` executable). I'll look into this, I don't think it will be very difficult.

**Comment by virtualluke** [comment] 2017-07-20 21:16
That was it. Thanks for the quick response!

**Comment by robertnishihara** [comment] 2017-07-20 21:57
Great!

**Comment by robertnishihara** [comment] 2017-07-21 00:05
This should be fixed by #760.

**Closed by robertnishihara** 2017-07-21 00:05 UTC
Labels: bug
