### ISSUE TITLE
[autoscaler] driver received error message when ray downscale

### ISSUE THREAD

**Issue by valiantljk** [ray-project/ray#15467] opened 2021-04-23 00:09 UTC
### What is the problem?
I used autoscaler feature in Ray. It works as expected when I submit a task that requires more resources than available res. However after 5 minutes(the default idle time), ray downscales, and at driver side, I got error messages like this:
```
The node with node id: 40d7709d4275bb0784e227591eceeeb9a8604fb30e5a28e4c90d9c04 and ip: 192.168.77.252 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a raylet crashes unexpectedly or has lagging heartbeats.
```
This seems to be some issue with the error handling or autoscaling part. 
I would expect no error message received at the driver side, bc downscaling is expected.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray nightly
Python 3.7

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
import ray,time
ray.util.connect("ip:port")
@ray.remote
def fun():
  time.sleep(15)
  return 1

futures = [fun.remote() for _ in range(10)]
```
Before running the code, with kubectl get pods:
```
example-cluster-ray-head-89v9q       1/1     Running   0          9m29s
example-cluster-ray-worker-4qmdw     1/1     Running   0          4m58s
example-cluster-ray-worker-8gxff     1/1     Running   0          9m19s
```
After running the code, with kubectl get pods:
```
NAME                                 READY   STATUS    RESTARTS   AGE
example-cluster-ray-head-89v9q       1/1     Running   0          9m29s
example-cluster-ray-worker-4qmdw     1/1     Running   0          4m58s
example-cluster-ray-worker-8gxff     1/1     Running   0          9m19s
example-cluster-ray-worker-cg64f     1/1     Running   0          5m10s
example-cluster-ray-worker-gnrws     1/1     Running   0          5m10s
example-cluster-ray-worker-jpgqb     1/1     Running   0          4m58s
example-cluster-ray-worker-kkvr4     1/1     Running   0          5m10s
example-cluster-ray-worker-n6pl4     1/1     Running   0          5m10s
example-cluster-ray-worker-nn7dz     1/1     Running   0          9m19s
example-cluster-ray-worker-s6xlt     1/1     Running   0          5m10s
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment] 2021-04-23 18:07
Thanks @valiantljk, cc @DmitriGekhtman and @wuisawesome . This error message seems the downscale is working but it shouldn't print out such error on intentional removing nodes.

**Comment by DmitriGekhtman** [comment] 2021-04-24 23:07
It's like related to this:
https://github.com/ray-project/ray/issues/15128

**Comment by AmeerHajAli** [comment] 2021-04-26 14:52
looks like a duplicate of #14129

**Closed** 2021-04-26 14:57 UTC
Labels: bug, fix-error-msg, triage
