### ISSUE TITLE
[RLlib nightly test] stress_test is consistently timing out

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#18498] opened 2021-09-10 15:35 UTC
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
nightly release

stress_test is consistently timing out

Sample test:
https://buildkite.com/ray-project/periodic-ci/builds/959#daab5212-220a-4f89-9a06-818f3f9f43eb

The following log is suspicious, is this expected in this test set up?
```
RUNNING)\n\n2021-09-10 02:41:08,565\tWARNING util.py:166 -- The `on_step_begin` operation took 2.127 s, which may be a performance bottleneck.\n2021-09-10 02:41:10,729\tWARNING util.py:166 -- The `get_next_failed_trial` operation took 2.161 s, which may be a performance bottleneck.\n2021-09-10 02:41:20,906\tWARNING util.py:166 -- The `on_step_begin` operation took 2.153 s, which may be a performance bottleneck.\n2021-09-10 02:41:23,135\tWARNING util.py:166 -- The `get_next_failed_trial` operation took 2.227 s, which may be a performance bottleneck.\n2021-09-10 02:41:33,223\tWARNING util.py:166 -- The `on_step_begin` operation took 2.063 s, which may be a performance bottleneck.\n2021-09-10 02:41:35,536\tWARNING util.py:166 -- The `get_next_failed_trial` operation took 2.310 s, which may be a performance bottleneck.\n2021-09-10 02:41:45,634\tWARNING util.py:166 -- The `on_step_begin` operation took 2.072 s, which may be a performance bottleneck.\n2021-09-10 02:41:47,929\tWARNING util.py:166 -- The `get_next_failed_trial` operation took 2.292 s, which may be a performance 
```

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by xwjiang2010** [comment] 2021-09-10 15:37
cc @sven1977

**Comment by jjyao** [comment] 2021-09-18 17:23
Any updates on this? @gjoliver @xwjiang2010

**Comment by gjoliver** [comment] 2021-09-18 17:28
just sent some updates on your email thread.
we need https://github.com/ray-project/ray/pull/18705, which I believe Sven's still trying to verify a little bit.
it's an error in our result checking code though, the actual stress test is fine.

if you want, we can take release-blocker tag off, since the problem is with the test itself.

**Comment by sven1977** [comment] 2021-09-20 13:57
This has been fixed as of this PR here. All RLlib release tests are now ok.
https://github.com/ray-project/ray/pull/18705

**Closed by sven1977** 2021-09-20 13:57 UTC
Labels: bug, release-blocker, P0
