### ISSUE TITLE
[Minor] Deprecated link in logger error

### ISSUE THREAD

**Issue by Butanium** [ray-project/ray#37392] opened 2023-07-13 10:00 UTC
https://github.com/ray-project/ray/blob/36b9bf2d4f1d901d9af64ebb483b474041ffe00c/python/ray/tests/test_logging.py#L130

This link: https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure is deprecated

**Comment by kevin85421** [comment] 2024-03-17 23:50
This is a duplicate of #37803. I have already opened #44073 to update the links.

**Closed by kevin85421** 2024-03-17 23:50 UTC
