### ISSUE TITLE
[Serve] Export error counter metric even when error count is zero

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#20927] opened 2021-12-06 23:41 UTC
The `serve_deployment_error_counter` metric doesn't show up unless there's at least one error.  We should instead always export this metric, and just set it to 0 if there haven't been any errors.

Reproduction:

`ray start --head --metrics-export-port=8080`

Then run

```python

import ray
from ray import serve

import time

ray.init(address="auto")
serve.start(detached=True)

@serve.deployment
def g():
    return True

@serve.deployment
def f():
    time.sleep(1)
    raise ValueError("exception")

f.deploy()
g.deploy()
```

Then ping `g` a few times (e.g. visit `http://127.0.0.1:8000/g`).

If you check `localhost:8080` (perhaps refreshing after 10 seconds), you can search for `serve_` and find several serve metrics, but `serve_deployment_error_counter` is missing.  Once you ping `f`, wait for 10 seconds and refresh `localhost:8080` again, the error counter appears.

**Comment by akshay-anyscale** [comment] 2024-10-15 18:08
@GeneDer was this fixed

**Comment by GeneDer** [comment] 2024-10-15 18:29
No, I don't think this is fixed, but I'm also not sure if the behavior described in the issue is desire. Typically those type of metrics are only triggered/ incremented when the event (in this case an error) has happened. Logging something here, even when setting the value to 0, seems to be a bit conflicting signal for an error has happened. What users should do is monitoring on the rate of change of this metrics. Will close this issue for now since it's also super old.

**Closed by GeneDer** 2024-10-15 18:29 UTC
Labels: bug, P1, serve
