### ISSUE TITLE
[Core][observability] nsight integration with ray workers, API doc, docs, etc.

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#39094] opened 2023-08-30 03:00 UTC
### Description

Ray should have nsight integrate with ray workers that could generate profile for nvidia gpus.
nsight need to run before the ray process launch, so potentially it could integrates with runtime env.

https://gist.github.com/mcarilli/376821aa1a7182dfcf59928a7cde3223 profiling scripts

**Comment by anyscalesam** [comment] 2023-09-28 16:50
@cadedaniel @scv119 can you say a bit more about the context here? Specifically
1. Do we need dashboard integration, or any API changes?
2. Any insight as to why this issue is "large" as compared to "small" (if it is through runtime envs)

**Comment by cadedaniel** [comment] 2023-09-28 18:48
1. I feel dashboard integration is P1. I don't expect API changes (maybe in runtime env?).
2. AFAIK we've only ever gotten this to work in ray local mode. so there's technical complexity to get it working with a real cluster / ray worker.

**Comment by richardliaw** [comment] 2023-10-04 20:01
Should we close this issue in lieu of a previous, more rich/commented issue: https://github.com/ray-project/ray/issues/19631 ?

**Comment by jjyao** [comment] 2023-10-04 20:19
Duplicate of https://github.com/ray-project/ray/issues/19631

**Closed by jjyao** 2023-10-04 20:19 UTC
Labels: enhancement, P0, size:large, core, core-runtime-env, ray 2.8

**Comment by anyscalesam** [comment] 2023-10-05 00:44
@jjyao is p0 right for #19631 ? Asking because this dupe was marked as p0 and in scope for ray28
