### ISSUE TITLE
[core][experimental] Higher than expected overhead for shared memory channels with NCCL

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#45319] opened 2024-05-14 00:02 UTC
### What happened + What you expected to happen

[Microbenchmark](https://github.com/ray-project/ray/blob/master/python/ray/_private/ray_experimental_perf.py#L150) results for a single-actor accelerated DAG shows about 30k calls/s, or about 30us/call. That is consistent with other microbenchmarks that @jackhumphries ran for channel performance, showing low 10s of us / channel op.

However, a [microbenchmark](https://github.com/ray-project/ray/blob/master/release/microbenchmark/experimental/accelerated_dag_gpu_microbenchmark.py) for the recently added NCCL transport shows about 5.8k calls/s for NCCL alone and 3.2k calls/s for DAG+NCCL. This translates to about 130us / DAG call, more than 4x what's expected.

### Versions / Dependencies

3.0dev

### Reproduction script

See linked microbenchmarks.

### Issue Severity

None

**Comment by anyscalesam** [comment] 2024-05-23 22:37
Discussed during standup today > goal is to improve the NCCL performance to be within 50% versus 4x. This will also help with vLLM performance (may or may not impact) but it will also draw that closer as well.

**Comment by anyscalesam** [comment] 2024-06-10 22:35
Environment setup - about to dive into debugging the overhead.

**Comment by anyscalesam** [comment] 2024-06-27 00:25
There are actually two things - one is the perf regression in our existing perf dashboard. The other one is the overheads around our seralizer (cloud pickl) > the first one we should fix for Developer Preview.

**Comment by stephanie-wang** [comment] 2024-06-27 22:21
#45953 has been merged, which was the P0 regression. The remaining overheads have been tracked down to python serialization of the tensor metadata, which we should be able to optimize later.

**Comment by stephanie-wang** [comment] 2024-07-25 22:40
Ray overhead has regressed to ~500us / NCCL op.

**Comment by anyscalesam** [comment] 2024-07-26 17:44
Just to recap - where @jackhumphries left off is we know some of the extraneous overhead is in our serializer so we need to build a custom serializer to optimize those paths (pretty long hanging fruit).

**Comment by anyscalesam** [comment] 2024-07-30 07:05
dropping bug so it doesn't pop in our dashboards cc @stephanie-wang @rkooo567

**Comment by woshiyyya** [comment] 2024-08-01 18:19
Did some benchmark comparing Tensor Transfer Latency between ADAG and Pure NCCL.

`InputNode -> W1 -> W2 -> W3 -> W4`

ADAG seems to be 3-5x slower than pure NCCL send/recv based on the experiment results: https://docs.google.com/spreadsheets/d/1G8xmJmuMJBPqBDvkJzjh5boAscJZ-lpt2nVdDyVx7H8/edit?usp=sharing

The code for benchmarking: https://gist.github.com/woshiyyya/31181c98f818f136ac275e188d48b528

**Comment by anyscalesam** [comment] 2024-08-05 20:00
Interesting... @woshiyyya what changed?

**Comment by rkooo567** [comment] 2024-08-05 22:18
@anyscalesam it was the original benchmark script has some issue

**Comment by rkooo567** [comment] 2024-08-08 07:00
btw we should prioritize fixing this soon. maybe let's take it next week.

**Comment by anyscalesam** [comment] 2024-08-19 17:44
Need for vLLM

**Comment by woshiyyya** [comment] 2024-08-27 17:49
> Interesting... @woshiyyya what changed?

@anyscalesam  I changed the return value of the last DAG node to `None`, this reduced an extra communication from actor to driver.

**Comment by kevin85421** [comment] 2024-10-29 19:51
@stephanie-wang I will take a look at this issue next week. Would you mind pointing me out which tests are you referring to? Thanks!

**Comment by kevin85421** [comment] 2024-11-06 00:24
I ran [accelerated_dag_gpu_microbenchmark.py](https://github.com/ray-project/ray/blob/master/release/microbenchmark/experimental/accelerated_dag_gpu_microbenchmark.py) on my GPU machine, and got the following results:



```
exec_nccl_gpu per second 5798.01 +- 16.49
exec_ray_dag_gpu_nccl_static_shape_direct_return per second 3041.9 +- 3.4
```

**Comment by kevin85421** [comment] 2024-11-10 00:18
The main performance difference between pure NCCL and RayCG is due to benchmarking two different aspects.

* For pure NCCL, we only measure the time for NCCL I/O.
* For RayCG, we benchmark the entire execute process, including overheads such as sending input to a DAG node via shared memory and returning the output to the driver via shared memory.

I performed experiments based on the following two scripts:

* [Pure benchmark](https://gist.github.com/kevin85421/5a1fe115e657f55d1c2ed846b5ab4345)
* [Ray Compiled Graphs](https://gist.github.com/kevin85421/37976859417d59c3d095f9dffe0df0f4)

The experimental results are shown in the screenshots below.

* Ray CG = NCCL I/O (a) + Overhead (b)
* Pure NCCL = NCCL I/O (a)

If the above equations are correct, increasing the data transfer size will make the average execution times of `Ray CG` and `Pure NCCL` more similar.

* When shape is small (4, 24576), the execution time of `Ray CG` (0.2506 ms) is 95% higher than `Pure NCCL` (0.128 ms). 

If the above equations are correct, the execution time of `Ray CG` should be approximately equal to `Pure NCCL` + `Overhead`.

We use a very small NCCL data transfer size, `shape = (1, 1)`, to simulate the `Overhead`.

RayCG (0.2506 ms) ~= Pure NCCL (0.128 ms) + Overhead (0.14 ms)



![Screenshot 2024-11-09 at 4 06 22 PM](https://github.com/user-attachments/assets/49e622c0-da03-465b-a514-aae3dbfd61de)
![Screenshot 2024-11-09 at 4 06 14 PM](https://github.com/user-attachments/assets/c76703d2-bfbc-4981-84f4-bb736629601e)

**Comment by kevin85421** [comment] 2024-12-02 18:37
I documented the process of verifying the calculation in https://github.com/ray-project/ray/pull/48860#issuecomment-2512348571. Closing this issue. @stephanie-wang, feel free to reopen the issue if I missed anything.

**Closed by kevin85421** 2024-12-02 18:37 UTC
Labels: P0, performance, core, compiled-graphs
