### ISSUE TITLE
[Datasets] Python GC falling behind in Ray data pipelines causing excess disk spilling

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#25249] opened 2022-05-27 02:38 UTC
## Problem
in some cases, the Python GC can fall behind on Ray. This can cause ObjectRefs to stay alive in Python-land, keeping their underlying data blocks in the Ray object store to stay alive longer than needed.

The following snippet illustrates the problem. If you run it on the latest Ray, it will explode in memory and start spilling to disk, even though in principle it needs at most ~1GB of active object store memory.
```
import ray

dataset = ray.data.range_tensor(5000, shape=(80, 80, 4), parallelism=100)
p = dataset.map_batches(lambda x: x).repeat()

for batch in p.iter_batches():
    pass
```

This is problematic since this pipeline pattern is one we'd like to use in AIR for distributed ingest. While the scenario is a little contrived (ML pipelines typically won't create data this fast), it can definitely occur in practice. Uber has reported somewhat similar questions around more memory used than expected.

## Possible solutions

- Force Python GC at a higher frequency: If you set RAY_local_gc_min_interval_s=1 RAY_global_gc_min_interval_s=1, then the above snippet GCs objects fast enough to avoid disk spilling.
**Cons**:
Forcing Python GC adds a lot of overhead. Doing it every second could be prohibitively slow.
- Eagerly delete objects (ray.internal.internal_api.free) in DatasetPipeline iterators. This works since in DatasetPipeline we know an object will no longer be used again, and hence can delete it explicitly, not waiting for Python GC.
**Cons**:
Specific fix to DatasetPipeline
- Fix Datasets / DatasetPipeline to avoid Python cyclic references. This will make the GC problem not exist.
**Cons**:
Could be hard to find the issue. https://code.activestate.com/recipes/523004-find-cyclical-references/ ?
Is it even possible to enforce this programmatically in Python?

## Success criteria
The pipeline above and similar pipelines work as expected with no memory leaks / spilling.
Integration / nightly tests on more complex pipelines (e.g., check_ingest.py) checking no memory leaks / spilling.
Also should more generally implement explicit memory freeing to resolve flaky tests / nondeterministic memory usage such as this issue:

=================================== FAILURES ===================================
_______________________ test_memory_release_lazy_shuffle _______________________
 
shutdown_only = None
 
    def test_memory_release_lazy_shuffle(shutdown_only):
        # TODO(ekl) why is this flaky? Due to eviction delay?
 
 

cc @jianoaix @scv119 @clarkzinzow @stephanie-wang 

### Versions / Dependencies

master

### Reproduction script

```
import ray

dataset = ray.data.range_tensor(5000, shape=(80, 80, 4), parallelism=100)
p = dataset.map_batches(lambda x: x).repeat()

for batch in p.iter_batches():
    pass
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by ericl** [comment] 2022-06-10 02:36
Here is a more advanced version that still doesn't pass after https://github.com/ray-project/ray/pull/25461

```
import ray

dataset = ray.data.range_tensor(500000, shape=(80, 80, 4), parallelism=100)
p = dataset.window(bytes_per_window=1024 * 1024 * 1024).repeat()
p1, p2 = p.split(2, equal=True)
print("start")

@ray.remote
def f(p):
        i = 0
        for batch in p.iter_batches():
                i += 1
                print(i)

ray.get([f.remote(p1), f.remote(p2)])
```

Note that setting `split(equal=False)` will work fine, it only triggers issues if equal=True. I guess the intermediate blocks are not getting cleaned up in the split coordinator actor.

**Comment by jianoaix** [comment] 2022-06-14 05:13
For the first part (without pipeline splitting), it should have been fixed with https://github.com/ray-project/ray/pull/25461.

For the second part, uncovered 3 parts:
- [Root caused, had a fix] The execution stages are collapsed when pipeline split, that is, the child pipelines do not inherit the stages from the parent pipeline and have zero stage at creation. So we can not just rely on whether there is any stage to decide if it's safe to clear blocks. I had a fix locally for this.
- [Root caused, fix to be added] The equalized splitting may create intermediate blocks, so we need to clear them.
- [Still investigating the root cause] There is something issue in using ray.internal.free() which seems not clear blocks as expected. So even if 1) we have the above two fixes (the merged one + the local one) and 2) allow unequal splitting, it still spills a lot of blocks.

**Comment by jianoaix** [comment] 2022-06-14 22:11
For the third part mentioned above, I thought it's due to ray.internal.free, but seems this will actually clear the objects although "ray memory" will still have an entry for that reference.

And then looked into pipeline splitting actor (since it's the delta introduced here), but didn't find anything interesting.
Actually, it looks we can have spilling even if we don't do pipeline splitting, with following code:
```
dataset = ray.data.range_tensor(500000, shape=(80, 80, 4), parallelism=200)
p = dataset.window(bytes_per_window=1024 * 1024 * 1024)

@ray.remote
class Provider:
    def __init__(self, p):
        self.it = p.iter_datasets()

    def get_dataset(self):
        return next(self.it)

provider = Provider.remote(p)

@ray.remote
def g():
    i = 0
    while True:
        print(i)
        i += 1
        dsref = provider.get_dataset.remote()
        ds = ray.get(dsref)
        for batch in ds.iter_batches():
            pass

ray.get(g.remote())
```

**Comment by jianoaix** [comment] 2022-06-17 20:15
With https://github.com/ray-project/ray/pull/25820 (draft) and a local hack to clear input block if we split it into two, the above advanced case had no spilling (for both equal=True and equal=False) running for 20mins:

--- Aggregate object store stats across all nodes ---
Plasma memory usage 4883 MiB, 109 objects, 52.2% full, 52.2% needed
Objects consumed by Ray tasks: 3920492 MiB.

It looks keeping around 10 objects through the test.

**Comment by clarkzinzow** [comment] 2022-06-27 17:54
@jianoaix Should we keep this open to capture remaining work? My understanding is that there two outstanding items:
1. Memory releasing during splits.
2. Unskipping the memory release tests, e.g. https://github.com/ray-project/ray/issues/24757

The tests involved for (2) are these: [1](https://github.com/ray-project/ray/blob/66650cdadbbc19735d7be4bc613b9c3de30a44da/python/ray/data/tests/test_optimize.py#L86-L144), [2](https://github.com/ray-project/ray/blob/66650cdadbbc19735d7be4bc613b9c3de30a44da/python/ray/data/tests/test_optimize.py#L164-L186).

**Closed** 2022-08-02 18:27 UTC
Labels: bug, P1, datasets
