### ISSUE TITLE
Redis error on macOS ray.init()

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#14640] opened 2021-03-12 04:10 UTC
Seeing this upon `ray.init()` -- just installed from the nightly build:

```
 File "/Users/rliaw/dev/tune-sklearn/tune_sklearn/tune_basesearch.py", line 656, in fit
    include_dashboard=False
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 726, in init
    ray_params=ray_params)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/node.py", line 227, in __init__
    self.start_head_processes()
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/node.py", line 870, in start_head_processes
    self.start_redis()
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/node.py", line 678, in start_redis
    port_blacklist=self._ray_params.reserved_ports)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/_private/services.py", line 878, in start_redis
    port_blacklist=port_blacklist)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/_private/services.py", line 1069, in _start_redis_instance
    ulimit_n - redis_client_buffer)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/redis/client.py", line 1243, in config_set
    return self.execute_command('CONFIG SET', name, value)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: Invalid argument '65504' for CONFIG SET 'maxclients' - The operating system is not able to handle the specified number of clients, try with 10000
[1]    59525 terminated  python test.py
```

**Comment by richardliaw** [comment] 2021-03-12 04:11
(though this was not easily reproducible, so feel free to close)

**Comment by robertnishihara** [comment] 2021-03-14 18:37
Reopening because I run into this like half of the time that I do `ray.init()`.

**Comment by robertnishihara** [comment] 2021-03-14 18:43
Ok, actually it seems to happen more frequently the first time after I install ray. So I can reproduce it about half the time by doing the following.

```
pip uninstall -y ray
pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-macosx_10_13_intel.whl
```

```
python
>>> import ray
>>> ray.init()
```

**Comment by richardliaw** [comment] 2021-03-16 03:29
Also see this:

```python
(raybuild) ➜  python git:(master) ✗ ray start --head
Local node IP: 192.168.1.115
2021-03-15 20:04:21,475	INFO services.py:1256 -- View the Ray dashboard at http://127.0.0.1:8265
[2021-03-15 20:04:22,611 C 3909 6800419] service_based_gcs_client.cc:227: Couldn't reconnect to GCS server. The last attempted GCS server address was 192.168.1.115:56842
*** StackTrace Information ***
    @        0x10a6a1060  ray::SpdLogMessage::Flush()
    @        0x10a670699  ray::RayLog::~RayLog()
    @        0x10a37544e  ray::gcs::ServiceBasedGcsClient::ReconnectGcsServer()
    @        0x10a374b5a  ray::gcs::ServiceBasedGcsClient::PeriodicallyCheckGcsServerAddress()
    @        0x10a641fde  ray::PeriodicalRunner::DoRunFnPeriodically()
    @        0x10a641edb  ray::PeriodicalRunner::RunFnPeriodically()
    @        0x10a373fbb  ray::gcs::ServiceBasedGcsClient::Connect()
    @        0x10a1c2d7f  ray::gcs::GlobalStateAccessor::Connect()
    @        0x10a1a42ab  __pyx_pw_3ray_7_raylet_19GlobalStateAccessor_3connect()
    @        0x1084eb1f3  _PyMethodDef_RawFastCallKeywords
    @        0x1084f72e4  _PyMethodDescr_FastCallKeywords
    @        0x10861bbff  call_function
    @        0x108613697  _PyEval_EvalFrameDefault
    @        0x10860d157  _PyEval_EvalCodeWithName
    @        0x1084eafc9  _PyFunction_FastCallKeywords
    @        0x10861bacc  call_function
    @        0x108613697  _PyEval_EvalFrameDefault
    @        0x1084eaf1b  _PyFunction_FastCallKeywords
    @        0x10861bacc  call_function
    @        0x108613697  _PyEval_EvalFrameDefault
    @        0x1084eaf1b  _PyFunction_FastCallKeywords
    @        0x10861bacc  call_function
    @        0x108613697  _PyEval_EvalFrameDefault
    @        0x10860d157  _PyEval_EvalCodeWithName
    @        0x1084eafc9  _PyFunction_FastCallKeywords
    @        0x10861bacc  call_function
    @        0x108613f5b  _PyEval_EvalFrameDefault
    @        0x10860d157  _PyEval_EvalCodeWithName
    @        0x1084eafc9  _PyFunction_FastCallKeywords
    @        0x10861bacc  call_function
    @        0x108613f5b  _PyEval_EvalFrameDefault
    @        0x10860d157  _PyEval_EvalCodeWithName
```

**Comment by richardliaw** [comment] 2021-03-18 18:58
@wuisawesome @ericl this happens really often to me, anyone I should assign for this?

**Comment by amogkam** [comment] 2021-03-22 17:49
@richardliaw @wuisawesome @ericl per @robertnishihara's suggestion, should this be a release blocker?

**Comment by amogkam** [comment] 2021-03-22 18:10
@wuisawesome are you planning to take this on? who would be the best person to assign to this?

**Comment by wuisawesome** [comment] 2021-03-22 18:11
Core team will triage it today.

**Comment by wuisawesome** [comment] 2021-03-24 23:45
@richardliaw what's the output of `ulimit -a` and what's in `gcs_serer.err` when you do `ray start --head`?

**Comment by wuisawesome** [comment] 2021-03-25 07:50
@robertnishihara @richardliaw can y'all provide some additional details to reproduce this? I can't reproduce it on either Big Sur or Catalina.

**Comment by richardliaw** [comment] 2021-03-25 19:59
Hmm, maybe it went away. For me, it was often the case if I installed Ray
on a new virtual env.

**Comment by amogkam** [comment] 2021-03-29 16:31
Just confirming- is this not reproducible? If not, then should we close the issue/remove it as a release blocker?

**Comment by richardliaw** [comment] 2021-03-29 16:33
yep! done

**Closed** 2021-04-21 18:11 UTC
Labels: P3, bug, needs-repro-script
