### ISSUE TITLE
[metrics] Warnings printed when redefining a metric

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#11144] opened 2020-09-30 21:36 UTC
### What is the problem?

```
(pid=25686) Attempt to register measure with already-registered name: name: "backend_queued_queries"; units: ""; description: "Current number of queries queued in the router for a backend"; type: double
```

### Reproduction (REQUIRED)
```
from ray.util import metrics

self.metric1 = metrics.Count("count", tag_keys=("my_key", ))
self.metric1.set_default_tags({"my_key": 1})
self.metric2 = metrics.Count("count", tag_keys=("my_key", ))
self.metric2.set_default_tags({"my_key": 2})
```

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment] 2022-12-08 07:10
Tried

```python3
import ray
from ray.util import metrics
ray.init()

metric1 = metrics.Counter("count", tag_keys=("my_key", ))
metric1.set_default_tags({"my_key": "1"})
metric2 = metrics.Counter("count", tag_keys=("my_key", ))
metric2.set_default_tags({"my_key": "2"})
import time
time.sleep(100)
```

in the master, and I couldn't reproduce it. Closing it. Please reopen if there's other repro script!

**Closed by rkooo567** 2022-12-08 07:10 UTC
Labels: bug, P2, dashboard, observability-ux
