### ISSUE TITLE
cap object store memory usage error

### ISSUE THREAD

**Issue by shreyagu** [ray-project/ray#5839] opened 2019-10-03 18:31 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.14.6
- **Ray installed from (source or binary)**: source
- **Ray version**: ray 0.7.5
- **Python version**:python 3.6
- **Exact command to reproduce**:

### Describe the problem

i created an AWS cluster and i run the [tune example here](https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/tune_mnist_keras.py) using **`ray.init(redis_address = ' ..')`** and it throws the following error:
Can someone please help me resolve it.
### Source code / logs
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/packages/__init__.py", line 27, in <module>
    from . import urllib3
ImportError: cannot import name 'urllib3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/web_server.py", line 26, in <module>
    import requests  # `requests` is not part of stdlib.
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python3/dist-packages/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/usr/lib/python3/dist-packages/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/usr/lib/python3/dist-packages/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'
2019-09-27 20:51:43,779    INFO resource_spec.py:205 -- Starting Ray with 0.1 GiB memory available for workers and up to 0.06 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
Traceback (most recent call last):
  File "example_ray.py", line 36, in <module>
    ray.init()
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1483, in init
    head=True, shutdown_at_exit=False, ray_params=ray_params)
  File "/usr/local/lib/python3.6/dist-packages/ray/node.py", line 156, in __init__
    self.start_ray_processes()
  File "/usr/local/lib/python3.6/dist-packages/ray/node.py", line 584, in start_ray_processes
    self.start_plasma_store()
  File "/usr/local/lib/python3.6/dist-packages/ray/node.py", line 486, in start_plasma_store
    plasma_store_socket_name=self._plasma_store_socket_name)
  File "/usr/local/lib/python3.6/dist-packages/ray/services.py", line 1360, in start_plasma_store
    ray_constants.OBJECT_STORE_MINIMUM_MEMORY_BYTES))
ValueError: Attempting to cap object store memory usage at 62453760 bytes, but the minimum allowed is 78643200 bytes.
```

**Comment by shreyagu** [comment] 2019-10-03 18:31
@richardliaw  @ericl @robertnishihara Can someone please help me in understanding this?

**Comment by richardliaw** [comment] 2019-10-07 17:29
What happens when you install `urllib3`?

**Comment by shreyagu** [comment] 2019-10-07 17:30
it says it's already installed

**Comment by richardliaw** [comment] 2019-10-07 18:08
Can you update to the most recent ray? Should be 0.7.5.

**Comment by shreyagu** [comment] 2019-10-07 18:28
could it be because of this issue with starting ray: 
https://github.com/ray-project/ray/issues/5811

**Comment by shreyagu** [comment] 2019-10-07 18:34
Sorry i take that back, the ray version is already updated to 0.7.5 @richardliaw , i mistyped i think.

**Comment by edoakes** [comment] 2019-11-15 23:54
Duplicate of https://github.com/ray-project/ray/issues/5811

**Closed by edoakes** 2019-11-15 23:54 UTC
