### ISSUE TITLE
[Core] [Error Message] Possible unhandled error from worker

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#12018] opened 2020-11-14 02:05 UTC
When you have a remote function that handles an exception, a `Possible unhandled error` message is still printed on the driver side. For example,
```
import time
import ray

ray.init()

@ray.remote
def foo():
    raise Exception("oops")

@ray.remote
def main():
    i = 0
    while True:
        i += 1
        time.sleep(1)
        print(i)
        try:
            ray.get(foo.remote())
        except:
            pass

ray.get(main.remote())
```
Shows the following message on the driver 
```
2020-11-13 18:03:16,514	ERROR worker.py:1036 -- Possible unhandled error from worker: ray::foo() (pid=68380, ip=192.168.2.228)
  File "python/ray/_raylet.pyx", line 482, in ray._raylet.execute_task
  File "<stdin>", line 3, in foo
Exception: oops
```
even though the exception is actually being properly handled in the remote function `main`. This is very confusing for the user because it implies that an error actually occurs even though it doesn't. At the very least we should emphasize that it is a **Possible** unhandled error and that it can be safe to ignore this message if it is being handled.

See https://github.com/ray-project/ray/issues/5240 and https://github.com/ray-project/ray/pull/11849#issuecomment-727111327 for more examples.

**Comment by concretevitamin** [comment] 2020-12-05 18:35
We (@franklsf95) got hit by this pretty hard in 1.0.1.  The expected behavior, as @amogkam said, is that there shouldn't be any warnings sent to the driver because the remote function actually catches the exceptions (in our case, not just `pass`).

**Comment by crystalww** [comment] 2020-12-07 07:43
@concretevitamin I have seen this Error serveral times when I modify some code or comment some code and re-run my program. I want to know whether the functions will be cached and will not be clear in ray worker nodes? As the fig shows below, the code was commented, but still raise an error.
 
![image](https://user-images.githubusercontent.com/20527302/101322298-bf947600-38a1-11eb-9690-2a19ea41d6c5.png)

**Comment by richardliaw** [comment] 2020-12-07 08:33
Thanks for the reports, all - I'm going to bump this to P1 because this is really misleading.

**Comment by richardliaw** [comment] 2020-12-07 08:34
Assigning to @rkooo567 because the blame points to you, but please reassign if there is someone better!

**Comment by rkooo567** [comment] 2020-12-07 09:09
@richardliaw Can you give me the link to the blame to understand the context better?

**Comment by richardliaw** [comment] 2020-12-07 09:10
ah I just searched for `Possible unhandled error from worker` and it showed me ray/worker.py:977.

**Comment by crystalww** [comment] 2020-12-07 09:19
> ah I just searched for `Possible unhandled error from worker` and it showed me ray/worker.py:977.
Forget to say, I'm using Ray 1.0.0
![image](https://user-images.githubusercontent.com/20527302/101332320-14d78400-38b0-11eb-83d2-74908713eba5.png)

**Comment by valiantljk** [comment] 2020-12-17 06:45
any update on this?
I run into this issue with similar error:

```
ERROR worker.py:977 -- Possible unhandled error from worker: ray::ParallelIteratorWorker.par_iter_next_batch() (pid=84874, ip=192.168.1.5)
```

**Comment by rkooo567** [comment] 2020-12-17 08:51
Sorry I didn't have enought time to work on it yet. I will work on it within a few weeks

**Comment by crystalww** [comment] 2020-12-17 14:54
> @concretevitamin I have seen this Error serveral times when I modify some code or comment some code and re-run my program. I want to know whether the functions will be cached and will not be clear in ray worker nodes? As the fig shows below, the code was commented, but still raise an error.
> 
> ![image](https://user-images.githubusercontent.com/20527302/101322298-bf947600-38a1-11eb-9690-2a19ea41d6c5.png)

I print `sys.modules` in remote function, found the Python `import module` caused my problem. `I guess there isn't a good way to clean imported modules`.  Use `reload(module)` can help when I change my code and re-run it. But if I run two projects in turn which import a module has the same name, It doesn't work.

**Comment by valiantljk** [comment] 2020-12-22 18:52
I'm still experiencing the error, could you give a hint on how to fix it? and what's the cause? Thanks @rkooo567 

```
ERROR worker.py:977 -- Possible unhandled error from worker: ray::ParallelIteratorWorker.par_iter_next_batch() (pid=67941, ip=192.168.1.9)
```

**Comment by amogkam** [comment] 2020-12-22 18:54
@valiantljk the message is being shown even though **no error actually occurs**. Since you are using ParallelIterators, it is safe to ignore this.

This is a bug on our end, and we will fix it shortly!

**Comment by rkooo567** [comment] 2021-01-16 03:01
cc @oliverhu if you have time, can you take a look at this issue?

**Comment by oliverhu** [comment] 2021-01-17 05:41
👌 @rkooo567

**Comment by oliverhu** [comment] 2021-01-17 16:20
@rkooo567  Do we need to push TaskError to Driver at all ? in `_raylet.pyx`:
```
ray.utils.push_error_to_driver(
                worker,
                ray_constants.TASK_PUSH_ERROR,
                str(failure_object),
                job_id=worker.current_job_id)
```
The RayTaskError message has been captured in Task return and in object_store. And the actual exception would be re-throw at parent worker or driver. Not sure why need to push task error to driver? 🤔

**Comment by rkooo567** [comment] 2021-01-17 20:13
Good point. I feel like this is unnecessary, and the reason why we have the issue is because we prints error messages twice? @richardliaw is it okay to just not publish the msg in this case? Any concern?

**Comment by rkooo567** [comment] 2021-01-18 17:26
cc @edoakes It seems like you are the one who introduced this error pub/sub for the first time? Can you add a comment for us?

**Comment by edoakes** [comment] 2021-01-19 16:02
I don't think so, this behavior is very old. If you `git blame`'d, it's probably just that I refactored it at some point. Regardless, removing this SGTM.

@pcmoritz chime in?

**Comment by ericl** [comment] 2021-02-11 00:07
@oliverhu @amogkam can you try out https://github.com/ray-project/ray/pull/14049 and confirm it resolves your use case?

**Comment by amogkam** [comment] 2021-02-11 01:06
@ericl I tried out #14049 on the example in this issue and I'm still seeing the error message being shown on the driver
```
(pid=81511) 1
(pid=81511) 2
(pid=81511) 3
(pid=81511) 4
(pid=81511) 5
2021-02-10 17:05:25,892	ERROR worker.py:1055 -- Possible unhandled error from worker: ray::foo() (pid=81503, ip=192.168.1.118)
  File "python/ray/_raylet.pyx", line 486, in ray._raylet.execute_task
  File "/Users/amog/dev/celeb-ptl.py", line 84, in foo
    raise Exception("oops")
Exception: oops
(pid=81511) 6
2021-02-10 17:05:26,895	ERROR worker.py:1055 -- Possible unhandled error from worker: ray::foo() (pid=81503, ip=192.168.1.118)
  File "python/ray/_raylet.pyx", line 486, in ray._raylet.execute_task
  File "/Users/amog/dev/celeb-ptl.py", line 84, in foo
    raise Exception("oops")
Exception: oops
(pid=81511) 7
2021-02-10 17:05:27,898	ERROR worker.py:1055 -- Possible unhandled error from worker: ray::foo() (pid=81503, ip=192.168.1.118)
  File "python/ray/_raylet.pyx", line 486, in ray._raylet.execute_task
  File "/Users/amog/dev/celeb-ptl.py", line 84, in foo
    raise Exception("oops")
Exception: oops
```

**Comment by ericl** [comment] 2021-02-11 01:15
Did you recompile? That's the old error message being printed it seems.

**Comment by oliverhu** [comment] 2021-02-11 07:20
That branch doesn't seem to build for me, I haven't pull the latest code for a while. Pulling master.

**Comment by amogkam** [comment] 2021-02-11 08:26
@ericl ah yes that's my bad. I forgot that I had to recompile because of C++ changes. Your patch fixes the issue- I tried on both the example on this issue and the one in https://github.com/ray-project/ray/pull/11849#issuecomment-727111327

**Comment by ericl** [comment] 2021-02-18 18:45
Reverted due to 
```
Thread 15435 (idle): "MainThread"
    syscall (libc-2.27.so)
    absl::lts_2019_08_08::synchronization_internal::Waiter::Wait (ray/_raylet.so)
    AbslInternalPerThreadSemWait (ray/_raylet.so)
    absl::lts_2019_08_08::Mutex::Block (ray/_raylet.so)
    absl::lts_2019_08_08::Mutex::LockSlowLoop (ray/_raylet.so)
    absl::lts_2019_08_08::Mutex::LockSlowWithDeadline (ray/_raylet.so)
    absl::lts_2019_08_08::Mutex::LockSlow (ray/_raylet.so)
    ray::CoreWorkerMemoryStore::GetOrPromoteToPlasma (ray/_raylet.so)
    ray::CoreWorker::PromoteObjectToPlasma (ray/_raylet.so)
    serialize_and_promote_object_ref (ray/_raylet.so)
    object_ref_reducer (ray/serialization.py:91)
    _Pickle_FastCall (_pickle.c:363)
    save (_pickle.c:4417)
    dump (_pickle.c:4527)
    _pickle_Pickler_dump (_pickle.c:4598)
    dump (ray/cloudpickle/cloudpickle_fast.py:588)
    dumps (ray/cloudpickle/cloudpickle_fast.py:73)
    _to_cloudpickle (ray/tune/utils/serialization.py:26)
    default (ray/tune/utils/serialization.py:21)
    _iterencode (json/encoder.py:437)
    _iterencode_dict (json/encoder.py:404)
    _iterencode_dict (json/encoder.py:404)
    _iterencode (json/encoder.py:430)
    encode (json/encoder.py:201)
    dumps (json/__init__.py:238)
    get_json_state (ray/tune/trial.py:604)
    get_checkpoints (ray/tune/trial_executor.py:72)
    _serialize_and_write (ray/tune/trial_runner.py:108)
    checkpoint (ray/tune/trial_runner.py:125)
    checkpoint (ray/tune/trial_runner.py:402)
    run (ray/tune/tune.py:522)
    <module> (pbt_dcgan_mnist_func.py:129)
Thread 15660 (idle): "Dummy-9"
    __pthread_cond_timedwait (libpthread-2.27.so)
    _raylet_unhandled_exception_handler (ray/_raylet.so)
    ray::CoreWorkerMemoryStore::Put (ray/_raylet.so)
    ray::TaskManager::MarkPendingTaskFailed (ray/_raylet.so)
    ray::TaskManager::PendingTaskFailed (ray/_raylet.so)
    std::_Function_handler<void (ray::Status const&, ray::rpc::PushTaskReply const&), ray::CoreWorkerDirectActorTaskSubmitter::PushActorTask(ray::CoreWorkerDirectActorTaskSubmitter::ClientQueue const&, ray::TaskSpecification const&, bool)::{lambda(ray::Status, ray::rpc::PushTaskReply const&)#1}>::_M_invoke (ray/_raylet.so)
    std::_Function_handler<void (ray::Status const&, ray::rpc::PushTaskReply const&), ray::rpc::CoreWorkerClient::SendRequests()::{lambda(ray::Status, ray::rpc::PushTaskReply const&)#1}>::_M_invoke (ray/_raylet.so)
    ray::rpc::ClientCallImpl<ray::rpc::PushTaskReply>::OnReplyReceived (ray/_raylet.so)
    boost::asio::detail::completion_handler<ray::rpc::ClientCallManager::PollEventsFromCompletionQueue(int)::{lambda()#1}>::do_complete (ray/_raylet.so)
    boost::asio::detail::scheduler::do_run_one (ray/_raylet.so)
    boost::asio::detail::scheduler::run (ray/_raylet.so)
    boost::asio::io_context::run (ray/_raylet.so)
    ray::CoreWorker::RunIOService (ray/_raylet.so)
    0x7fd6d7e3e66f (libstdc++.so.6.0.25)
```

**Closed** 2021-02-22 19:11 UTC
Labels: P1, fix-error-msg
