### ISSUE TITLE
[release][ci] air_benchmark_tune_torch_mnist failed

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#28975] opened 2022-10-03 05:24 UTC
### What happened + What you expected to happen

[Build ](https://buildkite.com/ray-project/release-tests-branch/builds/1080#0183906e-87c7-4d03-835f-181c85c547ed)
[Cluster](https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_TAmfcLbZGWWMu32PL5XNg1nY)

```
Results run 3: {'train_time': 224.828414328, 'tune_time': 348.08502680400034}
Full results: {'train_times': [226.341469459, 333.7736055319999, 224.828414328], 'train_mean': 261.64782977299996, 'train_sd': 51.004365699323685, 'tune_times': [343.143759339, 345.24248954199993, 348.08502680400034], 'tune_mean': 345.49042522833344, 'tune_sd': 2.024867916447225}
Traceback (most recent call last):
  File "workloads/tune_torch_benchmark.py", line 152, in <module>
    main()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "workloads/tune_torch_benchmark.py", line 144, in main
    ), f"{mean_tune_time:.2f} > {threshold:.2f} = {factor:.1f} * {mean_train_time:.2f}"
AssertionError: 345.49 > 313.98 = 1.2 * 261.65
```

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by krfricke** [comment] 2022-10-05 22:08
Running full comparison run with STRICT_SPREAD

```
Results run 1: {'train_time': 200.2172157099999, 'tune_time': 376.5727219940004}
```

Full comparison run with STRICT_PACK

```
Results run 1: {'train_time': 265.38922436799976, 'tune_time': 283.493486546}
```

So it seems like Ray core could do a better job PACKing placement groups?

**Comment by krfricke** [comment] 2022-10-06 00:39
More runs with STRICT_PACK:

```
Full results: {
'train_times': [279.84626481600026, 278.7021960659995, 235.01906158200018], 
'train_mean': 264.522507488, 
'train_sd': 20.867314370762937, 
'tune_times': [283.66437658799987, 282.0069965799994, 298.3782951110006], 
'tune_mean': 288.01655609299996, 
'tune_sd': 7.3580320616587835}
```

And with STRICT_SPREAD

```
Full results: {
'train_times': [193.08490988199992, 228.3113456730007, 190.8328014159997], 
'train_mean': 204.07635232366678, 
'train_sd': 17.161374752961017, 
'tune_times': [404.44294343300044, 408.4392190310009, 464.6334958590014], 
'tune_mean': 425.83855277433423, 
'tune_sd': 27.48063877679116}
```

**Comment by amogkam** [comment] 2022-10-06 01:17
So the faster training with STRICT_SPREAD makes sense for CPU training.

Looks like [PyTorch is multithreaded by default](https://jdhao.github.io/2020/07/06/pytorch_set_num_threads/) so having each replica on a different machine means that each one can utilize all cores and they won't be competing with each other or with other CPU processes like Data loaders as much. This seems to provide better performance despite the extra communication cost.

But if the cluster is fully utilized with multiple trials anyways, then the benefits of spread don't matter. There will just be the extra communication cost of synchronizing across multiple nodes (which is probably exacerbated since we have multiple trials).

So `STRICT_PACK` should be the most fair comparison.

**Comment by amogkam** [comment] 2022-10-06 01:22
Also the variance is ~20% which is the same as our threshold and is cutting it close. We should run for more times to reduce variance or increase our threshold to have more buffer.

Even something like just checking if Tune is <2x slower than Train only is probably good enough.

**Comment by amogkam** [comment] 2022-10-06 01:24
Actually the fact that we are not seeing these failures for GPU training means that it's probably a problem with our setup rather than a perf regression in Tune.

**Comment by rickyyx** [comment] 2022-10-14 16:23
Hmmm this seems to be still failing on the release branch with the linked PR in? https://buildkite.com/ray-project/release-tests-branch/builds/1114#0183d3c4-af14-43dc-b33e-77c37350271f 

Or if I am missing something here?

**Comment by amogkam** [comment] 2022-10-14 18:25
this passed again on a re-run so looks like a transient error: https://buildkite.com/ray-project/release-tests-branch/builds/1113#0183d76a-deac-4efa-8623-d1d1b43713e1.

We should look into deflaking this, but is not a release blocker. Closing this issue.

**Closed by amogkam** 2022-10-14 18:25 UTC
Labels: bug, release-blocker, air, r2.1-failure
