### ISSUE TITLE
[Bug] Queueing warning is wrong for concurrent actors

### ISSUE THREAD

**Issue by johnnycrab** [ray-project/ray#22278] opened 2022-02-10 09:21 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

**Issue only happens in Ray v 1.10.0, it does not happen in Ray v 1.9.2**

When creating a concurrent actor (`.options(max_concurrency=2)`) and submitting a lot of tasks (>5000) _from a separate thread_ to it, `ray.wait` seems to have no effect when trying to apply backpressure (simple reproduction script included). It gives the following warning messages:

```
2022-02-10 10:08:33,051 WARNING worker.py:1257 -- Warning: More than 5000 tasks are pending submission to actor 3bace1a54f2f0d66ad979db101000000. To reduce memory usage, wait for these tasks to finish before sending more.
2022-02-10 10:08:33,653 WARNING worker.py:1257 -- Warning: More than 10000 tasks are pending submission to actor 3bace1a54f2f0d66ad979db101000000. To reduce memory usage, wait for these tasks to finish before sending more.
2022-02-10 10:08:34,821 WARNING worker.py:1257 -- Warning: More than 20000 tasks are pending submission to actor 3bace1a54f2f0d66ad979db101000000. To reduce memory usage, wait for these tasks to finish before sending more.
2022-02-10 10:08:37,311 WARNING worker.py:1257 -- Warning: More than 40000 tasks are pending submission to actor 3bace1a54f2f0d66ad979db101000000. To reduce memory usage, wait for these tasks to finish before sending more.
2022-02-10 10:08:42,062 WARNING worker.py:1257 -- Warning: More than 80000 tasks are pending submission to actor 3bace1a54f2f0d66ad979db101000000. To reduce memory usage, wait for these tasks to finish before sending more.
```

Expected behaviour is for the warning not to show up.

This issue only happens in version 1.10.0, in version 1.9.2 it works as expected. Also the warning does not show up if the tasks are submitted not from a separate thread.

### Versions / Dependencies

Tested on two platforms:

1.) Ubuntu 18.04.5 LTS (Bionic Beaver), Ray v.1.10.0 (bug not happening in v.1.9.2), Python 3.7.11
2.) macOS Monterey v.12.1, Ray v.1.10.0 (bug not happening in v.1.9.2), Python 3.8.10

### Reproduction script

```python
import ray
import time
import threading

@ray.remote
class TheActor:
    def do_something_continuously(self):
        while True:
            time.sleep(0.00001)

    def do_something_else(self):
        time.sleep(0.00001)
        return "foo"


a = TheActor.options(max_concurrency=2).remote()
a.do_something_continuously.remote()

tasks = []

def add_to_actor(a):
    global tasks

    for i in range(100000):
            if len(tasks) > 1000:
                done, unfinished = ray.wait(tasks, num_returns=len(tasks) - 1000)
                tasks = unfinished
            tasks.append(a.do_something_else.remote())

thread = threading.Thread(target=add_to_actor, args=[a])

thread.start()
thread.join()
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment] 2022-02-17 00:01
cc @iycheng This seems to be a regression from 1.10

**Comment by jon-chuang** [comment] 2022-02-17 17:52
You can assign to me, I'll try repro and investigate which code paths ray.wait is/is not triggering.

**Comment by ericl** [comment] 2022-02-17 22:24
It sounds likely to be a reporting issue, since I can't imagine ray.wait() would be returning wrong results. Maybe the tracking is somehow sensitive to thread ids.

**Comment by simon-mo** [comment] 2022-02-17 22:41
> Maybe the tracking is somehow sensitive to thread ids.
I think the task context might not be threadsafe? We had this problem in async actors before right? @clarkzinzow

**Comment by ericl** [comment] 2022-03-01 06:16
From what I can tell, the proximal cause of this is that tasks submitted to concurrent actors have a `skip_queue` flag set. When this is true, it seems that the `client_processed_up_to_` counter is stuck at -1, triggering the queueing warning as a false positive.

It seems to be disabled on purpose in core_worker_client.h in this case:
```     if (skip_queue) {
      // Set this value so that the actor does not skip any tasks when
      // processing this request. We could also set it to max_finished_seq_no_,
      // but we just set it to the default of -1 to avoid taking the lock.
      request->set_client_processed_up_to(-1);
```

Possible solutions:
- Fix this counter so it's updated correctly for concurrent actors (just commenting out the above line doesn't seem to do it).
- Disable this warning when skip_queue is true.

cc @scv119 @rkooo567  on recommendation on how to proceed.

**Comment by rkooo567** [comment] 2022-03-01 06:27
I think setting this to -1 was intended because we'd like to remove ordering for concurrent actor case. So, the second suggestion sounds good to me. Maybe we can indicate some integer is out-of-order execution? (like OUT_OF_ORDER == -2, and we don't raise warning in this case)

**Comment by ericl** [comment] 2022-03-01 06:36
@rkooo567 if we remove it this PR will do: https://github.com/ray-project/ray/pull/22720

It does disable the warning entirely for concurrent actors, which is unfortunate, but maybe this is fine as an interim fix.

**Comment by rkooo567** [comment] 2022-03-01 06:50
Thoughts @scv119 ? I think if we want to actually raise the warning, we should probably have 2 attributes to track "seqno" and the total queued tasks.

**Closed** 2022-03-01 22:28 UTC
Labels: bug, P1

**Comment by jgiannuzzi** [comment] 2022-04-27 19:10
Hi everyone, I had opened #22385 about the same bug, and opened a PR that aims at fixing the warning rather than disabling it for concurrent actors: #22386.

Could you please take a look at it?
