### ISSUE TITLE
[release][weekly] `impala_test` failed

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#20383] opened 2021-11-15 19:26 UTC
https://buildkite.com/ray-project/periodic-ci/builds/1621#211dac65-def0-44e5-8fda-4b8d69a6a36b

**Comment by amogkam** [comment] 2021-11-15 19:32
@gjoliver @sven1977 can you look into this please?

**Comment by iycheng** [comment] 2021-11-17 03:48
@gjoliver / @sven1977  do you have some eta about this fixing?

**Comment by gjoliver** [comment] 2021-11-17 04:06
We think the problem is transient actually.
This is a run that Amog helped kick off 11.5 hrs ago, and it's still going, passing the 8hr mark when the last single worker OOM happened.
We should be able to know for sure tomorrow morning.

**Comment by gjoliver** [comment] 2021-11-17 16:46
Rerun passed, as expected.
Marking this as closed now.

**Comment by gjoliver** [comment] 2021-11-17 16:46
https://buildkite.com/ray-project/periodic-ci/builds/1647

**Closed by gjoliver** 2021-11-17 16:46 UTC
Labels: release-blocker, P0

**Comment by amogkam** [comment] 2021-11-19 23:23
FYI @iycheng the failure is due to an app config change. We confirmed that reverting this back fixes the test and the revert has been merged on master: https://github.com/ray-project/ray/pull/20397
