### ISSUE TITLE
Release test rllib_learning_tests_ppo_new_api_stack_torch.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#43720] opened 2024-03-05 19:35 UTC
Release test **rllib_learning_tests_ppo_new_api_stack_torch.aws** failed. See https://buildkite.com/ray-project/release/builds/10431#018e0e4a-bed2-4fac-81d4-911f40a2d57b for more details.

Managed by OSS Test Policy

**Comment by anyscalesam** [comment] 2024-03-12 00:28
@sven1977 any update on this; we need confirmation that this is/is-not a release-blocker for ray210

**Comment by sven1977** [comment] 2024-03-13 15:27
Ok, seems to be a wront machine config on our end. 4 GPUs where 8 needed. Will fix asap ...

**Comment by sven1977** [comment] 2024-03-14 19:43
Closing this issue. Fixed by https://github.com/ray-project/ray/pull/44001

**Comment by can-anyscale** [comment] 2024-03-15 11:42
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release/builds/11364#018e40a9-0d08-4a0d-a61f-727e7786ca6a

**Comment by khluu** [comment] 2024-03-17 08:52
This test still failed on releases/2.10.0 branch even after the fix was cherry picked in @sven1977

**Comment by khluu** [comment] 2024-03-18 17:35
@sven1977 confirmed the test works when kicked off manually

**Comment by can-anyscale** [comment] 2024-03-19 12:19
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release/builds/11543#018e5541-f276-4b5c-8b85-e42a93201d0e

**Comment by can-anyscale** [comment] 2024-03-19 17:46
https://github.com/ray-project/ray/pull/44116 to mark this test as unstable

**Comment by can-anyscale** [comment] 2024-03-21 14:42
was not a blocker for 2.10

**Comment by sven1977** [comment] 2024-09-16 15:28
Closing. This CI test has been stabilized

**Closed by sven1977** 2024-09-16 15:28 UTC
Labels: bug, P0, rllib, release-test, jailed-test, unstable-release-test, ray-test-bot
