### ISSUE TITLE
[dashboard] 0.8.6/0.9.0dev - dashboard is not loading machine view

### ISSUE THREAD

**Issue by RocketRider** [ray-project/ray#9135] opened 2020-06-25 04:52 UTC
When I start ray with the following command I can't open the dashboard. This happens with 0.8.6 and 0.9.0dev.
Sometimes I can see it, but then when worker node starts, it does not work anymore.

`ray start --head --redis-port=8009 --node-manager-port=8010 --object-manager-port=8011 --redis-shard-ports=8012,8013 --autoscaling-config=~/ray_bootstrap_config.yaml
`
I just see the side for a short time with "loading" and then it disappears. The same happens in Chromium and Firefox.

dashboard.err:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0625 06:43:24.643254 15365 15365 global_state_accessor.cc:25] Redis server address = 10.64.249.173:8009, is test flag = 0
I0625 06:43:24.644155 15365 15365 redis_client.cc:141] RedisClient connected.
I0625 06:43:24.652101 15365 15365 redis_gcs_client.cc:88] RedisGcsClient Connected.
I0625 06:43:24.652530 15365 15365 service_based_gcs_client.cc:75] ServiceBasedGcsClient Connected.
2020-06-25 06:43:24,659 INFO node_stats.py:179 -- NodeStats: subscribed to RAY_REPORTER.*
2020-06-25 06:43:24,660 INFO node_stats.py:183 -- NodeStats: subscribed to RAY_LOG_CHANNEL
2020-06-25 06:43:24,660 INFO node_stats.py:187 -- NodeStats: subscribed to 9
2020-06-25 06:43:24,661 INFO node_stats.py:191 -- NodeStats: subscribed to b'ACTOR:*'
```

![Bildschirmfoto von 2020-06-25 06-46-30](https://user-images.githubusercontent.com/1881640/85655804-4e288880-b6b0-11ea-8250-6ab88945d3e7.png)
![Bildschirmfoto von 2020-06-25 06-47-02](https://user-images.githubusercontent.com/1881640/85655809-4f59b580-b6b0-11ea-8cf4-5a09fae3dbc8.png)

**Comment by rkooo567** [comment] 2020-06-25 05:11
Can you also specify your OS? Also, I couldn't reproduce it from my machine. Would you mind sharing `ray_bootstrap_config .yaml`?

**Comment by RocketRider** [comment] 2020-06-25 05:36
I am running on Ubuntu 19.10.
I can reproduce it even without the autoscale.

starting on head:
ray start --head --port=8009 --node-manager-port=8010 --object-manager-port=8011 --redis-shard-ports=8012,8013 --min-worker-port 7000 --max-worker-port 8000
=> dashboard works
starting on worker:
ray start --address='10.64.249.173:8009' --redis-password='5241590000000000'
=> dashboard no longer works

But my worker node is not running properly. I can't execute anything on it, I am still trying to find out why it is not working. So it is probably related. But the dashboard should still work even when the worker is not running correctly.



ray_bootstrap_config .yaml:
```
# An unique identifier for the head node and workers of this cluster.
cluster_name: default

## NOTE: Typically for local clusters, min_workers == initial_workers == max_workers.

# The minimum number of workers nodes to launch in addition to the head
# node. This number should be >= 0.
# Typically, min_workers == initial_workers == max_workers.
min_workers: 8
# The initial number of worker nodes to launch in addition to the head node.
# Typically, min_workers == initial_workers == max_workers.
initial_workers: 8

# The maximum number of workers nodes to launch in addition to the head node.
# This takes precedence over min_workers.
# Typically, min_workers == initial_workers == max_workers.
max_workers: 8

# Autoscaling parameters.
# Ignore this if min_workers == initial_workers == max_workers.
autoscaling_mode: default
target_utilization_fraction: 0.8
idle_timeout_minutes: 5

# This executes all commands on all nodes in the docker container,
# and opens all the necessary ports to support the Ray cluster.
# Empty string means disabled. Assumes Docker is installed.
docker:
    image: "" # e.g., tensorflow/tensorflow:1.5.0-py3
    container_name: "" # e.g. ray_docker
    # If true, pulls latest version of image. Otherwise, `docker run` will only pull the image
    # if no cached version is present.
    pull_before_run: True
    run_options: []  # Extra options to pass into "docker run"

# Local specific configuration.
provider:
    type: local
    head_ip: LOCAL_IP_XXX
    worker_ips: [REMOTE_IP_XXX]

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: rl_cluster # make sure the user exist in all the nodes!
    ssh_private_key: ~/ray_bootstrap_key.pem

# Leave this empty.
head_node: {}

# Leave this empty.
worker_nodes: {}

# Files or directories to copy to the head and worker nodes. The format is a
# dictionary from REMOTE_PATH: LOCAL_PATH, e.g.
file_mounts: {
#    "rayRLib": "rayRLib",
#    "/path2/on/remote/machine": "/path2/on/local/machine",
}

# List of commands that will be run before `setup_commands`. If docker is
# enabled, these commands will run outside the container and before docker
# is setup.
initialization_commands: []

# List of shell commands to run to set up each nodes.
setup_commands: []
#    - pip3 install -U ray==0.8.6

# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
- ray stop
- ulimit -c unlimited && ray start --head --port=8009 --node-manager-port=8010 --object-manager-port=8011 --redis-shard-ports=8012,8013 --min-worker-port 7000 --max-worker-port 8000  --autoscaling-config=~/ray_bootstrap_config.yaml


# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
- ray stop
- ray start --address=$RAY_HEAD_IP:8009 --num-cpus=4 --node-manager-port=8010 --object-manager-port=8011 --min-worker-port 7000 --max-worker-port 8000



```

**Comment by edoakes** [comment] 2020-06-26 21:14
cc @mfitton could you take a look and try to repro this?

**Comment by RocketRider** [comment] 2020-07-09 15:23
Seems to be the same issue as: https://github.com/ray-project/ray/issues/9317

**Comment by rkooo567** [comment] 2020-07-26 06:28
#9317 is P0, so we will have a fix soon. I will close the issue since it is duplicated.

**Closed by rkooo567** 2020-07-26 06:28 UTC
Labels: P2, bug, dashboard
