### ISSUE TITLE
[release][CI] chaos_dask_on_ray_large_scale_test_no_spilling failed 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29100] opened 2022-10-05 22:52 UTC
### What happened + What you expected to happen

[Build failure ](https://buildkite.com/ray-project/release-tests-branch/builds/1092#0183a524-1ec3-49c8-8eea-a477b73da424)
[Cluster ](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_paXtVfrbrefk5QDGNRFmUTyb?command-history-section=command_history)

Seems OOM related. 

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by rickyyx** [comment] 2022-10-14 17:11
Any idea of why [this](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_PrMJ5LyAWVfiD7c999B8Gf6k?command-history-section=command_history) happens

This is a recent [failure](https://buildkite.com/ray-project/release-tests-branch/builds/1114#0183d3c4-b0b1-4872-a931-2ceee4c7e6e2) from the release branch 


There is definitely the dashboard agent memory leak as shown in the logs, but wondering if there's anything running? I didn't see any other outputs. 


Feel free to close if this is not a release-blocker and not showing up in the main branch.

**Comment by scv119** [comment] 2022-10-17 18:53
looks RAY_memory_usage_threshold_fraction is still 0.95 in the test?

**Comment by scv119** [comment] 2022-10-17 19:04
huh look it's agent memory leak according to the log: 
agent is using 23.35GiB of memory.

```
	MEM	COMMAND
[2m[36m(MemoryMonitorActor pid=1471)[0m 414	23.35GiB	/home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/agen
[2m[36m(MemoryMonitorActor pid=1471)[0m 1366	9.42GiB	python dask_on_ray/large_scale_test.py --num_workers 20 --worker_obj_store_size_in_gb 20 --error_rat
[2m[36m(MemoryMonitorActor pid=1471)[0m 341	3.25GiB	/home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=
[2m[36m(MemoryMonitorActor pid=1471)[0m 234	0.18GiB	/home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/gcs/gcs_server --log_dir=/tmp/ray/s
[2m[36m(MemoryMonitorActor pid=1471)[0m 270	0.18GiB	/home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/dash
```

**Comment by scv119** [comment] 2022-10-17 19:05
duplicate of #29199

**Comment by rkooo567** [comment] 2022-10-18 10:05
@scv119 @rickyyx I don't think this issue is related to #29199. It has the agent memory leak. But the root cause is the raylet is killed all of sudden in the beg of the run. Look

```
[2m[36m(MemoryMonitorActor pid=1471)[0m INFO:root:Memory usage: 23.805648803710938 / 219.5999984741211
[2m[36m(MemoryMonitorActor pid=1471)[0m INFO:root:Top 10 process memory usage:
[2m[36m(MemoryMonitorActor pid=1471)[0m INFO:root:PID	MEM	COMMAND
[2m[36m(MemoryMonitorActor pid=1471)[0m 341	2.79GiB	/home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=
[2m[36m(MemoryMonitorActor pid=1471)[0m 1859	1.46GiB	ray::IDLE
[2m[36m(MemoryMonitorActor pid=1471)[0m 9909	1.45GiB	ray::IDLE
[2m[36m(MemoryMonitorActor pid=1471)[0m 1576	1.44GiB	ray::IDLE
[2m[36m(MemoryMonitorActor pid=1471)[0m 15838	1.43GiB	ray::IDLE
[2m[36m(MemoryMonitorActor pid=1471)[0m 16544	1.42GiB	ray::IDLE
[2m[36m(MemoryMonitorActor pid=1471)[0m 16306	1.41GiB	ray::IDLE
[2m[36m(MemoryMonitorActor pid=1471)[0m 11135	1.41GiB	ray::dask:load_array_one_minute-2a3154de-9a42-4db6-95cb-e0155c20336f()
[2m[36m(MemoryMonitorActor pid=1471)[0m 15104	1.33GiB	ray::dask:load_array_one_minute-651bc8f8-5e2a-4a28-9737-3d49b6bc888b()
[2m[36m(MemoryMonitorActor pid=1471)[0m 15933	1.32GiB	ray::dask:load_array_one_minute-0ede7712-3473-4031-b3b3-891ce8fbaa6b()
[2m[36m(raylet)[0m Spilled 28599 MiB, 598 objects, write throughput 617 MiB/s.
2022-10-13 17:11:26,687	WARNING worker.py:1839 -- The node with node id: 5eb6ae514496e2e85ba145374b07522b6d65488a70bd997699b6fc9a and address: 172.31.109.49 and node name: 172.31.109.49 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a 	(1) raylet crashes unexpectedly (OOM, preempted node, etc.) 
```

When the raylet crashes it only uses 23GB of memory

**Comment by rkooo567** [comment] 2022-10-18 10:06
I don't think this issue is related to #29199. It is true this has agent memory leak, but it hangs when the mem usage is just 50GB/200GB.

**Comment by scv119** [comment] 2022-10-19 04:51
looks at the runs, the tests are inherently flaky? 
<img width="2184" alt="image" src="https://user-images.githubusercontent.com/837180/196600443-6eba9b64-4c70-4e80-8838-0e509e110b78.png">

not a release blocker for now.

**Comment by rkooo567** [comment] 2022-10-19 06:40
Maybe it means we have a deadlock in our protocol (or when we recover tasks)?

**Comment by hora-anyscale** [comment] 2022-11-04 23:46
Per Triage Sync: Closing since flaky test

**Closed by hora-anyscale** 2022-11-04 23:46 UTC
Labels: bug, triage, datasets
