### ISSUE TITLE
[tune/placement group] Excessive Logging in Placement Group creation

### ISSUE THREAD

**Issue by Dan-RAI** [ray-project/ray#15695] opened 2021-05-08 10:01 UTC
### What is the problem?
Excessive log creation. A simple optimization run results in 400GB+ in /tmp/ray/log files !

ray 1.3.0
python 3.7

### Reproduction (REQUIRED)
```
reporter = tune.JupyterNotebookReporter(overwrite=True)

analysis = tune.run(
        objective,
        metric="mean_loss",
        mode="min",
        num_samples=10000,
        config={
            "X": tune.uniform(0, 3),
            "Y": tune.uniform(0, 3),
            "F": tune.uniform(1,2.5),
            "Z": tune.choice([1,2,3,4,5,6,7,8,9,10,11,12,13,14]),
            "W": tune.choice([20,30,40,50,60,70,80,90])          
        },
        resources_per_trial={
            "cpu": 1,
            "gpu": 0,
        },
        progress_reporter=reporter
        )
```

**Comment by richardliaw** [comment] 2021-05-08 16:50
Hey @Dan-RAI, thanks for reporting. This is a duplicate of https://github.com/ray-project/ray/issues/15595

The fix is to set the environment variables:

```
TUNE_MAX_PENDING_TRIALS_PG=1
```
or downgrade to ray==1.2.

We'll have to include this in a patch release in the next 2 weeks.

**Closed** 2021-05-12 00:08 UTC
Labels: P1, bug, tune
