### ISSUE TITLE
[data][release] chaos dask on ray test fails

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#34091] opened 2023-04-05 04:59 UTC
### What happened + What you expected to happen

release test is failing both for spilling and non-spilling version

### Versions / Dependencies

2.4.0 / master

### Reproduction script

https://buildkite.com/ray-project/release-tests-branch/builds/1528#01874ea2-d196-4579-86b1-d45a3b87ab31

### Issue Severity

None

**Comment by scottjlee** [comment] 2023-04-05 17:14
The run completed fairly quickly and with logs missing, so I triggered a re-run. The rerun for both tests failed quickly as well, this time with a different error:
```
HTTP response body: {"error":{"detail":"Instance types i3.8xlarge, i3.8xlarge are  not supported for cloud AWS on Anyscale. Please contact Anyscale support for more details."}}
```

Looks like we may need to change the instance type here? I checked on Anyscale workspaces, and it seems like i3.8xlarge is not available as an instance type. What would be an appropriate alternative? cc @c21

**Comment by c21** [comment] 2023-04-05 21:59
Seeing this error in log, not sure if this is root cause, FYI @scv119 .

```
[ERROR 2023-04-04 16:53:33,256] util.py: 131  Retry function call failed due to An error occurred (404) when calling the HeadObject operation: Not Found in 10 seconds...
  | Traceback (most recent call last):
  | File "/tmp/release-pVsEjvFtz3/release/ray_release/util.py", line 125, in exponential_backoff_retry
  | return f()
  | File "/tmp/release-pVsEjvFtz3/release/ray_release/file_manager/job_file_manager.py", line 65, in <lambda>
  | Filename=target,
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/boto3/s3/inject.py", line 195, in download_file
  | callback=Callback,
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/boto3/s3/transfer.py", line 326, in download_file
  | future.result()
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/s3transfer/futures.py", line 103, in result
  | return self._coordinator.result()
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/s3transfer/futures.py", line 266, in result
  | raise self._exception
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/s3transfer/tasks.py", line 269, in _main
  | self._submit(transfer_future=transfer_future, **kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/s3transfer/download.py", line 357, in _submit
  | **transfer_future.meta.call_args.extra_args,
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
  | return self._make_api_call(operation_name, kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 960, in _make_api_call
  | raise error_class(parsed_response, operation_name)
  | botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
 

<br class="Apple-interchange-newline">
```

**Comment by scv119** [comment] 2023-04-06 21:24
should be addressed by https://github.com/anyscale/product/pull/19291

**Comment by scv119** [comment] 2023-04-06 21:24
not a release blocker.

**Comment by clarng** [comment] 2023-04-07 16:44
We have a bunch of dask release test failures, should we file a release blocker?

https://buildkite.com/ray-project/release-tests-branch/builds/1535#0187581b-8a41-4817-b3b0-e376599b7d14
https://buildkite.com/ray-project/release-tests-branch/builds/1535#0187581b-8a43-4b37-b934-a7cbf8849a1c

@c21 @scv119

**Comment by scv119** [comment] 2023-04-10 18:21
new errors
```


WARNING 2023-04-06 13:46:27,715] sdk.py: 67  Please note that the config field should be a CreateProductionJobConfig object and the dict type will no longer be supported in the future. Please update to use CreateProductionJobConfig so that your code will continue to work.
--
  | [INFO 2023-04-06 13:46:28,609] anyscale_job_manager.py: 93  Link to job: https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_st5cpvjwk6mcbealt9ne5afbq8
  |  
  | [INFO 2023-04-06 13:46:59,914] anyscale_job_manager.py: 211  ... job not yet running ...(31 seconds, 1768 seconds to job timeout) ...
  | [INFO 2023-04-06 13:47:29,498] anyscale_job_manager.py: 211  ... job not yet running ...(60 seconds, 1739 seconds to job timeout) ...
  | [INFO 2023-04-06 13:47:59,559] anyscale_job_manager.py: 211  ... job not yet running ...(90 seconds, 1709 seconds to job timeout) ...
  | [INFO 2023-04-06 13:48:30,778] anyscale_job_manager.py: 211  ... job not yet running ...(122 seconds, 1677 seconds to job timeout) ...
  | [INFO 2023-04-06 13:48:59,917] anyscale_job_manager.py: 211  ... job not yet running ...(151 seconds, 1648 seconds to job timeout) ...
  | [INFO 2023-04-06 13:49:30,583] anyscale_job_manager.py: 211  ... job not yet running ...(181 seconds, 1618 seconds to job timeout) ...
  | [INFO 2023-04-06 13:50:00,314] anyscale_job_manager.py: 211  ... job not yet running ...(211 seconds, 1588 seconds to job timeout) ...
  | [INFO 2023-04-06 13:50:21,037] anyscale_job_manager.py: 225  ... job started ...(231 seconds) ...
  | [INFO 2023-04-06 13:50:25,416] anyscale_job_manager.py: 233  Job entered terminal state OUT_OF_RETRIES.
  | [INFO 2023-04-06 13:50:25,939] anyscale_job_runner.py: 277  /tmp/tmpu4j3d7cj.json
  | [ERROR 2023-04-06 13:50:26,046] util.py: 131  Retry function call failed due to An error occurred (404) when calling the HeadObject operation: Not Found in 10 seconds...
  | Traceback (most recent call last):
  | File "/tmp/release-aeASW6kyFN/release/ray_release/util.py", line 125, in exponential_backoff_retry
  | return f()
  | File "/tmp/release-aeASW6kyFN/release/ray_release/file_manager/job_file_manager.py", line 65, in <lambda>
  | Filename=target,
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/boto3/s3/inject.py", line 195, in download_file
  | callback=Callback,
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/boto3/s3/transfer.py", line 326, in download_file
  | future.result()
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/s3transfer/futures.py", line 103, in result
  | return self._coordinator.result()
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/s3transfer/futures.py", line 266, in result
  | raise self._exception
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/s3transfer/tasks.py", line 269, in _main
  | self._submit(transfer_future=transfer_future, **kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/s3transfer/download.py", line 357, in _submit
  | **transfer_future.meta.call_args.extra_args,
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
  | return self._make_api_call(operation_name, kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 960, in _make_api_call
  | raise error_class(parsed_response, operation_name)
  | botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found


```

**Closed** 2023-05-26 17:07 UTC
Labels: bug, data, Ray 2.4, v2.4.0-pick
