### ISSUE TITLE
[AIR] Segfault 

### ISSUE THREAD

**Issue by tobiasweede** [ray-project/ray#28791] opened 2022-09-26 22:27 UTC
### What happened + What you expected to happen

I want to tune a ML model.
Running ray-tune on a HPC cluster via slurm:

```
*** SIGSEGV received at time=1664230886 on cpu 14 ***
PC: @     0x2b1452d395a0  (unknown)  _dl_allocate_tls_init
[failure_signal_handler.cc : 331] RAW: Signal 11 raised at PC=0x2b1452d395a0 while already in AbslFailureSignalHandler()
    @     0x2b1453663630  (unknown)  (unknown)
    @ ... and at least 1 more frames
[2022-09-27 00:21:27,008 E 73412 73420] logging.cc:361: *** SIGSEGV received at time=1664230887 on cpu 14 ***
[2022-09-27 00:21:27,011 E 73412 73420] logging.cc:361: PC: @     0x2b1452d395a0  (unknown)  _dl_allocate_tls_init
[2022-09-27 00:21:27,011 E 73412 73420] logging.cc:361:     @     0x2b1453663630  (unknown)  (unknown)
[2022-09-27 00:21:27,015 E 73412 73420] logging.cc:361:     @ ... and at least 1 more frames
Fatal Python error: Segmentation fault
```

### Versions / Dependencies

LInux Kernel: 4.9.215-36.el7.x86_64
Python 3.8
ray: version 3.0.0.dev0

### Reproduction script

NA

### Issue Severity

High: It blocks me from completing my task.

**Comment by amogkam** [comment] 2022-09-27 20:10
Can you provide a simple reproduction script and the full stdout?

**Comment by richardliaw** [comment] 2022-11-11 18:54
Closing since we have not received a repro for 1 month. Please feel free to reopen if you can provide!

**Closed by richardliaw** 2022-11-11 18:54 UTC
Labels: bug, needs-repro-script, triage, air
