### ISSUE TITLE
[Core] Fix async_timeout usage on py3.11

### ISSUE THREAD

**Issue by grizzlybearg** [ray-project/ray#41826] opened 2023-12-12 14:39 UTC
### What happened + What you expected to happen

I'm unable to include dashboard during initialization of ray.
I get a ModuleNotFoundError despite having installed `async-timeout`
> Traceback (most recent call last):
  File "/mnt/azureml/cr/j/82488a70be0d475fb0acfdce930a7bfa/exe/wd/main.py", line 901, in <module>
    tran.train()
  File "/mnt/azureml/cr/j/82488a70be0d475fb0acfdce930a7bfa/exe/wd/main.py", line 736, in train
    self.initialize_ray()
  File "/mnt/azureml/cr/j/82488a70be0d475fb0acfdce930a7bfa/exe/wd/main.py", line 756, in initialize_ray
    ray.init(
  File "/azureml-envs/nuvoenv/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/azureml-envs/nuvoenv/lib/python3.11/site-packages/ray/_private/worker.py", line 1567, in init
    _global_node = ray._private.node.Node(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/azureml-envs/nuvoenv/lib/python3.11/site-packages/ray/_private/node.py", line 307, in __init__
    self.start_head_processes()
  File "/azureml-envs/nuvoenv/lib/python3.11/site-packages/ray/_private/node.py", line 1324, in start_head_processes
    self.start_api_server(
  File "/azureml-envs/nuvoenv/lib/python3.11/site-packages/ray/_private/node.py", line 1073, in start_api_server
    self._webui_url, process_info = ray._private.services.start_api_server(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/azureml-envs/nuvoenv/lib/python3.11/site-packages/ray/_private/services.py", line 1396, in start_api_server
    raise e from e
  File "/azureml-envs/nuvoenv/lib/python3.11/site-packages/ray/_private/services.py", line 1384, in start_api_server
    raise Exception(last_log_str)
Exception: 
The last 20 lines of /tmp/ray/session_2023-12-12_14-25-47_913287_26/logs/dashboard.log (it contains the error message from the dashboard): 
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/azureml-envs/nuvoenv/lib/python3.11/site-packages/ray/dashboard/utils.py", line 134, in get_all_modules
    raise e
  File "/azureml-envs/nuvoenv/lib/python3.11/site-packages/ray/dashboard/utils.py", line 121, in get_all_modules
    importlib.import_module(name)
  File "/azureml-envs/nuvoenv/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/azureml-envs/nuvoenv/lib/python3.11/site-packages/ray/dashboard/modules/test/test_agent.py", line 6, in <module>
    import ray.dashboard.modules.test.test_utils as test_utils
  File "/azureml-envs/nuvoenv/lib/python3.11/site-packages/ray/dashboard/modules/test/test_utils.py", line 3, in <module>
    import async_timeout
ModuleNotFoundError: No module named 'async_timeout'

### Versions / Dependencies

Ray 2.8.1
Python 3.11.6

### Reproduction script

`
ray.init(
            include_dashboard=False,
            ignore_reinit_error=True,
            _memory=round(math.pow(1024, 3) * self.available_memory)
        )
`

### Issue Severity

High: It blocks me from completing my task.

**Comment by jjyao** [comment] 2023-12-18 22:24
Duplicate of #41318 and it's fixed in 2.9.0

**Closed by jjyao** 2023-12-18 22:24 UTC
Labels: bug, triage, core

**Comment by grizzlybearg** [comment] 2023-12-19 09:03
> Duplicate of #41318 and it's fixed in 2.9.0

When will 2.9.0 be released?

**Comment by jjyao** [comment] 2023-12-19 17:29
End of this month.
