### ISSUE TITLE
[Datasets, Core] ensure liveness when spilling happens.

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#20005] opened 2021-11-03 00:20 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

While benchmarking dataset once thing we noticed is that the performance is extremely slow, and sometime it even stalls when thrashing happens. we should guarantee liveness as long as the data could fit into disk.

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Anything else

N/A

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by jjyao** [comment] 2022-03-02 22:19
We cannot reproduce it anymore: as long as we have enough disk, even if we reduce object store mem size, the test still passed. Will close it for now until we can reproduce it in the future.

**Closed by jjyao** 2022-03-02 22:19 UTC
Labels: bug, P0
