### ISSUE TITLE
GPU resources not released after killing actor

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#1065] opened 2017-10-03 01:05 UTC
The following crashes with 

```
Exception: Could not find a node with enough GPUs or other resources to create this actor. The local scheduler information is [ {'ClientType': 'local_scheduler', 'Deleted': False, 'DBClientID': '31dc437d6df69857fea7a9eb6f04004421039e18', 'AuxAddress': '127.0.0.1:37853', 'NumCPUs': 32.0, 'NumGPUs': 1.0, 'LocalSchedulerSocketName': '/tmp/scheduler9534802'}].
```

```
import ray
import sys
import time

@ray.remote(num_gpus=1)
class Actor(object):
  def __init__(self):
    pass

ray.init(num_gpus=1)
a = Actor.remote()
a.__ray_terminate__.remote(a._ray_actor_id.id())

time.sleep(5)
a = Actor.remote()  # crashes with not enough gpus
```

cc @stephanie-wang @robertnishihara

**Comment by robertnishihara** [comment] 2017-10-03 02:50
That's very surprising. I can reproduce it. However, this kind of thing should be covered by our tests.. I'll look into it.

**Comment by haoyangz** [comment] 2018-02-28 03:58
Is this fixed? I still get this error when running the above.

ray version:  0.3.1

**Comment by haoyangz** [comment] 2018-02-28 04:01
Update:  it will only work for me with `time.sleep(20)`. It seems it takes about 15 seconds to disconnect. Is this expected?

**Comment by robertnishihara** [comment] 2018-02-28 05:40
This should be fixed (and really shouldn't take 15 seconds).

There are some bigger changes in the pipeline to handle actor creation more like the way we handle regular task placement, and when that happens the problem should *definitely* go away.

**Comment by haoyangz** [comment] 2018-02-28 18:11
I had this error when I was tuning neural network hyperparameters using Ray Tune with Hyperband. I later switched to an older machine with only two GPUs, and it didn't give me error when running the above snippets (disconnected after a few seconds). But I still got error when running Ray Tune.  So in the end, only part of the intended hyper-param trials are actually tested.

Any suggestions to debug this?

Will these changes be included in the next version?

**Comment by richardliaw** [comment] 2018-02-28 19:52
@haoyangz can you post the error and the minimal script you used?

**Comment by haoyangz** [comment] 2018-03-01 23:08
@richardliaw I checked that with the default FIFO scheduler,  there is no error.

**Comment by haoyangz** [comment] 2018-03-02 17:18
Well with enough trials, it seems FIFO will also have the error but much less frequent. 

Another similar error observed under FIFO (maybe also under hyperband, not sure exactly):

```
Traceback (most recent call last):
  File "/cluster/zeng/code/research/software/miniconda/lib/python2.7/site-packages/ray-0.3.1-py2.7-linux-x86_64.egg/ray/worker.py", line 762, in _process_task
    *arguments)
  File "/cluster/zeng/code/research/software/miniconda/lib/python2.7/site-packages/ray-0.3.1-py2.7-linux-x86_64.egg/ray/actor.py", line 209, in actor_method_executor
    method_returns = method(actor, *args)
  File "/cluster/zeng/code/research/software/miniconda/lib/python2.7/site-packages/ray-0.3.1-py2.7-linux-x86_64.egg/ray/tune/trainable.py", line 89, in __init__
    self._setup()
  File "/cluster/zeng/code/research/ray_tune_wrapper/mymodel.py", line 51, in _setup
    self.net = Net(self.config).cuda()
  File "/cluster/zeng/code/research/software/miniconda/lib/python2.7/site-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/cluster/zeng/code/research/software/miniconda/lib/python2.7/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/cluster/zeng/code/research/software/miniconda/lib/python2.7/site-packages/torch/nn/modules/module.py", line 152, in _apply
    param.data = fn(param.data)
  File "/cluster/zeng/code/research/software/miniconda/lib/python2.7/site-packages/torch/nn/modules/module.py", line 216, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/cluster/zeng/code/research/software/miniconda/lib/python2.7/site-packages/torch/_utils.py", line 69, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/cluster/zeng/code/research/software/miniconda/lib/python2.7/site-packages/torch/cuda/__init__.py", line 358, in _lazy_new
    _lazy_init()
  File "/cluster/zeng/code/research/software/miniconda/lib/python2.7/site-packages/torch/cuda/__init__.py", line 121, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /opt/conda/conda-bld/pytorch_1512378422383/work/torch/lib/THC/THCGeneral.c:70
```

**Comment by richardliaw** [comment] 2018-03-02 18:00
OK I'll try to reproduce this later today

**Comment by richardliaw** [comment] 2018-03-04 09:37
OK unfortunately, I was unable to reproduce this error. Can you post the entire stdout for running the above script? I tried running the given script on a p3.2xlarge on EC2, using `pytorch_p36` and `pytorch_p27` and using a wheel built off of master.

Here are the wheels that I used:

[python3.6](https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.3.1-cp36-cp36m-manylinux1_x86_64.whl)
[python2.7](https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.3.1-cp27-cp27mu-manylinux1_x86_64.whl)

Perhaps try these out?

PS, the above script has a typo - you'll need to change the HyperBand instantiation to:
```
hyperband = HyperBandScheduler(
    time_attr="timesteps_total", reward_attr="mean_loss",
    max_t=100)
```
And perhaps change the return of the training result, since hyperband expects monotonically increasing metrics:
```
return TrainingResult(mean_loss=-loss.data[0], timesteps_this_iter=1)  #note that it is now negative
```

**Comment by haoyangz** [comment] 2018-03-04 14:49
Thanks for looking into this!

Yes I found these two typos after I posted it, but as expected unfortunately they are NOT relevant to this error.

I tried uninstalling Ray and building from your wheels but the error is still there.

The full error is:

```
Created LogSyncer for /afs/csail.mit.edu/u/z/zeng/ray_results/hyperband_test/my_class_18_H=67_2018-03-04_09-40-26XaXBhx ->
Error starting runner, retrying: Traceback (most recent call last):
  File "/cluster/zeng/code/research/software/miniconda/lib/python2.7/site-packages/ray/tune/trial_runner.py", line 195, in _launch_trial
    trial.start()
  File "/cluster/zeng/code/research/software/miniconda/lib/python2.7/site-packages/ray/tune/trial.py", line 135, in start
    self._setup_runner()
  File "/cluster/zeng/code/research/software/miniconda/lib/python2.7/site-packages/ray/tune/trial.py", line 371, in _setup_runner
    logger_creator=logger_creator)
  File "/cluster/zeng/code/research/software/miniconda/lib/python2.7/site-packages/ray/actor.py", line 765, in remote
    resources, ray.worker.global_worker)
  File "/cluster/zeng/code/research/software/miniconda/lib/python2.7/site-packages/ray/actor.py", line 422, in export_actor
    resources.get("GPU", 0), worker.redis_client)
  File "/cluster/zeng/code/research/software/miniconda/lib/python2.7/site-packages/ray/utils.py", line 323, in select_local_scheduler
    "information is {}.".format(local_schedulers))
Exception: Could not find a node with enough GPUs or other resources to create this actor. The local scheduler information is [{'ClientType': 'local_scheduler', 'Deleted': False,                          'LocalSchedulerSocketName': '/tmp/scheduler21114305', 'AuxAddress': '127.0.0.1:44854', u'GPU': 8.0, u'CPU': 40.0, 'DBClientID': '3527a9804b993d0502107c435ccda69d42eef1f4'}].

Worker ip unknown, skipping log sync for /afs/csail.mit.edu/u/z/zeng/ray_results/hyperband_test/my_class_18_H=67_2018-03-04_09-40-26XaXBhx
```

And the above error is AFTER all the gpus have been used as indicated by the following log snippet:

```
Round #0:
  Bracket(Max Size (n)=5, Milestone (r)=100, completed=0.2%): {RUNNING: 5}
  Bracket(Max Size (n)=8, Milestone (r)=33, completed=0.0%): {PENDING: 5, RUNNING: 3}
  Bracket(Max Size (n)=15, Milestone (r)=11, completed=0.0%): {PENDING: 7}
Resources used: 0/40 CPUs, 8/8 GPUs
Result logdir: /afs/csail.mit.edu/u/z/zeng/ray_results/hyperband_test
PENDING trials:
 - my_class_10_H=27:    PENDING
 - my_class_11_H=28:    PENDING
 - my_class_12_H=67:    PENDING
 - my_class_13_H=96:    PENDING
 - my_class_14_H=73:    PENDING
 - my_class_15_H=92:    PENDING
 - my_class_16_H=52:    PENDING
 - my_class_17_H=64:    PENDING
 - my_class_18_H=67:    PENDING
 - my_class_19_H=37:    PENDING
 - my_class_5_H=80: PENDING
 - my_class_9_H=81: PENDING
RUNNING trials:
 - my_class_0_H=96: RUNNING
 - my_class_1_H=38: RUNNING
 - my_class_2_H=35: RUNNING
 - my_class_3_H=73: RUNNING
 - my_class_4_H=88: RUNNING [pid=40364], 0 s, 1 ts, -711 loss
 - my_class_6_H=21: RUNNING
 - my_class_7_H=55: RUNNING
 - my_class_8_H=36: RUNNING
```

And I am using CUDA9.0 + cudnn 7 with eight Nvidia 1080 Ti.

**Comment by haoyangz** [comment] 2018-03-04 16:24
Ok after experimenting on AWS p3.2xlarge, it seems that it works fine for python 3.6 but NOT for python 2.7.

What I did to setup for python 2.7:

```
conda create -n py27 python=2.7
source activate py27
wget https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.3.1-cp27-cp27mu-manylinux1_x86_64.whl
python install ray-0.3.1-cp27-cp27mu-manylinux1_x86_64.whl
conda install pytorch torchvision cuda90 -c pytorch
```

@richardliaw  Could you help look more into this? Thanks!

**Comment by richardliaw** [comment] 2018-03-04 20:42
OK I was able to reproduce this now. Thanks! Will investigate this...

**Comment by richardliaw** [comment] 2018-03-05 21:22
Hey @haoyangz, #1651 should fix your issue (it works on the p3.2xlarge test case you posted). 

Do you mind trying it out? You'd have to check out the branch and build from source.

**Comment by haoyangz** [comment] 2018-03-06 01:25
@richardliaw  Thanks! I just tried on our cluster and it seems to still produce errors. Compiling from scratch gives error on the AMI I am using:

```
+ cp /home/ubuntu/ray/thirdparty/pkg/arrow/cpp/build/cpp-install/bin/plasma_store /home/ubuntu/ray/python/ray/core/src/plasma/
error: [Errno 2] No such file or directory: './ray/pyarrow_files/pyarrow'
``` 

Could you give me the AMI that works for you and I will try on that.

**Comment by richardliaw** [comment] 2018-03-06 04:01
I'm just using the DL AMI 5.0

**Comment by richardliaw** [comment] 2018-03-06 04:06
Could you post your output from running on cluster? Just to verify that the retries are in place.

**Comment by richardliaw** [comment] 2018-03-06 08:28
Looks like what is happening is that this error is thrown, probably because some GPU resources are being released asynchronously:
```
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /opt/conda/conda-bld/pytorch_1512378422383/work/torch/lib/THC/THCGeneral.c:70
```
and the handling for this is not very well isolated, causing a mismatch of resource bookkeeping and then subsequently the local scheduler issue on a couple experiments. We should probably improve the isolation, but it also seems like only a couple trials fail and the experiment actually continues.

For debugging purposes, can you insert the following lines into your script at the beginning of` def _setup(self):`? It would be great to get the logs from this.
```
print("Ray detects {}".format(ray.utils.get_cuda_visible_devices()))
print("Torch detects {}".format(torch.cuda.device_count()))
print("Torch ready? {}.format(torch.cuda.is_available()))
```

BTW, as a quick workaround, you could try the following: in `_setup(self)`, sleep until Torch detects an available GPU.

**Comment by haoyangz** [comment] 2018-03-06 21:00
So I add the following lines at the begining of `def _setup()`:
```
        print("Ray detects {}".format(ray.utils.get_cuda_visible_devices()))
        print("Torch detects {}".format(torch.cuda.device_count()))
        print("Torch ready? {}".format(torch.cuda.is_available()))

        tried_time = 0
        try_interval = 1
        while not torch.cuda.is_available():
            print("Torch is not ready, wait for {} s. Have already waited for   {} s".format(try_interval, tried_time))
            time.sleep(try_interval)
            tried_time += try_interval

        print("Ready now! Waited for {} s".format(tried_time))
```

And here is the [stderr](https://s3.amazonaws.com/zengtest/error) and [stdout](https://s3.amazonaws.com/zengtest/output). It seems that the ones that failed to get the resource initially never got it later, no matter how long it waited (the ready msg "Ready now" never shows up in stdout) . From stderr, it seems they are killed/ignored because Ray waited for too long? The whole program hung forever and I had to interrupt with ctrl+c.

**Comment by richardliaw** [comment] 2018-03-06 23:06
From the stdout, only ` - my_class_17_H=93` was never able to run. It looks like the rest of the trials ran successfully? 

Is that right? If so, it's weird that the program hung forever.

**Comment by richardliaw** [comment] 2018-03-06 23:13
Stdout errors aside, this line is very weird - 
`Attempting to create an actor but there aren't enough available GPUs. We'll start the worker anyway without any GPUs, but this is incorrect behavior.`

**Comment by haoyangz** [comment] 2018-03-06 23:29
@richardliaw  Per you first comment, yes that seems to be the only trial that had an error. Overall the process is very random and sometimes all the trials are fine sometimes there are a few errors.

Per your second question, I don't know but searching in this repository I found [this](https://github.com/ray-project/ray/blob/0fcceef772a3126e027b0817988022ebda1a506e/src/local_scheduler/local_scheduler.cc#L964). Any idea what might be going on?

**Comment by richardliaw** [comment] 2018-03-07 02:03
Looks like there's inconsistency between the local scheduler and the Redis state. @robertnishihara is currently working on a fix (and we'll keep you updated on a PR). 

As a temporary fix (if urgent), here are two steps that will be beneficial:

1.  based off of the aforementioned PR, you can modify [this line](
https://github.com/ray-project/ray/pull/1651/files#diff-fce6ca2199c23a1292606f87d1422e89R181) to be `for sec in range(1, 5)`, which should decrease chance of failure significantly.

2. Consider putting this code in the beginning your `train` function - this will kill trials that were falsely started. 
```
cuda_devices = ray.utils.get_cuda_visible_devices()
if not cuda_devices:
    print("Ray detects {}".format(cuda_devices))
    raise Exception("No GPU devices allocated by Ray!")
``` 

Alternatively, if the GPU is not necessary for every, you could just `if-else` the cuda call based off of `torch.cuda.is_available()`. As you'd expect, certain trials would be slower, but you'll still get some of these results.

**Comment by richardliaw** [comment] 2018-03-20 03:07
@haoyangz now that #1668 is in; do you still run into errors like this for HyperBand?

**Comment by haoyangz** [comment] 2018-03-23 15:53
@richardliaw No errors now. Thanks!

**Comment by richardliaw** [comment] 2018-03-23 16:42
Awesome! Will close this issue for now.

**Closed by richardliaw** 2018-03-23 16:42 UTC
Labels: bug
