### ISSUE TITLE
[1.5.2] [1.4.1] [tune] [internalerror] The client has been closed.

### ISSUE THREAD

**Issue by dmkulazhenko** [ray-project/ray#17506] opened 2021-08-02 15:32 UTC
### Important:
This issue was NOT tested on latest Ray==1.5.1.
It's reported only because I have this in trace:
`RuntimeError: [internalerror] The client has been closed. Please report this stacktrace + your cluster configuration on Github!`
If you don't care about it and I shouldn't post this trace -- fell free to close it.

**UPD:** reproduced on ray==**1.5.1** and ray==**1.5.2**. 

### Env

Ray ver: ray[all]==1.4.1
OS: Amazon Linux 2
Python: 3.8.11 (pyenv-global)

Overall - clean AML2 with some libs such as `zlib / libffi / bzip2 / readline / ...`

### Reproduction

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

------

#### Ray cloud cluster config:

```
cluster_name: RAT-cluster
max_workers: 3
upscaling_speed: 1
idle_timeout_minutes: 1

provider:
    type: aws
    region: eu-west-1
    availability_zone: eu-west-1a
    cache_stopped_nodes: True

available_node_types:
    ray.head.default:
        min_workers: 0
        max_workers: 0
        resources: {"CPU": 0}
        node_config:
            InstanceType: m5.large
            ImageId: "my-ami"
            KeyName: stub
            SecurityGroupIds: ["sg-"]
            SubnetId: "subnet-"
            IamInstanceProfile: {Name: "ray-cluster"}
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 25

    ray.worker.default:
        min_workers: 0
        max_workers: 3
        resources: {}
        node_config:
            InstanceType: c5.2xlarge
            ImageId: "my-ami"
            KeyName: stub
            SecurityGroupIds: ["sg-"]
            SubnetId: "subnet-"
            IamInstanceProfile: {Name: "ray-cluster"}
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 25

head_node_type: ray.head.default

auth:
    ssh_user: ray-master
    ssh_private_key: "/home/stub/.ssh/stub.pem"

file_mounts: {
    /home/ray-master/.ssh: "/home/stub/Projects/project/local/keys"
}

rsync_exclude:
    - "**/.git"
    - "**/.git/**"
rsync_filter:
    - ".gitignore"

initialization_commands: []
setup_commands: [
    "test -e /home/ray-master/project || git clone -b branch --single-branch git@my.git/project",
    "test -e /home/ray-master/project2 || git clone git@my.git/project2",
    "pip install /home/ray-master/project",
    "pip install /home/ray-master/project2"
]
```

Tune-job that I execute is pretty simple:
- `optuna` calibration
- `checkpoint_frequency=1`
- `samples=5`

Really nothing special in calibration job, just a `tune.Experiment` executed via `tune.run()`.
Ray init: `ray.init(address="auto")`.

Trace:
```
== Status ==
Memory usage on this node: 1.7/7.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 2.0/8 CPUs, 0/0 GPUs, 0.0/15.61 GiB heap, 0.0/6.69 GiB objects
Current best trial: 56cb7d2e with f1=0.3159319785218439 and parameters={...}
Result logdir: /home/ray-master/pipeopt_experiments/test
Number of trials: 5/5 (2 RUNNING, 3 TERMINATED)
+----------------+------------+-------------------+---------------------------------------------------+------------------------------------------+-----------------------------------------+----------------------------------------------+-----------------------------------+-----------------------------------+--------+------------------+----------+-------------+-----------+
| Trial name     | status     | loc            
|----------------+------------+-------------------+---------------------------------------------------+------------------------------------------+-----------------------------------------+----------------------------------------------+-----------------------------------+-----------------------------------+--------+------------------+----------+-------------+-----------|
| Tuner_5673671a | RUNNING    | 10.111.0.227:3802 |   
| Tuner_5696156c | RUNNING    |                   |
| Tuner_fb9e2096 | TERMINATED |                   | 
| Tuner_56a9029e | TERMINATED |                   | 
| Tuner_56cb7d2e | TERMINATED |                   | 
+----------------+------------+-------------------+---------------------------------------------------+------------------------------------------+-----------------------------------------+----------------------------------------------+-----------------------------------+-----------------------------------+--------+------------------+----------+-------------+-----------+


2021-08-02 14:29:04,317	ERROR syncer.py:190 -- Sync execution failed.
Traceback (most recent call last):
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/syncer.py", line 186, in sync_down
    result = self.sync_client.sync_down(self._remote_path,
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/sync_client.py", line 212, in sync_down
    return self._execute(self.sync_down_template, source, target)
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/sync_client.py", line 271, in _execute
    stdout=self._get_logfile())
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/sync_client.py", line 201, in _get_logfile
    raise RuntimeError(
RuntimeError: [internalerror] The client has been closed. Please report this stacktrace + your cluster configuration on Github!
2021-08-02 14:29:04,317	ERROR syncer.py:413 -- Trial Tuner_5673671a: Checkpoint sync skipped. This should not happen.
Trial Tuner_5696156c reported f1=0.00 with parameters={...}. This trial completed.
== Status ==
Memory usage on this node: 1.7/7.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 1.0/8 CPUs, 0/0 GPUs, 0.0/15.61 GiB heap, 0.0/6.69 GiB objects
Current best trial: 56cb7d2e with f1=0.3159319785218439 and parameters={...}
Result logdir: /home/ray-master/pipeopt_experiments/test
Number of trials: 5/5 (1 RUNNING, 4 TERMINATED)
+----------------+------------+-------------------+---------------------------------------------------+------------------------------------------+-----------------------------------------+----------------------------------------------+-----------------------------------+-----------------------------------+--------+------------------+----------+-------------+-----------+
| Trial name     | status     | loc               |  
|----------------+------------+-------------------+---------------------------------------------------+------------------------------------------+-----------------------------------------+----------------------------------------------+-----------------------------------+-----------------------------------+--------+------------------+----------+-------------+-----------|
| Tuner_5696156c | RUNNING    | 10.111.0.227:3796 | 
| Tuner_fb9e2096 | TERMINATED |                   |   
| Tuner_5673671a | TERMINATED |                   |  
| Tuner_56a9029e | TERMINATED |                   |    
| Tuner_56cb7d2e | TERMINATED |                   |    
+----------------+------------+-------------------+---------------------------------------------------+------------------------------------------+-----------------------------------------+----------------------------------------------+-----------------------------------+-----------------------------------+--------+------------------+----------+-------------+-----------+


2021-08-02 14:39:36,857	ERROR syncer.py:190 -- Sync execution failed.
Traceback (most recent call last):
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/syncer.py", line 186, in sync_down
    result = self.sync_client.sync_down(self._remote_path,
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/sync_client.py", line 212, in sync_down
    return self._execute(self.sync_down_template, source, target)
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/sync_client.py", line 271, in _execute
    stdout=self._get_logfile())
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/sync_client.py", line 201, in _get_logfile
    raise RuntimeError(
RuntimeError: [internalerror] The client has been closed. Please report this stacktrace + your cluster configuration on Github!
2021-08-02 14:39:36,858	ERROR syncer.py:413 -- Trial Tuner_5696156c: Checkpoint sync skipped. This should not happen.
== Status ==
Memory usage on this node: 1.7/7.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/8 CPUs, 0/0 GPUs, 0.0/15.61 GiB heap, 0.0/6.69 GiB objects
Current best trial: 56cb7d2e with f1=0.3159319785218439 and parameters={...}
Result logdir: /home/ray-master/pipeopt_experiments/test
Number of trials: 5/5 (5 TERMINATED)
+----------------+------------+-------+---------------------------------------------------+------------------------------------------+-----------------------------------------+----------------------------------------------+-----------------------------------+-----------------------------------+--------+------------------+----------+-------------+-----------+
| Trial name     | status     | loc   |  
|----------------+------------+-------+---------------------------------------------------+------------------------------------------+-----------------------------------------+----------------------------------------------+-----------------------------------+-----------------------------------+--------+------------------+----------+-------------+-----------|
| Tuner_fb9e2096 | TERMINATED |       | 
| Tuner_5673671a | TERMINATED |       |   
| Tuner_5696156c | TERMINATED |       |    
| Tuner_56a9029e | TERMINATED |       |       
| Tuner_56cb7d2e | TERMINATED |       |      
+----------------+------------+-------+---------------------------------------------------+------------------------------------------+-----------------------------------------+----------------------------------------------+-----------------------------------+-----------------------------------+--------+------------------+----------+-------------+-----------+

2021-08-02 14:39:36,986	INFO tune.py:549 -- Total run time: 3641.36 seconds (3641.18 seconds for the tuning loop).
```

Also (not during this run, but one time I had this error during same trial run:
```
Failure # 1 (occurred at 2021-07-30_21-45-54)
Traceback (most recent call last):
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 702, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 686, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/worker.py", line 1483, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
```

Ray job executes like this:
```
$> ray up ray-cluster.yaml
$> ray submit ray-cluster.yaml test.py
```

test.py:
```
from project.api import ExperimentAPI
from project.pipeopt import Driver

CONFIG = {...}


def main():
    # Returns over internal Experiment object
    exp = ExperimentAPI(**CONFIG).instantiate() 
    
    # Driver -- tool, which inits ray
    driver = Driver(ray_init_params={"address": "auto"})
    
    # Transforms exp to Tune.Experiment and executes using Tune.run()
    driver.execute(exp)


if __name__ == "__main__":
    main()

```

Executing `test.py` on local machine (without `address="auto"`) leads to successful calibration.

**Comment by Mao771** [comment] 2021-08-13 07:29
Same problem:

```
2021-08-13 07:19:21,541 ERROR syncer.py:190 -- Sync execution failed.
Traceback (most recent call last):
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/syncer.py", line 186, in sync_down
    result = self.sync_client.sync_down(self._remote_path,
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/sync_client.py", line 212, in sync_down
    return self._execute(self.sync_down_template, source, target)
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/sync_client.py", line 271, in _execute
    stdout=self._get_logfile())
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/sync_client.py", line 201, in _get_logfile
    raise RuntimeError(
RuntimeError: [internalerror] The client has been closed. Please report this stacktrace + your cluster configuration on Github!
2021-08-13 07:19:21,541 ERROR syncer.py:413 -- Trial Tuner_5b7bbf54: Checkpoint sync skipped. This should not happen.
```

**Comment by dmkulazhenko** [comment] 2021-08-20 16:52
+ I can give you any error logs you want from head / worker nodes.

**Comment by max0x7ba** [comment] 2021-09-02 17:25
I experience the same problem with the same stacktrace with `ray-2.0.0.dev0`.

**Comment by richardliaw** [comment] 2021-09-02 17:27
@xwjiang2010 could you take this issue?

**Comment by max0x7ba** [comment] 2021-09-03 10:40
IMO, a part of the problem is that the syncers are cached and reused, but closed syncers don't get removed from the caches. After one trial completes on a node the syncer for the node is closed and subsequent trials on the same node fail to sync.

One example is https://github.com/ray-project/ray/blob/master/python/ray/tune/syncer.py#L380, replacing that condition with:

```
if trial not in self._syncers or self._syncers[trial].sync_client._closed:
```

Fixes this error, but I still get the following errors with no further details:
```
2021-09-03 10:30:18,633 ERROR trial_runner.py:940 -- Trial train_702a772a: Error handling checkpoint /home/max/ray_results/B/train_702a772a_params/checkpoint_000003/
Traceback (most recent call last):
  File "/home/max/anaconda3/envs/torch/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 932, in _process_trial_save
    self._callbacks.on_checkpoint(
  File "/home/max/anaconda3/envs/torch/lib/python3.8/site-packages/ray/tune/callback.py", line 216, in on_checkpoint
    callback.on_checkpoint(**info)
  File "/home/max/anaconda3/envs/torch/lib/python3.8/site-packages/ray/tune/syncer.py", line 459, in on_checkpoint
    self._sync_trial_checkpoint(trial, checkpoint)
  File "/home/max/anaconda3/envs/torch/lib/python3.8/site-packages/ray/tune/syncer.py", line 430, in _sync_trial_checkpoint
    raise TuneError("Trial {}: Checkpoint path {} not "
ray.tune.error.TuneError: Trial train_702a772a: Checkpoint path /home/max/ray_results/B/train_702a772a_params/checkpoint_000003/ not found after successful sync down.
```

@xwjiang2010 @richardliaw

**Comment by max0x7ba** [comment] 2021-09-03 13:26
The following change seems to fix the problem completely for me:

```
(torch) max@c01:~/anaconda3/envs/torch/lib/python3.8/site-packages/ray/tune$ diff -u syncer.py{~,}
--- syncer.py~	2021-07-08 13:34:06.000000000 +0000
+++ syncer.py	2021-09-03 13:19:26.046686402 +0000
@@ -448,7 +448,7 @@
             trainable_ip = ray.get(trial.runner.get_current_ip.remote())
         trial_syncer.set_worker_ip(trainable_ip)
         trial_syncer.sync_down_if_needed()
-        trial_syncer.close()
+        # trial_syncer.close()
 
     def on_checkpoint(self, iteration: int, trials: List["Trial"],
                       trial: "Trial", checkpoint: Checkpoint, **info):
```

@xwjiang2010 @richardliaw

**Comment by max0x7ba** [comment] 2021-09-06 22:42
It looks like not closing the syncer leaves `checkpoint_tmpxxxxxx` directories.

**Comment by max0x7ba** [comment] 2021-09-07 14:20
Testing `--temp-dir=/tmp` rsync option...

**Comment by xwjiang2010** [comment] 2021-09-07 15:59
Thanks @max0x7ba and @dmkulazhenko for reporting it!
I was able to reproduce with a head + 1worker set up running one trial.
When the last iteration of a trial is done, the following happens, which is problematic:
on_trial_complete ----> close sync_client ---> on_trial_save ---> sync_client.sync_down(), which throws an error as sync_client is already closed.

Recommended sync_client contract:
1. There could be additional calls on sync client after it's closed. Sync client should not crash but just gracefully disregard the calls. 
2. For sync_client implementation provided by us, we do a force sync down before it's closed to capture the more fresh checkpoint content.

@richardliaw @krfricke Want to run this by you to see if you are ok with the semantics and then I will implement the change. Thanks!

**Comment by max0x7ba** [comment] 2021-09-07 16:05
> 1. There could be additional calls on sync client after it's closed. Sync client should not crash but just gracefully disregard the calls.

The sync client is cached and reused, so that closing it causes other trial syncs from the same worker to fail.

Not closing the sync client at all seems to solve the problem.

**Comment by richardliaw** [comment] 2021-09-08 22:10
@max0x7ba hmm, sorry where is the code where the sync client is cached/reused?

**Comment by xwjiang2010** [comment] 2021-09-08 22:12
Also, see [Fix file descriptor leak by syncer](https://github.com/ray-project/ray/pull/12590/files) for information on why we cannot just leave the temporary files lingering around.

**Comment by max0x7ba** [comment] 2021-09-08 22:40
> @max0x7ba hmm, sorry where is the code where the sync client is cached/reused?

I thought in 

https://github.com/ray-project/ray/blob/9a35099992f5e21a1ea169d23b6f0aa112f12201/python/ray/tune/syncer.py#L39
https://github.com/ray-project/ray/blob/9a35099992f5e21a1ea169d23b6f0aa112f12201/python/ray/tune/syncer.py#L379

But now looking more into it, the syncers are per trial rather than worker host. My mistake.

**Comment by xwjiang2010** [comment] 2021-09-08 23:17
I took a stab with [this](https://github.com/ray-project/ray/pull/18450). I want to gather some feedback first. By patching the PR, my specific repro is fixed.

**Comment by max0x7ba** [comment] 2021-09-09 13:48
@xwjiang2010 It still seems to me that the root of the problem is that the syncer objects never get destroyed, rather they get stuck in those collections forever and this is why it needs to be closed explicitly. Closing explicitly fixes the file descriptor leak, but syncer objects continue to leak indefinitely.

**Comment by xwjiang2010** [comment] 2021-09-10 04:40
So there are a few issues:
- syncer object not released after a trial is terminated. Since we have 1-1 mapping between syncer and trial, this could be a memory leak when trial number is large.
- The contract around Ray Tune callback is vague now. For example, on_trial_complete() callback is invoked before the last on_checkpoint() callback, which leads to "client closed" error that you saw. This seems wrong. I believe a proper fix should involve an auditing of the current callback order.
My current PR is more of a "hack" than a proper fix. If this issue is not blocking you now, I would like to take some time to scope out a proper fix. Thanks!
@krfricke since we briefly talked about this today.

**Closed** 2022-05-03 14:32 UTC
Labels: bug, P1, tune
