### ISSUE TITLE
[Bug] Autoscaler killed idle nodes trigger the message ""The node has been marked dead because the detector has missed too many heartbeats from it"

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#18744] opened 2021-09-19 01:19 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

When the autoscaler kills idle nodes, you get the message "The node has been marked dead because the detector has missed too many heartbeats from it".

We should not print this warning message since it's confusing.

### Reproduction script

Run any autoscaling cluster, run a workload that launches a node, and wait for idle timeout to kill a node.

cc @DmitriGekhtman @AmeerHajAli 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment] 2021-09-19 02:03
Duplicate of https://github.com/ray-project/ray/issues/14129

We should get around to fixing this..

**Comment by DmitriGekhtman** [comment] 2021-09-19 02:03
Duplicate of https://github.com/ray-project/ray/issues/14129

We should get around to fixing this..

**Closed by DmitriGekhtman** 2021-09-19 02:03 UTC
Labels: bug, triage
