### ISSUE TITLE
`connect() got an unexpected keyword argument: 'use_raylet'`

### ISSUE THREAD

**Issue by alok** [ray-project/ray#1966] opened 2018-04-28 23:31 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.13.4
- **Ray installed from (source or binary)**: source
- **Ray version**: latest build from master
- **Python version**: 3.6.4 Anaconda
- **Exact command to reproduce**: `import ray, ray.init()`

### Describe the problem
Running *just* `import ray;ray.init()` on my mac gives a TypeError. 

I bisected, and the last good commit is `0fc989c6`. Commit `fbfbb1c0` is where the error starts.

### Source code / logs

```
 Traceback (most recent call last):
  File "/Users/alokbeniwal/dev/ray/python/ray/workers/default_worker.py", line 38, in <module>
    use_raylet=(args.raylet_name is not None))
TypeError: connect() got an unexpected keyword argument 'use_raylet'
Traceback (most recent call last):
  File "/Users/alokbeniwal/dev/ray/python/ray/workers/default_worker.py", line 38, in <module>
Traceback (most recent call last):
  File "/Users/alokbeniwal/dev/ray/python/ray/workers/default_worker.py", line 38, in <module>
    use_raylet=(args.raylet_name is not None))
TypeError: connect() got an unexpected keyword argument 'use_raylet'
    use_raylet=(args.raylet_name is not None))
TypeError: connect() got an unexpected keyword argument 'use_raylet'
Traceback (most recent call last):
  File "/Users/alokbeniwal/dev/ray/python/ray/workers/default_worker.py", line 38, in <module>
    use_raylet=(args.raylet_name is not None))
TypeError: connect() got an unexpected keyword argument 'use_raylet'
Traceback (most recent call last):
  File "/Users/alokbeniwal/dev/ray/python/ray/workers/default_worker.py", line 38, in <module>
    use_raylet=(args.raylet_name is not None))
TypeError: connect() got an unexpected keyword argument 'use_raylet'
Traceback (most recent call last):
  File "/Users/alokbeniwal/dev/ray/python/ray/workers/default_worker.py", line 38, in <module>
    use_raylet=(args.raylet_name is not None))
TypeError: connect() got an unexpected keyword argument 'use_raylet'
Traceback (most recent call last):
  File "/Users/alokbeniwal/dev/ray/python/ray/workers/default_worker.py", line 38, in <module>
    use_raylet=(args.raylet_name is not None))
TypeError: connect() got an unexpected keyword argument 'use_raylet'
Traceback (most recent call last):
  File "/Users/alokbeniwal/dev/ray/python/ray/workers/default_worker.py", line 38, in <module>
    use_raylet=(args.raylet_name is not None))
TypeError: connect() got an unexpected keyword argument 'use_raylet'
```

**Comment by robertnishihara** [comment] 2018-04-29 00:11
This makes me think that some of the files are out of sync or that you have two versions of Ray installed (e.g., one from `pip` and one from source). Can you double check that `import ray; ray.__file__` is the one you built from source? Can you also check `git status` and make sure that there aren't any unintended changes?

**Comment by Alok** [comment] 2018-04-30 06:16
Just rechecked `ray.__file__`. It's the one from source.

Just to be sure, I uninstalled the one from `pip`, I cloned a fresh copy of the repo in a totally different part of my file tree from the previous one, built it, and got the same error. Same commits worked/broke.

I suppose it could be something to do with my machine, but I'm struggling to see how I'd get that specific error then.

**Comment by alok** [comment] 2018-05-01 14:42
It's the ray built from source. (`~/miniconda3/bin/ray`)

**Comment by robertnishihara** [comment] 2018-08-10 18:08
Closing because I don't think is reproducible. Let me know if it's still an issue.

**Closed by robertnishihara** 2018-08-10 18:08 UTC
