### ISSUE TITLE
[release][CI] air_benchmark_xgboost_cpu_10 failure 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#28974] opened 2022-10-03 05:22 UTC
### What happened + What you expected to happen

[Build failure](https://buildkite.com/ray-project/release-tests-branch/builds/1080#0183906e-87b2-4e2b-9012-d8574f44622e)
[Cluster ](https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_E9wyLXYTyJDjiF84FueREXnD)

```
run_xgboost_prediction takes 531.6400554740001 seconds.
Results: {'training_time': 793.1882077000001, 'prediction_time': 531.6400554740001}
Traceback (most recent call last):
  File "workloads/xgboost_benchmark.py", line 153, in <module>
    main(args)
  File "workloads/xgboost_benchmark.py", line 134, in main
    f"Batch prediction on XGBoost is taking {prediction_time} seconds, "
RuntimeError: Batch prediction on XGBoost is taking 531.6400554740001 seconds, which is longer than expected (450 seconds).

```

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by c21** [comment] 2022-10-04 17:05
Still failing now - https://buildkite.com/ray-project/release-tests-branch/builds/1090#01839fe4-545c-4598-9c70-0a0eb95e6df3 .

**Comment by c21** [comment] 2022-10-07 16:31
Still failing yesterday - https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_LmPgPzNA7TLdJ32Wmd1AwKdH?command-history-section=command_history . 

Verified the change is taking effect on the run - https://github.com/ray-project/ray/commit/8fd6a5be144cf8fe21c4507807f306db69e67034 .

**Comment by jiaodong** [comment] 2022-10-07 23:41
We had regression on prediction side with cluster env on commit fd01488 , node memory pattern from training to prediction is 

<img width="1341" alt="Screen Shot 2022-10-07 at 4 39 23 PM" src="https://user-images.githubusercontent.com/6372689/194675700-4b1648be-8b1a-4e0b-9fa2-e4cce2994bf2.png">

Where our known, stable good run on commit c8dbbf3, node memory pattern from training to prediction is 

<img width="1438" alt="Screen Shot 2022-10-07 at 4 40 34 PM" src="https://user-images.githubusercontent.com/6372689/194675760-bf8840e7-57b8-4f14-862b-a125d0a0913c.png">

As a result, 10 worker 100GB data prediction regressed from 300sec to 500secs and failed release test.

**Comment by c21** [comment] 2022-10-08 00:25
CC @amogkam (ML oncall) FYI for @jiaodong's finding.

**Comment by jiaodong** [comment] 2022-10-11 19:52
@clarkzinzow 

I did a few more release test bisection with prediction batch_size = 8192 

Latency-wise, we're good with larger batch size on prediction side that e2e latency can be cut <200secs

```
run_xgboost_prediction takes 191.02347457200085 seconds.
run_xgboost_prediction takes 183.74121447799916 seconds.
```

But memory footprint suggests each node consistently used ~15 GB of RAM 

<img width="1275" alt="Screen Shot 2022-10-11 at 12 47 31 PM" src="https://user-images.githubusercontent.com/6372689/195185448-27fffd

compare to good commit on Oct 5th last Wed.

<img width="1096" alt="Screen Shot 2022-10-11 at 12 50 01 PM" src="https://user-images.githubusercontent.com/6372689/195185484-1e17c3a7-5c4d-422c-9326-3a87fcd8399b.png">
c8-d1a1-48b3-af05-6c8faa30166a.png">

**Comment by jiaodong** [comment] 2022-10-13 04:09
Root caused to https://github.com/ray-project/ray/pull/29103 cc: @clarng is this expected ?

Full bisection log see
https://docs.google.com/document/d/1SfbHV5AFZe3P_VA_snDve6yeCh8cobVAydn7MRqRSIE/edit#

**Comment by clarng** [comment] 2022-10-13 16:47
I think this is expected. There are several changes to the product + oss that is causing this
- product added memory limit to the container and we have less memory per node now (64 GiB -> 57 GiB)
- the test is ingesting 100GB of data on 10 nodes. It is expected that the memory usage on each node is > 10 GiB as it needs to process and store the results to the object store in addition to using the heap. 3-5 GiB per node doesn't look like the right amount of activity memory per node.

**Comment by jiaodong** [comment] 2022-10-13 21:04
^ PR about to increase batch size should be all we need, all other investigations and discussions completed

**Comment by clarkzinzow** [comment] 2022-10-18 00:41
@jiaodong With this [PR merged](https://github.com/ray-project/ray/pull/29337), and release tests passing on both the [PR](https://buildkite.com/ray-project/release-tests-pr/builds/18161#0183d7c9-df5b-4f11-8b32-ba440595d6fe) and in [master](https://buildkite.com/ray-project/release-tests-branch/builds/1126#0183e81b-743d-4902-8fa7-673a0ea975d9), I'm closing this as fixed.

**Closed by clarkzinzow** 2022-10-18 00:41 UTC
Labels: bug, release-blocker, P0, air, r2.1-failure
