### ISSUE TITLE
Build ARM wheels for Ray

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#13780] opened 2021-01-29 02:59 UTC
Due to user demand, we may eventually want to support ARM builds. For now, here are some instructions on how to build ray from source on ARM. This was tested using Ubuntu 20.04 on an AWS Graviton (ARM64) instance.

Building Ray on ARM. 

1. Install the basic Ray dependencies. 

```
sudo apt-get update
sudo apt-get install -y build-essential curl unzip psmisc
sudo apt-get install python3-dev python3-pip python-is-python3

pip install cython==0.29.0 pytest
```

2. Install bazel. Bazel doesn't come with an ARM installer script, so our `ci/travis/install-bazel.sh` doesn't work. 

```
mkdir -p ~/bin
wget https://github.com/bazelbuild/bazel/releases/download/3.7.2/bazel-3.7.2-linux-arm64 -o ~/bin/bazel
chmod u+x ~/bin/bazel
echo "PATH=\$HOME/bin:\$PATH" >> ~/.bashrc
source ~/.bashrc
```

**Comment by javimontero** [comment] 2021-03-10 10:33
Hey @wuisawesome, 

I think that you are outputting the output of wget to ~/bin/bazel instead of the binary itself.

Other than that. Have you managed to install ray on Graviton instances? I have building errors and I have no luck.

Thanks in advance.
Javi

**Comment by wuisawesome** [comment] 2021-03-10 20:56
Yes, I tested this when creating the issue. What issues are you running?

**Comment by nschrader** [comment] 2021-07-19 10:20
Worked perfectly for me, just one correction like the author of the previous comment already found out:

2. Install Bazel:
```bash
mkdir -p ~/bin
wget https://github.com/bazelbuild/bazel/releases/download/3.7.2/bazel-3.7.2-linux-arm64 -O ~/bin/bazel  # captial -O
chmod u+x ~/bin/bazel
echo "PATH=\$HOME/bin:\$PATH" >> ~/.bashrc
source ~/.bashrc
```

3. Compile Ray:
```bash
cd ~/ray
./build.sh
```

4. Build Python wheel (if that's why you are here):
```bash
cd ~/ray/python
python3 setup.py bdist_wheel
```
There it is in `~/ray/python/dist`

**Comment by ddelange** [comment] 2022-03-11 10:20
Duplicate of https://github.com/ray-project/ray/issues/12128 ?

**Comment by mattip** [comment] 2022-10-20 17:16
@richardliaw what action should we take here?

**Comment by dmarkey** [comment] 2022-12-29 22:39
With cheap AWS Graviton instances with loads of memory this would be greatly appreciated.

**Comment by dmarkey** [comment] 2023-01-02 00:49
[ray-2.2.0-cp310-cp310-linux_aarch64.zip](https://github.com/ray-project/ray/files/10329756/ray-2.2.0-cp310-cp310-linux_aarch64.zip)

Here is an arm64 wheel for ubuntu 22.04 if anyone is looking for it (YMMV of course).
You need to download and rename to ray-2.2.0-cp310-cp310-linux_aarch64.whl before installing with pip.

**Closed** 2023-01-09 19:04 UTC
Labels: enhancement, docs, QS

**Comment by krfricke** [comment] 2023-01-09 19:10
We are now building wheels for every commit with #31522. We may pick this onto the latest release (2.2.0), alternatively it will be definitely included in the next release.

**Comment by jppgks** [comment] 2023-01-10 17:13
This is awesome, thanks @krfricke ! Is there any chance of getting a PyPi release for 2.1 as well?

**Comment by krfricke** [comment] 2023-01-10 19:10
I'll look into it - generally it should work as 2.1 also uses the new CI system.

**Comment by pcmoritz** [comment] 2023-01-10 19:47
@jppgks Why can't you upgrade to 2.2? In general we don't backport features to old releases and encourage people to upgrade instead. If there is a blocker to upgrading, we really want to know :)
