### ISSUE TITLE
[Core] Memory leak (?) with no activity 

### ISSUE THREAD

**Issue by rgiacomin** [ray-project/ray#28047] opened 2022-08-22 13:41 UTC
### What happened + What you expected to happen

In my current development environment, I am experiencing an increasing memory usage. Because it is a dev environment, I am always starting and stopping drivers and remote actors... I've seen some issues/bugs related to memory leaks (either because of the dashboard or because remove functions and actors definitions are not gc'ed). To validate if these issues are the ones increasing memory usage, I decide to do a simple test: I provisioned a new Ray cluster (3-nodes, 8Gb RAM, 4 CPUs each), started it without the dashboard, and did not touch it (**I did not run any driver or remote function or actors.**)

As you can see by the chart below, memory consumption is increasing during the last 5 days (since I started the cluster).

![image](https://user-images.githubusercontent.com/57836657/185933893-1d96a103-cb4c-4fb8-9624-07a89208389d.png)

Is this a memory leak? Already identified/fixed?

### Versions / Dependencies

Python: 3.7.7
Ray: 1.13.0 
OS: Ubuntu

Running cluster on k8s.

### Reproduction script

Just provisioned a new cluster and started it. Nothing was deployed.

### Issue Severity

High: It blocks me from completing my task.

**Comment by mihajenko** [comment] 2022-08-22 19:09
@rgiacomin You said you did not start the dashboard. Can you go a bit more into how you did that? AFAIK on ray 1.13.0 you can't really turn off all dashboard processes, unless you kill them. The ray start flag `--include-dashboard=false` only turns off the frontend app.

**Comment by rgiacomin** [comment] 2022-08-22 22:17
I did not know that --include-dashboard=false only disables the front-end. I did not do anything other than setting this flag. 
What are the chances that bug [fix](https://github.com/ray-project/ray/issues/22027) will solve this issue?

**Comment by mihajenko** [comment] 2022-08-23 05:42
@rgiacomin I documented the same issue as you in #26568. Until the fix is verified, we developed a workaround: periodically restart the dashboard process using info from `/proc/$PID/cmdline`. We notice logging is broken, but node resource gauges are OK.

**Comment by rgiacomin** [comment] 2022-08-29 11:02
@mihajenko Please find below the list of processes I have running when I start the cluster with flag --include-dashboard=true and false, respectively.

Set to true:
![with](https://user-images.githubusercontent.com/57836657/187186639-7732df35-b2ad-454c-b837-32c875c41027.png)

Set to false:
![without](https://user-images.githubusercontent.com/57836657/187186720-34234a5e-098f-4763-afbb-e8dc54be3e7d.png)

In either case, if I try to kill any dashboard related process (dashboard.py or agent.py), the entire container crashes and restarts. How exactly you restart the leaky dashboard.py without restarting everything???

**Comment by mihajenko** [comment] 2022-09-01 08:19
> In either case, if I try to kill any dashboard related process (dashboard.py or agent.py), the entire container crashes and restarts. 

That's surprising to hear. That's not our experience.

Yes, we are running it in k8s. I'm posting our workaround script below. How you choose to run it is up to you. We run it as the k8s Pod container command.

```shell
#!/bin/bash

set +e

# parameters
programNameSearchTerm="dashboard.py"
retryInSeconds=${1:-3600}
export RAY_USAGE_STATS_ENABLED=0
export RAY_DISABLE_DASHBOARD_LOG_INFO=1

while true; do
    # find the process command and kill the process
    procPid=$(ps -fA | grep ${programNameSearchTerm} | head -n1 | tr -s " " | cut -d" " -f2)
    procCommand=$(tr '\0' ' ' < /proc/${procPid}/cmdline)
    if [ "$?" != "0" ]; then
        echo "Search for process again in $retryInSeconds s ..."
        sleep ${retryInSeconds}
        continue
    fi
    kill -9 ${procPid}

    # restart the process with the command
    echo "Restarting again in $retryInSeconds s ..."
    eval ${procCommand} &

    # sleep for a bit
    sleep ${retryInSeconds}
done

```

**Comment by rgiacomin** [comment] 2022-09-12 20:20
@mihajenko Sorry for the late response and thank you for sharing your script. We have tried exactly your script with the same (undesirable) effect, iow container crashes when we kill the process. We are now upgrading to Ray 2.0 hoping that the issue is solved in the new version. I will let you know if this is the case...

**Comment by rgiacomin** [comment] 2022-09-14 10:41
Unfortunately, same scenario with Ray 2.0. See pictures below, representing memory usage (last 12 hours) for head and 2 additional nodes. Again, I had no activity in this cluster since deployment (meaning, nothing configured to run on the cluster)...

Any hints? This is a blocker issue for me, because I can't keep restarting the cluster every x days...

![image](https://user-images.githubusercontent.com/57836657/190132597-dd03d864-e625-43e3-9a8a-c8192280c7f9.png)

![image](https://user-images.githubusercontent.com/57836657/190132674-9fb52308-0a13-47ed-ab71-025059a66e61.png)

![image](https://user-images.githubusercontent.com/57836657/190132747-6fbe91dd-b384-480b-828b-58f8daa67471.png)

**Comment by scottsun94** [comment] 2022-10-13 19:52
@rgiacomin Is this still happening? Do you know which processes are taking up more and more memory?
cc: @rkooo567 @ericl @rickyyx @clarng

**Comment by scottsun94** [comment] 2022-10-13 19:56
This might be related to this issue: https://github.com/ray-project/ray/issues/29199
cc: @alanwguo

**Comment by ericl** [comment] 2022-10-13 19:57
It might be related to #29199, which is under investigation. We'd need to confirm the process leaking memory to prioritize (top / htop snapshot).

**Comment by zhe-thoughts** [comment] 2022-12-10 02:17
Tentatively marking this as P1 since #29199 is P1

**Comment by zhe-thoughts** [comment] 2022-12-10 02:18
@raghukiran1224 Thanks for reporting! Could you verify if this is still an issue since #29199 is fixed in 2.1?

I'm also tentatively marking this issue itself P1 until we verify / close

**Comment by will-hang** [comment] 2022-12-13 04:18
We're seeing the same thing!

**Comment by rkooo567** [comment] 2023-07-20 22:59
I will close the issue for now since we believe the root cause has fixed. But please feel free to reopen the issue if you still see the issue from the latest Ray (2.5.1 today).

**Closed by rkooo567** 2023-07-20 22:59 UTC
Labels: bug, core, core-worker, P1.5
