### ISSUE TITLE
ES: RuntimeWarning: invalid value encountered in subtract

### ISSUE THREAD

**Issue by compressed** [ray-project/ray#949] opened 2017-09-08 16:57 UTC
Hi,
I've seen this error message sporadically during training. It results in a `NaN` coming out for the action value during training.

```
/root/ray/python/ray/rllib/es/utils.py:81: RuntimeWarning: invalid value encountered in subtract
  self.sumsq / self.count - np.square(self.mean), 1e-2))
Traceback (most recent call last):
  File "train.py", line 84, in <module>
    result = alg.train()
  File "/root/ray/python/ray/rllib/es/es.py", line 295, in train
    self.policy.set_ob_stat(self.ob_stat.mean, self.ob_stat.std)
```

From some debugging output I was able to gather that both `self.sumsq` and `self.mean` contain `inf` values when the error occurs.

**Comment by robertnishihara** [comment] 2017-09-08 21:24
Interesting. Can you share the command you used to run the script?

Some question:
- What version of TensorFlow are you using?
- Which Python version?
- How long does it typically take to reproduce the problem? How reproducible is it?

**Comment by robertnishihara** [comment] 2017-11-09 07:52
Closing for now since this was a while ago. Please reopen if it's still an issue.

**Closed by robertnishihara** 2017-11-09 07:52 UTC
