### ISSUE TITLE
[Core] Ray hangs when grpcio==1.48.0 is used. 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#27246] opened 2022-07-29 05:39 UTC
### What happened + What you expected to happen

Not entirely sure about the root cause, but when grpcio >= 1.48.0 is used, ray hangs on starting a new process.

We are not entirely sure why this happens now, but we should figure out the root cause.

Action items

1. We should upper bound the gRPC version because they are consistently the root cause of random hanging from core. 
2. We should figure out the root cause of 1.48.0 hanging.
3. We should make sure whenever there's a new gRPC version release, we test accordingly. 

### Versions / Dependencies

Master

### Reproduction script

Use grpcio==1.48.0

**Comment by jjyao** [comment] 2022-08-08 17:50
Duplicate of #27299

**Closed by jjyao** 2022-08-08 17:50 UTC
Labels: bug, P1, Ray 2.1
