### ISSUE TITLE
[dashboard] FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2022-07-06_16-46-30_058837_12938/logs/dashboard.log'

### ISSUE THREAD

**Issue by jinfagang** [ray-project/ray#26320] opened 2022-07-06 09:01 UTC
### What happened + What you expected to happen

```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2022-07-06_16-46-30_058837_12938/logs/dashboard.log'

2022-07-06 16:46:31,076	DEBUG gcs_utils.py:224 -- internal_kv_put b'CLUSTER_METADATA' b'{"ray_version": "1.13.0", "python_version": "3.9.13"}' True b'cluster'
2022-07-06 16:46:31,096	DEBUG gcs_utils.py:207 -- internal_kv_get b'dashboard' b'dashboard'
2022-07-06 16:46:31,202	DEBUG gcs_utils.py:207 -- internal_kv_get b'dashboard' b'dashboard'
2022-07-06 16:46:31,307	DEBUG gcs_utils.py:207 -- internal_kv_get b'dashboard' b'dashboard'
2022-07-06 16:46:31,413	DEBUG gcs_utils.py:207 -- internal_kv_get b'dashboard' b'dashboard'
2022-07-06 16:46:31,519	DEBUG gcs_utils.py:207 -- internal_kv_get b'dashboard' b'dashboard'
2022-07-06 16:46:31,520	ERROR services.py:1488 -- Failed to start the dashboard: Failed to start the dashboard, return code 1
Failed to read dashboard log: [Errno 2] No such file or directory: '/tmp/ray/session_2022-07-06_16-46-30_058837_12938/logs/dashboard.log'
2022-07-06 16:46:31,520	ERROR services.py:1489 -- Failed to start the dashboard, return code 1
Failed to read dashboard log: [Errno 2] No such file or directory: '/tmp/ray/session_2022-07-06_16-46-30_058837_12938/logs/dashboard.log'
```

### Versions / Dependencies

1.13

### Reproduction script

```

import ray
ray.init()

@ray.remote
def f(x):
	return x * x

futures = [f.remote(i) for i in range(4)]
print(ray.get(futers))  # [0, 1, 4, 9]
```

macOS, full trace back:

```
2022-07-06 17:00:23,648	ERROR services.py:1488 -- Failed to start the dashboard: Failed to start the dashboard, return code 1
Failed to read dashboard log: [Errno 2] No such file or directory: '/tmp/ray/session_2022-07-06_17-00-22_187900_14307/logs/dashboard.log'
2022-07-06 17:00:23,648	ERROR services.py:1489 -- Failed to start the dashboard, return code 1
Failed to read dashboard log: [Errno 2] No such file or directory: '/tmp/ray/session_2022-07-06_17-00-22_187900_14307/logs/dashboard.log'
Traceback (most recent call last):
    with open(dashboard_log, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2022-07-06_17-00-22_187900_14307/logs/dashboard.log'
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by rkooo567** [comment] 2022-07-06 22:43
Are you using M1 macbook?

**Comment by jinfagang** [comment] 2022-07-07 02:30
this error got because of dashboard lack of package, please don't mute the import error.... otherwise users didn't know what's going on and how to fix it....

**Comment by hetankevin** [comment] 2022-07-10 22:16
Am experiencing this same issue. What do you mean by "dashboard lack of package"? `from ray.dashboard import *` works fine for me, but upon executing `ray.init()` or even `ray.init(include_dashboard=False)` my kernel dies.

**Comment by hetankevin** [comment] 2022-07-10 22:34
Ah, got it. `pip uninstall grpcio` and then `conda install grpcio` worked for me.

**Comment by ericosmic** [comment] 2022-11-07 09:01
Also happen same problem, is this due to m1 mac?

**Comment by rkooo567** [comment] 2022-11-07 15:20
@ericosmic what's your output of dashboard.log file? https://docs.ray.io/en/master/ray-observability/ray-logging.html

**Comment by ericosmic** [comment] 2022-11-08 14:06
> @ericosmic what's your output of dashboard.log file? https://docs.ray.io/en/master/ray-observability/ray-logging.html
This is my error message:
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/35327931/200585719-48238ee7-19f7-49d3-8379-318223a5f789.png">

**Comment by dyllanwli** [comment] 2022-11-17 02:34
Got the same exactly same error. Any updates?

**Comment by rkelly712** [comment] 2022-12-02 22:21
I've the same issue.

**Comment by deepwonwoo** [comment] 2022-12-08 01:09
I have same issue,
I build ray cluster with 12 nodes(using 100 cpus)  and works fine  when I run small job(done in one day).
But when I scale up the job(just do more iterations in job, so runs more than one day), ray gives error like below

Can anyone help?
```
2022-12-08 00:00:06,225	WARNING worker.py:1839 -- The log monitor on node s2lice0184 failed with the following error:
Traceback (most recent call last):
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 520, in <module>
    log_monitor.run()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 436, in run
    anything_published = self.check_log_files_and_publish_updates()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 339, in check_log_files_and_publish_updates
    file_info.reopen_if_necessary()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 79, in reopen_if_necessary
    new_inode = os.stat(self.filename).st_ino
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2022-12-07_11-33-37_324202_3811/logs/raylet.err'

2022-12-08 00:00:06,226	WARNING worker.py:1839 -- The log monitor on node s2lice0163 failed with the following error:
Traceback (most recent call last):
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 520, in <module>
    log_monitor.run()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 436, in run
    anything_published = self.check_log_files_and_publish_updates()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 339, in check_log_files_and_publish_updates
    file_info.reopen_if_necessary()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 79, in reopen_if_necessary
    new_inode = os.stat(self.filename).st_ino
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2022-12-07_11-33-37_324202_3811/logs/raylet.err'

2022-12-08 00:00:06,227	WARNING worker.py:1839 -- The log monitor on node s2lice0173 failed with the following error:
Traceback (most recent call last):
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 520, in <module>
    log_monitor.run()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 436, in run
    anything_published = self.check_log_files_and_publish_updates()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 339, in check_log_files_and_publish_updates
    file_info.reopen_if_necessary()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 79, in reopen_if_necessary
    new_inode = os.stat(self.filename).st_ino
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2022-12-07_11-33-37_324202_3811/logs/raylet.err'

2022-12-08 00:00:06,227	WARNING worker.py:1839 -- The log monitor on node slice1434 failed with the following error:
Traceback (most recent call last):
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 520, in <module>
    log_monitor.run()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 436, in run
    anything_published = self.check_log_files_and_publish_updates()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 339, in check_log_files_and_publish_updates
    file_info.reopen_if_necessary()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 79, in reopen_if_necessary
    new_inode = os.stat(self.filename).st_ino
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2022-12-07_11-33-37_324202_3811/logs/raylet.err'

2022-12-08 00:00:06,227	WARNING worker.py:1839 -- The log monitor on node dsky2151 failed with the following error:
Traceback (most recent call last):
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 520, in <module>
    log_monitor.run()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 436, in run
    anything_published = self.check_log_files_and_publish_updates()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 339, in check_log_files_and_publish_updates
    file_info.reopen_if_necessary()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 79, in reopen_if_necessary
    new_inode = os.stat(self.filename).st_ino
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2022-12-07_11-33-37_324202_3811/logs/raylet.err'

2022-12-08 00:00:06,227	WARNING worker.py:1839 -- The log monitor on node s2lice0174 failed with the following error:
Traceback (most recent call last):
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 520, in <module>
    log_monitor.run()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 436, in run
    anything_published = self.check_log_files_and_publish_updates()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 339, in check_log_files_and_publish_updates
    file_info.reopen_if_necessary()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 79, in reopen_if_necessary
    new_inode = os.stat(self.filename).st_ino
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2022-12-07_11-33-37_324202_3811/logs/raylet.err'

2022-12-08 00:00:06,227	WARNING worker.py:1839 -- The log monitor on node slice1273 failed with the following error:
Traceback (most recent call last):
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 520, in <module>
    log_monitor.run()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 436, in run
    anything_published = self.check_log_files_and_publish_updates()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 339, in check_log_files_and_publish_updates
    file_info.reopen_if_necessary()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 79, in reopen_if_necessary
    new_inode = os.stat(self.filename).st_ino
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2022-12-07_11-33-37_324202_3811/logs/raylet.err'

2022-12-08 00:00:06,227	WARNING worker.py:1839 -- The log monitor on node s2lice0182 failed with the following error:
Traceback (most recent call last):
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 520, in <module>
    log_monitor.run()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 436, in run
    anything_published = self.check_log_files_and_publish_updates()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 339, in check_log_files_and_publish_updates
    file_info.reopen_if_necessary()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 79, in reopen_if_necessary
    new_inode = os.stat(self.filename).st_ino
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2022-12-07_11-33-37_324202_3811/logs/raylet.err'

2022-12-08 00:00:06,227	WARNING worker.py:1839 -- The log monitor on node slice1451 failed with the following error:
Traceback (most recent call last):
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 520, in <module>
    log_monitor.run()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 436, in run
    anything_published = self.check_log_files_and_publish_updates()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 339, in check_log_files_and_publish_updates
    file_info.reopen_if_necessary()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 79, in reopen_if_necessary
    new_inode = os.stat(self.filename).st_ino
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2022-12-07_11-33-37_324202_3811/logs/raylet.err'

2022-12-08 00:00:06,227	WARNING worker.py:1839 -- The log monitor on node s2lice0170 failed with the following error:
Traceback (most recent call last):
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 520, in <module>
    log_monitor.run()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 436, in run
    anything_published = self.check_log_files_and_publish_updates()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 339, in check_log_files_and_publish_updates
    file_info.reopen_if_necessary()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 79, in reopen_if_necessary
    new_inode = os.stat(self.filename).st_ino
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2022-12-07_11-33-37_324202_3811/logs/raylet.err'

2022-12-08 00:00:06,227	WARNING worker.py:1839 -- The log monitor on node s2lice0201 failed with the following error:
Traceback (most recent call last):
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 520, in <module>
    log_monitor.run()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 436, in run
    anything_published = self.check_log_files_and_publish_updates()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 339, in check_log_files_and_publish_updates
    file_info.reopen_if_necessary()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 79, in reopen_if_necessary
    new_inode = os.stat(self.filename).st_ino
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2022-12-07_11-33-37_324202_3811/logs/raylet.err'

2022-12-08 00:00:06,227	WARNING worker.py:1839 -- The log monitor on node slice1427 failed with the following error:
Traceback (most recent call last):
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 520, in <module>
    log_monitor.run()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 436, in run
    anything_published = self.check_log_files_and_publish_updates()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 339, in check_log_files_and_publish_updates
    file_info.reopen_if_necessary()
  File "/user/space.dev/deepwonwoo/ds_anaconda/envs/ray/lib/python3.10/site-packages/ray/_private/log_monitor.py", line 79, in reopen_if_necessary
    new_inode = os.stat(self.filename).st_ino
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2022-12-07_11-33-37_324202_3811/logs/raylet.err'

```

**Comment by YanivO1123** [comment] 2022-12-13 11:11
I have the same issue. 
In my case, I'm deploying ray jobs through slurm, and it works on and off. As in, some sbatch calls work fine, others crash with the following error:
![image](https://user-images.githubusercontent.com/33690998/207302418-11aabe61-dea2-4d91-b604-57ba97958a94.png)

**Comment by rkooo567** [comment] 2022-12-14 11:58
@YanivO1123 @rkelly712 @dyllanwli @ericosmic 

Is it possible for you guys to try this in the latest master? Also try https://github.com/ray-project/ray/issues/26320#issuecomment-1179813008

I also found out the error message is swallowed when the dashboard fails to start. I made a PR to fix this issue. https://github.com/ray-project/ray/pull/31097. I will merge it soon, and it'd be great if you guys try out in the master wheel to see the error message. I will lyk when this is merged

**Comment by YanivO1123** [comment] 2022-12-15 09:18
> grpcio

Trying pip uninstall grpcio and then conda install grpcio crashed my ray which was previosly working on and off, entirely. 
All of my jobs now crash with one of two different ray errors:
![image](https://user-images.githubusercontent.com/33690998/207820579-368901ef-62b2-4417-ba59-16da5c5fb006.png)

![image](https://user-images.githubusercontent.com/33690998/207819144-d4517bf6-045e-4466-a585-419665ac52fb.png)

The first error happens after ray.init has been called succesfully (I have a print after ray.init() that prints just before the error message, as can be seen in the screenshot).
The second error happens during ray.init

I'll try to update ray later today and see if the error reproduces.

**Comment by rkooo567** [comment] 2022-12-15 10:44
Can you make sure to download grpcio <= 1.49.1?

**Comment by rkooo567** [comment] 2022-12-15 10:45
this seems to be the restriction in the master...

**Comment by YanivO1123** [comment] 2022-12-19 08:50
> Can you make sure to download grpcio <= 1.49.1?

pip install grpcio == 1.49.1
pip uninstall -y ray
pip install -U "ray[default]"

Appears so far to have solved all of the problems I was observing.
However, the errors have a very flaky nature. I'll reply to this thread if I'll observe the same problems with additional use.
Thanks for the help!

**Comment by YanivO1123** [comment] 2022-12-19 09:38
> > Can you make sure to download grpcio <= 1.49.1?
> 
> pip install grpcio == 1.49.1 pip uninstall -y ray pip install -U "ray[default]"
> 
> Appears so far to have solved all of the problems I was observing. However, the errors have a very flaky nature. I'll reply to this thread if I'll observe the same problems with additional use. Thanks for the help!

Running additional jobs, the error is still there.
In 20 slurm jobs, I've observed the following error once:
![image](https://user-images.githubusercontent.com/33690998/208394804-e441ddc0-9a51-46fa-80f3-b0ecb4a41082.png)

**Comment by rkooo567** [comment] 2022-12-19 14:24
@YanivO1123 is it possible to share the whole session_latest/logs directory when this error occurs? Also this PR will expose more information regarding the dashboard failure https://github.com/ray-project/ray/pull/31097, but your issue doesn't seem to be only about the dashboard. The error "unable to register worker with raylet: no such file or directory" indicates something is completely broken.

**Comment by rkooo567** [comment] 2022-12-21 02:24
Hi guys. I merged the PR to print the correct error message to the output. You can access them using the nightly wheel. (the feature will be added to ray 2.3). https://docs.ray.io/en/master/ray-overview/installation.html#daily-releases-nightlies

Please try the latest wheel and report the error message to me. Thank you!

**Comment by rkooo567** [comment] 2023-01-16 04:49
Closing the issue. I believe the PR I merged will help everyone to figure out the root cause. If not, please lmk the new error message!

**Closed by rkooo567** 2023-01-16 04:49 UTC
Labels: bug, P1, dashboard

**Comment by tvrbanec** [comment] 2023-02-06 14:04
Hi.
I tried to start ray cluster, and initialisation is complaining about folder that does not exists (any more). I have no idea how to fix it. I tried ray 3.0.0 but it is the same as 2.2 (default).

File "/usr/local/lib/python3.9/dist-packages/ray/autoscaler/_private/util.py", line 434, in add_hash_of_file
    with open(fpath, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'some_path_to_the_folder'

**Comment by rkooo567** [comment] 2023-02-06 19:45
https://github.com/ray-project/ray/blob/2314775e4cf1dd3bd3dab3e8a6744c3f8213933b/python/ray/autoscaler/_private/util.py#L433

Hmm I could find the relevant code from the master. How did you build ray? Did you download from pypi?

**Comment by tvrbanec** [comment] 2023-02-11 21:45
Yes, I installed it with the pip3 install ray[default]. But never mind, I do not need those folders. It just works. :)
