### ISSUE TITLE
[core][regression] microbenchmark regression on 1_n actor calls (1_n_actor_calls_async and 1_n_async_actor_calls_async)

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#41423] opened 2023-11-28 00:50 UTC
### What happened + What you expected to happen

<img width="457" alt="image" src="https://github.com/ray-project/ray/assets/11676094/f1284578-1cef-4015-b5d8-952e0a8db005">

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

None

**Comment by jjyao** [comment] 2023-11-29 23:19
Duplicate of #41109

**Closed by jjyao** 2023-11-29 23:19 UTC
Labels: bug, release-blocker, P0, core
