### ISSUE TITLE
`[1.11 Release]` `network_overhead` unable to pass after retries

### ISSUE THREAD

**Issue by mwtian** [ray-project/ray#21865] opened 2022-01-25 21:09 UTC
`network_overhead` has failed consecutively after a few retries. The test looks like it passed in one attempt, although Buildkite still indicates a failure:
https://buildkite.com/ray-project/periodic-ci/builds/2503#6bd29292-d403-4c52-a9f8-2cd381ea3dbd/392

And there are failures with no apparent reason. There are error logs like `Ran into error when copying results dir to persistent location: [Errno 17] File exists: '/tmp/ray_release_test_artifacts'`, which appear in other failed tests as well:
https://buildkite.com/ray-project/periodic-ci/builds/2503#804b329d-8e17-4c5d-a960-7a27c2d11b5f/139-436

@xwjiang2010 since you are ML oncall, can you take a look to see if this is a real issue?

**Comment by xwjiang2010** [comment] 2022-01-25 22:38
Thanks @mwtian for reporting it. The test started failing consistently since 1/24 (Monday). Last successful run is on Sunday.
Main reason of failing is timeout. Threshold is 400s for smoke test. Before the test was consistently around 360 - 370 and now it's 410s.

The delta is not huge but can be reproduced consistently. I think we should try to understand it before increasing the timeout.
@krfricke Do you happen to recall anything landed between Sunday's nightly run and Monday's that could have caused it?

We could also check other Tune scalability tests to see if the increase also manifests itself in other tests (though not crossing threshold to trigger failure).

**Comment by mwtian** [comment] 2022-01-26 23:04
Adding @richardliaw as current ML oncall.

**Comment by mwtian** [comment] 2022-01-27 16:00
This test eventually passed on retries. Lowering to P1. Feel free to upgrade if you think this warrants P0.

**Comment by xwjiang2010** [comment] 2022-01-28 16:42
Could be product glitch. It's now returning to normal time: https://buildkite.com/ray-project/periodic-ci/builds/2565#512564b8-cc3f-4722-8754-706ce2f8b7a3

Closing it out.

**Closed by xwjiang2010** 2022-01-28 16:42 UTC
Labels: P1
