### ISSUE TITLE
[tune] Removing unnecessary checkpoints / freeing up disk space

### ISSUE THREAD

**Issue by dulex123** [ray-project/ray#4381] opened 2019-03-15 14:07 UTC
### Describe the problem

Currently there is no way to specify the removal of stale checkpoints. It fills up disk space based on checkpoint-freq.

One idea is to specify number of last checkpoints to keep `--keep-checkpoints-num`. This is fine, but it may not save the best performing (highest reward) model.

So another parameter that could help with this is: `--keep-best-checkpoints-num` which will specify how many of last highest-reward checkpoints to keep.

related: https://github.com/ray-project/ray/pull/4380

**Comment by richardliaw** [comment] 2019-03-21 02:46
This is a duplicate of #4287, let's consolidate discussion there

**Closed by richardliaw** 2019-03-21 02:46 UTC
