### ISSUE TITLE
[Data] Datasource.supports_distributed_reads is incorrectly set to True for `local://` schema paths

### ISSUE THREAD

**Issue by sodabeta7** [ray-project/ray#42261] opened 2024-01-09 08:35 UTC
### What happened + What you expected to happen

When using the `local:// schema` in the `ray.data.read_*` API, there is an issue with the parsing of the schema paths. The paths are not correctly parsed as `local`, which leads to the `datasource.supports_distributed_reads` being incorrectly marked as `True`, when it should be `False`.

The problem arises because the `path` is parsed and resolved in [this line of the code](https://github.com/ray-project/ray/blob/0f2a32778307ee02a193357a94c24933e5e191d4/python/ray/data/datasource/file_based_datasource.py#L165C39-L165C39), where the `local://` prefix is already removed. As a result, when the `path` is checked in [this subsequent line](https://github.com/ray-project/ray/blob/0f2a32778307ee02a193357a94c24933e5e191d4/python/ray/data/_internal/util.py#L328), the parsed schema is an empty string `''` rather than the expected `'local'`.

### Versions / Dependencies

2.9.0

### Reproduction script

```python
ds = ray.data.datasource.ImageDatasource(
    ["local:///root/img001.png", "local:///root/img002.png"],        
)
assert ds.supports_distributed_reads == False, "Expected to be False, but got True"
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by bveeramani** [comment] 2024-01-10 21:58
> Actually even if I override self._supports_distributed_reads to False, the reading task will still be scheduled to a different node, seems like scheduling strategy option to force local read is ignored somewhere?

That's weird. Here's the code for scheduling tasks on the driver's node:

https://github.com/ray-project/ray/blob/cd8fef3331b30c044b7d49f2e3561c81f8dbee37/python/ray/data/read_api.py#L307-L311

I tried reproducing this with 10,000 files on a 32 node cluster and it seems to work fine? If I don't override `_supports_distributed_reads`, I get `FileNotFound` errors, but if I override there aren't any errors.

```python
import ray

datasource = ray.data.datasource.BinaryDatasource(
    [f"local:///tmp/{i}.dat" for i in range(10_000)],
)
# If you uncomment this, the program won't error.
# datasource._supports_distributed_reads = False
ray.data.read_datasource(datasource).materialize()
```

**Comment by bveeramani** [comment] 2024-01-11 22:55
Thanks for isolating the issue! Looks like we override the scheduling strategy if you set `locality_with_output` (even if you've specified a local path):

https://github.com/ray-project/ray/blob/3f7f1b52c840d6780fd89ef9bc125ff96eb68e52/python/ray/data/_internal/execution/operators/map_operator.py#L189-L206

This isn't expected behavior, so we'll need to write a fix

**Comment by bveeramani** [comment] 2024-01-30 22:25
Closing because the originally issue has been fixed. Will create a new Issue for `locality_with_output` thing

**Closed by bveeramani** 2024-01-30 22:25 UTC
Labels: bug, P1, data

**Comment by bveeramani** [comment] 2024-01-30 22:33
Here's the issue for the follow up https://github.com/ray-project/ray/issues/42352
