### ISSUE TITLE
[Streaming shuffle] Workers are started unlimitedly if each ray object is 100KB. 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#16025] opened 2021-05-24 18:05 UTC
### What is the problem?

It seems like in the reduce phase, workers are started unlimitedly, if each of ray object is 100KB.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
python -m ray.experimental.shuffle --ray-address="localhost:6379" --num-partitions=1000 --partition-size=100e6
```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment] 2021-05-25 05:58
Btw, this worked normally when each object was 1MB not 100KB.

**Comment by rkooo567** [comment] 2021-05-25 05:59
So it should only happen when the object size is smaller than the certain threshold.

**Comment by ericl** [comment] 2021-06-02 04:11
This turns out to be a race condition in the initial implementation of avoiding releasing resources on ray.get(). The problem is that when an ObjectRef is deserialized, we are asynchronously resolving its status. This takes an RPC round trip to the owner (0-1ms). If we try to ray.get() an object during this period, then it can release resources even if the object is already created.

The real fix for this is somewhat complicated (we can asynchronously ping the owners in such a scenario), and may add some overheads. As a short term fix, we can wait for a short grace period before releasing resources. Since releasing resources is only really for the slow case (deadlock), and most well formed Ray programs don't need this, I think this bit of overhead is fine for now to simplify the design.

**Closed** 2021-06-04 01:35 UTC
Labels: P1, bug
