### ISSUE TITLE
Received message larger than max (218771147 vs. 104857600)

### ISSUE THREAD

**Issue by cgy-dayup** [ray-project/ray#21440] opened 2022-01-07 03:46 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

i want to use ray-tune for lightgbm on my own datasat.but i come across the problem:
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.RESOURCE_EXHAUSTED
        details = "Received message larger than max (218771147 vs. 104857600)"
        debug_error_string = "{"created":"@1641524270.413581456","description":"Error received from peer ipv4:10.207.179.214:36521","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Received message larger than max (218771147 vs. 104857600)","grpc_status":8}"

### Versions / Dependencies

ray 1.9.1

### Reproduction script

Received message larger than max (218771147 vs. 104857600)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment] 2022-01-07 03:55
Is this happening with ray client?

**Comment by richardliaw** [comment] 2022-01-07 04:14
Hey @AmeerHajAli, I think this is another Ray client issue, can we prioritize improving the error message here?

Also cc @istoica , @pcmoritz @edoakes for visibility.

**Comment by cgy-dayup** [comment] 2022-01-07 07:40
> Is this happening with ray client?

- i think there are some problems with message size limit?how can I slove it?

**Comment by AmeerHajAli** [comment] 2022-01-07 07:41
@ckw017 / @wuisawesome , is this a duplicate of https://github.com/ray-project/ray/issues/18378 ?

If so can we prioritize fixing this error message?

**Comment by cgy-dayup** [comment] 2022-01-07 07:52
> 
Are there any solution？

**Comment by ICESDHR** [comment] 2022-01-07 09:57
i have the same problem.
i use TuneSearchCV function to train model use 4GB dataset, my code is 
```
tune_search = TuneSearchCV(
        clf,
        parameter_grid,
        search_optimization="bayesian",
        n_trials=30,
        early_stopping=True,
        max_iters=3,
        verbose=2,
        time_budget_s=10,
    )
    tune_search.fit(x_train, y_train)
```
In the implementation of method TuneSearchCV.fit(), i found data transfer is forced, and data size > 2GB, and Throw an error like **ValueError: Message ray.rpc.DataRequest exceeds maximum protobuf size of 2GB: 5979803541**

```
# tune_sklearn/tune_basesearch.py
def _fit(self, X, y=None, groups=None, tune_params=None, **fit_params):
    ...
    X_id = ray.put(X)
    y_id = ray.put(y)
    ....
```

**so i think this is a bug. if only fix error message, function TuneSearchCV() can't train dataset which large than 2GB!**

**Comment by wuisawesome** [comment] 2022-01-11 17:55
@cgy-dayup I think the best mitigation is to chunk the object yourself for now (presumably it's a large array of some sort?)

@AmeerHajAli I believe @ckw017 is prioritizing fixing the actual underlying issue here already since we have multiple users running into this problem. 

Btw I'm going to close this as a duplicate of #18378 so that we can centralize tracking the issue there.

**Closed by wuisawesome** 2022-01-11 17:55 UTC
Labels: bug, P1, triage
