### ISSUE TITLE
[Ray Job][Ray Core][GCS FT] List job takes very long time to complete after head node restart 

### ISSUE THREAD

**Issue by llidev** [ray-project/ray#38786] opened 2023-08-23 18:01 UTC
### What happened + What you expected to happen

With a single node cluster, after my head node restart from failure in FT mode, `ray job list` takes very long time to complete, even though there is only one job is running (the job was submitted before head node restart).
```
>> time ray job list
Job submission server address: http://127.0.0.1:31977/
[JobDetails(type=<JobType.SUBMISSION: 'SUBMISSION'>, job_id=None, submission_id='main', driver_info=None, status=<JobStatus.RUNNING: 'RUNNING'>, entrypoint='sleep 10000', message='Job is currently running.', error_type=None, start_time=1692808075818, end_time=None, metadata={}, runtime_env={}, driver_agent_http_address='http://17.14.103.91:52365/', driver_node_id='ab42b4f2cbd7d973bf1988dc8d274b8b8bfeac1c3076828b077e7d67')]

real	2m1.708s
user	0m0.652s
```

In addition,  `gcs_server.out` log shows the below error:
```
[2023-08-23 17:11:59,159 I 664 664] (gcs_server) gcs_job_manager.cc:149: Getting all job info.
[2023-08-23 17:11:59,159 W 664 664] (gcs_server) gcs_job_manager.cc:227: Failed to get is_running_tasks from core worker: GrpcUnavailable: RPC Error message: failed to connect to all addresses; RPC Error details: 
[2023-08-23 17:11:59,159 W 664 664] (gcs_server) gcs_job_manager.cc:227: Failed to get is_running_tasks from core worker: GrpcUnavailable: RPC Error message: failed to connect to all addresses; RPC Error details: 
[2023-08-23 17:11:59,160 I 664 664] (gcs_server) gcs_job_manager.cc:185: Finished getting all job info.
```
So I guess GCS job manager is still trying to get job task info from the dead node?

### Versions / Dependencies

2.6.3

### Reproduction script

1. create a single node ray cluster with external redis for gcs FT
2. submit a single ray job with long running command such as `sleep 10000`
3. restart the head the node (in a new machine)
4. run `ray job list` multiple times

### Issue Severity

High: It blocks me from completing my task.

**Comment by sfrolich** [comment] 2023-10-24 16:40
I am seeing the same issue with Ray 2.7.1 on multiple node cluster. What's worse is that during this time when I submit jobs (not using the --no-wait flag) the job also hangs for minutes. This is pretty easy to reproduce and is highly visible.

**Comment by jjyao** [comment] 2023-10-25 05:33
Duplicate of #39947

**Closed by jjyao** 2023-10-25 05:33 UTC
Labels: bug, triage, core, job
