### ISSUE TITLE
ray.data map_batches leak dead ray::IDLE

### ISSUE THREAD

**Issue by happyxhw** [ray-project/ray#44448] opened 2024-04-03 09:28 UTC
### What happened + What you expected to happen

when fn in ray.data.map_batches return a big object, a dead ray::IDLE worker will leak, and consume much memory

![image](https://github.com/ray-project/ray/assets/44490504/af2bc5c6-1818-40e2-883b-3b90e15d8777)

if return a small object, will not

log:
[idle.log](https://github.com/ray-project/ray/files/14849990/idle.log)
[idle.out.txt](https://github.com/ray-project/ray/files/14849998/idle.out.txt)
[idle.err.txt](https://github.com/ray-project/ray/files/14849999/idle.err.txt)

### Versions / Dependencies

ray version 2.9.0

### Reproduction script

```python
import numpy as np
import ray


class Embedding(object):
    """
    embedding
    """

    def __call__(self, item):
        """
        ray call
        """
        results = []
        for i in range(0, 100):
            # big size object
            results.append({'vector': np.random.uniform(low=0.5, high=13.3, size=(38000,)).tolist()})

        return {'embedding': results}


@ray.remote(num_cpus=0)
def debug():
    ds = ray.data.from_items(list(range(0, 200)))
    ds = ds.map_batches(
        Embedding,
        batch_size=10,
        concurrency=(1, 4),
        num_cpus=0,
    )
    for item in ds.iter_batches():
        pass


if __name__ == '__main__':
    future = debug.remote()
    ray.get(future)
    ray.shutdown()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by happyxhw** [comment] 2024-04-03 09:55
using `yield`, not reture

https://docs.ray.io/en/latest/data/api/doc/ray.data.Dataset.map_batches.html

```python
from typing import Dict
import ray
import numpy as np

def map_fn_with_large_output(batch: Dict[str, np.ndarray]) -> Dict[str, np.ndarray]:
    for i in range(3):
        yield {"large_output": np.ones((100, 1000))}

ds = (
    ray.data.from_items([1])
    .map_batches(map_fn_with_large_output)
)
```

**Comment by happyxhw** [comment] 2024-04-08 09:38
try to kill by pid can release the memory
```python
import numpy as np
import ray
import ray.runtime_context


class Embedding(object):
    """
    embedding
    """

    def __call__(self, item):
        """
        ray call
        """
        for i in range(0, 100):
            yield {'vector': np.random.uniform(low=0.5, high=13.3, size=(380,)).tolist()}


@ray.remote(num_cpus=0)
def debug():
    ds = ray.data.from_items(list(range(0, 200)))
    ds = ds.map_batches(
        Embedding,
        batch_size=10,
        concurrency=(1, 4),
        num_cpus=0,
    )
    for item in ds.iter_batches():
        pass
    return ray.runtime_context.get_runtime_context().get_worker_id()


if __name__ == '__main__':
    future = debug.remote()
    worker_id = ray.get(future)

    import os
    import signal
    import time

    from ray.experimental.state.api import get_worker

    worker = get_worker(worker_id)
    pid = worker.pid
    ray.shutdown()

    time.sleep(10)
    os.kill(pid, signal.SIGKILL)

```

**Comment by bveeramani** [comment] 2024-04-18 20:19
Hey @happyxhw, looks like this is expected behavior: https://discuss.ray.io/t/why-is-there-a-lot-of-ray-idle-in-my-ray-process/10395

**Comment by happyxhw** [comment] 2024-04-22 02:52
> Hey @happyxhw, looks like this is expected behavior: https://discuss.ray.io/t/why-is-there-a-lot-of-ray-idle-in-my-ray-process/10395

I have read this discussion. I know "ray::IDLE" is something similar to a progress in a pool. But in this issue the "ray::IDLE" is dead without a  "ID". It never goes away while consuming too much memory, and can not be reused forever.

![image](https://github.com/ray-project/ray/assets/44490504/7903aa65-2ddc-4370-bd2a-c0aeaa1d946e)

**Comment by bveeramani** [comment] 2024-04-22 06:02
I ran the reproduction script with Ray 2.9.2, but I wasn't able to reproduce the issue. All of the IDLE processes have a PID.

@rynewang do you have a hunch about what might be going on here?

**Comment by rynewang** [comment] 2024-04-26 11:16
@happyxhw can you click "Log" or the "Stack Trace" to see what they are doing? They may be the dashboard process or other auxiliary servers.

**Comment by jjyao** [comment] 2024-05-13 21:33
Hi @happyxhw are you able to reproduce with latest Ray? We cannot reproduce it on our side. Closing now, feel free to reopen it if you can reproduce it.

**Closed by jjyao** 2024-05-13 21:33 UTC
Labels: bug, @external-author-action-required, core
