### ISSUE TITLE
[Core/Test] test_runtime_environment_working_dir_2 flaky 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#27629] opened 2022-08-08 06:08 UTC
### What happened + What you expected to happen

<img width="1599" alt="Screen Shot 2022-08-07 at 11 08 14 PM" src="https://user-images.githubusercontent.com/18510752/183350541-18d8bc1c-1e1c-4eff-9139-7c206d19e4c9.png">

Please fix asap! 

### Versions / Dependencies

.

### Reproduction script

n/a

**Comment by architkulkarni** [comment] 2022-08-08 15:50
Duplicate of https://github.com/ray-project/ray/issues/27562

**Closed by architkulkarni** 2022-08-08 15:50 UTC
Labels: bug, P0
