### ISSUE TITLE
[jobs] Ray Job Submission only running tasks on the head node

### ISSUE THREAD

**Issue by engrmg** [ray-project/ray#23010] opened 2022-03-10 17:15 UTC
Hi, 

We have a cluster of 1 head node and 3 workers in AWS. We deployed this using the AWS config. Our config is set to deploy 5 max workers.

We are following this tutorial https://docs.ray.io/en/latest/cluster/job-submission.html. We expanded the ray docker image and added our script with the following code.
```python

import ray
import requests

ray.init()

@ray.remote
class Counter:
    def __init__(self):
        self.counter = 0

    def inc(self):
        self.counter += 1

    def get_counter(self):
        return self.counter

counter = Counter.remote()

for _ in range(5):
    ray.get(counter.inc.remote())
    print(ray.get(counter.get_counter.remote()))

print(requests.__version__)
```

Our issue is that the head node is running all the work load. It never delegates to the worker nodes. The head node just keeps running 17 jobs at a time but never delegates. 

Is there any configuration parameter that we were supposed to set or is this a bug?

**Comment by edoakes** [comment] 2022-03-10 17:37
@engrmg I think the issue here is that you need to set `ray.init(address="auto")` to connect to the ray cluster, else it's just starting ray locally. We should make this work automatically and will do so before the next Ray release, we have a bug tracking it:
https://github.com/ray-project/ray/issues/22884

Let me know if that doesn't solve the issue.

**Comment by engrmg** [comment] 2022-03-14 17:08
Hi @edoakes 

Thank you for the quick response. We tried your suggestion and deployed our cluster to make sure everything was updated with the new script that contains `ray.init(address="auto")`. Unfortunately, the head seems to be behaving the same way and does not delegate jobs to the worker nodes. It does delegate 1 or two jobs randomly but 90% of the jobs submitted are completed by the head node. We tried submitting 200+ jobs and as you can imagine, the head node took a long time to finish. This also blocks the auto scaling mechanism. We would like to try out the autoscaler with AWS. 

Are we missing any configuration parameters for the cluster?

**Comment by edoakes** [comment] 2022-03-14 18:53
@engrmg what are the resource requirements of the tasks/actors in the jobs? It could be that they require `num_cpus=0` so they're all getting placed on the same node.

**Comment by engrmg** [comment] 2022-03-15 20:01
@edoakes 

We tried your suggestion and unfortunately does not help with delegation and autoscaling. We noticed that the jobs completed faster but the head can not handle more than 8 jobs at a time which results in a bottle neck on the head node. It does not use the full capacity of the cluster. This blocks the auto scaling mechanism.

We noticed this from looking at Actors in the Dashboard. There's a JobSupervisor actor per job that the head node is running. Seems like the head node can only run about 8 actors at a time.

**Comment by edoakes** [comment] 2022-03-18 21:15
@engrmg I will add this to our backlog to make it so the job submission drivers can be load-balanced across the cluster.

For now, my best recommendation is to try to make the driver script as lightweight as possible and do the heavy-lifting in the tasks/actors of the application. That way, you can pack more drivers without the head node being the bottleneck.

**Comment by SongGuyang** [comment] 2022-03-22 08:54
We set a little resource for the supervisor actor which launches the real driver. https://github.com/ray-project/ray/blob/master/dashboard/modules/job/job_manager.py#L453

Is it the root cause? Maybe we schedule the actors to local node by default without load balance?

**Comment by edoakes** [comment] 2022-03-22 16:05
@SongGuyang this is currently intentional because the way we support fetching logs for jobs is by reading them from local disk. If we want to run the actors across the cluster, we need to have a way to fetch & tail logs from each node (maybe through the per-node agent).

**Comment by madsenwattiq** [comment] 2022-03-25 17:32
I see the exact same issue with Ray 1.11.0, running a cluster of two nodes on two physical hosts on the same LAN -- removed any possible complexity from cloud clusters etc.  Can replicate with a tiny toy example, which launches more tasks than either of the machines has cores, and given the discussion in this thread I added `ray.init(address="auto")` to no effect.
![Screen Shot 2022-03-25 at 10 28 36 AM]

All tasks are launched only on the head node (screen shot attached).    (https://user-images.githubusercontent.com/36683499/160171977-d1a3c9e3-5a72-4462-ace8-843db2c779df.png)

Toy example which replicates the issue:

```python
import ray
import random
import time

ray.init(address="auto")

@ray.remote
def task():
    time.sleep(random.randint(2,25))
    return [x for x in range(random.randint(5,50))]

if __name__ == '__main__':
    results = []
    task_handles = [task.remote() for x in range(100)]

    ready_refs, remaining = ray.wait(task_handles)
    results.extend(ray.get(ready_refs))

    while len(remaining) > 0:
        print(f"Tasks remaining: {len(remaining)}")
        ready_refs, remaining = ray.wait(remaining)
        results.extend(ray.get(ready_refs))

    print(f"{results}")
```

**Comment by engrmg** [comment] 2022-08-02 17:10
We were able to make it work by adding a resource in our config. All worker nodes are "tagged" with resource name `count`.

 We figured this out around March 10. I'm not sure if this has been fixed in the newer releases. For the record, we are currently using 1.13.0 and when we filed this GitHub issue we were running version 1.11.0 and 1.10.0

`@ray.remote(num_cpus=1, resources={"count": 1})`

**Comment by architkulkarni** [comment] 2022-11-30 22:27
Closed by https://github.com/ray-project/ray/pull/28203 and https://github.com/ray-project/ray/pull/28654. Starting in Ray 2.2, the job submission API accepts `entrypoint_num_cpus`, `entrypoint_num_gpus`, and `entrypoint_resources` parameters when submitting the job.  By setting any of these parameters, Ray will schedule the job using the same logic it uses to schedule ordinary actors and tasks.

**Closed by architkulkarni** 2022-11-30 22:27 UTC
Labels: enhancement, P1
