### ISSUE TITLE
Build wheels for additional architectures

### ISSUE THREAD

**Issue by jkterry1** [ray-project/ray#7476] opened 2020-03-06 03:11 UTC
CUDA supports ARM, POWER8, POWER9, and x86_64. Ray only builds wheels for x86_64. Tons of supercomputers with GPUs use POWER, and Jetson boards (popularly used in robots) use ARM. Both of those are things that need to be supported.

Last I checked, building ray from source on POWER8 worked just fine.

This was first mentioned in issue #2358, but that was recently closed without explanation.

**Comment by simon-mo** [comment] 2020-03-06 03:26
We currently don't have POWER architecture in our CI to compile our binary and send it out for distribution. It also adds additional overhead for release testing. I can recommend the following:
- If possible, can you help us adding the wheels building steps to produce the POWER9 wheels? The relevant code is at https://github.com/ray-project/ray/blob/e29f2ef788dc399832240ae17fb9464515374eb7/.travis.yml#L130-L170 We might have to use clang cross-compile or running power on qemu. 
- the wheels will have limited support, for example, no fully covered testing. similar to tier 2-3 in rust support guideline https://forge.rust-lang.org/release/platform-support.html#tier-3

**Comment by ddelange** [comment] 2022-03-21 15:46
Adding aarch64 to the mix (ARM64), would make #12128 a duplicate

**Comment by mattip** [comment] 2022-10-20 18:15
Also see #4309 (for ppc64le) and #13780 (for aarch64/macos arm64).

**Comment by mattip** [comment] 2022-11-13 15:05
We should leave only one of the ARM issue #7476 (this one)  #13780 and #12128 open.

**Comment by richardliaw** [comment] 2022-12-21 09:02
I'm going to close this as duplicate of #13780

**Closed by richardliaw** 2022-12-21 09:02 UTC
Labels: enhancement, P3, QS
