### ISSUE TITLE
[tune] How to use local_mode=False?

### ISSUE THREAD

**Issue by letmaik** [ray-project/ray#7461] opened 2020-03-05 09:39 UTC
*Ray version and other system information (Python version, TensorFlow version, OS):*
ray==0.8.2
Python 3.7.3
Ubuntu 18.04

I have no issue using tune with `local_mode=True`, however, if I disable local mode, then the last line is:
```
2020-03-05 09:30:28,589 INFO services.py:1078 -- View the Ray dashboard at localhost:8265
```
I do see 100% CPU usage on the main Python process and 20% on the redis server. The workers are idle. This has been running over 10min without a change.

Is there anything I'm missing or don't understand? Should it just work?

**Comment by richardliaw** [comment] 2020-03-05 20:38
Did you set `num_samples` for `tune.run`?

**Comment by letmaik** [comment] 2020-03-05 21:31
@richardliaw  Yes, I set that to 1.

**Comment by richardliaw** [comment] 2020-03-05 21:36
Ah - can you set it to 8?

**Comment by letmaik** [comment] 2020-03-05 21:39
What does that do? I don't have any sample_from in my search space and with local mode it already works. Could you explain a bit more about this?

**Comment by richardliaw** [comment] 2020-03-06 01:30
It'll just run the same function 8 times, to test that Ray's parallelism is working. 

You might see lots of workers idle because ray starts worker processes by default. Since you've set number of samples to 1, you'll only be running 1 job (no parallelism).

**Comment by letmaik** [comment] 2020-03-06 08:16
Changing to 8 doesn't make a difference, it's still not starting any jobs. Very odd! What's the right way to debug is? Is there some option to enable super-verbose logging?

**Comment by richardliaw** [comment] 2020-03-07 07:39
Yeah; one way to debug this is to use the Ray Dashboard. 

Can you also post a stacktrace/logs from the output?

**Comment by Halopend** [comment] 2020-04-07 20:26
Mine is getting a broken pipe error. not sure why
raceback (most recent call last):
  File "/Users/halopend/.venv/lib/python3.7/site-packages/redis/connection.py", line 700, in send_packed_command
    sendall(self._sock, item)
  File "/Users/halopend/.venv/lib/python3.7/site-packages/redis/_compat.py", line 8, in sendall
    return sock.sendall(*args, **kwargs)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/halopend/.vscode/extensions/ms-python.python-2020.3.71659/pythonFiles/lib/python/debugpy/wheels/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/halopend/.vscode/extensions/ms-python.python-2020.3.71659/pythonFiles/lib/python/debugpy/wheels/debugpy/../debugpy/server/cli.py", line 429, in main
    run()
  File "/Users/halopend/.vscode/extensions/ms-python.python-2020.3.71659/pythonFiles/lib/python/debugpy/wheels/debugpy/../debugpy/server/cli.py", line 266, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/halopend/Documents/School/Neural.tmp/Assignment 4/a4_cnn_tf2.py", line 383, in <module>
    testRunner(config)
  File "/Users/halopend/Documents/School/Neural.tmp/Assignment 4/a4_cnn_tf2.py", line 357, in testRunner
    config=config
  File "/Users/halopend/.venv/lib/python3.7/site-packages/ray/tune/tune.py", line 229, in run
    run_identifier = Experiment.register_if_needed(exp)
  File "/Users/halopend/.venv/lib/python3.7/site-packages/ray/tune/experiment.py", line 212, in register_if_needed
    register_trainable(name, run_object)
  File "/Users/halopend/.venv/lib/python3.7/site-packages/ray/tune/registry.py", line 67, in register_trainable
    _global_registry.register(TRAINABLE_CLASS, name, trainable)
  File "/Users/halopend/.venv/lib/python3.7/site-packages/ray/tune/registry.py", line 108, in register
    self.flush_values()
  File "/Users/halopend/.venv/lib/python3.7/site-packages/ray/tune/registry.py", line 130, in flush_values
    _internal_kv_put(_make_key(category, key), value, overwrite=True)
  File "/Users/halopend/.venv/lib/python3.7/site-packages/ray/experimental/internal_kv.py", line 38, in _internal_kv_put
    updated = worker.redis_client.hset(key, "value", value)
  File "/Users/halopend/.venv/lib/python3.7/site-packages/redis/client.py", line 3004, in hset
    return self.execute_command('HSET', name, key, value)
  File "/Users/halopend/.venv/lib/python3.7/site-packages/redis/client.py", line 877, in execute_command
    conn.send_command(*args)
  File "/Users/halopend/.venv/lib/python3.7/site-packages/redis/connection.py", line 721, in send_command
    check_health=kwargs.get('check_health', True))
  File "/Users/halopend/.venv/lib/python3.7/site-packages/redis/connection.py", line 713, in send_packed_command
    (errno, errmsg))
redis.exceptions.ConnectionError: Error 32 while writing to socket. Broken pipe.

**Comment by krfricke** [comment] 2020-09-16 16:37
Since this issue is a bit dated, I'm closing it. If you still have problems running Tune, please open a new issue and provide a reproducible code example - that way we can better see if this is a problem on your side or in Tune. We're happy to help in either case.

**Closed by krfricke** 2020-09-16 16:37 UTC
Labels: question, tune
