### ISSUE TITLE
[Bug] ray.rllib.utils.error.EnvError: Env's `observation_space` Box does not contain returned observation after a reset

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#18654] opened 2021-09-15 20:33 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

run_regression_tests_stateless_cartpole_r2d2_tf

run_regression_tests_cartpole_continuous_pybullet_sac_tf

Consistently broken in CI. 

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by gjoliver** [comment] 2021-09-15 21:59
Both tests are failing because of the same problem. However, these error msgs don't make sense ...

ray.rllib.utils.error.EnvError: Env's `observation_space` Box([-4.8        -0.41887903], [4.8        0.41887903], (2,), float32) does not contain returned observation after a reset ([0.01022429 0.04979551])!

it obviously contains the obs.

**Comment by mvindiola1** [comment] 2021-09-15 22:55
@gjoliver It is the first dimension. The observed obs value is 0.01022429  but the range is [-4.8 -0.41887903]

**Comment by gjoliver** [comment] 2021-09-15 23:03
I think the ranges are +-4.8 and +-0.418879 though.
I verified it with a unit test.
I am really lost.

**Comment by mvindiola1** [comment] 2021-09-16 14:04
@gjoliver Sorry about that you  are correct I misread. Do you have a link to the failed tests I could look at. I tried to reproduce locally but they succeeded for me.

== Status ==
Memory usage on this node: 11.6/15.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/6 CPUs, 0/1 GPUs, 0.0/5.61 GiB heap, 0.0/2.81 GiB objects (0.0/1.0 accelerator_type:GTX)
Result logdir: /home/ray_results/cartpole-sac
Number of trials: 1/1 (1 TERMINATED)
+------------------------------------------------+------------+-------+--------+------------------+------+----------+----------------------+----------------------+--------------------+
| Trial name                                     | status     | loc   |   iter |   total time (s) |   ts |   reward |   episode_reward_max |   episode_reward_min |   episode_len_mean |
|------------------------------------------------+------------+-------+--------+------------------+------+----------+----------------------+----------------------+--------------------|
| SAC_CartPoleContinuousBulletEnv-v0_ad95a_00000 | TERMINATED |       |      3 |          88.8393 | 3000 |  41.1667 |                  148 |                   11 |            41.1667 |
+------------------------------------------------+------------+-------+--------+------------------+------+----------+----------------------+----------------------+--------------------+

Memory usage on this node: 11.7/15.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/6 CPUs, 0/0 GPUs, 0.0/5.46 GiB heap, 0.0/2.73 GiB objects (0.0/1.0 accelerator_type:GTX)
Result logdir: /home/ray_results/stateless-cartpole-r2d2
Number of trials: 1/1 (1 TERMINATED)
+------------------------------------------------------------------------------+------------+-------+--------+------------------+-------+----------+----------------------+----------------------+--------------------+
| Trial name                                                                   | status     | loc   |   iter |   total time (s) |    ts |   reward |   episode_reward_max |   episode_reward_min |   episode_len_mean |
|------------------------------------------------------------------------------+------------+-------+--------+------------------+-------+----------+----------------------+----------------------+--------------------|
| R2D2_ray.rllib.examples.env.stateless_cartpole.StatelessCartPole_e63cb_00000 | TERMINATED |       |     57 |           107.34 | 59045 |   153.08 |                  339 |                   65 |             153.08 |
+------------------------------------------------------------------------------+------------+-------+--------+------------------+-------+----------+----------------------+----------------------+--------------------+

**Comment by gjoliver** [comment] 2021-09-16 16:09
yeah, closing this for now, since the tests are green again.
if things turn out to be repeatedly flaky, will take another look.

**Closed by gjoliver** 2021-09-16 16:09 UTC
Labels: bug, triage

**Comment by yangysc** [comment] 2021-09-17 10:03
I think it is due to the gym version.  I ran into the same problem using the gym with version 0.20.0, and degraded gym to 0.18.0 to solve it. @xwjiang2010  Hope it helps!

**Comment by mvindiola1** [comment] 2021-09-17 12:57
@yangysc
I don't think it is the gym version. I just upgraded to gym==0.20.0 and both tests ran fine for me 10 times. Either it is an intermittent issue and I didn't trigger it or it is some combination of library versions that is incompatible.

**Comment by gjoliver** [comment] 2022-03-26 17:14
Please provide a reproduce script. Thanks.

**Comment by evo11x** [comment] 2022-03-26 17:38
I cannot provide the script because it depends on a bigger data which I cannot post here.

This is the error:

```
 pid=16948) 2022-03-26 19:30:48,757     ERROR worker.py:431 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=16948, ip=127.0.0.1)
 pid=16948)   File "python\ray\_raylet.pyx", line 625, in ray._raylet.execute_task
 pid=16948)   File "python\ray\_raylet.pyx", line 629, in ray._raylet.execute_task
 pid=16948)   File "python\ray\_raylet.pyx", line 578, in ray._raylet.execute_task.function_executor
 pid=16948)   File "d:\VS\PROJECTS\Python\myproject\.env\lib\site-packages\ray\_private\function_manager.py", line 609, in actor_method_executor
 pid=16948)     return method(__ray_actor, *args, **kwargs)
 pid=16948)   File "d:\VS\PROJECTS\Python\myproject\.env\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
 pid=16948)     return method(self, *_args, **_kwargs)
 pid=16948)   File "d:\VS\PROJECTS\Python\myproject\.env\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 463, in __init__
 pid=16948)     _validate_env(self.env, env_context=self.env_context)
 pid=16948)   File "d:\VS\PROJECTS\Python\myproject\.env\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 1700, in _validate_env
 pid=16948)     raise EnvError(
```

And this is my observation space

```
 self.obs_data1 = spaces.Box(low=-np.inf, high=np.inf, 
                                shape=(1200,),
                                dtype=np.float32)
                                
 self.obs_data2 = spaces.Box(low=-np.inf, high=np.inf,  
                                shape=(8400,),
                                dtype=np.float32)
                                
 self.obs_math = spaces.Box(low=-np.inf, high=np.inf, 
                                shape=(840,),
                                dtype=np.float32)
        
 self.observation_space = spaces.Dict({"data1": self.obs_data1,
                                       "data2": self.obs_data2,
                                       "math": self.obs_math})
```

When I increase the size of self.obs_math by any number the error starts to appear. If I increase data1 or data2 it works.

Again stable_baselines3 runs fine with the observation

**Comment by gjoliver** [comment] 2022-03-26 21:19
we have custom logics to verify that the obs you get form an env matches the declared spaces.
in your case, the data ranges are from -inf to inf, so the values will always be in range.
so there is likely some mis-match in the shape of the data your env returns after the reset call, i.e., it does not have shape (840,):

... does not contain returned observation after a reset ...

**Comment by evo11x** [comment] 2022-03-26 21:30
I have checked and reset returns the identical observation as the step which matches the declared observation. 
But I will do some more checks and try with a single observation non dict
