### ISSUE TITLE
View Ray Tune output in Google Colab Notebook

### ISSUE THREAD

**Issue by lucaguarro** [ray-project/ray#16197] opened 2021-06-02 18:46 UTC
### What is the problem?
This problem is very similar to [Issue #13060](https://github.com/ray-project/ray/issues/13060).
I am using the Huggingface + Raytune integration to run [this example](https://docs.ray.io/en/master/tune/examples/pbt_transformers.html). I am able to get the code running but am unable to view all the results. In the output I see many of these: `<IPython.core.display.HTML object>`

- Python Version: 3.7.10
- Ray Version: 1.3.0

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
The link above contains all the code that I am using but for convenience I can share my [Google Colab](https://colab.research.google.com/drive/1FjPDf11n5eONjgHowJqXWyepltX6DJru?usp=sharing) environment as well.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment] 2021-06-14 16:44
Hey @lucaguarro thanks for reporting this! @krfricke will take a closer look.

**Comment by krfricke** [comment] 2021-06-25 11:21
Hi @lucaguarro, unfortunately I cannot reproduce your issue. Your colab output looks like this to me:

<img width="909" alt="Screen Shot 2021-06-25 at 12 20 03 PM" src="https://user-images.githubusercontent.com/14904111/123417529-c53c7980-d5af-11eb-9af5-70bc27af8201.png">

And on a fresh colab with a basic example, both reporters work for me, too. Can you send me a screenshot or so?

**Comment by krfricke** [comment] 2021-06-25 11:32
The weird thing here is that you even specify a CLIReporter, which should not produce any jupyter table output at all. I'm wondering if this is actually caused by W&B - do you see tables like the one I posted above in your output?

**Comment by krfricke** [comment] 2021-06-25 12:34
Ah, I could finally reproduce it after logging in with W&B and disabling file output logging.

This seems to be a problem with W&B - they seem to detect the jupyter session, but since they log inside a Tune process, they should be logging text instead.

I'll try to work on a fix for that.

**Comment by krfricke** [comment] 2021-06-25 16:24
Turns out it's not wandb after all, but a hugging face progress callback. I'll file a PR on their end.

**Comment by krfricke** [comment] 2021-06-28 07:08
Closed by https://github.com/huggingface/transformers/pull/12357

**Closed by krfricke** 2021-06-28 07:08 UTC
Labels: P1, bug, tune
