### ISSUE TITLE
[Datasets] Group by multiple keys

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#31211] opened 2022-12-20 00:41 UTC
### Description

I want to do something like

```
dataset.groupby(["key1", "key2"]).map_groups(...)
```

### Use case

I need to group by multiple keys. Since `groupby` only supports one key, I have to write an additional UDF to add the key:

```
def add_key(batch):
    batch["key"] = (batch["key1"], batch["key2"])
    return batch

dataset.map_batches(add_key).groupby("key").map_groups(...)
```

**Comment by clarkzinzow** [comment] 2023-01-05 15:22
Agreed on the need for this! Duplicate of https://github.com/ray-project/ray/issues/25732; I think that coupling multi-key support for sorting and groupby since they share a lot of their implementation.

**Closed by clarkzinzow** 2023-01-05 15:22 UTC
Labels: enhancement, datasets
