### ISSUE TITLE
[Core][Nightly] Failed pipelined_ingestion_1500_gb_15_windows due to function manager

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#22161] opened 2022-02-07 03:57 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

It's failing due to https://github.com/ray-project/ray/commit/2038cc96c6833d296ffbeb8a4473bbe73391776c based on bisect https://buildkite.com/ray-project/periodic-ci/builds/2672

### Versions / Dependencies

master

### Reproduction script

nightly test

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment] 2022-02-07 06:39
cc @ericl can we revert this commit for now?

**Comment by ericl** [comment] 2022-02-07 18:50
Why is it failing?

**Comment by jjyao** [comment] 2022-02-07 19:07
It hangs at the very beginning:
```
(_prepare_read pid=387, ip=10.0.3.181)
--
  | Metadata Fetch Progress:  90%\|█████████ \| 9/10 [00:12<00:01,  1.07s/it]
  | (_prepare_read pid=387, ip=10.0.3.181)
  | Metadata Fetch Progress: 100%\|██████████\| 10/10 [00:13<00:00,  1.09s/it]
  | Metadata Fetch Progress: 100%\|██████████\| 10/10 [00:13<00:00,  1.39s/it]
  | (PipelineSplitExecutorCoordinator pid=353, ip=10.0.3.69)
  | Stage 0: 100%\|██████████\| 1/1 [03:25<00:00, 205.03s/it]
  | 2022-02-07 08:24:22,916	WARNING worker.py:1471 -- This worker was asked to execute a function that it does not have registered. You may have to restart Ray.


```

**Comment by jjyao** [comment] 2022-02-07 19:16
It's possible that `_wait_for_function` never returned.

**Comment by jjyao** [comment] 2022-02-07 19:22
Also saw
```
(raylet, ip=10.0.3.116) E0207 08:17:42.693564053     211 server_chttp2.cc:48]        {"created":"@1644250662.693506004","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":872,"referenced_errors":[{"created":"@1644250662.693500594","description":"Failed to add any wildcard listeners","file":"src/core/lib/iomgr/tcp_server_posix.cc","file_line":348,"referenced_errors":[{"created":"@1644250662.693482975","description":"Unable to configure socket","fd":17,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":216,"referenced_errors":[{"created":"@1644250662.693478391","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Address already in use","syscall":"bind"}]},{"created":"@1644250662.693499647","description":"Unable to configure socket","fd":17,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":216,"referenced_errors":[{"created":"@1644250662.693496384","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Address already in use","syscall":"bind"}]}]}]}
```

**Comment by ericl** [comment] 2022-02-07 19:35
I think we should just investigate this one instead. The PR will be quite hard to revert, and this isn't impacting other components.

**Comment by ericl** [comment] 2022-02-07 19:36
Can try setting DEFAULT_ENABLE_PANDAS_BLOCK=False to further narrow down the cause here.

**Comment by scv119** [comment] 2022-02-07 23:25
@jjyao I'm turning it off in https://github.com/ray-project/ray/pull/22194 for the other P0s

**Comment by jjyao** [comment] 2022-02-07 23:30
Thanks. For this case, turning it off seems to be not working.

**Comment by jjyao** [comment] 2022-02-08 17:25
Confirmed. It's infinite loop of `_wait_for_function`.

**Comment by ericl** [comment] 2022-02-08 18:24
Cc @iycheng

**Comment by jjyao** [comment] 2022-02-08 22:40
Basically `gcs_function_key_subscriber.poll()` doesn't return even though there are still new functions to be downloaded.

**Comment by iycheng** [comment] 2022-02-08 22:53
I think there might be two cases here: 1) pubsub is losing message; 2) import failed. @mwtian  could you help check whether 1) is happening?

**Comment by iycheng** [comment] 2022-02-08 23:03
```
(raylet, ip=10.0.3.116) E0207 08:17:42.693564053     211 server_chttp2.cc:48]        {"created":"@1644250662.693506004","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":872,"referenced_errors":[{"created":"@1644250662.693500594","description":"Failed to add any wildcard listeners","file":"src/core/lib/iomgr/tcp_server_posix.cc","file_line":348,"referenced_errors":[{"created":"@1644250662.693482975","description":"Unable to configure socket","fd":17,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":216,"referenced_errors":[{"created":"@1644250662.693478391","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Address already in use","syscall":"bind"}]},{"created":"@1644250662.693499647","description":"Unable to configure socket","fd":17,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":216,"referenced_errors":[{"created":"@1644250662.693496384","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Address already in use","syscall":"bind"}]}]}]}
(raylet, ip=10.0.3.116) E0207 08:17:59.503719569     220 server_chttp2.cc:48]        {"created":"@1644250679.503665345","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":872,"referenced_errors":[{"created":"@1644250679.503659633","description":"Failed to add any wildcard listeners","file":"src/core/lib/iomgr/tcp_server_posix.cc","file_line":348,"referenced_errors":[{"created":"@1644250679.503641889","description":"Unable to configure socket","fd":17,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":216,"referenced_errors":[{"created":"@1644250679.503637296","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Address already in use","syscall":"bind"}]},{"created":"@1644250679.503658684","description":"Unable to configure socket","fd":17,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":216,"referenced_errors":[{"created":"@1644250679.503655307","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Address already in use","syscall":"bind"}]}]}]}
```

It seems like grpc reported some errors.

**Comment by mwtian** [comment] 2022-02-11 17:43
The issue is tracked down to a call to Python GC that took ~ 2min 50s.
- Raylet periodically (every 10s in this case) sends a request ([LocalGC](https://sourcegraph.com/github.com/ray-project/ray@358771c63688ecd673bb0f18fd87b19ab7017d24/-/blob/src/ray/core_worker/core_worker.cc?L2912)) to core worker to execute GC in the language worker.
- In this case, the [callback](https://sourcegraph.com/github.com/ray-project/ray@358771c/-/blob/python/ray/_raylet.pyx?L871)  to Python GC somehow took almost ~ 170s. This callback either holds or competes for GIL, so it is likely all threads in the Python worker stalled for ~ 170s. 
- For subscribers, their long polls to the publisher are returned every 30s even with empty results. Then subscribers are expected to issue a new long poll soon. Otherwise, if a subscriber has no active poll and has not issued a new poll within sometime, the subscriber is marked dead and gets deleted. This is also happened to the import subscriber. Afterwards new imports would not be received by the import subscriber, even after the subscriber resumed polling.
- The interesting point about the last function exported, is that the export time coincides with when GC finishes. 
- During the period where GC is stalled, the core worker's rpc event loop (`io_service_`) is blocked too. This can be problematic on its own, and is one possibility of the root cause of the stall.

Here is a sample of logs.
```
From driver:
2022-02-11 07:59:53,922	WARNING worker.py:1467 -- Received error message for job: This worker (node=10.0.3.102 worker_id=9218f6c46c3b256d9a48afa49f706fd7efdb28fde27bfd5c9fc43590 PID=539) was asked to execute a function that it has not imported. You may have to restart Ray.

From Python worker:
:task_name:remote_read
2022-02-11 07:56:38,187	INFO import_thread.py:69 -- dbg ImportThread 1st search after start: self.num_imported=29
2022-02-11 07:56:38,188	INFO gcs_pubsub.py:443 -- dbg GcsFunctionKeySubscriber id=b'\xa2\x86)\xf4[\x86Z\xe5\xe8]\xb2\xa5\x8co\xea\xad\xfd\xf7AI\x07\x0er\x83\xad\xd1ae' hex=a28629f45b865ae5e85db2a58c6feaadfdf74149070e7283add16165 polling started
2022-02-11 07:56:38,189	INFO gcs_pubsub.py:286 -- dbg _poll_locked id=b'\xa2\x86)\xf4[\x86Z\xe5\xe8]\xb2\xa5\x8co\xea\xad\xfd\xf7AI\x07\x0er\x83\xad\xd1ae' hex=a28629f45b865ae5e85db2a58c6feaadfdf74149070e7283add16165 req=subscriber_id: "\242\206)\364[\206Z\345\350]\262\245\214o\352\255\375\367AI\007\016r\203\255\321ae"
2022-02-11 07:59:43,468	INFO actor.py:1103 -- dbg Actor destructor.
2022-02-11 07:59:43,507	INFO gcs_pubsub.py:286 -- dbg _poll_locked id=b'\xa2\x86)\xf4[\x86Z\xe5\xe8]\xb2\xa5\x8co\xea\xad\xfd\xf7AI\x07\x0er\x83\xad\xd1ae' hex=a28629f45b865ae5e85db2a58c6feaadfdf74149070e7283add16165 req=subscriber_id: "\242\206)\364[\206Z\345\350]\262\245\214o\352\255\375\367AI\007\016r\203\255\321ae"
2022-02-11 08:00:28,900	INFO gcs_pubsub.py:286 -- dbg _poll_locked id=b'\xa2\x86)\xf4[\x86Z\xe5\xe8]\xb2\xa5\x8co\xea\xad\xfd\xf7AI\x07\x0er\x83\xad\xd1ae' hex=a28629f45b865ae5e85db2a58c6feaadfdf74149070e7283add16165 req=subscriber_id: "\242\206)\364[\206Z\345\350]\262\245\214o\352\255\375\367AI\007\016r\203\255\321ae"

From Python core worker:
[2022-02-11 07:56:51,454 I 539 639] core_worker.cc:2916: dbg HandleLocalGC start 9218f6c46c3b256d9a48afa49f706fd7efdb28fde27bfd5c9fc43590
[2022-02-11 07:59:43,466 I 539 639] core_worker.cc:2918: dbg HandleLocalGC end 9218f6c46c3b256d9a48afa49f706fd7efdb28fde27bfd5c9fc43590

From GCS:
[2022-02-11 07:56:21,154 I 182 195] (gcs_server) pubsub_handler.cc:44: dbg HandleGcsPublish pub_messages { channel_type: RAY_PYTHON_FUNCTION_CHANNEL python_function_message { key: "RemoteFunction:02000000:u\206\215\356\336&\313e\246-y\341Q\027\335\315\371\372\367\375\305$@\036i\246h\233" } }
[2022-02-11 07:56:36,246 I 182 195] (gcs_server) pubsub_handler.cc:44: dbg HandleGcsPublish pub_messages { channel_type: RAY_PYTHON_FUNCTION_CHANNEL python_function_message { key: "ActorClass:02000000:\334\254eQ&\2673\326|B\"^|\307\205\000\260J|\270\214\314\261\255\234\334\213\271" } }
[2022-02-11 07:56:36,396 I 182 195] (gcs_server) pubsub_handler.cc:44: dbg HandleGcsPublish pub_messages { channel_type: RAY_PYTHON_FUNCTION_CHANNEL python_function_message { key: "RemoteFunction:02000000:\234\375\214\351\014#\204\314\357\220\013\347\251\2605!\363\337\337\000d3!\360\377\242K\235" } }
[2022-02-11 07:59:43,576 I 182 195] (gcs_server) pubsub_handler.cc:44: dbg HandleGcsPublish pub_messages { channel_type: RAY_PYTHON_FUNCTION_CHANNEL python_function_message { key: "RemoteFunction:02000000:P\201\331^\010\244\367\245J?\004\362\016A\241\241\377\365m\201\321\3156\177x\007\323\311" } }
```

It should be possible to mitigate the import subscriber issue on its own, but it seems the long GC stall is very problematic. I'm looking into the root cause.

**Comment by rkooo567** [comment] 2022-02-12 01:25
Maybe making it asynchornous == using a dedicated thread (it is an impl$

**Comment by mwtian** [comment] 2022-02-12 04:57
@rkooo567 Importer thread uses a Python-based subscriber (instead of the C++ subscriber), so it was unable to run when Python GIL is held by LocalGC callback or some other logic. Offloading LocalGC to another thread seems like a good change on its own, which I planned to experiment. But I'm not 100% sure it is addressing the root cause.

**Comment by rkooo567** [comment] 2022-02-12 06:52
Hmm I see. So the problem we need to solve is to make sure the pubsub health checking is not blocked by python thread right? I feel like this shouldn’t be fundamentally impossible since health checking is done in cpp. I guess you have some ideas, but some immediate thoughts;
1. Remove the current health checking mechanism and rely on grpc keepalive feature.
2. Idk how the python subscriber works now, but it must be possible to separate out pubsub logic / python code?

**Comment by ericl** [comment] 2022-02-12 07:21
Sounds like a bug in resume handling protocol? Shouldn't the client catch up after reconnecting to get the latest state?

**Comment by scv119** [comment] 2022-02-12 09:56
Yeah I think for correctness we'd better fix the resume handling protocol. Even we fix the GC seems we could still subject to other failure like network partition.

**Comment by ericl** [comment] 2022-02-12 19:46
Why doesn't the client send it's current state (e.g., "4"), and the server
can send an update if it's changed since then, e.g., advanced to "5"? Or
just always send the current state on subscribe.

We don't need true pub sub for gcs, just state subscription.

**Comment by mwtian** [comment] 2022-02-14 22:35
Downgrading to P1 since this is no longer occurring, and we know the likely root cause. Planned fixes include:
- Run LocalGC in a thread other than the RPC event loop.
- Improve subscriber reconnection to make sure it learns about the latest states of subscribed objects, after timeouts or errors. (#22340)

**Comment by ericl** [comment] 2022-02-14 23:05
Sounds good. Shall we also increase the timeout a little (5 min)?

**Comment by mwtian** [comment] 2022-02-14 23:32
Sure, will send out a PR later.

**Comment by mwtian** [comment] 2022-02-16 20:56
I'm using a commit that can reproduce the issue (missing import), and a few obvious mitigations do not seem to fix the issue:
- Increasing subscriber timeout. This increases the time where Python process appears stuck too.
- Using separate thread for GC.

Back to more investigations. Only thing we know for sure is that GIL is held for a long period time. The failure is also happening on the `releases/1.11.0` branch.

**Comment by mwtian** [comment] 2022-02-16 22:14
To clarify,`LocalGC` is not relevant to the deadlock as I originally thought. When `LocalGC` takes ~170s, it was because of trying to acquire GIL for ~170s. I'm still investigating the reason behind GIL being held for a long time here.

**Comment by mwtian** [comment] 2022-02-18 16:29
It was found that the test was spending a lot of time within `ray::parallel_memcopy()` while holding GIL. #22492 mitigates the GIL issue. There is no longer import missing errors. But test is still slow, and unable to finish within the allocated 4800s. Remaining questions are:
- Which change affected output format and increased output serialization time? I'm bisecting but I suspect it is related to pyarrow. cc @scv119 
- It should be possible to optimize serialization and `ray::parallel_memcopy()` to reduce the time spent in corner cases.

**Comment by mwtian** [comment] 2022-02-19 00:49
@scv119 since pinning pyarrow to < 7 avoids the issue, I assume version 7 introduced the serialization slow down? A dataset specific benchmark could be useful here. For `ray::parallel_memcopy()`, I can imagine it is useful for copying large buffers. But for smaller data it can be inefficient. Adding a benchmark and tuning it a bit could be useful, if we are running into issues.

Since the root cause is understood, and the uncovered problem of holding GIL while copying data has been mitigated, closing the issue now. Follow ups for more robust pubsub are tracked separately.

**Closed by mwtian** 2022-02-19 00:49 UTC
Labels: P1
