### ISSUE TITLE
[Core] Worker seen dead by driver if run with `--block` in a TTY console and a task wants to read from stdin

### ISSUE THREAD

**Issue by vnlitvinov** [ray-project/ray#47879] opened 2024-10-02 11:46 UTC
### What happened + What you expected to happen

I'm running a toy Ray cluster on two machines with GPUs, using docker and `rayproject/ray-ml:2.30.0-py39-gpu` image as base (my workload installs some additional packages including a VPN, but I don't think it's relevant here).

Then the cluster is spawned as follows:
1. A head node is created via `docker run ` passing my custom entrypoint shell script, which starts VPN and eventually runs `ray start --head --port=6379 --num-cpus=NUM_CPUS_PLACEHOLDER --node-ip-address=${VPN_IP} --num-gpus=NUM_GPUS_PLACEHOLDER --include-dashboard=true --dashboard-host=127.0.0.1 --node-manager-port=1915 --object-manager-port=1916 --dashboard-agent-grpc-port=1917 --dashboard-agent-listen-port=1918 --disable-usage-stats --block &`
2. Then on another machine, same image is spawned, but this time a little bit differently (with entrypoint being `tail -f /dev/null` to make it basically sit idle)
3. Then I create an interactive session via `docker exec -it ray_worker_gpu /bin/bash` and run commands in that shell, as follows:
4. VPN is created
5. Ray is started via `ray start --address=${HEADNODE_IP_ADDRESS}:6379 --node-name=$(hostname)-ray --node-manager-port=1915 --object-manager-port=1916 --dashboard-agent-grpc-port=1917 --dashboard-agent-listen-port=1918 --disable-usage-stats --block &`

At this point, I have two devices running Ray containers and connected to each other just fine.
Now, if I submit a simple Ray job that wants to read something from `stdin` (provided in reproduction script), the execution on the headnode pauses until eventually a worker is being marked as dead because its heartbeats stopped coming, with a message like `has been marked dead because the detector has missed too many heartbeats from it`.

Processes on the worker node are still happily running, though, and nothing suspicious in the logs as far as I can see, _however_ logs stop adding - so it feels like the raylet code actually freezes.

If I remove the `--block` option on the worker, the repro script quits with a (mostly expected) error:
```
Command failed with error:
 Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 5] Input/output error
```

While blocking indefinitely on waiting for stdin vs failing like above is questionable, node definitely should _not_ be dying if running such a script.

### Versions / Dependencies

Ray 2.30
Docker image `rayproject/ray-ml:2.30.0-py39-gpu` with some additional packages installed inside

### Reproduction script

```python
import ray
import subprocess
import sys

@ray.remote
def run_command_with_input():
    try:
        result = subprocess.run(
            [sys.executable, '-c', 'print(input())'],
            #['sudo', 'ls'],
            check=True,
            # stdin=None,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
        return result.stdout.decode('utf-8'), None
    except subprocess.CalledProcessError as e:
        return None, e.stderr.decode('utf-8')

def main():
    ray.init()

    stdout, stderr = ray.get(run_command_with_input.remote())

    if stdout:
        print("Command executed successfully:\n", stdout)
    if stderr:
        print("Command failed with error:\n", stderr)
    if stdout is None and stderr is None:
        print("No output or error was returned.")

if __name__ == "__main__":
    main()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by dayshah** [comment] 2024-12-10 22:05
So tried to repro with ```ray start --head --num-cpus 0 --block``` on head node and then did ```ray start --address='${HEADNODE_IP}:6379' --block``` separately for the worker and then ran your exact repro script and it worked successfully. I was able to run the script, type hi in the terminal where the worker was running, and see it show up as the output of the script. It's likely a product of your network/container setup. Let me know if you can figure out what the root cause may be, try running the head and worker on the same machine and seeing if that works.

Just as a disclaimer though, this isn't an ideal use case for ray in general though, ideally you shouldn't really be checking for things from standard input on a worker, where a worker gets scheduled isn't necessarily something that's supposed to be known ahead of time.

**Comment by vnlitvinov** [comment] 2024-12-11 13:32
@dayshah when you reproduced what I was seeing, did you spawn both head and worker Ray instances inside docker containers? It was the differentiator in my setup.

**Comment by dayshah** [comment] 2024-12-12 17:20
Just tried it with two docker containers running the rayproject/ray:2.40.0-py39-cpu-aarch64 images. Same steps as described in my previous comment running the repro script, and it works correctly. Successfully prints `hi` on the driver after i type `hi` in the blocked worker terminal. You mentioned you were also using a vpn, it seems that some setup with your network is likely blocking the communication in this situation.

**Comment by dayshah** [comment] 2024-12-19 21:55
Closing for now based on above, feel free to reopen and @ me if you find that it's not due to the network setup and due to something else.

**Closed by dayshah** 2024-12-19 21:55 UTC
Labels: bug, P2, core
