### ISSUE TITLE
[Core] ActorPool.map returns results in an unexpected order

### ISSUE THREAD

**Issue by Erin-Boehmer** [ray-project/ray#34165] opened 2023-04-07 18:44 UTC
### What happened + What you expected to happen

`ActorPool.map` returns results in an unexpected order. Here is the code I'm using (explanation in comments):

```
# Create async OCR and LayoutAnalysis actors to execute OCR and layout analysis processes
ocr_actors = [Ocr.remote() for i in range(4)]
lp_actors = [LayoutAnalysis.remote(self.layout_analysis_model) for i in range(4)]

# Gather actors into an ordered pool and distribute tasks to each
actor_pool = ActorPool(ocr_actors + lp_actors)
actor_pool_mapping = actor_pool.map(
    lambda a, d: a.process.remote(d), jpgs_buffer[:4] * 2
)

# ActorPool mapping synchronously pulls result futures.
# The order of jpgs_buffer inputs is maintained (returns jpg pages [0,1,2,3,0,1,2,3], as expected)
# But the Actor groups are reversed (returns LP, OCR rather than OCR, LP). 
results = list(actor_pool_mapping)
lp_results = results[:4] # I expect lp_results to be results[4:] given I passed that list of Actors to the pool 2nd 
ocr_results = results[4:] # I expect ocr_results to be results[:4] given I passed that list of Actors to the pool 1st 
```

This reverse ordering of Actor groups happens even when I change the code to `actor_pool = ActorPool(lp_actors + ocr_actors)`.

### Versions / Dependencies

Ray 2.3.0
Python 3.9.16

### Reproduction script
```
# Create async OCR and LayoutAnalysis actors to execute OCR and layout analysis processes
ocr_actors = [Ocr.remote() for i in range(4)]
lp_actors = [LayoutAnalysis.remote(self.layout_analysis_model) for i in range(4)]

# Gather actors into an ordered pool and distribute tasks to each
actor_pool = ActorPool(ocr_actors + lp_actors)
actor_pool_mapping = actor_pool.map(
    lambda a, d: a.process.remote(d), jpgs_buffer[:4] * 2
)

# ActorPool mapping synchronously pulls result futures.
# The order of jpgs_buffer inputs is maintained (returns jpg pages [0,1,2,3,0,1,2,3], as expected)
# But the Actor groups are reversed (returns LP, OCR rather than OCR, LP). 
results = list(actor_pool_mapping)
lp_results = results[:4] # I expect lp_results to be results[4:] given I passed that list of Actors to the pool 2nd 
ocr_results = results[4:] # I expect ocr_results to be results[:4] given I passed that list of Actors to the pool 1st 
```
### Issue Severity

Low: It annoys or frustrates me.

**Comment by matthewdeng** [comment] 2023-04-17 05:20
Hey @Erin-Boehmer, `ActorPool` does not guarantee any ordering amongst the _actors_ that are being mapped on, only the _values_ that you are passing in. 

1. If you want to maintain ordering between `ocr_actors` and `lp_actors` but not actors within each group, you may want to create a separate `ActorPool` for each.
2. If you want to maintain ordering between each actor, you may want to maintain the list of Actors and directly `zip` them with the values being submitted.


<details><summary>Additional Details</summary>
<p>

To explain the behavior you saw (LP -> OCR), this is happening because the `ActorPool` will actually `pop` the actors when submitting tasks, so it's not just the groups that are being reversed, but the order of all the actors that are in the list. But again, I wouldn't recommend relying on any ordering guarantees around actors when using `ActorPool`.

Quick example:
```python
import ray
from ray.util import ActorPool

@ray.remote
class SomeActor:
    def __init__(self, value) :
        self.value = value

    def process(self, data):
        return f"[{self.value}] {data}"


values = range(4)
actors = [SomeActor.remote(i) for i in values]
actor_pool = ActorPool(actors)

actor_pool_mapping = actor_pool.map(
    lambda a, d: a.process.remote(d), values
)
results = list(actor_pool_mapping)

print(results)
```
```
['[3] 0', '[2] 1', '[1] 2', '[0] 3']
```

</p>
</details>

**Comment by cadedaniel** [comment] 2023-04-17 19:37
Seems this is expected behavior. We could consider a change to the behavior but I think it's complicated because enforcing ordering on input actors only works for this trivial create/map case. When the `map` calls oversubscribe the available actors, it's difficult to say which actor it should go to. So, we should leave this as unordered.

Going to close this. Feel free to re-open @Erin-Boehmer if there's something we missed.

**Comment by Erin-Boehmer** [comment] 2023-04-25 14:58
@matthewdeng my use case is the first scenario you describe. I'd be fine having two separate actor pools (logically cleaner). The issue is the separate list() call for each. Forcing synchronization on a separate pool rather than both pools at the same time adds ~4 seconds to the total runtime for my service.

```
        # Create async actors to execute OCR and layout analysis
        ocr_actors = [Ocr.remote() for i in range(num_pages)]
        lp_actors = [
            LayoutAnalysis.remote(self.layout_analysis_model) for i in range(num_pages)
        ]

        # Gather actors into an ordered pool and distribute tasks to each
        ocr_actor_pool = ActorPool(ocr_actors)
        ocr_actor_pool_mapping = ocr_actor_pool.map(
            lambda a, d: a.process.remote(d), jpgs_buffer[:num_pages]
        )
        lp_actor_pool = ActorPool(lp_actors)
        lp_actor_pool_mapping = lp_actor_pool.map(
            lambda a, d: a.process.remote(d), jpgs_buffer[:num_pages]
        )

        # ActorPool mapping synchronously pulls result futures in reverse order
        ocr_results = list(ocr_actor_pool_mapping)  # takes less time, retrieve first (this call adds ~4 seconds)
        lp_results = list(lp_actor_pool_mapping)
```

**Comment by matthewdeng** [comment] 2023-04-27 03:28
@Erin-Boehmer I did some digging and it seems like this was indeed a bug in the `map` logic! I've filed a fix for this in https://github.com/ray-project/ray/pull/34813 - I've verified that it works locally and will add some tests before getting it merged.

On a separate note, I've been thinking about your example some more and just wanted to confirm for your use case that in practice you do eventually expect `num_pages` to be greater than `num_actors`? The reason for this question is just that if these numbers _are_ the same then there's no benefit to creating `Actor`s/`ActorPool`s over `Task`s.

**Comment by Erin-Boehmer** [comment] 2023-04-27 18:25
Awesome find @matthewdeng thank you 🙏 

My case is that I have 4 pages of text and want to run layout analysis and ocr on each of the pages in parallel. Here's what "proper execution" looks like:

<img width="625" alt="Screen Shot 2023-04-27 at 2 22 00 PM" src="https://user-images.githubusercontent.com/3460589/234956940-be91c482-a539-4028-90c4-cbfe0f5cddcc.png">

My understanding the Actors are helpful to init a state for each task (AWS boto3 conn for OCR, model init for layout analysis). Is there an advantage to instead running tasks?

**Comment by matthewdeng** [comment] 2023-04-27 18:52
Yeah your understanding is correct! If you only expect to call `process` once per `Actor` then there isn't much of a difference, whereas if you make multiple calls to `process` you can amortize that heavy initialization cost. 

For your particular example I'd say the benefits of using `Actor`/`ActorPool` would be to enable the ability to scale the number of pages you want to process while maintaining a fixed number of processes/resources. On the other hand, using `Task`s would provide you with (slightly) more granularity on how you handle each processing call.

Just for reference:

Actor
```python
@ray.remote
class LayoutAnalysis():
    def __init__(self):
          self.model = setup_model()

    def process(self, value):
        return self.model(value)
```

Task
```python
@ray.remote
def layout_analysis(value):
    model = setup_model()
    return model(value)
```

**Closed** 2023-05-01 22:53 UTC
Labels: bug, @external-author-action-required, core
