### ISSUE TITLE
[release][CI] long_running_impala failed 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29319] opened 2022-10-13 17:35 UTC
### What happened + What you expected to happen

[Build failure ](https://buildkite.com/ray-project/release-tests-branch/builds/1108#0183cdac-c984-4839-927e-37e476335a1c)

[Cluster](https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_8VTuCPu3RZ1292bwn6G6NuQk?command-history-section=command_history)

Looks like OOM issue related. 

```
Traceback (most recent call last):
  File "workloads/impala.py", line 61, in <module>
    callbacks=[ProgressCallback()],
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 877, in run_experiments
    callbacks=callbacks,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 771, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [IMPALA_CartPole-v1_0ee4f_00000])

```

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by gjoliver** [comment] 2022-10-17 17:53
maybe this dashboard mem leak thing should be a release blocker.

<img width="1119" alt="Screen Shot 2022-10-17 at 10 52 22 AM" src="https://user-images.githubusercontent.com/6347585/196247922-96e03e84-1e4d-4575-9ce3-9544b46c52aa.png">

**Comment by rickyyx** [comment] 2022-10-17 20:18
This is probably caused by the #29199

**Comment by rkooo567** [comment] 2022-10-17 20:38
Is it possible to bisect this? There must be information from the nightly dashboard? Looks like regression

**Comment by rickyyx** [comment] 2022-10-19 23:43
So this is caused by agent leak?

**Comment by rkooo567** [comment] 2022-10-20 07:25
yeah this one seems to be due to agent leak. Let's re-run after merging https://github.com/ray-project/ray/pull/29451

**Comment by rkooo567** [comment] 2022-10-20 07:25
I will take this issue @gjoliver @matthewdeng

**Comment by rickyyx** [comment] 2022-10-20 23:59
https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_ibY1y8rd6B5JzgYyyYxMksek?command-history-section=command_history most recent nightly still failed.

**Comment by rkooo567** [comment] 2022-10-21 06:39
The fix PR was merged after this date (it is merged on 20th).

**Comment by rkooo567** [comment] 2022-10-21 06:44
manually triggered here https://buildkite.com/ray-project/release-tests-pr/builds/18758

**Comment by rkooo567** [comment] 2022-10-22 14:37
running here https://buildkite.com/ray-project/release-tests-pr/builds/18760#0184001b-f13c-4527-9a5d-1a6b225155dd

**Comment by rkooo567** [comment] 2022-10-23 14:41
^ agent mem usage is 169MB after 23h run. So I think it can be closed

<img width="1342" alt="Screen Shot 2022-10-23 at 7 40 52 AM" src="https://user-images.githubusercontent.com/18510752/197398466-3f7dc404-972c-4623-94a6-af742376b72f.png">

**Closed by rkooo567** 2022-10-23 14:41 UTC
Labels: bug, release-blocker, triage, r2.1-failure
