### ISSUE TITLE
[Air] [Train] Streaming resource limits not being shared to Trainer 

### ISSUE THREAD

**Issue by bchalk101** [ray-project/ray#35164] opened 2023-05-09 08:27 UTC
### What happened + What you expected to happen

Hey,

I have tried to set the streaming object store memory, however, it does not appear to propagate down to the Trainer.

I have set it to 1MB, and confirm that it is set, however, when I use the DummyTrainer it prints out that it is set to 3.93GB.

`(pid=21176) Running: 2.0/8.0 CPU, 0.0/0.0 GPU, 88.3 MiB/3.93 GiB object_store_memory 0:   0%|          | 0/2547 [06:04<?, ?it/s]`

When I iterate over the dataset, with in the root process, than Ray only uses 1MB, for the stream.

### Versions / Dependencies

ray                           2.4.0
python                    3.7.8 

### Reproduction script

```
import ray.data
from ray.data.context import DatasetContext
from ray.air.util.check_ingest import DummyTrainer
from ray.air.config import ScalingConfig
# export RAY_DATA_VERBOSE_PROGRESS=1 

DatasetContext.get_current().execution_options.resource_limits.object_store_memory = 1024 * 1024
print(DatasetContext.get_current().execution_options.resource_limits.object_store_memory_str())


dataset = ray.data.range(100)

trainer = DummyTrainer(
    scaling_config=ScalingConfig(num_workers=1, use_gpu=False), 
    datasets={"train": dataset},
    num_epochs=1,
)
trainer.fit()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by ericl** [comment] 2023-05-09 20:17
Thanks for reporting this. This will be addressed when we integrate streaming data with Train; right now it is not supported via the `datasets` config.

However, you can work around this by creating the dataset within your trainer / train loop function itself.

**Comment by ericl** [comment] 2023-05-31 01:17
Duplicate of https://github.com/ray-project/ray/issues/32605

**Closed by ericl** 2023-05-31 01:17 UTC
Labels: bug, P1, train, air, data, Ray 2.6
