### ISSUE TITLE
[Bug] Ray Workflow in c:\ray does not work on windows

### ISSUE THREAD

**Issue by yonil7** [ray-project/ray#22640] opened 2022-02-24 22:29 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

```python
from ray import workflow
workflow.init(r'c:\ray')
```
Fail with the following exception:

> File "C:\miniconda3\...\lib\site-packages\ray\workflow\storage\__init__.py", line 50, in create_storage
>     raise ValueError(f"Invalid url: {storage_url}")
> ValueError: Invalid url: c:\ray
> 
(`'c:/ray'` and `r'file:///c:\ray'` also fail)

### Versions / Dependencies

ray-1.10.0

### Reproduction script

see above

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment] 2022-02-24 22:51
cc @iycheng is workflow currently supported at Windows?

**Comment by pcmoritz** [comment] 2022-03-08 17:47
@mattip or @czgdp1807 This is probably a simple path error, do you want to look into fixing it?

**Comment by czgdp1807** [comment] 2022-03-10 06:08
Let me try to repro this on my Azure VM.

**Comment by pcmoritz** [comment] 2022-03-10 06:38
@czgdp1807 Thanks for checking, how much work do you think it would be to fix it/can you look into that?

**Comment by czgdp1807** [comment] 2022-03-10 06:39
The reason I am able to figure out so far. The problem is that `urllib.parse` is used internally to parse any path provided as input to `workflow.init`. Now, since you are passing, `c:\ray`, `urllib.parse` splits it into `c` and `ray`. So, `scheme='c'` and `path=ray`. There is no case handled for `c` scheme in `create_storage`, so it fails with a `ValueError`. If I pass linux styled path i.e., `/ray`, then the `workflow.init` works. See outputs below,

Case - 1: With `c:\ray`,

```python
Python 3.8.11 (default, Aug  6 2021, 09:57:55) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ray import workflow
>>> workflow.init(r'c:\ray')
parsed_url:  ParseResult(scheme='c', netloc='', path='\\ray', params='', query='', fragment='')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\gagan\ray_project\ray\python\ray\workflow\api.py", line 58, in init
    storage = storage_base.create_storage(storage)
  File "c:\users\gagan\ray_project\ray\python\ray\workflow\storage\__init__.py", line 52, in create_storage
    raise ValueError(f"Invalid url: {storage_url}")
ValueError: Invalid url: c:\ray
```

Case - 2: With `/ray`,

```python
Python 3.8.11 (default, Aug  6 2021, 09:57:55) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ray import workflow
>>> workflow.init(r'/ray')
parsed_url:  ParseResult(scheme='', netloc='', path='/ray', params='', query='', fragment='')
2022-03-10 06:32:48,642 INFO services.py:1477 -- View the Ray dashboard at http://127.0.0.1:8265
2022-03-10 06:33:06,564 INFO workflow_access.py:399 -- Initializing workflow manager...
```

Possible fixes,

1. Always default to `return FilesystemStorageImpl(parsed_url.path)` whenever we encounter an unknown scheme.
2. Just add a case for windows paths i.e., `scheme='c'`. Specifically change, `if parsed_url.scheme == "file" or parsed_url.scheme == "":` to `if parsed_url.scheme == "file" or parsed_url.scheme == "" or parsed_url.scheme == 'c':`.
3. Raise an error that the scheme `c` is unkown. Add a potential info in the error message that this might be due to Windows paths having c as prefix.

**Comment by mattip** [comment] 2022-03-10 07:03
There is an [issue on python](https://bugs.python.org/issue42215) about this with no comments. Whatever the solution, it should be generalized to any arbitrary drive name `c`, `D`, `Z`, ... A variation on (1) might be to reprocess anything with an invalid scheme by prefixing with `file://` or `file:///` which would turn them into valid URIs:
```
>>> urlparse(r'file://c:\home')
ParseResult(scheme='file', netloc='c:\\home', path='', params='', query='', fragment='')
>>> urlparse(r'file:///c:\home')
ParseResult(scheme='file', netloc='', path='/c:\\home', params='', query='', fragment='')
>>> urlparse(r'file:///tmp/ray')
ParseResult(scheme='file', netloc='', path='/tmp/ray', params='', query='', fragment='')
```

**Comment by yonil7** [comment] 2022-03-10 07:30
Info that might help on Windows paths/URLs:
* In windows, an **_absolute_** path must start with the drive letter followed by colon (`c:` /  `d:` / ...)
* In windows, `/tmp`, `/`, `\tmp`, `\` are a kind of a **_relative_** paths - `\` always points to the root of the **current** drive (the drive of the **current** working directory)
* When I open a local pdf file in chrome on windows the URL looks like: `file:///C:/tmp/myfile.pdf` (with 3 slashes - first 2 separate the `schema` URL component from the `hostname` and the next slash separate the `hostname` from the URL `path` component)

**Comment by pcmoritz** [comment] 2022-03-15 16:27
@czgdp1807 Let's do 3, and ask the user to add `file:///` in front of the path (only on windows)

**Comment by yonil7** [comment] 2022-03-16 14:34
As I understand, this fix just change the error message wording but does not fix this issue.

There are 4 different types of error here:
1.
```python
#using regular windows path:
workflow.init(r'c:\ray') #or workflow.init(r'c:/ray')
```
Fail with the following exception:

> File "C:\miniconda3\...\lib\site-packages\ray\workflow\storage\__init__.py", line 50, in create_storage
>     raise ValueError(f"Invalid url: {storage_url}")
> ValueError: Invalid url: c:\ray
> 

2.
```python
#using URL with 3 slashes (valid URL):
workflow.init(r'file:///c:\ray') #or workflow.init(r'file:///c:/ray')
```
Fail with the following exception:

>   rwf.init(r'file:///c:\ray')
>   File "C:\miniconda3\...\lib\site-packages\ray\workflow\api.py", line 53, in init
>     storage = storage_base.create_storage(storage)
>   File "C:\miniconda3\...\lib\site-packages\ray\workflow\storage\__init__.py", line 35, in create_storage
>     return FilesystemStorageImpl(parsed_url.path)
>   File "C:\miniconda3\...\lib\site-packages\ray\workflow\storage\filesystem.py", line 131, in __init__
>     self._workflow_root_dir.mkdir(parents=True)
>   File "C:\miniconda3\...\lib\pathlib.py", line 1288, in mkdir
>     self._accessor.mkdir(self, mode)
> OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '\\c:\\ray'
> 

3.
```python
#using URL with 2 slashes (invalid URL):
workflow.init(r'file://c:\ray')
```
Does not fail but creates the storage in the current working directory.

4.
```python
#using URL with 2 slashes (invalid URL):
workflow.init(r'file://c:/ray')
```
Creates the storage directory always under the current drive (e.g. if the current working drive is `d:`, it will create `d:\ray` instead of `c:\ray`), then fail with the following exception:

>  pid=23212) 2022-03-16 16:17:32,834	ERROR worker.py:85 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::_resume_workflow_step_executor() (pid=18472, ip=127.0.0.1)
>  pid=23212)   File "C:\miniconda3\...\lib\site-packages\ray\workflow\recovery.py", line 111, in _construct_resume_workflow_from_step
>  pid=23212)     raise WorkflowStepNotRecoverableError(step_id)
>  pid=23212) ray.workflow.recovery.WorkflowStepNotRecoverableError: Workflow step[id=__main__.foo] is not recoverable
> 

IMHO, ray Windows users should be able to just pass simple Windows paths (that are not URLs) such as: `workflow.init(r'c:\ray')` for working localy.

**Comment by czgdp1807** [comment] 2022-03-16 14:41
> Does not fail but creates the storage in the current working directory.

What should be the desired behaviour instead? Should it create a folder in `C:\` drive with the name of `ray`?

**Comment by yonil7** [comment] 2022-03-16 14:56
> Does not fail but creates the storage in the current working directory.

means if I run the script in `c:\my\other\folder\` it will just use this folder as the workflow storage. (instead of in `c:\ray` folder)

> Creates the storage directory always under the current drive (e.g. if the current working drive is d:, it will create d:\ray instead of c:\ray)

This (case 4) is also faulty behavior. if I run the script from `d:\my\other\folder\` my workflow storage folder will be `d:\ray` and running the exact same script from `e:\my\other\folder\` causes the storage folder to be `e:\ray` (and after it there is `WorkflowStepNotRecoverableError` exception)

In terms of requirements, I think a simple, regular Windows path such as `c:\ray` should just work.

**Comment by czgdp1807** [comment] 2022-03-16 15:10
Sure. I will look into this. Thanks for specifying your requirements in detail.

**Comment by yonil7** [comment] 2022-03-22 16:44
@czgdp1807, regarding: "_Changing c: to d: results no directory created anywhere_", this happens because when you use path as `r'file://d:/workflow_dir'`, the `d:` part is dropped (as part of taking only the path component of this URL) and then it call windows to create `'/workflow_dir'` - in windows this is a *relative* path starting from the *current* working drive. (so the directory will be created in `c:` instead of in `d:`)

**Comment by yonil7** [comment] 2022-03-23 09:57
1. I'm not sure such change wont break this functionality for linux (e.g. if in linux we pass `'file://myserver/path/in/server'`)
2. I'm not sure its not a bug in Pyhon `urllib` that `netloc='d:'` (`netloc` should be the hostname of the machine - if its a bug in `urllib` we better not depend on its faulty output)
3. Its would be clearer for windows users to be able to pass just a path such as `'c:/workflow_dir'` without the `'file://'` prefix when working locally.

**Comment by czgdp1807** [comment] 2022-03-23 09:59
Most probable case is either 1 or 2. Doing 3 will require special case heuristics (which may not robust). 

> 1. I'm not sure such change wont break this functionality for linux (e.g. if in linux we pass `'file://myserver/path/in/server'`)

I think it shouldn't. `netloc` would be just empty. I don't have a linux system so can't say for sure. @mattip Can you test this out?

**Comment by yonil7** [comment] 2022-03-23 10:40
We can add code such as this in the beginning of `create_storage()` function:
```python
    if not is_url(storage_url):
        return FilesystemStorageImpl(storage_url) #if the passed string is not a URL, its asummed to be a path and its passed as is
```
For checking if a string is a URL or not, we can use one of the suggested ways here: https://stackoverflow.com/questions/7160737/how-to-validate-a-url-in-python-malformed-or-not

This way we don't relay on `urlparse()` to handle path properly. (as path is not a URL we should no pass it to `urlparse()` and expect it to parse it correctly)

**Comment by yonil7** [comment] 2022-08-02 05:09
Is there any update on this?

**Comment by mattip** [comment] 2022-08-05 11:27
`workflow.init(storage=path)` is no longer valid, the `storage=` kwarg is now part of `ray.init`. Searching through the PRs, this was changed in #24120. A minimum reproducer now uses `ray.init(storage=...)` and successfully parses the storage path. @yonil7 could you confirm that the nightly builds work as desired?

<details><summary>Minimum reproducer</summary>

```
from ray import workflow
import ray

@ray.remote
def one() -> int:
    return 1

@ray.remote
def add(a: int, b: int) -> int:
    return a + b

dag = add.bind(100, one.bind())

# Run the workflow until it completes and returns the output
ray.init(storage=r"c:\temp\storage")
assert workflow.run(dag) == 101
# Or you can run it asynchronously and fetching the output via 'ray.get'
output_ref = workflow.run_async(dag)
assert ray.get(output_ref) == 101
```

<details>

**Comment by mattip** [comment] 2022-10-20 18:15
Closing as fixed in master.

**Closed by mattip** 2022-10-20 18:15 UTC
Labels: bug, P3, QS, fixed-in-master
