### ISSUE TITLE
[core] `ray.get_runtime_context.get_assigned_resources()` does not return raw resources in PG

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#28814] opened 2022-09-27 15:32 UTC
### What happened + What you expected to happen

When `ray.get_runtime_context.get_assigned_resources()` is called in a task scheduled within a placement group, it returns the `CPU_group_xxx` and `CPU_group_n_xxx` resources, but not the regular `CPU` resource. This makes it hard to identify how many CPUs are allocated to the current task.

Expected behavior: Also return e.g. `"CPU": 2`.

### Versions / Dependencies

Latest master

### Reproduction script

```
import ray


@ray.remote(num_cpus=2)
def get_assigned_resources():
    return ray.get_runtime_context().get_assigned_resources()


ray.init(num_cpus=4)

res1 = ray.get(get_assigned_resources.remote())
assert res1.get("CPU") == 2, res1

pg = ray.util.placement_group([{"CPU": 2}])

res2 = ray.get(get_assigned_resources.options(placement_group=pg).remote())
assert res2.get("CPU") == 2, res2
# AssertionError: {'CPU_group_e765be422c439de2cd263c5d9d1701000000': 2.0}
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by larrylian** [comment] 2022-09-29 06:13
This is caused by the PG mechanism. I will see whether to optimize this problem later, but it will not be changed for the time being.

You are now just to count the resource size of the application. The current problem can be solved by processing the string "CPU_group_e765be422c439de2cd263c5d9d1701000000"

**Comment by rickyyx** [comment] 2022-12-10 00:13
Hey @larrylian could I assign this to you if you plan to take it on? Let me know if you need help and we will find someone else.

**Comment by larrylian** [comment] 2022-12-11 06:13
@rickyyx  @krfricke  This problem is not difficult to fix. The main question is whether the behavior of this interface can be changed in this way.

@scv119 @rkooo567  What do you think? Can this interface be changed like this? Or add another node?

**Comment by rkooo567** [comment] 2022-12-12 23:54
For any user faceing APIs, we shouldn't expose resources like CPU_group_e765be422c439de2cd263c5d9d1701000000, which is an implementation detail. I think @cadedaniel will look into fixing this...

**Comment by larrylian** [comment] 2023-02-21 02:54
@rkooo567   Since you has decided to change it like this, do you need me to fix it?

**Comment by larrylian** [comment] 2023-07-14 09:36
For reason:
> 1. For any user faceing APIs, we shouldn't expose resources like CPU_group_e765be422c439de2cd263c5d9d1701000000, which is an implementation detail 
> 2. #37384  OMP_NUM_THREADS not set correctly in placement group.

I will fix this issue. @scv119 @cadedaniel

**Comment by rkooo567** [comment] 2023-07-14 16:46
Thanks @larrylian !

@krfricke Is it not necessary we don't return any information regarding placement group btw?

**Closed** 2023-07-21 16:42 UTC
Labels: bug, dashboard, core, observability-ux, core-scheduler, P1.5
