### ISSUE TITLE
[release][CI] datasets_ingest_400G failed

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29098] opened 2022-10-05 22:49 UTC
### What happened + What you expected to happen

[Build failure ](https://buildkite.com/ray-project/release-tests-branch/builds/1092#0183a524-1ea8-4c7a-b3ff-0ccec829445f)

[Cluster ](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_87LZjb3qEvrk5hppdGaAkcHX?command-history-section=command_history)

Seems OOM kiiller related. 

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by matthewdeng** [comment] 2022-10-05 22:52
@clarng do you have any suggestions on how to handle this?

**Comment by c21** [comment] 2022-10-06 20:10
The test is passed now - https://buildkite.com/ray-project/release-tests-branch/builds/1080#0183906e-894e-4198-96aa-1450ed724066 . @clarng did you push any fix?

**Comment by clarng** [comment] 2022-10-12 17:25
Here are the 3 cluster instances 
[Oct 1 nightly ](https://buildkite.com/ray-project/release-tests-branch/builds/1080#0183906e-894e-4198-96aa-1450ed724066 ) workload finished in 42 minutes

[Oct 5 nightly] (https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_87LZjb3qEvrk5hppdGaAkcHX?command-history-section=command_history) workload failed after 11 minutes, seems due to OOM failure. The reason this regressed is most likely because we started enabling cgroup memory limit in anyscale, and in which case Ray started calculating memory usage based on cgroup stats, which had an issue where it was over-accounting, in which case it started killing workers pre-maturely and would cause the workload to fail. This is addressed by a [PR](https://github.com/ray-project/ray/pull/29103) that is merged on Oct 6 

[Oct 11 nightly] (https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_yZ43bBQ6AeVt26sWuM7nGmX8?command-history-section=command_history&drivers-section=runs) workload completed after 2 + hours, and in the logs / grafana we don't see OOM killing. We emit a counter when OOM kill happens and there isn't any [recorded](https://ec2-7c1kalm-17wvyib-0000-cust-mon.ray.aws-us-west-2-admin.anyscale-test-production.com/grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Cortex%22,%7B%22exemplar%22:true,%22expr%22:%22ray_memory_manager_worker_eviction_total%22,%22requestId%22:%22Q-5a17d159-72fa-4f52-b5cc-c86bad06c34a-0A%22%7D%5D). 

It looks like the test is now failing due to timeout because the workload took longer to complete. @c21  any idea what might have changed?

**Comment by c21** [comment] 2022-10-13 22:21
Thansk @clarng for checking out. The [latest failure of nightly test](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_1NhGqHVxAMGxz1JiuPUNnkUb?command-history-section=command_history) seems not related to OOM killer. I am looking.

**Comment by c21** [comment] 2022-10-14 16:26
The nightly test is not failing, but time out consistently. Latest nightly test - https://buildkite.com/ray-project/release-tests-branch/builds/1113#0183d365-cc5e-40c7-b39a-497eda8a3ea8 , and cluster - https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_pZS39esQXtfmYiX7zkhxbBpy?command-history-section=command_history .

It seems trainer was kept running, didn't see any exception. @jiaodong do you have any insight what is wrong here? Thanks.

**Comment by jiaodong** [comment] 2022-10-14 18:44
i didn't spot anything obviously wrong there, it's consistently producing training metrics like

```
[2m[36m(RayTrainWorker pid=2480)[0m training batch [38400] loss: -4.352588027487322e+18
[2m[36m(RayTrainWorker pid=2480)[0m time breakdown per_batch_time: [0.16144504808751883]
[2m[36m(RayTrainWorker pid=2480)[0m per_batch_train_time 0.01586770584197042
[2m[36m(RayTrainWorker pid=2480)[0m training batch [38500] loss: -4.401158953644327e+18
[2m[36m(RayTrainWorker pid=2480)[0m time breakdown per_batch_time: [0.16109630701210662]
[2m[36m(RayTrainWorker pid=2480)[0m per_batch_train_time 0.015867278135051042
```

@c21 that do you see from previous passing runs on this, does this metrics like `per_batch_time` match other passing ones ?

**Comment by c21** [comment] 2022-10-14 20:31
Looks like some regression after 10/06. Bisecting in https://github.com/ray-project/ray/compare/fd0148878...1bd8ab9b .

**Comment by rickyyx** [comment] 2022-10-17 20:23
@c21 any updates on this?

**Comment by clarkzinzow** [comment] 2022-10-17 23:56
@c21 @jiaodong We should note that the pipelining implementation changed (on 10/07) from [a manual windowed per-epoch shuffling](https://github.com/ray-project/ray/blob/75a0c491e8ee4009e8828081059cfc98543c4d51/release/nightly_tests/dataset/ray_sgd_runner.py#L206-L224) to the `ray.data.read_parquet().repeat().random_shuffle_each_epoch()` implementation, among other things, in this PR: https://github.com/ray-project/ray/commit/d99eff919bf785f911e4eebc87ddc4960344a139#diff-dbde3dd6084228c8dba884de1774f42d8c25c8a6ef9859971d9239410339c973

The general port from the old `Trainer` to AIR could possibly be the culprit.

**Comment by rickyyx** [comment] 2022-10-18 17:07
Most [recent failure ](https://buildkite.com/ray-project/release-tests-branch/builds/1129#0183e820-cbcf-4edb-951e-73a54dd5829a)on release branch

**Comment by clarng** [comment] 2022-10-18 17:15
looks like status of the command was killed, and not specifically about the workload that is running? Is this an infra issue?

**Comment by c21** [comment] 2022-10-18 18:57
We are debugging with product team now. Looks like same commit which was running successfully, is failing now. So not seem an issue with a specific commit.

**Comment by c21** [comment] 2022-10-18 20:09
FYI looks like a product issue after Chris Wong tested on an older version of product. He is investigating.

**Comment by ckw017** [comment] 2022-10-18 22:57
Note: I've been bisecting on product versions and its working on all of them. Including versions after 10/07.

**Comment by ckw017** [comment] 2022-10-18 23:38
I suspect this is not a product infrastructure issue. Was given these two examples:
* [passing](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_Yz6mBXVxFMbkPCXE9BD5tvrk?command-history-section=command_history)
* [failling](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_PMU7MfTAJLXiMaVVBwCVUpAr?command-history-section=command_history)

Using the same ray image `fd0148878d9b13449f708ae521d9bb1678c69b10`. However they're running different versions on the test

**Comment by c21** [comment] 2022-10-19 16:39
Thanks @ckw017, after bisecting I found https://github.com/ray-project/ray/commit/d99eff919bf785f911e4eebc87ddc4960344a139 is the commit causing test regression here.
* passing (before this commit) - https://buildkite.com/ray-project/release-tests-branch/builds/1133
* failing (with this commit) - https://buildkite.com/ray-project/release-tests-branch/builds/1134

@Yard1 could you help take a look? Thanks.

**Closed** 2022-12-09 21:42 UTC
Labels: bug, testing, train
