### ISSUE TITLE
[rllib] Possible breaking API changes in nightly for custom algorithms

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#12509] opened 2020-11-30 22:59 UTC
Due to the enabling by default of the trajectory view API (which is needed to fully support advanced / attention-based custom models), it is possible that some custom algorithms break (unintentionally).

Please post here if you run into any into any breakages, and we will try to resolve them.

**Comment by sven1977** [comment] 2020-12-09 12:03
What seems to break in 1.0.1 (but not anything larger than this version: 1.0.1post1 or 1.2) is when we have a custom RNN-based model that overrides ModelV2's `get_initial_state()`.
You would receive an empty list for your internal states in the model (forward) calls.

As workarounds, do one of the following:
- set `_use_trajectory_view_api=False` in your main config dict.
- OR: add the view requirements instructions to your model's constructor, similar to how it's done in the example RNN models (rllib/examples/models/rnn_model.py):
Example for a 2-state (c and h states) LSTM model (this goes into the model's c'tor).
```
        # Add state-ins to this model's view.
        for i in range(2):
            self.inference_view_requirements["state_in_{}".format(i)] = \
                ViewRequirement(
                    "state_out_{}".format(i),
                    shift=-1,
                    space=Box(-1.0, 1.0, shape=(self.lstm_state_size,)))
```

**Comment by sven1977** [comment] 2020-12-11 08:45
Another issue is that the environment's info dict is not present anymore in the postprocessing or train_batches.

The only workaround here is:
Set `_use_trajectory_view_api=False` in your Trainer config dict.

This bug was also fixed in all versions >1.0.1

**Comment by yangysc** [comment] 2020-12-22 02:16
Hi, Eric @ericl, I want to report a bug in the example of the recurrent version of autoregressive_action_model. I think it's due to the new trajectory view api change. Could you take a look? I think this example is very interesting since you first mentioned it last year, and I don't know how to handle this bug now. I made a recurrent version of it, and it errors using the lastest rllib (1.2.0.dev0)

```
C:\ProgramData\Anaconda3\envs\test\python.exe "D:\Program Files\JetBrains\PyCharm 2020.3\plugins\python\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 59869 --file C:/Users/yangs/Downloads/Compressed/ray/ray-master/rllib/examples/rnnautoregressive_action_dist.py
Connected to pydev debugger (build 203.5981.165)
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\test\lib\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2020-12-22 09:38:48,711	INFO services.py:1169 -- View the Ray dashboard at http://127.0.0.1:8265
2020-12-22 09:38:59,148	INFO trainer.py:631 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
C:\ProgramData\Anaconda3\envs\test\lib\site-packages\gym\logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
2020-12-22 09:39:19,346	ERROR syncer.py:72 -- Log sync requires rsync to be installed.
2020-12-22 09:39:19,353	ERROR trial_runner.py:607 -- Trial PPO_CorrelatedActionsEnv_7627b_00000: Error processing event.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\tune\trial_runner.py", line 519, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\tune\ray_trial_executor.py", line 497, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\worker.py", line 1386, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::PPO.train() (pid=21728, ip=192.168.1.118)
  File "python\ray\_raylet.pyx", line 434, in ray._raylet.execute_task
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\worker.py", line 173, in reraise_actor_init_error
    raise self.actor_init_error
  File "python\ray\_raylet.pyx", line 468, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 471, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 475, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 427, in ray._raylet.execute_task.function_executor
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\function_manager.py", line 556, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\rllib\agents\trainer_template.py", line 107, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\rllib\agents\trainer.py", line 480, in __init__
    super().__init__(config, logger_creator)
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\tune\trainable.py", line 96, in __init__
    self.setup(copy.deepcopy(self.config))
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\rllib\agents\trainer.py", line 644, in setup
    self._init(self.config, self.env_creator)
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\rllib\agents\trainer_template.py", line 134, in _init
    self.workers = self._make_workers(
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\rllib\agents\trainer.py", line 715, in _make_workers
    return WorkerSet(
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 79, in __init__
    remote_spaces = ray.get(self.remote_workers(
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\worker.py", line 1386, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::RolloutWorker.foreach_policy() (pid=21728, ip=192.168.1.118)
  File "python\ray\_raylet.pyx", line 434, in ray._raylet.execute_task
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\worker.py", line 173, in reraise_actor_init_error
    raise self.actor_init_error
  File "python\ray\_raylet.pyx", line 434, in ray._raylet.execute_task
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\worker.py", line 173, in reraise_actor_init_error
    raise self.actor_init_error
  File "python\ray\_raylet.pyx", line 468, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 471, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 475, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 427, in ray._raylet.execute_task.function_executor
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\function_manager.py", line 556, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 467, in __init__
    self.policy_map, self.preprocessors = self._build_policy_map(
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 1087, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\rllib\policy\torch_policy_template.py", line 249, in __init__
    self._initialize_loss_from_dummy_batch(
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\rllib\policy\policy.py", line 652, in _initialize_loss_from_dummy_batch
    self._loss(self, self.model, self.dist_class, train_batch)
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\rllib\agents\ppo\ppo_torch_policy.py", line 47, in ppo_surrogate_loss
    logits, state = model.from_batch(train_batch, is_training=True)
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\rllib\models\modelv2.py", line 249, in from_batch
    ret = self.__call__(input_dict, states, input_dict.get("seq_lens"))
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\rllib\models\modelv2.py", line 224, in __call__
    raise ValueError(
ValueError: Expected output shape of [None, 16], got torch.Size([4, 8, 16])
== Status ==
Memory usage on this node: 11.6/15.4 GiB
Using FIFO scheduling algorithm.
Resources requested: 3/16 CPUs, 0/0 GPUs, 0.0/2.78 GiB heap, 0.0/0.93 GiB objects
Result logdir: C:\Users\yangs\ray_results\PPO
Number of trials: 1/1 (1 RUNNING)
== Status ==
Memory usage on this node: 11.6/15.4 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/16 CPUs, 0/0 GPUs, 0.0/2.78 GiB heap, 0.0/0.93 GiB objects
Result logdir: C:\Users\yangs\ray_results\PPO
Number of trials: 1/1 (1 ERROR)
Number of errored trials: 1
+--------------------------------------+--------------+-----------------------------------------------------------------------------------------------------+
| Trial name                           |   # failures | error file                                                                                          |
|--------------------------------------+--------------+-----------------------------------------------------------------------------------------------------|
| PPO_CorrelatedActionsEnv_7627b_00000 |            1 | C:\Users\yangs\ray_results\PPO\PPO_CorrelatedActionsEnv_7627b_00000_0_2020-12-22_09-38-59\error.txt |
+--------------------------------------+--------------+-----------------------------------------------------------------------------------------------------+
python-BaseException
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm 2020.3\plugins\python\helpers\pydev\pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm 2020.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/yangs/Downloads/Compressed/ray/ray-master/rllib/examples/rnnautoregressive_action_dist.py", line 63, in <module>
    results = tune.run(args.run, stop=stop, config=config, verbose=1)
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ray\tune\tune.py", line 443, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [PPO_CorrelatedActionsEnv_7627b_00000])

```

The error is located in line 652 in the **ray\rllib\policy\policy.py** file when it tried to call the function **_initialize_loss_from_dummy_batch** , and I think it's due to the inconsistent batch size of handling rnn state using the new  trajectory view api.
```python
 def _initialize_loss_from_dummy_batch(
            self,
            auto_remove_unneeded_view_reqs: bool = True,
            stats_fn=None,
    ) -> None:
        """Performs test calls through policy's model and loss.

        NOTE: This base method should work for define-by-run Policies such as
        torch and tf-eager policies.

        If required, will thereby detect automatically, which data views are
        required by a) the forward pass, b) the postprocessing, and c) the loss
        functions, and remove those from self.view_requirements that are not
        necessary for these computations (to save data storage and transfer).

        Args:
            auto_remove_unneeded_view_reqs (bool): Whether to automatically
                remove those ViewRequirements records from
                self.view_requirements that are not needed.
            stats_fn (Optional[Callable[[Policy, SampleBatch], Dict[str,
                TensorType]]]): An optional stats function to be called after
                the loss.
        """
        sample_batch_size = max(self.batch_divisibility_req * 4, 32)
        self._dummy_batch = self._get_dummy_batch_from_view_requirements(
            sample_batch_size)
        input_dict = self._lazy_tensor_dict(self._dummy_batch)
        actions, state_outs, extra_outs = \
            self.compute_actions_from_input_dict(input_dict, explore=False)
        # Add all extra action outputs to view reqirements (these may be
        # filtered out later again, if not needed for postprocessing or loss).
        for key, value in extra_outs.items():
            self._dummy_batch[key] = np.zeros_like(value)
            if key not in self.view_requirements:
                self.view_requirements[key] = \
                    ViewRequirement(space=gym.spaces.Box(
                        -1.0, 1.0, shape=value.shape[1:], dtype=value.dtype))
        batch_for_postproc = UsageTrackingDict(self._dummy_batch)
        batch_for_postproc.count = self._dummy_batch.count
        self.exploration.postprocess_trajectory(self, batch_for_postproc)
        postprocessed_batch = self.postprocess_trajectory(batch_for_postproc)
        seq_lens = None
        if state_outs:
            B = 4  # For RNNs, have B=4, T=[depends on sample_batch_size]
            i = 0
            while "state_in_{}".format(i) in postprocessed_batch:
                postprocessed_batch["state_in_{}".format(i)] = \
                    postprocessed_batch["state_in_{}".format(i)][:B]
                if "state_out_{}".format(i) in postprocessed_batch:
                    postprocessed_batch["state_out_{}".format(i)] = \
                        postprocessed_batch["state_out_{}".format(i)][:B]
                i += 1
            seq_len = sample_batch_size // B
            seq_lens = np.array([seq_len for _ in range(B)], dtype=np.int32)
        # Wrap `train_batch` with a to-tensor UsageTrackingDict.
        train_batch = self._lazy_tensor_dict(postprocessed_batch)
        if seq_lens is not None:
            train_batch["seq_lens"] = seq_lens
        train_batch.count = self._dummy_batch.count
        # Call the loss function, if it exists.
        if self._loss is not None:
            self._loss(self, self.model, self.dist_class, train_batch)
```


Why do we have to require the  **seq_len = sample_batch_size // B** ? Since the default batch size value is 32, so seq_len is 8 when B is set to 4 (why is B set to 4?) , So there is an error when the policy tries to call the loss, since the obs in train_batch is reshape to [4, 8, feat_dim], instead of [32, feat_dim].   

 When I set the B to 1 instead of 4 in line 634 in policy.py file and squeeze the dimension [1, 32, feat_dim] to [32, feat_dim] ,  it still would error when it calculates the loss in future. I am a little confused how to use the custom recurrent autoregressive models. 


To reproduce this, I uploaded the recurrent version of autoregresive_action [example](https://drive.google.com/drive/folders/1sgCBMyCS9GehorMaz97RyG7qe6wyiEPH?usp=sharing).  The rnn model version is defined as follows:
```python
class TorchRNNAutoregressiveActionModel(TorchRNN, nn.Module):
    """PyTorch version of the AutoregressiveActionModel above."""

    def __init__(self,
                 obs_space,
                 action_space,
                 num_outputs,
                 model_config,
                 name,
                 fc_size=16,
                 lstm_state_size=256):
        nn.Module.__init__(self)
        super().__init__(obs_space, action_space, num_outputs, model_config,
                         name)

        if action_space != Tuple([Discrete(2), Discrete(2)]):
            raise ValueError(
                "This model only supports the [2, 2] action space")

        # Output of the model (normally 'logits', but for an autoregressive
        # dist this is more like a context/feature layer encoding the obs)
        self.context_layer = SlimFC(
            in_size=obs_space.shape[0],
            out_size=num_outputs,
            initializer=normc_init_torch(1.0),
            activation_fn=nn.Tanh,
        )

        # V(s)
        self.value_branch = SlimFC(
            in_size=num_outputs,
            out_size=1,
            initializer=normc_init_torch(0.01),
            activation_fn=None,
        )

        # P(a1 | obs)
        self.a1_logits = SlimFC(
            in_size=num_outputs,
            out_size=2,
            activation_fn=None,
            initializer=normc_init_torch(0.01))

        class _ActionModel(nn.Module):
            def __init__(self):
                nn.Module.__init__(self)
                self.a2_hidden = SlimFC(
                    in_size=1,
                    out_size=16,
                    activation_fn=nn.Tanh,
                    initializer=normc_init_torch(1.0))
                self.a2_logits = SlimFC(
                    in_size=16,
                    out_size=2,
                    activation_fn=None,
                    initializer=normc_init_torch(0.01))

            def forward(self_, ctx_input, a1_input):
                a1_logits = self.a1_logits(ctx_input)
                a2_logits = self_.a2_logits(self_.a2_hidden(a1_input))
                return a1_logits, a2_logits

        # P(a2 | a1)
        # --note: typically you'd want to implement P(a2 | a1, obs) as follows:
        # a2_context = tf.keras.layers.Concatenate(axis=1)(
        #     [ctx_input, a1_input])
        self.action_module = _ActionModel()

        self.obs_size = get_preprocessor(obs_space)(obs_space).size
        self.fc_size = fc_size
        self.lstm_state_size = lstm_state_size
        self.fc1 = nn.Linear(self.obs_size, self.fc_size)
        self.lstm = nn.LSTM(
            self.fc_size, self.lstm_state_size, batch_first=True)
        self.action_branch = nn.Linear(self.lstm_state_size, fc_size)
        self.value_branch = nn.Linear(self.lstm_state_size, 1)
        # Holds the current "base" output (before logits layer).
        self._features = None

    @override(ModelV2)
    def get_initial_state(self):
        # TODO: (sven): Get rid of `get_initial_state` once Trajectory
        #  View API is supported across all of RLlib.
        # Place hidden states on same device as model.
        h = [
            self.fc1.weight.new(1, self.lstm_state_size).zero_().squeeze(0),
            self.fc1.weight.new(1, self.lstm_state_size).zero_().squeeze(0)
        ]
        return h

    @override(TorchRNN)
    def forward(self, input_dict, state, seq_lens):
        x = self.context_layer(input_dict["obs"])
        if isinstance(seq_lens, np.ndarray):
            seq_lens = torch.Tensor(seq_lens).int()

        bs = input_dict["obs"].size(0)
        max_seq_len = bs // seq_lens.shape[0]
        self.time_major = self.model_config.get("_time_major", False)
        x = add_time_dimension(
            x,
            max_seq_len=max_seq_len,
            framework="torch",
            time_major=self.time_major,
        )
        self._features, [h, c] = self.lstm(
            x, [torch.unsqueeze(state[0], 0),
                torch.unsqueeze(state[1], 0)])
        self._features = self._features.squeeze(1)
        # if torch.isnan(self._features).any().item():
        #     print('na')
        action_out = self.action_branch(self._features)
        return action_out, [torch.squeeze(h, 0), torch.squeeze(c, 0)]

    @override(ModelV2)
    def value_function(self):
        assert self._features is not None, "must call forward() first"
        return torch.reshape(self.value_branch(self._features), [-1])
```

Thanks in advance!

**Comment by yangysc** [comment] 2020-12-22 13:08
@sven1977 Hi, Sven,  may I bother you also  taking a look for this issue? It's basically a recurrent version of the autoregressive example. And it cannot work with the latest rllib (1.2.0.dev0). Thanks

**Comment by 51616** [comment] 2020-12-22 15:28
Is there a doc for the `trajectory_view_api`? I'm kinda confuse how to handle this at the moment.

**Comment by simonsays1980** [comment] 2022-07-09 14:28
@gjoliver This can be closed I think

**Comment by gjoliver** [comment] 2022-07-14 17:06
@simonsays1980 thanks for the heads up.

**Closed by gjoliver** 2022-07-14 17:06 UTC
Labels: rllib
