### ISSUE TITLE
[Microbenchmark] n_n_actor_calls_with_arg_async regression

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#17588] opened 2021-08-04 22:19 UTC
### What is the problem?

it looks like `n_n_actor_calls_with_arg_async` has about 50% regression over the quarter. As you can see from the attached photo, it didn't happen gradually, but at one point. We should bisect to figure out what PR causes this. 

### Reproduction (REQUIRED)
Run microbenchmark 

<img width="1679" alt="Screen Shot 2021-08-04 at 10 20 06 AM" src="https://user-images.githubusercontent.com/18510752/128262574-994113eb-16c3-491f-b931-0eae176141cf.png">

**Comment by ericl** [comment] 2021-09-20 18:41
Ping on this? IIRC the cause of the first was PullManager revamp (expected). What about the cause of the second drop?

**Comment by rkooo567** [comment] 2021-09-20 20:38
First root cause: Pull manager revamp (expected)
Second root cause: OBOD update batching (will discuss with @scv119 if we will revert or fix this sprint once I come back). It looks like every test is not impacted but 1tb shuffle 5000 partitions (seems to be about 20% slower after this PR) and this microbenchmark test.

**Comment by ericl** [comment] 2021-09-21 01:40
Got it. I think we're ok to close this issue then, now that we understand the root cause. If the performance of this microbenchmark becomes relevant in future workloads, we now know where to look.

**Closed by ericl** 2021-09-21 01:40 UTC
Labels: bug, regression, P1
