### ISSUE TITLE
[core] A test utility library for injecting failure for Ray applications

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#17079] opened 2021-07-14 16:28 UTC
### Describe your feature request

It could be very nice to be able to do ray.simulate_node_unresponsive(node).

There are various failures that we should consider supporting, such as:

* Memory failures
* OS failures (thread limit, port limit, file limit)
* Network failures

cc @wuisawesome @rkooo567

**Comment by wuisawesome** [comment] 2021-07-14 17:12
Duplicate of #15433

**Closed by wuisawesome** 2021-07-14 17:12 UTC
Labels: enhancement

**Comment by richardliaw** [comment] 2021-07-14 17:28
nice, thanks for the pointer
