### ISSUE TITLE
[k8s] SIGTERM is sent to the head node when GCS is busy.

### ISSUE THREAD

**Issue by spolcyn** [ray-project/ray#26299] opened 2022-07-05 16:15 UTC
### What happened + What you expected to happen

We have an embarrassingly parallel workload that is periodically (every ~15-30m) resulting in the Ray process crashing and maxed out GCS CPU usage.

We'd expect that we can scale across as many CPUs as we can provide, up to the scalability envelope, and that Ray wouldn't crash (or that Ray would crash with a useful error message about which resource we need to provide more of).

Based on our understanding of the scalability envelope, we shouldn't have any problem running ~5000 tasks at a time across hundreds of nodes.

Setup:
1. Ray on k8s using `ray-operator` with autoscaling
2. Tasks use 1 CPU core each. We have 1K running at a time (as tasks finish, new ones are sent), though we've tried different #'s (higher & lower, from ~100 to ~10K) that also eventually result in Ray halting and restarting.
3. Each task takes 5-20 minutes, and the primary resource it uses is CPU with a network upload/download at the beginning and end.
4. Each worker node has 4 CPU cores, though we've tried larger numbers of cores (up to 48) to reduce the # of nodes that are created (crashes were still experienced)
5. Connecting via the Ray Client, though we've also tried Job Submission with the same result.

More context, error messages, and Grafana charts of CPU over time on the head node are in the Slack conversation: https://ray-distributed.slack.com/archives/CN2RGCHRR/p1656010978426509

### Versions / Dependencies

Python 3.9, Ray 1.13, Ubuntu 20.04

### Reproduction script

We can reliably reproduce it within our environment and we're happy to gather more data/try out new solutions as needed. Here's the suggested `perf` profile data:
[perf.data.gz] **EDIT: file removed for security reasons**

### Issue Severity

High: It blocks me from completing my task.

**Comment by spolcyn** [comment] 2022-07-06 20:51
@iycheng

**Comment by stephanie-wang** [comment] 2022-07-06 21:02
Thanks for filing this, @spolcyn! If possible, can you also attach a dump of the system logs from one of these runs? You can get this by running `ray cluster-dump` on the head node.

**Comment by stephanie-wang** [comment] 2022-07-06 21:10
Yes, that would be great, thanks!

**Comment by stephanie-wang** [comment] 2022-07-06 21:21
Could you also grab the same logs from one of the worker nodes?

**Comment by spolcyn** [comment] 2022-07-06 21:27
@stephanie-wang Sure, those worker nodes have been autoscaled down since the issues, but I can re-run and get the worker node logs.

**Comment by spolcyn** [comment] 2022-07-06 21:59
[worker-session.tar.gz](https://github.com/ray-project/ray/files/9058243/worker-session.tar.gz)

@stephanie-wang Here is the worker node session for a crashed session

**Comment by stephanie-wang** [comment] 2022-07-06 22:50
Thanks! Yes, it looks like the root cause is likely GCS failing under heavy load. From the worker's raylet.out file:
```
[2022-07-06 21:46:17,727 W 68 68] (raylet) gcs_client.cc:198: Unable to reach GCS at 20.10.30.245:6379. Failure: 14 failed to connect to all addresses
[2022-07-06 21:46:20,903 C 68 68] (raylet) node_manager.cc:170: This node has beem marked as dead.
*** StackTrace Information ***
    ray::SpdLogMessage::Flush()
    ray::RayLog::~RayLog()
    std::_Function_handler<>::_M_invoke()
    std::_Function_handler<>::_M_invoke()
    std::_Function_handler<>::_M_invoke()
    ray::rpc::ClientCallImpl<>::OnReplyReceived()
    std::_Function_handler<>::_M_invoke()
    EventTracker::RecordExecution()
    std::_Function_handler<>::_M_invoke()
    boost::asio::detail::completion_handler<>::do_complete()
    boost::asio::detail::scheduler::do_run_one()
    boost::asio::detail::scheduler::run()
    boost::asio::io_context::run()
    main
    __libc_start_main
```

@iycheng is it okay to assign this one to you?

**Comment by spolcyn** [comment] 2022-07-07 14:37
@stephanie-wang In the meantime, is there anything we can do to provide the GCS more resources, or ways we can architect differently to minimize the load on the GCS?

**Comment by scv119** [comment] 2022-07-15 01:53
@spolcyn one thing you can do is avoid jobs being scheduled on head node. you can achieve that by setting head node with 0 cpus.

**Comment by iycheng** [comment] 2022-07-15 20:22
```
[2022-07-06 21:46:20,903 C 68 68] (raylet) node_manager.cc:170: This node has beem marked as dead.
```

I actually see this multiple times. I think one issue is that when GCS is under high pressure, heartbeat is not processed well.

I'd prefer changing the heartbeat from pushing to pull, but before that I'm going to evaluating the bottleneck of the current method.

@spolcyn could you give this a try: setting the OS env `RAY_num_heartbeats_timeout=600` and see whether it can mitigate this issue?

**Comment by spolcyn** [comment] 2022-07-15 20:40
@iycheng Sure, we'll try that out -- is that timeout in seconds?

**Comment by spolcyn** [comment] 2022-07-18 20:50
@iycheng As an update:
1. The OS envvar didn't seem to change the overall performance -- it crashed in similar situations (though we noticed that dead nodes were marked dead less quickly, which resulted in some issues with workers thinking actors were alive when they weren't)
2. We were able to majorly reduce CPU usage by turning on the `RAY_log_to_stderr` envvar on our worker nodes, which removed log streaming to the head node -- the Ray dashboard seemed to take a lot of CPU with those.
3. In a different setup, we were running the GCS at 300% CPU usage without a crash (in that case, it was managing many Ray tasks and their results). This suggests to us the GCS may be a symptom, but not the cause of the crash.

**Comment by iycheng** [comment] 2022-07-19 19:32
Synced offline with @spolcyn and the root cause is about a SIGTERM sent from ray operator to the head node.

And the cluster is not backed by a storage, so GCS loses all the information of the raylet.

Then raylet exits since it's marked as dead by GCS (GCS doesn't recognize it).

Lower the priority to p1 given that it seems not a release blocker. Feel free to change it back.

**Comment by DmitriGekhtman** [comment] 2022-07-24 18:30
The operator attempts to extract resource information from the GCS by RPC.
I think this failure mode could happen if that request fails. That in turn could happen if the request times out due to high load on the GCS.

If you haven't tried this yet, I'd suggest also increasing the operator's resource requests.

The good news for Ray 2.0.0 is that the KubeRay operator does not share the same brittle design and should thus not experience this issue.

**Comment by DmitriGekhtman** [comment] 2022-11-19 17:09
The operator affected by this issue is deprecated and will be removed in Ray 2.2.0.

**Closed by DmitriGekhtman** 2022-11-19 17:09 UTC
Labels: bug, P1, infra
