### ISSUE TITLE
Huge memory usage from Ray's official docker images

### ISSUE THREAD

**Issue by MattEWeber** [ray-project/ray#16900] opened 2021-07-06 19:00 UTC
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

I just started working from a new PC and for some reason I'm seeing huge memory usage from Ray's official docker images. 
This is running with Linux kernel 5.10.42-1 docker version 20.10.7 and nothing configured aside from the usual docker user added to not run with sudo command.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

Running this simple command I reach my 32GB in a few seconds, without ever seeing Ray's dashboard url message
docker run rayproject/ray:1.4.1 python -c "import ray; ray.init()"  (same for 1.3 and 1.2 images)
Something is awfully wrong here... 
Something seems to be happening on the redis front, any ideas to look into?

```
docker run rayproject/ray:1.4.1 python -c "import ray; ray.init()"
^CTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 806, in init
    ray_params=ray_params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/node.py", line 230, in __init__
    self.start_head_processes()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/node.py", line 861, in start_head_processes
    self.start_redis()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/node.py", line 686, in start_redis
    port_denylist=self._ray_params.reserved_ports)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 883, in start_redis
    port_denylist=port_denylist)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 1074, in _start_redis_instance
    ulimit_n - redis_client_buffer)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/redis/client.py", line 1243, in config_set
    return self.execute_command('CONFIG SET', name, value)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 470, in read_response
    self.read_from_socket()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 427, in read_from_socket
    bufflen = recv_into(self._sock, self._buffer)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/redis/_compat.py", line 75, in recv_into
    return sock.recv_into(*args, **kwargs)
KeyboardInterrupt
```

**Comment by ijrsvt** [comment] 2021-07-07 17:45
Hmm, I was not able to reproduce this :(

**Comment by richardliaw** [comment] 2022-05-05 21:01
Closing this for now.

**Closed by richardliaw** 2022-05-05 21:01 UTC
Labels: bug, triage
