### ISSUE TITLE
[Serve]  Subsequent requests to crashed deployment result in error

### ISSUE THREAD

**Issue by Kepnu4** [ray-project/ray#47219] opened 2024-08-20 16:39 UTC
### What happened + What you expected to happen

If deployment crashes when subsequent calls will also fail until it gets restarted by `health_check_period_s` timer. 
I expect that subsequent call would hang until actor is restarted. 

### Versions / Dependencies

ray 2.34.0
Python 3.10.12
Ubuntu 22.04.4 LTS

### Reproduction script

```python
def create_worker():
    ray.init(num_cpus=1, num_gpus=0)
    serve.start(
        http_options={"host": "0.0.0.0"}
    )

    @serve.deployment(name="worker", health_check_period_s=3)
    class Worker:
        def __call__(self, request):
            number = request.query_params['number']
            if number == '0':
                # Crash: SIGSEGV
                import ctypes
                ctypes.string_at(0)
            return number

    serve.run(Worker.bind())

create_worker()

ret = requests.get("http://127.0.0.1:8000/worker?number=0", timeout=3)
print(f'Code {ret.status_code}: {ret.text}')
ret = requests.get("http://127.0.0.1:8000/worker?number=1", timeout=3)
print(f'Code {ret.status_code}: {ret.text}')
time.sleep(3)
ret = requests.get("http://127.0.0.1:8000/worker?number=1", timeout=3)
print(f'Code {ret.status_code}: {ret.text}')
```
Output:
```
Code 500: Internal Server Error
Code 500: Internal Server Error
(ProxyActor pid=2258692) ERROR:    ASGI callable returned without starting response.
(ProxyActor pid=2258692) ERROR:    ASGI callable returned without starting response.
(ServeController pid=2258548) WARNING 2024-08-20 16:27:37,094 controller 2258548 deployment_state.py:857 - Actor for Replica(id='0trtzeml', deployment='worker', app='default') crashed, marking it unhealthy immediately.
(ServeController pid=2258548) WARNING 2024-08-20 16:27:37,095 controller 2258548 deployment_state.py:2089 - Replica Replica(id='0trtzeml', deployment='worker', app='default') failed health check, stopping it.
(ServeController pid=2258548) INFO 2024-08-20 16:27:37,099 controller 2258548 deployment_state.py:2182 - Replica(id='0trtzeml', deployment='worker', app='default') is stopped.
(ServeController pid=2258548) INFO 2024-08-20 16:27:37,100 controller 2258548 deployment_state.py:1844 - Adding 1 replica to Deployment(name='worker', app='default').
(ServeController pid=2258548) ERROR 2024-08-20 16:27:37,110 controller 2258548 application_state.py:768 - The deployments ['worker'] are UNHEALTHY.
Code 200: 1
```

### Issue Severity

None

**Comment by edoakes** [comment] 2024-08-20 16:54
@Kepnu4 the health check timeout shouldn't isn't relevant here because the actor crash is detected quickly (you can test this by making the health check timeout very long and see that the behavior is the same).

The expected behavior here is that the first request that causes the crash fails and after that subsequent requests should indeed be queued (though it might be possible that 1-2 other requests fail depending on timing when the proxy detects the crash).

@zcin will try to repro and investigate

**Comment by zcin** [comment] 2024-08-20 17:22
@Kepnu4 I've confirmed this is reproducible on 2.34. Like @edoakes said, the expected behavior is that new requests will queue until a new replica is started when the controller health checks the dead replica. This is the case in master today, as we recently identified and fixed this exact issue; the fix will be released in Ray 2.36. You can test it out on the nightly wheel, or wait until 2.36 is released.

**Comment by Kepnu4** [comment] 2024-08-20 17:46
Thanks for the fast response, guys.
@zcin, I've tested it with the nightly build, and it works as you mentioned.

I'm curious, why does the proxy take time to detect that the actor has died? It returns an error on the first request, so it should know long before the second request that the actor has died.
If this is the expected behavior, how should it be handled? I originally encountered this issue when calling `handle.remote()` from another deployment. Should I manually retry it if it fails due to a dead actor?

**Closed** 2024-09-12 01:43 UTC
Labels: bug, P0, serve

**Comment by zcin** [comment] 2024-09-16 18:23
@Kepnu4 starting in Ray 2.37, the proxy will be able to detect the actor has died on the very next request. You should be able to rerun your repro script and it should work.
