### ISSUE TITLE
 Initializing cluster on SLURM causes "we can not found the matched Raylet address" warning

### ISSUE THREAD

**Issue by import-antigravity** [ray-project/ray#17491] opened 2021-08-02 00:37 UTC
### What is the problem?

Running Ray 1.5.1

### Reproduction (REQUIRED)

I'm using the following SLURM script, which is basically copypasted from the documentation:

```
#!/bin/bash
#SBATCH --job-name="experiment"
#SBATCH --output=experiment.out
#SBATCH -N 5
#SBATCH --mem=32gb
#SBATCH --tasks-per-node=1
#SBATCH -p class -C gpu2080
#SBATCH --gres=gpu:2
#SBATCH --cpus-per-task=8
#SBATCH --gpus-per-task=2
#SBATCH --time=36:00:00


echo "Loading modules..."

module swap intel gcc
module load cuda/10.1

source ~/miniconda3/etc/profile.d/conda.sh
conda activate [mycondaenv]


# __doc_head_address_start__

# Getting the node names
nodes=$(scontrol show hostnames "$SLURM_JOB_NODELIST")
nodes_array=($nodes)

head_node=${nodes_array[0]}
head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)


# __doc_head_ray_start__
port=6379
ip_head=$head_node_ip:$port
export ip_head
echo "IP Head: $ip_head"

echo "Starting HEAD at $head_node"
srun --nodes=1 --ntasks=1 --gres=gpu:2 -w "$head_node" \
    ray start --head --node-ip-address="$head_node_ip" --port=$port \
    --num-cpus "${SLURM_CPUS_PER_TASK}" --num-gpus "${SLURM_GPUS_PER_TASK}" \
    --dashboard-host "$head_node_ip" --block &
# __doc_head_ray_end__

# __doc_worker_ray_start__

# number of nodes other than the head node
worker_num=$((SLURM_JOB_NUM_NODES - 1))

for ((i = 1; i <= worker_num; i++)); do
    node_i=${nodes_array[$i]}
    echo "Starting WORKER $i at $node_i"
    srun --nodes=1 --ntasks=1 --gres=gpu:2 -w "$node_i" \
        ray start --address "$ip_head" \
        --num-cpus "${SLURM_CPUS_PER_TASK}" --num-gpus "${SLURM_GPUS_PER_TASK}" --block &
    sleep 1
done
# __doc_worker_ray_end__

# __doc_script_start__


# Run experiment
# "sbatch -p class run_experiment.slurm [path/to/config]"
python run_experiment.py ${SLURM_CPUS_PER_TASK} $1
```

`run_experiment.py` can really have anything as the warnings happen before `ray.init()`

The warnings are as follows:

```
[2021-08-01 20:06:41,407 I 28552 28552] global_state_accessor.cc:326: This node has an IP address of ***, while we can not found the matched Raylet address. This maybe come from when you connect the Ray cluster with a different IP address or connect a container.
[2021-08-01 20:06:41,435 I 7652 7652] global_state_accessor.cc:326: This node has an IP address of ***, while we can not found the matched Raylet address. This maybe come from when you connect the Ray cluster with a different IP address or connect a container.
[2021-08-01 20:06:41,435 I 14548 14548] global_state_accessor.cc:326: This node has an IP address of ***, while we can not found the matched Raylet address. This maybe come from when you connect the Ray cluster with a different IP address or connect a container.
[2021-08-01 20:06:41,437 I 4763 4763] global_state_accessor.cc:326: This node has an IP address of ***, while we can not found the matched Raylet address. This maybe come from when you connect the Ray cluster with a different IP address or connect a container.
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ X] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

Is this something we should be concerned about?

**Comment by import-antigravity** [comment] 2021-08-02 00:37
@amogkam

**Comment by akern40** [comment] 2021-08-05 18:02
I'm having the same issue. It appears the bug was introduced in 1.5.0, since running the exact same scripts using 1.3.0, 1.4.0, and 1.4.1 works as expected.

**Comment by amogkam** [comment] 2021-08-05 18:06
cc @rkooo567

**Comment by richardliaw** [comment] 2021-08-07 08:37
@import-antigravity and @akern40 thanks a bunch for reporting this! 

Can you tell me a bit about your slurm setup? Are you using singularity?

**Comment by akern40** [comment] 2021-08-09 16:10
@richardliaw we are using Slurm v20.11.3, without Singularity or other third-party container managers. I'm not sure what other information you're looking for (I'm just a consumer of our supercomputing resources, and don't know all of the low-level details) but if there's information that would help debug let me know and I'll see if I can find out.

**Comment by richardliaw** [comment] 2021-08-09 21:39
@akern40 awesome.

I wonder if this is a IP related issue. Can you enable ` RAY_BACKEND_LOG_LEVEL=debug` before you run `ray start`, then post the full folder from `/tmp/ray/session_latest/logs`?

**Comment by akern40** [comment] 2021-08-09 22:57
Ok, so I went to go set up an environment to try to replicate the issue (using Ray 1.5.1), and have discovered it's flaky. I was previously getting the `global_state_accessor` problem on every node start. Now, when I try to replicate it, I only get it once (nominally, according to my logs, after Ray has started all of the workers and my script starts). I'm not sure why this is.

After that warning shows, my script actually appears to run. I'm using Ray to do RLlib training, for context. I get a few thousand lines of stack traces telling me something along the lines of "SystemExit was raised from the worker" from just about every (PID, IP, Port) combination involved in the training, and then I get the standard RLlib output that shows that the training completed and converged, as expected.

I'll put a bunch more debug information in another post, so that this one doesn't become unwieldy.

**Comment by akern40** [comment] 2021-08-09 23:34
Here are a few pieces of context. I'm including my submission script and the raw output log from SLURM (edited down to get rid of personal details).

__Submission script:__
```shell
#!/bin/bash

#SBATCH --constraint=irrelevant, hopefully
#SBATCH --nodes=8
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=2
#SBATCH -o rllib-ppo-experiment-%j.log

RAY_BACKEND_LOG_LEVEL=debug
export RAY_BACKEND_LOG_LEVEL

SLURM_CPUS_PER_TASK=2
SLURM_GPUS_PER_TASK=0
export SLURM_CPUS_PER_TASK
export SLURM_GPUS_PER_TASK

export TMPDIR=(my temp dir)
mkdir -p $TMPDIR

# Loading required modules
source /etc/profile
module load anaconda/2021a
eval "$(conda shell.bash hook)"

# Activate the environment
conda activate strabo15

# Configure Ray for SLURM
# Get node names
nodes=$(scontrol show hostnames "$SLURM_JOB_NODELIST")
nodes_array=($nodes)

# Get head node IP
head_node=${nodes_array[0]}
head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)

# if we detect a space character in the head node IP, we'll
# convert it to an ipv4 address. This step is optional.
if [[ "$head_node_ip" == *" "* ]]; then
IFS=' ' read -ra ADDR <<<"$head_node_ip"
if [[ ${#ADDR[0]} -gt 16 ]]; then
  head_node_ip=${ADDR[1]}
else
  head_node_ip=${ADDR[0]}
fi
echo "IPV6 address detected. We split the IPV4 address as $head_node_ip"
fi

# Start Ray head node
port=6379
RAY_ADDRESS=$head_node_ip:$port
export RAY_ADDRESS
echo "IP Head: $RAY_ADDRESS"

echo "Temporary Directory: $TMPDIR"

echo "Starting HEAD at $head_node"
srun --nodes=1 --ntasks=1 -w "$head_node" \
    ray start --head --temp-dir="${TMPDIR}" --node-ip-address="$head_node_ip" --port=$port \
    --num-cpus "${SLURM_CPUS_PER_TASK}" --num-gpus "${SLURM_GPUS_PER_TASK}" --block &

# Start the worker nodes
# optional, though may be useful in certain versions of Ray < 1.0.
sleep 10

# number of nodes other than the head node
worker_num=$((SLURM_JOB_NUM_NODES - 1))
export worker_num

for ((i = 1; i <= worker_num; i++)); do
    node_i=${nodes_array[$i]}
    echo "Starting WORKER $i at $node_i"
    srun --nodes=1 --ntasks=1 -w "$node_i" \
        ray start --temp-dir="${TMPDIR}" --address "$RAY_ADDRESS" \
        --num-cpus "${SLURM_CPUS_PER_TASK}" --num-gpus "${SLURM_GPUS_PER_TASK}" --block &
    sleep 5
done

echo "Starting script"
python myscript.py
```

__SLURM output:__
```shell
Temporary Directory: ~/strabo15/43998793
Starting HEAD at c-4-9-4
2021-08-09 18:48:41,227 INFO services.py:1247 -- View the Ray dashboard at http://127.0.0.1:8265
Starting WORKER 1 at c-4-10-1
Starting WORKER 2 at c-4-10-2
Starting WORKER 3 at c-4-10-3
Starting WORKER 4 at c-4-10-4
Starting WORKER 5 at c-4-11-1
Starting WORKER 6 at c-4-11-2
Starting WORKER 7 at c-4-11-3
Starting script
2021-08-09 18:49:28,711 INFO worker.py:801 -- Connecting to existing Ray cluster at address: ***.31.***.95:6379
[2021-08-09 18:49:28,726 I 70942 70942] global_state_accessor.cc:326: This node has an IP address of ***.22.***.95, while we can not found the matched Raylet address. This maybe come from when you connect the Ray cluster with a different IP address or connect a container.
[2021-08-09 18:49:28,742 I 70942 70942] logging.cc:186: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1

(raylet, ip=***.22.***.98) [2021-08-09 18:49:29,625 I 78040 78040] logging.cc:186: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
(raylet, ip=***.22.***.98) [2021-08-09 18:49:29,627 I 78041 78041] logging.cc:186: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
# ... an a whole bunch of other processes reporting that they're logging debug

# Then we get into the errors. They seem to have two parts. The first is a SystemExit from a worker,
# which seems to be the same for every stacktrace
(pid=6949, ip=***.22.***.101) 2021-08-09 18:53:05,556 ERROR worker.py:421 -- SystemExit was raised from the worker
(pid=6949, ip=***.22.***.101) Traceback (most recent call last):
(pid=6949, ip=***.22.***.101)   File "python/ray/_raylet.pyx", line 530, in ray._raylet.execute_task
(pid=6949, ip=***.22.***.101)   File "python/ray/_raylet.pyx", line 534, in ray._raylet.execute_task
(pid=6949, ip=***.22.***.101)   File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task.function_executor
(pid=6949, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
(pid=6949, ip=***.22.***.101)     return method(__ray_actor, *args, **kwargs)
(pid=6949, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/site-packages/ray/actor.py", line 1027, in __ray_terminate__
(pid=6949, ip=***.22.***.101)     ray.actor.exit_actor()
(pid=6949, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/site-packages/ray/actor.py", line 1103, in exit_actor
(pid=6949, ip=***.22.***.101)     raise exit
(pid=6949, ip=***.22.***.101) SystemExit: 0

# Then we get a "another exception occurred" segment. This section seems to have a few different versions. Here's one:
(pid=6949, ip=***.22.***.101) During handling of the above exception, another exception occurred:
(pid=6949, ip=***.22.***.101)
(pid=6949, ip=***.22.***.101) Traceback (most recent call last):
(pid=6949, ip=***.22.***.101)   File "python/ray/_raylet.pyx", line 632, in ray._raylet.task_execution_handler
(pid=6949, ip=***.22.***.101)   File "python/ray/_raylet.pyx", line 486, in ray._raylet.execute_task
(pid=6949, ip=***.22.***.101)   File "python/ray/_raylet.pyx", line 523, in ray._raylet.execute_task
(pid=6949, ip=***.22.***.101)   File "python/ray/includes/libcoreworker.pxi", line 33, in ray._raylet.ProfileEvent.__exit__
(pid=6949, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/traceback.py", line 167, in format_exc
(pid=6949, ip=***.22.***.101)     return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
(pid=6949, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/traceback.py", line 121, in format_exception
(pid=6949, ip=***.22.***.101)     type(value), value, tb, limit=limit).format(chain=chain))
(pid=6949, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/traceback.py", line 508, in __init__
(pid=6949, ip=***.22.***.101)     capture_locals=capture_locals)
(pid=6949, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/traceback.py", line 363, in extract
(pid=6949, ip=***.22.***.101)     f.line
(pid=6949, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/traceback.py", line 285, in line
(pid=6949, ip=***.22.***.101)     self._line = linecache.getline(self.filename, self.lineno).strip()
(pid=6949, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/linecache.py", line 16, in getline
(pid=6949, ip=***.22.***.101)     lines = getlines(filename, module_globals)
(pid=6949, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/site-packages/torch/_fx/graph_module.py", line 27, in patched_getline
(pid=6949, ip=***.22.***.101)     return _orig_getlines(*args, **kwargs)
(pid=6949, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/linecache.py", line 47, in getlines
(pid=6949, ip=***.22.***.101)     return updatecache(filename, module_globals)
(pid=6949, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/linecache.py", line 136, in updatecache
(pid=6949, ip=***.22.***.101)     with tokenize.open(fullname) as fp:
(pid=6949, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/tokenize.py", line 451, in open
(pid=6949, ip=***.22.***.101)     text = TextIOWrapper(buffer, encoding, line_buffering=True)
(pid=6949, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/codecs.py", line 309, in __init__
(pid=6949, ip=***.22.***.101)     def __init__(self, errors='strict'):
(pid=6949, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/site-packages/ray/worker.py", line 418, in sigterm_handler
(pid=6949, ip=***.22.***.101)     sys.exit(1)
(pid=6949, ip=***.22.***.101) SystemExit: 1

...

# Here's another
(pid=6950, ip=***.22.***.101) Traceback (most recent call last):
(pid=6950, ip=***.22.***.101)   File "python/ray/_raylet.pyx", line 632, in ray._raylet.task_execution_handler
(pid=6950, ip=***.22.***.101)   File "python/ray/_raylet.pyx", line 486, in ray._raylet.execute_task
(pid=6950, ip=***.22.***.101)   File "python/ray/_raylet.pyx", line 523, in ray._raylet.execute_task
(pid=6950, ip=***.22.***.101)   File "python/ray/includes/libcoreworker.pxi", line 33, in ray._raylet.ProfileEvent.__exit__
(pid=6950, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/traceback.py", line 167, in format_exc
(pid=6950, ip=***.22.***.101)     return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
(pid=6950, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/traceback.py", line 121, in format_exception
(pid=6950, ip=***.22.***.101)     type(value), value, tb, limit=limit).format(chain=chain))
(pid=6950, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/traceback.py", line 508, in __init__
(pid=6950, ip=***.22.***.101)     capture_locals=capture_locals)
(pid=6950, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/traceback.py", line 363, in extract
(pid=6950, ip=***.22.***.101)     f.line
(pid=6950, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/traceback.py", line 285, in line
(pid=6950, ip=***.22.***.101)     self._line = linecache.getline(self.filename, self.lineno).strip()
(pid=6950, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/linecache.py", line 16, in getline
(pid=6950, ip=***.22.***.101)     lines = getlines(filename, module_globals)
(pid=6950, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/site-packages/torch/_fx/graph_module.py", line 27, in patched_getline
(pid=6950, ip=***.22.***.101)     return _orig_getlines(*args, **kwargs)
(pid=6950, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/linecache.py", line 47, in getlines
(pid=6950, ip=***.22.***.101)     return updatecache(filename, module_globals)
(pid=6950, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/linecache.py", line 136, in updatecache
(pid=6950, ip=***.22.***.101)     with tokenize.open(fullname) as fp:
(pid=6950, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/tokenize.py", line 449, in open
(pid=6950, ip=***.22.***.101)     encoding, lines = detect_encoding(buffer.readline)
(pid=6950, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/tokenize.py", line 418, in detect_encoding
(pid=6950, ip=***.22.***.101)     first = read_or_stop()
(pid=6950, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/tokenize.py", line 376, in read_or_stop
(pid=6950, ip=***.22.***.101)     return readline()
(pid=6950, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/site-packages/ray/worker.py", line 418, in sigterm_handler
(pid=6950, ip=***.22.***.101)     sys.exit(1)
(pid=6950, ip=***.22.***.101) SystemExit: 1

...

# And another
(pid=51860, ip=***.22.***.101) Traceback (most recent call last):
(pid=51860, ip=***.22.***.101)   File "python/ray/_raylet.pyx", line 632, in ray._raylet.task_execution_handler
(pid=51860, ip=***.22.***.101)   File "python/ray/_raylet.pyx", line 486, in ray._raylet.execute_task
(pid=51860, ip=***.22.***.101)   File "python/ray/_raylet.pyx", line 523, in ray._raylet.execute_task
(pid=51860, ip=***.22.***.101)   File "python/ray/includes/libcoreworker.pxi", line 42, in ray._raylet.ProfileEvent.__exit__
(pid=51860, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/json/__init__.py", line 231, in dumps
(pid=51860, ip=***.22.***.101)     return _default_encoder.encode(obj)
(pid=51860, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/json/encoder.py", line 199, in encode
(pid=51860, ip=***.22.***.101)     chunks = self.iterencode(o, _one_shot=True)
(pid=51860, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/json/encoder.py", line 214, in iterencode
(pid=51860, ip=***.22.***.101)     if self.check_circular:
(pid=51860, ip=***.22.***.101)   File "~/.conda/envs/strabo15/lib/python3.7/site-packages/ray/worker.py", line 418, in sigterm_handler
(pid=51860, ip=***.22.***.101)     sys.exit(1)
(pid=51860, ip=***.22.***.101) SystemExit: 1

# As best I can tell, those are the three "another exception" segments. There's tons of them.

# Then the regular RLlib output, which I won't include here.
```

**Comment by akern40** [comment] 2021-08-10 00:09
Ok lastly, as requested, I'm dropping in all of the contents of the `logs` directory. I'm also including the full SLURM output. Like I did above, all of these are sanitized so that the root directory is replaced with `~`, and IPs are obscured. Hopefully this shouldn't mess up any debugging, I made sure that all of the IPs are still unique. Github doesn't accept `.err` or `.out`, so I've replaced those with `_err.log` and `_out.log`. If there's a file that you'd expect to be here but isn't it's because it's empty.
[dashboard.log](https://github.com/ray-project/ray/files/6957991/dashboard.log)
[dashboard_agent.log](https://github.com/ray-project/ray/files/6957992/dashboard_agent.log)
[gcs_server_err.log](https://github.com/ray-project/ray/files/6957993/gcs_server_err.log)
[gcs_server_out.log](https://github.com/ray-project/ray/files/6957994/gcs_server_out.log)
[log_monitor.log](https://github.com/ray-project/ray/files/6957995/log_monitor.log)
[monitor.log](https://github.com/ray-project/ray/files/6957996/monitor.log)
[monitor_err.log](https://github.com/ray-project/ray/files/6957998/monitor_err.log)
[python-core-driver-01000000ffffffffffffffffffffffffffffffffffffffffffffffff_70942.log](https://github.com/ray-project/ray/files/6957999/python-core-driver-01000000ffffffffffffffffffffffffffffffffffffffffffffffff_70942.log)
[python-core-worker-0eabf6c66cce43e4b073c819fe517e6de8402b1ade8009c8a9ef0fa9_78041.log](https://github.com/ray-project/ray/files/6958000/python-core-worker-0eabf6c66cce43e4b073c819fe517e6de8402b1ade8009c8a9ef0fa9_78041.log)
[python-core-worker-1d00a087683efdadbe0c4231a9dc57b3e40ea4d75afd8972959c2b4d_51859.log](https://github.com/ray-project/ray/files/6958001/python-core-worker-1d00a087683efdadbe0c4231a9dc57b3e40ea4d75afd8972959c2b4d_51859.log)
[python-core-worker-5bc9510f69e949dd913f466701ddf917a0ee0e9a88a9e3704aab3319_6950.log](https://github.com/ray-project/ray/files/6958002/python-core-worker-5bc9510f69e949dd913f466701ddf917a0ee0e9a88a9e3704aab3319_6950.log)
[python-core-worker-7be70384df6a2b1c874272fae4014119edaa744b1aa58e161266981e_55723.log](https://github.com/ray-project/ray/files/6958003/python-core-worker-7be70384df6a2b1c874272fae4014119edaa744b1aa58e161266981e_55723.log)
[python-core-worker-44e0ab0de463cd78fa2948fa951a6704658e1565ce075e3c4e78f1f7_6949.log](https://github.com/ray-project/ray/files/6958004/python-core-worker-44e0ab0de463cd78fa2948fa951a6704658e1565ce075e3c4e78f1f7_6949.log)
[python-core-worker-30743861255b36d74f802f9a86099364e6c8b203e385d139dcd6aa51_78040.log](https://github.com/ray-project/ray/files/6958005/python-core-worker-30743861255b36d74f802f9a86099364e6c8b203e385d139dcd6aa51_78040.log)
[python-core-worker-b72eb5b344e438e3b70e55e1ff719c13ec77472a2619c2c45f8f339a_6997.log](https://github.com/ray-project/ray/files/6958006/python-core-worker-b72eb5b344e438e3b70e55e1ff719c13ec77472a2619c2c45f8f339a_6997.log)
[python-core-worker-cc1e98c6eb32a2cb82bdb867d7063c2901d04d954cb915247a04a640_51860.log](https://github.com/ray-project/ray/files/6958007/python-core-worker-cc1e98c6eb32a2cb82bdb867d7063c2901d04d954cb915247a04a640_51860.log)
[python-core-worker-d8eee0ab82d0c0e034951395842c4872cd104f4f2eb1520b303a2b75_55675.log](https://github.com/ray-project/ray/files/6958008/python-core-worker-d8eee0ab82d0c0e034951395842c4872cd104f4f2eb1520b303a2b75_55675.log)
[python-core-worker-2d0f509bea54edda04f3f43eafa942ba2c3cfa6eb5d9f5103f503e92_55676.log](https://github.com/ray-project/ray/files/6958009/python-core-worker-2d0f509bea54edda04f3f43eafa942ba2c3cfa6eb5d9f5103f503e92_55676.log)
[ray_client_server_err.log](https://github.com/ray-project/ray/files/6958012/ray_client_server_err.log)
[raylet_err.log](https://github.com/ray-project/ray/files/6958029/raylet_err.log)
[raylet_err.3.log](https://github.com/ray-project/ray/files/6958030/raylet_err.3.log)
[raylet_err.4.log](https://github.com/ray-project/ray/files/6958031/raylet_err.4.log)
[raylet_err.5.log](https://github.com/ray-project/ray/files/6958032/raylet_err.5.log)
[raylet_err.6.log](https://github.com/ray-project/ray/files/6958033/raylet_err.6.log)
[raylet_err.7.log](https://github.com/ray-project/ray/files/6958034/raylet_err.7.log)
[raylet_err.1.log](https://github.com/ray-project/ray/files/6958035/raylet_err.1.log)
[raylet_err.2.log](https://github.com/ray-project/ray/files/6958036/raylet_err.2.log)
[raylet_out.3.log](https://github.com/ray-project/ray/files/6958037/raylet_out.3.log)
[raylet_out.4.log](https://github.com/ray-project/ray/files/6958038/raylet_out.4.log)
[raylet_out.5.log](https://github.com/ray-project/ray/files/6958039/raylet_out.5.log)
[raylet_out.6.log](https://github.com/ray-project/ray/files/6958040/raylet_out.6.log)
[raylet_out.7.log](https://github.com/ray-project/ray/files/6958041/raylet_out.7.log)
[raylet_out.log](https://github.com/ray-project/ray/files/6958042/raylet_out.log)
[raylet_out.1.log](https://github.com/ray-project/ray/files/6958043/raylet_out.1.log)
[raylet_out.2.log](https://github.com/ray-project/ray/files/6958044/raylet_out.2.log)
[redis_out.log](https://github.com/ray-project/ray/files/6958046/redis_out.log)
[redis-shard_0_out.log](https://github.com/ray-project/ray/files/6958047/redis-shard_0_out.log)
[worker-5bc9510f69e949dd913f466701ddf917a0ee0e9a88a9e3704aab3319-01000000-6950_err.log](https://github.com/ray-project/ray/files/6958061/worker-5bc9510f69e949dd913f466701ddf917a0ee0e9a88a9e3704aab3319-01000000-6950_err.log)
[worker-2d0f509bea54edda04f3f43eafa942ba2c3cfa6eb5d9f5103f503e92-01000000-55676_err.log](https://github.com/ray-project/ray/files/6958062/worker-2d0f509bea54edda04f3f43eafa942ba2c3cfa6eb5d9f5103f503e92-01000000-55676_err.log)
[worker-5bc9510f69e949dd913f466701ddf917a0ee0e9a88a9e3704aab3319-01000000-6950_err.log](https://github.com/ray-project/ray/files/6958065/worker-5bc9510f69e949dd913f466701ddf917a0ee0e9a88a9e3704aab3319-01000000-6950_err.log)
[worker-44e0ab0de463cd78fa2948fa951a6704658e1565ce075e3c4e78f1f7-01000000-6949_err.log](https://github.com/ray-project/ray/files/6958067/worker-44e0ab0de463cd78fa2948fa951a6704658e1565ce075e3c4e78f1f7-01000000-6949_err.log)
[worker-30743861255b36d74f802f9a86099364e6c8b203e385d139dcd6aa51-01000000-78040_err.log](https://github.com/ray-project/ray/files/6958069/worker-30743861255b36d74f802f9a86099364e6c8b203e385d139dcd6aa51-01000000-78040_err.log)
[worker-cc1e98c6eb32a2cb82bdb867d7063c2901d04d954cb915247a04a640-01000000-51860_err.log](https://github.com/ray-project/ray/files/6958071/worker-cc1e98c6eb32a2cb82bdb867d7063c2901d04d954cb915247a04a640-01000000-51860_err.log)
[worker-d8eee0ab82d0c0e034951395842c4872cd104f4f2eb1520b303a2b75-01000000-55675_err.log](https://github.com/ray-project/ray/files/6958072/worker-d8eee0ab82d0c0e034951395842c4872cd104f4f2eb1520b303a2b75-01000000-55675_err.log)

**Comment by richardliaw** [comment] 2021-08-10 04:17
Thanks a bunch for all of these logs!

Taking a look, it seems like the sigterm handler in Ray is working properly, but Torch is manipulating the stack in some way:

```python
  File "~/.conda/envs/strabo15/lib/python3.7/site-packages/torch/_fx/graph_module.py", line 27, in patched_getline
    return _orig_getlines(*args, **kwargs)
```

which causes the exit code 1 to be returned from that thread. 

You mention this is largely a logging issue (your program runs correctly) -- perhaps maybe an easy solution here is just to provide a way to mute this exception log?

**Comment by akern40** [comment] 2021-08-10 18:30
Hopefully it wasn't an overwhelming number of logs! You asked for the whole folder, so I figured I'd just do a dump.

It's possible this is just a logging issue - I'll look into whether Ray is getting proper performance out of all of the nodes. However, I don't think Torch is manipulating the stack in a significant manner. Turns out their `fx` module [monkey-patches `linecache`](https://github.com/pytorch/pytorch/blob/v1.8.1/torch/fx/graph_module.py#L16) to deal with correct stack traces, but in each of the cases above it's just acting as a pass-through to the original `linecache` function. As a result, it shows up in the stack trace, but doesn't appear to change behavior of the trace or the program. What's more, RLlib calls for `torch==1.8.1` in both Ray 1.4.1 and Ray 1.5, so if it's an issue caused by Torch the problem should be consistent across Ray versions as well, right?

**Comment by andrewkhardy** [comment] 2021-11-01 14:52
I am getting the same issue, could we fix this?

**Comment by akern40** [comment] 2022-01-06 22:35
It is worth noting that this issue persists for the latest versions of Ray and RLlib, unfortunately. It continues to have no effect on training (as best I can tell) but does still say its failing to connect. Any help would be appreciated so that I don't have to worry something isn't going right, thanks!

**Comment by rkooo567** [comment] 2022-01-06 23:02
@richardliaw Was there any conclusion from the investigation of this issue? Maybe we should

**Comment by DmitriGekhtman** [comment] 2022-05-10 06:02
The error message occurred in the investigation of another issue https://github.com/ray-project/ray/issues/20402#issuecomment-969942536
It seems there might have been a change in the Ray core that led to this regression.

When Slurm deployment scripts are fixed, the Ray team would be very glad to coordinate on testing procedures to prevent these scripts from breaking again.

**Comment by jdrusso** [comment] 2022-10-24 23:19
This issue still persists

**Comment by DmitriGekhtman** [comment] 2022-10-25 04:44
cc @tupui

**Comment by zhe-thoughts** [comment] 2022-10-25 06:08
Assigning to @tupui for now since our documentations page indicates they are the maintainer of the module. But we will get back with a plan for this issue

**Comment by hw-ju** [comment] 2023-08-29 03:20
Hi!
I’m getting the same error on an HPC SLURM cluster:
```
global_state_accessor.cc:356: This node has an IP address of 172.16.204.7, but we cannot find a local Raylet with the same address. This can happen when you connect to the Ray cluster with a different IP address or when connecting to a container.
```
However, the experiments start running after this error and finish. So can this error be safely ignored?

**Comment by anyscalesam** [comment] 2024-10-09 16:15
@hw-ju is this still occurring for you?

**Closed by anyscalesam** 2024-10-09 16:15 UTC
Labels: bug, regression, P3, core
