### ISSUE TITLE
[RLLib] release test failure: rllib_learning_tests_apex_torch

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#33753] opened 2023-03-27 18:31 UTC
### What happened + What you expected to happen

https://buildkite.com/ray-project/release-tests-branch/builds/1470#018710b9-a0b3-4b1f-882c-35a0895484c4

### Versions / Dependencies

master

### Reproduction script

nightly

### Issue Severity

None

**Comment by clarng** [comment] 2023-03-27 18:32
Is this still failing? If so would be 2.4 release blocker

**Comment by avnishn** [comment] 2023-03-28 18:59
oh you know I think I know the problem:
https://github.com/ray-project/ray/pull/33814

**Comment by avnishn** [comment] 2023-03-28 20:12
I dug into this a little more. Its not clear where the issue is being created from. Looking at the job's cluster's logs, theres some issue thats being created while launching the job that is not appearing in any of the logs. I will wait for one more release test run before diving further to inspect.

**Comment by avnishn** [comment] 2023-03-29 18:40
closing this for now, as it looks like this was resolved by fixes in prod.

**Closed by avnishn** 2023-03-29 18:40 UTC
Labels: bug, release-blocker, P0, rllib, Ray 2.4
