### ISSUE TITLE
[Bug] ray.sgd.v2.Trainer hangs after restart

### ISSUE THREAD

**Issue by davidegraff** [ray-project/ray#19163] opened 2021-10-06 21:22 UTC
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RaySGD

### What happened + What you expected to happen

**the bug** : I have the general paradigm in my code:
```python
trainer.start()
trainer.run()
trainer.shutdown()
```
which works fine the first time this block of code is executed. However, the second time this block is executed, my program hangs. I recently ported from RaySGD v1 and my the old code didn't have this issue

**expected behavior**: that the code block is able to be executed an arbitrary number of times throughout program runtime

### Reproduction script

my training function is called multiple times throughout the program runtime and has the general structure:
```python
def train_model(config):
    trainer = Trainer(...)
    trainer.start()
    results = trainer.run(train_func, config)
    trainer.shutdown()
```

The second time this function is executed, the program hangs.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by davidegraff** [comment] 2021-10-07 02:38
I think it might be specific to my code. I ran the original `train_linear_example.py` with your modification on my system and it ran just fine. I then made the following modifications (in order) to bring it closer to my own code:
1. performing all training on GPUs (✅ )
2. allocating N cpu per process (in addition to the 1 GPU) (✅)
3. distributing data loading over `N` workers (✅)
4. defining a `collate_fn` for data loading that mimics a slow calculation (✅)

The only things still remaining that differentiate my code from the example are:
- training is done inside an object method. I.e., there is a `ModelWrapper` object which itself contains a `model` attribute that is trained and passed in to the `train_func` via the `config`
- the `Trainer` is also stored as a `Model` attribute, so distributed training is performed via code that looks something like:
```python
class ModelWrapper:
    def __init__(self, ...):
        self.model = Model(....)
        ....
        self.train_config = {...} # training options like number of epochs, learning rate, etc.
        self.trainer = Trainer("torch", num_workers, use_gpu, {"CPU": ncpu})

    def train(self, xs, ys):
        train_data, val_data = make_datasets(xs, ys)
        self.train_config["train_data"] = train_data
        self.train_config["val_data"] = val_data
        self.trainer.start()
        results = self.trainer.run(mpnn.sgd.train_func, self.train_config)
        self.trainer.shutdown()
```
over the course of program runtime, I will call `Model.train(xs, ys)` multiple times as I acquire more data (the context is active learning). The specific code I'm running can be found [here](https://github.com/coleygroup/molpal/blob/refactor/ray-sgd-v2/molpal/models/mpnmodels.py#L153) and [here](https://github.com/coleygroup/molpal/blob/refactor/ray-sgd-v2/molpal/models/mpnn/sgd.py#L19)

Thanks for the help!

Here's the modified `train_linear_example` script I used for testing with some annotations for what step the new lines were added in:
```python
import os
from time import sleep

import numpy as np
import ray
import ray.util.sgd.v2 as sgd
from ray.util.sgd.v2 import Trainer
from ray.util.sgd.v2.callbacks import JsonLoggerCallback, TBXLoggerCallback
import torch
from torch import nn
from torch.nn.parallel import DistributedDataParallel
from torch.utils.data import DataLoader, DistributedSampler


class LinearDataset(torch.utils.data.Dataset):
    def __init__(self, a, b, size=1000):
        x = np.arange(0, 10, 10 / size, dtype=np.float32)
        self.x = torch.from_numpy(x)
        self.y = torch.from_numpy(a * x + b)

    def __getitem__(self, index):
        return self.x[index, None], self.y[index, None]

    def __len__(self):
        return len(self.x)

# 4
def collate_fn(data):
    xs, ys = zip(*data)
    sleep(1)    # i.e., an expensive calculation
    return torch.stack(xs), torch.stack(ys)

def train(dataloader, model, loss_fn, optimizer, device=None):
    for X, y in dataloader:
        X, y = X.to(device), y.to(device)
        # Compute prediction error
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()


def validate(dataloader, model, loss_fn, device=None):
    num_batches = len(dataloader)
    model.eval()
    loss = 0
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            loss += loss_fn(pred, y).item()
    loss /= num_batches
    result = {"model": model.state_dict(), "loss": loss}
    return result


def train_func(config):
    data_size = config.get("data_size", 1000)
    val_size = config.get("val_size", 400)
    batch_size = config.get("batch_size", 32)
    hidden_size = config.get("hidden_size", 1)
    lr = config.get("lr", 1e-2)
    epochs = config.get("epochs", 3)
    ncpu = config.get("ncpu", 1) # 3


    # 1
    device = torch.device(
        f"cuda:{sgd.local_rank()}" if torch.cuda.is_available() else "cpu"
    )
    if torch.cuda.is_available():
        torch.cuda.set_device(device)

    train_dataset = LinearDataset(2, 5, size=data_size)
    val_dataset = LinearDataset(2, 5, size=val_size)

    train_loader = DataLoader(
        train_dataset,
        batch_size,
        sampler=DistributedSampler(train_dataset),
        num_workers=ncpu, # 3
        collate_fn=collate_fn # 4
    )
    validation_loader = DataLoader(
        val_dataset,
        batch_size,
        sampler=DistributedSampler(val_dataset),
        num_workers=ncpu, # 3
        collate_fn=collate_fn # 4
    )

    model = nn.Linear(1, hidden_size).to(device) # 1
    model = DistributedDataParallel(
        model, device_ids=[sgd.local_rank()] if torch.cuda.is_available() else None # 1
    )

    loss_fn = nn.MSELoss()

    optimizer = torch.optim.SGD(model.parameters(), lr=lr)

    results = []

    for _ in range(epochs):
        train(train_loader, model, loss_fn, optimizer, device) # 1
        result = validate(validation_loader, model, loss_fn, device) # 1
        sgd.report(**result)
        results.append(result)

    return results


def train_linear(num_workers, use_gpu, ncpu):
    trainer = Trainer("torch", num_workers, use_gpu, {"CPU": ncpu}) # 1/2
    config = {"lr": 1e-2, "hidden_size": 1, "batch_size": 4, "epochs": 3}
    trainer.start()
    results = trainer.run(
        train_func,
        config,
        callbacks=[JsonLoggerCallback(), TBXLoggerCallback()]
    )
    trainer.shutdown()

    print(results)
    return results


if __name__ == "__main__":
    try:
        if 'redis_password' in os.environ:
            ray.init(
                address=os.environ["ip_head"],
                _redis_password=os.environ['redis_password']
            )
        else:
            ray.init(address='auto')
    except ConnectionError:
        ray.init()
    except PermissionError:
        print('Failed to create a temporary directory for ray')
        raise

    print('Ray cluster online with resources:')
    print(ray.cluster_resources())
    print(flush=True)

    num_workers = max(1, int(ray.cluster_resources().get('GPU', 0)))  # 1
    ncpu = int(ray.cluster_resources().get('CPU', 1)) // num_workers # 2
    use_gpu = num_workers > 0 # 1

    for _ in range(3):
        train_linear(num_workers, use_gpu, ncpu)

```

**Comment by amogkam** [comment] 2022-04-11 19:51
Hey @davidegraff has this still been a problem with the latest Ray?

We have made some improvements to avoid various NCCL issues, which seem to be the cause of the hanging. I am going to close this for now, but please re-open if this is still an issue.

**Closed by amogkam** 2022-04-11 19:51 UTC
Labels: bug, P1, train

**Comment by davidegraff** [comment] 2022-04-11 20:56
no i haven't encountered this issue recently- thanks for checking in and all the great work!
