### ISSUE TITLE
[tune] not producing event files

### ISSUE THREAD

**Issue by Blubberblub** [ray-project/ray#17572] opened 2021-08-04 07:45 UTC
I used as small script to test tune and tensorboard logging. The logger saves some data to the correct sub-folder of "/home/user_name/ray_results" as expected but the tensorboard event files are missing so tensorboard doesn't show any logs.

```
from ray import tune
from ray.rllib.agents.ppo import PPOTrainer

config = {"env": "CartPole-v0",
			"evaluation_num_episodes": 1000}

stop = {"episode_reward_mean": 180}

tune.run(PPOTrainer, config=config, stop=stop)  # "log_level": "INFO" for verbose,
	 # "framework": "tfe"/"tf2" for eager,
	# "framework": "torch" for PyTorch
```

Ray version: 1.5.0
Python version: 3.8.5
TF-Version: 2.4.1
Tensorboard-version: 2.5.0
TensorboardX-version: 2.4
OS: WSL2(Ubuntu 20.04 LTS) on windows

The logs show nothing special. After some initial info i get the status messages on the training:
```
2021-08-04 09:25:05,435 INFO services.py:1245 -- View the Ray dashboard at http://127.0.0.1:8265
== Status ==
Memory usage on this node: 1.5/7.7 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/16 CPUs, 0/0 GPUs, 0.0/4.44 GiB heap, 0.0/2.22 GiB objects
Result logdir: /home/user_name/ray_results/PPO_2021-08-04_09-25-06
Number of trials: 1/1 (1 PENDING)
+-----------------------------+----------+-------+
| Trial name                  | status   | loc   |
|-----------------------------+----------+-------|
| PPO_CartPole-v0_178d2_00000 | PENDING  |       |
+-----------------------------+----------+-------+


(pid=2507) 2021-08-04 09:25:08,022      INFO trainer.py:706 -- Tip: set framework=tfe or the --eager flag to enable TensorFlow eager execution
(pid=2507) 2021-08-04 09:25:08,022      INFO trainer.py:718 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
Result for PPO_CartPole-v0_178d2_00000:
  agent_timesteps_total: 4000
  custom_metrics: {}
  date: 2021-08-04_09-25-15
  done: false
  episode_len_mean: 23.162790697674417
  episode_media: {}
  episode_reward_max: 84.0
  episode_reward_mean: 23.162790697674417
  episode_reward_min: 8.0
  episodes_this_iter: 172
  episodes_total: 172
  experiment_id: feb5d777210447a09f00a99cf96964d2
  hostname: TimHomePC
  info:
    learner:
      default_policy:
        learner_stats:
          cur_kl_coeff: 0.20000000298023224
          cur_lr: 4.999999873689376e-05
          entropy: 0.6622359752655029
          entropy_coeff: 0.0
          kl: 0.03187938034534454
          model: {}
          policy_loss: -0.04166114330291748
          total_loss: 94.79032135009766
          vf_explained_var: 0.09626156091690063
          vf_loss: 94.82559967041016
    num_agent_steps_sampled: 4000
    num_agent_steps_trained: 4000
    num_steps_sampled: 4000
    num_steps_trained: 4000
  iterations_since_restore: 1
  node_ip: 172.25.185.240
  num_healthy_workers: 2
  off_policy_estimator: {}
  perf:
    cpu_util_percent: 18.439999999999998
    gpu_util_percent0: .nan
    ram_util_percent: 27.28
    vram_util_percent0: 0.132568359375
  pid: 2507
  policy_reward_max: {}
  policy_reward_mean: {}
  policy_reward_min: {}
  sampler_perf:
    mean_action_processing_ms: 0.027521394371810445
    mean_env_render_ms: 0.0
    mean_env_wait_ms: 0.037298481906874785
    mean_inference_ms: 0.4726888064070825
    mean_raw_obs_processing_ms: 0.04472082471414716
  time_since_restore: 3.620401382446289
  time_this_iter_s: 3.620401382446289
  time_total_s: 3.620401382446289
  timers:
    learn_throughput: 1685.314
    learn_time_ms: 2373.445
    load_throughput: 194848.277
    load_time_ms: 20.529
    sample_throughput: 3321.821
    sample_time_ms: 1204.159
    update_time_ms: 2.104
  timestamp: 1628061915
  timesteps_since_restore: 0
  timesteps_total: 4000
  training_iteration: 1
  trial_id: 178d2_00000

== Status ==
Memory usage on this node: 2.1/7.7 GiB
Using FIFO scheduling algorithm.
Resources requested: 3.0/16 CPUs, 0/0 GPUs, 0.0/4.44 GiB heap, 0.0/2.22 GiB objects
Result logdir: /home/tim/ray_results/PPO_2021-08-04_09-25-06
Number of trials: 1/1 (1 RUNNING)
```

**Comment by krfricke** [comment] 2021-08-04 08:06
This is a duplicate of #17366 and has been fixed in #17403

The current workaround is:

```
from ray.tune.logger import TBXLoggerCallback
# ...
tune.run(
    # ...
    callbacks=[TBXLoggerCallback()]
)
```

Let me know if the problem persists!

**Closed by krfricke** 2021-08-04 08:06 UTC
Labels: bug, triage
