### ISSUE TITLE
[rllib] Custom loss not implemented for PyTorch policies?

### ISSUE THREAD

**Issue by janblumenkamp** [ray-project/ray#8193] opened 2020-04-27 13:06 UTC
### Describe your feature request
I would like to override the `custom_loss` function from `ModelV2` in my custom model, but it seems like the torch policy is currently not using the custom loss at all (it's definitely not called in my model). I briefly looked into it, but there appears to be no `loss_inputs` for the torch policy.

**Comment by sven1977** [comment] 2020-06-25 12:24
Closing this as a duplicate of this one here:
https://github.com/ray-project/ray/issues/8507

**Comment by sven1977** [comment] 2020-06-25 12:24
Thanks @janblumenkamp for catching this.

**Closed by sven1977** 2020-06-25 12:24 UTC
Labels: enhancement
