### ISSUE TITLE
[Core] Investigate fault tolerance for streaming generator

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#38698] opened 2023-08-21 23:02 UTC
Make sure that fault tolerance and object reconstruction work with streaming generator tasks and actor tasks.

**Comment by rkooo567** [comment] 2023-08-23 00:34
Planning to start working on it from this TH

**Comment by rkooo567** [comment] 2023-08-30 12:51
The root cause was that the lineage reconstruction is not triggered when the streaming ref generator is out of scope.

We can fix it by keeping the generator stream until the lineage is released. However, this approach requires some work, and it is safer merging this in 2.8 than cherry picking it for 2.7. Given the ray data is the only library that uses the lineage reconstruction, and there's the workaround in data layer (not GC streaming generator until the DAG is finished), it is for now safe to work around the problem in data layer. We will mark the issue as P0 + ray 2.8 after we close the PR ^

**Comment by rkooo567** [comment] 2023-08-30 22:02
I will reopen the issue with the core root cause

**Closed** 2023-08-30 22:02 UTC
Labels: release-blocker, P0, core, data
