### ISSUE TITLE
[Data] Arrow block overflow when handling binary data

### ISSUE THREAD

**Issue by tmbdev** [ray-project/ray#48042] opened 2024-10-16 13:55 UTC
### What happened + What you expected to happen

Trying to sort 56000 shards of 2000 elements each on a machine with 256GB of memory, 64 CPUs, and 2TB of tmp space.

```Python
def convert1(item):
    data = json.loads(item["text"])
    key = data["id"]
    packed = json.dumps(data, indent=2, default=custom_encoder).encode("utf-8")
    gzipped = gzip.compress(packed)
    sample = {
        "__key__": key,
        "json.gz": gzipped
    }
    return sample

files = sorted(list(braceexpand.braceexpand("gs://.../data-{000000..056287}.jsonl.gz")))
dataset = ray.data.read_text(files) 
dataset.map(convert1).sort("__key__").write_webdataset("gs://.../webdataset-shards/")
```

Got this internal error:

```
(raylet) Spilled 2171 MiB, 4 objects, write throughput 669 MiB/s. Set RAY_verbose_spill_logs=0 to disable this message.
(raylet) Spilled 65042 MiB, 259 objects, write throughput 1893 MiB/s.
(raylet) Spilled 65766 MiB, 260 objects, write throughput 1863 MiB/s.
(raylet) Spilled 126907 MiB, 387 objects, write throughput 947 MiB/s.
(raylet) Spilled 127930 MiB, 388 objects, write throughput 943 MiB/s.
(raylet) Spilled 128043 MiB, 389 objects, write throughput 943 MiB/s.
(raylet) Spilled 188979 MiB, 476 objects, write throughput 1206 MiB/s.
(raylet) Spilled 263071 MiB, 770 objects, write throughput 1342 MiB/s.
(raylet) Spilled 565582 MiB, 4279 objects, write throughput 1053 MiB/s.
2024-10-16 09:01:32,262	ERROR exceptions.py:73 -- Exception occurred in Ray Data or Ray Core internal code. If you continue to see this error, please open an issue on the Ray project GitHub page with the full stack trace below: https://github.com/ray-project/ray/issues/new/choose
2024-10-16 09:01:32,263	ERROR exceptions.py:81 -- Full stack trace:
Traceback (most recent call last):
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/exceptions.py", line 49, in handle_trace
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/plan.py", line 497, in execute
    blocks = execute_to_legacy_block_list(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/execution/legacy_compat.py", line 123, in execute_to_legacy_block_list
    block_list = _bundles_to_block_list(bundles)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/execution/legacy_compat.py", line 169, in _bundles_to_block_list
    for ref_bundle in bundles:
                      ^^^^^^^
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/execution/interfaces/executor.py", line 37, in __next__
    return self.get_next()
           ^^^^^^^^^^^^^^^
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/execution/streaming_executor.py", line 153, in get_next
    item = self._outer._output_node.get_output_blocking(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/execution/streaming_executor_state.py", line 296, in get_output_blocking
    raise self._exception
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/execution/streaming_executor.py", line 232, in run
    continue_sched = self._scheduling_loop_step(self._topology)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/execution/streaming_executor.py", line 322, in _scheduling_loop_step
    update_operator_states(topology)
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/execution/streaming_executor_state.py", line 501, in update_operator_states
    op.all_inputs_done()
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/execution/operators/base_physical_operator.py", line 101, in all_inputs_done
    self._output_buffer, self._stats = self._bulk_fn(self._input_buffer, ctx)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/planner/sort.py", line 66, in fn
    return scheduler.execute(
           ^^^^^^^^^^^^^^^^^^
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/planner/exchange/pull_based_shuffle_task_scheduler.py", line 127, in execute
    new_metadata = reduce_bar.fetch_until_complete(list(new_metadata))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/progress_bar.py", line 184, in fetch_until_complete
    for ref, result in zip(done, ray.get(done)):
                                 ^^^^^^^^^^^^^
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/_private/worker.py", line 2691, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/_private/worker.py", line 871, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ArrowInvalid): ray::reduce() (pid=1760054, ip=10.128.0.4)
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/planner/exchange/sort_task_spec.py", line 144, in reduce
    return BlockAccessor.for_block(mapper_outputs[0]).merge_sorted_blocks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/arrow_block.py", line 609, in merge_sorted_blocks
    ret = concat_and_sort(blocks, sort_key)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/arrow_ops/transform_pyarrow.py", line 318, in concat_and_sort
    return take_table(ret, indices)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/arrow_ops/transform_pyarrow.py", line 49, in take_table
    table = table.take(indices)
            ^^^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 2133, in pyarrow.lib._Tabular.take
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/pyarrow/compute.py", line 487, in take
    return call_function('take', [data, indices], options, memory_pool)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_compute.pyx", line 590, in pyarrow._compute.call_function
  File "pyarrow/_compute.pyx", line 385, in pyarrow._compute.Function.call
  File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: offset overflow while concatenating arrays
2024-10-16 09:01:32,279	ERROR worker.py:409 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::reduce() (pid=1760054, ip=10.128.0.4)
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/planner/exchange/sort_task_spec.py", line 144, in reduce
    return BlockAccessor.for_block(mapper_outputs[0]).merge_sorted_blocks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/arrow_block.py", line 609, in merge_sorted_blocks
    ret = concat_and_sort(blocks, sort_key)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/arrow_ops/transform_pyarrow.py", line 318, in concat_and_sort
    return take_table(ret, indices)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/ray/data/_internal/arrow_ops/transform_pyarrow.py", line 49, in take_table
    table = table.take(indices)
            ^^^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 2133, in pyarrow.lib._Tabular.take
  File "/work/anaconda3/envs/wikidata_env/lib/python3.12/site-packages/pyarrow/compute.py", line 487, in take
    return call_function('take', [data, indices], options, memory_pool)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_compute.pyx", line 590, in pyarrow._compute.call_function
  File "pyarrow/_compute.pyx", line 385, in pyarrow._compute.Function.call
  File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: offset overflow while concatenating arrays
```

### Versions / Dependencies

```
name: work_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.12=h4ab18f5_0
  - aom=3.6.1=h59595ed_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - cairo=1.18.0=hebfffa5_3
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.3.0=py312h68727a3_2
  - cpython=3.12.7=py312hd8ed1ab_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.6=3
  - cycler=0.12.1=pyhd8ed1ab_0
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.7=py312h2ec8cdc_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - double-conversion=3.3.0=h59595ed_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.3=h5888daf_0
  - ffmpeg=4.4.2=gpl_hdf48244_113
  - filelock=3.16.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.54.1=py312h66e93f0_0
  - freetype=2.12.1=h267a509_2
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py312h7201bc8_2
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.13=h59595ed_1003
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=9.0.0=hda332d3_1
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - intel-openmp=2022.0.1=h06a4308_3633
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.28.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py312h68727a3_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_1
  - lerc=4.0.0=h27087fc_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=16_linux64_mkl
  - libclang-cpp19.1=19.1.1=default_hb5137d0_0
  - libclang13=19.1.1=default_h9c6a7e4_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.11.1.6=0
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.3.7.77=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.22=hb9d3cd8_0
  - libdrm=2.4.123=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libegl=1.7.0=ha4b6fd6_1
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libgl=1.7.0=ha4b6fd6_1
  - libglib=2.82.1=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_1
  - libglx=1.7.0=ha4b6fd6_1
  - libgomp=14.1.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=16_linux64_mkl
  - libllvm19=19.1.1=ha7bfdaf_0
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.4=h7f98852_1002
  - libnvjpeg=11.9.0.86=0
  - libopengl=1.7.0=ha4b6fd6_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.44=hadc24fc_0
  - libpq=17.0=h04577a9_2
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.46.1=hadc24fc_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.7.0=he137b08_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h8a09558_1
  - libvpx=1.13.1=h59595ed_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.12.7=he7c6b58_4
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - lmdb=0.9.31=hd590300_1
  - markupsafe=3.0.1=py312h178313f_1
  - matplotlib=3.9.2=py312h7900ff3_1
  - matplotlib-base=3.9.2=py312hd3ec401_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2022.1.0=hc2b9512_224
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=9.0.1=h266115a_1
  - mysql-libs=9.0.1=he0572af_1
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.4.1=pyhd8ed1ab_0
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.2=h488ebb8_0
  - openldap=2.6.8=hedd0468_0
  - openssl=3.3.2=hb9d3cd8_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.3=py312hf9745cd_1
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.44=hba22ea6_2
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py312h56024de_1
  - pip=24.2=pyh8b19718_1
  - pixman=0.43.2=h59595ed_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=6.0.0=py312h66e93f0_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyside6=6.8.0=py312h91f0f75_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.12.7=hc5c86c4_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytorch=2.4.1=py3.12_cuda11.8_cudnn9.1.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h66e93f0_1
  - pyzmq=26.2.0=py312hbf22597_3
  - qhull=2020.2=h434a139_5
  - qt6-main=6.8.0=h6e8976b_0
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_0
  - scikit-learn=1.5.2=py312h7a48858_1
  - scipy=1.14.1=py312h7d485d2_0
  - setuptools=75.1.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - svt-av1=1.4.1=hcb278e6_0
  - sympy=1.13.3=pyh2585a3b_104
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.4.1=py312_cu118
  - torchtriton=3.0.0=py312
  - torchvision=0.19.1=py312_cu118
  - tornado=6.4.1=py312h66e93f0_1
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024b=hc8b5060_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.37=hd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-libice=1.1.1=hb9d3cd8_1
  - xorg-libsm=1.2.4=he73a12e_1
  - xorg-libx11=1.8.10=h4f16b4b_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.2=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.11=hb9d3cd8_1
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.5=hb9d3cd8_3
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h3b0a872_6
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py312hef9b889_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anthropic==0.36.0
      - anyio==4.6.0
      - attrs==24.2.0
      - bitsandbytes==0.44.1
      - braceexpand==0.1.7
      - cachetools==5.5.0
      - click==8.1.7
      - colorful==0.5.6
      - coolname==2.2.0
      - dataclasses-json==0.6.7
      - defusedxml==0.7.1
      - distlib==0.3.9
      - distro==1.9.0
      - fastapi==0.115.2
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - google-api-core==2.21.0
      - google-auth==2.35.0
      - googleapis-common-protos==1.65.0
      - greenlet==3.1.1
      - grpcio==1.66.2
      - h11==0.14.0
      - httpcore==1.0.6
      - httptools==0.6.1
      - httpx==0.27.2
      - huggingface-hub==0.25.2
      - icecream==2.1.3
      - ijson==3.3.0
      - ipywidgets==8.1.5
      - isodate==0.6.1
      - jiter==0.6.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyterlab-widgets==3.0.13
      - langchain==0.3.3
      - langchain-anthropic==0.2.3
      - langchain-community==0.3.2
      - langchain-core==0.3.10
      - langchain-openai==0.2.2
      - langchain-text-splitters==0.3.0
      - langsmith==0.1.134
      - linkify-it-py==2.0.3
      - markdown-it-py==3.0.0
      - marshmallow==3.22.0
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - memray==1.14.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - nltk==3.9.1
      - numpy==1.26.4
      - openai==1.51.2
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - orjson==3.10.7
      - prometheus-client==0.21.0
      - propcache==0.2.0
      - proto-plus==1.24.0
      - protobuf==5.28.2
      - py-spy==0.3.14
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydantic-settings==2.5.2
      - python-dotenv==1.0.1
      - ray==2.37.0
      - rdflib==7.0.0
      - referencing==0.35.1
      - regex==2024.9.11
      - requests-toolbelt==1.0.0
      - rich==13.9.2
      - rpds-py==0.20.0
      - rsa==4.9
      - shellingham==1.5.4
      - smart-open==7.0.5
      - sniffio==1.3.1
      - sqlalchemy==2.0.35
      - starlette==0.39.2
      - tenacity==8.5.0
      - textual==0.83.0
      - tiktoken==0.8.0
      - tokenizers==0.20.1
      - typer==0.12.5
      - typing-inspect==0.9.0
      - uc-micro-py==1.0.3
      - unidecode==1.3.8
      - uvicorn==0.31.1
      - uvloop==0.20.0
      - virtualenv==20.26.6
      - watchfiles==0.24.0
      - webdataset==0.2.100
      - websockets==13.1
      - widgetsnbextension==4.0.13
      - wrapt==1.16.0
      - yarl==1.15.1
```

### Reproduction script

See above.

### Issue Severity

High: It blocks me from completing my task.

**Comment by tmbdev** [comment] 2024-10-30 14:45
Just an additional comment here: this appears to be another case of some internal block growing to be larger than 2G, similar to https://github.com/ray-project/ray/issues/48419

However, in this case, the readers return reasonably small blocks, so the excessively sized blocks are created during sorting. Somehow, the mechanism that is supposed to keep block sizes reasonably small inside pipelines seems to be failing somewhere.

A quick workaround might be to compile with 64bit-offset PyArrow. However, blocks probably shouldn't grow that much unexpectedly.

**Comment by justin-miller-zefr** [comment] 2024-10-31 00:01
We're encountering this as well. Have you happened to discover any workarounds?

**Comment by alexeykudinkin** [comment] 2024-11-01 06:06
Duplicate of #48419 

Should be addressed by https://github.com/ray-project/ray/issues/48042

**Closed** 2024-11-21 07:02 UTC
Labels: bug, P0, data
