### ISSUE TITLE
[upbc] Bazel build failure

### ISSUE THREAD

**Issue by waarmond** [ray-project/ray#44683] opened 2024-04-11 17:59 UTC
### What happened + What you expected to happen

build_ext: Bazel crashes with InaccessibleObjectException
```
[602 / 3,823] Writing file external/upb/upbc/protoc-gen-upbdefs-2.params; 0s local
FATAL: bazel crashed due to an internal error. Printing stack trace:
[..]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make java.lang.String(byte[],byte) accessible: module java.base does not "opens java.lang" to unnamed module @633d68d2
[..]
subprocess.CalledProcessError: Command '['bazel', 'build', '--verbose_failures', '--', '//:ray_pkg', '//cpp:ray_cpp_pkg']' returned non-zero exit status 37.
```
According to [some people](https://groups.google.com/g/repo-discuss/c/v3EHHdjDhiU) `--host_jvm_args=--add-opens=java.base/java.lang=ALL-UNNAMED` would fix the issue. Where to place the line?

### Versions / Dependencies

Ray: git master
Python: 3.10
ArchLinux
bazel: Tried both 7.1.1 and 5.4.1

### Reproduction script

`python -m build --wheel --no-isolation`

### Issue Severity

None

**Comment by aslonnie** [comment] 2024-06-13 17:27
we cannot reproduce this. things build fine on our CI or manylinux image.

we also upgraded bazel to 6.

I am closing this.

**Closed by aslonnie** 2024-06-13 17:27 UTC
Labels: bug, triage, Devprod
