### ISSUE TITLE
[CI] bk://:mac: :apple: Wheels and Jars is failing/flaky on master.

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#29864] opened 2022-10-31 17:37 UTC
<img width="1045" alt="Screen Shot 2022-10-31 at 4 55 33 PM" src="https://user-images.githubusercontent.com/950914/199130819-4a3aa948-6473-4c7b-bccc-45782c5b364a.png">

* https://buildkite.com/ray-project/oss-ci-build-branch/builds/837#01842e4c-80f0-4afb-b85b-fc341e996d90
* https://buildkite.com/ray-project/oss-ci-build-branch/builds/835#01842d4d-05b6-4774-91ae-edf17b60cfe1

```
/Users/ec2-user/.zshrc: line 77: PS1: unbound variable
$ .buildkite/hooks/post-command
user command error: The plugin macos-sandbox command hook exited with status 1
```

An example passing build https://buildkite.com/ray-project/oss-ci-build-branch/builds/791#018426d1-9356-413e-9201-c9792b24973b
* Notice it doesn't have the `unbound variable` line present

**Comment by clarng** [comment] 2022-11-04 20:57
looks like a dupe of https://github.com/ray-project/ray/issues/30026

**Closed by clarng** 2022-11-04 20:57 UTC
Labels: P0
