### ISSUE TITLE
[dask on ray] Dask persist's scheduler parameter doesn't work well with `ray_dask_get` 

### ISSUE THREAD

**Issue by jennakwon06** [ray-project/ray#15327] opened 2021-04-15 05:54 UTC
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

It's a Ray autoscaling cluster that installed ray with `pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl`.

```

root@ip-10-0-0-127:/# python
Python 3.7.10 (default, Feb 19 2021, 00:13:37)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
ra>>>
>>> ray.__version__
'2.0.0.dev0'
>>> ray.__commit__
'27ab0c763370b70b10690ff32d3ee61dbd8730fe'

```

#### SCRIPT

```
import ray
import dask.array
from ray.util.dask import ray_dask_get


def main():
    print("Connecting to the Ray cluster...")
    ray.init(address="auto")
    print("Ray cluster resources ! = {}".format(ray.available_resources()))

    # Create a Dask array
    dask_array = dask.array.ones(10000)
    print("Dask array = {}".format(dask.base.collections_to_dsk([dask_array])))

    # PERSIST
    # Persist the array on the Ray cluster. Notice that the Ray ObjectRef is inlined.
    # The dask.array.ones() task was submitted to and is running on the Ray cluster.
    dask_arr_persisted = dask_array.persist(scheduler=ray_dask_get)
    print("Result from persist = {}".format(dask.base.collections_to_dsk([dask_arr_persisted])))
    print("Persisted array sum = {}".format(dask_arr_persisted.sum().compute()))



if __name__ == "__main__":
    main()

```

#### OUTPUT OF RUNNING SCRIPT ON CLUSTER

```

Shared connection to 54.200.10.20 closed.
Connecting to the Ray cluster...
2021-04-15 05:27:01,085	INFO worker.py:655 -- Connecting to existing Ray cluster at address: 10.0.0.127:6379
Ray cluster resources ! = {'node:10.0.0.127': 1.0, 'object_store_memory': 120000000000.0, 'memory': 136994909184.0}
Dask array = {('ones-06ea498ec1b2d91dc63036887fc5bebd', 0): (functools.partial(<function broadcast_trick.<locals>.inner at 0x7fe8418dcb00>, dtype=dtype('float64')), (10000,))}
Result from persist = {('ones-06ea498ec1b2d91dc63036887fc5bebd', 0): ObjectRef(f214a313eab94086ffffffffffffffffffffffff0200000001000000)}
2021-04-15 05:27:01,180	WARNING worker.py:1086 -- The actor or task with ID f214a313eab94086ffffffffffffffffffffffff02000000 cannot be scheduled right now. It requires {CPU: 1.000000} for placement, however the cluster currently cannot provide the requested resources. The required resources may be added as autoscaling takes place or placement groups are scheduled. Otherwise, consider reducing the resource requirements of the task.
Traceback (most recent call last):
  File "/root/demo_script_dask_on_ray.py", line 33, in <module>
    main()
  File "/root/demo_script_dask_on_ray.py", line 23, in main
    print("Persisted array sum = {}".format(dask_arr_persisted.sum().compute()))
  File "/opt/amazon/lib/python3.7/site-packages/dask/base.py", line 167, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/opt/amazon/lib/python3.7/site-packages/dask/base.py", line 447, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/amazon/lib/python3.7/site-packages/dask/threaded.py", line 84, in get
    **kwargs
  File "/opt/amazon/lib/python3.7/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/opt/amazon/lib/python3.7/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/opt/amazon/lib/python3.7/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/opt/amazon/lib/python3.7/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/opt/amazon/lib/python3.7/site-packages/dask/core.py", line 121, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/opt/amazon/lib/python3.7/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/opt/amazon/lib/python3.7/site-packages/dask/optimization.py", line 1022, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/opt/amazon/lib/python3.7/site-packages/dask/core.py", line 151, in get
    result = _execute_task(task, cache)
  File "/opt/amazon/lib/python3.7/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/opt/amazon/lib/python3.7/site-packages/dask/utils.py", line 31, in apply
    return func(*args, **kwargs)
  File "<__array_function__ internals>", line 6, in sum
  File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2229, in sum
    initial=initial, where=where)
  File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
numpy.AxisError: axis 0 is out of bounds for array of dimension 0


```

### Expected Output

I get the expected output if I do not use `scheduler=ray_dask_get` and instead use  `dask.config.set(scheduler=ray_dask_get)`

```

Shared connection to 54.200.10.20 closed.
Connecting to the Ray cluster...
2021-04-15 05:54:16,998	INFO worker.py:655 -- Connecting to existing Ray cluster at address: 10.0.0.127:6379
Ray cluster resources ! = {'object_store_memory': 120000000000.0, 'node:10.0.0.127': 1.0, 'memory': 136994909184.0}
Dask array = {('ones-06ea498ec1b2d91dc63036887fc5bebd', 0): (functools.partial(<function broadcast_trick.<locals>.inner at 0x7efc2e0a9c20>, dtype=dtype('float64')), (10000,))}
Result from persist = {('ones-06ea498ec1b2d91dc63036887fc5bebd', 0): 
ObjectRef(6665ba672dc799a4ffffffffffffffffffffffff0300000001000000)}
Persisted array sum = 10000.0
Shared connection to 54.200.10.20 closed.

```

- [ yes ] I have verified my script runs in a clean environment and reproduces the issue.
- [ yes ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment] 2021-04-15 05:58
cc @clarkzinzow Isn't this issue fixed by https://github.com/ray-project/ray/issues/14227?

**Comment by clarkzinzow** [comment] 2021-04-15 08:13
In the traceback, it looks like you aren't passing `scheduler=ray_dask_get` to the `.compute()` call, which is required for the persisted Ray objects to get resolved.

```
print("Persisted array sum = {}".format(dask_arr_persisted.sum().compute()
```

Without telling that `.compute()` call to use the Dask-on-Ray scheduler (either explicitly as a kwarg or via the Dask config), it will try to use the local multithreaded Dask scheduler which doesn't know how to handle the Ray object references that were inserted into the Dask graph by the `.persist()` call.

**Comment by rkooo567** [comment] 2021-04-15 22:31
@jennakwon06 Does @clarkzinzow comment resolve your issue?

**Comment by jennakwon06** [comment] 2021-04-16 02:44
Hey @clarkzinzow  - thanks for commenting!


That makes sense. It's strange though since this definitely works for a Ray cluster installed with `pip install -U ray`. Does this mean there's a difference in behavior between the nightly wheel and the official wheel?
 


```
import ray
import dask.array
from ray.util.dask import ray_dask_get

def main():
    print("Connecting to the Ray cluster...")
    ray.init(address="auto")
    print("Ray cluster resources ! = {}".format(ray.available_resources()))

    # Create a Dask array
    dask_array = dask.array.ones(10000)
    print("Dask array = {}".format(dask.base.collections_to_dsk([dask_array])))

    # PERSIST
    # Persist the array on the Ray cluster. Notice that the Ray ObjectRef is inlined.
    # The dask.array.ones() task was submitted to and is running on the Ray cluster.
    dask_arr_persisted = dask_array.persist(scheduler=ray_dask_get)
    print("Result from persist = {}".format(dask.base.collections_to_dsk([dask_arr_persisted])))
    print("Persisted array sum = {}".format(dask_arr_persisted.sum().compute()))


if __name__ == "__main__":
    main()


```


Output

```

Connecting to the Ray cluster...
2021-04-16 02:42:31,409	INFO worker.py:655 -- Connecting to existing Ray cluster at address: 10.0.0.109:6379
Ray cluster resources ! = {'CPU': 32.0, 'memory': 2611.0, 'object_store_memory': 1579.0, 'node:10.0.0.109': 1.0}
Dask array = {('ones-06ea498ec1b2d91dc63036887fc5bebd', 0): (functools.partial(<function broadcast_trick.<locals>.inner at 0x7fb97653f200>, dtype=dtype('float64')), (10000,))}
Result from persist = {('ones-06ea498ec1b2d91dc63036887fc5bebd', 0): array([1., 1., 1., ..., 1., 1., 1.])}
Persisted array sum = 10000.0


```

**Comment by clarkzinzow** [comment] 2021-04-16 04:30
> It's strange though since this definitely works for a Ray cluster installed with pip install -U ray. Does this mean there's a difference in behavior between the nightly wheel and the official wheel?

Hmm that _is_ weird, and shouldn't be the case. If a global or context manager config isn't set, you using the `ray_dask_get` scheduler for the persist and not for the compute should usually fail. 🤔 And you're sure that the returned value from`.compute()` is correct, that the object refs are replaced with their concrete values? I'm wondering if it could have been failing silently before.

**Comment by jennakwon06** [comment] 2021-04-16 04:52
I notice this line `Result from persist = {('ones-06ea498ec1b2d91dc63036887fc5bebd', 0): array([1., 1., 1., ..., 1., 1., 1.])}` which is an output from `print("Result from persist = {}".format(dask.base.collections_to_dsk([dask_arr_persisted])))`. This output does not have `ObjectRef` which is explained in https://docs.ray.io/en/master/dask-on-ray.html . So could it be that `persist`'s scheuler argument never worked with `ray_dask_get`?

**Comment by clarkzinzow** [comment] 2021-04-16 13:49
Ah! I don't think that `.persist()` was supported yet in Dask-on-Ray in the last release, so `.persist()` was equivalent to a `.compute()`! That's why you aren't seeing any object ref futures inlined in the Dask collection, it's computing and materializing the actual concrete values and inlining them.

**Comment by rkooo567** [comment] 2021-11-02 14:59
Looks like the issue is resolved. Please reopen if not!

**Closed** 2021-11-02 14:58 UTC
Labels: bug, P2
