### ISSUE TITLE
Unhandled error messages aren't printed until next interaction with shell

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#14485] opened 2021-03-04 00:42 UTC
If you run something like
```
@ray.remote
def f():
   assert False

f.remote()
```

, the unhandled exception won't actually be printed until you run some other command in the shell like `2 + 2`. It seems the print is stuck behind some lock and isn't runnable immediately.

**Comment by amogkam** [comment] 2021-03-22 17:49
@ericl per @robertnishihara's suggestion, should this be a release blocker?

**Comment by ericl** [comment] 2021-03-22 17:50
No, we are prioritizing this for Q2 though.

**Comment by ericl** [comment] 2021-03-22 20:09
Implementation note: I think the right fix here is to serialize the exception into a plain string on the producer side, and then RAY_LOG(ERROR) it from the core worker instead of calling back into Python land. This will require us to also fix https://github.com/ray-project/ray/issues/12893

**Comment by pcmoritz** [comment] 2021-04-12 17:47
For me the error actually just gets lost, even though I do `2+2` later. I think we should upgrade this to P0 and make it a release blocker, since it is a regression and is pretty bad behavior (error messages getting lost).

**Comment by wuisawesome** [comment] 2021-04-12 18:02
(Adding P1 label back for tracking purposes)

**Comment by stephanie-wang** [comment] 2021-04-13 17:19
@ericl, what do you think we should do here? Does it make sense to revert #14049?

**Comment by ericl** [comment] 2021-04-13 19:34
No, let's fix this in the next release.

**Comment by amogkam** [comment] 2021-04-14 20:37
We are reverting #14049 on the release branch but not on master.

When we make the new patch to fix this issue (https://github.com/ray-project/ray/issues/14485#issuecomment-804360374), we should also try to a unit test for this regression.

**Comment by zhe-thoughts** [comment] 2021-04-14 21:21
And to add some more context (since there has been some iterations on whether this is a release blocker). 

@ericl @robertnishihara @pcmoritz and I had more offline discussion. Based on that, we've decided to treat this issue as a release blocker for 1.3.

**Comment by wuisawesome** [comment] 2021-04-15 01:23
#15287 should fix this in the release branch only. After that's merged, we'll downgrade this back to P1 (but it will be fixed in the release).

**Comment by rkooo567** [comment] 2021-04-15 03:11
Hey @ericl IIUC, we print the exception when the object ref is deleted right? I think the root cause of the exception not being printed is because ipython doesn't GC object reference (it has internal reference to the object reference forever). The reason why it works only for python interactive shell is because python shell only stores the latest ref in the `_` variable. For example, 

```python3
>>> import numpy as np
>>> np.zeros(1000000)
array([0., 0., 0., ..., 0., 0., 0.])
>>> _
array([0., 0., 0., ..., 0., 0., 0.])
>>> 2 + 2
4
>>> _
4
```

**Closed** 2021-04-23 18:00 UTC
Labels: P1, bug, fix-error-msg
