### ISSUE TITLE
[dataset] Dataset pipeline hangs while doing e2e pipelined training

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#18797] opened 2021-09-22 05:22 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

While running dataset pipeline training e2e script, the pipeline seems to be hanging during/after processing epoch 0. We'd expect the script finish the training process.

```
...
(BaseHorovodWorker pid=104893, ip=172.31.58.88) Epoch 0, worker 6 stats over 80 steps: 801.347
(BaseHorovodWorker pid=104893, ip=172.31.58.88) Mean batch wait time: 0.172s +- 0.7031913604343902
(BaseHorovodWorker pid=104893, ip=172.31.58.88) Max batch wait time: 5.332s
(BaseHorovodWorker pid=104893, ip=172.31.58.88) Min batch wait time: 0.049s
(BaseHorovodWorker pid=104893, ip=172.31.58.88) Creating Torch shuffling dataset for worker 6 with 250000 batch size.
(BaseHorovodWorker pid=104892, ip=172.31.58.88) Processing batch 0 in epoch 1 on worker 5.
(BaseHorovodWorker pid=104903, ip=172.31.61.12) Processing batch 80 in epoch 0 on worker 1.
(BaseHorovodWorker pid=104905, ip=172.31.61.12) Processing batch 80 in epoch 0 on worker 3.
(BaseHorovodWorker pid=104867, ip=172.31.53.105)
(BaseHorovodWorker pid=104867, ip=172.31.53.105) Epoch 0, worker 13 stats over 80 steps: 801.39
```
full log:

https://gist.github.com/scv119/067621ba4380b6b300c0feb55a1f16fd
### Reproduction script

using this  [yaml](https://gist.github.com/scv119/e8c6b953759550c4a8a889676f831d50) to start cluster;
and run this script: [e2e.py](https://gist.github.com/scv119/cb1fc9df182c6d44d122fcb18238511f)
with python e2e.py

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by clarkzinzow** [comment] 2021-09-23 01:48
This appears to be caused by uneven trainer shards, which causes Horovod to hang on the optimizer step. Since uneven trainer shards are nonsensical for distributed data-parallel training, I'm closing this issue!

**Closed by clarkzinzow** 2021-09-23 01:48 UTC
Labels: bug, P1, triage
