### ISSUE TITLE
A simple job will hang with raylet

### ISSUE THREAD

**Issue by adoda** [ray-project/ray#3200] opened 2018-11-02 08:01 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Red Hat 4.8.5-4
- **Ray installed from (source or binary)**: source
- **Ray version**: master with commit: e49839c73f16489ed2baef55861e9b4e6e20814d
- **Python version**: python2.7
- **Exact command to reproduce**: execute the simple job in ray cluster

### Describe the problem

We execute a simple job in ray cluster with 3 nodes, each node with resource like:
```
cpu: 10 cores
memory: 30GB
```

The job like:
```
import time
import ray
import os

env_dist = os.environ
redis_address = env_dist.get('REDIS_ADDRESS')

ray.init(redis_address=redis_address)

@ray.remote
def f():
  time.sleep(0.01)
  return ray.services.get_node_ip_address()

# Get a list of the IP addresses of the nodes that have joined the cluster.
ip_list = set(ray.get([f.remote() for _ in range(100000)]))
print("ip_list", ip_list)
```

The job will be hang forever， and will print the info after tens minutes: 
```
The node with client ID 7addcc81bb1ef8d170875e27635197c9b3d680cd has been marked dead because the monitor has missed too many heartbeats from it.
```

We can found some log in raylet_0.err like:
```
W1102 15:20:24.683997   402 node_manager.cc:232] Last heartbeat was sent 562 ms ago
W1102 15:20:36.525331   402 node_manager.cc:232] Last heartbeat was sent 579 ms ago
W1102 15:20:48.447289   402 node_manager.cc:232] Last heartbeat was sent 556 ms ago
F1102 15:21:11.764168   402 node_manager.cc:342]  Check failed: client_id != gcs_client_->client_table().GetLocalClientId() Exiting because this node manager has mistakenly been marked dead by the monitor.
*** Check failure stack trace: ***
    @           0x558b78  google::LogMessage::Fail()
    @           0x558ad4  google::LogMessage::SendToLog()
    @           0x558458  google::LogMessage::Flush()
    @           0x558267  google::LogMessage::~LogMessage()
    @           0x4ca428  ray::RayLog::~RayLog()
    @           0x4f77a2  ray::raylet::NodeManager::ClientRemoved()
    @           0x4a0a71  ray::gcs::ClientTable::HandleNotification()
    @           0x4a131b  _ZNSt17_Function_handlerIFvPN3ray3gcs14AsyncGcsClientERKNS0_8UniqueIDERKSt6vectorI16ClientTableDataTSaIS8_EEEZZNS1_11ClientTable7ConnectERKS8_ENKUlS3_S6_SG_E_clES3_S6_SG_EUlS3_S6_SC_E_E9_M_invokeERKSt9_Any_dataS3_S6_SC_
    @           0x4af27c  _ZZN3ray3gcs3LogINS_8UniqueIDE15ClientTableDataE9SubscribeERKS2_S6_RKSt8functionIFvPNS0_14AsyncGcsClientES6_RKSt6vectorI16ClientTableDataTSaISB_EEEERKS7_IFvS9_EEENKUlRKSsE_clESP_
    @           0x4c5ff9  (anonymous namespace)::ProcessCallback()
    @           0x4c6f18  ray::gcs::SubscribeRedisCallback()
    @           0x510c56  redisProcessCallbacks
    @           0x4c9eb3  RedisAsioClient::handle_read()
    @           0x4ca341  boost::asio::detail::reactive_null_buffers_op<>::do_complete()
    @           0x48b7a1  boost::asio::detail::task_io_service::run()
    @           0x483714  main
    @     0x7f53a10f3b15  __libc_start_main
    @           0x487d09  (unknown)
    @              (nil)  (unknown)
```

This simple job will run ok with the version of ray some weeks ago (without raylet).

And if we decrease the times from 100,000 to 10,000, the job can finished.

**Comment by robertnishihara** [comment] 2018-11-10 23:07
@adoda thanks for reporting the issue! Can you check if this is fixed on the current master now?

**Comment by robertnishihara** [comment] 2018-11-10 23:16
Closing because it works on my laptop.

**Closed by robertnishihara** 2018-11-10 23:16 UTC

**Comment by adoda** [comment] 2018-11-13 01:50
Ok, we will try it with the current master.

**Comment by xutianming** [comment] 2018-11-13 06:38
> @adoda thanks for reporting the issue! Can you check if this is fixed on the current master now?

I tested it with the current master and it works now. Thank you for fixing this.
BTW, what was the root cause for this issue?

**Comment by adoda** [comment] 2018-11-13 08:49
It will work when running with 'for _ in range(100000)' and 'for _ in range(1000000)'.
But when using 'for _ in range(10000000)', we got the exception:
```
The monitor failed with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/ray/monitor.py", line 384, in <module>
    monitor.run()
  File "/opt/conda/lib/python2.7/site-packages/ray/monitor.py", line 321, in run
    self.process_messages()
  File "/opt/conda/lib/python2.7/site-packages/ray/monitor.py", line 251, in process_messages
    message_handler(channel, data)
  File "/opt/conda/lib/python2.7/site-packages/ray/monitor.py", line 213, in xray_driver_removed_handler
    self._xray_clean_up_entries_for_driver(driver_id)
  File "/opt/conda/lib/python2.7/site-packages/ray/monitor.py", line 190, in _xray_clean_up_entries_for_driver
    num_deleted = redis.delete(*keys)
  File "/opt/conda/lib/python2.7/site-packages/redis/client.py", line 937, in delete
    return self.execute_command('DEL', *names)
  File "/opt/conda/lib/python2.7/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 603, in send_packed_command
    (errno, errmsg))
ConnectionError: Error 104 while writing to socket. Connection reset by peer.
```

The log for raylet.WARNING:
```
Log file created at: 2018/11/13 16:23:15
Running on machine: z05b08419.sqa.zth
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W1113 16:23:15.566212   297 node_manager.cc:236] Last heartbeat was sent 690 ms ago
W1113 16:27:11.163815   297 node_manager.cc:236] Last heartbeat was sent 1775 ms ago
W1113 16:32:16.680919   297 node_manager.cc:236] Last heartbeat was sent 578 ms ago
W1113 16:33:55.419119   297 node_manager.cc:236] Last heartbeat was sent 3432 ms ago
W1113 16:34:05.942272   297 node_manager.cc:236] Last heartbeat was sent 806 ms ago
W1113 16:45:54.380439   297 client_connection.cc:110] ServerConnection has 128 buffered async writes
W1113 16:45:54.468716   297 client_connection.cc:110] ServerConnection has 128 buffered async writes
W1113 16:45:54.492759   297 client_connection.cc:110] ServerConnection has 256 buffered async writes
W1113 16:45:54.526021   297 client_connection.cc:110] ServerConnection has 256 buffered async writes
W1113 16:45:54.618288   297 client_connection.cc:110] ServerConnection has 256 buffered async writes
W1113 16:45:54.640764   297 client_connection.cc:110] ServerConnection has 256 buffered async writes
W1113 16:45:54.681093   297 client_connection.cc:110] ServerConnection has 256 buffered async writes
W1113 16:45:54.709389   297 client_connection.cc:110] ServerConnection has 128 buffered async writes
W1113 16:46:01.962538   297 node_manager.cc:236] Last heartbeat was sent 6938 ms ago
```

The log for plasma_store_0.err:
```
/home/admin/xiaoming.xtm/projects/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:1000: Allowing the Plasma store to use up to 20GB of memory.
/home/admin/xiaoming.xtm/projects/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:1030: Starting object store with directory /dev/shm and huge page support disabled
/home/admin/xiaoming.xtm/projects/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 77
/home/admin/xiaoming.xtm/projects/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 77
/home/admin/xiaoming.xtm/projects/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 77
/home/admin/xiaoming.xtm/projects/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 77
```

**Comment by adoda** [comment] 2018-11-14 01:36
So the problem is: the job will keep running when catch an exception, and will hang forever.
Suggestion: the job should be stop when catch an exception, instead of hang forever.

**Comment by robertnishihara** [comment] 2018-11-14 01:53
@adoda, did a Redis server die? Are there any interesting logs for the Redis servers?

Did any processes die? The logs you posted for the plasma store looks fine. For the raylet it looks like something is taking too long, but it doesn't look like anything failed.

**Comment by adoda** [comment] 2018-11-14 09:17
@robertnishihara 
We found no err log for redis.
When we try it again, we got other exception in raylet_0.err:
```
W1114 16:01:55.586911 31609 node_manager.cc:236] Last heartbeat was sent 767 ms ago
W1114 16:04:44.508221 31609 node_manager.cc:236] Last heartbeat was sent 1461 ms ago
W1114 16:10:19.735642 31609 client_connection.cc:240] [worker]ProcessMessage with type 10 took 166 ms.
W1114 16:10:22.821911 31609 client_connection.cc:240] [worker]ProcessMessage with type 10 took 115 ms.
W1114 16:10:29.557688 31609 client_connection.cc:240] [worker]ProcessMessage with type 10 took 227 ms.
W1114 16:10:36.756019 31609 node_manager.cc:236] Last heartbeat was sent 3055 ms ago
W1114 16:25:11.592159 31609 node_manager.cc:236] Last heartbeat was sent 7150 ms ago
W1114 16:38:35.152582 31609 node_manager.cc:236] Last heartbeat was sent 558 ms ago
W1114 16:38:38.313138 31609 client_connection.cc:240] [worker]ProcessMessage with type 10 took 112 ms.
W1114 16:38:38.861243 31609 client_connection.cc:240] [worker]ProcessMessage with type 10 took 125 ms.
W1114 16:38:50.014425 31609 client_connection.cc:240] [worker]ProcessMessage with type 10 took 712 ms.
W1114 16:38:50.021010 31609 node_manager.cc:236] Last heartbeat was sent 753 ms ago
W1114 16:58:38.856142 31609 task_dependency_manager.cc:255] Task lease to renew has already expired by -10275ms
W1114 16:58:38.856261 31609 task_dependency_manager.cc:255] Task lease to renew has already expired by -10274ms
W1114 16:58:38.856292 31609 task_dependency_manager.cc:255] Task lease to renew has already expired by -10274ms
F1114 16:58:38.867553 31609 node_manager.cc:373]  Check failed: client_id != gcs_client_->client_table().GetLocalClientId() Exiting because this node manager has mistakenly been marked dead by the monitor.
*** Check failure stack trace: ***
    @           0x55be58  google::LogMessage::Fail()
    @           0x55bdb4  google::LogMessage::SendToLog()
    @           0x55b738  google::LogMessage::Flush()
    @           0x55b547  google::LogMessage::~LogMessage()
    @           0x4cbd98  ray::RayLog::~RayLog()
    @           0x4fa6e2  ray::raylet::NodeManager::ClientRemoved()
    @           0x4a1c91  ray::gcs::ClientTable::HandleNotification()
    @           0x4a252b  _ZNSt17_Function_handlerIFvPN3ray3gcs14AsyncGcsClientERKNS0_8UniqueIDERKSt6vectorI16ClientTableDataTSaIS8_EEEZZNS1_11ClientTable7ConnectERKS8_ENKUlS3_S6_SG_E_clES3_S6_SG_EUlS3_S6_SC_E_E9_M_invokeERKSt9_Any_dataS3_S6_SC_
    @           0x4b0b5c  _ZZN3ray3gcs3LogINS_8UniqueIDE15ClientTableDataE9SubscribeERKS2_S6_RKSt8functionIFvPNS0_14AsyncGcsClientES6_RKSt6vectorI16ClientTableDataTSaISB_EEEERKS7_IFvS9_EEENKUlRKSsE_clESP_
    @           0x4c7eb9  (anonymous namespace)::ProcessCallback()
    @           0x4c8878  ray::gcs::SubscribeRedisCallback()
    @           0x5131d6  redisProcessCallbacks
    @           0x4cb823  RedisAsioClient::handle_read()
    @           0x4cbcb1  boost::asio::detail::reactive_null_buffers_op<>::do_complete()
    @           0x48b9a1  boost::asio::detail::task_io_service::run()
    @           0x48412a  main
    @     0x7f8e155d1b15  __libc_start_main
    @           0x4887e9  (unknown)
    @              (nil)  (unknown)
```
The log for plasma_store_0.err:
```
/home/admin/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:1000: Allowing the Plasma store to use up to 20GB of memory.
/home/admin/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:1030: Starting object store with directory /dev/shm and huge page support disabled
/home/admin/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 63
/home/admin/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 63
/home/admin/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 12
/home/admin/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 19
/home/admin/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 44
/home/admin/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 40
/home/admin/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 62
/home/admin/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 32
/home/admin/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 47
/home/admin/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 48
/home/admin/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 28
/home/admin/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 23
/home/admin/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 61
/home/admin/ray-test/build/external/arrow/src/arrow_ep/cpp/src/plasma/store.cc:609: Disconnecting client on fd 15
```

Screen display:
```
The node with client ID 5eca3de7fb06adaa972b3adb70061131989cdff7 has been marked dead because the monitor has missed too many heartbeats from it.
The monitor failed with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/ray/monitor.py", line 384, in <module>
    monitor.run()
  File "/opt/conda/lib/python2.7/site-packages/ray/monitor.py", line 321, in run
    self.process_messages()
  File "/opt/conda/lib/python2.7/site-packages/ray/monitor.py", line 251, in process_messages
    message_handler(channel, data)
  File "/opt/conda/lib/python2.7/site-packages/ray/monitor.py", line 213, in xray_driver_removed_handler
    self._xray_clean_up_entries_for_driver(driver_id)
  File "/opt/conda/lib/python2.7/site-packages/ray/monitor.py", line 190, in _xray_clean_up_entries_for_driver
    num_deleted = redis.delete(*keys)
  File "/opt/conda/lib/python2.7/site-packages/redis/client.py", line 937, in delete
    return self.execute_command('DEL', *names)
  File "/opt/conda/lib/python2.7/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/opt/conda/lib/python2.7/site-packages/redis/connection.py", line 603, in send_packed_command
    (errno, errmsg))
ConnectionError: Error 104 while writing to socket. Connection reset by peer.
```
No other useful log. And the job will hang forever.

**Comment by adoda** [comment] 2018-11-14 10:23
When I start head node with '--num-redis-shards=3', the job will finished. So I think the redis is the bottleneck when we start 10,000,000 tasks parallel. 
But now I got a log when job finished, like:
```
Exception in thread ray_push_profiling_information (most likely raised during interpreter shutdown):
```
Any suggestion for this? @robertnishihara

**Comment by robertnishihara** [comment] 2018-11-17 18:44
I think that last error is innocuous. The job should have run successfully.
