### ISSUE TITLE
[Dashboard] shows nothing

### ISSUE THREAD

**Issue by linshuxi** [ray-project/ray#41081] opened 2023-11-11 06:01 UTC
### What happened + What you expected to happen

Ray Dashboard shows nothing, and the dashboard log information is:

Traceback (most recent call last):
  File "D:\xx\python\lib\site-packages\ray\dashboard\modules\reporter\reporter_agent.py", line 1132, in _perform_iteration
    stats = self._get_all_stats()
  File "D:\xx\python\lib\site-packages\ray\dashboard\modules\reporter\reporter_agent.py", line 647, in _get_all_stats
    "workers": self._get_workers(),
  File "D:\xx\python\lib\site-packages\ray\dashboard\modules\reporter\reporter_agent.py", line 529, in _get_workers
    w.as_dict(
  File "D:\xx\python\lib\site-packages\ray\thirdparty_files\psutil\__init__.py", line 530, in as_dict
    raise ValueError("invalid attr name%s %s" % (
ValueError: invalid attr name 'num_fds'
2023-11-11 13:13:50,986	ERROR reporter_agent.py:1149 -- Error publishing node physical stats.

### Versions / Dependencies

Ray 2.8.0

### Reproduction script

ray start --head  --temp-dir=D:\\xx\\tmp --include-dashboard=true

### Issue Severity

None

**Comment by gentleman-turk** [comment] 2023-11-14 15:08
I'm having a similar issue with the dashboard. The resources in the static folder are returning 403: main.4e04a38d.js and main.388a904b.css

**Comment by mattip** [comment] 2023-11-27 17:12
Duplicate of 41388

**Comment by peytondmurray** [comment] 2023-11-28 18:59
Closing as complete with #41388. Please reopen if the issue persists.

**Closed by peytondmurray** 2023-11-28 18:59 UTC
Labels: bug, triage, windows, QS
