### ISSUE TITLE
[job] If runtime_env isn't specified for job, don't use any runtime_env for the supervisor actor/job driver.

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#32750] opened 2023-02-22 21:19 UTC
<img width="385" alt="image" src="https://user-images.githubusercontent.com/74173148/220761171-90542a2b-5204-41da-bfab-5356c09425b3.png">

**Comment by iycheng** [comment] 2023-02-23 02:17
Run the test in cmd mode and the regression just disappeared. So worker prestart not working in job is the root cause.

**Comment by scv119** [comment] 2023-02-24 07:35
Blocked by test infra.

**Comment by scv119** [comment] 2023-02-24 07:36
https://github.com/anyscale/product/issues/17926

**Comment by scv119** [comment] 2023-03-01 22:01
As we concluded we shouldn't use runtime env if runtime_env is not specified.

**Comment by scv119** [comment] 2023-03-01 22:04
a little bit more tenxt
We are running release test to benchmark Ray's performance and we noticed a recent regression in one of our release tests, namely [test_many_actors](https://sourcegraph.com/github.com/ray-project/ray/-/blob/release/benchmarks/distributed/test_many_actors.py?subtree=true). This test measures how fast we can launch 10000 actors in a 64 nodes cluster, and the performance has regressed from 700/seconds to 200/seconds.


The two runs that have regressions are the following:



2023-02-21 00:13:42 | many_actors | core-scalability-test | core | false | finished | 0 | https://s3-us-west-2.amazonaws.com/ray-wheels/master/3ef2c639c04ad09353944ae1f15681d066333344/ray-3.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl | 1037.985487971 | https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_hiubz54beax6pxr1rqar842dyb | true | https://buildkite.com/ray-project/release-tests-branch/builds/1406#018670dd-a145-4c2b-ac2e-ca649cf517b4 | {"actors_per_second":234.67274630550796,"num_actors":10000,"time":42.61253237724304,"success":"1","_peak_memory":6.23,"_peak_process_memory":"PID\tMEM\tCOMMAND\n381\t1.65GiB\t/home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/gcs/gcs_server --log_dir=/tmp/ray/s\n2262\t0.88GiB\tpython distributed/test_many_actors.py\n564\t0.46GiB\t/home/ray/anaconda3/bin/python /home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/dashboa\n22\t0.09GiB\t/home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/anyscale session web_terminal_server --deploy\n1072\t0.09GiB\t/home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/agen\n2564\t0.09GiB\tray::DashboardTester.run\n1656\t0.07GiB\tray::JobSupervisor\n12\t0.06GiB\t/home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/jupyter-notebook --allow-root --NotebookApp.t\n2407\t0.06GiB\tray::MemoryMonitorActor.run\n491\t0.05GiB\t/home/ray/anaconda3/bin/python -m ray.util.client.server --address=10.0.18.62:6379 --host=0.0.0.0 --","perf_metrics":[{"perf_metric_name":"actors_per_second","perf_metric_value":234.67274630550796,"perf_metric_type":"THROUGHPUT"},{"perf_metric_name":"dashboard_p50_latency_ms","perf_metric_value":5.911,"perf_metric_type":"LATENCY"},{"perf_metric_name":"dashboard_p95_latency_ms","perf_metric_value":213.008,"perf_metric_type":"LATENCY"},{"perf_metric_name":"dashboard_p99_latency_ms","perf_metric_value":956.319,"perf_metric_type":"LATENCY"}],"_dashboard_test_success":true,"_dashboard_memory_usage_mb":501.878784} |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2023-02-18 02:17:00 | many_actors | core-scalability-test | core | false | finished | 0 | https://s3-us-west-2.amazonaws.com/ray-wheels/master/edf9906455d850dfb32d782a5da5a8aad2cde4fe/ray-3.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl | 1173.823233178 |   | true | https://buildkite.com/ray-project/release-tests-branch/builds/1404#0186616e-f50f-48a4-8ac3-7b94e47a7bd4 | {"actors_per_second":782.5864484509568,"num_actors":10000,"time":12.778141021728516,"success":"1","_peak_memory":3.54,"_peak_process_memory":"PID\tMEM\tCOMMAND\n291\t1.7GiB\t/home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/gcs/gcs_server --log_dir=/tmp/ray/s\n2439\t0.85GiB\tpython distributed/test_many_actors.py\n464\t0.32GiB\t/home/ray/anaconda3/bin/python /home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/dashboa\n47\t0.09GiB\t/home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/anyscale session web_terminal_server --deploy\n765\t0.08GiB\t/home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/agen\n2661\t0.08GiB\tray::DashboardTester.run\n44\t0.06GiB\t/home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/jupyter-notebook --NotebookApp.token=aph0_Ckc\n2575\t0.06GiB\tray::MemoryMonitorActor.run\n391\t0.05GiB\t/home/ray/anaconda3/bin/python -m ray.util.client.server --address=172.31.196.86:9031 --host=0.0.0.0\n663\t0.05GiB\t/home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/log_m","perf_metrics":[{"perf_metric_name":"actors_per_second","perf_metric_value":782.5864484509568,"perf_metric_type":"THROUGHPUT"},{"perf_metric_name":"dashboard_p50_latency_ms","perf_metric_value":15.888,"perf_metric_type":"LATENCY"},{"perf_metric_name":"dashboard_p95_latency_ms","perf_metric_value":1455.137,"perf_metric_type":"LATENCY"},{"perf_metric_name":"dashboard_p99_latency_ms","perf_metric_value":3902.263,"perf_metric_type":"LATENCY"}],"_dashboard_test_success":true,"_dashboard_memory_usage_mb":527.310848} | https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_e4812113rs9v9gi2t6ufvldg2b



As we can notice the first run is using jobs and performance is around 234.67274630550796, where the second run has performance around 782.5864484509568.

There are two difference between these two runs:
1. the regressed one is on new stack using jobs, while the second run is running the test in a driver script
2. they are using different ray wheels; however as we compare the two ray wheels used, it's unlikely any change here will cause the regression:
```
git log edf9906455d850dfb32d782a5da5a8aad2cde4fe..3ef2c639c04ad09353944ae1f15681d066333344 --oneline
3ef2c639c0 Added a blog example for MMT in the use cases (#32647)
554840c9db [Core][C++ Worker] libray_api.so exports absl::flag symbols (#32648)
adf2b92afc [Release] Update paging Anyscale API call to fix OSS release tests (#32679)
acfc7626da [Release] Migrate (almost all, but 10) remaining Release Tests to Anyscale Jobs (#32616)
50045b610e [RLlib] Move Models + ActorCriticEncoder + Tests (#32453)
c6fe4bf51e [RLlib] Consolidate the API for both Tf and Torch PPO Learner (#32609)
7bf2431ebc [Serve] Multi app deploy improvements (route check & deployment clean up) (#32225)
```
Also as reported by @iycheng in https://github.com/ray-project/ray/issues/32750, he confirmed if we run without jobs there is no regression.

**Comment by scv119** [comment] 2023-03-01 22:08
@edoakes to triage

**Comment by gvspraveen** [comment] 2023-03-01 22:11
cc @akshay-anyscale

**Comment by architkulkarni** [comment] 2023-03-02 18:47
> > I think we should treat this as a pure OSS issue -- if you don't specify a runtime_env we pass in an empty runtime_env to the Ray job submission API. We should do the following in open source :
> 
> > [short term] If runtime_env isn't specified for job, don't use any runtime_env for the supervisor actor/job driver.
> > [long term] Fix the performance issues for runtime_env.

@scv119 should the short-term optimization be cherry picked into 2.3.1? cc @zhe-thoughts

**Comment by architkulkarni** [comment] 2023-03-02 19:01
Even if the user doesn't specify a runtime_env, we currently use the `env_vars` field of `runtime_env` to set the `RAY_ADDRESS` env var in the job entrypoint command.  For this part, we'll need some workaround that doesn't use `runtime_env`.  

One option is for Ray Jobs to prepend `RAY_ADDRESS=[...]` to the job entrypoint command.

**Comment by architkulkarni** [comment] 2023-03-02 19:15
Ah never mind, we don't set `NOSET_CUDA_VISIBLE_DEVICES` in the driver runtime_env, we only set it in the supervisor actor runtime_env, which won't affect many_tasks performance.

In summary, this should be an easy fix, don't see any issues

**Comment by architkulkarni** [comment] 2023-03-03 17:23
Hi @iycheng @scv119 @edoakes, sorry for the unrelated rambling earlier, but I think we *are* actually specifying a nonempty runtime_env in the release test that uses Jobs (we're specifying the `working_dir` which contains the script):

`"working_dir": "s3://ray-release-automation-results/working_dirs/many_actors/uiqstegauu/_anyscale_pkg_129811e2e486faca150426d69544bf7a.zip"`

This runtime_env will then be inherited by all the tasks and actors.  (If the Job runtime env were empty, then the tasks/actors would have an empty runtime env too.)

In particular I ran the repro on a 64 node cluster and got the following results, you can see there's no difference:

```
python test_many_actors.py:
548, 528 actors/sec
ray job submit -- python test_many_actors.py:
537, 537 actors/sec
```
 
So it's a regression from the non-Jobs workflow to the Jobs workflow, because our recommended Jobs workflow is to specify a `working_dir` for your Ray Job (`ray job submit --working-dir my_script_dir -- python my_script.py`), since that's how you get the script on the cluster. But this has always been the case for Jobs, so it's not a regression between Ray versions.

I don't see a short term fix for this unless we introduce some new API or semantics to only install the specified runtime_env in the job supervisor actor (the entrypoint script), and not have it inherited by all the tasks and actors.

To fix the numbers, you could potentially change the release test infra to not use a `working_dir` and instead use the test script from the `/ray/release` directory which already exists on the cluster nodes, but this doesn't fix the user side issue.

Any thoughts about this? Should we just do the long term fix?

**Comment by rickyyx** [comment] 2023-03-09 22:16
Just adding more context, seems multiple tests regressed rather than just the actors:
![image](https://user-images.githubusercontent.com/11676094/224172615-b79c5eba-414f-44e8-ad16-3719afc36db3.png)

**Comment by scv119** [comment] 2023-03-14 03:33
will move to use sdk instead of job for performance related release tests if @rkooo567 can't figure it out today :)

**Comment by edoakes** [comment] 2023-03-16 15:10
@scv119 my understanding is that `ray job submit -- python my_script.py` doesn't specify a runtime_env for the driver or tasks/actors unless the user does.

Regardless, I still don't see how this would be a long term fix -- many of our users are using runtime_env as the recommended way to package their code, so those benchmarks/tests that matter.

**Closed** 2023-03-17 06:03 UTC
Labels: P0

**Comment by rkooo567** [comment] 2023-03-17 06:11
We temporarily migrated to V1 + sdk runner (which recovers the stats). I will wait for a few more days to verify (I verified from the release tests, but just in case). The issue is created to migrate back to V2 https://github.com/ray-project/ray/issues/33414. We should do this asap since V1 won't be available soon.
