### ISSUE TITLE
[CI] `linux://python/ray/data:tests/test_dataset` failure due to not able to ray.init() the cluster

### ISSUE THREAD

**Issue by jianoaix** [ray-project/ray#33079] opened 2023-03-06 23:40 UTC
On master, this test failed when calling `ray.init(num_cpus=8)`, and it complained that it's connecting to an existing cluster. This however should not be the case, as we defensively called `ray.shutdown()` before calling ` ray.init(num_cpus=8)`.

CI link: https://buildkite.com/ray-project/oss-ci-build-branch/builds/2591#_

```
shutdown_only = None, block_split = False
tmp_path = PosixPath('/tmp/pytest-of-root/pytest-3/test_bulk_lazy_eval_split_mode0')

    @pytest.mark.parametrize("block_split", [False, True])
    def test_bulk_lazy_eval_split_mode(shutdown_only, block_split, tmp_path):
        # Defensively shutdown Ray for the first test here to make sure there
        # is no existing Ray cluster.
        ray.shutdown()
    
>       ray.init(num_cpus=8)

python/ray/data/tests/test_dataset.py:65: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/ray/python/ray/_private/client_mode_hook.py:105: in wrapper
    return func(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

address = None, num_cpus = 8, num_gpus = None, resources = None
object_store_memory = None, local_mode = False, ignore_reinit_error = False
include_dashboard = None, dashboard_host = '127.0.0.1'
....
            # In this case, we are connecting to an existing cluster.
            if num_cpus is not None or num_gpus is not None:
                raise ValueError(
>                   "When connecting to an existing cluster, num_cpus "
                    "and num_gpus must not be provided."
                )
E               ValueError: When connecting to an existing cluster, num_cpus and num_gpus must not be provided.

/ray/python/ray/_private/worker.py:1465: ValueError
```

**Comment by DaeSeokSong** [comment] 2023-03-30 07:32
> ValueError: When connecting to an existing cluster, num_cpus and num_gpus must not be provided.

In my case, this error is solved by "ray stop" in CLI

**Comment by c21** [comment] 2023-03-30 08:07
btw the issue is already resolved. Closing this issue.

**Closed by c21** 2023-03-30 08:07 UTC
Labels: P0, datasets
