### ISSUE TITLE
[release test] train_pytorch_linear_test hangs since Monday 2/21

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#22595] opened 2022-02-23 16:15 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Train

### What happened + What you expected to happen

fail: https://buildkite.com/ray-project/periodic-ci/builds/2877#7efe4aca-68fd-414f-9798-153a692cebd2
success: https://buildkite.com/ray-project/periodic-ci/builds/2841#9b925354-82d8-46bd-864b-508db98904db

the successful training finishes around 5min. The failed one reaches test timeout of 2 hours.

### Versions / Dependencies

master

### Reproduction script

NA

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xwjiang2010** [comment] 2022-02-23 19:10
On Monday it shows up as:

https://buildkite.com/ray-project/periodic-ci/builds/2869#be927d3d-5c9c-41aa-b468-1aa5fa465904 and https://buildkite.com/ray-project/periodic-ci/builds/2869#88167da2-2a9d-412e-81a1-dd3a433773dc

The cluster was running for > 10 hours and training is not yet finished.

**Comment by matthewdeng** [comment] 2022-02-23 22:54
From an initial glance I wasn't able to tell exactly where it's hanging. This test does run successfully on a single node in CI, so my current hunch is that it has to do something with the setup of the release tests. I'll spin up a cluster and see if I can reproduce. May be related to [this line](https://sourcegraph.com/github.com/ray-project/ray/-/blob/release/ml_user_tests/train/train_torch_linear_test.py?L20:56), though the Ray Lightning test which also sets this doesn't run into the same issue.

**Comment by amogkam** [comment] 2022-02-23 23:32
@xwjiang2010 and I just looked into it- there's something very weird going on. 3 of the workers are executing the training function and are blocked in DistributedDataParallel initializing, waiting for the other 3 workers. The other 3 workers are not actually executing any methods. Logs don't show any error or anything out of the ordinary.

This test was passing on Sunday though, so I am trying to reproduce a successful run with an older commit.

**Comment by matthewdeng** [comment] 2022-02-23 23:41
Hmm did the version of `torch` change?

**Comment by amogkam** [comment] 2022-02-23 23:42
no its been 1.9.0...we're thinking it's a change with ray core

**Comment by amogkam** [comment] 2022-02-24 00:21
Ok this runs successfully on commit 29d94a22114b02adfd3745c4991a3ce70592dd16

**Comment by xwjiang2010** [comment] 2022-02-24 06:51
Update: reverting runtime env fixes the test: https://buildkite.com/ray-project/periodic-ci/builds/2890#05a9ce04-e2a9-4b4e-8b2f-25ba63f3053d

**Comment by xwjiang2010** [comment] 2022-02-24 15:25
Porting over discussion from https://github.com/ray-project/ray/pull/22615

@SongGuyang See [here](https://sourcegraph.com/github.com/ray-project/ray/-/blob/python/ray/train/trainer.py?L197) for how runtime_env is used internally in Ray Train.

Also @edoakes @architkulkarni Could we add CI tests to catch regressions like this?

**Comment by xwjiang2010** [comment] 2022-02-24 17:07
Do we have a doc that discusses why one behavior is more favorable than the other?
Also isn't this a breaking change to existing customers? (Ray Train may not be the only one here...)

**Comment by edoakes** [comment] 2022-02-24 18:01
@matthewdeng @xwjiang2010 yes this is a breaking change that was merged without a deprecation plan or communication to users (this is my fault, I didn't review the PR). There's an [RFC](https://github.com/ray-project/ray/issues/21818) with discussion about the behavior.

We will revert the change and leave the behavior as-is for now and independently consider if we will make the behavior change at all (maybe for Ray 2.0?). If we do, I will let you know in advance.

**Comment by matthewdeng** [comment] 2022-02-24 19:55
@edoakes thanks that sounds good to me!

For what it's worth I do personally prefer the new behavior as it is just simpler and does have the ability to support the legacy behavior. Maybe another way to handle the rollout is to add a flag to control the behavior, and change the default value in a future release.

**Comment by xwjiang2010** [comment] 2022-02-24 20:28
@edoakes This is really helpful, thank you!

I see there are some discussions on the PR for a warning msg for API behavior change. However, we didn't catch anything mentioning runtime env from log output when debugging this issue. It could be that we are missing something in our debug flow. 

I have prepared a revert PR but if the team thinks fix forward is better, we can also do that.

**Comment by edoakes** [comment] 2022-02-24 21:28
@xwjiang2010 there wasn't an warning added AFAICT, let's go ahead with the revert and if we re-introduce we will do it more smoothly :)

**Comment by architkulkarni** [comment] 2022-02-24 21:57
There's a warning of the form `[2022-02-24 10:00:38,165 W 632 668] core_worker.cc:1425: Runtime env already exists and the parent runtime env is {"envVars": {"SERVE_ENABLE_SCALING_LOG": "1"}}. It will be overridden by {"envVars": {"SERVE_ENABLE_SCALING_LOG": "1"}}.
` but this was hidden in the `python-core-worker` logs rather than being streamed to the driver.  We'll make it more visible if we reintroduce it!

**Comment by SongGuyang** [comment] 2022-02-25 02:17
Sorry for this break and agree to revert my PR first. I think we already discuss this change enough in ray core team. But it is really hard to push a backwards incompatible change even though I pretty strong ensure the current runtime_env inheritance logic is not reasonable. 

And sorry for the invisible warning log which make you hard to identify the root cause commit. We should add a user level log in future PR.

@edoakes @architkulkarni let's discuss about how to push this refactor feature in slack and sync the plan to ray train team later.

By the way, my time zone is UTC+8 so I'm late to reply this issue. 😓

**Closed** 2022-04-07 18:47 UTC
Labels: bug, triage
