### ISSUE TITLE
[ml] release test failure: long_running_distributed_pytorch_pbt_failure

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#34258] opened 2023-04-11 05:01 UTC
### What happened + What you expected to happen

Seems like it has been flakey for a while, may / may not be release blocker

<img width="1303" alt="Screen Shot 2023-04-10 at 9 58 26 PM" src="https://user-images.githubusercontent.com/22830327/231060721-85b2f910-6ec3-4c92-965b-3c629db4f60f.png">

### Versions / Dependencies

master

### Reproduction script

https://buildkite.com/ray-project/release-tests-branch/builds/1517#018748a8-f793-4958-97de-b9be27c4bab3

### Issue Severity

None

**Comment by clarng** [comment] 2023-04-11 05:02
tagging ml oncall

**Comment by xwjiang2010** [comment] 2023-04-11 14:45
Actually I captured some initial learnings here: https://github.com/ray-project/ray/issues/34197

@clarng do you have any suggestions looking into the object store memory issue? 

Unfortunately, with lots of infra migrations in our release test, I can't seem to compare with the last successful run. What I am curious about is why the consistent object store memory grow. It's hard for me to tell whether this is release blocking or not without understanding that.

**Comment by hora-anyscale** [comment] 2023-04-14 20:21
closing as dupe of https://github.com/ray-project/ray/issues/34197

**Closed by hora-anyscale** 2023-04-14 20:21 UTC
Labels: bug, triage
