### ISSUE TITLE
ray on windows docker containers not able to connect with each other  

### ISSUE THREAD

**Issue by manishagarwal23** [ray-project/ray#11211] opened 2020-10-05 10:00 UTC
Discussion on slack now being continued as a bug .
Problem: I have 2 windows machine running docker . inside each docker 1 container of head and 1 container of ray worker are running . We tried to connect redis it cold connect .  but the dahboard says 0 workers /2cores . Also jobs are not scheduled on the worker node . 

I was asked to install latest nightly pf ray . unfortunately i get the following error on trying 

(app-root) sh-4.2# ray install-nightly
Running: /opt/app-root/bin/python3 -m pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp36-cp36m-manylinux1_x86_64.whl.
Collecting ray==1.0.0
  ERROR: HTTP error 404 while getting https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp36-cp36m-manylinux1_x86_64.whl
ERROR: Could not install requirement ray==1.0.0 from https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp36-cp36m-manylinux1_x86_64.whl because of HTTP error 404 Client Error: Not Found for url: https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp36-cp36m-manylinux1_x86_64.whl for URL https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp36-cp36m-manylinux1_x86_64.whl
Traceback (most recent call last):
  File "/opt/app-root/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/opt/app-root/lib/python3.6/site-packages/ray/scripts/scripts.py", line 1445, in main
    return cli()
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/ray/scripts/scripts.py", line 1404, in install_nightly
    subprocess.check_call(cmd)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/app-root/bin/python3', '-m', 'pip', 'install', '-U', 'https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp36-cp36m-manylinux1_x86_64.whl']' returned non-zero exit status 1.
(app-root) sh-4.2#
(app-root) sh-4.2#
(app-root) sh-4.2#
(app-root) sh-4.2#

**Comment by robertnishihara** [comment] 2020-10-05 13:14
Looks like the file  https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp36-cp36m-manylinux1_x86_64.whl doesn't exist, so `ray install-nightly` is not looking for the right thing.

Might be a bu with `ray install-nightly`.

**Comment by manishagarwal23** [comment] 2020-10-06 14:06
Any plan to fix it or should I go back to 0.8.7 ? What's the best release which works across machines on dockers ??

**Comment by manishagarwal23** [comment] 2020-10-07 11:01
![problem1](https://user-images.githubusercontent.com/6428619/95322354-fce88180-08b9-11eb-9597-9949e58a8661.JPG)


If you see the problem is that in dashboard we can see cpu of worker and RAM details but it still says 0 workers  . redis is able to communicate . 

Loooking only at worker logs 


![workey_raylet 5 err](https://user-images.githubusercontent.com/6428619/95322653-72545200-08ba-11eb-8df1-ff775280d831.JPG)


when we see .err of same fie we see it tries to connect to wrong port of head ode redis 

![workey_raylet 5 out](https://user-images.githubusercontent.com/6428619/95322704-86984f00-08ba-11eb-9eca-b9895e5ca25d.JPG)

**Comment by manishagarwal23** [comment] 2020-10-07 11:07
@rkooo567  @robertnishihara     can you please check once . IF you need any logs please let me know .  2 windows independent machines running dockers . i docker host has ray head running and another docker host has ray worker running  .  they both can ping each other .  The ports of docker are all exposed with host .

**Comment by sumanthratna** [comment] 2020-10-07 14:08
re: `install-nightly` it looks like the 1.0.0 wheels aren't in the s3 bucket anymore (I don't know if they were ever there)
https://github.com/ray-project/ray/blob/a302fb9b6f9240a3d2a969c19e847788fe57001e/python/ray/nightly-wheels.yaml#L1-L4

I think for now we should rebuild 1.0.0 and publish the wheels in the bucket and `install-nightly` should continue to work.

**Comment by rkooo567** [comment] 2020-10-07 16:44
That's not the wrong port. When machines are connected, it should be connected to `gcs_server`, which might run in a different port. You should make sure you specified port number of `--gcs-server` when you run `ray start --head`, and open the port in the docker image.

Also, if `install-nightly` fails, it is probably because our CI failed and didn't push the wheel to a S3 bucket properly.  You can probably try again now.

**Comment by manishagarwal23** [comment] 2020-10-07 17:20
@rkooo567  Yes I already did that . --gcs-server-port 4003 is what is written in the command that I shared above and I exposed all the ports mentioned above on head node. 


But do I need to use the same  port on ray worker too ?? For worker I followed only the command which is printed when I fired the head ray command . Head tells us the command to fire on each worker node.  

Since I am on ray 1.0.0 can you share command for head and worker in case I made a mistake above and I need to explicitly tell on worker .

**Comment by rkooo567** [comment] 2020-10-07 18:21
You are correct that you just need to use the same command it is printed (I realized it is quiet confusing haha..) You can think nodes should be connected to Redis, but when they are actually connected, there's a separate stateless server in front of the Redis (gcs_server). 

So I think what you said is correct. The issue is the raylet trying to connect to a weird address... It should be 6379 or 4003 I think (I am not 100% sure which port it should be in that code path).

Can you do a couple of things for troubleshooting? 

 1. Can you restart the docker container, run `ray stop --force`, and make sure you run gcs_server process running properly on a head node? You can check it using `lsof -i :4003` (gcs_server) and `lsof -i :6379` (redis).

2. After that, can you run (before you connect a worker node) on a head node?
```
ray.init()
print(ray.nodes())
```
?

3. Try connecting the worker, and run the same code on the head node again?

4. Lastly, can you see your head node and see what process is running on a port that failed raylet tries to connect to? In your example, go to the head node and see what's the process that is bound to the port 26048.

**Comment by manishagarwal23** [comment] 2020-10-13 05:09
(app-root) bash-4.2# lsof -i :4003
COMMAND    PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
gcs_serve 1056 root   24u  IPv4 2155484      0t0  TCP *:pxc-splr-ft (LISTEN)
gcs_serve 1056 root   26u  IPv4 2153404      0t0  TCP 3acfa729b090:pxc-splr-ft->3acfa729b090:38514 (ESTABLISHED)
gcs_serve 1056 root   64u  IPv4 2173101      0t0  TCP 3acfa729b090:pxc-splr-ft->3acfa729b090:39176 (ESTABLISHED)
/opt/app- 1070 root   31u  IPv4 2184943      0t0  TCP 3acfa729b090:39176->3acfa729b090:pxc-splr-ft (ESTABLISHED)
raylet    1072 root   19u  IPv4 2184776      0t0  TCP 3acfa729b090:38514->3acfa729b090:pxc-splr-ft (ESTABLISHED)
(app-root) bash-4.2# lsof -i :6379 | grep us
redis-ser 1047 root  174u  IPv4 2096889      0t0  TCP 3acfa729b090:6379->us-manish.office.com:36616 (ESTABLISHED)
redis-ser 1047 root  175u  IPv4 2182487      0t0  TCP 3acfa729b090:6379->us-manish.office.com:36726 (ESTABLISHED)
(app-root) bash-4.2# 



**When i took a look at the worker node and do ps i do not see raylet** 

(app-root) bash-4.2# 
(app-root) bash-4.2# ps -eaf | grep ray 
root        228      1  0 04:35 pts/0    00:00:00 /opt/app-root/lib/python3.6/site-packages/ray/core/src/plasma/plasma_store_server -s /tmp/ray/session_2020-10-13_04-32-25_220205_1043/sockets/plasma_store -m 7372815974 -d /tmp -z
root        230      1  0 04:35 pts/0    00:00:05 /opt/app-root/bin/python3 -u /opt/app-root/lib/python3.6/site-packages/ray/reporter.py --redis-address=172.23.49.92:6379 --port=61526 --metrics-export-port=48905 --redis-password 5241590000000000
root        231      1  0 04:35 pts/0    00:00:11 /opt/app-root/bin/python3 -u /opt/app-root/lib/python3.6/site-packages/ray/log_monitor.py --redis-address=172.23.49.92:6379 --logs-dir=/tmp/ray/session_2020-10-13_04-32-25_220205_1043/logs --redis-password 5241590000000000
root        483     45  0 05:08 pts/1    00:00:00 grep ray
(app-root) bash-4.2# 
(app-root) bash-4.2# 
(app-root) bash-4.2# ps -eaf | grep raylet
root        485     45  0 05:09 pts/1    00:00:00 grep raylet
(app-root) bash-4.2#

**Comment by rkooo567** [comment] 2020-10-13 23:57
@manishagarwal23 Can you check if the node ip address printed from `ray.init` is correct? If so, it will be fixed in the latest wheel.

**Comment by manishagarwal23** [comment] 2020-10-14 05:52
hi @rkooo567   , 

From worker node i tried to do ray init on worker node to connect to a cluster on head node . please see output 

first i tried this 
```
(app-root) bash-4.2# python 
Python 3.6.9 (default, Nov 11 2019, 11:24:16) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray 
>>> ray.init(address='172.23.49.92:6379')
2020-10-14 05:51:26,398	INFO worker.py:634 -- Connecting to existing Ray cluster at address: 172.23.49.92:6379
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1014 05:51:29.408102   612   612 redis_context.cc:303] Failed to connect to Redis, retrying.
W1014 05:51:32.415113   612   612 redis_context.cc:303] Failed to connect to Redis, retrying.
W1014 05:51:35.420097   612   612 redis_context.cc:303] Failed to connect to Redis, retrying.
W1014 05:51:38.426075   612   612 redis_context.cc:303] Failed to connect to Redis, retrying.
```


then i tried to pass pasword still same thing 
```

>>> import ray 
>>> ray.init(address='172.23.49.92:6379',_redis_password='5241590000000000')
2020-10-14 05:48:36,419	INFO worker.py:634 -- Connecting to existing Ray cluster at address: 172.23.49.92:6379
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1014 05:48:39.432098   601   601 redis_context.cc:303] Failed to connect to Redis, retrying.
W1014 05:48:42.438083   601   601 redis_context.cc:303] Failed to connect to Redis, retrying.
W1014 05:48:45.444072   601   601 redis_context.cc:303] Failed to connect to Redis, retrying.

```

**Comment by rkooo567** [comment] 2020-10-14 17:26
Oh, I meant can you run ray start --head in the head node and see if it prints the correct node IP address? If so, using nightly wheel will fix the issue.

**Comment by manishagarwal23** [comment] 2020-10-14 17:32
@rkooo567   intead of host ip (172.23.49.92) it prints local docker ip (172.17.0.3)   .. i suppose thats what the problem is which you stated .. 

can you please write out the command to get the nightly . it will make my life easy please.

(app-root) bash-4.2# ray start --head  --dashboard-host 0.0.0.0 --java-worker-options -1 --object-manager-port 4000  --node-manager-port 4001 --min-worker-port 10000 --max-worker-port 10010  --node-manager-port 4002   --gcs-server-port 4003
Local node IP: 172.17.0.3
2020-10-14 05:47:50,218	INFO services.py:1166 -- View the Ray dashboard at http://172.17.0.3:8265
2020-10-14 05:47:50,221	WARNING services.py:1625 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This may slow down performance! You may be able to free up space by

**Comment by rkooo567** [comment] 2020-10-14 17:40
Here is the instruction.https://docs.ray.io/en/master/installation.html#latest-snapshots-nightlies

Btw, I have some confusion here. You would like to connect to the head docker, not the host machine. Why do you try to connect to the head machine IP in this case?

**Comment by rkooo567** [comment] 2020-10-14 17:40
I think if you pass the head node docker IP instead of the host IP to `address` field, it might be resolved.

**Comment by manishagarwal23** [comment] 2020-10-14 17:45
i have 2 linux machines in my office premise and both have individual docker containers . The host and dockers conatiners have ports exposed via --network host . Hence i used the ip of the host and  the local docker ips wont be known to the remote machine .

**Comment by ijrsvt** [comment] 2020-10-14 18:35
@manishagarwal23 can you try two things:
1. Open up python and run the following two things:
```
from ray.services import get_node_ip_address
get_node_ip_address()
```

2. Try running `ray start --head ...` with the additional argument of `--node-ip-address=172.23.49.92`

**Comment by rkooo567** [comment] 2020-10-16 21:57
This is resolved by 1:1.

**Closed** 2020-10-16 21:57 UTC
Labels: P2, bug
