### ISSUE TITLE
very slow serializing data (ray.put)

### ISSUE THREAD

**Issue by virtualluke** [ray-project/ray#907] opened 2017-09-01 11:37 UTC
setup: ray 0.2.0 on a centos 7 cluster of 10 machines (56 cores, 256GB ram each, glusterfs), all stock ray parameters.

I have noticed extremely slow times at the end of a remote function returning a dict (which is in the 5-10 MB range).  I haven't tested different sizes.  It takes minutes to return.  Or more specifically I can see that the ray.put(dict) of this size in the routine causes that much delay.  

To test instead of returning the dict I pickled it to our glusterfs and picked it up in the returning function and unpickled it and that was very fast. (ray return well over a minute, pickle/unpickle to filesystem closer to 1 second.)

This seems like a serious issue as I don't want to pickle to disk whenever returning an object of any non-trivial size.

thoughts? I am not sure how to instrument more or how to perhaps log more in the ray infrastructure but am happy to test various things.

Is this perhaps related to https://issues.apache.org/jira/browse/ARROW-1282 ?

thanks,
Luke

**Comment by pcmoritz** [comment] 2017-09-01 16:18
Hey Luke,

thanks for reporting this! This is indeed a serious issue. I haven't been able to reproduce it yet, can you describe the workload that you are running in a little more detail? The size of the object store is 128GB I assume, what is the size of the objects in there, how does the dict look like that you are putting in?

Is it possible to have a small script that reproduces the problem? That's be most helpful for us.

-- Philipp.

**Comment by virtualluke** [comment] 2017-09-01 17:01
I will try to come up with a small set of code to reproduce the issue.

In the meantime:
python 3.6.1, Anaconda latest (4.4.0)

We have just started using ray a few weeks back and this was the real first test (which is after we had upgraded to 0.2.0) so I can't say if it was in a previous version.

**Comment by robertnishihara** [comment] 2017-09-01 17:44
@virtualluke It may be easier to reproduce the problem by manually calling `ray.put(obj)` and seeing how long that takes.

**Comment by virtualluke** [comment] 2017-09-01 18:03
ok, was able to reproduce with some simple code:
```
@ray.remote
def worker(j):
   dict_test = {}
   for i in range(100000):
        dict_test[i] = ["test","test","test","test","test"]

    return(dict_test)

ray.init(redis_address="10.1.2.3:6379")
results = ray.get([worker.remote(i) for i in range(100)])
```
On my cluster that version takes 38 seconds to complete.  If instead in the worker I pickle the dict to a file and return the file name and then in the main program unpickle the files the whole program takes 10 seconds.

**Comment by robertnishihara** [comment] 2017-09-01 20:47
At first I thought the problem was #319 (also https://issues.apache.org/jira/browse/ARROW-1382), since all of the strings are the same.

But then I tried making all of the strings different and it looks like the problem is still there. We'll need to profile this, thanks for bringing it up!

```python
import ray
import pickle

ray.init()

val = ["test" + str(i) for i in range(10 ** 6)]

%time s1 = pickle.dumps(val)  # 243ms

%time s2 = ray.put(val)  # 2min 31s!!!
```

These numbers are very surprising.

**Comment by virtualluke** [comment] 2017-09-01 21:04
We were very surprised as well, pickling to disk on the returns reminded me too much of old school MR.

**Comment by pcmoritz** [comment] 2017-09-01 21:08
As a workaround, consider this:

```
import ray
import pickle

ray.init()

val = ["test" + str(i) for i in range(10 ** 6)]

%time s1 = pickle.dumps(val)  # 214ms

import numpy as np

val2 = np.array(val)

%time s2 = ray.put(val2) # 172 ms
```

**Comment by virtualluke** [comment] 2017-09-01 21:29
I thought under the hood basically you were pickling and sending to redis, so should be a lot faster than persisting to a distributed FS.

The above work around works for things that easily fit into a np.array at least.

**Comment by robertnishihara** [comment] 2017-09-01 21:38
So, under the hood we are serializing it using our own serialization library which maps Python objects to the Apache Arrow format (not using pickle), and we're copying it into our shared memory object store (not Redis).

This approach seems to be working really well for objects that contain large numpy arrays, but it looks like it's not working for lists of strings.

**Comment by robertnishihara** [comment] 2017-09-01 23:32
Ok, I'm not sure what the problem is yet, but it should go away soon once we start using the latest version of Arrow.

Using the Arrow master, I see the following.

First starting the object store with

```
./plasma_store -s /tmp/plasmastore1 -m 1000000000
```

Then in Python

```python
import pyarrow.plasma as plasma

plasma_client = plasma.connect('/tmp/plasmastore1', '', 0)

original_object = ["test" + str(i) for i in range(1000000)]

%time object_id = plasma_client.put(original_object)  # 74ms

%time result = plasma_client.get(object_id)  # 251 ms
```

**Comment by virtualluke** [comment] 2017-09-01 23:47
that's great news.

**Comment by pcmoritz** [comment] 2017-09-01 23:58
Concretely it will be fixed when we merge https://github.com/ray-project/ray/pull/910

**Comment by robertnishihara** [comment] 2017-09-05 06:01
This is fixed in the master branch by #910.

**Closed by robertnishihara** 2017-09-05 06:01 UTC

**Comment by virtualluke** [comment] 2017-09-05 12:24
thanks for the work.  Is there a CI whl built in this project or nightly build whl that I could test against?

**Comment by robertnishihara** [comment] 2017-09-05 17:57
Not yet, we're already building them in Travis so it's just a matter of uploading them somewhere (maybe bintray or S3) #853. I'd like to do this soon..

Does building Ray from source work for you? If you have docker installed you can build the wheels manually using the instructions in https://github.com/ray-project/ray/blob/master/python/README-building-wheels.md.

**Comment by virtualluke** [comment] 2017-09-06 11:44
I was able to build the whl files from your comment, thanks. Minor question, do I need to do a "pip uninstall pyarrow ray" before pip install the new ray whl? (and then reinstall pyarrow?)  I did a pip uninstall pyarrow and the ray whl still installed so pyarrow is not a dependency? Seems odd.  I am guessing I am missing something basic.

Thanks (and if email is better for anything further instead of commenting on a closed ticket, just let me know)

**Comment by robertnishihara** [comment] 2017-09-06 16:24
So, we definitely build pyarrow when building Ray. `ray/python/setup.py` calls `ray/build.sh`, which calls `ray/src/thirdparty/build_thirdparty.sh`, which builds pyarrow.

However, it does not "install" pyarrow, so it won't add pyarrow to your PYTHONPATH.

However, when we import ray, we manually add it to your PYTHONPATH, see below

https://github.com/ray-project/ray/blob/953878364ec5d19b7563f1597f5631558c4b916a/python/ray/__init__.py#L9-L11

The goal here was to avoid interferring with people's existing pyarrow installations. Although in the future, we'd like to not even compile pyarrow ourselves but rather to just get it from PyPI.

**Comment by virtualluke** [comment] 2017-09-06 17:25
The above example is "fixed" in the latest pull, but this bug is still in the latest ray pull from today as seen in the below:

```
import ray
import pickle

ray.init()

d = dict()

for i in range (1000000):
    d[i] = set(["test"+str(i),"test10"+str(i)])

%time s1 = pickle.dumps(d) # 333 ms

%time s2 = ray.put(d) # 4.57s

```

**Comment by robertnishihara** [comment] 2017-09-06 17:53
Can you create a separate issue for this one?

Our serialization code is written in C++ and is normally quite fast when mapping Python objects to the Arrow format. However, the C++ code only handles primitive types and lists/dicts/tuples. So when it encounters something it doesn't know how to serialize (e.g., a set), then it falls back to using cloudpickle (so it leaves C++ and goes back to Python).

There are a couple things that could be done.
- Add a special case for sets in the C++ code (this probably makes sense, but it won't work if you replace the sets in your example with some custom Python class).
- We need to generally optimize this code path more.

**Comment by virtualluke** [comment] 2017-09-06 17:56
will create a new issue, appreciate the help.
