### ISSUE TITLE
[Serve] Kubernetes operator reapplies Serve config too frequently

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#28652] opened 2022-09-20 21:08 UTC
### What happened + What you expected to happen

From [a Ray Slack thread](https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1663343998548389):

> [A user is] working with Kuberay and Ray 2.0.0 and try to deploy a RayService. It was not easy to get the cluster to start up, because it failed and restarted often. [The user] managed to get it running, but [they] saw that the “task:run_graph” got aborted a lot of times on startup.

The user posted logs from the Serve controller and the Kubernetes operator that imply the controller was receiving new Serve config deployment requests more than once per second. E.g.:

```console
INFO 2022-09-20 00:39:34,046 controller 160 controller.py:439 - Received new config deployment request. Cancelling previous request.
INFO 2022-09-20 00:39:34,288 controller 160 controller.py:439 - Received new config deployment request. Cancelling previous request.
INFO 2022-09-20 00:39:34,446 controller 160 controller.py:439 - Received new config deployment request. Cancelling previous request.
INFO 2022-09-20 00:39:34,572 controller 160 controller.py:439 - Received new config deployment request. Cancelling previous request.
INFO 2022-09-20 00:39:34,750 controller 160 controller.py:439 - Received new config deployment request. Cancelling previous request.
```

This likely doesn't give enough time for Serve to deploy the config completely before the request is canceled and re-issued, preventing the Serve application from being deployed. This in turn likely caused the cluster to be marked unhealthy and restarted.

Ideally, the Serve application should have enough time to be started without being interrupted.

### Versions / Dependencies

Ray 2.0.0 and Kuberay.

### Reproduction script

See [the Ray Slack thread](https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1663343998548389) for logs.

The user observed the issue on the [FruitStand example](https://docs.ray.io/en/releases-2.0.0/serve/production-guide/config.html#fruit-config-yaml).

**Comment by brucez-anyscale** [comment] 2022-12-08 04:27
Thanks for the update. I think we know the solution. And just need to make it merged.
We need to let controller ignore state update triggered reconcile. Using
```
builder.WithPredicates(predicate.GenerationChangedPredicate{})
```

cc @sihanwang41

**Comment by brucez-anyscale** [comment] 2022-12-08 04:28
also cc @wilsonwang371 @Jeffwan

**Comment by wilsonwang371** [comment] 2022-12-08 04:36
> also cc @wilsonwang371 @Jeffwan 

Do we need to make the change in kuberay controller code?

**Comment by brucez-anyscale** [comment] 2022-12-08 05:10
> > also cc @wilsonwang371 @Jeffwan
> 
> Do we need to make the change in kuberay controller code?

It should be a code change for `SetupWithManager`

**Comment by sihanwang41** [comment] 2022-12-08 06:39
Hi @Martin4R, Thank you for trying it out!  I will have a test and verify the fix. If working, I will merge it.

**Comment by pandemosth** [comment] 2023-01-16 23:04
I'm seeing the same issue. Ray 2.2.0 and both Kuberay 0.4.0 and nightly. The above merge suggests this should have been fixed in 0.4.0 though.



I can see the same `Received new config deployment request. Cancelling previous request.` in Serve Controller log, and the kuberay-operator repeating the serve deployment every 2s until the cluster is restarted.

Excerpt from kuberay-operator logs:


```
2023-01-16T21:54:16.664Z	INFO	controllers.RayService	Reconciling the cluster component.	{"ServiceName": "default/dev"}
2023-01-16T21:54:16.666Z	DEBUG	controllers.RayService	fetchDashboardAgentURL 	{"dashboard agent service found": "dev-raycluster-prjd5-dashboard-svc"}
2023-01-16T21:54:16.666Z	DEBUG	controllers.RayService	fetchDashboardAgentURL 	{"dashboardURL": "dev-raycluster-prjd5-dashboard-svc.default.svc.cluster.local:52365"}
2023-01-16T21:54:16.666Z	DEBUG	controllers.RayService	shouldUpdate	{"shouldUpdateServe": true, "reason": "Nothing has been cached for cluster dev-raycluster-prjd5 with key default/dev/dev-raycluster-prjd5"}
2023-01-16T21:54:16.666Z	DEBUG	controllers.RayService	updateServeDeployment	{"config": ...}
2023-01-16T21:54:16.666Z	DEBUG	controllers.RayService	updateServeDeployment	{"json config": ...}
2023-01-16T21:54:17.560Z	DEBUG	controllers.RayService	updateServeDeployment	{"message": "Cached Serve config for Ray cluster dev-raycluster-prjd5 with key default/dev/dev-raycluster-prjd5"}
2023-01-16T21:54:17.560Z	DEBUG	events	Normal	{"object": {"kind":"RayService","namespace":"default","name":"dev","uid":"88554a22-bba3-45d3-99db-a318527cc7c4","apiVersion":"ray.io/v1alpha1","resourceVersion":"125680128"}, "reason": "SubmittedServeDeployment", "message": "Controller sent API request to update Serve deployments on cluster dev-raycluster-prjd5"}
2023-01-16T21:54:17.565Z	DEBUG	controllers.RayService	getAndCheckServeStatus	{"statusMap": {}, "serveStatuses": {"app_status":{"status":"DEPLOYING","lastUpdateTime":"2023-01-16T21:54:17Z","healthLastUpdateTime":"2023-01-16T21:54:17Z"}}}
2023-01-16T21:54:17.565Z	INFO	controllers.RayService	Check serve health	{"ServiceName": "default/dev", "isHealthy": true, "isReady": false, "isActive": false}
2023-01-16T21:54:17.591Z	INFO	controllers.RayService	Mark cluster as waiting for Serve deployments	{"ServiceName": "default/dev", "rayCluster": {"apiVersion": "ray.io/v1alpha1", "kind": "RayCluster", "namespace": "default", "name": "dev-raycluster-prjd5"}}
2023-01-16T21:54:17.591Z	INFO	controllers.RayService	Cluster is healthy but not ready: checking again in 2s	{"ServiceName": "default/dev"}
2023-01-16T21:54:17.592Z	DEBUG	events	Normal	{"object": {"kind":"RayService","namespace":"default","name":"dev","uid":"88554a22-bba3-45d3-99db-a318527cc7c4","apiVersion":"ray.io/v1alpha1","resourceVersion":"125680157"}, "reason": "ServiceNotReady", "message": "The service is not ready yet. Controller will perform a round of actions in 2s."}
2023-01-16T21:54:19.592Z	INFO	controllers.RayService	Reconciling the cluster component.	{"ServiceName": "default/dev"}
2023-01-16T21:54:19.595Z	DEBUG	controllers.RayService	fetchDashboardAgentURL 	{"dashboard agent service found": "dev-raycluster-prjd5-dashboard-svc"}
2023-01-16T21:54:19.595Z	DEBUG	controllers.RayService	fetchDashboardAgentURL 	{"dashboardURL": "dev-raycluster-prjd5-dashboard-svc.default.svc.cluster.local:52365"}
2023-01-16T21:54:19.595Z	DEBUG	controllers.RayService	shouldUpdate	{"shouldUpdateServe": true, "reason": "No Serve deployments have started deploying for cluster dev-raycluster-prjd5 with key default/dev/dev-raycluster-prjd5", "cachedServeConfig": ...}
2023-01-16T21:54:19.595Z	DEBUG	controllers.RayService	updateServeDeployment	{"config": ...}
2023-01-16T21:54:19.596Z	DEBUG	controllers.RayService	updateServeDeployment	{"json config": ...}
2023-01-16T21:54:19.607Z	DEBUG	controllers.RayService	updateServeDeployment	{"message": "Cached Serve config for Ray cluster dev-raycluster-prjd5 with key default/dev/dev-raycluster-prjd5"}
2023-01-16T21:54:19.608Z	DEBUG	events	Normal	{"object": {"kind":"RayService","namespace":"default","name":"dev","uid":"88554a22-bba3-45d3-99db-a318527cc7c4","apiVersion":"ray.io/v1alpha1","resourceVersion":"125680157"}, "reason": "SubmittedServeDeployment", "message": "Controller sent API request to update Serve deployments on cluster dev-raycluster-prjd5"}
2023-01-16T21:54:19.614Z	DEBUG	controllers.RayService	getAndCheckServeStatus	{"statusMap": {}, "serveStatuses": {"app_status":{"status":"DEPLOYING","lastUpdateTime":"2023-01-16T21:54:19Z","healthLastUpdateTime":"2023-01-16T21:54:17Z"}}}
2023-01-16T21:54:19.614Z	INFO	controllers.RayService	Check serve health	{"ServiceName": "default/dev", "isHealthy": true, "isReady": false, "isActive": false}
2023-01-16T21:54:19.655Z	INFO	controllers.RayService	Mark cluster as waiting for Serve deployments	{"ServiceName": "default/dev", "rayCluster": {"apiVersion": "ray.io/v1alpha1", "kind": "RayCluster", "namespace": "default", "name": "dev-raycluster-prjd5"}}
2023-01-16T21:54:19.655Z	INFO	controllers.RayService	Cluster is healthy but not ready: checking again in 2s	{"ServiceName": "default/dev"}
2023-01-16T21:54:19.655Z	DEBUG	events	Normal	{"object": {"kind":"RayService","namespace":"default","name":"dev","uid":"88554a22-bba3-45d3-99db-a318527cc7c4","apiVersion":"ray.io/v1alpha1","resourceVersion":"125680181"}, "reason": "ServiceNotReady", "message": "The service is not ready yet. Controller will perform a round of actions in 2s."}
```

This line looks suspicious since the logs show a serve deployment had started 2s earlier:

`2023-01-16T21:54:19.595Z	DEBUG	controllers.RayService	shouldUpdate	{"shouldUpdateServe": true, "reason": "No Serve deployments have started deploying for cluster dev-raycluster-prjd5 with key default/dev/dev-raycluster-prjd5", "cachedServeConfig": ...}`

**Comment by shrekris-anyscale** [comment] 2023-01-17 21:30
Hi @pandemosth, thanks for following up with the logs. It looks like this is still an issue, so we'll take a closer look.

**Comment by Martin4R** [comment] 2023-01-18 13:36
If this hinders the cluster from startup, the extremely dirty temporary workaround is to compile the Kuberay operator from source with the following change to rayservice_controller.go:
<img width="1230" alt="kuberay_operator_temporary_quickfix" src="https://user-images.githubusercontent.com/112665668/213184362-890c571d-9c3c-4d03-8749-ba6cb63cffaa.png">

```
                currentTime := time.Now().UTC().Unix()
		paused := true
		if currentTime%5 == 0 {
			paused = false
		}
		shouldUpdate = !paused
```

This makes the gaps between serve deployment requests 5 seconds long, which in my case is enough for the actors to report their status correctly.

**Comment by shrekris-anyscale** [comment] 2023-01-18 17:59
Thanks for posting the workaround @Martin4R! cc'ing @spillai to the issue.

**Comment by uthark** [comment] 2023-01-25 21:45
I confirm the issue. Can't deploy example app because of this.

**Comment by bewestphal** [comment] 2023-03-09 19:53
Thanks for the share @Martin4R. I've ported this workaround to my fork and has mitigated the issue.
https://github.com/bewestphal/kuberay/tree/bewestphal/service-controller-update-speed-ten

This feels like it needs a proper mechanism to wait though. Seeing this issue on v0.4.0.

Anecdotally I wanna say this happens when my app is larger, in terms of overall app bundle size.

**Comment by pascalwhoop** [comment] 2023-03-10 10:26
we're trying to host LLMs from alpa.ai via ray on a k8s cluster and are also facing this issue. One workaround for us is to deploy the cluster and a separate pod that connects to the cluster for a deployment separately but that is of course not the intended behavior.

**Comment by sihanwang41** [comment] 2023-04-27 16:23
> The issue is still there with Kuberay 0.5.0 and Ray 2.4.0. The serve deployment request is still applied at least every 2 seconds. The Actors never manage to startup and at some point the whole cluster gets restarted.
> 
> Logs from Serve Controller:
> 
> ```
> INFO 2023-04-27 06:04:01,931 controller 272 controller.py:582 - Starting deploy_serve_application task for application .
> INFO 2023-04-27 06:04:01,933 controller 272 application_state.py:345 - Received new config deployment for  request. Cancelling previous request.
> INFO 2023-04-27 06:04:04,169 controller 272 controller.py:582 - Starting deploy_serve_application task for application .
> INFO 2023-04-27 06:04:04,171 controller 272 application_state.py:345 - Received new config deployment for  request. Cancelling previous request.
> INFO 2023-04-27 06:04:06,223 controller 272 controller.py:582 - Starting deploy_serve_application task for application .
> INFO 2023-04-27 06:04:06,225 controller 272 application_state.py:345 - Received new config deployment for  request. Cancelling previous request.
> INFO 2023-04-27 06:04:07,271 controller 272 controller.py:582 - Starting deploy_serve_application task for application .
> INFO 2023-04-27 06:04:07,272 controller 272 application_state.py:345 - Received new config deployment for  request. Cancelling previous request.
> INFO 2023-04-27 06:04:08,384 controller 272 controller.py:582 - Starting deploy_serve_application task for application .
> INFO 2023-04-27 06:04:08,386 controller 272 application_state.py:345 - Received new config deployment for  request. Cancelling previous request.
> INFO 2023-04-27 06:04:10,527 controller 272 controller.py:582 - Starting deploy_serve_application task for application .
> INFO 2023-04-27 06:04:10,528 controller 272 application_state.py:345 - Received new config deployment for  request. Cancelling previous request.
> INFO 2023-04-27 06:04:12,259 controller 272 controller.py:582 - Starting deploy_serve_application task for application .
> INFO 2023-04-27 06:04:12,260 controller 272 application_state.py:345 - Received new config deployment for  request. Cancelling previous request.
> INFO 2023-04-27 06:04:12,728 controller 272 controller.py:582 - Starting deploy_serve_application task for application .
> INFO 2023-04-27 06:04:12,729 controller 272 application_state.py:345 - Received new config deployment for  request. Cancelling previous request.
> INFO 2023-04-27 06:04:14,831 controller 272 controller.py:582 - Starting deploy_serve_application task for application .
> INFO 2023-04-27 06:04:14,832 controller 272 application_state.py:345 - Received new config deployment for  request. Cancelling previous request.
> INFO 2023-04-27 06:04:16,981 controller 272 controller.py:582 - Starting deploy_serve_application task for application .
> INFO 2023-04-27 06:04:16,982 controller 272 application_state.py:345 - Received new config deployment for  request. Cancelling previous request.
> INFO 2023-04-27 06:04:17,372 controller 272 controller.py:582 - Starting deploy_serve_application task for application .
> INFO 2023-04-27 06:04:17,373 controller 272 application_state.py:345 - Received new config deployment for  request. Cancelling previous request.
> INFO 2023-04-27 06:04:19,328 controller 272 controller.py:582 - Starting deploy_serve_application task for application .
> INFO 2023-04-27 06:04:19,330 controller 272 application_state.py:345 - Received new config deployment for  request. Cancelling previous request.
> INFO 2023-04-27 06:04:21,444 controller 272 controller.py:582 - Starting deploy_serve_application task for application .
> INFO 2023-04-27 06:04:21,445 controller 272 application_state.py:345 - Received new config deployment for  request. Cancelling previous request.
> INFO 2023-04-27 06:04:22,684 controller 272 controller.py:582 - Starting deploy_serve_application task for application .
> INFO 2023-04-27 06:04:22,686 controller 272 application_state.py:345 - Received new config deployment for  request. Cancelling previous request.
> INFO 2023-04-27 06:04:23,672 controller 272 controller.py:582 - Starting deploy_serve_application task for application .
> INFO 2023-04-27 06:04:23,673 controller 272 application_state.py:345 - Received new config deployment for  request. Cancelling previous request.
> ```
> 
> Tried then to change the rayservice_controller.go to contain "ServiceDefaultRequeueDuration = 6 * time.Second" but this did not help. Had to reapply the "currentTime"-workaround from above to make it work.

Hi @Martin4R , thank you for trying it out. Unfortunately my change is not in 0.5.0, can you use nightly wheel to verify?

**Comment by Martin4R** [comment] 2023-04-27 16:47
Hi @sihanwang41,
I tried now with nightly docker-image of Kuberay-operator and it works fine.
Thanks! :-)

**Comment by Martin4R** [comment] 2023-05-09 22:52
Hi @sihanwang41,
yesterday and today we saw a strange behavior on two of the Kuberay-clusters we have, which is maybe related to the fix in the Kuberay operator you mentioned above. We were running the exact same nightly Kuberay-operator version which I used in my comment above.

The Kuberay clusters started up and the dashboard was available, but they did not start up any actors, not even the ServeController actor and the HTTPProxy actors which usually appear. For me it seems that the freshly started clusters never received the serve deployment request from the operator.
One cluster did not get well even after redeployments, but suddenly it worked again, and nobody knows why. 
The other cluster showed the same "actorless" startup, then got automatically restarted after the serviceUnhealthySecondThreshold/deploymentUnhealthySecondThreshold (which we set to 600 seconds) and got back to normal after this restart, without us changing anything on it's deployment or config.

So far we never saw a startup behavior like this before in the last 7 months we used Kuberay. So it must be something which came in recently.

I saw that the bugfix in the Kuberay operator was, to remove the logic which repeatedly reapplies the serve deployment config. My guess would be, that there is some kind of race-condition when a cluster freshly starts up. In the best case it receives the first serve deployment request from the operator because the cluster is already available. In the worst case the cluster is not available yet, misses the first serve deployment request and then stays in this state without any actors because the serve deployment request is now never resent.

Can you recheck if the bugfix can lead to a behavior like this?

**Comment by sihanwang41** [comment] 2023-05-10 22:53
Hi @Martin4R , 
If the request is not being received, operator should receive error and trigger another deploy request. We checked the dashboard health before sending requests.
Are you able to collect dashboard log and serve controller log?  So that i can help to understand the scenario better.

**Comment by sihanwang41** [comment] 2023-05-31 18:38
Hi @Martin4R , Look like that is different issue, please create a different ticket for the issue you have. Closing this ticket now.
Thanks!

**Closed by sihanwang41** 2023-05-31 18:38 UTC
Labels: bug, P1, serve
