### ISSUE TITLE
[dashboard] Dashboard Test is failing due to tensorboardX 's protobuf dependency issue.

### ISSUE THREAD

**Issue by aslonnie** [ray-project/ray#36658] opened 2023-06-21 19:32 UTC
### What happened + What you expected to happen

https://buildkite.com/ray-project/oss-ci-build-branch/builds/4563#0188de6c-10fd-4fbf-b52f-999140220081

or

https://buildkite.com/ray-project/oss-ci-build-branch/builds/4568#0188df13-0a86-44d2-81a1-86469747982b

Expects test to pass

### Versions / Dependencies

current master

### Reproduction script

open a blank PR that touches dashboard with a noop change, and one should be able to see the test failure.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by aslonnie** [comment] 2023-06-21 19:33
https://buildkite.com/ray-project/oss-ci-build-branch/builds/4568#0188df13-0a86-44d2-81a1-86469747982b/3584-3820

The test is pinning `tensorboardX` at version `2.4.1`, which has an old version of protobuf generated python file that is not compatible with the protobuf that the test is using.

**Comment by aslonnie** [comment] 2023-06-21 19:35
I tried upgraded `tensorboardX` to `2.6.1`, which uses `protobuf>=4`, but then will run into protobuf dependency version conflict with other pinned packages.

**Comment by aslonnie** [comment] 2023-06-21 19:35
cc @krfricke @can-anyscale @pcmoritz

**Comment by matthewdeng** [comment] 2023-06-21 19:50
I took a quick look at some of the Tune jobs (e.g. [this](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4563#0188de74-3da5-44d8-bb64-bd328c62bf2c)) and they are using protobuf 3.19.6. I think some ML dependencies should have this upper bound restriction, not sure why the Dashboard test doesn't though. @krfricke can you take a look and see where the right place to set this is?

**Comment by can-anyscale** [comment] 2023-06-21 20:32
Unrelated to this test failure, but in general, I think it worths an effort to regularly upgrade our library dependencies, and make sure all the versions won't be too stale (e.g. the pinned version is 6 month stale at the maximum). tensorboardX 3.9.x and protobuf 3.19.x all seems to be more than 1 year old, so it's just a matter of time when the are incompatible with other things that get deprecated.

**Comment by aslonnie** [comment] 2023-06-21 20:50
and pin everything in tests..

**Comment by hora-anyscale** [comment] 2023-06-21 21:44
This was marked as dupe of https://github.com/ray-project/ray/issues/36649 which was a P0, so making this P0

**Comment by matthewdeng** [comment] 2023-06-21 23:27
Yep both of these suggestions are in line with @krfricke's work towards unifying dependencies across Docker/CI.

**Closed** 2023-06-22 07:02 UTC
Labels: bug, P0, triage
