### ISSUE TITLE
Cannot import tensorflow in docker image rayproject/ray-ml:2.2.0-py310-gpu

### ISSUE THREAD

**Issue by wullli** [ray-project/ray#31855] opened 2023-01-23 13:01 UTC
### Error is thrown when trying to import tensorflow in ray-ml 2.2.0 docker images.

The ray-ml images seem to be broken on docker hub.

```
$ docker run -it rayproject/ray-ml:2.2.0-py310-gpu python3 -c "import tensorflow as tf"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ray/anaconda3/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/ray/anaconda3/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/home/ray/anaconda3/lib/python3.10/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "/home/ray/anaconda3/lib/python3.10/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/home/ray/anaconda3/lib/python3.10/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/home/ray/anaconda3/lib/python3.10/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/home/ray/anaconda3/lib/python3.10/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/home/ray/anaconda3/lib/python3.10/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/ray/anaconda3/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

Note that this also makes imports like the one below impossible. Since tensorflow is a requirement:
`docker run -it rayproject/ray-ml:2.2.0-py310-gpu python3 -c "from ray.rllib.algorithms.algorithm import Algorithm"
`
### Versions / Dependencies

Docker image: rayproject/ray-ml:2.2.0-py310-gpu

### Reproduction script

`$ docker run -it rayproject/ray-ml:2.2.0-py310-gpu python3 -c "import tensorflow as tf"`

### Issue Severity

High: It blocks me from completing my task.

**Comment by krfricke** [comment] 2023-01-28 00:40
Closing as duplicate of #31309 - and it also has been resolved just now. See #31309 for details

**Closed by krfricke** 2023-01-28 00:40 UTC
Labels: bug, P1
